### ISSUE TITLE
Single Test Failure possibly due Locale.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#1006]
This the second time I've encountered this single test failure.
```xml
      <test name="Microsoft.CodeAnalysis.UnitTests.Diagnostics.DiagnosticLocalizationTests.TestDiagnosticLocalization" type="Microsoft.CodeAnalysis.UnitTests.Diagnostics.DiagnosticLocalizationTests" method="TestDiagnosticLocalization" time="0.031" result="Fail">
        <failure exception-type="System.Collections.Generic.KeyNotFoundException">
          <message><![CDATA[System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.]]></message>
          <stack-trace><![CDATA[   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.UnitTests.Diagnostics.DiagnosticLocalizationTests.CustomResourceManager.GetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents) in C:\Users\Adam\Documents\GitHub\roslyn\Src\Compilers\Core\CodeAnalysisTest\Diagnostics\DiagnosticLocalizationTests.cs:line 183
   at Microsoft.CodeAnalysis.UnitTests.Diagnostics.DiagnosticLocalizationTests.CustomResourceManager.GetString(String name, CultureInfo culture) in C:\Users\Adam\Documents\GitHub\roslyn\Src\Compilers\Core\CodeAnalysisTest\Diagnostics\DiagnosticLocalizationTests.cs:line 178
   at Microsoft.CodeAnalysis.LocalizableResourceString.ToString(IFormatProvider formatProvider) in C:\Users\Adam\Documents\GitHub\roslyn\Src\Compilers\Core\Portable\Diagnostic\LocalizableResourceString.cs:line 111
   at Microsoft.CodeAnalysis.LocalizableString.ToString() in C:\Users\Adam\Documents\GitHub\roslyn\Src\Compilers\Core\Portable\Diagnostic\LocalizableString.cs:line 32
   at Microsoft.CodeAnalysis.UnitTests.Diagnostics.DiagnosticLocalizationTests.TestDiagnosticLocalization() in C:\Users\Adam\Documents\GitHub\roslyn\Src\Compilers\Core\CodeAnalysisTest\Diagnostics\DiagnosticLocalizationTests.cs:line 67]]></stack-trace>
        </failure>
      </test>
```
if I build via jerkins no failures.

I think it was introduced somewhere between #958 (no failures) and #1001 (1 failure)

**Comment by mavasani** [comment]
I thought this could be due to https://github.com/dotnet/roslyn/commit/356854df558807fc5a9bc2e58cf759a0c9deb3d1 ( #985 ), but that was merged into dotnet/roslyn late yesterday night and your issue was filed before that. So something else seems to have caused this. I am unable to repro this failure locally either. Does this repro consistently on your machine? If so, could you collect a dump and share it?

**Comment by AdamSpeight2008** [comment]
My repo master has first initiated at the at 97b84b5279c4935c3b44595a004e81110ed43e9d
and no build or test issue occurred  For r#1001 to sync I had to Pull and the from on the test has had the one failure since.

My machine is in the Locale `(UTC) Dublin, Edinburgh, Lisbon, London` but the VS2015ctp6 is `English (USA)`
I'll clear out the bin folder and rebuild and test.

**Comment by mavasani** [comment]
Thanks, that information helps, let me try to setup a machine with your environment and try to get a repro.

**Comment by AdamSpeight2008** [comment]
I'm just doing the clean build and test which usually takes about 30mins. I'll add and update once it's complete.

**Comment by brettfo** [comment]
Haven't seen this repro so I'm marking it as verified.
