### ISSUE TITLE
CSharpInteractiveDirectives vsi test failed in standalone due to missing MIcrosoft.Imaging.Interop.14.0.DesignTime.dll

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#10108]
**Version Used**: 
ML 25124.01
**Steps to Reproduce**:
Run CSharpInterativeDirectives vsi test on a machine w/o building Roslyn. (Standalone context)

Failure occurs in Scenario 4 at the 'CreateAndLoadTempFileInRepl' step. 

**Expected Behavior**:
Test succeeds
**Actual Behavior**:
Test fails with the following exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 File name: 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
    at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
    at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
    at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
    at Tao.Engine.Serialization.SerializationUtility.IsPropertySerialized(PropertyInfo property)
    at Tao.Engine.Serialization.ComplexSchemaType.get_Properties()
    at Tao.Engine.Serialization.ComplexSchemaType.ParseExisting(Object& target, XObject xml)
    at Tao.Engine.Serialization.ObjectDeserializer.ReadObject(Object target, XElement element, Func`2 stringConverter)
    at Tao.Engine.TaoAction.Parse(TaoEngine engine, XElement element)
    at Tao.Engine.DebuggableActionExecutor.Initialize()
    at Tao.Engine.DefaultActionExecutor.Initialize()

**Comment by mattscheffer** [comment]
@davkean

**Comment by tannergooding** [comment]
@ManishJayaswal, I don't believe this is an urgency now bug (the milestone is also wrong as this is for the ML branch which is Dev15).

From a brief look, I would guess that there is a binding redirect issue (or another issue falling out from us building against Dev14 but targeting Dev15).

**Comment by ManishJayaswal** [comment]
@tannergooding we are losing test coverage because I don't believe the scenario is covered anywhere else. Since this is Dev15 I am ok removing urgency now label but we should fix this issue sonn.

**Comment by tannergooding** [comment]
@Manish, I have provided a fix to @mattscheffer.

@mattscheffer, could you please checkin the fix to the TFS server and rerun the failing standalone tests (all of them) and mark the bug as `verified` once the test is passing.
