### ISSUE TITLE
TargetInvocationException in System.Reflection.Metadata.ModuleDefinition.get_Name()

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#10208]
See Jenkins job [here](http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_dbg_unit32/238).

There was no dump file created but the console log reports this stack trace:

```
12:20:47 Errors Roslyn.Services.Editor.VisualBasic.UnitTests.dll: 
12:20:47 
12:20:47 Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
12:20:47    at System.Reflection.Metadata.ModuleDefinition.get_Name()
12:20:47    at Microsoft.CodeAnalysis.PEModule.get_Name() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 293
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol.get_Name() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PEModuleSymbol.cs:line 164
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbol.get_MetadataName() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\Symbol.cs:line 80
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.ModuleSymbolKey..ctor(IModuleSymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.ModuleSymbolKey.cs:line 22
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitModule(IModuleSymbol moduleSymbol) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 69
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol.Accept[TResult](SymbolVisitor`1 visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\ModuleSymbol.cs:line 377
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.NamespaceSymbolKey.DetermineContainerKey(INamespaceSymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamespaceSymbolKey.cs:line 46
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.NamespaceSymbolKey..ctor(INamespaceSymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamespaceSymbolKey.cs:line 29
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitNamespace(INamespaceSymbol namespaceSymbol) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 81
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TResult](SymbolVisitor`1 visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\NamespaceSymbol.cs:line 391
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.NamedTypeSymbolKey..ctor(INamedTypeSymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamedTypeSymbolKey.cs:line 25
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitNamedType(INamedTypeSymbol namedTypeSymbol) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 74
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\NamedTypeSymbol.cs:line 1366
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey..ctor(IMethodSymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.MethodSymbolKey.cs:line 37
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitMethod(IMethodSymbol methodSymbol) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 64
12:20:47    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Accept[TResult](SymbolVisitor`1 visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Compilers\CSharp\Portable\Symbols\MethodSymbol.cs:line 1214
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
12:20:47    at Microsoft.CodeAnalysis.SymbolKey.Create(ISymbol symbol, Compilation compilation, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 108
12:20:47    at Microsoft.CodeAnalysis.SymbolKeyExtensions.GetSymbolKey(ISymbol symbol) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKeyExtensions.cs:line 11
12:20:47    at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 149
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionWorkerAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken)
12:20:47    at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 98
12:20:47    at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.<GetContextAsync>d__8.MoveNext() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 91
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetContextAsync(Document document, Int32 position, Boolean restrictToDeclarations, CancellationToken cancellationToken)
12:20:47    at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignature(Document document, Int32 position, Action`2 errorHandler, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 61
12:20:47    at Microsoft.CodeAnalysis.Editor.UnitTests.ChangeSignature.ChangeSignatureTestState.ChangeSignature() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\EditorFeatures\Test\ChangeSignature\ChangeSignatureTestState.cs:line 71
12:20:47    at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ChangeSignature.ChangeSignatureTests.VB$StateMachine_75_TestReorderParameters_AcrossLanguages_InvokeFromReference.MoveNext() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\EditorFeatures\VisualBasicTest\ChangeSignature\ReorderParameters.MultiFile.vb:line 110
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ChangeSignature.ChangeSignatureTests.TestReorderParameters_AcrossLanguages_InvokeFromReference()
12:20:47    --- End of inner exception stack trace ---
12:20:47    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
12:20:47    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
12:20:47    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
12:20:47    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
12:20:47    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
12:20:47    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
12:20:47    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__0()
12:20:47    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
12:20:47    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
12:20:47    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
12:20:47    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
12:20:47    at Xunit.Sdk.TestInvoker`1.RunAsync()
12:20:47    at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator)
12:20:47    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
12:20:47    at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0()
12:20:47    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
12:20:47    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.TestRunner`1.RunAsync()
12:20:47    at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync()
12:20:47    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
12:20:47    at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
12:20:47    at Roslyn.Test.Utilities.WpfTestCase.<>n__0(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
12:20:47    at Roslyn.Test.Utilities.WpfTestCase.<>c__DisplayClass2_0.<<RunAsync>b__0>d.MoveNext() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\EditorFeatures\TestUtilities\Threading\WpfTestCase.cs:line 58
12:20:47    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
12:20:47    at Roslyn.Test.Utilities.WpfTestCase.<>c__DisplayClass2_0.<RunAsync>b__0()
12:20:47    at System.Threading.Tasks.Task`1.InnerInvoke()
12:20:47    at System.Threading.Tasks.Task.Execute()
12:20:47    at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
12:20:47    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
12:20:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
12:20:47    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
12:20:47    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
12:20:47    at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
12:20:47    at Roslyn.Test.Utilities.StaTaskScheduler.<.ctor>b__7_1() in d:\j\workspace\roslyn-intern---b036dc4b\Open\src\EditorFeatures\TestUtilities\Threading\StaTaskScheduler.cs:line 51
12:20:47    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
12:20:47    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
12:20:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
12:20:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
12:20:47    at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by gafter** [comment]
I am not aware of this having been reproduced. I suspect a cosmic ray. Please reopen if it recurs.
