### ISSUE TITLE
"Index was outside the bounds of the array" during VB emit

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#10211]
This crashed during random dogfooding:
```
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1& useSiteDiagnostics)
```

A dump is available internally at \\<internal-server>\public\jasonmal\Dumps\Roslyn\10211

**Comment by jaredpar** [comment]
I was able to hit this occasionally on my machine as well.  It hits more often when I have incorrectly restored NuGet packages which makes sense with the dumps being unable to resolve `System.Object`.

**Comment by jaredpar** [comment]
Copying repro instructions ofrom #10252 

Confirmed this on my machine which has a vanilla update 1 installation:

- nuget.exe locals all -clear
- nuget.exe restore src\Compilers\Core\Portable\CodeAnalysis.csproj -configFile c:\users\jaredpar\code\roslyn\NuGet.Config
- Sync to 6ac83f3
- Open Compilers.sln
- Wait

Eventually it will crash with the stack that @TyOverby provided.

**Comment by KirillOsenkov** [comment]
This is also the reason http://source.roslyn.io has stopped updating (last successful update was on March 31). Machine that updates http://source.roslyn.io has VBC.exe crashed with IndexOutOfRange every time it runs the job.

**Comment by TyOverby** [comment]
@KirillOsenkov I'm working on a fix to the compiler to keep this from happening again, but in the meantime, in order to get things back online, clear your nuget cache and do a full restore.

```
nuget.exe locals all -clear
.\restore.cmd
```

**Comment by jasonmalinowski** [comment]
@TyOverby: how is this related to NuGet store corruption?

**Comment by TyOverby** [comment]
@jasonmalinowski This crash occurs when we get a set of references that doesn't contain `Object`.  I'm not sure how this happens, but I'm investigating it while writing https://github.com/dotnet/roslyn/pull/10331

**Comment by KirillOsenkov** [comment]
@TyOverby `nuget.exe locals all -clear` fixed it, thanks! No longer seeing the crash and http://source.roslyn.io was updated successfully again.

I've been having network issues on that VM and so somehow my NuGet cache might have gotten corrupted. I remember seeing Error 400 Bad Request in Red coming from NuGet output. Unfortunately I don't have any more information other than that.
