### ISSUE TITLE
CSharpCompiler.PrintLogo throws on Ubuntu

### ISSUE THREAD

**Issue by ctaggart** [dotnet/roslyn#10397]
**Version Used**: 
latest dotnet cli on Ubuntu

**Steps to Reproduce**:
via docker, see https://github.com/dotnet/cli/issues/2221

**Expected Behavior**:
It doesn't throw.

**Actual Behavior**:
```
root@63dd78325fcc:/# echo $sdk
/usr/share/dotnet/sdk/1.0.0-beta-002266
root@63dd78325fcc:/# $sdk/corehost $sdk/csc.dll

Unhandled Exception: System.TypeInitializationException: The type initializer for 'FileVersionInfo' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.PortableShim.FileVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted
```

**Comment by ctaggart** [comment]
Note that `dotnet` runs just fine, printing its version without throwing an exception:
```
root@63dd78325fcc:/# $sdk/corehost $sdk/dotnet.dll
.NET Command Line Tools (1.0.0-beta-002266)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Executes tests in a test project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package
```

**Comment by jaredpar** [comment]
@agocke it looks like `FileVersionInfo` isn't getting deployed on Ubuntu.

**Comment by agocke** [comment]
@jaredpar I just downloaded the latest binaries for Ubuntu and I see it in the tarball.

I don't know how to download the indicated build, though.

**Comment by jaredpar** [comment]
Sorry this issue got lost.  I just tried this on recent builds and it appears to be working correctly.  Please let us know if you still see the issue.

**Comment by ctaggart** [comment]
It is broken with `1.0.0-preview2-sdk`. I haven't tried it with newer builds yet. I just updated steps to reproduce here: https://github.com/dotnet/cli/issues/2221#issuecomment-234676171
