### ISSUE TITLE
[Flaky test] BasicEditAndContinue.Multi project debugging where not all modules are loaded 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10416]
See http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi0/110/consoleFull#-202636883661aefe2b-268e-4e71-8c03-11b4c0acbfbc

```
Regression

BasicEditAndContinue.Multi project debugging where not all modules are loaded (from (empty))

Failing for the past 1 build (Since Failed#300 )
Took 2 min 2 sec.
add description
Stacktrace

MESSAGE:
Exception has been thrown by the target of an invocation.
+++++++++++++++++++
STACK TRACE:

> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) 
at Tao.Engine.Utilities.MethodCaller.CallMethod[T](T objectWithMethods, XElement xmlMethod) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 85 
at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, IEnumerable`1 xmlList) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 37 
at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, XElement xml) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 30 
at Tao.Engine.DebuggableActionExecutor.CallMethods(TaoEngine engine, TaoAction action) in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 183 
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 142

```

**Comment by jasonmalinowski** [comment]
This is a flaky test, please investigate.

**Comment by balajikris** [comment]
Note: I've also seen the C# EnC test fail the same way.

**Comment by tmat** [comment]
@jasonmalinowski I don't see Artifacts for the run: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi0/110. Am I missing something or are they not published?

**Comment by jasonmalinowski** [comment]
This is also failing with 

```
21:43:18 System.Exception: Debugger could not hit break mode, current mode is DesignMode
21:43:18    at Roslyn.VSHosting.Test.RoslynActions.DebugAction.StartDebugging(Boolean waitForBreakMode) in d:\j\workspace\windows_vsi_p08ba736a3\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\DebugAction.cs:line 193
```

in the lab. An example: https://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/164/console

**Comment by jasonmalinowski** [comment]
Since this is still failing regularly, moving back to Urgency-Now.

**Comment by tmat** [comment]
@jasonmalinowski Any more recent failures? The above still doesn't have artifacts. The CI artifacts archiving was fixed but it seems the above job run before the fix took effect.

**Comment by jasonmalinowski** [comment]
@tmat: there might be. it seems there's a blaming issue going on here where this goes sideways, but then the text tao test fails. Generate type dialog tests were failing, and I filed this seeing what looked to be the underlying issue.

**Comment by tmat** [comment]
@jasonmalinowski So you claim this fails regularly. Can you point me to a failure in past week or two? I need to see a failure that has artifacts archived, otherwise there is nothing actionable to go with. If there is not such a failed build in past two weeks then I'm gonna remove "Urgency-soon" tag since this is clearly not blocking anyone.

**Comment by jasonmalinowski** [comment]
@tmat It looks like they've expired since. I'll close this, and will reactivate when we see it again.

**Comment by tmat** [comment]
@jasonmalinowski Thanks.
