### ISSUE TITLE
Test partitioning can eliminate EventListener race workaround

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#10680]
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit64/1112/artifact/Binaries/Release/xUnitResults/Roslyn.VisualStudio.Services.UnitTests.dll.0.out.log

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)

http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1111/artifact/Binaries/Debug/xUnitResults/Roslyn.Services.Editor.UnitTests2.dll.0.out.log

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.XunitTestAssemblyRunner.<RunTestCollectionsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestAssemblyRunner`1.<RunAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.XunitTestFrameworkExecutor.<RunTestCases>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by balajikris** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_dbg_unit64/1432/ seems to have ran into this yesterday. interested in taking a look at this instance to see if something was missed?

~~~
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
~~~

**Comment by jaredpar** [comment]
@balajikris is the DLL in question written in C# or VB?

**Comment by balajikris** [comment]
It's VB, Roslyn.VisualStudio.Services.UnitTests.dll

**Comment by jaredpar** [comment]
See #10779.  Need the same fix for VB that I made for C#.

**Comment by balajikris** [comment]
Ah, didn't know that. Thanks @jaredpar

**Comment by balajikris** [comment]
Looks like a C# binary ran into this yesterday, is this unexpected?

Run: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit64/1446/
Artifact: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit64/1446/artifact/Open/Binaries/Release/xUnitResults/Roslyn.Compilers.CSharp.EnC.UnitTests.dll.out.log

~~~
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Compilers.CSharp.EnC.UnitTests
  Discovered:  Roslyn.Compilers.CSharp.EnC.UnitTests
  Starting:    Roslyn.Compilers.CSharp.EnC.UnitTests
    Microsoft.CodeAnalysis.CSharp.UnitTests.EditAndContinueApplyTests.RunAll
    Microsoft.CodeAnalysis.CSharp.UnitTests.EditAndContinueApplyTests.RunAll [SKIP]
      Target platform is not x86
  Finished:    Roslyn.Compilers.CSharp.EnC.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
~~~

**Comment by jasonmalinowski** [comment]
It looks like this impacted [this build](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/2098). I'm not sure why this would have reappeared, but the issue clearly isn't closed.

I've archived the artifacts at `\\mlangfs1\public\jasonmal\Dumps\Roslyn\10680`.

**Comment by jaredpar** [comment]
Looks like two issues:

1. The EventListenerGuard isn't included in this test project hence it's not getting the protection.
2. This is a VB project hence we need to make a VB copy of the guard.
