### ISSUE TITLE
Nuget restore on Linux failed with System.IO.IOException: Too many open files

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10709]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6287/console

```
16:36:37 Restore CrossPlatform.sln
16:37:07 
16:37:07 Unhandled Exception: System.IO.IOException: Too many open files
16:37:07    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
16:37:07    at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
16:37:07    at System.ConsolePal.OpenStandardOutput()
16:37:07    at System.Console.<>c.<get_Out>b__25_0()
16:37:07    at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
16:37:07    at System.Console.WriteLine(String value)
16:37:07    at Microsoft.DotNet.Tools.Restore.RestoreCommand.<>c__DisplayClass1_0.<Run>b__3()
16:37:07    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
16:37:07    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
16:37:07    at Microsoft.DotNet.Cli.Program.Main(String[] args)
16:37:07 Restore failed
```

**Comment by jmarolf** [comment]
@agocke where is the nuget bug for too many file handles?

**Comment by agocke** [comment]
@jmarolf https://github.com/NuGet/Home/issues/2163

**Comment by jasonmalinowski** [comment]
The NuGet side fixed this awhile ago, and we're on it now.
