### ISSUE TITLE
VS IntegrationTests: VerifyInstanceCount action sometimes fails with ArgumentException

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#10726]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/616/console

```
	Executing action [4/20/2016 5:09:16 PM] VerifyInstanceCount
10:20:06 --------------------------------
10:20:06 System.ArgumentException: Illegal characters in path.
10:20:06 
10:20:06 Server stack trace: 
10:20:06    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
10:20:06    at System.IO.Path.GetFileName(String path)
10:20:06    at System.IO.Path.GetFileNameWithoutExtension(String path)
10:20:06    at Microsoft.Diagnostics.Runtime.DataTargetImpl.get_ClrVersions() in c:\b\4745\1867\src\CLRMemoryDiagnostic\Public\src\datatargetimpl.cs:line 93
10:20:06    at Roslyn.Hosting.Test.VerifyInstanceCountAction.Execute() in d:\j\workspace\dotnet_roslyn---664bbf48\Closed\Hosting\RoslynTaoActions\Actions\SharedActions\VerifyInstanceCountAction.cs:line 61
10:20:06    at Roslyn.Hosting.Test.SerializedData.ExecuteShim() in d:\j\workspace\dotnet_roslyn---664bbf48\Closed\Hosting\RoslynTaoActions\Actions\SharedActions\SerializedData.cs:line 25
10:20:06    at Roslyn.VSHosting.Test.InProcessAPI.InvokeInVS(Action action) in d:\j\workspace\dotnet_roslyn---664bbf48\Closed\Hosting\Test\Actions\VisualStudio\Utilities\InProcessAPI.cs:line 51
10:20:06    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
10:20:06    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
10:20:06 
10:20:06 Exception rethrown at [0]: 
10:20:06    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
10:20:06    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
10:20:06    at Roslyn.VSHosting.Test.InProcessAPI.InvokeInVS(Action action)
10:20:06    at Roslyn.Hosting.Test.SharedAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---664bbf48\Closed\Hosting\RoslynTaoActions\Actions\SharedActions\SharedAction.cs:line 14
10:20:06    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
10:20:06    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
10:20:06 ================================
```

**Comment by brettfo** [comment]
The Jenkins archive is gone and looking at the stack this is external to us anyways (ClrMD).

Closing it since it's not directly actionable and I see little value in wrapping the offending line in a `try/catch`; we don't have direct access to the path that contains the invalid character so we can't directly examine it and couldn't do anything even if we could see it.
