### ISSUE TITLE
AV reading ModuleDefinition during test run

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10775]
Usually something like this indicates misuse of the metadata reader (ie we've disposed it before we've finished using it).

PR: [#10773](https://github.com/dotnet/roslyn/pull/10773) *Update GUIDs of dependencies projects in tree.* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6436/
```
16:19:46   Errors Roslyn.Services.Editor.UnitTests2.dll: 
16:19:46   
16:19:46   Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
16:19:46      at System.Reflection.Metadata.ModuleDefinition.get_Name()
16:19:46      at Microsoft.CodeAnalysis.PEModule.get_Name() in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 293
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol.get_Name() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PEModuleSymbol.cs:line 164
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbol.get_MetadataName() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Symbol.cs:line 80
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.ModuleSymbolKey..ctor(IModuleSymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.ModuleSymbolKey.cs:line 22
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitModule(IModuleSymbol moduleSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 69
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbols.ModuleSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\ModuleSymbol.cs:line 377
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.NamespaceSymbolKey.DetermineContainerKey(INamespaceSymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamespaceSymbolKey.cs:line 46
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.NamespaceSymbolKey..ctor(INamespaceSymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamespaceSymbolKey.cs:line 29
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitNamespace(INamespaceSymbol namespaceSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 81
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\NamespaceSymbol.cs:line 421
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.NamedTypeSymbolKey..ctor(INamedTypeSymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.NamedTypeSymbolKey.cs:line 25
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitNamedType(INamedTypeSymbol namedTypeSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 74
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\NamedTypeSymbol.cs:line 1371
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey..ctor(IMethodSymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.MethodSymbolKey.cs:line 37
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitMethod(IMethodSymbol methodSymbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.Visitor.cs:line 64
16:19:46      at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Accept[TResult](SymbolVisitor`1 visitor) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\MethodSymbol.cs:line 1201
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 121
16:19:46      at Microsoft.CodeAnalysis.SymbolKey.Create(ISymbol symbol, Compilation compilation, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 108
16:19:46      at Microsoft.CodeAnalysis.SymbolKeyExtensions.GetSymbolKey(ISymbol symbol) in q:\roslyn\src\Workspaces\Core\Portable\SymbolId\SymbolKeyExtensions.cs:line 11
16:19:46      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext() in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 149
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionWorkerAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken)
16:19:46      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSourceDefinitionAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken) in q:\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder.cs:line 98
16:19:46      at Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.GoToDefinitionHelpers.TryGoToDefinition(ISymbol symbol, Project project, IEnumerable`1 presenters, CancellationToken cancellationToken, Boolean thirdPartyNavigationAllowed, Boolean throwOnHiddenDefinition) in q:\roslyn\src\EditorFeatures\Core\Implementation\GoToDefinition\GoToDefinitionHelpers.cs:line 46
16:19:46      at Microsoft.CodeAnalysis.Editor.Implementation.GoToDefinition.AbstractGoToDefinitionService.TryGoToDefinition(Document document, Int32 position, CancellationToken cancellationToken) in q:\roslyn\src\EditorFeatures\Core\Implementation\GoToDefinition\AbstractGoToDefinitionService.cs:line 55
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests._Closure$__._Lambda$__1-0(Document document, Int32 cursorPosition, IEnumerable`1 presenters) in q:\roslyn\src\EditorFeatures\Test2\GoToDefinition\GoToDefinitionTests.vb:line 19
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.Utilities.GoToHelpers.GoToTestHelpers.VB$StateMachine_3_TestAsync.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\Utilities\GoToHelpers\GoToTestHelpers.vb:line 45
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.Utilities.GoToHelpers.GoToTestHelpers.TestAsync(XElement workspaceDefinition, Boolean expectedResult, Func`4 executeOnDocument)
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.TestAsync(XElement workspaceDefinition, Boolean expectedResult) in q:\roslyn\src\EditorFeatures\Test2\GoToDefinition\GoToDefinitionTests.vb:line 13
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.VB$StateMachine_70_TestCrossLanguageNavigationToVBModuleMember.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\GoToDefinition\GoToDefinitionTests.vb:line 1657
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.TestCrossLanguageNavigationToVBModuleMember()
16:19:46      --- End of inner exception stack trace ---
16:19:46      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
16:19:46      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
16:19:46      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
16:19:46      at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
16:19:46      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
16:19:46      at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
16:19:46      at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
16:19:46      at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
16:19:46      at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
16:19:46      at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
16:19:46      at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
16:19:46      at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
16:19:46      at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.TestRunner`1.RunAsync()
16:19:46      at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Xunit.Sdk.TestCaseRunner`1.RunAsync()
16:19:46      at Roslyn.Test.Utilities.WpfTestCase.<>n__0(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
16:19:46      at Roslyn.Test.Utilities.WpfTestCase.<>c__DisplayClass2_0.<<RunAsync>b__0>d.MoveNext() in q:\roslyn\src\EditorFeatures\TestUtilities\Threading\WpfTestCase.cs:line 58
16:19:46      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
16:19:46      at Roslyn.Test.Utilities.WpfTestCase.<>c__DisplayClass2_0.<RunAsync>b__0()
16:19:46      at System.Threading.Tasks.Task`1.InnerInvoke()
16:19:46      at System.Threading.Tasks.Task.Execute()
16:19:46      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:19:46      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:19:46      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
16:19:46      at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
16:19:46      at Roslyn.Test.Utilities.StaTaskScheduler.<.ctor>b__7_1() in q:\roslyn\src\EditorFeatures\TestUtilities\Threading\StaTaskScheduler.cs:line 51
16:19:46      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:19:46      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:19:46      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:19:46      at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by davkean** [comment]
tag @tmat, look familar?

**Comment by jaredpar** [comment]
My fault for letting this one go.  At this point though the bug isn't actionable and there haven't been any recent occurrences.  Closing.

**Comment by tmat** [comment]
Seems like the PE symbol is access after metadata have been disposed
