### ISSUE TITLE
Restore failing on Linux with "System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning."

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#10838]
Restore failed on Linux: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6490/

```
09:30:18 Restoring toolset packages
09:30:20 log  : Restoring packages for /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/build/ToolsetPackages/project.json...
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:20 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:24 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:24 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:25 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 error: Failed to retrieve information from remote source '/home/dotnet-bot/.nuget/packages/'.
09:30:26 log  : Installing Microsoft.DiaSymReader.Native 1.3.3.
09:30:26 log  : Installing xunit.runner.console 2.1.0-beta4-build3109.
09:30:26 log  : Installing Microsoft.NETCore.Platforms 1.0.0.
09:30:26 log  : Installing FakeSign 0.9.2.
09:30:26 log  : Installing Microsoft.Net.RoslynDiagnostics 1.1.1-beta1-20150818-01.
09:30:26 log  : Installing Microsoft.Net.Compilers 1.2.0-rc.
09:30:26 log  : Installing Roslyn.Build.Util 0.9.4-portable.
09:30:26 log  : Installing Microsoft.Build.Mono.Debug 14.1.0.
09:30:27 log  : Installing Microsoft.CodeAnalysis.Test.Resources.Proprietary 1.2.0-beta1-20160105-04.
09:30:27 log  : Installing xunit 2.1.0-beta4-build3109.
09:30:27 log  : Installing Microsoft.Build.Framework 0.1.0-preview-00005.
09:30:27 log  : Installing Microsoft.Build.Utilities.Core 0.1.0-preview-00005.
09:30:27 log  : Installing System.Diagnostics.Debug 4.0.10.
09:30:27 log  : Installing System.Collections 4.0.10.
09:30:27 log  : Installing System.Linq 4.0.0.
09:30:27 log  : Installing System.Runtime 4.0.20.
09:30:27 log  : Installing System.IO.FileSystem 4.0.0.
09:30:27 log  : Installing Microsoft.Tpl.Dataflow 4.5.24.
09:30:27 log  : Installing xunit.assert 2.1.0-beta4-build3109.
09:30:27 log  : Installing xunit.core 2.1.0-beta4-build3109.
09:30:27 log  : Installing System.Text.Encoding 4.0.0.
09:30:27 log  : Installing System.Runtime.Handles 4.0.0.
09:30:27 log  : Installing System.IO.FileSystem.Primitives 4.0.0.
09:30:27 log  : Installing System.Threading.Tasks 4.0.0.
09:30:27 log  : Installing System.IO 4.0.0.
09:30:27 log  : Installing xunit.extensibility.core 2.1.0-beta4-build3109.
09:30:27 log  : Installing xunit.abstractions 2.0.0.
09:30:28 warn : Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005 
09:30:28 warn :  ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework  
09:30:28 warn :  ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
09:30:28 warn : Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00005 
09:30:28 warn :  ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework  
09:30:28 warn :  ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.4-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
09:30:28 log  : Writing lock file to disk. Path: /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/build/ToolsetPackages/project.lock.json
09:30:28 log  : /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/build/ToolsetPackages/project.json
09:30:28 log  : Restore completed in 7877ms.
09:30:28 Restore CrossPlatform.sln
09:31:04 
09:31:04 
09:31:04 Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
09:31:04  (Exception from HRESULT: 0x8007001F)
09:31:04    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
09:31:04    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
09:31:04    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
09:31:04    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A device attached to the system is not functioning.
09:31:04  (Exception from HRESULT: 0x8007001F)
09:31:04    at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset()
09:31:04    at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr arg)
09:31:04    at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle)
09:31:04    at System.Net.Http.CurlHandler.MultiAgent.WorkerLoop()
09:31:04 
09:31:05 Restore failed

```

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
Another failure: 10:50:18 Unhandled Exception: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An internal error occurred.
10:50:19  (Exception from HRESULT: 0x8007054F)

**Comment by davkean** [comment]
This looks to be a permanent failure.

**Comment by davkean** [comment]
I've talked to @jasonmalinowski - I've marked this as an urgency-now bug, and assigned to the active viper @JohnHamby.

**Comment by mattwar** [comment]
@davkean I'm viper right now.   Is this nuget failing to load the cryptography dll?

**Comment by davkean** [comment]
It looks to be a failing disk - or some sort of I/O issue:

`A device attached to the system is not functioning.`
`An internal error occurred.`

These are the Azure VMs, so perhaps we have a bad VM? Not sure what machines it's occur or not, if you look at the top of the build log, you can see the VM name: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6490/console

**Comment by mattwar** [comment]
It's @agocke opinion that these failures are intermittent and are caused by IO failures coming up from the OS that the runtime doesn't handle properly.  These failures only started occurring when we switched to dynamic VM allocation.

**Comment by mattwar** [comment]
The failure is not specific to a single azure machine.

**Comment by mattwar** [comment]
Also failed here: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6507/console

**Comment by davkean** [comment]
Hit this again: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6539/console

**Comment by davkean** [comment]
And again: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6540/console

**Comment by natidea** [comment]
Reassigned to current viper

**Comment by ManishJayaswal** [comment]
Are we still seeing this?

**Comment by tannergooding** [comment]
I'm not seeing anything recent. I'm going to close for the time being.
