### ISSUE TITLE
Assert in diagnostics v2 engine

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10901]
I opened Newtonsoft.Json in VS, turned on full solution diagnostics and v2 engine and did some editing and hit the below assert:

![trydeserializedocumentasync](https://cloud.githubusercontent.com/assets/10605811/14837516/0c09fef2-0bce-11e6-9b3e-f64f9be2ad50.png)

Dump shared at `\\<%internal_share%\public\mavasani\v2_engine\Assert_TryDeserializeDocumentAsync.dmp`

**Comment by mavasani** [comment]
FYI @heejaechang

**Comment by mavasani** [comment]
Okay, I think I found a repro

1. Turn on v2 and full solution diagnostics
2. Open Newtonsoft.Json.Portable
3. Open 3-4 files and click on them to see their diagnostics populated in error list
4. Close any of the opened file, and then click on a diagnostic for the closed file in error list. You should hit the assert.

**Comment by mavasani** [comment]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
How this can happen?



   at Roslyn.Utilities.Contract.Assert(Boolean condition, String message)

   at Roslyn.Utilities.Contract.Requires(Boolean condition, String message)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectState.<GetAnalysisDataAsync>d__7.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectState.GetAnalysisDataAsync(Document document, Boolean avoidLoadingData, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IDECachedDiagnosticGetter.<GetProjectStateDiagnosticsAsync>d__5.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IDECachedDiagnosticGetter.GetProjectStateDiagnosticsAsync(StateSet stateSet, Project project, DocumentId documentId, AnalysisKind kind, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IDECachedDiagnosticGetter.<GetDiagnosticsAsync>d__3.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IDECachedDiagnosticGetter.GetDiagnosticsAsync(StateSet stateSet, Project project, DocumentId documentId, AnalysisKind kind, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.DiagnosticGetter.<GetSpecificDiagnosticsAsync>d__18.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.DiagnosticGetter.GetSpecificDiagnosticsAsync(CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.GetSpecificCachedDiagnosticsAsync(Solution solution, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.GetSpecificCachedDiagnosticsAsync(Solution solution, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.GetSpecificCachedDiagnosticsAsync(Workspace workspace, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.Microsoft.CodeAnalysis.Diagnostics.IDiagnosticUpdateSource.GetDiagnostics(Workspace workspace, ProjectId projectId, DocumentId documentId, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticService.GetSpecificDiagnostics(Workspace workspace, ProjectId projectId, DocumentId documentId, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticService.GetDiagnostics(Workspace workspace, ProjectId projectId, DocumentId documentId, Object id, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.AdjustInitialDiagnostics(Solution solution, UpdatedEventArgs args, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.GetInitialDiagnostics(CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.<>c__DisplayClass9_0.<.ctor>b__0()

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by heejaechang** [comment]
@mavasani thank you known issue that I am testing fix now.

**Comment by mavasani** [comment]
Oh, good to know!

**Comment by heejaechang** [comment]
this should be fixed now.
