### ISSUE TITLE
CSharpErrorLog_v2_Engine Integration test failing

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#10965]
Test was checked in here https://github.com/dotnet/roslyn-internal/pull/919 Yesterday.

See Build here: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/697/

Originally encountered on this PR: https://github.com/dotnet/roslyn/pull/10953

![image](https://cloud.githubusercontent.com/assets/9797472/14906147/2af9f34e-0d6d-11e6-964c-53f0cc7b096b.png)

```
Start - list of failing integration tests:
17:23:09 CSharpErrorLog_v2_Engine.xml
17:23:09 End - list of failing integration tests.
17:23:13 VS integration tests failed
17:23:13 ================================================================================
17:23:13 Dumping the log file for the last TAO test.  It may or may not include a failure.
17:23:13 ================================================================================
17:23:13 Test: CSharpNavigateTo started: 4/29/2016 12:23:58 AM
17:23:13 	Executing action [4/29/2016 12:23:58 AM] StartTarget
17:23:13 Begin Waiting for Apex Communication
17:23:13 	Executing action [4/29/2016 12:23:58 AM] AddProject
17:23:13 	Executing action [4/29/2016 12:24:09 AM] AddItem
17:23:13 	Executing action [4/29/2016 12:24:09 AM] OpenFile
17:23:13 DEBUG: executed DTE command File.OpenFile.
17:23:13 DEBUG: start polling for code window
17:23:13 DEBUG: polling complete
17:23:13 	Executing action [4/29/2016 12:24:09 AM] SetEditorText
17:23:13 	Executing action [4/29/2016 12:24:09 AM] CloseFile
17:23:13 The file did save the correct text.
17:23:13 	Executing action [4/29/2016 12:24:09 AM] AddItem
17:23:13 	Executing action [4/29/2016 12:24:09 AM] OpenFile
17:23:13 DEBUG: executed DTE command File.OpenFile.
17:23:13 DEBUG: start polling for code window
17:23:13 DEBUG: polling complete
17:23:13 	Executing action [4/29/2016 12:24:09 AM] WaitForWorkspace
17:23:13  Scenario: Verify 'Navigate To' class
17:23:13 	Executing action [4/29/2016 12:24:09 AM] NavigateTo
17:23:13 	Executing action [4/29/2016 12:24:09 AM] VerifyEditorSelection
17:23:13  Scenario: Verify 'Navigate To' member
17:23:13 	Executing action [4/29/2016 12:24:10 AM] NavigateTo
17:23:13 	Executing action [4/29/2016 12:24:10 AM] VerifyEditorSelection
17:23:13  Scenario: Verify 'Navigate To' from vb file
17:23:13 	Executing action [4/29/2016 12:24:10 AM] AddProject
17:23:13 	Executing action [4/29/2016 12:24:20 AM] AddItem
17:23:13 	Executing action [4/29/2016 12:24:20 AM] OpenFile
17:23:13 DEBUG: executed DTE command File.OpenFile.
17:23:13 DEBUG: start polling for code window
17:23:13 DEBUG: polling complete
17:23:13 	Executing action [4/29/2016 12:24:20 AM] WaitForWorkspace
17:23:13 	Executing action [4/29/2016 12:24:20 AM] NavigateTo
17:23:13 	Executing action [4/29/2016 12:24:20 AM] VerifyEditorSelection
17:23:13  Scenario: Verify IDocumentNavigationService calls utilized by 'Navigate To' correctly promote the preview tab to a permanent tab on item selection
17:23:13 	Executing action [4/29/2016 12:24:20 AM] ExcludeScenarioInHost
17:23:13 	Executing action [4/29/2016 12:24:20 AM] CloseFile
17:23:13 	Executing action [4/29/2016 12:24:20 AM] DocumentNavigation
17:23:13 	Executing action [4/29/2016 12:24:21 AM] VerifyActiveDocumentWindow
17:23:13 	Executing action [4/29/2016 12:24:21 AM] DocumentNavigation
17:23:13 	Executing action [4/29/2016 12:24:21 AM] VerifyActiveDocumentWindow
17:23:13 	Executing action [4/29/2016 12:24:21 AM] CloseTarget
17:23:13 Test finished: 4/29/2016 12:24:23 AM
17:23:13 	Executing action [4/29/2016 12:24:23 AM] CloseTarget
17:23:13 Closing VS. force Close = True, closeVsToFreeHandles = False
17:23:13 
17:23:13 ================================================================================
17:23:13 Dumping logs of all failed TAO tests.
17:23:13 ================================================================================
17:23:13 ================================================================================
17:23:13  Dumping log file d:\j\workspace\dotnet_roslyn---b84db72c\Open\Binaries\Release\VSIntegrationTestLogs\CSharpErrorLog_v2_Engine.txt
17:23:13 Test: CSharpErrorLog_v2_Engine started: 4/28/2016 11:46:22 PM
17:23:13 	Executing action [4/28/2016 11:46:22 PM] StartTarget
17:23:13 Begin Waiting for Apex Communication
17:23:13 	Executing action [4/28/2016 11:46:22 PM] SetFeatureOption
17:23:13 	Executing action [4/28/2016 11:46:22 PM] SetFeatureOption
17:23:13 	Executing action [4/28/2016 11:46:22 PM] ExecuteCommand
17:23:13 	Executing action [4/28/2016 11:46:22 PM] VerifyErrorList
17:23:13 	Executing action [4/28/2016 11:48:18 PM] UnzipFile
17:23:13 	Executing action [4/28/2016 11:48:18 PM] OpenProject
17:23:13  Scenario: Error List Intellisense Diagnostics
17:23:13 	Executing action [4/28/2016 11:48:18 PM] ExecuteCommand
17:23:13 	Executing action [4/28/2016 11:48:18 PM] VerifyErrorList
17:23:13 Verifying error list content against the baseline: Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\ErrorLogBaselineFile.json
17:23:13  Scenario: Error List Build Diagnostics
17:23:13 	Executing action [4/28/2016 11:48:43 PM] Build
17:23:13 	Executing action [4/28/2016 11:48:56 PM] ExecuteCommand
17:23:13 	Executing action [4/28/2016 11:48:56 PM] VerifyErrorLog
17:23:13 	Executing action [4/28/2016 11:48:58 PM] CleanSolution
17:23:13 	Executing action [4/28/2016 11:48:58 PM] Build
17:23:13 	Executing action [4/28/2016 11:49:11 PM] ExecuteCommand
17:23:13 	Executing action [4/28/2016 11:49:11 PM] VerifyErrorLog
17:23:13 --------------------------------
17:23:13 System.Exception: Verify Error log failed:
17:23:13 
17:23:13 Expected Count: '9798'
17:23:13 Actual Count: '0'
17:23:13 
17:23:13 Details:
17:23:13 
17:23:13 	Missing diagnostics: 
17:23:13 		"ruleId": "SA1101",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Serialization\/TraceJsonWriter.cs",;"startLine": 196,;"startColumn": 13,
17:23:13 		"ruleId": "SA1121",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Linq\/JToken.cs",;"startLine": 1784,;"startColumn": 61,
17:23:13 		"ruleId": "SA1101",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Linq\/JValue.cs",;"startLine": 759,;"startColumn": 25,
17:23:13 		"ruleId": "SA1101",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Linq\/JsonPath\/JPath.cs",;"startLine": 720,;"startColumn": 33,
17:23:13 		"ruleId": "SA1101",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Linq\/JsonPath\/JPath.cs",;"startLine": 720,;"startColumn": 21,
17:23:13 		"ruleId": "SA1202",;"uri": "file:Closed\/Test\/Solutions\/Newtonsoft.Json\/Newtonsoft.Json\/Converters\/ExpandoObjectConverter.cs",;"startLine": 150,;"startColumn": 30,
<Elided So This Log Doesn't Crash Your Browser>

17:23:15 Server stack trace: 
17:23:15    at Roslyn.VSHosting.Test.RoslynInProcessAPI.VerifyErrorLog(ImmutableDictionary`2 actual, ImmutableDictionary`2 baseline, Boolean isBuildDiagnostics) in d:\j\workspace\dotnet_roslyn---b84db72c\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI_Diagnostics.cs:line 381
17:23:15    at Roslyn.VSHosting.Test.RoslynInProcessAPI.VerifyErrorLog(DiagnosticsMode mode, String errorLogBaselineFile, Boolean ignoreSuppressedDiagnostics, String projectNameOpt, String documentNameOpt) in d:\j\workspace\dotnet_roslyn---b84db72c\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI_Diagnostics.cs:line 179
17:23:15    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
17:23:15    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
17:23:15 
17:23:15 Exception rethrown at [0]: 
17:23:15    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
17:23:15    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
17:23:15    at Roslyn.VSHosting.Test.RoslynInProcessAPI.VerifyErrorLog(DiagnosticsMode mode, String errorLogBaselineFile, Boolean ignoreSuppressedDiagnostics, String projectNameOpt, String documentNameOpt)
17:23:15    at Roslyn.VSHosting.Test.VerifyErrorLogAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---b84db72c\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyErrorLogAction.cs:line 62
17:23:15    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
17:23:15    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
17:23:15 ================================
```

**Comment by jmarolf** [comment]
@mavasani

**Comment by mavasani** [comment]
@heejaechang - this scenario does build and then asks external diagnostic update source for diagnostics.

**Comment by heejaechang** [comment]
is this race or failing all the time?

**Comment by heejaechang** [comment]
@mavasani build error is asynchronous, are you waiting for build (not VS build) to finish?

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/TaskList/ExternalErrorDiagnosticUpdateSource.cs,40

**Comment by mavasani** [comment]
Probably not, can you fix the VerifyErrorLogAction that calls GetBuildErrors to do this correctly?

**Comment by heejaechang** [comment]
sure
