### ISSUE TITLE
VBCSCompiler.exe crashes with InvalidProgramException

### ISSUE THREAD

**Issue by jakesays** [dotnet/roslyn#110]
While trying to build Roslyn master I'm getting the exception InvalidProgramException ("Common Language Runtime detected an invalid program.".) Stack trace is listed below.

Environment:
Windows 7 64bit, Visual studio 2013 update 4.

I open a visual studio command prompt and type "msbuild /t:Build /p:CIBuild=true" to pick up the Roslyn2013 solution.

Stack:
   at System.Collections.Immutable.SecurePooledObject`1.Use[TCaller](TCaller& caller)
   at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.PushLeft(SortedInt32KeyNode`1 node)
   at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator..ctor(SortedInt32KeyNode`1 root)
   at System.Collections.Immutable.ImmutableDictionary`2.Enumerator..ctor(SortedInt32KeyNode`1 root, Builder builder)
   at System.Collections.Immutable.ImmutableDictionary`2.GetEnumerator()
   at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<>c__DisplayClass5_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.Cache.<.ctor>b__5_3()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.GetMergedReferenceDirectives()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.CSharp.DeclarationTable.get_ReferenceDirectives()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBoundReferenceManager()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CompilerServer.CSharpCompilerServer.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(String currentDirectory, String libDirectory, String responseFileDirectory, String tempPath, String[] commandLineArguments, TextWriter output, CancellationToken cancellationToken, Boolean& utf8output)
   at Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.CSharpCompile(BuildRequest req, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CompilerServer.CompilerRequestHandler.HandleRequest(BuildRequest req, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.Connection.<>c__DisplayClass6_0.<ServeBuildRequest>b__0()

**Comment by pharring** [comment]
@theoy I've seen this internally in Watson dumps but couldn't get a solid repro.

**Comment by jakesays** [comment]
Anything I can do to help track this down?

**Comment by theoy** [comment]
Hi @jakesays - this looks like the same issue as dotnet/corefx#320, which can be resolved by upgrading to .NET 4.5.2.

Also, for the time being the configuration that we internally utilize for development is based on Visual Studio 2015. At the current point, Master is developed against internal nightly builds of Visual Studio. However, we maintain a [CTP5 branch](https://github.com/dotnet/roslyn/commits/releases/Dev14CTP5) that is relatively recent and works against the publicly available [VS2015 CTP5](http://www.visualstudio.com/news/vs2015-vs). If you're looking to contribute and submit a pull request against that branch, we'll gladly port it to work against Master.

Thanks!

**Comment by nguerrera** [comment]
Fixed in https://github.com/dotnet/corefx/commit/534c6e75e690c2ba7889f6e8c6853178973f8db6
