### ISSUE TITLE
Flaky test: CSharpDebuggerIntellisense

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#11032]
This failed in this test run: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/498/consoleFull#-4663002361aefe2b-268e-4e71-8c03-11b4c0acbfbc

**Comment by ManishJayaswal** [comment]
@drognanar can you take a look at this?

**Comment by jmarolf** [comment]
![image](https://cloud.githubusercontent.com/assets/9797472/17381170/8007437e-597f-11e6-9444-65100dad1d77.png)

```
Start - list of failing integration tests:
13:32:08 BasicSmartIndenter.xml
13:32:08 End - list of failing integration tests.
13:32:09 VS integration tests failed
13:32:09 ================================================================================
13:32:09 Dumping the log file for the last TAO test.  It may or may not include a failure.
13:32:09 ================================================================================
13:32:09 Test: CSharpDebuggerIntellisense started: 8/3/2016 8:32:37 PM
13:32:09 	Executing action [8/3/2016 8:32:37 PM] StartTarget
13:32:09 Begin Waiting for Apex Communication
13:32:09 	Executing action [8/3/2016 8:32:37 PM] AddProject
13:32:09 	Executing action [8/3/2016 8:32:37 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:32:38 PM] Debug
13:32:09 			 [8/3/2016 8:32:38 PM] Set Breakpoint
13:32:09 			 [8/3/2016 8:32:38 PM] Set Breakpoint
13:32:09 			 [8/3/2016 8:32:38 PM] Set Breakpoint
13:32:09 			 [8/3/2016 8:32:38 PM] Disable Diagnostics Hub
13:32:09 			 [8/3/2016 8:32:38 PM] Start Debugging
13:32:09  Scenario: Do not format or crash on ;
13:32:09 	Executing action [8/3/2016 8:32:41 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:41 PM] Debug
13:32:09 			 [8/3/2016 8:32:41 PM] Continue
13:32:09 	Executing action [8/3/2016 8:32:41 PM] ImmediateWindow
13:32:09  Scenario: Completion on first character
13:32:09 	Executing action [8/3/2016 8:32:42 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:42 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:42 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:32:48 PM] VerifyCompletionList
13:32:09  Scenario: Completion after dot
13:32:09 	Executing action [8/3/2016 8:32:48 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:48 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:49 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:32:54 PM] VerifyCompletionList
13:32:09  Scenario: Completion after ?
13:32:09 	Executing action [8/3/2016 8:32:54 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:54 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:32:56 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:33:01 PM] VerifyCompletionList
13:32:09  Scenario: Completion after open paren in method call
13:32:09 	Executing action [8/3/2016 8:33:01 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:01 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:03 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:33:08 PM] VerifyCompletionList
13:32:09  Scenario: Signature help
13:32:09 	Executing action [8/3/2016 8:33:08 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:08 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:10 PM] VerifySignatureHelp
13:32:09  Scenario: Completion in an expression
13:32:09 	Executing action [8/3/2016 8:33:10 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:10 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:10 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:33:16 PM] VerifyCompletionList
13:32:09  Scenario: Locals from previous block are not visible in the current block
13:32:09 	Executing action [8/3/2016 8:33:16 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:16 PM] Debug
13:32:09 			 [8/3/2016 8:33:16 PM] Continue
13:32:09 			 [8/3/2016 8:33:16 PM] Try Wait For Break Mode
13:32:09 	Executing action [8/3/2016 8:33:16 PM] ImmediateWindow
13:32:09 	Executing action [8/3/2016 8:33:17 PM] WaitForCompletionSet
13:32:09 	Executing action [8/3/2016 8:33:22 PM] VerifyCompletionList
13:32:09 	Executing action [8/3/2016 8:33:22 PM] CloseTarget
13:32:09 Test finished: 8/3/2016 8:33:24 PM
13:32:09 	Executing action [8/3/2016 8:33:24 PM] CloseTarget
13:32:09 Closing VS. force Close = True, closeVsToFreeHandles = False
13:32:09 
13:32:09 ================================================================================
13:32:09 Dumping logs of all failed TAO tests.
13:32:09 ================================================================================
13:32:09 ================================================================================
13:32:09  Dumping log file d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\VSIntegrationTestLogs\BasicSmartIndenter.txt
13:32:09 Test: BasicSmartIndenter started: 8/3/2016 8:13:33 PM
13:32:09 	Executing action [8/3/2016 8:13:33 PM] StartTarget
13:32:09 Begin Waiting for Apex Communication
13:32:09 	Executing action [8/3/2016 8:13:33 PM] AddProject
13:32:09 	Executing action [8/3/2016 8:13:43 PM] AddItem
13:32:09  Scenario: empty
13:32:09 	Executing action [8/3/2016 8:13:43 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:44 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:44 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:45 PM] VerifyCaretPosition
13:32:09  Scenario: Imports
13:32:09 	Executing action [8/3/2016 8:13:45 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:45 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:45 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:45 PM] VerifyCaretPosition
13:32:09  Scenario: namespace
13:32:09 	Executing action [8/3/2016 8:13:45 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:45 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:45 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:46 PM] VerifyCaretPosition
13:32:09  Scenario: class
13:32:09 	Executing action [8/3/2016 8:13:46 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:46 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:46 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:47 PM] VerifyCaretPosition
13:32:09  Scenario: method
13:32:09 	Executing action [8/3/2016 8:13:47 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:47 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:47 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:47 PM] VerifyCaretPosition
13:32:09  Scenario: statements
13:32:09 	Executing action [8/3/2016 8:13:47 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:47 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:47 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:49 PM] VerifyCaretPosition
13:32:09  Scenario: Lambda
13:32:09 	Executing action [8/3/2016 8:13:49 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:49 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:49 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:50 PM] VerifyCaretPosition
13:32:09  Scenario: Inside Doc comments with use tabs option
13:32:09 	Executing action [8/3/2016 8:13:50 PM] SetFormattingOptions
13:32:09 	Executing action [8/3/2016 8:13:50 PM] SetEditorText
13:32:09 	Executing action [8/3/2016 8:13:50 PM] PlaceCursor
13:32:09 	Executing action [8/3/2016 8:13:50 PM] SendKeys
13:32:09 	Executing action [8/3/2016 8:13:51 PM] VerifyCaretPosition
13:32:09 	Executing action [8/3/2016 8:13:51 PM] VerifyEditorContainsText
13:32:09 --------------------------------
13:32:09 System.Exception: Actual and expected items don't match:
13:32:09 Expected: Namespace NS
13:32:09 	Class TestClass
13:32:09 		''' <summary>
13:32:09 		''' MARKER
13:32:09 		''' 
13:32:09 		''' </summary>
13:32:09 		Sub Method()
13:32:09 		End Sub
13:32:09 	End Class
13:32:09 End Namespace
13:32:09 Actual: Namespace NS
13:32:09     Class TestClass
13:32:09         ''' <summary>
13:32:09         ''' MARKER
13:32:09         ''' 
13:32:09         ''' </summary>
13:32:09         Sub Method()
13:32:09         End Sub
13:32:09     End Class
13:32:09 End Namespace
13:32:09 
13:32:09    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
13:32:09    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
13:32:09    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 
```

**Comment by ManishJayaswal** [comment]
These tests are not running and are getting updated for willow so closing this issue as it is not actionable.
