### ISSUE TITLE
NRE at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#11092]
I do not have a repro, but am hitting this NRE very often while typing. It seems to be from RenameTrackingTaggerProvider.

I have InstallDogfood bits from master which are a day old (1.03.0.60503)

Dump saved at: `\\<%Internal_Share%>\public\dumps\11092\devenv.dmp`

Message: `Object reference not set to an instance of an object.`

Call stack:
>    at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>d__5.MoveNext()
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1..ctor(TSymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(ILocalSymbol localSymbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20.MoveNext()

**Comment by mavasani** [comment]
I am hitting this frequently even with the latest InstallDogfood bits from master - I am marking this as urgency soon and rolling back to older Roslyn bits :-(

**Comment by mavasani** [comment]
FYI @dpoeschl

**Comment by mavasani** [comment]
Note that all the crashes seem to occur when there are errors in code being edited. I rolled back to Roslyn bits from 27th April and still hitting this crash. Rename tracking diagnostic is marked as [NotConfigurable](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/RenameTracking/RenameTrackingDiagnosticAnalyzer.cs,13), so I guess it cannot be suppressed either.

**Comment by mavasani** [comment]
I rolled back to bits from the 26th April and haven't seen any more crashes. Probably something checked in during these 2 days that regressed this?

**Comment by mavasani** [comment]
Commented too soon - got the same exception on bits from 26th as well :-(

**Comment by jmarolf** [comment]
@ManishJayaswal ran into this just now.  

```
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>d__5.MoveNext()
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1..ctor(TSymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(ILocalSymbol localSymbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20.MoveNext()
```

Looks to be the same issue.  I'll take a look.

**Comment by mavasani** [comment]
I have a consistent repro now:

1. Git clone roslyn-analyzers git repo and checkout the sources from 8th May
2. cibuild - to build the repo
3. Open src\Analyzers.sln
4. Open file: \src\Microsoft.QualityGuidelines.Analyzers\Core\UseLiteralsWhereAppropriate.cs
5. Go to line 73 and delete all text after 'fieldInitializerValue.Type' on that line in the if condition, including the && operator.
6. Enter '.SpecialType ==' after 'fieldInitializerValue.Type' and hit space - you should hit this crash

**Comment by mavasani** [comment]
Can we also consider making Rename tracking diagnostic configurable, so that it can be disabled if the user doesn't care about this feature?

**Comment by jmarolf** [comment]
@mavasani 's repro steps uncover a different crash.  Filed as https://github.com/dotnet/roslyn/issues/11193

**Comment by jmarolf** [comment]
So here's whats happening:

```C#
public static SymbolKey GetSymbolKey(this ISymbol symbol)
{
    return SymbolKey.Create(symbol, null, CancellationToken.None);
}
```
We call `symbol.GetSymbolKey()` which calls `SymbolKey.Create` passing in a null compilation.

```C#
internal static SymbolKey Create(ISymbol symbol, CancellationToken cancellationToken = default(CancellationToken))
{
    return GetOrCreate(symbol, new Visitor(compilation, cancellationToken));
}
```
We create a new visitor object with a null compilation.  Normally this would be the end of it but we crash due to this null compilation later.
```C#
private static SymbolKey GetOrCreate(ISymbol symbol, Visitor visitor)
{
    if (symbol == null)
    {
        return s_null;
    }

    SymbolKey result;
    if (!visitor.SymbolCache.TryGetValue(symbol, out result))
    {
>>      result = symbol.Accept(visitor);
        visitor.SymbolCache[symbol] = result;
    }

    return result;
}
```
The call to Accept will cause the visitor to be exercised. We jump through the visit methods until we arrive at
```C#
public override SymbolKey VisitLocal(ILocalSymbol localSymbol)
{
>>  return new NonDeclarationSymbolKey<ILocalSymbol>(localSymbol, this);
}
```
Which calls Enumerate Symbols
```C#
internal NonDeclarationSymbolKey(TSymbol symbol, Visitor visitor)
{
    var containingSymbol = symbol.ContainingSymbol;

    while (!containingSymbol.DeclaringSyntaxReferences.Any())
    {
        containingSymbol = containingSymbol.ContainingSymbol;
    }

    _containingKey = GetOrCreate(containingSymbol, visitor);
    _localName = symbol.Name;

>>  foreach (var possibleSymbol in EnumerateSymbols(visitor.Compilation, containingSymbol, _localName, visitor.CancellationToken))
    {
        if (possibleSymbol.Item1.Equals(symbol))
        {
            _ordinal = possibleSymbol.Item2;
            break;
        }
    }
}
```
In this case because of the visitation pattern we end up calling `EnumerateSymbols` and passing in a null compilation.
This will always crash if we end of visiting a local as part of creating a `SymbolKey`

**Comment by mavasani** [comment]
@jmarolf I have consistent repro for this now, and I verified that this time the exception is NRE from `Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`

1. Checkout Roslyn code from my PR: https://github.com/dotnet/roslyn/pull/11225 (commit https://github.com/dotnet/roslyn/pull/11225/commits/6f90c89cc3d075f56e1b1c5318198f949a3916c5) - I hope to merge this PR soon, so you may be able to skip this step.
2. Open Roslyn.sln and wait for solution load to complete.
3. Open file `src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs` and close all other documents.
4. Goto line 657:
 (`if (!_lazyGeneratedCodeSymbolsMap.TryGetValue(tree, out existingGeneratedCodeSymbols))`)
5. Save All and close the solution. Restart VS and open Roslyn.sln again.
6. Put the cursor at the end of `existingGeneratedCodeSymbols`, line 657, column 101 and type any character - you should hit this crash.
