### ISSUE TITLE
NRE when editing cs file in Visual Studio 2015

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/roslyn#11244]
**Version Used**: 

```
Visual Studio Enterprise 2015 v14.0.25123.00 Update 2
Roslyn Insider v1.3.0.60510 from nightly feed
```

**Steps to Reproduce**:

Several crashes of Visual Studio 2015 Update 2 when editing file. To reproduce, take the attached file and try to add an "await" in line 137.
[BaseDataSourceObservableCollection.zip](https://github.com/dotnet/roslyn/files/258731/BaseDataSourceObservableCollection.zip)

**Expected Behavior**:

Visual Studio 2015 should not crash.

**Actual Behavior**:

Visual Studio 2015 crashes with the following exception details (taken from event viewer):

```
Anwendung: devenv.exe
Frameworkversion: v4.0.30319
Beschreibung: Die Anwendung forderte die Beendigung des Prozesses durch System.Environment.FailFast(Zeichenfolgenmeldung) an.
Meldung: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>d__5.MoveNext()
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1..ctor(TSymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(ILocalSymbol localSymbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1.<EnumerateSymbols>d__5.MoveNext()
   at Microsoft.CodeAnalysis.SymbolKey.NonDeclarationSymbolKey`1..ctor(TSymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.SymbolKey.Visitor.VisitLocal(ILocalSymbol localSymbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.SymbolKey.GetOrCreate(ISymbol symbol, Visitor visitor)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSourceDefinitionWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableSymbolAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.TrackingSession.<DetermineIfRenamableIdentifierAsync>d__20.MoveNext()<---

Stapel:
   bei System.Environment.FailFast(System.String, System.Exception)
   bei Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   bei Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   bei Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   bei Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
   bei System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
   bei System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task.FinishStageTwo()
   bei System.Threading.Tasks.Task.Finish(Boolean)
   bei System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetException(System.Object)
   bei System.Threading.Tasks.UnwrapPromise`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.UnwrapPromise`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ProcessInnerTask(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.UnwrapPromise`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ProcessCompletedOuterTask(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.UnwrapPromise`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].InvokeCore(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.UnwrapPromise`1[[Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider+TriggerIdentifierKind, Microsoft.CodeAnalysis.EditorFeatures, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Invoke(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task.FinishStageTwo()
   bei System.Threading.Tasks.Task.Finish(Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by jmarolf** [comment]
Looks similar to https://github.com/dotnet/roslyn/issues/11092

**Comment by schuettecarsten** [comment]
Seems to be fixed, https://github.com/dotnet/roslyn/issues/11092 is also closed.

**Comment by jmarolf** [comment]
Thanks! I'll close this then
