### ISSUE TITLE
NullReferenceException in csi.exe

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#11284]
**Version Used**: 
> Microsoft (R) Visual C# Interactive Compiler version 1.2.0.60317
> Copyright (C) Microsoft Corporation. All rights reserved.

**Steps to Reproduce**:

1. Start csi.exe
2. Execute `struct Test { public static readonly Test? Null = null; }`
3. Execute `Test.Null`

**Expected Behavior**: 
`null`

**Actual Behavior**:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonTypeNameFormatter.FormatNonGenericTypeName(TypeInfo typeInfo, CommonTypeNameFormatterOptions options)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpTypeNameFormatter.FormatTypeName(Type type, CommonTypeNameFormatterOptions options)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatException(Exception e)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.DisplayException(Exception e)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.TryBuildAndRun(Script`1 newScript, InteractiveScriptGlobals globals, ScriptState`1& state, ScriptOptions& options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveLoop(ScriptOptions options, String initialScriptCodeOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveCore(ErrorLogger errorLogger)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractive()
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.Csi.Main(String[] args)
```

**Comment by svick** [comment]
This code not returning `null` is a bug in the CLR: dotnet/coreclr#4049.

I think that this code throwing a `NullRerefenceException` instead of the `TypeLoadException` that is thrown by the CLR is a bug in Roslyn scripting.

**Comment by tmat** [comment]
The scripting issue is fixed by https://github.com/dotnet/roslyn/pull/11296
