### ISSUE TITLE
VS2015 -> XAML View not working any more

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/roslyn#113]
Intellisense could not be initialized due to the following error: System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.AddNamespace(IAssembly assembly, IXmlNamespace xmlNamespace, String clrNamespace) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfXmlnsDefinitionMap.RegisterAssemblyNamespaces(IAssembly assembly, IEnumerable1 attributes)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.RegisterAssemblies(IEnumerable1 referencedAssemblies) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfPlatformMetadata.CreateXmlnsDefinitionMap(ManagedTypeResolver typeResolver) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Reset() at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Initialize(ITypeResolver typeResolver) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedTypeResolverService.GetTypeResolver(IHostProject hostProject) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlFileInformationService.CreateFileInformationContext(IHostSourceItem sourceItem) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.EnsureBufferCache(IVsTextLines textLines) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.CreateSource(IVsTextLines textLines) Intellisense could not be initialized due to the following error: System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.AddNamespace(IAssembly assembly, IXmlNamespace xmlNamespace, String clrNamespace)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfXmlnsDefinitionMap.RegisterAssemblyNamespaces(IAssembly assembly, IEnumerable1 attributes) at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedXmlnsDefinitionMap.RegisterAssemblies(IEnumerable1 referencedAssemblies)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Platform.Wpf.WpfPlatformMetadata.CreateXmlnsDefinitionMap(ManagedTypeResolver typeResolver)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Reset()
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedPlatformMetadata.Initialize(ITypeResolver typeResolver)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Metadata.ManagedTypeResolverService.GetTypeResolver(IHostProject hostProject)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlFileInformationService.CreateFileInformationContext(IHostSourceItem sourceItem)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.EnsureBufferCache(IVsTextLines textLines)
at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.XamlLanguageService.CreateSource(IVsTextLines textLines)

**Comment by Pilchie** [comment]
@jogibear9988 I'm not sure what this bug is supposed to represent.  Looks like you might have pasted output from git instead of something else?

**Comment by jogibear9988** [comment]
sorry somehow i posted the wrong content...,

can you reopen?

**Comment by Pilchie** [comment]
Hi again @jogibear9988.  Unfortunately, the Xaml language service is not part of Roslyn.  Can you file this issue for them on http://connect.microsoft.com instead?

**Comment by jogibear9988** [comment]
Are you sure?

quote from http://www.visualstudio.com/en-us/news/vs2015-vs.aspx

XAML Language Service

Fast, reliable, and modern 
In this release, we’ve rebuilt the XAML language service on top of .NET Compiler Platform ("Roslyn") so that we can provide you with a fast and reliable XAML editing experience that includes IntelliSense.

**Comment by RichiCoder1** [comment]
That means it's utilizing Roslyn, but it's not actually a built in part of it under the Roslyn team's perview.

**Comment by jogibear9988** [comment]
Thanks for the Info...

https://connect.microsoft.com/VisualStudio/feedback/details/1107865/xaml-editor-not-workin-anymore
