### ISSUE TITLE
Assertion failed during build

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#11306]
Using latest version, built from source.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
How this can happen?



   at Roslyn.Utilities.Contract.Assert(Boolean condition, String message)

   at Roslyn.Utilities.Contract.Requires(Boolean condition, String message)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectState.<GetAnalysisDataAsync>d__8.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectState.GetAnalysisDataAsync(Project project, Boolean avoidLoadingData, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectAnalysisData.<CreateAsync>d__9.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.ProjectAnalysisData.CreateAsync(Project project, IEnumerable`1 stateSets, Boolean avoidLoadingData, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.<CreateProjectAnalysisDataAsync>d__14.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.CreateProjectAnalysisDataAsync(Project project, ImmutableArray`1 stateSets, ImmutableArray`1 diagnostics)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.<SynchronizeWithBuildAsync>d__13.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.SynchronizeWithBuildAsync(Workspace workspace, ImmutableDictionary`2 map)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.SynchronizeWithBuildAsync(Workspace workspace, ImmutableDictionary`2 diagnostics)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.SynchronizeWithBuildAsync(Workspace workspace, ImmutableDictionary`2 diagnostics)

   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.CleanupAllLiveErrors(DiagnosticAnalyzerService diagnosticService, IEnumerable`1 projects)

   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.<CleanupAllLiveErrorsIfNeededAsync>d__21.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.CleanupAllLiveErrorsIfNeededAsync(DiagnosticAnalyzerService diagnosticService, Solution solution, InprogressState state)

   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.<>c__DisplayClass20_0.<<OnSolutionBuild>b__0>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.<>c__DisplayClass20_0.<OnSolutionBuild>b__0()

   at Roslyn.Utilities.SimpleTaskQueue.<>c__DisplayClass8_0.<ScheduleTask>b__1(Task t)

   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass20_1.<ContinueWithAfterDelayFromAsync>b__1(Task _)

   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by bkoelman** [comment]
Debugger breaks at: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.ProjectState.cs#L102.

**Comment by mavasani** [comment]
Tagging @heejaechang

**Comment by heejaechang** [comment]
thank you for reporting.

it looks like there is a case where desalinizing project state might fail (active file state being merged back to project before the very first project analysis ran)

I will add comment to show when the case can happen. it should be okay for you to just ignore assert.
