### ISSUE TITLE
Test Runner should catch IOExceptions

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11364]
If the Test Runner encounters a IOException like there not being a enough spare on the disc to output the logs. It locks the process and can not be killed, which mean subsequent runs fails as it still has hold of file handles.
The only fix (I know of) is to restart the OS.

**Comment by jaredpar** [comment]
I'm not sure how the test runner can lock a process, especially if the test runner process itself dies.  The test runner does spawn a number of child xunit processes but doesn't "lock" them.  

Can you be more specific on what you feel is getting locked here?

**Comment by AdamSpeight2008** [comment]
@jaredpar Dug through the Applications Log
```
Faulting application name: RunTests.exe, version: 42.42.42.42, time stamp: 0xa6d927d8
Faulting module name: KERNELBASE.dll, version: 10.0.10586.306, time stamp: 0x571afb9a
Exception code: 0xe0434352
Fault offset: 0x000bdae8
Faulting process id: 0x4d30
Faulting application start time: 0x01d1afe6d8c61e5e
Faulting application path: M:\roslyn-AdamSpeight2008\Binaries\Debug\RunTests\RunTests.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 0d63e5d7-b6d3-4588-b4d3-44c7af5daae2
Faulting package full name: 
Faulting package-relative application ID: 


Application: RunTests.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   at System.IO.FileStream.FlushWrite(Boolean)
   at System.IO.FileStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   at System.IO.File.WriteAllText(System.String, System.String)
   at RunTests.TestRunner.PrintFailedTestResult(RunTests.TestResult)
   at RunTests.TestRunner.Print(System.Collections.Generic.List`1<RunTests.TestResult>)
   at RunTests.TestRunner+<RunAllAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[[RunTests.RunAllResult, RunTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=null]].GetResult()
   at RunTests.Program+<RunCore>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at RunTests.Program.Main(System.String[])

Faulting application name: csc.exe, version: 42.42.42.42, time stamp: 0xb034754c
Faulting module name: KERNELBASE.dll, version: 10.0.10586.306, time stamp: 0x571af331
Exception code: 0xe0434352
Fault offset: 0x0000000000071f28
Faulting process id: 0x4784
Faulting application start time: 0x01d1afe78770f77d
Faulting application path: M:\roslyn-AdamSpeight2008\Binaries\Debug\csc.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 4cefb148-af5e-468c-964f-b2f32236da34
Faulting package full name: 
Faulting package-relative application ID: 


Application: csc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   at System.IO.FileStream.FlushWrite(Boolean)
   at System.IO.FileStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at Microsoft.CodeAnalysis.CommonCompiler+CompilerEmitStreamProvider.Dispose()
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter, Microsoft.CodeAnalysis.ErrorLogger, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc+<>c__DisplayClass1_0.<Run>b__0(System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Boolean, System.IO.TextWriter, System.Func`2<System.IO.TextWriter,Int32>)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[], System.String[])
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])

Faulting application name: vbc.exe, version: 42.42.42.42, time stamp: 0xcee6f57f
Faulting module name: KERNELBASE.dll, version: 10.0.10586.306, time stamp: 0x571af331
Exception code: 0xe0434352
Fault offset: 0x0000000000071f28
Faulting process id: 0x66f0
Faulting application start time: 0x01d1afe77d6bbb1e
Faulting application path: M:\roslyn-AdamSpeight2008\Binaries\Debug\vbc.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 16b92db6-8a1a-4ebd-b1c0-a345f3022cd8
Faulting package full name: 
Faulting package-relative application ID: 

Application: vbc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   at System.IO.FileStream.FlushWrite(Boolean)
   at System.IO.FileStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at Microsoft.CodeAnalysis.CommonCompiler+CompilerEmitStreamProvider.Dispose()
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter, Microsoft.CodeAnalysis.ErrorLogger, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Vbc+<>c__DisplayClass1_0.<Run>b__0(System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Boolean, System.IO.TextWriter, System.Func`2<System.IO.TextWriter,Int32>)
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Vbc.Run(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(System.String[], System.String[])
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(System.String[])
```

Do any of the unit test write to disc? Without catching the potential exceptions.

**Comment by jaredpar** [comment]
Quoting myself

> Can you be more specific on what you feel is getting locked here?

**Comment by AdamSpeight2008** [comment]
In `Process Explorer` the following are `suspended`.
```
RunTests.exe
csc.exe
vbc.exe
```

**Comment by jmarolf** [comment]
@AdamSpeight2008 my question is: does `RunTests.exe` never complete? or is the problem that is completes but it fails a lot of tests so its difficult to root cause the failures?

**Comment by AdamSpeight2008** [comment]
From what I recall. I think a test tried to write disc, failed due to lack of  space. (4 Gb RAMDisc)
As they are run in parallel the other test finish. It get to point after printing out the results. Red Text come up about failures. 

Then when you try to rerun the test, even after making space. The tests can run because a file is in use.

**Comment by AdamSpeight2008** [comment]
Encountered it again the in use files are.
```
  VisualStudioInteractiveWindow -> M:\roslyn-AdamSpeight2008\Binaries\Debug\Microsoft.VisualStudio.VsInteractiveWindow.
  vsix
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'M:\roslyn-
AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Adam
Speight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): warning MSB3026: Could not cop
y "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\
Binaries\Debug\Microsoft.CodeAnalysis.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'M:\roslyn
-AdamSpeight2008\Binaries\Debug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-Ada
mSpeight2008\src\Compilers\Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): error MSB3027: Could not copy
"M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight2008\Bi
naries\Debug\Microsoft.CodeAnalysis.dll". Exceeded retry count of 10. Failed. [M:\roslyn-AdamSpeight2008\src\Compilers\
Core\Portable\CodeAnalysis.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3813,5): error MSB3021: Unable to copy
file "M:\roslyn-AdamSpeight2008\Binaries\Obj\CodeAnalysis\Debug\Microsoft.CodeAnalysis.dll" to "M:\roslyn-AdamSpeight20
08\Binaries\Debug\Microsoft.CodeAnalysis.dll". The process cannot access the file 'M:\roslyn-AdamSpeight2008\Binaries\D
ebug\Microsoft.CodeAnalysis.dll' because it is being used by another process. [M:\roslyn-AdamSpeight2008\src\Compilers\
Core\Portable\CodeAnalysis.csproj]
  ProcessWatchdog -> M:\roslyn-AdamSpeight2008\Binaries\Debug\ProcessWatchdog\ProcessWatchdog.exe
  RunTests -> M:\roslyn-AdamSpeight2008\Binaries\Debug\RunTests\RunTests.exe
```

**Comment by jaredpar** [comment]
Have you run `handle.exe` when this happens to see what process is holding those binaries?

**Comment by AdamSpeight2008** [comment]
Looks like if `Keep Test Execution Engine Running` is enabled then there is a good chance of the file being in use.
