### ISSUE TITLE
CodeAction unit tests are flakey (TestGenerateFromEventHandler, TestWithLeftShift0)

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#11388]
Assert.NotNull() failure in 2 different GFU tests in the following test runs. 

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/7289/testReport/junit/Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.GenerateMethod/GenerateMethodTests/TestGenerateFromEventHandler/

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/7287/testReport/junit/Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateEnumMember/GenerateEnumMemberTests/TestWithLeftShift0/

~~~
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__20.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 317 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__15.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 222 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__14.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 206 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 175 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__12.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 163 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.GenerateMethod.GenerateMethodTests.VB$StateMachine_91_TestGenerateFromEventHandler.MoveNext() in q:\roslyn\src\EditorFeatures\VisualBasicTest\Diagnostics\GenerateMethod\GenerateMethodTests.vb:line 871 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

~~~
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__20.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 317 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__15.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 222 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__14.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 206 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 175 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__12.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 163 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateEnumMember.GenerateEnumMemberTests.<TestWithLeftShift0>d__12.MoveNext() in q:\roslyn\src\EditorFeatures\CSharpTest\Diagnostics\GenerateEnumMember\GenerateEnumMemberTests.cs:line 111 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by balajikris** [comment]
A similar failure from RemoveUnnecessaryImports
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/1447/

~~~
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__20.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 317 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__15.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 222 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__14.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 206 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 175 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__12.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs:line 163 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports.RemoveUnnecessaryImportsTests.VB$StateMachine_16_TestImportsSurroundedByDirectives.MoveNext() in d:\j\workspace\roslyn-intern---4cf810ea\Open\src\EditorFeatures\VisualBasicTest\Diagnostics\RemoveUnnecessaryImports\RemoveUnnecessaryImportsTests.vb:line 140 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by balajikris** [comment]
Roslyn-Master-Signed-Release\20160527.1\xUnitResults\Roslyn.Services.Editor.CSharp.UnitTests.dll.txt:

Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.AddUsing.AddUsingTests+NuGet.TestAddInsideLambda [FAIL]
~~~
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Services.Editor.CSharp.UnitTests
  Discovered:  Roslyn.Services.Editor.CSharp.UnitTests
  Starting:    Roslyn.Services.Editor.CSharp.UnitTests
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.Suppression.CSharpSuppressionTests+CSharpGlobalSuppressMessageSuppressionTests+UserInfoDiagnosticSuppressionTests.TestFixAllInSolution [SKIP]
      TODO: File a GitHubIssue for test framework unable to handle multiple projects in solution with same file name.
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.RemoveUnnecessaryCast.RemoveUnnecessaryCastTests.DontRemoveNecessaryCastWhichInCollectionInitializer2 [SKIP]
      529787
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.RemoveUnnecessaryCast.RemoveUnnecessaryCastTests.DontRemoveNecessaryCastWhichInCollectionInitializer1 [SKIP]
      529787
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.RemoveUnnecessaryCast.RemoveUnnecessaryCastTests.RemoveUnneededCastInCollectionInitializer [SKIP]
      529787
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesTests.SimplifyGenericTypeName7 [SKIP]
      https://github.com/dotnet/roslyn/issues/9877
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesTests.SimplifyGenericTypeName3 [SKIP]
      https://github.com/dotnet/roslyn/issues/9877
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesTests.TestConflicts [SKIP]
      https://github.com/dotnet/roslyn/issues/9877
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.GenerateDelegateType_ObjectCreationExpression_SimpleLambdaEmpty [SKIP]
      872935
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings.IntroduceVariable.IntroduceVariableTests.TestConstantForFixedBufferInitializer [SKIP]
      552389
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.SymbolId.SymbolKeyTest.C2CAssemblyChanged02 [SKIP]
      530169
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionSetSources.SymbolCompletionProviderTests.EditorBrowsable_Property_BrowsableStateNever [SKIP]
      674611
    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Formatting.Indentation.SmartIndenterTests.AtBeginningOfSpanInNugget [SKIP]
      674611
    Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.RudeEditStatementTests.Lambdas_Update_Signature_CustomModifiers1 [SKIP]
      TODO
      Assert.NotNull() Failure
      Stack Trace:
        F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(316,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__21.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(222,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(208,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(171,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\EditorFeatures\CSharpTest\Diagnostics\AddUsing\AddUsingTests.cs(1977,0): at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.AddUsing.AddUsingTests.<TestAddInsideLambda>d__121.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Roslyn.Services.Editor.CSharp.UnitTests
=== TEST EXECUTION SUMMARY ===
   Roslyn.Services.Editor.CSharp.UnitTests  Total: 8096, Errors: 0, Failed: 1, Skipped: 13, Time: 219.415s
~~~

**Comment by balajikris** [comment]
\Roslyn-Stabilization-Signed-Release\20160601.1\xUnitResults

~~~
Roslyn.Services.Editor.VisualBasic.UnitTests.dll

     Assert.NotNull() Failure
      Stack Trace:
        F:\Builds\5570\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(316,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__21.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5570\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(222,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        F:\Builds\5570\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(208,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5570\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\EditorFeatures\Test\CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(170,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5570\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\EditorFeatures\VisualBasicTest\Diagnostics\GenerateMethod\GenerateMethodTests.vb(416,0): at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Diagnostics.GenerateMethod.GenerateMethodTests.VB$StateMachine_51_TestInTopLevelImplicitClass1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by jasonmalinowski** [comment]
@Pilchie, can we get some traction on this? This has been failing a number of signed builds recently.

**Comment by Pilchie** [comment]
Can you take a look at this?

**Comment by CyrusNajmabadi** [comment]
I've been running these in a loop locally for an hour without any problems.

**Comment by CyrusNajmabadi** [comment]
Closing this out.
