### ISSUE TITLE
C# and VB Emit unit tests are failing locally.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11402]
The emit unittest fail locally but not on Jenkins.

**FUTURE BRANCH**

**Version Used**: 
```
OS: Window 10 Pro ( x64 )
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
```

**Steps to Reproduce**:

1. `msbuild /v:m /m BuildAndTest.proj` 

**Expected Behavior**:
No failures.

**Actual Behavior**:
Similar to #2375

VB Emit Failures
```
    InternalsVisibleToAndStrongNameTests.IVTSigned
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_InaccessibleSymbol2, "C").WithArguments("C", "Friend").WithLocation(2, 26),
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_InaccessibleSymbol2, "C").WithArguments("C", "Friend").WithLocation(2, 26),
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\Test\Utilities\VisualBasic\DiagnosticExtensions.vb(16,0): at Microsoft.CodeAnalysis.VisualBasic.DiagnosticsExtensions.VerifyDiagnostics(VisualBasicCompilation c, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(635,0): at InternalsVisibleToAndStrongNameTests.IVTSigned()

    InternalsVisibleToAndStrongNameTests.IVTSuccessThroughIAssembly
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(799,0): at InternalsVisibleToAndStrongNameTests.IVTSuccessThroughIAssembly()

    InternalsVisibleToAndStrongNameTests.PubKeyFromKeyContainerAttribute
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\Test\Utilities\VisualBasic\DiagnosticExtensions.vb(16,0): at Microsoft.CodeAnalysis.VisualBasic.DiagnosticsExtensions.VerifyDiagnostics(VisualBasicCompilation c, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(128,0): at InternalsVisibleToAndStrongNameTests.PubKeyFromKeyContainerAttribute()

    InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerAttr
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1176,0): at InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(Stream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1227,0): at InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerAttr()

    InternalsVisibleToAndStrongNameTests.IVTDeferredSuccess
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(702,0): at InternalsVisibleToAndStrongNameTests.IVTDeferredSuccess()

    InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatch
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\Test\Utilities\VisualBasic\DiagnosticExtensions.vb(16,0): at Microsoft.CodeAnalysis.VisualBasic.DiagnosticsExtensions.VerifyDiagnostics(VisualBasicCompilation c, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(753,0): at InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatch()
 
   InternalsVisibleToAndStrongNameTests.IVTDeferredFailSignMismatch
      
      MISSING ERROR MESSAGES:
      BC36958: Friend access was granted by 'Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null', but the strong name signing state of the output assembly does not match that of the granting assembly.
      UNEXPECTED ERROR MESSAGES:
      BC36957: Friend access was granted by 'Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null', but the public key of the output assembly does not match that specified by the attribute in the granting assembly.
      BC36981: Error extracting public key from container 'roslynTestContainer': Keyset does not exist (Exception from HRESULT: 0x80090016)
      
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb(885,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.AssertTheseDiagnostics(ImmutableArray`1 errors, String expectedText, Boolean suppressInfos)
        src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb(841,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.AssertTheseDiagnostics(ImmutableArray`1 errors, XElement errs, Boolean suppressInfos)
        src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb(819,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.AssertTheseDiagnostics(Compilation compilation, XElement errs, Boolean suppressInfos)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(734,0): at InternalsVisibleToAndStrongNameTests.IVTDeferredFailSignMismatch()



    InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1176,0): at InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(Stream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1247,0): at InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine()

   InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine_1
      
      Expected:
      Actual:
          Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>     Diagnostic(ERRID.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1176,0): at InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(Stream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\VisualBasic\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.vb(1269,0): at InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine_1()

    InternalsVisibleToAndStrongNameTests.BadInputStream
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        src\Compilers\VisualBasic\Test\Emit\Attributes\EmitTestStrongNameProvider.vb(59,0): at InternalsVisibleToAndStrongNameTests.BadInputStream()
```

C# Emit Failures
```
    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTSuccessThroughIAssembly
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(903,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTSuccessThroughIAssembly()

    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.KeyContainerAttributeOptionConflict
      
      Expected:
                      Diagnostic(ErrorCode.WRN_CmdOptionConflictsSource).WithArguments("CryptoKeyContainer", "System.Reflection.AssemblyKeyNameAttribute")
      Actual:
                      // error CS7028: Error signing output with public key from container 'RoslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("RoslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1),
                      // warning CS1616: Option 'CryptoKeyContainer' overrides attribute 'System.Reflection.AssemblyKeyNameAttribute' given in a source file or added module
                      Diagnostic(ErrorCode.WRN_CmdOptionConflictsSource).WithArguments("CryptoKeyContainer", "System.Reflection.AssemblyKeyNameAttribute").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("RoslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1),
      ++>                 Diagnostic(ErrorCode.WRN_CmdOptionConflictsSource).WithArguments("CryptoKeyContainer", "System.Reflection.AssemblyKeyNameAttribute").WithLocation(1, 1)
      -->                 Diagnostic(ErrorCode.WRN_CmdOptionConflictsSource).WithArguments("CryptoKeyContainer", "System.Reflection.AssemblyKeyNameAttribute")
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(358,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.KeyContainerAttributeOptionConflict()

    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatch
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(876,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatch()

    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredSuccess
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(820,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredSuccess()

    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine_1
      
      Expected:
      Actual:
                      // error CS7028: Error signing output with public key from container 'roslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1076,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(MemoryStream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1180,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine_1()


    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.PubKeyFromKeyContainerAttribute
      
      Expected:
      Actual:
                      // error CS7028: Error signing output with public key from container 'roslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(192,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.PubKeyFromKeyContainerAttribute()


    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerAttr
      
      Expected:
      Actual:
                      // error CS7028: Error signing output with public key from container 'roslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1076,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(MemoryStream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1108,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerAttr()


    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatchIAssembly
      
      Expected:
                      Diagnostic(ErrorCode.ERR_FriendRefNotEqualToThis).WithArguments("Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce65828c82a341f2")
      Actual:
                      // error CS7028: Error signing output with public key from container 'roslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1),
                      // error CS0281: Friend access was granted by 'Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce65828c82a341f2', but the public key of the output assembly does not match that specified by the attribute in the granting assembly.
                      Diagnostic(ErrorCode.ERR_FriendRefNotEqualToThis).WithArguments("Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce65828c82a341f2").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1),
      ++>                 Diagnostic(ErrorCode.ERR_FriendRefNotEqualToThis).WithArguments("Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce65828c82a341f2").WithLocation(1, 1)
      -->                 Diagnostic(ErrorCode.ERR_FriendRefNotEqualToThis).WithArguments("Paul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce65828c82a341f2")
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(933,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailKeyMismatchIAssembly()



    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTSigned
      Assert.Empty() Failure
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(762,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTSigned()
    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.BadInputStream
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\EmitTestStrongNameProvider.cs(60,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.BadInputStream()
    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine
      
      Expected:
      Actual:
                      // error CS7028: Error signing output with public key from container 'roslynTestContainer' -- Keyset does not exist (Exception from HRESULT: 0x80090016)
                      Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Diff:
      ++>                 Diagnostic(ErrorCode.ERR_PublicKeyContainerFailure).WithArguments("roslynTestContainer", "Keyset does not exist (Exception from HRESULT: 0x80090016)").WithLocation(1, 1)
      Expected: True
      Actual:   False
      Stack Trace:
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
        src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1076,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.ConfirmModuleAttributePresentAndAddingToAssemblyResultsInSignedOutput(MemoryStream moduleContents, AttributeDescription expectedModuleAttr)
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(1162,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerCmdLine()
   Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailSignMismatch
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        src\Compilers\CSharp\Test\Emit\Attributes\InternalsVisibleToAndStrongNameTests.cs(847,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.IVTDeferredFailSignMismatch()
```

**Comment by jmarolf** [comment]
@AdamSpeight2008 can you add the failures so we can investigate this? which emit tests failed?

**Comment by AdamSpeight2008** [comment]
@jmarolf Will do. I need to dig through the logs again.

**Comment by jmarolf** [comment]
@AdamSpeight2008 thanks! :)

**Comment by AdamSpeight2008** [comment]
@jmarolf Also just add that it is the `Future` branch. (see #11335)

**Comment by jmarolf** [comment]
@AdamSpeight2008 I assumed as much

**Comment by jaredpar** [comment]
This has been inactive for a while and these suites are consistently passing on a number of machines.  Closing for now.  Please comment if still an issue.
