### ISSUE TITLE
BasicGenerateTypeDialog VSI test failure

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#11429]
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/1344/consoleFull#-124009285561aefe2b-268e-4e71-8c03-11b4c0acbfbc

Issue 1: Individual TAO Test Failure
Failing integration tests:
BasicGenerateTypeDialog.xml

```
16:28:55  Scenario: Generate Type Dialog VB-SameProject
16:28:55    Executing action [5/18/2016 11:24:45 PM] AddProject
16:28:55    Executing action [5/18/2016 11:24:55 PM] AddProject
16:28:55    Executing action [5/18/2016 11:25:05 PM] AddItem
16:28:55    Executing action [5/18/2016 11:25:06 PM] OpenFile
16:28:55 DEBUG: executed DTE command File.OpenFile.
16:28:55 DEBUG: start polling for code window
16:28:55 DEBUG: polling complete
16:28:55    Executing action [5/18/2016 11:25:06 PM] SetEditorText
16:28:55    Executing action [5/18/2016 11:25:06 PM] PlaceCursor
16:28:55    Executing action [5/18/2016 11:25:06 PM] GenerateTypeDialog
16:28:55 ComboBox 'AccessList' value set to 'Public'
16:28:55 ComboBox 'KindList' value set to 'Structure'
16:28:55 Radio button 'CreateNewFileRadioButton' selected
16:28:55 TextBox value set to GenerateTypeTest2
16:28:55 Button OkButton clicked
16:28:55    Executing action [5/18/2016 11:25:13 PM] OpenFile
16:28:55 DEBUG: executed DTE command File.OpenFile.
16:28:55 DEBUG: start polling for code window
16:28:55 DEBUG: polling complete
16:28:55    Executing action [5/18/2016 11:25:13 PM] VerifyText
16:28:55    Executing action [5/18/2016 11:25:13 PM] OpenFile
16:28:55 DEBUG: executed DTE command File.OpenFile.
16:28:55 DEBUG: start polling for code window
16:28:55 DEBUG: polling complete
16:28:55    Executing action [5/18/2016 11:25:13 PM] VerifyText
16:28:55 --------------------------------
16:28:55 System.Exception: Actual and expected items don't match:
16:28:55 Expected: Class C
16:28:55     Sub Method()
16:28:55         Dim _A As A
16:28:55     End Sub
16:28:55 End Class
16:28:55 
16:28:55 Actual: Class C
16:28:55     Sub Method() 
16:28:55         Dim _A As A
16:28:55     End Sub
16:28:55 End Class
16:28:55 
16:28:55 
16:28:55    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\roslyn-intern---1b30020b\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
16:28:55    at Roslyn.VSHosting.Test.VerifyTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\roslyn-intern---1b30020b\Closed\Hosting\Test\Actions\VisualStudio\VerifyTextAction.cs:line 21
16:28:55    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
```

**Comment by Pilchie** [comment]
Can you take a look at this?  It's been failing quite a few rolling and PR builds lately.

**Comment by Pilchie** [comment]
Hit this again on http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/285/

**Comment by mavasani** [comment]
+1
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/288/testReport/

**Comment by mavasani** [comment]
And failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/427/

**Comment by CyrusNajmabadi** [comment]
None of the links in this bug actually lead to any jenkins failures with logs.  I don't know what i can do with this bug.
