### ISSUE TITLE
Crash after starting WebDeploy

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#11456]
**Version Used**: VS2015.2

**Steps to Reproduce** (not reproduceable):
1. Develop a web application in Debug|AnyCPU, finish a feature, test it, git commit
2. Open Web Deploy for test system; Release|AnyCPU
3. Klick deploy button
4. Visual Studio shows "Build started..."
5. Visual Studio stopped working (right before the automatic opening of the output window to show build progress)

**Expected Behavior**:
Visual Studio should never crash

**Actual Behavior**:
This time it did

```
Message: System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeInCache(MetadataTypeName& emittedName)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(MetadataTypeName& emittedName, ConsList`1 visitedAssemblies, Boolean digThroughForwardedTypes)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(AssemblySymbol assembly, MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt, Boolean includeReferences, Boolean isWellKnownType, DiagnosticBag warnings)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetWellKnownType(WellKnownType type)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.IsEqualOrDerivedFromWellKnownClass(TypeSymbol type, WellKnownType wellKnownType, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.CheckAttributeTypeViability(Symbol symbol, Boolean diagnose, DiagnosticInfo& diagInfo)
   at Microsoft.CodeAnalysis.CSharp.Binder.IsSingleViableAttributeType(LookupResult result, Symbol& symbol)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupAttributeType(LookupResult result, NamespaceOrTypeSymbol qualifierOpt, String name, Int32 arity, ConsList`1 basesBeingResolved, LookupOptions options, Boolean diagnose, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(IdentifierNameSyntax node, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics, NamespaceOrTypeSymbol qualifierOpt, Boolean isNameofArgument, ArrayBuilder`1 symbols)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleNamespaceOrTypeOrAliasSymbol(SimpleNameSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics, NamespaceOrTypeSymbol qualifierOpt)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindQualifiedName(ExpressionSyntax leftName, SimpleNameSyntax rightName, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindType(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeTypes(ImmutableArray`1 binders, ImmutableArray`1 attributesToBind, Symbol ownerSymbol, NamedTypeSymbol[] boundAttributeTypes, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(OneOrMany`1 attributesSyntaxLists, CustomAttributesBag`1& lazyCustomAttributesBag, AttributeLocation symbolPart, Boolean earlyDecodingOnly)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetSourceDecodedWellKnownAttributeData()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_AssemblyVersionAttributeSetting()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeIdentity()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_Identity()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.HasMissingReferences(Compilation compilation, IReadOnlyList`1 metadataReferences)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<FinalizeCompilationAsync>d__29.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker+<FinalizeCompilationAsync>d__29.MoveNext()
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.CodeAnalysis.MetadataTypeName+Key, Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TryGetValue(Key, System.__Canon ByRef)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeInCache(Microsoft.CodeAnalysis.MetadataTypeName ByRef)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(Microsoft.CodeAnalysis.MetadataTypeName ByRef, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol>, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol, Microsoft.CodeAnalysis.MetadataTypeName ByRef, Microsoft.CodeAnalysis.AssemblyIdentity)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(Microsoft.CodeAnalysis.MetadataTypeName ByRef, Microsoft.CodeAnalysis.AssemblyIdentity, Boolean, Boolean, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTypeByMetadataName(System.String, Boolean, Boolean, Boolean, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetWellKnownType(Microsoft.CodeAnalysis.WellKnownType)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.IsEqualOrDerivedFromWellKnownClass(Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.WellKnownType, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DiagnosticInfo> ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.CheckAttributeTypeViability(Microsoft.CodeAnalysis.CSharp.Symbol, Boolean, Microsoft.CodeAnalysis.DiagnosticInfo ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.IsSingleViableAttributeType(Microsoft.CodeAnalysis.CSharp.LookupResult, Microsoft.CodeAnalysis.CSharp.Symbol ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupAttributeType(Microsoft.CodeAnalysis.CSharp.LookupResult, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol, System.String, Int32, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>, Microsoft.CodeAnalysis.CSharp.LookupOptions, Boolean, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DiagnosticInfo> ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>, Boolean, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol, Boolean, Microsoft.CodeAnalysis.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.Symbol>)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>, Boolean, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindQualifiedName(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindType(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbol>)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeTypes(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Binder>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax>, Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol[], Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany`1<Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>>, Microsoft.CodeAnalysis.CustomAttributesBag`1<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetSourceDecodedWellKnownAttributeData()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_AssemblyVersionAttributeSetting()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeIdentity()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_Identity()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ResolveMetadataReferences(System.__Canon, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<ReferencedAssemblyIdentity<System.__Canon,System.__Canon>>>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.MetadataReference> ByRef, System.Collections.Generic.IDictionary`2<Roslyn.Utilities.ValueTuple`2<System.String,System.String>,Microsoft.CodeAnalysis.MetadataReference> ByRef, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.MetadataReference> ByRef, System.Collections.Immutable.ImmutableArray`1<AssemblyData<System.__Canon,System.__Canon>> ByRef, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.PEModule> ByRef, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation+ReferenceManager.CreateAndSetSourceAssemblyFullBind(Microsoft.CodeAnalysis.CSharp.CSharpCompilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation+ReferenceManager.CreateSourceAssemblyForCompilation(Microsoft.CodeAnalysis.CSharp.CSharpCompilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(Microsoft.CodeAnalysis.MetadataReference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(Microsoft.CodeAnalysis.MetadataReference)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker.HasMissingReferences(Microsoft.CodeAnalysis.Compilation, System.Collections.Generic.IReadOnlyList`1<Microsoft.CodeAnalysis.MetadataReference>)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker+<FinalizeCompilationAsync>d__29.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.Solution+CompilationTracker+<FinalizeCompilationAsync>d__29, Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<FinalizeCompilationAsync>d__29 ByRef)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker.FinalizeCompilationAsync(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Compilation, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker.BuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker+<GetOrBuildCompilationInfoAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.Solution+CompilationTracker+<GetOrBuildCompilationInfoAsync>d__21, Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetOrBuildCompilationInfoAsync>d__21 ByRef)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker.GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Solution+CompilationTracker.GetCompilationAsync(Microsoft.CodeAnalysis.Solution, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Solution.GetCompilationAsync(Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Host.BackgroundCompiler+<>c__DisplayClass14_0.<BuildCompilationsAsync>b__2(Microsoft.CodeAnalysis.Project)
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.CodeAnalysis.Host.BackgroundCompiler.BuildCompilationsAsync(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.ProjectId, System.Collections.Generic.ISet`1<Microsoft.CodeAnalysis.ProjectId>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Host.BackgroundCompiler+<>c__DisplayClass13_0.<BuildCompilationsAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by gafter** [comment]
Sounds like a bug in `System.Collections.Concurrent.ConcurrentDictionary'2.`??
