### ISSUE TITLE
Compiler server unit tests are failing with "Compiler server did not exit in time"

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#11505]
This is affecting signed builds a lot, please investigate. See Roslyn-Master-Signed-Release queue - 20160523.2 for an e.g.

~~~
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Compilers.CompilerServer.UnitTests
  Discovered:  Roslyn.Compilers.CompilerServer.UnitTests
  Starting:    Roslyn.Compilers.CompilerServer.UnitTests
      Compiler server did not exit in time
      Expected: True
      Actual:   False
      Stack Trace:
        F:\Builds\5570\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(1324,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<ServerRespectsAppConfig>d__68.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Roslyn.Compilers.CompilerServer.UnitTests
=== TEST EXECUTION SUMMARY ===
   Roslyn.Compilers.CompilerServer.UnitTests  Total: 94, Errors: 0, Failed: 1, Skipped: 0, Time: 296.005s
~~~

**Comment by jaredpar** [comment]
This should be addressed by #11514
