### ISSUE TITLE
Stack traces for types compiled with DebugInformationFormat.PortablePdb are missing source line information

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#11535]
**Version Used**: 1.3.0-beta1-20160429-01

**Steps to Reproduce**:
[Mvc](https://github.com/aspnet/Mvc) switched to using `DebugInformationFormat.PortablePdb` recently for compiling generated view code. Stack traces for these types don't contain any line information. For instance, here's what an exception stack trace looks like when compiled with `DebugInformationFormat.Pdb`:

```C#
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__21.MoveNext() in /Views/Home/Index.cshtml:line 4
```

And with `DebugInformationFormat.PortablePdb`:
```C#
at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__21.MoveNext()
```

Similarly missing line information from `Environment.StackTrace`:
 ```
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNetCore._Views_Home_Index_cshtml.ExecuteAsync() <---- MISSING
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) in D:\work\katana\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\RazorView.cs:line 158 <-- OK
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext() in D:\work\katana\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\RazorView.cs:line 144
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext() in D:\work\katana\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\RazorView.cs:line 101
```   

Any guidance on what me might be doing wrong here? The code that emits the assembly: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L114-L117

**Comment by mikem8361** [comment]
This issue tracked portable pdb support for Exception.StackTrace. https://github.com/dotnet/coreclr/issues/3906.  It has been implemented and the issue closed.

**Comment by pranavkm** [comment]
Thanks @mikem8361 . We haven't picked up RTM CoreFx packages yet. I'll give that a try.
