### ISSUE TITLE
VB unit test failure: ConvertReferenceTypeToIntrinsicValueType

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#11570]
A VB unit test in the master branch is failing on my machine. I'd guess it's a locale thing: my settings expect dates in **dd/MM**/yyyy format
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.ConversionsTests.ConvertReferenceTypeToIntrinsicValueType
    Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
    Execution failed for assembly 'C:\Users\Lorcan\AppData\Local\Temp\'.
    Exception: System.InvalidCastException: Conversion from string "5/23/2016" to type 'Date' is not valid.
        at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
        at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(Object Value)
        at Module1.TestDate(IComparable value3)
        at Module1.Main()
    ---- System.InvalidCastException : Conversion from string "5/23/2016" to type 'Date' is not valid.
    Stack Trace:
    src\Test\Utilities\Desktop\HostedRuntimeEnvironment.cs(250,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, Int32 expectedOutputLength, String& processOutput)
    src\Test\Utilities\Desktop\HostedRuntimeEnvironment.cs(257,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
    src\Test\Utilities\Desktop\CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
    src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
    src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
    src\Compilers\Test\Utilities\VisualBasic\BasicTestBase.vb(77,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.BasicTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
    src\Compilers\VisualBasic\Test\Semantic\Semantics\Conversions.vb(4855,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.ConversionsTests.ConvertReferenceTypeToIntrinsicValueType()
    ----- Inner Stack Trace -----
        at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
        at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(Object Value)
        at Module1.TestDate(IComparable value3)
        at Module1.Main()
```

**Comment by lorcanmooney** [comment]
Fixed by #11635
