### ISSUE TITLE
InvalidCastException when using an invalid MetadataReference

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#11581]
I'm experimenting with netmodules and when I try to reference netmodule from a stream, I get `InvalidCastException` at `Compilation.Emit()`.

Looking at the source, [only `MetadataReference.CreateFromFile()` supports netmodule references](https://github.com/dotnet/roslyn/blob/5b77e6d/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L227-L245). That's fine, but the other `Create*` methods (like [`CreateFromStream()`](https://github.com/dotnet/roslyn/blob/5b77e6d/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L189-L199)) just silently assume the reference is an assembly reference, even when passed `MetadataReferenceProperties.Module`, causing that `InvalidCastException`. I think the other `Create*` methods should throw when an attempt at creating a netmodule reference through them is made.

**Version Used**: 2.0.0-beta1

**Steps to Reproduce**:

Execute the following code:

``` c#
var module = CSharpCompilation.Create(null)
    .WithOptions(new CSharpCompilationOptions(OutputKind.NetModule, moduleName: "m"))
    .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location))
    .AddSyntaxTrees(CSharpSyntaxTree.ParseText("class C {}"));

var moduleStream = new MemoryStream();

var emitResult = module.Emit(moduleStream);

moduleStream.Position = 0;

var assembly = CSharpCompilation.Create("a")
    .WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
    .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location))
    .AddReferences(
        MetadataReference.CreateFromStream(
            moduleStream, MetadataReferenceProperties.Module));

emitResult = assembly.Emit("a.dll");
```

**Expected Behavior**:

`MetadataReference.CreateFromStream(moduleStream, MetadataReferenceProperties.Module)` throws an exception, probably `ArgumentException`.

**Actual Behavior**:

`assembly.Emit("a.dll")` throws:

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.AssemblyMetadata' to type 'Microsoft.CodeAnalysis.ModuleMetadata'.
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FileSystemExtensions.Emit(Compilation compilation, String outputPath, String pdbPath, String xmlDocPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpFileSystemExtensions.Emit(CSharpCompilation compilation, String outputPath, String pdbPath, String xmlDocumentationPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
   at Program.Main(String[] args)
```

**Comment by jcouv** [comment]
I'm not sure that's desirable. Most of the compiler APIs are lazy. The stream is read once it is used.

**Comment by tmat** [comment]
As @jcouv  says CreateFromStream doesn't read the content of the stream and thus doesn't know if it's a module or not. If it could know we wouldn't ask the caller to specify it via the properties. That said, the ReferenceManager should not throw InvalidCastException but report a diagnostic instead.
