### ISSUE TITLE
Crash while debugging Minidump

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#11623]
**Version Used**: Roslyn-Master-Signed, 1.3.0.60526

**Steps to Reproduce**: I had opened Roslyn.sln, then opened a dump file, and started debugging the dump file. It crashed a few minutes into the debug session.

**Stack:**

```
System.ArgumentException: An element with the same key but a different value already exists. Key: Microsoft.CodeAnalysis.EditAndContinue.RudeEditDiagnosticAnalyzer
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<MergeProjectDiagnosticAnalyzerDiagnosticsAsync>d__10.MoveNext() in F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 294
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDiagnosticsAsync>d__6.MoveNext() in F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 162
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDiagnosticsAsync>d__7.MoveNext() in F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 185
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<GetProjectAnalysisDataAsync>d__4.MoveNext() in F:\Builds\5569\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 115
```

**Expected Behavior**: It doesn't crash.

**Comment by jasonmalinowski** [comment]
An internal dump file is available under <team share>\jasonmal\Dumps\Roslyn\11623.

**Comment by ManishJayaswal** [comment]
The message seems very familiar. I bet I have seen it in one of the Watsons we already have.

**Comment by ManishJayaswal** [comment]
Haven't heard many complaints about this so moving this to 2.1
