### ISSUE TITLE
Crash formatting parenthesized lambda expression

### ISSUE THREAD

**Issue by Caraul** [dotnet/roslyn#11642]
**Version Used**: 
1.2.2

**Steps to Reproduce**:
```
    var syntaxNode =
        ParenthesizedExpression(
            ParenthesizedLambdaExpression(ParameterList(), Block()));
    var result = Formatter.Format(syntaxNode, new AdhocWorkspace());
```
**Expected Behavior**:
Formatter.Format succeeds returning formatted node

**Actual Behavior**:
Microsoft.CodeAnalysis.CSharp.Formatting.BaseFormattingRule.SomeParentHasMissingCloseBrace fails with NullReferenceException

**Comment by Pilchie** [comment]
@balajikris can you take a look?

**Comment by balajikris** [comment]
@Caraul : could you please share the full source for this program that compiles? I'm curious to see how the syntaxNode looks like that can cause this exception in the formatter api. 
I pasted this code in a CodeRefactoring template, but i can't seem to find definitions for many methods used here and hence couldn't compile the code.

**Comment by Caraul** [comment]
Of course no problem:

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Formatting;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TestParenthesizedExpression
{
    internal class Program
    {
        internal static void Main()
        {
            var syntaxNode =
                ParenthesizedExpression(
                    ParenthesizedLambdaExpression(ParameterList(), Block()));
            var result = Formatter.Format(syntaxNode, new AdhocWorkspace());
        }
    }
}
```
It should be a very simple expression a-la (()=>{})

**Comment by balajikris** [comment]
@Caraul : thanks, expected I was missing a using statement or two, and Add using refactoring didn't suggest the `using static Ms.Ca.CSharp.SyntaxFactory`.. hmm, will file a separate bug for that.

**Comment by balajikris** [comment]
stack for the null ref:

~~~
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node) in D:\repos\roslyn-internal\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 160
   at Microsoft.CodeAnalysis.CSharp.Formatting.BaseFormattingRule.SomeParentHasMissingCloseBrace(SyntaxNode node) in D:\repos\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Formatting\Rules\BaseFormattingRule.cs:line 260
   at Microsoft.CodeAnalysis.CSharp.Formatting.BaseFormattingRule.AddBraceSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken) in D:\repos\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Formatting\Rules\BaseFormattingRule.cs:line 228
   at Microsoft.CodeAnalysis.CSharp.Formatting.SuppressFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Formatting\Rules\SuppressFormattingRule.cs:line 23
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.Formatting.Rules.AbstractFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\AbstractFormattingRule.cs:line 16
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.Formatting.Rules.AbstractFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\AbstractFormattingRule.cs:line 16
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.Formatting.Rules.AbstractFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\AbstractFormattingRule.cs:line 16
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.CSharp.Formatting.ElasticTriviaFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Formatting\Rules\ElasticTriviaFormattingRule.cs:line 26
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.Formatting.Rules.AbstractFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\AbstractFormattingRule.cs:line 16
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs:line 28
   at Microsoft.CodeAnalysis.Formatting.Rules.AbstractFormattingRule.AddSuppressOperations(List`1 list, SyntaxNode node, SyntaxToken lastToken, OptionSet optionSet, NextAction`1 nextOperation) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\AbstractFormattingRule.cs:line 16
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.<.ctor>b__8_0(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 40
   at Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Engine\ChainedFormattingRules.cs:line 105
   at Microsoft.CodeAnalysis.Formatting.Rules.NextAction`1.Invoke(List`1 arguments) in D:\repos\roslyn-internal\Open\src\Workspaces\Core\Portable\Formatting\Rules\NextAction`1.cs...
~~~

**Comment by balajikris** [comment]
**Notes:**
simply checking for null at `SomeParentHasMissingCloseBrace` fixes the issue. The code expects a fully formed node that has a compilation unit, which is what a roslyn document would have, but it is also in a formatter public api path, which can be given _'a'_ syntax node. It seems like this path was added during one of the updates as a part of some bug fixing. Will dive into git history and add tests as appropriate.

```C#
private bool SomeParentHasMissingCloseBrace(SyntaxNode node)
        {
            while (node != null && node.Kind() != SyntaxKind.CompilationUnit)
            {
```

**Comment by balajikris** [comment]
**Notes:** 

1. Bug did not meet ask mode bar per IDE-triage, since it has no user impact on VS. The scenario is formatting an arbitrary node that is not associated with a syntax tree. 
2. 2.0 (preview 3) is in ask mode, as is 1.3 milestone. So, I have moved the bug to 2.0 (preview 4) milestone and merging the fix in master branch.

**Comment by balajikris** [comment]
@Caraul : thank you for filing the bug. It is now fixed in `master`.

**Comment by Caraul** [comment]
:+1:
