### ISSUE TITLE
Incorrect Instance Count after debugging in BasicDebuggerIntellisense

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#11699]
**Version Used**: 
ML 25401.01
**Steps to Reproduce**:
Run BasicDebuggerIntellisense.xml via standalone. Contact me for a machine

Failure occurs during the 'Locals from previous block are not visible in the current block' scenario. It looks like there is a timing issue due to the closeTarget action right before the verifyInstanceCount action. Test did not pass on reset.

Scenario: Locals from previous block are not visible in the current block
    Executing action [6/1/2016 11:38:34 AM] ImmediateWindow
    Executing action [6/1/2016 11:38:34 AM] Debug
             [6/1/2016 11:38:34 AM] Continue
             [6/1/2016 11:38:34 AM] Try Wait For Break Mode
    Executing action [6/1/2016 11:38:34 AM] ImmediateWindow
    Executing action [6/1/2016 11:38:35 AM] WaitForCompletionSet
    Executing action [6/1/2016 11:38:40 AM] VerifyCompletionList
    Executing action [6/1/2016 11:38:40 AM] CloseTarget
##     Executing action [6/1/2016 11:38:41 AM] VerifyInstanceCount

Tao.Engine.Exceptions.UnexpectedResultException: Expected:[1]
Actual:[2]

Server stack trace: 
   at Roslyn.Hosting.Test.VerifyInstanceCountAction.Fail(Int32 expected, Int32 actual)
   at Roslyn.Hosting.Test.VerifyInstanceCountAction.CheckCount(Int32 expected, Int32 actual, ComparisonKind comparison)
   at Roslyn.Hosting.Test.VerifyInstanceCountAction.CheckType(IEnumerable`1 groups, KnownType typeName, Int32 count, ComparisonKind comparison, Lazy`1 types)
   at Roslyn.Hosting.Test.VerifyInstanceCountAction.Execute()
   at Roslyn.Hosting.Test.SerializedData.ExecuteShim()
   at Roslyn.VSHosting.Test.InProcessAPI.InvokeInVS(Action action)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Roslyn.VSHosting.Test.InProcessAPI.InvokeInVS(Action action)
   at Roslyn.Hosting.Test.SharedAction.Execute(TaoEngine engine)
   at Tao.Engine.DebuggableActionExecutor.Execute()
#    at Tao.Engine.DefaultActionExecutor.Execute()

**Comment by mavasani** [comment]
I am seeing this with my local VSI testing on Dev15 preview3 as well - tagging @ManishJayaswal who said @tannergooding will probably investigate this failure. I am going to disable this VSI test for the effort of moving Jenkins to Dev15

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-internal/pull/1198 disables this test, marking this as Urgency-Now. NOTE: the test currently passes on Dev14 (Jenkins), so the work here is to verify it passes on a standalone Dev15 install and then unskip it so that when we move Jenkins to Dev15, the test doesn't fail.

**Comment by ManishJayaswal** [comment]
Closing this as we are working to re-enable all integration tests which have been on the floor for many months.
