### ISSUE TITLE
Question/Issue : "NullReferenceException" when using interactive C#

### ISSUE THREAD

**Issue by sherry-ummen** [dotnet/roslyn#11711]
**Visual Studio 2015 Update 2**: 

**Steps to Reproduce**:

1.#r use to load one of our organization dll (sorry cannot share it) 

**Expected Behavior**:
Wanted to call a method from the loaded DLL

**Actual Behavior**:
I get this exception:

`Unexpected error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonTypeNameFormatter.FormatNonGenericTypeName(TypeInfo typeInfo, CommonTypeNameFormatterOptions options)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonTypeNameFormatter.FormatTypeName(Type type, CommonTypeNameFormatterOptions options)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpTypeNameFormatter.FormatTypeName(Type type, CommonTypeNameFormatterOptions options)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatException(Exception e)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpObjectFormatter.FormatException(Exception e)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<>c__DisplayClass42_0.<<ExecuteOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteOnUIThread>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteAsync>d__30.MoveNext()
> `

Interesting fact is that if I create a new class library just for testing then I am able to load and run the methods in that DLL but this dll (organization) which is a .net Assembly I am not able to get a method called.

I could help in debugging the problem if someone is wiling to help me. Thanks
**Please close it if you seem it to be irrelevant **

**Comment by tmat** [comment]
Looks like https://github.com/dotnet/roslyn/issues/11284.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/11296
