### ISSUE TITLE
Support IntPtr conversions in the method argument rewriter.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#11751]
IntPtr conversion can stay in the bound tree past lowering in a case where a COM method is invoked in an Expression Tree lambda.

A typical situation where this could happen is when a COM method is tested in a mock framework that is Expression Tree based.

If such conversion is seen by the call argument rewriter a crash/watson would result when code is compiled.

Short repro:
```C#

using System;
using System.Linq.Expressions;
using System.Runtime.InteropServices;

unsafe class Program
{

    static void Main(string[] args)
    {
        IntPtr y = new IntPtr();
                
        IAaa i = null;

        Expression<Action> e = () =>  i.Test((ulong)y, null);
    }
}

[ComImport]
[Guid(""A88A175D-2448-447A-B786-64682CBEF156"")]
public interface IAaa
{
    void Test(ulong y, object z);
}
```

causes a crash like:
CLR: Managed code called FailFast, saying "System.InvalidOperationException: Unexpected value 'IntPtr' of type 'Microsoft.CodeAnalysis.CSharp.ConversionKind'
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.IsSafeForReordering(BoundExpression expression, RefKind kind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildStoresToTemps(Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1 argumentRefKinds, ImmutableArray`1 rewrittenArguments, BoundExpression[] arguments, ArrayBuilder`1 refKinds, ArrayBuilder`1 storesToTemps)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArguments(CSharpSyntaxNode syntax, ImmutableArray`1 rewrittenArguments, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1& argumentRefKindsOpt, ImmutableArray`1& temps, Boolean invokedAsExtensionMethod, ThreeState enableCallerInfo)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeCall(CSharpSyntaxNode syntax, BoundExpression rewrittenReceiver, MethodSymbol method, ImmutableArray`1 rewrittenArguments, ImmutableArray`1 argumentRefKindsOpt, Boolean expanded, Boolean invokedAsExtensionMethod, ImmutableArray`1 argsToParamsOpt, LookupResultKind resultKind, TypeSymbol type, BoundCall nodeOpt)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitCall(BoundCall node)

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/11752
