### ISSUE TITLE
'ExtractMethodCodeRefactoringProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11802]
Tried to extract a method in C# code with memory hog mode 500, the code got extracted, but the option to provide friendly name wasn't offered. Then I noticed the notification quoted in the title.

**Comment by jasonmalinowski** [comment]
@jmarolf is there a way we can make this actionable?

**Comment by Pilchie** [comment]
@AlekseyTs Do you have any more information that might help us track this down?  What you were extracting, etc?

**Comment by rbeurskens** [comment]
Not sure it will help, but it would not harm , I guess: (stack trace from the same error in VS2017)
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.VariablesDeclaredWalker.NoteDeclaredPatternVariables(BoundPattern pattern)
   at Microsoft.CodeAnalysis.CSharp.VariablesDeclaredWalker.VisitPattern(BoundExpression expression,BoundPattern pattern)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitPatternSwitchBlock(BoundPatternSwitchStatement node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitPatternSwitchStatement(BoundPatternSwitchStatement node)
   at Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitPatternSwitchStatement(BoundPatternSwitchStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundPatternSwitchStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractRegionControlFlowPass.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitStatement(BoundStatement statement)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitStatements(ImmutableArray`1 statements)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractRegionControlFlowPass.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Analyze(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.VariablesDeclaredWalker.Analyze(CSharpCompilation compilation,Symbol member,BoundNode node,BoundNode firstInRegion,BoundNode lastInRegion)
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_VariablesDeclared()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
