### ISSUE TITLE
CSharpEditAndContinue.xml is flaky

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#11846]
Failing Build: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/80/

Many failures of the form:

> MESSAGE:
Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))
+++++++++++++++++++
STACK TRACE:
at EnvDTE._DTE.get_ActiveWindow() at Tao.VS.VisualStudioAction.ExecuteCommand(String commandName, String argument) in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\Test\Actions\VisualStudio\VisualStudioAction.cs:line 100 at Roslyn.VSHosting.Test.VerifyErrorListAction.BeforeExecute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyErrorListAction.cs:line 56 at Tao.Engine.DebuggableActionExecutor.Initialize() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 175 at Tao.Engine.DefaultActionExecutor.Initialize() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 22

And 

> MESSAGE:
Exception has been thrown by the target of an invocation.
+++++++++++++++++++
STACK TRACE:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Tao.Engine.Utilities.MethodCaller.CallMethod[T](T objectWithMethods, XElement xmlMethod) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 85 at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, IEnumerable`1 xmlList) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 37 at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, XElement xml) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 30 at Tao.Engine.DebuggableActionExecutor.CallMethods(TaoEngine engine, TaoAction action) in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 183 at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 142

**Comment by tmat** [comment]
Seems like a bug in VS DTE implementation. Not sure what can we do about this. @DustinCampbell any ideas? Who owns this stuff?

**Comment by DustinCampbell** [comment]
not me. :smile: cc @jasonmalinowski, who also doesn't own it.

Fixing integration tests is owned by the team who owns the test. It looks to me like an RPC call was rejected, which could happen for any number of reasons. It'll need to be investigated, debugged and fixed.

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure Where are the build and test artifacts for the failing job?

**Comment by tmat** [comment]
I fixed the artifacts archiving, so next time this shows up we should have more actionable info.

**Comment by ManishJayaswal** [comment]
closing this issue as this is not actionable.
