### ISSUE TITLE
XML Literals attribute names.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#11925]
``` xml
-<test time="0.1291459" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.OptionalArgumentTests_ImplicitDefaultValue.TestCallerFilePath1" result="Fail" method="TestCallerFilePath1" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.OptionalArgumentTests_ImplicitDefaultValue">


-<failure exception-type="Microsoft.CodeAnalysis.Test.Utilities.ExecutionException">


-<message>

-<![CDATA[Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : \r\nExecution failed for assembly 'C:\Users\Adam\AppData\Local\Temp\'.\r\nExpected:  1: 'C:\filename'\r\n2: 'a\b\..\c\d'\r\n3: '*'\r\n4: '       '\r\n\r\nActual:   1: ''\r\n2: ''\r\n3: ''\r\n4: ''\r\n\r\n]]>
</message>


-<stack-trace>

-<![CDATA[   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput) in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Desktop\HostedRuntimeEnvironment.cs:line 263
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Desktop\CommonTestBase.CompilationVerifier.cs:line 109
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify) in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Desktop\CommonTestBase.cs:line 204
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify) in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Desktop\CommonTestBase.cs:line 129
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.BasicTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify) in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\VisualBasic\BasicTestBase.vb:line 77
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.OptionalArgumentTests_ImplicitDefaultValue.TestCallerFilePath1() in C:\Users\Adam\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Semantic\Semantics\OptionalArgumentTests_Implicit.vb:line 2004]]>
</stack-trace>

</failure>

</test>
```

The xml attribute `exception-type` can not state within xml literals. VB thinks the the `-` is a minus sign and not a hypen.

A **Workaround** is to access the attribute "long hand" ::-  `xmlnode.Attribute("exception-type")`

Should the xml-literals support the full range on valid xml attribute identifiers?

**Comment by jaredpar** [comment]
Cannot repro in VS 2017
