### ISSUE TITLE
Csc.exe crashes when compiling Roslyn with latest Roslyn

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#1197]
I'm attempting to compile Roslyn with the latest Roslyn bits. Csc.exe fails with the following exception:

```
 Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
 Parameter name: bytes
    at System.Text.Encoding.ThrowBytesOverflow()
    at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
    at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
    at System.Text.EncoderNLS.Convert(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
    at System.Text.EncoderNLS.Convert(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Boolean flush, Int32& charsUsed, Int32& bytesUsed, Boolean& completed)
    at Microsoft.CodeAnalysis.Text.SourceTextStream.Read(Byte[] buffer, Int32 offset, Int32 count)
    at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)
    --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at Roslyn.Utilities.HashAlgorithm.ComputeHash(Stream stream)
    at Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum(Stream stream, SourceHashAlgorithm algorithmId)
    at Microsoft.CodeAnalysis.Text.SourceText.GetChecksum()
    at Microsoft.CodeAnalysis.SyntaxTree.GetChecksumAndAlgorithm()
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at Microsoft.Cci.DebugSourceDocument.get_ChecksumAndAlgorithm()
    at Microsoft.Cci.PdbWriter.GetDocumentWriter(DebugSourceDocument document)
    at Microsoft.Cci.PdbWriter.EmitSequencePoints(ImmutableArray`1 sequencePoints)
    at Microsoft.Cci.PdbWriter.SerializeDebugInfo(IMethodBody methodBody, UInt32 localSignatureToken, CustomDebugInfoWriter customDebugInfoWriter)
    at Microsoft.Cci.MetadataWriter.SerializeMethodBodies(BinaryWriter writer, PdbWriter pdbWriterOpt)
    at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(PdbWriter pdbWriterOpt, BinaryWriter metadataWriter, BinaryWriter ilWriter, BinaryWriter mappedFieldDataWriter, BinaryWriter managedResourceDataWriter, Func`2 calculateMethodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, UInt32& moduleVersionIdOffsetInMetadataStream, UInt32& entryPointToken, MetadataSizes& metadataSizes)
    at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, PdbWriter nativePdbWriterOpt, UInt32& entryPointToken)
    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, PdbWriter nativePdbWriterOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, PdbOutputInfo pdbOutputInfo, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, PdbOutputInfo pdbOutputInfo, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, PdbOutputInfo pdbOutputInfo, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args)
    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)

```

**Comment by jaredpar** [comment]
Found a minimal repo for this bug:

``` csharp
            var target = @"E:\dd\ros\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs";
            var text = File.ReadAllText(target);
            var sourceText = SourceText.From(text, Encoding.UTF8);
            var methodInfo = sourceText.GetType().GetMethod("GetChecksum", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            methodInfo.Invoke(sourceText, null);
```

**Comment by jaredpar** [comment]
@tmeschter  I was able to do a self host build of Roslyn.sln with the contents of my PR.  So you should be unblocked for update after that is accepted.
