### ISSUE TITLE
Failing VB completion unit test SelectKeywordFirst

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#11980]
The following unit test fails on a fresh clone of master:

```vb
        <WorkItem(546208, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/546208")>
        <WpfFact, Trait(Traits.Feature, Traits.Features.Completion)>
        Public Async Function SelectKeywordFirst() As Task
            Using state = TestState.CreateVisualBasicTestState(
                              <Document>
Class C
    Sub M()
        $$
    End Sub

    Sub GetType()
    End Sub
End Class
                              </Document>)

                state.SendTypeChars("GetType")
                Await state.WaitForAsynchronousOperationsAsync()
                Await state.AssertSelectedCompletionItem("GetType", VBFeaturesResources.GettypeFunction + vbCrLf +
                    ReturnsSystemTypeObject + vbCrLf +
                    $"GetType({Typename}) As Type")
            End Using
        End Function
```

The failure mode is

```none
------ Test started: Assembly: Roslyn.Services.Editor.UnitTests2.dll ------
Unknown .NET Framework Version: v4.6
Test 'Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.SelectKeywordFirst' failed:
	Assert.Equal() Failure
          ↓ (pos 0)
Expected: GetType function\r\nReturns a System.Type o···
Actual:   Sub C.GetType()
          ↑ (pos 0)
	IntelliSense\TestState.vb(270,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState.VB$StateMachine_36_AssertSelectedCompletionItem.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	IntelliSense\VisualBasicCompletionCommandHandlerTests.vb(1843,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_88_SelectKeywordFirst.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

0 passed, 1 failed, 0 skipped, took 8.87 seconds (xUnit.net 2.1.0 build 3179).
```

**Comment by gafter** [comment]
@cston, @CyrusNajmabadi, @rchande @CyrusNajmabadi @jasonmalinowski This is the underlying issue for PR #12016.

**Comment by Pilchie** [comment]
Please take a look.

**Comment by rchande** [comment]
@gafter I'm unable to make this fail locally and https://github.com/dotnet/roslyn/pull/12051/files (which reverts the skip) is also green. Since I'm unable to make the test fail, I'm going to resolve the bug.

**Comment by rchande** [comment]
This is fixed now.
