### ISSUE TITLE
[Test Failure] CSharpLinkedFile.xml failed in windows_vsi_p2_prtest on PR #1061

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#11984]
PR: [#1061](https://github.com/dotnet/roslyn-internal/pull/1061) _Removing an unecessary identical call to 'BuildNuGets.csx'_ by @tannergooding
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/145/

```
Start - list of failing integration tests:
15:34:41 CSharpLinkedFile.xml
15:34:41 End - list of failing integration tests.
15:34:51 VS integration tests failed
15:34:51 ================================================================================
15:34:51 Dumping the log file for the last TAO test.  It may or may not include a failure.
15:34:51 ================================================================================
15:34:51 Test: CSharpMiscellaneousFiles started: 6/13/2016 10:35:32 PM
15:34:51    Executing action [6/13/2016 10:35:32 PM] StartTarget
15:34:51 Begin Waiting for Apex Communication
15:34:51    Executing action [6/13/2016 10:35:32 PM] CreateTemporaryFile
15:34:51    Executing action [6/13/2016 10:35:32 PM] CreateTemporaryFile
15:34:51  Scenario: 1) Open miscellaneous C# file and verify language services are wired up but no squiggles exist.
15:34:51    Executing action [6/13/2016 10:35:32 PM] OpenFile
15:34:51 DEBUG: found path via temporary FileId.
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:35:32 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:35:32 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:35:32 PM] VerifyQuickInfo
15:34:51    Executing action [6/13/2016 10:35:32 PM] VerifyErrorTags
15:34:51    Executing action [6/13/2016 10:35:38 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:35:38 PM] VerifyNoCodeActionsAvailable
15:34:51  Scenario: 2) Rename the open file and verify language services.
15:34:51    Executing action [6/13/2016 10:35:58 PM] SaveFile
15:34:51    Executing action [6/13/2016 10:35:58 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:35:58 PM] VerifyQuickInfo
15:34:51    Executing action [6/13/2016 10:35:58 PM] VerifyErrorTags
15:34:51  Scenario: 3) Create a text file, rename to .cs, and verify language services.
15:34:51    Executing action [6/13/2016 10:36:04 PM] OpenFile
15:34:51 DEBUG: found path via temporary FileId.
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:36:04 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:36:04 PM] SaveFile
15:34:51    Executing action [6/13/2016 10:36:04 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:36:04 PM] VerifyQuickInfo
15:34:51    Executing action [6/13/2016 10:36:04 PM] VerifyErrorTags
15:34:51  Scenario: 4) Verify Find References still works in a miscellaneous file
15:34:51    Executing action [6/13/2016 10:36:10 PM] OpenFile
15:34:51 DEBUG: found path via temporary FileId.
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:36:10 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:36:10 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:36:10 PM] SendKeys
15:34:51    Executing action [6/13/2016 10:36:10 PM] VerifyFindSymbolResults
15:34:51    Executing action [6/13/2016 10:36:10 PM] CloseTarget
15:34:51    Executing action [6/13/2016 10:36:11 PM] CleanupTemporaryFiles
15:34:51 Test finished: 6/13/2016 10:36:11 PM
15:34:51    Executing action [6/13/2016 10:36:11 PM] CloseTarget
15:34:51 Closing VS. force Close = True, closeVsToFreeHandles = False
15:34:51 
15:34:51 ================================================================================
15:34:51 Dumping logs of all failed TAO tests.
15:34:51 ================================================================================
15:34:51 ================================================================================
15:34:51  Dumping log file d:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\VSIntegrationTestLogs\CSharpLinkedFile.txt
15:34:51 Test: CSharpLinkedFile started: 6/13/2016 10:32:50 PM
15:34:51    Executing action [6/13/2016 10:32:50 PM] StartTarget
15:34:51 Begin Waiting for Apex Communication
15:34:51    Executing action [6/13/2016 10:32:50 PM] AddProject
15:34:51    Executing action [6/13/2016 10:33:00 PM] SetProjectConfigurationProperty
15:34:51    Executing action [6/13/2016 10:33:00 PM] AddItem
15:34:51    Executing action [6/13/2016 10:33:01 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:33:01 PM] VerifyEditorContainsText
15:34:51    Executing action [6/13/2016 10:33:01 PM] CloseFile
15:34:51 The file did save the correct text.
15:34:51    Executing action [6/13/2016 10:33:01 PM] AddProject
15:34:51    Executing action [6/13/2016 10:33:11 PM] SetProjectConfigurationProperty
15:34:51  Scenario: Verify if projects have been set up correctly with conditional compilation symbols
15:34:51    Executing action [6/13/2016 10:33:11 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:11 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:11 PM] VerifyTokenType
15:34:51    Executing action [6/13/2016 10:33:17 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:17 PM] VerifyTokenType
15:34:51    Executing action [6/13/2016 10:33:17 PM] CloseFile
15:34:51  Scenario: Verify adding a linked file to another project when the file is open in the editor from the original host project
15:34:51    Executing action [6/13/2016 10:33:17 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:17 PM] AddLinkFile
15:34:51    Executing action [6/13/2016 10:33:17 PM] NavigationBar
15:34:51    Executing action [6/13/2016 10:33:19 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:19 PM] VerifyTokenType
15:34:51    Executing action [6/13/2016 10:33:23 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:23 PM] VerifyTokenType
15:34:51    Executing action [6/13/2016 10:33:23 PM] CloseFile
15:34:51  Scenario: Verify union intellisense Intellisense: Intellisense Tooltip
15:34:51    Executing action [6/13/2016 10:33:23 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:24 PM] NavigationBar
15:34:51    Executing action [6/13/2016 10:33:25 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:25 PM] SendKeys
15:34:51    Executing action [6/13/2016 10:33:26 PM] InvokeCompletionList
15:34:51    Executing action [6/13/2016 10:33:26 PM] VerifyCompletionList
15:34:51    Executing action [6/13/2016 10:33:26 PM] CloseFile
15:34:51  Scenario: Verify Union Intellisense: Signature Help
15:34:51    Executing action [6/13/2016 10:33:26 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:27 PM] NavigationBar
15:34:51    Executing action [6/13/2016 10:33:28 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:28 PM] SendKeys
15:34:51    Executing action [6/13/2016 10:33:29 PM] VerifySignatureHelp
15:34:51    Executing action [6/13/2016 10:33:29 PM] CloseFile
15:34:51  Scenario: Verify Union Intellisense: Quickinfo
15:34:51    Executing action [6/13/2016 10:33:29 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:29 PM] NavigationBar
15:34:51    Executing action [6/13/2016 10:33:31 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:31 PM] SendKeys
15:34:51    Executing action [6/13/2016 10:33:31 PM] VerifyQuickInfo
15:34:51    Executing action [6/13/2016 10:33:34 PM] CloseFile
15:34:51  Scenario: Bugfix 1068969 - ArgumentOutofRangeException during Rename Tracking
15:34:51    Executing action [6/13/2016 10:33:34 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:33:35 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:33:35 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:33:35 PM] SendKeys
15:34:51    Executing action [6/13/2016 10:33:35 PM] VerifyCodeActions
15:34:51 --------------------------------
15:34:51 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: No Active Smart Tags in View!  Buffer content type=CSharp
15:34:51    at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass49_0.<VerifyCodeActions>b__0() in d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 246
15:34:51    --- End of inner exception stack trace ---
15:34:51    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
15:34:51    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
15:34:51    at System.Delegate.DynamicInvokeImpl(Object[] args)
15:34:51    at System.Delegate.DynamicInvoke(Object[] args)
15:34:51    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values) in f:\dd\src\Omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 118
15:34:51    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
15:34:51 ================================
15:34:51 
15:34:51 
15:34:51 Saved screenshot: d:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Screenshots\2016-06-13_22-34-01_44 - Exception System.Reflection.TargetInvocationException.png
15:34:51    Executing action [6/13/2016 10:34:01 PM] CloseFile
15:34:51  Scenario: Verify closing solution with open linked files does not corrupt the workspace state for the next solution opened
15:34:51    Executing action [6/13/2016 10:34:01 PM] OpenFile
15:34:51 DEBUG: executed DTE command File.OpenFile.
15:34:51 DEBUG: start polling for code window
15:34:51 DEBUG: polling complete
15:34:51    Executing action [6/13/2016 10:34:01 PM] CloseSolution
15:34:51    Executing action [6/13/2016 10:34:01 PM] AddProject
15:34:51    Executing action [6/13/2016 10:34:12 PM] AddItem
15:34:51    Executing action [6/13/2016 10:34:12 PM] SetEditorText
15:34:51    Executing action [6/13/2016 10:34:12 PM] PlaceCursor
15:34:51    Executing action [6/13/2016 10:34:12 PM] VerifyTokenType
15:34:51    Executing action [6/13/2016 10:34:17 PM] CloseFile
15:34:51    Executing action [6/13/2016 10:34:18 PM] CloseTarget
15:34:51 Test finished: 6/13/2016 10:34:19 PM
15:34:51    Executing action [6/13/2016 10:34:19 PM] CloseTarget
15:34:51 Closing VS. force Close = True, closeVsToFreeHandles = False
15:34:51 
15:34:51 ================================================================================
15:34:51  Dumping log file d:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\VSIntegrationTestLogs\TaoStartup.txt
15:34:51 Created screenshots folder: d:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Screenshots
15:34:51 Saved screenshot: d:\j\workspace\windows_vsi_p---ad02e19d\Open\Binaries\Release\Screenshots\2016-06-13_21-58-08_81 - Verifying Screenshot Reliability.png
15:34:51 
15:34:51 BUILD WARNINGS for d:\j\workspace\windows_vsi_p---ad02e19d\Roslyn.sln
15:34:51 21:52:46.188   159>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Tools\Source\VsixExpInstaller\VsixExpInstaller.csproj]
15:34:51 21:52:46.300   160>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Tools\Source\UninstallRoslynOnBuildBox\UninstallRoslynOnBuildBox.csproj]
15:34:51 21:54:24.091   152>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1897,5): warning MSB3836: The existing binding redirect on "Microsoft.VisualStudio.GraphModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is incorrect. Consider removing it from the application configuration file. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />". [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\HostingIntegrationTest.csproj]
15:34:51 21:54:24.091   152>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1897,5): warning MSB3836: The existing binding redirect on "Microsoft.VisualStudio.ComponentModelHost, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is incorrect. Consider removing it from the application configuration file. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />". [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\HostingIntegrationTest.csproj]
15:34:51 21:54:24.091   152>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1897,5): warning MSB3836: The existing binding redirect on "Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is incorrect. Consider removing it from the application configuration file. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />". [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\HostingIntegrationTest.csproj]
15:34:51 21:54:24.091   152>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1897,5): warning MSB3836: The existing binding redirect on "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is incorrect. Consider removing it from the application configuration file. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />". [d:\j\workspace\windows_vsi_p---ad02e19d\Closed\Hosting\Test\HostingIntegrationTest.csproj]
15:34:51 ===============================================
15:34:51 There were failures, see red messages above :-(
15:34:51 ===============================================
15:34:51 
15:34:51 Total Time: 00:45:38.4982084
15:34:51 
15:34:51 Build failed with ERRORLEVEL 1
15:34:51 
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by Pilchie** [comment]
Hit this again on http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/microupdate/job/windows_vsi_p2_open_prtest/36/ as part of https://github.com/dotnet/roslyn/pull/12686

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_prtest/621/testReport/junit/(root)/CSharpLinkedFile/Bugfix_1068969___ArgumentOutofRangeException_during_Rename_Tracking/

**Comment by mavasani** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/453/

**Comment by genlu** [comment]
This particular test failed again but seemingly with a different exception.
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/569/

```
08:25:00 ================================================================================
08:25:00 Dumping logs of all failed TAO tests.
08:25:00 ================================================================================
08:25:00 ================================================================================
08:25:00  Dumping log file d:\j\workspace\windows_vsi_p---5fa6ff52\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\CSharpLinkedFile.txt
08:25:00 Test: CSharpLinkedFile started: 10/31/2016 3:24:51 PM
08:25:00 	Executing action [10/31/2016 3:24:51 PM] StartTarget
08:25:00 Begin Waiting for Apex Communication
08:25:00 	Executing action [10/31/2016 3:24:51 PM] AddProject
08:25:00 	Executing action [10/31/2016 3:25:01 PM] SetProjectConfigurationProperty
08:25:00 	Executing action [10/31/2016 3:25:01 PM] AddItem
08:25:00 	Executing action [10/31/2016 3:25:01 PM] SetEditorText
08:25:00 	Executing action [10/31/2016 3:25:02 PM] VerifyEditorContainsText
08:25:00 	Executing action [10/31/2016 3:25:02 PM] CloseFile
08:25:00 --------------------------------
08:25:00 System.Exception: The text that we thought we were saving isn't what we saved!
08:25:00    at Roslyn.VSHosting.Test.CloseFileAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\Test\Actions\VisualStudio\CloseFileAction.cs:line 60
08:25:00    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 139
08:25:00    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 36
08:25:00 ================================
08:25:00 
08:25:00 
08:25:00 Saved screenshot: d:\j\workspace\windows_vsi_p---5fa6ff52\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-10-31_15-25-02_08 - Exception System.Exception.png
08:25:00 	Executing action [10/31/2016 3:25:02 PM] CloseTarget
08:25:00 Test finished: 10/31/2016 3:25:03 PM
08:25:00 	Executing action [10/31/2016 3:25:03 PM] CloseTarget
08:25:00 Closing VS. force Close = True, closeVsToFreeHandles = False
08:25:00 	  Cleared VS MEF Component Cache.
08:25:00 
08:25:00 ================================================================================
```

**Comment by Pilchie** [comment]
Do you already have an open bug on this?  Looks like maybe we have some logs now?

>08:25:00 System.Exception: The text that we thought we were saving isn't what we saved!
08:25:00    at Roslyn.VSHosting.Test.CloseFileAction.Execute(TaoEngine engine) in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\Test\Actions\VisualStudio\CloseFileAction.cs:line 60
08:25:00    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 139

**Comment by jasonmalinowski** [comment]
@Pilchie This is the tracking bug AFAIK.

**Comment by Pilchie** [comment]
Moving to 2.1, as we wouldn't fix this in escrow without an understood customer impact.

**Comment by jasonmalinowski** [comment]
This test is dead.
