### ISSUE TITLE
[Flaky test] AV in SyntaxAnnotationTests.TestCSharpAllInOneRandom

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12236]
See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/800

```
13:17:33   Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
13:17:33      at Microsoft.CodeAnalysis.SyntaxNodeOrToken..ctor(SyntaxNode node)
13:17:33      at Microsoft.CodeAnalysis.SyntaxNodeOrToken.op_Implicit(SyntaxNode node)
13:17:33      at Microsoft.CodeAnalysis.ChildSyntaxList.ItemInternal(SyntaxNode node, Int32 index)
13:17:33      at Microsoft.CodeAnalysis.ChildSyntaxList.Enumerator.TryMoveNextAndGetCurrent(SyntaxNodeOrToken& current)
13:17:33      at Microsoft.CodeAnalysis.SyntaxNode.ChildSyntaxListEnumeratorStack.TryGetNextInSpan(TextSpan& span, SyntaxNodeOrToken& value)
13:17:33      at Microsoft.CodeAnalysis.SyntaxNode.ThreeEnumeratorListStack.TryGetNextInSpan(TextSpan& span, SyntaxNodeOrToken& value)
13:17:33      at Microsoft.CodeAnalysis.SyntaxNode.<DescendantNodesAndTokensIntoTrivia>d__166.MoveNext()
13:17:33      at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
13:17:33      at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
13:17:33      at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
13:17:33      at Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxAnnotationTests.GetAllNodesAndTokens(SyntaxNode root)
13:17:33      at Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxAnnotationTests.TestRandomAnnotations(SyntaxTree syntaxTree)
13:17:33      at Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxAnnotationTests.TestCSharpAllInOneRandom()
```

**Comment by mavasani** [comment]
Not sure if this is a test issue or a bug - so added both labels.

**Comment by jaredpar** [comment]
Closing as we haven't seen this failure recently.
