### ISSUE TITLE
CSharpErrorlog fails when ran in Standalone with System.ArgumentException regarding a key for 'CS8032'

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#12286]
**Version Used**: 
ML 25429.00
**Steps to Reproduce**:
Run CSharpErrorList.xml in a standalone context. Contact me and I can give you a machine.

Exception hit is:
```
 Scenario: Error List Build Diagnostics
     Executing action [6/29/2016 10:21:08 AM] Build
     Executing action [6/29/2016 10:21:14 AM] ExecuteCommand
     Executing action [6/29/2016 10:21:14 AM] VerifyErrorLog
 --------------------------------
 System.ArgumentException: An element with the same key but a different value already exists. Key: "ruleId": "CS8032",

 Server stack trace: 
    at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
    at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
    at Roslyn.VSHosting.Test.RoslynInProcessAPI.ParseErrorLog(String errorLogFile)
    at Roslyn.VSHosting.Test.RoslynInProcessAPI.VerifyErrorLog(DiagnosticsMode mode, String errorLogBaselineFile, Boolean ignoreSuppressedDiagnostics, String errorLogBaselineRegenerateReadmeFile, String projectNameOpt, String documentNameOpt)
    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

 Exception rethrown at [0]: 
    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
    at Roslyn.VSHosting.Test.RoslynInProcessAPI.VerifyErrorLog(DiagnosticsMode mode, String errorLogBaselineFile, Boolean ignoreSuppressedDiagnostics, String errorLogBaselineRegenerateReadmeFile, String projectNameOpt, String documentNameOpt)
    at Roslyn.VSHosting.Test.VerifyErrorLogAction.Execute(TaoEngine engine)
    at Tao.Engine.DebuggableActionExecutor.Execute()
    at Tao.Engine.DefaultActionExecutor.Execute()
 ================================
```

Cause might have something to do with how CS8032 seems to be hitting a file not found warning for an old version of System.Collections.Immutable. It's looking for 1.1.36.0 when we are on 1.1.37.0. Does the solution Newtonsoft.Json need an update?

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10537189/16462165/e2ed7384-3de4-11e6-9cef-8479cad7da29.png)

**Comment by mavasani** [comment]
'CS8032' is not expected for this test - your error list shows that something is wrong with your compiler toolset setup and build caused the analyzer to not even execute. I am closing this as a setup issue. Please re-activate if you hit this on Jenkins OR on a VS instance where CS8032 is not fired during build.
