### ISSUE TITLE
Randomly encountering TaskCanceledException errors

### ISSUE THREAD

**Issue by tanveerbadar** [dotnet/roslyn#12484]
**Version Used**:  1.3.2, VS 2015 Update 3

**Steps to Reproduce**:

When reasoning about my work codebase, I seem to be getting TaskCanceledException errors randomly. Stack trace (not so helpful) is given below.

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at AnalysisRun.Program.Main(String[] args) in \AnalyzerDriver\Program.cs:line 25
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

So far the errors are thrown by Document.GetSemanticModelAsync() and SymbolFinder.FindReferencesAsync() functions. These exceptions started occurring randomly, and are thrown on only some projects. I created a sample class library project, that appears to be parsed correctly.

**Expected Behavior**: A valid object should be returned.

**Actual Behavior**: Exceptions encountered.

**Comment by svick** [comment]
What is the stack trace of the `InnerException`? Can you share your code?

**Comment by tanveerbadar** [comment]
That stack trace is null. Code, unfortunately, cannot be shared because of various NDAs.

Are there any general causes where this exception might get thrown?

**Comment by tanveerbadar** [comment]
My suspicion is the recently released VS 2015 Update 3 KB 3165756 Patch. I'll try to rollback that update tomorrow and see if sanity returns.

**Comment by mavasani** [comment]
@tanveerbadar Do you have a dump for the exception? Can you attach a debugger and collect the dump?

Btw, I am not sure why this is assigned to analyzers area path. There is nothing in the repro that suggests this is coming from analyzer execution.

**Comment by tanveerbadar** [comment]
I have collected a dump, how do I share it with you?

**Comment by mavasani** [comment]
@tanveerbadar Can you please follow the steps [here](http://connect.microsoft.com/VisualStudio/content/content.aspx?ContentID=31113) in _Reporting a crash_ section to report the crash dump?

**Comment by mavasani** [comment]
@tanveerbadar I am closing this issue - kindly upload the crash dumps via the link above, and we will investigate them.

**Comment by Pilchie** [comment]
Note - @CyrusNajmabadi might be investigating a similar issue around `TaskCanceledException`s getting thrown in roslyn APIs.
