### ISSUE TITLE
Completion will not show doc comments for symbols containing anonymous types in them.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#12530]
Using this code:

```c#
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        new[] { new { x = 1 } }$$
    }
}
```

Bring up completion at $$ and pick something like ToArray.

Expected:
Doc comments.

Actual:
No doc comments.

The reason for this is that completion now uses a data model where we encode a representation of a symbol as a string, and hten later on try to recover it for things like doc comments.  With anonymous types, there is no system in the compilers to create or resolve them later on.  As such, resolution fails and we can't show doc comment text anymore.

When we used to hold onto symbols directly, this was not a problem.  But the new system doens't adequately handle this.

**Comment by DustinCampbell** [comment]
Great catch @CyrusNajmabadi!

**Comment by aelij** [comment]
I just encountered this bug, and for some completion items, it even throws. Documenting it here to make sure the fix also took care of that.

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Construct(ImmutableArray`1 typeArguments)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(ITypeSymbol[] arguments)
   at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingMethods(IReadOnlyList`1 containers, String name, List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseNamedSymbol(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.Parse(String id, Compilation compilation, List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.GetFirstSymbolForId(String id, Compilation compilation)
   at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.DecodeSymbols(List`1 ids, Compilation compilation, List`1 symbols)
   at async Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.GetSymbolsAsync(?)
   at async Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.GetDescriptionAsync(?)
```

**Comment by CyrusNajmabadi** [comment]
Do you have a repro case that we can test out?

**Comment by aelij** [comment]
```csharp
var ws = new AdhocWorkspace(MefHostServices.Create(compositionContext));
var p = ws.AddProject("x", LanguageNames.CSharp)
    .WithMetadataReferences(new[] {
        FromType(typeof(object)),
        FromType(typeof(Enumerable))
    });

var code = @"using System.Linq; class C { void M() { new[] { new { X = 3 } }.";
var d = p.AddDocument("d", code);

var index = code.Length;

var cs = CompletionService.GetService(d);
var t = await cs.GetCompletionsAsync(d, index, CompletionTrigger.Default);
var item = t.Items.First(x => x.DisplayText == "AsParallel<>");
var changes = await cs.GetChangeAsync(d, item);
var description = await cs.GetDescriptionAsync(d, item);
```

`FromType` creates a `MetadataReference` using a `FileBasedXmlDocumentationProvider` (created using Reflection).
