### ISSUE TITLE
VS Code NFW in Interop.Crypto.EvpSha1 on OSX

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/roslyn#12681]
In the C# VSCode extension on OSX (and **only** on OSX), I am seeing non-fatal watsons being sent from Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CSharpLanguageInstructionDecoder:GetMethodName. Here is the stack:

```
vs.diagnostics.debugger.nonfatalerror.exceptionstack":"at Interop.Crypto.EvpSha1()
at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
at System.Security.Cryptography.SHA1.Implementation..ctor()
at System.Security.Cryptography.SHA1.Create()
at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
at Microsoft.CodeAnalysis.AssemblyIdentity.KeysEqual(AssemblyIdentity x, AssemblyIdentity y)
at Microsoft.CodeAnalysis.AssemblyIdentity.MemberwiseEqual(AssemblyIdentity x, AssemblyIdentity y)
at Microsoft.CodeAnalysis.AssemblyIdentityComparer.TriviallyEquivalent(AssemblyIdentity x, AssemblyIdentity y)
at Microsoft.CodeAnalysis.AssemblyIdentityComparer.Compare(AssemblyIdentity reference, String referenceDisplayName, AssemblyIdentity definition, Boolean& unificationAppl
```

Exception type: System.TypeInitializationException

Is this code correct on OSX? Should this go to the CoreFX team?

**Comment by tmat** [comment]
My guess would be that the machine is missing OpenSSL.

**Comment by gregg-miskelly** [comment]
We are fixing this in the C# extension, so resolving as external.  See https://github.com/OmniSharp/omnisharp-vscode/issues/779.
