### ISSUE TITLE
Flaky IDE cross language unit test failures

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#12790]
See http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_debug_unit32_prtest/374/

 Test Result (4 failures / +4)Microsoft.CodeAnalysis.Editor.UnitTests.Rename.DashboardTests.ConflictsAcrossLanguages_Resolvable
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests+CSharpConflicts.BreakingRenameCrossAssembly
Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddImport.AddImportCrossLanguageTests.TestExtensionMethods1
Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddImport.AddImportCrossLanguageTests.TestExtensionMethods2

**Comment by jasonmalinowski** [comment]
The last three all failed due to a failing assert:

	at System.Diagnostics.Debug.Assert(Boolean condition)
	at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader, String metadataName, Int32 arity, Boolean isPartialMethodImplementationPart, ImmutableArray`1 parameterRefKinds, Int32 beforeParametersPosition, IMethodSymbol method) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.MethodSymbolKey.cs:line 219
	at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader, String metadataName, Int32 arity, Boolean isPartialMethodImplementationPart, ImmutableArray`1 parameterRefKinds, Int32 beforeParametersPosition, INamedTypeSymbol namedType) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.MethodSymbolKey.cs:line 186
	at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.MethodSymbolKey.cs:line 155
	at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.SymbolKeyReader.cs:line 531
	at Microsoft.CodeAnalysis.SymbolKey.Reader`2.ReadSymbolKeyWorker(Boolean first) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.SymbolKeyReader.cs:line 258
	at Microsoft.CodeAnalysis.SymbolKey.Reader`2.ReadFirstSymbolKey() in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.SymbolKeyReader.cs:line 222
	at Microsoft.CodeAnalysis.SymbolKey.Resolve(String symbolKey, Compilation compilation, Boolean ignoreAssemblyKey, CancellationToken cancellationToken) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 119
	at Microsoft.CodeAnalysis.SymbolKey.Resolve(Compilation compilation, Boolean ignoreAssemblyKey, CancellationToken cancellationToken) in D:\j\workspace\windows_debug---f061378f\Open\src\Workspaces\Core\Portable\SymbolId\SymbolKey.cs:line 141

The first doesn't have a useful trace from the file, but given it's cross-language it's probably the same thing.

**Comment by jasonmalinowski** [comment]
FYI to @Pilchie and @mattwar if they have any obvious idea here before I dig further. The offending line is [here](https://github.com/dotnet/roslyn/blob/fb9324de0f17a00616a53079785f5ebaff4a75d8/src/Workspaces/Core/Portable/SymbolId/SymbolKey.MethodSymbolKey.cs#L219).

**Comment by Pilchie** [comment]
I think @CyrusNajmabadi is the `SymbolKey` guy...

**Comment by CyrusNajmabadi** [comment]
This is a bad assert.  We need to understand the symbolic condition that can cause this.

However, if we can't figure it out, a reasonable workaround is to use a stack of 'current method symbols' instead of just having a single field for it.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: my thought was if this was a recursion issue, we'd see MethodSymbolKey.Resolve recursing on the stack that lead to the Debug.Assert. But we don't.

I do see one potential bug where we don't clear this field when putting the objects back into the object pool. I'm determining now if it's possible for us to observe a cancellation during MethodSymbolKey.Resolve.

**Comment by CyrusNajmabadi** [comment]
Er.  by "bad assert" i mean "this is a strange condition that the code is not prepared to handle"  not "we need to change hte assert because it's bogus".  I want to understand what symbolic condition can cause this assert to fire.  If we cna't figure it out we can at least be resilient to this sort of thing by using a stack.

**Comment by jasonmalinowski** [comment]
Ah yes, we don't clear this during cancellation. Pull request coming shortly.
