### ISSUE TITLE
VS crash: KeyNotFoundException from Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetOrCreateContext

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#1281]
Crash dump:

%internal_share%\tomat\Bugs\1281

Stack trace

```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key) in f:\dd\NDP\clr\src\BCL\System\Collections\Generic\Dictionary.cs:line 184
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetOrCreateContext(Document document, Int32 position, CancellationToken cancellationToken) in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 300
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetPerContextSymbols>d__21.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 264
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 140
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__17.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 210
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__16.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 172
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 206
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\NDP\clr\src\BCL\System\Runtime\CompilerServices\TaskAwaiter.cs:line 168
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in F:\Builds\6635\Roslyn\Main-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
```

**Comment by AdamSpeight2008** [comment]
Is this related to #1006 ?

**Comment by Pilchie** [comment]
@AdamSpeight2008 doesn't look related to me.

**Comment by rchande** [comment]
Can you verify, @tmat ?

**Comment by tmat** [comment]
@rchande Don't have a reliable repro. Will install new build tomorrow.
