### ISSUE TITLE
BasicBraceHighlighting.xml test failure

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#13126]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/2391/console

```
10:00:16 ================================================================================
10:00:16 Dumping the log file for the last TAO test.  It may or may not include a failure.
10:00:16 ================================================================================
10:00:16 Test: SplitFile started: 8/12/2016 5:00:58 PM
10:00:16 	Executing action [8/12/2016 5:00:58 PM] StartTarget
10:00:16 	Executing action [8/12/2016 5:00:58 PM] SetFeatureOption
10:00:16 	Executing action [8/12/2016 5:00:58 PM] SetFeatureOption
10:00:16  Scenario: Test tagger ranges (bug 622028)
10:00:16 	Executing action [8/12/2016 5:00:58 PM] ExecuteCommand
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 	Executing action [8/12/2016 5:00:58 PM] DeleteText
10:00:16 	Executing action [8/12/2016 5:00:58 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:00:58 PM] VerifyKeywordHighlightTags
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:01 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# brace highlighting
10:00:16 	Executing action [8/12/2016 5:01:01 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:01 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:01 PM] VerifyBraceHighlightTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:05 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB brace highlighting
10:00:16 	Executing action [8/12/2016 5:01:05 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:05 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:05 PM] VerifyBraceHighlightTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:08 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# classification
10:00:16 	Executing action [8/12/2016 5:01:08 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:08 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:08 PM] VerifyTokenType
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:14 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB classification
10:00:16 	Executing action [8/12/2016 5:01:14 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:14 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:15 PM] VerifyTokenType
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:20 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# smart indent
10:00:16 	Executing action [8/12/2016 5:01:20 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:21 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:21 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:21 PM] VerifyCaretPosition
10:00:16 	Executing action [8/12/2016 5:01:21 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB smart indent
10:00:16 	Executing action [8/12/2016 5:01:21 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:21 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:21 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:21 PM] VerifyCaretPosition
10:00:16 	Executing action [8/12/2016 5:01:21 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# IntelliSense
10:00:16 	Executing action [8/12/2016 5:01:21 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:22 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:22 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:22 PM] VerifyCompletionList
10:00:16 	Executing action [8/12/2016 5:01:22 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:22 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB IntelliSense
10:00:16 	Executing action [8/12/2016 5:01:22 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:22 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:23 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:23 PM] VerifyCompletionList
10:00:16 	Executing action [8/12/2016 5:01:23 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:23 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# keyword highlighting
10:00:16 	Executing action [8/12/2016 5:01:23 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:23 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:23 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:24 PM] VerifyKeywordHighlightTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:26 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:26 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB keyword highlighting
10:00:16 	Executing action [8/12/2016 5:01:26 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:27 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:27 PM] InsertText
10:00:16 	Executing action [8/12/2016 5:01:27 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:27 PM] VerifyKeywordHighlightTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:30 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:30 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: Cross-Language Reference Highlighting
10:00:16 	Executing action [8/12/2016 5:01:30 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:30 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:30 PM] VerifyReferenceHighlightTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:33 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:33 PM] VerifyCaretPosition
10:00:16 	Executing action [8/12/2016 5:01:33 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: Line separators
10:00:16 	Executing action [8/12/2016 5:01:34 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:34 PM] VerifyLineSeparators
10:00:16 	Executing action [8/12/2016 5:01:37 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# Organize document
10:00:16 	Executing action [8/12/2016 5:01:37 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:37 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:37 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:37 PM] OrganizeDocument
10:00:16 	Executing action [8/12/2016 5:01:37 PM] VerifyEditorContainsText
10:00:16 	Executing action [8/12/2016 5:01:37 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:37 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB organize document
10:00:16 	Executing action [8/12/2016 5:01:38 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:38 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:38 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:38 PM] OrganizeDocument
10:00:16 	Executing action [8/12/2016 5:01:38 PM] VerifyEditorContainsText
10:00:16 	Executing action [8/12/2016 5:01:38 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:38 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: Outlining
10:00:16 	Executing action [8/12/2016 5:01:38 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:38 PM] VerifyOutlining
10:00:16 	Executing action [8/12/2016 5:01:40 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# squiggles
10:00:16 	Executing action [8/12/2016 5:01:40 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:41 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:41 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:41 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:41 PM] VerifyErrorTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:47 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:47 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB squiggles
10:00:16 	Executing action [8/12/2016 5:01:47 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:47 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:47 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:47 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:47 PM] VerifyErrorTags
10:00:16 given range is not current
10:00:16 given range is not current
10:00:16 	Executing action [8/12/2016 5:01:53 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:53 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:53 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# GotoDef
10:00:16 	Executing action [8/12/2016 5:01:53 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:53 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:53 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:54 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:54 PM] SendKeys
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 	Executing action [8/12/2016 5:01:54 PM] VerifyCurrentLine
10:00:16 	Executing action [8/12/2016 5:01:54 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: VB GotoDef
10:00:16 	Executing action [8/12/2016 5:01:54 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:54 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:54 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:55 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:55 PM] SendKeys
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 	Executing action [8/12/2016 5:01:55 PM] VerifyCurrentLine
10:00:16 	Executing action [8/12/2016 5:01:55 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16  Scenario: C# Formatting
10:00:16 	Executing action [8/12/2016 5:01:55 PM] ExecuteCommand
10:00:16 	Executing action [8/12/2016 5:01:55 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 5:01:55 PM] InsertText
10:00:16 	Executing action [8/12/2016 5:01:55 PM] DeleteText
10:00:16 	Executing action [8/12/2016 5:01:55 PM] SendKeys
10:00:16 	Executing action [8/12/2016 5:01:55 PM] DeleteText
10:00:16 	Executing action [8/12/2016 5:01:55 PM] CloseSolution
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 	Executing action [8/12/2016 5:01:55 PM] CloseTarget
10:00:16 Test finished: 8/12/2016 5:01:55 PM
10:00:16 
10:00:16 ================================================================================
10:00:16 Dumping logs of all failed TAO tests.
10:00:16 ================================================================================
10:00:16 ================================================================================
10:00:16  Dumping log file d:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\ETAIntegrationTestLogs\BasicBraceHighlighting.txt
10:00:16 Test: BasicBraceHighlighting started: 8/12/2016 4:45:36 PM
10:00:16 	Executing action [8/12/2016 4:45:36 PM] StartTarget
10:00:16 	Executing action [8/12/2016 4:45:36 PM] AddProject
10:00:16 	Executing action [8/12/2016 4:45:36 PM] AddItem
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 	Executing action [8/12/2016 4:45:36 PM] OpenFile
10:00:16  Scenario: {
10:00:16 	Executing action [8/12/2016 4:45:36 PM] SetEditorText
10:00:16 	Executing action [8/12/2016 4:45:36 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:36 PM] VerifyBraceHighlightTags
10:00:16 	Executing action [8/12/2016 4:45:39 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:39 PM] VerifyBraceHighlightTags
10:00:16  Scenario: }
10:00:16 	Executing action [8/12/2016 4:45:39 PM] SetEditorText
10:00:16 	Executing action [8/12/2016 4:45:39 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:39 PM] VerifyBraceHighlightTags
10:00:16 	Executing action [8/12/2016 4:45:39 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:39 PM] VerifyBraceHighlightTags
10:00:16  Scenario: Automatic Brace Completion
10:00:16 	Executing action [8/12/2016 4:45:39 PM] SetEditorText
10:00:16 	Executing action [8/12/2016 4:45:39 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:39 PM] SendKeys
10:00:16 	Executing action [8/12/2016 4:45:39 PM] VerifyEditorContainsText
10:00:16  Scenario: Automatic brace completion shift+enter
10:00:16 	Executing action [8/12/2016 4:45:39 PM] SetEditorText
10:00:16 	Executing action [8/12/2016 4:45:39 PM] PlaceCursor
10:00:16 	Executing action [8/12/2016 4:45:39 PM] SendKeys
10:00:16 	Executing action [8/12/2016 4:45:40 PM] VerifyEditorContainsText
10:00:16 	Executing action [8/12/2016 4:45:40 PM] CloseTarget
10:00:16 Note: ActiveTextView has lost Keyboard focus.
10:00:16 --------------------------------
10:00:16 System.AggregateException: Exceptions found in the exception log ---> System.NullReferenceException: Object reference not set to an instance of an object.
10:00:16    at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.HandleNormalFiltering(Model model, Document document, CompletionFilterReason filterReason, ITextSnapshot textSnapshot, CompletionHelper helper, ImmutableArray`1 recentItems, String filterText, List`1 filterResults) in d:\j\workspace\windows_eta_o---d880a2eb\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 218
10:00:16    --- End of inner exception stack trace ---
10:00:16    at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16
10:00:16    at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
10:00:16 --- End of stack trace from previous location where exception was thrown ---
10:00:16    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:00:16    at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
10:00:16    at Roslyn.Hosting.Test.EditorTestAppAction.Execute(TaoEngine engine) in d:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 147
10:00:16    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 139
10:00:16    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\omni\TAO\Tao.Engine\ActionExecutor.cs:line 36
10:00:16 ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
10:00:16    at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.HandleNormalFiltering(Model model, Document document, CompletionFilterReason filterReason, ITextSnapshot textSnapshot, CompletionHelper helper, ImmutableArray`1 recentItems, String filterText, List`1 filterResults) in d:\j\workspace\windows_eta_o---d880a2eb\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 218<---
10:00:16 
10:00:16 ================================
```

**Comment by Pilchie** [comment]
@CyrusNajmabadi @rchande - this looks worrying:

>10:00:16 System.AggregateException: Exceptions found in the exception log ---> System.NullReferenceException: Object reference not set to an instance of an object.
10:00:16    at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.HandleNormalFiltering(Model model, Document document, CompletionFilterReason filterReason, ITextSnapshot textSnapshot, CompletionHelper helper, ImmutableArray`1 recentItems, String filterText, List`1 filterResults) in d:\j\workspace\windows_eta_o---d880a2eb\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 218

**Comment by CyrusNajmabadi** [comment]
This was fixed with https://github.com/dotnet/roslyn/commit/cd738c498884deee60d8cd5e8c0e97c95459eb06
