### ISSUE TITLE
PlaceholderLocalRewriter is unable to handle Declaration Pattern

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#13159]
I will submit a unit-test shortly.
Because the rewriter doesn't apply appropriate transformation to the BoundDeclarationPattern node, later phases fail with the following exception:
```
	System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
	at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	CodeGen\Optimizer.cs(1761,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.RecordVarWrite(LocalSymbol local)
	CodeGen\Optimizer.cs(958,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitAssignmentOperator(BoundAssignmentOperator node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(1147,0): at Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(464,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpressionCore(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(503,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpression(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(697,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitSequence(BoundSequence node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(2530,0): at Microsoft.CodeAnalysis.CSharp.BoundSequence.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(464,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpressionCore(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(503,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpression(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(1091,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters)
	CodeGen\Optimizer.cs(1042,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitCall(BoundCall node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(4499,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(464,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpressionCore(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(520,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpressionCoreWithStackGuard(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(507,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpression(BoundExpression node, ExprContext context)
	CodeGen\Optimizer.cs(817,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitExpressionStatement(BoundExpressionStatement node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(2704,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(573,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitStatement(BoundNode node)
	CodeGen\Optimizer.cs(451,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.Visit(BoundNode node)
	BoundTree\BoundTreeRewriter.cs(36,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
	BoundTree\BoundTreeRewriter.cs(25,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(8728,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitBlock(BoundBlock node)
	CodeGen\Optimizer.cs(597,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitBlock(BoundBlock node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(2349,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(573,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitStatement(BoundNode node)
	CodeGen\Optimizer.cs(451,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.Visit(BoundNode node)
	BoundTree\BoundTreeRewriter.cs(36,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
	BoundTree\BoundTreeRewriter.cs(25,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(8728,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitBlock(BoundBlock node)
	CodeGen\Optimizer.cs(597,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitBlock(BoundBlock node)
	F:\GitHub\AlekseyTs\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs(2349,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
	BoundTree\BoundTreeVisitors.cs(147,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
	CodeGen\Optimizer.cs(573,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.VisitStatement(BoundNode node)
	CodeGen\Optimizer.cs(451,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.Visit(BoundNode node)
	CodeGen\Optimizer.cs(433,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.StackOptimizerPass1.Analyze(BoundNode node, Dictionary`2 locals, Boolean debugFriendly)
	CodeGen\Optimizer.cs(60,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.Optimizer.Optimize(BoundStatement src, Boolean debugFriendly, HashSet`1& stackLocals)
	CodeGen\CodeGenerator.cs(115,0): at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator..ctor(MethodSymbol method, BoundStatement boundBody, ILBuilder builder, PEModuleBuilder moduleBuilder, DiagnosticBag diagnostics, OptimizationLevel optimizations, Boolean emittingPdb)
	Compiler\MethodCompiler.cs(1324,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, ImmutableArray`1 dynamicAnalysisSpans)
	Compiler\MethodCompiler.cs(631,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState)
	Compiler\MethodCompiler.cs(570,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(ImmutableArray`1 additionalTypes, DiagnosticBag diagnostics)
	Compiler\MethodCompiler.cs(145,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
	Compilation\CSharpCompilation.cs(2328,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
	Compilation\Compilation.cs(1621,0): at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
	CompilationContext.cs(154,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.CompileExpression(String typeName, String methodName, ImmutableArray`1 aliases, CompilationTestData testData, DiagnosticBag diagnostics, ResultProperties& resultProperties)
	EvaluationContext.cs(244,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CompileExpression(String expr, DkmEvaluationFlags compilationFlags, ImmutableArray`1 aliases, DiagnosticBag diagnostics, ResultProperties& resultProperties, CompilationTestData testData)
	ExpressionCompilerTestHelpers.cs(223,0): at Microsoft.CodeAnalysis.ExpressionEvaluator.UnitTests.ExpressionCompilerTestHelpers.CompileExpression(EvaluationContextBase evaluationContext, String expr, DkmEvaluationFlags compilationFlags, ImmutableArray`1 aliases, DiagnosticFormatter formatter, ResultProperties& resultProperties, String& error, ImmutableArray`1& missingAssemblyIdentities, CultureInfo preferredUICulture, CompilationTestData testData)
	F:\GitHub\AlekseyTs\roslyn\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\DeclarationTests.cs(1496,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.UnitTests.DeclarationTests.CompileDeclaration(EvaluationContext context, String declaration, DkmClrCompilationResultFlags& flags, CompilationTestData& testData)
	F:\GitHub\AlekseyTs\roslyn\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\DeclarationTests.cs(164,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.UnitTests.DeclarationTests.<>c.<ExpressionLocals_ExpressionStatement_02>b__2_0(RuntimeInstance runtime)
	ExpressionCompilerTestBase.cs(66,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.UnitTests.ExpressionCompilerTestBase.WithRuntimeInstance(Compilation compilation, IEnumerable`1 references, Boolean includeLocalSignatures, Action`1 validator)
	ExpressionCompilerTestBase.cs(52,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.UnitTests.ExpressionCompilerTestBase.WithRuntimeInstance(Compilation compilation, Action`1 validator)
	F:\GitHub\AlekseyTs\roslyn\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\DeclarationTests.cs(158,0): at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.UnitTests.DeclarationTests.ExpressionLocals_ExpressionStatement_02()
```

**Comment by gafter** [comment]
@jcouv I think the placeholders were added recently for deconstruction. Why do we have a new rewriter pass?

**Comment by gafter** [comment]
@AlekseyTs Blocked on missing test case.

**Comment by AlekseyTs** [comment]
@gafter 
> @jcouv I think the placeholders were added recently for deconstruction. Why do we have a new rewriter pass?

This isn't related to deconstruction work. PlaceholderLocalRewriter is part of ExpressionEvaluator and it is not new. Since BoundDeclarationPattern node represents a reference to a local, it has to handle this node specially, but it doesn't at the moment.

**Comment by AlekseyTs** [comment]
@gafter The test case has been submitted in #13183
