### ISSUE TITLE
RenameOverloadsCSharp test failed once in CI

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn#13186]
This looks like an intermittent failure. It passed on retest in #13137

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/2494/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/InlineRenameTests/RenameOverloadsCSharp/

```
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.InlineRenameTests.RenameOverloadsCSharp (from Roslyn.Services.Editor.UnitTests2) 

Assert.Equal() Failure (pos 3)
Expected: barfoo
Actual: bar

STACK TRACE:

at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTestHelpers.VB$StateMachine_8_VerifyTagsAreCorrect.MoveNext() 
  in q:\roslyn\src\EditorFeatures\Test2\Rename\RenameTestHelpers.vb:line 87 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.InlineRenameTests.VB$StateMachine_4_VerifyRenameOptionChangedSessionCommit.MoveNext() 
  in q:\roslyn\src\EditorFeatures\Test2\Rename\InlineRenameTests.vb:line 120
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.InlineRenameTests.VB$StateMachine_5_RenameOverloadsCSharp.MoveNext() 
  in q:\roslyn\src\EditorFeatures\Test2\Rename\InlineRenameTests.vb:line 152
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by rchande** [comment]
Artifacts are gone. Closing,

**Comment by jasonmalinowski** [comment]
This also failed in our signed build: https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=526226&tab=ms.vss-test-web.test-result-details

**Comment by jasonmalinowski** [comment]
And again: https://devdiv.visualstudio.com/DevDiv/_build?buildId=605723&tab=ms.vss-test-web.test-result-details&_a=summary. @Pilchie and @dpoeschl can we get the test disabled or looked at?

**Comment by JoeRobich** [comment]
Closing as there are no recent issues with this

**Comment by jasonmalinowski** [comment]
Reopening -- there are no recent issues with this since the test is still skipped.

**Comment by JoeRobich** [comment]
Thanks! I've been trying to leave the skipped issues open, but I missed this one.
