### ISSUE TITLE
VB tuples: CreateTupleTypeSymbol crashes with a crafted error underlying type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13277]
```VB
  <Fact>
        Public Sub CreateTupleTypeSymbol_UnderlyingTypeIsError()

            Dim comp = VisualBasicCompilation.Create("test", references:={MscorlibRef})

            Dim intType As TypeSymbol = comp.GetSpecialType(SpecialType.System_Int32)
            Dim vt2 = comp.CreateErrorTypeSymbol(Nothing, "ValueTuple", 2).Construct(intType, intType)

            Dim tuple = comp.CreateTupleTypeSymbol(vt2, Nothing)

        End Sub
```

```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTuples.CreateTupleTypeSymbol_UnderlyingTypeIsError' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	Symbols\NamedTypeSymbol.vb(1253,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.IsTupleCompatible(Int32& tupleCardinality)
	Compilation\VisualBasicCompilation.vb(2616,0): at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CommonCreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames)
	Compilation\Compilation.cs(849,0): at Microsoft.CodeAnalysis.Compilation.CreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames)
	CodeGen\CodeGenTuples.vb(2424,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTuples.CreateTupleTypeSymbol_UnderlyingTypeIsError()
```

Found this while investigating https://github.com/dotnet/roslyn/issues/13042 (the refactoring unittest would hit this when the ValueTuple type would not be present)

**Comment by jcouv** [comment]
FYI @VSadov

**Comment by VSadov** [comment]
There is no crash any more, so the test can simply be enabled.
Since it is a test only issue, it is not needed for RC.
