### ISSUE TITLE
Compiler crashes when using patterns with type name: Unexpected value 'TypeExpression' of type 'BoundKind'

### ISSUE THREAD

**Issue by Eyas** [dotnet/roslyn#13316]
**Version Used**: Visual Studio "15" Previews 3 & 4

**Steps to Reproduce**:

I uncovered this during a typo. Attempt to compile this code:

```cs
using System;

namespace CS7
{
    class T1 { int a; }
    class Program
    {
        static void Main(string[] args)
        {
            if (T1 is object i)
            {
                Console.WriteLine($"Writing O {i}.");
            }
            else { Console.WriteLine($"Writing Not O."); }
        }

    }
}
```

**Expected Behavior**: Compiles successfully.

**Actual Behavior**: Exception thrown:

```
"csc.exe" exited with code -2146232797

Unhandled Exception: System.InvalidOperationException: Unexpected value 'TypeExpression' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAsExpression(BoundAsOperator asOp, Boolean used)
```

**Comment by weitzhandler** [comment]
For a reason I can't reproduce, I'm having the same issue when trying to compile the [corefx](/dotnet/corefx) repo.

I tried reinstalling .NET Core and .NET Framework, but that wasn't much of help.
Anything to try, please?
