### ISSUE TITLE
VS2015 crash due to unhandled System.InvalidCastException (Nightly Build 2.0.0.6082601)

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/roslyn#13360]
VS2015 crashes when opening one of our solutions. Reproduceable with nightly build 2.0.0.6082501, but visual studio does not provide any more information, why and on which file this exception occurs.

```
Anwendung: devenv.exe
Frameworkversion: v4.0.30319
Beschreibung: Die Anwendung forderte die Beendigung des Prozesses durch System.Environment.FailFast(Zeichenfolgenmeldung) an.
Meldung: System.InvalidCastException: Das Objekt des Typs "WithThreeChildren" kann nicht in Typ "Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CSharpSyntaxNode" umgewandelt werden.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxTokenWithTrivia..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxTokenWithTrivia.<>c.<GetReader>b__5_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.CreateInstance(Type type)
   at Roslyn.Utilities.ObjectReader.ReadReadableObject()
   at Roslyn.Utilities.ObjectReader.ReadObject(DataKind kind)
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.UsingDirectiveSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.UsingDirectiveSyntax.<>c.<GetReader>b__27_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.CreateInstance(Type type)
   at Roslyn.Utilities.ObjectReader.ReadReadableObject()
   at Roslyn.Utilities.ObjectReader.ReadObject(DataKind kind)
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildrenBase..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithManyChildren.<>c.<GetReader>b__3_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.CreateInstance(Type type)
   at Roslyn.Utilities.ObjectReader.ReadReadableObject()
   at Roslyn.Utilities.ObjectReader.ReadObject(DataKind kind)
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax..ctor(ObjectReader reader)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax.<>c.<GetReader>b__27_0(ObjectReader r)
   at Roslyn.Utilities.ObjectReader.CreateInstance(Type type)
   at Roslyn.Utilities.ObjectReader.ReadReadableObject()
   at Roslyn.Utilities.ObjectReader.ReadObject(DataKind kind)
   at Roslyn.Utilities.ObjectReader.ReadValue()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.DeserializeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.DeserializeNodeFrom(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.RecoverRoot(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.Recover(CancellationToken cancellationToken)
   at Roslyn.Utilities.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.RecoverableSyntaxTree.GetRoot(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetRootCore(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.PositionalSyntaxReference.GetSyntax(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.MergedTypeDeclaration.GetAttributeDeclarations()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributesBag()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributes()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.get_IsExplicitDefinitionOfNoPiaLocalType()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(NamespaceSymbol ns)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(NamespaceSymbol ns)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(NamespaceSymbol ns)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(NamespaceSymbol ns)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.get_ContainsExplicitDefinitionOfNoPiaLocalTypes()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.MightContainNoPiaLocalTypes()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.AssemblyDataForCompilation.get_ContainsNoPiaLocalTypes()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ReuseAssemblySymbolsWithNoPiaLocalTypes(BoundInputAssembly[] boundInputs, TAssemblySymbol[] candidateInputAssemblySymbols, ImmutableArray`1 assemblies, Int32 corLibraryIndex)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.Bind(TCompilation compilation, ImmutableArray`1 explicitAssemblies, ImmutableArray`1 explicitModules, ImmutableArray`1 explicitReferences, ImmutableArray`1 explicitReferenceMap, MetadataReferenceResolver resolverOpt, MetadataImportOptions importOptions, Boolean supersedeLowerVersions, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& allAssemblies, ImmutableArray`1& implicitlyResolvedReferences, ImmutableArray`1& implicitlyResolvedReferenceMap, DiagnosticBag resolutionDiagnostics, Boolean& hasCircularReference, Int32& corLibraryIndex)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Compilation compilation, List`1 newReferences, Dictionary`2 metadataReferenceToProjectId)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__34.MoveNext()
Stapel:
   bei System.Environment.FailFast(System.String, System.Exception)
   bei Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   bei Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   bei Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<FinalizeCompilationAsync>d__34.MoveNext()
   bei Roslyn.Utilities.AsyncLazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValue(System.Threading.CancellationToken)
   bei Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValue(System.Threading.CancellationToken)
   bei Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory+CSharpSyntaxTreeFactoryService+RecoverableSyntaxTree.GetRoot(System.Threading.CancellationToken)
   bei Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetRootCore(System.Threading.CancellationToken)
   bei Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory+CSharpSyntaxTreeFactoryService+PositionalSyntaxReference.GetSyntax(System.Threading.CancellationToken)
   bei Microsoft.CodeAnalysis.CSharp.MergedTypeDeclaration.GetAttributeDeclarations()
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributesBag()
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributes()
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.get_IsExplicitDefinitionOfNoPiaLocalType()
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol)
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol)
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol)
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.NamespaceContainsExplicitDefinitionOfNoPiaLocalTypes(Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol)
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.get_ContainsExplicitDefinitionOfNoPiaLocalTypes()
   bei Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.MightContainNoPiaLocalTypes()
   bei Microsoft.CodeAnalysis.CSharp.CSharpCompilation+ReferenceManager+AssemblyDataForCompilation.get_ContainsNoPiaLocalTypes()
   bei Microsoft.CodeAnalysis.CommonReferenceManager`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ReuseAssemblySymbolsWithNoPiaLocalTypes(BoundInputAssembly<System.__Canon,System.__Canon>[], System.__Canon[], System.Collections.Immutable.ImmutableArray`1<AssemblyData<System.__Canon,System.__Canon>>, Int32)
   bei Microsoft.CodeAnalysis.CommonReferenceManager`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Bind(System.__Canon, System.Collections.Immutable.ImmutableArray`1<AssemblyData<System.__Canon,System.__Canon>>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.PEModule>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.MetadataReference>, System.Collections.Immutable.ImmutableArray`1<ResolvedReference<System.__Canon,System.__Canon>>, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.MetadataImportOptions, Boolean, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<ReferencedAssemblyIdentity<System.__Canon,System.__Canon>>>, System.Collections.Immutable.ImmutableArray`1<AssemblyData<System.__Canon,System.__Canon>> ByRef, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.MetadataReference> ByRef, System.Collections.Immutable.ImmutableArray`1<ResolvedReference<System.__Canon,System.__Canon>> ByRef, Microsoft.CodeAnalysis.DiagnosticBag, Boolean ByRef, Int32 ByRef)
   bei Microsoft.CodeAnalysis.CSharp.CSharpCompilation+ReferenceManager.CreateAndSetSourceAssemblyFullBind(Microsoft.CodeAnalysis.CSharp.CSharpCompilation)
   bei Microsoft.CodeAnalysis.CSharp.CSharpCompilation+ReferenceManager.CreateSourceAssemblyForCompilation(Microsoft.CodeAnalysis.CSharp.CSharpCompilation)
   bei Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(Microsoft.CodeAnalysis.MetadataReference)
   bei Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(Microsoft.CodeAnalysis.MetadataReference)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Microsoft.CodeAnalysis.Compilation, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.MetadataReference>, System.Collections.Generic.Dictionary`2<Microsoft.CodeAnalysis.MetadataReference,Microsoft.CodeAnalysis.ProjectId>)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<FinalizeCompilationAsync>d__34.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<GetMetadataReferenceAsync>d__38.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task.FinishStageTwo()
   bei System.Threading.Tasks.Task.Finish(Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.SolutionState+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(CompilationInfo)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.SolutionState+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SetResult(CompilationInfo)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<GetOrBuildCompilationInfoAsync>d__26.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.SolutionState+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(CompilationInfo)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.SolutionState+CompilationTracker+CompilationInfo, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SetResult(CompilationInfo)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<BuildCompilationInfoFromScratchAsync>d__28.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bei Microsoft.CodeAnalysis.SolutionState+CompilationTracker+<BuildDeclarationCompilationFromScratchAsync>d__29.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bei Microsoft.CodeAnalysis.DocumentState+<GetSyntaxTreeAsync>d__38.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bei System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bei Roslyn.Utilities.AsyncLazy`1+Request[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteFromTaskSynchronously(System.Threading.Tasks.Task`1<System.__Canon>)
   bei Roslyn.Utilities.AsyncLazy`1+Request[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteFromTaskSynchronouslyStub(System.Object)
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
   bei System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by gafter** [comment]
Is this reproducible with a recent VS2017?

**Comment by gafter** [comment]
Closing as not reproducible. Please let us know if you can indeed reproduce this with a recent VS.
