### ISSUE TITLE
NullReferenceException in LocalRewriter when using incomplete ValueTuple

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#13365]
**Version Used**: master

**Steps to Reproduce**:

Write [the following code in Try Roslyn](http://tryroslyn.azurewebsites.net/#b:master/HYQwtgpgzgDiDGEAEBlAnlALhMAoA3rksUjAK4BGANgJbxJYBOZ8mSAaiFWRACpkwqEADy8AjABokvAEwA+IiUIkVpSrXqdufAUIAU4pDWxhJ0mUZMyAlEnwBfXAEhHj3KEiwEydFhwA6ACUyYEwaSH8AYQB7MBgaIUYUCEYANzpoAkVicmo6JHgqECgoaV0IAFEhSFCAOXBoAEFMTEYaCjJsJAAuJGbW9s6IbLsRlVyNMsFK6og6hqh+to7sPSYaYABzAG0AXSRWkGAoADNoxjB6z1sHEddcXAn8wuLSyKzx9Xy9DbYADykvyQaFsAHEIJgYucACYbEDYKB6WwAXjkSD0AAYJBjrABuEYjJ70VLRGjQpAABTaoShjFhoARSJGylUxB+oSQAKMHJBSGRSHBkOiMLhjLxYxIqRAjAYfKQABIAER6fB/exSfBoezWRX4lT2Yi4exAA):

```c#
namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public ValueTuple(T1 item1, T2 item2) {}
	}
}

namespace System.Runtime.CompilerServices
{
    public class TupleElementNamesAttribute : Attribute
    {
        public TupleElementNamesAttribute(string[] transformNames) {}
    }
}

public class C
{
    public (int x, int y) GetCoordinates() => (0,0);
    
    public void PrintCoordinates()
    {
        (int x, int y) = GetCoordinates();
        var s = $"({x}, {y})";
    }  
}
```

**Expected Behavior**:

The compiler reports errors, probably:

> Error CS8128: Member 'Item1' was not found on type 'ValueTuple<T1, T2>' from assembly 'Test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
> Error CS8128: Member 'Item2' was not found on type 'ValueTuple<T1, T2>' from assembly 'Test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Actual Behavior**:

A `NullReferenceException` is thrown:

```
error : Object reference not set to an instance of an object.
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.AccessTupleFields(BoundDeconstructionAssignmentOperator node, BoundDeconstructionDeconstructStep deconstruction, ArrayBuilder`1 temps, ArrayBuilder`1 stores, ArrayBuilder`1 placeholders) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_DeconstructionAssignmentOperator.cs:line 182
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.ApplyDeconstructions(BoundDeconstructionAssignmentOperator node, ArrayBuilder`1 temps, ArrayBuilder`1 stores, ArrayBuilder`1 placeholders, BoundExpression loweredRight) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_DeconstructionAssignmentOperator.cs:line 56
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitDeconstructionAssignmentOperator(BoundDeconstructionAssignmentOperator node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_DeconstructionAssignmentOperator.cs:line 25
 at Microsoft.CodeAnalysis.CSharp.BoundDeconstructionAssignmentOperator.Accept(BoundTreeVisitor visitor) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs:line 1230
 at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 147
 at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\BoundTree\BoundTreeRewriter.cs:line 96
 at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 225
 at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 206
 at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\BoundTree\BoundTreeRewriter.cs:line 91
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 177
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpression(BoundExpression node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 151
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_ExpressionStatement.cs:line 97
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitLocalDeconstructionDeclaration(BoundLocalDeconstructionDeclaration node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_ExpressionStatement.cs:line 42
 at Microsoft.CodeAnalysis.CSharp.BoundLocalDeconstructionDeclaration.Accept(BoundTreeVisitor visitor) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs:line 1179
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 140
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Block.cs:line 24
 at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs:line 2387
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 140
 at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, Boolean instrumentForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawLocalFunctions, Boolean& sawAwaitInExceptionHandler) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 94
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1202
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 992
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 433
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 323
 at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
 at System.Threading.Tasks.Task.InnerInvoke()
 at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 238
 at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 137
 at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2335
 at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1905
 at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\dotnet\Src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1853
 at TryRoslyn.Core.Processing.CodeProcessor.Process(String code, ProcessingOptions options) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!sites\dotnet-master\Core\Processing\CodeProcessor.cs:line 44
 at TryRoslyn.Web.Api.Controllers.RoslynController.Compilation(CompilationArguments arguments) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!sites\dotnet-master\Web.Api\Controllers\RoslynController.cs:line 18
 at lambda_method(Closure , Object , Object[] )
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

---

The errors in "Expected Behavior" are already correctly reported in [the following case](http://tryroslyn.azurewebsites.net/#b:master/HYQwtgpgzgDiDGEAEBlAnlALhMAoA3rksUjAK4BGANgJbxJYBOZ8mSAaiFWRACpkwqEADy8AjABokvAEwA+IiUIkVpSrXqdufAUIAU4pDWxhJ0mUZMyAlEnwBfRcUePc5anSTwqIKFCQAwgROah70AG4A9jQAJkgAsnrWIcqqxHo0wGwAHlKZbGi2ALxIegAMEmXWANwhKuEgjAxIJQAkAER6+Nn2Uvho9tbttSr2xLj2QA=):

```c#
namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public ValueTuple(T1 item1, T2 item2) {}
    }
}

public class C
{
    public void M()
    {
        (int x, int y) = (0,0);
        var s = $"({x}, {y})";
    }  
}
```

**Comment by jcouv** [comment]
Thanks @svick for reporting the problem. Fixed with https://github.com/dotnet/roslyn/pull/13463
