### ISSUE TITLE
IlasmUtilities can cause unhandled exception when cleaning up temps

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#13626]
See https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=316944&_a=summary&tab=ms.vss-test-web.test-result-details

```
Stack trace
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.Dispose() in D:\A\_work\19\s\src\Test\Utilities\Shared\TempFiles\DisposableFile.cs:line 25
at Microsoft.CodeAnalysis.Test.Utilities.IlasmUtilities.IlasmTempAssembly(String declarations, Boolean appendDefaultHeader, Boolean includePdb, String& assemblyPath, String& pdbPath) in D:\A\_work\19\s\src\Test\Utilities\Desktop\IlasmUtilities.cs:line 95
at Microsoft.CodeAnalysis.Test.Utilities.IlasmUtilities.CreateTempAssembly(String declarations, Boolean appendDefaultHeader) in D:\A\_work\19\s\src\Test\Utilities\Desktop\IlasmUtilities.cs:line 16
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateReferenceFromIlCode(String ilSource, Boolean appendDefaultHeader, ImmutableArray`1& ilImage) in D:\A\_work\19\s\src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb:line 380
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithCustomILSource(XElement sources, String ilSource, VisualBasicCompilationOptions options, IEnumerable`1& spans, Boolean includeVbRuntime, Boolean includeSystemCore, Boolean appendDefaultHeader, VisualBasicParseOptions parseOptions, MetadataReference& ilReference, ImmutableArray`1& ilImage) in D:\A\_work\19\s\src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb:line 373
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Symbols.Metadata.PE.LoadingOperators.Import2()
```

**Comment by jasonmalinowski** [comment]
This broke another build: https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=321217&tab=ms.vss-test-web.test-result-details

**Comment by jasonmalinowski** [comment]
@jaredpar can we get this bug triaged out?

**Comment by jaredpar** [comment]
@TyOverby please take a look at this.

**Comment by jasonmalinowski** [comment]
And another one: https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=322995&tab=ms.vss-test-web.test-result-details

**Comment by jaredpar** [comment]
The relevant error text is the following:

``` txt
System.IO.IOException : The process cannot access the file 'C:\Users\dlab\AppData\Local\Temp\RoslynTests\_0_3c52f167-6aaa-49bb-96c0-d9ff7e493b08.il' because it is being used by another process.
```

Did someone turn on a virus checker in the build lab?

**Comment by agocke** [comment]
I haven't seen this since I added the additional verification. I'm going to close it until I see it again.
