### ISSUE TITLE
expression-bodied ctor fails to generate call to base()

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13691]
The following test fails on the `features/exprbody` branch:

```cs
        [Fact]
        public void RunCtorProp()
        {
            string source = @"
using System;
public class Program 
{
    static void Main()
    {
        var p = new Program();
        p.Prop = 2;
    }
    Program() => Console.Write(1);
    int Prop { set => Console.Write(value); }
    ~Program() => Console.Write(string.Empty);
}
";
            CompileAndVerify(source, expectedOutput: "12");
        }
```

with

```none
Test 'Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.Semantics.ExpressionBodiedMemberTests.RunCtorProp' failed: Microsoft.CodeAnalysis.Test.Utilities.PeVerifyException : 
PeVerify failed for assembly 'C:\Users\ngafter\AppData\Local\Temp\':
[ : Program::.ctor][mdToken=0x6000002][offset 0x00000006] Return from .ctor when this is uninitialized.


	RuntimeAssemblyManager.cs(471,0): at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
	at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
	HostedRuntimeEnvironment.cs(304,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.PeVerify()
	CommonTestBase.CompilationVerifier.cs(99,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, EmitOptions emitOptions, Boolean peVerify, SignatureDescription[] expectedSignatures)
	D:\Roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(212,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Boolean verify)
	D:\Roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(135,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, EmitOptions emitOptions, Boolean verify)
	D:\Roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(89,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String[] sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Boolean verify)
	D:\Roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(53,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Boolean verify)
	D:\Roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(81,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Boolean verify)
	Semantics\ExpressionBodiedMemberTests.cs(366,0): at Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.Semantics.ExpressionBodiedMemberTests.RunCtorProp()
```

**Comment by gafter** [comment]
@lachbaer Can you work on fixing these issues? I'll check in the tests shortly.

**Comment by lachbaer** [comment]
Yes,I'll work on it, but probably not before Sep. 13th

**Comment by gafter** [comment]
Thanks!

**Comment by gafter** [comment]
@lachbaer I'll work on these.

**Comment by lachbaer** [comment]
@gafter just started on it yesterday, let's see who's first ;-) No, not really. By now I don't have a clue where to start...

**Comment by lachbaer** [comment]
@gafter 
I think the problem might be in `MethodCompiler.cs` line 1594
```C#
        else if (sourceMethod.IsExpressionBodied)
                {
                    var methodSyntax = sourceMethod.SyntaxNode;
                    var arrowExpression = methodSyntax.GetExpressionBodySyntax();

                    Binder binder = factory.GetBinder(arrowExpression);
                    binder = new ExecutableCodeBinder(arrowExpression, sourceMethod, binder);
                    importChain = binder.ImportChain;
                    // Add locals
                    return binder.BindExpressionBodyAsBlock(arrowExpression, diagnostics);
```
because of the `return` it doesn't reach line 1614
```C#
            var constructorInitializer = BindConstructorInitializerIfAny(method, compilationState, diagnostics);
```
