### ISSUE TITLE
expression-bodied dtor fails to generate call to ~base()

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13692]
The following test fails on the `features/exprbody` branch:

```cs
        [Fact]
        public void ExpressionBodiedClassDestructor()
        {
            var text = @"
using System;

public class Base
{
    ~Base() => Console.WriteLine(""~Base"");
}

public class Program
{
    public static void Main()
    {
        Base b = new Base();
        b = null;
        GC.Collect(GC.MaxGeneration);
        GC.WaitForPendingFinalizers();
    }
}
";
            var validator = GetDestructorValidator("Base");
            var compVerifier = CompileAndVerify(text,
                sourceSymbolValidator: validator,
                symbolValidator: validator,
                expectedOutput: @"~Base",
                expectedSignatures: new[]
                {
                    Signature("Base", "Finalize", ".method family hidebysig virtual instance System.Void Finalize() cil managed")
                });

            compVerifier.VerifyIL("Base.Finalize", @"
{
  // Code size       20 (0x14)
  .maxstack  1
  .try
  {
    IL_0000:  ldstr      ""~Base""
    IL_0005:  call       ""void System.Console.WriteLine(string)""
    IL_000a:  leave.s    IL_0013
  }
  finally
  {
    IL_000c:  ldarg.0
    IL_000d:  call       ""void object.Finalize()""
    IL_0012:  endfinally
  }
  IL_0013:  ret
}
");
        }
```

with

```none
------ Test started: Assembly: Roslyn.Compilers.CSharp.Emit.UnitTests.dll ------

Unknown .NET Framework Version: v4.6
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.DestructorTests.ExpressionBodiedClassDestructor' failed: 
Expected:
{
  // Code size       20 (0x14)
  .maxstack  1
  .try
  {
    IL_0000:  ldstr      ""~Base""
    IL_0005:  call       ""void System.Console.WriteLine(string)""
    IL_000a:  leave.s    IL_0013
  }
  finally
  {
    IL_000c:  ldarg.0
    IL_000d:  call       ""void object.Finalize()""
    IL_0012:  endfinally
  }
  IL_0013:  ret
}
Actual:
{
  // Code size       11 (0xb)
  .maxstack  1
  IL_0000:  ldstr      ""~Base""
  IL_0005:  call       ""void System.Console.WriteLine(string)""
  IL_000a:  ret
}
Differences:
    {
++>   // Code size       11 (0xb)
-->   // Code size       20 (0x14)
      .maxstack  1
++>   IL_0000:  ldstr      ""~Base""
++>   IL_0005:  call       ""void System.Console.WriteLine(string)""
++>   IL_000a:  ret
-->   .try
-->   {
-->     IL_0000:  ldstr      ""~Base""
-->     IL_0005:  call       ""void System.Console.WriteLine(string)""
-->     IL_000a:  leave.s    IL_0013
-->   }
-->   finally
-->   {
-->     IL_000c:  ldarg.0
-->     IL_000d:  call       ""void object.Finalize()""
-->     IL_0012:  endfinally
-->   }
-->   IL_0013:  ret
    }

Expected: True
Actual:   False
	D:\Roslyn\src\Test\Utilities\Shared\Assert\AssertEx.cs(340,0): at Roslyn.Test.Utilities.AssertEx.AssertEqualToleratingWhitespaceDifferences(String expected, String actual, Boolean escapeQuotes, String expectedValueSourcePath, Int32 expectedValueSourceLine)
	CommonTestBase.CompilationVerifier.cs(187,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.VerifyILImpl(String qualifiedMethodName, String expectedIL, Boolean realIL, String sequencePoints, String callerPath, Int32 callerLine, Boolean escapeQuotes)
	CommonTestBase.CompilationVerifier.cs(157,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.VerifyIL(String qualifiedMethodName, String expectedIL, Boolean realIL, String sequencePoints, String callerPath, Int32 callerLine)
	CodeGen\DestructorTests.cs(110,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.DestructorTests.ExpressionBodiedClassDestructor()

0 passed, 1 failed, 0 skipped, took 4.02 seconds (xUnit.net 2.1.0 build 3179).
```

**Comment by gafter** [comment]
This failure occurs even when the base call is explicit:

```cs
        [Fact]
        public void RunCtorWithBase02()
        {
            string source = @"
using System;
public class Base
{
    Base(int i) { Console.Write(i); }
}
public class Program : Base
{
    static void Main()
    {
        var p = new Program();
    }
    Program() : base(1) => Console.Write(2);
}
";
            CompileAndVerify(source, expectedOutput: "12");
        }
```

**Comment by gafter** [comment]
@lachbaer Can you work on fixing these issues? I'll check in the tests shortly.

**Comment by gafter** [comment]
@lachbaer I'll work on these.

**Comment by lachbaer** [comment]
`MethodCompiler.cs` line 1557:
```C#
               if (blockSyntax != null)
                {
                    var inMethodBinder = factory.GetBinder(blockSyntax);

                    var binder = new ExecutableCodeBinder(blockSyntax, sourceMethod, inMethodBinder);
                    body = (BoundBlock)binder.BindEmbeddedBlock(blockSyntax, diagnostics);
                    importChain = binder.ImportChain;

                    if (method.MethodKind == MethodKind.Destructor)
                    {
                        return MethodBodySynthesizer.ConstructDestructorBody(method, body);
                    }
```
If case of an expression body this `if`-Block does not get called.
