### ISSUE TITLE
Crash in move type to file

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#13969]
**Steps to Reproduce**:

1. Move nested type to file 

**Expected Behavior**:

Move to file works

**Actual Behavior**:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.RemoveNode(SyntaxNode root,SyntaxNode node,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.RemoveChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.AddNewDocumentWithSingleTypeDeclarationAndImportsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.GetOperationsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass15_0.<GetPreviewOperationsAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass26_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by Pilchie** [comment]
Can you take a look and see how common this is?  This is a new feature in P5, it would be nice to not have it break every time...

**Comment by balajikris** [comment]
some notes: 
```C#
// remove things that are not being moved, from the forked document.
var membersToRemove = GetMembersToRemove(root);
foreach (var member in membersToRemove)
{
    documentEditor.RemoveNode(member, SyntaxRemoveOptions.KeepNoTrivia);
}
```

audit [this code](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs#L84). If `GetMembersToRemove` returns members that are not present in the tree, then the `documentEditor` would probably throw. One way that it can return members that are not present, is that if it returns duplicate members, the member would have been removed the first time and when we try to remove it the second time, that'd throw. Just a guess, I didn't see this happen under the debugger.

**Comment by CyrusNajmabadi** [comment]
To repro this, you need a sibling type with a nested type within.  We'll try to remove both the sibling and the nested type.  I don't think that's common enough to warrant Preview5.  But that's just me.

**Comment by Pilchie** [comment]
Agreed.
