### ISSUE TITLE
NRE in InvokeDelegateWithConditionalAccessAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#14002]
**Version Used**: 25722.00

**Steps to Reproduce**:
1. Install today's ML branch drop (25722.00)
2. Open VS and enable full solution analysis for C# from Tools Options
3. Open Roslyn.sln and open some source file from CSharpCodeAnalysis.csproj to prioritize analysis on the project.
4. Wait for analysis/error list.

I get the below AD0001 diagnostics in the error list:

```
Severity    Code    Description Project File    Line    Suppression State   Detail Description
Error   AD0001  Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.   CSharpCodeAnalysis      1   Active  Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp
SyntaxTree: C:\roslyn\src\Compilers\CSharp\Portable\Parser\LexerCache.cs
SyntaxNode: if (kind == SyntaxKind.None) { kind ... [IfStatementSyntax]@[881..1066) (21,32)-(24,33)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
Error   AD0001  Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.   CSharpSyntaxGenerator       1   Active  Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: CSharpSyntaxGenerator
SyntaxTree: C:\roslyn\src\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\TestWriter.cs
SyntaxNode: if (!first) { WriteLine(); } [IfStatementSyntax]@[2641..2724) (75,16)-(78,17)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by CyrusNajmabadi** [comment]
@mavasani do you have a dump when this happens?  All it gives above is a method that a null ref happens in.  That's fairly vague.

**Comment by mavasani** [comment]
I don't have a dump, but the repro is pretty trivial as soon as you get a latest ML drop - you just need to attach a debugger and set a breakpoint [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1148).

**Comment by CyrusNajmabadi** [comment]
We are reporting watsons for these, correct?

**Comment by CyrusNajmabadi** [comment]
I can't repro this at all.  i did both 'full solution analysis' and i just went to the two files where we got the excpetion reported in your case.  In neither case did i have an exception.  I validated that things work fine on the syntax nodes in question in your report. 

So something is happening strange on your machine that isn't happening on mine.  Can you attempt to repro locally and tell me where the actual null ref is?  With a method this large, it's just impossible to try to in down with no more info and no local repro.

**Comment by mavasani** [comment]
I am unable to repro this anymore.
