### ISSUE TITLE
ForEach parser throws NullReferenceException

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#14067]
**Version Used**: 2.0.0.60923

**Steps to Reproduce**:

1.  Create a new ConsoleApplication, paste code from #14064 in there. (I do not have saving new projects enabled, but presumably that does not matter.)
2. Put cursor on the `public string Name { get; set; }` line and keep pressing Alt+Up to move the line up.
3. Once you reach this state, Visual Studio crashes:
```C#
            foreach (var name in names)
        public string Name { get; set; }
```
with
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.GreenNode.AdjustFlagsAndWidth(GreenNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ForEachStatementSyntax..ctor(SyntaxKind kind, SyntaxToken forEachKeyword, SyntaxToken openParenToken, TypeSyntax type, SyntaxToken identifier, SyntaxToken inKeyword, ExpressionSyntax expression, SyntaxToken closeParenToken, StatementSyntax statement, SyntaxFactoryContext context)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseForEachStatement()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseForOrForEachStatement()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementNoDeclaration(Boolean allowAnyExpression)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore()
...
```

**Comment by gafter** [comment]
I was not able to repro this in master. I'll try update 5.

**Comment by gafter** [comment]
I am able to repro this in update 5.

**Comment by gafter** [comment]
This was fixed in master in #13924.

/cc @VSadov Should the fix be ported to update 5?

**Comment by MattGertz** [comment]
@gafter @VSadov Help me understand the types of the customer scenarios that could trigger this.

**Comment by gafter** [comment]
@MattGertz This can occur during typing in the presence of syntax errors. It doesn't occur often, but when it occurs the symptom is a crash.

**Comment by MattGertz** [comment]
@gafter @VSadov For Shiproom, we'd need to understand how/when it regressed and what we will do to plug up the test hole (which info may already be in #13924, perhaps).  The bar is sky-high today, but sounds like we should take it.  Please work with @natidea.

**Comment by VSadov** [comment]
Is seems that the regression could be introduced in ed1335cb, so it is not very old.

Now that we have more evidence that the crash scenario is, while relatively uncommon, is bad enough to cause grief, we should try porting it.

**Comment by gafter** [comment]
Declined by shiproom for preview 5, and already fixed in RC.

**Comment by miloush** [comment]
Not that it would matter, but this can be hit by much more common edits, such as enclosing foreach in another one, or adding method calls (such as Where) to the enumerated variable.

Anyway, I have hit what I believe is the same bug but for the **if** statement. Let me know if this is a different one and should be filed separately:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.GreenNode.AdjustFlagsAndWidth(GreenNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.IfStatementSyntax..ctor(SyntaxKind kind, SyntaxToken ifKeyword, SyntaxToken openParenToken, ExpressionSyntax condition, SyntaxToken closeParenToken, StatementSyntax statement, ElseClauseSyntax else, SyntaxFactoryContext context)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseIfStatement()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementNoDeclaration(Boolean allowAnyExpression)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatements(CSharpSyntaxNode& previousNode, SyntaxListBuilder`1 statements, Boolean stopOnSwitchSections)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlock(Boolean isMethodBody, Boolean isAccessorBody)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAccessorDeclaration(Boolean isEvent, Boolean& hasGetOrAdd, Boolean& hasSetOrRemove)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAccessorList(Boolean isEvent)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParsePropertyDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind, String typeName)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind, String typeName)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceDeclaration()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__15.MoveNext()
```
