### ISSUE TITLE
Immediate crash when trying to create a new project with Preview5.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14089]
Looking up the stack, it looks like FileKey is: {'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll'@5/28/2014 11:35:42 AM}

VS hits this then immediately closes.  

Stack is: 

```
System.ArgumentException: Assembly must have at least one module.
Parameter name: modules
   at Microsoft.CodeAnalysis.AssemblyMetadata.Create(ImmutableArray`1 modules)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReferenceManager.CreateAssemblyMetadata(FileKey fileKey, ModuleMetadata manifestModule, List`1 storages, Func`3 moduleMetadataFactory)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReferenceManager.TryCreateAssemblyMetadataFromMetadataImporter(FileKey fileKey, AssemblyMetadata& metadata)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReferenceManager.GetMetadata(String fullPath, DateTime snapshotTimestamp)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReference.Snapshot.GetMetadataImpl()
   at Microsoft.CodeAnalysis.PortableExecutableReference.GetMetadataNoCopy()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetMetadata(PortableExecutableReference peReference, CommonMessageProvider messageProvider, Location location, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBoundReferenceManager()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.Compilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.HasMissingReferences(Compilation compilation, IReadOnlyList`1 metadataReferences)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__34.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
FYI @Pilchie

**Comment by gafter** [comment]
This is preventing dogfooding and ad-hoc testing.

**Comment by Pilchie** [comment]
Now that this is unblocked - can we have a test of this scenario please?
