### ISSUE TITLE
Crash with OOP while doing local development.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14107]
Stack:

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> StreamJsonRpc.RemoteInvocationException: Request locate failed with message: Cannot find service module info file '*/snapshotService.servicehub.service.json' in 'C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\common7\ServiceHub\Services', using discovery services failed: VsixServiceDiscovery: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ServiceHub.VsixServiceDiscovery.ExternalSettingsManager.CreateExternalSettingsManager(String appIdPath, String rootSuffix)
   at Microsoft.ServiceHub.VsixServiceDiscovery.ExtensionEnumerator.EnumerateContentLocations(ExtensionEnumerationOptions options)
   at Microsoft.ServiceHub.VsixServiceDiscovery.DiscoveryService.EnsureServiceModulesEnumerated()
   at Microsoft.ServiceHub.VsixServiceDiscovery.DiscoveryService.discoverService(String serviceName)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__56`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang @panopticoncentral @srivatsn 

This is synced to a recent master, and just hitting F5 to launch a fresh RoslynDev hive.

**Comment by heejaechang** [comment]
which vs drop? preview 5?

**Comment by CyrusNajmabadi** [comment]
Yes.  Preview5.

**Comment by heejaechang** [comment]
interesting. it failed to discover json file installed through vsix.

can you set this set SERVICEHUBTRACELEVEL=Verbose and run devenv from that command prompt and see %temp%\servicehub\logs to see what has failed.

**Comment by heejaechang** [comment]
I dont see this happening. please re-open if it still repro.
