### ISSUE TITLE
Rename local variable that matches tuple name does not behave very rationally

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14116]
**Steps to Reproduce**:
1.  Create a new C# project
2.  Have some code like:

``` C#
var tuple = (number: 5, greeting: "Hello");
var number = tuple.number;
var greeting = tuple.greeting;
```
1. select `greeting` in variable `var greeting`
2. attempt to rename `greeting`

**Expected Behavior**:
Inline rename is offered

**Actual Behavior**:
Visual Studio Crashes

```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<>c__DisplayClass3_0.<ComputeDeclarationConflictsAsync>b__0(SyntaxToken t) in D:\A\_work\24\s\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 814
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConflictsAsync>d__3.MoveNext() in D:\A\_work\24\s\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 814
```

**Comment by Pilchie** [comment]
Can you take a look at this since @jcouv is OOF?

**Comment by VSadov** [comment]
The scenario is no longer causing a crash (so moving out of RC). 
The behavior is still not very rational. It looks like the local declaration is assumed as declaring location for a tuple element. 

It seems we have a more broad issue with declaring syntax for tuple elements (tracked by https://github.com/dotnet/roslyn/issues/14600 ). 

Once that is fixed, this scenario may or may not start working correctly. It is, however, not a crash.

**Comment by VSadov** [comment]
related to https://github.com/dotnet/roslyn/issues/14600
