### ISSUE TITLE
Move Type crash

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#14125]
In a file named Program.cs
```C#
namespace N { class C { } }
namespace N2 { class C2 { } }
```

Try to Move Type on C
<details>
    <summary>Stack trace</summary>
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.RemoveNode(SyntaxNode root,SyntaxNode node,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.RemoveChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.AddNewDocumentWithSingleTypeDeclarationAndImportsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.GetOperationsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass15_0.<GetPreviewOperationsAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass26_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
</details>

**Comment by CyrusNajmabadi** [comment]
Fixed with 8b85e2ecba5bed8ebab11d6e0031e7d9b33a9f71
