### ISSUE TITLE
Microsoft.Net.Compilers package is broken due to missing Facades.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#14248]
The Microsoft.Net.Compilers package is currently broken due to missing Facades. Attempting to build using the latest Microsoft.Net.Compilers package on MyGet currently results in the following:

```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.FileVersionInfo, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

This is currently blocking one of our repositories.

**Comment by tannergooding** [comment]
FYI. @ManishJayaswal for the blocking aspect. This is preventing us from creating integration tests. This is also preventing us from moving to new bits (such as the ones that will contain https://github.com/dotnet/roslyn/issues/13722). We will not be able to insert until this is resolved.
