### ISSUE TITLE
Crash in Completion when displaying tuple types

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#14272]
Type `Do1` at the $$ and wait for the completion list tooltip to show for Do1.

``` C#
class Program
{
    static void Main(string[] args)
    {
        $$
    }

    static void Do1((string, int) a) { }
}
```

```
System.ArgumentException: The underlying type for a tuple must be tuple-compatible.
Parameter name: underlyingType
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonCreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames) in F:\roslyn-internal\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2769
   at Microsoft.CodeAnalysis.Compilation.CreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames) in F:\roslyn-internal\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 846
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.<>c__DisplayClass2_0.<Resolve>b__0(INamedTypeSymbol t) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.TupleTypeSymbolKey.cs:line 37
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.SymbolKey.CreateSymbolInfo(IEnumerable`1 symbols) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 171
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(SymbolKeyReader reader) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.TupleTypeSymbolKey.cs:line 38
10/4/2016 2:17:09 PM
Source: First chance exception: Microsoft.CodeAnalysis.CSharp
StackTrace:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonCreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames) in F:\roslyn-internal\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2769
   at Microsoft.CodeAnalysis.Compilation.CreateTupleTypeSymbol(INamedTypeSymbol underlyingType, ImmutableArray`1 elementNames) in F:\roslyn-internal\Open\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 846
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.<>c__DisplayClass2_0.<Resolve>b__0(INamedTypeSymbol t) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.TupleTypeSymbolKey.cs:line 37
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.SymbolKey.CreateSymbolInfo(IEnumerable`1 symbols) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.cs:line 171
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(SymbolKeyReader reader) in F:\roslyn-internal\Open\src\Workspaces\Core\Portable\SymbolKey\SymbolKey.TupleTypeSymbolKey.cs:line 38
```

**Comment by AlekseyTs** [comment]
I can repro the ArgumentException only when ValueTuple types are not available. However, it looks like 
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader reader) function is prepared to deal with this situation, it catches the exception and performs the necessary error recovery.

The Compilation.CreateTupleTypeSymbol throw this exception because the underlying type given to it is an error type without a namespace. This makes it tuple incompatible, it doesn’t pass the  qualified name test. The information that it is supposed to be in a System  namespace is “lost in translation” because there is no such namespace in the source module.

**Comment by AlekseyTs** [comment]
Resolving as Won't Fix
