### ISSUE TITLE
InvokeDelegateWithConditionalAccessAnalyzer throws exception analyzing if expressions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14322]
**Version Used**: Preview 5 (25725.00)

```
Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'
'Exception occurred with following context:
SyntaxNode: if (attr != null && attr.KeyPreserveCase ... [IfStatementSyntax]@[2258..2388) (57,16)-(59,17)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

```
Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.' 
'Exception occurred with following context:
SyntaxNode: if (attr != null && attr.KeyPreserveCase ... [IfStatementSyntax]@[2258..2388) (57,16)-(59,17)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
'Exception occurred with following context:
SyntaxNode: if (_contentLoaded) { return; } ... [IfStatementSyntax]@[1741..1802) (50,12)-(52,13)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.InvokeDelegateWithConditionalAccess.InvokeDelegateWithConditionalAccessAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by CyrusNajmabadi** [comment]
Can you link me to the dumps for these?  The stack and exception here are too vague to narrow this down to whatever the problem is.

**Comment by Pilchie** [comment]
Is this the options related NullReferenceException from out of proc serialization?
