### ISSUE TITLE
CSharpUseObjectInitializerDiagnosticAnalyzer throws exception analyzing object creation expressions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14323]
**Version Used**: Preview 5 (25725.00)

```
Analyzer 'Microsoft.CodeAnalysis.CSharp.UseObjectInitializer.CSharpUseObjectInitializerDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
'Exception occurred with following context:
SyntaxNode: new ServiceProvider() [ObjectCreationExpressionSyntax]@[401..422) (14,27)-(14,48)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.UseObjectInitializer.AbstractUseObjectInitializerDiagnosticAnalyzer`7.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

```
Analyzer 'Microsoft.CodeAnalysis.CSharp.UseObjectInitializer.CSharpUseObjectInitializerDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
'Exception occurred with following context:
SyntaxNode: new Settings() [ObjectCreationExpressionSyntax]@[927..941) (17,128)-(17,142)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.UseObjectInitializer.AbstractUseObjectInitializerDiagnosticAnalyzer`7.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by Pilchie** [comment]
Another options NullRef?
