### ISSUE TITLE
Compiler assertion when foreach iterator variable is captured in lambda expression  and foreach statement doesn't use braces for body

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn#1443]
Compile the following code:

```
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
    public static void Main()
    {
        IList<string> list1 = null;

        foreach (string list1Item in list1)
            Foo(() => list1Item == null);
    }

    static void Foo(Func<bool> func) { }
}
```

EXPECTED: Code compiles successfully
ACTUAL: UnexpectedValue Assert/Exception

This doesn't repro for me with the CTP6 compilers, but does when I compile the code from GitHub, so it appears to be a recent regression.

Here's the stack trace:

```
Unexpected value 'ExpressionStatement' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind'

   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o) in C:\git\roslyn\src\Compilers\Core\Portable\InternalUtilities\ExceptionUtilities.cs:line 13
   at Microsoft.CodeAnalysis.CSharp.LambdaFrame.AssertIsClosureScopeSyntax(CSharpSyntaxNode syntaxOpt) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaFrame.cs:line 90
   at Microsoft.CodeAnalysis.CSharp.LambdaFrame..ctor(VariableSlotAllocator slotAllocatorOpt, MethodSymbol topLevelMethod, MethodDebugId methodId, CSharpSyntaxNode scopeSyntaxOpt, Int32 closureOrdinal) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaFrame.cs:line 40
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.GetFrameForScope(BoundNode scope, ArrayBuilder`1 closureDebugInfo) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 312
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.MakeFrames(ArrayBuilder`1 closureDebugInfo) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 28
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean assignLocals) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 219
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1192
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 955
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 440
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 341
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\git\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by gafter** [comment]
@tmat I believe you've been changing this area recently?
