### ISSUE TITLE
TestPreviewDiagnosticTaggerInPreviewPane is flakey

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#14444]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/1039/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Preview/PreviewWorkspaceTests/TestPreviewDiagnosticTaggerInPreviewPane/

Stacktrace

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: 1\r\nActual: 0
+++++++++++++++++++
STACK TRACE:
 at Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests.<TestPreviewDiagnosticTaggerInPreviewPane>d__9.MoveNext() in q:\roslyn\src\EditorFeatures\Test\Preview\PreviewWorkspaceTests.cs:line 268
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Pilchie** [comment]
Is the same root cause as https://github.com/dotnet/roslyn/issues/10916 (which I am woefully behind in investigating)?

**Comment by CyrusNajmabadi** [comment]
Still flakey

**Comment by Pilchie** [comment]
@CyrusNajmabadi could you link to the Jenkins job where this failed again, so that I can take a look and if the failure was the same?

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only, moving this out (again) to get this off the radar, but we really need to figure this out.
