### ISSUE TITLE
Compiler crash when getting compeletion form method group

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#14546]
**Version Used**: 

Visual Studio 2015 Update 3

Commit ded36f8ac5d67fbb3da8e4199dbe4a8069d9c1d3 (latest)

**Steps to Reproduce**:

1.  Type `new object().ToString.`

**Expected Behavior**:

Anything reasonable.

**Actual Behavior**:

Visual Studio crashed.

**Stack Trace**:

````
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.SuppressDefaultTupleElements(INamespaceOrTypeSymbol container, ImmutableArray`1 symbols)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsOffOfBoundExpression(CSharpSyntaxContext context, ExpressionSyntax originalExpression, ExpressionSyntax expression, SymbolInfo leftHandBinding, INamespaceOrTypeSymbol container, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsOffOfExpression(CSharpSyntaxContext context, ExpressionSyntax originalExpression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsOffOfContainer(CSharpSyntaxContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsWorker(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetRecommendedSymbolsAtPositionWorkerAsync(Workspace workspace, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.<GetRecommendedSymbolsAtPositionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Recommendations.Recommender.<GetImmutableRecommendedSymbolsAtPositionAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetCompletionListAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__13.MoveNext()
````

**Comment by Pilchie** [comment]
Moving to @VSadov since @jcouv is out right now.

**Comment by VSadov** [comment]
fixed by https://github.com/dotnet/roslyn/pull/14589
