### ISSUE TITLE
Crash during Inline Rename conflict detection in VB

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#14554]
_Reported via Visual Studio Feedback_

**Steps to Reproduce**:
1. Start with the following code.

``` VB
Public MustInherit Class Base
    Public MustOverride Function Close() As Boolean
    Public MustOverride Function Save() As Boolean
End Class

Public Class Crasher
    Sub New(a As Action)
    End Sub
End Class

Public Class Other
    Inherits Base

    Public Sub New(vm As Base)
        Me.Vm = vm
    End Sub

    Public ReadOnly Property Vm As Base

    Public ReadOnly Property Crash As New Crasher(Sub()
                                                      Vm.Close()
                                                  End Sub)
    Public Overrides Function Close() As Boolean
        Return False
    End Function

    Public Overrides Function Save() As Boolean
        Return False
    End Function
End Class

Public Class Tester
    Inherits Base

    Public Overrides Function Close() As Boolean
        Return False
    End Function

    Public Overrides Function Save() As Boolean
        Return False
    End Function
End Class
```
1. Invoke Inline Rename (<kbd>F2</kbd> or <kbd>Ctrl+R, R</kbd>) on `Tester.Close()`
2. Rename `Close` to `Save`

**Expected Behavior**: An unresolvable conflict is reported

**Actual Behavior**: VS crashes

**Comment by dpoeschl** [comment]
A couple of assertions

```
   at Microsoft.CodeAnalysis.VisualBasic.Utilities.SpeculationAnalyzer.CreateSpeculativeSemanticModelForNode(SyntaxNode nodeToSpeculate, SemanticModel semanticModel, Int32 position, Boolean isInNamespaceOrTypeContext)

   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.GetSemanticModelForNode(SyntaxNode node, SemanticModel originalSemanticModel)

   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode)

   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMultiLineLambdaExpression(MultiLineLambdaExpressionSyntax nod......

<truncated>
```

```
expanding a syntax node which cannot be speculated?



   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode)

   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMultiLineLambdaExpression(MultiLineLambdaExpressionSyntax node)

   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MultiLineLambdaExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)

   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)

   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visi......

<truncated>
```

And then a null reference:

```
   at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel, SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Simplification.SimplificationHelpers.GetOriginalSymbolInfo(SemanticModel semanticModel, SyntaxNode expression)
   at Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expander.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expander.VisitExpressionStatement(ExpressionStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expander.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Simplification.VisualBasicSimplificationService.Expand(SyntaxNode node, SemanticModel semanticModel, SyntaxAnnotation aliasReplacementAnnotation, Func`2 expandInsideNode, Boolean expandParameter, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMultiLineLambdaExpression(MultiLineLambdaExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MultiLineLambdaExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitSimpleArgument(SimpleArgumentSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleArgumentSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ArgumentListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitAsNewClause(AsNewClauseSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AsNewClauseSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitPropertyStatement(PropertyStatementSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.AnnotateAndRename(RenameRewriterParameters parameters)
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__27.MoveNext()
```

**Comment by dpoeschl** [comment]
Simpler repro
```C#
Class C
    Sub New(a As Action)
    End Sub

    Public ReadOnly Property Vm As C

    Public ReadOnly Property Crash As New C(Sub()
                                                Vm.Close()
                                            End Sub)

    Public Function Close() As Boolean
        Return False
    End Function

    Public Function Save() As Boolean
        Return False
    End Function
End Class
```

**Comment by dpoeschl** [comment]
Getting rid of `Vm` and just calling `Close()` in `Crash` causes lots of asserts but no crash.
