### ISSUE TITLE
Crash in find references

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#14653]
*Repro:* find references in CodeStyleOptions.cs, PreferIntrinsicPredefinedTypeKeywordInDeclaration.

```
System.ArgumentOutOfRangeException: ''end' must not be less than 'start''
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start, Int32 end)
   at Microsoft.VisualStudio.LanguageServices.FindReferences.StreamingFindReferencesPresenter.TableDataSourceFindReferencesContext.FillInClassifiedSpanGaps(SourceText sourceText, Int32 startPosition, IEnumerable`1 classifiedSpans)
   at Microsoft.VisualStudio.LanguageServices.FindReferences.StreamingFindReferencesPresenter.TableDataSourceFindReferencesContext.MergeClassifiedSpans(List`1 syntaxSpans, List`1 semanticSpans, TextSpan widenedSpan, SourceText sourceText)
   at Microsoft.VisualStudio.LanguageServices.FindReferences.StreamingFindReferencesPresenter.TableDataSourceFindReferencesContext.<GetTaggedTextForReferenceAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.FindReferences.StreamingFindReferencesPresenter.TableDataSourceFindReferencesContext.<CreateDocumentLocationEntryAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.FindReferences.StreamingFindReferencesPresenter.TableDataSourceFindReferencesContext.<OnEntryFoundAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

@CyrusNajmabadi is already looking. FYI to @pilchie as this is with the build we just RIed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14655
