### ISSUE TITLE
Optional value in VB operator causes crash

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#14688]
Consider the following code:

``` vb
    Public Class Foo
        Public Shared Operator Not(Optional x As Foo) As Foo
        End Operator
    End Class
```

This will cause an exception and VS crash.  I believe it's illegal for optional to be in operators.  Either way though this should not crash VS.

**Comment by OmarTawfik** [comment]
Crash below:
`System.InvalidOperationException: Unexpected value 'OperatorStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.CreateBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, Binder containingBinder)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position, Binder containingBinder)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.VisitParameter(ParameterSyntax node)
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterSyntax.Accept[TResult](VisualBasicSyntaxVisitor1 visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.MakeBinder(SyntaxNode node, Int32 position)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderAtOrAbove(SyntaxNode node, Int32 position)
   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForPosition(SyntaxNode node, Int32 position)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(Int32 position)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(ExpressionSyntax node, SymbolInfoOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNameSyntax(NameSyntax node, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode(SyntaxNode syntax, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNodeOrToken(SyntaxNodeOrToken nodeOrToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, List1 list, Func2 getNodeClassifiers, Func2 getTokenClassifiers, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, Func2 getNodeClassifiers, Func2 getTokenClassifiers, List1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()`
