### ISSUE TITLE
[Test Failure] BasicWinForms failed in windows_vsi_p1_open_prtest on PR #14824

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#14833]
Following 2 vsi tests failed in windows_vsi_p1_open_prtest on PR #14824 
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/550/

BasicWinForms.Add a Click() Handler
BasicWinForms.Rename the control

```
Start - list of failing integration tests:
08:22:41 BasicWinForms.xml
08:22:41 End - list of failing integration tests.
08:22:42 VS integration tests failed
08:22:42 ================================================================================
08:22:42 Dumping the log file for the last TAO test.  It may or may not include a failure.
08:22:42 ================================================================================
08:22:42 Test: CSharpBraceHighlighting started: 10/31/2016 3:22:36 PM
08:22:42 	Executing action [10/31/2016 3:22:36 PM] StartTarget
08:22:42 Begin Waiting for Apex Communication
08:22:42 	Executing action [10/31/2016 3:22:36 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:22:46 PM] AddItem
08:22:42 	Executing action [10/31/2016 3:22:46 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:22:46 PM] SetEditorText
08:22:42  Scenario: [
08:22:42 	Executing action [10/31/2016 3:22:46 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:22:46 PM] VerifyBraceHighlightTags
08:22:42 	Executing action [10/31/2016 3:22:47 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:22:47 PM] VerifyBraceHighlightTags
08:22:42  Scenario: ]
08:22:42 	Executing action [10/31/2016 3:22:47 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:22:47 PM] VerifyBraceHighlightTags
08:22:42 	Executing action [10/31/2016 3:22:47 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:22:47 PM] VerifyBraceHighlightTags
08:22:42 	Executing action [10/31/2016 3:22:47 PM] CloseTarget
08:22:42 Test finished: 10/31/2016 3:22:48 PM
08:22:42 	Executing action [10/31/2016 3:22:48 PM] CloseTarget
08:22:42 Closing VS. force Close = True, closeVsToFreeHandles = False
08:22:42 	  Cleared VS MEF Component Cache.
08:22:42 
08:22:42 ================================================================================
08:22:42 Dumping logs of all failed TAO tests.
08:22:42 ================================================================================
08:22:42 ================================================================================
08:22:42  Dumping log file d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\BasicWinForms.txt
08:22:42 Test: BasicWinForms started: 10/31/2016 3:18:42 PM
08:22:42 	Executing action [10/31/2016 3:18:42 PM] StartTarget
08:22:42 Begin Waiting for Apex Communication
08:22:42  Scenario: Test My IntelliSense
08:22:42 	Executing action [10/31/2016 3:18:42 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:18:45 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:18:45 PM] SetEditorText
08:22:42 	Executing action [10/31/2016 3:18:45 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:18:45 PM] SendKeys
08:22:42 	Executing action [10/31/2016 3:18:48 PM] VerifyCompletionList
08:22:42 	Executing action [10/31/2016 3:18:48 PM] SendKeys
08:22:42 	Executing action [10/31/2016 3:18:48 PM] VerifyCompletionList
08:22:42 	Executing action [10/31/2016 3:18:49 PM] CloseSolution
08:22:42  Scenario: Bug 586849 - GTD on My.Forms.FormName
08:22:42 	Executing action [10/31/2016 3:18:49 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:18:49 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:18:49 PM] SetEditorText
08:22:42 	Executing action [10/31/2016 3:18:50 PM] PlaceCursor
08:22:42 	Executing action [10/31/2016 3:18:50 PM] GoToDefinition
08:22:42 	Executing action [10/31/2016 3:18:50 PM] VerifyCaretPosition
08:22:42 	Executing action [10/31/2016 3:18:50 PM] CloseSolution
08:22:42  Scenario: Add a control
08:22:42 	Executing action [10/31/2016 3:18:50 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:18:51 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:18:51 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:18:51 PM] Build
08:22:42 Waiting for Roslyn features SolutionCrawler: 10/31/2016 3:18:59 PM
08:22:42 Waiting for Roslyn features ErrorList: 10/31/2016 3:19:04 PM
08:22:42 Finished waiting for Roslyn features SolutionCrawler and ErrorList: 10/31/2016 3:19:04 PM
08:22:42 Waiting for error list: 10/31/2016 3:19:06 PM
08:22:42 Finished waiting for error list: 10/31/2016 3:19:08 PM
08:22:42 	Executing action [10/31/2016 3:19:10 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:10 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:10 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:10 PM] CloseSolution
08:22:42  Scenario: Add a Click() Handler
08:22:42 	Executing action [10/31/2016 3:19:10 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:19:11 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:11 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:19:11 PM] WinFormsEditControlEvent
08:22:42 		Handler 'ExecuteWhenButtonClicked' added for event 'Click' successfully.
08:22:42 	Executing action [10/31/2016 3:19:11 PM] ExecuteCommand
08:22:42 	Executing action [10/31/2016 3:19:11 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:11 PM] VerifyEditorContainsText
08:22:42 --------------------------------
08:22:42 System.Exception: Actual and expected items don't match:
08:22:42 Expected: Private Sub ExecuteWhenButtonClicked(sender As Object, e As EventArgs) Handles SomeButton.Click
08:22:42 
08:22:42     End Sub
08:22:42 Actual: Public Class Form1
08:22:42 
08:22:42 End Class
08:22:42 
08:22:42 
08:22:42    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
08:22:42    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
08:22:42    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
08:22:42 ================================
08:22:42 
08:22:42 
08:22:42 Saved screenshot: d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-10-31_15-19-11_46 - Exception System.Reflection.TargetInvocationException.png
08:22:42 	Executing action [10/31/2016 3:19:11 PM] CloseSolution
08:22:42  Scenario: Rename the control
08:22:42 	Executing action [10/31/2016 3:19:12 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:19:12 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:12 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:19:12 PM] WinFormsEditControlProperty
08:22:42 		Property 'Text' changed to 'ButtonTextValue' successfully.
08:22:42 	Executing action [10/31/2016 3:19:12 PM] WinFormsEditControlEvent
08:22:42 		Handler 'SomeButtonHandler' added for event 'Click' successfully.
08:22:42 	Executing action [10/31/2016 3:19:12 PM] WinFormsEditControlProperty
08:22:42 		Property 'Name' changed to 'SomeNewButton' successfully.
08:22:42 	Executing action [10/31/2016 3:19:12 PM] Build
08:22:42 Waiting for Roslyn features SolutionCrawler: 10/31/2016 3:19:13 PM
08:22:42 Waiting for Roslyn features ErrorList: 10/31/2016 3:19:18 PM
08:22:42 Finished waiting for Roslyn features SolutionCrawler and ErrorList: 10/31/2016 3:19:18 PM
08:22:42 Waiting for error list: 10/31/2016 3:19:20 PM
08:22:42 Finished waiting for error list: 10/31/2016 3:19:22 PM
08:22:42 	Executing action [10/31/2016 3:19:24 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:24 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:24 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:24 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:24 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:24 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:24 PM] VerifyEditorContainsText
08:22:42 --------------------------------
08:22:42 System.Exception: Actual and expected items don't match:
08:22:42 Expected: Private Sub SomeButtonHandler(sender As Object, e As EventArgs) Handles SomeNewButton.Click
08:22:42 Actual: Public Class Form1
08:22:42 
08:22:42 End Class
08:22:42 
08:22:42 
08:22:42    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
08:22:42    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
08:22:42    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
08:22:42 ================================
08:22:42 
08:22:42 
08:22:42 Saved screenshot: d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-10-31_15-19-24_79 - Exception System.Reflection.TargetInvocationException.png
08:22:42 	Executing action [10/31/2016 3:19:24 PM] CloseSolution
08:22:42  Scenario: Remove event handler
08:22:42 	Executing action [10/31/2016 3:19:24 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:19:25 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:25 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:19:25 PM] WinFormsEditControlEvent
08:22:42 		Handler 'FooHandler' added for event 'Click' successfully.
08:22:42 	Executing action [10/31/2016 3:19:25 PM] WinFormsEditControlEvent
08:22:42 		Handler '' added for event 'Click' successfully.
08:22:42 	Executing action [10/31/2016 3:19:25 PM] ExecuteCommand
08:22:42 	Executing action [10/31/2016 3:19:25 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:25 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:25 PM] CloseSolution
08:22:42  Scenario: Change Accessibility
08:22:42 	Executing action [10/31/2016 3:19:25 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:19:26 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:26 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:19:26 PM] WinFormsEditControlProperty
08:22:42 		Property 'Modifiers' changed to 'Public' successfully.
08:22:42 	Executing action [10/31/2016 3:19:26 PM] Build
08:22:42 Waiting for Roslyn features SolutionCrawler: 10/31/2016 3:19:27 PM
08:22:42 Waiting for Roslyn features ErrorList: 10/31/2016 3:19:32 PM
08:22:42 Finished waiting for Roslyn features SolutionCrawler and ErrorList: 10/31/2016 3:19:32 PM
08:22:42 Waiting for error list: 10/31/2016 3:19:34 PM
08:22:42 Finished waiting for error list: 10/31/2016 3:19:36 PM
08:22:42 	Executing action [10/31/2016 3:19:38 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:38 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:38 PM] CloseSolution
08:22:42  Scenario: Delete a control
08:22:42 	Executing action [10/31/2016 3:19:38 PM] AddProject
08:22:42 	Executing action [10/31/2016 3:19:39 PM] OpenFile
08:22:42 DEBUG: found and activated window.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:39 PM] WinFormsAddControl
08:22:42 		Control 'SomeButton' added successfully.
08:22:42 	Executing action [10/31/2016 3:19:39 PM] WinFormsDeleteControl
08:22:42 		Control 'SomeButton' deleted successfully.
08:22:42 	Executing action [10/31/2016 3:19:39 PM] Build
08:22:42 Waiting for Roslyn features SolutionCrawler: 10/31/2016 3:19:40 PM
08:22:42 Waiting for Roslyn features ErrorList: 10/31/2016 3:19:44 PM
08:22:42 Finished waiting for Roslyn features SolutionCrawler and ErrorList: 10/31/2016 3:19:44 PM
08:22:42 Waiting for error list: 10/31/2016 3:19:46 PM
08:22:42 Finished waiting for error list: 10/31/2016 3:19:48 PM
08:22:42 	Executing action [10/31/2016 3:19:50 PM] OpenFile
08:22:42 DEBUG: executed DTE command File.OpenFile.
08:22:42 DEBUG: start polling for code window
08:22:42 DEBUG: polling complete
08:22:42 	Executing action [10/31/2016 3:19:50 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:50 PM] VerifyEditorContainsText
08:22:42 	Executing action [10/31/2016 3:19:50 PM] CloseSolution
08:22:42 	Executing action [10/31/2016 3:19:51 PM] CloseTarget
08:22:42 Test finished: 10/31/2016 3:19:51 PM
08:22:42 	Executing action [10/31/2016 3:19:51 PM] CloseTarget
08:22:42 Closing VS. force Close = True, closeVsToFreeHandles = False
08:22:42 	  Cleared VS MEF Component Cache.
08:22:42 
08:22:42 ================================================================================
08:22:42  Dumping log file d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\VSIntegrationTestLogs\TaoStartup.txt
08:22:42 Created screenshots folder: d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\Screenshots
08:22:42 Saved screenshot: d:\j\workspace\windows_vsi_p---9a06aa34\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-10-31_15-09-47_18 - Verifying Screenshot Reliability.png
08:22:42 
08:22:42 BUILD WARNINGS for d:\j\workspace\windows_vsi_p---9a06aa34\Roslyn.sln
08:22:42 15:08:29.148   148>C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\j\workspace\windows_vsi_p---9a06aa34\Closed\Hosting\RoslynTaoActions\RoslynTaoActions.csproj]
08:22:42 ===============================================
08:22:42 There were failures, see red messages above :-(
08:22:42 ===============================================
```

**Comment by jmarolf** [comment]
Hit this today
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_dev15_p1_open_prtest/20/ 
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_dev15_p1_open_prtest/21/

**Comment by Pilchie** [comment]
We won't fix this Escrow without understanding the customer scenario.

**Comment by Pilchie** [comment]
This test has been replaced. Closing
