### ISSUE TITLE
[Test Failure] CSharpVenus -  Generate Type Into App_Code Folder failed in  windows_vsi_p3_open_prtest #14889

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#14894]
CSharpVenus - Scenario: Generate Type Into App_Code Folder failed in #14889

```
Scenario: Generate Type Into App_Code Folder
    Executing action [11/2/2016 3:19:24 PM] OpenFile
DEBUG: executed DTE command File.OpenFile.
DEBUG: start polling for code window
DEBUG: polling complete
    Executing action [11/2/2016 3:19:24 PM] OpenFile
DEBUG: executed DTE command File.OpenFile.
DEBUG: start polling for code window
DEBUG: polling complete
    Executing action [11/2/2016 3:19:24 PM] SetEditorText
    Executing action [11/2/2016 3:19:25 PM] WaitForWorkspace
    Executing action [11/2/2016 3:19:25 PM] WaitForFeature
    Executing action [11/2/2016 3:19:30 PM] WaitForFeature
    Executing action [11/2/2016 3:19:30 PM] PlaceCursor
    Executing action [11/2/2016 3:19:30 PM] WaitForFeature
    Executing action [11/2/2016 3:19:30 PM] VerifyCodeActions
--------------------------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: No Active Smart Tags in View!  Buffer content type=CSharp
   at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass50_0.<VerifyCodeActions>b__0() in d:\j\workspace\windows_vsi_p---ee5cdb44\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 255
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values) in f:\dd\src\omni\Apex\Framework\Hosts\Services\UIThreadInvoker\UIThreadInvokerHelper.cs:line 118
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
================================


Saved screenshot: d:\j\workspace\windows_vsi_p---ee5cdb44\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2016-11-02_15-19-50_83 - Exception System.Reflection.TargetInvocationException.png

    Executing action [11/2/2016 3:19:50 PM] CloseFile
    Executing action [11/2/2016 3:19:50 PM] SetFeatureOption
    Executing action [11/2/2016 3:19:51 PM] CloseTarget
```
![csharpvenus](https://cloud.githubusercontent.com/assets/788783/19940440/e7b7f296-a0e9-11e6-9f3d-b538e5693139.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen issues here in years.
