### ISSUE TITLE
SyntaxTree serialization fails trying to write VB date time literal

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#14943]
This code:

Public Class C
    Private _x As DateTime = #10/5/2015#
End Class

Causes this exception when the tree gets serialized:

System.InvalidOperationException: Cannot serialize type 'System.DateTime'.
   at Roslyn.Utilities.StreamObjectWriter.WriteObject(Object instance)
   at Roslyn.Utilities.StreamObjectWriter.WriteVariant(Variant value)
   at Roslyn.Utilities.StreamObjectWriter.Emit()
   at Roslyn.Utilities.StreamObjectWriter.WriteValue(Object value)
   at Microsoft.CodeAnalysis.SyntaxNode.SerializeTo(Stream stream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.<SaveAsync>d__6.MoveNext()

**Comment by Pilchie** [comment]
Can we get more details about when this happens?  @asecchia?

**Comment by mattwar** [comment]
How can it be more clear than the title of the issue?

**Comment by Pilchie** [comment]
How does a user experience this?  Does this crash VS whenever there is a VB file with a date constant?  Should this be in RC instead of RC2?

**Comment by mattwar** [comment]
The bug is caused by my recent change to the serializer that is in master and not in RC.

**Comment by Pilchie** [comment]
Ah, great!  Thanks!

**Comment by asecchia** [comment]
I opened roslyn.sln and VS crashed (failfast)

**Comment by mattwar** [comment]
@pilchie there is a nice PR here for you to green light #14944

**Comment by dpoeschl** [comment]
Reopening because this change was reverted as part of https://github.com/dotnet/roslyn/pull/15068

**Comment by dpoeschl** [comment]
FYI @mattwar

**Comment by mattwar** [comment]
This only failed because of the serialization changes you also rolled back.
