### ISSUE TITLE
StreamJsonRpc throws ObjectDisposedException and crashes VS

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#14940]
**Version Used**: d15prerel/15.0.25831.2

**Steps to Reproduce**:

1. clone https://github.com/icsharpcode/NRefactory.git 
2.  Checkout https://github.com/icsharpcode/NRefactory/commit/89ef9706523059f0a39b04b15ebcd4dea87e0e08
3.  Open NRefactory.sln
4. Set ICSharpCode.NRefactory.Cecil as the startup project
5. Make sure all projects have loaded if you have DPL turned on
6. Open ICSharpCode.NRefactory.Cecil\CecilLoader.cs
7. Scroll through applying refactoring and expanding regions

Eventually you will get a crash with the following stack:
```
Cannot access a disposed object.
Object name: 'StreamJsonRpc.JsonRpc'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message) in D:\A\_work\6\s\src\Microsoft.VisualStudio.Validation.Shared\Verify.cs:line 117
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__56`1.MoveNext() in E:\A\_work\20\s\src\StreamJsonRpc.Shared\JsonRpc.cs:line 438
   at Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcSession.<InitializeAsync>d__7.MoveNext() in E:\A\_work\4\s\src\VisualStudio\Core\Next\Remote\JsonRpcSession.cs:line 69
   at Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcSession.<CreateAsync>d__5.MoveNext() in E:\A\_work\4\s\src\VisualStudio\Core\Next\Remote\JsonRpcSession.cs:line 43
   at Microsoft.VisualStudio.LanguageServices.Remote.ServiceHubRemoteHostClient.<CreateServiceSessionAsync>d__6.MoveNext() in E:\A\_work\4\s\src\VisualStudio\Core\Next\Remote\ServiceHubRemoteHostClient.cs:line 85
   at Microsoft.CodeAnalysis.Remote.RemoteHostClient.<CreateServiceSessionAsync>d__6.MoveNext() in E:\A\_work\4\s\src\Workspaces\Core\Portable\Remote\RemoteHostClient.cs:line 39
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<AnalyzeOutOfProcAsync>d__5.MoveNext() in E:\A\_work\4\s\src\VisualStudio\Core\Def\Implementation\Diagnostics\VisualStudioDiagnosticAnalyzerExecutor.cs:line 89
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<AnalyzeAsync>d__4.MoveNext() in E:\A\_work\4\s\src\VisualStudio\Core\Def\Implementation\Diagnostics\VisualStudioDiagnosticAnalyzerExecutor.cs:line 59
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<AnalyzeAsync>d__19.MoveNext() in E:\A\_work\4\s\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 500
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDiagnosticsAsync>d__6.MoveNext() in E:\A\_work\4\s\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticIncrementalAnalyzer.Executor.cs:line 160
```

Dump at: \\mlangfs1\public\jmarolf\Dumps\RPC_Crash_FailFast.dmp

**Comment by Pilchie** [comment]
@srivatsn @heejaechang @MattGertz - This looks like the internal report we saw yesterday?

**Comment by MattGertz** [comment]
Also, this is marked as d15prerel -- is this also in d15rel?

**Comment by jmarolf** [comment]
@MattGertz retracing my steps on the original machine.  Once I get a set of repro steps I will try them on my d15rel machine

**Comment by heejaechang** [comment]
@MattGertz just want to let you know. I think we want to bring this to escrow.

**Comment by Pilchie** [comment]
I just hit this on today's d15rel build while dogfooding.

**Comment by MattGertz** [comment]
@Pilchie We'll need to move quickly then.

**Comment by natidea** [comment]
@heejaechang we can close this now
