### ISSUE TITLE
Visual Studio crashes due to end of stream exception

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#15031]
**Version Used**: d15rel/15.0.25903.2

**Steps to Reproduce**: 

No solid repro steps yet.  Will update will more precise steps when I have them

1. Checkout https://github.com/dotnet/roslyn
2. Open Roslyn.sln after restoring nuget packages
3. After editing files in multiple projects (and introducing errors in each project) VS crashes

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticResultSerializer.Deserialize(ObjectReader reader, DiagnosticDataSerializer serializer, Project project, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticResultSerializer.Deserialize(ObjectReader reader, IDictionary`2 analyzerMap, Project project, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<GetCompilerAnalysisResultAsync>d__8.MoveNext()
   at Microsoft.CodeAnalysis.Remote.Extensions.<InvokeAsync>d__1`1.MoveNext()
   at Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcSession.<InvokeAsync>d__11`1.MoveNext()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<AnalyzeOutOfProcAsync>d__5.MoveNext()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<AnalyzeAsync>d__4.MoveNext()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<AnalyzeAsync>d__19.MoveNext()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDiagnosticsAsync>d__6.MoveNext()
```

**Comment by alrz** [comment]
Same as #14887

**Comment by Pilchie** [comment]
Tagging @heejaechang  and @srivatsn

**Comment by heejaechang** [comment]
I think it is happening if stream closed in the middle of object reader/writer working on the stream. trying to repro.

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn/pull/15110
