### ISSUE TITLE
Possible DPL crash.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15044]
Was trying out DPL.  Reloaded a solution after git syncing.  VS crashed:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.Close()
   at Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavor.Dispose(Boolean)
   at Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavorBase.Dispose()
   at Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavorBase.Close()
   at Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.Close()
```

```
Faulting application name: devenv.exe, version: 15.0.25903.1, time stamp: 0x581bced5
Faulting module name: csproj.dll, version: 15.0.25903.1, time stamp: 0x581bd38a
Exception code: 0xc0000005
Fault offset: 0x00049e43
Faulting process id: 0x18d4
Faulting application start time: 0x01d238772245d20f
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC#\VCSPackages\csproj.dll
Report Id: 8834b8f4-365f-4cdf-9f53-c530a02794a8
Faulting package full name: 
Faulting package-relative application ID: 
```

Faulting module in csproj, making me think this is us.

```
Fault bucket 129164463681, type 5
Event Name: FaultTolerantHeap
Response: Not available
Cab Id: 0
```

```
Fault bucket 108519034425, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0
```

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @Pilchie

**Comment by AdamSpeight2008** [comment]
A fault in the 'FaultTolerantHeap` surely not?

**Comment by jasonmalinowski** [comment]
There's a good chance this is the null-ref bug that @Pilchie is working on. @CyrusNajmabadi did you capture the dump?

**Comment by CyrusNajmabadi** [comment]
No.  For some reason watson isn't uploading dumps for me.

**Comment by CyrusNajmabadi** [comment]
Stack is:

```
 	csproj.dll!CLangFileNode::ClearMsBuildItem() Line 64	C++
>	csproj.dll!CLangProject::RemoveMsBuildItemsFromFolderandFileNodes(CLangFolderNode * pFolder) Line 386	C++
 	csproj.dll!CLangProject::RemoveMsBuildItemsFromFolderandFileNodes(CLangFolderNode * pFolder) Line 393	C++
 	csproj.dll!CLangProject::OnCloseHierarchy() Line 362	C++
 	csproj.dll!CVsProject::OnCloseHierarchy() Line 304	C++
 	csproj.dll!CLangHierarchy::Close() Line 407	C++
 	csproj.dll!CVsProjHierarchy::Close() Line 175	C++
 	csproj.dll!CCSharpProjHierarchy::Close() Line 45	C++
 	msenv.dll!CProject::Close(int fRemoveProjectDir) Line 614	C++
 	msenv.dll!CSolution::RemoveProjectByCProject(CProject * pProject, int fUnloadProject, int nUnloadReasonID, unsigned long dwUnloadStatus) Line 21757	C++
 	msenv.dll!CSolution::RemoveProjectByHierarchy(IVsHierarchy * pHierarchy, int fUnloadProject) Line 21715	C++
 	msenv.dll!CSolution::CloseSolutionElement(unsigned long grfCloseOpts, IVsHierarchy * pHier, unsigned long docCookie) Line 5937	C++
 	msenv.dll!CSolutionItemsProject::CloseChildren() Line 12794	C++
 	msenv.dll!CProject::Close(int fRemoveProjectDir) Line 593	C++
 	msenv.dll!CSolution::RemoveProjectByCProject(CProject * pProject, int fUnloadProject, int nUnloadReasonID, unsigned long dwUnloadStatus) Line 21757	C++
 	msenv.dll!CSolution::RemoveProjectByHierarchy(IVsHierarchy * pHierarchy, int fUnloadProject) Line 21715	C++
 	msenv.dll!CSolution::CloseSolutionElement(unsigned long grfCloseOpts, IVsHierarchy * pHier, unsigned long docCookie) Line 5937	C++
 	msenv.dll!CSolutionItemsProject::CloseChildren() Line 12794	C++
 	msenv.dll!CProject::Close(int fRemoveProjectDir) Line 593	C++
 	msenv.dll!CSolution::RemoveProjectByCProject(CProject * pProject, int fUnloadProject, int nUnloadReasonID, unsigned long dwUnloadStatus) Line 21757	C++
 	msenv.dll!CSolution::RemoveProjectByHierarchy(IVsHierarchy * pHierarchy, int fUnloadProject) Line 21715	C++
 	msenv.dll!CSolution::CloseSolutionElement(unsigned long grfCloseOpts, IVsHierarchy * pHier, unsigned long docCookie) Line 5937	C++
 	msenv.dll!CSolution::ClearProjectsInternal(bool fSkipNested, std::set<CProject *,std::less<CProject *>,std::allocator<CProject *> > & projectsAlreadyClosed) Line 12444	C++
 	msenv.dll!CSolution::Clear(bool bClearProjects) Line 12217	C++
 	msenv.dll!CSolution::Close(int fDoSave, int fSaveAll, int fUpdateMRU) Line 18050	C++
 	msenv.dll!CSolution::CloseSolutionElement(unsigned long grfCloseOpts, IVsHierarchy * pHier, unsigned long docCookie) Line 5941	C++
 	msenv.dll!CSolution::UnloadReloadSolution() Line 18485	C++
 	msenv.dll!CSolution::TimerWndProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 3188	C++
 	msenv.dll!CSolution::StaticTimerWndProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 3080	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	
 	msenv.dll!SCMI::FPreTranslateMessage(tagMSG * pMsg) Line 226	C++
 	msenv.dll!SCM::FPushMessageLoop(SCMI * pscmi, unsigned long uReason, void * pvLoopData) Line 2262	C++
 	msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long dwComponentID, unsigned long uReason, void * pvLoopData) Line 2998	C++
 	msenv.dll!CMsoComponent::PushMsgLoop(unsigned long msgloop) Line 705	C++
 	msenv.dll!VStudioMainLogged() Line 1178	C++
 	msenv.dll!VStudioMain(MAINPARAM * pMainParam) Line 1259	C++
 	devenv.exe!00e1b8b6()	Unknown
 	devenv.exe!00e1b32f()	Unknown
 	devenv.exe!00e2f1d3()	Unknown
 	devenv.exe!00e2ecc3()	Unknown
 	[External Code]	
```

Tagging @jasonmalinowski @Pilchie

**Comment by CyrusNajmabadi** [comment]
Dump is at: "\\mlangfs1\public\cyrusn\Dumps\devenv.exe.68388.dmp"

**Comment by CyrusNajmabadi** [comment]
Code that is crashing is:

```c++
void CLangFileNode::ClearMsBuildItem()
{
     m_srpMSBuildItem = NULL;
}
```

Which indicates to me that the this pointer is bad.

This is called from code that looks like:

```c++
    CLangFileNode* pFileNode = pFolder->GetFirstFile(FALSE);
    while(pFileNode)
    {
        pFileNode->ClearMsBuildItem();
        pFileNode = pFolder->GetNextFile(pFileNode, FALSE);
    }
```

So the pFileNode is not null, but not valid either.  Yaay.

**Comment by Pilchie** [comment]
@srivatsn can you take this - it doesn't appear to have anything to do with DPL, but it's a native crash in csproj.dll

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2093
