### ISSUE TITLE
tagger causing vs to crash 

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15109]
version - latest master.
vs drop - ml25810.00

dump and bits in \\[mlangshare]\hechang\tagger

Callstack

...

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Should have been disposed!
DataSource-StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1..ctor(IForegroundNotificationService notificationService, ITextEditorFactoryService textEditorFactoryService, IEditorOptionsFactoryService editorOptionsFactoryService, IProjectionBufferFactoryService projectionBufferFactoryService, IEnumerable`1 asyncListeners)
   at Microsoft.CodeAnalysis.Editor.Structure.VisualStudio15StructureTaggerProvider..ctor(IForegroundNotificationService notificationService, ITextEditorFactoryService textEditorFactoryService, IEditorOptionsFactoryService editorOptionsFactoryService, IProjectionBufferFactoryService projectionBufferFactoryService, IEnumerable`1 asyncListeners)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Structure.OutliningBlockTaggerProvider.CreateTagger[T](ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManagerService.<>c__DisplayClass8_0.<GetOutliningManager>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManagerService.GetOutliningManager(ITextView textView)
   at Microsoft.VisualStudio.Text.Editor.Implementation.OutliningAdornmentManagerFactory.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView)
   at Microsoft.VisualStudio.Text.IntraTextAdornmentSupport.Implementation.IntraTextAdornmentSpaceNegotiatingTaggerProvider.<>c__DisplayClass5_0`1.<CreateTagger>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.IntraTextAdornmentSupport.Implementation.IntraTextAdornmentSpaceNegotiatingTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer..ctor(ITextView view, IViewTagAggregatorFactoryService tagAggregatorFactoryService)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer.<>c__DisplayClass4_0.<GetSequencer>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer.GetSequencer(ITextView view, IViewTagAggregatorFactoryService tagAggregatorFactoryService)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencerFactoryService.Create(ITextView view)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.PreOuterQueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsTrackSelectionExPrivate.Register()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConnectSelectionContext()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Activate()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_ActiveViewChanged(Object sender, ActiveViewChangedEventArgs e)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(View view, ActivationType type)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.ActiveViewDeferrer.DisposeManagedResources()
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Dispose()
   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.<>c__DisplayClass24_0.<LoadBinaryDocumentStates>b__0(VersionedBinaryReader VersionedBinaryReader)
   at Microsoft.VisualStudio.Utilities.VersionedBinaryReader.ReadVersioned(Int32 expectedVersion, ReadCallback callback, Boolean throwOnUnexpectedVersion)
   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.LoadBinaryDocumentStates(WindowManagerService windowManager, IStream comStream, Boolean isExternal)
   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.LoadDocumentStates(WindowManagerService windowManager, IStream comStream, Boolean isExternal)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.<>c__DisplayClass173_0.<LoadDocumentStates>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Action method, Boolean reportError)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.LoadDocumentStates(IStream stream, Int32 fExternal)
   at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(String verb, Object pvaIn, Object& pvaOut)
   at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.DebugRecordInitialStackTrace()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagger[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousTaggerProvider`1.CreateTagger[T](ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.ITaggerProvider.CreateTagger[T](ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Structure.OutliningBlockTaggerProvider.CreateTagger[T](ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManagerService.<>c__DisplayClass8_0.<GetOutliningManager>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManagerService.GetOutliningManager(ITextView textView)
   at Microsoft.VisualStudio.Text.Editor.Implementation.OutliningAdornmentManagerFactory.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView)
   at Microsoft.VisualStudio.Text.IntraTextAdornmentSupport.Implementation.IntraTextAdornmentSpaceNegotiatingTaggerProvider.<>c__DisplayClass5_0`1.<CreateTagger>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.IntraTextAdornmentSupport.Implementation.IntraTextAdornmentSpaceNegotiatingTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1..ctor(TagAggregatorFactoryService factory, ITextView textView, IBufferGraph bufferGraph, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView, TagAggregatorOptions options)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregatorFactoryService.CreateTagAggregator[T](ITextView textView)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer..ctor(ITextView view, IViewTagAggregatorFactoryService tagAggregatorFactoryService)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer.<>c__DisplayClass4_0.<GetSequencer>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencer.GetSequencer(ITextView view, IViewTagAggregatorFactoryService tagAggregatorFactoryService)
   at Microsoft.VisualStudio.Text.TextAndAdornmentSequencer.Implementation.TextAndAdornmentSequencerFactoryService.Create(ITextView view)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.SetInfo()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.SetInfo()
   at Microsoft.VisualStudio.PlatformUI.StatusBarService.OnElementValueChanged(UInt32 elementid, Object varValueOld, Object varValueNew)
   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsTrackSelectionExPrivate.Register()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConnectSelectionContext()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Activate()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_ActiveViewChanged(Object sender, ActiveViewChangedEventArgs e)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(View view, ActivationType type)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ShowInternal(ShowFlags showFlags)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<Show>b__493_0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Func`1 method, Boolean reportError, Boolean setShellErrorInfo)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Show()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.<Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show>b__12_0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocumentCore(DocumentId documentId, Boolean activate)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocument(DocumentId documentId, Boolean activate)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.OpenDocument(Workspace workspace, DocumentId documentId, OptionSet options)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToLineAndOffset(Workspace workspace, DocumentId documentId, Int32 lineNumber, Int32 offset, OptionSet options)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableEntriesSnapshot`1.TryNavigateTo(Workspace workspace, DocumentId documentId, Int32 line, Int32 column, Boolean previewTab)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSnapshot.TryNavigateTo(Int32 index, Boolean previewTab)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableControlEventProcessorProvider`1.EventProcessor.PreprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass40_0.<OnEntryElementNavigate>b__2(ITableControlEventProcessor p, ITableEntryHandle entry)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass59_1`1.<EventProcessorHandler>b__0()
   at Microsoft.VisualStudio.Editor.Implementation.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.EventProcessorHandler[T](ITableEntryHandle entry, T e, Func`2 getHandled, Action`2 setHandled, Action`2 preprocess, Action`1 defaultAction, Action`2 postprocess)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.OnEntryElementNavigate(Object sender, TableEntryNavigateEventArgs e)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.FireNavigateToEvent(ITableEntryHandle entry, Boolean isPreview, NavigateInvocationKind invocation, RoutedEventArgs args)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.DefaultMouseLeftButtonDownHandler(ITableEntryHandle entry, MouseButtonEventArgs e)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass25_0.<OnEntryElementMouseLeftButtonDown>b__1(ITableEntryHandle entry)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.EventProcessorHandler[T](ITableEntryHandle entry, T e, Func`2 getHandled, Action`2 setHandled, Action`2 preprocess, Action`1 defaultAction, Action`2 postprocess)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.EventProcessorHandler(Object sender, RoutedEventArgs e, Action`2 preprocess, Action`1 defaultAction, Action`2 postprocess)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.OnEntryElementMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

  Source=Microsoft.CodeAnalysis.Workspaces
  StackTrace:
   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()

**Comment by Pilchie** [comment]
What build of VS is this?  Tagging @CyrusNajmabadi  and @dpugh - because we did have some issues here, but they should be fixed in the latest editor bits.

**Comment by heejaechang** [comment]
base drop is ml25810.00 with latest roslyn vsix installed.

**Comment by Pilchie** [comment]
I'm pretty sure that your base drop is missing the latest fix @dpugh checked in for this issue.

**Comment by heejaechang** [comment]
alright then.
