### ISSUE TITLE
EE:  Internal Error in the EE when creating conflicting pseudovariable

### ISSUE THREAD

**Issue by plnelson** [dotnet/roslyn#15132]
**Dev15**: 

**Steps to Reproduce**:

1.  Debug the following C# code:
```C#
using System.Diagnostics;
class Program
{
    static void Main()
    {
        int a = 0;
        int c = 0;
        Debugger.Break();
        Debugger.Break();
    }
}
```
2. In the Immediate window, evaluate "var a = c;"

**Expected Behavior**:
Compile error

**Actual Behavior**:
"Internal error in the expression evaluator"

**Comment by plnelson** [comment]
**Non-fatal Watson Exception Call stack:**
```
   at Microsoft.VisualStudio.Debugger.WatsonErrorReport.CheckThrottledSubmission(String componentName)
   at Microsoft.VisualStudio.Debugger.WatsonErrorReport.ReportIfNecessary()
   at XapiExceptionProcessing.ReportCurrentNonFatalExceptionIfRequired(XapiExceptionInfo exceptionInfo)
   at XapiExceptionProcessing.OnException(Exception exception, Object implementation, Type interfaceType, String targetMethodName)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrExpressionCompiler_CompileExpression(IntPtr pvClassInfo, IntPtr Expression, IntPtr InstructionAddress, IntPtr InspectionContext, IntPtr& Error, IntPtr& Result)
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EELocalSymbol.get_IdentifierToken()
   at Microsoft.CodeAnalysis.CSharp.LocalScopeBinder.LookupLocal(SyntaxToken nameToken)
   at Microsoft.CodeAnalysis.CSharp.Binder.LocateDeclaredVariableSymbol(SyntaxToken identifier, TypeSyntax typeSyntax, EqualsValueClauseSyntax equalsValue)
   at Micr......
<truncated>
```

**Comment by darthwalsh** [comment]
Possibly related to https://developercommunity.visualstudio.com/content/problem/122916/declaring-variable-in-immediate-window-changes-dat.html ?

**Comment by ivanbasov** [comment]
Thank you, @darthwalsh! It looks like those issues should be investigated together.

**Comment by ivanbasov** [comment]
Resolved with https://github.com/dotnet/roslyn/pull/24198
