### ISSUE TITLE
VBC crashes when compiling code with ValueTuples in it:

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15198]
See: https://github.com/dotnet/roslyn/pull/15196

Specifically commit: https://github.com/dotnet/roslyn/pull/15196/commits/4807ff7efe16d1113636ce918ce69e3164eaa9e0

Crashes with:
error MSB6006: "vbc.exe" exited with code 1. [D:\j\workspace\windows_debug---09a07fba\src\Workspaces\VisualBasic\Portable\BasicWorkspace.vbproj]

This appears to be the bootstrapped compiler crashing.

**Comment by AdamSpeight2008** [comment]
Is this anything to do with some public methods not appearing in the PublicAPI file? via the generated files.
I can remember, it is the ones with `(Of TResult)` or not.
```vb.net
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of TResult).VisitNamedTupleElement(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.NamedTupleElementSyntax) -> TResult
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of TResult).VisitTupleExpression(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleExpressionSyntax) -> TResult
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of TResult).VisitTupleType(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleTypeSyntax) -> TResult
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor(Of TResult).VisitTypedTupleElement(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TypedTupleElementSyntax) -> TResult
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor.VisitNamedTupleElement(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.NamedTupleElementSyntax) -> Void
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor.VisitTupleExpression(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleExpressionSyntax) -> Void
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor.VisitTupleType(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TupleTypeSyntax) -> Void
Overridable Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor.VisitTypedTupleElement(node As Microsoft.CodeAnalysis.VisualBasic.Syntax.TypedTupleElementSyntax) -> Void

```

**Comment by jaredpar** [comment]
Here is the stack of the crash

``` txt
Microsoft (R) Visual Basic Compiler version 42.42.42.42424
Copyright (C) Microsoft Corporation. All rights reserved.

Debug.Assert failed with message: Fail:
Stack Trace
   at Microsoft.CodeAnalysis.CommandLine.ExitingTraceListener.Exit(String originalMessage)
   at Microsoft.CodeAnalysis.CommandLine.ExitingTraceListener.WriteLine(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitPropertyAccess(BoundPropertyAccess node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundPropertyAccess.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpressio
n node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpr
ession node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression e
xpression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpression(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitTupleExpression(BoundTupleExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitTupleLiteral(BoundTupleLiteral node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTupleLiteral.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpressio
n node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpr
ession node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression e
xpression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpression(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.RewriteReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitLambda(BoundLambda node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitLambda(BoundLambda node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundLambda.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpressio
n node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpr
ession node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression e
xpression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpression(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitConversion(BoundConversion node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitConversion(BoundConversion node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundConversion.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpressio
n node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpr
ession node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression e
xpression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpression(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpressionNode(BoundExpression expression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.RewriteCallArguments(ImmutableArray`1 arguments, ImmutableArray`1
 parameters, ImmutableArray`1& temporaries, ImmutableArray`1& copyBack, Boolean suppressObjectClone)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpressio
n node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpr
ession node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression e
xpression)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitExpression(BoundExpression node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.RewriteReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.BoundTreeRewriterWithStackGuard.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.RewriteNode(BoundNode node, MethodSymbol topMethod, MethodSymbol
currentMethod, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, DiagnosticBa
g diagnostics, HashSet`1& rewrittenNodes, Boolean& hasLambdas, ISet`1& symbolsCapturedWithoutCtor, RewritingFlags flags,
 Instrumenter instrumenter, Int32 recursionDepth)
   at Microsoft.CodeAnalysis.VisualBasic.LocalRewriter.Rewrite(BoundBlock node, MethodSymbol topMethod, TypeCompilationS
tate compilationState, SynthesizedSubmissionFields previousSubmissionFields, DiagnosticBag diagnostics, HashSet`1& rewri
ttenNodes, Boolean& hasLambdas, ISet`1& symbolsCapturedWithoutCopyCtor, RewritingFlags flags, Instrumenter instrumenter,
 MethodSymbol currentMethod)
   at Microsoft.CodeAnalysis.VisualBasic.Rewriter.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, Bound
Block body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrum
entForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, DiagnosticBa
g diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 c
losureDebugInfoBuilder, Int32& delegateRelaxationIdDispenser, StateMachineTypeSymbol& stateMachineTypeOpt, Boolean allow
OmissionOfConditionalCalls, Boolean isBodySynthesized)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.LowerAndEmitMethod(MethodSymbol method, Int32 methodOrdinal, Bou
ndBlock block, Binder binderOpt, TypeCompilationState compilationState, DiagnosticBag diagsForCurrentMethod, ProcessedFi
eldOrPropertyInitializers processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol cons
tructorToInject, Int32& delegateRelaxationIdDispenser)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(MethodSymbol method, Int32 methodOrdinal, Int32& w
ithEventPropertyIdDispenser, Int32& delegateRelaxationIdDispenser, Predicate`1 filter, TypeCompilationState compilationS
tate, ProcessedFieldOrPropertyInitializers processedInitializers, Binder containingTypeBinder, SynthesizedSubmissionFiel
ds previousSubmissionFields, MethodSymbol& referencedConstructor)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType, Predicate`1 fil
ter)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__29-0._Lambda$__0()
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>



```

**Comment by CyrusNajmabadi** [comment]
@jaredpar do you know what file/line this was happening on?

**Comment by VSadov** [comment]
@CyrusNajmabadi   Having this failing only in bootsrap build would indicate that there is a breaking Compiler change, but are there any Compiler changes?

**Comment by CyrusNajmabadi** [comment]
No.  There are no compiler changes.

**Comment by CyrusNajmabadi** [comment]
You can see everything that changed here: https://github.com/dotnet/roslyn/pull/15196

**Comment by VSadov** [comment]
Simple repro:
```VB
Imports System
Imports System.Collections.Generic

Public Class C
    Shared Sub Main()
        dim inst = new C
        dim f As (Integer, Integer) = (inst.P1, inst.P1) ' <-- crashes in lowering
    End Sub

    public readonly Property P1 as integer
        Get 
            return 42
        End Get
    end Property
End Class
```

Something has changed very recently and prevents use of properties in tuple literals in VB.

**Comment by AdamSpeight2008** [comment]
I don't think this is anything to due to @CyrusNajmabadi 's work, as those changes are not in master yet.
