### ISSUE TITLE
Intermittent failure in VerifyRenameTrackingWorksAfterInlineRenameCommit 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#15225]
See https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc2/job/windows_release_unit64_prtest/18/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/InlineRenameTests/VerifyRenameTrackingWorksAfterInlineRenameCommit/

Stacktrace

```
MESSAGE:
Assert.Equal() Failure
Expected: 1
Actual: 0
+++++++++++++++++++
STACK TRACE:
 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTestHelpers.VB$StateMachine_13_VerifyRenameTrackingTags.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\Rename\RenameTestHelpers.vb:line 137
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.InlineRenameTests.VB$StateMachine_24_VerifyRenameTrackingWorksAfterInlineRenameCommit.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\Rename\InlineRenameTests.vb:line 844
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by TyOverby** [comment]
Hit again https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/795/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/InlineRenameTests/VerifyRenameTrackingWorksAfterInlineRenameCommit/

**Comment by dpoeschl** [comment]
Apparently we don't keep 9 days of Jenkins logs. ☹️

**Comment by jasonmalinowski** [comment]
This failed again: https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=475343&tab=ms.vss-test-web.test-result-details.

**Comment by jasonmalinowski** [comment]
And again: https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=501015&tab=ms.vss-test-web.test-result-details

@dpoeschl @Pilchie what is the plan here? Can we investigate or disable?

**Comment by Pilchie** [comment]
Moving to 2.1 - we won't fix in escrow unless we identify a customer scenario.
