### ISSUE TITLE
SourceText cannot be embedded exception being thrown on certain projects

### ISSUE THREAD

**Issue by mjsabby** [dotnet/roslyn#15254]
**Version Used**: 
2.0.0-rc3-61111-05

**Steps to Reproduce**:

[Repro.zip](https://github.com/dotnet/roslyn/files/592751/Repro.zip)

1. Unzip the Repro.zip
2. Open it in VS 2017 RC
3. Build

**Expected Behavior**:

The build succeeds

**Actual Behavior**:

```
Unhandled Exception: System.ArgumentException: SourceText cannot be embedded. Provide encoding or canBeEmbedded=true
  at construction.
  Parameter name: text
     at Microsoft.CodeAnalysis.EmbeddedText.FromSource(String filePath, SourceText text)
     at Microsoft.CodeAnalysis.CommonCompiler.AcquireEmbeddedTexts(Compilation compilation, IList`1 diagnostics)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationTo
  ken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
     at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter,
  IAnalyzerAssemblyLoader analyzerLoader)
     at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildP
  aths, TextWriter textWriter)
     at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths build
  Paths, TextWriter textWriter)
     at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments
  , RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs)
     at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

**Comment by mjsabby** [comment]
cc @nguerrera

**Comment by mjsabby** [comment]
Compiled and tested this with all Bing.com managed code and no new issues found so I'm closing this.
