### ISSUE TITLE
Crash in expand/reduce with Tuples.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#15409]
```
Unexpected type syntax TupleType

at Microsoft.CodeAna|ysis.CSharp.CSharpSyntaxFactsService.ExpandTypeName(TypeSyntax type, StringBuilder builder)
at Microsoft.CodeAna|ysis.CSharp.CSharpSyntaxFactsService.ExpandTypeName(TypeSyntax type, StringBuilder builder)
at Microsoft.CodeAna|ysis.CSharp.CSharpSyntaxFactsService.ExpandExplicitlnterfaceName(String identifier,ExplicitlnterfaceSpecifierSyntax explicitlnterfaceSpecifier)
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.TryGetDeclaredSymbolInfo(SyntaxNode node, DeclaredSymbollnfo&declaredSymbollnfo)
at Microsoft.CodeAnalysis.FindSymb0|s.SyntaxTreelndex.CreateInfoAsync(Document document, CancellationTokencancellationToken)
at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreelndex.<PrecalculateAsync>d_44.MoveNext0
at S .... ..
<truncated>
```

![image](https://cloud.githubusercontent.com/assets/4564579/20467790/79642ed2-af43-11e6-97c8-df4722267a35.png)

**Comment by Pilchie** [comment]
Any idea what you were doing when you hit this?
