### ISSUE TITLE
Roslyn UnauthorizedAccessException crashed Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by lextm** [dotnet/roslyn#15412]
**Version Used**: 1.3.1

**Steps to Reproduce**:

1. Use a working C# project with .snk to sign the assembly.
2. Remove NTFS access of your account from this .snk file outside VS.
3. Load this project again in VS and open any C# file.

**Expected Behavior**:
VS should not crash. Roslyn might fail to provide IntelliSense.

**Actual Behavior**:
VS simply crashed, with a dialog saying "devenv.exe - System Warning" and "Unknown Hard Error".

Seems to be related to #3740 so a design debt.

**More Information**:
A crash dump analysis shows the call stack,
```
CLR: Managed code called FailFast, saying "System.UnauthorizedAccessException: Access to the path 'C:\somepath\somekey.snk' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at Microsoft.CodeAnalysis.DesktopStrongNameProvider.ReadAllBytes(String fullPath)
   at Microsoft.CodeAnalysis.DesktopStrongNameProvider.CreateKeys(String keyFilePath, String keyContainerName, CommonMessageProvider messageProvider)
   at Microsoft.CodeAnalysis.StrongNameKeys.Create(StrongNameProvider providerOpt, String keyFilePath, String keyContainerName, CommonMessageProvider messageProvider)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeStrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_StrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeIdentity()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_Identity()
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetAssemblyOrModuleSymbol(MetadataReference reference)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Compilation compilation, List`1 newReferences, Dictionary`2 metadataReferenceToProjectId)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<FinalizeCompilationAsync>d__29.MoveNext()"
```
The version number of Roslyn can be found
```
0:076> lmvm Microsoft_CodeAnalysis_ni
start    end        module name
2e1c0000 2e99d000   Microsoft_CodeAnalysis_ni   (deferred)             
    Image path: C:\Windows\assembly\NativeImages_v4.0.30319_32\Microsoft.Cbf18da00#\6b2819f94ffdcf4efbc6bbc31153fadb\Microsoft.CodeAnalysis.ni.dll
    Image name: Microsoft.CodeAnalysis.ni.dll
    Has CLR image header, track-debug-data flag not set
    Timestamp:        ***** Invalid (95BDA679)
    CheckSum:         00000000
    ImageSize:        007DD000
    File version:     1.3.1.60616
    Product version:  1.3.1.60616
    File flags:       0 (Mask 3F)
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0000.04b0
    CompanyName:      Microsoft Corporation
    InternalName:     Microsoft.CodeAnalysis.dll
    OriginalFilename: Microsoft.CodeAnalysis.dll
    ProductVersion:   1.3.1.60616
    FileVersion:      1.3.1.60616
    FileDescription:   
    LegalCopyright:   © Microsoft Corporation. All rights reserved.
```

**Justification**
Sometimes a key file is hosted on a network share for projects with ACL settings so as to put a restriction on which developers can build and distribute the binaries.

However, if a developer has no access to this key file, but has access to the source files, he/she should be able to work on the project normally. However, this miserable crash prevents them from using VS on such projects at all.

**Comment by jaredpar** [comment]
This is fixed now as we handle exceptions at this layer and wrap it in a diagnostic.
