### ISSUE TITLE
CSharpGoToDefinition VSI test failing

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#15461]
The "Go To Definition with multiple results" scenario is failing with the following exception stack trace:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
    System.NullReferenceException: Object reference not set to an instance of an object.
        at Roslyn.VSHosting.Test.RoslynInProcessAPI.DumpListContents(IVsSimpleObjectList2 objectList, List`1 result) in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 897
        at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass113_0.<GetFindSymbolResults>b__0() in d:\j\workspace\windows_vsi_p---5fa6ff52\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\Utilities\RoslynInProcessAPI.cs:line 888
        --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Delegate.DynamicInvokeImpl(Object[] args)
    at System.Delegate.DynamicInvoke(Object[] args)
    at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values)
    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
```

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/24/

**Comment by Pilchie** [comment]
@CyrusNajmabadi Didn't you just change this code?  Can you take a look here?

**Comment by DustinCampbell** [comment]
This is still failing: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/36/

@Pilchie: Shouldn't this have an urgency label?

**Comment by Pilchie** [comment]
Yes, thanks.  @CyrusNajmabadi please take a look here ASAP.

**Comment by CyrusNajmabadi** [comment]
Sure.  I'll look.  Thanks!

**Comment by Pilchie** [comment]
@CyrusNajmabadi you and @tmeschter wrote FAR tests for the new framework, right?  ARe the old ones deleted?  Should this bug just be closed?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/18227
