### ISSUE TITLE
IDE crashes on deconstruction with discard

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#15468]
The following program causes the IDE to crash, because type inference doesn't handle the new syntax model for deconstruction.

FYI @gafter @CyrusNajmabadi 

```C#
class Program
{
    int _private;
    void Main(string[] args)
    {
        (_private, _) = 
    }
}
```

```
   at Microsoft.CodeAnalysis.Compilation.CreateTupleTypeSymbol(ImmutableArray`1 elementTypes, ImmutableArray`1 elementNames, ImmutableArray`1 elementLocations)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.GetTupleType(TupleExpressionSyntax tuple)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInVariableComponentAssignment(ExpressionSyntax left)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInBinaryOrAssignmentExpression(ExpressionSyntax binop, SyntaxToken operatorToken, ExpressionSyntax left, ExpressionSyntax right, ExpressionSyntax expressionOpt, Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass8_0.<InferTypesWorker_DoNotCallDirectly>b__7(AssignmentExpressionSyntax assignmentExpression)
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TDerivedType39,TDerivedType40,TDerivedType41,TDerivedType42,TDerivedType43,TDerivedType44,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 matchFunc39, Func`2 matchFunc40, Func`2 matchFunc41, Func`2 matchFunc42, Func`2 matchFunc43, Func`2 matchFunc44, Func`2 defaultFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(Int32 position)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.InferTypes(SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext.ComputeInferredTypes(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext..ctor(Workspace workspace, SemanticModel semanticModel, Int32 position, SyntaxToken leftToken, SyntaxToken targetToken, Boolean isTypeContext, Boolean isNamespaceContext, Boolean isNamespaceDeclarationNameContext, Boolean isPreProcessorDirectiveContext, Boolean isRightOfNameSeparator, Boolean isStatementContext, Boolean isAnyExpressionContext, Boolean isAttributeNameContext, Boolean isEnumTypeMemberAccessContext, Boolean isNameOfContext, Boolean isInQuery, Boolean isInImportsDirective, Boolean isWithinAsyncMethod, Boolean isPossibleTupleContext, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext..ctor(Workspace workspace, SemanticModel semanticModel, Int32 position, SyntaxToken leftToken, SyntaxToken targetToken, TypeDeclarationSyntax containingTypeDeclaration, BaseTypeDeclarationSyntax containingTypeOrEnumDeclaration, Boolean isInNonUserCode, Boolean isPreProcessorDirectiveContext, Boolean isPreProcessorKeywordContext, Boolean isPreProcessorExpressionContext, Boolean isTypeContext, Boolean isNamespaceContext, Boolean isNamespaceDeclarationNameContext, Boolean isStatementContext, Boolean isGlobalStatementContext, Boolean isAnyExpressionContext, Boolean isNonAttributeExpressionContext, Boolean isConstantExpressionContext, Boolean isAttributeNameContext, Boolean isEnumTypeMemberAccessContext, Boolean isNameOfContext, Boolean isInQuery, Boolean isInImportsDirective, Boolean isLabelContext, Boolean isTypeArgumentOfConstraintContext, Boolean isRightOfDotOrArrowOrColonColon, Boolean isIsOrAsContext, Boolean isObjectCreationTypeContext, Boolean isDefiniteCastTypeContext, Boolean isGenericTypeArgumentContext, Boolean isEnumBaseListContext, Boolean isIsOrAsTypeContext, Boolean isLocalVariableDeclarationContext, Boolean isDeclarationExpressionContext, Boolean isFixedVariableDeclarationContext, Boolean isParameterTypeContext, Boolean isPossibleLambdaOrAnonymousMethodParameterTypeContext, Boolean isImplicitOrExplicitOperatorTypeContext, Boolean isPrimaryFunctionExpressionContext, Boolean isDelegateReturnTypeContext, Boolean isTypeOfExpressionContext, ISet`1 precedingModifiers, Boolean isInstanceContext, Boolean isCrefContext, Boolean isCatchFilterContext, Boolean isDestructorTypeContext, Boolean isPossibleTupleContext, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.ObjectCreationCompletionProvider.<CreateContext>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetCompletionListAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__13.MoveNext()
```

**Comment by jcouv** [comment]
Fixed by #15469
