### ISSUE TITLE
Opening Roslyn.sln asks to update to Visual Studio 2015 - Update 1 when it already has Update 3 installed

### ISSUE THREAD

**Issue by codingonHP** [dotnet/roslyn#15517]
**Version Used**: 

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
Installed Version: Enterprise

I have just cloned the repo and when I tried to open it in VS 2015 with update 3 installed. none of the project are loading. I am getting following error:
**Install Update 1 for Visual Studio.**

What am I missing here ?

**Comment by jmarolf** [comment]
Do you have the VSSDK installed?

**Comment by codingonHP** [comment]
@jmarolf : Yes I have VSSDK installed. I am able to play around with Roslyn API in my VS edition. Everything works fine.

**Comment by jasonmalinowski** [comment]
@rchande and @Pilchie, wasn't this some known issue we're tracking somewhere else?

**Comment by rchande** [comment]
@codingonHP What Roslyn branch/commit do you have checked out?

**Comment by rchande** [comment]
Also @codingonHP have you run `restore.cmd`?

**Comment by codingonHP** [comment]
@rchande : I checked out master branch.
I did try to run restore.cmd but it failed with following error :
System.Management.Automation.RuntimeException: The variable '$_' cannot be retrieved because it has not been set.
   at System.Management.Automation.VariableDereferenceNode.GetVariable(ExecutionContext context)
   at System.Management.Automation.VariableDereferenceNode.PrivateGetValue(ExecutionContext context)
   at System.Management.Automation.VariableDereferenceNode.GetValue(ExecutionContext context)
   at System.Management.Automation.ArrayLiteralNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.MethodCallNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
Error loading NuGet.exe information 65535

**Comment by khionu** [comment]
I'm having the same issue with VS 2017. Commit: b68450f519df3af2b985a70dee320e83fa35381a

**Comment by jasonmalinowski** [comment]
Ah, we're tracking that issue over at #15667.
