### ISSUE TITLE
Compiler produces unverified code for ref returns

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#15614]
This test fails:

```cs
        [Fact]
        void InvokeVarForLvalueInParens()
        {
            var source = @"
class Program
{
    public static void Main()
    {
        (var(x, y)) = 10;
        System.Console.WriteLine(z);
    }
    static int x = 1, y = 2, z = 3;
    static ref int var(int x, int y)
    {
        return ref z;
    }
}";
            var compilation = CreateCompilationWithMscorlib(source, references: new[] { ValueTupleRef, SystemRuntimeFacadeRef }, options: TestOptions.DebugExe);
            compilation.VerifyDiagnostics();
            CompileAndVerify(compilation, expectedOutput: "10");
        }
```

with

```none
------ Test started: Assembly: Roslyn.Compilers.CSharp.Emit.UnitTests.dll ------

Unknown .NET Framework Version: v4.6
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenDeconstructTests.InvokeVarForLvalueInParens' failed: Microsoft.CodeAnalysis.Test.Utilities.PeVerifyException : 
PeVerify failed for assembly 'C:\Users\ngafter\AppData\Local\Temp\':
[ : Program::var1][mdToken=0x6000002][offset 0x0000000A] Return type is ByRef, TypedReference, ArgHandle, or ArgIterator.


	at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
	at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
	at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.PeVerify()
	at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, EmitOptions emitOptions, Boolean peVerify, SignatureDescription[] expectedSignatures)
	at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Boolean verify)
	at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, EmitOptions emitOptions, Boolean verify)
	at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	CodeGen\CodeGenDeconstructTests.cs(5802,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenDeconstructTests.InvokeVarForLvalueInParens()

0 passed, 1 failed, 0 skipped, took 3.15 seconds (xUnit.net 2.1.0 build 3179).
```

We probably need to test a similar consumption scenario for VB.

**Comment by gafter** [comment]
Test pending in #15548

**Comment by jcouv** [comment]
FYI @VSadov

**Comment by jaredpar** [comment]
The verification error is expected here as peverify isn't fully updated for ref returns.  It is still using managed C++ rules which are more restrictive.  For these scenarios we should disable verification for the time being.

**Comment by gafter** [comment]
Should't updating the CLI spec and updating the verifier be part of implementing this feature? It feels like our work is not completed while it is in this state.

**Comment by jaredpar** [comment]
@gafter yes. We've met and discussed with the verifier team.  The fix is coming but the verifier releases as part of desktop hence it's a bit delayed from the compiler. 

As for the CLI spec I don't know if we have a specific item tracking that yet.  Will let @VSadov respond.

**Comment by jcouv** [comment]
This seems a duplicate of https://github.com/dotnet/roslyn/issues/12285
I'll let you confirm and resolve.

**Comment by VSadov** [comment]
I do not know where a bug against CLI spec would go.

NOTE: It does not necessary need to be a general fix to the CLI spec (as in: requiring all conforming implementations to follow it). I am not sure the relaxation of the rules needed for MC++ is recorded there either.

It could be just an implementation-specific amendment where we would be essentially relaxing our verification rules and accepting some cases that CLI does not require us to accept.

**Comment by tmat** [comment]
@VSadov You can add it here: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/Ecma-335-Issues.md

**Comment by gafter** [comment]
@VSadov Unlike MC++, Roslyn is the reference implementation for the C# language targeting the CLI spec. I believe the Roslyn C# compiler should target the CLI spec (by default) for programs that use only features described in the C# language specification (though it may be capable of emitting in other modes). Of course we need to modify the CLI spec to accomplish that, and therefore we should do exactly that. Along with that, we will need to modify peverify. [And then test the combination of the two](https://github.com/dotnet/roslyn/issues/15901).
