### ISSUE TITLE
Invalid `Inline temporary variable` fix crashes Visual Studio

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#15624]
**Version Used**: 

Latest `master` branch

Visual Studio 2017 RC

**Steps to Reproduce**:

1.  Paste the following code snippet:

```` C#
class C
{
    object V;

    public C()
    {
        V$$ =;
    }
}
````

2.  Press `Ctrl + .` on `$$`

**Actual Behavior**:

There is a `Inine temporary variable` fix, but I don't understand which variable can be inlined, and Visual Studio crashed.

StackTrack:

````
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IReadOnlyList<T>.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpIsAndCastCheckCodeFixProvider.AddEdits(SyntaxEditor editor, Diagnostic diagnostic, CancellationToken cancellationToken) in D:\cs\roslyn\src\Features\CSharp\Portable\UsePatternMatching\CSharpIsAndCastCheckCodeFixProvider.cs:line 53
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpIsAndCastCheckCodeFixProvider.FixAllAsync(Document document, ImmutableArray`1 diagnostics, SyntaxEditor editor, CancellationToken cancellationToken) in D:\cs\roslyn\src\Features\CSharp\Portable\UsePatternMatching\CSharpIsAndCastCheckCodeFixProvider.cs:line 42
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<>c__DisplayClass2_0.<FixAllAsync>b__0(SyntaxEditor editor) in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeFixes\SyntaxEditorBasedCodeFixProvider.cs:line 27
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<FixAllWithEditorAsync>d__3.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeFixes\SyntaxEditorBasedCodeFixProvider.cs:line 39
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionAsync>d__21.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 143
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputeOperationsAsync>d__18.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 112
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputePreviewOperationsAsync>d__20.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 134
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetPreviewOperationsAsync>d__17.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 97
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<GetPreviewResultAsync>d__23.MoveNext() in D:\cs\roslyn\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedAction.cs:line 212
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<<GetPreviewAsync>b__0>d.MoveNext() in D:\cs\roslyn\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedActionWithNestedFlavors.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext() in D:\cs\roslyn\src\Workspaces\Core\Portable\ExtensionManager\IExtensionManagerExtensions.cs:line 107
````

**Comment by CyrusNajmabadi** [comment]
I'm not reproing this:

![image](https://cloud.githubusercontent.com/assets/4564579/21206056/82fc5274-c214-11e6-965f-f95d7e3a7904.png)

or

![image](https://cloud.githubusercontent.com/assets/4564579/21206058/8a76c8cc-c214-11e6-9530-1a1648529331.png)


I can't get a lightbulb to show at all.

**Comment by CnSimonChan** [comment]
It doesn't repro in RC 2.

**Comment by CyrusNajmabadi** [comment]
Thanks for verifying!
