### ISSUE TITLE
Error building: Automation.RuntimeException in restore.cmd

### ISSUE THREAD

**Issue by qwertie** [dotnet/roslyn#15667]
**Version Used**: Building master branch on Windows 7

**Steps to Reproduce**:

1. Do [installation prerequisites](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md) (get VS 2015 Update 3, install "VS insider" vsix, clone dotnet/roslyn.)
2. Run "Developer Command Prompt for VS2015", navigate to the directory of Git clone
3. Run restore.cmd

**Expected Behavior**:

It installs Roslyn prerequisites, I guess.

**Actual Behavior**: Exception

~~~
System.Management.Automation.RuntimeException: The variable '$_' cannot be retrieved because it has not been set.
   at System.Management.Automation.VariableDereferenceNode.GetVariable(ExecutionContext context)
   at System.Management.Automation.VariableDereferenceNode.PrivateGetValue(ExecutionContext context)
   at System.Management.Automation.VariableDereferenceNode.GetValue(ExecutionContext context)
   at System.Management.Automation.ArrayLiteralNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.MethodCallNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ArrayList& resultList, ExecutionC
ontext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputP
ipe, ArrayList& resultList, ExecutionContext context)
Error loading NuGet.exe information 65535
~~~

Since NuGet.exe was mentioned, I downloaded the [recommended latest (v3.4.4)](https://dist.nuget.org/index.html) version and used it to replace the only copy of NuGet on my hard drive. This did not change the error message.

**Comment by jasonmalinowski** [comment]
@jaredpar, this looks like this is a failure to run this part of restore.cmd:

     call "%RoslynRoot%build\scripts\LoadNuGetInfo.cmd" || goto :LoadNuGetInfoFailed

And the reason it failed was some sort of PowerShell failure. Any ideas?

**Comment by jaredpar** [comment]
@qwertie mentioned he's running on Windows 7.  That means a significantly older version of Powershell than we are using.  It's possible we are using a new powershell construct that isn't available there.

**Comment by qwertie** [comment]
Let me know if I can do anything to help debug (admission: I never use Powershell)

**Comment by abubakarm** [comment]
I downloaded the Windows Management Framework 3.0 https://www.microsoft.com/en-us/download/details.aspx?id=34595 , on windows 7 64 bits, and this error was gone.
