### ISSUE TITLE
Visual Studio crashed attempting to invoke a code fix

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15765]
I'm unable to repro this, but this is what I did:

#1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Debug\LaunchProfileData.cs at line 213
5. Open Lightbulb, choose Object Initialization Can Be Simplified

--- Crash -- 
```
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte[]'.
   at Microsoft.CodeAnalysis.ProjectId.ReadFrom(ObjectReader reader)
   at Microsoft.CodeAnalysis.DocumentId.ReadFrom(ObjectReader reader)
   at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticResultSerializer.Deserialize(ObjectReader reader, DiagnosticDataSerializer serializer, Project project, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticResultSerializer.Deserialize(ObjectReader reader, IDictionary`2 analyzerMap, Project project, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioDiagnosticAnalyzerExecutor.<GetCompilerAnalysisResultAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.Extensions.<InvokeAsync>d__1`1.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.Remote.Extensions.IsCancelled(System.Exception)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by heejaechang** [comment]
this is fixed but schedule to RC3. (https://github.com/dotnet/roslyn/pull/15590)

race was found during adding cancellation unit tests and fixed as part of unit test PR.

**Comment by Pilchie** [comment]
Moving to analyzers.

**Comment by heejaechang** [comment]
should be fixed. **this** indicates it is old code. fix is scheduled for RC3 though.

   **at Microsoft.CodeAnalysis.Remote.Extensions.IsCancelled(System.Exception)**
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],

**Comment by heejaechang** [comment]
should be fixed by https://github.com/dotnet/roslyn/pull/15590

issue is related to a race on cancellation. which got discovered while adding cancellation unit tests, and fixed.
