### ISSUE TITLE
[Failing Test] Basic/CSharpMetadataAsSource.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#15861]
content of MAS changed - looks like xml document is missing

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_prtest/132/artifact/Open/Binaries/Release/Exes/EditorTestApp/VSIntegrationTestLogs/BasicMetadataAsSource.html

and

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_prtest/134/console
....

System.Exception: Actual and expected items don't match:
Expected: \Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
#End Region

Imports System.Globalization
Imports System.Runtime
Imports System.Runtime.InteropServices
Imports System.Security

Namespace System
    '
    ' Summary:
    '     Represents a 32-bit signed integer.To browse the .NET Framework source code for
    '     this type, see the Reference Source.
    <ComVisible(True)>
    Public Structure Int32
Actual: #Region "Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
' C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
#End Region

Imports System.Globalization
Imports System.Runtime
Imports System.Runtime.InteropServices
Imports System.Security

Namespace System
    '
    <ComVisible(True)>
    Public Structure Int32
        Implements IComparable, IFormattable, IConvertible, IComparable(Of Int32), IEquatable(Of Int32)
        '
        Public Const MaxValue As Int32 = 2147483647
        '
        Public Const MinValue As Int32 = -2147483648

        '
        Public Shared Function TryParse(s As String, ByRef result As Int32) As Boolean
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Shared Function Parse(s As String, style As NumberStyles, provider As IFormatProvider) As Int32
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Shared Function Parse(s As String, provider As IFormatProvider) As Int32
        '
        Public Shared Function Parse(s As String, style As NumberStyles) As Int32
        '
        Public Shared Function Parse(s As String) As Int32
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Shared Function TryParse(s As String, style As NumberStyles, provider As IFormatProvider, ByRef result As Int32) As Boolean
        '
        <SecuritySafeCritical>
        Public Function ToString(format As String, provider As IFormatProvider) As String
        '
        <SecuritySafeCritical> <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Function ToString(format As String) As String
        '
        <SecuritySafeCritical> <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Overrides Function ToString() As String
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Overrides Function GetHashCode() As Int32
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Function Equals(obj As Int32) As Boolean
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Overrides Function Equals(obj As Object) As Boolean
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Function CompareTo(value As Int32) As Int32
        '
        Public Function CompareTo(value As Object) As Int32
        '
        <SecuritySafeCritical> <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Function ToString(provider As IFormatProvider) As String
        '
        <TargetedPatchingOptOut("Performance critical to inline across NGen image boundaries")>
        Public Function GetTypeCode() As TypeCode
    End Structure
End Namespace

   at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\windows_vsi_p---9267604d\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
   at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\windows_vsi_p---9267604d\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by heejaechang** [comment]
fixed by https://github.com/dotnet/roslyn/pull/15874
