### ISSUE TITLE
vbc.exe fails on system with FIPS compliance enabled

### ISSUE THREAD

**Issue by AndrewKoransky** [dotnet/roslyn#15939]
**Version Used**: 1.3.1.60621

**Steps to Reproduce**:

1. Enable FIPS compliance in the OS and reboot.
2. Try to compile a asp.net website using the latest stable VB14 compiler.

**Expected Behavior**: site should compile.

**Actual Behavior**: error is logged... I believe the build is failing because SHA256 is not FIPS compliant:

Application: vbc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Security.Cryptography.SHA256Managed..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(System.String, System.Object[])
   at System.Security.Cryptography.SHA256.Create()
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.GetBasePipeName(System.String)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.GetPipeNameForPath(System.String)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.GetSessionKey(Microsoft.CodeAnalysis.CommandLine.BuildPaths)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(System.String[], System.String[])
   at Microsoft.CodeAnalysis.VisualBasic.CommandLine.Program.Main(System.String[])

**Comment by morganbr** [comment]
@AndrewKoransky  I think this already got fixed in the desktop .NET Framework 4.6.2. What version are you using?  On older versions of the .NET Framework, SHA256.Create tries to create  
SHA256Managed, which isn't FIPS compliant. 

If Roslyn wants to work around this, either:
1. Use a FIPS-compliant implementation, probably SHA256Cng or 
2. Use CryptoConfig.AddAlgorithm to map the string System.Security.Cryptography.SHA256 to a FIPS-compliant implementation.

CC @bartonjs

**Comment by AndrewKoransky** [comment]
I am on 4.6.1. I'll try upgrading the server and website to 4.6.2 and see if that helps. But know that not all hosting environments allow for this, so any work-arounds Rosalyn can implement would be appreciated.

**Comment by gafter** [comment]
@AndrewKoransky We have not heard from you in a year. Please reopen if that did not address the issue for you.
