### ISSUE TITLE
Attempting to inline variable causes analyzer and fix all provider to crash

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#15992]
1. Clone at this commit:
https://github.com/davkean/roslyn-project-system/commit/f19967712d698a1a56ef1c61d31c09e556d4f63f
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (I picked yesterday's build of Roslyn - 12/18)
4. Open DictionaryEqualityComparer.cs
5. Navigate to line 110, click Quick Actions and Refactorings
6. Point to **inline variable declaration** -> **Fix all occurances in Solution**

-- Multiple issues-- 
SyntaxEditorBasedFixAllProvider encountered an error and has been disabled with:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia)
   at Microsoft.CodeAnalysis.CSharp.InlineDeclaration.CSharpInlineDeclarationCodeFixProvider.<>c.<AddEditsAsync>b__4_0(SyntaxNode t,SyntaxGenerator g)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass19_0.<InvokeCoreAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Error List shows:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.InlineDeclaration.CSharpInlineDeclarationDiagnosticAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Inconsistent syntax tree features
Parameter name: trees'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.InlineDeclaration.CSharpInlineDeclarationDiagnosticAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Inconsistent syntax tree features
Parameter name: trees'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.InlineDeclaration.CSharpInlineDeclarationDiagnosticAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Inconsistent syntax tree features
Parameter name: trees'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests		1	Active

```

**Comment by davkean** [comment]
tag @CyrusNajmabadi this is the latest bits out of master.

**Comment by davkean** [comment]
This is repeatable

**Comment by CyrusNajmabadi** [comment]
Thanks.  I'll take a look later.

**Comment by CyrusNajmabadi** [comment]
Do you happen to know what file/location of code where this is crashing (i.e. if you attach a debugger).  Just looking at what's going on syntactically in the crashing location would be helpful for psychically debugging.

Note: i'm talking about the location in *your* code where the fixup is crashing when it tries to apply the fix.

Thanks!

**Comment by davkean** [comment]
I'll try and isolate it.

**Comment by davkean** [comment]
This is one instance of the problems, in src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\PropertyPage.cs

``` C#
                    IVsHierarchy hier = null;
                    int hr;
                    hr = browseObj.GetProjectItem(out hier, out uint itemid);
                    if (hr == VSConstants.S_OK && itemid == VSConstants.VSITEMID_ROOT)
                    {
                       [...]
                    }
```

**Comment by davkean** [comment]
If I remove the assignment to `hier = null`, then it stops crashing. Couldn't isolate this anymore though - tried repro'ing in a Console app with similar code and it doesn't repro.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/16008#pullrequestreview-13923431
