### ISSUE TITLE
Are MefHostServices thread-safe/reusable in Roslyn 1.3.2?

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#16124]
**Version:** 1.3.2

I'm getting random test failures when creating multiple parallel workspaces over the same instance of `MefHostServices`. Is it a bug, or is parallel use of `MefHostServices` instance unsupported?

**Workspace:**
```csharp
    internal class CustomWorkspace : Workspace {
        public CustomWorkspace(HostServices host) : base(host, "Custom" /* same as AdHoc */) {
        }

        public override bool CanOpenDocuments => true;

        public override bool CanApplyChange(ApplyChangesKind feature) {
            return feature == ApplyChangesKind.ChangeDocument;
        }

        public new Solution SetCurrentSolution(Solution solution) {
            return base.SetCurrentSolution(solution);
        }
    }
```

**Stack Traces**
```
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Workspace.get_Options()
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService..ctor(HostLanguageServices languageServices)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CreateLanguageService(HostLanguageServices provider)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
   at Microsoft.CodeAnalysis.DocumentState.Create(DocumentInfo info, ParseOptions options, HostLanguageServices language, SolutionServices services)
   at Microsoft.CodeAnalysis.Solution.AddDocument(DocumentId documentId, String name, SourceText text, IEnumerable`1 folders, String filePath, Boolean isGenerated)
```

```
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Options.OptionService..ctor(IEnumerable`1 optionProviders, IEnumerable`1 optionSerializers)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Providers.Lazy.LazyWithMetadataExportDescriptorProvider.<>c__DisplayClass5`2.<>c__DisplayClass7.<>c__DisplayClass9.<>c__DisplayClassb.<GetLazyDefinitions>b__4()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c__DisplayClass5_0.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.Workspace.get_Options()
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService..ctor(HostLanguageServices languageServices)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CreateLanguageService(HostLanguageServices provider)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
   at Microsoft.CodeAnalysis.DocumentState.Create(DocumentInfo info, ParseOptions options, HostLanguageServices language, SolutionServices services)
   at Microsoft.CodeAnalysis.Solution.AddDocument(DocumentId documentId, String name, SourceText text, IEnumerable`1 folders, String filePath, Boolean isGenerated)
```

**Comment by ashmind** [comment]
@Pilchie I noticed that my tests didn't actually reuse anything, and was able to isolate the issue within Roslyn code only. This ticket is misleading now, so I'll close this and create a new one with a proper test case.
