### ISSUE TITLE
IntelliSense: Cannot override properties with both accessors

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#16334]
**Version Used**: a2df65047264ed08fb3a985056085dbcee821253 

```C#
class B {
	public virtual int A { get; set; }
	class C : B {
		override A
	}
}
```

Press Ctrl+Space after the last `A`.

```
System.InvalidOperationException: Unexpected Null
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.<DetermineNewDocumentAsync>d__8.MoveNext()
```

Demo: http://tryroslyn-edge.azurewebsites.net/#b:master/f:>ilr/MYGwhgzhAEBC0G8CwAoAkABwK4CMQEthoA3fAJwBcswRp8A7C6AQUWgHMBTCgbmgm58AvqjShIMAMLQAXHESi0Ae2KcyZfABNO0USJRCgA==

**Comment by SLaks** [comment]
Within VS, once per session (?), this also shows yellow bar for CSharpSpellCheckCodeFixProvider:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.OverrideCompletionProvider.GetTargetCaretPosition(SyntaxNode caretTarget)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.GetChangeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetChangeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.GetInsertionTextAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by SLaks** [comment]
On TryRoslyn-Edge, I also get this error with just one accessor: http://tryroslyn-edge.azurewebsites.net/#b:master/f:>ilr/MYGwhgzhAEBC0G8CwAoAkABwK4CMQEthoA3fAJwBcswRoIKz8A7Ac2gBVoBeAPmgCIAgvwDcqaBOihIMAMLQAXHETjJagPbEApmUYATLR1USAvqhNA==

On VS (15.0.26020), that works fine, producing `public override System.String T => base.T;`, and only fails with `{ get; set; }`.

**Comment by Pilchie** [comment]
The second error with `TryRoslyn-Edge` fails [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractMemberInsertingCompletionProvider.cs,100), which implies a problem with the way the workspace is set up there.  It doesn't fail on my current build.  The one with two accessors does however.

**Comment by Pilchie** [comment]
This doesn't repro if the option for accessors is changes to "PreferBlockBodies".  @rchande or @CyrusNajmabadi can you take a quick look?
