### ISSUE TITLE
csc crashes when referencing module that forwards same type to multiple assemblies

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#16484]
To reproduce:

1) Save the following il into `forwarder.il`:
```assembly
.assembly extern Destination1
{                 
}

.assembly extern Destination2
{                 
}

.class extern forwarder Destination.TestClass
{
	.assembly extern Destination1
}

.class extern forwarder Destination.TestClass
{
	.assembly extern Destination2
}
```
2) Compile this into a module using `ilasm` to produce `forwarder.dll`.
3) Compile the following C# code referencing `forwarder.dll`:

```csharp
namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
```

**Native compiler behaviour:**
`error CS1577: Assembly generation failed -- Type 'Destination.TestClass' is forwarded to multiple assemblies: 'Destination2' and 'Destination1'`

**Roslyn compiler behaviour:**
Crashes with the following exception:
```
Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.PEModule.EnsureForwardTypeToAssemblyMap()
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol.<GetForwardedTypes>d__77.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.LoadAndValidateNetModuleAttributes(CustomAttributesBag`1& lazyNetModuleAttributesBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetNetModuleDecodedWellKnownAttributeData()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetWellKnownAttributeDataStringField(Func`2 fieldGetter, String missingValue)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeStrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_StrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ValidateAttributeSemantics(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

@AlekseyTs comment: We should only report the error if the user is referencing the type, and we should ignore the multiple forwards and resume normally otherwise.

@jaredpar copy of VSO 223973.

**Comment by jcouv** [comment]
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems?id=369815

**Comment by jaredpar** [comment]
Moving to 2.1 based on the current bar.
