### ISSUE TITLE
Crash in SemanticModel

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#16759]
Callstack is:

```c#
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBindingRoot(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node,CSharpSyntaxNode& bindableNode,BoundNode& lowestBoundNode,BoundNode& highestBoundNode,BoundNode& boundParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node,SymbolInfoOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel,ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions.IsEnumTypeMemberAccessContext(SyntaxTree syntaxTree,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker(Workspace workspace,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetRecommendedSymbolsAtPositionWorkerAsync(Workspace workspace,SemanticModel semanticModel,Int32 position,OptionSet options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPositionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Recommendations.Recommender.GetImmutableRecommendedSymbolsAtPositionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetPerContextSymbols(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

No dump unfortunately.

**Comment by jaredpar** [comment]
Took a look at this and it appears that we are getting an unexpected null [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/MemberSemanticModel.cs,1267).  

``` c#
Debug.Assert(current != null, "How did we get outside the root?");
```

The stack though is pretty generic and doesn't give any hint to the code that got us here.  Closing as I don't think there is much action we can take here without a dump, source code, etc ...
