### ISSUE TITLE
Exception in `SolutionState.CheckContainsDocument` crashes VS

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#16771]
I have a crash dump for this. \\jcouvdev\shared-dumps\issue-16771

```C#
The solution does not contain the specified document.
   at Microsoft.CodeAnalysis.SolutionState.CheckContainsDocument(DocumentId documentId)
   at Microsoft.CodeAnalysis.SolutionState.RemoveDocument(DocumentId documentId)
   at Microsoft.CodeAnalysis.Solution.RemoveDocument(DocumentId documentId)
   at Microsoft.CodeAnalysis.Project.RemoveDocument(DocumentId documentId)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateDocumentsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateDocumentsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.SolutionService.<UpdatePrimaryWorkspaceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.RemoteHostService.<SynchronizePrimaryWorkspaceAsync>d__5.MoveNext()
```

![image](https://cloud.githubusercontent.com/assets/12466233/22343012/5835fd70-e3ab-11e6-9d42-50b101025a7e.png)

```
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26119.0 D15REL
Microsoft .NET Framework
Version 4.6.01586
```

**Comment by Pilchie** [comment]
Tag @heejaechang

**Comment by heejaechang** [comment]
@jcouv can you update it to d15rel 26123.00 or higher to see whether it still repro? any version below that has some issues.

**Comment by jcouv** [comment]
I've not hit this again.
