### ISSUE TITLE
"Method must be a static method." when passing lambda expression to AppDomain.Create

### ISSUE THREAD

**Issue by yarin** [dotnet/roslyn#16874]
**Version Used**: 
Visual Studio 2015 Update 3; Visual C# Compiler version 1.3.1.60616.

Compared with and does not occur in Visual Studio 2012 Update 5 (Visual C# Compiler version 4.6.1087.0). In both cases, .NET framework 4.5 was used as target platform, the code was compiled as Debug+AnyCPU and was run on a x64 machine with Windows 7 SP1.

**Steps to Reproduce**:

Compile and run the following program with both VS2012 and VS2015.
```
    class Program
    {
        static void Main()
        {
            var setup = new AppDomainSetup();
            setup.AppDomainInitializer = x => { };
            AppDomain.CreateDomain("", null, setup);
        }
    }
```

**Expected Behavior**:
When compiled with VS2012, the program exits normally. I would expect this to be same in VS2015.

**Actual Behavior**:
When compiled with VS2015, the following exception occurs:
```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Method must be a static method.
Parameter name: ConsoleApplication1.Program+<>c::<Main>b__0_0
  ParamName=ConsoleApplication1.Program+<>c::<Main>b__0_0
  Source=mscorlib
  StackTrace:
       at System.AppDomain.nCreateDomain(String friendlyName, AppDomainSetup setup, Evidence providedSecurityInfo, Evidence creatorsSecurityInfo, IntPtr parentSecurityDescriptor)
       at System.AppDomainManager.CreateDomainHelper(String friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo)
       at Microsoft.VisualStudio.HostingProcess.VSHostAppDomainManager.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup appdomaininfo)
       at System.AppDomain.InternalCreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
       at System.AppDomain.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
       at ConsoleApplication1.Program.Main() in c:\xxx\ConsoleApplication1\Program.cs:line 11
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

nCreateDomain seems to be native code. It looks as if the older compiler was recognizing that the method generated from the lambda expression could be made static, while the new one does not.

**Comment by HaloFour** [comment]
Relevant discussion:  https://roslyn.codeplex.com/workitem/246

My understanding is that whether the lambda method was static or not was an implementation detail that could change based on a number of things even in the previous compilers.  If that method specifically requires a delegate to a static method you're probably better off not using lambdas.

**Comment by gafter** [comment]
See also https://github.com/dotnet/roslyn/issues/4793

**Comment by gafter** [comment]
As @VSadov has pointed out to me:

> AppDomainSetupis a platform API and can have particular requirements like specifically require a delegate with “null” object.
> 
> I would not recommend relying on implementation details of language features such as lambdas to satisfy such low level requirements.
> 
> If specifically a delegate to a static method is required, user should just make a real method like that, take a delegate, pass to the API…

This change (to produce delegates with a non-null receiver for non-capturing lambdas) was done in the VS2015 timeframe, and we do not anticipate reversing it. We measure up to 30% speedup on synthetic benchmarks due to this change, and that can have a real impact on application code.
