### ISSUE TITLE
VS Crash: contract failed in CodeModel.AbstractProjectCodeModel.GetCodeModelCache

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#16973]
While working in Compilers.sln.

Build:
D15Rel 26202.1

Stack trace:

```
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message) in E:\A\_work\6\s\src\Workspaces\Core\Portable\Utilities\Contract.cs:line 86
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractProjectCodeModel.GetCodeModelCache() in E:\A\_work\6\s\src\VisualStudio\Core\Impl\CodeModel\AbstractProjectCodeModel.cs:line 54
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractProjectCodeModel.TryGetCachedFileCodeModel(String fileName, ComHandle`2& fileCodeModelHandle) in E:\A\_work\6\s\src\VisualStudio\Core\Impl\CodeModel\AbstractProjectCodeModel.cs:line 69
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.FireEvents(DocumentId documentId, CancellationToken cancellationToken) in E:\A\_work\6\s\src\VisualStudio\Core\Impl\CodeModel\CodeModelIncrementalAnalyzer.cs:line 86
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.AnalyzeSyntaxAsync(Document document, InvocationReasons reasons, CancellationToken cancellationToken) in E:\A\_work\6\s\src\VisualStudio\Core\Impl\CodeModel\CodeModelIncrementalAnalyzer.cs:line 60
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass30_0.<ProcessDocumentAnalyzersAsync>b__0(IIncrementalAnalyzer a, Document d, CancellationToken c) in E:\A\_work\6\s\src\Features\Core\Portable\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 153
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass31_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext() in E:\A\_work\6\s\src\Features\Core\Portable\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2.MoveNext() in E:\A\_work\6\s\src\Features\Core\Portable\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 229
```

Memory dump:

```%internal_share%\public\tomat\Bugs\16973```

**Comment by Pilchie** [comment]
Is this the same as the OptProf test you were looking at?

**Comment by tmeschter** [comment]
@Pilchie Yes, that's the one.

**Comment by tmeschter** [comment]
@tmat Do you remember what you were doing when this occurred? Loading a solution, or perhaps closing one solution in order to open another?

**Comment by tmat** [comment]
I think closing solution.

**Comment by Pilchie** [comment]
@tmeschter fixed, now, right?

**Comment by tmeschter** [comment]
@Pilchie Yes, this has been fixed.

**Comment by Pilchie** [comment]
Can you link the PR and close?

**Comment by Pilchie** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/17893
