### ISSUE TITLE
InvalidOperationException in StartPushingToWorkspaceAndNotifyOfOpenDocuments()

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#17001]
**Version Used**: VS2017RC.4 15.0.26206.0

- edit a csproj file in a solution with several projects (I added/removed a cs file)
- VS will display a dialog box: click on "reload solution"

I tried to repro it again but couldn't. Perhaps the stack trace is enough:

The exception object (`System.InvalidOperationException: Unexpected false`) contains this stack trace:

```
   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.StartPushingToWorkspaceAndNotifyOfOpenDocuments()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractProjectCodeModel.GetCodeModelCache()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractProjectCodeModel.TryGetCachedFileCodeModel(String fileName, ComHandle`2& fileCodeModelHandle)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.FireEvents(DocumentId documentId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.AnalyzeSyntaxAsync(Document document, InvocationReasons reasons, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass30_0.<ProcessDocumentAnalyzersAsync>b__0(IIncrementalAnalyzer a, Document d, CancellationToken c)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass31_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2.MoveNext()
```

Stack trace:

```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception exception)
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler)
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2<Microsoft.CodeAnalysis.Document, object>.MoveNext()
 	mscorlib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task task)
 	mscorlib.dll!System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<object>.GetResult()
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2<Microsoft.CodeAnalysis.Document, object>.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<object>.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2<Microsoft.CodeAnalysis.Document, object>>(ref Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2<Microsoft.CodeAnalysis.Document, object> stateMachine)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.GetOrDefaultAsync<Microsoft.CodeAnalysis.Document, object>(Microsoft.CodeAnalysis.Document value, System.Func<Microsoft.CodeAnalysis.Document, System.Threading.CancellationToken, System.Threading.Tasks.Task<object>> funcAsync, System.Threading.CancellationToken cancellationToken)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__31`1<Microsoft.CodeAnalysis.Document>.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__31`1<Microsoft.CodeAnalysis.Document>>(ref Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__31`1<Microsoft.CodeAnalysis.Document> stateMachine)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync<Microsoft.CodeAnalysis.Document>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.Document value, System.Func<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer, Microsoft.CodeAnalysis.Document, System.Threading.CancellationToken, System.Threading.Tasks.Task> runnerAsync, System.Threading.CancellationToken cancellationToken)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<ProcessDocumentAnalyzersAsync>d__30.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<ProcessDocumentAnalyzersAsync>d__30>(ref Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<ProcessDocumentAnalyzersAsync>d__30 stateMachine)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.ProcessDocumentAnalyzersAsync(Microsoft.CodeAnalysis.Document document, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.WorkItem workItem, System.Threading.CancellationToken cancellationToken)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ProcessDocumentAsync>d__31.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ProcessDocumentAsync>d__31>(ref Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ProcessDocumentAsync>d__31 stateMachine)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.ProcessDocumentAsync(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.WorkItem workItem, System.Threading.CancellationTokenSource source)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ExecuteAsync>d__18.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ExecuteAsync>d__18>(ref Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ExecuteAsync>d__18 stateMachine)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.ExecuteAsync()
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor.<ProcessAsync>d__12.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ExecuteAsync>d__18.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.AbstractPriorityProcessor.<WaitForHigherPriorityOperationsAsync>d__12.MoveNext()
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)
 	mscorlib.dll!System.Threading.Tasks.Task.WhenAllPromise.Invoke(System.Threading.Tasks.Task completedTask)
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()
 	mscorlib.dll!System.Threading.Tasks.Task<object>.TrySetResult(object result)
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<object>.TrySetResult(object result)
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<object>.SetResult(object result)
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.GlobalOperationAwareIdleProcessor.OnGlobalOperationStopped(object sender, Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs e)
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Notification.GlobalOperationNotificationService.<>c__DisplayClass10_1.<RaiseGlobalOperationStopped>b__1(System.EventHandler<Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs> handler)
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.EventMap.Registry<System.EventHandler<Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs>>.Invoke(System.Action<System.EventHandler<Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs>> invoker)
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.EventMap.EventHandlerSet<System.EventHandler<Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs>>.RaiseEvent(System.Action<System.EventHandler<Microsoft.CodeAnalysis.Notification.GlobalOperationEventArgs>> invoker)
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Notification.GlobalOperationNotificationService.<>c__DisplayClass10_1.<RaiseGlobalOperationStopped>b__0()
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.<>c__DisplayClass15_0.<ContinueWithAfterDelay>b__1(System.Threading.Tasks.Task _)
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.<>c__DisplayClass3_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task antecedent)
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.<>c__DisplayClass7_0`1<bool>.<SafeContinueWith>b__0(System.Threading.Tasks.Task t)
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<bool>.InnerInvoke()
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 	[Native to Managed Transition]
```

**Comment by mavasani** [comment]
@tmeschter @DustinCampbell is this the same Watson we received a few days ago?

**Comment by DustinCampbell** [comment]
It looks like the one @tmeschter asked me about.

**Comment by tmeschter** [comment]
@mavasani Yes.

**Comment by Pilchie** [comment]
@tmeschter - this is fixed now right?

**Comment by tmeschter** [comment]
@Pilchie Yes, this has already been fixed.

**Comment by Pilchie** [comment]
Can you link the PR and close?

**Comment by Pilchie** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/17893
