### ISSUE TITLE
Compilation.GetSemanticModel throws ArgumentException: Syntax tree '' was not found to remove

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#17095]
**Version Used**: 
VS 2017 + Roslyn 2.0.0-rc4
**Steps to Reproduce**:

1.  Write an analyzer that use Compilation.GetSemanticModel
2.  Deploy the extension and open a solution to run the analyzer
3.  Expected exception occurred (it was working in a earlier Roslyn version.)

**Expected Behavior**:
The analyzer run with no exception and code can get the SementicModel instance.

**Actual Behavior**:
Exception occurred, see details:

System.ArgumentException occurred
  HResult=0x80070057
  Message=SyntaxTree '' not found to remove
  Source=Microsoft.CodeAnalysis.CSharp
  StackTrace:
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.Compilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeFix.OperationExtensions.GetOperation(IMethodSymbol method, Compilation compilation, CancellationToken cancellationToken) in C:\Source\Repos\Code Fix\CodeFix\Core\OperationExtensions.cs:line 55
   at Microsoft.CodeFix.Diagnostics.Design.CA1062DiagnosticAnalyzer.CheckMethod(IMethodSymbol symbol, IBlockStatement block, IParameterSymbol parameter, Compilation compilation, Action`1 addDiagnostic, CancellationToken cancellationToken) in C:\Source\Repos\Code Fix\CodeFix\Diagnostics\Design\CA1062DiagnosticAnalyzer.cs:line 114
   at Microsoft.CodeFix.Diagnostics.Design.CA1062DiagnosticAnalyzer.Analyze(IMethodSymbol symbol, Compilation compilation, Action`1 addDiagnostic, AnalyzerOptions options, CancellationToken cancellationToken) in C:\Source\Repos\Code Fix\CodeFix\Diagnostics\Design\CA1062DiagnosticAnalyzer.cs:line 61
   at Microsoft.CodeFix.MethodAnalyzer.AnalyzeCore(ISymbol symbol, Compilation compilation, Action`1 addDiagnostic, AnalyzerOptions options, CancellationToken cancellationToken) in C:\Source\Repos\Code Fix\CodeFix\Core\MethodAnalyzer.cs:line 15
   at Microsoft.CodeFix.SymbolAnalyzer.Analyze(SymbolAnalysisContext context) in C:\Source\Repos\Code Fix\CodeFix\Core\SymbolAnalyzer.cs:line 39
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)

I hide the actual syntax tree, let me know if you need the source for repro.

**Comment by M-Pixel** [comment]
Is the `SyntaxTree ... was not found to remove` error always a compiler bug? I ran into it and posted a [StackOverflow question](https://stackoverflow.com/questions/46571071/roslyn-how-to-get-semantic-model-for-renamed-class-without-not-found-to-remove) - I'm not sure if I'm missing some sort of resolve/update step, or if I'm experiencing the same bug that is referenced by this issue.

**Comment by heejaechang** [comment]
@mazhou-msft can you provide me repro?

**Comment by M-Pixel** [comment]
My case was not a compiler bug. If you take a look at the linked StackOverflow question, there's a very good answer to what was going wrong. I think there's probably an opportunity here to add a more descriptive error when `GetSemanticModel` is given a `SyntaxTree` that the `Compilation` does not contain.

**Comment by mazhou-msft** [comment]
@heejaechang sorry for the delay somehow I don't get a notification form GitHub.

I will try to load the project that can repro months back tomorrow, then I will share you details if I still can repro.
