### ISSUE TITLE
Assertion failed in ObjectWriter.WriteValue

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17233]
Sorry I don't have more details. The popup came up and I just copied the stack.
I think this was on version 15.0.26215.1 D15REL.

```
Enum should not be written with WriteValue.  Write them as ints instead.



   at Roslyn.Utilities.ObjectWriter.WriteValue(Object value)

   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.XmlNameTokenSyntax.WriteTo(ObjectWriter writer)

   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer)

   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(Object instance, IObjectWritable writable)

   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance)

   at Roslyn.Utilities.ObjectWriter.WriteValue(Object value)

   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.XmlNameSyntax.WriteTo(ObjectWriter writer)

   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer)

   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(Object instance, IObjectWritable writable)

   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance)

   at Roslyn.Utilities.ObjectWriter.WriteValue(Object value)

   at Mi......
```

FYI @CyrusNajmabadi since you added this assertion recently.

**Comment by Pilchie** [comment]
I'm pretty sure @jmarolf fixed this already.

**Comment by jaredpar** [comment]
Closing as fixed based on the comments. Can reopen if we see it again.
