### ISSUE TITLE
IDE crash when typing ?1 in Immediate windows (ViewTextSpan)

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#17234]
I think I'm hitting different bugs, as I'm getting at least two different stack traces. 
This is on version 15.0.26216.1 D15REL.

This one seems related to Intellisense.

Repro:
1. Create a trivial VB app (Console, .Net framework 4.6, attached zip file). Then debugged it and hit a breakpoint.
2. Type `?1` in the Immediate window.
3. Get a crash.

I have a dump file:\\\jcouvdev\shared-dumps\issue-17234

[ConsoleAppVBCrash.zip](https://github.com/dotnet/roslyn/files/784727/ConsoleAppVBCrash.zip)

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Queue empty.
  Source=System
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.MapDownToSnapshot(Span span, IProjectionSnapshot start, ITextSnapshot target) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\ViewTextSpan.cs:line 124
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.GetSubjectBufferTextSpanInViewBuffer(TextSpan textSpan) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\ViewTextSpan.cs:line 67
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model.GetViewBufferSpan(TextSpan subjectBufferSpan) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Model.cs:line 295
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model.GetCurrentTextInSnapshot(TextSpan originalSpan, ITextSnapshot textSnapshot, Dictionary`2 textSpanToTextCache, Nullable`1 endPoint) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Model.cs:line 285
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.IsAfterDot(Model model, ITextSnapshot textSnapshot, Dictionary`2 textSpanToText) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 219
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackgroundWorker(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 118
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackground(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 48
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.<>c__DisplayClass13_0.<FilterModel>b__0(Model model) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_FilterModel.cs:line 35
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass16_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(TModel m, CancellationToken c) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\ModelComputation.cs:line 116
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass17_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(Task`1 t) in E:\repos\roslyn\src\EditorFeatures\Core\Implementation\Intellisense\ModelComputation.cs:line 133
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass16_0`2.<SafeContinueWithFromAsync>b__0(Task antecedent) in E:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 268
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

The other crash I'm getting (for the same repro steps) is https://github.com/dotnet/roslyn/issues/17235

**Comment by Pilchie** [comment]
Is this the same issue as the "Ctrl+J", number case?

**Comment by rchande** [comment]
This should be fixed now.
