### ISSUE TITLE
VS analyzer doesn't show important messages about why an analyzer failed or stopped

### ISSUE THREAD

**Issue by ali-hk** [dotnet/roslyn#17265]
I've written a code refactoring that adds some documents under folders. If the user has a folder in the file system that's not part of the project and the refactoring then tries to generate a file into that folder, it fails and shows the "Analzyer disabled because it stopped working, enable/ignore" banner, but the user will have no idea why and no way to figure this out.
A COMException gets thrown with a full explanation of why, but the user has no way of getting to that explanation.
This can occur fairly **easily** if the user adds a file to the project, then decides not to save the CSPROJ.

Similarly, if a file has been marked read-only, an UnauthorizedAccessException occurs upon applying the change, which shows the banner with no indication of why it failed.

Here's an example of the details from a COMException:
```
A file or folder with the name 'Internal' already exists on disk at this location. Please choose another name.

If this file or folder does not appear in the Solution Explorer, then it is not currently part of your project. To view files which exist on disk, but are not in the project, select Show All Files from the Project menu.

   at EnvDTE.ProjectItems.AddFolder(String Name, String Kind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.CreateFolder(ProjectItems currentItems, String container)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.FindOrCreateFolder(Project project, IEnumerable`1 containers)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToFolder(IVisualStudioHostProject hostProject, Project project, DocumentId documentId, IEnumerable`1 folders, String documentName, SourceCodeKind sourceCodeKind, SourceText initialText, String filePath, Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info, SourceText initialText, Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info, SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
```

Here things got even weirder when I deleted the folder from disk and tried again. In order to resolve this, I had to close Visual Studio and reopen the solution.
```
bufferAdapter is not a VsTextDocData

   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetAdapter(IVsTextBuffer bufferAdapter)
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetDocumentBuffer(IVsTextBuffer bufferAdapter)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider, String filePath, Boolean needsSave, Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(IVisualStudioHostDocument hostDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.StandardTextDocument.UpdateText(SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentTextChanged(DocumentId documentId, SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges, DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
```

Repro steps (read-only scenario):

1. Mark a file as read-only
2. Attempt to update that file via a refactoring
Expected: User is shown a message saying the file is read-only
Actual: It appears to the user as if the analyzer itself failed with no way of getting more information

Repro steps (existing folder scenario):
1. Create a folder in the project directory directly from cmd or File Explorer
2. Attempt to add a document to the project with that folder name as one of the arguments
Expected: Document creation shouldn't fail, it should generate into that folder and add the document (and hence the folder to the project)
Actual: It appears to the user as if the analyzer itself failed with no way of getting more information

**Comment by CyrusNajmabadi** [comment]
Not planning on making changes here.
