### ISSUE TITLE
Assert in object writing for VB decimal literals

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#17336]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Enum should not be written with WriteValue.  Write them as ints instead.

   at Roslyn.Utilities.ObjectWriter.WriteValue(Object value)

   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.DecimalLiteralTokenSyntax.WriteTo(ObjectWriter writer)

   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer)

   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(Object instance, IObjectWritable writable)

   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance)

   at Roslyn.Utilities.ObjectWriter.WriteValue(Object value)

   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.LiteralExpressionSyntax.WriteTo(ObjectWriter writer)

   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer)

   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(Object instance, IObjectWritable writable)

   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance)

   at Roslyn.Utilities.ObjectWriter.WriteValue(Object......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by CyrusNajmabadi** [comment]
@jmarolf You recently did a similar for for XmlTokens right?  Woudl this be a <1 min fix for you?
