### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.ForStatement Is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17397]
Failed in [this](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/446) run

```
Stacktrace

MESSAGE:
Assert.EndsWith() Failure:
Expected: 81
Actual: 0
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest.VerifyLastReplOutputEndsWith(String expectedReplOutput) in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractInteractiveWindowTest.cs:line 62
at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.ForStatement() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpInteractive.cs:line 36
```

**Comment by CyrusNajmabadi** [comment]
Closing as this test is not skipped.
