### ISSUE TITLE
Compiler crash: something is wrong with the decision tree for switch statement patterns

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#17542]
**Version Used**: 

`master` branch @ March 4

**Steps to Reproduce**:

Compile the following code:

```c#
class S {
  void M(string s, bool b) {
    switch (s) {
      case var _ when b: break;
      case "abc": break;
      case null: break;
    }
  }
}
```

**Expected Behavior**:

Successful compilation

**Actual Behavior**:

```
This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddByNull(DecisionTree decision, DecisionMaker makeDecision) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 362
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddByNull(Guarded guarded, DecisionMaker makeDecision) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 434
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddByNull(DecisionTree decision, DecisionMaker makeDecision) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 365
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddByNull(ByType byType, DecisionMaker makeDecision) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 382
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddByNull(DecisionTree decision, DecisionMaker makeDecision) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 353
   at Microsoft.CodeAnalysis.CSharp.DecisionTreeBuilder.AddToDecisionTree(DecisionTree decisionTree, SyntaxNode sectionSyntax, BoundPatternSwitchLabel label) in \Src\Compilers\CSharp\Portable\BoundTree\DecisionTreeBuilder.cs:line 52
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.PatternSwitchLocalRewriter.LowerToDecisionTree(BoundExpression loweredExpression, BoundPatternSwitchStatement node) in \Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_PatternSwitchStatement.cs:line 172
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.PatternSwitchLocalRewriter.LowerPatternSwitch(BoundExpression loweredExpression, BoundPatternSwitchStatement node, ArrayBuilder`1 loweredDecisionTree) in \Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_PatternSwitchStatement.cs:line 140
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.PatternSwitchLocalRewriter.MakeLoweredForm(BoundPatternSwitchStatement node) in \Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_PatternSwitchStatement.cs:line 76
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.PatternSwitchLocalRewriter.MakeLoweredForm(LocalRewriter localRewriter, BoundPatternSwitchStatement node) in \Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_PatternSwitchStatement.cs:line 51
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitPatternSwitchStatement(BoundPatternSwitchStatement node) in \Src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_PatternSwitchStatement.cs:line 16
```

**Comment by alrz** [comment]
Looks like https://github.com/dotnet/roslyn/issues/16876

**Comment by gafter** [comment]
Yes, this is a dup. I will see if I can get a fix included in an update sooner than the next quarterly update.
