### ISSUE TITLE
VS crashes when typing valid deconstructing declaration

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#17572]
Uncomment the second line in the following code to crash VS 2017 RC4

```cs
  class Program
  {
    static void Main(string[] args)
    {
       (var (a,b), var c) = ((1,2),3); // this line compiles
    // (var (a,b), var c)
    }
```

This is rather unfortunate as this could be a start of some valid syntax construct as demonstrated by the first line.

![vscrash](https://cloud.githubusercontent.com/assets/5566206/23610749/ccc10304-0284-11e7-8e97-9756c5c8ada3.gif)

**Comment by alrz** [comment]
```
System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeconstructionVariable(TypeSymbol declType, SingleVariableDesignationSyntax designation, CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Deconstruct.cs:line 752
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationVariables(TypeSymbol declType, VariableDesignationSyntax node, CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 740
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationVariables(TypeSymbol declType, VariableDesignationSyntax node, CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 754
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationExpression(DeclarationExpressionSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 726
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 641
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 396
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 304
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTupleExpression(TupleExpressionSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 824
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 629
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 396
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 304
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 512
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 505
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 50
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2336
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2324
   at Microsoft.CodeAnalysis.CSharp.Binder.BindEmbeddedBlock(BlockSyntax node, DiagnosticBag diagnostics) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2316
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1527
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 879
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 434
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 324
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 239
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 138
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(DiagnosticBag diagnostics, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2003
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1970
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1908
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAllDiagnosticsWithoutStateTrackingAsync>d__49.MoveNext() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\Core\Portable\DiagnosticAnalyzer\CompilationWithAnalyzers.cs:line 448
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAllDiagnosticsAsync>d__42.MoveNext() in D:\#TeamCity\buildAgent\work\596e688e8f7f38c8\!roslyn\sources\dotnet\Src\Compilers\Core\Portable\DiagnosticAnalyzer\CompilationWithAnalyzers.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__9.MoveNext()
```

**Comment by mjcheetham** [comment]
Repos also for me in VS2017 RTW (15.0.0-RTW+26228.4).

In addition, VS _also_ crashes if you type a single slash `/` character either above or below the nested tuple statements.. even the one which doesn't crash.

```cs
/
(var (a,b), var c) = ((1,2),3); // this line compiles
// (var (a,b), var c)
```

This crash doesn't display the "Program has stopped working" dialog. `devenv.exe` just stops.

If you try a second slash quickly enough (as if to type a comment `//`) then it doesn't crash (presumably because the compiler only re-parses the file once you stop typing long enough).

![vs_crash_1](https://cloud.githubusercontent.com/assets/5658207/23715669/48a5b522-0425-11e7-9b52-4538ad2d375a.gif)

**Comment by mjcheetham** [comment]
<details>
  <summary>Stack trace</summary>
<pre>
System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeconstructionVariable(TypeSymbol declType, SingleVariableDesignationSyntax designation, CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationVariables(TypeSymbol declType, VariableDesignationSyntax node, CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationVariables(TypeSymbol declType, VariableDesignationSyntax node, CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationExpression(DeclarationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTupleExpression(TupleExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleBinaryOperator(BinaryExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol.LocalSymbolWithEnclosingContext.InferTypeOfVarVariable(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol.GetTypeSymbol()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol.get_Type()
   at Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol.Microsoft.CodeAnalysis.ILocalSymbol.get_Type()
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.TypeFromVariable(SingleVariableDesignationSyntax variableDesignation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode(SyntaxNode syntax, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, List`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
</pre>
</details>
