### ISSUE TITLE
VS crash in VisualStudioProjectTracker.GetOrCreateProjectFromArgumentsAndReferences

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17570]
_From @AArnott on March 6, 2017 3:4_

d15rel 26228.00
I have lightweight solution load turned on.
This crashed twice in a row (2 out of 2 attempts)

```
git clone https://github.com/aarnott/pinvoke
cd pinvoke
git checkout bugrepro/roslyn-project-system/1678
devenv src\pinvoke.sln
```

Crashes with:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.Single[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<Byte>)
   at System.Linq.ImmutableArrayExtensions.SingleOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Immutable.ImmutableArray`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.GetOrCreateProjectFromArgumentsAndReferences(Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContextFactory, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader, System.String, System.Collections.Generic.IReadOnlyDictionary`2<System.String,Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DeferredProjectInformation>, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.String>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<PopulateWorkspaceFromDeferredProjectInfoAsync>d__69.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<LoadSolutionFromMSBuildAsync>d__62.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<FireAndForget>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

_Copied from original issue: dotnet/roslyn-project-system#1678_

**Comment by davkean** [comment]
_From @AArnott on March 6, 2017 3:7_

Repro project (in case the contents of .vs or some other folder are interesting)
[pinvoke.zip](https://github.com/dotnet/roslyn-project-system/files/820067/pinvoke.zip)

**Comment by AArnott** [comment]
Note the repro disappeared after I ran `git clean -fdx :/` and turned off lightweight solution load. So please turn that on, and possibly use the .zip file I included in the repro.

**Comment by Pilchie** [comment]
Thanks @AArnott This an issue we've seen in Watson but haven't figured out yet.  It's definitely related to lightweight solution load.  I'll take a look as soon as I get a chance.

**Comment by AArnott** [comment]
Awesome. I hope my repro helps you understand the Watson reports.

**Comment by Pilchie** [comment]
I'm unable to repro from your zip file, though I also suspect I don't have all the right dependencies installed.  I get these errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'D:\KevinPi\Desktop\pinvoke\pinvoke\src\NtDll\NtDll.csproj' for '.NETFramework,Version=v4.6'.			0	
Error		Unable to resolve 'D:\KevinPi\Desktop\pinvoke\pinvoke\src\Wtsapi32\Wtsapi32.csproj' for '.NETFramework,Version=v4.0'.			0	
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	Windows.Core	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111	
```

Plus 48 copies of:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateCodeFromAttributes" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	Gdi32	C:\Users\KevinPi\.nuget\packages\codegeneration.roslyn.buildtime\0.1.57\build\CodeGeneration.Roslyn.BuildTime.targets	20	
```

**Comment by AArnott** [comment]
The NuGet resolve errors are NuGet/Home#4753 and can be ignored as far as I can tell.

The GenerateCodeFromAttributes error can be fixed by installing [MSBuild 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159). I don't know if that's significant to the repro though.

Or if it would be helpful I can allow someone to remote into my laptop to study the repro there.

**Comment by Pilchie** [comment]
Interesting - looking at this again, and I'm not seeing it repro, because I'm seeing the CPS based projects opted out of DPL, and so we never have any projects that are opening in DPL that have refereneces to them. I suspect that finding the reason CPS projects are being loaded in DPL mode will be the key here.

**Comment by davkean** [comment]
@AArnott What build is this? We had a bug fixed late where we were being opt'd in. Either way though, we're going to be opt'd in eventually - won't this still be an issue?

**Comment by Pilchie** [comment]
@davkean Yes, but I'd like to have a repro so that I can test that my fix is doing the right thing.  I've made a guess at it, but I'm not confident in it, and we're seeing Watson hits of this in the wild too.

**Comment by Pilchie** [comment]
Actually - I take that back.  The `CodeGeneration` and `CodeGeneration.Debugging` projects *are* opted in, even though they are CPS projects.  They just don't trigger this bug because they don't have any P2P refs...

**Comment by davkean** [comment]
@Pilchie You can either build us and remove this line: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/Packaging/CSharpProjectSystemPackage.cs#L34. Or find the Microsoft.VisualStudio.ProjectSystem.CSharp.VS.pkgdef on the machine and remove the opt out and run `devenv /setup`.

**Comment by AArnott** [comment]
@davkean I was definitely using RTW (d15rtwsvc 26228.4) when I repro'd this. And now that I'm on 26228.9 I saw it crash with this same callstack just yesterday.

**Comment by Pilchie** [comment]
@davkean I tried enlisting and removing that line, but all projects still seem opted out except the two above.  I don't think it matters for this repro, I think I know how to force it again, but it's still strange.

**Comment by Pilchie** [comment]
(and I verified in the modules window that my binaries were being loaded)

**Comment by Pilchie** [comment]
I was able to force a repro and put together a fix in https://github.com/dotnet/roslyn/pull/17903. @AArnott let's work to tomorrow to verify that it works for you.

**Comment by AArnott** [comment]
Sounds good. :)
