### ISSUE TITLE
"CSharpAddImportCodeFixProvider' encountered an error and has been disabled" keeps appearing

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#17702]
**Version Used**: VS2017 

**Steps to Reproduce**:
Not sure. Happens occasionally when editing files. A error notification appears with "'CSharpAddImportCodeFixProvider' encountered an error and has been disabled." The following stack trace is offered:
```
System.ArgumentNullException : Value cannot be null.
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.Location.Create(SyntaxTree syntaxTree,TextSpan textSpan)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.CreateSourceLocation(String filePath,Int32 start,Int32 length)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadLocation()
   at Microsoft.CodeAnalysis.SymbolKey.Reader`1.ReadArray[T](Func`1 readFunction)
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKey()
   at Microsoft.CodeAnalysis.SymbolKey.Reader`1.ReadArray[T](Func`1 readFunction)
   at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader,Boolean isPartialMethodImplementationPart,IMethodSymbol method)
   at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader,String metadataName,Int32 arity,Boolean isPartialMethodImplementationPart,ImmutableArray`1 parameterRefKinds,Int32 beforeParametersPosition,IMethodSymbol method)
   at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader,String metadataName,Int32 arity,Boolean isPartialMethodImplementationPart,ImmutableArray`1 parameterRefKinds,Int32 beforeParametersPosition,INamedTypeSymbol namedType)
   at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
   at Microsoft.CodeAnalysis.SymbolKey.Resolve(String symbolKey,Compilation compilation,Boolean ignoreAssemblyKey,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<>c__DisplayClass21_0.<GetUnfilteredSymbolsAsync>b__0(ISymbol s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.GetUnfilteredSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.AddDeclarationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindDeclarationsAsyncImpl(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SearchScope.FindDeclarationsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.GetNamespacesForMatchingExtensionMethodsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReferenceFinder.DoAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.FindResultsInAllSymbolsInStartingProjectAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Further, selecting the enable and ignore future erros button doesn't work as expected as this error continues to appear.

**Expected Behavior**:
Ideally the fix provider shouldn't error. But when it does, the request to "ignore future errors" should be respected.

**Actual Behavior**:
"Endless" yellow error bars appear in the editor window, despite selecting "Enable and ignore future errors"

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Is this something you already fixed?
