### ISSUE TITLE
CSharpCodeActions.Add Using (fuzzy match) and related fixes after Rename Tracking Is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17818]
Encountered in [this](https://github.com/dotnet/roslyn/pull/17760) PR

[Jenkins Failure](https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3441/testReport/junit/(root)/CSharpCodeActions/Add_Using__fuzzy_match__and_related_fixes_after_Rename_Tracking)

```
MESSAGE:
No Active Light Bulbs in View!
+++++++++++++++++++
STACK TRACE:
 at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message)
 at Roslyn.Hosting.Test.VerifyCodeActionsAction.ExecuteOnUIThread() in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\RoslynTaoActions\Actions\EditorTestApp\VerifyCodeActionsAction.cs:line 125 
 at Roslyn.Hosting.Test.EditorAction.<Execute>b__0_0() in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 21
 at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
 at Roslyn.Hosting.Test.EditorAction.Execute(TaoEngine engine) in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 13
 at Tao.Engine.DebuggableActionExecutor.Execute() at Tao.Engine.DefaultActionExecutor.Execute()
```

**Comment by genlu** [comment]
Saw this again in #18238 

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev16/job/windows_eta_open_prtest/48/testReport/junit/(root)/CSharpCodeActions/Add_Using__fuzzy_match__and_related_fixes_after_Rename_Tracking/

**Comment by Pilchie** [comment]
@rchande - did these get ported?  Should we just close this bug?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't been flakey and is not skipped.
