### ISSUE TITLE
CSharpCodeActions.Suppress assembly SuppressMessageAttribute Is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17819]
Encountered in [this](https://github.com/dotnet/roslyn/pull/17760) PR

[Jenkins Failure](https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3441/testReport/junit/(root)/CSharpCodeActions/Suppress_assembly_SuppressMessageAttribute/)

```
MESSAGE:
Exceptions found in the exception log
+++++++++++++++++++
STACK TRACE:
 at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16
 at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
 at Roslyn.Hosting.Test.EditorTestAppAction.Execute(TaoEngine engine) in D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 147
 at Tao.Engine.DebuggableActionExecutor.Execute()
 at Tao.Engine.DefaultActionExecutor.Execute()
```

**Comment by genlu** [comment]
See this again

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/4058/testReport/junit/(root)/CSharpCodeActions/Suppress_assembly_SuppressMessageAttribute/

**Comment by genlu** [comment]
See this again in #18238 

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev16/job/windows_eta_open_prtest/48/testReport/junit/(root)/CSharpCodeActions/Suppress_assembly_SuppressMessageAttribute/

**Comment by 333fred** [comment]
Again in #18330, https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/4230/.

**Comment by CyrusNajmabadi** [comment]
This test doesn't exist anymore.
