### ISSUE TITLE
Contract failure in VisualStudioWorkspaceImpl while opening a .cshtml file in the editor.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#1782]
1. open a Asp.Net **vNext** Web Application - choose Asp.Net 5 Preview Web API template
2. double click Views-> _GlobalImport.cshtml to open it in the editor
3. Contract failure dialog shows up
4. Vs Freezes after dismissing the dialog, colorization fails. Sometimes you dont get the contract failure but vs freezes rightaway. Repro is consistent.

```C#
Contract.Requires(sharedHierarchy == LinkedFileUtilities.GetSharedHierarchyForItem(hierarchy, itemId));
```
~~~
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue

   at Roslyn.Utilities.Contract.Assert(Boolean condition, String message)
   at Roslyn.Utilities.Contract.Requires(Boolean condition, String message)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.VisualStudioWorkspaceHost.SubscribeToSharedHierarchyEvents(DocumentId documentId) in D:\Roslyn\Main\Open\src\VisualStudio\Core\Def\Implementation\ProjectSystem\VisualStudioWorkspaceImpl.cs:line 1105
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.VisualStudioWorkspaceHost.Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioWorkspaceHost.OnDocumentOpened(DocumentId documentId, ITextBuffer textBuffer, Boolean currentContext) in D:\Roslyn\Main\Open\src\VisualStudio\Core\Def\Implementation\ProjectSystem\VisualStudioWorkspaceImpl.cs:line 1082
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.<>c__DisplayClass116_0.<AddDocument>b__1(IVi......
<truncated>

Abort   Retry   Ignore   

~~~

**Comment by Pilchie** [comment]
@heejaechang I think you just added this, no?

**Comment by heejaechang** [comment]
@Pilchie yes. I did. so, hierarchy for the document does get changed.

**Comment by heejaechang** [comment]
@AArnott Andrew, my assert found a case where IVsHierarchy for shared project being changed in web case. is there a way to get notified for such case?

**Comment by Pilchie** [comment]
Also tagging @dpoeschl so he sees this.

**Comment by AArnott** [comment]
@heejaechang Yay for asserts! :)
ASP.NET 5 doesn't support "shared projects". Are you talking about their stub hierarchies used for the language service? Documents should never be owned by these, I believe.
In general though, you can hook IVsRunningDocumentTableEvents to be notified when a document transfers in ownership.

**Comment by heejaechang** [comment]
found the issue. validating a fix. I need to bring this to RC though since fix caused this is RC fix.

**Comment by balajikris** [comment]
that's great. It is also blocking me in finding a repro for a watson crash.

**Comment by heejaechang** [comment]
@balajikris you can unblock yourself using this - https://github.com/dotnet/roslyn/pull/1786/files - before I check this in.

**Comment by balajikris** [comment]
@heejaechang Awesome, thank you.

**Comment by heejaechang** [comment]
#1786 - PR sent.

**Comment by heejaechang** [comment]
checked in #1786
