### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.Rename_Control Is flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17821]
Encountered in [this](https://github.com/dotnet/roslyn/pull/17760) PR

[Jenkins Failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1159/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/Rename_Control/)

```
MESSAGE:
System.InvalidCastException : Unable to cast object of type 'Microsoft.VisualStudio.PlatformUI.UIHierarchyMarshaler' to type 'System.ComponentModel.Design.IDesignerHost'.
+++++++++++++++++++
STACK TRACE:
Server stack trace:
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.EditWinFormButtonProperty(String buttonName, String propertyName, String propertyValue, String propertyTypeName)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown
 at [0]:
 at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.EditWinFormButtonProperty(String buttonName, String propertyName, String propertyValue, String propertyTypeName)
 at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.Rename_Control() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicWinForms.cs:line 113
```

**Comment by Pilchie** [comment]
Looks like the same issue as 17820 in another scenario.
