### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.Remove_Event_Handle Is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#17820]
Encountered in [this](https://github.com/dotnet/roslyn/pull/17760) PR

[Jenkins Failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1159/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/Remove_Event_Handler/)

```
MESSAGE:
System.InvalidCastException : Unable to cast object of type 'Microsoft.VisualStudio.PlatformUI.UIHierarchyMarshaler' to type 'System.ComponentModel.Design.IDesignerHost'.
+++++++++++++++++++
STACK TRACE:
Server stack trace:
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.EditWinFormButtonEvent(String buttonName, String eventName, String eventHandlerName)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown
 at [0]:
 at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.EditWinFormButtonEvent(String buttonName, String eventName, String eventHandlerName)
 at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.Remove_Event_Handler() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicWinForms.cs:line 139
```

**Comment by Pilchie** [comment]
@tmeschter any idea what's up here?

**Comment by tmeschter** [comment]
@Pilchie Not a clue. :-) @jmarolf ported that test, I believe.

**Comment by Pilchie** [comment]
Oh - oops.  @jmarolf ?

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by sharwell** [comment]
This is no longer occurring
