### ISSUE TITLE
"Move Type to" throws NullReferenceException

### ISSUE THREAD

**Issue by Seairth** [dotnet/roslyn#17837]
**Version Used**: VS 2017 Pro / 15.0.0.-RTW+26228.4

I had a file with two classes, Class1 and Class2. Class1 had dependencies on Class2, but were otherwise simple classes. I used "Move Type To..." to move Class2 to a separate file.  The new file was created and contained Class2.  However, Class2 was not removed from the original file and VS reported an exception from the provider. 

Stack trace:

```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Utilities.IVsEditorAdaptersFactoryServiceExtensions.TryGetUndoManager(IVsEditorAdaptersFactoryService editorAdaptersFactoryService,Workspace workspace,DocumentId contextDocumentId,CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetUndoManager()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info,SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

**Comment by dpoeschl** [comment]
@CyrusNajmabadi Looks like you addressed something similar with https://github.com/dotnet/roslyn/commit/1826965ea15fe44ecd590b60f43c72686eb4b51a. Do you think this is fixed by that change as well?

**Comment by CyrusNajmabadi** [comment]
Yes.  That should have fixed this issue as well.

**Comment by dpoeschl** [comment]
Awesome, thanks Cyrus. And thanks for the bug report @Seairth! This should be fixed in an upcoming release of Visual Studio.
