### ISSUE TITLE
Move type to file crashes in CPS projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#17898]
![image](https://cloud.githubusercontent.com/assets/1103906/23974073/794ae82e-0a2d-11e7-9dc8-f37f0e293031.png)

```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Utilities.IVsEditorAdaptersFactoryServiceExtensions.TryGetUndoManager(IVsEditorAdaptersFactoryService editorAdaptersFactoryService,Workspace workspace,DocumentId contextDocumentId,CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetUndoManager()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info,SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
```

I suspect that this was supposed to be disabled.

**Comment by davkean** [comment]
It also moved this interface to a strange location (it's reversed the folder names):

![image](https://cloud.githubusercontent.com/assets/1103906/23974134/b7025008-0a2d-11e7-8719-6ffc6345162a.png)

@CyrusNajmabadi I suspect this is our bug - I'm guessing this comes from the folder names that we end up passing to you?

**Comment by CyrusNajmabadi** [comment]
Do you have the actual line where this crashed?  I'd like to at least know what is null.

**Comment by davkean** [comment]
Nope.

**Comment by CyrusNajmabadi** [comment]
Is there a repro for this?

**Comment by davkean** [comment]
Ugh, I thought it was all move type to files in a CPS (.NET Core) project - but it's not. I need to see if I can repro this again...

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Do you have a repro for this?  I can make our code more resilient here.  BUt we'd like to know what causes this in teh first place.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Did you mean to tag @davkean?

**Comment by CyrusNajmabadi** [comment]
Yes, yes i did :)

**Comment by davkean** [comment]
I've not hit it again and can't repro it.
