### ISSUE TITLE
GetOperation for VB using throws an exception

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#17917]
```VB
Module Program
    Class C
        Implements IDisposable
        Public Sub Dispose() Implements IDisposable.Dispose
        End Sub
    End Class
    Sub Main(args As String())
        Using c1 As New C
            Console.WriteLine(c1)
        End Using
    End Sub
End Module
```

Attempting to get the IOperation tree of the `UsingStatement` node results in this exception:
```
System.Exception: ASSERT FAILED 
3/15/2017 16:06:08
Source:    at Roslyn.Editor.TestApp.OutputWindowTraceListener.Fail(String message, String detailMessage) in D:\git\roslyn-internal\Closed\Hosting\EditorTestApp\UI\ToolWindows\Output\OutputWindowTraceListener.cs:line 50
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.Bind(Binder binder, SyntaxNode node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodeSummary(VisualBasicSyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SemanticModel.GetOperationInternal(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Test.Extensions.SemanticModelExtensions.GetOperationInternal(SemanticModel model, SyntaxNode node)
```

**Comment by jinujoseph** [comment]
@333fred , can you check if this is fixed

**Comment by 333fred** [comment]
This issue does appear to be fixed. However, we now have an issue where we're not appropriately creating the nested `IVariableDeclaration`s that go under the Using. Current tree for the above UsingStatementSyntax:

```
IVariableDeclarationStatement (0 declarations) (OperationKind.VariableDeclarationStatement) (Syntax: 'Using c1 As New C')
```

**Comment by 333fred** [comment]
Tracking that issue with https://github.com/dotnet/roslyn/issues/22279.
