### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#18026]
[Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1524/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpCodeActions/GenerateMethodInClosedFile/) failed in [this](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1524/) run from [this](https://github.com/dotnet/roslyn/pull/17932) PR.

```
MESSAGE:
System.InvalidOperationException : Sequence contains no matching element
+++++++++++++++++++
STACK TRACE:
Server stack trace:
 at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.GetProject(String nameOrFileName)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.AddFile(String projectName, String fileName, String contents, Boolean open)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown
 at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.AddFile(String projectName, String fileName, String contents, Boolean open)
 at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GenerateMethodInClosedFile() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpCodeActions.cs:line 23
```

**Comment by tmat** [comment]
@ivanbasov FYI

**Comment by Pilchie** [comment]
@dpoeschl does this look famillar at all to yo?u

**Comment by jmarolf** [comment]
This is actually a failure due to a test infrastructure change in one of my PRs
