### ISSUE TITLE
VS2017 Editor: The refactoring provider crashes when using the result of a C#7 Tuple

### ISSUE THREAD

**Issue by raffaeler** [dotnet/roslyn#18031]
**Version Used**:  Visual Studio 2017

**Steps to Reproduce**:
1.  Create a method returning a C#7 style Tuple
2.  Call that method from another method and use the tuple as by the picture
3.  To cause the problem just select the "Message" property by double clicking on it (see picture)
4.  Visual Studio will show the crash of the ExtractMethodCodeRefactoringProvider

**Expected Behavior**:
The "ExtractMethodCodeRefactoringProvider" should not crash.
Despite clicking the button "Enable and ignore future errors" the yellow bar shows up again

**Actual Behavior**:
![refactoringproviderbug](https://cloud.githubusercontent.com/assets/5183152/24168890/1b87362c-0e7c-11e7-925e-7b31b44b4652.png)

```
The stack trace of the yellow bar is the following:
System.ArgumentNullException : Value cannot be null.
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.Location.Create(SyntaxTree syntaxTree,TextSpan textSpan)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.CreateSourceLocation(String filePath,Int32 start,Int32 length)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadLocation()
   at Microsoft.CodeAnalysis.SymbolKey.Reader`1.ReadArray[T](Func`1 readFunction)
   at Microsoft.CodeAnalysis.SymbolKey.TupleTypeSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
   at Microsoft.CodeAnalysis.SymbolKey.Resolve(String symbolKey,Compilation compilation,Boolean ignoreAssemblyKey,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.Extensions.ResolveType[T](SemanticModel semanticModel,T symbol)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.CreateMethodParameters()
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateMethodDefinition(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Pilchie** [comment]
@CyrusNajmabadi Is this a repro for the extract method issue we've seen reported a couple of times?

**Comment by CyrusNajmabadi** [comment]
No.  But this is a known issue with SymbolKeys that i fixed here: https://github.com/dotnet/roslyn/pull/17863
