### ISSUE TITLE
VS crash: ArgumentOutOfRangeException thrown by AbstractSemanticQuickInfoProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18041]
Stack trace:

```
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position, Boolean findInsideTrivia) in E:\A\_work\19\s\src\Compilers\Core\Portable\Syntax\SyntaxNode.cs:line 1315
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.<FindTokenInLinkedDocument>d__2.MoveNext() in E:\A\_work\19\s\src\EditorFeatures\Core\Implementation\Intellisense\QuickInfo\Providers\AbstractSemanticQuickInfoProvider.cs:line 150
```

```
	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.FindTokenInLinkedDocument(Microsoft.CodeAnalysis.SyntaxToken token, Microsoft.CodeAnalysis.Document originalDocument, Microsoft.CodeAnalysis.Document linkedDocument, System.Threading.CancellationToken cancellationToken) Line 147	C#
>	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.BuildContentAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxToken token, System.Threading.CancellationToken cancellationToken) Line 74	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.GetQuickInfoItemAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxToken token, int position, System.Threading.CancellationToken cancellationToken) Line 78	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.GetItemAsync(Microsoft.CodeAnalysis.Document document, int position, System.Threading.CancellationToken cancellationToken) Line 43	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller.ComputeModelInBackgroundAsync(int position, Microsoft.VisualStudio.Text.ITextSnapshot snapshot, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.IQuickInfoProvider> providers, bool trackMouse, System.Threading.CancellationToken cancellationToken) Line 154	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller.StartSession.AnonymousMethod__0(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Model model, System.Threading.CancellationToken cancellationToken) Line 109	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<System.__Canon>.ChainTaskAndNotifyControllerWhenFinished.AnonymousMethod__0(System.Threading.Tasks.Task<System.__Canon> t) Line 133	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWithFromAsync.AnonymousMethod__0(System.Threading.Tasks.Task antecedent) Line 268	C#
```

Crash dump:
%internal_share%\public\tomat\Bugs\18041

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Looks like this could be that race in linked documents.  @tmat Out of curiosity, did this happen shortly after a paste?

**Comment by tmat** [comment]
Not sure. It's possible.

**Comment by dpoeschl** [comment]
It's definitely that same issue.

**Comment by Pilchie** [comment]
Also reported in https://developercommunity.visualstudio.com/content/problem/43706/random-visual-studio-crash.html

**Comment by Pilchie** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/18890, right?
