### ISSUE TITLE
Assert failure at Microsoft.CodeAnalysis.VisualBasic.Syntax.KeywordTable.TokenOfString(String tokenName)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18073]
Execute the following IOperation unit test:

```
       <Fact, WorkItem(17595, "https://github.com/dotnet/roslyn/issues/17595")>
        Public Sub InvalidLambdaBinding_UnboundLambda()
            Dim source = <![CDATA[
Class Program
    Private Shared Sub Main(args As String())
        Dim x = Function() F()'BIND:"Function() F()"
    End Sub

    Private Shared Sub F()
    End Sub
End Class
    ]]>.Value

            Dim expectedOperationTree = <![CDATA[
]]>.Value

            VerifyOperationTreeForTest(Of SingleLineLambdaExpressionSyntax)(source, expectedOperationTree)
        End Sub
```

**Got:**
```
      Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : 
      
      Stack Trace:
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceListener.Fail(String message)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition)
           at Microsoft.CodeAnalysis.VisualBasic.Syntax.KeywordTable.TokenOfString(String tokenName)
           at Microsoft.CodeAnalysis.VisualBasic.SyntaxFacts.GetKeywordKind(String text)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.EscapeIdentifier(String identifier)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.CreatePart(SymbolDisplayPartKind kind, ISymbol symbol, String text, Boolean noEscaping)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitLocal(ILocalSymbol symbol)
           at Microsoft.CodeAnalysis.VisualBasic.Symbols.LocalSymbol.Accept(SymbolVisitor visitor)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol, SymbolDisplayFormat format)
           at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayString(ISymbol symbol, SymbolDisplayFormat format)
           at Microsoft.CodeAnalysis.VisualBasic.Symbol.ISymbol_ToDisplayString(SymbolDisplayFormat format)
           at Microsoft.CodeAnalysis.Test.Extensions.SymbolExtensions.ToTestDisplayString(ISymbol symbol)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.LogSymbol(ISymbol symbol, String header, Boolean logDisplayString)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.LogLocals(IEnumerable`1 locals)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitBlockStatement(IBlockStatement operation)
           at Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept(OperationVisitor visitor)
           at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitLambdaExpression(ILambdaExpression operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitLambdaExpression(ILambdaExpression operation)
           at Microsoft.CodeAnalysis.VisualBasic.BoundLambda.Accept(OperationVisitor visitor)
           at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitConversionExpression(IConversionExpression operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitConversionExpression(IConversionExpression operation)
           at Microsoft.CodeAnalysis.VisualBasic.BoundConversion.Accept(OperationVisitor visitor)
           at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(IOperation operation)
           at Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.GetOperationTree(IOperation operation, Int32 initialIndent)
           at Microsoft.CodeAnalysis.VisualBasic.UnitTests.SemanticModelTestBase.GetOperationTreeForTest[TSyntaxNode](VisualBasicCompilation compilation, String fileName, Int32 which)
           at Microsoft.CodeAnalysis.VisualBasic.UnitTests.SemanticModelTestBase.GetOperationTreeForTest[TSyntaxNode](String testSrc, VisualBasicParseOptions parseOptions, Int32 which)
           at Microsoft.CodeAnalysis.VisualBasic.UnitTests.SemanticModelTestBase.VerifyOperationTreeForTest[TSyntaxNode](String testSrc, String expectedOperationTree, VisualBasicParseOptions parseOptions, Int32 which)
        Open\src\Compilers\VisualBasic\Test\Semantic\IOperation\IOperationTests_InvalidExpression.vb(219,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.IOperationTests.InvalidLambdaBinding_UnboundLambda()
```

**Comment by mavasani** [comment]
Tag @dotnet/analyzer-ioperation @AlekseyTs

**Comment by jinujoseph** [comment]
@333fred , can you check if this still repros

**Comment by mavasani** [comment]
Test is unskipped and executing fine
