### ISSUE TITLE
Fix all in solution fails before making any changes

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#18124]
**Version Used**: VS 2017 (26228.4)

**Steps to Reproduce**:

1. Install StyleCop Analyzers in the Roslyn.sln solution (or use sharwell/roslyn@5234906a068604050c3eda56a2abe3da2de83e2f)
2. Find a file which is missing a header, and attempt to Fix All in Solution

**Expected Behavior**:

All violations are fixed.

**Actual Behavior**:

The actual behavior varies between the following:

1. Some, but not all, violations are fixed
2. The wait dialog disappears, but rather than show the preview window nothing occurs at all

With a debugger attached, I observed the following exception:

```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.Preview.PreviewEngine..ctor(String title,String helpString,String description,String topLevelItemName,Glyph topLevelGlyph,Solution newSolution,Solution oldSolution,IComponentModel componentModel,IVsImageService2 imageService,Boolean showCheckBoxes)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Preview.PreviewDialogService.PreviewChanges(String title,String helpString,String description,String topLevelName,Glyph topLevelGlyph,Solution newSolution,Solution oldSolution,Boolean showCheckBoxes)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.PreviewChanges(Solution currentSolution,Solution newSolution,String fixAllPreviewChangesTitle,String fixAllTopLevelHeader,String languageOpt,Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)<---
```

**Comment by sharwell** [comment]
:memo: I later observed the same exception message attempting to preview the changes from a single code fix (as opposed to a match fix).

**Comment by sharwell** [comment]
:memo: I've found it very difficult to reproduce this bug with the debugger attached. I am not certain that the `NullReferenceException` is always the cause. With that said, the following seems to cause the code fix to run without problems:

1. After switching to the branch referenced in my instructions, delete the **.vs** folder before opening the solution.
2. "Wait a long time." The exact amount of time is not clear - the issue still occurred after Test Explorer was finished discovering tests (~15 minutes), but when I tried again an hour later it worked.

To test the fixes for headers using the commit referenced above, you can use the following simpler set of tests:

1. Check out commit sharwell/roslyn@5234906
2. Run **Restore.cmd**
3. Delete the **.vs** folder
4. Open **Roslyn.sln**
5. Open a C# source file in the solution
6. Delete the copyright header at the top of the file
7. Wait an appropriate amount of time (to reproduce the issue you don't have to wait really, but to actually see it run correctly you need to "wait a long time")
8. Run Fix All in Solution for the warning reported at the top of the file

**Comment by CyrusNajmabadi** [comment]
Did you capture a dump as well?

**Comment by CyrusNajmabadi** [comment]
Sam, can you collect more information and add it to the bug?

**Comment by sharwell** [comment]
:memo: Most of these should be covered by #19714 and #19637.
