### ISSUE TITLE
Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#18230]
Changed branches in git and reloaded the solution.  Then this happened.
```
=====================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
3/27/2017 5:06:47 PM
Crippling
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__161.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**Comment by Pilchie** [comment]
Tagging @srivatsn  and @davkean but I believe this belongs either internally on CPS, or on `roslyn-project-system`.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn-project-system#1874
