### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.(CSharpErrorListDesktop|CSharpErrorListNetCore).ErrorLevelWarning failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18352]
Both versions of these tests failed in PR https://github.com/dotnet/roslyn/pull/18028 in the same way.

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1983/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpErrorListDesktop/ErrorLevelWarning/
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/1983/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpErrorListNetCore/ErrorLevelWarning/

```
Assert.Equal() Failure
Expected: ErrorListItem[] [
    Severity:Warning Description:The variable 'unused' is assigned but its value is never used Project:TestProj.csproj File:Class1.cs Line:6 Column:13
]
Actual: ErrorListItem[] [
   Severity:Warning Description:Can be made const Project:TestProj.csproj File:Class1.cs Line:6 Column:9,
   Severity:Warning Description:The variable 'unused' is assigned but its value is never used Project:TestProj.csproj File:Class1.cs Line:6 Column:13
]
```

(Reformatted for readability, the actual issue is the extra warning. Starting with @jmarolf.

**Comment by 333fred** [comment]
Failed in an official build: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration/672/. @jmarolf, do you have time to look at this? If not, @Pilchie, can you get someone else to take a look?

**Comment by 333fred** [comment]
And another: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev16/job/windows_debug_vs-integration/29/. Making this a higher priority

**Comment by 333fred** [comment]
A bunch more failures in the latest VSI tests. FYI @Pilchie. There seems to be more flakyness from this general set of tests, as Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorsDuringMethodBodyEditing failed on the latest debug build as well. 
```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList
      Assert.Equal() Failure
      Expected: ErrorListItem[] [Severity:Error Description:The type or namespace name 'P' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:Class1.cs Line:4 Column:12, Severity:Error Description:'Console' does not contain a definition for 'WriteLin' Project:TestProj.csproj File:Class1.cs Line:6 Column:24]
      Actual:   ErrorListItem[] [Severity:Error Description:The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:2 Column:7, Severity:Error Description:The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:3 Column:7, Severity:Error Description:The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:20, Severity:Error Description:Predefined type 'System.String' is not defined or imported Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:71, Severity:Error Description:The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:99, ...]
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpErrorListCommon.cs(53,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListCommon.ErrorList()
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpErrorListNetCore.cs(21,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList()
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorsDuringMethodBodyEditing
      Assert.Equal() Failure
      Expected: ErrorListItem[] []
      Actual:   ErrorListItem[] [Severity:Error Description:The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:2 Column:7, Severity:Error Description:The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:3 Column:7, Severity:Error Description:The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:20, Severity:Error Description:Predefined type 'System.String' is not defined or imported Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:71, Severity:Error Description:The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) Project:TestProj.csproj File:.NETCoreApp,Version=v1.1.AssemblyAttributes.cs Line:4 Column:99, ...]
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpErrorListCommon.cs(103,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListCommon.ErrorsDuringMethodBodyEditing()
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpErrorListNetCore.cs(35,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorsDuringMethodBodyEditing()
```
![image](https://cloud.githubusercontent.com/assets/2371880/24970287/9daa51be-1f68-11e7-812d-bfad23a0b99e.png)
![image](https://cloud.githubusercontent.com/assets/2371880/24970290/a1ffc564-1f68-11e7-877e-a28f1cb37f89.png)

**Comment by 333fred** [comment]
Also @jmarolf

**Comment by mavasani** [comment]
The additional diagnostic is coming from our sample analyzer MakeConstCS: https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Samples/CSharp/MakeConst/Impl/DiagnosticAnalyzer.cs#L23

We shouldn't be building samples when running integration tests. This seems like an infrastructure issue. @333fred @jasonmalinowski who should be looking into this?

**Comment by 333fred** [comment]
Buildmaster @jaredpar?

**Comment by jaredpar** [comment]
> We shouldn't be building samples when running integration tests. This seems like an infrastructure issue

Agree.  Believe we've decided that's the case previously as well.  We've just never had the time to make it happen.

**Comment by jmarolf** [comment]
My proposed resolution to this is to build the samples with /p:DeployExtensions=False on ci

**Comment by jmarolf** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/18122
