### ISSUE TITLE
BasicIntellisense.Type a Variable is Broken

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18397]
Broken in Dev16 vsi tests. Looks like https://github.com/dotnet/roslyn/commit/f4f341ec3987d8326657c6ebc1f252edf524e698 could be the cause, the integration tests started failing after the Open pointer was moved to include it.

**Comment by 333fred** [comment]
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0/722/

**Comment by mavasani** [comment]
I also got a failure: https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_prtest/617/

**Comment by 333fred** [comment]
I'm going to disable this test for, it's failed in every vsi build in master for the past few days.

**Comment by 333fred** [comment]
Jenkins Logs:

```
Test: BasicIntellisense started: 4/3/2017 10:11:17 PM
    Executing action [4/3/2017 10:11:17 PM] StartTarget
Begin Waiting for Apex Communication
    Executing action [4/3/2017 10:11:17 PM] AddProject
    Executing action [4/3/2017 10:11:28 PM] AddItem
    Executing action [4/3/2017 10:11:28 PM] OpenFile
DEBUG: executed DTE command File.OpenFile.
DEBUG: start polling for code window
DEBUG: polling complete
    Executing action [4/3/2017 10:11:28 PM] SetSuggestionMode
...
 Scenario: Type a variable declaration
    Executing action [4/3/2017 10:11:37 PM] SetEditorText
    Executing action [4/3/2017 10:11:37 PM] SetEditorText
    Executing action [4/3/2017 10:11:37 PM] PlaceCursor
    Executing action [4/3/2017 10:11:37 PM] SendKeys
    Executing action [4/3/2017 10:11:38 PM] SetSuggestionMode
    Executing action [4/3/2017 10:11:38 PM] WaitForWorkspace
    Executing action [4/3/2017 10:11:38 PM] SendKeys
    Executing action [4/3/2017 10:11:38 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:38 PM] SendKeys
    Executing action [4/3/2017 10:11:39 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:39 PM] SendKeys
    Executing action [4/3/2017 10:11:40 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:40 PM] SendKeys
    Executing action [4/3/2017 10:11:40 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:40 PM] SendKeys
    Executing action [4/3/2017 10:11:41 PM] SendKeys
    Executing action [4/3/2017 10:11:42 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:42 PM] SendKeys
    Executing action [4/3/2017 10:11:42 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:43 PM] SendKeys
    Executing action [4/3/2017 10:11:44 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:44 PM] SendKeys
    Executing action [4/3/2017 10:11:44 PM] VerifyCompletionList
    Executing action [4/3/2017 10:11:44 PM] SendKeys
    Executing action [4/3/2017 10:11:45 PM] VerifyCompletionList
--------------------------------
System.Exception: Completion list was showing and it wasn't expected to be showing
   at Roslyn.VSHosting.Test.VerifyCompletionListAction.<>c.<Execute>b__28_0(Object[] args) in D:\j\workspace\windows_vsi_p08ba736a3\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\VerifyCompletionListAction.cs:line 57
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)
================================


Saved screenshot: D:\j\workspace\windows_vsi_p08ba736a3\Open\Binaries\Release\Exes\EditorTestApp\Screenshots\2017-04-03_22-11-45_80 - Exception System.Reflection.TargetInvocationException.png

    Executing action [4/3/2017 10:11:45 PM] SendKeys
...
Test finished: 4/3/2017 10:12:26 PM
    Executing action [4/3/2017 10:12:26 PM] CloseTarget
Closing VS. force Close = True, closeVsToFreeHandles = False
      Cleared VS MEF Component Cache.
```
![image](https://cloud.githubusercontent.com/assets/2371880/24671263/bf31bce4-1925-11e7-8c08-53f3e2de1fee.png)
