### ISSUE TITLE
[Flaky Test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify failed in release build

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18428]
Possibly related to #18293, but since that issue doesn't describe this test specifically, opening a separate bug. Failed in https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/680/. Jenkins Logs:

```
 Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify
      System.Exception : Predicate never assigned a value after 10000 milliseconds and no exceptions were thrown. REPL text: > #reset
      Resetting execution engine.
      Loading context from 'CSharpInteractive.rsp'.
      > using System;
      > #reset
      Resetting execution engine.
      Loading context from 'CSharpInteractive.rsp'.
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.Http.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Windows.Forms.dll"
      > #r "TestProj.exe"
      > using TestProj;
      > x
      (1,1): error CS0103: The name 'x' does not exist in the current context
      > (new TestProj.C()).M()
      (1,15): error CS0234: The type or namespace name 'C' does not exist in the namespace 'TestProj' (are you missing an assembly reference?)
      > .
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 predicate)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutputContains(String outputText)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutputContains(String outputText)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\Extensions\InteractiveExtensions.Verifiers.cs(16,0): at Roslyn.VisualStudio.IntegrationTests.Extensions.Interactive.InteractiveExtensions.WaitForLastReplOut
```
![image](https://cloud.githubusercontent.com/assets/2371880/24670870/8ee39216-1924-11e7-8201-bbdc5c23c0f5.png)

Tagging @tmat @ivanbasov.

**Comment by tmat** [comment]
@ivanbasov is oof, let's disable the test until he has a chance to look into it.

**Comment by 333fred** [comment]
@ivanbasov, another failure.

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration/768/

```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify
      System.Exception : Predicate never assigned a value after 10000 milliseconds and no exceptions were thrown. REPL text: > #reset
      Resetting execution engine.
      Loading context from 'CSharpInteractive.rsp'.
      > using System;
      > #reset
      Resetting execution engine.
      Loading context from 'CSharpInteractive.rsp'.
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.Http.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll"
      > #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Windows.Forms.dll"
      > #r "TestProj.exe"
      > using TestProj;
      > x
      (1,1): error CS0103: The name 'x' does not exist in the current context
      > (new TestProj.C()).M()
      (1,15): error CS0234: The type or namespace name 'C' does not exist in the namespace 'TestProj' (are you missing an assembly reference?)
      > .
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 predicate)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutput(String outputText)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutput(String outputText)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.WaitForLastReplOutput(String outputText)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpSendToInteractive.cs(237,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify()
```

![image](https://cloud.githubusercontent.com/assets/2371880/25050988/44059540-20ff-11e7-8f40-96e14a9e9e38.png)

**Comment by ivanbasov** [comment]
Thank you, @333fred!
If you can see it failing for the next time, could you please make a screenshot with the whole Team Explorer?

**Comment by 333fred** [comment]
@ivanbasov I'm not taking the screenshots, the automated test system is.

**Comment by tmat** [comment]
@ivanbasov Can we log some information to help diagnosing the failure?
