### ISSUE TITLE
Microsoft.CodeAnalysis.UnitTests.LinkedFileDiffMerging.LinkedFileDiffMergingTests.TestChangeSignature failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18432]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4403/

**Comment by tmat** [comment]
```
  Microsoft.CodeAnalysis.UnitTests.LinkedFileDiffMerging.LinkedFileDiffMergingTests.TestChangeSignature
      Assert.Equal() Failure
                                            (pos 24)
      Expected: Â·Â·Â·ic class Class1\r\n{\r\n    void M(int z, int x)\r\n    {\r\n    }\r\n#Â·Â·Â·
      Actual:   Â·Â·Â·ic class Class1\r\n{\r\n\r\n/* Unmerged change from project 'ProjecÂ·Â·Â·
                                            (pos 24)
      Stack Trace:
        q:\roslyn\src\Workspaces\CoreTest\LinkedFileDiffMerging\LinkedFileDiffMergingTests.cs(48,0): at Microsoft.CodeAnalysis.UnitTests.LinkedFileDiffMerging.LinkedFileDiffMergingTests.TestLinkedFileSet(String startText, List`1 updatedTexts, String expectedMergedText, String languageName)
        q:\roslyn\src\Workspaces\CoreTest\LinkedFileDiffMerging\LinkedFileDiffMergingTests.Features.cs(15,0): at Microsoft.CodeAnalysis.UnitTests.LinkedFileDiffMerging.LinkedFileDiffMergingTests.TestChangeSignature()
```

**Comment by dpoeschl** [comment]
This uses `SyntaxDiffer.GetTextChanges(SyntaxTree, SyntaxTree)`, and I'm not sure whether the problem is in the linked file diff merging part, or the diffs themselves...
