### ISSUE TITLE
'GenerateConversionCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#18461]
Place the caret in the first '-1' literal in the following code:

```cs
    static void Main(string[] args)
    {
        byte b;
        var q = ((byte, byte))unchecked((b, _) = (-1, -1));
    }
```

VS will show an error message with the following stack trace

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundTupleLiteral' to type 'Microsoft.CodeAnalysis.CSharp.BoundConvertedTupleLiteral'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoForNode(BoundNode lowestBoundNode,BoundNode highestBoundNode,BoundNode boundNodeForSyntacticParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoCore(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.GenerateMember.GenerateParameterizedMember.CSharpGenerateConversionService.TryGetImplicitConversionMethodAndTypeToGenerateIn(SemanticDocument document,SyntaxNode expression,ISet`1 classInterfaceModuleStructTypes,CancellationToken cancellationToken,IMethodSymbol& methodSymbol,INamedTypeSymbol& typeToGenerateIn)
   at Microsoft.CodeAnalysis.CSharp.GenerateMember.GenerateParameterizedMember.CSharpGenerateConversionService.TryInitializeImplicitConversionState(SemanticDocument document,SyntaxNode expression,ISet`1 classInterfaceModuleStructTypes,CancellationToken cancellationToken,SyntaxToken& identifierToken,IMethodSymbol& methodSymbol,INamedTypeSymbol& typeToGenerateIn)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateConversionService`4.State.TryInitializeImplicitConversion(TService service,SemanticDocument document,SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateConversionService`4.State.TryInitializeConversionAsync(TService service,SemanticDocument document,SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateConversionService`4.State.GenerateConversionStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateConversionService`4.GenerateConversionAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jcouv** [comment]
This was fixed already (see https://github.com/dotnet/roslyn/commit/f3b584cd#diff-ba3ecd61f189797c20fa27971a6c8f0d)
Verified this no longer repros in VS 15.5.

Thanks for reporting the issue. I'll go ahead and close it. Feel free to re-open if you encounter it again.
