### ISSUE TITLE
Tests are Hanging

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18465]
There seems to be an intermittent problem with hanging vsi tests. As an example, see the logs saved in "\\mlangfs1\public\frsilb\logs\Jenkins Hang". These are from a debug and release build of https://github.com/dotnet/roslyn/pull/18454.

**Comment by 333fred** [comment]
FYI @dotnet/roslyn-infrastructure.

**Comment by 333fred** [comment]
Managed to get dumps of xunit and vs: "\\mlangfs1\public\frsilb\dumps\integration_test_hang"

**Comment by jmarolf** [comment]
This is caused by a failing refactoring. Full solution analysis is enabled so it could be any of the test files in use [here](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspaceBase.cs#L58).

`public class Class1 { }`
`public class Class2 { Class1 c; }`

```
"Object reference not set to an instance of an object."
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.GetParameterNode(SyntaxToken token, Int32 position)
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.<ComputeRefactoringsAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 441
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext()
```

**Comment by jmarolf** [comment]
@CyrusNajmabadi we are seeing it crash [here](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs#L125) with a null `Parent`

**Comment by 333fred** [comment]
Full dump at the null site: "\\mlangfs1\public\frsilb\dumps\integration_test_hang\devenv_integration_test_hang_at_null.dmp"
