### ISSUE TITLE
Multiple info bars in VB file

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#18499]
New VB console app with the following text:
```VB
Class C
    Sub Main()
        For a = 0 To 1 Step 1
            For b = 0 To 2
        Next b, a
    End Sub
End Class
```
Place the caret at position 0 (before class). 
Two error bars appear:

'VisualBasicInitializeMemberFromParameterCodeRefactoringPorivder":
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.GetParameterNode(SyntaxToken token,Int32 position)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.ComputeRefactoringsAsync[TParameterSyntax,TMemberDeclarationSyntax,TStatementSyntax,TExpressionSyntax,TBinaryExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

 'VisualBasicAddParameterCheckCodeRefactoringProvider':
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.GetParameterNode(SyntaxToken token,Int32 position)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.ComputeRefactoringsAsync[TParameterSyntax,TMemberDeclarationSyntax,TStatementSyntax,TExpressionSyntax,TBinaryExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by rchande** [comment]
I have VS set up to dogfood Roslyn and 2.3.0.6160605 is currently installed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/18487
