### ISSUE TITLE
CSharpInitializeMemberFromParameterCodeRefactoringProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#18517]
**Version Used**: Latest dogfooding bits as of this writing.

**Steps to Reproduce**:

1. Checkout this branch: https://github.com/dpoeschl/roslyn/tree/CSharpInitializeMemberFromParameterCodeRefactoringProviderFailure
2. Open "CSharpGoToImplementation.cs"

**Expected Behavior**: No infobar errors.

**Actual Behavior**: Infobar error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.GetParameterNode(SyntaxToken token,Int32 position)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`5.ComputeRefactoringsAsync[TParameterSyntax,TMemberDeclarationSyntax,TStatementSyntax,TExpressionSyntax,TBinaryExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by dpoeschl** [comment]
(Cyrus already fixed this)

**Comment by CyrusNajmabadi** [comment]
Reopening so i can close with gusto!

**Comment by CyrusNajmabadi** [comment]
Closing with prejudice.

**Comment by jmarolf** [comment]
@CyrusNajmabadi @dpoeschl WAT

**Comment by CyrusNajmabadi** [comment]
Ooops

**Comment by dpoeschl** [comment]
My bad.

**Comment by CyrusNajmabadi** [comment]
Assigning to me to look at this.

**Comment by Pilchie** [comment]
Seriously:

![sherlock-stop](https://cloud.githubusercontent.com/assets/312835/24872809/86ef78f0-1dd3-11e7-8b36-bd2c1e202116.gif)
