### ISSUE TITLE
Unit test failure in roslyn internal

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18532]
Roslyn.Services.Editor.CSharp.UnitTests, CSharpEditorServicesTest. Test exited with this exception:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: WaitCallback
   at System.Threading.ThreadPool.QueueUserWorkItemHelper(WaitCallback callBack, Object state, StackCrawlMark& stackMark, Boolean compressStack)
   at System.Threading.ThreadPool.QueueUserWorkItem(WaitCallback callBack, Object state)
   at MS.Internal.WindowsBase.GCNotificationToken.Finalize()
```

Creating an issue to track, we'll see if it repros in future runs.
https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/dev16/job/windows_release_unit64/39/

Full unit test log: [Roslyn.Services.Editor.CSharp.UnitTests.dll.4.out.log.txt](https://github.com/dotnet/roslyn/files/906483/Roslyn.Services.Editor.CSharp.UnitTests.dll.4.out.log.txt)

Full build log: [buildlog.txt](https://github.com/dotnet/roslyn/files/906488/buildlog.txt)

**Comment by 333fred** [comment]
Happened again in https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/view/Official%20Builds/job/dev16/job/windows_release_unit64/39/. @jaredpar @dotnet/roslyn-infrastructure, who should this be routed to?

**Comment by jasonmalinowski** [comment]
@jaredpar had some hack for one WPF bug, but that might not be sufficient. Did we get a crash dump for it or anywhere else? The full stack might be more useful than what it is giving in the log.

**Comment by 333fred** [comment]
There do not appear to be any dumps in the archived artifacts from that run.

**Comment by jaredpar** [comment]
This is pretty strange.  The NRE is coming on the call to QueueUserWorkItem as the delegate parameter is `null`.  The call site is very constrained here, here is the class in it`s entirety:

``` c#
class GCNotificationToken
    {
        WaitCallback callback;
        object state;
 
        GCNotificationToken(WaitCallback callback, object state)
        {
            this.callback = callback;
            this.state = state;
        }
 
        ~GCNotificationToken()
        {
            // Schedule cleanup
            ThreadPool.QueueUserWorkItem(callback, state);
        }
 
        internal static void RegisterCallback(WaitCallback callback, object state)
        {
            new GCNotificationToken(callback, state);
        }
    }
```

all calls to RegisterCallback are with static readonly fields that are always non-null.  Hence only scenario I can imagine where we call QueueUserWorkItem with a null work item is;

- Constructor is entered 
- Thread abort happens before `callback` is assigned
- A GC later and boom goes the world

Crazy to say the least and seems not plausible here.

**Comment by JoeRobich** [comment]
Closing as there have been no recent reports of this
