### ISSUE TITLE
Broken Tests: CSharp/VB DeleteControl

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18602]
Tests:
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.DeleteControl
Stack:
```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.DeleteControl
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass45_1.<DeleteWinFormButton>g__ComponentRemoved0(Object sender, ComponentEventArgs e)
           at System.ComponentModel.Design.ComponentEventHandler.Invoke(Object sender, ComponentEventArgs e)
           at System.ComponentModel.Design.DesignerHost.RemoveFromContainerPostProcess(IComponent component, IContainer container)
           at System.ComponentModel.Design.DesignerHost.Remove(IComponent component)
           at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.DestroyComponent(IComponent component)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass45_2.<DeleteWinFormButton>b__1()
           at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread(Action action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.DeleteWinFormButton(String buttonName)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.DeleteWinFormButton(String buttonName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.DeleteWinFormButton(String buttonName)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpWinForms.cs(160,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.DeleteControl()
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/2371880/24922376/eb01d58e-1ea2-11e7-9045-d87b018cf9a4.png)

Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.DeleteControl
Stack:
```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.DeleteControl
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass45_1.<DeleteWinFormButton>g__ComponentRemoved0(Object sender, ComponentEventArgs e)
           at System.ComponentModel.Design.ComponentEventHandler.Invoke(Object sender, ComponentEventArgs e)
           at System.ComponentModel.Design.DesignerHost.RemoveFromContainerPostProcess(IComponent component, IContainer container)
           at System.ComponentModel.Design.DesignerHost.Remove(IComponent component)
           at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.DestroyComponent(IComponent component)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass45_2.<DeleteWinFormButton>b__1()
           at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread(Action action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.DeleteWinFormButton(String buttonName)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.DeleteWinFormButton(String buttonName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.DeleteWinFormButton(String buttonName)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicWinForms.cs(188,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.DeleteControl()
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/2371880/24922385/f1c68e46-1ea2-11e7-8f52-41935308f253.png)

**Comment by 333fred** [comment]
@Pilchie, can you get this assigned please?
