### ISSUE TITLE
[Flaky Test] Microsoft.CodeAnalysis.VisualBasic.UnitTests.MyTemplateTests.MyWinformApp

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#18637]
Failed in https://github.com/dotnet/roslyn/pull/17906. 
```
MESSAGE:
System.IO.FileLoadException : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Not enough storage is available to process this command. (Exception from HRESULT: 0x80070008)
+++++++++++++++++++
STACK TRACE:
Server stack trace: at System.Reflection.RuntimeAssembly.GetEntryPoint(RuntimeAssembly assembly, ObjectHandleOnStack retMethod) at System.Reflection.RuntimeAssembly.get_EntryPoint() at Microsoft.CodeAnalysis.Test.Utilities.CodeRuntime.RuntimeAssemblyManager.Execute(String moduleName, Int32 expectedOutputLength, String& output) at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Microsoft.CodeAnalysis.Test.Utilities.CodeRuntime.RuntimeAssemblyManager.Execute(String moduleName, Int32 expectedOutputLength, String& output) at Microsoft.CodeAnalysis.Test.Utilities.CodeRuntime.DesktopRuntimeEnvironment.Execute(String moduleName, Int32 expectedOutputLength, String& processOutput) at Microsoft.CodeAnalysis.Test.Utilities.CodeRuntime.DesktopRuntimeEnvironment.Execute(String moduleName, String expectedOutput) at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, EmitOptions emitOptions, Boolean peVerify, SignatureDescription[] expectedSignatures) at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, EmitOptions emitOptions, Boolean verify) at Microsoft.CodeAnalysis.VisualBasic.UnitTests.MyTemplateTests.MyWinformApp() in q:\roslyn\src\Compilers\VisualBasic\Test\Semantic\Compilation\MyTemplateTests.vb:line 217
```
@dotnet/roslyn-compiler

**Comment by jaredpar** [comment]
> Not enough storage is available to process this command. 

Is this related to us not properly isolating the `%TEMP%` directory and hence running out of space?
  
https://github.com/dotnet/roslyn/pull/18603

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/features_ref-reassignment/job/windows_release_unit32_prtest/5/testReport/junit/Microsoft.CodeAnalysis.VisualBasic.UnitTests/MyTemplateTests/MyWinformApp/

```
Stacktrace
MESSAGE:
System.IO.FileLoadException : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Not enough storage is available to process this command. (Exception from HRESULT: 0x80070008)
+++++++++++++++++++
STACK TRACE:
Server stack trace:
at System.Reflection.RuntimeAssembly.GetEntryPoint(RuntimeAssembly assembly, ObjectHandleOnStack retMethod) at System.Reflection.RuntimeAssembly.get_EntryPoint()
at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute(String moduleName, String[] mainArgs, Nullable`1 expectedOutputLength, String& output)
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.Execute(String moduleName, String[] mainArgs, Nullable`1 expectedOutputLength, String& output) 
at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput) at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures) 
at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify) 
at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) 
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.BasicTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) 
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.MyTemplateTests.MyWinformApp()
```
