### ISSUE TITLE
VsixExpInstaller cannot install Roslyn.VisualStudio.Setup.Next because of "Razor Language Services"

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#18701]
**Version Used**:   [roslyntools.microsoft.vsixexpinstaller 0.2.4-beta](https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.Microsoft.VSIXExpInstaller/0.2.4-beta) and latest roslyn master

**Steps to Reproduce**:

1.  download nuget package
2.  run following command
```
<Path\To\nuget\cache>\roslyntools.microsoft.vsixexpinstaller\0.2.4-beta\tools\VsixExpInstaller.exe  /rootSuffix:RoslynDev /vsInstallDir:"Path\To\Visual Studio" Roslyn\Enlistment\Binaries\Debug\Vsix\VisualStudioSetup.Next\Roslyn.VisualStudio.Setup.Next.vsix
``` 

**Expected Behavior**:
installs successfully

**Actual Behavior**:

```
VsixExpInstaller.exe /rootSuffix:RoslynDev /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" C:\source\roslyn\Binaries\Debug\Vsix\VisualStudioSetup.Next\Roslyn.VisualStudio.Setup.Next.vsix
Updating C:\source\roslyn\Binaries\Debug\Vsix\VisualStudioSetup.Next\Roslyn.VisualStudio.Setup.Next.vsix...
BreaksExistingExtensionsException: This extension cannot be installed because the following extensions contain dependencies that would be broken as a result of this installation:
- Razor Language Services
Microsoft.VisualStudio.ExtensionManager.BreaksExistingExtensionsException: This extension cannot be installed because the following extensions contain dependencies that would be broken as a result of this installation:
- Razor Language Services
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Install(IInstallableExtension extension, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Install(IInstallableExtension extension, Boolean perMachine)
   at VsixExpInstaller.Program.<Main>g__RunProgram10_1(<>c__DisplayClass10_1& )
   at VsixExpInstaller.Program.Main(String[] args)
```

**Comment by jmarolf** [comment]
This is not a problem on RTM machines (where we run integration tests).  This only happens on Int Preview builds.  I would expect that this will block us from moving to newer builds of VS in future.

**Comment by Pilchie** [comment]
@rynowak @toddgrun can you help with this?  We probably need an open version number somewhere...

**Comment by rynowak** [comment]
Is this an issue because of our prerequisite for Roslyn? See https://github.com/aspnet/Razor/blob/dev/tooling/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest#L20

Should we remove the 16.0?

/cc @pranavkm

**Comment by pranavkm** [comment]
@Pilchie is there a version range you'd recommend here?

**Comment by rynowak** [comment]
I'm getting the sense that this should be `[15.0,)` but I'm not that knowledgable about VS setup things. @Pilchie Please advise as we're trying to get this checked in to our codebase today and get this into our insertion planned for Monday

**Comment by Pilchie** [comment]
@jmarolf @jasonmalinowski @brettfo do you understand what version this should be specified as?

**Comment by jasonmalinowski** [comment]
Yeah, that should probably be `[15.0,)`. No reason we'd break support in a higher version.

**Comment by jmarolf** [comment]
Talking to @brettfo its unclear why we are receiving this message.  I'll need to try this out using the default VsixInstaller to see if this is a bug in `VsixExpInstaller` or a bug in the SDK.

**Comment by rynowak** [comment]
We're spinning a build of our VSIX without the version cap to see if that will help.

You would run into binary compat issues with the editor, until our insertion on Monday, but we can at least see if this change will fix the setup issue.

**Comment by rynowak** [comment]
BTW you guys have this in one of your templates: https://github.com/dotnet/roslyn/blob/master/src/Setup/Templates/CSharp/Diagnostic/Analyzer/source.extension.vsixmanifest#L23

**Comment by jasonmalinowski** [comment]
@jmarolf Do we already have a bug tracking fixing that issue @rynowak pointed out? That's not good.

**Comment by tannergooding** [comment]
I'm not seeing the issue in the latest internal dogfood build (26424.2-Preview). @rynowak, would this build have your change?

**Comment by rynowak** [comment]
We didn't make a change to our VSIX. I know we had some changes in the component authoring at some point but I don't have a lot of context on that. Keep in mind we would only be in the box if you have web tools.

**Comment by CyrusNajmabadi** [comment]
I'm hitting this now and i'm unable to install the latest Roslyn LS: 

![image](https://cloud.githubusercontent.com/assets/4564579/25727253/1b386e42-30dd-11e7-96dd-08636b4bec2d.png)

I'm on

![image](https://cloud.githubusercontent.com/assets/4564579/25727269/2cd032ac-30dd-11e7-88ad-0a1dbe8a9372.png)

Is there a workaround?  This is preventing dogfooding of Roslyn bits.

**Comment by CyrusNajmabadi** [comment]
Note: i can't seem to uninstall Razor support from VS.  However, when i try, it then wants to remove:

![image](https://cloud.githubusercontent.com/assets/4564579/25727333/74bb5722-30dd-11e7-916d-8833cd26dc03.png)

But we need this to build Roslyn.  Can we decouple Razor here?

**Comment by CyrusNajmabadi** [comment]
False alarm on my part.  It looks like the issue here is Diasymreader, not razor

**Comment by CyrusNajmabadi** [comment]
Closing out as stale.
