### ISSUE TITLE
Compiler crash on bad code in the IDE

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18763]
**Version Used**: VS 2017 (also reproducible with VS 2015)

**Steps to Reproduce**:

1. Open a new Console Application
2. Paste the following code into the main class
``` c#
[X(() => this._Y)]
public void Z()
{
}
```
3. Move the mouse over `this`

**Expected Behavior**:

Some error message.

**Actual Behavior**:

Visual Studio crashes.

-----------------------------------

Possible stack trace:
``` none
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddUnwrappingErrorTypes(ArrayBuilder`1 builder, Symbol s)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, ISemanticFactsService semanticFacts, ISyntaxFactsService syntaxFacts, SyntaxToken token, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, SyntaxToken token, Workspace workspace, CancellationToken cancellationToken)
```

-----------------------------------
Also recorded internally at
- https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=406701
- https://vsfeedback/comment/844007

**Comment by brianhartung** [comment]
Hi. I'm a first time contributor. I fixed this issue locally and now just need to create a pull request but I thought I'd comment first so no one wastes their time looking further into it while I figure out how to do the PR, etc.

**Comment by brianhartung** [comment]
All tests pass if I run them locally but the first PR test fails with the "xunit produced no error output but had exit code 1" error that's been referenced on and off for the last couple of years.

Not sure what to do at this point...any chance someone can help take a look at this? Thanks in advance!
