### ISSUE TITLE
Crash when switching branches for a solution with lightweight solution load enabled

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/roslyn#18831]
**Version Used**: 
Dev15RTW

**Steps to Reproduce**:
See [DevDiv 400136](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/400136)

In VS with Lightweight Solution Load enabled,
1. In console, git checkout branch_A
2. Open a solution
3. In console, git checkout branch_B
4. Click the reload button

**Expected Behavior**:
VS does not crash

**Actual Behavior**:
Intermittently VS crashes

**Call Stack**
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
```
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.ContainsProject(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState.AddToPushListIfNeeded(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject, System.Collections.Generic.List`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>, System.Collections.Generic.HashSet`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState.AddToPushListIfNeeded(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject, System.Collections.Generic.List`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>, System.Collections.Generic.HashSet`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState.StartPushingToWorkspaceAndNotifyOfOpenDocuments(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.StartPushingToWorkspaceAndNotifyOfOpenDocuments(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.FinishLoad()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<PopulateWorkspaceFromDeferredProjectInfoAsync>d__60.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<LoadSolutionFromMSBuildAsync>d__58.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at ...
```

**Comment by Pilchie** [comment]
We don't actually have a dump or a repro here.  Emailed the internal customer to see if they can repro to get more info.

**Comment by Pilchie** [comment]
Will re-activate if I hear back.
