### ISSUE TITLE
VS Crash: NRE from Microsoft.CodeAnalysis.LanguageServices.AbstractSyntaxFactsService.AppendTokens

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#18843]
```
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSyntaxFactsService.AppendTokens(SyntaxNode node, StringBuilder builder) in E:\A\_work\11\s\src\Workspaces\Core\Portable\LanguageServices\SyntaxFactsService\AbstractSyntaxFactsService.cs:line 398
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.AppendParameters(SeparatedSyntaxList`1 parameters, StringBuilder builder) in E:\A\_work\11\s\src\Workspaces\CSharp\Portable\LanguageServices\CSharpSyntaxFactsService.cs:line 1011
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.GetMethodSuffix(MethodDeclarationSyntax method) in E:\A\_work\11\s\src\Workspaces\CSharp\Portable\LanguageServices\CSharpSyntaxFactsService.cs:line 941
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.TryGetDeclaredSymbolInfo(SyntaxNode node, DeclaredSymbolInfo& declaredSymbolInfo) in E:\A\_work\11\s\src\Workspaces\CSharp\Portable\LanguageServices\CSharpSyntaxFactsService.cs:line 870
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<CreateInfoAsync>d__45.MoveNext() in E:\A\_work\11\s\src\Workspaces\Core\Portable\FindSymbols\SyntaxTree\SyntaxTreeIndex_Create.cs:line 79
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<PrecalculateAsync>d__56.MoveNext() in E:\A\_work\11\s\src\Workspaces\Core\Portable\FindSymbols\SyntaxTree\SyntaxTreeIndex.cs:line 55
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass31_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext() in E:\A\_work\11\s\src\Features\Core\Portable\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 185
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2.MoveNext() in E:\A\_work\11\s\src\Features\Core\Portable\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 244
```

Crash dump: %internal_share%\public\tomat\Bugs\18843

**Comment by Pilchie** [comment]
@CyrusNajmabadi This is what you just checked in I believe?

**Comment by CyrusNajmabadi** [comment]
> This is what you just checked in I believe?

Yes.  @tmat do you have a dump or watson bucket?

**Comment by tmat** [comment]
> Crash dump: %internal_share%\public\tomat\Bugs\18843

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks!

**Comment by CyrusNajmabadi** [comment]
what is %internal_share%?
