### ISSUE TITLE
[Test Fail, VB] ConflictMarkerResolutionTests

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#19035]
Used the version in this pr #17651 (at 76a205b)
```
------ Run test started ------
[xUnit.net 00:00:00.7219700]   Starting:    Roslyn.Services.Editor.VisualBasic.UnitTests
[xUnit.net 00:00:04.5124854]   Finished:    Roslyn.Services.Editor.VisualBasic.UnitTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
========== Run test finished: 3 run (0:00:05.0754057) ==========
```

```
Test Name:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeBoth1
Test FullName:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeBoth1
Test Source:	L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb : line 89
Test Outcome:	Failed
Test Duration:	0:00:03.527

Result StackTrace:	
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestInRegularAndScript1Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.VB$StateMachine_4_TestTakeBoth1.MoveNext() in L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.InRange() Failure
Range:  (0 - -1)
Actual: 2
```

```
Test Name:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeBottom1
Test FullName:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeBottom1
Test Source:	L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb : line 53
Test Outcome:	Failed
Test Duration:	0:00:00.043

Result StackTrace:	
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestInRegularAndScript1Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.VB$StateMachine_3_TestTakeBottom1.MoveNext() in L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.InRange() Failure
Range:  (0 - -1)
Actual: 1


```

```
Test Name:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeTop1
Test FullName:	Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.TestTakeTop1
Test Source:	L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb : line 17
Test Outcome:	Failed
Test Duration:	0:00:00.034

Result StackTrace:	
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestInRegularAndScript1Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.ConflictMarkerResolution.ConflictMarkerResolutionTests.VB$StateMachine_2_TestTakeTop1.MoveNext() in L:\roslyn-AdamSpeight2008\src\EditorFeatures\VisualBasicTest\ConflictMarkerResolution\ConflictMarkerResolutionTests.vb:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.InRange() Failure
Range:  (0 - -1)
Actual: 0

```

**Comment by AdamSpeight2008** [comment]
Master:  All unit tests pass.

**Comment by Pilchie** [comment]
@AdamSpeight2008 Are you sure this isn't related to the VB Scanner changes in that PR?

**Comment by Pilchie** [comment]
We're not seeing this in our tests - please let us know if you can repro without your changes.

**Comment by AdamSpeight2008** [comment]
@Pilchie It was the change to parser.
