### ISSUE TITLE
EnC: NRE on edit around closuring Expression<T>

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#19039]
**Version Used**: VS2017 (26403.7)

**Steps to Reproduce**:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var strings = new List<string>().AsQueryable();
            var result = strings.Where(x => strings.Any());

            //Console.WriteLine();
        }
    }
}
```
1. Step to `var result = strings.Where(x => strings.Any());`
2. Uncomment `//Console.WriteLine();`
3. `F10`

**Expected Behavior**:
Edit gets applied and `Console.WriteLine();` becomes next instruction to be executed

**Actual Behavior**:
Temporary local variable of type "ConsoleApp1.Program.**<>c__DisplayClass0#1">**" was "null".
![image](https://cloud.githubusercontent.com/assets/7110884/25480678/10b9c698-2b4a-11e7-81b9-599c8cdbf8df.png)

**Comment by tmat** [comment]
@Suchiman Thanks for a great repro. Will take a look.

**Comment by tmat** [comment]
Assertion fails in debug builds. The problem is likely related to the expression tree.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.CSharp.LambdaFrame.MakeName(SyntaxNode scopeSyntaxOpt, DebugId methodId, DebugId closureId)

   at Microsoft.CodeAnalysis.CSharp.LambdaFrame..ctor(MethodSymbol topLevelMethod, MethodSymbol containingMethod, Boolean isStruct, SyntaxNode scopeSyntaxOpt, DebugId methodId, DebugId closureId)

   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.GetFrameForScope(Scope scope, ArrayBuilder`1 closureDebugInfo)

   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.<>c__DisplayClass37_0.<MakeFrames>b__0(Scope scope, Closure closure)

   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.Analysis.VisitClosures(Scope scope, Action`2 action)

   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.MakeFrames(ArrayBuilder`1 closureDebugInfo)

   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, HashSet`1 assignLocals)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg)

   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg)

   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)

   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, ICollection`1 updatedMethods, CompilationTestData testData, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, ICollection`1 updatedMethods, CompilationTestData testData, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, ICollection`1 updatedMethods, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.<EmitProjectDeltaAsync>d__34.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitProjectDeltaAsync(Project project, EmitBaseline baseline, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.LanguageServices.Implementation.EditAndContinue.VsENCRebuildableProjectImpl.EmitProjectDelta()

   at Roslyn.Utilities.TaskFactoryExtensions.<>c__DisplayClass3_0`1.<SafeStartNew>b__0()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by Suchiman** [comment]
Does no longer reproduce in 16.6p2
