### ISSUE TITLE
VS crash: 'TryGetDocumentOption' in type 'DocumentOptions doesn't have implementation

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#19158]
**Version Used**: 
RTW + install Roslyn.Deployment vsix from 20170501.1
**Steps to Reproduce**:
1.  Create a new C# .NET core app
2. Wait for crash

```
CLR: Managed code called FailFast, saying "System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Method 'TryGetDocumentOption' in type 'DocumentOptions' from assembly 'Microsoft.CodeAnalysis.EditorFeatures.Next, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.<GetOptionsForDocumentAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.GetOptionsForDocumentAsync(Document document, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.<GetUpdatedOptionSetForDocumentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<<GetOptionsAsync>b__36_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Highlighting.HighlighterViewTaggerProvider.<ProduceTagsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.<ProduceTagsAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__83.MoveNext()
---> (Inner Exception #0) System.TypeLoadException: Method 'TryGetDocumentOption' in type 'DocumentOptions' from assembly 'Microsoft.CodeAnalysis.EditorFeatures.Next, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.<GetOptionsForDocumentAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Options.EditorConfigDocumentOptionsProvider.GetOptionsForDocumentAsync(Document document, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.<GetUpdatedOptionSetForDocumentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<<GetOptionsAsync>b__36_0>d.MoveNext()<---
```

**Comment by mattscheffer** [comment]
@mavasani

**Comment by mavasani** [comment]
Tagging @jasonmalinowski @sharwell

**Comment by jasonmalinowski** [comment]
This is another instance of having mismatched bits. I'm guessing if @brettfo looks at his machine he'll see he has different VSIXes installed from different branches at once. @jaredpar is working on fixing this. (FYI to @Pilchie as well.)

**Comment by jaredpar** [comment]
What fix is it imagined that I'm working on here?

**Comment by jasonmalinowski** [comment]
@jaredpar Fixing the VSIX feed publishing.

**Comment by jaredpar** [comment]
How does fixing feed publishing address this problem?  Looks like a straight up crash.

**Comment by jasonmalinowski** [comment]
@jaredpar This happens when you have two VSIXes installed from two different branches simultaneously.

**Comment by jaredpar** [comment]
Okay ... so why doesn't one win over the other?

**Comment by jasonmalinowski** [comment]
@jaredpar Sorry, I wasn't clear: he's getting VisualStudioSetup.Next from one branch and VisualStudioSetup from a different branch. This means any implicit API break between the two causes this.

**Comment by CyrusNajmabadi** [comment]
Closing out as this appears to be a point in time publishing issue.
