### ISSUE TITLE
CSharpAddParameterCheckCodeRefactoringProvider crashes when a project doesn't have any valid references

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#19171]
1. File -> New -> Console App (.NET Core)
2. Right-click project, and choose Edit ConsoleApp1.csproj
3. Change `<TargetFramework>netcoreapp2.0</TargetFramework>` to `<TargetFramework>IDoNotExist</TargetFramework>`
4. Open Program.cs:
5. On 'args' of `string[] args', CTRL+.

Code action crashes with:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Extensions.ITypeSymbolExtensions.GenerateTypeSyntax(INamespaceOrTypeSymbol symbol,Boolean nameSyntax)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.TypeExpression(ITypeSymbol typeSymbol)
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractAddParameterCheckCodeRefactoringProvider`5.CreateArgumentNullException(Compilation compilation,SyntaxGenerator generator,IParameterSymbol parameter)
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractAddParameterCheckCodeRefactoringProvider`5.CreateNullCheckStatement(Compilation compilation,SyntaxGenerator generator,IParameterSymbol parameter)
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractAddParameterCheckCodeRefactoringProvider`5.<>c__DisplayClass6_0.<AddNullCheckAsync>b__0(Compilation c,SyntaxGenerator g)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractAddParameterCheckCodeRefactoringProvider`5.AddNullCheckStatementAsync[TParameterSyntax,TMemberDeclarationSyntax,TStatementSyntax,TExpressionSyntax,TBinaryExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractAddParameterCheckCodeRefactoringProvider`5.AddNullCheckAsync[TParameterSyntax,TMemberDeclarationSyntax,TStatementSyntax,TExpressionSyntax,TBinaryExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by davkean** [comment]
I suspect the same will occur if you run this before the project has finished restoring.
