### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty [FAIL]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#19191]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3606/consoleFull#6464135312d31e50d-1517-49fc-92b3-2ca637122019

```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty
      Assert.Contains() Failure
      Not found: this.SomeButton.Text = "NewButtonText"
      In value:  namespace TestProj
      {
          partial class Form1
          {
              /// <summary>
              /// Required designer variable.
              /// </summary>
              private System.ComponentModel.IContainer components = null;
      
              /// <summary>
              /// Clean up any resources being used.
              /// </summary>
              /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
              protected override void Dispose(bool disposing)
              {
                  if (disposing && (components != null))
                  {
                      components.Dispose();
                  }
                  base.Dispose(disposing);
              }
      
              #region Windows Form Designer generated code
      
              /// <summary>
              /// Required method for Designer support - do not modify
              /// the contents of this method with the code editor.
              /// </summary>
              private void InitializeComponent()
              {
                  this.components = new System.ComponentModel.Container();
                  this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
                  this.Text = "Form1";
              }
      
              #endregion
          }
      }
      
      
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpWinForms.cs(44,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty()
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.RemoveEventHandler
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode
      Assert.Contains() Failure
      Not found: this.SomeButton.Text = "ButtonTextGoesHere";
      In value:  namespace TestProj
      {
          partial class Form1
          {
              /// <summary>
              /// Required designer variable.
              /// </summary>
              private System.ComponentModel.IContainer components = null;
      
              /// <summary>
              /// Clean up any resources being used.
              /// </summary>
              /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
              protected override void Dispose(bool disposing)
              {
                  if (disposing && (components != null))
                  {
                      components.Dispose();
                  }
                  base.Dispose(disposing);
              }
      
              #region Windows Form Designer generated code
      
              /// <summary>
              /// Required method for Designer support - do not modify
              /// the contents of this method with the code editor.
              /// </summary>
              private void InitializeComponent()
              {
                  this.components = new System.ComponentModel.Container();
                  this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
                  this.Text = "Form1";
              }
      
              #endregion
          }
      }
      
      
      Stack Trace:
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpWinForms.cs(62,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode()
```

**Comment by Pilchie** [comment]
Same old failing to save through DTE on close issue?

**Comment by jasonmalinowski** [comment]
@Pilchie Doesn't (obviously) look like it yet. The validation code for that was copied over and I don't see evidence of that being thrown. Going to add some other logging.

**Comment by MattGertz** [comment]
Mondo escrow triage: test only, moving out.
