### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.TypingHelpDirectiveWorks [FAIL]

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#19209]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3610/

```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.BclConsoleCall
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.ForStatement
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.TypingHelpDirectiveWorks
      System.AggregateException : One or more errors occurred.
      ---- System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.
      
      ---- System.Runtime.Remoting.RemotingException : Failed to connect to an IPC Port: The system cannot find the file specified.
       
      Stack Trace:
        
        ----- Inner Stack Trace #1 (System.Runtime.Remoting.RemotingException) -----
        
        Server stack trace: 
           at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
           at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
           at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
           at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
           at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
           at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
           at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
           at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
           at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
           at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.WaitForApplicationIdle()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.WaitForApplicationIdle()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.Input.SendKeys.SendInputs(INPUT[] inputs)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.Input.SendKeys.Send(Object[] keys)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpInteractive.cs(104,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.TypingHelpDirectiveWorks()
        ----- Inner Stack Trace #2 (System.Runtime.Remoting.RemotingException) -----
        
        Server stack trace: 
           at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
           at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
           at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
           at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudioWorkspace_InProc.CleanUpWaitingService()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.VisualStudioWorkspace_OutOfProc.CleanUpWaitingService()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.CleanUp()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceContext.Dispose()
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs(29,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose()
        C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.WpfInteractionAsync
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.CutDeletePasteSelectAll
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.VerifyUndoAndRedo
```

**Comment by jasonmalinowski** [comment]
@dpoeschl @VSadov Did we get this test disabled?

**Comment by jasonmalinowski** [comment]
Test is disabled, moving to interactive to actually fix the test.

**Comment by tmat** [comment]
@ivanbasov Please take a look.

**Comment by ivanbasov** [comment]
Looking into logs, I think that the test mentioned failed due to a VS failure after the previous test. We have an issue for tracking this #18293. This means that with disabling this test, another test running next to the current one can become flaky.

I will take a look at this when considering #18293.

Tagging @jmarolf and @tannergooding who may have more ideas.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by CyrusNajmabadi** [comment]
Closing as this test is not skipped.
