### ISSUE TITLE
CSharpAddImportCodeFixProvider - Syntax node with not within Syntax Tree

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#19218]
**Version Used**: 15.0.0.26228.12

**Steps to Reproduce**:

1. New C# solution
2. Following code:
```CSharp

namespace ConsoleApp1
{
    using System.Linq;
    using System.Collections.Generic;

    public class Program 
    {
        static void Main(string[] args)
        {
            IVsStatusBar x;
        }
    }
}

```
3. Add reference to `Microsoft.VisualStudio.Shell.Interop`
4. Place cursor on `IVsStatusBar` and press `Ctr+.` to bring up quick fix
5. Observe crash when hovering over option to add `using`.

*Note:* The crash is not present when the `usings` are moved outside of the `namespace`

![image](http://i.imgur.com/GU49h4F.gif)

Stack:

```
System.AggregateException : One or more errors occurred. ---> Syntax node is not within syntax tree
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReference.SymbolReferenceCodeAction.ComputeOperationsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.ArgumentException : Syntax node is not within syntax tree
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(NamespaceDeclarationSyntax declarationSyntax,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportCodeFixProvider.ConflictsWithExistingMember(SemanticModel semanticModel,NamespaceDeclarationSyntax namespaceToAddTo,String rightOfAliasName)
   at Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportCodeFixProvider.RemoveGlobalAliasIfUnnecessary(SemanticModel semanticModel,NameSyntax nameSyntax,NamespaceDeclarationSyntax namespaceToAddTo)
   at Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportCodeFixProvider.GetUsingDirective(Document document,INamespaceOrTypeSymbol namespaceOrTypeSymbol,SemanticModel semanticModel,CompilationUnitSyntax root,SyntaxNode contextNode)
   at async Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportCodeFixProvider.AddImportWorkerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.AddImport.CSharpAddImportCodeFixProvider.AddImportAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1.SymbolReference.GetOperationAsync[TSimpleNameSyntax](<Unknown Parameters>)<---
```

**Comment by Pilchie** [comment]
@JoshVarty Are you able to repro this 100%?  @dpoeschl/ @CyrusNajmabadi - can one of you investigate?  This may be the other issue from the linked files race.

**Comment by JoshVarty** [comment]
I've reproed this 100% on two different projects, but only with `IVsStatusBar` for some reason.

**Comment by CyrusNajmabadi** [comment]
I'd love a repro i could take a look at!

**Comment by JoshVarty** [comment]
@CyrusNajmabadi Did my "Steps to repro" not work for you? If not, I can probably bring my laptop over to your office tomorrow or something.

**Comment by CyrusNajmabadi** [comment]
I'll try it out.  Where do i reference Microsoft.VisualStudio.Shell.Interop from?

**Comment by JoshVarty** [comment]
Strange, if I have a space at the top of the file it seems to work:

![image](https://cloud.githubusercontent.com/assets/1249087/25685412/0ec6f2da-301c-11e7-82ec-71198e60709d.png)

If I do no, it doesn't: 

![image](https://cloud.githubusercontent.com/assets/1249087/25685417/183b48ac-301c-11e7-992e-80d030f81ba2.png)

Also note that the option is different in each example. It's got different text and it's in a different order.

@CyrusNajmabadi I got it from the GAC but I'm guessing you could just use the one located at:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.dll`

**Comment by JoshVarty** [comment]
Oh sorry, that's a different fix... It's not adding the `using`

**Comment by CyrusNajmabadi** [comment]
Thanks Josh, that was very helpful.  I was able to track this down with that simple repro.
