### ISSUE TITLE
PdbReader crashes on simple assembly from .NET Standard 1.0 project with tuples

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#19352]
ILSpy crashes with this error:
```
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Note that if I delete the PDB file, ILSpy can load the assembly just fine.

Here are the binaries causing the problem (dll and pdb):
[repro.zip](https://github.com/dotnet/roslyn/files/984883/repro.zip)

You can also repro with those steps:
1. Create a new solution with a .NET Standard 1.0 console project
2. Add latest ValueTuple package from myget (https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ValueTuple/4.4.0-preview1-25305-02)
3. Put a simple method (`(int, int) M() { throw null; }`)
4. Build the project
5. Open the resulting assembly in ILSpy

FYI @tmat

**Comment by tmat** [comment]
A known bug in ILSpy. They need to update to the latest build of Cecil.

**Comment by jcouv** [comment]
Thanks

**Comment by jcouv** [comment]
Found the ILSpy issue: https://github.com/icsharpcode/ILSpy/issues/789
