### ISSUE TITLE
Integration test CSharpCodeActions.FastDoubleInvoke failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#19350]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3895/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log

```
 Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.FastDoubleInvoke
      System.InvalidOperationException : No expanded light bulb session found after View.ShowSmartTag.  Buffer content type=CSharp
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.GetLightBulbActions(ILightBulbBroker broker, IWpfTextView view)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass19_0.<GetLightBulbApplicationAction>b__0(IWpfTextView view)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass11_0.<GetExecuteOnActionViewCallback>b__0()
           at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke(Action callback)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread(Action action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ExecuteOnActiveView(Action`1 action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ApplyLightBulbAction(String actionName, Nullable`1 fixAllScope, Boolean blockUntilComplete)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ApplyLightBulbAction(String actionName, Nullable`1 fixAllScope, Boolean blockUntilComplete)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.ApplyLightBulbAction(String action, Nullable`1 fixAllScope, Boolean blockUntilComplete)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CodeActions(IEnumerable`1 expectedItems, String applyFix, Boolean verifyNotShowing, Boolean ensureExpectedItemsAreOrdered, Nullable`1 fixAllScope, Boolean blockUntilComplete)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CodeAction(String expectedItem, Boolean applyFix, Boolean verifyNotShowing, Boolean ensureExpectedItemsAreOrdered, Nullable`1 fixAllScope, Boolean blockUntilComplete)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpCodeActions.cs(80,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.FastDoubleInvoke()
```

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving out.

**Comment by dpoeschl** [comment]
Haven't seen this failure after a week and a half of monitoring, so closing for now. Will reactivate if it happens again.
