### ISSUE TITLE
Compiler crashes when a user defined struct is used as a well known attribute synthesized by the compiler

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn#19394]
Example test:

```csharp
            var code = @"
namespace System.Runtime.CompilerServices
{
    public struct DynamicAttribute
    {
        public DynamicAttribute(bool[] transformFlags)
        {
        }
}
}
class T
{
    void M(dynamic x) {}
}
";

            CreateCompilationWithMscorlib(code).VerifyEmitDiagnostics(/* there should be an error */);
```

However, the compiler crashes with the following:

```
	System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
	at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	at Microsoft.Cci.FullMetadataWriter.DefinitionIndex`1.get_Item(T item)
	at Microsoft.Cci.FullMetadataWriter.GetMethodDefinitionHandle(IMethodDefinition def)
	at Microsoft.Cci.MetadataWriter.GetCustomAttributeTypeCodedIndex(IMethodReference methodReference)
	at Microsoft.Cci.MetadataWriter.AddCustomAttributeToTable(EntityHandle parentHandle, ICustomAttribute customAttribute)
	at Microsoft.Cci.MetadataWriter.AddCustomAttributesToTable[T](IEnumerable`1 parentList, Func`2 getDefinitionHandle)
	at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows(ImmutableArray`1 sortedGenericParameters)
	at Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, BlobBuilder mappedFieldDataWriter, BlobBuilder resourceWriter, BlobBuilder dynamicAnalysisDataOpt, Blob& mvidFixup)
	at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
	at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean isDeterministic, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.GetEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, IEnumerable`1 manifestResources)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, DiagnosticDescription[] expected)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
	Attributes\AttributeTests_RefReadOnly.cs(1666,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_RefReadOnly.RefReadOnlyDefinitionsInsideUserDefinedIxxxsReadOnlyAttribute_Struct()
```

**Comment by OmarTawfik** [comment]
cc @AlekseyTs

**Comment by AlekseyTs** [comment]
Related to #19395.

**Comment by OmarTawfik** [comment]
This is basically because for structs, we synthesize parameter-less constructors and add them to the symbol table, however we don't emit them. So the lookup for the well known constructor succeeds, but we crash on emit because it is not written to metadata. From `SourceMemberContainerSymbol.cs`:

```csharp
            // NOTE: Per section 11.3.8 of the spec, "every struct implicitly has a parameterless instance constructor".
            // We won't insert a parameterless constructor for a struct if there already is one.
            // We don't expect anything to be emitted, but it should be in the symbol table.
            if ((!hasParameterlessInstanceConstructor && this.IsStructType()) || (!hasInstanceConstructor && !this.IsStatic))
            {
                members.Add((this.TypeKind == TypeKind.Submission) ?
                    new SynthesizedSubmissionConstructor(this, diagnostics) :
                    new SynthesizedInstanceConstructor(this));
            }
```

**Comment by tmat** [comment]
Just had a similarly looking crash: 

`%internal_share%\public\tomat\Bugs\Roslyn19394`

**Comment by OmarTawfik** [comment]
There are three cases we want to consider when trying to emit attributes:

* Optional attributes that we can skip
* Optional attributes that we can replace
* Required attributes that we cannot emit and we have to provide diagnostics instead of crashing.
