### ISSUE TITLE
Crash after changing content type.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#1940]
We need to better handle content types changing.  I was looking at this and saw at least one crash:

1. Create a C# project
2. Rename Program.cs to Program.vb
3. Close and open the file
4. Convert the syntax to be VB syntax (by hand)
5. Rename the file back to Program.cs
6. Start converting the syntax back to C#

Result:
Crash: 
```
"Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax'."
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.IDocumentExtensions.VB$StateMachine_5_GetVisualBasicSyntaxRootAsync.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.SignatureHelp.GenericNameSignatureHelpProvider.VB$StateMachine_13_GetItemsWorkerAsync.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.<GetItemsAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.<ComputeItemsAsync>d__10.MoveNext()
```

**Comment by Pilchie** [comment]
Minidump with heap at <internal-share>\dumps\1940\1940.dmp.
