### ISSUE TITLE
VS crash with NullReferenceException at IncrementalAnalyzer.<UpdateReferenceAsync> on Roslyn solution

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/roslyn#19462]
**Version Used**: 
VS: vsuvscore 26510.01
Roslyn: 2.03.0.61709

**Steps to Reproduce**:

1. Clone and init Roslyn, master branch
2. Open solution in VS, in LSL mode
3. Wait for a couple of seconds

**Expected Behavior**:
VS does not crash

**Actual Behavior**:
VS crashes with _NullReferenceException_

**Crash Dump**
in ```\\vspfs3\public\ilbiryuk\RoslynCrash```

**Stack trace:**
```
   at Microsoft.CodeAnalysis.IncrementalCaches.SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer.<UpdateReferenceAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.IncrementalCaches.SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer.<UpdateSymbolTreeInfoAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass31_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__33`2.MoveNext()
```

**Callstack where the exception is reported**
```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 152	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.GetOrDefaultAsync<Microsoft.CodeAnalysis.Document, object>(Microsoft.CodeAnalysis.Document value, System.Func<Microsoft.CodeAnalysis.Document, System.Threading.CancellationToken, System.Threading.Tasks.Task<object>> funcAsync, System.Threading.CancellationToken cancellationToken) Line 237	C#
 	[Resuming Async Method]	
 	[Native to Managed Transition]	
 	... 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.GetOrDefaultAsync<Microsoft.CodeAnalysis.Document, object>(Microsoft.CodeAnalysis.Document value, System.Func<Microsoft.CodeAnalysis.Document, System.Threading.CancellationToken, System.Threading.Tasks.Task<object>> funcAsync, System.Threading.CancellationToken cancellationToken) Line 244	C#
 	[Resuming Async Method]
        ...
 Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync.AnonymousMethod__0(Microsoft.CodeAnalysis.Document v, System.Threading.CancellationToken c) Line 186	C#
 	[Resuming Async Method]	
        ...
	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.IncrementalCaches.SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer.UpdateSymbolTreeInfoAsync(Microsoft.CodeAnalysis.Project project, System.Threading.CancellationToken cancellationToken) Line 206	C#
 	[Resuming Async Method]	
        ...
	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.IncrementalCaches.SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer.UpdateSourceSymbolTreeInfoAsync(Microsoft.CodeAnalysis.Project project, System.Threading.CancellationToken cancellationToken) Line 222	C#
 	[Resuming Async Method]	
        ...
	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo.LoadOrCreateAsync<Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo>(Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.Checksum checksum, string filePath, bool loadOnly, System.Func<System.Threading.Tasks.Task<Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo>> createAsync, string keySuffix, System.Func<Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo, Microsoft.CodeAnalysis.Checksum> getPersistedChecksum, System.Func<Roslyn.Utilities.ObjectReader, Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo> readObject, System.Threading.CancellationToken cancellationToken) Line 133	C#
 	[Resuming Async Method]	
        ...
	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolTreeInfo.CreateSourceSymbolTreeInfoAsync(Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Checksum checksum, System.Threading.CancellationToken cancellationToken) Line 95	C#
 	[Resuming Async Method]	
        ...
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.SolutionState solution, bool lockGate, System.Threading.CancellationToken cancellationToken) Line 415	C#
 	[Resuming Async Method]
        ...
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoFromScratchAsync(Microsoft.CodeAnalysis.SolutionState solution, Microsoft.CodeAnalysis.SolutionState.CompilationTracker.State state, System.Threading.CancellationToken cancellationToken) Line 479	C#
 	[Resuming Async Method]	
        ...
	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildDeclarationCompilationFromScratchAsync(Microsoft.CodeAnalysis.SolutionState solution, System.Threading.CancellationToken cancellationToken) Line 501	C#
 	[Resuming Async Method]	
        ...
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken) Line 655	C#
 	[Resuming Async Method]	
        ...
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken) Line 655	C#
 	[Resuming Async Method]	
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync<Microsoft.CodeAnalysis.Document>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.Document value, System.Func<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer, Microsoft.CodeAnalysis.Document, System.Threading.CancellationToken, System.Threading.Tasks.Task> runnerAsync, System.Threading.CancellationToken cancellationToken) Line 183	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.ProcessDocumentAnalyzersAsync(Microsoft.CodeAnalysis.Document document, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.WorkItem workItem, System.Threading.CancellationToken cancellationToken) Line 158	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.ProcessDocumentAsync(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer> analyzers, Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.WorkItem workItem, System.Threading.CancellationTokenSource source) Line 340	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.TryProcessOneHigherPriorityDocumentAsync() Line 282	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.ExecuteAsync() Line 142	C#
 	[Async Call]	
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor.ProcessAsync() Line 93	C#
```

**Comment by Pilchie** [comment]
> at Microsoft.CodeAnalysis.IncrementalCaches.SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer.<UpdateReferenceAsync>d__8.MoveNext()

@CyrusNajmabadi is this the issue you fixed yesterday?

**Comment by IlyaBiryukov** [comment]
If there is a workaround, private bits, or I can build and patch myself, please let me know. This issue is blocking verification of another bug fix I have for LSL. Thanks.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/19408.

You'll have to upgrade the version of Roslyn you use.
