### ISSUE TITLE
Exception when trying to get a property access modifier of an getter or setter with no access modifier where the accessor is a expression-bodied member

### ISSUE THREAD

**Issue by raboud** [dotnet/roslyn#19480]
**Version Used**: 
15.2(26430.6)
**Steps to Reproduce**:

1.  Input

```csharp
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ClaimsManager.Models.UI
{
    public class WindowsAccount
    {     
        [JsonProperty("Test")]
        public string UserName { get; set; }
        [Required]
        public string Domain { get; set; }

        public string WindowsUserID => $"{Domain}\\{UserName}"; 

        [JsonIgnore]
        public UserLoginInfo UserLogin => new UserLoginInfo("Windows", WindowsUserID);


    }
}
```

2. 
via EnvDTE

call 

```csharp
private static IEnumerable<IntellisenseProperty> GetProperties(CodeElements props, HashSet<string> traversedTypes, HashSet<string> references = null)
        {
            return from p in props.OfType<CodeProperty>()
                   where !p.Attributes.Cast<CodeAttribute>().Any(a => "System.Runtime.Serialization.IgnoreDataMemberAttribute" == a.FullName || "Newtonsoft.Json.JsonIgnoreAttribute" == a.FullName)
                   where vsCMAccess.vsCMAccessPublic == p.Access && p.Getter != null && !p.Getter.IsShared && IsPublic(p.Getter)
                   select new IntellisenseProperty
                   {
                       Name = GetName(p),
                       Type = GetType(p.Parent, p.Type, traversedTypes, references),
                       Summary = GetSummary(p),
                       JsonName = GetJsonName(p)
                   };
        }
```

for that class

**Expected Behavior**:
would expect to get vsCMAccessPublic

**Actual Behavior**:

```
ComExeption

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEFail()
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.GetDefaultAccessibility(SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.GetAccess(SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAccessorFunction.get_Access()
   at EnvDTE.CodeFunction.get_Access()
   at TypeScriptDefinitionGenerator.IntellisenseParser.IsPublic(CodeFunction cf) in C:\code\GitHub\TypeScriptDefinitionGenerator\src\Generator\IntellisenseParser.cs:line 190
```

**Comment by Pilchie** [comment]
@DustinCampbell / @CyrusNajmabadi we fixed `GetStartPoint()` for these right, but we don't support `Access`?

**Comment by raboud** [comment]
I have the fix and a unit test....just haven't done the check in and pull request.

**Comment by Pilchie** [comment]
Fantastic - I'll pull this into 15.3 then.  Looking forward to the contribution.

**Comment by raboud** [comment]
Pull request is in #19528...I hope I did it correctly

**Comment by MattGertz** [comment]
@Pilchie On track for 6/1? Makes ASK but not Escrow.

**Comment by Pilchie** [comment]
@MattGertz Yes, just waiting for a second review ( @jasonmalinowski ) and the ask mode template.
