### ISSUE TITLE
UriFormatException in GetHelpLink

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#19542]
**Version Used**: 26510.0

**Steps to Reproduce**:
Just put any non-BMP character anywhere inappropriately -  e.g.
```C#
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            𐌸|
        }
    }
}
```
(just the character on its own in a file does the trick too)

**Actual Behavior**:
A message box with editor extension exception:
```
System.UriFormatException: Invalid URI: There is an invalid sequence in the string.
 at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd) at System.Uri.EscapeDataString(String stringToEscape)
 at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.BrowserHelper.CreateBingQueryUri(String errorCode, String title, String language, String projectType)
 at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.BrowserHelper.CreateBingQueryUri(DiagnosticData diagnostic)
 at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.GetHelpLink(DiagnosticData item)
 at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSnapshot.TryGetValue(Int32 index, String columnName, Object& content)
 at Microsoft.VisualStudio.Shell.TableControl.Implementation.SnapshotTableEntryViewModel.TryGetValue(String columnName, Object& content)
```

**Expected Behavior**:
No message boxes, i.e. ~~either~~ encode URL first ~~or tolerate UriFormatExceptions~~ (there are likely more ways to get it besides non-BMP chars).

**Comment by SomeAnon42** [comment]
What's interesting is that I can only reproduce this using the preview builds (15.3, both preview 2.0 and preview 2.1). Not seeing any errors in 15.2.
![poop](https://user-images.githubusercontent.com/6377116/27427617-47da43c6-5748-11e7-960a-4762113f48f0.PNG)

**Comment by ivanbasov** [comment]
Cannot reproduce this with 15.8 preview 4.
