### ISSUE TITLE
NullReferenceException in WorkspaceMetadataFileReferenceResolver.Equals(WorkspaceMetadataFileReferenceResolver)

### ISSUE THREAD

**Issue by PawelAndruszkiewicz** [dotnet/roslyn#19553]
**Version Used**: 
 Microsoft.CodeAnalysis.Workspaces 2.1.0.61520

**Steps to Reproduce**:
```
using System;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;

namespace WorkspaceMetadataFileReferenceResolverIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var workspace = MSBuildWorkspace.Create();
            var project = workspace.OpenProjectAsync(args[0]).Result;
            var compilation = project.GetCompilationAsync().Result;
            var options = compilation.Options.WithMetadataReferenceResolver(new ReferenceResolver());
            compilation = compilation.WithOptions(options);
        }
    }

    class ReferenceResolver : MetadataReferenceResolver
    {
        public override bool Equals(object other)
        {
            throw new NotImplementedException();
        }

        public override int GetHashCode()
        {
            throw new NotImplementedException();
        }

        public override ImmutableArray<PortableExecutableReference> ResolveReference(string reference, string baseFilePath, MetadataReferenceProperties properties)
        {
            throw new NotImplementedException();
        }
    }
}
```

Run the sample application passing a full path to csproj.

**Expected Behavior**:
Sample application should not throw an exception.

**Actual Behavior**:
Sample application throws an exception in line `compilation = compilation.WithOptions(options);`:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.Equals(WorkspaceMetadataFileReferenceResolver other)
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.Equals(Object other)
   at System.Object.Equals(Object objA, Object objB)
   at Microsoft.CodeAnalysis.CompilationOptions.CanReuseCompilationReferenceManager(CompilationOptions other)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithOptions(CSharpCompilationOptions options)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithOptions(CompilationOptions options)
   at Microsoft.CodeAnalysis.Compilation.WithOptions(CompilationOptions options)
   at WorkspaceMetadataFileReferenceResolverIssue.Program.Main(String[] args) in D:\Works
paceMetadataFileReferenceResolverIssue\Program.cs:line 16
```

**Comment by Pilchie** [comment]
@PawelAndruszkiewicz care to supply a PR?  It's likely a simple oversight in the implementation of `WorkspaceMetadataFileReferenceResolver.Equals`

**Comment by fsacer** [comment]
Added the null check.

**Comment by PawelAndruszkiewicz** [comment]
@Pilchie PR would require an approval from my employer and it would take some time.

@fsacer Thanks :)

**Comment by Pilchie** [comment]
@PawelAndruszkiewicz Understood (but maybe start talking to your employer so you are all set next time 😉).  

@fsacer Indeed, thanks - I'll review that now.
