### ISSUE TITLE
Flaky Test: Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigationBar.VerifyNavBar2

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#19558]
Seems like this could be a test framework issue, occurred on one of my prs where it didn't fail previously, and the newly pushed commits reordered an if statement in a section of code that wasn't run by this test. 

I say framework issue because this test checking to see if `C` and `S` are in the nav bar, and they appear to be in the nav bar from the screenshot.

**Screen Shot**:
![image](https://cloud.githubusercontent.com/assets/2371880/26122086/26791020-3a2b-11e7-8996-f5b46e2f7c72.png)

**Stack Trace**:
```
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
Server stack trace: at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.GetPropertyValue(Object instance, String propertyName) at 
Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.GetPropertyValue[PropertyType](Object instance, String propertyName) at 
Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetNavbar(IWpfTextView textView) at 
Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetNavigationBarComboBoxes(IWpfTextView textView) at
 Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass2_0.<GetNavbarItemIndex>b__1(IWpfTextView v) at 
Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass9_0`1.<ExecuteOnActiveView>b__0() at 
System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore() at 
System.Windows.Threading.DispatcherOperation.InvokeImpl()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread[T](Func`1 action)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ExecuteOnActiveView[T](Func`2 action)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetNavbarItemIndex(Int32 index, String itemText)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.SelectNavBarItem(Int32 comboboxIndex, String selection)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) 
Exception rethrown at [0]: 
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.SelectNavBarItem(Int32 comboboxIndex, String selection)
 at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.SelectTypeNavBarItem(String item)
 at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigationBar.VerifyNavBar2() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\CSharp\CSharpNavigationBar.cs:line 71
```

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only, moving out to get it off the radar.

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/2093/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpNavigationBar/TestSplitWindow/

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits in 6 years and integration test rewrites.
