### ISSUE TITLE
OOM with memory mapped files

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#19604]
```
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass13_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.<SaveAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass13_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.<SaveAsync>d__7.MoveNext()<---
```

**Comment by CyrusNajmabadi** [comment]
I have a dump, but the site outages are making it hard to upload.

**Comment by sharwell** [comment]
:arrow_right: `MemoryMappedInfo.CreateWritableStream` needs to be updated to handle this `IOException` in the same way `CreateReadableStream` handles it.
