### ISSUE TITLE
Intermittent crash in VS

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#1980]
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.Runtime.InteropServices.COMException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))</Message><StackTrace>   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateUnknownCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, CodeElement&amp;amp; element, Object&amp;amp; parentElement)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.FireEvents()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.&amp;lt;&amp;gt;c__DisplayClass6_0.&amp;lt;FireEvents&amp;gt;b__0()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.&amp;lt;&amp;gt;c__DisplayClass1_0.&amp;lt;SafeStartNew&amp;gt;b__0()</StackTrace><ExceptionString>System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateUnknownCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, CodeElement&amp;amp; element, Object&amp;amp; parentElement)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.FireEvents()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.&amp;lt;&amp;gt;c__DisplayClass6_0.&amp;lt;FireEvents&amp;gt;b__0()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.&amp;lt;&amp;gt;c__DisplayClass1_0.&amp;lt;SafeStartNew&amp;gt;b__0()</ExceptionString></Exception></TraceRecord>

**Comment by Pilchie** [comment]
@basoundr  can you take a look at this ASAP?

**Comment by Pilchie** [comment]
Moving to 1.0 (stable), since we don't think enough people will hit this to keep in preview.
