### ISSUE TITLE
NonFatalWatson: Updating installed packages for a project

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#19879]
In the week of 5/18 - 5/25 on 15.3 based branches, there were ~145 hits with this stack:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at Roslyn.Utilities.ICollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 values)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Pilchie** [comment]
Putting in 15.3, since you have a PR out for this already.
