### ISSUE TITLE
CI test failure: Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests+Shared.TestSorting

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#19963]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/7050/

```
   Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests+Shared.TestSorting
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(944,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.TestContext.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(608,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.<TestGenerateFromSourceSymbolAsync>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.Shared.cs(341,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.Shared.<TestSorting>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
This is unfortunately unactionable.  TestWorkspace.Dispose is huge and complex.  If we hit this again, please download the artifacts for that failed run.
