### ISSUE TITLE
GetRenamableDefinitionLocationsAsync throws NullReferenceException

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#20040]
**Version Used**: 1.2.0 and 2.2.0 both repro the issue.

**Steps to Reproduce**:

```
git clone https://github.com/microsoft/vs-threading.git
cd vs-threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests
git checkout bugrepro/dotnet/roslyn/20040
msbuild /t:restore
msbuild
xunit.console ..\..\bin\Microsoft.VisualStudio.Threading.Analyzers.Tests\Debug\net46\Microsoft.VisualStudio.Threading.Analyzers.Tests.dll -html report.html -parallel all -method Microsoft.VisualStudio.Threading.Analyzers.Tests.VSTHRD103UseAsyncOptionAnalyzerTests.GenericMethodName
```

**Expected Behavior**:

Preferably a passing test, although I've been changing my library so I'm not sure if I have a bug of my own.

**Actual Behavior**:

A `NullReferenceException` thrown from within Roslyn:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Rename.RenameLocations.ReferenceProcessing.<GetRenamableDefinitionLocationsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Rename.RenameLocations.<AddLocationsReferenceSymbolsAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Rename.RenameLocations.<FindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Rename.Renamer.<RenameSymbolAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<MakeMethodAsync>d__16.MoveNext() in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers\Utils.cs:line 423
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD103UseAsyncOptionCodeFix.ReplaceSyncMethodCallWithAwaitAsync.<GetChangedSolutionAsync>d__9.MoveNext() in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers\VSTHRD103UseAsyncOptionCodeFix.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputeOperationsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputeOperationsAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetOperationsCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetOperationsAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.Analyzers.Tests.CodeFixVerifier.ApplyFix(Document document, CodeAction codeAction) in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\Helpers\CodeFixVerifier.Helper.cs:line 28
   at Microsoft.VisualStudio.Threading.Analyzers.Tests.CodeFixVerifier.VerifyFix(String language, DiagnosticAnalyzer analyzer, CodeFixProvider codeFixProvider, String oldSource, String newSource, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics) in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\Helpers\CodeFixVerifier.cs:line 106
   at Microsoft.VisualStudio.Threading.Analyzers.Tests.CodeFixVerifier.VerifyCSharpFix(String oldSource, String newSource, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics) in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\Helpers\CodeFixVerifier.cs:line 55
   at Microsoft.VisualStudio.Threading.Analyzers.Tests.VSTHRD103UseAsyncOptionAnalyzerTests.GenericMethodName() in C:\git\threading\src\Microsoft.VisualStudio.Threading.Analyzers.Tests\VSTHRD103UseAsyncOptionAnalyzerTests.cs:line 923
```

**Comment by Pilchie** [comment]
Could this be the same thing as https://github.com/dotnet/roslyn/issues/7364?

**Comment by Pilchie** [comment]
Leaving in 15.3 in case this is a dupe and helps us understand #7364.

**Comment by AArnott** [comment]
When I load symbols and source for the thrown NRE, I see that it fails on [this line](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs#L304-L307).

**Comment by AArnott** [comment]
I also can see that this expression specifically is what returns null and then is unconditionally dereferenced: `solution.GetDocument(location.SourceTree)`

**Comment by Pilchie** [comment]
Can you get the Text of the source tree and see if it is one of your files.

**Comment by AArnott** [comment]
Yes, I'm looking into that now. In the `location.SourceTree` I see a full syntax tree (the full document) from my test. But the Solution.Projects.Documents collection has the same file represented but *only contains the method syntax*: It's just a method body rather than a full compilation unit. And the `MethodDeclarationSyntax.Parent == null`. So since the `SyntaxTree` is different between these two references, we get null back.

So how did we get here? 
I had been manipulating the SyntaxTree, and this method specifically. I stepped through it and found that my `MethodDeclarationSyntax` loses its Parent information as a result of this call:

```csharp
method = method.WithBody(updatedBody);
```

That is, before this call, `method.Parent != null` and after this call, `method.Parent == null` and `method.SyntaxTree` only returns the method rather than the whole compilation unit. This particular behavior may be by design, I don't know. Perhaps I need to call `SyntaxTree.ReplaceNode(methodBefore, methodAfter)` in order to get back to a rooted tree. But the very odd thing is that this code does *not* lose its parent:

```csharp
method = method.WithReturnType(returnType);
```

So it seems that `MethodDeclarationSyntax.WithBody` in particular is what loses parent information. 

Anyway, after this, I update the Document with the latest `method.SyntaxTree`, which returns just the method syntax instead of the whole document. And somehow this leads to the inconsistent state within Roslyn and the NRE.

**Comment by Pilchie** [comment]
You need to call replace node. If `WithReturnType` doesn't lose its parent, that is a bug.

**Comment by AArnott** [comment]
Should a `Document` allow setting a `MethodDeclarationSyntax` as its root node? Or can we say there's a bug there, given it leads to Roslyn throwing NRE later?

**Comment by Pilchie** [comment]
SyntaxTree supporting arbitrary nodes is deliberate. 

Document could maybe protect, but in general, Document doesn't eagerly realize the tree, so I'm not sure we could accurately detect this.

**Comment by AArnott** [comment]
In my case, I have this line:
```
            document = document.WithSyntaxRoot(root);
```

Given that tree is realized at least at the root, it could detect it at that point, couldn't it?

**Comment by AArnott** [comment]
When I have a bunch of syntax changes to make, I'm finding it *very* tedious to re-parent it. Is it really this bad, or am I doing it wrong?

```csharp
            // bookmark the original syntax node so we can find it after mutation in the newly rooted tree
            var bookmark = new SyntaxAnnotation();
            var root = await syntaxNode.SyntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);
            root = root.ReplaceNode(syntaxNode, syntaxNode.WithAdditionalAnnotations(bookmark));
            document = document.WithSyntaxRoot(root);
            root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
            syntaxNode = (T)root.GetAnnotatedNodes(bookmark).Single();

            // now mutate syntax Node
            var newSyntaxNode = syntaxNode.WithSomething(else);

            // Now re-parent and re-acquire the method syntax
            root = root.ReplaceNode(syntaxNode, newSyntaxNode);
            document = document.WithSyntaxRoot(root);
            root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
            newSyntaxNode = root.GetAnnotatedNodes(bookmark).Single();
```

**Comment by AArnott** [comment]
Now that I've fixed my re-parenting, I see full syntax trees in both places, but the NRE is still firing. I'll see if I can figure out what I may still be doing wrong...

**Comment by AArnott** [comment]
I was still passing in an old `IMethodSymbol` to the `RenameSymbolAsync` method. So mixing of versions also results in NRE being thrown.

**Comment by AArnott** [comment]
OK, so after I fixed all my local variable version consistency issues, my scenario works without NRE being thrown.
So I think what we have here is that if a very easy to make bug (for me, at least) exists in syntax tree manipulation code, then Roslyn has a high likelihood of throwing NRE which if closely studied can lead the guilty party to realize their mistake. I'd prefer an exception when the mistake is made, or an exception later that says what I likely did wrong.

Given #7364 alleges that somehow the document *was* in an invalid state at some point in the past when the null is hit, it seems quite possible that some refactoring of the document had put it into an internally inconsistent state such that a later refactoring fails in this way. 

I'm unblocked. I'll accept whatever you want to do with this bug. :)

**Comment by Pilchie** [comment]
I filed https://github.com/dotnet/roslyn/issues/20082 to track updating the argument syntax.  I think we'll close this issue though.
