### ISSUE TITLE
Symbols missing when running unittests

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20189]
When a unittest fails, only the test code itself gets proper location information (such that you can click on that line and jump to the location in the code). I suspect there is a problem with copying PDBs in our build.
FYI @jaredpar 

```
	at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition)
	at Microsoft.CodeAnalysis.CSharp.ErrorFacts.GetMessage(MessageID code, CultureInfo culture)
	at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLangVersions(TextWriter consoleOutput)
	at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
	CommandLineTests.cs(1419,0): at Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.LangVersion_ListLangVersions()
```

I took a quick look at this. There is possibly a data size motivation, as copying PDBs along with all the assemblies copied to the test folders would increase the disk space used.

**Comment by jasonmalinowski** [comment]
@jaredpar any idea if we intentionally tweaked this somewhere? I'm not aware of so, and obvious greps didn't come up with anything.

And also since we're building deterministic, the DLL doesn't have an embedded PDB path, correct? That is what probably saves us in normal cases here.

**Comment by jaredpar** [comment]
@jasonmalinowski 

>  I'm not aware of so, and obvious greps didn't come up with anything.

We moved to the new SDK. Have to fight MSBuild even harder to get PDBs copied correctly now.

**Comment by jcouv** [comment]
That's no longer a problem, since we use embedded symbols for local builds.
Closing
