### ISSUE TITLE
OOP: Operation cancelled crash in document highlights

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#20195]
**Version Used**: 
d15rel.26606.0 with Roslyn 2.3.0.6181304.

Dump file at `"\\mlangfs1\public\kevinpi\HighlightReferencesDogfooding.dmp"`.

Callstack:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: StreamJsonRpc.RemoteInvocationException: The task was cancelled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__65`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcClient.<InvokeAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsInRemoteProcessAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.<<TryNewServiceAsync>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.<TryServiceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.<ProduceTagsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__83.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Investigating.  However @heejaechang I may need some help here.  Looking at this feature, we don't do anything special with cancellation tokens.  The IDE side uses a normal cancellation token and passes it to the OOP system.  And all we do on the OOP side is access "this.CancellationToken".   So if we're getting some strange cancellation exception, it seems like it might be some sort of race/issue in the OOP subsystem.

**Comment by heejaechang** [comment]
let me take a look. I want to move to native support of cancellation in StreamJson as well that got added in newer version. I just have one PR required to be in before I start on that change.

**Comment by CyrusNajmabadi** [comment]
The issue seems to be with this code:

```c#
        public async Task<T> InvokeAsync<T>(string targetName, params object[] arguments)
        {
            _cancellationToken.ThrowIfCancellationRequested();

            try
            {
                return await _rpc.InvokeAsync<T>(targetName, arguments).ConfigureAwait(false);
            }
            catch
            {
                // any exception can be thrown from StreamJsonRpc if JsonRpc is disposed in the middle of read/write.
                // until we move to newly added cancellation support in JsonRpc, we will catch exception and translate to
                // cancellation exception here. if any exception is thrown unrelated to cancellation, then we will rethrow
                // the exception
                _cancellationToken.ThrowIfCancellationRequested();
                throw;
            }
        }
```

_rpc.InvokeAsync seems to eb throwing RemoteInvocationException that is *wrapping* an OperationCanceledException.  However, our local _cancellationToken has not been canceled.  Are we doing any sort of client caching?  Is that causing us to make a call with one cancellation token (which gets canceled), but we're holding onto another cancellation token (which hasn't been canceled)?

**Comment by CyrusNajmabadi** [comment]
Found it.  The bug is in:

RemoteHostClientService

Specifically, "lazyInstance" captures the cancellation token of the thread that created it.  But it can be used across many different threads (with different cancellation tokens).  So the thread that originally asked for the client has not canceled, but the "document highlights" thread chooses to cancel.  THis cancels on the remote side, but when we see that back on the host side we don't think we're actually canceled because we're looking at the wrong cancellation token.

**Comment by CyrusNajmabadi** [comment]
Assigning to Heejae.

**Comment by heejaechang** [comment]
@CyrusNajmabadi can you link the source? I dont see such thing. http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,145

are we talking about VS or unit test?

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn/issues/20195#issuecomment-308262350 

OOP side can't cancel itself unless VS side cancelled operation. OOP side raise cancellation only if VS side raised cancellation since current model of cancellation is closing connection from VS side.

**Comment by heejaechang** [comment]
can the HR throw its own cancellation which is not the given one? .. @Pilchie is this reproducible?

**Comment by Pilchie** [comment]
> @Pilchie is this reproducible?

No - I don't have a repro 😦

**Comment by CyrusNajmabadi** [comment]
@heejaechang When would we have a RemoteInvocationException that holds onto a OperationCanceledException internally?

**Comment by heejaechang** [comment]
@CyrusNajmabadi service hub has no idea on cancellation. what it says is in OOP side, someone threw exception with message "task was cancelled". most likely Operation cancellation exception.

**Comment by heejaechang** [comment]
@CyrusNajmabadi ya, I already looked through it. couldn't figure out. OOP dump probably required to figure it out since it will tell us which cancellation token is actually thrown. right now, that info is missing. for this.CancellationToken to be thrown, connection must be gone (http://source.roslyn.io/#Microsoft.CodeAnalysis.Remote.ServiceHub/Shared/ServiceHubServiceBase.cs,157) but we only close the connection if session is disposed.

and we only dispose the session if 1. session is finished or 2. cancellation is thrown. 

(1) can only happen if HR on OOP side return in which case cancellation can't be thrown (2) can't happen unless VS side cancellation is raised.

**Comment by Pilchie** [comment]
@heejaechang - how can I get a dump of the OOP side when this happens?

**Comment by heejaechang** [comment]
@Pilchie I think I need to do something on OOP side that if cancellation is thrown and it is not same one as this.Cancellation, I should FailFast the process.
