### ISSUE TITLE
Integration test failures due to `AnnotationTagger`

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#20219]
Dump at `https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/1160/artifact/Binaries/Debug/`

This appears to affect REPL and possibly other projection scenarios.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Editor.Implementation.AnnotationTagger.<GetTags>d__10.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()
```

**Comment by Pilchie** [comment]
@rchande artifacts are likely to get cleaned within about 24hours.  Maybe download the zip and store somewhere?

**Comment by rchande** [comment]
Artifacts zip at \\mlangfs1\public\rchande\20219

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only issue; moving out to get this off the radar.

**Comment by jinujoseph** [comment]
Closed via [Link](https://github.com/dotnet/roslyn/pull/25151)

**Comment by sharwell** [comment]
Reopening since I missed some tests
