### ISSUE TITLE
PR#19999 Assert Failure

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#20300]
I am currently working on PR #19999 (which is in a runnable state but unstable).
So I am running a debug to try out things, when I get an assert failure.
```vbnet
Imports System.Runtime.CompilerServices
Module Module1

    Sub Main()
        Example()

    End Sub
    Sub Example(
               <CallerMemberName> Optional M0 As String,
               <CallerFilePath> Optional F0 As String,
               <CallerLineNumber> Optional L0 As Integer = 0,
               <CallerMemberName> Optional M1 As String,
               <CallerFilePath> Optional F1 As String,
               <CallerLineNumber> Optional L1 As Integer)
        Debug.Assert(M0 = M1)
        Debug.Assert(F0 = F1)
        Debug.Assert(L0 = L1)
    End Sub
End Module
```
After the first or second `As String` type a space then equal sign ` =`. 
An assert is thrown 
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected difference at offset 239: Line 10, Column 55 "               <CallerFilePath> Optional F0 As String =,"

   at Microsoft.CodeAnalysis.SyntaxTreeExtensions.VerifySource(SyntaxTree tree, IEnumerable`1 changes)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxTree.WithChanges(SourceText newText, TextChangeRange[] changes)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(ValueSource`1 oldTreeSource, ValueSource`1 newTextSource, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Document......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Could you offer some guidance to the cause and how mitigate it?

**Comment by AdamSpeight2008** [comment]
```
Microsoft Visual Studio Enterprise 2017 Preview (2)
Version 15.3.0 Preview 2.1
VisualStudio.15.Preview/15.3.0-pre.2.1+26608.5
Microsoft .NET Framework
Version 4.6.01055


Visual Basic 2017   00369-60000-00001-AA005
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA005
Microsoft Visual C# 2017
```
@jaredpar 
I think the issue was being caused by VS not correctly detecting the changed built files, in dependent project. Eg Changing `CodeAnalysis` not being detected in `VisualStudioSetup.Next`
