### ISSUE TITLE
ReferenceCachingVB is flakey in readonly-ref branch

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#20345]
The flakyness is likely brought with an integration. 
it is highly unlikely to be caused by the changes in the branch.

We should monitor the test in 15.6 and see if it is flaky there too.

**Comment by cston** [comment]
[Failed](https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit32_prtest/138/) in `features/ioperation` as well. 
```
 Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.ReferenceCachingVB
      System.IO.IOException : The process cannot access the file 'D:\j\workspace\windows_debug---36449f06\Binaries\Temp\RoslynTests\116184c3-62bb-4ca7-a0c8-12298250e0c1\ReferenceCachingVB\hello3.exe' because it is being used by another process.
      Stack Trace:
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.File.InternalDelete(String path, Boolean checkHost)
           at System.IO.File.Delete(String path)
           at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.Dispose()
        q:\roslyn\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(747,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<ReferenceCachingVB>d__54.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by khyperia** [comment]
Flaked in https://github.com/dotnet/roslyn/pull/22142 as well. [`windows_release_unit32_prtest`](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9558/)

**Comment by tmat** [comment]
Similarly the corresponding C# test:

```
Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.ReferenceCachingCS
      System.InvalidOperationException : 
      The file 'D:\j\workspace\windows_relea---a77477fc\Binaries\Temp\RoslynTests\06143ed5-69fd-40f3-a2b1-9434c7f4ddb9\ReferenceCachingCS\hello3.exe' seems to have been opened in a way that prevents us from deleting it on close.
      Is the file loaded as an assembly (e.g. via Assembly.LoadFile)?
      
      IOException: The process cannot access the file 'D:\j\workspace\windows_relea---a77477fc\Binaries\Temp\RoslynTests\06143ed5-69fd-40f3-a2b1-9434c7f4ddb9\ReferenceCachingCS\hello3.exe' because it is being used by another process.
      ---- System.IO.IOException : The process cannot access the file 'D:\j\workspace\windows_relea---a77477fc\Binaries\Temp\RoslynTests\06143ed5-69fd-40f3-a2b1-9434c7f4ddb9\ReferenceCachingCS\hello3.exe' because it is being used by another process.
      Stack Trace:
           at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.Dispose()
        q:\roslyn\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(853,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<ReferenceCachingCS>d__55.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace -----
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
           at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.DeleteFileOnClose(String fullPath)
           at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.Dispose()
```

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/10258/artifact/Binaries/Release/UnitTests/VBCSCompilerTests/net46/xUnitResults/Roslyn.Compilers.CompilerServer.UnitTests.dll.out.log

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn/issues/19763
