### ISSUE TITLE
NullReferenceException in TestWorkspace.Dispose

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20370]
Test failures in [windows_release_unit64_prtest](https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_release_unit64_prtest/107/) in #20276.
```
Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestCodeActionPreviewAndApply
Microsoft.CodeAnalysis.Editor.UnitTests.MetadataAsSource.MetadataAsSourceTests+VisualBasic.BracketedIdentifierSimplificationTest
```
```
MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
 at Microsoft.CodeAnalysis.Editor.UnitTests.MetadataAsSource.AbstractMetadataAsSourceTests.TestContext.Dispose() in q:\roslyn\src\EditorFeatures\Test\MetadataAsSource\AbstractMetadataAsSourceTests.TestContext.cs:line 145
 at Microsoft.CodeAnalysis.Editor.UnitTests.MetadataAsSource.MetadataAsSourceTests.VisualBasic.<BracketedIdentifierSimplificationTest>d__1.MoveNext() in q:\roslyn\src\EditorFeatures\Test\MetadataAsSource\MetadataAsSourceTests.VisualBasic.cs:line 68
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by MattGertz** [comment]
Mondo escrow triage:  keeping while we determine if this is a product issue.

**Comment by Pilchie** [comment]
Does not appear to be a product issue.

**Comment by Pilchie** [comment]
Pulling back into 15.3, because while not a product issue, it is hitting several tests, which makes infrastructure unreliable, and they can't easily just be skipped.

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit64_prtest/210/

**Comment by khyperia** [comment]
Failed in https://github.com/dotnet/roslyn/pull/22142 . [`windows_release_unit64_prtest`](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/9593)

**Comment by 333fred** [comment]
Another failure, dev15.5-preview1-staging, https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.5-preview1-staging/job/windows_debug_unit64/4/

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen this in 7 years.
