### ISSUE TITLE
Unit test failure on new compiler toolset

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#2048]
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Completion.CompletionProviders.CommitGenericOnParen fails after updating the toolset to Microsoft.Net.ToolsetCompilers.1.0.0-rc2-20150415-05.nupkg.

I verified that the test passes with exact same enlistment but on prior toolset (1.0.0-rc2-20150413-02)

See: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_windows_prtest/1892/testReport/Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Completion.CompletionProviders/SymbolCompletionProviderTests/CommitGenericOnParen/

I am not sure if the test needs to be fixed OR there is a compiler regression.

**Comment by mavasani** [comment]
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Completion.CompletionProviders.SymbolCompletionProviderTests.CommitGenericOnParen : System.InvalidOperationException : Sequence contains no matching element
Stack Trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.VerifyProviderCommitCheckResults(Document document, Int32 position, String itemToCommit, String expectedCodeAfterCommit, Nullable`1 commitChar, String textTypedSoFar) in C:\Roslyn\Open\src\EditorFeatures\Test\Completion\AbstractCompletionProviderTests.cs:line 336
   at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.VerifyProviderCommitWorker(String codeBeforeCommit, Int32 position, String itemToCommit, String expectedCodeAfterCommit, Nullable`1 commitChar, String textTypedSoFar, SourceCodeKind sourceCodeKind) in C:\Roslyn\Open\src\EditorFeatures\Test\Completion\AbstractCompletionProviderTests.cs:line 321
   at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.VerifyProviderCommit(String markupBeforeCommit, String itemToCommit, String expectedCodeAfterCommit, Nullable`1 commitChar, String textTypedSoFar, Nullable`1 sourceCodeKind) in C:\Roslyn\Open\src\EditorFeatures\Test\Completion\AbstractCompletionProviderTests.cs:line 142
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Completion.CompletionProviders.SymbolCompletionProviderTests.CommitGenericOnParen() in C:\Roslyn\Open\src\EditorFeatures\VisualBasicTest\Completion\CompletionProviders\SymbolCompletionProviderTests.vb:line 5102

Total tests: 1, Failures: 1, Skipped: 0, Time: 1.290 seconds

![expected_completion_item](https://cloud.githubusercontent.com/assets/10605811/7182715/0e158b06-e408-11e4-8fc2-ddfcef2aaeed.png)

![actaul_completion_list](https://cloud.githubusercontent.com/assets/10605811/7182726/177bea96-e408-11e4-8d91-9fd1023e3f5b.png)

**Comment by mavasani** [comment]
#2047 that updates the toolset.

**Comment by mavasani** [comment]
Could this be due to: https://github.com/dotnet/roslyn/commit/117d8bbb86c3c9b7877fe11b2ea50aea3c53389f

**Comment by pharring** [comment]
Should be fixed by #2120 Please try to re-enable this test when you get the new toolset.

**Comment by Pilchie** [comment]
This is blocked until the toolset is updated.

**Comment by Pilchie** [comment]
We have a new toolset now.
