### ISSUE TITLE
Completion is crashing in Typescript

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#20518]
```
   at Microsoft.CodeAnalysis.Completion.CompletionHelperServiceFactory.Service.GetCompletionHelper(Document document)
   at Microsoft.CodeAnalysis.Completion.CompletionHelper.GetHelper(Document document)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackgroundWorker(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackground(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.<>c__DisplayClass13_0.<FilterModel>b__0(Model model)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass16_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(TModel m, CancellationToken c)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass17_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(Task`1 t)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass16_0`2.<SafeContinueWithFromAsync>b__0(Task antecedent)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

We used to do this: https://github.com/dotnet/roslyn/commit/e6f090e991841d8ffb56a2be4856e41f07965ab5#diff-43f2d45ee2583c9cacabda0738d3e790L30

Now we do this: https://github.com/dotnet/roslyn/commit/e6f090e991841d8ffb56a2be4856e41f07965ab5#diff-8f9bcc305143524e9ca40b5e731bf224R35

**Comment by MattGertz** [comment]
Mondo escrow triage: meets the bar.

**Comment by Pilchie** [comment]
This is fixed and merged already.  Closing.
