### ISSUE TITLE
SdkPathInAction test failed locally

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#20510]
Stack trace:
```
 Microsoft.CodeAnalysis.VisualBasic.CommandLine.UnitTests.CommandLineTests.SdkPathInAction
      System.IO.IOException : The process cannot access the file 'C:\Users\tomat\AppData\Local\Temp\RoslynTests\b9f6dd36-f122-4cd9-9196-60e4771d13bf\System.Runtime.dll' because it is being used by another process.
      Stack Trace:
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
           at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
           at Microsoft.CodeAnalysis.Test.Utilities.TempFile.WriteAllBytes(Byte[] content)
        src\Compilers\VisualBasic\Test\CommandLine\CommandLineTests.vb(4441,0): at Microsoft.CodeAnalysis.VisualBasic.CommandLine.UnitTests.CommandLineTests.SdkPathInAction()
```

I believe the issue is that we are launching a process that reads a file that we overwrite in the next step of the test:

http://source.roslyn.io/#Roslyn.Compilers.VisualBasic.CommandLine.UnitTests/CommandLineTests.vb,4435

Windows might keep the handle to the file open. Perhaps we need to open the file with proper FileShare permission or change the test logic.

**Comment by JoeRobich** [comment]
Closing as this test seems to no longer exist
