### ISSUE TITLE
[Test failure] VsixExpInstaller.exe: The local extension failed to uninstall

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20562]
windows_debug_vs-integration_prtest [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5664) in https://github.com/dotnet/roslyn/pull/20051
```
16:00:54 	Uninstalling ExpressionEvaluatorPackage.vsix
16:00:54 "C:\Users\dotnet-bot\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe" -u /rootSuffix:RoslynDev /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" D:\j\workspace\windows_debug---0c191de0\Binaries\Debug\Vsix\ExpressionEvaluatorPackage\ExpressionEvaluatorPackage.vsix
16:00:54   Running as Admin.
16:00:59   Uninstalling local extension: 'C:\USERS\DOTNET-BOT\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_42810653ROSLYNDEV\EXTENSIONS\Y5VUOLUM.VJV\'
16:01:01 Exception: The local extension failed to uninstall.
16:01:01 System.Exception: The local extension failed to uninstall.
16:01:01    at VsixExpInstaller.Program.<>c__DisplayClass9_3.<Main>g__Uninstall8(IInstalledExtension installedExtension)
16:01:01    at VsixExpInstaller.Program.<>c__DisplayClass9_2.<Main>g__RunProgram1()
16:01:01    at VsixExpInstaller.Program.Main(String[] args)
16:01:01 Command failed to execute: C:\Users\dotnet-bot\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe -u /rootSuffix:RoslynDev /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" D:\j\workspace\windows_debug---0c191de0\Binaries\Debug\Vsix\ExpressionEvaluatorPackage\ExpressionEvaluatorPackage.vsix
16:01:01 System.Management.Automation.RuntimeException: Command failed to execute: C:\Users\dotnet-bot\.nuget\packages\roslyntools.microsoft.vsixexpinstaller\0.4.0-beta\tools\VsixExpInstaller.exe -u /rootSuffix:RoslynDev /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise" D:\j\workspace\windows_debug---0c191de0\Binaries\Debug\Vsix\ExpressionEvaluatorPackage\ExpressionEvaluatorPackage.vsix
16:01:01 at Exec-Command, D:\j\workspace\windows_debug---0c191de0\build\scripts\build-utils.ps1: line 73
16:01:01 at Deploy-VsixViaTool, D:\j\workspace\windows_debug---0c191de0\build\scripts\build.ps1: line 287
16:01:01 at Test-XUnit, D:\j\workspace\windows_debug---0c191de0\build\scripts\build.ps1: line 207
16:01:01 at <ScriptBlock>, D:\j\workspace\windows_debug---0c191de0\build\scripts\build.ps1: line 410
```

**Comment by cston** [comment]
windows_debug_vs-integration_prtest [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5689) in https://github.com/dotnet/roslyn/pull/20548

**Comment by jasonmalinowski** [comment]
This has been worked around. @tannergooding do we have a tracking bug for the root issue or is this it?

**Comment by jasonmalinowski** [comment]
@tannergooding, @cston, where did we land on this?

**Comment by CyrusNajmabadi** [comment]
Closing due to age and lack of movement.
