### ISSUE TITLE
Integration tests fail because the directory C:\Users\dotnet-bot\AppData\Local\RunTestsStorage cannot be found

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#20622]
Currently all integration runs are failing due to this error.

```
RunTest command line
C:\Users\dotnet-bot\.nuget\packages\xunit.runner.console\2.2.0-beta4-build3444\tools -log:D:\j\workspace\windows_debug---5a93876c\Binaries\Debug\runtests.log -xml -timeout:50 -procdumppath:c:\SysInternals D:\j\workspace\windows_debug---5a93876c\Binaries\Debug\UnitTests\VisualStudioIntegrationTests\Roslyn.VisualStudio.IntegrationTests.dll
Unable to cleanup storage
Could not find a part of the path 'C:\Users\dotnet-bot\AppData\Local\RunTestsStorage'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Directory.GetFiles(String path)
   at RunTests.Cache.LocalDataStorage.CleanupStorage() in q:\roslyn\src\Tools\Source\RunTests\Cache\LocalDataStorage.cs:line 143
Error Unable to resolve 3 referenced assemblies
	Microsoft.VisualStudio.ProjectAggregator, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		Microsoft.VisualStudio.Shell.15.0
	Microsoft.VisualStudio.TemplateWizardInterface, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		NuGet.VisualStudio
	Microsoft.VisualStudio.VSHelp, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		Microsoft.VisualStudio.Shell.15.0
: Unable to calculate content file for D:\j\workspace\windows_debug---5a93876c\Binaries\Debug\UnitTests\VisualStudioIntegrationTests\Roslyn.VisualStudio.IntegrationTests.dll
Unable to resolve 3 referenced assemblies
	Microsoft.VisualStudio.ProjectAggregator, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		Microsoft.VisualStudio.Shell.15.0
	Microsoft.VisualStudio.TemplateWizardInterface, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		NuGet.VisualStudio
	Microsoft.VisualStudio.VSHelp, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a referenced from
		Microsoft.VisualStudio.Shell.15.0

   at RunTests.Cache.ContentUtil.AppendReferences(StringBuilder builder, String unitTestAssemblyPath) in q:\roslyn\src\Tools\Source\RunTests\Cache\ContentUtil.cs:line 88
   at RunTests.Cache.ContentUtil.BuildTestResultContent(AssemblyInfo assemblyInfo) in q:\roslyn\src\Tools\Source\RunTests\Cache\ContentUtil.cs:line 63
   at RunTests.Cache.ContentUtil.GetTestResultContentFile(AssemblyInfo assemblyInfo) in q:\roslyn\src\Tools\Source\RunTests\Cache\ContentUtil.cs:line 43
   at RunTests.Cache.CachingTestExecutor.<RunTestAsync>d__7.MoveNext() in q:\roslyn\src\Tools\Source\RunTests\Cache\CachingTestExecutor.cs:line 36
Launched ProcDump attached to xunit.console.x86 (process Id: 5144)
```

**Comment by jasonmalinowski** [comment]
@jmarolf Are we still seeing this somewhere?
@jaredpar any ideas what might have happened here?

**Comment by jaredpar** [comment]
No idea what would've happened here. But that code should never throw.

**Comment by jaredpar** [comment]
This is a red herring. This exception is put only in the runtests.log file because it's for diagnostics only. It doesn't impact the success of the build. 

I recently made a change to stop producing this exception. Not because it's causing problems but because it makes people think it's causing problems. To be fair, it does look scary enough.
