### ISSUE TITLE
Cyclic struct fails to compile with net45 target framework, compiles and crashes with TypeLoadException with netstandard target framework

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#20624]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.2.0.61624

**Steps to Reproduce**:

1. `git clone https://github.com/hughbe/excel-mapper/tree/roslyn-demo`
2. `cd excel-mapper/src`
3. `dotnet restore`
4. `dotnet build`
5. `cd ExcelMapper.Tests`
6. `dotnet test`

**Expected Behavior**:

Compilation fails at step 4.
> Pipeline\PipelineResult.cs(9,35): error CS0523: Struct member 'PipelineResult<T>.PreviousResult' of type 'PipelineResult<T>?' causes a cycle in the struct layout [C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\ExcelMapper.csproj]

**Note**: changing the [ExcelMapper.csproj](https://github.com/hughbe/excel-mapper/blob/roslyn-demo/src/ExcelMapper/ExcelMapper.csproj) from

```xml
  <PropertyGroup>
    <TargetFrameworks>netstandard1.4</TargetFrameworks>
  </PropertyGroup>
```

to

```xml
  <PropertyGroup>
    <TargetFrameworks>netstandard1.4;net46</TargetFrameworks>
  </PropertyGroup>
```

causes the compilation to fail, and no TypeLoadException to be thrown.

**Actual Behavior**:

`TypeLoadException` thrown running the unit tests in step 6.

```
Failed   ExcelMapper.Tests.ExcelSheetTests.ReadRow_FirstRow_ReturnsExpected
Error Message:
 System.TypeLoadException : Could not load type 'ExcelMapper.Pipeline.PipelineResult`1' from assembly 'ExcelMapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Stack Trace:
   at ExcelMapper.Pipeline.Pipeline`1.CompletePipeline(String stringValue)
   at ExcelMapper.Pipeline.ColumnPipeline`1.Execute(ExcelSheet sheet, ExcelRow row) in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\Pipeline\ColumnPipeline.cs:line 29
   at ExcelMapper.ExcelPropertyMap.Execute(Object value, ExcelSheet sheet, ExcelRow row) in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\ExcelPropertyMap.cs:line 21
   at ExcelMapper.ExcelClassMap.Execute(ExcelSheet sheet, ExcelRow row) in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\ExcelClassMap.cs:line 26
   at ExcelMapper.ExcelSheet.TryReadRow[T](T& value) in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\ExcelSheet.cs:line 81
   at ExcelMapper.ExcelSheet.ReadRow[T]() in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper\ExcelSheet.cs:line 61
   at ExcelMapper.Tests.ExcelSheetTests.ReadRow_FirstRow_ReturnsExpected() in C:\Users\hugh\Documents\GitHub\excel-mapper\src\ExcelMapper.Tests\ExcelMapper\ExcelSheetTests.cs:line 66
```

**Comment by gafter** [comment]
The offending code is this

``` c#
    public struct PipelineResult<T>
    {
        public PipelineResult<T>? PreviousResult { get; }
```

This auto-property creates a backing field of type `Nullable<PipelineResult<T>>`, which contains a private field of type `PipelineResult<T>`, thus inducing a cycle. I don't know why the compiler doesn't see this in a `net46` project.

**Comment by hughbe** [comment]
Neal, I believe the compiler doesn't see this in a netstandard project - the netstandard project is the one that crashes on runtime

**Comment by gafter** [comment]
I suspect the reference assembly for the netstandard framework does not contain the private backing field of type `T` for the struct `Nullable<T>`. If so, the bug is in the reference assembly, not the compiler.

**Comment by gafter** [comment]
Issue moved to [dotnet/corefx #25251](https://github.com/dotnet/corefx/issues/25251) via [**ZenHub**](https://www.zenhub.com/)
