### ISSUE TITLE
[Test failure] BasicWinForms.DeleteControl: RemotingException: Failed to read from an IPC Port: The pipe has been ended.

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20675]
Test [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5857/) in PR https://github.com/dotnet/roslyn/pull/20556.

```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.DeleteControl
      System.AggregateException : One or more errors occurred.
      ---- System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.
      
      ---- System.Runtime.Remoting.RemotingException : Failed to connect to an IPC Port: The system cannot find the file specified.
       
      Stack Trace:
        
        ----- Inner Stack Trace #1 (System.Runtime.Remoting.RemotingException) -----
        ...
        ----- Inner Stack Trace #2 (System.Runtime.Remoting.RemotingException) -----
        
        Server stack trace: 
           at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
           at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
           at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
           at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudioWorkspace_InProc.CleanUpWaitingService()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.VisualStudioWorkspace_OutOfProc.CleanUpWaitingService()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.CleanUp()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceContext.Dispose()
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs(29,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose()
           at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```
From the [screenshot](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5857/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/BasicWinForms.DeleteControl-RemotingException-16.36.08.png), Microsoft Visual Studio 2017 is restarting.

**Comment by cston** [comment]
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicGoToDefinition.ObjectBrowserNavigation [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5909/) at the same location in PR https://github.com/dotnet/roslyn/pull/20681.

**Comment by cston** [comment]
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.RenameControl [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5933) at the same location in PR https://github.com/dotnet/roslyn/pull/20540.

**Comment by dpoeschl** [comment]
[BasicGoToDefinition.ObjectBrowserNavigation](https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6580/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Roslyn.VisualStudio.IntegrationTests.dll.out.log)

**Comment by dpoeschl** [comment]
This bug needs to be split up. Assigning to myself.

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration_prtest/6507/

**Comment by dpoeschl** [comment]
Okay, moved the active one to a new, clean bug for tracking. Closing this one in favor of the individualized bugs.
