### ISSUE TITLE
[Test failure] BasicExpressionEvaluator.ValidateLocalsWindow: No locals

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20674]
Test [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5854/) in PR https://github.com/dotnet/roslyn/pull/20654.
```
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.ValidateLocalsWindow
      Assert.Equal() Failure
      Expected: 20
      Actual:   0
      Stack Trace:
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.LocalsWindow_OutOfProc.Verifier.CheckCount(Int32 expectedCount)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicExpressionEvaluator.cs(63,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.ValidateLocalsWindow()
```
From the [screenshot](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5854/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/BasicExpressionEvaluator.ValidateLocalsWindow-EqualException-16.12.08.png), the `Autos` window was visible, not the `Locals` window.

See similar issue https://github.com/dotnet/roslyn/issues/20552.

**Comment by JoeRobich** [comment]
Unskipping this test is being tracked by https://github.com/dotnet/roslyn/issues/75456
