### ISSUE TITLE
[Test failure] CodeGenerationTests.Shared.TestSorting: InvalidOperationException : The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20700]
windows_debug_unit64_prtest [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/7780) in https://github.com/dotnet/roslyn/pull/20686.
```
Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests+Shared.TestSorting
      System.InvalidOperationException : The calling thread cannot access this object because a different thread owns it.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(945,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.TestContext.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(609,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.<TestGenerateFromSourceSymbolAsync>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.Shared.cs(341,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.Shared.<TestSorting>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Pilchie** [comment]
Can you take a look?  Maybe these tests need to be WpfFacts, if they are using a view?

**Comment by CyrusNajmabadi** [comment]
There's not enough information here to know what's going wrong.  In fact, because tests run in parallel (with the same export provider), you can hear about exceptions in another one test when another test disposes its workspace.  We need to capture more informatoin to properly track down who is at fault.  https://github.com/dotnet/roslyn/pull/20828 is a PR that attempts to do just that.

**Comment by cston** [comment]
Keeping the issue open while it is being tracked down.

**Comment by CyrusNajmabadi** [comment]
Yup.  That makes sense.

**Comment by CyrusNajmabadi** [comment]
There's been no movement on this for 3 years. The test hasn't been flakey.  Closing out as this issue isn't actionable.
