### ISSUE TITLE
[Test failure] BasicExpressionEvaluator: COMException : Operation not supported. Unknown error: 0x8971003c

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#20711]
vs-integration test [failures](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5964/) in `BasicExpressionEvaluator`

```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.EvaluateInvalidExpressions
      System.Runtime.InteropServices.COMException : Operation not supported. Unknown error: 0x8971003c.
      Stack Trace:
        
        Server stack trace: 
           at EnvDTE.Debugger.StepOver(Boolean WaitForBreakOrEnd)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Debugger_OutOfProc.StepOver(Boolean waitForBreakOrEnd)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicExpressionEvaluator.cs(149,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.Dispose(Boolean disposing)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs(30,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose()
           at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.ValidateLocalsWindow
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.StateMachineTypeParameters
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.EvaluatePrimitiveValues
      System.Runtime.InteropServices.COMException : Operation not supported. Unknown error: 0x8971003c.
      Stack Trace:
        
        Server stack trace: 
           at EnvDTE.Debugger.StepOver(Boolean WaitForBreakOrEnd)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.StepOver(Boolean waitForBreakOrEnd)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Debugger_OutOfProc.StepOver(Boolean waitForBreakOrEnd)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicExpressionEvaluator.cs(149,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicExpressionEvaluator.Dispose(Boolean disposing)
        q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\AbstractIntegrationTest.cs(30,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.Dispose()
           at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by cston** [comment]
Another instance of the [failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5974/).

**Comment by cston** [comment]
As of https://github.com/dotnet/roslyn/commit/9a0720919642962ad016a0b8431b56dfc1560fdd, `BasicExpressionEvaluator.Dispose` is now called. @ivanbasov, is the `Dispose` method necessary (is the call to `Debugger.StepOver` needed)?

**Comment by cston** [comment]
cc @sharwell

**Comment by dpoeschl** [comment]
@tmat @jinujoseph (or whoever owns this now) Can I just disable these? If not, is somebody looking into them? They've been failing somewhat frequently, maybe 1/5 PR runs...

**Comment by tmat** [comment]
@ivanbasov

**Comment by srivatsn** [comment]
[Another instance](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/6186/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicExpressionEvaluator/EvaluatePrimitiveValues/)

**Comment by dpoeschl** [comment]
A decent percent of the failures under https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/ are this, recent ones are not hard to find if you're looking for artifacts or something.

**Comment by ivanbasov** [comment]
should enable tests properly
