### ISSUE TITLE
Multiple EE expansion tests fail when run in parallel 64-bit XUnit 2

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#208]
There are multiple test failures that look something like:

```
Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpansionTests.NameConflictsWithPropertyOnGenericBase [FAIL]
      Assert.Equal() Failure
      Position: First difference is at position 1
      Expected: P (A(Of Integer))
      Actual:   P
      Stack Trace:
         E:\roslyn_git\Closed\ExpressionEvaluator\Core\Test\ResultProvider\ResultProviderTestBase.cs(323,0): at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.Verify(DkmEvaluationResult actual, DkmEvaluationResult expected)
         E:\roslyn_git\Closed\ExpressionEvaluator\Core\Test\ResultProvider\ResultProviderTestBase.cs(300,0): at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.Verify(IReadOnlyList`1 actual, DkmEvaluationResult[] expected)
         E:\roslyn_git\Closed\ExpressionEvaluator\VisualBasic\Test\ResultProvider\ExpansionTests.vb(529,0): at Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpansionTests.NameConflictsWithPropertyOnGenericBase()
```

All the test failures seem to be NameConflictsWith... tests and it seems that both the C# and VB version of the tests fail. The tests fail when used with a 64-bit version of XUnit2 running the test assemblies in parallel. To reproduce the failures.

1. Unshelve XUnit2ParallelWithFixes;angocke
2. Build Roslyn and restore NuGet packages.
3. Execute something like
```
.\packages\xunit.runners.2.0.0-rc1-build2826\tools\xunit.console.exe E:\roslyn_git\Open\Binaries\Debug\Roslyn.ExpressionEvaluator.CSharp.ExpressionCompiler.UnitTests.dll E:\roslyn_git\Open\Binaries\Debug\Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll E:\roslyn_git\Open\Binaries\Debug\Roslyn.ExpressionEvaluator.VisualBasic.ExpressionCompiler.UnitTests.dll E:\roslyn_git\Open\Binaries\Debug\Roslyn.ExpressionEvaluator.VisualBasic.ResultProvider.UnitTests.dll -noshadow -parallel assemblies
```

with whatever modifications are appropriate for your directory layout.

**Comment by amcasey** [comment]
Note that in the example command line, "." refers to the Open directory.

**Comment by amcasey** [comment]
ExpansionTests.IntPtrPointer is failing for unrelated reasons.  This surprises me since there are several similar tests.

**Comment by amcasey** [comment]
Fixed.

**Comment by amcasey** [comment]
@agocke Please verify and label "Verified"
