### ISSUE TITLE
InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormat test failure

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#20840]
Failed in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/8077/artifact/Binaries/Debug/UnitTests/EditorServicesTest2/xUnitResults/Roslyn.Services.Editor2.UnitTests.dll.out.log

Failure details:
```
Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormat
      System.Reflection.TargetParameterCountException : Parameter count mismatch.
      Stack Trace:
           at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Delegate.DynamicInvokeImpl(Object[] args)
           at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
           at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Windows.Threading.DispatcherOperation.Invoke()
           at System.Windows.Threading.Dispatcher.ProcessQueue()
           at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
           at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
           at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
           at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
           at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
           at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
           at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
           at Roslyn.Test.Utilities.DispatcherExtensions.DoEvents(Dispatcher dispatcher)
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test2\InteractivePaste\InteractivePasteCommandHandlerTests.vb(55,0): at Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormat()
    Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopyOnBlankLine
      System.AggregateException : One or more errors occurred.
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 28
      When created thread name: StaTaskScheduler thread
      Current thread id       : 4
      Current thread name     : 
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 28
      When created thread name: StaTaskScheduler thread
      Current thread id       : 4
      Current thread name     : 
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 28
      When created thread name: StaTaskScheduler thread
      Current thread id       : 4
      Current thread name     : 
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 28
      When created thread name: StaTaskScheduler thread
      Current thread id       : 4
      Current thread name     : 
      
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test2\InteractivePaste\InteractivePasteCommandHandlerTests.vb(215,0): at Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopyOnBlankLine()
        ----- Inner Stack Trace #1 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.StateMachine.Connect()
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices)
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #2 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.set_CachedTagTrees(ImmutableDictionary`2 value)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #3 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.set_CachedTagTrees(ImmutableDictionary`2 value)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #4 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.set_CachedTagTrees(ImmutableDictionary`2 value)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
    Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsLineCopy
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test2\InteractivePaste\InteractivePasteCommandHandlerTests.vb(127,0): at Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsLineCopy()
    Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormatAsBoxCopy
System.InvalidOperationException: Should have been disposed!
DataSource-StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider..ctor(IBraceMatchingService braceMatcherService, IForegroundNotificationService notificationService, IEnumerable`1 asyncListeners)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.DebugRecordInitialStackTrace()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()
```

**Comment by dpoeschl** [comment]
This looks like a bunch of different things actually. Will split up.
