### ISSUE TITLE
CSharpConvertConcatenationToInterpolatedStringRefactoringProvider encountered an error and has been disabled.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#20943]
From: https://developercommunity.visualstudio.com/content/problem/78891/csharpconvertconcatenationtointerpolatedstringrefa.html

Was writing c# code for console application when all of a sudden this popup appeared right below the menu bar. "Show Stack Trace" link gives below information

```
System.NullReferenceException : Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Can you assign to someone else.

**Comment by TheAtomicOption** [comment]
I just got the same error in VS2017 v15.4.3

It popped up after I changed this line:
```
if (assemArray[j, 0] == sr.Value2 ?? ""
```
to this:  
```
(assemArray[j, 0] ?? "" == sr.Value2 ?? ""
```

I reverted, clicked 'enable', re-entered the change, and got the same error. Putting in extra parenthesis before adding `?? ""` avoided the crash resulting in this:
```
if ((assemArray[j, 0] ?? "") == (sr.Value2 ?? ""))
```

Hopefully that makes it reproducible.



Stack trace for completeness:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mbrierst** [comment]
I've got the same message.  Different stack trace though:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by sharwell** [comment]
Here's another reproducer. Place the caret before `"d"` and press <kbd>Ctrl</kbd>+<kbd>.</kbd>

```csharp
using System;
public class Class1
{
    public Class1()
    {
        dynamic a = "b";
        string c = "d" + a + "e";
    }
}
```

:link: https://developercommunity.visualstudio.com/content/problem/183546/csharpconvertconcatenationtointerpolatedstringrefa-2.html

**Comment by jinujoseph** [comment]
also reported at [link](https://developercommunity.visualstudio.com/content/problem/200309/netstandard-dynamic-string.html)
