### ISSUE TITLE
Test failures in AssertIsForeground (RenameTracking and DiagnosticsTaggerProvider)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#20953]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_unit32_prtest/8289/artifact/Binaries/Debug/UnitTests/EditorServicesTest2/xUnitResults/Roslyn.Services.Editor2.UnitTests.dll.out.log

```
 Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekAcrossProjectsInvolvingPortableReferences
      System.AggregateException : 3 exception(s) were thrown during test.
      Note: exceptions may have been thrown by another test running concurrently with
      this test.  This can happen with any tests that share the same ExportProvider.
      Examining individual exception stacks may help reveal the original test and source 
      of the problem.
      
      Exception 0:
      Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException: When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
         at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
         at System.Diagnostics.TraceListener.Fail(String message)
         at System.Diagnostics.TraceInternal.Fail(String message)
         at System.Diagnostics.Debug.Assert(Boolean condition, String message)
         at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
         at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.StateMachine.Connect()
         at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices)
         at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
      
      Exception 1:
      Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException: When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
         at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
         at System.Diagnostics.TraceListener.Fail(String message)
         at System.Diagnostics.TraceInternal.Fail(String message)
         at System.Diagnostics.Debug.Assert(Boolean condition, String message)
         at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.OnTaggerCreated()
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.ITaggerProvider.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
      
      Exception 2:
      Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException: When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
         at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
         at System.Diagnostics.TraceListener.Fail(String message)
         at System.Diagnostics.TraceInternal.Fail(String message)
         at System.Diagnostics.Debug.Assert(Boolean condition, String message)
         at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.OnTaggerCreated()
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.ITaggerProvider.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
      
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
      ---- Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : When created kind       : StaUnitTest
      When created thread id  : 11
      When created thread name: StaTaskScheduler thread
      Current thread id       : 6
      Current thread name     : 
      
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test2\Peek\PeekTests.vb(181,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekAcrossProjectsInvolvingPortableReferences()
        ----- Inner Stack Trace #1 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceListener.Fail(String message)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.StateMachine.Connect()
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices)
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #2 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceListener.Fail(String message)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.OnTaggerCreated()
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.ITaggerProvider.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #3 (Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException) -----
           at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
           at System.Diagnostics.TraceListener.Fail(String message)
           at System.Diagnostics.TraceInternal.Fail(String message)
           at System.Diagnostics.Debug.Assert(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.AggregatingTagger.OnTaggerCreated()
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.AbstractDiagnosticsTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.ITaggerProvider.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
```

**Comment by Pilchie** [comment]
Giving back to you, since you're already invested in `ForegroundThreadAffinitizedObject`

**Comment by dpoeschl** [comment]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_unit32_prtest/8350/artifact/Binaries/Release/UnitTests/EditorServicesTest/xUnitResults/Roslyn.Services.Editor.UnitTests.dll.out.log

```
Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestCodeActionPreviewAndApply
      System.AggregateException : 2 exception(s) were thrown during test.
      Note: exceptions may have been thrown by another test running concurrently with
      this test.  This can happen with any tests that share the same ExportProvider.
      Examining individual exception stacks may help reveal the original test and source 
      of the problem.
      
      Exception 0:
      System.InvalidOperationException: Unexpected false
         at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
         at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
         at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices)
         at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer)
         at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
      
      Exception 1:
      System.InvalidOperationException: Unexpected false
         at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
         at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
         at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
         at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
         at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
         at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
         at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
         at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
      
      
      ---- System.InvalidOperationException : Unexpected false
      ---- System.InvalidOperationException : Unexpected false
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test\LinkedFiles\LinkedFileDiffMergingEditorTests.cs(48,0): at Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.<TestCodeActionPreviewAndApply>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
           at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices)
           at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
        ----- Inner Stack Trace #2 (System.InvalidOperationException) -----
           at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
           at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
           at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
           at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
System.InvalidOperationException: Should have been disposed! Try running in Debug to get the allocation callstack
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()
```

**Comment by dpoeschl** [comment]
Again in https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_unit64_prtest/8371/artifact/Binaries/Debug/UnitTests/EditorServicesTest/xUnitResults/Roslyn.Services.Editor.UnitTests.dll.out.log

**Comment by agocke** [comment]
Another repro  https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32/1565

**Comment by tmat** [comment]
One more: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9343/artifact/Binaries/Release/UnitTests/EditorServicesTest2/xUnitResults/Roslyn.Services.Editor2.UnitTests.dll.out.log

**Comment by tmat** [comment]
Another failure: 
```
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message) in /_/src/Workspaces/Core/Portable/Utilities/Contract.cs:line 86
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground() in /_/src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs:line 100
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.Tagger..ctor(StateMachine stateMachine, ITextUndoHistoryRegistry undoHistoryRegistry, IWaitIndicator waitIndicator, IEnumerable`1 refactorNotifyServices) in /_/src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.Tagger.cs:line 33
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.CreateTagger[T](ITextBuffer buffer) in /_/src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.cs:line 63
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer) in E:\A\_work\24\s\src\Editor\Text\Impl\TagAggregator\TagAggregator.cs:line 609
```

Crash dump from Jenkins:
`%internal_share%\public\tomat\Bugs\Roslyn20953`

@jinujoseph This issue is getting hit too often...
