### ISSUE TITLE
VS Test: Null references in VS adornment code

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#21010]
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_unit64_prtest/8351/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes/CodeFixServiceTests/TestGetCodeFixWithExceptionInFixableDiagnosticIds2/

```
MESSAGE:
System.AggregateException : 3 exception(s) were thrown during test.
Note: exceptions may have been thrown by another test running concurrently with
this test. This can happen with any tests that share the same ExportProvider.
Examining individual exception stacks may help reveal the original test and source 
of the problem.

Exception 0:
System.NullReferenceException: Object reference not set to an instance of an object.
 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)
 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

Exception 1:
System.NullReferenceException: Object reference not set to an instance of an object.
 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)
 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

Exception 2:
System.NullReferenceException: Object reference not set to an instance of an object.
 
at Microsoft.VisualStudio.Text.AdornmentLibrary.TextMarkers.Implementation.TextMarkerVisualManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)


---- System.NullReferenceException : Object reference not set to an instance of an object.
---- System.NullReferenceException : Object reference not set to an instance of an object.
---- System.NullReferenceException : Object reference not set to an instance of an object.

+++++++++++++++++++
STACK TRACE:

at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize) 
at Microsoft.CodeAnalysis.Workspace.Dispose() 
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.CodeFixServiceTests.<GetDefaultFixesAsync>d__6.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeFixes\CodeFixServiceTests.cs:line 103 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.CodeFixServiceTests.<TestGetCodeFixWithExceptionInFixableDiagnosticIds2>d__4.MoveNext() in q:\roslyn\src\EditorFeatures\Test\CodeFixes\CodeFixServiceTests.cs:line 84 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace #1 (System.NullReferenceException) ----- 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint) 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e) 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) ----- Inner Stack Trace #2 (System.NullReferenceException) ----- 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint) 
at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e) 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) ----- Inner Stack Trace #3 (System.NullReferenceException) ----- 
at Microsoft.VisualStudio.Text.AdornmentLibrary.TextMarkers.Implementation.TextMarkerVisualManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e) 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by dpoeschl** [comment]
Filing on the IDE team to see if anything has changed here recently on our side.

**Comment by Pilchie** [comment]
Tagging @olegtk - do these look like known issues?

**Comment by Pilchie** [comment]
Ping @olegtk @markw-t @hemchans?

**Comment by olegtk** [comment]
Hard to tell. Do you have a dump by any chance, @dpoeschl ?

**Comment by dpoeschl** [comment]
Nope, artifacts already gone from Jenkins. Will reopen if we see this again.
