### ISSUE TITLE
Microsoft.CodeAnalysis.Editor.UnitTests.SolutionCrawler.WorkCoordinatorTests.Document_InvocationReasons is failing

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21082]
This test was missing a [Fact]. When I tried adding it, it is failing:

```
MESSAGE:
Assert.False() Failure
Expected: False
Actual: True
+++++++++++++++++++
STACK TRACE:
 at Microsoft.CodeAnalysis.Editor.UnitTests.SolutionCrawler.WorkCoordinatorTests.WorkCoordinatorWorkspace.Dispose(Boolean finalize) in q:\roslyn\src\EditorFeatures\Test\SolutionCrawler\WorkCoordinatorTests.cs:line 1039
 at Microsoft.CodeAnalysis.Workspace.Dispose()
 at Microsoft.CodeAnalysis.Editor.UnitTests.SolutionCrawler.WorkCoordinatorTests.<Document_InvocationReasons>d__24.MoveNext() in q:\roslyn\src\EditorFeatures\Test\SolutionCrawler\WorkCoordinatorTests.cs:line 536 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
This code is gone.
