### ISSUE TITLE
Random test failure in Roslyn.Services.Editor.UnitTests

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21110]
[The failure in Jenkins](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/8481/artifact/Binaries/Debug/UnitTests/EditorServicesTest/xUnitResults/) but I think all we have is the log file. Not obvious to me which test failed:

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Services.Editor.UnitTests
  Discovered:  Roslyn.Services.Editor.UnitTests
  Starting:    Roslyn.Services.Editor.UnitTests
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestOpenFileOnlyAnalyzerDiagnostics
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestHasSuccessfullyLoadedBeingFalseWithCompilerAnalyzerFSAOn
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestHasSuccessfullyLoadedBeingFalseFSAOn
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestHasSuccessfullyLoadedBeingFalse
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestSynchronizeWithBuild
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestHasSuccessfullyLoadedBeingFalseWhenFileOpened
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticAnalyzerServiceTests.TestHasSuccessfullyLoadedBeingFalseWhenFileOpenedWithCompilerAnalyzer
    Microsoft.CodeAnalysis.Editor.UnitTests.Structure.BlockSpanTests.TestProperties
    Microsoft.CodeAnalysis.Editor.UnitTests.Structure.BlockSpanTests.TestToStringWithHintSpan
    Microsoft.CodeAnalysis.Editor.UnitTests.Structure.BlockSpanTests.TestToStringWithoutHintSpan
    Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestWorkspaceTryApplyChangesDirectCall
    Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestCodeActionPreviewAndApply
System.InvalidOperationException: Should have been disposed!
DataSource-StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider..ctor(IBraceMatchingService braceMatcherService, IForegroundNotificationService notificationService, IEnumerable`1 asyncListeners)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.DebugRecordInitialStackTrace()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()
```

**Comment by Pilchie** [comment]
@olegtk This looks like a case where a view tagger isn't getting disposed - any known issues  there?

**Comment by Pilchie** [comment]
Can you take a look and see if it's possible we didn't close a view in a test or somthing?

**Comment by tmat** [comment]
Another hit: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/8856/artifact/Binaries/Debug/UnitTests/EditorServicesTest2/xUnitResults/Roslyn.Services.Editor2.UnitTests.dll.out.log

**Comment by Pilchie** [comment]
@jasonmalinowski can you try to get more info here?

**Comment by jasonmalinowski** [comment]
Not much we can do with this now and a lot has also changed since then.
