### ISSUE TITLE
(UWP) .NET Native MissingManifestResourceException with a ResX Resource on .NET Standard 1.4

### ISSUE THREAD

**Issue by WilliamABradley** [dotnet/roslyn#21206]
**Version Used**: 
Microsoft.NETCore.UniversalWindowsPlatform: 5.4.0
NET Standard: 1.4

(Potentially linked to #20773)

**Steps to Reproduce**:
1. Create a UWP Project.
2. Create a .NET Standard Project.
3. Create a Resource file (ResX) in NET Standard Project.
4. Link UWP Project to NET Standard Project via Reference.
5. Fetch a String from the Resource File using Code Behind (Using the ResXFileCodeGenerator or Public variant).
6. Set Build Configuration to Release.
7. Weep.

**Expected Behavior**:
The String is loaded Successfully.

**Actual Behavior**:
I managed to reproduce the issue in a Test Project below.

Message:
```
System.Resources.MissingManifestResourceException: 'MissingManifestResource_ResWFileNotLoaded, ResXLib.Strings.Strings'
```

StackTrace:
```
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture) in f:\dd\ndp\fxcore\src\System.Resources.ResourceManager\System\Resources\ResourceManager.cs:line 75
   at TestNetCoreResXUWPIssue.MainPage..ctor() in c:\users\willi\documents\visual studio 2017\Projects\TestNetCoreResXUWPIssue\TestNetCoreResXUWPIssue\MainPage.xaml.cs:line 28
   at TestNetCoreResXUWPIssue.TestNetCoreResXUWPIssue_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() in c:\users\willi\documents\visual studio 2017\Projects\TestNetCoreResXUWPIssue\TestNetCoreResXUWPIssue\obj\x64\Release\XamlTypeInfo.g.cs:line 178
   at TestNetCoreResXUWPIssue.TestNetCoreResXUWPIssue_XamlTypeInfo.XamlUserType.ActivateInstance() in c:\users\willi\documents\visual studio 2017\Projects\TestNetCoreResXUWPIssue\TestNetCoreResXUWPIssue\obj\x64\Release\XamlTypeInfo.g.cs:line 333
   at Windows.UI.Xaml.Markup.IXamlType__Impl.Vtbl.ActivateInstance__n(IntPtr pComThis, Void** unsafe_instance__retval) in c:\users\willi\documents\visual studio 2017\Projects\TestNetCoreResXUWPIssue\TestNetCoreResXUWPIssue\obj\x64\Release\ilc\intermediate\TestNetCoreResXUWPIssue.McgInterop\ImplTypes.g.cs:line 21122
```

**Comment by WilliamABradley** [comment]
I solved this Issue.

There was a Compilation Warning during Release Configuration that you can easily miss, saying that the NeutralResourceLanguageAttribute wasn't set, and that it wouldn't allow it from being used in App Packages.

After setting all of the `[assembly: NeutralResourcesLanguage("en-NZ")]` on UWP Libraries, and `<NeutralLanguage>en-NZ</NeutralLanguage>` on .NET Standard Libraries, I no longer receive this Message, and my App runs successfully.

Perhaps the warning I was provided could be more visible, perhaps by making it an Error rather than a Warning, because it was preventing my App from Starting, when it loaded one of these Resources.
