### ISSUE TITLE
VS 2017 15.3.0 (Preview 7.0) - Code Refactoring - Code Analysis Bug 

### ISSUE THREAD

**Issue by sujaysarma** [dotnet/roslyn#21360]
Attention: @CyrusNajmabadi, @Pilchie 
(This is the issue I emailed you about and you asked I file an issue here for tracking)

**Version Used**:
Visual Studio 2017, Build 15.3.0 Preview 7.0
Microsoft (R) Roslyn C# Compiler version 2.3.2.61928 

**Steps to Reproduce**:

1. In Visual Studio 2017, Build 15.3.0 Preview 7.0, open a file and work on some code
2. Suddenly the "notice bar" appears on top of the editor tab window with the error message.
3. You can click Enable and continue working (Code Analysis works again), but after some time it will crash again.

Not pattern [type of project / code / actions] observed at this time for this behaviour. It is consistent, but not predictable.

Clicking on the "View Stack Trace" option in the notice bar that appears, I see this stack trace:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.BinaryExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.ConvertIfToSwitch.CSharpConvertIfToSwitchCodeRefactoringProvider.CSharpAnalyzer.CreatePatternFromExpression(ExpressionSyntax operand)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.ConvertIfToSwitch.AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer`4.<GetSections>d__7.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at async Microsoft.CodeAnalysis.ConvertIfToSwitch.AbstractConvertIfToSwitchCodeRefactoringProvider.Analyzer`4.ComputeRefactoringsAsync[TStatementSyntax,TIfStatementSyntax,TExpressionSyntax,TSwitchLabelSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ConvertIfToSwitch.AbstractConvertIfToSwitchCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
Simple repro:

```c#
static class Program
{
    static void Main(int i)
    {
        // Invoke refactoring here
        if ((i == 0) && i == 1)
        {

        }
        else if (i == 1)
        {

        }
    }
}
```

**Comment by sujaysarma** [comment]
I was not doing any refactoring in the traditional sense. I was just coding. Perhaps the refactoring got triggered while I was normally editing [type, delete, backspace, that sort of thing] code.

**Comment by sharwell** [comment]
@sujaysarma The refactoring engine is invoked as you work in the background just to find places where refactorings are available, in order to show the light bulb. The work to calculate the refactored result is only done if you invoke the light bulb and show a preview. :smile:
