### ISSUE TITLE
Command Line parser fails on `-debug+/debug:portable`

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#21508]
Command Line parser fails on `-debug+/debug:portable`

```
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)   at System.Environment.get_StackTrace()   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)   at System.Diagnostics.Debug.Assert(Boolean condition)   at Microsoft.CodeAnalysis.CommandLineParser.<ParseFileArgument>d__41.MoveNext()   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.CommonParse(IEnumerable`1 args, String baseDirectory, String sdkDirectoryOpt, String additionalReferenceDirectories)   at Microsoft.CodeAnalysis.CommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CommonCompiler..ctor(CommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler..ctor(CSharpCommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc..ctor(String responseFile, BuildPaths buildPaths, String[] args, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 13
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 22
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 47
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/BuildClient.cs:line 85
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 42
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/CSharp/CscCore/Program.cs:line 10
Unhandled Exception: System.Diagnostics.Debug+DebugAssertException:

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CommandLineParser.<ParseFileArgument>d__41.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.CommonParse(IEnumerable`1 args, String baseDirectory, String sdkDirectoryOpt, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CommonCompiler..ctor(CommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler..ctor(CSharpCommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc..ctor(String responseFile, BuildPaths buildPaths, String[] args, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 13
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 22
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 47
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/BuildClient.cs:line 85
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 42
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/CSharp/CscCore/Program.cs:line 10
   at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CommandLineParser.<ParseFileArgument>d__41.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineParser.CommonParse(IEnumerable`1 args, String baseDirectory, String sdkDirectoryOpt, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CommandLineParser.Parse(IEnumerable`1 args, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories)
   at Microsoft.CodeAnalysis.CommonCompiler..ctor(CommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler..ctor(CSharpCommandLineParser parser, String responseFile, String[] args, BuildPaths buildPaths, String additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc..ctor(String responseFile, BuildPaths buildPaths, String[] args, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 13
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/Csc.cs:line 22
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 47
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/BuildClient.cs:line 85
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/Shared/CoreClrBuildClient.cs:line 42
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) in /Users/tyoverby/workspace/c#/roslyn/src/Compilers/CSharp/CscCore/Program.cs:line 10
```

**Comment by jcouv** [comment]
Fixed for 15.6 preview 3
