### ISSUE TITLE
FileChangeTracker shouldn't subscribe just to unsubscribe

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#21704]
Consider the pattern we do today when we dispose of a FileChangeTracker:

https://github.com/dotnet/roslyn/blob/6dcaacc61efc3edbebeaf4dd3a6ef22c1d1874ae/src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeTracker.cs#L139-L145

When we open a solution, we create a bunch of Lazys for each file that is in the solution, and then create a series of tasks which will pull on those Lazys to subscribe for each file. When we close the solution, we unsubscribe from everything, which we do by waiting for each Lazy. If you close the solution soon enough, we'll pull on the Lazys to get the subscription cookie, only to then immediately use that cookie to unsubscribe.

We just need to be a bit smarter here: it's correct to wait for subscription to finish before trying to unsubscribe, but if we never even started the subscription and can safely abort before starting the request, we should just abort the subscription request.

**Comment by jviau** [comment]
This is currently causing crashes during testing. Initializing the lazy during `StopFileChangeListening()` is throwing a `NotSupportedException`, which crashes tests due to `FailFast` behavior in `FilterException`.

Here is the call stack:
```
00DFD6E4 178e892c System.NotSupportedException
00DFD6E8 0c891e74 System.Action`1[[System.Exception, mscorlib]]
00DFD710 2061e574 System.String    System.NotSupportedException: Specified method is not supported.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.<StartFileChangeListeningAsync>b__17_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.StopFileChangeListening()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReference.Dispose()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Disconnect()
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.Disconnect()
00DFD714 178e892c System.NotSupportedException
00DFD744 178e892c System.NotSupportedException
00DFD748 0c891e74 System.Action`1[[System.Exception, mscorlib]]
00DFD774 178e892c System.NotSupportedException
00DFD77C 0c891e74 System.Action`1[[System.Exception, mscorlib]]
00DFD7A4 178e892c System.NotSupportedException
00DFD7B4 2061e574 System.String    System.NotSupportedException: Specified method is not supported.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.<StartFileChangeListeningAsync>b__17_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.StopFileChangeListening()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReference.Dispose()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Disconnect()
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.ProjectSystemShim.VisualBasicProject.Disconnect()
```

**Comment by jviau** [comment]
Talked with @jasonmalinowski, he pointed me to a root issue in the VS file watcher. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/459037

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski i don't see this code anymore.  do we still need this?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski i'm tentatively closing this out (it's been 8 years).  If you think it is still important enough to do, reopen.

**Comment by jasonmalinowski** [comment]
Not sure if the code exists, but it's definitely being deleted once we merge https://github.com/dotnet/roslyn/pull/78321.
