### ISSUE TITLE
Contract violation in Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize() during test run

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21708]
From: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9125/
     Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestCodeActionPreviewAndApply
System.InvalidOperationException: Should have been disposed! Try running in Debug to get the allocation callstack
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()

**Comment by AlekseyTs** [comment]
This could be the same issue https://ci.dot.net/job/dotnet_roslyn/job/features_DefaultInterfaceImplementation/job/windows_debug_unit32_prtest/53/

**Comment by AlekseyTs** [comment]
Here is another instance of this issue: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64/1606/

**Comment by AlekseyTs** [comment]
Bumping the priority, I see this kind of failure often.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-ide IDE team, could someone investigate this failure?

**Comment by AlekseyTs** [comment]
This looks like another instance: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32/1605/

**Comment by AlekseyTs** [comment]
This looks like another instance:
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_unit32/1609/
```
    Microsoft.CodeAnalysis.Editor.UnitTests.LinkedFiles.LinkedFileDiffMergingEditorTests.TestCodeActionPreviewAndApply
System.InvalidOperationException: Should have been disposed!
DataSource-StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1..ctor(IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider..ctor(IBraceMatchingService braceMatcherService, IForegroundNotificationService notificationService, IEnumerable`1 asyncListeners)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


StackTrace:
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.DebugRecordInitialStackTrace()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource..ctor(ITextView textViewOpt, ITextBuffer subjectBuffer, AbstractAsynchronousTaggerProvider`1 dataSource, IAsynchronousOperationListener asyncListener, IForegroundNotificationService notificationService)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetOrCreateTagSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.CreateTaggerWorker[T](ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AsynchronousViewTaggerProvider`1.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<Initialize>b__13_0(ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.Initialize()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.EnsureInitialized()
   at Microsoft.VisualStudio.Utilities.JoinableTaskHelper.<>c__DisplayClass4_0.<<RunOnUIThread>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0()
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()
```

**Comment by AlekseyTs** [comment]
Ping @dotnet/roslyn-ide, @jasonmalinowski

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_release_unit64_prtest/153/artifact/Binaries/Release/UnitTests/EditorServicesTest2/xUnitResults/Roslyn.Services.Editor2.UnitTests.dll.out.log

```
System.InvalidOperationException: Should have been disposed! Try running in Debug to get the allocation callstack
   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.Finalize()
```

**Comment by 333fred** [comment]
Another failue: https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_unit64_prtest/209/.

**Comment by 333fred** [comment]
Another failure https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7-preview1-vs-deps/job/windows_debug_unit64/5/. @jasonmalinowski, have you looked into this at all?

**Comment by jasonmalinowski** [comment]
I can't find any failures of this in runfo; given the age of this let's close this out as stale.
