### ISSUE TITLE
InlineTemporaryCodeRefactoringProvider fails (InfoBar) on VB code

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#21739]
Try to inline `diagInfo` local in code below. The code provider crashes and gets disabled. The stacktrace is copied below.

```VB
        Private Sub CheckNamedArgumentsForLateboundInvocation(argumentNames As ImmutableArray(Of String),
                                                            arguments As ImmutableArray(Of BoundExpression),
                                                            diagnostics As DiagnosticBag)

            If argumentNames.Count = 0 Then
                Return
            End If

            If Not Compilation.LanguageVersion.AllowNonTrailingNamedArguments() Then
                Return
            End If

            Dim seenName As Boolean = False
            For i As Integer = 0 To argumentNames.Count - 1

                If argumentNames(i) IsNot Nothing Then
                    seenName = True
                ElseIf seenName Then
                    Dim diagInfo = ErrorFactory.ErrorInfo(ERRID.ERR_NamedArgumentSpecificationBeforeFixedArgumentInLateboundInvocation)
                    ReportDiagnostic(diagnostics, arguments(i).Syntax, diagInfo)
                    Return
                End If
            Next

        End Sub
```

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxList`1.RemoveAt(Int32 index)
   at Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.RemoveDefinition(ModifiedIdentifierSyntax modifiedIdentifier,SyntaxNode newBlock)
   at async Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.VB$StateMachine_10_InlineTemporaryAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

FYI @sharwell @CyrusNajmabadi for triage.

**Comment by dpoeschl** [comment]
It shows the InfoBar but doesn't crash the product.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
