### ISSUE TITLE
System.InvalidOperationException : "The calling thread cannot access this object because a different thread owns it." is thrown by Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.TestExtensionMethods test

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#21741]
From https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.4.x/job/windows_debug_unit64/20/:
```
Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.TestExtensionMethods
      System.InvalidOperationException : The calling thread cannot access this object because a different thread owns it.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(944,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.TestContext.Dispose()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.cs(608,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.<TestGenerateFromSourceSymbolAsync>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        q:\roslyn\src\EditorFeatures\Test\CodeGeneration\CodeGenerationTests.CSharp.cs(1154,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests.<TestExtensionMethods>d__34.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

CC @dotnet/roslyn-ide, @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@sharwell cleaned up much of this area to avoid sharing state between tests, and that would have fixed some issues like this.
