### ISSUE TITLE
InvalidOperationException from Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.GetDocument

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#21771]
Stack trace:

```
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.GetDocument()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackgroundWorker(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.FilterModelInBackground(Model model, Int32 id, SnapshotPoint caretPosition, CompletionFilterReason filterReason, ImmutableDictionary`2 filterState)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.<>c__DisplayClass13_0.<FilterModel>b__0(Model model)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass16_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(TModel m, CancellationToken c)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass17_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(Task`1 t)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass16_0`2.<SafeContinueWithFromAsync>b__0(Task antecedent)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\TaskContinuation.cs:line 121
   at System.Threading.Tasks.Task.Execute() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 2498
```

Crash dump: %internal_share%\public\tomat\Bugs\21771

VS version: 15.4.0 P1 (26823.1.d15rel)

**Comment by rchande** [comment]
Looks like this might be a different bug

**Comment by rchande** [comment]
Actually, this stack is no longer possible in the most recent builds of Roslyn (GetDocument()) is not allowed to be called from background threads
