### ISSUE TITLE
CompilerServerUnitTests.HelloWorldCS fails intermittently

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#2183]
Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.HelloWorldCS
System.IO.IOException : The process cannot access the file 'C:\Users\tomat\AppData\Local\Temp\RoslynTests\0858c6f7-88af-47e2-a19c-14cd51ee8cd1\hello.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.CodeAnalysis.Test.Utilities.DisposableFile.Dispose() in C:\R5\Src\Test\Utilities\DisposableFile.cs:line 27
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.VerifyResultAndOutput(ProcessResult result, TempDirectory path, String expectedOutput) in C:\R5\Src\Compilers\Core\VBCSCompilerTests\CompilerServerTests.cs:line 332
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.HelloWorldCS() in C:\R5\Src\Compilers\Core\VBCSCompilerTests\CompilerServerTests.cs:line 436

**Comment by VSadov** [comment]
Consider pushing to 1.1 if this is just an infrastructure/test issue

**Comment by jaredpar** [comment]
I've run this test 200+ times on my machine with the latest code and have not seen this issue.  If this repros for you again could you use handle / process explorer to see which process is holding onto the file? That would help us track it down if it still exists.

**Comment by VSadov** [comment]
Thanks!!
