### ISSUE TITLE
IDE crashes when editing code that involves stackalloc expressions

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#21887]
When I am trying to edit stuff that involves stackalloc I frequently see a crash with the following stack.
It seems that semantic model is not robust against broken code when stackalloc is involved.

==============

Message: System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundBadExpression' to type 'Microsoft.CodeAnalysis.CSharp.BoundConversion'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoForNode(BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)

**Comment by OmarTawfik** [comment]
Fixed By #21746
