### ISSUE TITLE
Flaky test failure PersistentService_Solution_WriteReadSameInstance

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22230]
See https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/9632/testReport/junit/Microsoft.CodeAnalysis.UnitTests.WorkspaceServices/SQLitePersistentStorageTests/PersistentService_Solution_WriteReadSameInstance/

```
Stacktrace
MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.ReadStringToEnd(Stream stream) in q:\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 425
at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Solution_WriteReadSameInstance>d__24.MoveNext() in q:\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 157
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Solution_WriteReadSameInstance>d__23.MoveNext() in q:\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 141 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
Closing out.  This test has been running for years now without an issue.
