### ISSUE TITLE
EnC crash - rename of captured local

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#2225]
Run to breakpoint.  Rename f1 to g1 (ignore rename conflicts - #1729).

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication3
{
    class Program
    {
        int x = 1;

        static void Main(string[] args)
        {
            Program p = new Program() { x = 2 };
            p.M(y: 3);

        }

        void M(int y)
        {
            Func<int> f1 = () => y;
            Func<int, long> f2 = z => f1() + z;
            Func<int, byte> f3 = z => (byte)(f2(y) + z);
            Func<byte> f4;
            if (f1() != f2(f3(y)))
            {
                byte b = 2;
                Func<Func<int>, Func<byte>> f5 = f => () => (byte)(f3(f()) + b);
                f4 = f5(f1);
            }
            else
            {
                long l = 4;
                f4 = () => (byte)f2(y + (int)l);
            }

            Debugger.Break();
            Console.WriteLine(f4());
        }
    }
}
```

**Comment by amcasey** [comment]
```
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>An item with the same key has already been added.</Message><StackTrace>   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.CalculateCapturedVariablesMaps(SemanticModel oldModel, ImmutableArray`1 oldCaptures, ISymbol oldMember, SyntaxNode oldMemberBody, SemanticModel newModel, ImmutableArray`1 newCaptures, ISymbol newMember, SyntaxNode newMemberBody, BidirectionalMap`1 map, ArrayBuilder`1 reverseCapturesMap, ArrayBuilder`1 newCapturesToClosureScopes, ArrayBuilder`1 oldCapturesToClosureScopes, List`1 diagnostics, Boolean&amp;amp; hasErrors, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaAndClosureRudeEdits(SemanticModel oldModel, SyntaxNode oldMemberBody, ISymbol oldMember, SemanticModel newModel, SyntaxNode newMemberBody, ISymbol newMember, IReadOnlyDictionary`2 matchedLambdasOpt, BidirectionalMap`1 map, List`1 diagnostics, Boolean&amp;amp; newBodyHasLambdas, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.AnalyzeSemantics(EditScript`1 editScript, Dictionary`2 editMap, SourceText oldText, ImmutableArray`1 oldActiveStatements, List`1 triviaEdits, List`1 updatedMethods, SemanticModel oldModel, SemanticModel newModel, List`1 semanticEdits, List`1 diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.&amp;lt;AnalyzeDocumentAsync&amp;gt;d__62.MoveNext()</StackTrace><ExceptionString>System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.CalculateCapturedVariablesMaps(SemanticModel oldModel, ImmutableArray`1 oldCaptures, ISymbol oldMember, SyntaxNode oldMemberBody, SemanticModel newModel, ImmutableArray`1 newCaptures, ISymbol newMember, SyntaxNode newMemberBody, BidirectionalMap`1 map, ArrayBuilder`1 reverseCapturesMap, ArrayBuilder`1 newCapturesToClosureScopes, ArrayBuilder`1 oldCapturesToClosureScopes, List`1 diagnostics, Boolean&amp;amp; hasErrors, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaAndClosureRudeEdits(SemanticModel oldModel, SyntaxNode oldMemberBody, ISymbol oldMember, SemanticModel newModel, SyntaxNode newMemberBody, ISymbol newMember, IReadOnlyDictionary`2 matchedLambdasOpt, BidirectionalMap`1 map, List`1 diagnostics, Boolean&amp;amp; newBodyHasLambdas, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.AnalyzeSemantics(EditScript`1 editScript, Dictionary`2 editMap, SourceText oldText, ImmutableArray`1 oldActiveStatements, List`1 triviaEdits, List`1 updatedMethods, SemanticModel oldModel, SemanticModel newModel, List`1 semanticEdits, List`1 diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.&amp;lt;AnalyzeDocumentAsync&amp;gt;d__62.MoveNext()</ExceptionString></Exception></TraceRecord>
```

**Comment by amcasey** [comment]
This may be a dup of #2223.

**Comment by amcasey** [comment]
I believe it's a dup.

**Comment by tmat** [comment]
More issues with the same repro:
1) After applying the rename change the EE still displays "f1", not "g1". 
2) Step twice after applying the change. TypeLoadException Could not load type "Invalid_Token.0x02000000" is thrown.
3) Moving IP to the open brace of M's body kills thhe debugging session and produces an error:
"Unable to set the next statement. Operation not supported. Unknown error: 0x89710067."

**Comment by tmat** [comment]
Can't be reproduced anymore since #2731 disallows renaming captured local.
