### ISSUE TITLE
'GenerateTypeCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by dimaaan** [dotnet/roslyn#22293]
**Version Used**: 
Visual Studio Community 2017 v15.3.5

**Steps to Reproduce**:

1. File -> New -> Windows Classic Desktop Console App (.NET Framework) targeting .NET Framework 3.0
2. In Program.cs paste:
```csharp
using System;
using System.Threading;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Task task = new Task(Display);
            task.Start();
        }

        static void Display()
        {
        }
    }
}
```
3. Over `new Task(Display)` choose 'Show potential fixes'

**Expected Behavior**:
'Show potential fixes' should suggest me to update to .NET Framework 4+ to use Task or didn't appears at all.

**Actual Behavior**:
Message "'GenerateTypeCodeFixProvider' encountered an error and has been disabled" apeears at the top of code editor window.

Pressing show stack trace gives:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Extensions.ITypeSymbolExtensions.GenerateTypeSyntax(INamespaceOrTypeSymbol symbol,Boolean nameSyntax)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.FieldGenerator.GenerateFieldDeclaration(IFieldSymbol field,CodeGenerationDestination destination,CodeGenerationOptions options)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.FieldGenerator.AddFieldTo(TypeDeclarationSyntax destination,IFieldSymbol field,CodeGenerationOptions options,IList`1 availableIndices)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddField[TDeclarationNode](TDeclarationNode destination,IFieldSymbol field,CodeGenerationOptions options,IList`1 availableIndices)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.UpdateDestination[TDeclarationNode](IList`1 availableIndices,CodeGenerationOptions options,TDeclarationNode currentDestination,ISymbol member,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembersToAppropiateLocationInDestination[TDeclarationSyntax](TDeclarationSyntax destination,IEnumerable`1 members,IList`1 availableIndices,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembers[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 members,IList`1 availableIndices,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembers[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 members,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.NamedTypeGenerator.GenerateNamedTypeDeclaration(ICodeGenerationService service,INamedTypeSymbol namedType,CodeGenerationDestination destination,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.NamedTypeGenerator.AddNamedTypeTo(ICodeGenerationService service,NamespaceDeclarationSyntax destination,INamedTypeSymbol namedType,CodeGenerationOptions options,IList`1 availableIndices,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddNamedType[TDeclarationNode](TDeclarationNode destination,INamedTypeSymbol namedType,CodeGenerationOptions options,IList`1 availableIndices,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.UpdateDestination[TDeclarationNode](IList`1 availableIndices,CodeGenerationOptions options,TDeclarationNode currentDestination,ISymbol member,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembersToAppropiateLocationInDestination[TDeclarationSyntax](TDeclarationSyntax destination,IEnumerable`1 members,IList`1 availableIndices,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembers[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 members,IList`1 availableIndices,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.AddMembers[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 members,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.NamespaceGenerator.GenerateNamespaceDeclaration(ICodeGenerationService service,INamespaceSymbol namespace,CodeGenerationOptions options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.NamespaceGenerator.AddNamespaceTo(ICodeGenerationService service,CompilationUnitSyntax destination,INamespaceSymbol namespace,CodeGenerationOptions options,IList`1 availableIndices,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddNamespace[TDeclarationNode](TDeclarationNode destination,INamespaceSymbol namespace,CodeGenerationOptions options,IList`1 availableIndices,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.<>c__DisplayClass54_0.<AddNamespaceAsync>b__0(SyntaxNode t,CodeGenerationOptions opts,IList`1 ai,CancellationToken ct)
   at async Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.GetEditAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.Editor.GetGenerateInNewFileOperationsAsync[TService,TSimpleNameSyntax,TObjectCreationExpressionSyntax,TExpressionSyntax,TTypeDeclarationSyntax,TArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.Editor.GetOperationsAsync[TService,TSimpleNameSyntax,TObjectCreationExpressionSyntax,TExpressionSyntax,TTypeDeclarationSyntax,TArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.GenerateTypeCodeAction.ComputeOperationsAsync[TService,TSimpleNameSyntax,TObjectCreationExpressionSyntax,TExpressionSyntax,TTypeDeclarationSyntax,TArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by dpoeschl** [comment]
I was unable to reproduce this locally, but I might have missed something. @chborl, can you try it out?

**Comment by sys27** [comment]
@dpoeschl I can reproduce it every time (VS Community 15.3.5) and only if you click 'Show potential fixes' on `new Task`, but `Task task =` works (VS throw the exception, when it is trying to build code preview).

It throws the exception, because `IFieldSymbol.Type` is null and `FieldGenerator.GenerateFieldDeclaration` calls the `GenerateTypeSyntax()` on null object (FieldGenerator.cs@104).

Maybe, `DetermineMembers()` should return `IMethodSymbol` instead of `IFieldSytem` (because actually Display is method).

`IFieldSymbol` is created by `Editor`, then we try to `DetermineMembers` -> `AddFieldDelegatingConstructor` and try to determine the type of argument (in our case 'Display'), but `CSharpSemanticModel.GetTypeInfoForNode()` cannot find right type (because Display is not IFieldSymbol and doesn't have a type, if we change it to `static int Display` everything works) and keep it null.

Probably, we need to add new condition, right after `if (highestBoundExprKind == BoundKind.Lambda)` to check is it BoundKind.MethodGroup and some how get the right type (System.Action).

**Comment by Neme12** [comment]
@sys27
> some how get the right type (System.Action).
The code already does that. The core issue here is that there's no `System.Action` in .NET Framework 3.0. `DetermineMembers` works correctly. It creates the new field that should have `System.Action` as its type, but instead the type is null.

**Comment by Neme12** [comment]
I don't know what to do here... We probably shouldn't create a delegate type for you. But object won't work.

**Comment by Neme12** [comment]
> But object won't work.

well I guess it's gonna have to... there's no way around this really. @dimaaan what would you like us to do here?

IMO, the best thing to do would be to just put in System.Action, make you realize it doesn't exist and make you question your choice of framework version even more :smile: but the code works with symbols, so we have to give it a real type

**Comment by CyrusNajmabadi** [comment]
Our standard practice is to just use 'object'. The user can adjust the result to whatever they want based on their own coding practices.
