### ISSUE TITLE
EditAndContinueTests.AnonymousTypes changes emit order in 64-bit runner

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#223]
Failure:

```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTests.AnonymousTypes [FAIL]
        Actual:
        <Module>,
        VB$AnonymousType_1`2,
        VB$AnonymousType_2`1,
        VB$AnonymousType_0`2,
        A,
        B
        Differences:
            <Module>,
            VB$AnonymousType_1`2,
        ++> VB$AnonymousType_2`1,
            VB$AnonymousType_0`2,
        Stack Trace:
           src\Test\Utilities\AssertEx.cs(208,0): at Roslyn.Test.Utilities.AssertEx.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTestBase.vb(212,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTestBase.CheckNames(MetadataReader[] readers, StringHandle[] handles, String[] expectedNames)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTestBase.vb(207,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTestBase.CheckNames(MetadataReader reader, StringHandle[] handles, String[] expectedNames)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTests.vb(3328,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTests.AnonymousTypes()
```

**Comment by tmat** [comment]
Known issue - anonymous types are non-deterministically ordered. The compiler needs to be fixed to order them.

**Comment by tmat** [comment]
(the non-determinism is in enumerating dictionary entries)

**Comment by gafter** [comment]
I see there is also a skipped test `AnonymousDelegates` which I will investigate to see if it is the same issue.

**Comment by agocke** [comment]
jenkins retest this please

**Comment by gafter** [comment]
@agocke can you please verify?

**Comment by gafter** [comment]
Verifying that this test is no longer skipped in the stabilization branch.
