### ISSUE TITLE
AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat Null Reference Info Bar

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22324]
From: https://developercommunity.visualstudio.com/content/problem/117219/microsoftcodeanalysisconverttointerpolatedstringab.html

```
at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Parametri sconosciuti>)
at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Parametri sconosciuti>)
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by a11smiles** [comment]
I too am getting this: 

    System.NullReferenceException : Object reference not set to an instance of an object.
    at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
    at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
    at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Neme12** [comment]
Could this be a duplicate of #20943? Is there any repro of this?

**Comment by Neme12** [comment]
@jinujoseph Can you please check?

**Comment by Neme12** [comment]
I don't know how this works so I'm sorry to bother but is there any repro/code attached to the feedback item so we can make sure it is the same issue as #20943? If not, can we just assume that because the stack trace is the same and close this as a duplicate? @jinujoseph

**Comment by jnm2** [comment]
I'm hitting this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
