### ISSUE TITLE
 Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.SQLitePersistentStorageTests.PersistentService_Document_WriteReadSameInstance is flakey

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#22437]
When testing locally

 `Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.SQLitePersistentStorageTests.PersistentService_Document_WriteReadSameInstance`

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.ReadStringToEnd(Stream stream) in C:\workspace\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 425
   at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Document_WriteReadSameInstance>d__28.MoveNext() in C:\workspace\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Document_WriteReadSameInstance>d__27.MoveNext() in C:\workspace\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by heejaechang** [comment]
@sharwell any idea?

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't had any issues for years and we have an existing system for tracking flakey tests.
