### ISSUE TITLE
VS crash: ArgumentException from ExternalErrorDiagnosticUpdateSource.AddNewErrors

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#22522]
Stack trace:

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) in f:\dd\ndp\clr\src\BCL\system\throwhelper.cs:line 72
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) in f:\dd\ndp\clr\src\BCL\system\collections\generic\dictionary.cs:line 393
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ExternalErrorDiagnosticUpdateSource.<>c__DisplayClass29_0.<AddNewErrors>b__0() in E:\A\_work\24\s\src\VisualStudio\Core\Def\Implementation\TaskList\ExternalErrorDiagnosticUpdateSource.cs:line 306
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass15_0.<ContinueWithAfterDelay>b__1(Task _) in E:\A\_work\24\s\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 278
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass3_0.<SafeContinueWith>g__continuationFunction0(Task antecedent) in E:\A\_work\24\s\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 105
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass7_0`1.<SafeContinueWith>g__outerFunction0(Task t) in E:\A\_work\24\s\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 179
```

Crash dump:

%internal_share%\public\tomat\Bugs\22522

**Comment by CyrusNajmabadi** [comment]
This type has been removed.
