### ISSUE TITLE
Visual Studio crashed when compiling VB class library with Roslyn based extension

### ISSUE THREAD

**Issue by ranuka2** [dotnet/roslyn#22537]
**Version Used**: Microsoft.CondeAnalysis 1.3.2

**Steps to Reproduce**:

1. Create a VSIX (VB#) project in Visual Studio 2015 Update 3 with .Net framework 4.5
2. Add Microsoft.CodeAnalysis library version 1.3.2 to VSIX project using NuGet
3. Add menu command "Compile" to the VSIX project
4. Add following code in menu command action

```
string projectFilePath = @"C:\VBProj\ClassLib.vbproj";
string outputFilePath = @"C:\TargetFolder\myDll.dll";
Project project = null;

using (var workspace = MSBuildWorkspace.Create())
{
	project = workspace.OpenProjectAsync(projectFilePath).Result;
	var compilation = project.GetCompilationAsync().Result;
	var compilationStatus = compilation.Emit(outputFilePath);
	bool isSuccess = compilationStatus.Success; 
}
```
5. Install the compiled extension (VSIX) in VS 2015 Update 3 and Invoke the "Compile" menu command

**Expected Behavior**:
Roslyn should be able to compile the project and emit output to target location.

**Actual Behavior**:
Visual Studio crashed with following trace log.

> Faulting application name: devenv.exe, version: 14.0.25420.1, time stamp:
> 0x57685d85
> 
> Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
> 
> Exception code: 0x80131623
> 
> Fault offset: 0x26a2ab86
> 
> Faulting process id: 0x23d0
> 
> Faulting application start time: 0x01d3363ac17ff278
> 
> Faulting application path: [C:\Program|file:///C:/Program] Files (x86)\Microsoft Visual Studio
> 14.0\Common7\IDE\devenv.exe
> 
> Faulting module path: unknown
> 
> Report Id: xxxx-xxx-xxxx-xxxx-xxxxx
> 
> 
> 
> Application: devenv.exe
> 
> Framework Version: v4.0.30319
> 
> Description: The application requested process termination through
> System.Environment.FailFast(string message).
> 
> Message: System.ArgumentException: An item with the same key has already
> been added.
> 
> at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
> 
> at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue
> value, Boolean add)
> 
> at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
> 
> at Microsoft.CodeAnalysis.Solution.CompilationTracker.<
> FinalizeCompilationAsync>d__29.MoveNext()
> 
> Stack:
> 
> at System.Environment.FailFast(System.String, System.Exception)
> 
> at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
> 
> at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception,
> System.Action`1<System.Exception>)
> 
> at Microsoft.CodeAnalysis.ErrorReporting.FatalError.
> ReportUnlessCanceled(System.Exception)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> FinalizeCompilationAsync>d__29.MoveNext()
> 
> at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
> 
> at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
> Version=4.0.0.0, Culture=neutral, PublicKeyToken=
> b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0,
> Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon,
> System.__Canon, Boolean)
> 
> at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
> Version=4.0.0.0, Culture=neutral, PublicKeyToken=
> b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0,
> Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon,
> System.__Canon)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> FinalizeCompilationAsync>d__29.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<FinalizeCompilationAsync>d__29,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<FinalizeCompilationAsync>d__29 ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> FinalizeCompilationAsync(Microsoft.CodeAnalysis.Solution,
> Microsoft.CodeAnalysis.Compilation, System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> BuildCompilationInfoFromScratchAsync>d__23.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<BuildCompilationInfoFromScratchAsync>d__23,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<BuildCompilationInfoFromScratchAsync>d__23
> ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> BuildCompilationInfoFromScratchAsync(Microsoft.CodeAnalysis.Solution,
> State, System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> BuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, System.Threading.
> CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> GetOrBuildCompilationInfoAsync>d__21.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<GetOrBuildCompilationInfoAsync>d__21,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<GetOrBuildCompilationInfoAsync>d__21
> ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, Boolean,
> System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> GetCompilationAsync(Microsoft.CodeAnalysis.Solution, System.Threading.
> CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> GetMetadataReferenceAsync>d__33.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon,
> mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=
> b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<GetMetadataReferenceAsync>d__33,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<GetMetadataReferenceAsync>d__33 ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> GetMetadataReferenceAsync(Microsoft.CodeAnalysis.Solution,
> Microsoft.CodeAnalysis.ProjectState, Microsoft.CodeAnalysis.ProjectReference,
> System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution.GetMetadataReferenceAsync(
> Microsoft.CodeAnalysis.ProjectReference, Microsoft.CodeAnalysis.ProjectState,
> System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> FinalizeCompilationAsync>d__29.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<FinalizeCompilationAsync>d__29,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<FinalizeCompilationAsync>d__29 ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> FinalizeCompilationAsync(Microsoft.CodeAnalysis.Solution,
> Microsoft.CodeAnalysis.Compilation, System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> BuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, System.Threading.
> CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> GetOrBuildCompilationInfoAsync>d__21.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.Solution+CompilationTracker+CompilationInfo,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].Start[[Microsoft.CodeAnalysis.
> Solution+CompilationTracker+<GetOrBuildCompilationInfoAsync>d__21,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]](<GetOrBuildCompilationInfoAsync>d__21
> ByRef)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker.
> GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.Solution, Boolean,
> System.Threading.CancellationToken)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> GetMetadataOnlyImageReferenceAsync>d__35.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore+
> MoveNextRunner.InvokeMoveNext(System.Object)
> 
> at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore+
> MoveNextRunner.Run()
> 
> at System.Threading.Tasks.AwaitTaskContinuation.
> RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task
> ByRef)
> 
> at System.Threading.Tasks.Task.FinishContinuations()
> 
> at System.Threading.Tasks.Task.FinishStageThree()
> 
> at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.VersionStamp,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.
> CodeAnalysis.VersionStamp)
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.VersionStamp, Microsoft.CodeAnalysis.Workspaces,
> Version=1.3.1.0, Culture=neutral, PublicKeyToken=
> 31bf3856ad364e35]].SetResult(Microsoft.CodeAnalysis.VersionStamp)
> 
> at Microsoft.CodeAnalysis.Solution+CompilationTracker+<
> GetDependentSemanticVersionAsync>d__43.MoveNext()
> 
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore+
> MoveNextRunner.InvokeMoveNext(System.Object)
> 
> at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Runtime.CompilerServices.AsyncMethodBuilderCore+
> MoveNextRunner.Run()
> 
> at System.Threading.Tasks.AwaitTaskContinuation.
> RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task
> ByRef)
> 
> at System.Threading.Tasks.Task.FinishContinuations()
> 
> at System.Threading.Tasks.Task.FinishStageThree()
> 
> at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.VersionStamp,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.
> CodeAnalysis.VersionStamp)
> 
> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[
> Microsoft.CodeAnalysis.VersionStamp, Microsoft.CodeAnalysis.Workspaces,
> Version=1.3.1.0, Culture=neutral, PublicKeyToken=
> 31bf3856ad364e35]].SetResult(Microsoft.CodeAnalysis.VersionStamp)
> 
> at Roslyn.Utilities.AsyncLazy`1+Request[[Microsoft.CodeAnalysis.VersionStamp,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].CompleteFromTaskSynchronously(
> System.Threading.Tasks.Task`1<Microsoft.CodeAnalysis.VersionStamp>)
> 
> at Roslyn.Utilities.AsyncLazy`1+Request[[Microsoft.CodeAnalysis.VersionStamp,
> Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral,
> PublicKeyToken=31bf3856ad364e35]].CompleteFromTaskSynchronouslyS
> tub(System.Object)
> 
> at System.Threading.Tasks.Task.InnerInvoke()
> 
> at System.Threading.Tasks.Task.Execute()
> 
> at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
> 
> at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
> System.Threading.ContextCallback, System.Object, Boolean)
> 
> at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task
> ByRef)
> 
> at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
> 
> at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.
> ExecuteWorkItem()
> 
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 
> at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
>

**Comment by sharwell** [comment]
@heejaechang Were these issues not fixed by #33262?
