### ISSUE TITLE
Flaky test: Metadata file 'mscorlib.dll (netstandard 2.0 ref)' could not be opened

### ISSUE THREAD

**Issue by khyperia** [dotnet/roslyn#22603]
https://github.com/dotnet/roslyn/pull/22487

https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_14_debug_prtest/6867/

```
09:40:46     Microsoft.CodeAnalysis.CSharp.UnitTests.PatternParsingTexts.ThrowExpression_Good [FAIL]
09:40:46       
09:40:46       Expected:
09:40:46       Actual:
09:40:46                       // error CS0009: Metadata file 'mscorlib.dll (netstandard 2.0 ref)' could not be opened -- Invalid argument
09:40:46                       Diagnostic(ErrorCode.FTL_MetadataCantOpenFile).WithArguments("mscorlib.dll (netstandard 2.0 ref)", "Invalid argument").WithLocation(1, 1)
09:40:46       Diff:
09:40:46       ++>                 Diagnostic(ErrorCode.FTL_MetadataCantOpenFile).WithArguments("mscorlib.dll (netstandard 2.0 ref)", "Invalid argument").WithLocation(1, 1)
09:40:46       Expected: True
09:40:46       Actual:   False
09:40:46       Stack Trace:
09:40:46            at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
09:40:46            at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
09:40:46            at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
09:40:46            at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
09:40:46         /mnt/j/workspace/dotnet_roslyn/master/ubuntu_14_debug_prtest/src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs(75,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternParsingTexts.ThrowExpression_Good()
```

**Comment by 333fred** [comment]
Failed again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.6.x-vs-deps/job/mac_debug/50/

**Comment by jaredpar** [comment]
This seems to have stabilized since I moved it to the new compilation helpers. Will re-open if this happens again.
