### ISSUE TITLE
VS crash: AbstractInternalsVisibleToCompletionProvider.GetAttributeSyntaxNodeOfToken throws NRE

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#22690]
```
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node) in E:\A\_work\24\s\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.IsStringLiteralExpression(SyntaxNode node) in E:\A\_work\24\s\src\Workspaces\CSharp\Portable\LanguageServices\CSharpSyntaxFactsService.cs:line 1314
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractInternalsVisibleToCompletionProvider.GetAttributeSyntaxNodeOfToken(ISyntaxFactsService syntaxFactsService, SyntaxToken token) in E:\A\_work\24\s\src\Features\Core\Portable\Completion\Providers\AbstractInternalsVisibleToCompletionProvider.cs:line 78
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractInternalsVisibleToCompletionProvider.<ProvideCompletionsAsync>d__4.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\Providers\AbstractInternalsVisibleToCompletionProvider.cs:line 55
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__31.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 449
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__24.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 311
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__22.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 241
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionService.<GetCompletionsAndSetItemDocumentAsync>d__11.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionService.cs:line 183
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__13.MoveNext() in E:\A\_work\24\s\src\EditorFeatures\Core\Implementation\IntelliSense\Completion\Controller.Session_ComputeModel.cs:line 103
```

Crash dump: %internal_share%\public\tomat\Bugs\22690

VS build: 15.5.0 P1 (26927.1)

**Comment by tmat** [comment]
@jinujoseph This is causing crash when typing in Interactive Window.

**Comment by jinujoseph** [comment]
cc @MaStr11

**Comment by MaStr11** [comment]
I tried to reproduce this but the *C# interactive window* isn't working in my experimental hive (TypeLoadException for WatsonReporter in VsInteractiveWindowPackage'1.Initialize). I wasn't able to get an NRE in normal code files because [token.Parent](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractInternalsVisibleToCompletionProvider.cs,77) is never `null` there. I assume that adding a null check [here](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractInternalsVisibleToCompletionProvider.cs,78) should be enough to prevent the NRE:
```CSharp
if (node != null && syntaxFactsService.IsStringLiteralExpression(node))
```
I tried to come up with a test for C# interactive to provoke an NRE like so:
```VB
        <WorkItem(22690, "https://github.com/dotnet/roslyn/issues/22690")>
        <WpfFact, Trait(Traits.Feature, Traits.Features.Completion)>
        Public Async Function CodeCompletionInInteractive() As Task
            Using state = TestState.CreateTestStateFromWorkspace(
                <Workspace>
                    <Submission Language="C#" CommonReferences="true">$$</Submission>
                </Workspace>, workspaceKind:=WorkspaceKind.Interactive)
                state.SendInvokeCompletionList()
                Await state.AssertCompletionSession()
                state.SendTypeChars("""")
                Await state.AssertNoCompletionSession()
            End Using
        End Function
```
This test passes without NRE (`token.Parent` is not null after `SendTypeChars("""")`). So I have no idea how to reproduce this NRE.

**Comment by jinujoseph** [comment]
cc @tmat were you consistently able to repro this ?
@sharwell to validate and triage for 15.5

**Comment by jinujoseph** [comment]
@ivanbasov , can you check if you are seeing hit for this in Watson

**Comment by ivanbasov** [comment]
@jinujoseph, I could not find any Watson for this issue.

**Comment by sharwell** [comment]
@MaStr11 I have no idea how to reproduce this. Can you sent a PR with the added null check, but no need to add a test since it doesn't reproduce the error.

**Comment by MaStr11** [comment]
Okay. I will do so within the next 2 days.
