### ISSUE TITLE
Sqlite exception is leaking from persistent service

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22766]
Sqlite is implementation detail and anything about it should never escape persistent service boundary. but it looks like Sqlite exception is leaking from the service.

in dev15.5 preview 1, I got this exception in the service hub log.

```
10/18/2017 02:39:06 : Error : Microsoft.CodeAnalysis.Remote.CodeAnalysisService (1496) : Exception: Microsoft.CodeAnalysis.SQLite.Interop.SqlException: database table is locked: StringInfo1
database table is locked
   at Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Throw(sqlite3 handle, Result result)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.TryFetchStringTable(SqlConnection connection)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.BulkPopulateProjectIds(SqlConnection connection, Project project, Boolean fetchStringTable)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.TryGetDocumentDataId(SqlConnection connection, Document document, String name, Int64& dataId)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.DocumentAccessor.TryGetDatabaseId(SqlConnection connection, ValueTuple`2 key, Int64& dataId)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.Accessor`3.<ReadStreamAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<LoadAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<GetIndexWorkerAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<GetIndexAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ComputeSearchResultsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<TryFilterPreviousSearchResultsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<FindSearchResultsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<>c__DisplayClass13_0.<<SearchProjectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.<RunServiceAsync>d__25`1.MoveNext()
10/18/2017 02:39:06 : Error : Microsoft.CodeAnalysis.Remote.CodeAnalysisService (1496) : From:    at Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.LogUnlessCanceled(Exception ex, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.<RunServiceAsync>d__25`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.<RunServiceAsync>d__25`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Remote.ServiceHubServiceBase.RunServiceAsync[T](Func`2 callAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<SearchProjectAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.SearchProjectAsync(ProjectId projectId, String searchPattern, CancellationToken cancellationToken)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at StreamJsonRpc.TargetMethod.Invoke(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.<DispatchIncomingRequestAsync>d__68.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at StreamJsonRpc.JsonRpc.DispatchIncomingRequestAsync(JsonRpcMessage request, JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonRpc.<HandleRpcAsync>d__72.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at StreamJsonRpc.JsonRpc.HandleRpcAsync(String json)
   at StreamJsonRpc.JsonRpc.<>c__DisplayClass71_0.<<ReadAndHandleRequestsAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at StreamJsonRpc.JsonRpc.<>c__DisplayClass71_0.<ReadAndHandleRequestsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by heejaechang** [comment]
I am a bit confused on Sqlite Busy and Lock exception. when and how those can happen?

**Comment by sharwell** [comment]
This issue was fixed for 15.5 Preview 2 by 9577061e928d873e877c5e49152785decd19e21c. Comments are in #22658.

**Comment by heejaechang** [comment]
that's good to hear. but still curious. I believe we are using shared connection and no exclusive mode. so in what condition db becomes locked or busy?

**Comment by sharwell** [comment]
When using a shared cache, only one connection is allowed to have write access at a time. Subsequent attempts to write from other connections will see LOCKED.

**Comment by heejaechang** [comment]
but all of our connection is shared connection and each process own 1 db, unless there is code path that create a connection without shared connection bit on, this can't happen?

if there is a code path, then, that looks like a bug.

**Comment by sharwell** [comment]
> but all of our connection is shared connection

This is the scenario that produces a LOCKED result.

* If we used multiple connections but did not use a shared cache, this case would see a BUSY result.
* If we only used one connection instance in the code, we would not see a LOCKED or BUSY result (exclusive access by only one connection all the way from application layer to DB layer).

**Comment by heejaechang** [comment]
I see. I read this again. (https://www.sqlite.org/sharedcache.html) and multiple connection with shared cache is a bit different than Esent it looks like

have we tested which one is better for us? just using 1 connection with concurrent access vs multiple connection with no concurrent access?

**Comment by heejaechang** [comment]
@jinujoseph @sharwell said this is already fixed.

**Comment by heejaechang** [comment]
@sharwell curious. when Busy or Locked situation happens, does persistent service retry or just throw exception or return false for the caller to handle?

**Comment by sharwell** [comment]
@heejaechang I'm not actually sure there.
