### ISSUE TITLE
Add Using from NuGet stopped working in 15.5 on 10/9

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#22806]
**Version Used**: I can repro on 15.5.0 P1 27009.1.d15rel

**Steps to Reproduce**:

1. Back up and then delete your `%localappdata%\Microsoft\VisualStudio\15.0_<letters>\PackageCache` directory
2. Open a new C# project and type `JsonConvert j;` in a method
3. Wait a few minutes for the PackageCache of NuGet types to repopulate. Ctrl+. on `JsonConvert`.

**Expected Behavior**: Add Using offers to download Json.NET (and the PackageCache directory deleted in step 1 is recreated with a nuget database inside)
**Actual Behavior**: No Add Using (and no recreated PackageCache directory / nuget database)

Exception:
```
Unable to find method 'OnDownloadFullDatabaseStartedAsync/1' on Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchService+LogService for the following reasons: 
```
```
Downloading index failed:
StreamJsonRpc.RemoteMethodNotFoundException: Unable to find method 'OnDownloadFullDatabaseStartedAsync/1' on Microsoft.VisualStudio.LanguageServices.SymbolSearch.VisualStudioSymbolSearchService+LogService for the following reasons: 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__64`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.Updater.<DownloadFullDatabaseAsync>d__9.MoveNext()
```

**Comment by dpoeschl** [comment]
I think it's supposed to jump to `VisualStudioSymbolSearchProgressService.OnDownloadFullDatabaseStartedAsync`, not `VisualStudioSymbolSearchService+LogService`
