### ISSUE TITLE
[Discussion] Method linking

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#22857]
## Background

For async and iterator statemachines the source method can be linked back from the running method using the StateMachineAttribute and knowledge that the statemachine is defined in a type at the same level as the source method https://github.com/dotnet/coreclr/pull/14655

![Match back](https://aoa.blob.core.windows.net/aspnet/matching.png)

However; this is an implementation detail of the current output of the roslyn compiler.

## Aims

It would be desirable if there was a way in the type system to link back that did not rely on the layout.

It would also be desirable if there was a mechanism that worked for lambdas and local functions.

## Use Case

An example use case for this is output in stack traces.

## Discussion Starter

One approach would be to add new attributes for the source and generated method/types so the two could be matched.
```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsageAttribute(AttributeTargets.All, Inherited = true)]
    public class CompilerGeneratedTypeAttribute: Attribute
    {
        public Type BuilderType { get; }
        public string BuilderMethodName { get; }
    }

    [AttributeUsageAttribute(AttributeTargets.All, Inherited = true)]
    public class CompilerGeneratedMethodAttribute: Attribute
    {
        public Type BuilderType { get; }
        public string BuilderMethodName { get; }
    }

    [AttributeUsageAttribute(AttributeTargets.All, Inherited = true)]
    public class BuilderMethodAttribute : Attribute
    {
        public Type GeneratedType { get; }
        public string GeneratedMethodName { get; }
        public string DisplayMethodName { get; }
    }
}
```
Async and iterators both already have a contract via `IAsyncStateMachine` and `IEnumerator` and match can be confirmed via `StateMachineAttribute` on the source method; so they would only need the `CompilerGeneratedTypeAttribute` to tell the runtime where to look for the source method
```csharp
class System.Linq.Enumerable
{
    [CompilerGeneratedType(builderType: = typeof(Enumerable), 
                           builderMethodName:= "SkipWhileIterator")]
    class <SkipWhileIterator>d__177`1 : IEnumerator
    {
        // ...
    }
}
```
Local functions would require both; with the `DisplayMethodName` referring to the original local function name:
```csharp
class Program
{
    public void Foo(int arg)
    {
        PrintTheArg();
        return;
        void PrintTheArg()
        {
            Console.WriteLine(arg);
        }
    }
}
```
Creating
```csharp
class Program
{
    internal struct c__DisplayClass0_0
    {
        public int arg;
    }
    
    [BuilderMethod(generatedType: = typeof(Program), 
                   generatedMethodName:= "Foo_g__PrintTheArg0_0", 
                   displayMethodName := "PrintTheArg")]
    public void Foo(int arg)
    {
        var c__DisplayClass0_ = new c__DisplayClass0_0() { arg = arg };
        Foo_g__PrintTheArg0_0(ref c__DisplayClass0_);
    }

    [CompilerGeneratedType(builderType: = typeof(Program), 
                           builderMethodName:= "Foo")]
    internal static void Foo_g__PrintTheArg0_0(ref c__DisplayClass0_0 ptr)
    {
        Console.WriteLine(ptr.arg);
    }
}
```

Lambdas' `DisplayMethodName` could be sequential for the containing function e.g. `Lambda1`,`Lambda2` and capturing ones could perhaps be differentiated `Closure3`, `Closure4`

**Comment by tmat** [comment]
@tmat

**Comment by benaadams** [comment]
As an example on what change processing the stack trace in this (and a couple other ways) is it transforms this output
```
at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Microsoft.Extensions.Internal.StackTraceHelperTest.<Iterator>d__5.MoveNext()
at System.String.Join(String separator, IEnumerable`1 values)
at Microsoft.Extensions.Internal.StackTraceHelperTest.GenericClass`1.GenericMethod[V](V& value)
at Microsoft.Extensions.Internal.StackTraceHelperTest.<MethodAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.Extensions.Internal.StackTraceHelperTest.<MethodAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.Extensions.Internal.StackTraceHelperTest.Method(String value)
at Microsoft.Extensions.Internal.StackTraceHelperTest.StackTraceHelper_ProducesReadableOutput()
```
To this
```
System.Collections.Generic.List<T>+Enumerator.MoveNextRare()
Microsoft.Extensions.Internal.StackTraceHelperTest.Iterator()+MoveNext()
string.Join(string separator, IEnumerable<string> values)
Microsoft.Extensions.Internal.StackTraceHelperTest+GenericClass<T>.GenericMethod<V>(ref V value)
Microsoft.Extensions.Internal.StackTraceHelperTest.MethodAsync(int value)
Microsoft.Extensions.Internal.StackTraceHelperTest.MethodAsync<TValue>(TValue value)
Microsoft.Extensions.Internal.StackTraceHelperTest.Method(string value)
Microsoft.Extensions.Internal.StackTraceHelperTest.StackTraceHelper_ProducesReadableOutput()
```
 https://github.com/aspnet/Common/pull/274#discussion_r147352931

**Comment by danmosemsft** [comment]
Clearly the cleaner stack is an improvement but is it worth retaining some indication of where the async transition happened? It may be relevant.

**Comment by benaadams** [comment]
It doesn't differentiate between actual async and a sync completion - they both have the boundary - however I am also experimenting with deeper stack trace insight in a library https://github.com/benaadams/Ben.Demystifier

It marks the methods as `async` and the output is more like:
```csharp
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
 at bool System.Collections.Generic.List<T>+Enumerator.MoveNextRare()
 at bool Program.Iterator(int startAt)+MoveNext()                             // Resolved enumerator
 at bool System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext() // Resolved enumerator
 at string string.Join(string separator, IEnumerable<string> values)                    
 at string Program+GenericClass<TSuperType>.GenericMethod<TSubType>(ref TSubType value) 
 at async Task<string> Program.MethodAsync(int value)                         // Resolved async 
 at async Task<string> Program.MethodAsync<TValue>(TValue value)              // Resolved async 
 at string Program.Method(string value)+()=>{}                                // Resolved lambda source 
 at string Program.RunLambda(Func<string> lambda)                              
 at (string val, bool) Program.Method(string value)                           // Tuple returning
 at ref string Program.RefMethod(string value)+LocalFuncRefReturn()           // ref return local func
 at int Program.RefMethod(string value)+LocalFuncParam(string val)            // local function
 at string Program.RefMethod(string value)                                     
 at (string val, bool) static Program()+(string s, bool b)=>{}                // tuple return static lambda
 at void static Program()+(string s, bool b)=>{}                              // void static lambda
 at void Program.Start((string val, bool) param)                              // Resolved tuple param
 at void Program.Start((string val, bool) param)+LocalFunc1(long l)           // void local function 
 at bool Program.Start((string val, bool) param)+LocalFunc2(bool b1, bool b2) // bool return local function 
 at string Program.Start()                                                     
 at void Program()+()=>{}                                                     // ctor defined lambda  
 at void Program(Action action)+(object state)=>{}                            // ctor defined lambda 
 at void Program.RunAction(Action<object> lambda, object state)                
 at new Program(Action action)                                                // constructor 
 at new Program()                                                             // constructor 
 at void Program.Main(String[] args)                             
```
However I also have to parse the method's il to get exact overload matching on lambdas/locals without an extra annotation

**Comment by danmosemsft** [comment]
I do not understand well how async works, but is it interesting to distinguish whether there was actually an async transition (ie. thread may have done other work) since a method marked async may actually complete synchronously?

**Comment by benaadams** [comment]
> is it interesting to distinguish whether there was actually an async transition (ie. thread may have done other work) since a method marked async may actually complete synchronously?

I'd think so; however the stack traces don't currently differentiate

**Comment by tmat** [comment]
My concern would be the size of the additional metadata this would produce. 

A crazy idea: what if the compiler emitted an assembly level attribute that contains a RegEx pattern with a single group that translates compiler-generated metadata name to the original source name of the method? The reges would only match compiler generated names.
