### ISSUE TITLE
CompilerServerUnitTests.MultipleSimultaneousCompiles failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#22913]
```
MESSAGE:
System.AggregateException : One or more errors occurred.
---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
+++++++++++++++++++
STACK TRACE:
----- Inner Stack Trace #1 (System.IndexOutOfRangeException) ----- 
at System.Collections.Generic.List`1.Add(T item) 
at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.CreateDirectory() 
at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<MultipleSimultaneousCompiles>d__42.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 ----- Inner Stack Trace #2 (System.IndexOutOfRangeException) -----
 at System.Collections.Generic.List`1.Enumerator.MoveNext() at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.DisposeAll(IEnumerable`1 temps) 
at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.Dispose() at Roslyn.Test.Utilities.TestBase.Dispose() 
at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by tmat** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/post-dev15.5-contrib/job/windows_debug_unit32_prtest/131/testReport/junit/Microsoft.CodeAnalysis.CompilerServer.UnitTests/CompilerServerUnitTests/MultipleSimultaneousCompiles/

**Comment by khyperia** [comment]
Another repro in https://github.com/dotnet/roslyn/pull/23507 - https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/10915/testReport/junit/Microsoft.CodeAnalysis.CompilerServer.UnitTests/CompilerServerUnitTests/MultipleSimultaneousCompiles/

```
Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MultipleSimultaneousCompiles
      System.AggregateException : One or more errors occurred.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
        
        ----- Inner Stack Trace #1 (System.IndexOutOfRangeException) -----
           at System.Collections.Generic.List`1.Add(T item)
           at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.AddFile(DisposableFile file)
           at Microsoft.CodeAnalysis.Test.Utilities.TempDirectory.CreateFile(String name)
           at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.CreateFiles(TempDirectory currentDirectory, IEnumerable`1 files)
           at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.RunCommandLineCompiler(RequestLanguage language, String argumentsSingle, TempDirectory currentDirectory, IEnumerable`1 filesInDirectory, IEnumerable`1 additionalEnvironmentVars, Encoding redirectEncoding, Boolean shouldRunOnServer)
           at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<>c__DisplayClass41_0.<RunCompilationAsync>b__0()
           at System.Threading.Tasks.Task`1.InnerInvoke()
           at System.Threading.Tasks.Task.Execute()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<MultipleSimultaneousCompiles>d__42.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace #2 (System.IndexOutOfRangeException) -----
           at System.Collections.Generic.List`1.Enumerator.MoveNext()
           at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.DisposeAll(IEnumerable`1 temps)
           at Microsoft.CodeAnalysis.Test.Utilities.TempRoot.Dispose()
           at Roslyn.Test.Utilities.TestBase.Dispose()
           at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```
