### ISSUE TITLE
InvalidCastException in operation factory code (CreateBoundMemberInitializerOperation) while executing latest FxCop operation analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22967]
**Version Used**: Install latest d15rel drop 27031.1.d15rel

**Steps to Reproduce**:

1. git clone https://github.com/JamesNK/Newtonsoft.Json
2. add myget package feed for roslyn-analyzers: https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json
3. install latest preview of Microsoft.CodeAnalysis.FxCopAnalyzers version 2.6.0-beta1-62231-02 to all projects in solution
4. enable FSA for C#

Got the following AD0002 diagnostic for crash in Operation factory while executing analyzers:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0002	Analyzer driver threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.LazyInvalidOperation' to type 'Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation'.'.	Newtonsoft.Json.Tests(net35)		1	Active	Analyzer driver threw the following exception:
'System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.LazyInvalidOperation' to type 'Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation'.
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.<>c__DisplayClass49_0.<CreateBoundMemberInitializerOperation>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Operations.BaseMemberInitializerExpression.<get_Children>d__6.MoveNext()
   at Microsoft.CodeAnalysis.Operations.OperationExtensions.<Descendants>d__3.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
-----
'.
```

**Comment by mavasani** [comment]
Tagging @jinujoseph

**Comment by mavasani** [comment]
Tagging @AlekseyTs @cston @dotnet/analyzer-ioperation 

It seems like [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Operations/CSharpOperationFactory.cs,966) cast is failing and we need to change the type of [IMemberInitializerOperation.InitializedMember](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IMemberInitializerOperation.cs,24) from `IMemberReferenceOperation` to `IOperation` to handle error cases and stop doing this cast. Does this sound reasonable or needs discussing at next design meeting?

**Comment by mavasani** [comment]
So, I investigated this further and looks like the `IMemberInitializerOperation` is only used for C# for [BoundObjectInitializerMember](http://source.roslyn.io/#q=BoundObjectInitializerMember). VB creates a simple assignment bound node/operation with member reference as the left and initializer expression as the right. I think we should make the tree shape consistent across languages using either of the following:

1. Remove IMemberInitializerOperation API and match VB's current operation tree.
2. Generate IMemberInitializerOperation node in VB for nested member initializer.

I think we can go for option 1 and add the API back later if there is feedback.

**Comment by mavasani** [comment]
I read the specs for [C#](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#object-initializers) and [VB](https://github.com/dotnet/vblang/blob/master/spec/expressions.md#object-creation-expressions) object/collection initializers and realized that only C# supports the nested object member initializers of the form mentioned in http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IMemberInitializerOperation.cs,11. VB only allows expressions as the right hand side of member initializer. So the fact that IMemberInitializerOperation node appears only for C# is correct, but we should probably rename the node better, say `INestedMemberInitializerOperation`? I will leave that as a separate issue/discussion and proceed with fixing the InvalidCastException here.
