### ISSUE TITLE
Access is denied: 'Microsoft.CodeAnalysis.Remote.RemoteHostClient'

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#23296]
**Version Used**: 15.3.2

**Steps to Reproduce**:

1. Open VisualStudioSetup.Next.csproj
2. Start Debugging or Start Without Debugging 
3. Open a ConsoleApp project

**Actual Behavior**:

After a couple of seconds an exception is thrown.
```
Access is denied: 'Microsoft.CodeAnalysis.Remote.RemoteHostClient'.
   at Roslyn.VisualStudio.DiagnosticsWindow.Remote.RemoteHostClientFactory.<CreateAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Roslyn.VisualStudio.DiagnosticsWindow.Remote.RemoteHostClientFactory.CreateAsync(Workspace workspace, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.RemoteHostClientService.<EnableAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteHostClientExtensions.<SynchronizePrimaryWorkspaceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ResetStatesAsync>d__37.MoveNext()

**Comment by jcouv** [comment]
@heejaechang Could you help route/triage this issue?

**Comment by heejaechang** [comment]
@alrz is this still repro? and there was some changes on VS.Next, you probably want to use latest VS (15.5) and make sure you delete RoslynDev hive and start fresh.

**Comment by alrz** [comment]
Doesn't repro on 15.5 Preview 3 with roslyn's master. Closing.
