### ISSUE TITLE
ExtractMethodCodeFefactoringProvider - System.ArgumentOutOfRangeException : 'end' must not be less than 'start'

### ISSUE THREAD

**Issue by elachlan** [dotnet/roslyn#23451]
**Version Used**:
Microsoft Visual Studio Community 2017 
Version 15.4.5
VisualStudio.15.Release/15.4.5+27004.2010
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Community
Visual Basic 2017   00369-60000-00001-AA072

**Steps to Reproduce**:

```
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionResult.ContainsInstanceExpression()
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicMethodExtractor.VisualBasicCodeGenerator.CreateMethodModifiers()
   at async Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicMethodExtractor.VisualBasicCodeGenerator.VB$StateMachine_11_GenerateMethodDefinitionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicMethodExtractor.VisualBasicCodeGenerator.VB$StateMachine_5_GenerateResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by elachlan** [comment]
ContainsInstanceExpression should probably just return false when the first and last are equal or if last is less than first.

**Comment by CyrusNajmabadi** [comment]
This indicates a bug elsewhere.  best if the bug was fixed and now the downstream symptom :)

**Comment by jinujoseph** [comment]
@JoeRobich can you see if this is resolved by your fix [here ](https://github.com/dotnet/roslyn/pull/28983)

**Comment by jinujoseph** [comment]
also reported [here ](https://developercommunity.visualstudio.com/content/problem/311260/introducevariablecoderefactoringprovider-encounter-1.html)

**Comment by JoeRobich** [comment]
@jinujoseph This issue is different than the one that I fixed.

@elachlan I know it has been a while, but can you share steps to reproduce this issue? Was there a particular VB language feature you were trying out when you started to see this issue?

**Comment by elachlan** [comment]
@JoeRobich It was in Nov 2017. I can't remember what I would have been doing.

**Comment by jinujoseph** [comment]
reported at [link](https://developercommunity.visualstudio.com/content/problem/344691/microsoft-code-analysis-problem.html)

**Comment by CyrusNajmabadi** [comment]
Closing out as fixed.
