### ISSUE TITLE
Intermittent failure in DiagnosticAnalyzerTests.DiagnosticAnalyzerAllInOne

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#2349]
Assert below fails from time to time.
```
Private Function BuildMembersAndInitializers(diagBag As DiagnosticBag) As MembersAndInitializers
#If DEBUG Then
            Dim threadId = Environment.CurrentManagedThreadId
            Debug.Assert(m_computingMembersThreadId <> threadId)
            Interlocked.CompareExchange(m_computingMembersThreadId, threadId, 0)
#End If 
``` 
Here is the stack trace of the exception:

```
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.BuildMembersAndInitializers(DiagnosticBag diagBag) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1683
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GetMembersAndInitializers() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1646
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.get_MemberAndInitializerLookup() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1639
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GetMembers(String name) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 3131
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbolExtensions.FindMember(NamedTypeSymbol container, String symbolName, SymbolKind kind, TextSpan nameSpan, SyntaxTree tree) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\NamedTypeSymbolExtensions.vb:line 34
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.FindSymbolFromSyntax(MethodBaseSyntax syntax, SyntaxTree tree, NamedTypeSymbol container) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMethodSymbol.vb:line 1100
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetDeclaredSymbol(MethodBaseSyntax declarationSyntax, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1032
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclaredSymbol(MethodBlockBaseSyntax declarationSyntax, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 2650
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclaredSymbolCore(SyntaxNode declaration, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3302
   at Microsoft.CodeAnalysis.SemanticModel.GetDeclarationInfo(SyntaxNode node, Boolean getSymbol, IEnumerable`1 executableCodeBlocks, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 839
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.ComputeDeclarationsCore(SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, ArrayBuilder`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3596
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.ComputeDeclarationsCore(SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, ArrayBuilder`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3551
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclarationsInNode(SyntaxNode node, Boolean getSymbol, CancellationToken cancellationToken, Nullable`1 levelsToCompute) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3447
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<AnalyzeDeclaringReferenceAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 351
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventsAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 319").WithLocation(1, 1)s
```

**Comment by AlekseyTs** [comment]
@VSadov Please verify.

**Comment by jaredpar** [comment]
The updated assert has been in place for two months now and we have seen no recurrences of the problem.  Verified.
