### ISSUE TITLE
CSharpAddImportCodeFixProvider Crashes on add reference to system.componentmodel.composition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23535]
A new NetStandard 2.0 project, with source code copied from an earlier project: it has an [Export] attribute.

The IDE suggests to add reference to System.ComponentModel.Composition ... And the CSharpAddImportCodeFixProvider Ccrashes.

System.AggregateException : One or more errors occurred. ---&gt; The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---&gt; (Inner Exception #0) System.IO.FileLoadException : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly&amp; assembly,Boolean forIntrospection,Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at async Microsoft.VisualStudio.ProjectSystem.References.UnresolvedAssemblyReference.GetAssemblyNameAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.&lt;&gt;c__DisplayClass28_0.&lt;Add&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.&lt;&gt;c__DisplayClass562_0.&lt;Mutate&gt;b__0(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction,Boolean includesFileSystemChange)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.Add(String bstrPath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyMetadataReferenceAdded(ProjectId projectId,MetadataReference metadataReference)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155562/csharpaddimportcodefixprovider-crashes-on-add-refe.html
VSTS ticketId: 529528_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Looks like a crash in Microsoft.VisualStudio.ProjectSystem.  Tagging @davkean

**Comment by davkean** [comment]
Hmm, you are giving us what looks like a bad path perhaps in ApplyMetadataReferenceAdded?
