### ISSUE TITLE
Typing <space> after override keyword crashes Visual Studio

### ISSUE THREAD

**Issue by DiablosOffens** [dotnet/roslyn#23617]
**Version Used**:
1.3.4.60902 (Visual Studio 2015 Update 3 with KB3165756 applied)

**Steps to Reproduce**:

1. Create a C# source file.
2. Insert the following code:
```
class Foo<T>
{
public virtual void Bar() {}
}
class FooBar<T1, T2> : Foo<T2>
{
override
}

```
3. Hit `<space>` after override keyword to trigger code completion.
4. If it has not already crashed, try to select `Bar` as method to override.

**Expected Behavior**:
Snippet of code is inserted at the place where `override` was.

**Actual Behavior**:
Crash or System.IndexOutOfRangeException if Visual Studio was running under a debugger.
The following call stack was listed for the Exception:
```
   at Microsoft.CodeAnalysis.SymbolId.Parser.GetNthTypeParameter(INamedTypeSymbol typeSymbol, Int32 n)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeParameterSymbol(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeSymbol()
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseTypeArguments(List`1 typeArguments)
   at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(INamespaceOrTypeSymbol container, String name, List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.GetMatchingTypes(IReadOnlyList`1 containers, String name, List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseNamedSymbol(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.ParseSymbolId(List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.Parser.Parse(String id, Compilation compilation, List`1 results)
   at Microsoft.CodeAnalysis.SymbolId.GetFirstSymbolForId(String id, Compilation compilation)
   at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.DecodeSymbols(List`1 ids, Compilation compilation, List`1 symbols)
   at Microsoft.CodeAnalysis.Completion.Providers.SymbolCompletionItem.<GetSymbolsAsync>d__6.MoveNext()
```
I found a gist file which shows the same exception, but I don't know where it belongs to:
https://gist.github.com/tomasr/9a7f2997f01d4180c6618df89a12d43f

**Comment by jcouv** [comment]
Tagging @jinujoseph 
We should first try and repro on a more recent version of VS.

**Comment by jinujoseph** [comment]
@richaverma1 can you get this validated with latest 15.6 pls

**Comment by richaverma1** [comment]
I could not repro it on latest 15.6 Preview1 - d15.6  27205.0

**Comment by vsccarl** [comment]
I could not repro it on latest 15.5 preview6 -  d15svc 27130.2002

**Comment by jinujoseph** [comment]
@DiablosOffens closing this issue as this doesn't repro on latest VS

**Comment by DiablosOffens** [comment]
I read [this ](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Visual%20Studio&Filter=FilterNO) about support lifecycles, so Visual Studio 2015 with Update 3 is fully supported until 2020.
I don't understand why you only test it on the latest experimental versions and don't check the current production versions.
Is there a new 15.x release for Visual Studio 2015?
