### ISSUE TITLE
CSharpRenameTrackingCodeFixProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23640]
I keep getting this error. I cannot perform any rename operation.

System.AggregateException : One or more errors occurred. ---&gt; Unexpected false
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---&gt; (Inner Exception #0) System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VsRefactorNotifyService.TryOnBeforeGlobalSymbolRenamed(Workspace workspace,IEnumerable`1 changedDocumentIDs,ISymbol symbol,String newName,Boolean throwOnFailure)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.IRefactorNotifyServiceExtensions.TryOnBeforeGlobalSymbolRenamed(IEnumerable`1 refactorNotifyServices,Workspace workspace,IEnumerable`1 changedDocuments,ISymbol symbol,String newName,Boolean throwOnFailure)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/51508/csharprenametrackingcodefixprovider-encountered-an.html
VSTS ticketId: 429334_

**Comment by dpoeschl** [comment]
Comment from Kevin: "The callstack (A ThrowIfFalse in TryOnBeforeGlobalSymbolRenamed), looks to be coming from an inlined AssertIsForegroundThread, which means this rename is happening on a bg thread somehow?"

**Comment by CyrusNajmabadi** [comment]
Don't see any hits on this.  no reports in 5+ years.  closing out.
