### ISSUE TITLE
'CSharpAddImportCodeFixProvider' crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23658]
updated a class library in the solution.
I was busy adding all missing namespaces.
The application crashed because a file was under source control (TFS) and locked by a colleague. So it could not add the namespace to the class.
Resulting in a crash of the CSharpAddImportCodeFixProvider.

Other classes that were not checked out by my colleague were no problem.

System.AggregateException : One or more errors occurred. ---&gt; Unable to check out the files from source control.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---&gt; (Inner Exception #0) System.Exception : Unable to check out the files from source control.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments(IEnumerable`1 documents)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/160715/csharpaddimportcodefixprovider-crash.html
VSTS ticketId: 533380_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by wstaelens** [comment]
this is my original report.

**Comment by jinujoseph** [comment]
Also reported at [Link](https://developercommunity.visualstudio.com/content/problem/183670/when-applying-code-fix-cancel-file-checkout-tfvc-c.html)

**Comment by CyrusNajmabadi** [comment]
I don't see any prism hits for this.  Clsoing out as we haven't heard anything on this in 5 years.
