### ISSUE TITLE
VB: GenerateConstructorCodeFixProvider should not crash when code has semantic errors.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#23807]
**Version Used**: 

Visual Studio Community 2017 v15.5.1

**Steps to Reproduce**:

Type in the following code in a VB console project:

```vb
Public Module Module1
  Public Class Test
    Private foo As Integer
    Private bar As String

    Private baz As New Test("hh")
  End Class

  Public Sub Main()
  End Sub
End Module
```

The editor will put a red squiggle on the `"hh"` of the line `Private baz As New Test("hh")`. When you hover over the sguiggle the tooltip correctly shows the error that too many arguments have been passed to `Sub New()` but then the `GenerateConstructorCodeFixProvider` kicks in and crashes:

![vs_constructor_provider_crash](https://user-images.githubusercontent.com/20465797/34060077-37c14576-e1f3-11e7-9fb4-69aa1d145d4e.png)

If you click the Enable button in that error message near the top, then hover over the squiggly again at `"hh"`, the `GenerateConstructorCodeFixProvider` crashes. You can repeat this as many times as you want and it crashes every time. The stack trace given is:

```
System.ArgumentException : Node is not within syntax tree
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.CheckSyntaxNode(VisualBasicSyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel,SyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor.VisualBasicGenerateConstructorService.GetDelegatingConstructor(State state,SemanticDocument document,Int32 argumentCount,INamedTypeSymbol namedType,ISet`1 candidates,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateThisOrBaseDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GenerateThisOrBaseDelegatingConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.Editor.GetEditAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.GenerateConstructorCodeAction.GetEditAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`3.GenerateConstructorAsync[TService,TArgumentSyntax,TAttributeArgumentSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

**Expected Behavior**:

It should not crash. I have used the `GenerateConstructorCodeFixProvider` many times and I usually trigger it by placing the caret on a blank line within the class just after the fields/properties. In fact you can trigger it without crashing in the sample code above, if you do this by placing the caret in the blank below `Private bar As String`. However the moment you hover the cursor over the red squiggly line, it crashes.

**Comment by jcouv** [comment]
Confirmed this is an IDE problem.

When `GetSymbolInfo` is called in `GetDelegatingConstructor`, it fails because the `newTypeName.Parent` node which it received does not belong to the tree used to make the speculative semantic model.
That's because when that semantic model is created `CreateSpeculativeSemanticModelForNode`, it will use an artificial node as it's root, when we're trying to analyze a `AsNewClause`, which is the case in this scenario.

```vb
' VisualBasic.GenerateConstructor.VisualBasicGenerateConstructorService.GetDelegatingConstructor
                Dim speculativeModel = SpeculationAnalyzer.CreateSpeculativeSemanticModelForNode(oldNode, newNode, document.SemanticModel)
                If speculativeModel IsNot Nothing Then
                    Dim symbolInfo = speculativeModel.GetSymbolInfo(newTypeName.Parent, cancellationToken)
                    Return GenerateConstructorHelpers.GetDelegatingConstructor(
                        document, symbolInfo, candidates, namedType, state.ParameterTypes)
                End If
```

```vb
' CreateSpeculativeSemanticModelForNode
     Case SyntaxKind.AsNewClause
                    ' Speculation is not supported for AsNewClauseSyntax nodes.
                    ' Generate an EqualsValueSyntax node with the inner NewExpression of the AsNewClauseSyntax node for speculation.

                    Dim asNewClauseNode = DirectCast(nodeToSpeculate, AsNewClauseSyntax)
                    nodeToSpeculate = SyntaxFactory.EqualsValue(asNewClauseNode.NewExpression)
                    nodeToSpeculate = asNewClauseNode.CopyAnnotationsTo(nodeToSpeculate)
                    semanticModel.TryGetSpeculativeSemanticModel(position, DirectCast(nodeToSpeculate, EqualsValueSyntax), speculativeModel)
                    Return speculativeModel
```

Here's a test that reproes the problem:
```vb
' Public Class GenerateConstructorTests     
        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateConstructor)>
        <WorkItem(23807, "https://github.com/dotnet/roslyn/issues/23807")>
        Public Async Function TestBug() As Task
            Await TestInRegularAndScriptAsync(
"
Class Test
    Private field As New Test([|1|])
End Class
",
"")
        End Function
```

**Comment by ericmutta** [comment]
> @jcouv Confirmed this is an IDE problem.

Thanks for following up as always!

I really wish the IDE guys were here on github too, it would make it much more convenient to report bugs across the entire Visual Studio product (IDE + compilers). I have been sitting on a few bug reports since there's no place on github to post them (e.g. in v15.5.1 the menu under `File > Recent Projects and Solutions` is lazy loaded. When you open the IDE and go there, it starts off empty, making you thinking you've lost your history. You have to click away and navigate back to the menu a second time to find the list populated).

**Comment by jcouv** [comment]
@ericmutta For the problem you describe (with menu non populating properly the first time), I'd recommend you use the "Send Feedback" button in top-right corner. It allows taking and attaching screenshots, so you should be able to illustrate the empty menu.

**Comment by ericmutta** [comment]
> @jcouv I'd recommend you use the "Send Feedback" button in top-right corner.

Will do, thanks for the tip! 👍

**Comment by jinujoseph** [comment]
reported [link](https://developercommunity.visualstudio.com/content/problem/277398/rename-class.html)

**Comment by vatsalyaagrawal** [comment]
https://github.com/dotnet/roslyn/issues/23807

**Comment by ericmutta** [comment]
Thanks @JoeRobich  (and team) for finally fixing this! :+1:
