### ISSUE TITLE
CSharpRenameTrackingCodeFixProvider throws the System.NullReferenceExcpetion on the solution that contains F# library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#23889]
Hi,

I have recorded a screencast that illustrates the issue: https://www.screencast.com/t/z0rn9lvbZMcD

The probleamatic solution is attached.

Stack trace: System.AggregateException : One or more errors occurred. ---&gt; Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.ComputePreviewOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unknown Parameters&gt;)
---&gt; (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.Finders.NamedTypeSymbolReferenceFinder.DetermineDocumentsToSearchAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.CreateProjectToDocumentMapAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(&lt;Unknown Parameters&gt;)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindRenamableReferencesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.AddLocationsReferenceSymbolsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.FindAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Rename.Renamer.RenameSymbolAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolWorkerAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/166190/csharprenametrackingcodefixprovider-throws-the-sys.html
VSTS ticketId: 537049_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by AhmedAAshour** [comment]
I'm also getting the same error when renaming a property in a C# project.

Here's my stack trace:
System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> One or more errors occurred. ---> Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> One or more errors occurred. ---> Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.FindTypesFromCacheOrComputeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindImplementedInterfaceMembersAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractMethodOrPropertyOrEventSymbolReferenceFinder`1.DetermineCascadedSymbolsAsync[TSymbol](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.Finders.PropertySymbolReferenceFinder.DetermineCascadedSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_0.<DetermineAllSymbolsCoreAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.DetermineAllSymbolsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.DetermineAllSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindRenamableReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.AddLocationsReferenceSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.FindAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.Renamer.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolWorkerAsync(<Unknown Parameters>)
---> (Inner Exception #0) System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.AddSourceTypesInProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.FindTypesInProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.FindTypesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<>c__DisplayClass9_0.<FindTypesFromCacheOrComputeAsync>b__0(<Unknown Parameters>)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.ProjectIndex.CreateIndexAsync(<Unknown Parameters>)<---
<---
<---

**Comment by pulverize** [comment]
Not sure if our solution contains F#. It's pretty large and messy, so I wouldn't be surprised. But, this rename bug just started hitting me over the last few days and we definitely haven't added F# in that timeframe.

`System.AggregateException : One or more errors occurred. ---> Rename Tracking could not update solution.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.InvalidOperationException : Rename Tracking could not update solution.
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForResetOfTypedIdentifier(Workspace workspace,Solution newSolution,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
`

**Comment by dgchurchill** [comment]
This is likely the same underlying issue as https://github.com/dotnet/roslyn/issues/28474

**Comment by jinujoseph** [comment]
@jasonmalinowski  this should already be addressed via [https://github.com/dotnet/roslyn/issues/25655](url)

**Comment by jasonmalinowski** [comment]
Yeah, let's call this one complete; there might still be more bugs lurking; I don't think I'll have any confidence though those are _new_ bugs until people are using 15.8.

**Comment by rpanjwani** [comment]
happens in 2019 community for me depsite restarts:

`System.AggregateException : One or more errors occurred. ---> Changing document 'C:\projects\msgroup\mantlemapperdotnet\MantleMapperDotNet.WebCore\Views\SampleData\Sample\_ImportSample.g.cs' is not supported.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NotSupportedException : Changing document 'C:\projects\msgroup\mantlemapperdotnet\MantleMapperDotNet.WebCore\Views\SampleData\Sample\_ImportSample.g.cs' is not supported.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForGlobalIdentifierRename(Workspace workspace,Solution newSolution,Solution oldSolution,String undoName,IEnumerable`1 changedDocuments,ISymbol symbol,String newName,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
`
