### ISSUE TITLE
Quick Info over malformed code crashes Visual Studio

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#23883]
**Version Used**: 
15.6.0 Preview 1.1 [27217.0.d15.6]
15.6.0 Preview 2.0 [27206.4000.vsuvscore]

**Steps to Reproduce**:

1. Insert this code
```csharp
        void method1()
        {
            if (method2())
                .Any(b => b.ContentType, out var chars)
            {
            }
        }
```
2. Hover over `b.ContentType`

**Expected Behavior**:
Quick info shows `(parameter) ? b` over `b`
and nothing over `ContentType`

**Actual Behavior**:
Visual Studio crashes when mouse is over either `b` or `ContentType`

**Notes**

When editing code, I ended up with invalid syntax that combines extra closing parenthesis, multi line and `out var`. VS crashed when I tried to invoke completion. I noticed that it also crashes on quick info. 

The issue goes away when I remove `, out var chars` in the second line:
```csharp
if (method2())
.Any(b => b.ContentType)
```
or if the code is all in one line, 
```csharp
if (method2()).Any(b => b.ContentType, out var chars)
```

**Stack Trace**
**"This program location is thought to be unreachable."**
```
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundLambdaOrQuery(CSharpSyntaxNode lambdaOrQuery)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetEnclosingBinderInternal(CSharpSyntaxNode node, Int32 position)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetEnclosingBinderInternal(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetEnclosingBinderInternal(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbol(Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbolCore(Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetEnclosingSymbol[TSymbol](SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.<BindTokenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.<BuildContentAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.<GetQuickInfoItemAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.<GetItemAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller.<ComputeModelInBackgroundAsync>d__9.MoveNext()
```

**Comment by jcouv** [comment]
Assigned to @AlekseyTs to take a look and triage. Thanks
