### ISSUE TITLE
Scrolling down and then up in completion window in breakpoint shows "Queue empty" in MessageBox

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23891]
**Version Used**: 
Version 15.6.0 Preview 1.1 [27217.0.d15.6]

**Steps to Reproduce**:

1. File -> New -> Console App (.NET Framework)
2. Set a breakpoint 
3. Right-click on breakpoint and Conditions...
4. Check conditions
5. In expression text box, press CTRL+Space to show completion window
6. Holding down, down arrow scroll until a few pages and the top completions items are waay off screen
7. Holding down up arrow scroll back up to the top of the completion window

```
---------------------------
Microsoft Visual Studio
---------------------------
Queue empty.
---------------------------
OK   
---------------------------
```

**Comment by dpoeschl** [comment]
Repro'd for me.
```
<description>System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.MapDownToSnapshot(Span span, IProjectionSnapshot start, ITextSnapshot target)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.GetSubjectBufferTextSpanInViewBuffer(TextSpan textSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.OnModelUpdated(Model modelOpt)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AbstractController`4.Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.IController&lt;TModel&gt;.OnModelUpdated(TModel result)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.OnModelUpdated(TModel result, Boolean updateController)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.WaitForController()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.ChangeSelectionWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.ChangeSelection(Action computationAction)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.TryHandleUpKey()
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.TryHandleUpKey(UpKeyCommandArgs commandArgs)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractIntelliSenseCommandHandler.ExecuteCommand(UpKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass14_1`1.&lt;Execute&gt;b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

**Comment by JieCarolHu** [comment]
@dpoeschl I am taking this one if you don't mind, I am planning to fix it together with https://github.com/dotnet/roslyn/issues/23890

**Comment by dpoeschl** [comment]
@JieCarolHu Go for it! 😄

**Comment by JieCarolHu** [comment]
@dpoeschl  Could you re-review this pls? Thanks
It was part of this PR: https://github.com/dotnet/roslyn/pull/26119
