### ISSUE TITLE
Scrolling too far up on completion window in suggestion mode throws exception

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#23890]
Version: Version 15.6.0 Preview 1.1 [27217.0.d15.6]

1. File -> New -> Console App (.NET Framework)
2. Set a breakpoint 
3. Right-click on breakpoint and Conditions...
4. Check conditions
5. In expression text box, press CTRL+Space to show completion window
6. Press up 4 times 

![image](https://user-images.githubusercontent.com/1103906/36185931-0473309a-1190-11e8-98f2-67f9b1527261.png)

```
System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.CancellableContentControl..ctor(ToolTipProvider toolTipProvider, CustomCommitCompletion item) 
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.GetUIElement(Completion itemToRender, ICompletionSession context, UIElementType elementType) 
at Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.<>c__DisplayClass6_0`2.<FindUIElement>b__0(IUIElementProvider`2 provider) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter) 
--- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

This sometimes occurs when you scrolling the window with the keyboard and you scroll too far.

This occurs in suggestion mode wherever you use it - but gave breakpoint repro because suggestion mode is on by default in it.

**Comment by JieCarolHu** [comment]
@jinujoseph I tested on 27328.0.d15.6, the completion window never appears after I press CTRL+Space. Do we have a separate bug to track this issue?

**Comment by miloush** [comment]
I believe I hit this in 15.6.0 Preview 4:
```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.CancellableContentControl..ctor(ToolTipProvider toolTipProvider, CustomCommitCompletion item)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.GetUIElement(Completion itemToRender, ICompletionSession context, UIElementType elementType)
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.<>c__DisplayClass6_0`2.<FindUIElement>b__0(IUIElementProvider`2 provider)
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)
```

Not 100% sure but I think it was the autocompletion in immediate window.

**Comment by JieCarolHu** [comment]
I tested on build 27411 and the issue seems fixed already. The completion windows shows and works properly. No errors or exceptions after I press Up key >10 times.
@miloush @davkean Could you please update to the latest build and try again? Thanks!

![image](https://user-images.githubusercontent.com/17056651/36171135-4b753478-10b6-11e8-9c8c-c5dff3afdad1.png)

**Comment by davkean** [comment]
@JieCarolHu I can still repro this on VisualStudio.15.IntPreview/15.6.0-pre.5.0+27411.0.d15.6 with same stack:
```
    <record>1883</record>
    <time>2018/02/14 02:58:22.894</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.CancellableContentControl..ctor(ToolTipProvider toolTipProvider, CustomCommitCompletion item)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.GetUIElement(Completion itemToRender, ICompletionSession context, UIElementType elementType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.&lt;&gt;c__DisplayClass6_0`2.&lt;FindUIElement&gt;b__0(IUIElementProvider`2 provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
</activity>
```

**Comment by davkean** [comment]
Be sure to follow the repro instructions exactly, my screen shot was a little wrong - notice I'm at the top of the completion window. I've updated the screen shot.

**Comment by JieCarolHu** [comment]
Thanks, I am able to repro it now :) 
I need to keep on pressing the Up key until the highlight reaches the very top space in the completion window. I will look into it.
