### ISSUE TITLE
Microsoft CodeAnalysis OOM Exception 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#24055]
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1503

-----------------------------
@chillryan

I've reported this issue through the visual studio feedback tool [see link](https://developercommunity.visualstudio.com/content/problem/174842/visual-studio-155-crashes-when-switching-git-branc.html) but figured I'd try my chances posting here.

I'm using the Code Analysis 2017 extension for VS 2017 15.5. In looking at the stack trace, I can only assume that since the extension is running inside the devenv process, when its analysis a loaded solution, it hits the OOM. 

Since I've hit this situation a very frequent basis, I've disabled solution analysis for C# projects hoping that will help. I'll report back here if there are any changes or comment on the visual studio feedback link posted prior.

**Comment by mavasani** [comment]
@sharwell @heejaechang - Do we have a tracking issue for our memory usage drastically increasing on switching git branches? The feedback link mentions switching git branches as the major culprit. I have seen it very often while working on Roslyn as well.

**Comment by heejaechang** [comment]
I think it probably the same tagger issue since switching git branch will cause a lot of document to be changed causing a lot of files to be re-analyzed, raising a lot of diagnostic changed events, all pushed into UI queue and OOM.

**Comment by sharwell** [comment]
@heejaechang I reviewed the heap dump and can confirm that this is the `PendingWork` bug.

**Comment by sharwell** [comment]
@chillryan I just reviewed your feedback history. Several items have comments linking back to an internal bug we refer to as the "`PendingWork`" bug. When this is fixed, you should see many of your feedback items close afterwards and the improvement should be substantial.

**Comment by chillryan** [comment]
@sharwell thanks for update.

**Comment by sharwell** [comment]
@chillryan Not specifically. If so, most of them were filed by you. 😆 There were multiple proposed solutions which are in the final evaluation stage. I'll link whichever one we settle on back to this issue.

**Comment by udlose** [comment]
@sharwell - Can you confirm if the attached file is related to the same issue?

[devenv.exe__PID__62124__Date__01_10_2018__Time_10_51_38AM__41__Manual Dump_MultipleRules.zip](https://github.com/dotnet/roslyn/files/1619811/devenv.exe__PID__62124__Date__01_10_2018__Time_10_51_38AM__41__Manual.Dump_MultipleRules.zip)

**Comment by sharwell** [comment]
@udlose I would need a full heap dump to confirm. Better to just submit a new feedback ticket. Feel free to mention that it should be directed to me for initial investigation. 😄

**Comment by udlose** [comment]
@sharwell - new defect is at [VS Crash with OutOfMemoryException](https://developercommunity.visualstudio.com/content/problem/180410/vs-crash-with-outofmemoryexception.html)

**Comment by sharwell** [comment]
> There are 11,299,087 instances of Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.PendingWork

That's definitely the same bug. This situation results a large amount of unnecessary computation that has ramifications vastly exceeding the size of the list itself.

**Comment by udlose** [comment]
is there native code used by those `PendingWork `classes?  It's curious to see the native heap at 2.5GB...

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/pull/23448

**Comment by udlose** [comment]
@jinujoseph what release number of VS will this be included in?

**Comment by jinujoseph** [comment]
15.6 Preview 4 onward

**Comment by Panoone** [comment]
I only started experiencing this problem today - with all projects - despite having no problem with VS Pro 2017 for months. I tried upgrading to 15.5.6 with no success.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.TypeLoadException: Could not load type 'System.Security.Cryptography.IncrementalHash' from assembly 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.CodeAnalysis.Checksum.Create(Stream stream)
   at Microsoft.CodeAnalysis.Execution.AbstractReferenceSerializationService.CreateChecksum(AnalyzerReference reference, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Serialization.Serializer.CreateChecksum(Object value, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.RemoteHostClientService.AddGlobalAssets(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.RemoteHostClientService.<EnableAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.RemoteHostClientExtensions.<SynchronizePrimaryWorkspaceAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.NormalPriorityProcessor.<ResetStatesAsync>d__37.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor+<ResetStatesAsync>d__37.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor+<ResetStatesAsync>d__37.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor+<ResetStatesAsync>d__37, Microsoft.CodeAnalysis.Features, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ResetStatesAsync>d__37 ByRef)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor.ResetStatesAsync()
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor+<ExecuteAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor+<ExecuteAsync>d__17, Microsoft.CodeAnalysis.Features, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ExecuteAsync>d__17 ByRef)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+NormalPriorityProcessor.ExecuteAsync()
   at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor+<ProcessAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>)
   at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor+<WaitForIdleAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.Task+DelayPromise.Complete()
   at System.Threading.Tasks.Task+<>c.<Delay>b__274_1(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

Followed by:

Faulting application name: devenv.exe, version: 15.0.27130.2010, time stamp: 0x5a31e4ea
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80131623
Fault offset: 0x2d6b5fba
Faulting process ID: 0x3668
Faulting application start time: 0x01d399754ad12c19
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
Faulting module path: unknown
Report ID: c9e71bbf-bb95-4e6d-b46a-c1e27109804e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by CyrusNajmabadi** [comment]
@Panoone That appears to be a different issue.  It's not an OOM, but rather a type-load failure.

**Comment by udlose** [comment]
@Panoone i had a fellow dev hit that same problem. The fix was to install .net 4.7.1. For some reason it's looking for those assemblies. Once it was installed, the problem was solved.

**Comment by Panoone** [comment]
@udlose Thanks, Dave. I'll give it a go. There was a significant Windows 10 update last night and I'm assuming something in that was the culprit.

**Comment by Panoone** [comment]
@udlose Yep, upgrading .NET Framework resolved the issue. Thanks again.
