### ISSUE TITLE
[Flaky] ProduceErrorsOnRef_Properties_Ref_Set test

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#24182]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_16_debug_prtest/8403/

```
    Microsoft.CodeAnalysis.CSharp.UnitTests.DeclarationParsingTests.ProduceErrorsOnRef_Properties_Ref_Set [FAIL]
17:56:01       
17:56:01       Expected:
17:56:01                       Diagnostic(ErrorCode.ERR_BadMemberFlag, "set").WithArguments("ref").WithLocation(6, 13)
17:56:01       Actual:
17:56:01 
                      // error CS0009: Metadata file 'mscorlib.dll (netstandard 2.0 ref)' could not be opened -- Invalid argument
17:56:01                       Diagnostic(ErrorCode.FTL_MetadataCantOpenFile).WithArguments("mscorlib.dll (netstandard 2.0 ref)", "Invalid argument").WithLocation(1, 1),
17:56:01                       // (6,13): error CS0106: The modifier 'ref' is not valid for this item
17:56:01                       //         ref set => throw null;
17:56:01                       Diagnostic(ErrorCode.ERR_BadMemberFlag, "set").WithArguments("ref").WithLocation(6, 13)
17:56:01       Diff:
17:56:01       ++>                 Diagnostic(ErrorCode.FTL_MetadataCantOpenFile).WithArguments("mscorlib.dll (netstandard 2.0 ref)", "Invalid argument").WithLocation(1, 1),
17:56:01                           Diagnostic(ErrorCode.ERR_BadMemberFlag, "set").WithArguments("ref").WithLocation(6, 13)
17:56:01       Expected: True
17:56:01       Actual:   False
17:56:01       Stack Trace:
17:56:01         /_/src/Test/Utilities/Portable/Diagnostics/DiagnosticExtensions.cs(91,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
17:56:01         /_/src/Test/Utilities/Portable/Diagnostics/DiagnosticExtensions.cs(46,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
17:56:01         /_/src/Test/Utilities/Portable/Diagnostics/DiagnosticExtensions.cs(61,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
17:56:01         /_/src/Test/Utilities/Portable/Diagnostics/DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
17:56:01         /_/src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs(6391,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.DeclarationParsingTests.ProduceErrorsOnRef_Properties_Ref_Set()
```

**Comment by drognanar** [comment]
Might be related to:
#23042
https://ci.dot.net/job/dotnet_roslyn/job/dev15.5.x/job/ubuntu_14_debug/92/
https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_16_debug/1472/
