### ISSUE TITLE
Null Ref sometimes when calling AddProject on our test automation machine.  Race condition?

### ISSUE THREAD

**Issue by lhfiedler** [dotnet/roslyn#24260]
**Version Used**: 
2.6.1

Stack:

```
System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService..ctor(IGlobalOptionService globalOptionService, HostWorkspaceServices workspaceServices)
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.CreateService(HostWorkspaceServices workspaceServices)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.Workspace.get_Options()
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService..ctor(HostLanguageServices languageServices)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CreateLanguageService(HostLanguageServices provider)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
   at Microsoft.CodeAnalysis.ProjectState.FixProjectInfo(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.ProjectState..ctor(ProjectInfo projectInfo, HostLanguageServices languageServices, SolutionServices solutionServices)
   at Microsoft.CodeAnalysis.SolutionState.AddProject(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.AdhocWorkspace.AddProject(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.AdhocWorkspace.AddProject(String name, String language)
```

**Steps to Reproduce**:

```csharp
CompositionHost compositionContext = new ContainerConfiguration()
    .WithParts(partTypes)
    .CreateContainer();

MefHostServices host = MefHostServices.Create(compositionContext);

var workspace = new AdhocWorkspace(host);

var project = workspace
    .AddProject("CodeProject", ProjectLanguage(language))
    .WithMetadataReferences(MetaDataReferences());
```

Can you guys check if there's a race condition your code?

**Comment by sharwell** [comment]
@lhfiedler I recently tried to enable concurrent testing of StyleCop Analyzers using independent MEF containers similar to what you showed. I ran into many problems with the approach and was finally convinced that there is no reasonable way to enable concurrency in this manner.

However, as a second approach I tried switching from MEF 2 to VS MEF as the container host, and found a completely different result. The following pull request shows how I converted the test suite from sequential to parallel:

DotNetAnalyzers/StyleCopAnalyzers#2737

**Comment by sharwell** [comment]
Resolving as **External** since the bug appears to originate in MEF 2 (part of [dotnet/corefx](https://github.com/dotnet/corefx)).

**Comment by lhfiedler** [comment]
So we should be using MefV1HostServices instead of MefHostServices for creating truly isolated hosts?  What's the difference?

**Comment by sharwell** [comment]
@lhfiedler `MefV1HostServices` is used for convenience, but it's not really the "solution". The main difference is the use of `Microsoft.VisualStudio.Composition.IExportProviderFactory`. The `AsExportProvider` extension method makes the resulting `ExportProvider` *look* like a MEF v1 export provider, but the implementation is completely different. `MefV1HostServices` is the easiest way to connect Roslyn's `HostServices` to vs-mef's `ExportProvider`.

**Comment by jasonmalinowski** [comment]
Reactivating to investigate whether there's a bug in Roslyn or a bug in MEF, and if so to get a proper bug filed on that team.

**Comment by CyrusNajmabadi** [comment]
Closing as these scenarios were rewritten and we haven't heard anything about this in 6 years.
