### ISSUE TITLE
ConditionalAccessOffConstrainedTypeParameter_Field

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#24479]
Currently seeing these two failures

**Version Used**: 
`Microsoft (R) Visual C# Compiler version 2.7.0.62518 (d0445909)`

```
 Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalAccessOffConstrainedTypeParameter_Field
Roslyn.Test.Utilities.ExecutionException : \r\nExecution failed for assembly ''.\r\nExpected: \r\n636461511000000000\r\n636461511000000000\r\nFalse\r\n\r\nActual:   636461799000000000\r\n636461799000000000\r\nFalse\r\n\r\n
   at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\Platform\Desktop\DesktopRuntimeEnvironment.cs:line 245
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CompilationVerifier.cs:line 104
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 235
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 149
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(IEnumerable`1 sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 99
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 61
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 80
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalAccessOffConstrainedTypeParameter_Field() in D:\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs:line 7487
0.0176673s
```

``` ✘Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalAccessOffConstrainedTypeParameter_Property
Roslyn.Test.Utilities.ExecutionException : \r\nExecution failed for assembly ''.\r\nExpected: \r\n636461511000000000\r\n636461511000000000\r\nFalse\r\n\r\nActual:   636461799000000000\r\n636461799000000000\r\nFalse\r\n\r\n
   at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\Platform\Desktop\DesktopRuntimeEnvironment.cs:line 245
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CompilationVerifier.cs:line 104
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 235
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 149
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(IEnumerable`1 sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 99
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Test\Utilities\Portable\CommonTestBase.cs:line 61
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, ParseOptions parseOptions, EmitOptions emitOptions, Verification verify) in D:\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 80
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalAccessOffConstrainedTypeParameter_Property() in D:\roslyn-AdamSpeight2008\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs:line 7436
```

**Comment by jcouv** [comment]
I've seen such errors in the past (typically in greater numbers though) due to how git checked out files.

**Comment by AdamSpeight2008** [comment]
@jcouv It is confusing to me as I'm not touching the csharp code.

**Comment by alrz** [comment]
I think this is fixed in https://github.com/dotnet/roslyn/pull/24323

**Comment by AdamSpeight2008** [comment]
Rebased onto latest commit, failures gone.
