### ISSUE TITLE
Analyzer written in C# throws NotSupportedException on VB UnitTest

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#2462]
Repro steps:
- In VS2015 RC, create new project: Visual C#, Extensibility, Analyzer with Code Fix
- On the generated analyzer class, replace existing attribute with:
    `[DiagnosticAnalyzer(LanguageNames.CSharp, LanguageNames.VisualBasic)]`
- In generated file UnitTests.cs, override `GetBasicDiagnosticAnalyzer` and return same analyzer
- In the same file, add a test with some enquoted VB code and call `VerifyBasicDiagnostic(text);`

Expected:
Run the test and verify that no diagnostics are triggered.

Actual:
System.NotSupportedException: The language 'Visual Basic' is not supported.

Result StackTrace:	
at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetLanguageServices(String languageName)
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetLanguageServices(String languageName)
   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo)
   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectId projectId, String name, String assemblyName, String language)
   at TestHelper.DiagnosticVerifier.CreateProject(String[] sources, String language) in D:\Bart\Documents\Visual Studio 2015\Projects\Analyzers\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs.Test\Helpers\DiagnosticVerifier.Helper.cs:line 158
   at TestHelper.DiagnosticVerifier.GetDocuments(String[] sources, String language) in D:\Bart\Documents\Visual Studio 2015\Projects\Analyzers\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs.Test\Helpers\DiagnosticVerifier.Helper.cs:line 123
   at TestHelper.DiagnosticVerifier.GetSortedDiagnostics(String[] sources, String language, DiagnosticAnalyzer analyzer) in D:\Bart\Documents\Visual Studio 2015\Projects\Analyzers\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs.Test\Helpers\DiagnosticVerifier.Helper.cs:line 42
   at TestHelper.DiagnosticVerifier.VerifyDiagnostics(String[] sources, String language, DiagnosticAnalyzer analyzer, DiagnosticResult[] expected) in D:\Bart\Documents\Visual Studio 2015\Projects\Analyzers\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs.Test\Verifiers\DiagnosticVerifier.cs:line 90
   at TestHelper.DiagnosticVerifier.VerifyBasicDiagnostic(String source, DiagnosticResult[] expected) in D:\Bart\Documents\Visual Studio 2015\Projects\Analyzers\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs\ReadonlyFieldsInStructs.Test\Verifiers\DiagnosticVerifier.cs:line 55

**Comment by bkoelman** [comment]
The problem disappeared after I manually added the next lines to Test\packages.config:

    <package id="Microsoft.CodeAnalysis.VisualBasic" version="1.0.0-rc2" targetFramework="net45" userInstalled="true" />
    <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="1.0.0-rc2" targetFramework="net45" userInstalled="true" />

And the next lines to Test.csproj file:

    <Reference Include="Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.CodeAnalysis.VisualBasic.1.0.0-rc2\lib\net45\Microsoft.CodeAnalysis.VisualBasic.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.VisualBasic.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.CodeAnalysis.VisualBasic.1.0.0-rc2\lib\net45\Microsoft.CodeAnalysis.VisualBasic.Desktop.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.CodeAnalysis.VisualBasic.Workspaces.1.0.0-rc2\lib\net45\Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.CodeAnalysis.VisualBasic.Workspaces.1.0.0-rc2\lib\net45\Microsoft.CodeAnalysis.VisualBasic.Workspaces.Desktop.dll</HintPath>
      <Private>True</Private>
    </Reference>

**Comment by jmarolf** [comment]
We don't add VB references to C# analyzer projects, and we don't add C# to VB projects.  Is this proposal change that so that the C# analyzer has both?

**Comment by bkoelman** [comment]
Yes that would feel more consistent to me as an API consumer. To have both refecences in both project types. After all, everything else is in place for a single analyzer to target both languages. 

The C# project template contains C# generated code that exposes both methods (`GetBasicDiagnosticAnalyzer()` and `GetCSharpDiagnosticAnalyzer`), while the VB project template exposes these same methods (but written in VB code).

If the general guidance is to always make separate analyzers per language, then I think no helper code should be in the project template for both languages, because that suggests they can be mixed.

**Comment by srivatsn** [comment]
We could add the C#\VB references to the test projects. I don't think we want to do that for the analyzer projects because then that leads to loading the VB dlls in a C# project unnecessarily.

**Comment by bkoelman** [comment]
@srivatsn Sounds like a good solution if that solves the "Language not supported" exception. 

The thing is, only after creating a VB Analyzer project and running a file-system diff I discovered which additional references / package imports were needed.

Users that do not have VB installed have no clue how the resolve this error. I believe a better exception message would help, or a simple explanation comment on the templated `[DiagnosticAnalyzer(LanguageNames.CSharp)]`, for example describing which package imports are needed for VB/C# support.

**Comment by jmarolf** [comment]
Fixed with internal changeset  1474285

**Comment by jmarolf** [comment]
@srivatsn  could you please verify?
