### ISSUE TITLE
2.6.1: NullReferenceException in BatchFixAllProvider

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#24653]
**Version Used**: 

Microsoft.CodeAnalysis v2.6.1, running on .NET Framework 4.7.1

**Steps to Reproduce**:

This is tricky - I have a program (not open-source) that applies code fixes across large amounts of solutions.

When upgrading it from Roslyn 2.2 to Roslyn 2.6.1, I encountered this exception.

**Expected Behavior**:

Program works as it used to.

**Actual Behavior**:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryAddDocumentMergeChangesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFinalDocumentTextAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetDocumentIdToFinalTextAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryMergeFixesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryGetMergedFixAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.CodeFixEquivalenceGroup.<GetOperationsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.SolutionProcessor.<ApplyFixesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.SolutionProcessor.<ProcessSolutionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.Processor.<ProcessAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<MainAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<Main>(String[] args)
```

Or, simplified:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryAddDocumentMergeChangesAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFinalDocumentTextAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetDocumentIdToFinalTextAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryMergeFixesAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryGetMergedFixAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync
   at WTG.BulkAnalysis.Core.CodeFixEquivalenceGroup.GetOperationsAsync
   at WTG.BulkAnalysis.Core.SolutionProcessor.ApplyFixesAsync
   at WTG.BulkAnalysis.Core.SolutionProcessor.ProcessSolutionAsync
   at WTG.BulkAnalysis.Core.Processor.ProcessAsync
   at WTG.BulkAnalysis.Runner.Program.MainAsync
   at WTG.BulkAnalysis.Runner.Program.Main(String[] args)
```

`CodeFixEquivalenceGroup.GetOperationsAsync` looks like this:

```
public async Task<ImmutableArray<CodeActionOperation>> GetOperationsAsync(CancellationToken cancellationToken)
{
    var diagnostic = documentDiagnosticsToFix
        .Values
        .SelectMany(i => i.Values)
        .Concat(projectDiagnosticsToFix.Values)
        .First()
        .First();

    var document = solution.GetDocument(diagnostic.Location.SourceTree);

    var diagnosticIds = new HashSet<string>(
        documentDiagnosticsToFix
            .Values
            .SelectMany(i => i.Values)
            .Concat(projectDiagnosticsToFix.Values)
            .SelectMany(i => i)
            .Select(j => j.Id));

    var diagnosticsProvider = new TesterDiagnosticProvider(
        documentDiagnosticsToFix,
        projectDiagnosticsToFix);

    var context = new FixAllContext(
        document,
        codeFixProvider,
        FixAllScope.Solution,
        codeFixEquivalenceKey,
        diagnosticIds,
        diagnosticsProvider,
        cancellationToken);

    var action = await fixAllProvider
        .GetFixAsync(context)
        .ConfigureAwait(false);

    return await action
        .GetOperationsAsync(cancellationToken)
        .ConfigureAwait(false);
}
```

`fixAllProvider` comes from `Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider.GetFixAllProvider()`.

The cause of the crash appears to be that `differenceService` is null [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,400).

**Comment by CyrusNajmabadi** [comment]
Are you running in VS?

**Comment by CyrusNajmabadi** [comment]
This is def strange given that we should always have a default export for this at the workspace layer:

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LinkedFileDiffMerging/DefaultDocumentTextDifferencingService.cs,13

```c#
    [ExportWorkspaceService(typeof(IDocumentTextDifferencingService), ServiceLayer.Default), Shared]
    internal class DefaultDocumentTextDifferencingService : IDocumentTextDifferencingService
```

**Comment by yaakov-h** [comment]
No, this is a command-line application running outside of VS.

It crashes both standalone and also when run as a child process with the debugger attached.

**Comment by brian-reichle** [comment]
I created a repository with a simple(-ish) demonstration of the issue.

https://github.com/brian-reichle/Issue-Demonstration-24653

The Roslyn2.2 branch works fine, but the Roslyn2.3 and Roslyn2.6.1 branches get the NullReferenceException.

**Comment by yaakov-h** [comment]
@CyrusNajmabadi Any idea why differenceService would be null in the repro above?

![image](https://user-images.githubusercontent.com/426009/36364188-ba73fb04-1596-11e8-88a2-b7a856894e14.png)

**Comment by CyrusNajmabadi** [comment]
Nope.  no clue.  someone will have to debug. There should always be a differencing service.

**Comment by yaakov-h** [comment]
Seems to have been resolved by accident then. Closing...
