### ISSUE TITLE
CompositionFailedException when using RoslynDev in 15.6

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#24720]
**Version Used**:  Visual Studio 15.6 preview 4 (happened on preview 3 as well; don't know before that)

When I run VisualStudioSetup/Next or just build and run RoslynDev in 15.6 and open a C# project, I keep getting this exception:
```c#
Microsoft.VisualStudio.Composition.CompositionFailedException
  HResult=0x80131500
  Message=Expected 1 export(s) with contract name "Microsoft.VisualStudio.Text.Editor.Commanding.IEditorCommandHandlerServiceFactory" but found 0 after applying applicable constraints.
  Source=Microsoft.VisualStudio.Composition
  StackTrace:
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter..ctor(ITextView textView, ITextBuffer subjectBuffer, IOleCommandTarget nextCommandTarget)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceFilter.EnsureCommandHandlerServiceAdapter()
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceFilter.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerQueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.QueryVisualStudio2000Status(Guid& pguidCmdGroup, UInt32 commandCount, OLECMD[] prgCmds, IntPtr commandText) in C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\AbstractOleCommandTarget.Query.cs:line 208
   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.QueryStatus(Guid& pguidCmdGroup, UInt32 commandCount, OLECMD[] prgCmds, IntPtr commandText) in C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\AbstractOleCommandTarget.Query.cs:line 30
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerQueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.QueryStatus(Guid& pguidCmdGroup, UInt32 commandCount, OLECMD[] prgCmds, IntPtr commandText)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.QueryStatus(Guid& pguidCmdGroup, UInt32 cCmds, OLECMD[] prgCmds, IntPtr pCmdText)

[External Code]
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.QueryVisualStudio2000Status(ref System.Guid pguidCmdGroup, uint commandCount, Microsoft.VisualStudio.OLE.Interop.OLECMD[] prgCmds, System.IntPtr commandText) Line 208
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\AbstractOleCommandTarget.Query.cs(208)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.QueryStatus(ref System.Guid pguidCmdGroup, uint commandCount, Microsoft.VisualStudio.OLE.Interop.OLECMD[] prgCmds, System.IntPtr commandText) Line 30
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\AbstractOleCommandTarget.Query.cs(30)
[External Code]
```

It keeps constantly getting thrown. If I try to ignore it, VS is completely unusable, it won't allow me to type (but I can navigate). I will even get the exception message when trying to close VS so I have to use task manager at that point. 

This does **not** happen with 15.5.

Before that, I also get this (don't know if related) one-time exception:
```c#
Managed Debugging Assistant 'LoaderLock' 
  Message=Managed Debugging Assistant 'LoaderLock' : 'Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'

[External Code]
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService<Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpPackage, Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpLanguageService>.GetServices() Line 154
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractLanguageService`2.cs(154)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService<Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpPackage, Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpLanguageService>.Setup() Line 96
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractLanguageService`2.cs(96)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage<Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpPackage, Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpLanguageService>.Initialize.AnonymousMethod__9_0() Line 51
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractPackage`2.cs(51)
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage<Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpPackage, Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpLanguageService>.RegisterLanguageService.AnonymousMethod__0(System.ComponentModel.Design.IServiceContainer container, System.Type type) Line 130
	at C:\Users\neme1\Source\Repos\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractPackage`2.cs(130)
[External Code]
```

**Comment by jasonmalinowski** [comment]
@Neme12 Which branch are you using?

**Comment by Neme12** [comment]
@jasonmalinowski master

**Comment by jasonmalinowski** [comment]
Hmm...that code shouldn't be in that branch. Try a full rebuild to see if that clears it up.

The LoaderLock thing is unrelated but known.

**Comment by Neme12** [comment]
@jasonmalinowski  It's working now. I have no idea what changed. I did a lot of rebuilds and restores before including deleting the Binaries folder and even the whole repo. Now it worked.

**Comment by Neme12** [comment]
Now I'm getting this in my regular install too after upgrading to 15.6 (which I very much regret).

**Comment by Neme12** [comment]
Building the Roslyn project seems to do the trick.
