### ISSUE TITLE
A linq error: System.Data.SqlClient.SqlException (0x80131904)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#24777]
A linq like this:

```csharp
var ss = from a in dbContext.comm_work
					 from part in dbContext.class_class.Where(x => x.child == a.partid).DefaultIfEmpty()
					 from czy in dbContext.usergl_czy.Where(x => x.czyid == a.czyid).DefaultIfEmpty()
					 from spczy in dbContext.usergl_czy.Where(x => x.czyid == a.shenpiczyid).DefaultIfEmpty()
					 from node in dbContext.comm_shenpinode.Where(x => x.id == a.shenpizt).DefaultIfEmpty()
					 where a.xh == info.QueryCondition.Xhs
					 select new
					 {
						 #region MyRegion
						 a,
						 part = new
						 {
							 part.child,
							 part.childname
						 },
						 czy = new
						 {
							 czy.czyid,
							 czy.czybm,
							 czy.czy
						 },
						 shenpiczy = new
						 {
							 spczy.czyid,
							 spczy.czybm,
							 spczy.czy
						 },
						 node = new
						 {
							 node.id,
							 node.mc
						 }
						 #endregion
					 };

			var lst_ss = ss.ToList();
```

a error happied:

```
{System.Data.SqlClient.SqlException (0x80131904): 无法绑定由多个部分组成的标识符 "a.shenpizt"。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
```

but i change the linq order ,like this below,it is normal :

```csharp
var ss = from a in dbContext.comm_work
					 from part in dbContext.class_class.Where(x => x.child == a.partid).DefaultIfEmpty()
					 from node in dbContext.comm_shenpinode.Where(x => x.id == a.shenpizt).DefaultIfEmpty()
					 from czy in dbContext.usergl_czy.Where(x => x.czyid == a.czyid).DefaultIfEmpty()
					 from spczy in dbContext.usergl_czy.Where(x => x.czyid == a.shenpiczyid).DefaultIfEmpty()
					 where a.xh == info.QueryCondition.Xhs
					 select new
					 {
						 #region MyRegion
						 a,
						 part = new
						 {
							 part.child,
							 part.childname
						 },
						 node = new
						 {
							 node.id,
							 node.mc
						 },
						 czy = new
						 {
							 czy.czyid,
							 czy.czybm,
							 czy.czy
						 },
						 shenpiczy = new
						 {
							 spczy.czyid,
							 spczy.czybm,
							 spczy.czy
						 }
						 #endregion
					 };

			var lst_ss = ss.ToList();
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/156123/a-linq-error-systemdatasqlclientsqlexception-0x801.html
VSTS ticketId: 529808_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jaredpar** [comment]
Closing as this doesn't appear to be a C# compiler bug but rather in the SQL data layer.
