### ISSUE TITLE
TestPeekDefinitionFromVisualBasicMetadataAsSource: Null ref in dispose

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25093]
```
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionFromVisualBasicMetadataAsSource
      System.Exception : 1 exception(s) were thrown during test.
      Note: exceptions may have been thrown by another test running concurrently with
      this test.  This can happen with any tests that share the same ExportProvider.
      Examining individual exception stacks may help reveal the original test and source 
      of the problem.
      
      Exception 0:
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)
         at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
         at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
      
      
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Dispose(Boolean finalize)
           at Microsoft.CodeAnalysis.Workspace.Dispose()
           at Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionFromVisualBasicMetadataAsSource()
        ----- Inner Stack Trace -----
           at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)
           at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)
```

Possibly the same issue as https://github.com/dotnet/roslyn/issues/20370, but I'm not 100% sure so I'm opening a new issue. Failed in 15.6.x-vs-deps https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.6.x-vs-deps/job/windows_debug_unit64/37/.

**Comment by Shyam-Gupta** [comment]
Happened again today: https://ci.dot.net/job/dotnet_roslyn/job/dev15.7-preview1-vs-deps/job/windows_debug_unit64_prtest/7/

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't happened in 6 years.
