### ISSUE TITLE
SQLitePersistentStorageTests.PersistentService_Document_WriteReadSameInstance failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25114]
Seen once during a merge pr from master->master-vs-deps (https://github.com/dotnet/roslyn/pull/25092). Test run is here: https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_debug_unit64_prtest/216/. @CyrusNajmabadi, any chance you have any ideas as to what could cause this?

Stack:
```
    Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.SQLitePersistentStorageTests.PersistentService_Document_WriteReadSameInstance
      Assert.Equal() Failure
                                        (pos 2197)
      Expected: Â·Â·Â· ESENT,Goodbye ESENT,Goodbye ESENT,Goodbye ESENT,Goodbye ESENÂ·Â·Â·
      Actual:   Â·Â·Â· ESENT,Goodbye ESENT
                                        (pos 2197)
      Stack Trace:
           at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Document_WriteReadSameInstance>d__28.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<PersistentService_Document_WriteReadSameInstance>d__27.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by 333fred** [comment]
Failed in the signed build as well: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1440679&tab=ms.vss-test-web.test-result-details&_a=summary

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't been hit again and we're on sqlite now.
