### ISSUE TITLE
CSharpEncapsulateField.EncapsulateThroughCommand Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25120]
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpEncapsulateField.EncapsulateThroughCommand
      System.Windows.Automation.ElementNotAvailableException : Unrecognized error.
      Stack Trace:
           at MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
           at MS.Internal.Automation.UiaCoreApi.UiaGetUpdatedCache(SafeNodeHandle hnode, UiaCacheRequest request, NormalizeState normalize, Condition customCondition)
           at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.FindDialogByPropertyWorker(Int32 visualStudioHWnd, String propertyValue, AutomationProperty nameProperty)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.FindDialogByNameWorker(Int32 visualStudioHWnd, String dialogName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.<>c__DisplayClass2_0.<FindDialogByName>b__0()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.Retry[T](Func`1 action, Func`2 stoppingCondition, TimeSpan delay)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.FindDialogByName(Int32 visualStudioHWnd, String dialogName, Boolean isOpen)
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpEncapsulateField.cs(43,0): at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpEncapsulateField.EncapsulateThroughCommand()
```
Failed on this line: https://github.com/dotnet/roslyn/blob/6b99a66af076f94ce05bfb6c8a3b2c36e95f6f20/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpEncapsulateField.cs#L43

Screenshot:
![image](https://user-images.githubusercontent.com/2371880/36806409-c96a5b96-1c74-11e8-93fb-c9db2310ab8c.png)

**Comment by 333fred** [comment]
Failed again, https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration/1976/. @jinujoseph can someone look at this, 2 hits in 2 days?
