### ISSUE TITLE
VisualBasicSnippetInfoService is failing MEF cache for 15.7

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25212]
15.7.0 Preview 1.0 [27501.3002.d15.7stg]

```
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.VisualStudio.LanguageServices.VisualBasic.Snippets.VisualBasicSnippetInfoService". ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.PartDiscovery.GetElementTypeFromMany(Type type)
   at Microsoft.VisualStudio.Composition.PartDiscovery.GetTypeIdentityFromImportingType(Type type, Boolean importMany)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscovery.TryCreateImportDefinition(Type importingType, ICustomAttributeProvider member, ImmutableHashSet`1 importConstraints, ImportDefinition& importDefinition)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscovery.CreateImport(ParameterInfo parameter, ImmutableHashSet`1 importConstraints)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass27_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace 
```

**Comment by heejaechang** [comment]
it doesnt repro with 27505.3000 d15.7stg and the drop used here no longer exist on cpvsbuild.

closing as not repro.

**Comment by davkean** [comment]
VisualBasicSnippetInfoService is marked with an ImportMany its constructor for a non-collection type, which is very likely the cause:

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/VisualBasic/Impl/Snippets/VisualBasicSnippetInfoService.vb#L21

**Comment by davkean** [comment]
Which was changed in this PR: https://github.com/dotnet/roslyn/pull/24512 at the end of Jan.

**Comment by heejaechang** [comment]
yes. it is a bug. thank you for finding it. not sure why snippet works though in d15.7stg..

**Comment by heejaechang** [comment]
I see it in MEF error log but VS runs fine... interesting. anyway, thank you for reopening the issue!

**Comment by jinujoseph** [comment]
fixed via https://github.com/dotnet/roslyn/pull/25361
