### ISSUE TITLE
AbstractGenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider failure in the MEF cache for 15.7

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25211]
15.7.0 Preview 1.0 [27501.3002.d15.7stg]

```
Error #1
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.AbstractGenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider". ---> System.InvalidOperationException: No importing constructor found.
   at Microsoft.Verify.Operation(Boolean condition, String message)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass27_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace ---
```

**Comment by CyrusNajmabadi** [comment]
It's an abstract class:

```c#
 internal abstract partial class AbstractGenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider : AbstractGenerateFromMembersCodeRefactoringProvider
```

Why is MEF trying to find an importing constructor for it?

**Comment by davkean** [comment]
https://github.com/dotnet/roslyn/blob/3678d5345745f1853607afedbf0efcbaec04aaac/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs#L22
