### ISSUE TITLE
ChangeSignatureDialog integration test failures

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25230]
Seen a few failures from different unit tests, all with the same stack:
```
System.Windows.Automation.ElementNotAvailableException: Element not available ---> System.Runtime.InteropServices.COMException: An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
   at UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at System.Windows.Automation.AutomationElement.GetCurrentPropertyValue(AutomationProperty property, Boolean ignoreDefaultValue)
   --- End of inner exception stack trace ---
   at System.Windows.Automation.AutomationElement.GetCurrentPropertyValue(AutomationProperty property, Boolean ignoreDefaultValue).GetType().Name
   at System.Windows.Automation.AutomationElement.GetCurrentPropertyValue(AutomationProperty property, Boolean ignoreDefaultValue)
```
Failed tests that I've seen: CSharpChangeSignatureDialog.VerifyRemoveParameter, BasicChangeSignatureDialog.VerifyReorderParameters
Links:
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration/1981/
https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration/1980/
![image](https://user-images.githubusercontent.com/2371880/36994562-5b1a9336-2066-11e8-9f92-d35438357505.png)

**Comment by 333fred** [comment]
Again: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/1988/

**Comment by 333fred** [comment]
Another failure. Slightly different stack, but it's the same exception so I'd guess it'll be the same fix. https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration/1993/
```
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyReorderParameters
      System.Windows.Automation.ElementNotAvailableException : Element not available
      ---- System.Runtime.InteropServices.COMException : An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
      Stack Trace:
           at System.Windows.Automation.SelectionItemPattern.Select()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.ChangeSignatureDialog_OutOfProc.SelectParameter(String parameterName)
           at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyReorderParameters()
        ----- Inner Stack Trace -----
           at UIAutomationClient.IUIAutomationSelectionItemPattern.Select()
           at System.Windows.Automation.SelectionItemPattern.Select()
```

**Comment by CyrusNajmabadi** [comment]
Getting this here: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/10701/

**Comment by 333fred** [comment]
@jinujoseph can you please have someone look into this?

**Comment by jinujoseph** [comment]
cc @jcouv

**Comment by sharwell** [comment]
This should be fixed now. The issue can be closed after verifying the tests are not disabled.

**Comment by dpoeschl** [comment]
Looks like this hit again in https://ci.dot.net/job/dotnet_roslyn/job/dev15.9.x-vs-deps/job/windows_debug_vs-integration_prtest/49/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicChangeSignatureDialog/VerifyReorderParameters/

**Comment by CyrusNajmabadi** [comment]
These tests are enabled and haven't failed in 6 years.  Closing htis out.
