### ISSUE TITLE
Error when analyzing code

### ISSUE THREAD

**Issue by mallibone** [dotnet/roslyn#25354]
**Version Used**: 2.8.0.62701

**Steps to Reproduce**:

1. Compile solution 

**Expected Behavior**:
No Exceptions should show up in the warning detail description.
**Actual Behavior**:
The following exception is being displayed:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8618	Non-nullable field '_navigationItems' is uninitialized.	Foo FooDrive\ViewModels\VMSubcategory\VMName.cs	29	Active
Warning		The "GetReferenceNearestTargetFrameworkTask" task failed unexpectedly.
System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at EnvDTE.Project.get_UniqueName()
   at Microsoft.VisualStudio.ProjectUtilities.GetVsHierarchy(IServiceProvider provider, Project project, Boolean throwOnFailure)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.GetProjectOutputs(Project project)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.AddProjectEntries(Project project, List`1 entries)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.EnsurePopulated(Boolean fPopulateProject)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.SearchProjectEntries(AssemblyName assemblyName, String typeName, Boolean ignoreTypeCase, Assembly& assembly)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.SearchEntries(AssemblyName assemblyName, String typeName, Boolean ignoreCase, Assembly& assembly, ReferenceType refType)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.SearchEntries(AssemblyName assemblyName, String typeName, Boolean ignoreTypeCase, Assembly& assembly)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.System.ComponentModel.Design.ITypeResolutionService.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.System.ComponentModel.Design.ITypeResolutionService.GetType(String name)
   at Microsoft.VisualStudio.Design.VSDynamicTypeService.OnTypeResolve(Object sender, ResolveEventArgs e)
   at System.AppDomain.OnTypeResolveEvent(RuntimeAssembly assembly, String typeName)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at NuGet.Common.RuntimeEnvironmentHelper.<>c.<.cctor>b__14_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at NuGet.Common.RuntimeEnvironmentHelper.get_IsMono()
   at NuGet.Build.MSBuildLogger.Log(ILogMessage message)
   at NuGet.Common.LoggerBase.Log(LogLevel level, String data)
   at NuGet.Build.Tasks.BuildTasksUtility.LogTaskParam(ILogger log, String direction, String name, String[] values)
   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Gesundheitsnavigator.Core.RocketHealthTypes.Tests		
```

**Comment by CyrusNajmabadi** [comment]
No prism hits on this at all.  No other reports.  Clsoign out.
