### ISSUE TITLE
Regression in BinaryFormatter's serialization of lambdas in very particular circumstances from VS 2017 v15.4 to VS 2017 v15.5

### ISSUE THREAD

**Issue by hrichardlee** [dotnet/roslyn#25355]
**Version Used**: Visual Studio 2017 v15.5.7

**Steps to Reproduce**:

1. In Visual Studio 2017 v15.5.7, create a new C# Console Application, and make Program.cs look like:
```
using System;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace ConsoleApplicationVS2017
{
    public static class Serialization
    {
        public static byte[] Serialize(Func<int> o)
        {
            var binaryFormatter = new BinaryFormatter();
            using (var stream = new MemoryStream())
            {
                binaryFormatter.Serialize(stream, o);
                return stream.ToArray();
            }
        }
    }

    [Serializable]
    public class Class1
    {
        private int Property { get; set; }

        public void Run()
        {
            Serialization.Serialize(() => Property + 5);

            var localVariable = Property;
            Func<int, int> func2 = o => localVariable + o;
        }
    }

    public static class Program
    {
        public static void Main()
        {
            new Class1().Run();
        }
    }
}
```
2. Run this application.

**Expected Behavior**:
Program executes successfully

**Actual Behavior**:
Program throws an exception:
```
Unhandled Exception: System.Runtime.Serialization.SerializationException: Type 'ConsoleApplicationVS2017.Class1+<>c__DisplayClass4_0' in Assembly 'ConsoleAppVS2017, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)

   at ConsoleApplicationVS2017.Serialization.Serialize(Func`1 o) in e:\source\scratch\ConsoleAppVS2017\ConsoleAppVS2017\Program.cs:line 14
   at ConsoleApplicationVS2017.Class1.Run() in e:\source\scratch\ConsoleAppVS2017\ConsoleAppVS2017\Program.cs:line 27
   at ConsoleApplicationVS2017.Program.Main() in e:\source\scratch\ConsoleAppVS2017\ConsoleAppVS2017\Program.cs:line 38
```

I'm pretty sure this did not happen with Visual Studio 2017 v15.4. I haven't double-checked this, but I did run this exact repro against Visual Studio 2015, which definitely does produce code that runs successfully. For good measure, I looked at the IL generated by the different versions of the compiler in .NET Reflector.

Here's the IL generated by Visual Studio 2015 which works:
```
[CompilerGenerated]
private sealed class <>c__DisplayClass4_0
{
    public int localVariable;

    internal int <Run>b__1(int o) => 
        (this.localVariable + o);
}
```

and `Class1` has a member
```
[CompilerGenerated]
private int <Run>b__4_0() => 
    (this.Property + 5);
```

Here's the IL generated by Visual Studio 2017 which doesn't work:
```
[CompilerGenerated]
private sealed class <>c__DisplayClass4_0
{
    public Class1 <>4__this;
    public int localVariable;

    internal int <Run>b__0() => 
        (this.<>4__this.Property + 5);

    internal int <Run>b__1(int o) => 
        (this.localVariable + o);
}
```

As far as I can describe, it, the problem happens when we try to serialize a lambda that has an implicit reference to `this`, from inside of a function that also has a lambda (that is never explicitly serialized!) that has a reference to a local variable. If any of these things are changed (the first lambda doesn’t have the implicit reference, the second non-serialized lambda is in a different function, the second non-serialized lambda doesn’t reference a local variable), the function serializes.

**Comment by jcouv** [comment]
Tagging @agocke

**Comment by agocke** [comment]
Yes, this is likely due to some changes to the closure conversion code that places lambdas in a slightly different location.

In general, I would say that serialization of compiler-generated code should not assumed to be robust across releases.

**Comment by agocke** [comment]
cc @jaredpar to decide how important we think this is.

**Comment by tmat** [comment]
I'd argue that serializing compiler-generated types is undefined and not supported. 
Perhaps an analyzer would be useful. @jinujoseph

**Comment by agocke** [comment]
It is absolutely undefined, according to the C# language specification.

**Comment by jaredpar** [comment]
@agocke and @tmat are correct. The compiler makes no guarantees about the shape or names of types that it emits as an implementation detail of features like closures, async, iterators, etc ...
