### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.CrossLanguageTests.CanBeReferencedByName Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25502]
Null Ref on this line: https://github.com/dotnet/roslyn/blob/07c65e2541f16a10dd1fa8532b6f3030682ca99b/src/Compilers/Core/Portable/PEWriter/DebugDirectoryExtensions.cs#L38
Failure: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/ubuntu_16_debug/1547/

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Roslyn.Reflection.PortableExecutable.DebugDirectoryExtensions.AddPdbChecksumEntry(DebugDirectoryBuilder builder, String algorithmName, ImmutableArray`1 checksum) in /_/src/Compilers/Core/Portable/PEWriter/DebugDirectoryExtensions.cs:line 38
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/PEWriter/PeWriter.cs:line 253
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2650
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2479
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2240
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.EmitToArray(Compilation compilation, EmitOptions options, CompilationTestData testData, DiagnosticDescription[] expectedWarnings, Stream pdbStream, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts) in /_/src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs:line 49
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.EmitToImageReference(Compilation comp, EmitOptions options, Boolean embedInteropTypes, ImmutableArray`1 aliases, DiagnosticDescription[] expectedWarnings) in /_/src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs:line 95
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CrossLanguageTests.CanBeReferencedByName() in /_/src/Compilers/CSharp/Test/Symbol/CrossLanguageTests.cs:line 27
```

Tagging @tmat for investigation.

**Comment by 333fred** [comment]
Note this was on the `ubuntu_16_debug` test.

**Comment by 333fred** [comment]
Another similar failure: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/mac_debug/2285/
Failed in the same place on the Microsoft.CodeAnalysis.CSharp.UnitTests.BadSymbolReference.MissingBaseClass test.

**Comment by tmat** [comment]
Looks like a race condition where multiple tests are emitting.

**Comment by tmat** [comment]
Fixing

**Comment by 333fred** [comment]
Failed again in master-vs-deps, but it looks like the fix hasn't made it there yet.

**Comment by jinujoseph** [comment]
closing the issue , pls reopen if you see this again
