### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Expressions_Tests.ConstantFields1 Failure OutOfMemoryException

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25627]
Failed in jenkins in dev15.7.x-vs-deps: https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x-vs-deps/job/windows_release_unit32/71/testReport/junit/Microsoft.CodeAnalysis.VisualBasic.UnitTests/Binder_Expressions_Tests/ConstantFields1/
```
    Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Expressions_Tests.ConstantFields1
      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
      Stack Trace:
           at TestReferences.SymbolsTests.Fields.<>c.<.cctor>b__5_0()
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.LazyInitValue()
           at System.Lazy`1.get_Value()
           at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Expressions_Tests.ConstantFields1()
```
@dotnet/roslyn-compiler

**Comment by dpoeschl** [comment]
Happened again: https://ci.dot.net/job/dotnet_roslyn/job/dev15.8.x-vs-deps/job/windows_release_unit32_prtest/19/testReport/junit/Microsoft.CodeAnalysis.VisualBasic.UnitTests/Binder_Expressions_Tests/ConstantFields1/

**Comment by JoeRobich** [comment]
Closing as test is passing
