### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGenerateTypeDialog.OpenAndCloseDialog Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#25625]
Failed in master integration tests [here](https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_release_vs-integration/2002/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpGenerateTypeDialog/OpenAndCloseDialog/).
Stack:
```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGenerateTypeDialog.OpenAndCloseDialog
      System.Windows.Automation.ElementNotAvailableException : Element not available
      ---- System.Runtime.InteropServices.COMException : An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
      Stack Trace:
           at System.Windows.Automation.AutomationElement.TryGetCurrentPattern(AutomationPattern pattern, Object& patternObject)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.AutomationElementExtensions.Invoke(AutomationElement element)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.GenerateTypeDialog_OutOfProc.ClickCancel()
           at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpGenerateTypeDialog.OpenAndCloseDialog()
        ----- Inner Stack Trace -----
           at UIAutomationClient.IUIAutomationElement.GetCurrentPattern(Int32 patternId)
           at System.Windows.Automation.AutomationElement.TryGetCurrentPattern(AutomationPattern pattern, Object& patternObject)
```
Screenshot:
![image](https://user-images.githubusercontent.com/2371880/37672429-2fc81c14-2c2b-11e8-9afc-1ffe7f56a5d5.png)

Given the exception, it's very possibly related to https://github.com/dotnet/roslyn/issues/25230. @dpoeschl, does that seem possible to you? If so, could you close this as a dupe?

**Comment by sharwell** [comment]
This is now fixed. The issue can be closed after verifying the test is not disabled.

**Comment by sharwell** [comment]
The test is enabled

https://github.com/dotnet/roslyn/blob/63820dfce70dfb4d90e95097364d565e9a549043/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpGenerateTypeDialog.cs#L30-L31
