### ISSUE TITLE
[Regression] Syntax no longer shows up in Find All References if it refers to symbols outside of the project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#25716]
**Version Used**: 
Version 15.7.0 Preview 3.0 [27523.0.d15.7]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. In `Main` in Program.cs, add:
``` C#
            Console.WriteLine("Foo");
```
3. Right-click on WriteLine and choose _Find All References_

**Expected Behavior**:
In 15.6.3:
![image](https://user-images.githubusercontent.com/1103906/37885235-cc034436-30ff-11e8-95bc-07c601d067d6.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/37885241-d893cf5e-30ff-11e8-929a-8e51de763cf0.png)

~Note: I tried to repro this on a new project and couldn't - however, it repros in every FAR I've done in project-system and CPS solution.~

I've found a 100% repro, updated steps.

**Comment by davkean** [comment]
Note it appears that if the resulting symbol is _inside_ of the same project - it shows.

**Comment by jcouv** [comment]
Tagging @jinujoseph to prioritize/assign.

**Comment by sharwell** [comment]
I can reproduce this in commit 15.6.3 experimental instance using commit 1481ef3c14086466db36f771bb109330f86e5333, which certainly suggests this is a Roslyn-based problem. Git Bisect time...

**Comment by sharwell** [comment]
```
"C:\Program Files\Git\bin\git.exe" bisect bad
1063c092d2ca0a48f4bd189e53002ae714348955 is the first bad commit
commit 1063c092d2ca0a48f4bd189e53002ae714348955
Author: Mike Krüger <mikkrg@microsoft.com>
Date:   Mon Feb 19 08:45:52 2018 +0100

    Added member classification support for c#.

:040000 040000 5ef21b0e2c95f63cc62e33bd2cd48c5b97c9fdf5 cf4adcff51c9f82ab1617f647fce1c021b9e0a8a M  src
```

**Comment by sharwell** [comment]
I see this in the output window during debugging:

```
Exception thrown: 'System.ArgumentNullException' in Microsoft.VisualStudio.Platform.VSEditor.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
System.Windows.Data Error: 17 : Cannot get 'Item[]' value (type 'Object') from '' (type 'SnapshotTableEntryViewModel'). BindingExpression:Path=[linetext]; DataItem='SnapshotTableEntryViewModel' (HashCode=65872662); target element is 'ContentPresenter' (Name=''); target property is 'Content' (type 'Object') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: classificationType
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationFormatMap.GetTextProperties(IClassificationType classificationType)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.WpfClassificationExtensions.ToRun(ClassifiedText part, IClassificationFormatMap formatMap, ClassificationTypeMap typeMap)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.WpfClassificationExtensions.ToInlines(IEnumerable`1 parts, IClassificationFormatMap formatMap, ClassificationTypeMap typeMap, Action`3 runCallback)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.DocumentSpanEntry.CreateLineTextInlines()
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.AbstractDocumentSpanEntry.TryCreateColumnContent(String columnName, FrameworkElement& content)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.DocumentSpanEntry.TryCreateColumnContent(String columnName, FrameworkElement& content)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter.TableEntriesSnapshot.TryCreateColumnContent(Int32 index, String columnName, Boolean singleColumnView, FrameworkElement& content)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.SnapshotTableEntryViewModel.TryCreateColumnContent(String columnName, Boolean singleColumnView, FrameworkElement& content)
   at Microsoft.VisualStudio.Shell.TableControl.TableEntryHandleExtensions.TryCreateColumnContent(ITableEntryHandle entry, ITableColumnDefinition column, Boolean singleColumnView, FrameworkElement& content)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableEntryViewModel.GetEntryContent(ITableColumnDefinition column)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableEntryViewModel.get_Item(String columnName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

**Comment by jcouv** [comment]
Thanks!
For the record, the fix made it into preview 3.

**Comment by davkean** [comment]
This looks like it got regressed again: https://github.com/dotnet/roslyn/issues/25716.
