### ISSUE TITLE
NullReferenceException in DocumentationCommentExtensions.IsMultilineDocComment

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25746]
Originally posted by @Jehoel in DotNetAnalyzers/StyleCopAnalyzers#2648

> While a editing C# Console project and typing "//////" on an empty line line inside my `void Main` I got a message informing me an Editor Extension had crashed.
> 
> Here's the message logged in `ActivityLog.xml`:
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.CodeAnalysis.CSharp.Extensions.DocumentationCommentExtensions.IsMultilineDocComment(DocumentationCommentTriviaSyntax documentationComment)
>    at Microsoft.CodeAnalysis.Editor.CSharp.DocumentationComments.DocumentationCommentCommandHandler.IsMultilineDocComment(DocumentationCommentTriviaSyntax documentationComment)
>    at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.TryGenerateExteriorTriviaAfterEnter(SyntaxTree syntaxTree, SourceText text, Int32 position, Int32 originalPosition, ITextBuffer subjectBuffer, ITextView textView, DocumentOptionSet options, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.InsertOnEnterTyped(SyntaxTree syntaxTree, SourceText text, Int32 position, Int32 originalPosition, ITextBuffer subjectBuffer, ITextView textView, DocumentOptionSet options, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.CompleteComment(ITextBuffer subjectBuffer, ITextView textView, Int32 originalCaretPosition, Func`9 insertAction, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.ExecuteCommand(ReturnKeyCommandArgs args, CommandExecutionContext context)
>    at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
>    at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
>    at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
> ```
> 
> Repro steps:
> 
> 1. Open an existing C# console project in VS 2017 (15.6.4)
> 2. On an empty line inside a method type "/////" (several forward-slashes)
> 3. VS will display the extension crash warning dialog. The above stack-trace will be written to `ActivityLog.xml`.

**Comment by zo0o0ot** [comment]
I am also experiencing this issue. I'm adding a comment to a block of commented code like this:

```
//////                  *aaa  01/01/18 XX-000  code comment
//////                  *bbb 01/10/18 XX-001  different code comment
```

When pressing enter on the previous line to add a new line, the same error described above occurs.

**Comment by jinujoseph** [comment]
Also reported at [link](https://developercommunity.visualstudio.com/content/problem/264456/null-reference-exception-on-typing-c.html)
