### ISSUE TITLE
Installation of compiled source releases/VS2015RC onto Studio 2015 RC Fails

### ISSUE THREAD

**Issue by grbd** [dotnet/roslyn#2578]
Hi,
I've recently been interested in getting ide support for csx script files working with Visual Studio 2015 RC, for use with scriptcs (to get intellisense / auto complete etc), at the moment csx files are just seen as basic text files

From what I understand of the script API it was disabled for a while, then re-enabled but only within source within github, so I figured I'd have a go at rebuilding the source / installing manually into studio 2015RC to get csx syntax highlighting working
From what I've been told on the chat I only need to install the interactive ones, however for the hell of it I tried all of them, but none would install

```
git clone https://github.com/dotnet/roslyn.git
git checkout releases/VS2015RC
```

Then I just built the whole lot with Studio 2015 RC using Roslyn.sln
After that I tried installing each of the vsix files just to see what would happen

* **Microsoft.VisualStudio.VsInteractiveWindow.vsix** - Not sure how to remove this one via Program Features, couldn't find an option for it
```
07/05/2015 16:36:52 - Upgrading 'Roslyn Language Services', version 1.0.0.50411 to version 42.42.42.42.
07/05/2015 16:36:53 - Install Error : Microsoft.VisualStudio.ExtensionManager.BreaksExistingExtensionsException: This extension cannot be installed because the following extensions contain dependencies that would be broken as a result of this installation:
- Roslyn Expression Evaluators
- Roslyn Telemetry
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

```

* **Roslyn.VisualStudio.InteractiveComponents.vsix** - Perhaps this isn't picking up on the integrated version included with 2015 RC
```
07/05/2015 16:45:08 - Beginning to install extension to Microsoft Visual Studio Enterprise 2015 RC...
07/05/2015 16:45:08 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Roslyn Language Services
- VisualStudio Interactive Components
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

* **Roslyn.VisualStudio.Setup.Interactive.vsix** - I think this one doesn't install because it needs some of the others first
```
07/05/2015 16:43:31 - Beginning to install extension to Microsoft Visual Studio Enterprise 2015 RC...
07/05/2015 16:43:31 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Roslyn Components
- Roslyn Interactive Components
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

* **Roslyn.VisualStudio.Setup.vsix** - This is probably just conflicting with the one already installed into Studio, I don't think it's an interactive one
```
07/05/2015 16:36:52 - Beginning to install extension to Microsoft Visual Studio Enterprise 2015 RC...
07/05/2015 16:36:52 - Upgrading 'Roslyn Language Services', version 1.0.0.50411 to version 42.42.42.42.
07/05/2015 16:36:53 - Install Error : Microsoft.VisualStudio.ExtensionManager.BreaksExistingExtensionsException: This extension cannot be installed because the following extensions contain dependencies that would be broken as a result of this installation:
- Roslyn Expression Evaluators
- Roslyn Telemetry
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

* **ExpressionEvaluatorPackage.vsix** - Again not an interactive one, but for info
```
07/05/2015 16:49:28 - Upgrading 'Roslyn Expression Evaluators', version 1.0.0.50411 to version 42.42.42.42.
07/05/2015 16:49:29 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Roslyn Language Services
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

**Comment by grbd** [comment]
Just to give an update on this one, I figured out how to run roslyn via the Rosyln profile using the wiki

I was able to get OpenSourceDebug working but only after applying this patch to the current releases/VS2015RC version https://github.com/dotnet/roslyn/blob/8cda04e7151dadaae93f6e0ce2db20084a6e069d/src/Tools/Source/OpenSourceDebug/enableopensource.pkgdef

However this didn't include ide support for csx files, so I then tried loading in the vsix files into the Roslyn profile of Visual studio using Root-VSIX.exe 14.0 Roslyn [file].vsix

These load okay into the profile
* Roslyn.VisualStudio.DiagnosticsWindow.vsix
* Microsoft.CodeAnalysis.Analyzers.Setup.vsix
* FxCopRulesSetup.vsix

These still fail with the same errors as before
* Roslyn.VisualStudio.Setup.vsix
* Roslyn.VisualStudio.Setup.Interactive.vsix
* Roslyn.VisualStudio.InteractiveComponents.vsix
* Microsoft.VisualStudio.VsInteractiveWindow.vsix
* ExpressionEvaluatorPackage.vsix

**Comment by ManishJayaswal** [comment]
unfortunately we have not tried this so this will need to be investigated.

**Comment by grbd** [comment]
For info I did a bit more experimentation
the OpenSourceDebug project appears to be used for debugging as a single extension pulling files from other extensions into a single file (a wrapper for multiple extensions)

although OpenSourceDebug lacks the components for Roslyn.VisualStudio.Setup.Interactive.vsix ("Roslyn Interactive Language Services") and Roslyn.VisualStudio.InteractiveComponents.vsix ("Roslyn Interactive Components "), this might be by design if these extensions aren't yet ready perhaps (the ones used for .csx file support)

I noticed the VSSDKTargetPlatformRegRootSuffix setting was set to "Roslyn" for OpenSourceDebug, and to "RoslynDev" for the individual extensions (again maybe it's by design)
so I had a quick go at setting everything to "Roslyn" then trying to load in those extensions seperatley using Root-VSIX.exe just to see if I could hack it to work, however all I ended up with is "Expected 1 export(s) with contract name "Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace" but found 0 after applying applicable constraints." in the ActivityLog.xml

**Comment by stajs** [comment]
I'm also interested in getting .csx file support in VS2015, so :+1:

**Comment by Kazetsukai** [comment]
me 3, :+1:

**Comment by ManishJayaswal** [comment]
@grbd have you tried this on top of VS2015 Update 1 bits?

**Comment by grbd** [comment]
Yep just tried this on the latest VS2015 update 1
it looks like csx files are now recognised under studio. So I'll close this down
