### ISSUE TITLE
DumpLocalVariableValue tests show crashing VS

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#25814]
**Version Used**: Commit 3c001e34c3e638d7e880372218c3a8b6ecea8d41

The two `DumpLocalVariableValue` tests (previously named `DumpLocalVaribleValue`) fail when Visual Studio crashes with the following exception:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.MapDownToSnapshot(Span span, IProjectionSnapshot start, ITextSnapshot target)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.GetSubjectBufferTextSpanInViewBuffer(TextSpan textSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.SetCaretPosition(Int32 desiredCaretPosition)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Commit(CompletionItem item, Model model, Nullable`1 commitChar, ITextSnapshot initialTextSnapshot, Action nextHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnNonTypeChar(CompletionItem item, Model model)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnTab(Action nextHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs>.ExecuteCommand(TabKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs>.ExecuteCommand(TabKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionErrorHandler.HandleError(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(System.Object, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__0()
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.ExecuteCommand(Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs, System.Action, Microsoft.VisualStudio.Commanding.CommandExecutionContext)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.VisualStudio.Commanding.ICommandHandler, System.__Canon, System.Action, Microsoft.VisualStudio.Commanding.CommandExecutionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(System.Object, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__0()
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.ExecuteCommandHandlerChain(Microsoft.VisualStudio.Commanding.CommandExecutionContext, System.Action, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`3<Microsoft.VisualStudio.Text.Editor.ITextView,Microsoft.VisualStudio.Text.ITextBuffer,System.__Canon>, System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.ExecuteTabKeyCommand(System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.ExecuteVisualStudio2000(System.Guid ByRef, UInt32, IntPtr, IntPtr, System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.LanguageServices.Implementation.DebuggerIntelliSense.DebuggerIntelliSenseFilter`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
```

**Comment by CyrusNajmabadi** [comment]
Wonderful!
