### ISSUE TITLE
System.ArgumentException: Illegal characters in path at MSBuildWorkspace.Create().OpenProjectAsync(projectPath).Result

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#25812]
**Version Used**: 
2.7.0
.NET Framework 7.0

**Steps to Reproduce**:

1. We use following code for opening a .csproj using Roslyn's **MSBuildWorkspace** :
```
foreach(var projectPath in csProjFiles)
{
      using (var workspace = MSBuildWorkspace.Create())
     {
           Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
          workspace.LoadMetadataForReferencedProjects = true;
     }
}
```
2. When we run the above code locally using Visual Studios, the above code works well for all the .csproj file paths in **csProjFiles** collection.
3. But when we run the same code on the server where we deploy the this code, we get following exception:
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetAbsolutePath(String path) in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/ProjectFile/ProjectFile.cs:line 442
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetOutputDirectory() in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/ProjectFile/ProjectFile.cs:line 227
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.CSharpCompilerInputs..ctor(CSharpProjectFile projectFile) in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/CSharp/CSharpProjectFileLoader.CSharpProjectFile.cs:line 222
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__3.MoveNext() in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/CSharp/CSharpProjectFileLoader.CSharpProjectFile.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadProjectAsync>d__23.MoveNext() in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/MSBuildProjectLoader.cs:line 322
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadProjectInfoAsync>d__20.MoveNext() in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/MSBuildProjectLoader.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenProjectAsync>d__23.MoveNext() in /_/src/Workspaces/Core/Desktop/Workspace/MSBuild/MSBuildWorkspace.cs:line 197
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
```
4. This exception comes randomly for different csproj files.

**Expected Behavior**:
No exception should be thrown and all the projects should load successfully.

**Actual Behavior**:
System.ArgumentException: Illegal characters in path

**Comment by jmarolf** [comment]
What is the path that you are trying to load your project from when it is failing?

**Comment by abhijitparkhi1983** [comment]
@jmarolf 

`C:\Repo\checkouts\/90a38b8eeb28cbf3b493a3b75f0e0cbb\src\Main\Build\Tools\Editor\InstallEditor.csproj`

this is the same path locally as well as when it is used on the server.

**Comment by buko1234** [comment]
I do not know if it helps, but I ran recently into the similar problem - everything worked ok locally, but when run on Jenkins, I received these exceptions. Turned out setting ProgramData environment variable on Jenkins solved the issue.

**Comment by DustinCampbell** [comment]
I strongly suspect that https://github.com/dotnet/roslyn/pull/30560 will address this problem.
