### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_CallerInfoAttributes.TestCallerFilePath2 is failing for CoreCLR in DefaultInterfaceImplementation branch possibly due to behavior change in CoreCLR

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#25882]
```
Failed
Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_CallerInfoAttributes.TestCallerFilePath2 (from (empty))

Failing for the past 1 build (Since Failed#43 )
Took 21 ms.
Stacktrace
MESSAGE:
Roslyn.Test.Utilities.ExecutionException : 

Execution failed for assembly '9d7f08bb-ef1b-4841-bfed-9df22a7a5775, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Expected: 
1: 'C:\\filename'
2: 'C:\\A\\B\\a\\c\\d.cs'
3: '*'
4: 'C:\\abc'
5: ' '

Actual: 
1: 'C:\\filename'
2: 'C:\\A\\B\\a\\c\\d.cs'
3: 'C:\\A\\B\\*'
4: 'C:\\abc'
5: ' '
\r\n

+++++++++++++++++++
STACK TRACE:
 at Roslyn.Test.Utilities.CoreClr.CoreCLRRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput) in /_/src/Test/Utilities/Portable/Platform/CoreClr/CoreCLRRuntimeEnvironment.cs:line 83
 at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures) in /_/src/Test/Utilities/Portable/CompilationVerifier.cs:line 96
 at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify) in /_/src/Test/Utilities/Portable/CommonTestBase.cs:line 231
 at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) in /_/src/Test/Utilities/Portable/CommonTestBase.cs:line 157
 at Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_CallerInfoAttributes.TestCallerFilePath2() in /_/src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_CallerInfoAttributes.cs:line 1548
```

**Comment by AlekseyTs** [comment]
See https://ci.dot.net/job/dotnet_roslyn/job/features_DefaultInterfaceImplementation/job/windows_coreclr_test_prtest/43/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/AttributeTests_CallerInfoAttributes/TestCallerFilePath2/ for more information

The test is disabled for CoreCLR in DefaultInterfaceImplementation branch because of that failure.

**Comment by AlekseyTs** [comment]
Interestingly the test didn't fail in local CoreCLR run, but failed in CI.

**Comment by AlekseyTs** [comment]
It looks like the test is no longer disabled
