### ISSUE TITLE
After pulling in the lastest master, i cannot f5 into roslyn anymore.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#25899]
When i try, i get:

```

ERROR | LegacySitePackage failed for package [Roslyn Diagnostics Window]Source: 'Microsoft.VisualStudio.Composition' Description: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". ---> System.NotSupportedException: Cannot instantiate with unsupported importing constructor of type: RuntimeMethodInfo   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider

LegacySitePackage failed for package [Roslyn Diagnostics Window]Source: 'Microsoft.VisualStudio.Composition' Description: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". ---> System.NotSupportedException: Cannot instantiate with unsupported importing constructor of type: RuntimeMethodInfo   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()   at System.ComponentModel.Composition.Primitives.Export.get_Value()   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c__DisplayClass5_0.<.ctor>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()   at Microsoft.CodeAnalysis.SolutionServices..ctor(Workspace workspace)   at Microsoft.CodeAnalysis.SolutionState..ctor(Workspace workspace, SolutionInfo info)   at Microsoft.CodeAnalysis.Workspace.CreateSolution(SolutionId id)   at Microsoft.CodeAnalysis.Workspace..ctor(HostServices host, String workspaceKind)   at Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace..ctor(HostServices hostServices, WorkspaceBackgroundWork backgroundWork)   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl..ctor(ExportProvider exportProvider)   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace..ctor(ExportProvider exportProvider, IEnumerable`1 streamingPresenters, IEnumerable`1 documentOptionsProviderFactories)   --- End of inner exception stack trace ---   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_0`2.<GetExports>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()   at Roslyn.VisualStudio.DiagnosticsWindow.VisualStudioDiagnosticsWindowPackage.Initialize()   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)System.NotSupportedException: Cannot instantiate with unsupported importing constructor of type: RuntimeMethodInfo   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()   at System.ComponentModel.Composition.Primitives.Export.get_Value()   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c__DisplayClass5_0.<.ctor>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()   at Microsoft.CodeAnalysis.SolutionServices..ctor(Workspace workspace)   at Microsoft.CodeAnalysis.SolutionState..ctor(Workspace workspace, SolutionInfo info)   at Microsoft.CodeAnalysis.Workspace.CreateSolution(SolutionId id)   at Microsoft.CodeAnalysis.Workspace..ctor(HostServices host, String workspaceKind)   at Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace..ctor(HostServices hostServices, WorkspaceBackgroundWork backgroundWork)   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl..ctor(ExportProvider exportProvider)   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace..ctor(ExportProvider exportProvider, IEnumerable`1 streamingPresenters, IEnumerable`1 documentOptionsProviderFactories)
```

And

```
A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". ---> System.NotSupportedException: Cannot instantiate with unsupported importing constructor of type: RuntimeMethodInfo   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()   at System.ComponentModel.Composition.Primitives.Export.get_Value()   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c__DisplayClass5_0.<.ctor>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()   at Microsoft.CodeAnalysis.SolutionServices..ctor(Workspace workspace)   at Microsoft.CodeAnalysis.SolutionState..ctor(Workspace workspace, SolutionInfo info)   at Microsoft.CodeAnalysis.Workspace.CreateSolution(SolutionId id)   at Microsoft.CodeAnalysis.Workspace..ctor(HostServices host, String workspaceKind)   at Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace..ctor(HostServices hostServices, WorkspaceBackgroundWork backgroundWork)   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl..ctor(ExportProvider exportProvider)   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace..ctor(ExportProvider exportProvider, IEnumerable`1 streamingPresenters, IEnumerable`1 documentOptionsProviderFactories)    --- End of inner exception stack trace ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_0`2.<GetExports>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()   at Roslyn.VisualStudio.DiagnosticsWindow.VisualStudioDiagnosticsWindowPackage.Initialize()   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--
```

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @sharwell @jmarolf Do you know what happened here?  Did we just do something in master that would make things incompatible?

**Comment by jmarolf** [comment]
Looking at the [history](https://github.com/dotnet/roslyn/commits/master/) I don't see any *-deps branch changes being merged in.  @CyrusNajmabadi did you `git clean -xdf` and build after resetting your VS hive?

**Comment by CyrusNajmabadi** [comment]
Haven't done that yet.  How do i reset the VS hive? Thanks!

**Comment by jasonmalinowski** [comment]
Hmm, I *did* change the version of the package being used to build VSIXes. I guess our integration test runs build them and deploy themselves, so maybe that *did* break things?

**Comment by CyrusNajmabadi** [comment]
Cleaning everything and deleting my hive fixed things.  Must have been a build-to-build issue!

**Comment by alrz** [comment]
@CyrusNajmabadi Is this issue similar to yours?
```
Microsoft.VisualStudio.Composition.CompositionFailedException: 
'Expected 1 export(s) with contract name
"Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.MiscellaneousFilesWorkspace"
but found 0 after applying applicable constraints.'
```
How can I try deleting the hive?

**Comment by jmarolf** [comment]
@alrz to reset the `RoslynDev` hive you would run the following:

```ini
%comspec% /C "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\CreateExpInstance.exe" /Reset /VSInstance=15.0_e0227681 /RootSuffix=RoslynDev
```
Assuming the VS you are using is installed to `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise` and assuming the VS instance id is `e0227681 `

**NOTE:** You can find your instance Id by running the following [vswhere](https://github.com/Microsoft/vswhere/releases/download/2.4.1/vswhere.exe) command
```ini
vswhere.exe -all -prerelease -property instanceId
```

**Comment by alrz** [comment]
Thanks! Resolved.

**Comment by Jehoel** [comment]
This happened to me just now after my PC rebooted after a power-spike while Visual Studio was running. I don't know how to fix it, unfortunately.
