### ISSUE TITLE
ReplacePropertyWithMethodsCodeRefactoringProvider caused NullReferenceException

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#25910]
**Version Used**: VS 15.6.4

Not sure what triggered it, but I don't see another issue for this.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.UpdateReferencesInDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.UpdateReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.ReplacePropertyWithMethodsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
Do you know what file you were in, and the code somewhat around you ? (or the whole code file)?  ReplacePropertyWithMethodsCodeRefactoringProvider only shows up on a property, so if we looked at your properties it might help narrow this down.

**Comment by jinujoseph** [comment]
Also reported at [DC](https://developercommunity.visualstudio.com/content/problem/390312/replacepropertywithmethodscoderefactoringprovider-3.html)

**Comment by jinujoseph** [comment]
Related to https://github.com/dotnet/roslyn/issues/21934 ?

**Comment by IraJain09** [comment]
**Steps:-**
1.Create a C# Console Project
2.Try to replace method to property

**Actual Output:-**
**ReplaceMethodWithPropertyCodeRefractoringProvider** Crash Occurs. 
![1 3](https://user-images.githubusercontent.com/49509107/60865713-3c05ce00-a244-11e9-98ad-5b967725aeaf.PNG)



![image](https://user-images.githubusercontent.com/49509107/60865781-58a20600-a244-11e9-9a8e-b8666a0e0bb5.png)

**Comment by allisonchou** [comment]
@IraJain09 Hi, what version of VS is this on? So far I cannot reproduce the problem using the code provided.

**Comment by IraJain09** [comment]
@allisonchou This bug reproduced in 
Build Branch:-D16.3 
Build Number:-

**Comment by allisonchou** [comment]
@IraJain09 I still can't seem to reproduce the bug, unfortunately. Can you share the full source file(s) you are using that produces the error?

**Comment by tmat** [comment]
Another case captured by servicehub logs in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155340

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/a5d841ab72d9527a2c3b30c37348f2e512bbbbbd/src/Workspaces/Core/Portable/Editing/SyntaxEditor.cs#L318

It's most likely that GetCurrentNode is returning null. Possibly related to https://github.com/dotnet/roslyn/issues/41526? @jnm2 You may be able to tell whether it's related?

**Comment by jnm2** [comment]
Sorry, I've lost all context for #41526 at this point and would have to read the thread to find out what I knew.
