### ISSUE TITLE
Cannot instantiate with unsupported importing constructor of type: RuntimeMethodInfo

### ISSUE THREAD

**Issue by cezarypiatek** [dotnet/roslyn#25962]
Hi
I'm working on a set of Code Fix providers based on roslyn. One of my providers is responsible for converting the following code

```csharp
public UserDTO Map(UserEntity s)
{
     return new UserDTO(s);
}
```
into this

```csharp
 public UserDTO Map(UserEntity s)
{
     return new UserDTO(firstName: s.FirstName, lastName: s.LastName, age: s.Age, cash: s.Cash);
}
```
After upgrading to VS 15.6.5 (VS 15.5.0 previously) when I hit ctr+. in place of invalid invocation `new UserDTO(s);` (there is no constructor that accepts this argument) I'm getting the following error. 

![image](https://user-images.githubusercontent.com/7759991/38385629-a0955008-3912-11e8-825d-2ee979d376eb.png)

I don't get any exception from my code fix provider code when I run it under debbuger. Source code of my providers is available here https://github.com/cezarypiatek/MappingGenerator

**Comment by azbrainiac** [comment]
I have the same problem

**Comment by cezarypiatek** [comment]
Seems to be solved here https://github.com/dotnet/roslyn/issues/25899

**Comment by cezarypiatek** [comment]
It looks like the problem came back. Visual Studio 15.7.4

Stacktrace:

```
at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass27_1.<GetFixerPerLanguageMap>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<AppendFixesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<GetFixesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetCodeFixes(IDocumentSupportsFeatureService supportsFeatureService, ISuggestedActionCategorySet requestedActionCategories, Workspace workspace, Document document, SnapshotSpan range, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActions(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.<>c__DisplayClass40_1.<TryGetSuggestedActionSets>b__0(IWaitContext c)
   at Microsoft.VisualStudio.Editor.Implementation.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Action`1 action)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.TryGetSuggestedActionSets(IEnumerable`1& actionSets, ISuggestedActionCategorySet overrideRequestedActionCategories)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.TransitionToExpandedState()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.ChangeState(LightBulbState newState)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.<OnSessionStateChanged>b__34_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by EdwinEngelen** [comment]
I'm also experiencing this problem. For me the problem disappears when I move methods to a new class.

For example. I have a class with extension methods A and B. When I add another method C (and don't use it) I get the error. Moving the extension method C to a new class resolves the error.

`
public static class ExpressionExtensions
{
public static bool MethodA(this ExpressionSyntax expressionSyntax, SyntaxNodeAnalysisContext context) {…}
public static bool MethodB(this ExpressionSyntax expressionSyntax, SyntaxNodeAnalysisContext context) {…}
// Adding this line causes the error
public static bool MethodB(this ExpressionSyntax expressionSyntax, SyntaxNodeAnalysisContext context) {…}
}
`

**Comment by InflexCZE** [comment]
Make sure to update to latest Roslyn package. Updating to 2.8.2 solved the issue for me.

**Comment by BADF00D** [comment]
I had the same issue, but independent of the version of Roslyn (I tested 2.4, 2.7 2.8 and 2.8.2). Afterwards I updated VS Community from 15.7.5 to 15.7.6 and the issue disappears.

**Comment by CyrusNajmabadi** [comment]
Closing out as there are no recent reports of this.
