### ISSUE TITLE
ArgumentException in SetForegroundWindow triggers integration test failure

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26036]
This was supposed to be fixed by 53178e6896830f7d4441f5c405a0660fff6e580c but is still observed in some cases.

Example:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_release_vs-integration_prtest/360/

```
System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

Server stack trace: 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.IntegrationHelper.SetForegroundWindow(IntPtr window, Boolean skipAttachingThread)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.<>c__DisplayClass7_0.<ActivateMainWindow>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.ActivateMainWindow(Boolean skipAttachingThreads)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg).GetType().Name

Server stack trace: 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.IntegrationHelper.SetForegroundWindow(IntPtr window, Boolean skipAttachingThread)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.<>c__DisplayClass7_0.<ActivateMainWindow>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudio_InProc.ActivateMainWindow(Boolean skipAttachingThreads)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
```

**Comment by sharwell** [comment]
:memo: This failure can lead to cascading failures like the ones seen here:
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_release_vs-integration_prtest/344/artifact/Binaries/Release/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen this in 6 years.
