### ISSUE TITLE
RPC call rejected leads to test failure

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#26043]
⚠️ This was supposed to be fixed by 08fee02ee145f7e7354be4a77ed25c1ae63e67d5. Before making code changes, we should verify that the above change was actually included in the failed build.

Example:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration/38/
https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration/43/

```
System.Runtime.InteropServices.COMException (0x80010001): Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))
   at EnvDTE._DTE.get_Commands()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.StartRemoteIntegrationService(DTE dte)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance..ctor(Process hostProcess, DTE dte, ImmutableHashSet`1 supportedPackageIds, String installationPath)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<UpdateCurrentlyRunningInstanceAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<GetNewOrUsedInstanceAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspaceBase.<InitializeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task).GetType().Name
   at EnvDTE._DTE.get_Commands()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.StartRemoteIntegrationService(DTE dte)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance..ctor(Process hostProcess, DTE dte, ImmutableHashSet`1 supportedPackageIds, String installationPath)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<UpdateCurrentlyRunningInstanceAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<GetNewOrUsedInstanceAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspaceBase.<InitializeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by jaredpar** [comment]
> This was supposed to be fixed by 08fee02. Before making code changes, we should verify that the above change was actually included in the failed build.

That doesn't appear to be included. 

``` cmd
C:\Users\jaredpar\code\roslyn> git merge-base --is-ancestor 137cb02ff7e6be8b3afaed19b4d72b74642635  08fee02
C:\Users\jaredpar\code\roslyn> $?
False
```

**Comment by jaredpar** [comment]
Updated my comment based on my remembering what ancestor and descendant actually mean.

**Comment by sharwell** [comment]
In that case my best guess is the timeout was hit:

https://github.com/dotnet/roslyn/blob/a5a3d5246111c58f1b3237b1af7adf5bd5c19a91/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractIntegrationTest.cs#L140-L142

**Comment by sharwell** [comment]
Agree. I only saw two instance of this issue in the history, so it's not as common as some of the others I filed today. Worth figuring out though.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen this in 6 years.
