### ISSUE TITLE
CSharpUpgradeProjectCodeFixProvider failes with 'Unable to check out the files from source control.'

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#26093]
**Version Used**: 

15.6.6

**Steps to Reproduce**:

1. Create a new project and set the language version to 7.0
2. Do a SVN check in of the project (with an external tool, In my case *SmartSVN*. The tool was opened with the solution opened during the next steps, VS does not recognize that the solution is under version control and offers *Add to version control* in the bottom right corner.). 
3. Use a new language feature (e.g. `readonly struct`)
4. Choose *Upgrade all projects to language version 'Latest'* from quick fixes.

**Expected Behavior**:

All csproj of the solution are upgraded.

**Actual Behavior**:

The `CSharpUpgradeProjectCodeFixProvider` fails with

```
System.AggregateException : Mindestens ein Fehler ist aufgetreten. ---> Unable to check out the files from source control.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.Exception : Unable to check out the files from source control.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments(IEnumerable`1 documents)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unbekannte Parameter>)<---
```

**More details**

The exception isn't raised always. If you choose *Ignore and continue* from the golden bar and repeat the quick fix, parts of the solution get fixed until the exception is rissen again (after project 32 out of 59 in total in my case). I can't tell if the *steps to reproduce* are really all that is needed to re produce the failure. It's more like a description of my setup:

* Solution with several projects
* Solution is under version control (SVN, not managed by visual studio).

/cc @jcouv

**Comment by Neme12** [comment]
sounds like a duplicate of #18199

**Comment by MaStr11** [comment]
It is indeed a duplicate. Thank you for pointing that out.
