### ISSUE TITLE
Compiler (VBCSCompiler.exe, *and* csc.exe) crashes when building

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/roslyn#26238]
**Version Used**: VS 15.6.6
C# Tools   `2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80`

**Steps to Reproduce**:

1. Run MSBuild.exe with a custom project that builds a csproj.

**Expected Behavior**: successful compilation

**Actual Behavior**: compiler crashes with System.TypeLoadException.
```
Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.CoreClrShim' from assembly
 'Microsoft.CodeAnalysis, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

I updated to VS 2017 15.6.6 this morning, and now my projects which previously built without issue are crashing the compiler with the above exception. What is odd to me, is that I didn't think I was installing a *beta* build, but the version listed for the C# tools says that it is "beta3". Is this expected? Both VBSCCompiler.exe and csc.exe present crash messages, also not sure if this is strange, or normal behavior.

**Comment by MarkPflug** [comment]
I should also mention that this is not project-specific. Creating a new C# console app (framework or core) exhibits the same crash.

**Comment by MarkPflug** [comment]
Further investigation...

The machine with the issue has a Microsoft.CodeAnalysis.dll v2.7.0.0 in the GAC. Looking in that assembly, I don't see the CoreClrShim type. The Microsoft.CodeAnalysis.dll also exists in "\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn", which *does* contain the CoreClrShim type. The  date on the GAC folder is 3/8. I don't think that I manually GACed this, so I looked at my installed program list to see if anything looked suspicious. It appears I ran a lot of installers that day:
[InstallLog](https://raw.githubusercontent.com/MarkPflug/Share/master/installLog.png)

Perhaps the .NET core 2.1 preview?

The assembly version infos:
GAC: (bad)
[assembly: AssemblyInformationalVersion("2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019")]

bin: (good)
[assembly: AssemblyInformationalVersion("2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80")]

**Comment by MarkPflug** [comment]
I think I've convinced myself that this was my own doing. There were 4 assemblies in the GAC that shouldn't  have been there that had timestamps that were very close in time, but enough seconds apart that it looks like they were installed manually. I uninstalled them from the GAC, and things are working again. I will now close this issue, with great shame.
