### ISSUE TITLE
FileFromSameProjectTogetherTest hangs or fails sometimes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#26244]
Seen in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/13216/, there's an async hang somewhere. The test's async state machine has __state == 0 which I _think_ means we're waiting on the first await and I see there are active diagnostic tokens here:

/_/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.LowPriorityProcessor.cs

**Comment by tmat** [comment]
Failure:
https://dev.azure.com/dnceng/public/_build/results?buildId=259742&view=ms.vss-test-web.build-test-results-tab&runId=6933516&resultId=100149&paneView=debug

```
 at Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector) in /_/src/Test/Utilities/Portable/Assert/AssertEx.cs:line 418
   at Microsoft.CodeAnalysis.EditAndContinue.UnitTests.Extensions.Verify(IEnumerable`1 diagnostics, String newSource, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/TestUtilities/EditAndContinue/Extensions.cs:line 17
   at Microsoft.CodeAnalysis.EditAndContinue.UnitTests.EditAndContinueTestHelpers.VerifySemantics(EditScript`1 editScript, ActiveStatementsDescription activeStatements, IEnumerable`1 additionalOldSources, IEnumerable`1 additionalNewSources, SemanticEditDescription[] expectedSemanticEdits, DiagnosticDescription expectedDeclarationError, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/TestUtilities/EditAndContinue/EditAndContinueTestHelpers.cs:line 297
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemantics(EditScript`1 editScript, ActiveStatementsDescription activeStatements, IEnumerable`1 additionalOldSources, IEnumerable`1 additionalNewSources, SemanticEditDescription[] expectedSemanticEdits, DiagnosticDescription expectedDeclarationError, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/Extensions.cs:line 101
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemantics(EditScript`1 editScript, ActiveStatementsDescription activeStatements, SemanticEditDescription[] expectedSemanticEdits, DiagnosticDescription expectedDeclarationError, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/Extensions.cs:line 89
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemanticDiagnostics(EditScript`1 editScript, DiagnosticDescription expectedDeclarationError, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/Extensions.cs:line 70
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemanticDiagnostics(EditScript`1 editScript, RudeEditDiagnosticDescription[] expectedDiagnostics) in /_/src/EditorFeatures/CSharpTest/EditAndContinue/Helpers/Extensions.cs:line 62
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.StatementEditingTests.Queries_CeaseCapturingTransparentIdentifiers1() in /_/src/EditorFeatures/CSharpTest/EditAndContinue/StatementEditingTests.cs:line 7815
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't hit this in years and we have a dedicated system for tracking flakey tests now.
