### ISSUE TITLE
Flakey integration test VisualBasic.BasicWinForms.ChangeControlProperty

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#26443]
**VisualBasic.BasicWinForms.ChangeControlProperty** [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/915/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/ChangeControlProperty/) in debug on a non-code PR (https://github.com/dotnet/roslyn/pull/26416) with the following message:

**Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlProperty** (from Roslyn.VisualStudio.IntegrationTests)

Failing for the past 1 build (Since Failed#915 )
Took 3.3 sec.
Stacktrace
MESSAGE:
Assert.Contains() Failure
Not found: `Me.SomeButton.Text = "NewButtonText"`
In value:
```VB 
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
 Inherits System.Windows.Forms.Form

 'Form overrides dispose to clean up the component list.
 <System.Diagnostics.DebuggerNonUserCode()> _
 Protected Overrides Sub Dispose(ByVal disposing As Boolean)
  Try
   If disposing AndAlso components IsNot Nothing Then
    components.Dispose()
   End If
  Finally
   MyBase.Dispose(disposing)
  End Try
 End Sub

 'Required by the Windows Form Designer
 Private components As System.ComponentModel.IContainer

 'NOTE: The following procedure is required by the Windows Form Designer
 'It can be modified using the Windows Form Designer. 
 'Do not modify it using the code editor.
 <System.Diagnostics.DebuggerStepThrough()> _
 Private Sub InitializeComponent()
  components = New System.ComponentModel.Container()
  Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
  Me.ClientSize = New System.Drawing.Size(800, 450)
  Me.Text = "Form1"
 End Sub

End Class
```
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlProperty()

**Comment by 333fred** [comment]
Similar failures in the CSharp versions:
**`Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty`**
```
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: this.SomeButton.Text = "NewButtonText"
In value:  namespace TestProj
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Text = "Form1";
        }

        #endregion
    }
}


   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty().GetType().Name
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty()
```
![image](https://user-images.githubusercontent.com/2371880/42481657-63d056ba-8398-11e8-9698-d7397cf5b2b0.png)

**`Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode`**
```
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: this.SomeButton.Text = "ButtonTextGoesHere";
In value:  namespace TestProj
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Text = "Form1";
        }

        #endregion
    }
}


   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode().GetType().Name
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode()
```
![image](https://user-images.githubusercontent.com/2371880/42481662-69da7036-8398-11e8-8fdc-89a50362bcf4.png)

**Comment by JoeRobich** [comment]
Saw this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=123658&view=ms.vss-test-web.build-test-results-tab)

**Comment by sharwell** [comment]
@JoeRobich Please open a new issue for reoccurrence of old flaky tests
