### ISSUE TITLE
"Thread was being aborted" popups

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26468]
I'm working on branch `features/recursive-patterns` (commit f753435f10c01c1708389f6dcbc28c70c047de44) and editing/running some tests in `src\EditorFeatures\CSharpTest\AutomaticCompletion\AutomaticBraceCompletionTests.cs`.

I'm getting popups with the following stack trace.
I'm using `VisualStudio.15.Preview/15.7.0-pre.1.0+27512.0`.

I'll try again on Monday on 15.8 preview 1.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Thread was being aborted.



   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.<ProcessAsync>d__13.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task.FinishStageTwo()

   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)

   at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception exception)

   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.<WaitForPendingWorkAsync>d__16.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Threading.Tasks.Task.DelayPromise.Complete()

   at System.Threading.Tasks.Task.<>c.<Delay>b__274_1(Object state)

   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireNextTimers()

   at System.Threading.TimerQueue.AppDomainTimerCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by jcouv** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An error occurred creating the configuration section for system.diagnostics: Thread was being aborted. (C:\repos\roslyn\Binaries\Debug\UnitTests\CSharpEditorServicesTest\Roslyn.Services.Editor.CSharp.UnitTests.DLL.config line 10)



   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.<ProcessAsync>d__13.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task.FinishStageTwo()

   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)

   at System.Threading.Tasks.Task`1.TrySetException(Object exceptionObject)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception exception)

   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.<WaitForPendingWorkAsync>d__16.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Threading.Tasks.Task.DelayPromise.Complete()

   at System.Threading.Tasks.Task.<>c.<Delay>b__274_1(Object state)

   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireNextTimers()

   at System.Threading.TimerQueue.AppDomainTimerCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by sharwell** [comment]
If it's the same issue I hit earlier today, have a fix for this locally. Will send a fix tomorrow.

**Comment by jcouv** [comment]
Thanks @sharwell for the fix.
Closing the issue.
