### ISSUE TITLE
Sharplab shows TypeInferenceService error on recursive-patterns branch

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#26559]
```C#
public class C {
    public void M() {
        _ = e is { };
    }
}
```

[Sharplab link](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwhTIzUAmIA1AD4ACADAARcAjAG4AsACguAZgEAmPgGE+Abwl91AmVwAsfALIAKAJQq1G8wH0+AXj4Q+OZCr4BfMePMuJLoA=)

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.Filter(IEnumerable`1 types, Boolean filterUnusable) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.AbstractTypeInferrer.cs:line 72
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(TExpressionSyntax expression, Boolean filterUnusable) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.AbstractTypeInferrer.cs:line 52
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.InferTypes(SemanticModel semanticModel, SyntaxNode expression, String nameOpt, CancellationToken cancellationToken) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.cs:line 97
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferDelegateType(ITypeInferenceService typeInferenceService, SemanticModel semanticModel, SyntaxNode expression, CancellationToken cancellationToken) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Workspaces\Core\Portable\Shared\Extensions\ITypeInferenceServiceExtensions.cs:line 31
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.TryInitializeSimpleName(TService service, SemanticDocument document, TSimpleNameSyntax simpleName, CancellationToken cancellationToken) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Features\Core\Portable\GenerateMember\GenerateParameterizedMember\AbstractGenerateMethodService.State.cs:line 150
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.TryInitializeMethodAsync(TService service, SemanticDocument document, SyntaxNode node, CancellationToken cancellationToken) in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Features\Core\Portable\GenerateMember\GenerateParameterizedMember\AbstractGenerateMethodService.State.cs:line 64
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.<GenerateMethodStateAsync>d__0.MoveNext() in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Features\Core\Portable\GenerateMember\GenerateParameterizedMember\AbstractGenerateMethodService.State.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.<GenerateMethodAsync>d__5.MoveNext() in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Features\Core\Portable\GenerateMember\GenerateParameterizedMember\AbstractGenerateMethodService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.<RegisterCodeFixesAsync>d__0.MoveNext() in D:\$TC\work\c99972096bc51e45\!roslyn\sources\dotnet\src\Features\Core\Portable\CodeFixes\GenerateMember\AbstractGenerateMemberCodeFixProvider.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<GetCodeActionsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
@jcouv Is this still relevant?  property-patterns have already shipped at thsi point.

**Comment by jcouv** [comment]
No longer repros. Closing. Thanks for the ping
