### ISSUE TITLE
VB Extract Method: Fails asserts inside With blocks

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#2662]
1. select the expression within [| and |] and invoke Extract method.
2. Lots of assert fails in debug builds. 
3. No crash in release builds. the entire With block is extracted to a new method. 

```VB
Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Runtime.CompilerServices

Module Program
    Sub Main(args As String())

    End Sub
    Private Sub AddCustomer()
        Dim theCustomer As New Customer

        With theCustomer
            .Name = "Abc"
            .URL = "http://www.microsoft.com/"
            .City = "Redmond"
            .Print(.[|Name|])
        End With

        With theCustomer.Comments
            .Add("First comment.")
            .Add("Second comment.")
        End With

    End Sub

    <Extension()>
    Public Sub Print(ByVal cust As Customer, str As String)
        Console.WriteLine(str)
    End Sub

    Public Class Customer
        Public Property Name As String
        Public Property City As String
        Public Property URL As String

        Public Property Comments As New List(Of String)
    End Class
End Module
```
Call stack:
~~~
System.Exception: New bound node does not match existing bound node 
5/11/2015 5:32:12 PM
Source:    
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.SemanticModelMapsBuilder.GuardedCacheBoundNodes(BoundNode root, MemberSemanticModel semanticModel, SmallDictionary`2 nodeCache, VisualBasicSyntaxNode thisSyntaxNodeOnly) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 2056
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GuardedIncrementalBind(VisualBasicSyntaxNode bindingRoot, Binder enclosingBinder) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 1849
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 1762
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 141
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundRoot() in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 87
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.CreateRegionAnalysisContext(StatementSyntax firstStatement, StatementSyntax lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1900
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.AnalyzeDataFlow(StatementSyntax firstStatement, StatementSyntax lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1493
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.AnalyzeDataFlowCore(SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3314
   at Microsoft.CodeAnalysis.SemanticModel.AnalyzeDataFlow(SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 656
   at Microsoft.CodeAnalysis.ModelExtensions.AnalyzeDataFlow(SemanticModel semanticModel, SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\Extensions.cs:line 170
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.ContainsAllStaticLocalUsagesDefinedInSelectionIfExist(SelectionInfo selectionInfo, SemanticModel semanticModel, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 202
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.CheckErrorCasesAndAppendDescriptions(SelectionInfo selectionInfo, SemanticModel semanticModel, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 126
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.VB$StateMachine_4_GetValidSelectionAsync.MoveNext() in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 35
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.GetValidSelectionAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.<ExtractMethodAsync>d__2.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\ExtractMethod\AbstractExtractMethodService.cs:line 30
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodService.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\Core\ExtractMethod\ExtractMethodService.cs:line 15
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.<GetCodeActionAsync>d__2.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 63
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.GetCodeActionAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.<ComputeRefactoringsAsync>d__1.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 48
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 146
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan state, CodeRefactoringProvider provider, IExtensionManager extensionManager, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass7_1.<<GetRefactoringsAsync>b__0>d.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 109
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass7_1.<GetRefactoringsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

StackTrace: 


System.Exception: ASSERT FAILED 
5/11/2015 5:32:12 PM
Source:
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.SemanticModelMapsBuilder.GuardedCacheBoundNodes(BoundNode root, MemberSemanticModel semanticModel, SmallDictionary`2 nodeCache, VisualBasicSyntaxNode thisSyntaxNodeOnly) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 2053
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GuardedIncrementalBind(VisualBasicSyntaxNode bindingRoot, Binder enclosingBinder) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 1849
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 1762
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 141
   at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundRoot() in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Binding\MemberSemanticModel.vb:line 87
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.CreateRegionAnalysisContext(StatementSyntax firstStatement, StatementSyntax lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1900
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.AnalyzeDataFlow(StatementSyntax firstStatement, StatementSyntax lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1493
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.AnalyzeDataFlowCore(SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3314
   at Microsoft.CodeAnalysis.SemanticModel.AnalyzeDataFlow(SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 656
   at Microsoft.CodeAnalysis.ModelExtensions.AnalyzeDataFlow(SemanticModel semanticModel, SyntaxNode firstStatement, SyntaxNode lastStatement) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\Extensions.cs:line 170
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.ContainsAllStaticLocalUsagesDefinedInSelectionIfExist(SelectionInfo selectionInfo, SemanticModel semanticModel, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 202
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.CheckErrorCasesAndAppendDescriptions(SelectionInfo selectionInfo, SemanticModel semanticModel, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 126
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.VB$StateMachine_4_GetValidSelectionAsync.MoveNext() in E:\Roslyn\Main\Open\src\Features\VisualBasic\ExtractMethod\VisualBasicSelectionValidator.vb:line 35
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.VisualBasic.ExtractMethod.VisualBasicSelectionValidator.GetValidSelectionAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.<ExtractMethodAsync>d__2.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\ExtractMethod\AbstractExtractMethodService.cs:line 30
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodService.ExtractMethodAsync(Document document, TextSpan textSpan, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\Core\ExtractMethod\ExtractMethodService.cs:line 15
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.<GetCodeActionAsync>d__2.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 63
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.GetCodeActionAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.<ComputeRefactoringsAsync>d__1.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 48
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.AbstractExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 146
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan state, CodeRefactoringProvider provider, IExtensionManager extensionManager, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass7_1.<<GetRefactoringsAsync>b__0>d.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\CodeRefactorings\CodeRefactoringService.cs:line 109
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass7_1.<GetRefactoringsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
~~~

**Comment by Pilchie** [comment]
Moving to compiler for the asserts.  IDE is willing to live with the selection expansion to the whole with block for RTM.

**Comment by AlekseyTs** [comment]
@balajikris Please verify.
