### ISSUE TITLE
Nullable Reference Types Preview installation failed.

### ISSUE THREAD

**Issue by LYP951018** [dotnet/roslyn#26791]
**Version Used**: 
The [latest 05/07/18] version.
**Steps to Reproduce**:

1. Run install.bat.

**Expected Behavior**:
Output installed successful.

**Actual Behavior**:

```
Could not find a part of the path 'C:\Users\yelpliu\AppData\Local\Microsoft\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Roslyn.Compilers.Extension.VisualStudio.15.0_9e4224ea.props'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\yelpliu\AppData\Local\Microsoft\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Roslyn.Compilers.Extension.VisualStudio.15.0_9e4224ea.props'.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
    at Microsoft.PowerShell.Commands.FileSystemContentReaderWriter.CreateStreams(String filePath, String streamName, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Encoding fileEncoding)
    at Microsoft.PowerShell.Commands.FileSystemProvider.GetContentWriter(String path)
    at Write-CompilerPropsFileXml, F:\Roslyn_Nullable_References_Preview_05072018.2\tools\utils.ps1: line 229
    at Copy-CompilerVsix, F:\Roslyn_Nullable_References_Preview_05072018.2\tools\utils.ps1: line 187
    at <ScriptBlock>, F:\Roslyn_Nullable_References_Preview_05072018.2\tools\install.ps1: line 52
```

**Comment by KathleenDollard** [comment]
I just tested the new (5/14/2018) version on the wiki for nullable. 

Install succeeds. It seems to work. 

It's late here so I'm off until tomorrow. 

I would love if the CSharp 8 other features (pattern matching) was also fixed so I can use it in tomorrow's talk. 

Thank you!

**Comment by jmarolf** [comment]
the [nullable preview](https://github.com/dotnet/csharplang/wiki/Nullable-Reference-Types-Preview) got updated with the fix.  I'll close this once the fix for the C# patterns and ranges preview is up

**Comment by nawuko** [comment]
Can confirm, installing & working just fine now.

**Comment by jmarolf** [comment]
the [C# patterns and ranges preview](https://github.com/dotnet/csharplang/wiki/vNext-Preview) has also been updated.

**Comment by KathleenDollard** [comment]
This is fixed for me with the new bits.
