### ISSUE TITLE
Misc build failures in 'prodcon/roslyn/master/' - '20180510.01'

### ISSUE THREAD

**Issue by jcagme** [dotnet/roslyn#26842]
@dotnet-mc-bot commented on [Thu May 10 2018](https://github.com/dotnet/core-eng/issues/3453)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1674737
  - **Agent:** DDMBLDW132
  - **Error log:** 1>E:\A\_work\0\s\src\Tools\MicroBuild\Build.proj(0,0): error MSB3073: The command "powershell -noprofile -executionPolicy ByPass -file E:\A\_work\0\s\src\Tools\MicroBuild\microbuild.ps1 -restore -official -platform -branch refs/he...

@jcagme, @markwilkie

---

@jcagme commented on [Thu May 10 2018](https://github.com/dotnet/core-eng/issues/3453#issuecomment-388092589)

There were some test failures during this build. FYI @mmitche 

---

@jcagme commented on [Mon May 14 2018](https://github.com/dotnet/core-eng/issues/3453#issuecomment-388862688)

Hit++: https://github.com/dotnet/core-eng/issues/3482

FYI: @jaredpar @mmitche 

---

@jaredpar commented on [Mon May 14 2018](https://github.com/dotnet/core-eng/issues/3453#issuecomment-388865494)

@jasonmalinowski looks like an IDE failure here 

``` txt
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at MS.Internal.WeakEventTable.OnShutDown()
   at MS.Internal.WeakEventTable.WeakEventTableShutDownListener.OnShutDown(Object target, Object sender, EventArgs e)
   at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```

**Comment by jaredpar** [comment]
Why are multiple bugs getting opened for the same issue?

**Comment by jcagme** [comment]
I just moved the issue which was originally created in core-eng to this repo. The other one is now closed so it is just one

**Comment by jasonmalinowski** [comment]
@jaredpar Hmm, at least that given stack has nothing our team owns on it. Do we have dumps or something else we can look at?

**Comment by jcagme** [comment]
Hit++. https://github.com/dotnet/roslyn/issues/26842

**Comment by jcagme** [comment]
Hit++. https://github.com/dotnet/core-eng/issues/3495

**Comment by jcagme** [comment]
One more. https://github.com/dotnet/core-eng/issues/3504

**Comment by jaredpar** [comment]
@jasonmalinowski this looks like yet another case where procdump won't produce a dump file even though the process clearly exits with an exception. The most recent run has procdump running and this type of crash doesn't register as a dump worth event. There is also no other exception we can hook into here. 

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1696171&tab=artifacts

I'm not sure how to proceed with this but it seems like it's a prodcon blocker at the moment.

**Comment by jaredpar** [comment]
@jasonmalinowski test takes ~1 minute to run and generates ~1,350 exceptions in that minute. 

Honestly I'm not sure we can do what you're suggestion. It's unclear from the stack which AppDomain this is even occurring in. If it's AppDomain 0 then not sure we can escape to that easily. If it's in AppDomain 1 then we could hook shutdown I guess and forcibly clear the table ourselves.

**Comment by jasonmalinowski** [comment]
My assumption here is there's some exception we leaked which is getting reraised here. And yes I have zero idea which AppDomain this is happening in. But I don't have a better idea, so...

**Comment by jaredpar** [comment]
@jasonmalinowski don't think that is the case. I spent a bit of time digging around the WeakEvent table implementation this morning. Based on the reading it seems they are timing out in their call to `Dispatcher.Invoke`. I don't know if it's because we have so much in the queue that they don't have time to process. But at a glance it appears to be a cancellation due to timeout on their end.

**Comment by jasonmalinowski** [comment]
@sharwell did add some code that generally ensures we have queued work completed prior to starting another test. Maybe we need to check that code then?

**Comment by 333fred** [comment]
Looks like I just hit this on this PR: https://github.com/dotnet/roslyn/pull/27873
Job Link: https://ci.dot.net/job/dotnet_roslyn/job/features_null-operator-enhancements/job/windows_debug_spanish_unit32_prtest/4/
(After translating, the stack is the same)
