### ISSUE TITLE
NullReferenceException in VisualBasicMakeFieldReadonlyCodeFixProvider

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn#26850]
**Repro steps**:
1. Create a VB console app.
2. Declare a variable without a type: `Dim age`
3. Press **Ctrl**+**.** or open the Quick Actions menu.

**Expected result**:
To be able to choose the 'Add readonly modifier' refactoring from the Quick Actions menu.

**Actual result**:
A yellow message bar appears saying that 'VisualBasicMakeFieldReadonlyCodeFixProvider' encountered an error and has been disabled. The stack trace is:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.<>c.<MakeFieldReadonlyAsync>b__6_0(TSymbolSyntax g)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at async Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.MakeFieldReadonlyAsync[TSymbolSyntax,TFieldDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.FixWithEditorAsync[TSymbolSyntax,TFieldDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jinujoseph** [comment]
cc @sharwell ,
