### ISSUE TITLE
Incorrect assumptions are made in Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddLiteralValue

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#26895]
Type of the literal doesn't have to match type of the parameter. See 
```
        Protected Overrides Sub AddLiteralValue(type As SpecialType, value As Object)
            Debug.Assert(value.GetType().GetTypeInfo().IsPrimitive OrElse TypeOf value Is String OrElse TypeOf value Is Decimal OrElse TypeOf value Is DateTime)

            Select Case type
                Case SpecialType.System_String
                    SymbolDisplay.AddSymbolDisplayParts(builder, DirectCast(value, String))

                Case SpecialType.System_Char
                    SymbolDisplay.AddSymbolDisplayParts(builder, DirectCast(value, Char))

                Case Else
                    Dim valueString = SymbolDisplay.FormatPrimitive(value, quoteStrings:=True, useHexadecimalNumbers:=False)
                    Me.builder.Add(CreatePart(SymbolDisplayPartKind.NumericLiteral, Nothing, valueString, False))
            End Select
        End Sub
```

See StringWithOptionalDateTimeValue function in Microsoft.CodeAnalysis.VisualBasic.UnitTests.Emit.OptionalArgumentsTests.TestStringWithOptionalDateTimeValue unit-test

**Comment by AlekseyTs** [comment]
This issue causing an InvalidCastException for symbols used in Microsoft.CodeAnalysis.VisualBasic.UnitTests.Emit.OptionalArgumentsTests.TestStringWithOptionalDateTimeValue unit-test:
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Emit.OptionalArgumentsTests.TestStringWithOptionalDateTimeValue' failed:
	System.InvalidCastException : Unable to cast object of type 'System.DateTime' to type 'System.String'.
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor_Constants.vb(23,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddLiteralValue(SpecialType type, Object value)
	f:\GitHub\roslyn2\roslyn\src\Compilers\Core\Portable\SymbolDisplay\AbstractSymbolDisplayVisitor.cs(94,0): at Microsoft.CodeAnalysis.SymbolDisplay.AbstractSymbolDisplayVisitor.AddNonNullConstantValue(ITypeSymbol type, Object constantValue, Boolean preferNumericValueOrExpandedFlagsForEnum)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor_Constants.vb(39,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddConstantValue(ITypeSymbol type, Object constantValue, Boolean preferNumericValueOrExpandedFlagsForEnum)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor.Members.vb(511,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitParameter(IParameterSymbol symbol)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\Symbols\ParameterSymbol.vb(338,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.ParameterSymbol.Accept(SymbolVisitor visitor)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor.Members.vb(621,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddParametersIfRequired(Boolean isExtensionMethod, ImmutableArray`1 parameters)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor.Members.vb(377,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddMethodParameters(IMethodSymbol method)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplayVisitor.Members.vb(194,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitMethod(IMethodSymbol symbol)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\Symbols\MethodSymbol.vb(1065,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol.Accept(SymbolVisitor visitor)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplay.vb(106,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplay.vb(61,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol, SymbolDisplayFormat format)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\SymbolDisplay\SymbolDisplay.vb(25,0): at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayString(ISymbol symbol, SymbolDisplayFormat format)
	f:\GitHub\roslyn2\roslyn\src\Compilers\VisualBasic\Portable\Symbols\Symbol.vb(1168,0): at Microsoft.CodeAnalysis.VisualBasic.Symbol.ISymbol_ToDisplayString(SymbolDisplayFormat format)
```
