### ISSUE TITLE
NRE from DocumentationCommentExtensions.IsMultilineDocComment

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#27223]
[VS Feedback issue](https://developercommunity.visualstudio.com/content/problem/229613/nullreferenceexception-in-ismultilinedoccomment.html)

Repro:

Create a console app, place cursor in line 10 between `<summary>` and `</summary>`, hit enter.

```C#
namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            const string code = @"
class Program
{
    /// <summary></summary>
    static void Main(string[] args)
    {
    }
}
";
        }
    }
}
```

Stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.CodeAnalysis.CSharp.Extensions.DocumentationCommentExtensions.IsMultilineDocComment(DocumentationCommentTriviaSyntax documentationComment)
 at Microsoft.CodeAnalysis.Editor.CSharp.DocumentationComments.DocumentationCommentCommandHandler.IsMultilineDocComment(DocumentationCommentTriviaSyntax documentationComment)
 at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.TryGenerateExteriorTriviaAfterEnter(SyntaxTree syntaxTree, SourceText text, Int32 position, Int32 originalPosition, ITextBuffer subjectBuffer, ITextView textView, DocumentOptionSet options, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.InsertOnEnterTyped(SyntaxTree syntaxTree, SourceText text, Int32 position, Int32 originalPosition, ITextBuffer subjectBuffer, ITextView textView, DocumentOptionSet options, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.CompleteComment(ITextBuffer subjectBuffer, ITextView textView, Int32 originalCaretPosition, Func`9 insertAction, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.DocumentationComments.AbstractDocumentationCommentCommandHandler`2.ExecuteCommand(ReturnKeyCommandArgs args, CommandExecutionContext context)
 at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
 at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) 
```

**Comment by tmat** [comment]
@jinujoseph FYI

**Comment by jinujoseph** [comment]
related to https://github.com/dotnet/roslyn/issues/25746
