### ISSUE TITLE
NRE in CSharpUseImplicitTypeHelper.AssignmentSupportsStylePreference

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#27221]
Got the following NRE while editing some broken code in Roslyn.sln, I don't have repro steps:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Utilities.CSharpUseImplicitTypeHelper.AssignmentSupportsStylePreference(SyntaxToken identifier,TypeSyntax typeName,ExpressionSyntax initializer,SemanticModel semanticModel,OptionSet optionSet,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Utilities.CSharpUseImplicitTypeHelper.TryAnalyzeVariableDeclaration(TypeSyntax typeName,SemanticModel semanticModel,OptionSet optionSet,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.CodeRefactorings.UseType.AbstractUseTypeCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi

**Comment by jinujoseph** [comment]
Same as https://github.com/dotnet/roslyn/issues/26735 ?

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Could likely be a duple.  From looking at the method my best guess is that it's:

```c#
            var declaredType = semanticModel.GetTypeInfo(typeName, cancellationToken).Type;
            if (declaredType != null && declaredType.TypeKind == TypeKind.Dynamic)
            {
                return false;
            }
//...

                return declaredType.Equals(initializerType);
```

It seems quite possible that declaredType could be null.  Then, we would NRE several lines lower.  

Note: i really didn't do anything with this metohd.  It was just a move from here:
https://github.com/dotnet/roslyn/pull/25865/files#diff-843b2b95dec3ec4b6e5786077c4a455bL197

I'm happy to assist with it, but it's been effectively the same code for a while.

**Comment by jcouv** [comment]
Found a repro. I'll go ahead with a fix.

Repro:
```C#
class C1
{
    ref int N() => throw null;
    public void M()
    {

        ref var x = N();
    }
}
```

**Comment by ivanbasov** [comment]
I could not find any related Watson for this issue.

**Comment by jcouv** [comment]
Fix is ready for review (#27246). Thanks

**Comment by jcouv** [comment]
Fixed in 15.8 preview 3.

**Comment by jinujoseph** [comment]
Another example which causes this 
class Program
    {
        static void Main(string[] args)
        {
            int[] variableParams = new int[2];
            ref int variableParams[0] = ref parameters.EnemyAttackAdjust[0];
        }
    }

from [link](https://developercommunity.visualstudio.com/content/problem/261228/vs-crash-when-removing-ref-int.html)

**Comment by jcouv** [comment]
Re-opened. I need to verify this ref re-assignment case as well.

**Comment by jcouv** [comment]
Verified the additional scenario in test. Closing again.
