### ISSUE TITLE
VerificationException due to read-only struct use

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#27382]
**Related issues**:

These are all closed, and as this is a pretty nasty and hard-to-track-down issue (you only find out it's a problem when running from full framework, and it's not at all obvious what causes it) I thought it better to raise the issue than stay quiet...

- #22485 ("Cannot change initonly field outside its .ctor regression")
- #22707 (VerificationException when using 15.5 preview)
- #22712 ("Consider switching to peverify-compat automatically when APTCA or similar attributes are used")

**Version Used**:  Visual Studio 15.7.3; from the command line, csc reports version 2.8.3.62923 (7aafab56)

**Steps to Reproduce**:

1. Create a class library targeting just .NET Standard 2.0

Project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <!--<Features>peverify-compat</Features> -->
  </PropertyGroup>
</Project>
```

Code:

```csharp
[assembly: System.Security.AllowPartiallyTrustedCallers]

namespace Library
{
    public readonly struct OuterStruct
    {
        private readonly ValueHolder implementation;

        public int Value => implementation.Value;

        public OuterStruct(int value) => implementation = new ValueHolder(value);
    }

    internal readonly struct ValueHolder
    {
        internal int Value { get; }

        internal ValueHolder(int value) => Value = value;
    }
}
``` 

2. Create a console app targeting the full framework, with a reference:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>
</Project>
```

Code:

```csharp
using Library;
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var outer = new OuterStruct(100);
            Console.WriteLine(outer.Value);
        }
    }
}
```

3. Run! 

**Expected Behavior**:

Prints 100.

**Actual Behavior**:

```text
Unhandled Exception: System.Security.VerificationException: Operation could destabilize the runtime.
   at Library.OuterStruct.get_Value()
   at ConsoleApp.Program.Main(String[] args)
```

Workarounds:

- Remove AllowPartiallyTrustedCallers
- Use the peverify-compat feature

What I would like to see:

- A warning when the compiler detects that it's emitting non-verifiable code that could easily break full frameworks calling it
- A good docs page that gives guidance to library developers as to which of these workarounds to use

**Comment by jcouv** [comment]
Tagging @jaredpar for thoughts

**Comment by jaredpar** [comment]
> A warning when the compiler detects that it's emitting non-verifiable code that could easily break full frameworks calling it

The compiler is not really able to do this in a general sense. The peverify tool, on which verification is based, is based on ECMA355 but it's not a rigorous implementation of it. Additionally different peverify instances enforce different verification rules. This is particularly noticeable between the various JIT implementations (LegacyJIT vs. JIT64). @VSadov used to upset me by showing examples where they differ. 

Hence this isn't a rule we can strictly implement as there is no official standard to go by. We could of course take the most pessimistic view of all known peverify implementations but even that produces undesirable behaviors.  Concretely here are some problems that would come with that: 

- There are many corlibs out there besides the official ones and very few of them are named mscorlib. This is a peverify violation as it enforces corlib must be called mscorlib (implied strongly by Partition IV). Hence this would be a compat break as all these corlibs would now compile with a warning.
- The compiler would be forced to issue a warning when compiling every single netstandard or netcoreapp project out there. For those projects corlib is named netstandard.dll and hence peverify is going to issue error virtually every single time (csc.dll has ~20 of them last time I checked). 

That being said though the compiler does not emit known verification errors by default (other than the mscorlib one). The developer must take the explicit action of specifying LangVersion to be 7.2 (or higher). At that point the developer has opted into language features which aren't compatible with any peverify instance: `readonly structs`, `in` parameters, `Span<T>`, ref returns, etc ...  Hence the compiler will necessarily emit patterns that don't pass verification.

Part of the problem here is that peverify is a fixed and fractured standard to target yet the runtime and language are constantly evolving. This is why the compiler team has been investing in [ILVerify](https://github.com/dotnet/corert/tree/master/src/ILVerify). This is a managed implementation of verification that we can adapt as the language and runtime evolve. It's still a work in progress but we're almost at the point where the compiler test suites can fully move over to using it instead of peverify. 

Note: it can be argued that ECMA355 doesn't actually strictly say corlib must be named mscorlib. Still though peverify enforces that and hence it's necessary to consider if you want to avoid all verification errors. 

> A good docs page that gives guidance to library developers as to which of these workarounds to use

I will try and turn the discussion here into a good doc on the issue.

**Comment by jskeet** [comment]
Thanks for the detailed reply. I think the problem is that it's not clear - at least, it certainly wasn't clear to me - that opting into readonly structs, in parameters etc would be incompatible with peverify. While users have to manually opt into C# 7.2 at the moment, I *assume* that when C# 8 is released, that will be the default - so users will be able to use the C# 7.2 features without any barrier at all.

What was alarming to me here was that at no stage did I do anything that I'd considered "dangerous" - and yet I ended up with a library which couldn't be used from the full desktop framework (even the most recent version), with no indication.

It's possible that this will hardly affect anyone - my guess is that *relatively* few library authors as specifying AllowPartiallyTrustedCallers in the first place, which seems to be at least part of the trigger for problems. (This is an area I know very little about.)

It might be instructive to analyze all "active" NuGet packages (e.g. those released in the last year) to see how many specify APTCA. I would *hope* that many NuGet packages will move to target netstandard in the future, and that many of them will use C# 7.2 features over time - so getting an idea of the scale of the potential problem would be useful. Does MS already have helpful infrastructure that makes this sort of analysis simple?

**Comment by jaredpar** [comment]
> I assume that when C# 8 is released, that will be the default - so users will be able to use the C# 7.2 features without any barrier at all.

Indeed and you're correct at that point it will only require a single action to get the behavior: using one of the features that triggers a verification error. It's more explicit in some cases and less in others. 

> It's possible that this will hardly affect anyone - my guess is that relatively few library authors as specifying AllowPartiallyTrustedCallers in the first place, which seems to be at least part of the trigger for problems. 

This was definitely part of our consideration. It's really the only case that gets affected by this change. So far it's mostly played out. We've had < 5 total reports of this problem. In most cases the developers simply removed the attribute altogether as it wasn't really a feature they were deliberately using. 

> Does MS already have helpful infrastructure that makes this sort of analysis simple?

Simple no :). But we looked into this a bit before we made the change using the analysis we did have available. The analysis indicated the combination which is problematic was quite low in practice. All together that meant we had the following:

1. The problematic pattern appears to be in very low use.
1. The new C# 7.2 features require an explicit opt-in and hence it won't be a simple "upgrade and it breaks" type of issue. 
1. This exact break already happened in 7.0 via ref returns (oops) and so far we hadn't seen any reports of it. At the same time this is a much smaller feature hence that's not a great indicator. 

Taken together we decided to ship as we did (explicit opt-in via language version) and let actual customer feedback inform how we approach C# 8.0 + NS3.0 where there is one less opt-in step. 

If we did take action here it would likely be in the form of an analyzer. The type of analysis being done (what TF in combination with a series of attributes and their values) is more appropriate for an analyzer than the compiler.

**Comment by jskeet** [comment]
An analyzer does feel like a reasonable solution. I appreciate the complexity and trade-offs involved here - I'm not exactly an unbiased observer, having been hit by it :)

(Random thought: it would be useful to have a way of running analyzers against NuGet packages and raising issues against the affected projects, if possible.)

**Comment by PetSerAl** [comment]
Shorter repro case:
```csharp
using System;
using System.Security;
[assembly:SecurityTransparent]
static class Test {
    readonly struct S {
        public void M() { }
    }
    static readonly S s;
    static void Main() => s.M();
}
```

**Comment by mletterle** [comment]
This is now default behavior on VS2019, so maybe worth revisiting. I ran into this when updating a project to use .NET 4.8 and NetStandard. Use to rely on peverify to ensure valid output, guess that's the end of that...
