### ISSUE TITLE
Unreachable exception with async-foreach

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#27651]
`Unexpected value 'ForEachStatement' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'`

```C#
   at Microsoft.CodeAnalysis.CSharp.ExitPointsWalker.LeaveRegion() in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ExitPointsWalker.cs:line 149
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 290
   at Microsoft.CodeAnalysis.CSharp.AbstractRegionControlFlowPass.Visit(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractRegionControlFlowPass.cs:line 27
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitStatement(BoundStatement statement) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 622
   at Microsoft.CodeAnalysis.CSharp.ControlFlowPass.VisitStatement(BoundStatement statement) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ControlFlowPass.cs:line 230
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitStatements(ImmutableArray`1 statements) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 1178
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitBlock(BoundBlock node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 1170
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 2372
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 147
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 301
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 290
   at Microsoft.CodeAnalysis.CSharp.AbstractRegionControlFlowPass.Visit(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractRegionControlFlowPass.cs:line 27
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitMethodBodies(BoundBlock blockBody, BoundBlock expressionBody) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 2815
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 2785
   at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 6361
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 147
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 301
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 290
   at Microsoft.CodeAnalysis.CSharp.AbstractRegionControlFlowPass.Visit(BoundNode node) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractRegionControlFlowPass.cs:line 27
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Scan(Boolean& badRegion) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\PreciseAbstractFlowPass.cs:line 370
   at Microsoft.CodeAnalysis.CSharp.ControlFlowPass.Scan(Boolean& badRegion) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ControlFlowPass.cs:line 117
   at Microsoft.CodeAnalysis.CSharp.ExitPointsWalker.Analyze(Boolean& badRegion) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ExitPointsWalker.cs:line 60
   at Microsoft.CodeAnalysis.CSharp.ExitPointsWalker.Analyze(CSharpCompilation compilation, Symbol member, BoundNode node, BoundNode firstInRegion, BoundNode lastInRegion) in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ExitPointsWalker.cs:line 46
   at Microsoft.CodeAnalysis.CSharp.CSharpControlFlowAnalysis.get_ExitPoints() in D:\repos\roslyn3\src\Compilers\CSharp\Portable\FlowAnalysis\ControlFlowAnalysis.cs:line 59
   at Microsoft.CodeAnalysis.ExtractMethod.SelectionValidator.IsFinalSpanSemanticallyValidSpan(SemanticModel semanticModel, TextSpan textSpan, Tuple`2 range, CancellationToken cancellationToken) in D:\repos\roslyn3\src\Features\Core\Portable\ExtractMethod\SelectionValidator.cs:line 63
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.<GetValidSelectionAsync>d__1.MoveNext() in D:\repos\roslyn3\src\Features\CSharp\Portable\ExtractMethod\CSharpSelectionValidator.cs:line 67
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.<ExtractMethodAsync>d__2.MoveNext() in D:\repos\roslyn3\src\Features\Core\Portable\ExtractMethod\AbstractExtractMethodService.cs:line 42
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.<GetCodeActionAsync>d__1.MoveNext() in D:\repos\roslyn3\src\Features\Core\Portable\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.<ComputeRefactoringsAsync>d__0.MoveNext() in D:\repos\roslyn3\src\Features\Core\Portable\CodeRefactorings\ExtractMethod\AbstractExtractMethodCodeRefactoringProvider.cs:line 47
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext() in D:\repos\roslyn3\src\Features\Core\Portable\CodeRefactorings\CodeRefactoringService.cs:line 143
```

I've hit this in the IDE by selecting some code that includes an async-foreach.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/28218
