### ISSUE TITLE
Assert in CodeGenerator.EmitConversionExpression

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#2774]
```VB
            Const source = "
Imports System.Linq

Class C
    Sub M(args As String())
        Dim concat =
            From x In args
            Let y = x.ToString()
            Let z = x.GetHashCode()
            Select x & y & z
    End Sub
End Class
"

            Dim comp = CreateCompilationWithMscorlib({source}, {SystemCoreRef}, TestOptions.DebugDll)
            comp.VerifyEmitDiagnostics()
```

```
Debug.Assert() Failure
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitConversion.vb(189,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitConversionExpression(BoundConversion conversion, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitExpression.vb(58,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitExpression.vb(478,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitExpression.vb(1007,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitExpression.vb(40,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\CodeGenerator.vb(211,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitSequencePointExpression(BoundSequencePointExpression node, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitExpression.vb(100,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitStatement.vb(868,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitReturnStatement(BoundReturnStatement boundReturnStatement)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitStatement.vb(38,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitStatement.vb(1200,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitBlock(BoundBlock scope)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\EmitStatement.vb(16,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\CodeGenerator.vb(144,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.GenerateImpl()
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\CodeGen\CodeGenerator.vb(88,0): at Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.Generate()
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(1523,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean generateDebugInfo)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(961,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(746,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol, Predicate`1 filter)
   F:\Enlistments\roslyn\Src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(515,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__31-0._Lambda$__0()
```

**Comment by amcasey** [comment]
If you add an additional reference, ```MsvbRef```, the assert goes away.  I suspect we're missing a diagnostic (which *is* reported if you evaluate ```x & y & z``` outside a query).

**Comment by amcasey** [comment]
FYI @VSadov

**Comment by AlekseyTs** [comment]
@amcasey Please verify.

**Comment by amcasey** [comment]
Now reports an appropriate diagnostic: ```Diagnostic(ERRID.ERR_MissingRuntimeHelper, "z").WithArguments("Microsoft.VisualBasic.CompilerServices.Conversions.ToString").WithLocation(10, 28)```

Verified in master after integration from stabilization.
