### ISSUE TITLE
How to use the Create-API  in namespace "CSharpScript"?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#27782]
```C#
 var script = CSharpScript.Create<Action>(
     code, 
     ScriptOptions.Default.AddReferences(Assembly.GetEntryAssembly()),
     typeof(MyClass)
);
 script.Compile();
 return script.CreateDelegate();
```

Error:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The script requires access to global variables but none were given
Parameter name: globals
   at Microsoft.CodeAnalysis.Scripting.Script`1.ValidateGlobals(Object globals, Type globalsType) in /_/src/Scripting/Core/Script.cs:line 560
   at Microsoft.CodeAnalysis.Scripting.Script`1.<>c__DisplayClass18_0.<CreateDelegate>b__0(Object globals, CancellationToken token) in /_/src/Scripting/Core/Script.cs:line 482
```

**Comment by NMSAzulX** [comment]
I think I can slove it ..
