### ISSUE TITLE
[Regression] Visual Studio crashes if you reopen Options with the code style page open

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27820]
**Version Used**: 
15.8.0 Preview 3.0 [27807.3004.d15.8stg] & 15.8.0 Preview 3.0 [27812.3003.d15.8stg]

This does not repo in 15.8 Preview 2.0, however, is a 100% repro in the builds above.

**Steps to Reproduce**:

1. Tools -> Options -> Text Editor -> C# -> Code Style
2. Click OK
3. Tools -> Options

-- Crash --

src\Editor\Text\Impl\WpfView\WpfTextView.cs

``` C#
       IWpfTextViewLine IWpfTextView.GetTextViewLineContainingBufferPosition(SnapshotPoint bufferPosition)
        {
            if (_textViewLinesCollection == null)
                throw new InvalidOperationException("GetTextViewLineContainingBufferPosition called before view is fully initialized.");

            if (_isClosed)
                throw new InvalidOperationException("GetTextViewLineContainingBufferPosition called after the view is closed"); <!-- Throws
```

```
>	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Microsoft.VisualStudio.Text.Editor.IWpfTextView.GetTextViewLineContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint bufferPosition) Line 942	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.GetTextViewLineContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint bufferPosition) Line 933	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.ContainingTextViewLine.get() Line 77	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.IsWithinViewport.get() Line 112	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.AccessibleCaret.OnViewVisibilityChanged(object sender, System.Windows.DependencyPropertyChangedEventArgs e) Line 109	C#
 	PresentationCore.dll!System.Windows.UIElement.RaiseDependencyPropertyChanged(System.Windows.EventPrivateKey key, System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e) Line 1567	C#
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual v, System.Windows.DependencyProperty property)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty property)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject d, System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs e)	Unknown
 	WindowsBase.dll!System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.UpdateIsVisibleCache()	Unknown
 	PresentationCore.dll!System.Windows.PresentationSource.RootChanged(System.Windows.Media.Visual oldRoot, System.Windows.Media.Visual newRoot)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisualInternal.set(System.Windows.Media.Visual value)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisual.set(System.Windows.Media.Visual value)	Unknown
 	WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.OnHandleCreated.AnonymousMethod__54_0()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Action callback, System.Windows.Threading.DispatcherPriority priority, System.Threading.CancellationToken cancellationToken, System.TimeSpan timeout)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Action callback)	Unknown
 	WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.OnHandleCreated(System.EventArgs e)	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.UIElementDialogPage.DialogPageElementHost.OnHandleCreated(System.EventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmCreate(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.UIElementDialogPage.DialogPageElementHost.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	user32.dll!738bbe6b()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	Unknown
 	user32.dll!738b833a()	Unknown
 	user32.dll!738b7eda()	Unknown
 	user32.dll!738baad3()	Unknown
 	ntdll.dll!_KiUserCallbackDispatcher@12() Line 517	Unknown
 	win32u.dll!74d1321c()	Unknown
 	user32.dll!738b273d()	Unknown
 	ntdll.dll!_ZwQueryAttributesFile@8() Line 585	Unknown
 	ntdll.dll!LdrpGetNtPathFromDosPath(const _UNICODE_STRING * DosPath, _LDRP_FILENAME_BUFFER * NtPath) Line 2880	C
 	System.Windows.Forms.ni.dll!52131b7f()	Unknown
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.UnsafeNativeMethods.CreateWindowEx(int dwExStyle, string lpszClassName, string lpszWindowName, int style, int x, int y, int width, int height, System.Runtime.InteropServices.HandleRef hWndParent, System.Runtime.InteropServices.HandleRef hMenu, System.Runtime.InteropServices.HandleRef hInst, object pvParam)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams cp)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateHandle()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Handle.get()	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.DialogPage.System.Windows.Forms.IWin32Window.Handle.get()	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.GetPropertyPage(ref System.Guid rguidPage, Microsoft.VisualStudio.Shell.Interop.VSPROPSHEETPAGE[] ppage)	Unknown

```

**Comment by davkean** [comment]
This also crashed while I was using the page:

```
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Microsoft.VisualStudio.Text.Editor.IWpfTextView.GetTextViewLineContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.GetTextViewLineContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint)
   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_ContainingTextViewLine()
   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_IsWithinViewport()
   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.AccessibleCaret.OnViewVisibilityChanged(System.Object, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.RaiseDependencyPropertyChanged(System.Windows.EventPrivateKey, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)

```

**Comment by olegtk** [comment]
Likely editor bug given "MultiSelection" on the call stack, please route to us.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633808.
