### ISSUE TITLE
Unhandled compiler exception when converting a delegate creation expression involving a dynamic expression

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#27927]
```csharp
(Expression<Func<dynamic, Func<int>>>)(d => new Func<int>(d))
```

causes compiler error

```
System.InvalidOperationException: Unexpected value 'Sequence' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Expressions(ImmutableArray`1 expressions)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.DelegateCreation(BoundExpression receiver, MethodSymbol method, TypeSymbol delegateType, Boolean staticMember)
   at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitDelegateCreationExpression(BoundDelegateCreationExpression node)
```

**Comment by bartdesmet** [comment]
Too much lowering has taken place due to the lack of an earlier check in the diagnostics pass for expression tree conversion constraints.
