### ISSUE TITLE
IntroduceVariableCodeRefactoringProviderSystem.ArgumentOutOfRangeException : 'end' must not be less than 'start'

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#27949]
Had the following invalid code while refactoring:

``` C#

        public static ImageMoniker ApplicationPrivate = return new ImageMoniker { Guid = s_manifestGuid, Id = 0 };
        public static ImageMoniker ApplicationWarning = return new ImageMoniker { Guid = s_manifestGuid, Id = 1 };

        public static ImageMoniker CodeInformationPrivate = return new ImageMoniker { Guid = s_manifestGuid, Id = 2 };

        public static ImageMoniker CodeInformationWarning = return new ImageMoniker { Guid = s_manifestGuid, Id = 3 };

        public static ImageMoniker Component = return new ImageMoniker { Guid = s_manifestGuid, Id = 4 };

        public static ImageMoniker ComponentPrivate = return new ImageMoniker { Guid = s_manifestGuid, Id = 5 };

        public static ImageMoniker ComponentWarning = return new ImageMoniker { Guid = s_manifestGuid, Id = 6 };
        public static ImageMoniker ErrorSmall = return new ImageMoniker { Guid = s_manifestGuid, Id = 7 };
```

```
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.GetExpressionUnderSpan(SyntaxTree tree,TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.TryInitialize(TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.Generate(TService service,SemanticDocument document,TextSpan textSpan,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jinujoseph** [comment]
Reported at [DC]([url](https://developercommunity.visualstudio.com/content/problem/380143/intorducevariablecoderefactoringprovider-encounter.html))
