### ISSUE TITLE
Cannot build with latest master.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28003]
I'm getting the following:

```
12>------ Build started: Project: ServicesVisualStudio, Configuration: Debug Any CPU ------
12>VsdConfigTool.exe : error XAC9999: INTERNAL COMPILER ERROR. Unhandled exception (System.UnauthorizedAccessException).
12>--------------------------------------------------------------------------
12>Access to the path 'C:\Microsoft.VisualStudio.LanguageServices.vsdconfig' is denied.
12>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
12>   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
12>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
12>   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
12>   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
12>   at XapiConfigRuntime.Processor.Run(ProcessorArguments args)
12>   at VsdConfigTool.EntryPoint.Main(String[] args)
12>--------------------------------------------------------------------------
12>C:\GitHub\roslyn-internal\roslyn\build\Targets\Vsdconfig.targets(19,5): error MSB3073: The command ""C:\Users\cyrus\.nuget\packages\\Microsoft.VSSDK.BuildTools\15.8.68-develop-g109a00ff\tools\VSSDK\bin\vsdconfigtool.exe" "ManagedEditAndContinueService.vsdconfigxml" "C:\GitHub\roslyn-internal\roslyn\Binaries\Obj\ServicesVisualStudio\Debug\\Microsoft.VisualStudio.LanguageServices.dll" "\Microsoft.VisualStudio.LanguageServices.vsdconfig"" exited with code -1.
12>Done building project "ServicesVisualStudio_uue4jukm_wpftmp.csproj" -- FAILED.
```

Looks like something has been misconfigured, and a tool is trying to write directly into the C:\ drive.

This started recently.  I'm not sure if any authoring has changed in the last few days.

Tagging @sharwell @jmarolf for ideas here.  This totally blocks me currently.

**Comment by JieCarolHu** [comment]
Vsdconfig.targets has the following line, so it looks like $(OutDir) is empty:
Exec Command="&quot;$(_VsdConfigTool)&quot; @(VsdConfigXml -> '&quot;%(RelativeDir)%(FileName)%(Extension)&quot;', ' ') &quot;$(IntermediateOutputPath)\$(AssemblyName).dll&quot; &quot;$(OutDir)\$(AssemblyName).vsdconfig&quot;"

**Comment by jaredpar** [comment]
@tmat could this be related to the build change u merged today?

**Comment by tmat** [comment]
You mean the Source Link change? That was into `master-vs-deps` branch.

**Comment by tmat** [comment]
I'm not aware of changing anything around `OutDir`.

**Comment by tmat** [comment]
Oh, never mind. I was confused - SourceLInk was actually to master. So maybe it is related. I'll take a look.

**Comment by tmat** [comment]
Yes, I think it's my fault. Fixing.

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn/pull/28007

**Comment by tmat** [comment]
Fixed.

**Comment by CyrusNajmabadi** [comment]
Thanks for the fast turnaround!
