### ISSUE TITLE
Cannot build with latest master.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28036]
Probably related to: https://github.com/dotnet/roslyn/issues/28003

I can now build normal projects.  However, test projets fail in VS with:

```
23>------ Build started: Project: VisualBasicServicesTest, Configuration: Release Any CPU ------
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018: The "TranslateSource" task failed unexpectedly.
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018: System.IO.FileNotFoundException: File not found: Formatting\xlf\XmlLiterals.cs.xlf
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018: File name: 'Formatting\xlf\XmlLiterals.cs.xlf'
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018:    at XliffTasks.Tasks.XlfTask.LoadXlfDocument(String path, String language, Boolean createIfNonExistent)
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018:    at XliffTasks.Tasks.TranslateSource.ExecuteCore()
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018:    at XliffTasks.Tasks.XlfTask.Execute()
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
23>C:\Users\cyrus\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(167,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
23>Done building project "VisualBasicServicesTest.vbproj" -- FAILED.
```

Tagging @tmat @jaredpar for ideas.

**Comment by CyrusNajmabadi** [comment]
Note: it's not just that project.  Many test projects fail for me.

**Comment by tmat** [comment]
I don't see any errors when I 
1) clean repo
2) restore
3) open Roslyn.sln in VS
4) build

**Comment by tmat** [comment]
@tmeschter Any ideas?

**Comment by tmeschter** [comment]
@CyrusNajmabadi Have you tried the usual steps:

1. Closing and reopening VS
2. Syncing to the latest `master`
3. Restoring again

There were changes to how we pull XliffTasks into projects, but you're the only one running into problems as far as I know. :-)

**Comment by CyrusNajmabadi** [comment]
i did a git-clean and that seems to have fixed things.  Thanks!
