### ISSUE TITLE
Crash while editing

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#28040]
Got this crash while editing a using statement:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsEntirelyWithinSingleLineDocComment(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsEntirelyWithinNonUserCodeComment(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsInNonUserCode(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.<ProvideCompletionsAsync>d__1.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsEntirelyWithinSingleLineDocComment(Microsoft.CodeAnalysis.SyntaxTree, Int32, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsEntirelyWithinNonUserCodeComment(Microsoft.CodeAnalysis.SyntaxTree, Int32, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.SyntaxTreeExtensions.IsInNonUserCode(Microsoft.CodeAnalysis.SyntaxTree, Int32, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1, Microsoft.CodeAnalysis.CSharp.Features, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProvideCompletionsAsync>d__1 ByRef)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.ProvideCompletionsAsync(Microsoft.CodeAnalysis.Completion.CompletionContext)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetContextAsync>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetContextAsync>d__33, Microsoft.CodeAnalysis.Features, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetContextAsync>d__33 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(Microsoft.CodeAnalysis.Completion.CompletionProvider, Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Options.OptionSet, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<ComputeNonEmptyCompletionContextsAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<ComputeNonEmptyCompletionContextsAsync>d__26, Microsoft.CodeAnalysis.Features, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComputeNonEmptyCompletionContextsAsync>d__26 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Options.OptionSet, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Completion.CompletionProvider>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetCompletionsAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetCompletionsAsync>d__24, Microsoft.CodeAnalysis.Features, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetCompletionsAsync>d__24 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, System.Collections.Immutable.ImmutableHashSet`1<System.String>, Microsoft.CodeAnalysis.Options.OptionSet, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionService+<GetCompletionsAndSetItemDocumentAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Completion.CompletionService+<GetCompletionsAndSetItemDocumentAsync>d__11, Microsoft.CodeAnalysis.Features, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetCompletionsAndSetItemDocumentAsync>d__11 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAndSetItemDocumentAsync(Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, System.Collections.Immutable.ImmutableHashSet`1<System.String>, Microsoft.CodeAnalysis.Options.OptionSet, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer+<DoInBackgroundAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer+<DoInBackgroundAsync>d__13, Microsoft.CodeAnalysis.EditorFeatures, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<DoInBackgroundAsync>d__13 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer.DoInBackgroundAsync(System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller+Session+ModelComputer.<Do>b__12_0(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Model, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1+<>c__DisplayClass17_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ChainTaskAndNotifyControllerWhenFinished>b__0(System.Threading.Tasks.Task`1<System.__Canon>)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass16_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWithFromAsync>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.PrioritizedTaskScheduler.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

Watson bucket is:

```
Fault bucket 125730739576, type 5
Event Name: PerfWatsonVS12Data
Response: Not available
Cab Id: 0
```

**Comment by ivanbasov** [comment]
There is VSO [397711](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/397711)
It is ranked 287 in 15.7.4. There are Watson heap dumps https://watson/Failure?FailureSearchText=6f329d54-254a-1b2a-028e-e682757b49e1

Scheduling the issue to Dev16.

**Comment by genlu** [comment]
No hit since dev16. Closed
