### ISSUE TITLE
batchfixallprovider does work properly  

### ISSUE THREAD

**Issue by Foroughi** [dotnet/roslyn#28283]
**Version Used**: 
2.8.2
**Steps to Reproduce**:

I have a simple rule that makes devs to use `@this`  for the first parameter of extension methods. like 

```
void func1(this string var1)
{
....
}
```

which should be 

```
void func1(this string @this)
{
...
}
```

Here is the problem. If I try to use the code fixer we have created one by one, the fixer works fine, but if I try to use the project-wide fixer I got an error 

```
System.ArgumentException : Syntax node is not within syntax tree
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(ParameterSyntax declarationSyntax,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetDeclaredSymbol(SemanticModel semanticModel,ParameterSyntax declarationSyntax,CancellationToken cancellationToken)
   at async GCop.Common.FixProvider.Naming.ExtensionMethodFirstParamCodeFixProvider.ChangeParameterName(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionInternalAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetChangedDocumentsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetDocumentIdToChangedDocuments(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryMergeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryGetMergedFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Here is the way i`ve impemented the fixer : 

```
public class ExtensionMethodFirstParamCodeFixProvider : GCopCodeFixProvider
    {
        string Title => "Change to @this";
        public override ImmutableArray<string> FixableDiagnosticIds => ImmutableArray.Create("GCop218");

        protected override void RegisterCodeFix()
        {
            try
            {
                var token = Root.FindToken(DiagnosticSpan.Start).Parent.AncestorsAndSelf().OfType<MethodDeclarationSyntax>().FirstOrDefault();
                if (token == null) return;

                Context.RegisterCodeFix(CodeAction.Create(Title, action => ChangeParameterName(Context.Document, token, action), Title), Diagnostic);
            }
            catch (NullReferenceException)
            {
                // No matter to handle NullReferenceException
            }
        }

        async Task<Solution> ChangeParameterName(Document document, MethodDeclarationSyntax methodDeclaration, CancellationToken cancellationToken)
        {
            var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
            var typeSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration.ParameterList.Parameters[0], cancellationToken);

            return await Renamer.RenameSymbolAsync(document.Project.Solution, typeSymbol, "@this", document.Project.Solution.Workspace.Options, cancellationToken).ConfigureAwait(false);
        }
    }

```

The question here is if our fixer has any issue, then why when I try to fix them one by one it works fine, but when I try to use the project-wide fixer, I got that error 

here is the [link ](https://github.com/Geeksltd/Olive/tree/master/Olive)of the project I'm working. Our analyzers already installed on it. Build and trying to use the project-wide fix for a rule named GCop218

**Comment by mavasani** [comment]
BatchFixAllProvider does not support code fixes such as yours - see [limitations](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md#limitations-of-the-batchfixer) of the batch fixer. You should implement your own [custom FixAllProvider](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md#implementing-a-custom-fixallprovider).
