### ISSUE TITLE
ChangeSignature: Error encountered while changing delegate signature <ChangeSignnatureCodeRefactoringProvider>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28292]
An error was encountered while changing the signature of a delegate: 
```
Changesignaturecoderefactoringprovider encountered an error, stack: System.NullReferenceException: The object reference was not set to an instance of the object. 
At microsoft.codeanalysis.changesignature.delegateinvokemethodreferencefinder.&lt;&gt;c__displayclass4_0.&lt; Findreferencesindocumentasync&gt;b__3 (Syntaxnode e) 
at System.linq.enumerable.&lt;&gt;c__displayclass6_0 ' 1.&lt; Combinepredicates&gt;b__0 (TSource x) 
at the System.Linq.Enumerable.WhereEnumerableIterator ' 1.MoveNext () 
at System.Linq. enumerable.&lt;concatiterator&gt;d__59 ' 1.MoveNext () 
at System.Linq.Enumerable.WhereSelectEnumerableIterator ' 2. MoveNext () 
at System.Linq.Buffer ' 1..ctor (IEnumerable ' 1 source) 
at System.linq.enumerable.toarray[tsource] (ienumerab Le ' 1 source) 
at System.collections.immutable.immutablearray.createrange[t] (IEnumerable ' 1 items) 
at System.Collection S.immutable.immutablearray.toimmutablearray[tsource] (IEnumerable ' 1 items) 
at async Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.FindReferencesInDocumentAsync (&lt; Unknown parameter &gt;) 
at Async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync (&lt; unknown parameter &gt;) 
at Async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync (&lt; unknown parameter &gt;) 
at Async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync (&lt; unknown parameter &gt;) 
at Async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync (&lt; unknown parameter &gt;)
 at Async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync (&lt; unknown parameter &gt;)
 at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync (&lt; unknown parameter &gt;) 
at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync (&lt; unknown parameter &gt;) 
at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectsAsync (&lt; unknown parameter &gt;) 
at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync (&lt; unknown parameter &gt;)
 at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync (&lt; unknown parameter &gt;)
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () 
at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync (&lt; unknown parameter &gt;) 
at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.FindChangeSignatureReferencesAsync (&lt; Unknown parameter &gt;) 
at Roslyn.utilities.taskextensions.waitandgetresult_cancallonbackground[t] (Task ' 1 task, CancellationToken CancellationToken) 
at Roslyn.utilities.taskextensions.waitandgetresult[t] (Task ' 1 task, CancellationToken CancellationToken) 
at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution ( Changesignatureanalyzedcontext Context,changesignatureoptionsresult Options,cancellationtoken CancellationToken, solution&amp; updatedsolution) 
at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext (
   Changesignatureanalyzedcontext Context,changesignatureoptionsresult Options,cancellationtoken CancellationToken) 
At Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync (Object options, CancellationToken CancellationToken)
 at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync (&lt; unknown parameter &gt;) 
at Roslyn.utilities.taskextensions.waitandgetresult_cancallonbackground[t] (Task ' 1 task,cancellationtoken CancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker (Func ' 1 getfromdocument,iprogresstracker progresstracker,cancellationtoken CancellationToken) 
at microsoft.codeanalysis.editor.implementation.suggestions.suggestedaction.&lt;&gt;c__displayclass18_0.&lt; Invokecore&gt;b__0 () 
at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction ( Iextensionmanager extensionmanager,object extension,action Action)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/283840/更改委托签名时遇到错误.html
VSTS ticketId: 640342_
_These are the original issue comments:_

Jane Wu - MSFT [MSFT] on 6/28/2018, 09:53 PM (6 days ago): <p>Translated from Bing:</p><p>Error encountered while changing the signature of a delegate: ChangeSignatureCodeRefactoringProvider encountered an error, stack:<br>System.NullReferenceException : An object reference was not set to an instance of the object.</p><p>at Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.&lt;&gt;c_<em>DisplayClass4_0.&lt;FindReferencesInDocumentAsync&gt;b3(SyntaxNode e)<br> at System.Linq.Enumerable.&lt;&gt;cDisplayClass6_0`1.&lt;CombinePredicates&gt;b0(TSource x)<br> at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()<br> at System.Linq.Enumerable.&lt;ConcatIterator&gt;d59`1.MoveNext()<br> at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()<br> at System.Linq.Buffer`1..ctor(IEnumerable`1 source)<br> at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)<br> at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)<br> at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)<br> at async Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.FindReferencesInDocumentAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p class="x-hidden-focus"><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p class="x-hidden-focus"><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p class="x-hidden-focus"><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectsAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<br> at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p><em> at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.FindChangeSignatureReferencesAsync(&lt;</em>Unknown parameter<em>&gt;)</em></p><p class="x-hidden-focus"><em> at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)<br> at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)<br> at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalyzedContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken,Solution& updatedSolution)<br> at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalyzedContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken)<br> at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options,CancellationToken cancellationToken)<br> at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(&lt;</em>Unknown parameter<em>&gt;)<br></em></p><p class="x-hidden-focus"><em> at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)<br> at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)<br> at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;cDisplayClass18_0.&lt;InvokeCore&gt;b</em>_0()<br> at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)</p>
```
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
Also reported at [DC](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/941669)

**Comment by lawrence-laz** [comment]
I think I encountered the same error. Also while changing a delegate's signature:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.<>c__DisplayClass4_0.<FindReferencesInDocumentAsync>b__3(SyntaxNode e)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Roslyn.Utilities.EnumerableExtensions.SelectAsArray[TSource,TResult](IEnumerable`1 source,Func`2 selector)
   at async Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.FindReferencesInDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.FindChangeSignatureReferencesAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken,Solution& updatedSolution)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ruudsieb** [comment]
Same error here, adding a parameter to a delegate, and moving it to the first position in the argument list. (VS2019 16.8.4)

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.<>c__DisplayClass4_0.<FindReferencesInDocumentAsync>b__3(SyntaxNode e)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Roslyn.Utilities.EnumerableExtensions.SelectAsArray[TSource,TResult](IEnumerable`1 source,Func`2 selector)
   at async Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.FindReferencesInDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.FindChangeSignatureReferencesAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken,Solution& updatedSolution)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
This was also reported in Discord:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.<>c__DisplayClass4_0.<FindReferencesInDocumentAsync>b__3(SyntaxNode e)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Roslyn.Utilities.EnumerableExtensions.SelectAsArray[TSource,TResult](IEnumerable`1 source,Func`2 selector)
   at async Microsoft.CodeAnalysis.ChangeSignature.DelegateInvokeMethodReferenceFinder.FindReferencesInDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentQueueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.FindChangeSignatureReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.CreateUpdatedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.<ChangeSignatureWithContextAsync>g__GetChangeSignatureResultAsync|17_0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by nZeus** [comment]
Me too:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetParameterIndexFromInvocationArgument(SyntaxNode argument,Document document,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.ChangeSignature.CSharpChangeSignatureService.GetInvocationSymbolAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by Youssef1313** [comment]
@nZeus That's a different issue that was fixed in https://github.com/dotnet/roslyn/pull/65307

**Comment by CyrusNajmabadi** [comment]
Closing as i don't see any more hits on this and this code was rewritten and NRTified.
