### ISSUE TITLE
WorkspacesNetCore.ProjectProperties does not set OptionInfer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#28361]
**Version Used**: 62d5b054ec1086cae7340aad6022f138c97cd06d

Test result (using new test harness):

```text
Test Name:	Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.ProjectPropertiesAsync (VS2017)
Test FullName:	Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.ProjectPropertiesAsync
Test Source:	D:\dev\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\Workspace\WorkspacesNetCore.cs : line 55
Test Outcome:	Failed
Test Duration:	0:00:14.322

Result StackTrace:	
at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspaceBase.<ProjectPropertiesAsync>d__11.MoveNext() in D:\dev\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\Workspace\WorkspaceBase.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.<ProjectPropertiesAsync>d__4.MoveNext() in D:\dev\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\Workspace\WorkspacesNetCore.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.Harness.IdeTestInvoker.<ScreenshotOnFailureAsync>d__2.MoveNext() in D:\dev\roslyn\src\VisualStudio\IntegrationTest\TestUtilities\Harness\IdeTestInvoker.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Assert.Equal() Failure
                                 ↓ (pos 23)
Expected: ···‎ Program.M‎(p‎ As‎ Object‎)‎ ‎(‎+‎ 1‎ overload‎)
Actual:   ···‎ Program.M‎(p‎ As‎ Integer‎)‎ ‎(‎+‎ 1‎ overload‎)
                                 ↑ (pos 23)
```

**Comment by sharwell** [comment]
Reassigning to @ivanbasov since #28173 was rejected.
