### ISSUE TITLE
Test Spanish Queue -- Timeout cloning repo from GitHub.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#28409]
Example: https://ci.dot.net/job/dotnet_roslyn/job/dev15.8-preview4-vs-deps/job/windows_debug_spanish_unit32_prtest/16/

```
00:00:03.593  > git fetch --tags --progress https://github.com/dotnet/roslyn +refs/heads/*:refs/remotes/origin/* # timeout=90
00:00:38.788 
ERROR: Error cloning remote repo 'origin'
00:00:38.788 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/dotnet/roslyn +refs/heads/*:refs/remotes/origin/*" returned status code 128:
00:00:38.788 stdout: 
00:00:38.788 stderr: fatal: unable to access 'https://github.com/dotnet/roslyn/': The requested URL returned error: 504
00:00:38.788 
00:00:38.788 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1643)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:352)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:559)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
00:00:38.788 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
00:00:38.788 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
00:00:38.788 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
00:00:38.788 	at hudson.remoting.Request$2.run(Request.java:358)
00:00:38.788 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
00:00:38.788 	at java.util.concurrent.FutureTask.run(Unknown Source)
00:00:38.788 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
00:00:38.789 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
00:00:38.789 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
00:00:38.789 	at java.lang.Thread.run(Unknown Source)
00:00:38.789 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 40.118.202.19/40.118.202.19:6080
00:00:38.789 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
00:00:38.789 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
00:00:38.789 		at hudson.remoting.Channel.call(Channel.java:908)
00:00:38.789 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
00:00:38.789 		at sun.reflect.GeneratedMethodAccessor639.invoke(Unknown Source)
00:00:38.789 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:38.789 		at java.lang.reflect.Method.invoke(Method.java:498)
00:00:38.789 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
00:00:38.789 		at com.sun.proxy.$Proxy182.execute(Unknown Source)
00:00:38.789 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1075)
00:00:38.789 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
00:00:38.789 		at hudson.scm.SCM.checkout(SCM.java:495)
00:00:38.789 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
00:00:38.789 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
00:00:38.789 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:38.789 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
00:00:38.789 		at hudson.model.Run.execute(Run.java:1724)
00:00:38.789 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:00:38.789 		at hudson.model.ResourceController.execute(ResourceController.java:97)
00:00:38.789 		at hudson.model.Executor.run(Executor.java:429)
00:00:38.789 
```

**Comment by jasonmalinowski** [comment]
@dpoeschl Have we seen this again? If not, tempted to just close as this doesn't seem to be terribly actionable.
