### ISSUE TITLE
CSharpFormatting.ApplyEditorConfigAndFormatDocument Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#28454]
```
Xunit.Sdk.EqualException: Assert.Equal() Failure
                                ↓ (pos 16)
Expected: \r\nclass C\r\n{\r\n  public int X1\r\n  {\r\n    get\r\n    {\r\n     ···
Actual:   \r\nclass C\r\n{\r\n    public int X1\r\n    {\r\n        get\r\n    ···
                                ↑ (pos 16)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences).GetType().Name
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
```
![csharpformatting applyeditorconfigandformatdocument-equalexception-21 34 38](https://user-images.githubusercontent.com/2371880/42542031-c9e1b626-8459-11e8-982a-9812d48a97bf.png)

Seen here: https://ci.dot.net/job/dotnet_roslyn/job/features_null-operator-enhancements/job/windows_debug_vs-integration_prtest/10/

**Comment by JoeRobich** [comment]
Hit this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=127738&view=ms.vss-test-web.build-test-results-tab)

```
Xunit.Sdk.EqualException: Assert.Equal() Failure
                                ↓ (pos 16)
Expected: \r\nclass C\r\n{\r\n    public int X1\r\n    {\r\n        get\r\n    ···
Actual:   \r\nclass C\r\n{\r\n  public int X1\r\n  {\r\n    get\r\n    {\r\n     ···
                                ↑ (pos 16)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\projects\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244.GetType().Name
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\projects\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
```

![19 36 02-CSharpFormatting ApplyEditorConfigAndFormatDocument-EqualException](https://user-images.githubusercontent.com/611219/54642191-3a27bd00-4a51-11e9-8749-032066082ec4.png)

**Comment by JoeRobich** [comment]
Hit this again [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=139053&view=ms.vss-test-web.build-test-results-tab)

**Comment by sharwell** [comment]
@JoeRobich This is failing just shy of 10% of the time now.

**Comment by mavasani** [comment]
@sharwell Failed again in https://github.com/dotnet/roslyn/pull/35494/checks?check_run_id=117730255

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't hit this in years and we have a dedicated system for tracking flakey tests now.
