### ISSUE TITLE
Microsoft.CodeAnalysis.Scripting.CompilationErrorException

### ISSUE THREAD

**Issue by jiangjinnan** [dotnet/roslyn#28803]
**Version Used**: 
.NET Core: netcoreapp2.1
Microsoft.CodeAnalysis.CSharp.Scripting: 2.8.2

```
namespace Scripting
{
    public class Foo { }
    public class Bar
    {
        public Foo Foo { get; }
        public Bar(Foo foo) => Foo = foo;
        public void Print() => Console.WriteLine(Foo);
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            var options = ScriptOptions.Default
                .AddReferences(typeof(Program).Assembly)
                .AddImports("Scripting");

            //Success
            await CSharpScript
               .Create("var bar = new Bar(new Foo());", options)
               .ContinueWith("bar.Print()")
               .RunAsync();

            //Fail
            await CSharpScript
                .Create("var foo = new Foo();", options)
                .ContinueWith("var bar = new Bar(foo);")
                .ContinueWith("bar.Print()")
                .RunAsync();

            Console.Read();
        }
    }
}
```
Exception:
```
Unhandled Exception: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (1,19): error CS1503: Argument 1: cannot convert from 'Scripting.Foo [App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]' to 'Scripting.Foo [c:\users\jjn47239\Source\Repos\ConsoleApp14\ConsoleApp14\bin\Debug\netcoreapp2.1\App.dll]'
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter) in /_/src/Scripting/Core/ScriptBuilder.cs:line 104
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken) in /_/src/Scripting/Core/ScriptBuilder.cs:line 89
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken) in /_/src/Scripting/Core/Script.cs:line 359
   at Microsoft.CodeAnalysis.Scripting.Script`1.CommonGetExecutor(CancellationToken cancellationToken) in /_/src/Scripting/Core/Script.cs:line 343
   at Microsoft.CodeAnalysis.Scripting.Script`1.TryGetPrecedingExecutors(Script lastExecutedScriptInChainOpt, CancellationToken cancellationToken) in /_/src/Scripting/Core/Script.cs:line 407
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetPrecedingExecutors(CancellationToken cancellationToken) in /_/src/Scripting/Core/Script.cs:line 370
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken) in /_/src/Scripting/Core/Script.cs:line 459
   at Scripting.Program.Main(String[] args) in c:\users\jjn47239\Source\Repos\ConsoleApp14\ConsoleApp14\Program.cs:line 31
   at Scripting.Program.<Main>(String[] args)
Press any key to continue . . .
```

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by svick** [comment]
This looks very similar to https://github.com/dotnet/roslyn/issues/23123.
