### ISSUE TITLE
extractmethodcoderefactoringprovider error with System.ArgumentNullException : Value cannot be null.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#28922]
I could not find this error reported already. 

System.ArgumentNullException : Value cannot be null.
Parameter name: items
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.Sort(IEnumerable`1 data)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.AnalyzeReadWrite()
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_Captured()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/297574/extractmethodcoderefactoringprovider-error-with-sy.html
VSTS ticketId: 652286_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
reported at [DC ](https://developercommunity.visualstudio.com/content/problem/748866/extractmethodcoderefractoringprovider-hat-einen-fe.html)

**Comment by CyrusNajmabadi** [comment]
Not seeing this in prism.
