### ISSUE TITLE
Calls to Project.CodeModel.AddNamespace crashes VS2015

### ISSUE THREAD

**Issue by v-yadli** [dotnet/roslyn#2893]
How to reproduce:

```C#
        private EnvDTE.CodeClass GenerateCodeClassFile(EnvDTE.Project project, /* other unrelated stuff */)
        {
            string project_path = project.Properties.Item("FullPath").Value.ToString();
            string file_path    = System.IO.Path.Combine(project_path, className + ".cs");
            string file_header = @"using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;";


            System.IO.File.WriteAllText(file_path, file_header);

            var proj_item = project.ProjectItems.AddFromFile(file_path);

        /* Crashes here */
            var code_namespace  = project.CodeModel.AddNamespace(project.Properties.Item("DefaultNamespace").Value.ToString(), file_path, Type.Missing);
```

Exception thrown:

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=Nullable object must have a value.
  Source=EnvDTE
  StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.RootCodeModel.GetFileCodeModel(Object location)
       at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.RootCodeModel.AddNamespace(String name, Object location, Object position)
       at EnvDTE.CodeModel.AddNamespace(String Name, Object Location, Object Position)
       at Trinity.VSExtension.Wizards.GraphEngineAppWizard.GenerateCodeClassFile(Project project, String ref_namespace, String className, List`1 baseTypeGenericParams, String baseName)
       at Trinity.VSExtension.Wizards.GraphEngineAppWizard.GenerateMain(Project project, List`1 servers, List`1 proxies, String ref_namespace, Boolean stubsGenerated)
       at Trinity.VSExtension.Wizards.GraphEngineAppWizard.WizardWindowClosed(Object sender, EventArgs e)
       at System.Windows.Window.OnClosed(EventArgs e)
       at System.Windows.Window.WmDestroy()
       at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException: 

```

The stack trace indicates that the problem is related to the second parameter Location, which is the file path. I also tried to extract relative path from the item I just created through AddFromFile but it produces the same exception.

**Comment by DustinCampbell** [comment]
Fixed with PR #2996.
