### ISSUE TITLE
Integration test failure: CSharpChangeSignatureDialog.VerifyReorderParameters/VerifyRemoveParameter "Failed to write to an IPC Port: The pipe is being closed."

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#29001]
PR: https://github.com/dotnet/roslyn/pull/28983
Failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3128/

Failures: 
- `Failed to write to an IPC Port: The pipe is being closed.`
- `The channel 'IPC channel client for 3816' is already registered.`

**Comment by dpoeschl** [comment]
There is no dump available.

**Comment by dpoeschl** [comment]
FYI: @JoeRobich

**Comment by JoeRobich** [comment]
Another example: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3151/artifact/Binaries/Debug/Logs/Microsoft.VisualStudio.LanguageServices.IntegrationTests.dll.out.log

**Comment by dpoeschl** [comment]
Possibly again: https://ci.dot.net/job/dotnet_roslyn/job/features_embeddedRegex/job/windows_debug_vs-integration_prtest/256/artifact/Binaries/Debug/Logs/Microsoft.VisualStudio.LanguageServices.IntegrationTests.dll.out.log

```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyCrossLanguageGlobalUndo
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpClassification.VerifyProjectConfigChange
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpClassification.VerifyColorOfSomeTokens
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpClassification.SemanticClassification
      System.Runtime.Remoting.RemotingException : Failed to write to an IPC Port: The pipe is being closed.
      
      Stack Trace:
        
        Server stack trace: 
           at System.Runtime.Remoting.Channels.Ipc.IpcPort.Write(Byte[] data, Int32 offset, Int32 size)
           at System.Runtime.Remoting.Channels.Ipc.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
           at System.Runtime.Remoting.Channels.ChunkedMemoryStream.WriteTo(Stream stream)
           at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.SendRequest(IMessage msg, ITransportHeaders headers, Stream contentStream)
           at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
           at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.VisualStudioWorkspace_InProc.CleanUpWaitingService()
        /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/VisualStudioWorkspace_OutOfProc.cs(59,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.VisualStudioWorkspace_OutOfProc.CleanUpWaitingService()
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs(172,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.CleanUp()
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs(191,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.Close(Boolean exitHostProcess)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs(128,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.NotifyCurrentInstanceContextDisposed(Boolean canReuse)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs(119,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<GetNewOrUsedInstanceAsync>d__9.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractIntegrationTest.cs(54,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs(40,0): at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.ApplyEditorConfigAndFixAllOccurrences
      System.Runtime.Remoting.RemotingException : The channel 'IPC channel client for 2452' is already registered.
      Stack Trace:
           at System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelInternal(IChannel chnl, Boolean ensureSecurity)
           at System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(IChannel chnl, Boolean ensureSecurity)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs(88,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance..ctor(Process hostProcess, DTE dte, ImmutableHashSet`1 supportedPackageIds, String installationPath)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs(194,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<UpdateCurrentlyRunningInstanceAsync>d__12.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
        /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs(120,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<GetNewOrUsedInstanceAsync>d__9.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractIntegrationTest.cs(54,0): at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs(40,0): at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.OrderFixesByCursorProximityRight
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.SuppressionAfterRefactorings
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.AddUsingExactMatchBeforeRenameTracking
    Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.InvokeDelegateWithConditionalAccessMultipleTimes
```

**Comment by CyrusNajmabadi** [comment]
closing as we haven't seen this in 5 years.
