### ISSUE TITLE
InvalidOperationException from TypeSymbolWithAnnotations.GetHashCode()

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#29049]
`csc /langversion:8.0 c.cs`
```c#
[module: System.Runtime.CompilerServices.NonNullTypes(true)]
interface I<T> { }
class A : I<A> { }
class B<T> where T : I<A?> { }
class Program
{
    static void Main()
    {
        new B<A>();
    }
}
```
```
(9,15): warning CS8631: The type 'A' cannot be used as type parameter 'T' in the generic type or method 'B<T>'. Nullability of type argument 'A' doesn't match constraint type 'I<A?>'.

Unhandled Exception: System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbolWithAnnotations.GetHashCode()
   at Roslyn.Utilities.Hash.Combine[T](T newKeyPart, Int32 currentKey)
   at Microsoft.CodeAnalysis.DiagnosticInfo.GetHashCode()
   at Microsoft.CodeAnalysis.DiagnosticWithInfo.GetHashCode()
   at System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Microsoft.CodeAnalysis.CommonCompiler.ReportErrors(IEnumerable`1 diagnostics, TextWriter consoleOutput, ErrorLogger errorLoggerOpt)
```

**Comment by cston** [comment]
Fixed in #29045.
