### ISSUE TITLE
ExtractMethodCodeRefactoringProvider

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29088]
```text
System.AggregateException : One or more errors occurred. ---> Inconsistent length calculation in projection snapshot.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.InvalidOperationException : Inconsistent length calculation in projection snapshot.
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot..ctor(ProjectionBuffer projectionBuffer,ITextVersion2 version,StringRebuilder content,IList`1 sourceSpans)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.TakeSnapshot()
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.SetCurrentVersionAndSnapshot(INormalizedTextChangeCollection normalizedChanges,Int32 reiteratedVersionNumber)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.InterpretSourceChanges(EditOptions options,Object editTag)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.PropagateSourceChanges(EditOptions options,Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.PerformMasterEdit(ITextBuffer buffer,ISubordinateTextEdit xedit,EditOptions options,Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.TextBuffer.BasicEdit.PerformApply()
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferEdit.Apply()
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextBufferEditExtensions.ApplyAndLogExceptions(ITextBufferEdit edit)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextBufferEditExtensions.ApplyAndLogExceptions(ITextBufferEdit edit)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.TextEditApplication.UpdateText(SourceText newText,ITextBuffer buffer,EditOptions options)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.StandardTextDocument.UpdateText(SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/302051/extractmethodcoderefactoringprovider.html
VSTS ticketId: 655702_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't see any other hits for this.
