### ISSUE TITLE
ArgumentNullException binding inaccessible type

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#29253]
`csc /t:library a.cs`:
```c#
class A { }
```
`csc /r:a.dll b.cs`:
```c#
class B
{
    static void Main()
    {
        new A();
    }
}
```
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.PEAssembly.GetInternalsVisibleToPublicKeys(String simpleName)
   at Microsoft.CodeAnalysis.CSharp.Binder.<CheckViability>g__IsBadIvtSpecification|564_0(<>c__DisplayClass564_0& )
   at Microsoft.CodeAnalysis.CSharp.Binder.CheckViability(Symbol symbol, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Boolean diagnose, HashSet`1& useSiteDiagnostics, ConsList`1 basesBeingResolved)
```

**Comment by cston** [comment]
cc @jaredpar

**Comment by jaredpar** [comment]
This is fixed now.
