### ISSUE TITLE
'WaitAndGetResult cannot be called from a thread pool thread.

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#29363]
**Version Used**: VS15.8 p5, Roslyn on `master`

**Steps to Reproduce**:

1. Open Roslyn.sln 
2. Run debugger on Roslyn.VisualStudio.Setup project
3. Open Compilers.sln in the second VS instance
3. Wait a few seconds

**Actual Behavior**: 

`System.InvalidOperationException: 'WaitAndGetResult cannot be called from a thread pool thread.'`

This is the location where it's thrown.

> ```cs
> #if DEBUG
>             if (IsThreadPoolThread(Thread.CurrentThread))
>             {
>                 // If you hit this when running tests then your code is in error.  WaitAndGetResult
>                 // should only be called from a foreground thread.  There are a few ways you may 
>                 // want to fix this.
>                 //
>                 // First, if you're actually calling this directly *in test code* then you could 
>                 // either:
>                 //
>                 //  1) Mark the test with [WpfFact].  This is not preferred, and should only be
>                 //     when testing an actual UI feature (like command handlers).
>                 //  2) Make the test actually async (preferred).
>                 //
>                 // If you are calling WaitAndGetResult from product code, then that code must
>                 // be a foreground thread (i.e. a command handler).  It cannot be from a threadpool
>                 // thread *ever*.
>                 throw new InvalidOperationException($"{nameof(WaitAndGetResult)} cannot be called from a thread pool thread.");
>             }
> #endif
> ```

**Comment by alrz** [comment]
```
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzer.GetTodoItems(Workspace workspace, DocumentId id, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzerProvider.GetTodoItems(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseTodoListTable.TableDataSource.TableEntriesSource.GetItems()
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory`1.AggregatedEntriesSource.GetItems()
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory`1.GetCurrentSnapshot()
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.Sink.AddFactory(ITableEntriesSnapshotFactory factory)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.Sink.ApplyPendingChanges(Boolean& anyChanges, Boolean& anyTransferedState)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControl.UpdateEntries(HashSet`1 variableColumns, Boolean anyColumnChanges, List`1& frozenSinksAwaitingDisposal)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControl.<UpdateEntriesAsync>d__159.MoveNext()
```

**Comment by alrz** [comment]
Early return from GetTodoItems with `return default` freezes the second instance completely.
