### ISSUE TITLE
VisualBasicUseConditionalExpressionForCodeRefactoringProvider Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#29376]
Whant to convert the following code to pur If(x,y,z)

 If TheEmployee Is Nothing Then
         EmployeeNumber = String.Empty
  Else
         EmployeeNumber = TheEmployee.ExternalId
 End If

above provider declared Error.

StackTrace:

 System.InvalidCastException : Das Objekt des Typs &quot;Microsoft.CodeAnalysis.VisualBasic.Syntax.AccessorBlockSyntax&quot; kann nicht in Typ &quot;Microsoft.CodeAnalysis.VisualBasic.Syntax.VariableDeclaratorSyntax&quot; umgewandelt werden.
   at Microsoft.CodeAnalysis.VisualBasic.UseConditionalExpression.VisualBasicUseConditionalExpressionForAssignmentCodeRefactoringProvider.GetDeclaratorSyntax(IVariableDeclaratorOperation declarator)
   at Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionForAssignmentCodeFixProvider`6.TryConvertWhenAssignmentToLocalDeclaredImmediateAbove(ISyntaxFactsService syntaxFacts,SyntaxEditor editor,IConditionalOperation ifOperation,ISimpleAssignmentOperation trueAssignment,ISimpleAssignmentOperation falseAssignment,TExpressionSyntax conditionalExpression)
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionForAssignmentCodeFixProvider`6.FixOneAsync[TStatementSyntax,TIfStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TExpressionSyntax,TConditionalExpressionSyntax](&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionCodeFixProvider`4.FixAllAsync[TStatementSyntax,TIfStatementSyntax,TExpressionSyntax,TConditionalExpressionSyntax](&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unbekannte Parameter&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/312892/visualbasicuseconditionalexpressionforcoderefactor.html
VSTS ticketId: 665132_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by redpit** [comment]
To be clear: the error only happens if the PropertyName was used as return value
Using a Return instead the refactoring works.

Error Case:
Public ReadOnly Property EmployeeNumber as String
If TheEmployee Is Nothing Then
EmployeeNumber = String.Empty
Else
EmployeeNumber = TheEmployee.ExternalId
End If
End Property

Working Case:
Public ReadOnly Property EmployeeNumber as String
If TheEmployee Is Nothing Then
   Return String.Empty
Else
  Return TheEmployee.ExternalId
End If
End Property

**Comment by CyrusNajmabadi** [comment]
@redpit Could you provide a minimal example of what you're trying to do?  I'm finding your comments a bit hard to understand. 

For example you seem to have declared a property `Public ReadOnly Property EmployeeNumber as String` with some code in it.  However, the code is not in a getter or setter...

Also, to format code, use: ```vb

**Comment by CyrusNajmabadi** [comment]
@redpit I have a fix available for your crash.  Thanks for the report!
