### ISSUE TITLE
CSharpValidateFormatStringDiagnosticAnalyzer crashes for local function named Format

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#29398]
Visual Studio 15.8.1

```c#
public class C
{
    public void M()
    {
        Format();
        void Format() { }
    }
}
```

Gives:

> AD0001 Analyzer 'Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer' threw the following exception:

```
Exception occurred with following context:
Compilation: RoslynRepro
SyntaxTree: C:\Users\jmusser\Source\Repos\RoslynRepro\RoslynRepro\Class1.cs
SyntaxNode: Format() [InvocationExpressionSyntax]@[55..63) (4,8)-(4,16)

System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.TryGetValidFormatMethodSymbol(SyntaxNodeAnalysisContext context, SymbolInfo symbolInfo)
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.AnalyzeNode(SyntaxNodeAnalysisContext context, INamedTypeSymbol formatProviderType)
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.<>c__DisplayClass15_0.<Initialize>b__1(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

[(repros on master on sharplab, too)](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgMwAEhATKQMICwAUAN4OmvlmEAspAsgBQBKFm2b0240gDEA9gkgxBAbmETy3GXIgKBpRqQC+Kgw0P0gA===)

**Comment by CyrusNajmabadi** [comment]
Tagging @chborl

**Comment by CyrusNajmabadi** [comment]
@jnm2 can you clarify what is unpleasant here?  What's the experience you're getting?

**Comment by CyrusNajmabadi** [comment]
So it's just putting one item in the list?  Or is it many items?  Can you give a screen shot?

**Comment by jnm2** [comment]
One item:

![image](https://user-images.githubusercontent.com/8040367/45920757-19522680-be77-11e8-94aa-bf94882081e6.png)

**Comment by CyrusNajmabadi** [comment]
My personal opinoin is that that would def not meet the bar.  It's a minor annoyance.

**Comment by jnm2** [comment]
Yes; is there any change that the fix for this minor unpleasantness could be ported to 15.9.x just so we don't have to wait until May or so? The fix is five lines, so I thought it might be super easy for the team and a reasonable question.

**Comment by jinujoseph** [comment]
@jnm2 unfortunately at this point it looks unlikely that this will be ported over to 15.9 
15.9 is high bar focusing on high customer blocking issues.

**Comment by jnm2** [comment]
Alright, thank you!
