### ISSUE TITLE
[Question]In my Codefix createChangedSolution does nothing when I want to edit multiple Documents except I click "fix all occurrences in Solution"

### ISSUE THREAD

**Issue by Herrmel** [dotnet/roslyn#29414]
Is there a way to always use "fix all occurrences in Solution" when I create my CodeAction? 
For some Reason the preview seems to work as it previews me one correct fix in a different document than the corresponding diagnostic. However if I click my Codefix nothing happens at all and after trying to apply the codefix a second time I get an Error:
```
System.AggregateException : Mindestens ein Fehler ist aufgetreten. ---> Das Ändern der Dokumenteigenschaften wird nicht unterstützt.(Translation: One or more Errors occurred -> Modification of documentproperties is not supported)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NotSupportedException : Das Ändern der Dokumenteigenschaften wird nicht unterstützt.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unbekannte Parameter>)<---
```

Hope you can help me since I couldnt find a way. I don't think my code is relevant but if you think otherwise I can provide it to you.

**Comment by CyrusNajmabadi** [comment]
> Is there a way to always use "fix all occurrences in Solution" when I create my CodeAction?

Can you clarify what you mean by that?  If you want to fix everything in the solution, and that's all you want to support... then why not have your code action just be a SolutionChangeAction and have it do precisely that?
