### ISSUE TITLE
"Invert If" refactoring in latest Visual Studio throws an exception in some cases

### ISSUE THREAD

**Issue by cosborne83** [dotnet/roslyn#29434]
**Visual Studio 15.8.1**: 

**Steps to Reproduce**:

Attempt to perform an "Invert If" refactoring on C# code of the form:

    if (foo is SomeType)
    {
        // Do X
    }
    else
    {
        // Do Y
    }

**Expected Behavior**:

The `if` condition is inverted and the if/else blocks swapped.

**Actual Behavior**:

The following error is shown:

`'CSharpInvertIfCodeRefactoringProvider' encountered an error and has been disabled.`

With stack-trace:

    System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.LazyIsTypeExpression' to type 'Microsoft.CodeAnalysis.Operations.IBinaryOperation'.
       at Microsoft.CodeAnalysis.CodeRefactorings.InvertIf.AbstractInvertIfCodeRefactoringProvider.GetNegationOfBinaryExpression(SyntaxNode expressionNode,SyntaxGenerator generator,ISyntaxFactsService syntaxFacts,SemanticModel semanticModel,CancellationToken cancellationToken)
       at Microsoft.CodeAnalysis.CodeRefactorings.InvertIf.AbstractInvertIfCodeRefactoringProvider.Negate(SyntaxNode expression,SyntaxGenerator generator,ISyntaxFactsService syntaxFacts,SemanticModel semanticModel,CancellationToken cancellationToken)
       at Microsoft.CodeAnalysis.CSharp.CodeRefactorings.InvertIf.CSharpInvertIfCodeRefactoringProvider.GetRootWithInvertIfStatement(Document document,SemanticModel model,SyntaxNode ifStatementSyntax,CancellationToken cancellationToken)
       at async Microsoft.CodeAnalysis.CodeRefactorings.InvertIf.AbstractInvertIfCodeRefactoringProvider.InvertIfAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
       at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by CyrusNajmabadi** [comment]
tagging @alrz

**Comment by alrz** [comment]
Isn't this an IOperation bug? perhaps LazyIsTypeExpression should implement IBinaryOperation?

**Comment by alrz** [comment]
IsExpression *is* a BinaryExpressionSyntax. (although IsPatternExpression has its own node). From there I supposed this should work here.

**Comment by CyrusNajmabadi** [comment]
> IsExpression is a BinaryExpressionSyntax 

It is.  But in a very weird way.  The parser won't let you do the following for example:  `a is foo()`.  IMO, 'is' was a bit of a mistake syntactically.  It should have been like IsPatternExpression.  i.e. we should have had an IsExpression or IsTypeExpression.  But it's too late to address teh syntax side of things.  But i'm fine if IOp behaves like it does.

That said, let's find out what the rest of hte IOp people think about this.  Tagging @heejaechang @mavasani @333fred @AlekseyTs .

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/30173
