### ISSUE TITLE
[Flaky] CSharp_FixupSpanDuringResolvableConflict_ComplexificationReordersReferenceSpans Failure

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#29483]
Test Log:
```
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.CSharp_FixupSpanDuringResolvableConflict_ComplexificationReordersReferenceSpans
      Assert.Equal() Failure
      Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[41..44), [177..180), [184..187)]
      Actual:   List<Span> [[41..44), [177..180), [177..180), [184..187), [184..187)]
      Stack Trace:
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(91,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(26,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_2_VerifyTaggedSpans.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(61,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_6_VerifySpansBeforeConflictResolution.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(1383,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_28_CSharp_FixupSpanDuringResolvableConflict_ComplexificationReordersReferenceSpans.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://ci.dot.net/job/dotnet_roslyn/job/features_null-operator-enhancements/job/windows_release_unit32_prtest/20/
https://github.com/dotnet/roslyn/pull/29476

From the failure output, it appears that some of the spans are duplicated? I've not seen this failure before, and that particular branch has no changes related to anything used in the test over features/compiler.

**Comment by 333fred** [comment]
Hit what looks to be a similar failure: https://ci.dot.net/job/dotnet_roslyn/job/features_null-operator-enhancements/job/windows_release_unit64_prtest/34/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/RenameTagProducerTests/CSharp_FixupSpanDuringResolvableConflict_ContainedComplexifiedSpan/

**Comment by JoeRobich** [comment]
Hit a similar failure in the Spanish Unit Tests for #31623 [Build log](https://dnceng.visualstudio.com/public/_build/results?buildId=54816)

**Comment by JoeRobich** [comment]
Hit a similar failure in https://github.com/dotnet/roslyn/pull/32332 on Windows_Desktop_Unit_Tests release - [Logs](https://dnceng.visualstudio.com/public/_build/results?buildId=70059) Attempt 1
```
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.RenameTagProducerTests.CSharp_FixupSpanDuringResolvableConflict_ReferenceConflict 
    Assert.Equal() Failure
    Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[24..27), [66..69), [72..75)]\r\nActual: List<Span> [[24..27), [66..69), [66..69), [72..75), [72..75)]
```

**Comment by JoeRobich** [comment]
Hit a similar failure in #32411 on Windows_Desktop_Unit_Tests release_64 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=71541&view=ms.vss-test-web.test-result-details) Attempt 1

```
Assert.Equal() Failure
    Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[24..27), [66..69), [72..75)]
    Actual: List<Span> [[24..27), [66..69), [66..69), [72..75), [72..75)]
```

**Comment by JoeRobich** [comment]
Hit the initial issue again - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=134246&view=logs)

**Comment by JoeRobich** [comment]
Hit again - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=226279)

**Comment by ryzngard** [comment]
Hit in [signed build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2851661&view=ms.vss-test-web.test-result-details)
Hit in [merge PR build](https://dev.azure.com/dnceng/public/_build/results?buildId=265868)

**Comment by JoeRobich** [comment]
RenameTagProducerTests.ValidTagsDuringSimpleRename failed [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=328780&view=ms.vss-test-web.build-test-results-tab&runId=9620540&resultId=100403&paneView=debug)
```
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.ValidTagsDuringSimpleRename [STARTING]
      Assert.Equal() Failure
      Expected: WhereSelectEnumerableIterator<TextSpan, Span> [[40..43), [208..211), [220..223)]
      Actual:   List<Span> [[40..43), [208..211), [208..211), [220..223), [220..223)]
      Stack Trace:
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(91,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(26,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_2_VerifyTaggedSpans.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb(129,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_10_ValidTagsDuringSimpleRename.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.ValidTagsDuringSimpleRename [FINISHED] Time: 6.8517663s
```

**Comment by jaredpar** [comment]
Please stop adding comments to bugs like this. Instead disable the test. Doing anything else is just letting future  developers waste time.

**Comment by sharwell** [comment]
@jaredpar I didn't disable the tests because I already sent a fix for them. Since the problem was already diagnosed and a fix submitted which links to this issue, I marked related items as duplicates.

**Comment by JoeRobich** [comment]
@sharwell I assumed he was talking to me.

**Comment by tmat** [comment]
VisualBasic_FixupSpanDuringResolvableConflict_NeedsEscaping failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=473387&view=ms.vss-test-web.build-test-results-tab&runId=15070414&resultId=157612&paneView=debug
