### ISSUE TITLE
Loading an MSBuild project with a malformed file path should not throw an exception.

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#29494]
I've create a demo repository [PathogenPlayground/MSBuildWorkspaceInvalidPathCrash](https://github.com/PathogenPlayground/MSBuildWorkspaceInvalidPathCrash) that demonstrates this issue. The readme for this repository contains extra details on the behavior in Visual Studio vs MSBuild vs `Microsoft.CodeAnalysis.Workspaces.MSBuild`, which are summarized below.

---

**Version Used**: 2.9.0 (NuGet)

**Steps to Reproduce**:

1. Create a project file with a malformed path in a file name. (IE: `<AdditionalFiles Include="TEST::" />`
2. Load the project with `MSBuildWorkspace.OpenProjectAsync`

**Expected Behavior**:

The malformed file path is ignored (and maybe a warning is emitted.)

_This is the basic behavior of the `msbuild` command and Visual Studio._

**Actual Behavior**:

A `NotSupportedException` is thrown with the message "The given path's format is not supported." and the following stack trace:

```
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetAbsolutePathRelativeToProject(String path) in /_/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs:line 201
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetDocumentFilePath(ITaskItem documentItem) in /_/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs:line 206
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.MakeAdditionalDocumentFileInfo(ITaskItem documentItem) in /_/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs:line 184
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.CreateProjectFileInfo(ProjectInstance project) in /_/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs:line 133
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<BuildProjectFileInfoAsync>d__17.MoveNext() in /_/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs:line 101
** Snipped **
```

The problem line in question appears to be the use of `Path.GetFullPath` at [ProjectFile.cs:202](https://github.com/dotnet/roslyn/blob/66f85bd989527c50802669b3474ece40dccde909/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L202).

**Comment by DustinCampbell** [comment]
Thanks for the solid repro @PathogenDavid!

**Comment by PathogenDavid** [comment]
No problem, thanks for fixing the issue!
