### ISSUE TITLE
make exception from tagger not to crash VS. but file NFW and move one.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#29811]
this is related to https://github.com/dotnet/roslyn/pull/29785

we probably want to do this for all taggers. @CyrusNajmabadi suggested that there might be 1 place where we can put such exceptions and move on rather than putting it at each place.

the benefit of that is, all taggers that at least use the framework will get this behavior automatically, the disadvantage is that NFW we have will most likely not captured right context since it is async method chain.

we can use both approaches if we want to. have a generic one to not crash but have per tagger specific one to capture better NFW for investigation.

**Comment by heejaechang** [comment]
looks like same root cause from typescript can crash other parts as well.

https://watson/BucketDetails?BucketIdentifier=f75056c7-7959-a1d4-f3ac-f1813fc13cd2

root issue will be handled by typescript. but meanwhile, we probably want to make nav bar not to crash VS as well.

...

at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Text.Implementation.TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)
   at Microsoft.CodeAnalysis.Editor.NavigationBarItem.<>c__DisplayClass27_0.<InitializeTrackingSpans>b__0(TextSpan s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.NavigationBarItem.InitializeTrackingSpans(ITextSnapshot textSnapshot)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.<>c__DisplayClass29_0.<ComputeModelAsync>b__0(NavigationBarItem i)
   at Roslyn.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source, Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.<ComputeModelAsync>d__29.MoveNext()

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
