### ISSUE TITLE
Installing NonNullable Reference Types preview fails

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#29987]
**Version Used**: 
15.8.4 / 15.9 preview 2
(english VS on german system)

**Steps to Reproduce**:

1. Download preview and unzip
2. Run .\install.bat from elevated prompt
```
Installing Roslyn Insiders Build
Installing Preview Into C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
Using VS Instance 75b52a36 at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
"C:\Users\Robin\Downloads\NonNull\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /u /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Users\Robin\Downloads\NonNull\vsix\RoslynDeployment.vsix"
  Running as Admin.
  de-DE
  Nothing to uninstall...
Using VS Instance 75b52a36 at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
"C:\Users\Robin\Downloads\NonNull\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Users\Robin\Downloads\NonNull\vsix\RoslynDeployment.vsix"
  Running as Admin.
  de-DE
  Installing local extension: 'C:\Users\Robin\Downloads\NonNull\vsix\RoslynDeployment.vsix'

Unhandled Exception: System.Runtime.InteropServices.COMException: Element not found. (Exception from HRESULT: 0x80070490)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupConfiguration2.GetInstanceForCurrentProcess()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.get_VsProductVersion()
   at Microsoft.VisualStudio.ExtensionManager.Utilities.GetRunningSKUVersionAndEdition(String& version, String& edition)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.get_VersionAndEdition()
   at Microsoft.VisualStudio.ExtensionManager.InstalledExtensionImpl.get_VsVersion()
   at Microsoft.VisualStudio.ExtensionManager.InstalledExtensionImpl.AssetTargetsVsVersion(IDictionary`2 attributes)
   at Microsoft.VisualStudio.ExtensionManager.InstalledExtensionImpl.RemoveInapplicableAssets()
   at Microsoft.VisualStudio.ExtensionManager.InstalledExtensionImpl..ctor(IExtension extension, String installPath, IEngineHost engineHost, Boolean installedPerMachine)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ToInstalledExtension(InstallableExtensionImpl extension, Boolean perMachine)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.<>c__DisplayClass183_0.<PreviewInstalledExtensions>b__4(InstallableExtensionImpl installableExtension)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PreviewInstalledExtensions(InstallableExtensionImpl extension, Boolean perMachine, List`1 previewedInstalledExtensions, IInstalledExtensionList modifiedInstalledExtensionsList)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.FindRecursiveInstallConflicts(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, List`1 impactedExtensions, Boolean isNested)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Install(IInstallableExtension extension, InstallFlags installFlags, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Install(IInstallableExtension extension, Boolean perMachine)
   at VsixExpInstaller.Program.<>c__DisplayClass16_0.<Main>g__Install|7(IInstallableExtension installableExtension, <>c__DisplayClass16_4& , <>c__DisplayClass16_5& )
   at VsixExpInstaller.Program.<>c__DisplayClass16_0.<Main>g__RunProgram|1()
   at VsixExpInstaller.Program.Main(String[] args)
Command failed to execute: "C:\Users\Robin\Downloads\NonNull\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Users\Robin\Downloads\NonNull\vsix\RoslynDeployment.vsix"
System.Management.Automation.RuntimeException: Command failed to execute: "C:\Users\Robin\Downloads\NonNull\tools\vsixexpinstaller\VsixExpInstaller.exe" /rootSuffix: /vsInstallDir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" "C:\Users\Robin\Downloads\NonNull\vsix\RoslynDeployment.vsix"
at Exec-CommandCore, C:\Users\Robin\Downloads\NonNull\tools\utils.ps1: Line 39
at Exec-Console, C:\Users\Robin\Downloads\NonNull\tools\utils.ps1: Line 71
at Use-VsixTool, C:\Users\Robin\Downloads\NonNull\tools\utils.ps1: Line 149
at Install-VsixViaTool, C:\Users\Robin\Downloads\NonNull\tools\utils.ps1: Line 112
at <ScriptBlock>, C:\Users\Robin\Downloads\NonNull\tools\install.ps1: Line 50
```

**Expected Behavior**:
Installs successfully

**Actual Behavior**:
Fails with exception

**Comment by jcouv** [comment]
Tagging @jmarolf

**Comment by jmarolf** [comment]
tagging @sharwell who encountered this issue.  It appears that this is a breaking change made in 15.8.4

**Comment by jinujoseph** [comment]
tracking [bug ](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/686556) on platform team

**Comment by jcouv** [comment]
FYI, the fix missed the window for 15.8.5, but is scheduled as part of 15.8.6. Sorry for the wait.

**Comment by jcouv** [comment]
15.8.6 was just released. I may not be able to confirm the fix this afternoon. If anyone here does try, please share your result. Thanks!

**Comment by jcouv** [comment]
Awesome. Thanks @Suchiman for confirming.

**Comment by Craigfis** [comment]
It won't install on 15.9.0 preview 3 for me.

**Comment by jcouv** [comment]
@Craigfis The nullable preview installer only installs on an RTM version of VS. 15.8.6 is recommended at the moment (latest RTM bits).

**Comment by pellea** [comment]
@jcouv Is it possible - at our own risk - to install it on the latest preview bits?

**Comment by jcouv** [comment]
Please update to 15.8.6. The issue with 15.8.5 was fixed there.
Otherwise, you can checkout roslyn, 'restore.cmd', 'msbuild /v:m /m roslyn.sln' and 'devenv /rootSuffix RoslynDev'

________________________________

**Comment by pellea** [comment]
@jcouv I have the 15.9 preview 3 like @Craigfis. I don't really want to downgrade VS (I don't even know if that is possible).

**Comment by chucker** [comment]
@pellea VS Preview installs side-by-side with VS regular. Thus, installing 15.8.6 won't be a downgrade; your 15.9 Preview 3 installation will remain.

**Comment by pellea** [comment]
@chucker I never installed the regular version. I have only the preview. If there is no possibilities to get this to work with the preview version, I'll then install the regular version.

**Comment by chucker** [comment]
@pellea Yup. It's not currently compatible with the 15.9 preview. You'll need to install the regular 15.8.x on the side to test this.
