### ISSUE TITLE
Build crashes in csc.exe since Visual Studio 15.8.x on multiple machines and build server

### ISSUE THREAD

**Issue by MilKAOS** [dotnet/roslyn#30044]
**Version Used**: 

Visual Studio 15.8.4 - all .NET framework versions are installed

We have this behavior on all 4 development machines (which have the same setup; with Windows 10; VS 15.8.x) and on two build servers with Windows Server 2016 and VS.
For us the issue occurs since Visual Studio 15.8

**Steps to Reproduce**:

1. Create New Project: Console App (.NET Core)
2. Build Project/Solution
3. Crash in CodeAnalysis (see errors below)

**Expected Behavior**:

No crashes / No error messages

**Actual Behavior**:

As Visual Studio output: ` Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.SeparatedSyntaxList'1' from assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

```
1>------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.SeparatedSyntaxList`1' from assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.System.Collections.Generic.IEnumerable<TNode>.GetEnumerator()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbol.GetAttributesToBind(OneOrMany`1 attributeDeclarationSyntaxLists, AttributeLocation symbolPart, DiagnosticBag diagnostics, CSharpCompilation compilation, Func`2 attributeMatchesOpt, Binder rootBinderOpt, ImmutableArray`1& binders)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(OneOrMany`1 attributesSyntaxLists, CustomAttributesBag`1& lazyCustomAttributesBag, AttributeLocation symbolPart, Boolean earlyDecodingOnly, Binder binderOpt, Func`2 attributeMatchesOpt)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
1>Done building project "ConsoleApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

As messages in the event viewer:
```
____________
Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 6F0CB2CA (6F0B0000) with exit code 80131506.
____________
Faulting application name: ServiceHub.RoslynCodeAnalysisService32.exe, version: 1.3.77.18573, time stamp: 0xdc9a59bf
Faulting module name: clr.dll, version: 4.7.3132.0, time stamp: 0x5b554329
Exception code: 0xc0000005
Fault offset: 0x0001b2ca
Faulting process id: 0x1954
Faulting application start time: 0x01d450f8e7465638
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.CLR.x86\ServiceHub.RoslynCodeAnalysisService32.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: bb92a4e4-1d70-41fc-a636-2598dce4bcbc
Faulting package full name: 
Faulting package-relative application ID: 
____________
Application: csc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System.Collections.Generic.IEnumerable<TNode>.GetEnumerator()
   at System.Collections.Immutable.ImmutableArray`1+Builder[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.CodeAnalysis.CSharp.Symbol.GetAttributesToBind(Roslyn.Utilities.OneOrMany`1<Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>>, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CSharp.CSharpCompilation, System.Func`2<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax,Boolean>, Microsoft.CodeAnalysis.CSharp.Binder, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Binder> ByRef)
   at Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany`1<Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>>, Microsoft.CodeAnalysis.CustomAttributesBag`1<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation, Boolean, Microsoft.CodeAnalysis.CSharp.Binder, System.Func`2<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax,Boolean>)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(Microsoft.CodeAnalysis.SourceLocation, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(Microsoft.CodeAnalysis.SyntaxTree, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>, System.Func`4<System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Diagnostic>,Microsoft.CodeAnalysis.SyntaxTree,System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(Microsoft.CodeAnalysis.CompilationStage, Boolean, Microsoft.CodeAnalysis.DiagnosticBag, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(Microsoft.CodeAnalysis.TouchedFileLogger, Microsoft.CodeAnalysis.Compilation ByRef, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.AdditionalTextFile>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.DiagnosticBag, System.Threading.CancellationToken, System.Threading.CancellationTokenSource ByRef, Boolean ByRef, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver ByRef)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter, Microsoft.CodeAnalysis.ErrorLogger, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc+<>c__DisplayClass1_0.<Run>b__0(System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`2<System.IO.TextWriter,Int32>)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(System.String[], Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(System.String[], Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.BuildPaths, System.IO.TextWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])
____________
Faulting application name: csc.exe, version: 2.9.0.63208, time stamp: 0x970ce7d3
Faulting module name: KERNELBASE.dll, version: 10.0.16299.611, time stamp: 0x2ef5f131
Exception code: 0xe0434352
Fault offset: 0x00000000000450d8
Faulting process id: 0xa54
Faulting application start time: 0x01d450f8f2e6938f
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csc.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ec5a9265-9ed1-4c5a-b982-420f7b352b23
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by jcouv** [comment]
@MilKAOS Sorry to hear about that.
This feels like a setup issue (a dll is missing). Specially, I suspect the `Microsoft.CodeAnalysis.dll` file is missing.

Could you share the output of the following directory listing command?

`dir /B "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\"`

After that and assuming the `Microsoft.CodeAnalysis.dll` file is indeed missing, I'd recommend you try "Repair" in the installer. If that doesn't help, I'll forward this issue to the installer team.

**Comment by MilKAOS** [comment]
No, it is unfortunately not that easy. We already tried repair and reinstallation of VS 2017.

![csc](https://user-images.githubusercontent.com/18283597/45864886-dcedd000-bd7b-11e8-8175-2525a4dd7535.PNG)

**Comment by MilKAOS** [comment]
P.S. I tried to get additional information with crash dumps via the documented registry entries. But unfortunately no crash dumps get created. I can only guess it is because deven.exe itself doesn't crash but a part Visual Studio uses.
If someone has ideas how I can collect more information which could help, please let me know.

**Comment by jaredpar** [comment]
This definitely looks like a bad installation. Can you zip up the folder containing csc.exe and share it out for us to take a look at?

**Comment by MilKAOS** [comment]
Of course, no problem. The files are attached as zip.
[Roslyn.zip](https://github.com/dotnet/roslyn/files/2414101/Roslyn.zip)

**Comment by jaredpar** [comment]
Thanks for providing that. The binaries in that folder are correct. I examined both the versions and compiled some applications that should excercise the code path that was failing. So that still points to something specific to your machine.

One thought: can you check and see if there are any assemblies that start with the name Microsoft.CodeAnalysis in the GAC?

**Comment by MilKAOS** [comment]
There is a Microsoft.CodeAnalysis folder in the GAC but the folder is empty. Should I remove the folder?
![image](https://user-images.githubusercontent.com/18283597/46142368-0bc1e580-c257-11e8-96db-934d3a448a3b.png)

**Comment by MilKAOS** [comment]
In between I installed DebugDiag to get more crash information. You can find two detailed crash logs attached. Maybe that helps a little bit.

My workflow for both crahshes:
1. I started VS 2017.
2. I opened the console solution I created earlier via the Startup screen.
3. I run the build. (The errors were shown.)
4. I closed VS 2017.

[devenv__PID__244__Date__09_27_2018__Time_02_03_10PM__547__Log.txt](https://github.com/dotnet/roslyn/files/2423984/devenv__PID__244__Date__09_27_2018__Time_02_03_10PM__547__Log.txt)
[devenv__PID__7536__Date__09_27_2018__Time_01_56_24PM__330__Log.txt](https://github.com/dotnet/roslyn/files/2423985/devenv__PID__7536__Date__09_27_2018__Time_01_56_24PM__330__Log.txt)

**Comment by jaredpar** [comment]
Can you use `gacutil` to see if it believes any copies are installed into the GAC? That would be the more definitive method.

**Comment by MilKAOS** [comment]
```
C:\>gacutil /l Microsoft.CodeAnalysis
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:

Number of items = 0
```

Attached is also the complete GAC list. But there is nothing which I could relate to CodeAnalysis.
[output.txt](https://github.com/dotnet/roslyn/files/2430515/output.txt)

**Comment by jaredpar** [comment]
Hmm. I'm going to ask around about this. I'm pretty much at a loss as to what is going on here. It's very certainly a machine state issue as I can run the binaries locally and produce binaries (as well as go through other tests to look for consistency issues). But given that it's across four machines that's particularly odd. I've eliminated all the other items that I would suspect being a problem here.

**Comment by jaredpar** [comment]
@MilKAOS one idea that popped up. Have you tried running `csc.exe` on a simple "Hello World" style application directly? That would isolate out potential issues in your build setup.

**Comment by MilKAOS** [comment]
@jaredpar Yes, your description is absolutely correct.

Maybe the behavior is better visible in the crash dump logs I attached earlier.  Because it contains the start of Visual Studio and the crash. Is something missing at the startup of Visual Studio, is something used which shouldn't be used (.NET framework issues)? We are confused as well.

And it is not only our four development machines (which could be plausible because of the similar setup) but also our two build servers (which run on different hardware and OS).

**Comment by jaredpar** [comment]
Can you do a build from Visual Studio then and grab a binary log when csc crashes? This extension will help with the generation of the log files.

https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools

**Comment by jaredpar** [comment]
Do you have JustMock installed on your machines? If so is there a correlation with the broken machines and the ones that have that installed?

**Comment by MilKAOS** [comment]
@jaredpar Yes, we actually have and it is of course on all these machines. 
I just tried by uninstalling JustMock on my machine and now the builds work. It really seems to be the problem, thank you very much!

**Comment by jaredpar** [comment]
Glad that was the issue. Profilers can have tricksy behavior like this. 

Thanks for providing the binlog. That was the key to figuring this out!
