### ISSUE TITLE
Cannot include resources in Script compilination options.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#30090]
**Version Used**: Latest from nuget

**Steps to Reproduce**:

1. Create a new C# Console App
2. Set the contents of the program to
```cs
// Main() method
AppDomain.CurrentDomain.UnhandledException += UnhandledException;
var scriptTask = CSharpScript.Create(
    File.OpenRead($"{Environment.CurrentDirectory}{Path.DirectorySeparatorChar}Scripts{Path.DirectorySeparatorChar}Main.csx"),
    ScriptOptions.Default.WithFilePath($"{Environment.CurrentDirectory}{Path.DirectorySeparatorChar}Scripts{Path.DirectorySeparatorChar}Main.csx")).RunAsync();

// seems to throw the exception here.
if (scriptTask.Result.Exception != null)
{
}

private static void UnhandledException(object sender, UnhandledExceptionEventArgs e)
{
    var ex = (Exception)e.ExceptionObject;
    MessageBox.Show($"{ex.InnerException.Message}{Environment.NewLine}{ex.InnerException.StackTrace}", "Script Error!", MessageBoxButtons.OK, MessageBoxIcon.Error);
    Console.WriteLine($"{ex.InnerException.Message}{Environment.NewLine}{ex.InnerException.StackTrace}");
    Application.Exit();
}
```
And this on the script:
```cs
public class Test
{
    public Test()
    {
        // exception should be from this line.
        System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Test));
    }
}
```
3. Hit F5
4. Observe the following exception similar to this one:
```cs
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Form1.resources" was correctly embedded or linked into assembly "R*a720db28-a50b-47d6-a97f-4547c24066a1#1-0" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName)
   at Submission#0.Form1.InitializeComponent()
   at Submission#0.Form1..ctor()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TestImageZooming.Program.Main() in C:\Users\User\Desktop\TestImageZooming\Program.cs:line 29
```

**Expected Behavior**:
To be able to embed the resources into the compilation of the scripts.
**Actual Behavior**:
No way to include them currently.

**Comment by AraHaan** [comment]
cc: @tannergooding

**Comment by tmat** [comment]
Why do you need resources in a script?

**Comment by AraHaan** [comment]
Well in a project, I am creating a GUI (Windows Forms) inside of a script to allow people to extend it using Scripts. However the GUI needs resources.

**Comment by tmat** [comment]
You want the extensions to define their own resources, or do you just need them to access the application resources?

**Comment by AraHaan** [comment]
I want them to have their own.

**Comment by tmat** [comment]
In that case they would need to compile the resources into an assembly that's distributed with the script and pass a type from that assembly to `System.ComponentModel.ComponentResourceManager`.
