### ISSUE TITLE
AD0001 should not be reported for expected cancellation

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30264]
**Version Used**: 15.9 Preview 2

**Steps to Reproduce**:

1. Write a `SyntaxNode` analyzer
2. In the analyzer, call `context.CancellationToken.ThrowIfCancellationRequested()`

**Expected Behavior**:

In cancellation scenarios, the IDE silently stops analysis and continues execution.

**Actual Behavior**:

The IDE reports AD0001 for the analyzer throwing an exception. Here is an example:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD001UseSwitchToMainThreadAsyncAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at D:\dev\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(924,21): System.OperationCanceledException The operation was canceled.. Syntax: Debug.Assert(methodSymbol.IsImplicitlyDeclared)'.	Microsoft.CodeAnalysis.CSharp		1	Active	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD001UseSwitchToMainThreadAsyncAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.CSharp
SyntaxTree: D:\dev\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs
SyntaxNode: Debug.Assert(methodSymbol.IsImplicitlyDeclared ... [InvocationExpressionSyntax]@[45231..45278) (923,20)-(923,67)

System.Exception: Analyzer failure while processing syntax at D:\dev\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(924,21): System.OperationCanceledException The operation was canceled.. Syntax: Debug.Assert(methodSymbol.IsImplicitlyDeclared) ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
-----
'.
```

**Comment by mavasani** [comment]
Interesting we do seem to handle cancellation in the exception filter before reporting AD0001: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1411. Need to investigate how the cancellation token passed to the context is different from the one help by the driver.

**Comment by AArnott** [comment]
This is because we wrap `OperationCanceledException` along with all other exceptions thrown from analyzers in an `Exception` that gives much more context about where the error occurred so that such error reports are more actionable. 
We didn't mean to or need to wrap OCE in particular, but we hadn't had a special case to let that slip through. We fixed this in https://github.com/Microsoft/vs-threading/commit/061223411ac5b545fac24ff7c133bde57334033e and https://github.com/Microsoft/vs-threading/commit/f88fbddfdf4090d76535ba38e9594fe97adb2c22, which both shipped with v15.8.168 of our analyzers. Are you running something older than that?

**Comment by CyrusNajmabadi** [comment]
This was closed as no-repro.  But i'm hitting this.  What info do you need to help track this down.

**Comment by CyrusNajmabadi** [comment]
@mavasani ^

**Comment by AArnott** [comment]
@CyrusNajmabadi :  Answer is above, and quoted below

> We fixed this in Microsoft/vs-threading@0612234 and Microsoft/vs-threading@f88fbdd, which both shipped with v15.8.168 of our analyzers. Are you running something older than that?

**Comment by CyrusNajmabadi** [comment]
I'm running 
![image](https://user-images.githubusercontent.com/4564579/46826456-dc2cd600-cd4a-11e8-8c3c-de9139ed4f50.png)

Is the fix in there?

**Comment by CyrusNajmabadi** [comment]
I dn't know hot to figure out what version of Microsoft.VisualStudio.Threading.Analyzers is running.  Where would i look for that dll?

**Comment by mavasani** [comment]
@sharwell Which branch of Roslyn has the required VS threading analyzers package?

**Comment by AArnott** [comment]
@CyrusNajmabadi this isn't anything to do with the version of VS you're running. The analyzers are brought in via a nuget package reference. You can look in your project.assets.json file to see what version of the analyzers the project that showed this error has brought in.

**Comment by sharwell** [comment]
@mavasani Roslyn uses a version of these analyzers which does not contain the fix. It doesn't have any impact on builds, it's just a sporadic message in the error list.

**Comment by AArnott** [comment]
It should be easy enough to update the version of the analyzers though, right? Can you just do that?

**Comment by CyrusNajmabadi** [comment]
What nuget reference is needed for thsi? I searched for Microsoft.VisualStudio.Threading, but i couldn't find anything.

**Comment by mavasani** [comment]
> Roslyn uses a version of these analyzers which does not contain the fix. It doesn't have any impact on builds, it's just a sporadic message in the error list.

Ah, I thought this was closed as no-repro as we moved a specific branch to the required analyzer package version.

**Comment by tateisu** [comment]
still I got this warning.

```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態	詳細の説明
警告	AD0001	アナライザー 'Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer' が型 'System.OperationCanceledException' の例外をメッセージ '操作は取り消されました。' 付きでスローしました。	StarGarner-XamlProject		1	アクティブ	アナライザー 'Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer'が、次の例をスローしました:
'System.OperationCanceledException: 操作は取り消されました。
   場所 System.Threading.CancellationToken.ThrowOperationCanceledException()
   場所 System.Threading.CancellationToken.ThrowIfCancellationRequested()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.ThrowIfCanceled()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.NextToken()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.ParseXmlDocument(Int32 elements)
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.ParseXmlDocument()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.CachingParser.ParseAndCacheResult(Parser parser, CachedParseResult resultContext, ITextSnapshot textSnapshot)
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.CachingParser.GetOrParseXmlDocument(ITextSnapshot textSnapshot, IXmlParseContext parseContext, IMarkupSourceProvider sourceProvider, CancellationToken cancelToken, Parser parser)
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.CreateXmlTree(CancellationToken cancellationToken)
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<>c__DisplayClass433_0.<GetXmlTreeAsync>b__0()
   場所 System.Threading.Tasks.Task`1.InnerInvoke()
   場所 System.Threading.Tasks.Task.Execute()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<GetXamlTreeAsync>d__435.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<Microsoft-VisualStudio-DesignTools-Xaml-LanguageService-Semantics-IXamlFileInformationContext-GetMessagesAsync>d__385.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   場所 Microsoft.VisualStudio.DesignTools.Xaml.CodeAnalysis.Diagnostics.Analyzers.XamlDocumentAnalyzerService.<AnalyzeSyntaxAsync>d__15.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer.<AnalyzeSyntaxAsync>d__2.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.<ComputeDocumentDiagnosticAnalyzerDiagnosticsAsync>d__30.MoveNext()
-----
'。
```

environment
```
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.8.03752

インストールされているバージョン:Community

Visual C++ 2019   00435-60000-00000-AA241
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

C# ツール   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
IDE で使用する C# コンポーネント。プロジェクトの種類や設定に応じて、異なるバージョンのコンパイラを使用できます。

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

F# 4.7 の Visual F# Tools 10.8.0.0    16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
F# 4.7 の Microsoft Visual F# Tools 10.8.0.0

IntelliCode 拡張機能   1.0
IntelliCode Visual Studio 拡張機能の詳細情報

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ ウィザード   1.0
Microsoft Visual C++ ウィザード

Microsoft Visual Studio VC パッケージ   1.0
Microsoft Visual Studio VC パッケージ

NuGet パッケージ マネージャー   5.5.0
Visual Studio 内の NuGet パッケージ マネージャー。NuGet の詳細については、https://docs.nuget.org/ にアクセスしてください

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Google Test 向けに作成された単体テストを含む、Visual Studio のテスト ツールを有効にします。拡張機能のインストール ディレクトリに、使用条件およびサード パーティからの通知が含まれています。

Visual Basic ツール   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
IDE で使用する Visual Basic コンポーネント。プロジェクトの種類や設定に応じて、異なるバージョンのコンパイラを使用できます。

Visual Studio Code デバッグ アダプターのホスト パッケージ   1.0
Visual Studio Code デバッグ アダプターを Visual Studio でホストするための相互運用レイヤー

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

**Comment by sharwell** [comment]
@tateisu That is a very different issue. Can you file an issue using the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool for Visual Studio?

**Comment by tateisu** [comment]
I was added AD0001 to suppress warnings and then removed, the warning was gone.
I will report if I get same warning again.

**Comment by sharwell** [comment]
@mavasani I missed that `XamlDocumentDiagnosticAnalyzer` is part of this repository. Can you check that it's using the correct cancellation token?

**Comment by mavasani** [comment]
The analyzer calls into [IXamlDocumentAnalyzerService](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Xaml/Impl/Diagnostics/Analyzers/IXamlDocumentAnalyzerService.cs), which is not implemented in this repo. Should likely be moved to the XAML team?
