### ISSUE TITLE
NRE at Microsoft.CodeAnalysis.CSharp.Diagnostics.CSharpUnboundIdentifiersDiagnosticAnalyzer.ConstructorDoesNotExist

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#3027]
I saw the following in my error list:

```
Severity	Code	Description	Project	File	Line	Detail Description
Message	AD0001	The User Diagnostic Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.CSharpUnboundIdentifiersDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	CodeAnalysisDiagnosticAnalyzers		1
```
> Analyzer 'Microsoft.CodeAnalysis.CSharp.Diagnostics.CSharpUnboundIdentifiersDiagnosticAnalyzer' threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.CSharpUnboundIdentifiersDiagnosticAnalyzer.ConstructorDoesNotExist(SyntaxNode node, SymbolInfo info, SemanticModel model)
   at Microsoft.CodeAnalysis.Diagnostics.AddImport.UnboundIdentifiersDiagnosticAnalyzerBase`5.ReportUnboundIdentifierNames(SyntaxNodeAnalysisContext context, SyntaxNode member)
   at Microsoft.CodeAnalysis.Diagnostics.AddImport.UnboundIdentifiersDiagnosticAnalyzerBase`5.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass32_0`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze, Action`3 onAnalyzerException, CancellationToken cancellationToken)'.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/b041933a34ec47aef5f71894777f40639429d5a3
