### ISSUE TITLE
Rolsyn 2.9.0 very broken or is it me?

### ISSUE THREAD

**Issue by zezba9000** [dotnet/roslyn#30307]
**Version Used**: Works in 2.8.2 but broken in 2.9.0

**Steps to Reproduce**:
NOTE: Two bugs here.

1. Update this proj on GitHub to 2.9.0: https://github.com/zezba9000/CSharpTranspiler
2. Install other missing packages: Microsoft.CodeAnalysis.Workspaces.MSBuild & Microsoft.Build.Runtime
3. Put a break-point on line 29 in file "CSharpTranspiler/Program.cs"
4. Run "CSharpTranspiler" proj and you will get a broken "System.Runtime" exception.
5. Resolve the issue by deleting the "App.config" file
6. Run again and Roslyn's "CSharpParseOptions.ParseOptions.LanguageVersion" thinks what is a "**.NET 2.0 + C# 3.0**" proj is "**C# 7.x**" (which is totally wrong)

**Expected Behavior**:
Should work like 2.8.2 does.
NOTE: C# 3 to C# 7 issue exists in .NET Core proj as well.

**Actual Behavior**:
Fails to resolve dependencies correctly.
Fails to get C# lang version correctly in proj

**Other Info**
Microsoft Visual Studio Community 2017 Version 15.8.6
CSharpTranspiler proj Targeting .NET framework 4.7.2 + C# 7.3
Roslyn trying to load a proj with .NET 2.0 + C# 3.0

**Comment by jaredpar** [comment]
> Run "CSharpTranspiler" proj and you will get a broken "System.Runtime" exception.

Can you give us the full exception information here including the stack trace? 

> Resolve the issue by deleting the "App.config" file

Can you you post the contents of app.config? Guessing this is binding redirect related.

**Comment by zezba9000** [comment]
Error message

> Could not load file or assembly 'System.Composition.TypedParts, Version=1.0.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack Trace

>    at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
>    at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.get_DefaultServices()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create()
>    at CSharpTranspiler.Agnostic.Solution.<Parse>d__5.MoveNext() in C:\Users\zezba9000\Dev\Andrew\CSharpTranspiler\CSharpTranspiler\Agnostic\Solution.cs:line 31
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at CSharpTranspiler.Program.<Compile>d__1.MoveNext() in C:\Users\zezba9000\Dev\Andrew\CSharpTranspiler\CSharpTranspiler\Program.cs:line 23

App.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection.Metadata" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4.3.0" newVersion="1.4.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.3.0" newVersion="1.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Xml.ReaderWriter" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Composition.AttributedModel" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.33.0" newVersion="1.0.33.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Composition.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.33.0" newVersion="1.0.33.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Composition.TypedParts" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.33.0" newVersion="1.0.33.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Composition.Hosting" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.33.0" newVersion="1.0.33.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Algorithms" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Xml.XPath.XDocument" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.FileVersionInfo" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Thread" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Linq" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Linq.Expressions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

package.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Build" version="15.8.166" targetFramework="net47" />
  <package id="Microsoft.Build.Framework" version="15.8.166" targetFramework="net47" />
  <package id="Microsoft.Build.Runtime" version="15.8.166" targetFramework="net47" />
  <package id="Microsoft.Build.Tasks.Core" version="15.8.166" targetFramework="net47" />
  <package id="Microsoft.Build.Utilities.Core" version="15.8.166" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="2.6.1" targetFramework="net47" developmentDependency="true" />
  <package id="Microsoft.CodeAnalysis.Common" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.VisualBasic" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.VisualBasic.Workspaces" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.Workspaces.Common" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.CodeAnalysis.Workspaces.MSBuild" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.VisualStudio.LanguageServices" version="2.9.0" targetFramework="net47" />
  <package id="Microsoft.VisualStudio.Setup.Configuration.Interop" version="1.16.30" targetFramework="net47" developmentDependency="true" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.2" targetFramework="net47" />
  <package id="SQLitePCLRaw.core" version="1.1.2" targetFramework="net47" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.1.2" targetFramework="net47" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.1.2" targetFramework="net47" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.1.2" targetFramework="net47" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.1.2" targetFramework="net47" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net47" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net47" />
  <package id="System.Composition" version="1.0.31" targetFramework="net47" />
  <package id="System.Composition.AttributedModel" version="1.0.31" targetFramework="net47" />
  <package id="System.Composition.Convention" version="1.0.31" targetFramework="net47" />
  <package id="System.Composition.Hosting" version="1.0.31" targetFramework="net47" />
  <package id="System.Composition.Runtime" version="1.0.31" targetFramework="net47" />
  <package id="System.Composition.TypedParts" version="1.0.31" targetFramework="net47" />
  <package id="System.Console" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.StackTrace" version="4.3.0" targetFramework="net47" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net47" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net47" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net47" />
  <package id="System.IO" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net47" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq" version="4.3.0" targetFramework="net47" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net47" />
  <package id="System.Reflection.Metadata" version="1.6.0" targetFramework="net47" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net47" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net47" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding.CodePages" version="4.3.0" targetFramework="net47" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Tasks.Dataflow" version="4.5.24" targetFramework="net47" />
  <package id="System.Threading.Tasks.Extensions" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="net47" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="net47" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="net47" />
  <package id="System.Xml.XPath.XDocument" version="4.3.0" targetFramework="net47" />
</packages>
```

**Comment by zezba9000** [comment]
Also pushed up a Roslyn Update branch: https://github.com/zezba9000/CSharpTranspiler/tree/RoslynUpdate

RoslynUpdate (2.9.0) = broken
master (2.8.2) = working

**Comment by jaredpar** [comment]
CC @DustinCampbell as it appears to be a workspace issue

**Comment by DustinCampbell** [comment]
The issue here is that `Microsoft.Build.Runtime` was used instead of `Microsoft.Build.Locator`. The difference between these packages is significant. When you use `Microsoft.Build.Runtime`, you're expected to include the full MSBuild toolset needed to process and projects and solutions that your application needs to open with your application. In contrast, `Microsoft.Build.Locator` finds an instance of MSBuild on your machine (likely in Visual Studio) and uses that for opening projects and solutions.

@zezba9000, I've submitted a PR to your project that applies the changes necessary to update your project to 2.9.0: https://github.com/zezba9000/CSharpTranspiler/pull/1.

**Comment by zezba9000** [comment]
Interesting, ok tnx, I'll go through the pull request this weekend tnx!
If there are migration docs in this area, let me know and I'll make sure to reference it in the future.
