### ISSUE TITLE
ChangeSignature isn't aware of nullability

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#30315]
1. The popup dialog doesn't display nullability annotations (`?`).
2. Changing the order of parameters on a signature involving nullability causes a crash.

![image](https://user-images.githubusercontent.com/12466233/46497221-d2492700-c7ce-11e8-921d-af8617290154.png)

FYI @dpoeschl

**Comment by CyrusNajmabadi** [comment]
That's concerning.  What's the crash? Does that indicate some change in behavior in existing APIs that is not compatible with previous contracts?

**Comment by jcouv** [comment]
The crash shows an `InvalidOperationException` with `WaitAndGetResult cannot be called from a thread pool thread.`. That doesn't look related to nullability.
This is on 15.9 preview 1.

@dpoeschl Does this look familiar by any chance?


```
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 75
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalyzedContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken, Solution& updatedSolution) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 209
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalyzedContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 160
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options, CancellationToken cancellationToken) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\ChangeSignatureCodeAction.cs:line 33
   at Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.<GetOperationsAsync>d__1.MoveNext() in C:\repos\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeActionWithOptions.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 87
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 74
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument, IProgressTracker progressTracker, CancellationToken cancellationToken) in C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActions\SuggestedAction.cs:line 153
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0() in C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActions\SuggestedAction.cs:line 138
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager, Object extension, Action action) in C:\repos\roslyn\src\Workspaces\Core\Portable\ExtensionManager\IExtensionManagerExtensions.cs:line 23
```

**Comment by dpoeschl** [comment]
Yeah, seems unrelated. Probably need to do something like https://github.com/dotnet/roslyn/pull/29484 here as well

**Comment by dpoeschl** [comment]
Should have emphasized the "seems". It's reproing in this scenario for you?

**Comment by jcouv** [comment]
Yes, I repro'ed this on two machines (work and home). Both with 15.9.
In one case I used the async-streams branch as-is, in the other case I used a merge of dev16.0.x into the async-streams branch (this is where the stacktrace was taken from).
I will try again this afternoon with plain dev16.0.x for comparison.

**Comment by jasonmalinowski** [comment]
Confirmed that the crash is badness in this code doing async-over-sync-over-async and isn't related to nullable -- if you remove the assert it works just fine. That's also asserting in literally any application, so it's not new.
