### ISSUE TITLE
Crash in VS Editor when viewing interpolated string with format specifiers

### ISSUE THREAD

**Issue by peterwald** [dotnet/roslyn#30378]
**Version Used**: 

**Steps to Reproduce**:

1. Open a source file containing the following line of code:
```csharp
var filename = $"{generation:000}-{index:0000}{ext}";
```

**Expected Behavior**:
View source code with syntax highlighting.

**Actual Behavior**:

VS crashes and restarts.

Crashes at this location: https://github.com/dotnet/roslyn/blob/fe80f83075d723eddd6e26582c75f27f242c69c4/src/Workspaces/CSharp/Portable/EmbeddedLanguages/VirtualChars/CSharpVirtualCharService.cs#L53

Stack:
```
ModLoad: 25570000 25575000   C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Diagaa8d7fa5#\75439711865fc400acd68387b8b053b4\System.Diagnostics.Debug.ni.dll
CLR: Managed code called FailFast, saying "System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.InterpolationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.InterpolatedStringExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.EmbeddedLanguages.VirtualChars.CSharpVirtualCharService.TryConvertToVirtualCharsWorker(SyntaxToken token)
   at Microsoft.CodeAnalysis.EmbeddedLanguages.VirtualChars.AbstractVirtualCharService.TryConvertToVirtualChars(SyntaxToken token)
   at Microsoft.CodeAnalysis.EmbeddedLanguages.LanguageServices.FallbackEmbeddedLanguage.FallbackSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxToken token, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.Classifiers.AbstractEmbeddedLanguagesClassifier.AddClassifications(Workspace workspace, SyntaxToken token, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyToken(SyntaxToken syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()"
```

**Comment by Neme12** [comment]
Tagging @CyrusNajmabadi (this is inside virtual char service)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi (or whoever) if you're able to manage a fix please target it at dev16.0.x.

**Comment by CyrusNajmabadi** [comment]
Will do.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Fix available.
