### ISSUE TITLE
VB: Multiple refactoring providers crash when invoking rename refactoring on lambda parameter.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#30390]
**Version Used**: 

Visual Studio Community 2017 v15.8.5

**Steps to Reproduce**:

Type in the following code:

```vb
Public Module Module1
  Public Sub Run(ArgAction As Func(Of String, Integer))
  End Sub

  Public Sub Main()
    Run(Function(foo) foo.Length)
  End Sub
End Module
```

Next we want to rename the parameter `foo` in the lambda function passed in the call to `Run(...)` so it becomes `food`. Put the caret at the end of `foo` add the `d`. The rename tracking rectangle is activated and the lightbulb is shown:

![vs_rename_crash_1](https://user-images.githubusercontent.com/20465797/46643695-e5207a80-cb85-11e8-9740-dc989b8727f8.png)

If you click the lightbulb (or use the keyboard shortcut) to show the code actions menu, the menu is shown after a brief pause and two refactoring code providers crash immediately:

![vs_rename_crash_2](https://user-images.githubusercontent.com/20465797/46643777-37fa3200-cb86-11e8-8200-ba564fd7a8ab.png)

The stack trace for `VisualBasicAddParameterCheckCodeRefactoringProvider` is:

```
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicAddParameterCheckCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

...and the stack trace for `VisualBasicInitializeMemberFromParameterCodeRefactoringProvider` is:

```
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Expected Behavior**:

The rename operation can be completed without a problem and nothing fatal happens, but it would be great if code providers not related to the rename operation did not crash. Looking at the above stack traces, the culprit seems to be the same function:

```
Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation()
```

**Comment by ericmutta** [comment]
An extra bit of detail: those providers do NOT crash if you do the rename by right-clicking on `foo` and choosing `Rename...` to bring up the rename dialog.

**Comment by Neme12** [comment]
duplicate of #29333?
