### ISSUE TITLE
Handle null descriptor in DiagnosticAnalyzer.SupportedDiagnostics

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30453]
Likely cause of intermittent FailFast in integration tests: https://ci.dot.net/job/dotnet_roslyn/job/dev16.0.x/job/windows_debug_vs-integration_prtest/189/artifact/Binaries/Debug/UnitTests/Microsoft.VisualStudio.LanguageServices.IntegrationTests/xUnitResults/Screenshots/Unknown-RemotingException-16.23.36.DotNet.log

```
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.ComputeDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.GetOrComputeDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.GetSupportedDiagnosticDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, Func`2 isCompilerAnalyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, AnalyzerManager analyzerManager, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<GetAnalyzerActionsAsync>d__105.MoveNext()
```

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/30454
