### ISSUE TITLE
Intermittent integration test failures: BasicNavigationBar.CodeSpit and BasicNavigationBar.VerifyNavBar

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#30544]
See https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/4564/artifact/Binaries/debug/Logs/Microsoft.VisualStudio.LanguageServices.IntegrationTests.dll.out.log

```
Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.CodeSpit [STARTING]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.ObjectExtensions.GetFieldValue(Object instance, String fieldName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.ObjectExtensions.GetFieldValue[FieldType](Object instance, String fieldName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetNavigationBarComboBoxes(IWpfTextView textView)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass54_0.<GetSelectedNavBarItem>b__0(IWpfTextView v)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass9_0`1.<ExecuteOnActiveView>b__0()
           at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread[T](Func`1 action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ExecuteOnActiveView[T](Func`2 action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetSelectedNavBarItem(Int32 comboBoxIndex)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetSelectedNavBarItem(Int32 comboBoxIndex)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs(279,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.GetTypeNavBarSelection()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs(104,0): at Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.VerifyLeftSelected(String expected)
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs(80,0): at Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.CodeSpit()
    Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.CodeSpit [FINISHED] Time: 0.572537s
```

```
    Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.VerifyNavBar [STARTING]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        
        Server stack trace: 
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.ObjectExtensions.GetFieldValue(Object instance, String fieldName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.ReflectionExtensions.ObjectExtensions.GetFieldValue[FieldType](Object instance, String fieldName)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetNavigationBarComboBoxes(IWpfTextView textView)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.<>c__DisplayClass54_0.<GetSelectedNavBarItem>b__0(IWpfTextView v)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass9_0`1.<ExecuteOnActiveView>b__0()
           at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
           at System.Windows.Threading.DispatcherOperation.InvokeImpl()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
           at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread[T](Func`1 action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ExecuteOnActiveView[T](Func`2 action)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetSelectedNavBarItem(Int32 comboBoxIndex)
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Editor_InProc.GetSelectedNavBarItem(Int32 comboBoxIndex)
        /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.cs(279,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.GetTypeNavBarSelection()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs(104,0): at Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.VerifyLeftSelected(String expected)
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicNavigationBar.cs(40,0): at Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.VerifyNavBar()
    Roslyn.VisualStudio.IntegrationTests.Basic.BasicNavigationBar.VerifyNavBar [FINISHED] Time: 0.4626095s
```

**Comment by JoeRobich** [comment]
Hit this again in #31605 [Build logs](https://dnceng.visualstudio.com/public/_build/results?buildId=54666)

**Comment by JoeRobich** [comment]
Hit this again in #31622 [Build logs](https://dnceng.visualstudio.com/public/_build/results?buildId=54690)
