### ISSUE TITLE
ExtractMethodCodeRefactoringProvider threw NullReferenceException when highlighting a method invocation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#30750]
**Version Used**: 

**Steps to Reproduce**:

1. Highlight the text between the '$' (remove the $ first)

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System.Collections.Immutable;

namespace Microsoft.VisualStudio.ProjectSystem.LanguageServices
{
    internal interface SimpleProjectDiff
    {
        public ProjectChangeDiff(IImmutableSet<string> addedItems, IImmutableSet<string> removedItems)
        {
            Requires.$NotEmpty$(addedItems, nameof(addedItems));
            Requires.NotEmpty(removedItems, nameof(removedItems));

            AddedItems = addedItems;
            RemovedItems = removedItems;

        }
        public IImmutableSet<string> AddedItems
        {
            get;
        }

        public IImmutableSet<string> RemovedItems
        {
            get;
        }
    }
}

```

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpTriviaResult.AnnotationResolver(SyntaxNode node,TriviaLocation location,SyntaxAnnotation annotation,SyntaxNode callsite,MethodDeclarationSyntax method)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpTriviaResult.<>c__DisplayClass2_0.<GetAnnotationResolver>b__0(SyntaxNode node,TriviaLocation location,SyntaxAnnotation annotation)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.<>c__DisplayClass13_0.<RecoverTokensAtEdges>b__1(TriviaLocation location)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IEqualityComparer`1 comparer)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.RecoverTokensAtEdges(SyntaxNode root,AnnotationResolver annotationResolver)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.RestoreTrivia(SyntaxNode root,AnnotationResolver annotationResolver,TriviaResolver triviaResolver)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.TriviaResult.ApplyAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by davkean** [comment]
Looks like it's related to the fact this this method body lives in an interface - I was in the middle of a refactoring.
