### ISSUE TITLE
FindSymbols throws on broken code

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30763]
```
10/25/2018 12:19:03 : Error : Microsoft.CodeAnalysis.Remote.CodeAnalysisService (994) : Exception: System.NotSupportedException: There are no pointer types in VB.
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CommonCreatePointerTypeSymbol(ITypeSymbol elementType)
   at Microsoft.CodeAnalysis.Compilation.CreatePointerTypeSymbol(ITypeSymbol pointedAtType)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.SymbolKey.PointerTypeSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKey()
   at Microsoft.CodeAnalysis.SymbolKey.Reader`1.ReadArray[T](Func`1 readFunction)
   at Microsoft.CodeAnalysis.SymbolKey.MethodSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKeyWorker(Boolean first)
   at Microsoft.CodeAnalysis.SymbolKey.Resolve(String symbolKey, Compilation compilation, Boolean ignoreAssemblyKey, Boolean resolveLocations, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.DeclarationFinder.<>c__DisplayClass1_0.<AddCompilationDeclarationsWithNormalQueryAsync>b__1(SymbolAndProjectId s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.FindSymbols.DeclarationFinder.<AddCompilationDeclarationsWithNormalQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.DeclarationFinder.<FindAllDeclarationsWithNormalQueryInCurrentProcessAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.DeclarationFinder.<FindAllDeclarationsWithNormalQueryAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.AllSymbolsProjectSearchScope.<FindDeclarationsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by jinujoseph** [comment]
@heejaechang  do you have a repro/example of a broken code which caused this ?

**Comment by CyrusNajmabadi** [comment]
Looks related to doing a FindRefs on a method in a cross-language scenario that contains a pointer type.  Hopefully should not be hard to repro.

**Comment by CyrusNajmabadi** [comment]
This was fixed.
