### ISSUE TITLE
VisualBasicInitializeMemberFromParameterCodeRefactoringProvider throws

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30779]
```
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Neme12** [comment]
duplicate of @29333?

**Comment by sharwell** [comment]
Duplicate of #29333
