### ISSUE TITLE
VisualBasicAddParameterCheckCodeRefactoringProvider throws

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30780]
```
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicAddParameterCheckCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by heejaechang** [comment]
I think this is the code when it throws

ublic Async Function MapSpansAsync(document As Document, spans As IEnumerable(Of TextSpan), cancellationToken As CancellationToken) As Task(Of ImmutableArray(Of MappedSpanResult)) Implements ISpanMappingService.MapSpansAsync
                    Dim testWorkspace = DirectCast(document.Project.Solution.Workspace, TestWorkspace)
                    Dim testDocument = testWorkspace.GetTestDocument(document.Id)

                    Dim mappedTestDocument = testWorkspace.Documents.First(Function(d) $$)

**Comment by Neme12** [comment]
duplicate of #29333?

**Comment by sharwell** [comment]
Duplicate of #29333
