### ISSUE TITLE
await struct that implements IObservable throws EntryPointNotFoundException

### ISSUE THREAD

**Issue by neuecc** [dotnet/roslyn#30956]
**Version Used**: 
Microsoft Visual Studio Professional 2017 Version 15.8.7

**Steps to Reproduce**:

1. Create a new C# Console App(.NET Framework) project
2. Add `System.Reactive` package from NuGet(latest, `4.1.2`)
3. Copy and paste following code
4. Run on Debug Mode

```csharp
using System;
using System.Reactive.Linq;
using System.Threading.Tasks;

public struct StructObservable<T> : IObservable<T>
{
    public IDisposable Subscribe(IObserver<T> observer)
    {
        observer.OnNext(default(T));
        observer.OnCompleted();
        return null;
    }
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("BEGIN ------");
        Foo.BarAsync().GetAwaiter().GetResult(); // System.EntryPointNotFoundException
        Console.WriteLine("END ------");
    }
}

public static class Foo
{
    public static async Task BarAsync()
    {
        await new StructObservable<int>();
    }
}
```

**Expected Behavior**:

Display shows

```
BEGIN ------
END ------
```

**Actual Behavior**:
Display shows

```
BEGIN ------

ハンドルされていない例外: System.EntryPointNotFoundException: エントリ ポイントが見つかりませんでした。
   場所 System.IObservable`1.Subscribe(IObserver`1 observer)
   場所 System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   場所 System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   場所 System.Reactive.Subjects.AsyncSubject`1.GetResult()
   場所 Foo.<BarAsync>d__0.MoveNext() 場所 C:\Users\S04451\source\repos\ConsoleApp4\ConsoleApp4\Program.cs:行 29
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   場所 Program.Main(String[] args) 場所 C:\Users\S04451\source\repos\ConsoleApp4\ConsoleApp4\Program.cs:行 20
```

(log is run on Japanese Windows, this means unhandled exception: System.EntryPointNotFoundException.)

---

If chainging `public struct StructObservable<T>` -> `public class StructObservable<T>`
or `await new StructObservable<int>()` -> `await new StructObservable<int>().AsObservable()` works fine.
If run on Release Mode, display shows `BEGIN ------` only. 
If run on Unity Editor, shows `InvalidProgramException: Invalid IL code in HogeMoge/<OnClick>d__3:MoveNext (): IL_0021: call      0x2b0000be`.

**Comment by itn3000** [comment]
When I ran the same source with dotnet core SDK 2.1.402,I got the following output:
```
BEGIN ------

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Reactive.Linq.Observable.GetAwaiter[TSource](IObservable`1 source) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable.Awaiter.cs:line 24
   at Foo.BarAsync() in G:\src\gitrepos\dotnet-sandbox\rxasynctest\Program.cs:line 29
   at Program.Main(String[] args) in G:\src\gitrepos\dotnet-sandbox\rxasynctest\Program.cs:line 20
```

Here is my `dotnet --info` output:
```
.NET Core SDK (global.json を反映):
 Version:   2.1.402
 Commit:    3599f217f4

ランタイム環境:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003133 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003156 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

And it was OK with same workaround.

**Comment by ufcpp** [comment]
Simpler repro:

```cs
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

public interface IAwaitable { }
public struct StructAwaitable : IAwaitable { }

public static class Extensions
{
    public static TaskAwaiter GetAwaiter(this IAwaitable x)
    {
        if (x == null) throw new ArgumentNullException(nameof(x));
        return Task.CompletedTask.GetAwaiter();
    }
}

class Program
{
    static async Task Main(string[] args)
    {
        await new StructAwaitable();
    }
}
```

Expected Behavior:
Completed successfully

Actual Behavior:
This code throws `ArgumentNullException`.

The IL generated from the `Main` (`<Main>d__0.MoveNext`) is:

```il
...
    IL_000c:  initobj    StructAwaitable
    IL_0012:  ldloc.2                    // Is the ldloc.2 redundant? or is stloc.2 needed before this line?
    IL_0013:  call       valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter Extensions::GetAwaiter(class IAwaitable)
    IL_0018:  stloc.1
...
```

**Comment by jaredpar** [comment]
@cston looks like we are missing a box operation in the emitted IL. The simple repro at the bottom demonstrates this easily.

``` il
IL_000a: ldloca.s 2
IL_000c: initobj StructAwaitable
IL_0012: ldloc.2
IL_0013: call valuetype [mscorlib]System.Runtime.CompilerServices.TaskAwaiter Extensions::GetAwaiter(class IAwaitable)
IL_0018: stloc.1
```

**Comment by cston** [comment]
Thanks for the repros. It looks like there is a related issue with collection initializers and structs. Logged #38726.
