### ISSUE TITLE
null exception from find symbols caused by VBMoveDeclarationNearReferenceCodeRefactoringProvider

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#30976]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.State.TryInitializeAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.State.GenerateAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveDeclarationNearReference.AbstractMoveDeclarationNearReferenceCodeRefactoringProvider`4.ComputeRefactoringsAsync[TService,TStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by heejaechang** [comment]
not sure what code caused this from happening since it is from code refactoring, my caret is already moved when info bar showed up.

**Comment by CyrusNajmabadi** [comment]
Hrmm.. would be hard to tell without more information.  Did a watson get sent?  The code for that method is simply:

```c#
            // Don't visit projects more than once.  
            if (visitedProjects.Add(projectId))
            {
                var project = _solution.GetProject(projectId);

                // Visit dependencies first.  That way the compilation for a project that we depend
                // on is already ready for us when we need it.
                foreach (var dependent in project.ProjectReferences)
                {
                    _cancellationToken.ThrowIfCancellationRequested();

                    await ProcessProjectAsync(
                        dependent.ProjectId, projectToDocumentMap, visitedProjects).ConfigureAwait(false);
                }

                await ProcessProjectAsync(project, projectToDocumentMap).ConfigureAwait(false);
            }
```

There are very little opportunities for null-refs.

1. visitedProjects is initialized at the start of thigns and passed in here.  it should be null.
2. We would rash if _solution.GetProject returned null. But that would indicate something *very* wrong with teh workspace since we're using projectIds returned from the dependency graph.  Definitely possible, but we need to really hope it's not that.  Did @jasonmalinowski 's work to change the dependency graph go in?
3. we would crash if project.ProjectReferences returns null.

Those are hte only 3, and right now '2' seems the most suspect.
3. project.Project

**Comment by CyrusNajmabadi** [comment]
Would `project.ProjectReferences` return `null` for any of its elements in that case?  If so, yes.  That would explain this.  Thanks!

**Comment by CyrusNajmabadi** [comment]
this was NRTified and we haven't hit this since.
