### ISSUE TITLE
Roslyn DLLs appear to be in the wrong subfolder of msbuild

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#31051]
**Version Used**: 28307.50.d16.0 with 2.11.0-beta1-63430-07+c96268112e069a5282fe6ab2b55db213c524b80c

**Steps to Reproduce**:

1. Install VS

**Expected Behavior**: Roslyn DLLs are under `msbuild\current\bin`

**Actual Behavior**: Roslyn DLLs are under `msbuild\15.0\bin`

As a result, the text templating build task fails:

```
Microsoft.TextTemplating.targets(340,5): error : An Exception was thrown while running the transformation code. The process cannot continue.  The following Exception was thrown:
Microsoft.TextTemplating.targets(340,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
Microsoft.TextTemplating.targets(340,5): error : File name: 'Microsoft.CodeAnalysis, Version=2.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Microsoft.TextTemplating.targets(340,5): error :    at Microsoft.VisualStudio.TextTemplating.CompilerBridge..ctor(String source, Boolean debug, IEnumerable`1 references, String cmdLineArguments)
Microsoft.TextTemplating.targets(340,5): error :    at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Create(SupportedLanguage language, String source, Boolean debug, IEnumerable`1 references, String cmdLineArguments)
Microsoft.TextTemplating.targets(340,5): error :    at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable`1 references, Boolean debug, SupportedLanguage language, String compilerOptions)
Microsoft.TextTemplating.targets(340,5): error :    at Microsoft.VisualStudio.TextTemplating.TransformationRunner.LocateAssembly(Boolean cacheAssemblies, String fullClassName, String source, String inputFile, Boolean debug, SupportedLanguage language, IEnumerable`1 compilerReferences, String compilerOptions)
Microsoft.TextTemplating.targets(340,5): error :    at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PrepareTransformation(TemplateProcessingSession session, String source, ITextTemplatingEngineHost host)
```

**Comment by amcasey** [comment]
FYI @jasonmalinowski @agocke

**Comment by jasonmalinowski** [comment]
@jaredpar and @rainersigwald probably want to know (or already do) too.

**Comment by jaredpar** [comment]
The DLLs are in the expected place right now. There is a plan to move them into current in the preview 2 time frame. This sounds like a bug in text templating. No one should be taking hard dependencies on where our binaries live. Not even MSBuild does this. 

Closing as a this time we are laying out binaries as we would expect.
