### ISSUE TITLE
Unable to decompile MemoryStream

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#31122]
I have code that references a System.IO.MemoryStream.

I then right click on the declaration of the memory stream and choose &quot;Go to Definition&quot;

The file that is then displayed starts like this and the code following clearly isn't the correct decompliation:

```
#region Assembly System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\brownm001\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.Extensions.dll
// Decompiled with ICSharpCode.Decompiler 3.1.0.3652
#endregion
/// Exception while reading XmlDoc: System.Xml.XmlException: The 'br' start tag on line 712 position 11 does not match the end tag of 'p'. Line 712, position 755.
///   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
///   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
///   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
///   at System.Xml.XmlTextReaderImpl.ParseEndElement()
///   at System.Xml.XmlTextReaderImpl.ParseElementContent()
///   at System.Xml.XmlTextReaderImpl.Read()
///   at System.Xml.XmlTextReader.Read()
///   at System.Xml.XmlTextReaderImpl.Skip()
///   at System.Xml.XmlTextReader.Skip()
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader)
///   at ICSharpCode.Decompiler.Documentation.XmlDocumentationProvider..ctor(String fileName)
///   at ICSharpCode.Decompiler.Documentation.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
///   at ICSharpCode.Decompiler.CSharp.Transforms.AddXmlDocumentationTransform.Run(AstNode rootNode, TransformContext context)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/357935/unable-to-decompile-memorystream.html
VSTS ticketId: 705871_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Decompilation succeeds locally for me.
