### ISSUE TITLE
InvalidOperationException when showing parameters in Immediate window

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#31180]
**Version Used**: VisualStudio.15.Preview/15.9.0-pre.6.0+28307.53

During a paused debugging session, in the Immediate window I tried to press Ctrl+K, P (show parameter info) on one of the lines I excuted earlier.
I was presented with ActivityLog.xml error:

```
System.InvalidOperationException: Nullable object must have a value.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.ComputeModel(ImmutableArray`1 providers, SignatureHelpTriggerInfo triggerInfo)
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.StartSession(ImmutableArray`1 providers, SignatureHelpTriggerInfo triggerInfo)
at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.InvokeSignatureHelpCommandArgs>.ExecuteCommand(InvokeSignatureHelpCommandArgs args, Action nextHandler, CommandExecutionContext context)
at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler, CommandExecutionContext context)
at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.InvokeSignatureHelpCommandArgs>.ExecuteCommand(InvokeSignatureHelpCommandArgs args, Action nextHandler, CommandExecutionContext context)
at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)
```

**Comment by jinujoseph** [comment]
cc @tmat
