### ISSUE TITLE
CodeLens is crashing ServiceHub due to missing Microsoft.VisualStudio.ExtensionManager.Implementation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31324]
**Version Used**: 
Version 16.0.0 Preview 2.0 [28321.115.d16.0stg]

11/23/2018 16:23:09 : Error : System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.CodeLens.Service.MefHostCompositionService' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ExtensionManager.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.CodeLens.Service.MefHostCompositionService.VsixDiscoveryHelper.EnumerateCodeLensExtensionVsixLocations()
   at Microsoft.VisualStudio.CodeLens.Service.MefHostCompositionService..ctor(Boolean composeImmediately)
   at Microsoft.VisualStudio.CodeLens.Service.MefHostCompositionService..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.CodeLens.Service.CodeLensServiceHubService..ctor(Stream stream, IServiceProvider serviceProvider)

**Comment by jinujoseph** [comment]
moved to platform [team](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752442)
