### ISSUE TITLE
IOperation Test Hook Tests Broken

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#31450]
A number of tests are currently broken with the IOperation test hook, mostly due to range and indexers (fyi @agocke). The ones that aren't due to that are mostly nullable reference type tests:
```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer
Operation [2] in [B2] uses capture [0] from another region. Should the regions be merged?\r\nExpected: True\r\nActual:   False
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__assertCaptureReferences|10(PooledHashSet`1 state, IOperation operation, BasicBlock block, Int32 operationIndex, PooledHashSet`1 longLivedIds, PooledHashSet`1 referencedIds) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 792
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__verifyCaptures|0() in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 396
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(StringBuilder stringBuilder, Compilation compilation, ControlFlowGraph graph, ControlFlowRegion enclosing, String idSuffix, Int32 indent) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 346
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(Compilation compilation, ControlFlowGraph graph) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 83
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.<ValidateIOperations>g__checkControlFlowGraph|13_1(IOperation root, <>c__DisplayClass13_0& ) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 345
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.ValidateIOperations(Func`1 createCompilation) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 320
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilationCore(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable, Nullable`1 experimentalFeature) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 884
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 851
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, TargetFramework targetFramework, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 842
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer() in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\NullableReferenceTypesTests.cs:line 41162
Traits:
Compiler	NullableReferenceTypes
0.0390464s ✘  Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer_Properties
Operation [2] in [B2] uses capture [0] from another region. Should the regions be merged?\r\nExpected: True\r\nActual:   False
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__assertCaptureReferences|10(PooledHashSet`1 state, IOperation operation, BasicBlock block, Int32 operationIndex, PooledHashSet`1 longLivedIds, PooledHashSet`1 referencedIds) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 792
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__verifyCaptures|0() in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 396
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(StringBuilder stringBuilder, Compilation compilation, ControlFlowGraph graph, ControlFlowRegion enclosing, String idSuffix, Int32 indent) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 346
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(Compilation compilation, ControlFlowGraph graph) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 83
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.<ValidateIOperations>g__checkControlFlowGraph|13_1(IOperation root, <>c__DisplayClass13_0& ) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 345
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.ValidateIOperations(Func`1 createCompilation) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 320
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilationCore(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable, Nullable`1 experimentalFeature) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 884
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 851
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, TargetFramework targetFramework, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 842
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer_Properties() in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\NullableReferenceTypesTests.cs:line 41256
Traits:
Compiler	NullableReferenceTypes
0.1654632s ✘  Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer_Struct
Operation [2] in [B2] uses capture [0] from another region. Should the regions be merged?\r\nExpected: True\r\nActual:   False
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__assertCaptureReferences|10(PooledHashSet`1 state, IOperation operation, BasicBlock block, Int32 operationIndex, PooledHashSet`1 longLivedIds, PooledHashSet`1 referencedIds) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 792
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.<>c__DisplayClass3_0.<GetFlowGraph>g__verifyCaptures|0() in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 396
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(StringBuilder stringBuilder, Compilation compilation, ControlFlowGraph graph, ControlFlowRegion enclosing, String idSuffix, Int32 indent) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 346
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetFlowGraph(Compilation compilation, ControlFlowGraph graph) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\ControlFlowGraphVerifier.cs:line 83
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.<ValidateIOperations>g__checkControlFlowGraph|13_1(IOperation root, <>c__DisplayClass13_0& ) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 345
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.ValidateIOperations(Func`1 createCompilation) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 320
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilationCore(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable, Nullable`1 experimentalFeature) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 884
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 851
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, TargetFramework targetFramework, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 842
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.Members_ObjectInitializer_Struct() in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\NullableReferenceTypesTests.cs:line 41209
Traits:
Compiler	NullableReferenceTypes
0.0221635s ✘  Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.New_01
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.MergeSubRegionAndFree(RegionBuilder subRegion, ArrayBuilder`1 blocks, PooledDictionary`2 regionMap) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 587
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.PopStackFrame(EvalStackFrame frame, Boolean mergeNestedRegions) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1659
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.PopStackFrame[T](EvalStackFrame frame, T value) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1687
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation, Nullable`1 argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 6579
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 6569
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitSimpleAssignment(ISimpleAssignmentOperation operation, Nullable`1 captureIdForResult) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1953
   at Microsoft.CodeAnalysis.Operations.BaseSimpleAssignmentOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationNodes.cs:line 683
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationVisitor.cs:line 610
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation, Nullable`1 argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 6579
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 6569
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitExpressionStatement(IExpressionStatementOperation operation, Nullable`1 captureIdForResult) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 3146
   at Microsoft.CodeAnalysis.Operations.BaseExpressionStatementOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationNodes.cs:line 2311
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationVisitor.cs:line 610
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1191
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatements(ImmutableArray`1 statements) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1360
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitBlock(IBlockOperation operation, Nullable`1 captureIdForResult) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1321
   at Microsoft.CodeAnalysis.Operations.BaseBlockOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationNodes.cs:line 1298
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationVisitor.cs:line 610
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1191
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodies(IBlockOperation blockBody, IBlockOperation expressionBody) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1420
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodyBaseOperation(IMethodBodyBaseOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1413
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodyOperation(IMethodBodyOperation operation, Nullable`1 captureIdForResult) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1406
   at Microsoft.CodeAnalysis.Operations.BaseMethodBodyOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationNodes.cs:line 8620
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\OperationVisitor.cs:line 610
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 1191
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Create(IOperation body, ControlFlowGraph parent, ControlFlowRegion enclosing, CaptureIdDispenser captureIdDispenser, Context& context) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Core\Portable\Operations\ControlFlowGraphBuilder.cs:line 109
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.<ValidateIOperations>g__checkControlFlowGraph|13_1(IOperation root, <>c__DisplayClass13_0& ) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 345
   at Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.ValidateIOperations(Func`1 createCompilation) in C:\Users\frsilb\Documents\git\roslyn\src\Test\Utilities\Portable\Compilation\CompilationExtensions.cs:line 320
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilationCore(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable, Nullable`1 experimentalFeature) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 884
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 851
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, TargetFramework targetFramework, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 842
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.New_01() in C:\Users\frsilb\Documents\git\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\NullableReferenceTypesTests.cs:line 22308
```

**Comment by 333fred** [comment]
The index and range tests appear to just be that support has not been implemented in the control flow graph code yet, and therefore any test code that involves them fails.
