### ISSUE TITLE
Exception encountered in AbstractAddImportFeatureService while working

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#31568]
I don't have a repro, but the stack trace is below from the crash

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.AwaitExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.GetExpressionOfAwaitExpression(SyntaxNode node)
   at Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetAwaitInfo(SemanticModel semanticModel,ISyntaxFactsService syntaxFactsService,SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.SymbolReferenceFinder.GetReferencesForGetAwaiterAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.SymbolReferenceFinder.DoAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsInAllSymbolsInStartingProjectAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesInCurrentProcessAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesForDiagnosticsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ryzngard** [comment]
I haven't hit this in a long time, closing as no repro.
