### ISSUE TITLE
ArgumentOutOfRangeException in Snippet.ExpansionFilter.OnCaretChange

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#31689]
**Version Used**: 16.0.0 Preview 1

**Steps to Reproduce**:

I am not entirely sure what the repro is, I was typing a constructor...
```C#
public ConfidenceEnvelope(double confidence, IEnumerable<Trialre|
```
I probably expected 'TrialResult' to be commited by `>` or Ctrl+Space.

**Actual Behavior**:
ActivityLog:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at Microsoft.VisualStudio.Editor.Implementation.Snippet.ExpansionFilter.OnCaretChange()
at Microsoft.VisualStudio.Editor.Implementation.Snippet.VsExpansionShim.OnCaretChange()
at Microsoft.VisualStudio.Editor.Implementation.TextDocData.OnCaretChange()
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Caret_PositionChanged(Object sender, CaretPositionChangedEventArgs e)
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by jinujoseph** [comment]
routed to [editor](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/959700)
