### ISSUE TITLE
`InvalidCastException` when calling `VisualBasicSyntaxGenerator.GetAttributes()` with a VB constructor

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#31720]
As title says. Discovered in an integration test run.

**Comment by CyrusNajmabadi** [comment]
@333fred Any callstack for this?

**Comment by 333fred** [comment]
```
Event Time (UTC): 12/12/2018 6:27:24 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.ConstructorBlockSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax'.
   at Microsoft.CodeAnalysis.VisualBasic.CodeGeneration.VisualBasicSyntaxGenerator.GetAttributeLists(SyntaxNode node)
   at Microsoft.CodeAnalysis.VisualBasic.CodeGeneration.VisualBasicSyntaxGenerator.GetAttributes(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.VisualBasic.Editor.Wrapping.SeparatedSyntaxList.VisualBasicParameterWrapper.PositionIsApplicable(SyntaxNode root, Int32 position, SyntaxNode declaration, ParameterListSyntax listSyntax)
   at Microsoft.CodeAnalysis.Editor.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.<TryCreateComputerAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Wrapping.AbstractWrappingCodeRefactoringProvider.<ComputeRefactoringsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionManager+ExtensionManager.HandleException(System.Object, System.Exception)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<GetRefactoringFromProviderAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<GetRefactoringFromProviderAsync>d__8, Microsoft.CodeAnalysis.Features, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetRefactoringFromProviderAsync>d__8 ByRef)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider, Microsoft.CodeAnalysis.Extensions.IExtensionManager, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<HasRefactoringsAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<HasRefactoringsAsync>d__6, Microsoft.CodeAnalysis.Features, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<HasRefactoringsAsync>d__6 ByRef)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.HasRefactoringsAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource+<TryGetRefactoringSuggestedActionCategoryAsync>d__41.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource+<TryGetRefactoringSuggestedActionCategoryAsync>d__41, Microsoft.CodeAnalysis.EditorFeatures.Wpf, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<TryGetRefactoringSuggestedActionCategoryAsync>d__41 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.TryGetRefactoringSuggestedActionCategoryAsync(Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider, Microsoft.CodeAnalysis.Document, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource+<>c__DisplayClass48_2.<GetSuggestedActionCategoriesAsync>b__1()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Yup.  Def a bug in the generator.  Easy to see that here:

![image](https://user-images.githubusercontent.com/4564579/49898690-8a6a0000-fe0e-11e8-976a-1577b3e3c902.png)

:)

**Comment by CyrusNajmabadi** [comment]
Amazing it's never been hit until now.

**Comment by sharwell** [comment]
> Amazing it's never been hit until now.

I'm guessing it's been hit many times, but people didn't look at the test results. 😄
