### ISSUE TITLE
CSharpAddImportCodeFixProvider crashed when you have two variables with same name

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#31788]
``` C#
        [Fact]
        public async Task QueryDebugTargetsAsync_ConsoleAppLaunchWithNoDebuggerIntegratedConsole_DoesNotWrapInCmd()
        {
            var debugger = IVsDebugger10Factory.ImplementIsIntegratedConsoleEnabled(enabled: true);
            var properties = new Dictionary<string, string>() {
                {"TargetPath", @"C:\ConsoleApp.exe"},
                {"TargetFrameworkIdentifier", @".NETFramework" }
                };

            var debugger = GetDebugTargetsProvider("exe", properties, debugger);

            var activeProfile = new LaunchProfile() { Name = "Name", CommandName = "Project" };

            var result = await debugger.QueryDebugTargetsAsync(DebugLaunchOptions.NoDebug, activeProfile);

            Assert.Single(result);
            Assert.Contains("cmd.exe", result[0].Executable);
        }
```

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.AwaitExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.GetExpressionOfAwaitExpression(SyntaxNode node)
   at Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetAwaitInfo(SemanticModel semanticModel,ISyntaxFactsService syntaxFactsService,SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.SymbolReferenceFinder.GetReferencesForGetAwaiterAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.SymbolReferenceFinder.DoAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsInAllSymbolsInStartingProjectAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.FindResultsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesInCurrentProcessAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesForDiagnosticsAsync[TSimpleNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jinujoseph** [comment]
reported at [DC ](https://developercommunity.visualstudio.com/content/problem/411373/csharpaddimportcodefixprovider-encountered-an-erro-7.html)

**Comment by JoeRobich** [comment]
This was fixed recently in https://github.com/dotnet/roslyn/pull/31693 and will be in preview 2.
