### ISSUE TITLE
PreviewChangesTests.TestLinkedFileChangesMergedAndDeduplicated failed

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#31810]
[Build Logs](https://dnceng.visualstudio.com/public/_build/results?buildId=58877&view=logs) Attempt 1

Test Log:
```
System.AggregateException : One or more errors occurred.\r\n---- System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Preview.PreviewEngine..ctor(IThreadingContext threadingContext, String title, String helpString, String description, String topLevelItemName, Glyph topLevelGlyph, Solution newSolution, Solution oldSolution, IComponentModel componentModel, IVsImageService2 imageService, Boolean showCheckBoxes) in /_/src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs:line 67
   at Microsoft.VisualStudio.LanguageServices.Implementation.Preview.PreviewEngine..ctor(IThreadingContext threadingContext, String title, String helpString, String description, String topLevelItemName, Glyph topLevelGlyph, Solution newSolution, Solution oldSolution, IComponentModel componentModel, Boolean showCheckBoxes) in /_/src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs:line 44
   at Microsoft.VisualStudio.LanguageServices.UnitTests.Preview.PreviewChangesTests.TestLinkedFileChangesMergedAndDeduplicated() in /_/src/VisualStudio/Core/Test/Preview/PreviewChangesTests.vb:line 292
----- Inner Stack Trace -----
   at Microsoft.CodeAnalysis.LinkedFileDiffMergingSession.<MergeLinkedDocumentGroupAsync>d__6.MoveNext() in /_/src/Workspaces/Core/Portable/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.LinkedFileDiffMergingSession.<MergeDiffsAsync>d__5.MoveNext() in /_/src/Workspaces/Core/Portable/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Solution.<WithMergedLinkedFileChangesAsync>d__91.MoveNext() in /_/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs:line 1002
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't hit this in years and we have a dedicated system for tracking flakey tests now.
