### ISSUE TITLE
AsyncCompletion: Roslyn incorrectly acts multiple times and throws

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#31892]
**Version Used**: 28417.110.d16.0stg 

**Steps to Reproduce**:

1. In AspNet**Core** project, in .cshtml file, type `@inject datet`
2. Press Ctrl+J
3. Press space or another commit character

**Expected Behavior**:
Completion to `@inject DateTime`

**Actual Behavior**:
Roslyn throws when attempting to add a property to the text view's property bag

```
System.ArgumentException: An entry with the same key already exists.
   at System.Collections.Specialized.ListDictionary.Add(Object key, Object value)
   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.<GetCompletionContextAsync>d__16.MoveNext()
```

Note that completion probes Roslyn multiple times on various buffers.
Roslyn should act only in one case, but signed up to participate in completion in two locations
![image](https://user-images.githubusercontent.com/1673956/50124891-6138dd80-021b-11e9-8181-c6a6318cfcd6.png)
This is actually the same buffer, but the caret location was projected to two locations (706 and 830) in the following snapshot, which maps to gibberish.

I think that there are two issues at hand:
1) Roslyn should not double-add a property
2) Editor to investigate weird mapping

```
// <auto-generated/>\r\n#pragma warning disable 1591\r\nnamespace AspNetCore\r\n{\r\n    #line hidden\r\n    using TModel = global::System.Object;\r\n    using System;\r\n    using System.Collections.Generic;\r\n    using System.Linq;\r\n    using System.Threading.Tasks;\r\n    using Microsoft.AspNetCore.Mvc;\r\n    using Microsoft.AspNetCore.Mvc.Rendering;\r\n    using Microsoft.AspNetCore.Mvc.ViewFeatures;\r\n    public class _Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IndexModel>\r\n    {\r\n        #pragma warning disable 219\r\n        private void __RazorDirectiveTokenHelpers__() {\r\n        ((System.Action)(() => {\r\n#line 1 \"C:\\Users\\amwieczo\\source\\repos\\AspNetCoreWebApp\\AspNetCoreWebApp\\Index.cshtml\"\r\ndatet __typeHelper = default(datet);\r\n\r\n#line default\r\n#line hidden\r\n        }\r\n        ))();\r\n        ((System.Action)(() => {\r\n }\r\n        ))();\r\n        ((System.Action)(() => {\r\n#line 2 \"C:\\Users\\amwieczo\\source\\repos\\AspNetCoreWebApp\\AspNetCoreWebApp\\Index.cshtml\"\r\nIndexModel __typeHelper = default(IndexModel);\r\n\r\n#line default\r\n#line hidden\r\n        }\r\n        ))();\r\n        }\r\n        #pragma warning restore 219\r\n        #pragma warning disable 0414\r\n        private static System.Object __o = null;\r\n        #pragma warning restore 0414\r\n        #pragma warning disable 1998\r\n        public async override global::System.Threading.Tasks.Task ExecuteAsync()\r\n        {\r\n#line 3 \"C:\\Users\\amwieczo\\source\\repos\\AspNetCoreWebApp\\AspNetCoreWebApp\\Index.cshtml\"\r\n  \r\n\r\n#line default\r\n#line hidden\r\n        }\r\n        #pragma warning restore 1998\r\n        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]\r\n        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }\r\n        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]\r\n        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }\r\n        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]\r\n        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }\r\n        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]\r\n        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }\r\n        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]\r\n        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IndexModel> Html { get; private set; }\r\n    }\r\n}\r\n#pragma warning restore 1591\r\n
```

**Comment by ivanbasov** [comment]
It seems that the current contract means that `GetCompletionContextAsync `should not be called twice for the same session. If the contract changes, we should revise not just the current issue but other potential ones as well. Therefore, we should keep using `AddProperty` to be sure that the contract is still valid.
