### ISSUE TITLE
Exception every time I open Visual Studio 2017

### ISSUE THREAD

**Issue by KnutHaraldR** [dotnet/roslyn#32016]
Getting this in my log:

```
System.AggregateException: One or more errors occurred.
 ---&gt; System.IO.FileNotFoundException: Could not load
 file or assembly &apos;Microsoft.VisualStudio.Data, 
 Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; 
 or one of its dependencies. Systemet finner ikke angitt fil.&#x000D;&#x000A; 
 at MySql.Data.VisualStudio.DocumentNode.GetCurrentConnection()&#x000D;&#x000A; 
 at MySql.Data.VisualStudio.LanguageServiceUtil.GetConnection()&#x000D;&#x000A;  
 at MySql.Data.VisualStudio.LanguageService.MySqlQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession
 session, IList`1 qiContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession
 (IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;
 TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()
---
 End of stack trace from previous location where exception was thrown ---
  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;
 ComputeSourceContentAsync&gt;d__44.MoveNext()
--- End of stack trace from previous 
 location where exception was thrown ---
   
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) 
 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Data,
 Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
 Systemet finner ikke angitt fil.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Data,
 Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;  
 at MySql.Data.VisualStudio.DocumentNode.GetCurrentConnection()&#x000D;&#x000A; 
 at MySql.Data.VisualStudio.LanguageServiceUtil.GetConnection()&#x000D;&#x000A;  
 at MySql.Data.VisualStudio.LanguageService.MySqlQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, 
 IList`1 qiContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A; 
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session,
 IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;
 TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A; 
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;  
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;---
 End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;&#x000D;&#x000A;
 WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)
 to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry 
 value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;&lt;---&#x000D;&#x000A;
```

**Comment by sharwell** [comment]
@KnutHaraldR This appears to be an issue with the following third-party extension:
https://github.com/mysql/mysql-for-vs

I recommend filing this issue on their issue tracker. 😄
