### ISSUE TITLE
If I remove the space from { 0}, to {0}, it works perfectly. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32089]
With this statement: Console.WriteLine(&quot;char.IsWhiteSpace('Hello There',5): { 0}&quot;,char.IsWhiteSpace(&quot;Hello There&quot;, 5));

I get:
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.IO.TextWriter.WriteLine(String format, Object arg0)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object arg0)
   at System.Console.WriteLine(String format, Object arg0)
   at WriteTextFile.WriteTextFile.CharFunctionality() in C:\Users\qetuo\Documents\Visual Studio 2018\WriteTextFile\WriteTextFile\Program.cs:line 182

If I remove the space from { 0}, to {0}, it works perfectly. 

Having the space should not be a problem.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/398878/if-i-remove-the-space-from-0-to-0-it-works-perfect.html
VSTS ticketId: 739988_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
@jaredpar can you move this to dotnet/corefx?

**Comment by gafter** [comment]
Issue moved to [dotnet/corefx #34320](https://github.com/dotnet/corefx/issues/34320) via [**ZenHub**](https://www.zenhub.com/)
