### ISSUE TITLE
VisualBasicUseConditionalExpressionForAssignmentCodeRefactoringProvider STILL on Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32087]
You closed my last Error message as Duplicate but there is still the same error sice many releases.

try the following refactoring:

    Public Function ColName(aExtendedName As Boolean) As String
        If aExtendedName Then
            ColName = Current.SchemaName & "." & ColName()
        Else
            ColName = Name
        End If
    End Function

Result:
IDE0045 goes to Error

```
Here the Stack Trace:
System.InvalidCastException : Das Objekt des Typs &quot;Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax&quot; kann nicht in Typ &quot;Microsoft.CodeAnalysis.VisualBasic.Syntax.VariableDeclaratorSyntax&quot; umgewandelt werden.
   at Microsoft.CodeAnalysis.VisualBasic.UseConditionalExpression.VisualBasicUseConditionalExpressionForAssignmentCodeRefactoringProvider.GetDeclaratorSyntax(IVariableDeclaratorOperation declarator)
   at Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionForAssignmentCodeFixProvider`6.TryConvertWhenAssignmentToLocalDeclaredImmediateAbove(ISyntaxFactsService syntaxFacts,SyntaxEditor editor,IConditionalOperation ifOperation,ISimpleAssignmentOperation trueAssignment,ISimpleAssignmentOperation falseAssignment,TExpressionSyntax conditionalExpression)
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionForAssignmentCodeFixProvider`6.FixOneAsync[TStatementSyntax,TIfStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TExpressionSyntax,TConditionalExpressionSyntax](&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionCodeFixProvider`4.FixAllAsync[TStatementSyntax,TIfStatementSyntax,TExpressionSyntax,TConditionalExpressionSyntax](&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unbekannte Parameter&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unbekannte Parameter&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/403049/visualbasicuseconditionalexpressionforassignmentco.html
VSTS ticketId: 744255_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by redpit** [comment]
There is still the same Bug in version19.5.4
Why is this issue again declared "Duplicate and added a solution"?

**Comment by sharwell** [comment]
This is related to #29376, but the code sample is slightly different and the exception message suggests it could be a different bug in the same provider.

@redpit This issue is open and not marked as a duplicate. There are currently six total copies of the two bugs you filed. Four of them (including two that are not publicly visible) are marked as duplicates, leaving two of them open for fixing. 😄

**Comment by CyrusNajmabadi** [comment]
Does not repro for me.  Generates:

![image](https://user-images.githubusercontent.com/4564579/152617012-cd55d18e-13de-49bf-847d-6ef7c03c1c0b.png)
