### ISSUE TITLE
MoveTypeCodeRefactoringProvider encounted an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32080]
when I ctrl-dot on a class or interface that is in the file of a different piece of code, and then press down to select &quot;move to ...&quot; I get an error that tells me &quot;MoveTypeCodeRefactoringProvider encounted an error and has been disabled&quot;.

The stacktrace is:
```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Analyze(SyntaxTriviaList list,AnalysisResult&amp; result)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Leading(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.CreateLeadingTrivia(SyntaxToken token)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetOriginalTriviaData(TokenData token1,TokenData token2)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetColumn(TokenData tokenData,Func`3 triviaDataGetter)
   at Microsoft.CodeAnalysis.Formatting.FormattingContext.AddAnchorIndentationOperation(AnchorIndentationOperation operation)
   at Roslyn.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source,Action`1 action)
   at Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.&lt;&gt;c__DisplayClass14_0.&lt;FormatAsync&gt;b__0(Task`1 task)
   at Microsoft.CodeAnalysis.Formatting.TaskExecutor.SynchronousExecutor.ContinueWith[T1,T2](Task`1 previousTask,Func`2 nextAction,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.FormatAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.FormatIndividuallyAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Formatting.Formatter.FormatAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryImports.AbstractCSharpRemoveUnnecessaryImportsService.FormatResultAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryImports.AbstractCSharpRemoveUnnecessaryImportsService.RemoveUnnecessaryImportsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.AddNewDocumentWithSingleTypeDeclarationAndImportsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeEditor.GetOperationsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.MoveType.AbstractMoveTypeService`5.MoveTypeCodeAction.ComputeOperationsAsync[TService,TTypeDeclarationSyntax,TNamespaceDeclarationSyntax,TMemberDeclarationSyntax,TCompilationUnitSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unknown Parameters&gt;)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/416137/movetypecoderefactoringprovider-encounted-an-error.html
VSTS ticketId: 757134_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by jinujoseph** [comment]
also reported [here ](https://developercommunity.visualstudio.com/content/problem/417136/generateconstructorfrommemberscoderefactoringprovi.html)

**Comment by ryzngard** [comment]
Unable to repro in Dev 16 Preview 1.1. Tried with the below code, where `ctrl+dot` -> `move to …` is selected on Address. 

```C#
internal class Person
    {
        public string FirstName { get; }
        public string MiddleName { get; }
        public string LastName { get; }

        public class Address
        {
            public int Zip { get; }
        }
    }
```

**Comment by ryzngard** [comment]
Same for `Generate constructor` on the `Person` class.
