### ISSUE TITLE
Integration test failure in CSharpNavigationBar.VerifyNavBar

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#32437]
See https://dev.azure.com/dnceng/public/_build/results?buildId=72058&view=ms.vss-test-web.test-result-details

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.EqualException: Assert.Equal() Failure
          ↓ (pos 0)
Expected: public static bool operator 
Actual:   !=(C c1, C c2) { return fals
          ↑ (pos 0)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\projects\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
   at Xunit.Assert.Equal(String expected, String actual) in C:\projects\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 174
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.Verifier.CurrentLineTextAndAssertCaretPosition(String expectedText, Boolean trimWhitespace) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.Verifier.cs:line 87
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Editor_OutOfProc.Verifier.CurrentLineText(String expectedText, Boolean assertCaretPosition, Boolean trimWhitespace) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Editor_OutOfProc.Verifier.cs:line 29
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigationBar.VerifyNavBar() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpNavigationBar.cs:line 53
```
![csharpnavigationbar verifynavbar-equalexception-16 57 19](https://user-images.githubusercontent.com/10605811/51133407-c287a880-17e9-11e9-8ba3-aeb4aece453d.png)

**Comment by mavasani** [comment]
Tagging @sharwell in case he has seen this failure before.

**Comment by sharwell** [comment]
@mavasani This class of bug is the primary outstanding issue with integration tests. For some reason, some of the time when <kbd>Enter</kbd> is sent to the nav bar, it shows up in the editor instead. I have not been able to reproduce this locally to figure out which of the following is occurring:

1. The command goes through the nav bar but does not stop there
2. Something is dismissing the nav bar prior to sending the enter command
3. The nav bar is visible, but command focus is instead set to the editor

**Comment by CyrusNajmabadi** [comment]
Closing out.  These tests have been stable.
