### ISSUE TITLE
GenerateMethodUsingTypeConstraint_2BaseTypeConstraints_Interfaces Test Failure

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#32533]
Saw this in #32525 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=74067&view=ms.vss-test-web.test-result-details) Windows Desktop Debug Test64 Attempt 1

```
Error message
System.AggregateException : One or more errors occurred.\r\n---- System.InvalidOperationException : WaitAndGetResult cannot be called from a thread pool thread.
Stack trace
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_10_GetDiagnosticAndFixesAsync.MoveNext() in /_/src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_8_GetDiagnosticAndFixAsync.MoveNext() in /_/src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AbstractCrossLanguageUserDiagnosticTest.VB$StateMachine_6_TestAsync.MoveNext() in /_/src/EditorFeatures/Test2/Diagnostics/AbstractCrossLanguageUserDiagnosticTest.vb:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.VB$StateMachine_16_GenerateMethodUsingTypeConstraint_2BaseTypeConstraints_Interfaces.MoveNext() in /_/src/EditorFeatures/Test2/Diagnostics/GenerateFromUsage/GenerateMethodCrossLanguageTests.vb:line 659
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Utilities/TaskExtensions.cs:line 74
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeSymbolExtensions.ReplaceTypeParameterBasedOnTypeConstraintVisitor.<>c__DisplayClass10_0.<VisitTypeParameter>b__1(ITypeSymbol ct) in /_/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.ReplaceTypeParameterBasedOnTypeConstraintVisitor.cs:line 102
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeSymbolExtensions.ReplaceTypeParameterBasedOnTypeConstraintVisitor.VisitTypeParameter(ITypeParameterSymbol symbol) in /_/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.ReplaceTypeParameterBasedOnTypeConstraintVisitor.cs:line 99
```

**Comment by JoeRobich** [comment]
Saw this again in #32761 - [Build Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=79976&view=logs) Spanish_Unit_Tests Attempt 1

**Comment by JoeRobich** [comment]
Saw this again: [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125082&view=ms.vss-test-web.build-test-results-tab)

**Comment by dpoeschl** [comment]
Same thing again but a different individual test, `GenerateMethodUsingTypeConstraint_3BaseTypeConstraints_CommonDerivedNestedType`, in https://dev.azure.com/dnceng/public/_build/results?buildId=175043

**Comment by 333fred** [comment]
Hit again https://github.com/dotnet/roslyn/pull/38056.

**Comment by JoeRobich** [comment]
Closing as test is passing
