### ISSUE TITLE
Extract Method C7 crash was not fixed successfully?

### ISSUE THREAD

**Issue by verelpode** [dotnet/roslyn#32650]
This ExtractMethodCodeRefactoringProvider C7 crash was supposed to be fixed, but surprisingly it happened to me again today with VS 15.9.3.  Following is the code that caused it (with some names changed).

```
		private MyEnum1 _GetValueValidity(StringSegment inValueStr, out StringSegment outCorrectedString, bool inAllowTrim)
		{
			outCorrectedString = inValueStr;
			if (!fIsSurroundingWhiteSpaceAllowed)
			{
				StringSegment trimmedStrSeg = inValueStr.Trim();
				if (trimmedStrSeg.Length < inValueStr.Length)   // xxxxx
				{
					if (!inAllowTrim) return MyEnum1.XXX1;
					inValueStr = trimmedStrSeg;
					outCorrectedString = trimmedStrSeg;
				}
			}

			if (!fAreLineBreakCharsAllowed && MyHelper1.FindVertWhiteSpace(inValueStr) >= 0)
				return MyEnum1.XXX2;
			
			if (fAllowedCharMatcher != null && fAllowedCharMatcher.FindNonChar(inValueStr) >= 0)
				return MyEnum1.XXX1;

			int valueStrLength = inValueStr.Length;
			if (valueStrLength < fMinCharCount)
				return (valueStrLength == 0) ? MyEnum1.XXX3 : MyEnum1.XXX4;
			int mxcc = fMaxCharCount;
			if (mxcc >= 0 && valueStrLength > mxcc)
				return MyEnum1.XXX5;

			return MyEnum1.XXX6;
		}

		public override MyEnum1 GetValueValidity()
		{
			return this._GetValueValidity(fEditTextBox.Text, inAllowTrim: true);
		}
```

```
ExtractMethodCodeRefactoringProvider encountered an error and has been disabled.
System.InvalidOperationException : Matrix does not contain Key 'C7'.
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_Originally posted by @verelpode in https://github.com/dotnet/roslyn/issue_comments#issuecomment-455733140_

and   https://github.com/dotnet/roslyn/issues/29658

**Comment by verelpode** [comment]
oops, the fixes went into a later version number than I thought, according to @CyrusNajmabadi, so I'm going to close this issue.
