### ISSUE TITLE
'VisualBasicConvertForToForEachCodeRefactoringProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#32822]
VSF_TYPE_MARKDOWNStacktrace

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.ConvertForToForEach.VisualBasicConvertForToForEachCodeRefactoringProvider.TryGetForStatementComponents(ForBlockSyntax forBlock,SyntaxToken&amp; iterationVariable,ExpressionSyntax&amp; initializer,MemberAccessExpressionSyntax&amp; memberAccess,ExpressionSyntax&amp; stepValueExpressionOpt,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ConvertForToForEach.AbstractConvertForToForEachCodeRefactoringProvider`6.ComputeRefactoringsAsync[TStatementSyntax,TForStatementSyntax,TExpressionSyntax,TMemberAccessExpressionSyntax,TTypeNode,TVariableDeclaratorSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/435505/visualbasicconvertfortoforeachcoderefactoringprovi.html
VSTS ticketId: 777066_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by heejaechang** [comment]
NFW dump - https://watson/Failure?FailureSearchText=eec5079e-36cc-22fd-2ba0-ded67ab698ef#

heap dump requested

**Comment by heejaechang** [comment]
had over 1500+ hit last 90 days according to NFW so, we should get dump soon.

**Comment by heejaechang** [comment]
still no dump with heap yet.

**Comment by allisonchou** [comment]
Repro for issue in latest release:
``` VB
    Sub Test()
        Dim list = New List(Of Integer)
        For newIndex = 0 To list.Count - 1 ' type the character '\' at the end of the line to invoke exception
        Next
    End Sub
```
