### ISSUE TITLE
EE: Assertion failed in Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.GetDisplayClassVariables

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#3299]
1) Run to breakpoint as indicated.
2) Change the first yield statement from ```yield return d;``` to ```yield return d.ToString();```
3) F10 and evaluate d

```C#
using System.Collections.Generic;
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        args = Iterator2().ToArray();
    }

    private static IEnumerable<string> Iterator2()
    {
        dynamic d = "x";  // breakpoint

        yield return d;
        yield return d;
    }
}
```

```
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.GetDisplayClassVariables(ArrayBuilder`1 displayClassVariableNamesInOrderBuilder, Dictionary`2 displayClassVariablesBuilder, HashSet`1 parameterNames, InScopeHoistedLocals inScopeHoistedLocals, DisplayClassInstanceAndFields instance, HashSet`1 hoistedParameterNames) in C:\R4\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\CompilationContext.cs:line 1391

   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.GetDisplayClassVariables(MethodSymbol method, ImmutableArray`1 locals, InScopeHoistedLocals inScopeHoistedLocals, ImmutableArray`1& displayClassVariableNamesInOrder, ImmutableDictionary`2& displayClassVariables, ImmutableHashSet`1& hoistedParameterNames) in C:\R4\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\CompilationContext.cs:line 1196

   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext..ctor(CSharpCompilation compilation, MetadataDecoder metadataDecoder, MethodSymbol currentFrame, ImmutableArray`1 locals, InScopeHoistedLocals inScopeHoistedLocals, MethodDebugInfo methodDebugInfo, CSharpSyntaxNode syntax) in C:\R4\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\CompilationContext.cs:line 89

   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateCompilationContext(CSharpSyntaxNode syntax) in C:\R4\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\EvaluationContext.cs:line 218

   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CompileGetLocals(ArrayBuilder`1 locals, Boolean argumentsOnly, ImmutableArray`1 aliases, DiagnosticBag diagnostics, String& typeName, CompilationTestData testData) in C:\R4\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\EvaluationContext.cs:line 381

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.<>c__DisplayClass1_1.<Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrExpressionCompiler.GetClrLocalVariableQuery>b__1(EvaluationContextBase context, DiagnosticBag diagnostics) in C:\R4\src\ExpressionEvaluator\Core\Source\ExpressionCompiler\ExpressionCompiler.cs:line 51

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileWithRetry[TResult](ImmutableArray`1 metadataBlocks, DiagnosticFormatter formatter, CreateContextDelegate createContext, CompileDelegate`1 compile, GetMetadataBytesPtrFunction getMetaDataBytesPtr, String& errorMessage) in C:\R4\src\ExpressionEvaluator\Core\Source\ExpressionCompiler\ExpressionCompiler.cs:line 331

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileWithRetry[TResult](DkmClrModuleInstance moduleInstance, ImmutableArray`1 metadataBlocks, CreateContextDelegate createContext, CompileDelegate`1 compile, String& errorMessage) in C:\R4\src\ExpressionEvaluator\Core\Source\ExpressionCompiler\ExpressionCompiler.cs:line 304

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrExpressionCompiler.GetClrLocalVariableQuery(DkmInspectionContext inspectionContext, DkmClrInstructionAddress instructionAddress, Boolean argumentsOnly) in C:\R4\src\ExpressionEvaluator\Core\Source\ExpressionCompiler\ExpressionCompiler.cs:line 43

   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrExpressionCompiler_GetClrLocalVariableQuery(IntPtr pvClassInfo, IntPtr InspectionContext, IntPtr InstructionAddress, Byte ArgumentsOnly, IntPtr& Result)

   at Microsoft.VisualStudio.Debugger.Evaluation.NativeDkmInspectionContext.Proc92260B87C04ECE6862D88F7A45EECD13(IntPtr pThis, IntPtr InstructionAddress, Byte ArgumentsOnly, IntPtr& Result)

   at Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext.GetClrLocalVariableQuery(DkmClrInstructionAddress InstructionAddress, Boolean ArgumentsOnly)

   at VSDebugEngine.ManagedEE.LocalsProvider.Create(DkmInspectionContext inspectionContext, DkmStackWalkFrame frame, Boolean argumentsOnly)

   at VSDebugEngine.ManagedEE.EntryPoint.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmLanguageExpressionEvaluator.GetFrameLocals(DkmInspectionContext inspectionContext, DkmWorkList workList, DkmStackWalkFrame stackFrame, DkmCompletionRoutine`1 completionRoutine)

   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmLanguageExpressionEvaluator_GetFrameLocals(IntPtr pvClassInfo, IntPtr InspectionContext, IntPtr WorkList, IntPtr StackFrame, IntPtr CompletionRoutine)
```

**Comment by cston** [comment]
@tmat Are you still able to repro this?

**Comment by tmat** [comment]
@cston Not the assert, but I see:
		d	The debugger is unable to evaluate this expression	object

**Comment by cston** [comment]
Thanks @tmat. Those other two issues are tracked by separate bugs.
