### ISSUE TITLE
Intellisense Crash on Preview 4

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#33280]
**Version Used**: VisualStudio.16.int.d16.0stg/16.0.0-pre.4.0+28608.196.d16.0stg

**Steps to Reproduce**:

1. Create a new class file
2. begin to type an interface name without a `:`

```C#
public class Class1 [|InterfaceName|]
{
}
```

**Expected Behavior**:

No Crash

**Actual Behavior**:

VS Crash

```ini
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSetPresenter.AnnounceUIACompletionPresense()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSetPresenter+<>c__DisplayClass66_0.<OnIsVisibleChanged>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by jinujoseph** [comment]
@ivanbasov  related to async completion ?

**Comment by ivanbasov** [comment]
Roslyn is not on stack. Moved to the Edtior team with https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790569
