### ISSUE TITLE
CSharpAddImportCodeFixProvider crashes by unknown type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#33497]
When adding a program-element like variable/property etc., if the type is an unknown (not yet added nuget package, or older version library which does not contain the new interface) type then the CSharpAddImportCodeFixProvider crashes.
Stacktrace:

System.AggregateException : One or more errors occurred. ---&gt; A reference to the component 'LIG.FW.Interface' already exists in the project.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---&gt; (Inner Exception #0) System.Runtime.InteropServices.COMException : A reference to the component 'LIG.FW.Interface' already exists in the project.
   at VSLangProj.References.AddProject(Project pProject)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyProjectReferenceAdded(ProjectId projectId,ProjectReference projectReference)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)&lt;---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/438080/csharpaddimportcodefixprovider-crashes-by-unknown.html
VSTS ticketId: 779478_
_These are the original issue comments:_

Visual Studio Feedback System on 2/17/2019, 02:50 AM (2 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.
