### ISSUE TITLE
Failed assertion in SolutionState.CheckContainsDocument

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33652]
**Version Used**: #33646

https://dev.azure.com/dnceng/public/_build/results?buildId=105532

**Steps to Reproduce**:

Found in integration tests.

```
Event Time (UTC): 2/25/2019 1:26:22 AM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Exception
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Exit(System.String)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean)
   at Microsoft.CodeAnalysis.SolutionState.CheckContainsDocument(Microsoft.CodeAnalysis.DocumentId)
   at Microsoft.CodeAnalysis.SolutionState.WithDocumentText(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.PreservationMode)
   at Microsoft.CodeAnalysis.Solution.WithDocumentText(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.PreservationMode)
   at Microsoft.CodeAnalysis.Text.TextExtensions.GetOpenDocumentInCurrentContextWithChanges(Microsoft.CodeAnalysis.Text.SourceText)
   at Microsoft.CodeAnalysis.Text.Extensions.GetOpenDocumentInCurrentContextWithChanges(Microsoft.VisualStudio.Text.ITextSnapshot)
   at Microsoft.VisualStudio.CodeSense.Roslyn.DynamicSyntaxTreeProvider+DynamicSyntaxTree+<UpdateAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.VisualStudio.CodeSense.Roslyn.DynamicSyntaxTreeProvider+DynamicSyntaxTree+<UpdateAsync>d__7, Microsoft.VisualStudio.CodeSense.Roslyn, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<UpdateAsync>d__7 ByRef)
   at Microsoft.VisualStudio.CodeSense.Roslyn.DynamicSyntaxTreeProvider+DynamicSyntaxTree.UpdateAsync(Microsoft.VisualStudio.Text.ITextSnapshot, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.CodeSense.Roslyn.CodeElementCache+<RebuildAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.VisualStudio.CodeSense.Roslyn.CodeElementCache+<RebuildAsync>d__9, Microsoft.VisualStudio.CodeSense.Roslyn, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<RebuildAsync>d__9 ByRef)
   at Microsoft.VisualStudio.CodeSense.Roslyn.CodeElementCache.RebuildAsync(Microsoft.VisualStudio.Text.ITextSnapshot, Boolean, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger+<UpdateSnapshotAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger+<UpdateSnapshotAsync>d__15, Microsoft.VisualStudio.CodeSense.Roslyn, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<UpdateSnapshotAsync>d__15 ByRef)
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger.UpdateSnapshotAsync(Microsoft.VisualStudio.Text.ITextSnapshot, Boolean, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.CodeSense.Editor.Tagger`1+<>c__DisplayClass22_1+<<UpdateSnapshotAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.VisualStudio.CodeSense.Editor.Tagger`1+<>c__DisplayClass22_1+<<UpdateSnapshotAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.VisualStudio.CodeSense, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<<UpdateSnapshotAsync>b__0>d<System.__Canon> ByRef)
   at Microsoft.VisualStudio.CodeSense.Editor.Tagger`1+<>c__DisplayClass22_1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<UpdateSnapshotAsync>b__0(System.Threading.Tasks.Task`1<Int32>)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by sharwell** [comment]
:link: This assertion caused a failure in https://dev.azure.com/dnceng/public/_build/results?buildId=122766

**Comment by sharwell** [comment]
@heejaechang This is impacting many test runs. Can you take a look?

**Comment by jasonmalinowski** [comment]
Looks like I independently found this and have #34195 out to fix this.
