### ISSUE TITLE
CSharpUpgradeProjectCodeFixProvider crashes in ASP.Net Core application

### ISSUE THREAD

**Issue by vsccarl** [dotnet/roslyn#33700]
Copied from VSO/797009.

**Version Used**: 
Affected Branch: 16.0 Preview 4 
Affected Build: 16.0 Preview 4 [28619.130.d16.0] 
Affected Product Language: English 

**Steps to Reproduce**:

1. Create a new ASP.Net Core Application project with template Web Application
2. Edit Startup.cs to contain a c# 8 feature (e.g. static local function)
3. Alt+Enter on the red squiggled static keyword to upgrade the project c# version.

**Expected Behavior**:
Project is upgrade to c# 8 and I can use static local functions.

**Actual Behavior**:
Yellow warning appears at the top that says "CSharpUpgradeProjectCodeFixProvider encountered an error and has been disabled"
With stack trace
```
System.AggregateException : One or more errors occurred. ---> Changing document 'C:\Users\dabarbet\source\repos\WebApplication1\WebApplication1\Pages\Privacy.g.cs' is not supported.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NotSupportedException : Changing document 'C:\Users\dabarbet\source\repos\WebApplication1\WebApplication1\Pages\Privacy.g.cs' is not supported.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

It seems like this might be expected but it isn't completely clear.

**Comment by jhoiby** [comment]
Hello, I'm getting a similar error trying to rename a class in the following code: 
```
namespace SSar.Presentation.WebUI.Areas.SarBaseImport.Pages
{
    public class LoadMdbModel : PageModel
    {
        public LoadMdbModel(ILegacyDataProvider<SarBaseRow> legacyDataProvider)
        {
            Data = legacyDataProvider?.Data 
                               ?? throw new ArgumentNullException(nameof(legacyDataProvider));
        }

        [BindProperty]
        public IEnumerable<SarBaseRow> Data { get; set; }

        public void OnGet()
        {
        }
    }
}
```
If I change the class name from "LoadMdbModel" to "Pg2LoadMdbModel", then use the suggested action to do a global rename of the class I get a notification bar at the top of the code window that says "'CSharpRenameTrackingCodeFixProvider' encountered an error and has been disabled."

Following the failed class name change I get a series of three errors in the error list. They are all similar to:
```
Code: CS0234
Description: The type or namespace name 'LoadMdbModel' does not exist in the namespace 'SSar.Presentation.WebUI.Areas.SarBaseImport.Pages' (are you missing an assembly reference?)
File: LoadMdb.cshtml (hover tip: C:\Users\James\Source\repos\SmartSar\SSar.Presentation.WebUI\Areas\SarBaseImport\Pages\LoadMdb.cshtml
```
Using:

VS Community Version: 16.1.4

Manually-installed extensions: 
- JetBrains ReSharper Ultimate 2019.1.2

SDK's manually installed outside of VS installer (IIRC):
- DotNetCore 2.2.300
- DotNetCore 3.0.100 Preview 6

Here's the stack trace: 
```
System.AggregateException : One or more errors occurred. ---> Changing document 'C:\Users\james\source\repos\SmartSAR\SSar.Presentation.WebUI\Areas\SarBaseImport\Pages\Pg2LoadMdb.g.cs' is not supported.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NotSupportedException : Changing document 'C:\Users\james\source\repos\SmartSAR\SSar.Presentation.WebUI\Areas\SarBaseImport\Pages\Pg2LoadMdb.g.cs' is not supported.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForGlobalIdentifierRename(Workspace workspace,Solution newSolution,Solution oldSolution,String undoName,IEnumerable`1 changedDocuments,ISymbol symbol,String newName,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

**Comment by vatsalyaagrawal** [comment]
https://developercommunity.visualstudio.com/content/problem/664056/csharprenametrackingcodefixprovider-encountered-an-1.html

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro.  We can track this through prism.
