### ISSUE TITLE
Exception dialog in PasteTrackingService

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#33776]
**Version Used**: `16.0.0 Preview 4.0 28625.133.d16.0`

**Steps to Reproduce**:

I can't reproduce it, but I had some code on my clipboard (I thought) and pasted. Nothing happened immediately, so I pasted again and got the below failure via the ActivityLog popup.

**Failure**:

```
System.ArgumentException: Item has already been added. Key in dictionary: &apos;System.Object&apos;  Key being added: &apos;System.Object&apos;
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)
   at Microsoft.CodeAnalysis.PasteTracking.PasteTrackingService.RegisterPastedTextSpan(ITextBuffer textBuffer, TextSpan textSpan)
   at Microsoft.CodeAnalysis.PasteTracking.PasteTrackingPasteCommandHandler.ExecuteCommand(PasteCommandArgs args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;Execute&gt;b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)
```

**Comment by dpoeschl** [comment]
FYI @JoeRobich
