### ISSUE TITLE
Integration test cleanup fails to close debugger source browser window

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33785]
![image](https://user-images.githubusercontent.com/1408396/53644151-807cbf80-3bfb-11e9-9da1-838c11cdc8a5.png)

```
System.TimeoutException: Failed to enter design mode in a timely manner.

Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.WaitForDesignMode()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.CleanUpOpenSolution()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.CleanUpOpenSolution()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.CleanUp() in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs:line 210
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.Close(Boolean exitHostProcess) in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs:line 244
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<UpdateCurrentlyRunningInstanceAsync>d__12.MoveNext() in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task).GetType().Name

Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.WaitForDesignMode()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.CleanUpOpenSolution()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.SolutionExplorer_InProc.CleanUpOpenSolution()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.CleanUp() in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs:line 210
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstance.Close(Boolean exitHostProcess) in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstance.cs:line 244
   at Microsoft.VisualStudio.IntegrationTest.Utilities.VisualStudioInstanceFactory.<UpdateCurrentlyRunningInstanceAsync>d__12.MoveNext() in /_/src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by sharwell** [comment]
@tmat This is looking like it could be a regression in the **master** branch

**Comment by tmat** [comment]
Can you reproduce it manually?

**Comment by sharwell** [comment]
@tmat Not so far. I'll see if I can figure out which test is triggering it and run it in a loop to see if it's locally reproducible.

**Comment by sharwell** [comment]
:memo: The workaround added in #33850 should be removed when this issue is fixed.
