### ISSUE TITLE
FailFast in integration tests (ProjectId.ReadFrom)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#33856]
**Version Used**: Occurred in integration test build for #33834

**Steps to Reproduce**:

```
Event Time (UTC): 3/4/2019 10:39:49 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Exception: Unexpected value 'UInt16' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Exit(System.String)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean, System.String)
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(System.Object)
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind)
   at Roslyn.Utilities.ObjectReader.ReadStringValue()
   at Roslyn.Utilities.ObjectReader.ReadString()
   at Microsoft.CodeAnalysis.ProjectId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.DocumentId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, System.Collections.Generic.IDictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.VersionStamp, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<GetCompilerAnalysisResultAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner.GetCompilerAnalysisResultAsync(System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<>c__DisplayClass8_1.<AnalyzeOutOfProcAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by heejaechang** [comment]
@sharwell do we have a dump? if not, a way to repro?

**Comment by sharwell** [comment]
@heejaechang The only information we have are the build logs from that integration test run. I don't believe that includes dump files.

**Comment by heejaechang** [comment]
@sharwell okay, how about servicehub logs from %temp%\servicehub\logs? that also can help me to track down issue.

the stream it is throwing get messed when cancellation is thrown while data is being transferred, and just dropped. I would like to check whether this is the case. in that case, it is expected since that's how cancellation is handled in current design for named pipe for OOP. when cancellation is thrown, server/client just drop/close connection and that can cause exception like above since stream is in unknown state. but it gets ignored.

it might not that case but other bug, but dump or logs will probably have info to figure what out cases it is.

**Comment by sharwell** [comment]
Another stack trace:

🔗 https://dnceng.visualstudio.com/public/_build/results?buildId=117739

```
Event Time (UTC): 3/8/2019 1:41:24 AM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Exception: Unexpected value '108' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Exit(System.String)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean, System.String)
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(System.Object)
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind)
   at Roslyn.Utilities.ObjectReader.ReadStringValue()
   at Roslyn.Utilities.ObjectReader.ReadString()
   at Microsoft.CodeAnalysis.ProjectId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.DocumentId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, System.Collections.Generic.IDictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.VersionStamp, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<GetCompilerAnalysisResultAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner.GetCompilerAnalysisResultAsync(System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<>c__DisplayClass8_1.<AnalyzeOutOfProcAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by sharwell** [comment]
@heejaechang This should give you the Watson bucket:

```
Event Time (UTC): 3/8/2019 1:41:41 AM
Application Name: devenv.exe
Application Version: 15.9.28307.344
Faulting Module: Microsoft.CodeAnalysis.Workspaces
Faulting Module Version: 42.42.42.42424
Event Name: CLR20r3
Cab Id: 0
Fault Bucket: 1311705318003623880
Hashed Bucket: bebfcbd0e55f3e0342341d097998c7c8
Watson Report Id: 984c20ea-613e-4140-b637-0a07e81590aa
```

**Comment by sharwell** [comment]
Another stack trace:

```
Event Time (UTC): 4/5/2019 6:35:55 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Exception: Unexpected value '101' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Exit(System.String)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean, System.String)
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(System.Object)
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind)
   at Roslyn.Utilities.ObjectReader.ReadStringValue()
   at Roslyn.Utilities.ObjectReader.ReadString()
   at Microsoft.CodeAnalysis.ProjectId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.DocumentId.ReadFrom(Roslyn.Utilities.ObjectReader)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.Deserialize(Roslyn.Utilities.ObjectReader, System.Collections.Generic.IDictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.VersionStamp, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<GetCompilerAnalysisResultAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner.GetCompilerAnalysisResultAsync(System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+InProcOrRemoteHostAnalyzerRunner+<>c__DisplayClass8_1.<AnalyzeOutOfProcAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__1`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by CyrusNajmabadi** [comment]
Haven't seen any more reports of this.  And we don't diagnosticresult serialization anymore.
