### ISSUE TITLE
'SyntaxEditorBasedFixAllProvider' encountered an error - InvalidCastException

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#33895]
Hi there,

I am using VS 2019 preview 4.1 and I have tried to do an apply code fix on full solution for rule `IDE0048: Parentheses should be added for clarity` and I end up with the following stack trace:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.Parenthesize(SyntaxNode expression,Boolean includeElasticTrivia,Boolean addSimplifierAnnotation)
   at Microsoft.CodeAnalysis.AddRequiredParentheses.AddRequiredParenthesesCodeFixProvider.<>c__DisplayClass4_0.<FixAllAsync>b__0(SyntaxNode current,SyntaxGenerator _)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.FixDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

Cheers,
Amaury

**Comment by CyrusNajmabadi** [comment]
@Evangelink Can you provide your solution and where you invoked the feature from?  Thanks!

**Comment by Evangelink** [comment]
Hi @CyrusNajmabadi,

I am wondering if this issue was a side-effect of something else because I was able to reproduce multiple times in a row the issue yesterday but I no longer can today.

I am sending you the link to the solution I was working on when it was failing: https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/SonarAnalyzer.sln

Feel free to close the ticket as I cannot manage to reproduce the error. I'll comment if I do manage to have an always failing reproducer.

Thanks for your time anyway!

**Comment by Youssef1313** [comment]
This cast was removed in https://github.com/dotnet/roslyn/pull/43438. But it feels odd to pass a class declaration to `Parenthesize`.

**Comment by CyrusNajmabadi** [comment]
Prism shows no hits for this, and we've gotten no other reports or repro cases.  So i'm going to close this otu as presumbly being fixed in the interim period.
