### ISSUE TITLE
CSharpUpgradeProject.LegacyProject_MultiplePlatforms_AllConfigurationsUpdated Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34161]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125135&view=ms.vss-test-web.build-test-results-tab)

```
Assert.All() Failure: 4 out of 4 items in the collection did not pass.
[3]: Item: <PropertyGroup Condition=\"'$(Configuration)|$(Platform)' == 'Release|x64'\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <OutputPath>bin\\x64\\Release\\</OutputPath>
 <PlatformTarget>x64</PlatformTarget>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: latest
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[2]: Item: <PropertyGroup Condition=\"'$(Configuration)|$(Platform)' == 'Debug|x64'\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <OutputPath>bin\\x64\\Debug\\</OutputPath>
 <PlatformTarget>x64</PlatformTarget>
 <LangVersion>7.0</LangVersion>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 ↓ (pos 0)
 Expected: latest
 Actual: 7.0
 ↑ (pos 0)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[1]: Item: <PropertyGroup Condition=\"'$(Configuration)|$(Platform)' == 'Release|x86'\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <OutputPath>bin\\x86\\Release\\</OutputPath>
 <PlatformTarget>x86</PlatformTarget>
 <LangVersion>7.1</LangVersion>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 ↓ (pos 0)
 Expected: latest
 Actual: 7.1
 ↑ (pos 0)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[0]: Item: <PropertyGroup Condition=\"'$(Configuration)|$(Platform)' == 'Debug|x86'\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <OutputPath>bin\\x86\\Debug\\</OutputPath>
 <PlatformTarget>x86</PlatformTarget>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: latest
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.
```

**Comment by JoeRobich** [comment]
Unskipping this test is being tracked by https://github.com/dotnet/roslyn/issues/63026
