### ISSUE TITLE
CSharpUpdateProjectToAllowUnsafe.CPSProject_GeneralPropertyGroupUpdated Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34165]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125135&view=ms.vss-test-web.build-test-results-tab)

```
Assert.Contains() Failure
Not found: (filter expression)
In value: WhereEnumerableIterator<XElement> [<PropertyGroup>
 <TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>]
```

**Comment by JoeRobich** [comment]
Saw this again [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=137183&view=ms.vss-test-web.build-test-results-tab) Release Legacy:

Stack trace:
```
   at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.VerifyPropertyOutsideConfiguration(XElement projectElement, String name, String value) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 31
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpUpdateProjectToAllowUnsafe.CPSProject_GeneralPropertyGroupUpdated() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpUpdateProjectToAllowUnsafe.cs:line 42
```

![02 58 46-CSharpUpdateProjectToAllowUnsafe CPSProject_GeneralPropertyGroupUpdated-ContainsException](https://user-images.githubusercontent.com/611219/55291923-57d21c00-5399-11e9-87f5-85d99aaa88a7.png)
