### ISSUE TITLE
CSharpUpdateProjectToAllowUnsafe.LegacyProject_AllConfigurationsUpdated Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34164]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125135&view=ms.vss-test-web.build-test-results-tab)

Failed when expecting `true`
```
Assert.All() Failure: 2 out of 2 items in the collection did not pass.
[1]: Item: <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <DebugType>pdbonly</DebugType>
 <Optimize>true</Optimize>
 <OutputPath>bin\\Release\\</OutputPath>
 <DefineConstants>TRACE</DefineConstants>
 <ErrorReport>prompt</ErrorReport>
 <WarningLevel>4</WarningLevel>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: true
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[0]: Item: <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <DebugSymbols>true</DebugSymbols>
 <DebugType>full</DebugType>
 <Optimize>false</Optimize>
 <OutputPath>bin\\Debug\\</OutputPath>
 <DefineConstants>DEBUG;TRACE</DefineConstants>
 <ErrorReport>prompt</ErrorReport>
 <WarningLevel>4</WarningLevel>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: true
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
```

Failed when expecting `latest`
```
Assert.All() Failure: 2 out of 2 items in the collection did not pass.
[1]: Item: <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <DebugType>pdbonly</DebugType>
 <Optimize>true</Optimize>
 <OutputPath>bin\\Release\\</OutputPath>
 <DefineConstants>TRACE</DefineConstants>
 <ErrorReport>prompt</ErrorReport>
 <WarningLevel>4</WarningLevel>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: latest
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[0]: Item: <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">
 <DebugSymbols>true</DebugSymbols>
 <DebugType>full</DebugType>
 <Optimize>false</Optimize>
 <OutputPath>bin\\Debug\\</OutputPath>
 <DefineConstants>DEBUG;TRACE</DefineConstants>
 <ErrorReport>prompt</ErrorReport>
 <WarningLevel>4</WarningLevel>
 </PropertyGroup>
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: latest
 Actual: (null)
 at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\StringAsserts.cs:line 244
 at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.<>c__DisplayClass3_0.<VerifyPropertyInEachConfiguration>b__0(XElement group) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 43
 at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
```

**Comment by JoeRobich** [comment]
Unskipping this test is being tracked by https://github.com/dotnet/roslyn/issues/63026
