### ISSUE TITLE
BasicAddMissingReference.VerifyAvailableCodeActions Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34289]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=128510&view=ms.vss-test-web.build-test-results-tab)

```
System.Exception: Marker 'y.goo' not found in text: Module Module1

    Sub Main()

    End Sub

End Module


Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass8_0.<PlaceCaret>b__0(IWpfTextView view)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass13_0.<GetExecuteOnActionViewCallback>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.PlaceCaret(String marker, Int32 charsOffset, Int32 occurrence, Boolean extendSelection, Boolean selectBlock)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg).GetType().Name
```

![10 14 22-BasicAddMissingReference VerifyAvailableCodeActions-TargetInvocationException](https://user-images.githubusercontent.com/611219/54700694-bf15e380-4af0-11e9-8231-93a10e610a8d.png)

**Comment by JoeRobich** [comment]
This was likely caused by a earlier failure in `SolutionState.CheckContainsDocument` which has a fix that is flowing through.
