### ISSUE TITLE
CSharpCodeActions.ApplyEditorConfigAndFixAllOccurrences Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34288]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=128138&view=ms.vss-test-web.build-test-results-tab)

Error message:
```
System.NullReferenceException : Object reference not set to an instance of an object.
```
Stack trace:
```
Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass21_0.<<GetLightBulbApplicationAction>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass19_0.<<ApplyLightBulbAction>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ApplyLightBulbAction(String actionName, Nullable`1 fixAllScope, Boolean blockUntilComplete)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.ApplyLightBulbAction(String actionName, Nullable`1 fixAllScope, Boolean blockUntilComplete)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.ApplyLightBulbAction(String action, Nullable`1 fixAllScope, Boolean blockUntilComplete) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/TextViewWindow_OutOfProc.cs:line 82
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CodeActions(IEnumerable`1 expectedItems, String applyFix, Boolean verifyNotShowing, Boolean ensureExpectedItemsAreOrdered, Nullable`1 fixAllScope, Boolean blockUntilComplete) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/TextViewWindow_OutOfProc.Verifier.cs:line 75
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CodeAction(String expectedItem, Boolean applyFix, Boolean verifyNotShowing, Boolean ensureExpectedItemsAreOrdered, Nullable`1 fixAllScope, Boolean blockUntilComplete) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/TextViewWindow_OutOfProc.Verifier.cs:line 34
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.ApplyEditorConfigAndFixAllOccurrences() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs:line 243
```

![02 29 29-CSharpCodeActions ApplyEditorConfigAndFixAllOccurrences-NullReferenceException](https://user-images.githubusercontent.com/611219/54660698-a841a380-4a94-11e9-8b87-ae74a052ddf0.png)

**Comment by dpoeschl** [comment]
Happened to me again here: https://github.com/dotnet/roslyn/pull/33733#issuecomment-476276266

**Comment by CyrusNajmabadi** [comment]
closing out as this has been running fine.
