### ISSUE TITLE
Failed Assert in VisualStudioMetadataReferenceManager..ctor

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#34329]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=129561&view=ms.vss-test-web.build-test-results-tab) Release Legacy run

```
Event Time (UTC): 3/21/2019 12:23:52 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Exception
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Exit(System.String)
   at Microsoft.VisualStudio.IntegrationTest.Setup.IntegrationTestTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReferenceManager..ctor(System.IServiceProvider, Microsoft.CodeAnalysis.Host.ITemporaryStorageService)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioMetadataReferenceManagerFactory.CreateService(Microsoft.CodeAnalysis.Host.HostWorkspaceServices)
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices+<>c__DisplayClass5_0.<.ctor>b__1()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at Microsoft.VisualStudio.LanguageServices.Setup.RoslynPackage.DisposeVisualStudioServices()
   at Microsoft.VisualStudio.LanguageServices.Setup.RoslynPackage.Dispose(Boolean)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.Close()
```

![12 42 26-Unknown-MissingMethodException](https://user-images.githubusercontent.com/611219/54760316-124d6c00-4bad-11e9-972c-adf2c3870e31.png)

**Comment by JoeRobich** [comment]
Not sure if VS didn't start on this run, but every test seems to have failed.
