### ISSUE TITLE
CSharpAddMissingImportsRefactoringProvider encountered an error 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#34398]
![image](https://user-images.githubusercontent.com/12449387/54889937-3d151a00-4e64-11e9-9c95-a768de389db0.png)

```
System.NotImplementedException : The method or operation is not implemented.
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.GetChangesForCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.ApplyFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.AddMissingImportsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsRefactoringProvider.AddMissingImports(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Hit this when i tired to copy the code from https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext?view=netframework-4.7.2 to a class filein console application

**Comment by JoeRobich** [comment]
This is a bug with how `AbstractAddMissingImportsFeatureService` is applying the add import code actions. The `AssemblyReferenceCodeAction` does not implement `GetChangedDocumentAsync` but instead implements `ComputeOperationsAsync`.

**Comment by jinujoseph** [comment]
also reported at [DC](https://developercommunity.visualstudio.com/content/problem/530411/csharpaddmissingimportsrefactoringprovider-error.html)
