### ISSUE TITLE
Allow code fixes to modify the project file

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#34636]
There are a number of useful cases where a code fix provider would need to add/modify project properties in order to fully implement a feature (i.e. the [AllowUnsafe](https://github.com/dotnet/roslyn/pull/25875) option went to some hoops to implement it, or changing `LangVersion`, etc.). There are also scenarios where a simple migration to a new feature just requires removing properties and therefore contributing towards a cleaner project file with less legacy properties lagging around as years go by.

A potential approach to this would be to add the project file itself as an `AdditionalFile`:

```xml
	<ItemGroup>
		<AdditionalFiles Include="$(MSBuildProjectFullPath)" />
	</ItemGroup>
```

And then the code fix could simply change the additional file text with the existing supported APIs:

```csharp
    private async Task<Solution> CreateChangedSolutionAsync(CodeFixContext context, Diagnostic diagnostic, CancellationToken cancellation)
    {
        var projectDoc = context.Document.Project.AdditionalDocuments
            .FirstOrDefault(doc => doc.FilePath.EndsWith(".csproj"));

        if (projectDoc == null)
            return null;

        var documentSyntax = Parser.ParseText((await projectDoc.GetTextAsync()).ToString());
        var newNode = documentSyntax.Accept(new AddPropertyVisitor("AndroidUseIntermediateDesignerFile", "True"));

        var text = await projectDoc.GetTextAsync(cancellation);
        var newDoc = context.Document.Project.Solution
            .WithAdditionalDocumentText(projectDoc.Id, SourceText.From(
                newNode.ToFullString(), text.Encoding))
            .GetProject(context.Document.Project.Id)
            .GetDocument(context.Document.Id);

        return newDoc.Project.Solution;
    }
```

In the above case, I'm using an [full-fidelity XML parser/editor](https://www.nuget.org/packages/GuiLabs.Language.Xml/) which results in the following IDE experience:

![image](https://user-images.githubusercontent.com/169707/55342554-714d9380-547f-11e9-9610-9eafb2a8f5f0.png)

Currently, applying that fix will result in the following exception, since it's not really a supported scenario:

```
System.AggregateException : One or more errors occurred. ---> Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.Runtime.InteropServices.COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode,IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider,String filePath,IVsHierarchy hierarchyOpt,Boolean needsSave,Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAdditionalDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
```

But I think it would be quite useful if it "just worked". I would have expected it to work for CPS at least, since it does allow opening the .csproj in the editor and modifying it while the project is opened, but the same exception occurs for both project systems at the moment.

Just for reference, here's the visitor that adds that property based on the [GuiLabs.Language.Xml](https://www.nuget.org/packages/GuiLabs.Language.Xml/) package: 
```csharp
        class AddPropertyVisitor : SyntaxRewriter
        {
            bool propertyAdded = false;
            string name;
            string value;

            public AddPropertyVisitor(string name, string value)
            {
                this.name = name;
                this.value = value;
            }

            public override Microsoft.Language.Xml.SyntaxNode VisitXmlElement(Microsoft.Language.Xml.XmlElementSyntax node)
            {
                if (node.Name == "PropertyGroup" && !propertyAdded)
                {
                    var elementSyntax = Parser.ParseText("\r\n\t\t" + new XElement(name, value));
                    propertyAdded = true;

                    return node.AddChild(elementSyntax.RootSyntax).AsNode;
                }

                return base.VisitXmlElement(node);
            }
        }
```

**Comment by jasonmalinowski** [comment]
So I think this is a good suggestion to play around with. Assuming we wanted the project file to be available for things _other_ than just in-IDE code fixes, we'd need to add the project file to the additional files list at the MSBuild targets level, but that's a trivial change (and is to my understanding what @kzu was doing when he tried this).

I think the only design question for me would be whether this seems "inappropriate" in some way or means analyzers are perhaps too bound to MSBuild, but analyzers doing this are already implicitly bound by definition, so that's probably fine. There's probably a non-trivial amount of work needed to make sure the IDE correctly handles the application of the fixes for both project systems, especially if the project systems have unsaved changes to those files, but I don't think anything there would be insurmountable.

Thoughts @jinujoseph @jaredpar @sharwell? I'm not sure if we previously considered this and rejected it for some reason. Should we add it to the design meeting backlog?

**Comment by jaredpar** [comment]
I don't see any issues with it. The direct project file seems like it would be a logical input as additional files. I'd worry a bit though if we started venturing into areas like Directory.Build.props files. That seems like it would get a bit out of control.

**Comment by mavasani** [comment]
Note that we have had pretty similar requests in the past. For example, see https://github.com/dotnet/roslyn/issues/11097#issuecomment-217972294. The first requested item in that comment is a more generic request of passing in all non-source files in the project as additional files, so scenarios such as analysis of xaml files, resx files, web.config files, etc. work by default for corresponding analyzers without the user having to tag them as additional files in their project. However, that request has always had perf concerns as we might pass in a humongous list of files as additional files, and never have any analyzer using it.

**Comment by mavasani** [comment]
Note that we have also had requests to expose the MSBuild properties for the project so analysis can be configured based on the runtime values of these properties. Basically, this current issue only seems to be requesting project files as additional files from the perspective of _code fixes_, but we have had numerous requests for the same functionality in the past from the perspective of _analyzers_.

**Comment by kzu** [comment]
>  However, that request has always had perf concerns as we might pass in a humongous list of files as additional files

This issue is not about automatically passing in anything, just the ability of a nuget-provided anayzer to also provide its own targets that can (optionally, fully opt-in) pass themselves whichever project files it needs and have the infrastructure support editing and saving them, since even the code action preview window is already working just fine. A "tiny" enabler, if you will, that does not require agreeing on anything being passed in by default that might have a negative impact.

> Note that we have also had requests to expose the MSBuild properties for the project 

This can readily be done [by other means](https://github.com/kzu/AutoCodeFix/blob/master/src/AutoCodeFix.Tasks/AutoCodeFix.targets#L61-L83) via nuget-provided targets and analyzers that have knowledge of them, so it's also out of scope of this request intentionally to keep it absolutely minimal and make for an "easy yes" one ;)

**Comment by jasonmalinowski** [comment]
> This issue is not about automatically passing in anything, just the ability of a nuget-provided anayzer to also provide its own targets that can (optionally, fully opt-in) pass themselves whichever project files it needs and have the infrastructure support editing and saving them, since even the code action preview window is already working just fine.

So the expectation is you just bundle a .target in the NuGet in the build/ folder like anything else, and use that to add yourself to the build. That's usable for you, correct?

**Comment by kzu** [comment]
Yes, absolutely!

**Comment by kzu** [comment]
Not saying the experience can be made easier/more intuitive down the road, just saying I'd rather have something that works sooner, even if it requires a bit of work on my part, than waiting longer for something that will at most save me from a .targets (which I already have in most cases anyway).

**Comment by jasonmalinowski** [comment]
@kzu: so you can already do that today: in your NuGet package you can add a .targets or .props inside a build/ folder, and that can add things to AdditionalFiles and NuGet will include that in the build. You don't need anything from us. The only thing you don't already have here is us not crashing once you do it.

**Comment by jasonmalinowski** [comment]
This was also looked at during design review: I had some questions about whether or not we needed to do this specific value centrally, but since you can add this in a NuGet package today there's no problems there. At this point this is just a bug we need to fix so it doesn't get all crashy.

**Comment by kzu** [comment]
Exactly! 💯

**Comment by kzu** [comment]
So, should this be labelled as a bug rather than a feature request then?

**Comment by jasonmalinowski** [comment]
@kzu: indeed.

**Comment by kzu** [comment]
Looks like having this capability (not crashing) would make it a nice fit for suggesting global using end up in the project file 😉  https://github.com/dotnet/docs/issues/29746

**Comment by kzu** [comment]
Another scenario where the built-in code fixers could be smarter by helping users upgrade to newer features they read all over the web:

1. Create a netstandard2 class library
2. Try to use a file-scoped namespace:

![image](https://user-images.githubusercontent.com/169707/198402440-60247aa0-07b1-439c-9577-f19c287f7993.png)

The codefix is rather useless if I wanted to use the feature:

![image](https://user-images.githubusercontent.com/169707/198402503-ebb7df00-db12-4588-9511-5cfab53cc9ba.png)

If this bug was fixed, the team could provide a codefix that would create/update the `<LangVersion>Latest</LangVersion>` appropriately in the .csproj.

**Comment by CyrusNajmabadi** [comment]
@kzu we do offer that:

![image](https://user-images.githubusercontent.com/4564579/198727177-381f7fcb-d9b9-4bf4-b784-cdf12471ac54.png)

**Comment by kzu** [comment]
File | New | Class Library (netstandard2.0): 

![image](https://user-images.githubusercontent.com/169707/198730095-13da1929-0b35-41c0-8c84-03e93776dd39.png)

```
Microsoft Visual Studio Enterprise 2022
Version 17.4.0 Preview 4.0
VisualStudio.17.Preview/17.4.0-pre.4.0+33015.44
Microsoft .NET Framework
Version 4.8.09032
```

Not getting it. Also, is this another case where it was fixed one-off like others have? Because I bring it up here so that us (third party via nuget) can also do this easily :)

**Comment by kzu** [comment]
If I set langversion to `Latest`, things work just fine, FWIW (I do this all the time with analyzers/source generators/codefixers, for example). Also, if you just add [Poly#](https://www.nuget.org/packages/PolySharp/), for example, you get full C#10 features too. 

I'm sure this is to simplify complexity for consumers, but I can attest to NS2 + C#10 working just fine on net472 (within VS extensions, for example).

**Comment by ryzngard** [comment]
Jason is right, we don't recommend purely based on the supported versions based on TFM. Even if it works, things can break in unexpected ways and isn't supported. 

Technically using `Latest` with net472 isn't supported, and if something breaks you're on your own :P

**Comment by kzu** [comment]
Sure. I don't want the conversation to derail from the original bug that would be awesome to get fixed here ;)

**Comment by kzu** [comment]
Here you can see what not being able to codefix project properties results in: https://x.com/davidfowl/status/1859069210007400585

Gazillion properties that now MUST be used in projects, with no clear way for nuget authors to help users properly set up, due to this not being there.

**Comment by CyrusNajmabadi** [comment]
@kzu this is on the backlog and we have practically no resources available to invest here.  If you want to contribute a fix though, we'd be happy to take it.  Thanks.

**Comment by kzu** [comment]
Sure thing, I'd be happy to contribute. It would be super helpful if someone with knowledge of the codebase could offer a couple pointers on where to look though, so as not to start from scratch from that stacktrace 🙏

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski can you please advise. Why are we even opening an invisible editor here?  Is it for undo?

**Comment by jasonmalinowski** [comment]
@kzu Have we just checked if this still reproduces? The bug is fairly old at this point and I could imagine any number of changes have happened over time.

@CyrusNajmabadi One reason for the invisible editor would be undo, yes. We'd also need to capture the text buffer generally because if the user has the project file open so they can see it we'd have to acquire the open text buffer -- directly writing to disk would cause some strange reloads and may blow away user edits in that case.

Let's verify this still reproduces with the same stack first, and then we can loop in the project system folks. IIRC there's a bit of magic around the text buffers that back a .csproj file, and to acquire the buffer from the RDT you need to hop through an extra interface. I don't know if the InvisibleEditor code is going through that path, and whether it is or isn't might be a bug or might be a feature.

**Comment by kzu** [comment]
I'm in the process of creating a minimal repro to check again. Will report back soon. Thanks!

**Comment by kzu** [comment]
Ok, got the sample up at https://github.com/kzu/ProjectCodeFixer.

The readme has some details, but basically:
1. Codefix is not being picked up (no idea why, I've a dozen other projects set up exactly the same and it works 100% reliably)
2. Might be related to the fact that I can't even unit test the code fixer due to: `System.InvalidOperationException : Code fix is attempting to provide a fix for a non-local analyzer diagnostic`
3. The expected behavior would be to be able to provide a codefix in a code file, that actually fixes an additional file (in this case, the project file).

At some point, perhaps the registering of a codefix in another file was disabled entirely, dunno.

**Comment by jasonmalinowski** [comment]
@kzu Just to clarify, you were still able to reproduce the original issue, or the new issues are completely blocking that?

**Comment by kzu** [comment]
Completely blocked since the code fix for the additional file isn't being picked at all.

**Comment by jasonmalinowski** [comment]
@sharwell do you recognize that error?

**Comment by CyrusNajmabadi** [comment]
@kzu as mentioned: https://github.com/dotnet/roslyn/issues/34636#issuecomment-2492301236

**Comment by kzu** [comment]
@CyrusNajmabadi as mentioned: https://github.com/dotnet/roslyn/issues/34636#issuecomment-2492328780
