### ISSUE TITLE
SetVisualStudioBootstrapperBuildArgs fails during build -restore -ci

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#34928]
Clone Roslyn and run `build -restore -ci`. 

It fails with:
```
Downloading https://raw.githubusercontent.com/dotnet/roslyn/master/eng/config/PublishData.json
##vso[task.setvariable variable=VisualStudio.MajorVersion;]16
##vso[task.setvariable variable=VisualStudio.ChannelName;]int.d16.1stg
Cannot find path 'C:\roslyn\artifacts\VSSetup\Debug\Insertion' because it does not exist.
System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\roslyn\artifacts\VSSetup\Debug\Insertion' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetChildNamesInDir(String dir, String leafElement, Boolean getAllContainers, CmdletProviderContext context, Boolean dirIsProviderPath, PSDriveInfo drive, ContainerCmdletProvider provider, String& modifiedDirPath)
   at System.Management.Automation.LocationGlobber.GenerateNewPSPathsWithGlobLeaf(List`1 currentDirs, PSDriveInfo drive, String leafElement, Boolean isLastLeaf, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.GetChildItems(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord()
at SetVisualStudioBootstrapperBuildArgs, C:\roslyn\eng\build.ps1: line 331
at <ScriptBlock>, C:\roslyn\eng\build.ps1: line 612
at <ScriptBlock>, <No file>: line 1
```

If I'd like to just build Roslyn without insertion, it would be nice to have a command-line flag to disable calling `SetVisualStudioBootstrapperBuildArgs` here:

https://github.com/KirillOsenkov/roslyn/blob/297aaf20e69ddb60dc4756a7bcc78b419a1916b4/eng/build.ps1#L607-L609

**Comment by CyrusNajmabadi** [comment]
I don't repro this :)
