### ISSUE TITLE
FailFast in HostWorkspaceServicesExtensions.CreateContentTypeMap: An item with the same key has already been added

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#34987]
Observed in integration tests.

```
Event Time (UTC): 4/13/2019 1:38:38 AM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.HostWorkspaceServicesExtensions.CreateContentTypeMap(HostWorkspaceServices hostWorkspaceServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.HostWorkspaceServicesExtensions.GetDefaultContentTypeName(HostWorkspaceServices workspaceServices, String language)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.HostWorkspaceServicesExtensions.LanguageMatches(String language, IContentType contentType, HostWorkspaceServices workspaceServices)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.HostWorkspaceServicesExtensions.GetLanguageServices(HostWorkspaceServices workspaceServices, IContentType contentType)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__46.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionErrorHandler.HandleError(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1+<GetTagsForBuffer>d__46[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.InternalGetClassificationSpans(Microsoft.VisualStudio.Text.SnapshotSpan, System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Text.Tagging.IMappingTagSpan`1<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>>)
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierAggregator.GetClassificationSpans(Microsoft.VisualStudio.Text.SnapshotSpan)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.NormalizedSpanGenerator.CreateClassifiedRuns(Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Text.Classification.IAccurateClassifier, Microsoft.VisualStudio.Text.Classification.IClassificationFormatMap, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.NormalizedSpanGenerator.Create(Microsoft.VisualStudio.Text.Formatting.ITextAndAdornmentCollection, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.Classification.IAccurateClassifier, Microsoft.VisualStudio.Text.Classification.IClassificationFormatMap, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLineSource.FormatLineInVisualBuffer(Microsoft.VisualStudio.Text.ITextSnapshotLine, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.FormatSnapshotLine(Microsoft.VisualStudio.Text.ITextSnapshotLine, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView+LayoutLineCache.DoAnchorFormat(Microsoft.VisualStudio.Text.SnapshotPoint, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoAnchorLayout(LayoutDescription, Microsoft.VisualStudio.Text.SnapshotPoint, Double, Double, Microsoft.VisualStudio.Text.Editor.ViewRelativePosition, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.VisualStudio.Text.SnapshotPoint, Double, Microsoft.VisualStudio.Text.Editor.ViewRelativePosition, Double, Double, Boolean, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(Microsoft.VisualStudio.Text.Editor.IWpfTextView)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.<InitializeDifferenceViewer>b__40_0(Microsoft.VisualStudio.Text.Differencing.IDifferenceTextViewModel, Microsoft.VisualStudio.Text.Editor.ITextViewRoleSet, Microsoft.VisualStudio.Text.Editor.IEditorOptions, System.Windows.FrameworkElement ByRef, Microsoft.VisualStudio.Text.Editor.IWpfTextViewHost ByRef)
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.EnsureRightHost()
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.GetHostForViewMode(Microsoft.VisualStudio.Text.Differencing.DifferenceViewMode)
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.UpdateVisual()
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.Initialize(Microsoft.VisualStudio.Text.Differencing.IDifferenceBuffer, Microsoft.VisualStudio.Text.Differencing.CreateTextViewHostCallback, Microsoft.VisualStudio.Text.Editor.IEditorOptions)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.InitializeDifferenceViewer()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindowPane.<CreateView>b__33_0()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.PreOuterQueryStatus(System.Guid ByRef, UInt32, Microsoft.VisualStudio.OLE.Interop.OLECMD[])
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.QueryStatus(System.Guid ByRef, UInt32, Microsoft.VisualStudio.OLE.Interop.OLECMD[], IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.QueryStatus(System.Guid ByRef, UInt32, Microsoft.VisualStudio.OLE.Interop.OLECMD[], IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.QueryStatus(System.Guid ByRef, UInt32, Microsoft.VisualStudio.OLE.Interop.OLECMD[], IntPtr)
   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsTrackSelectionExPrivate.Register()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConnectSelectionContext()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Activate()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_ActiveViewChanged(System.Object, Microsoft.VisualStudio.PlatformUI.Shell.ActiveViewChangedEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.EventHandler`1<System.__Canon>, System.Object, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(Microsoft.VisualStudio.PlatformUI.Shell.View, Microsoft.VisualStudio.PlatformUI.Shell.ActivationType)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.ActivateViewFromTabControl(System.Windows.Controls.TabControl, Microsoft.VisualStudio.PlatformUI.Shell.ActivationType)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.OnTabControlSelectionChanged(System.Object, System.Windows.Controls.SelectionChangedEventArgs)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager+<>c.<.cctor>b__24_27(System.Object, System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.TabControl.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
   at Microsoft.VisualStudio.PlatformUI.LayoutSynchronizedTabControl.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(System.Collections.Generic.List`1<ItemInfo>, System.Collections.Generic.List`1<ItemInfo>)
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.SelectJustThisItem(ItemInfo, Boolean)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.InvalidateProperty(System.Windows.DependencyProperty, Boolean)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean)
   at System.Windows.Data.BindingExpression.TransferValue(System.Object, Boolean)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean, Boolean, Boolean)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32, System.ComponentModel.ICollectionView, System.Object, Boolean)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(System.Windows.DependencyObject, System.Windows.DependencyProperty, Boolean)
   at MS.Internal.Data.ClrBindingWorker.OnSourceInvalidation(System.Windows.DependencyObject, System.Windows.DependencyProperty, Boolean)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependentList.InvalidateDependents(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewElement.UpdateParentSelectedElement()
   at Microsoft.VisualStudio.PlatformUI.Shell.View.OnIsSelectedChanged()
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewElement.OnIsSelectedChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewElement.set_IsSelected(Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ShowInternal(ShowFlags)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<Show>b__506_0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Show()
   at Microsoft.VisualStudio.Platform.WindowManagement.DTE.Window.set_Visible(Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.DTE.WindowBase+<>c__DisplayClass69_0.<set_Visible>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<Boolean>)
   at Microsoft.VisualStudio.Platform.WindowManagement.DTE.WindowBase.set_Visible(Boolean)
   at Microsoft.VisualStudio.TemplateWizard.Wizard.OpenNotedItems(System.String, System.Collections.Generic.List`1<WizardExtension>, EnvDTE.Project)
   at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(System.Object, Int32, System.Object[] ByRef, System.Object[] ByRef, EnvDTE.wizardResult ByRef)
```

**Comment by sharwell** [comment]
This error was caused by #34945.

The pull request introduced [FSharpContentTypeLanguageService](https://github.com/dotnet/roslyn/blob/d4b17e6e662c733b0035294d3c8ec4f4f16c5dc7/src/Tools/ExternalAccess/FSharp/Editor/FSharpContentTypeLanguageService.cs) which resulted in two copies of this service in the MEF catalog.
