### ISSUE TITLE
Crash during lightbulb PreviewPane construction

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#3502]
Unfortunately all I have left is the stack. I was attached to VS & XDesProc and tried to show the lightbulb in the VS being debugged. I haven't been able to find a repro.

```
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Microsoft.VisualStudio.LanguageServices.Implementation.PreviewPane.PreviewPane.InitializeComponent()
   at Microsoft.VisualStudio.LanguageServices.Implementation.PreviewPane.PreviewPane..ctor(Image severityIcon, String id, String title, String description, Uri helpLink, String helpLinkToolTipText, Object previewContent, Boolean logIdVerbatimInTelemetry)
   at Microsoft.VisualStudio.LanguageServices.Implementation.PreviewPane.PreviewPaneService.Microsoft.CodeAnalysis.Editor.Host.IPreviewPaneService.GetPreviewPane(Diagnostic diagnostic, String language, String projectType, Object previewContent)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<GetPreviewAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by dpoeschl** [comment]
Analyzers team - have you seen or heard of this before?

**Comment by mavasani** [comment]
Probably @shyamnamboodiripad has the most context, but he is returning next week..

**Comment by Pilchie** [comment]
Follow up with @shyamnamboodiripad and then close?

**Comment by shyamnamboodiripad** [comment]
@dpoeschl I haven't heard of this before. I am not sure what the problem is but I think this has nothing to do with our code for the preview pane. Stack trace indicates that the problem is happening inside WPF in InitializeComponent() when its reading xaml so perhaps this is some WPF bug? What was the exception (anything interesting in the exception type / message)? It may be interesting to see if similar WPF stack trace shows up in other internal bug reports...
