### ISSUE TITLE
[Regression] Unloading a project/solution crashes Visual Studio if there is pending Roslyn work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#35360]
This was introduced in https://github.com/dotnet/roslyn/pull/34785.

Visual Studio is crashing on me if I close a Solution before Roslyn has finished analyzing the project for Designer attributes via DesignerAttributeIncrementalAnalyzer.

````
ObjectDisposedException
object name: 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.DisposingWrapper`1[[Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Designers.ProjectItemDesignerUpdateService+ProjectItemDesignerUpdateServiceImplementation, Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]'.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.DisposingWrapper`1.get_Value()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Designers.ProjectItemDesignerUpdateService.SetProjectItemDesignerTypeAsync(String projectItemPath, String designerType)
   at Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.DesignerAttributeIncrementalAnalyzer.<RegisterDesignerAttributeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.DesignerAttributeIncrementalAnalyzer.<RegisterDesignerAttributeAndSaveStateAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.DesignerAttributeIncrementalAnalyzer.<AnalyzeDocumentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass32_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__34`2.MoveNext()
````

**Comment by davkean** [comment]
This work should be tied to the lifetime of the project, and should be cancelled if the project is unloaded.

**Comment by davkean** [comment]
tag @heejaechang
