### ISSUE TITLE
VS 15.9.7 InvalidOperationException Unexpected Null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#35435]
Occured in VS 15.9.7

While typing in the IDE I got the follow error: ExtractMethodCodeRefactoringProvider encountered an error and has been disabled. Here is the stacktrace:

```
System.InvalidOperationException : Unexpected Null
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value,String message)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetCallSiteContainerFromExpression()
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.GetOutermostCallSiteContainerToProcess(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(&lt;Unknown Parameters&gt;)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/464228/vs-1597-invalidoperationexception-unexpected-null.html
VSTS ticketId: 796901_
_These are the original issue comments:_

Visual Studio Feedback System on 2/21/2019, 00:31 AM (69 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of prism hits.
