### ISSUE TITLE
make service hub log to include method that throw exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#35654]
right now, exception log such as this, make it very hard without dump, what call is exactly failing.

we should make this log better.

...

05/10/2019 17:03:52 : Error : 1 :exception: System.ArgumentException: Object serialized to Array. JObject instance expected.

   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)

   at StreamJsonRpc.JsonMessageFormatter.TokenizeUserData(JsonRpcMessage jsonRpcMessage)

   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)

   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer, JsonRpcMessage message)

   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content, CancellationToken cancellationToken)

   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken)

   at StreamJsonRpc.MessageHandlerBase.<WriteAsync>d__15.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()

   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__88`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcEx.<InvokeAsync>d__10.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at

**Comment by CyrusNajmabadi** [comment]
We already do this.
