### ISSUE TITLE
PublicAPI checker crashing.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#35670]
I'm running into this in the https://github.com/dotnet/roslyn/pull/32999 PR.

When i make a public API change and attempt to add the item to the the unshipped.txt file i run into: 

```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.<>c__DisplayClass8_0.<TryGetSingleChangedText>b__1(DocumentId id)
   at System.Linq.ImmutableArrayExtensions.Any[T](ImmutableArray`1 immutableArray,Func`2 predicate)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.TryGetSingleChangedText(Solution oldSolution,ImmutableArray`1 operationsList)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

**Comment by CyrusNajmabadi** [comment]
@sharwell Any ideas on this?

**Comment by sharwell** [comment]
This was fixed by #35300

**Comment by sharwell** [comment]
The workaround I've been using is applying a Fix All with preview, and then copying the text from the preview window and manually pasting it over the current content of the unshipped file.

**Comment by CyrusNajmabadi** [comment]
Thanks.  I'll try that!
