### ISSUE TITLE
Integration test CPSProject_GeneralPropertyGroupUpdated failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#35909]
https://dev.azure.com/dnceng/public/_build/results?buildId=197521&view=ms.vss-test-web.build-test-results-tab&runId=4796290&paneView=debug&resultId=100389

```
Assert.Contains() Failure\r\nNot found: (filter expression)\r\nIn value: WhereEnumerableIterator<XElement> [<PropertyGroup>\r\n <TargetFramework>netstandard2.0</TargetFramework>\r\n</PropertyGroup>]

Stack trace
   at Roslyn.VisualStudio.IntegrationTests.AbstractUpdateProjectTest.VerifyPropertyOutsideConfiguration(XElement projectElement, String name, String value) in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractUpdateProjectTest.cs:line 31
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpUpdateProjectToAllowUnsafe.CPSProject_GeneralPropertyGroupUpdated() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpUpdateProjectToAllowUnsafe.cs:line 44
Build 20190522.24 Failed

Showing filters 1 through 3
```

**Comment by sharwell** [comment]
@tmat Just waiting on reviews for #35907
