### ISSUE TITLE
NullReferenceException in CSharpDiagnosticAnalyzerApiUsageAnalyzer for open generic type

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#35941]
**Version Used**: microsoft.codeanalysis.analyzers - 2.6.2-beta2

**note**: this *beta* version of the meta-analyzers is still referred to in new releases of Roslyn. https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/ (look at the dependencies)

**Steps to Reproduce**:

1. Create an analyzer project
2. Paste in [this code](https://github.com/aspnet/AspNetCore/blob/6115c18f17737ee8e0f0680ea709b6149fe2322f/src/Components/Analyzers/src/ComponentSymbols.cs)
3. Do a build, or type in the file to run the meta-analyzers

**Expected Behavior**:

Does not crash

**Actual Behavior**:

```txt
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.AspNetCore.Components.Analyzers		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.AspNetCore.Components.Analyzers
ISymbol: ComponentSymbols (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.AddUsedNamedTypeCore(ITypeSymbol typeOpt, Builder builder, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.AddUsedNamedTypeCore(ITypeSymbol typeOpt, Builder builder, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.GetUsedNamedTypes(INamedTypeSymbol namedType, Compilation compilation, CancellationToken cancellationToken, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.<>c__DisplayClass11_0.<Initialize>b__1(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__40_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

The issue seems to be related to these lines of code:
```C#
var dictionary = compilation.GetTypeByMetadataName(typeof(Dictionary<,>).FullName);
            var @string = compilation.GetSpecialType(SpecialType.System_String);
            var @object = compilation.GetSpecialType(SpecialType.System_Object);
            if (dictionary == null || @string == null || @object == null)
            {
                symbols = null;
                return false;
            }

var parameterCaptureUnmatchedValuesRuntimeType = dictionary.Construct(@string, @object);
```

If I change this to use a simpler construct `compilation.GetTypeByMetadataName(typeof(Dictionary<string,object>).FullName)` - this takes aware the error (yes I'm aware this won't actually find the type).

**Comment by mavasani** [comment]
@rynowak This is a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1888#issuecomment-454969167. Can you try to explicitly reference analyzer package version 2.6.3 or higher?

FYI that once https://github.com/dotnet/roslyn/issues/32618 is addressed, the version of analyzer that comes with Microsoft.CodeAnalysis.nupkg should have this fix.

**Comment by rynowak** [comment]
Ok great thanks!

Are you planning to fix the package reference soon? That seems like an important thing to address and it's been around for a while.

**Comment by mavasani** [comment]
Yes, @sharwell has a PR to update it: https://github.com/dotnet/roslyn/pull/35439
