### ISSUE TITLE
BasicEditAndContinue.LocalsWindowUpdatesAfterLocalGetsItsTypeUpdatedDuringEnC Fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#35952]
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=200739&view=ms.vss-test-web.build-test-results-tab&runId=4873668&resultId=100245&paneView=debug) - Integration Debug Async Attempt #1

```
    Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicEditAndContinue.LocalsWindowUpdatesAfterLocalGetsItsTypeUpdatedDuringEnC [STARTING]
      System.Runtime.InteropServices.COMException : Unable to execute method at this time.
      Stack Trace:
        
        Server stack trace: 
           at EnvDTE.Debugger.SetNextStatement()
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.SetNextStatement()
           at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
           at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
        
        Exception rethrown at [0]: 
           at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
           at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
           at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.Debugger_InProc.SetNextStatement()
        /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/Debugger_OutOfProc.cs(40,0): at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.Debugger_OutOfProc.SetNextStatement()
        /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicEditAndContinue.cs(270,0): at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicEditAndContinue.LocalsWindowUpdatesAfterLocalGetsItsTypeUpdatedDuringEnC()
```

**Comment by ryzngard** [comment]
Seen again [here](https://dev.azure.com/dnceng/public/_build/results?buildId=291123&view=ms.vss-test-web.build-test-results-tab&runId=8217442&resultId=100003&paneView=debug)

**Comment by JoeRobich** [comment]
Unskipping this test is being tracked by https://github.com/dotnet/roslyn/issues/75456
