### ISSUE TITLE
Compiler crash when tuple equality used with a conversion-from-expression

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#35958]
The [following code causes the C# compiler to crash](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUA0QMwUBMZAwmQN4NkCKrKgDYKAFjIBZCGgB2ACgCU/QX3qDNFShwhkAvGQXKDAPl4BfJXQ1aBVAJzGISaUoOGFU1xCXXVAhYBZMGiEtImPEH00UA===):

``` c#
using System;

public class C {
    public static void Main()
    {
        Action a = (() => {});
        Console.WriteLine((a, M) == (M, a));
    }
    
    static void M() {}
}
```

the failure is

``` none
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundLocal' to type 'Microsoft.CodeAnalysis.CSharp.BoundMethodGroup'.
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeConversionNode(BoundConversion oldNode, SyntaxNode syntax, BoundExpression rewrittenOperand, Conversion conversion, Boolean checked, Boolean explicitCastInCode, ConstantValue constantValueOpt, TypeSymbol rewrittenType)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeConversionNode(SyntaxNode syntax, BoundExpression rewrittenOperand, Conversion conversion, TypeSymbol rewrittenType, Boolean checked, Boolean explicitCastInCode, ConstantValue constantValueOpt)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleSingleOperator(Single single, BoundExpression left, BoundExpression right, TypeSymbol boolType, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleOperator(TupleBinaryOperatorInfo operator, BoundExpression left, BoundExpression right, TypeSymbol boolType, ArrayBuilder`1 temps, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteNonNullableNestedTupleOperators(Multiple operators, BoundExpression left, BoundExpression right, TypeSymbol type, ArrayBuilder`1 temps, ArrayBuilder`1 effects, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleNestedOperators(Multiple operators, BoundExpression left, BoundExpression right, TypeSymbol boolType, ArrayBuilder`1 temps, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitTupleBinaryOperator(BoundTupleBinaryOperator node)
   at Microsoft.CodeAnalysis.CSharp.BoundTupleBinaryOperator.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteExpressionStatement(BoundExpressionStatement node, Boolean suppressInstrumentation)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, Boolean instrumentForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawLocalFunctions, Boolean& sawAwaitInExceptionHandler)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
```

I believe the root cause is that the design of the tuple equality operator requires deferring the tuple element conversions.  But conversions that are *conversion-from-expression*s should not be deferred.

/cc @jcouv

**Comment by gafter** [comment]
Here is another example:

``` c#
using System;

public class C {
    public static void Main()
    {
        K k = null;
        Console.WriteLine((k, 1) == (M, 1));
    }
    
    static void M() {}
}

class K
{
    public static bool operator ==(K k, System.Action a) => true;
    public static bool operator !=(K k, System.Action a) => false;
}
```

**Comment by gafter** [comment]
Here is another example:

``` c#
using System;

public class C {
    public static void Main()
    {
        K k = null;
        Console.WriteLine((k, 1) == ($"", 1));
    }
    
    static void M() {}
}

class K
{
    public static bool operator ==(K k, IFormattable a) => true;
    public static bool operator !=(K k, IFormattable a) => false;
}
```
