### ISSUE TITLE
NRE in GetAssemblyReferenceAlias on VS2015 RC

### ISSUE THREAD

**Issue by redknightlois** [dotnet/roslyn#3616]
I was trying to compile the RavenDB source code on VS2015 RC and the Raven.Tests.Bundles project failed with:

```
1>  Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
1>     at Microsoft.Cci.PdbWriter.GetAssemblyReferenceAlias(IAssemblyReference assembly, HashSet`1 declaredExternAliases)
1>     at Microsoft.Cci.PdbWriter.TryEncodeImport(UsedNamespaceOrType import, HashSet`1 declaredExternAliasesOpt, Boolean isProjectLevel)
1>     at Microsoft.Cci.PdbWriter.DefineNamespaceScopes(IMethodBody methodBody)
1>     at Microsoft.Cci.PdbWriter.SerializeDebugInfo(IMethodBody methodBody, UInt32 localSignatureToken, CustomDebugInfoWriter customDebugInfoWriter)
1>     at Microsoft.Cci.MetadataWriter.SerializeMethodBodies(BinaryWriter writer, PdbWriter pdbWriterOpt)
1>     at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(PdbWriter pdbWriterOpt, BinaryWriter metadataWriter, BinaryWriter ilWriter, BinaryWriter mappedFieldDataWriter, BinaryWriter managedResourceDataWriter, Func`2 calculateMethodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, UInt32& moduleVersionIdOffsetInMetadataStream, UInt32& entryPointToken, MetadataSizes& metadataSizes)
1>     at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, PdbWriter nativePdbWriterOpt, UInt32& entryPointToken)
1>     at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, PdbWriter nativePdbWriterOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, PdbOutputInfo pdbOutputInfo, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, PdbOutputInfo pdbOutputInfo, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args)
1>     at Microsoft.CodeAnalysis.BuildTasks.BuildClient.RunWithConsoleOutput(String[] args, RequestLanguage language, Func`2 fallbackCompiler)
1>     at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
1>     at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc2.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(384,9): error MSB6006: "csc2.exe" exited with code -1073741819
```
You can download the source code for repro from: https://github.com/ayende/ravendb

**Comment by VSadov** [comment]
What project in particular causes this?
I am so far unable to reproduce the crash with the most recent bits. Perhaps the issue has been fixed, but I want to be sure.

**Comment by redknightlois** [comment]
Raven.Tests.Bundles. Is there any way to try the latest bits in order to repro here?

**Comment by jaredpar** [comment]
I just tested this out against Visual Studio 2015 RTM and the current master branch of RavenDB.  I was able to build the entire solution without errors.  There were a number of late bug fixes to this particular area of the compiler.  It seems that one of them fixed this issue.
