### ISSUE TITLE
Auto-Restore sometimes causes invisible unhandled exception in SDK-style projects

### ISSUE THREAD

**Issue by donnie-msft** [dotnet/roslyn#36180]
## Details about Problem
Sometimes when opening an SDK-style project, while loading into VS, an unhandled exception occurs during the NuGet auto-restore (seemingly caused by a race condition with the project loading). It is not visible to the user, but shows up while debugging the Experimental VS and opening an SDK project. Concern is whether this could cause a future hard-to-find bug during auto-restore, and perhaps work is happening on the Project before project loading is complete.

An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
System.InvalidOperationException: 'The operation failed as details for project ConsoleApp7 could not be loaded.'
at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context) in C:\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Projects\NetCorePackageReferenceProject.cs:line 144
at NuGet.VisualStudio.VsPackageInstallerServices.d__8.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Implementation\Extensibility\VsPackageInstallerServices.cs:line 116
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass10_0.<<GetInstalledPackages>b__0>d.MoveNext() in C:\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Implementation\Extensibility\VsPackageInstallerServices.cs:line 193 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions) at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod)
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project) in C:\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Implementation\Extensibility\VsPackageInstallerServices.cs:line 166
at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)

## Detailed repro steps so we can see the same problem
Repro for both @donnie-msft (on VS 16.2.0 prev3) and @dominoFire, but is inconsistent, and may take a few attempts.:

1. Launch experimental VS.

2. Ensure Exception Handling settings will break on any unhandled exception.

3. Open an SDK-style solution (preferably new and un-compiled which seems to more consistently repro).

4. If the race condition occurs, then the Restore will cause the above exception while the solution is loading and restoring.

**Comment by CyrusNajmabadi** [comment]
This is not in roslyn.  Closing out.
