### ISSUE TITLE
Hit NRE in completion (GetDescriptionAsync)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#36381]
**Version Used**: 

Version 16.2.0 Preview 2.0 [28930.63.d16.2stg]

**Steps to Reproduce**:

I don't have repro steps, just saw an NRE reported in goldbar with the following exception stack in activity log:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.<GetDescriptionAsync>d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.<GetDescriptionAsync>d__23.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__35`1.MoveNext() ---
 End of stack trace from previous location where exception was thrown ---
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mavasani** [comment]
Tag @ivanbasov

**Comment by ivanbasov** [comment]
Thank you, @mavasani !
The callstack leads to the completionprovider which is shared between async and the original completion. Therefore, I'd remove 'async' from the issue title.

**Comment by ivanbasov** [comment]
@mavasani , if this happened with a script/test scenario, can we get the description of the test scenario?

Was any extension involved? e.g. TS or F#?

**Comment by mavasani** [comment]
Nope just while typing code inside Roslyn.sln and attempting to invoke completion.

**Comment by ivanbasov** [comment]
@mavasani , any specific code you can remember? e.g. C# vs VB, enum, namespace, attribute, etc?
