### ISSUE TITLE
ArgumentOutOfRangeException from Analyzers

### ISSUE THREAD

**Issue by jnyrup** [dotnet/roslyn#36400]
**Version Used**: 
Visual Studio Professional 2019 16.1.3

**Steps to Reproduce**:

I was replacing `\n` line endings with `\r\n` in some code when this happened.

**Expected Behavior**:
No exception should occur.

**Actual Behavior**:
```
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetAdjustedSpan(SourceText text,TextSpan textSpan)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetInitialSelectionInfo(SyntaxNode root,SourceText text,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetValidSelectionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Maybe related to #28983?

**Comment by CyrusNajmabadi** [comment]
Closingg out as we rewrote this area.
