### ISSUE TITLE
CSharpSemanticModel.ToLanguageSpecific throws ArgumentException

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#36702]
**Version Used**: VS 16.2 Preview 4 (29021.251.d16.2stg)

**Steps to Reproduce**:

1. Create a new C# console application (.NET Core or .NET Framework)
2. In the main method, type these characters individually (do not copy-paste): `var ts = new TraceSource("hi") {  Switch = { ` (trailing space should follow the open curly brace)

**Expected Behavior**:

Auto-completion assists in writing out the nested initializers by offering property names.

**Actual Behavior**:

Roslyn promptly throws an exception and offers no completion within the nested initializers. VS shows the exception as an infobar across the top, with an offer to view the log. 

![image](https://user-images.githubusercontent.com/3548/60021624-94877980-964f-11e9-9f87-574e80f78e2a.png)

Looking at the log file reveals the following callstack:

```
System.ArgumentException: Not a C# symbol.
Parameter name: container
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.ToLanguageSpecific(INamespaceOrTypeSymbol container)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbolsCore(Int32 position, INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractObjectInitializerCompletionProvider.<ProvideCompletionsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.<GetCompletionContextAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Even when I use copy-paste or edit an existing code block with a nested initializer like this to avoid the exception infobar being displayed, I still get no completion assist within this syntax.

**Comment by jcouv** [comment]
The code that throws this exception is very straightforward (copied below). From quick debugging, I see that the `container` parameter receives an instance of `Microsoft.CodeAnalysis.NullableExtensions.NamedTypeSymbolWithNullableAnnotation` which causes the problem.
Tagging @jasonmalinowski @333fred as FYI and flagging the issue as area-IDE.

```C#

        private static NamespaceOrTypeSymbol ToLanguageSpecific(INamespaceOrTypeSymbol container)
        {
            if ((object)container == null)
            {
                return null;
            }

            if (!(container is NamespaceOrTypeSymbol namespaceOrTypeSymbol))
            {
                throw new ArgumentException(CSharpResources.NotACSharpSymbol, nameof(container));
            }

            return namespaceOrTypeSymbol;
        }
```
