### ISSUE TITLE
Completion crashes (fault) if more than instance of Roslyn completion service (different languages) are attached to the single completion session

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#37087]
from activity.log

```
Exception from ActivityLog.xml:

System.ArgumentException: An entry with the same key already exists.
   at System.Collections.Specialized.ListDictionary.Add(Object key, Object value)
   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.&lt;GetCompletionContextAsync&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.&lt;CallExtensionPointAsync&gt;d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ivanbasov** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/36936

**Comment by genlu** [comment]
Fixed by #36395

**Comment by genlu** [comment]
Actually, this is fixed by #36146

**Comment by ivanbasov** [comment]
@genlu should we resolve the GitHub issue?

**Comment by genlu** [comment]
Will close this once #36146 is merged, which is pending approval for preview 2
