### ISSUE TITLE
Regression in DocumentEditor

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#37226]
Here is the most minimal repro I could make:

```cs
[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(SwapFix))]
public class SwapFix : CodeFixProvider
{
    public override ImmutableArray<string> FixableDiagnosticIds { get; } = ImmutableArray.Create(
        "CS0246");

    public override async Task RegisterCodeFixesAsync(CodeFixContext context)
    {
        var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);

        foreach (var diagnostic in context.Diagnostics)
        {
            if (root.FindNode(diagnostic.Location.SourceSpan) is SyntaxNode node &&
                node.FirstAncestorOrSelf<ParameterListSyntax>() is ParameterListSyntax list &&
                list.Parameters.Count == 2)
            {
                context.RegisterCodeFix(
                    CodeAction.Create(
                        $"Swap parameters.",
                        FixAsync,
                        nameof(SwapFix)),
                    diagnostic);

                async Task<Document> FixAsync(CancellationToken cancellationToken)
                {
                    var editor = await DocumentEditor.CreateAsync(context.Document, cancellationToken)
                                                     .ConfigureAwait(false);
                    editor.ReplaceNode(list.Parameters[0], list.Parameters[1]);
                    editor.ReplaceNode(list.Parameters[1], list.Parameters[0]);
                    return editor.GetChangedDocument();
                }
            }
        }
    }
}
```

Run it on:
```cs
namespace N
{
    class C
    {
        void M(StringBuilder x, int y) { }
    }
}
```

It works in 2.3.1 but latest version gives:
```
System.InvalidOperationException : Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root, SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at Microsoft.CodeAnalysis.Editing.DocumentEditor.GetChangedDocument()
```

**Comment by CyrusNajmabadi** [comment]
This regressed in https://github.com/dotnet/roslyn/pull/31558.  Tagging @mavasani

**Comment by CyrusNajmabadi** [comment]
@mavasani the problem here is that because you are now tracking the new node, you may be tracking the same node multiple times.  In @JohanLarsson's example `int y` is now tracked twice.  Once because it's the old-node that will be replaced with `StringBuilder x` and once because it is now the `new node` that `StringBuilder x` is replaced with.

When GetChangedDocment is called it then eventually calls `var current = root.GetCurrentNode(this.Node);` on `int y` which crashes because it actually is in there twice.

Note: this has hit several customers including @paul1956 and @JohanLarsson .  Also tagging @jinujoseph .

**Comment by CyrusNajmabadi** [comment]
@JohanLarsson Thanks for the simple repro!

**Comment by mavasani** [comment]
I believe this is a tricky API question. Let us consider @JohanLarsson's transformation code: 

```csharp
var editor = await DocumentEditor.CreateAsync(context.Document, cancellationToken) .ConfigureAwait(false);
editor.ReplaceNode(list.Parameters[0], list.Parameters[1]);
editor.ReplaceNode(list.Parameters[1], list.Parameters[0]);
return editor.GetChangedDocument();
```

As @CyrusNajmabadi clarified above, after the first `ReplaceNode` invocation, there are 2 copies of `list.Parameters[1]` being tracked, as with https://github.com/dotnet/roslyn/pull/31558 we now track both the old nodes in the original tree and new node(s) being supplied to Replace or Insert invocations, with the assumption that users may want to further perform editor operations on either the nodes in original tree or newly added nodes.

We can change the logic for the API to track new nodes _only if_ they are not part of the original tree. However, that breaks a code transformation for slightly tweaked version of above code, where the user _does intend_ that both the old and new nodes get tracked automatically so they can later do a `ReplaceNodes` invocation to work on all the tracked nodes in latest tree (old and new):

```csharp
var editor = await DocumentEditor.CreateAsync(context.Document, cancellationToken) .ConfigureAwait(false);
var param1Type = list.Parameters[0].Type;
editor.ReplaceNode(list.Parameters[1].Type, param1Type); // Change 'param2' to have the same type node as 'param1'
// ... Some other code transformations
editor.ReplaceNodes(param1Type, editor.Generator.TypeExpression(SpecialType.System_Boolean)); // Change all nodes that have 'param1Type' to be boolean now.
return editor.GetChangedDocument();
```

We also have couple other options here:
1. Add an optional flag or new overloads to Replace/Insert APIs on the syntax editor to perform these operations without tracking the new nodes.
2. Call out the new API behavior as the only supported semantics for the API, and the clients that intend the non-tracking behavior for new nodes should just clone the node and pass it in. So for @JohanLarsson's example, he would have to replace the first ReplaceNode invocation with `editor.ReplaceNode(list.Parameters[0], editor.Generator.ParameterDeclaration(... /* derive arguments from list.Parameters[1] */);`

Any thoughts? Also tagging @dotnet/roslyn-analysis and marking this as needs design review so it is discussed at the design meeting.

**Comment by mavasani** [comment]
Meant to tag @dotnet/roslyn-ide for thoughts..

**Comment by paul1956** [comment]
I would be nice if it worked the way it did in used to work, I have tried to use @JohanLarsson fix and for me it did not fix the issue because I think I use the "slightly tweaked version". If you want to change the API the information on what I need to fix needs to be a lot clearer. I have 22 code fixes using Document Editor and only 3 that broke with the API change and are still broke with John's fix. As a temporary "fix" throwing an error with what I did wrong, instead if just showing a blank Preview Window would be preferred.

**Comment by mavasani** [comment]
@paul1956 Can you share your code for the code action?

**Comment by JohanLarsson** [comment]
@paul1956 out of curiosity, what fix do you mean? The \~fix\~ in the original post is just the minimal self contained repro I could think of for showing the regression.

**Comment by paul1956** [comment]
@JohanLarsson you had a workaround that you posted that did not work for me. @mavasani  The Lambda one works correct the other 3 fail but if you look at _Document returned in every case it is correct.
```VB
Option Explicit On
Option Infer Off
Option Strict On

Imports System.Collections.Immutable

Namespace Style

    <ExportCodeRefactoringProvider(LanguageNames.VisualBasic, Name:=NameOf(AddAsClauseRefactoringProvider)), [Shared]>
    Public Class AddAsClauseRefactoringProvider
        Inherits CodeRefactoringProvider

        Private Const Title As String = "Add As Clause refactoring"

        Private ReadOnly Property FixableDiagnosticIds As ImmutableArray(Of String) = ImmutableArray.Create(
            DiagnosticIds.AddAsClauseDiagnosticId,
            DiagnosticIds.AddAsClauseForLambdaDiagnosticId,
            DiagnosticIds.ERR_NameNotDeclared1DiagnosticId,
            DiagnosticIds.ERR_StrictDisallowImplicitObjectDiagnosticId,
            DiagnosticIds.ERR_StrictDisallowsImplicitProcDiagnosticId,
            DiagnosticIds.ERR_EnumNotExpression1DiagnosticId,
            DiagnosticIds.ERR_TypeNotExpression1DiagnosticId,
            DiagnosticIds.ERR_ClassNotExpression1DiagnosticId,
            DiagnosticIds.ERR_StructureNotExpression1DiagnosticId,
            DiagnosticIds.ERR_InterfaceNotExpression1DiagnosticId,
            DiagnosticIds.ERR_NamespaceNotExpression1DiagnosticId
            )

        Public NotOverridable Overrides Async Function ComputeRefactoringsAsync(context As CodeRefactoringContext) As Task
            Dim span As TextSpan = context.Span
            If Not span.IsEmpty Then
                Return
            End If
            Dim _Document As Document = context.Document
            Dim root As SyntaxNode = Await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(False)
            Dim model As SemanticModel = Await _Document.GetSemanticModelAsync(Nothing)
            ' Don't offer this refactoring if Option Explicit because the CodeFix provider will handle it
            If model.OptionStrict = OptionStrict.On AndAlso model.OptionInfer = True Then Return
            ' Find the node at the selection.

            For Each DiagnosticEntry As Diagnostic In model.GetDiagnostics(context.Span)
                ' Does Diagnostic contain any of the errors I care about?
                If Me.FixableDiagnosticIds.Any(Function(m As String) m.ToString = DiagnosticEntry.Id.ToString) Then
                    Continue For
                End If
                Return
            Next

            Dim _VariableDeclarator As VariableDeclaratorSyntax = root.FindNode(context.Span, getInnermostNodeForTie:=True)?.FirstAncestorOrSelf(Of VariableDeclaratorSyntax)()
            If _VariableDeclarator IsNot Nothing Then
                ' only for a local declaration node
                If _VariableDeclarator.Names.Count > 1 Then
                    Return
                End If
                If _VariableDeclarator.AsClause IsNot Nothing Then
                    Return
                End If
                If _VariableDeclarator.Initializer Is Nothing Then
                    Return
                End If
                context.RegisterRefactoring(CodeAction.Create(Title, Function(c As CancellationToken) AddAsClauseAsync(_Document, _VariableDeclarator, c)))
                Exit Function
            End If
            Dim ForStatement As ForStatementSyntax = root.FindNode(context.Span, getInnermostNodeForTie:=True)?.FirstAncestorOrSelf(Of ForStatementSyntax)()
            If ForStatement IsNot Nothing Then
                Dim ControlVariable As VisualBasicSyntaxNode = ForStatement.ControlVariable
                If ControlVariable Is Nothing Then Return

                Dim ControlVariableName As IdentifierNameSyntax = TryCast(ControlVariable, IdentifierNameSyntax)
                If ControlVariableName?.Kind = SyntaxKind.IdentifierName Then
                    context.RegisterRefactoring(CodeAction.Create(Title, Function(c As CancellationToken) AddAsClauseAsync(_Document, ForStatement, c)))
                End If
                Exit Function
            End If
            Dim ForEachStatement As ForEachStatementSyntax = root.FindNode(context.Span, getInnermostNodeForTie:=True)?.FirstAncestorOrSelf(Of ForEachStatementSyntax)()
            If ForEachStatement Is Nothing Then
                Return
            End If

            Dim ForEachControlVariable As VisualBasicSyntaxNode = ForEachStatement.ControlVariable
            If ForEachControlVariable Is Nothing Then Return
            Dim IdentifierName As IdentifierNameSyntax = TryCast(ForEachControlVariable, IdentifierNameSyntax)
            If IdentifierName?.Kind = SyntaxKind.IdentifierName Then
                context.RegisterRefactoring(CodeAction.Create(Title, Function(c As CancellationToken) AddAsClauseAsync(_Document, ForEachStatement, c)))
            End If
        End Function
    End Class
End Namespace
        Public Async Function AddAsClauseAsync(_Document As Document, lVariableDeclarator As VariableDeclaratorSyntax, _CancellationToken As CancellationToken) As Task(Of Document)
            If Not IsEnoughMemoryReport(MemoryLimit) Then
                Return _Document
            End If
            Try
                Dim root As SyntaxNode = Await _Document.GetSyntaxRootAsync(_CancellationToken)
                Dim variableDeclaratorSyntax1 As VariableDeclaratorSyntax
                Dim Model As SemanticModel = Await _Document.GetSemanticModelAsync(_CancellationToken)
                Dim Expression As ExpressionSyntax = lVariableDeclarator.Initializer.Value
                Dim variableITypeSymbol As (_ITypeSymbol As ITypeSymbol, _Error As Boolean) = Expression.DetermineType(Model, _CancellationToken)
                If variableITypeSymbol._Error Then
                    Return _Document
                End If
                If variableITypeSymbol.ToString.Contains(" ?)") Then
                    Return _Document
                End If
                variableDeclaratorSyntax1 = GetNewInvocation(lVariableDeclarator, Model, variableITypeSymbol._ITypeSymbol, _CancellationToken).WithTriviaFrom(lVariableDeclarator)

                If variableDeclaratorSyntax1 Is Nothing OrElse variableDeclaratorSyntax1.Equals(lVariableDeclarator) Then
                    Return _Document
                End If
                Dim _DocumentEditor As DocumentEditor = Await DocumentEditor.CreateAsync(_Document)
                _DocumentEditor.ReplaceNode(lVariableDeclarator, variableDeclaratorSyntax1.WithTriviaFrom(lVariableDeclarator).WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation))
                Return _DocumentEditor.GetChangedDocument()
            Catch ex As Exception When ex.HResult <> (New OperationCanceledException).HResult
                Stop
            End Try
            Return _Document
        End Function

        Public Async Function AddAsClauseAsync(_Document As Document, lLambdaEHeaderSyntax As LambdaHeaderSyntax, _CancellationToken As CancellationToken) As Task(Of Document)
            If Not IsEnoughMemoryReport(MemoryLimit) Then
                Return _Document
            End If
            Try
                Dim lLabdaExpression As LambdaExpressionSyntax = lLambdaEHeaderSyntax.FirstAncestorOfType(Of LambdaExpressionSyntax)
                If lLabdaExpression Is Nothing Then
                    Exit Try
                End If
                Dim NewParameters As SeparatedSyntaxList(Of ParameterSyntax)
                Dim Model As SemanticModel = Await _Document.GetSemanticModelAsync(_CancellationToken)
                Dim sometype As ITypeSymbol = lLabdaExpression.DetermineType(Model, _CancellationToken)._ITypeSymbol
                Dim Types As List(Of TypeSyntax) = GetTypes(sometype)
                If Types.Count = 0 Then
                    Return _Document
                End If

                Dim Parameters As SeparatedSyntaxList(Of ParameterSyntax) = lLabdaExpression.SubOrFunctionHeader.ParameterList.Parameters

                If Parameters.Count = 0 Then
                    Exit Try
                End If
                Dim i As Integer = 0
                For Each param As ParameterSyntax In Parameters
                    Dim NewSimpleAsClause As SimpleAsClauseSyntax = SimpleAsClause(
                                        Token(SyntaxKind.AsKeyword),
                                        New SyntaxList(Of AttributeListSyntax),
                                        Types(i).WithLeadingTrivia(Space).WithAdditionalAnnotations(Simplifier.Annotation))
                    NewParameters = NewParameters.Add(param.WithTrailingTrivia(Space).WithAsClause(NewSimpleAsClause))
                    i += 1
                Next

                If NewParameters.Count <> lLambdaEHeaderSyntax.ParameterList.Parameters.Count Then
                    Return _Document
                End If
                Dim _DocumentEditor As DocumentEditor = Await DocumentEditor.CreateAsync(_Document)
                _DocumentEditor.ReplaceNode(lLambdaEHeaderSyntax.ParameterList, ParameterList(NewParameters).WithTriviaFrom(lLambdaEHeaderSyntax.ParameterList).WithAdditionalAnnotations(Simplifier.Annotation))
                Return _DocumentEditor.GetChangedDocument()
            Catch ex As Exception When ex.HResult <> (New OperationCanceledException).HResult
                Stop
            End Try
            Return _Document
        End Function

        Public Async Function AddAsClauseAsync(_Document As Document, ForStatement As ForStatementSyntax, _CancellationToken As CancellationToken) As Task(Of Document)
            If Not IsEnoughMemoryReport(MemoryLimit) Then
                Return _Document
            End If
            Try

                Dim fromValue As ExpressionSyntax = ForStatement.FromValue
                Dim Model As SemanticModel = Await _Document.GetSemanticModelAsync(_CancellationToken)
                Dim variableITypeSymbol As (_ITypeSymbol As ITypeSymbol, _Error As Boolean) = fromValue.DetermineType(Model, _CancellationToken)
                If variableITypeSymbol._Error Then
                    Return _Document
                End If

                Dim AsClause As AsClauseSyntax = GetAsClause(True, fromValue, Model, variableITypeSymbol._ITypeSymbol, _CancellationToken)
                If AsClause Is Nothing Then
                    Return _Document
                End If
                Dim oldControlVariable As VisualBasicSyntaxNode = ForStatement.ControlVariable
                If oldControlVariable Is Nothing Then
                    Return _Document
                End If
                Dim newControlVariable As VariableDeclaratorSyntax = Nothing
                If TypeOf oldControlVariable Is IdentifierNameSyntax Then
                    newControlVariable = VariableDeclarator(SingletonSeparatedList(
                                                                ModifiedIdentifier(DirectCast(oldControlVariable, IdentifierNameSyntax).Identifier)),
                                                                AsClause,
                                                                initializer:=Nothing
                                                                ).
                                                                WithTriviaFrom(oldControlVariable).WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation)
                ElseIf TypeOf oldControlVariable Is VariableDeclaratorSyntax Then
                    Dim oldControlVariable1 As VariableDeclaratorSyntax = DirectCast(oldControlVariable, VariableDeclaratorSyntax)
                    If oldControlVariable1.Names.Count <> 1 Then
                        Return _Document
                    End If
                    newControlVariable = VariableDeclarator(SingletonSeparatedList(
                                                                oldControlVariable1.Names(0)),
                                                                AsClause,
                                                                initializer:=Nothing
                                                                ).
                                                                WithTriviaFrom(oldControlVariable).WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation)
                End If
                Dim _DocumentEditor As DocumentEditor = Await DocumentEditor.CreateAsync(_Document)
                _DocumentEditor.ReplaceNode(ForStatement.ControlVariable, newControlVariable.WithTriviaFrom(ForStatement.ControlVariable))
                Return _DocumentEditor.GetChangedDocument()
            Catch ex As Exception When ex.HResult <> (New OperationCanceledException).HResult
                Stop
            End Try
            Return _Document
        End Function

        Public Async Function AddAsClauseAsync(_Document As Document, _ForEachStatement As ForEachStatementSyntax, _CancellationToken As CancellationToken) As Task(Of Document)
            If Not IsEnoughMemoryReport(MemoryLimit) Then
                Return _Document
            End If
            Try
                Dim root As SyntaxNode = Await _Document.GetSyntaxRootAsync(_CancellationToken)
                Dim oldControlVariable As VisualBasicSyntaxNode = _ForEachStatement.ControlVariable
                If oldControlVariable Is Nothing Then
                    Return _Document
                End If

                Dim Model As SemanticModel = Await _Document.GetSemanticModelAsync(_CancellationToken)
                Dim AsClause As AsClauseSyntax = GetAsClause(_ForEachStatement, Model, _CancellationToken)
                If AsClause Is Nothing Then
                    Return _Document
                End If
                Dim newControlVariable As VariableDeclaratorSyntax = Nothing
                If TypeOf oldControlVariable Is IdentifierNameSyntax Then
                    newControlVariable = VariableDeclarator(SingletonSeparatedList(
                                                                ModifiedIdentifier(DirectCast(oldControlVariable, IdentifierNameSyntax).Identifier)),
                                                                AsClause,
                                                                initializer:=Nothing
                                                                ).
                                                                WithTriviaFrom(oldControlVariable).WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation)
                ElseIf TypeOf oldControlVariable Is VariableDeclaratorSyntax Then
                    Dim oldControlVariable1 As VariableDeclaratorSyntax = DirectCast(oldControlVariable, VariableDeclaratorSyntax)
                    If oldControlVariable1.Names.Count <> 1 Then
                        Return _Document
                    End If
                    newControlVariable = VariableDeclarator(SingletonSeparatedList(
                                                                oldControlVariable1.Names(0)),
                                                                AsClause,
                                                                initializer:=Nothing
                                                                ).
                                                                WithTriviaFrom(oldControlVariable).WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation)
                End If
                If newControlVariable Is Nothing Then
                    Return _Document
                End If
                Dim _DocumentEditor As DocumentEditor = Await DocumentEditor.CreateAsync(_Document)
                _DocumentEditor.ReplaceNode(oldControlVariable, newControlVariable)
                Return _DocumentEditor.GetChangedDocument()
            Catch ex As Exception When ex.HResult <> (New OperationCanceledException).HResult
                Stop
            End Try
            Return _Document
        End Function
```

**Comment by CyrusNajmabadi** [comment]
@paul1956 can you trim that down to a simpler repro?

**Comment by paul1956** [comment]
@CyrusNajmabadi so far I have not been able too, I will try again tonight.

**Comment by paul1956** [comment]
@CyrusNajmabadi  https://github.com/paul1956/Analyzer1 is the smallest repo that I could create easily. There are 23 Tests, 13 pass and 10 fail. VerifyFixAddAsClauseToDim is the simplest one that fails. They all fail in ApplyFix.

**Comment by mavasani** [comment]
@paul1956 I debugged your repro test `VerifyFixAddAsClauseToDim` and your case seems to be unrelated to this issue. The changed document from DocumentEditor does indeed have the correct replaced node and text, but there might likely be some other issue downstream

![image](https://user-images.githubusercontent.com/10605811/63557802-09b3e580-c4ff-11e9-8293-76337d312529.png)

**Comment by paul1956** [comment]
@mavasani that's for looking, after that line the code enters Roslyn in the VSIX and when I tracked it the original Solution is Null. when the code fails and not Null when everything works. Any ideas what is wrong and what I can do to fix this or what bug I need to report if this is not it.

**Comment by paul1956** [comment]
@mavasani thanks for looking, after that line the code enters Roslyn in the VSIX and when I tracked it the original Solution is Null. when the code fails and not Null when everything works. Any ideas what is wrong and what I can do to fix this or what bug I need to report if this is not it.

**Comment by sharwell** [comment]
Design review conclusion: Despite a change in behavior which caused some analyzers to break, we believe the new behavior is more flexible and supports more scenarios which we would like to continue supporting. There are two ways to work around this issue which should work with all versions of Roslyn:

1. Perform the code fix by removing the first parameter, and then adding the parameter at a new location
2. Alternately, it should be possible to correct this by cloning the syntax node before trying to copy it from one location in the tree to another

@mavasani should be able to provide more specific examples of these two workarounds if needed.
