### ISSUE TITLE
Remove unused parameters analyzer threw InvalidOperationException

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn#37273]
**Version Used**: Visual Studio 2019 version 16.1.6

**Steps to Reproduce**:

1. I had some C# code like the following:

    ```csharp
    public class Class1
    {
        public int GetNum(int arg1) { return 1; }
        int GetNum3(int arg1) { return 1; }
    }
    ````

2. Add an .EditorConfig file to the project.
3. Add the following line to the EditorConfig file:

    `dotnet_code_quality_unused_parameters = nonpublic:suggestion`

**Expected Behavior**:

No exception

**Actual Behavior**:

An exception appeared in the Error List as an AD0001 warning as follows:

'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Conventions
ISymbol: GetNum (Method)

System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.ShouldReportUnusedParameters(ISymbol symbol, UnusedParametersPreference unusedParametersPreference, ReportDiagnostic unusedParametersSeverity)
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.AnalyzeOperationBlockEnd(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`2.<ExecuteBlockActions>b__55_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

**Comment by mavasani** [comment]
This was also just reported on vsfeedback: https://github.com/dotnet/roslyn/issues/37326 and I am about to send a PR out to fix it.
