### ISSUE TITLE
System.ArgumentException: Not a C# symbol.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37333]
**VS2019 16.2.0 Preview 3.0**

I have this simple method;

```
public static T NullObjectRetry&lt;T&gt;(Func&lt;T&gt; funcToRun)
{
    var returnVal = funcToRun();

for (var i = 0; i &lt; 10; i++)
    {
        if (returnVal == null)
        {
            Console.WriteLine(&quot;Retrying &quot; + (i + 1) + &quot; - &quot; + (i + 1) * 1000 + &quot; seconds&quot;);
            Thread.Sleep((i + 1) * 1000);
        }
        else
        {
            break;
        }

returnVal = funcToRun();
    }

return returnVal;
}
```

Every time I try to use this method writing something like the below;

```
bool isValueTrue = TestUtils.NullObjectRetry(() =&gt;
{
    if (fakeClass.GetBool() == false) return null;
    return true;
});
```

The second I begin to right a &quot;return&quot; statement within the function my VS just freezes and reboots; Looking at the event viewer there is an error saying;

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Not a C# symbol.
Parameter name: typeArguments
```

and an application error saying;

```
Faulting application name: devenv.exe, version: 16.2.29021.104, time stamp: 0x5d0d2e76
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80131623
Fault offset: 0x286a3212
Faulting process id: 0x5a0c
Faulting application start time: 0x01d53c242a0d7616
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: da99e1ae-fb52-4517-bff9-45eeab6c14e0
Faulting package full name: 
Faulting package-relative application ID: 
```

I've attached to full stack trace.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/648587/systemargumentexception-not-a-c-symbol.html
VSTS ticketId: 948096_
_These are the original issue comments:_

Visual Studio Feedback System on 7/17/2019, 01:46 AM (34 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by sharwell** [comment]
```
Event Time (UTC): 16/07/2019 10:41:07 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Not a C# symbol.

Parameter name: typeArguments

   at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.EnsureCSharpSymbolOrNull[TSource,TDestination](TSource symbol, String paramName)

   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(ITypeSymbol[] arguments)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.Instantiate(IMethodSymbol method, IList`1 invocationTypes)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass21_0.<InferTypeInArgument>b__2(IMethodSymbol m)

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(Int32 index, IEnumerable`1 methods, ArgumentSyntax argumentOpt)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInInvocationExpression(InvocationExpressionSyntax invocation, Int32 index, ArgumentSyntax argumentOpt)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(ArgumentSyntax argument, Nullable`1 previousToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(SyntaxNode node)

   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.InferTypes(SyntaxNode expression, Boolean filterUnusable)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInAnonymousFunctionExpression(AnonymousFunctionExpressionSyntax anonymousFunction)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeForReturnStatement(ReturnStatementSyntax returnStatement, Nullable`1 previousToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position)

   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.InferTypes(SemanticModel semanticModel, Int32 position, String nameOpt, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferType(ITypeInferenceService typeInferenceService, SemanticModel semanticModel, Int32 position, Boolean objectAsDefault, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.<ProvideCompletionsAsync>d__1.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.EnsureCSharpSymbolOrNull[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.String)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(Microsoft.CodeAnalysis.ITypeSymbol[])
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.Instantiate(Microsoft.CodeAnalysis.IMethodSymbol, System.Collections.Generic.IList`1<Microsoft.CodeAnalysis.ITypeSymbol>)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer+<>c__DisplayClass21_0.<InferTypeInArgument>b__2(Microsoft.CodeAnalysis.IMethodSymbol)
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypeInArgument(Int32, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.IMethodSymbol>, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypeInInvocationExpression(Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax, Int32, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypeInArgument(Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax, System.Nullable`1<Microsoft.CodeAnalysis.SyntaxToken>)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypesWorker_DoNotCallDirectly(Microsoft.CodeAnalysis.SyntaxNode)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService+AbstractTypeInferrer.InferTypes(Microsoft.CodeAnalysis.SyntaxNode, Boolean)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypeInAnonymousFunctionExpression(Microsoft.CodeAnalysis.CSharp.Syntax.AnonymousFunctionExpressionSyntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypeForReturnStatement(Microsoft.CodeAnalysis.CSharp.Syntax.ReturnStatementSyntax, System.Nullable`1<Microsoft.CodeAnalysis.SyntaxToken>)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService+TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.InferTypes(Microsoft.CodeAnalysis.SemanticModel, Int32, System.String, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferType(Microsoft.CodeAnalysis.LanguageServices.ITypeInferenceService, Microsoft.CodeAnalysis.SemanticModel, Int32, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider+<ProvideCompletionsAsync>d__1, Microsoft.CodeAnalysis.CSharp.Features, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProvideCompletionsAsync>d__1 ByRef)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.ProvideCompletionsAsync(Microsoft.CodeAnalysis.Completion.CompletionContext)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetContextAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetContextAsync>d__32, Microsoft.CodeAnalysis.Features, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetContextAsync>d__32 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(Microsoft.CodeAnalysis.Completion.CompletionProvider, Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Options.OptionSet, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<ComputeNonEmptyCompletionContextsAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<ComputeNonEmptyCompletionContextsAsync>d__26, Microsoft.CodeAnalysis.Features, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComputeNonEmptyCompletionContextsAsync>d__26 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Options.OptionSet, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Completion.CompletionProvider>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetCompletionsAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders+<GetCompletionsAsync>d__24, Microsoft.CodeAnalysis.Features, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetCompletionsAsync>d__24 ByRef)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Microsoft.CodeAnalysis.Document, Int32, Microsoft.CodeAnalysis.Completion.CompletionTrigger, System.Collections.Immutable.ImmutableHashSet`1<System.String>, Microsoft.CodeAnalysis.Options.OptionSet, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource+<GetCompletionContextAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource+<GetCompletionContextAsync>d__22, Microsoft.CodeAnalysis.EditorFeatures, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetCompletionContextAsync>d__22 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.GetCompletionContextAsync(Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.IAsyncCompletionSession, Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionTrigger, Microsoft.VisualStudio.Text.SnapshotPoint, Microsoft.VisualStudio.Text.SnapshotSpan, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession+<>c__DisplayClass88_1.<ConnectToCompletionSources>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations+<CallExtensionPointAsync>d__35`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.VisualStudio.Text.Utilities.GuardedOperations+<CallExtensionPointAsync>d__35`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.VisualStudio.Platform.VSEditor, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<CallExtensionPointAsync>d__35`1<System.__Canon> ByRef)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPointAsync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>, System.__Canon)
   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession+<ConnectToCompletionSources>d__88.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation+<>c.<Run>b__2_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.PrioritizedTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations+<CallExtensionPointAsync>d__35`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation+<>c.<Run>b__2_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.PrioritizedTaskScheduler.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by vatsalyaagrawal** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958972

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't gotten more hits on this (in prism/watson/anywhere)
