### ISSUE TITLE
InvalidOperationException in PlaceholderLocalSymbol.IdentifierToken

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3742]
```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.get_IdentifierToken()
at Microsoft.CodeAnalysis.CSharp.LocalScopeBinder.LookupLocal(SyntaxToken nameToken)
at Microsoft.CodeAnalysis.CSharp.Binder.LookupLocal(SyntaxToken nameToken)
at Microsoft.CodeAnalysis.CSharp.LocalScopeBinder.LookupLocal(SyntaxToken nameToken)
at Microsoft.CodeAnalysis.CSharp.Binder.LocateDeclaredVariableSymbol(VariableDeclaratorSyntax declarator; TypeSyntax typeSyntax)
at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatement(LocalDeclarationStatementSyntax node; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.<>c__DisplayClass12_0.<CompileExpression>b__0(EEMethodSymbol method; DiagnosticBag diags)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EEMethodSymbol.GenerateMethodBody(TypeCompilationState compilation...
```

**Comment by amcasey** [comment]
6 hits in builds on or after 6/20.

**Comment by amcasey** [comment]
We had an internal repro with the following in the Immediate window (1209169):

```C#
var x = 0;
x++
```

**Comment by amcasey** [comment]
This might also be related to #3861.

**Comment by amcasey** [comment]
FYI @kuhlenh

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Likely fixed in the last 10 years.
