### ISSUE TITLE
Assert failure in Binder.BindDeconstruction

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#37444]
A [fix in the convert switch statement to switch expression rewriter](https://github.com/dotnet/roslyn/pull/37016#discussion_r300811422) fails on an assert in `Binder.BindDeconstruction` for 2 tests:
- Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.ConvertSwitchStatementToExpression.ConvertSwitchStatementToExpressionTests.TestAssignment
- Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.ConvertSwitchStatementToExpression.ConvertSwitchStatementToExpressionTests.TestNested_01

It fails when the rewritten expression looks like

````
var j = (i) switch { ... }
````

Roslyn tries to bind a deconstruction and fails on an assert:

````
DeconstructionVariable locals = BindDeconstructionVariables(left, diagnostics, ref declaration, ref expression);
Debug.Assert(locals.HasNestedVariables);
````

````
    System.InvalidOperationException : 
    
  Stack Trace: 
    at ThrowingTraceListener.Fail(String message, String detailMessage) in ThrowingTraceListener.cs line: 24
    at TraceListener.Fail(String message)
    at TraceInternal.Fail(String message)
    at Debug.Assert(Boolean condition)
    at Binder.BindDeconstruction(CSharpSyntaxNode deconstruction, ExpressionSyntax left, ExpressionSyntax right, DiagnosticBag diagnostics, DeclarationExpressionSyntax& declaration, ExpressionSyntax& expression, Boolean resultIsUsedOverride, BoundDeconstructValuePlaceholder rightPlaceholder) in Binder_Deconstruct.cs line: 95
    at Binder.BindDeconstruction(AssignmentExpressionSyntax node, DiagnosticBag diagnostics, Boolean resultIsUsedOverride) in Binder_Deconstruct.cs line: 33
    at Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 1333
    at Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in Binder_Expressions.cs line: 404
    at Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in Binder_Expressions.cs line: 329
    at Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in Binder_Expressions.cs line: 228
    at Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in Binder_Statements.cs line: 588
    at Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 581
    at Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 52
    at Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 1662
    at Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 1650
    at Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in Binder_Statements.cs line: 43
    at Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) in Binder_Statements.cs line: 3170
    at Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in Binder_Statements.cs line: 3118
    at MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, ValueTuple`4& forSemanticModel) in MethodCompiler.cs line: 1653
    at MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in MethodCompiler.cs line: 958
    at MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in MethodCompiler.cs line: 507
    at MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg) in MethodCompiler.cs line: 385
    at NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument) in NamedTypeSymbol.cs line: 576
    at MethodCompiler.CompileNamespace(NamespaceSymbol symbol) in MethodCompiler.cs line: 364
    at MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in MethodCompiler.cs line: 152
    at CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken) in CSharpCompilation.cs line: 2412
    at CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in CSharpCompilation.cs line: 2544
    at SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in SyntaxTreeSemanticModel.cs line: 134
    at <GetErrorsAsync>d__7.MoveNext() in DocumentExtensions.cs line: 120
...
````

**Comment by gafter** [comment]
I suspect an ill-formed syntax tree.  Can you reproduce this from source?

**Comment by gafter** [comment]
It looks like you've constructed an ill-formed syntax tree.  You've constructed an expression statement containing a declaration expression on the left.  That is not legal.  This should be a local declaration statement with initializer.
