### ISSUE TITLE
Csharpaddimportcodefixprovider encountered an error - issue occured after solution load was complete

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37579]
Not sure if it only started occuring recently, but I noticed it in the newest internal preview. 

The stack trace is as below: 

```
System.InvalidOperationException : This instance must be flushed before being reinitialized.
   at Nerdbank.Streams.BufferTextWriter.Initialize(IBufferWriter`1 bufferWriter,Encoding encoding)
   at StreamJsonRpc.JsonMessageFormatter.WriteJToken(IBufferWriter`1 contentBuffer,JToken json)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer,JsonRpcMessage message)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content,CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content,CancellationToken cancellationToken)
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(&lt;Unknown Parameters&gt;)
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.ServiceHub.Client.HubClient.LocateServiceAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.ServiceHub.Client.HubClient.LocateServiceAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.ServiceHub.Client.HubClient.RequestServiceChannelNameAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.ServiceHub.Client.HubClient.RequestServiceAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.LanguageServices.Remote.ServiceHubRemoteHostClient.Connections.RetryRemoteCallAsync[TException,TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.LanguageServices.Remote.ServiceHubRemoteHostClient.Connections.RequestServiceAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.LanguageServices.Remote.ServiceHubRemoteHostClient.ConnectionManager.TryCreateNewConnectionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteHostClientExtensions.TryCreateSessionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteHostClientExtensions.TryCreateCodeAnalysisSessionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteHostClientExtensions.TryRunCodeAnalysisRemoteAsync[T](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesAsync[TSimpleNameSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportFeatureService`1.GetFixesForDiagnosticsAsync[TSimpleNameSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/665906/csharpaddimportcodefixprovider-encountered-an-erro-8.html
VSTS ticketId: 957019_
_These are the original issue comments:_

Visual Studio Feedback System on 7/29/2019, 11:31 PM (11 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by heejaechang** [comment]
@AArnott have you seen this issue? something new we are getting after moving to StreamJsonRpc 2.0

**Comment by AArnott** [comment]
Are you sharing a `JsonMessageFormatter` across multiple instances of `JsonRpc`?
See https://github.com/microsoft/vs-streamjsonrpc/issues/303 for a discussion of this same exception being reported by another user that ended up being because they reused the `JsonMessageFormatter` across several connections, which is not supported.

**Comment by heejaechang** [comment]
@AArnott 
just checked and we do not share the formatter
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Shared/Extensions.cs,28

and callstack here point to ServiceHub.Client.LocateServiceAsync
at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.ServiceHub.Client.HubClient.LocateServiceAsync

not ours. so, the hubclient might sharing it?

**Comment by heejaechang** [comment]
moved to extensibility team - https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/959430

**Comment by AArnott** [comment]
FYI we have a fix for an issue that we believe will address this here: https://github.com/microsoft/vs-streamjsonrpc/pull/321
