### ISSUE TITLE
AssetStorageTests.TestCleanup failed

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#37576]
Failed in Windows_Desktop_Unit_Tests release_32 - Attempt 1

[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=285222&view=ms.vss-test-web.build-test-results-tab&runId=7989300&resultId=100719&paneView=debug)

```
asset not cleaned up
Expected: True
Actual: False
   at Roslyn.VisualStudio.Next.UnitTests.Remote.AssetStorageTests.<TestCleanup>d__2.MoveNext() in /_/src/VisualStudio/Core/Test.Next/Services/AssetStorageTests.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by JoeRobich** [comment]
Closing as this test is passing
