### ISSUE TITLE
NullReferenceException in Microsoft.CodeAnalysis.CSharp.Symbols.MemberSignatureComparer.HaveSameReturnTypes

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#37625]
**Version Used**: 

An analyzer in VS2019 16.3 preview 1

````
Analyzer 'Meziantou.Analyzer.Rules.MakeMethodStaticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MemberSignatureComparer.HaveSameReturnTypes(Symbol member1, TypeMap typeMap1, Symbol member2, TypeMap typeMap2, TypeCompareKind typeComparison)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MemberSignatureComparer.Equals(Symbol member1, Symbol member2)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.IsInterfaceMemberImplementation(Symbol candidateMember, Symbol interfaceMember, Boolean implementingTypeIsFromSomeCompilation)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindPotentialImplicitImplementationMemberDeclaredInType(Symbol interfaceMember, Boolean implementingTypeIsFromSomeCompilation, TypeSymbol currType, Symbol& implicitImpl, Symbol& closeMismatch)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationForInterfaceMember(Symbol interfaceMember, TypeSymbol implementingType, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationAndDiagnosticsForInterfaceMember(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMemberInNonInterfaceWithDiagnostics(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMember(Symbol interfaceMember)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.FindImplementationForInterfaceMember(ISymbol interfaceMember)
   at Meziantou.Analyzer.MethodSymbolExtensions.<>c__DisplayClass5_0.<GetImplementingInterfaceSymbol>b__1(ISymbol interfaceMember)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Meziantou.Analyzer.MethodSymbolExtensions.GetImplementingInterfaceSymbol(ISymbol symbol)
   at Meziantou.Analyzer.MethodSymbolExtensions.IsInterfaceImplementation(IPropertySymbol property)
   at Meziantou.Analyzer.Rules.MakeMethodStaticAnalyzer.AnalyzerContext.IsPotentialStatic(IPropertySymbol symbol)
   at Meziantou.Analyzer.Rules.MakeMethodStaticAnalyzer.AnalyzerContext.AnalyzeProperty(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__53`1.<ExecuteSyntaxNodeAction>b__53_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
````

The code of the last method of my analyzer in the stack trace is available here: https://github.com/meziantou/Meziantou.Analyzer/blob/137a45fe687a17fa52665429a09db538d24b6b8e/src/Meziantou.Analyzer/Internals/MethodSymbolExtensions.cs#L45

````csharp
private static ISymbol GetImplementingInterfaceSymbol(this ISymbol symbol)
{
    if (symbol.ContainingType == null)
        return null;

    return symbol.ContainingType.AllInterfaces
        .SelectMany(@interface => @interface.GetMembers())
        .FirstOrDefault(interfaceMember => symbol.Equals(symbol.ContainingType.FindImplementationForInterfaceMember(interfaceMember)));
}
````

**Expected Behavior**:

It doesn't throw a NRE

**Actual Behavior**:

It throws a NRE

**Comment by sharwell** [comment]
Related to #35226, #33240, #37354
