### ISSUE TITLE
Assertion failed while editing method with switch expression: Unhandled declaration pattern context

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37673]
**Version Used**: 

F5 from the latest master-vs-deps.

**Steps to Reproduce**:

Console app with following code:

```C#
class C
{
    static void Main()
    {
        var obj = F();
        object result;
        switch (obj)
        {
            case int i:
                result = i * 10;
                break;

            case C x when x.P == 1:
                result = "D";
                break;

            default:
                result = obj;
                break;
        }
        Console.WriteLine(result);
    }
}
```

Right click on switch keyword and use refactoring "change to switch expression".

**Expected Behavior**:

No assert.

**Actual Behavior**:

```
Unhandled declaration pattern context
   at Microsoft.CodeAnalysis.OperationExtensions.GetValueUsageInfo(IOperation operation)
   at icrosoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis.SymbolUsageAnalysis.Walker.OnReferenceFound(ISymbol symbol, IOperation operation)
   at icrosoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis.SymbolUsageAnalysis.Walker.VisitDeclarationPattern(IDeclarationPatternOperation operation)
   at Microsoft.CodeAnalysis.Operations.DeclarationPatternOperation.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Operations.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Operations.OperationWalker.VisitOperationArrayElement[T](T operation)
   at Microsoft.CodeAnalysis.Operations.OperationWalker.VisitArray[T](IEnumerable`1 operations)
   at Microsoft.CodeAnalysis.Operations.OperationWalker.DefaultVisit(IOperation operation)
   at icrosoft.CodeAnalysis.Operations.OperationVisitor.VisitSwitchExpressionArm(ISwitchExpressionArmOperation ope......

```

**Comment by gafter** [comment]
The IDE is apparently creating an invalid syntax tree for
`object result = obj switch { ...`

Instead of representing this as a local variable declaration, it is representing it as an expression statement containing an assignment expression containing a declaration expression on the left-hand-side.  That is not correct.  The compiler has no specified behavior when confronted with syntax nodes that the parser could never construct.

**Comment by tmat** [comment]
@jasonmalinowski

**Comment by gafter** [comment]
I believe this is fixed now.  See https://github.com/dotnet/roslyn/pull/37016#discussion_r307008560

**Comment by jinujoseph** [comment]
@jasonmalinowski  to confirm the fix
