### ISSUE TITLE
VS 15.9 - UriFormatException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#37722]
Marked Priority 1 in DC 

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/383068/vs-159-uriformatexception.html)._

---
While typing in the IDE I got the following error: &quot;An exception has been encountered. This may be caused by an extension. You can get more information from the ActivityLog.xml&quot;.

Here is the exception and stacktrace at the bottom of that file:

```
System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32&amp; destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.BrowserHelper.CreateBingQueryUri(String errorCode, String title, String language, String projectType)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.BrowserHelper.CreateBingQueryUri(DiagnosticData diagnostic)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.GetHelpLinkToolTipText(DiagnosticData item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSnapshot.TryGetValue(Int32 index, String columnName, Object&amp; content)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.SnapshotTableEntryViewModel.TryGetValue(String columnName, Object&amp; content)
```

---
#### Fiona Niu[MSFT] on 11/14/2018, 11:12 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario?</p><p> </p><p>We look forward to hearing from you!</p>

#### Fiona Niu[MSFT] on 11/22/2018, 10:39 PM: 

<p>Thank you for your feedback! Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to repro it, please provide us with more info!</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The underlying cause of this bug is #26717.
