### ISSUE TITLE
Failed assertions when declaring ref variables in EE

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#37749]
**Version Used**: 
![image](https://user-images.githubusercontent.com/41759/62503003-1b7b5600-b7a7-11e9-8943-d17537536d42.png)

**Steps to Reproduce**:
Step into a method:

```C#
    static void Main()
    {
        var a = new int[1];
        ref readonly var x = ref F(a);
    }
```

Type 
```C#
ref readonly var z = ref x;
```

to Immediate Window.

**Expected Behavior**:

No assert.

**Actual Behavior**:

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
undeclared local Local System.Int32 z

   at Microsoft.CodeAnalysis.CSharp.BoundNode.LocalsScanner.CheckDeclared(LocalSymbol local)
   at Microsoft.CodeAnalysis.CSharp.BoundNode.LocalsScanner.VisitPseudoVariable(BoundPseudoVariable node)
   at Microsoft.CodeAnalysis.CSharp.BoundPseudoVariable.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitAssignmentOperator(BoundAssignmentOperator node)
   at Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator.Accept(BoundTreeVisitor visitor)
```

**Comment by tmat** [comment]
@cston @jcouv Looks like a compiler issue. Could you please take a look?
