### ISSUE TITLE
Code metrics calculation from command line can't resolve msbuild location correctly!

### ISSUE THREAD

**Issue by gremlm** [dotnet/roslyn#37890]
For calculating code metrics I have included Microsoft.CodeAnalysis.Metrics 2.9.4 nuget package to my csproj project.
Before executing msbuild from the command line, I have called  "nuget.exe restore", and it correctly found MSBuild and restore package:
"MSBuild auto-detection: using msbuild version '16.200.19.32702' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
Restoring NuGet package Microsoft.CodeAnalysis.Metrics.2.9.4. ..."

Then, from command line I am calling msbuild with /t:Metrics option:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\MSBuild.exe" /p:Configuration=Debug /t:Metrics My.sln "

which ended with following error:
"Unhandled Exception: System.ArgumentException: Directory "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\MSBuild\Current\Bin" does not exist
  Parameter name: msbuildPath
     at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String msbuildPath)
     at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
     at Metrics.Program.<RunAsync>d__1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)"

It looks like  Metrics.exe looking for msbuild in wrong location, but nugget.exe in correct one?

**Comment by mavasani** [comment]
@vatsalyaagrawal Can you please port this bug to roslyn-analyzers repo?
