### ISSUE TITLE
Assert evaluating expression after invalid using in Interactive Window

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3795]
```
> from x in args select x + 1
(1,11): error CS0103: The name 'args' does not exist in the current context
> var args = new[] { 1, 2, 3 };
> from x in args select x + 1
(1,11): error CS1935: Could not find an implementation of the query pattern for source type 'int[]'.  'Select' not found.  Are you missing a reference to 'System.Core.dll' or a using directive for 'System.Linq'?
> using System.Linq;
> from x in args select x + 1
Unexpected error:
System.InvalidOperationException: Previous submission has errors.
   at Microsoft.CodeAnalysis.Compilation.ValidateSubmissionParameters(Compilation previousSubmission, Type returnType, Type& hostObjectType) in F:\Enlistments\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 148
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 247
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CreateSubmission(String assemblyName, SyntaxTree syntaxTree, IEnumerable`1 references, CSharpCompilationOptions options, Compilation previousSubmission, Type returnType, Type hostObjectType) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 222
   at Microsoft.CodeAnalysis.Scripting.CSharp.CSharpScript.CreateCompilation() in F:\Enlistments\roslyn\src\Scripting\CSharp\CSharpScript.cs:line 155
   at Microsoft.CodeAnalysis.Scripting.Script.GetCompilation() in F:\Enlistments\roslyn\src\Scripting\Core\Script.cs:line 350
   at Microsoft.CodeAnalysis.Scripting.Script.GetExecutor(CancellationToken cancellationToken) in F:\Enlistments\roslyn\src\Scripting\Core\Script.cs:line 408
   at Microsoft.CodeAnalysis.Scripting.Script.Build() in F:\Enlistments\roslyn\src\Scripting\Core\Script.cs:line 363
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.Compile(String text, String path) in F:\Enlistments\roslyn\src\Interactive\Features\Interactive\Core\InteractiveHost.Service.cs:line 655
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.Execute(String text) in F:\Enlistments\roslyn\src\Interactive\Features\Interactive\Core\InteractiveHost.Service.cs:line 736
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.ExecuteAsync(RemoteAsyncOperation`1 operation, String text) in F:\Enlistments\roslyn\src\Interactive\Features\Interactive\Core\InteractiveHost.Service.cs:line 381
```

**Comment by amcasey** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected error



   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.ReportUnhandledException(Exception e) in F:\Enlistments\roslyn\src\Interactive\Features\Interactive\Core\InteractiveHost.Service.cs:line 452

   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.ExecuteAsync(RemoteAsyncOperation`1 operation, String text) in F:\Enlistments\roslyn\src\Interactive\Features\Interactive\Core\InteractiveHost.Service.cs:line 385

   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)

   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

   at System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.AsyncProcessMessage(IMessage reqMsg, IMessageSink replySink)

   at System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.AsyncProcessMessage(IMessage reqMsg, IMessageSink replySink)

   at System.Runtime.Remoting.Channels.AsyncWorkItem.FinishAsyncWorkCallback(Object[] args)

   at System.Threading.Thread.CompleteCrossContextCallback(InternalCrossContextDelegate ftnToCall, Object[] args)

   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)

   at System.Runtime.Remoting.Channels.AsyncWorkItem.FinishAsyncWork(Object stateIgnored)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by amcasey** [comment]
Part of #3785.

**Comment by amcasey** [comment]
Reduced:

```
> using System.Linq;
> x
Unexpected error:
System.InvalidOperationException: Previous submission has errors.
```

**Comment by amcasey** [comment]
When I replace the using with an unbound identifier (also an error), ```Compilation.ValidateSubmissionParameters``` indicates that there is no previous submission.  So maybe we ignore submissions with errors?  If that's the case, then the problem is that we're not ignoring submissions with errors (only?) in usings.

**Comment by amcasey** [comment]
Whereas ```Compile("foo")``` results in a ```CompilationErrorException```, ```Compile("using foo")``` does not.  This suggests that ```Compile``` and ```ValidateSubmissionParameters``` are using different criteria.

**Comment by amcasey** [comment]
The former uses the diagnostics from ```Compilation.Emit``` whereas the latter uses the diagnostics from ```Compilation.GetDiagnostics```.  It seems strange that the latter would include more.

**Comment by amcasey** [comment]
Compilation is being short-circuited because ```CSharpCompilation.HasCodeToEmit``` is returning true (because the submission declares no members).

**Comment by amcasey** [comment]
The fix is to still report diagnostics in the short-circuit case.  I'll add a test.
