### ISSUE TITLE
TetsTemporaryStorageText failing with null Encoding

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#380]
The following failure is occurring on developer machines:

```
Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorageText
Assert.Equal() Failure
Expected: (null)
Actual:   System.Text.UnicodeEncoding
   at Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorage(ITemporaryStorageService temporaryStorageService, SourceText text) in E:\dd\ros-git\Src\Workspaces\CoreTest\WorkspaceServiceTests\TemporaryStorageServiceTests.cs:line 82
   at Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorageText() in E:\dd\ros-git\Src\Workspaces\CoreTest\WorkspaceServiceTests\TemporaryStorageServiceTests.cs:line 29
Traits:
```

Disabling the suite for now.

**Comment by pharring** [comment]
@heejaechang This is yours. You already fixed the test, but we need a code fix.

**Comment by pharring** [comment]
@heejaechang See also #384 which contains my initial attempt to fix it (prior to our discussion about adding back the TextReader overload on ITextFactoryService)
