### ISSUE TITLE
CSharp Scripting string interpolation using switch epxression fails with CS8652

### ISSUE THREAD

**Issue by standsed** [dotnet/roslyn#38005]
**Version Used**: 
dotnet 3.0.100-preview7-012821
Microsoft.CodeAnalysis.CSharp.Scripting 3.3.0-beta1-final
**Steps to Reproduce**:

Run xunit test (FluentAssertions)
```        
        [Fact]
        public async void Eval()
        {
            const string template = @"{(1 == 1 ? ""11"" : ""22"")}";
            var works = await CSharpScript.EvaluateAsync($@"return $@""{template}"";");
            works.Should().Be("11");

            $"{1 switch {2 => "22", 1 => "11"}}".Should().Be("11");
            
            const string template2 = @"{(1 switch {2 => ""22"", 1 => ""11""})}";
            var fails = await CSharpScript.EvaluateAsync($@"return $@""{template2}"";");
            fails.Should().Be("11");
        }
```

**Expected Behavior**:
Test passed

**Actual Behavior**:
Test fails at line 
`var fails = await CSharpScript.EvaluateAsync($@"return $@""{template2}"";");`
wtih exception
```
  Error Message:
   Microsoft.CodeAnalysis.Scripting.CompilationErrorException : (1,13): error CS8652: The feature 'recursive patterns' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
  Stack Trace:
     at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
...
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
```

**Comment by svick** [comment]
I believe this is the expected behavior. `CSharpScript` uses the `latest` version, which is currently still C# 7.3 and there doesn't seem to be any public way to change that.

**Comment by filipw** [comment]
You need to switch to `LanguageVersion.Preview`, otherwise it defaults to `Latest` which is `7.3`.

```
await CSharpScript.EvaluateAsync($@"return $@""{template2}"";", ScriptOptions.Default.WithLanguageVersion(LanguageVersion.Preview);
```

We added the option to switch the version specifically for situations like this.

**Comment by standsed** [comment]
> You need to switch to `LanguageVersion.Preview`, otherwise it defaults to `Latest` which is `7.3`.
> 
> ```
> await CSharpScript.EvaluateAsync($@"return $@""{template2}"";", ScriptOptions.Default.WithLanguageVersion(LanguageVersion.Preview));
> ```
> 
> We added the option to switch the version specifically for situations like this.

It works, thank you!
