### ISSUE TITLE
Exception from AsynchronousTagger in activity log

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#3807]
I ran into this exception when trying to collapse outlining in preview changes dialog below as part of previewing fix for an issue reported by one of the analyzers in System.Runtime.Analyzers (in VB).

![blah](https://cloud.githubusercontent.com/assets/10579684/8468473/c6bae75a-2021-11e5-821f-8ccafe58d6ce.png)

The crash was not fatal (did not bring down VS). I was also unable to reproduce the issue again when I tried to expand collapse repeatedly again.

```
System.ArgumentNullException: Value cannot be null. Parameter name: collection 
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
at Microsoft.CodeAnalysis.Editor.Shared.Tagging.AsynchronousTagger`1.GetTagsForSmallNumberOfSpans(NormalizedSnapshotSpanCollection requestedSpans, ITagSpanIntervalTree`1 tags)
at Microsoft.CodeAnalysis.Editor.Shared.Tagging.AsynchronousTagger`1.GetTags(NormalizedSnapshotSpanCollection requestedSpans, ITagSpanIntervalTree`1 tags)
at Microsoft.CodeAnalysis.Editor.Shared.Tagging.AsynchronousTagger`1.GetTags(NormalizedSnapshotSpanCollection requestedSpans)
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
```

**Comment by Pilchie** [comment]
Can you see if this is an issue with your tagging changes?

**Comment by CyrusNajmabadi** [comment]
@Pilchie Just to make sure we're on the same page.  You're asking me to see if this reproes or is-fixed with the tagger changes i'm making.  You're not asking me if my tagger changes cause this, correct? :)

**Comment by Pilchie** [comment]
Right - see if this code path even exists with your changes.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  Will do.  Note: the codepath does exist.  but i'll at least try out the outlining-in-preview scenario.  it's possible it was fixed (or horribly regressed) with my changes.

**Comment by CyrusNajmabadi** [comment]
Doesn't seem to repro after my changes.  @shyamnamboodiripad let me know if you still run into this (after applying my changes).  I'd love a live repro.  Thanks!
