### ISSUE TITLE
Assert from Binder.CanAddLookupSymbolInfo in Interactive Window CSharpRecommendationService

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#3817]
Was typing "START" at goto.

![interactiveassert](https://cloud.githubusercontent.com/assets/10508071/8488335/d7f51586-20c6-11e5-8519-e305d3209af9.png)

**Comment by amcasey** [comment]
```
   at Microsoft.CodeAnalysis.CSharp.Binder.CanAddLookupSymbolInfo(Symbol symbol, LookupOptions options, TypeSymbol accessThroughType) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Lookup.cs:line 1207
   at Microsoft.CodeAnalysis.CSharp.Imports.AddLookupSymbolsInfoInUsings(ImmutableArray`1 usings, Binder binder, LookupSymbolsInfo result, LookupOptions options) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Binder\Imports.cs:line 629
   at Microsoft.CodeAnalysis.CSharp.UsingsBinder.AddLookupSymbolsInfoInSingleBinder(LookupSymbolsInfo result, LookupOptions options, Binder originalBinder) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Binder\UsingsBinder.cs:line 67
   at Microsoft.CodeAnalysis.CSharp.Binder.AddLookupSymbolsInfo(LookupSymbolsInfo result, LookupOptions options) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Lookup.cs:line 1439
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbolsInternal(Int32 position, NamespaceOrTypeSymbol container, String name, LookupOptions options, Boolean useBaseReferenceAccessibility) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1388
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupLabels(Int32 position, String name) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1304
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupLabelsCore(Int32 position, String name) in F:\Enlistments\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 4537
   at Microsoft.CodeAnalysis.SemanticModel.LookupLabels(Int32 position, String name)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForLabelContext(CSharpSyntaxContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForCurrentContext(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsWorker(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetRecommendedSymbolsAtPositionWorker(Workspace workspace, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPosition(Workspace workspace, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Recommendations.Recommender.GetRecommendedSymbolsAtPosition(SemanticModel semanticModel, Int32 position, Workspace workspace, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.SymbolCompletionProvider.GetSymbolsWorker(AbstractSyntaxContext context, Int32 position, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetSymbolsWorker(Int32 position, Boolean preselect, AbstractSyntaxContext context, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, Boolean preselect, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.GetItemsAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.GetGroupAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupAsync(ICompletionProvider provider, Document documentOpt, SourceText text, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupsAsync(Document documentOpt, SourceText text, Int32 position, CompletionTriggerInfo triggerInfo, IEnumerable`1 completionProviders, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupsAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, IEnumerable`1 completionProviders, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.GetGroupsAsync(ICompletionService completionService, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.DoInBackgroundAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<Do>b__14_0(Model model, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.<>c__DisplayClass17_0.<ChainTaskAndNotifyControllerWhenFinished>b__0(Task`1 t)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass14_0`2.<SafeContinueWithFromAsync>b__0(Task antecedent)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.PrioritizedTaskScheduler.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by amcasey** [comment]
Part of #3785

**Comment by amcasey** [comment]
The assert is that the ```LookupOptions``` are valid.

**Comment by amcasey** [comment]
```MustNotBeNamespace``` is added by a ```UsingsBinder```.  Seems like we shouldn't reach that point when looking for a label.  I bet there's an intermediate binder that short-circuits this case in regular C# code.

**Comment by amcasey** [comment]
Clarification: It's actually an ```InteractiveUsingsBinder```.  The binder chain is different in the Interactive Window, which is why we're not hitting this in regular code.

**Comment by amcasey** [comment]
From ```InContainerBinder.AddLookupSymbolsInfoInSingleBinder```:

```C#
// if we are looking only for labels we do not need to search through the imports
if (!IsSubmissionClass && ((options & LookupOptions.LabelsOnly) == 0))
```

We should probably have a similar kick out in the interactive case.

**Comment by amcasey** [comment]
Empirically, VB appears to be unaffected.  I'll confirm in the code.

**Comment by amcasey** [comment]
@cston Can you please verify?
