### ISSUE TITLE
VisualBasicCompletionCommandHandlerTests.TestMRUKeepsTwoRecentlyUsedItems UnitTest fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#38349]
Multiple failures in PR validation [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=328771&view=ms.vss-test-web.build-test-results-tab&runId=9620558&resultId=100452&paneView=debug)

```
Error message
Assert.Equal() Failure\r\n ↓ (pos 9)\r\nExpected: Ma(m:=(Ma(m:=(\r\nActual: M(Ma(m:=(Ma(\r\n ↑ (pos 9)

Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_147_TestMRUKeepsTwoRecentlyUsedItems.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb:line 3110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by JoeRobich** [comment]
Same issue was found in the CSharpCompletionCommandHandlerTests
```
      Assert.Equal() Failure
                           ↓ (pos 11)
      Expected:         Ma(m:(Ma(m:(
      Actual:           Ma(M(Ma(m:(
                           ↑ (pos 11)
      Stack Trace:
        /_/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb(4623,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.VB$StateMachine_189_TestMRUKeepsTwoRecentlyUsedItems.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ivanbasov** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/38413
