### ISSUE TITLE
VisualBasicCompletionCommandHandlerTests.DotIsInserted UnitTest fails

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#38350]
Multiple failures in PR validation [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=328771&view=ms.vss-test-web.build-test-results-tab&runId=9620558&resultId=100452&paneView=debug)

```
Error message
Current completion is not soft-selected. Expected: soft-selected\r\nExpected: True\r\nActual: False

Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModernCompletionTestState.VB$StateMachine_28_AssertSelectedCompletionItem.MoveNext() in /_/src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_15_DotIsInserted.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb:line 271
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ivanbasov** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/38413
