### ISSUE TITLE
VisualBasicCompletionCommandHandlerTests.TestBangFiltersInDocComment

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#38351]
Failures in PR validation [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=328771&view=ms.vss-test-web.build-test-results-tab&runId=9620558&resultId=100452&paneView=debug)
```
Error message
AssertCompletionSession\r\nExpected: True\r\nActual: False

Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModernCompletionTestState.VB$StateMachine_22_AssertCompletionSession.MoveNext() in /_/src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_59_TestBangFiltersInDocComment.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb:line 1369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ivanbasov** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/38413
