### ISSUE TITLE
completion leaking cancellation exception

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38455]
```
<entry>
<record>5061</record>
<time>2019/06/05 19:03:33.638</time>
<type>Error</type>
<source>Editor or Editor Extension</source>
<description>System.OperationCanceledException: The operation was canceled.
 at System.Threading.CancellationToken.ThrowOperationCanceledException()
 at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
 at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.Commit(Document document, CompletionService completionService, ITextView view, ITextBuffer subjectBuffer, CompletionItem roslynItem, TextSpan completionListSpan, Nullable`1 commitCharacter, ITextSnapshot triggerSnapshot, CompletionRules rules, String filterText, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.TryCommit(IAsyncCompletionSession session, ITextBuffer subjectBuffer, CompletionItem item, Char typeChar, CancellationToken cancellationToken)
 at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.<>c__DisplayClass67_1.<CommitItem>b__0()
 at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
</entry>
```

**Comment by heejaechang** [comment]
@ivanbasov it looks like cancellation exception from async completion is leaking to editor. or editor team is not catching them correctly. can you take a look?

**Comment by ivanbasov** [comment]
Let me take a look

**Comment by ivanbasov** [comment]
@AmadeusW , Roslyn should pass OperationCanceledException to Editor. Could you please take a look?

**Comment by AmadeusW** [comment]
@ivanbasov, Editor ignores the exception if the token that we passed is canceled (`e is OperationCanceledException && token.IsCancellationRequested`)

We're reporting the exception because our token is not canceled, but Roslyn threw OperationCanceledException. Please comment on the state of the token, and which code path throws.

The execution path is equivalent to:
```
            try
            {
                return commitManager.TryCommit(this, textBuffer, itemToCommit, typedChar, token);
            }
            catch (Exception e) when (e is OperationCanceledException && token.IsCancellationRequested)
            {
                return CommitResult.Unhandled;
            }
            catch (Exception e) when (true)
            {
                HandleException(commitManager, e);
                return CommitResult.Unhandled;
            }
```

**Comment by ivanbasov** [comment]
Thank you, @AmadeusW ! Provided a fix: https://github.com/dotnet/roslyn/pull/38526
