### ISSUE TITLE
FixupSpan tests are flaky

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#38555]
The following two tests are failing in otherwise good builds:

- `CSharp_FixupSpanDuringResolvableConflict_ComplexificationReordersReferenceSpans`
- `VisualBasic_FixupSpanDuringResolvableConflict_NonReferenceConflict`

Error message: 

```
Assert.Equal() Failure\r\nExpected: WhereSelectEnumerableIterator<TextSpan, Span> [[41..44), [177..180), [184..187)]\r\nActual: List<Span> [[41..44), [177..180), [177..180), [184..187), [184..187)]
```

Stack trace:

```
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_8_VerifyTaggedSpansCore.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_2_VerifyTaggedSpans.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_6_VerifySpansBeforeConflictResolution.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.VB$StateMachine_28_CSharp_FixupSpanDuringResolvableConflict_ComplexificationReordersReferenceSpans.MoveNext() in /_/src/EditorFeatures/Test2/Rename/RenameTagProducerTests.vb:line 1383
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by sharwell** [comment]
These are duplicates of #29483. Can you link the skip attribute to that issue so this one can be closed?

**Comment by jaredpar** [comment]
Feel free to send a PR that does this after I merge. I'm not resetting my PR at this point given I've already been delayed by this failure. There was ample opportunity before this to disable the test with the correct link. I'm not sure why my search didn't pull this up initially but I did look for it.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/38769 skips another test, CSharp_FixupSpanDuringResolvableConflict_ReferenceConflict, and replaces the links for this bug with the one linked by @sharwell.
