### ISSUE TITLE
Inline rename throws InvalidOperationException in ASP.NET Core page

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#38557]
**Version Used**: 

**Steps to Reproduce**:

1. Create an ASP.NET Core Web App
2. Open `Error.cshtml`.
3. Rename `ErrorModel` class to `ErrorModel2` (Ctrl+R+R).

**Expected Behavior**:

**Actual Behavior**:

Assertion failed:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)

   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.RawRaiseEvent(TextContentChangedEventArgs args, Boolean immediate)

   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.SourceSpansChangedEventRaiser.RaiseEvent(BaseBuffer baseBuffer, Boolean immediate)

   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.RaiseEvents()

   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.FinishEdit()

   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.SpanEdit.ReplaceSpans(Int32 position, Int32 spansToReplace, IList`1 spansToInsert, EditOptions options, Object editTag)

   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.ReplaceSpans(Int32 position, Int32 spansToReplace, IList`1 spansToInsert, EditOptions options, Object editTag)

   at Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionManager.UpdateTextBuffer(ProjectionMapping[] mappings, String fullLangBufferText)

   at Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionManager.SetMappingsHelper(ProjectionMapping[] mappings, String fullLangBufferText)

   at Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionBuffer.SetTextAndMappings(String text, ProjectionMapping[] mappings)

   at Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.SetTextAndMappings(List`1 newCodeRanges)

   at Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.<>c__DisplayClass80_0.<OnDocumentStructureChanged>b__0()

   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)

   at Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.OnDocumentStructureChanged(Object sender, DocumentStructureChangedEventArgs e)

   at Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioRazorParser.OnDocumentStructureChanged(Object state)

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(Object obj)

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

```

Followed by an exception:
```
>	System.Core.dll!System.Linq.Enumerable.Single<Microsoft.VisualStudio.Text.SnapshotSpan>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Text.SnapshotSpan> source) Line 1173	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(object sender, Microsoft.VisualStudio.Text.TextContentChangedEventArgs args) Line 247	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent<Microsoft.VisualStudio.Text.TextContentChangedEventArgs>(object sender, System.EventHandler<Microsoft.VisualStudio.Text.TextContentChangedEventArgs> eventHandlers, Microsoft.VisualStudio.Text.TextContentChangedEventArgs args) Line 546	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BaseBuffer.RawRaiseEvent(Microsoft.VisualStudio.Text.TextContentChangedEventArgs args, bool immediate) Line 1061	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.SourceSpansChangedEventRaiser.RaiseEvent(Microsoft.VisualStudio.Text.Implementation.BaseBuffer baseBuffer, bool immediate) Line 362	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.RaiseEvents() Line 626	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.FinishEdit() Line 586	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.SpanEdit.ReplaceSpans(int position, int spansToReplace, System.Collections.Generic.IList<object> spansToInsert, Microsoft.VisualStudio.Text.EditOptions options, object editTag) Line 758	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.ReplaceSpans(int position, int spansToReplace, System.Collections.Generic.IList<object> spansToInsert, Microsoft.VisualStudio.Text.EditOptions options, object editTag) Line 995	C#
 	Microsoft.WebTools.Languages.Html.Editor.dll!Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionManager.UpdateTextBuffer(Microsoft.WebTools.Languages.Html.Editor.Projection.ProjectionMapping[] mappings, string fullLangBufferText) Line 156	C#
 	Microsoft.WebTools.Languages.Html.Editor.dll!Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionManager.SetMappingsHelper(Microsoft.WebTools.Languages.Html.Editor.Projection.ProjectionMapping[] mappings, string fullLangBufferText) Line 214	C#
 	Microsoft.WebTools.Languages.Html.Editor.dll!Microsoft.WebTools.Languages.Html.Editor.Projection.LanguageProjectionBuffer.SetTextAndMappings(string text, Microsoft.WebTools.Languages.Html.Editor.Projection.ProjectionMapping[] mappings) Line 34	C#
 	Microsoft.WebTools.Languages.Razor.Core.dll!Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.SetTextAndMappings(System.Collections.Generic.List<Microsoft.WebTools.Languages.Html.Editor.ContainedLanguage.Razor.RazorRange> newCodeRanges) Line 873	C#
 	Microsoft.WebTools.Languages.Razor.Core.dll!Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.OnDocumentStructureChanged.AnonymousMethod__0() Line 345	C#
 	Microsoft.WebTools.Languages.Shared.Editor.dll!Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(object errorSource, System.Action action) Line 84	C#
 	Microsoft.WebTools.Languages.Razor.Core.dll!Microsoft.WebTools.Languages.Razor.Core.RazorCodeGenerator.OnDocumentStructureChanged(object sender, Microsoft.VisualStudio.Editor.Razor.DocumentStructureChangedEventArgs e) Line 366	C#
 	Microsoft.VisualStudio.Editor.Razor.dll!Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioRazorParser.OnDocumentStructureChanged(object state) Line 472	C#

```

**Comment by CyrusNajmabadi** [comment]
This would be handled by Razor now (which uses lsp rename).  Clsoing out.
