### ISSUE TITLE
AD0001 (KeyNotFoundException) from AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#38668]
**Version Used**:
16.3.0 Preview 3.0

**Steps to Reproduce**:
```csharp
using System.Text;

internal static class C1
{
    public const int A = 42;
}

internal class C2
{
    public int A { get; set; }
}

internal class C3
{
    public string M(C2 c2)
    {
        var result = new StringBuilder();
        switch (c2.A)
        {
            case C1.A:
                result.Append("A");
                break;
            default:
                result.Append("*");
                break;
        }
        return result.ToString();
    }
}
```

**Expected Behavior**:
No AD0001

**Actual Behavior**:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.	…		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: …
IOperation: ExpressionStatement
SyntaxTree: C:\Users\…\Test.cs
SyntaxNode: result.Append("A"); [ExpressionStatementSyntax]@[319..338) (20,16)-(20,35)

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.AnalyzeExpressionStatement(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Comment by Tragetaschen** [comment]
Do you have a (couple of) candidates, then I can check.

**Comment by mavasani** [comment]
> Is there a better way to check the contents of .editorconfig files?

I believe @sharwell had a tracking issue to create an IDE analyzer that validates our IDE options in .editorconfig files.

**Comment by Tragetaschen** [comment]
#19055

**Comment by OoLunar** [comment]
Good to know that it's an invalid editorconfig option. Are there plans to warn us which option is invalid instead of getting an unhelpful CSC KeyNotFound warning?

**Comment by CyrusNajmabadi** [comment]
@jmarolf Does thsi go away now that the user can set these with the editorconfig ui?  Does it tell you if you wrote things badly?

**Comment by jmarolf** [comment]
We don't have a mechanism to surface diagnostics in editorconfig yet if you manually edit the file, however if these options are set via the UI you should be "protected" from setting them to invalid values.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits.
