### ISSUE TITLE
IntroduceVariableCodeRefactoring Crash

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#38708]
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position,Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.CodeRefactoringHelpers.IsNodeUnderselected(SyntaxNode node,TextSpan selection)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.TryInitializeAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.GenerateAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

The selection here appears to be a little finicky, it need to be in the middle of some kind of nested expression, I think? Here's a screenshot of my selection:
![image](https://user-images.githubusercontent.com/2371880/64991005-db1ef580-d885-11e9-8cf5-0d61bcce5a57.png)
As far as I can tell, the offer to rename the method is unrelated, it's just showing that as I was simplifying my repro.

Raw code as well:
```cs
using System;
class C {
    public void M()
    {
        Console.WriteLine("Hello world");
        Console.WriteLine(new C());
    }
}
```

VS Version 29312.127 Int Preview

**Comment by CyrusNajmabadi** [comment]
tagging @petrroll .  Note: this may have been fixed already.

**Comment by yyjdelete** [comment]
Hit the same issue in VS16.4 Preview1.0

Select all text between `>` and `<`.
```cs
        public static void Method()
        {
            //>
            var str = "<aaa";
        }
```

**Comment by petrroll** [comment]
I assume the issue is that the `position` is outside of the Token passed into the `IsNodeUnderselected` which is also used as root for finding leftmost token. 

I thought I eliminated all instances where I used non-root Token as Token but this one must've slipped by.

**Comment by petrroll** [comment]
Hmm, that doesn't seem to be the issue: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeRefactoringHelpers.cs,34b38eefcd6d9c43

Can't immediately see how that can fail. That said, IIRC there should be an easier way (and faster) to get the first and last token of the Node. And switching to that solution might fix the issue as byproduct.

**Comment by miloush** [comment]
Just hit this one with VisualStudio.16.Preview/16.4.0-pre.1.0+29319.158

**Comment by miloush** [comment]
And here is a repro:
```C#
class Program
{
    static void Main()
    {
        Main();
    }
}
```

Select the semicolon only, either by double-clicking it or by keyboard.

**Comment by petrroll** [comment]
I have found the issue and have a fix ready, PR in an hour or so.

**Comment by petrroll** [comment]
Fix in https://github.com/dotnet/roslyn/pull/39091

cc: @mavasani

**Comment by jinujoseph** [comment]
reported in [DC ](https://developercommunity.visualstudio.com/content/problem/741935/introducevariablecoderefactoringprovider-crashed-w.html) , [DC](https://developercommunity.visualstudio.com/content/problem/767441/introducevariablecoderefactoringprovider-encounter-7.html)
