### ISSUE TITLE
MSBuildWorkspace shouldn't attempt to remove properties declared in an imported file

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#38971]
**Version Used**: 
16.3

**Steps to Reproduce**:

1. Use MSBuildWorkspace to load a project that uses https://github.com/onovotny/MSBuildSdkExtras

**Expected Behavior**:
Should work

**Actual Behavior**:
```
System.InvalidOperationException: Cannot modify an evaluated object originating in an imported file "C:\Users\Administrator\.nuget\packages\msbuild.sdk.extras\1.6.68\Build\Inference.targets".
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(Boolean condition, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Project.RemoveProperty(ProjectProperty property)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<GetProjectFileInfosAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectFileInfosAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

I suspect that this line is causing the issue:
https://github.com/dotnet/roslyn/blob/98ec28ef6f76a773a54a361ae939df51bcb9b92b/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L78

**Comment by KirillOsenkov** [comment]
The project is using https://www.nuget.org/packages/MSBuild.Sdk.Extras/1.6.68

**Comment by KirillOsenkov** [comment]
The solution being analyzed is https://github.com/unoplatform/uno

**Comment by jjcolumb** [comment]
Is there any workaround meanwhile?

**Comment by jjcolumb** [comment]
Will this be included in 16.5?

**Comment by jasonmalinowski** [comment]
@jjcolumb Once we close the bug we'll update the milestone accordingly. At this point the bug is still open, unfortunately. 😦

**Comment by KirillOsenkov** [comment]
See related https://github.com/dotnet/roslyn/issues/31011

**Comment by KirillOsenkov** [comment]
It appears that https://github.com/dotnet/roslyn/pull/39748 by @ltrzesniewski might have inadvertently fixed this issue as well??

**Comment by ltrzesniewski** [comment]
Yeah, I wouldn't be surprised if this issue and the one you linked both were solved in v16.5+. 😉

**Comment by jasonmalinowski** [comment]
The offending code doesn't exist anymore, so this is fixed.
