### ISSUE TITLE
Editor: syntax node is not within syntax tree

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39296]
**[Happens in 16.4.0-preview-3.0-[29409.185.master]**

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/774122/editor-syntax-node-is-not-within-syntax-tree.html)._

---
[regression] [worked-in:Not sure about prev, 16.3 works for sure]
1. Get latest Int Preview Visual Studio. 
1. git clone https://github.com/NuGet/NuGet.Client
1. Follow the instructions up to configure.ps1
1. Open NuGet.sln in Visual Studio. 

After the solution was fully loaded the moment I started type, a yellow bar popped with, 
an error occured, see log file. Clicking on that opens the activity log in the default xml viewer. 

In there I found the below. 
Note that there could be other problems, but this error was related to types of issues I was seeing. 

```
&lt;entry&gt;
    &lt;record&gt;2738&lt;/record&gt;
    &lt;time&gt;2019/10/11 18:15:44.663&lt;/time&gt;
    &lt;type&gt;Error&lt;/type&gt;
    &lt;source&gt;Editor or Editor Extension&lt;/source&gt;
    &lt;description&gt;System.AggregateException: One or more errors occurred. ---&amp;gt; System.ArgumentException: Syntax node is not within syntax tree&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetRelatedFieldSymbolAsync&amp;gt;d__7.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetDocumentationFromSymbolAsync&amp;gt;d__5.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetQuickInfoItemAsync&amp;gt;d__4.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&amp;lt;ComputeSourceContentAsync&amp;gt;d__39.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&amp;#x000D;&amp;#x000A;   --- End of inner exception stack trace ---&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&amp;lt;UpdateAsync&amp;gt;d__32.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.&amp;lt;UpdateAsync&amp;gt;d__5.MoveNext()&amp;#x000D;&amp;#x000A;---&amp;gt; (Inner Exception #0) System.ArgumentException: Syntax node is not within syntax tree&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetRelatedFieldSymbolAsync&amp;gt;d__7.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetDocumentationFromSymbolAsync&amp;gt;d__5.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at SyntaxTree.VisualStudio.Unity.Documentation.UnityQuickInfoSource.&amp;lt;GetQuickInfoItemAsync&amp;gt;d__4.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&amp;lt;ComputeSourceContentAsync&amp;gt;d__39.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&amp;lt;---&amp;#x000D;&amp;#x000A;&lt;/description&gt;
  &lt;/entry&gt;
```

---
#### Visual Studio Feedback System on 10/11/2019, 08:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/15/2019, 02:09 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I just hit this in 16.6 Preview 3 with a slightly different stack:

```
Syntax node is not within syntax tree
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.QuickInfo.CSharpSemanticQuickInfoProvider.TryGetNullabilityAnalysis(Workspace workspace, SemanticModel semanticModel, SyntaxToken token, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<CreateContentAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<BuildQuickInfoAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoServiceWithProviders.<GetQuickInfoAsync>d__5.MoveNext()
```

**Comment by sharwell** [comment]
@JoeRobich just hit this again

**Comment by sharwell** [comment]
@JoeRobich I just hit this again. Same stack as https://github.com/dotnet/roslyn/issues/39296#issuecomment-616531844.

**Comment by sharwell** [comment]
@JoeRobich I just hit this again

**Comment by ooples** [comment]
@JoeRobich I also got this error using the latest visual studio preview version
```
at 
Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode 
syntax)<BR>at 
Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(VariableDeclaratorSyntax 
declarationSyntax, CancellationToken cancellationToken)<BR>at 
Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(SyntaxNode 
node, CancellationToken cancellationToken)<BR>at 
Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.LookupSymbol()<BR>at 
Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeVariable.GetSymbolType()<BR>at 
Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeVariable.get_Type()<BR>at 
EnvDTE.CodeVariable.get_Type()<BR>at 
Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomParser.OnTypePopulateMembers(Object 
sender, EventArgs e)<BR>at 
System.CodeDom.CodeTypeDeclaration.get_Members()<BR>at 
Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomParser.CodeTypeDeclarationPopulator.OnPopulateMembers(Object 
sender, EventArgs e)<BR>at 
System.CodeDom.CodeTypeDeclaration.get_Members()<BR>at 
Microsoft.WinForms.DesignTools.Client.Loader.RemoteCodeDomDesignerLoader.EnsureInitializeComponentStatementsPopulated()<BR>at 
Microsoft.WinForms.DesignTools.Client.Loader.RemoteCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager 
manager)<BR>at 
Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager 
serializationManager)<BR>--- End of stack trace from previous location where 
exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager 
serializationManager)<BR>at 
System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost 
host)
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't gotten a report of this in 4 years, and tehre's nothing in prism for this.
