### ISSUE TITLE
ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39328]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/547144/extractinterfacecoderefactoringprovider-encountere.html)._

---
This happens everytime. The class that I am trying to extract interface from is defined in a shared project (shproj).

The stack trace:
```
System.AggregateException : One or more errors occurred. ---&gt; Files and folders cannot be:
- Empty strings 
- System reserved names, including 'CON', 'AUX', PRN', 'COM1' or 'LPT2' 
- contain only '.'
- have any of the following characters: / ? : &amp; \ * &quot; &lt; &gt; | # %
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass18_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---&gt; (Inner Exception #0) System.InvalidOperationException : Files and folders cannot be:
- Empty strings 
- System reserved names, including 'CON', 'AUX', PRN', 'COM1' or 'LPT2' 
- contain only '.'
- have any of the following characters: / ? : &amp; \ * &quot; &lt; &gt; | # %
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Utilities.ValidateFileName(IServiceProvider serviceProvider,String filePath)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.&lt;&gt;c__DisplayClass2_0.&lt;AddFolder&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.&lt;&gt;c__DisplayClass68_0`1.&lt;Mutate&gt;b__0[T](&lt;Unknown Parameters&gt;)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.&lt;&gt;c__DisplayClass569_0.&lt;Mutate&gt;b__0(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction,Boolean includesFileSystemChange,String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.Mutate[T](Func`1 asyncAction,Boolean includesFileSystemChange,String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFolder(String name,String kind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.CreateFolder(ProjectItems currentItems,String container)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.Extensions.ProjectExtensions.FindOrCreateFolder(Project project,IEnumerable`1 containers)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToFolder(AbstractProject hostProject,Project project,DocumentId documentId,IEnumerable`1 folders,String documentName, SourceCodeKind sourceCodeKind,SourceText initialText,String filePath,Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,Boolean isAdditionalDocument)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentAdded(DocumentInfo info,SourceText text)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;---
```

---
#### Visual Studio Feedback System on 4/26/2019, 00:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/6/2019, 04:37 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by beccamc** [comment]
I see Extract Interface working in a .shproj. 
![extract](https://user-images.githubusercontent.com/9122518/232619214-1a290f88-8f7a-4411-8642-4e9bc41c4c57.gif)

From the error message, it looks like the class name is not valid for a new file. Without more information on the class name this cannot be investigated. Given this item is 3+ years old, closing.

**Comment by beccamc** [comment]
Actually it looks like this is still an issue - check out 36706 for updates
