### ISSUE TITLE
VB.NET Return Await causes code fix providers to crash in 16.3.4

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39333]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/776481/vbnet-return-await-causes-code-fix-providers-to-cr.html)._

---
I am able to reproduce in a new VB.NET console application targetting .NET Framework 4.7.2, and typing the following into the default Module1.vb module - how fast you type varies when exactly the errors show.  This seems to be triggered by `Return Await`, since just `Return something` doesn't seem to cause the errors.

```
Module Module1

    Sub Main()

    End Sub

End Module

Class Testing

    Private Async Function WaitForIt() As Task(Of Boolean)
        Return Await tas  '&lt;-- crashes here, was starting to type Task.Delay(1000)
    End Function

End Class
```

I first see an exception message at the top:

An exception of type ArgumentException has been encountered.  This may be cause by an extension.

Log file attached for that.  Then several code fix providers crash.

'GenerateParameterizedMemberCodeFixProvider' encountered an error and has been disabled.
'VisualBasicGenerateVariableCodeFixProvider' encountered an error and has been disabled.
'VisualBasicSpellCheckCodeFixProvider' encountered an error and has been disabled.

Stack traces in the order listed above...

```
System.ArgumentException : Not a VB symbol.
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SymbolExtensions.EnsureVbSymbolOrNothing[TSource,TDestination](TSource symbol,String paramName)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ConstructTypeArguments(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.INamedTypeSymbol_Construct(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicTypeInferenceService.TypeInferrer._Closure$__19-0._Lambda$__0(TypeInferenceInfo t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.&lt;DistinctIterator&gt;d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.Filter(IEnumerable`1 types,Boolean filterUnusable)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.InferTypes(SyntaxNode expression,Boolean filterUnusable)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.InferTypes(SemanticModel semanticModel,SyntaxNode expression,String nameOpt,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferTypes(ITypeInferenceService service,SemanticModel semanticModel,SyntaxNode expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.TryInitializeSimpleName(TService service,SemanticDocument semanticDocument,TSimpleNameSyntax simpleName,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.TryInitializeMethodAsync(TService service,SemanticDocument document,SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.GenerateMethodStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.GenerateMethodAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

```
System.ArgumentException : Not a VB symbol.
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SymbolExtensions.EnsureVbSymbolOrNothing[TSource,TDestination](TSource symbol,String paramName)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ConstructTypeArguments(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.INamedTypeSymbol_Construct(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicTypeInferenceService.TypeInferrer._Closure$__19-0._Lambda$__0(TypeInferenceInfo t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.&lt;DistinctIterator&gt;d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.Filter(IEnumerable`1 types,Boolean filterUnusable)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.InferTypes(SyntaxNode expression,Boolean filterUnusable)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.InferTypes(SemanticModel semanticModel,SyntaxNode expression,String nameOpt,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.State.DetermineFieldType(SemanticDocument semanticDocument,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.State.TryInitializeSimpleName(TService service,SemanticDocument semanticDocument,TSimpleNameSyntax simpleName,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.State.TryInitializeAsync[TService,TSimpleNameSyntax,TExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.State.GenerateAsync[TService,TSimpleNameSyntax,TExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateVariable.AbstractGenerateVariableService`3.GenerateVariableAsync[TService,TSimpleNameSyntax,TExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

```
System.ArgumentException : Not a VB symbol.
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SymbolExtensions.EnsureVbSymbolOrNothing[TSource,TDestination](TSource symbol,String paramName)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ConstructTypeArguments(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.INamedTypeSymbol_Construct(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicTypeInferenceService.TypeInferrer._Closure$__19-0._Lambda$__0(TypeInferenceInfo t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.&lt;DistinctIterator&gt;d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService.InferTypes(SemanticModel semanticModel,Int32 position,String nameOpt,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext.ComputeInferredTypes(Workspace workspace,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext..ctor(Workspace workspace,SemanticModel semanticModel,Int32 position,SyntaxToken leftToken,SyntaxToken targetToken,Boolean isTypeContext,Boolean isNamespaceContext,Boolean isNamespaceDeclarationNameContext,Boolean isPreProcessorDirectiveContext,Boolean isRightOfNameSeparator,Boolean isStatementContext,Boolean isAnyExpressionContext,Boolean isAttributeNameContext,Boolean isEnumTypeMemberAccessContext,Boolean isNameOfContext,Boolean isInQuery,Boolean isInImportsDirective,Boolean isWithinAsyncMethod,Boolean isPossibleTupleContext,Boolean isPatternContext,Boolean isRightSideOfNumericType,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext..ctor(Workspace workspace,SemanticModel semanticModel,Int32 position,SyntaxToken leftToken,SyntaxToken targetToken,SyntaxToken touchingToken,Boolean isTypeContext,Boolean isNamespaceContext,Boolean isNamespaceDeclarationNameContext,Boolean isPreProcessorDirectiveContext,Boolean isRightOfNameSeparator,Boolean isSingleLineStatementContext,Boolean isExpressionContext,Boolean isAttributeNameContext,Boolean isEnumTypeMemberAccessContext,Boolean isNameOfContext,Boolean isInLambda,Boolean isInQuery,Boolean isInImportsDirective,Boolean isCustomEventContext,Boolean isPossibleTupleContext,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery.VisualBasicSyntaxContext.VB$StateMachine_19_CreateContextAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.VisualBasic.Completion.Providers.KeywordCompletionProvider.VB$StateMachine_2_CreateContextAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.RecommendCompletionItemsAsync[TContext](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetUnionItemsFromDocumentAndLinkedDocumentsAsync[T](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.ProvideCompletionsAsync[TContext](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 10/14/2019, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Reproduced in 16.4 preview 2. Related to #36517
