### ISSUE TITLE
Syntax Visualizer - View Directed Graph causes VS 2019 (16.3) to crash

### ISSUE THREAD

**Issue by jwooley** [dotnet/roslyn#39343]
**Version Used**:  16.3.4

**Steps to Reproduce**:
Install the Visual Studio Extension Development workload
Add components for "Code Map" , "DGML Editor", and ".NET Compiler Platform SDK"
Open a C# Code file.
Open View -> Other Window -> Syntax Visualizer
Select a variable declaration statement in the C# code.
Right click on the node in the visualizer and select View Directed Syntax Graph. 
Visual Studio crashes and reboots.

From the event log:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Resources.MissingManifestResourceException
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at Roslyn.SyntaxVisualizer.DgmlHelper.My.Resources.Resources.get_SyntaxNodeLabel()
   at Roslyn.SyntaxVisualizer.DgmlHelper.SyntaxDgmlHelper.GetLabelForNode(Microsoft.CodeAnalysis.SyntaxNode)
   at Roslyn.SyntaxVisualizer.DgmlHelper.SyntaxDgmlHelper.ProcessNode(Roslyn.SyntaxVisualizer.DgmlHelper.SyntaxDgmlOptions, Microsoft.CodeAnalysis.SyntaxNode, System.Xml.Linq.XElement, Int32 ByRef, System.Xml.Linq.XElement, System.Xml.Linq.XElement, System.Collections.Generic.HashSet`1<System.String>)
   at Roslyn.SyntaxVisualizer.DgmlHelper.SyntaxDgmlHelper.ToDgml(Microsoft.CodeAnalysis.SyntaxNode, Roslyn.SyntaxVisualizer.DgmlHelper.SyntaxDgmlOptions)
   at Roslyn.SyntaxVisualizer.Extension.SyntaxVisualizerContainer.DisplaySyntaxNodeDgml(Microsoft.CodeAnalysis.SyntaxNode)
   at Roslyn.SyntaxVisualizer.Control.SyntaxVisualizerControl.DirectedSyntaxGraphMenuItem_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Expected Behavior**:
Visualizer should appear

**Actual Behavior**:
VS Reboots

**Comment by jwooley** [comment]
Also crashing on 16.4.0 preview 2.0.
