### ISSUE TITLE
Live Unit Testing fails with 'FatalError - System.ArgumentException: Syntax tree already present'

### ISSUE THREAD

**Issue by prosser** [dotnet/roslyn#39577]
**Version Used**: 16.3.7

**Steps to Reproduce**:

1. Load solution with SDK-style project targeting net462. Ours also has included .props and .targets, including those injected by .nupkg with custom build tasks.
2. Start LUT

**Expected Behavior**:
LUT starts as expected

**Actual Behavior**:
Error and LUT does not start.

[15:43:05.756 Error] - FatalError - System.ArgumentException: Syntax tree already present
Parameter name: trees[136]
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonAddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.CompilationComparer.GetUpdatedCompilation(Compilation compilation, CommandLineArguments arguments, Logger logger, BuildDifference& differences)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.EmitHelper.<EmitAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildService.<EmitSingleProjectAsync>d__57.MoveNext()
[15:43:05.761 Info] Build completed with failures. Errors were logged under '<redacted>\v16\lut\0\diag\'.
[15:43:21.477 Info] Live Unit Testing stopped.

**Comment by prosser** [comment]
Git repo is available by request, please contact directly.
