### ISSUE TITLE
MisplacedUsingDirectivesDiagnosticAnalyzer ' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39599]
**Version Used**: 
Version 16.5.0 Preview 1.0 [29429.152.master]

**Steps to Reproduce**:

``` C#
namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package
{
    using System;
    using System.Collections.Immutable;
    using System.ComponentModel.Composition;
    using System.Diagnostics.CodeAnalysis;
    using System.Diagnostics.Contracts;
    using System.Threading;
    using Microsoft.VisualStudio.Shell.Interop;
```

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'.	Microsoft.VisualStudio.ProjectSystem.VS.Implementation		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\VsProjectTypeValuesCacheService.cs
SyntaxNode: namespace Microsoft.VisualStudio ... [NamespaceDeclarationSyntax]@[314..24814) (6,0)-(495,1)

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.SequenceEqualComparer.Equals(List`1 x, List`1 y)
   at Microsoft.CodeAnalysis.ConcurrentCache`2.TryAdd(TKey key, TValue value)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(String sourcePath)
   at Microsoft.CodeAnalysis.ProjectState.WorkspaceAnalyzerConfigOptionsProvider.GetOptions(SyntaxTree tree)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.GetFilteredDiagnostic(Diagnostic diagnostic, Compilation compilation, AnalyzerOptions analyzerOptions)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass117_0.<GetDiagnosticSink>b__0(Diagnostic diagnostic, DiagnosticAnalyzer analyzer, Boolean isSyntaxDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.AnalyzerDiagnosticReporter.AddDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.ReportDiagnostics(SyntaxNodeAnalysisContext context, DiagnosticDescriptor descriptor, IEnumerable`1 usingDirectives, CodeStyleOption`1 option)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by jnm2** [comment]
I just hit this same stack trace (from GetOptionsForSourcePath up) from CSharpUseIsNullCheckForReferenceEqualsDiagnosticAnalyzer:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.UseIsNullCheck.CSharpUseIsNullCheckForReferenceEqualsDiagnosticAnalyzer' threw an exception of type 'System.AggregateException' with message 'One or more errors occurred.'.	NUnit.TestAdapter.Tests (net46)		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.UseIsNullCheck.CSharpUseIsNullCheckForReferenceEqualsDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: NUnit.VisualStudio.TestAdapter.Tests
SyntaxTree: C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnitTestAdapterTests\DumpXmlTests.cs
SyntaxNode: nameof(DumpXml) [InvocationExpressionSyntax]@[1497..1512) (29,14)-(29,29)

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.SequenceEqualComparer.Equals(List`1 x, List`1 y)
   at Microsoft.CodeAnalysis.ConcurrentCache`2.TryAdd(TKey key, TValue value)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(String sourcePath)
   at Microsoft.CodeAnalysis.DocumentState.<GetAnalyzerOptionsAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Options.EditorConfig.EditorConfigDocumentOptionsProviderFactory.EditorConfigDocumentOptionsProvider.<GetOptionsForDocumentAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.<GetUpdatedOptionSetForDocumentAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<>c__DisplayClass37_0.<<InitializeCachedOptions>b__0>d.MoveNext()'.
```

**Comment by sharwell** [comment]
@agocke I'm seeing a bunch of reports for this from different teams. Is it something you are familiar with?

**Comment by agocke** [comment]
Nope, looking now
