### ISSUE TITLE
Default interface implementation fails with NRE when using generic parameters

### ISSUE THREAD

**Issue by saltukkos** [dotnet/roslyn#39692]
**Version Used**: 
netcore 3.0, Visual Studio 16.3.5

**Steps to Reproduce**:

1. Write the interface like this: 
 ```
    public interface IFoo<T>
    {
        sealed Type GetItemType() => typeof(T);
    }
```
2. Implement this interface and create instance of your class
3. Call method `GetItemType()` 

**Expected Behavior**:
The same result which returned by non-sealed version of this method (returns `T` from implementation class) or compile-time error

**Actual Behavior**:
Runtime throws NRE when accessing type of `T`

**Comment by jaredpar** [comment]
@AlekseyTs PTAL

**Comment by AlekseyTs** [comment]
I am not able to reproduce this in Visual Studio Version 16.5.0 Preview 1.0 [29427.7.master] in a project targeting netcoreapp3.1.

The following app:
```
using System;

namespace ConsoleApp5
{
    class Program : I1<int>
    {
        static void Main(string[] args)
        {
            Console.WriteLine(((I1<int>)new Program()).GetItemType1());
            Console.WriteLine(((I1<int>)new Program()).GetItemType2());
            Console.WriteLine(I1<int>.GetItemType3());
            Console.WriteLine("Done!");
        }
    }
}


public interface I1<T>
{
    sealed Type GetItemType1() => typeof(T);
    Type GetItemType2() => typeof(T);
    static Type GetItemType3() => typeof(T);
}
```

runs successfully and prints:
```
System.Int32
System.Int32
System.Int32
Done!
```

**Comment by saltukkos** [comment]
@AlekseyTs you need to instantiate this with any reference type, looks that problem connected with shared `System.__Canon` instantiations.

**Comment by AlekseyTs** [comment]
@saltukkos 
> you need to instantiate this with any reference type, looks that problem connected with shared System.__Canon instantiations.

Tried with ```string``` and ```System.Action``` types, still works as expected. Please provide complete repro scenario so that we can simply do copy/paste, build, run, observe. Thanks.

**Comment by saltukkos** [comment]
I created a sample solution https://github.com/saltukkos/csharp8-interface-implementation-bug

**Comment by AlekseyTs** [comment]
I can repro the crash now. It looks like the presence of the local is significant. For code below, ```Test1``` works fine, but ```Test2``` throws, even though they are roughly equivalent in what they are doing.
```
using System;

namespace Sample
{
    public sealed class C1 : I1<string>
    {
    }

    class Program
    {
        static void Main(string[] args)
        {
            Test1();
            Test2();
        }

        private static void Test1()
        {
            Console.WriteLine(((I1<string>)new C1()).GetItemType());
        }

        private static void Test2()
        {
            I1<string> c1 = new C1();
            Console.WriteLine(c1.GetItemType());
        }
    }
}

public interface I1<T>
{
    sealed Type GetItemType() => typeof(T);
}
``` 

Observed:
```
System.String
Unhandled exception. System.NullReferenceException: Object reference not set to
an instance of an object.
   at I1`1.GetItemType()
   at Sample.Program.Test2()
   at Sample.Program.Main(String[] args)
```

Here is an IL for the methods:
```
.method private hidebysig static void  Test1() cil managed
{
  // Code size       16 (0x10)
  .maxstack  8
  IL_0000:  newobj     instance void Sample.C1::.ctor()
  IL_0005:  call       instance class [System.Runtime]System.Type class I1`1<string>::GetItemType()
  IL_000a:  call       void [System.Console]System.Console::WriteLine(object)
  IL_000f:  ret
} // end of method Program::Test1

.method private hidebysig static void  Test2() cil managed
{
  // Code size       16 (0x10)
  .maxstack  8
  IL_0000:  newobj     instance void Sample.C1::.ctor()
  IL_0005:  callvirt   instance class [System.Runtime]System.Type class I1`1<string>::GetItemType()
  IL_000a:  call       void [System.Console]System.Console::WriteLine(object)
  IL_000f:  ret
} // end of method Program::Test2
```

The IL looks reasonable to me. The only difference is that ```Test2``` uses ```callvirt``` to call the interface method even though the method is not virtual, which should be perfectly legal. This looks like an issue with runtime rather than with compiler.

**Comment by jaredpar** [comment]
Should we move this issue over to coreclr then?

**Comment by AlekseyTs** [comment]
> Should we move this issue over to coreclr then?

I already opened one https://github.com/dotnet/coreclr/issues/27739.

**Comment by AlFasGD** [comment]
Issue still persists in VS 2019 Community 16.5.0 Preview 1.0, targetting both .NET Core 3.0 and 3.1.
