### ISSUE TITLE
Cannot f5 latest roslyn.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#39702]
I get:

```
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.LiveShare.LanguageServices.16.3, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.          c:\users\cyrus\appdata\local\microsoft\visualstudio\16.0_bd1a5c57roslyndev\extensions\microsoft\roslyn language services\42.42.42.4242424\Microsoft.VisualStudio.LanguageServices.LiveShare.dll
```

What is this dll and how can someone external f5 without it?  thanks!

**Comment by CyrusNajmabadi** [comment]
tagging @jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
@dibarbet?

**Comment by dibarbet** [comment]
16.4 P3?  Is the error presenting itself outside of the MEF log?  I'm not personally seeing it in the MEF log, and F5'ing is working normally.  [My 16.4 P3 mef log](https://gist.github.com/dibarbet/db8da97fb65579684e6e3a7b5e006a30#file-16_4_p3_roslyndev_err-txt).
It's a liveshare dll, so if liveshare is uninstalled then that could be one way it would be missing, but liveshare ships in box.  I also don't know exactly why you'd see that in F5, it should only be trying to load that dll if you start a liveshare session.

Two possible suggestions - cleaning the hive and uninstall / re-install liveshare (easiest way is probably through modify on the vs launcher).

**Comment by CyrusNajmabadi** [comment]
Also have mef composition erorrs lke:

```
----- Catalog construction errors -----
Error #1
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.VisualStudio.LanguageServices.LiveShare.Client.CSharpLspClientServiceFactory". ---> Microsoft.VisualStudio.Composition.PartDiscoveryException: Part discovery failed at member <ActiveLanguageServerClient>k__BackingField. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.LiveShare.LanguageServices.Guest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at Microsoft.VisualStudio.Composition.ReflectionHelpers.GetMemberType(MemberInfo fieldOrPropertyOrType)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.AddImportsFromMembers(PropertyInfo[] declaredProperties, FieldInfo[] declaredFields, TypeRef partTypeRef, IList`1 imports)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.AddImportsFromMembers(PropertyInfo[] declaredProperties, FieldInfo[] declaredFields, TypeRef partTypeRef, IList`1 imports)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass31_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace ---
Error #2
```

**Comment by CyrusNajmabadi** [comment]
> 16.4 P3

No. 16.4p2.  Is p3 a requirement to work on roslyn?  If so *can you guys please publish this somewhere*.

**Comment by dibarbet** [comment]
>  Is p3 a requirement to work on roslyn?

Nope!  I haven't encountered this on P2 either.  All of those dlls ship in-box with VS.  Main thing I can think of is that the liveshare extension upgrade process is somehow busted.  Would suggest cleaning the hive and re-installing the liveshare component to see if it continues.  If that works, let me know and I'll followup with them to get it fixed.

**Comment by CyrusNajmabadi** [comment]
> Would suggest cleaning the hive 

What does thsi mean *specifically*.  I do not want to hork my vs install.  htat happened just a few weeks ago and i had to wipe my machine to get back into a working state.  I don't want to ahve to do that again.

**Comment by dibarbet** [comment]
I generally delete all the RoslynDev hive directories in `%localappdata%\Microsoft\VisualStudio` when I encounter issues like this.  E.g., for my preview 3 install it's `C:\Users\dabarbet\AppData\Local\Microsoft\VisualStudio\16.0_ea3e8983RoslynDev`.  It should get re-created whenever you F5 again.

I have a hunch that re-installing liveshare will be the more impactful change, so would try that first if you're (rightfully... 😄 ) wary of deleting random VS directories.

**Comment by CyrusNajmabadi** [comment]
Ok.  I will try that.

**Comment by CyrusNajmabadi** [comment]
@dibarbet i have wiped my hive.  it didn't help.  How do i get rid of liveshare?  i can't find anything in the vs installer related to it.

**Comment by CyrusNajmabadi** [comment]
Note: it's not even installed:

![image](https://user-images.githubusercontent.com/4564579/68262387-04434300-fff8-11e9-8426-069f1df823aa.png)

**Comment by CyrusNajmabadi** [comment]
are we basically busted if this optional component isn't intalled?  did we take a hard dependency on it somehow?

**Comment by dibarbet** [comment]
Ah!  That would explain why the dll is missing.  I believe installing it would be a good work around for now.

You don't generally need liveshare to be installed for just running VS, as the roslyn liveshare components should only try to load once a liveshare session is started.  But from what you are seeing, it's possible that you may need them now to actually F5 roslyn.  If that's the case, it wasn't intentional.  I'll check tomorrow if we actually need that hard dependency or if it's a bug.

Liveshare is by default installed in-box nowadays, so unless someone goes out of their way to uninstall the extension, it should be present.

**Comment by CyrusNajmabadi** [comment]
> Liveshare is by default installed in-box nowadays, so unless someone goes out of their way to uninstall the extension, it should be present.

i didn't do anything intentional.  i just dont' install components i don't think i need.  LiveShare looks to be optional.  So we need to remove our dependency on it from our load paths.  Thanks!

**Comment by CyrusNajmabadi** [comment]
I can't load RoslynPackage at all now:

```

A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: This part (Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace) cannot be instantiated.   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.ThrowPartNotInstantiableException()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() |   |   | Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost | 2019/11/06 02:41:20.562
-- | -- | -- | -- | --
467 | ERROR | A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: This part (Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace) cannot be instantiated.   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.ThrowPartNotInstantiableException()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() |   |   | Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost | 2019/11/06 02:41:20.580
468 | ERROR | SetSite failed for package [RoslynPackage]Source: 'Microsoft.VisualStudio.Composition' Description: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace". ---> Microsoft.VisualStudio.Composition.CompositionFailedException: This part (Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace) cannot be instantiated.   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.ThrowPartNotInstantiableException()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Options.GlobalOptionService.LoadOptionFromSerializerOrGetDefault(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.WorkspaceOptionSet.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.WorkspaceOptionSet.WithChangedOption(OptionKey optionAndLanguage, Object value)   at Microsoft.CodeAnalysis.Options.OptionSet.WithChangedOption[T](Option`1 option, T value)   at Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace..ctor(HostServices hostServices)   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl..ctor(ExportProvider exportProvider, IAsyncServiceProvider asyncServiceProvider)   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace..ctor(ExportProvider exportProvider, Lazy`1 streamingPresenter, IAsyncServiceProvider asyncServiceProvider)    --- End of inner exception stack trace ---   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass71_1`2.<GetExports>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()   at Microsoft.VisualStudio.LanguageServices.Setup.RoslynPackage.<InitializeAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskComplete(Task task, CancellationToken cancel, Int32 ms)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_1.<InternalGetResult>b__1()   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_0.<InternalGetResult>b__0()   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass108_0.<InvokeWithWaitDialog>b__0()   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult()Microsoft.VisualStudio.Composition.CompositionFailedException: This part (Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace) cannot be instantiated.   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.ThrowPartNotInstantiableException()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Options.GlobalOptionService.LoadOptionFromSerializerOrGetDefault(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.WorkspaceOptionSet.GetOption(OptionKey optionKey)   at Microsoft.CodeAnalysis.Options.WorkspaceOptionSet.WithChangedOption(OptionKey optionAndLanguage, Object value)   at Microsoft.CodeAnalysis.Options.OptionSet.WithChangedOption[T](Option`1 option, T value)   at Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace..ctor(HostServices hostServices)   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl..ctor(ExportProvider exportProvider, IAsyncServiceProvider asyncServiceProvider)   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace..ctor(ExportProvider exportProvider, Lazy`1 streamingPresenter, IAsyncServiceProvider asyncServiceProvider) | {6CF2E545-6109-4730-8883-CF43D7AEC3E1} | 80131500 | VisualStudio | 2019/11/06 02:41:20.595
469 | ERROR | End package load [RoslynPackage]

```

**Comment by CyrusNajmabadi** [comment]
@jinujoseph This is proving to be a complete blocker.  No amount of work to try to fix VS is helping here.

**Comment by CyrusNajmabadi** [comment]
I also now have two of these:

![image](https://user-images.githubusercontent.com/4564579/68265292-7ae43e80-0000-11ea-911b-a9b4c200ee37.png)

**Comment by CyrusNajmabadi** [comment]
I wiped my machine and got things up and running.  Going to bed now.  No clue what the root cause was, but something about VS/LiveShare/XamlEditor was super super super unhappy.

**Comment by sharwell** [comment]
> I also now have two of these:

I always seem to have that

**Comment by dibarbet** [comment]
The two c#_lsp options has to do with razor / liveshare content type switching.  I'm working on getting rid of c#_lsp all together for 16.5P1.

Will also look into why liveshare is required to F5 roslyn.
