### ISSUE TITLE
Bad KeyValuePair deconstruction crashes VS in '#nullable enable' context

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#39857]
**Version Used**: 16.4.0 Preview 2.0, .NET Core 3.1.0-preview2.19525.6

**Steps to Reproduce**:

1. Create new console app project (.NET Core)
2. Paste following code:
```cs
#nullable enable
using System.Collections.Generic;

namespace Test {
    class Test {
        private readonly Dictionary<string, string> _dictionary;
        public void Crash() {
            string value;
            foreach((string key, value) in _dictionary) {
            }
        }
    }
}
```

**Expected Behavior**: Nothing happened

**Actual Behavior**: VS crashes

**Comment by RikkiGibson** [comment]
I can't repro this in 16.5-preview1 but I can repro in 16.4-preview5.

Here's exception details for 16.4-preview5:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.CSharp
  StackTrace:
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.AsMember(NamedTypeSymbol newOwner) in /_/src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:line 822
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitDeconstructMethodArguments(ArrayBuilder`1 variables, Conversion conversion, BoundExpression right, Nullable`1 rightResultOpt) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 6095
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitDeconstructionAssignmentOperator(BoundDeconstructionAssignmentOperator node, Nullable`1 rightResultOpt) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 6054
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitForEachIterationVariables(BoundForEachStatement node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 6893
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitForEachStatement(BoundForEachStatement node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 2272
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitForEachStatement(BoundForEachStatement node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1578
   at Microsoft.CodeAnalysis.CSharp.BoundForEachStatement.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 3355
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 326
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 314
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1770
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatement(BoundStatement statement) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1793
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1549
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2571
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 326
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 314
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1770
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitMethodBodies(BoundBlock blockBody, BoundBlock expressionBody) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 2988
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 2907
   at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 7311
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 326
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 314
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 1770
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.Scan(Boolean& badRegion) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 379
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 439
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.Analyze(Boolean& badRegion, Optional`1 initialState) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:line 397
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, VariableState initialState, Builder snapshotBuilderOpt) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 665
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, Conversions conversions, DiagnosticBag diagnostics, Boolean useMethodSignatureParameterTypes, MethodSymbol delegateInvokeMethodOpt, VariableState initialState, Builder analyzedNullabilityMapOpt, Builder snapshotBuilderOpt, ArrayBuilder`1 returnTypesOpt) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 646
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols) in /_/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:line 488
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1677
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 981
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 507
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 385
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument) in /_/src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:line 575
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 362
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 339
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument) in /_/src/Compilers/CSharp/Portable/Symbols/NamespaceSymbol.cs:line 135
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 362
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 148
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2410
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2542
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:line 134
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GenerateCompilationEvents(AnalysisScope analysisScope, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 798
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GenerateCompilationEventsAndPopulateEventsCacheAsync>d__58.MoveNext() in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 784
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__57.MoveNext() in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 688

  This exception was originally thrown at this call stack:
    Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.AsMember(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) in MethodSymbol.cs
    Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitDeconstructMethodArguments(Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.CSharp.NullableWalker.DeconstructionVariable>, Microsoft.CodeAnalysis.CSharp.Conversion, Microsoft.CodeAnalysis.CSharp.BoundExpression, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithState?) in NullableWalker.cs
    Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitDeconstructionAssignmentOperator(Microsoft.CodeAnalysis.CSharp.BoundDeconstructionAssignmentOperator, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithState?) in NullableWalker.cs
    Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitForEachIterationVariables(Microsoft.CodeAnalysis.CSharp.BoundForEachStatement) in NullableWalker.cs
    Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitForEachStatement(Microsoft.CodeAnalysis.CSharp.BoundForEachStatement) in NullableWalker.cs
    Microsoft.CodeAnalysis.CSharp.BoundForEachStatement.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) in BoundNodes.xml.Generated.cs
    Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) in NullableWalker.cs
    ...
    [Call Stack Truncated]
```

**Comment by RikkiGibson** [comment]
Hi @ronnygunawan, it looks like VS 16.5 preview 1 is out, it would be really helpful if you could try to reproduce this bug, and if you can't repro then I think we can close this out.

**Comment by ronnygunawan** [comment]
I can no longer repro this in 16.5 preview 1. Thanks.
