### ISSUE TITLE
"This program location is thought to be unreachable" from CSharpInvertIfCodeRefactoringProvider

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#39993]
**Version Used**: 16.4-p6

```
System.InvalidOperationException : This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(DeclarationExpressionSyntax declarationExpression,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics,ArgumentSyntax argumentSyntax,Boolean allowArglist,RefKind refKind)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result,DiagnosticBag diagnostics,Boolean& hadError,Boolean& hadLangVersionError,ArgumentSyntax argumentSyntax,Boolean allowArglist,Boolean isDelegateCreation)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,DiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSpeculativelyBoundExpression(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,Binder& binder,ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSpeculativelyBoundExpression(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption,Binder& binder,ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSpeculativeSymbolInfo(SemanticModel semanticModel,Int32 position,ExpressionSyntax expression,SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpExtensionMethodReducer.TryReduceExtensionMethod(InvocationExpressionSyntax node,SemanticModel semanticModel,InvocationExpressionSyntax rewrittenNode,SimpleNameSyntax expressionName)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpExtensionMethodReducer.SimplifyExtensionMethod(InvocationExpressionSyntax node,SemanticModel semanticModel,OptionSet optionSet,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyNode[TNode](TNode node,SyntaxNode newNode,SyntaxNode parentNode,Func`5 simplifier)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.SimplifyExpression[TExpression](TExpression expression,SyntaxNode newNode,Func`5 simplifier)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpExtensionMethodReducer.Rewriter.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIfStatement(IfStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.AbstractCSharpReducer.AbstractReductionRewriter.VisitNodeOrToken(SyntaxNodeOrToken nodeOrToken,SemanticModel semanticModel,Boolean simplifyAllDescendants)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.<>c__DisplayClass10_1.<ReduceAsync>b__0[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.ReduceAsyncInternal[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.AbstractSimplificationService`3.ReduceAsync[TExpressionSyntax,TStatementSyntax,TCrefSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Simplification.Simplifier.ReduceAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.CleanupDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.PostProcessChangesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.PostProcessAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Current file. NRTs enabled, Ctrl+. at the beginning of `if (!MetadataTokens` and preview the 'Invert if' option:

```cs
using System;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;

namespace RefAssemblyGen
{
    internal sealed class MetadataEditList
    {
        private static readonly object OriginalRowMarker = new object();

        private readonly IndexedLookup<object>[] tables;
        private readonly MetadataReader reader;

        public MetadataEditList(MetadataReader reader)
        {
            var tableIndexes = (TableIndex[])Enum.GetValues(typeof(TableIndex));

            tables = new IndexedLookup<object>[tableIndexes.Max(i => (int)i) + 1];
            this.reader = reader;
        }

        public void Keep(EntityHandle handle) => Set(handle, OriginalRowMarker);

        public void Replace(CustomAttributeHandle handle, CustomAttribute newRow) => Set(handle, newRow);

        public CustomAttributeHandle Add(CustomAttribute newRow)
        {
            Set()
        }

        private IndexedLookup<object> GetTable(HandleKind handleKind)
        {
            if (!MetadataTokens.TryGetTableIndex(handleKind, out var tableIndex))
                throw new ArgumentException("The specified handle kind is not stored in a table.");

            return tables[(int)tableIndex];
        }

        private void Set(EntityHandle handle, object data)
        {
            if (handle.IsNil)
                throw new ArgumentException("The specified handle must not be nil.", nameof(handle));

            ref var element = ref GetTable(handle.Kind)[reader.GetRowNumber(handle)];

            if (element is object)
                throw new InvalidOperationException($"The specified handle has already been {(element == OriginalRowMarker ? "kept" : "replaced")}.");

            element = OriginalRowMarker;
        }
    }
}
```

**Comment by YairHalberstadt** [comment]
Here is  UnitTest which triggers this error. I'm working on a fix.
Note it fails only when NRTs are enabled.

```csharp
        [Fact]
        [WorkItem(39993, "https://github.com/dotnet/roslyn/issues/39993")]
        public void CanSpeculativelyBindOutVariableDeclarationWithNullabilityEnabled()
        {
            var text =
@"
#nullable enable
class A {
    void M() {}
}
";
            var tree = Parse(text);
            var comp = (Compilation)CreateCompilation(tree);

            var adecl = tree.GetCompilationUnitRoot().Members[0] as TypeDeclarationSyntax;
            var mdecl = adecl.Members[0] as MethodDeclarationSyntax;
            var body = mdecl.Body;

            var model = comp.GetSemanticModel(tree);

            var speculate = SyntaxFactory.ParseExpression("int.TryParse(\"\", out var i)");
            model.GetSpeculativeSymbolInfo(body.SpanStart, speculate, SpeculativeBindingOption.BindAsExpression);
        }
```

**Comment by YairHalberstadt** [comment]
@333fred 

It looks like this bug was caused by changes to SpeculativeBinding for NRTs:

You added the following about 6 months ago:

```csharp
        internal override BoundExpression GetSpeculativelyBoundExpression(int position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, out Binder binder, out ImmutableArray<Symbol> crefSymbols)
        {
            if (expression == null)
            {
                throw new ArgumentNullException(nameof(expression));
            }

            if (!Compilation.NullableSemanticAnalysisEnabled || bindingOption != SpeculativeBindingOption.BindAsExpression)
            {
                return GetSpeculativelyBoundExpressionWithoutNullability(position, expression, bindingOption, out binder, out crefSymbols);
            }

            crefSymbols = default;
            position = CheckAndAdjustPosition(position);
            expression = SyntaxFactory.GetStandaloneExpression(expression);
            binder = GetEnclosingBinder(position);
            var boundRoot = binder.BindExpression(expression, _ignoredDiagnostics);
            ImmutableDictionary<Symbol, Symbol> ignored = null;
            return (BoundExpression)NullableWalker.AnalyzeAndRewriteSpeculation(position, boundRoot, binder, GetSnapshotManager(), newSnapshots: out _, remappedSymbols: ref ignored);
        }
```

Whilst we previously would create a new binder for speculative binding, if NRTS are enabled we use the existing binder. I'm guessing that's to allow us to reuse nullability analysis.

However as a result if the expression declares variables we error, as the LocalsMap is incorrect from the old binder.

I wonder how you would suggest fixing this?

Thanks

**Comment by 333fred** [comment]
@YairHalberstadt what exactly is failing about it?

**Comment by YairHalberstadt** [comment]
@333fred 

When binding the out variable, we look for the local the out variable declaration declares in the binder. If we can't find it we assume the location is unreachable.

Since we are using the existing binder rather than a new speculative binder, the locals do not contain the one declared by the out declaration.

**Comment by 333fred** [comment]
@YairHalberstadt I've just run into this independently when fixing https://github.com/dotnet/roslyn/issues/40750 and adding new tests. I'm going to fix this one at the same time.
