### ISSUE TITLE
SyntaxEditorBasedFixAllProvider encoutered an error - NullReferenceException

### ISSUE THREAD

**Issue by odyth** [dotnet/roslyn#40031]
**Version Used**: 
Visual Studio Professional 2019 Version 16.3.10

**Steps to Reproduce**:

1. Find some code that needs to Use discard '_'
![image](https://user-images.githubusercontent.com/947020/69689034-bc2bb380-10bf-11ea-82e9-fd32e274d8e9.png)

2. Try and apply this change to the project or solution (document works). 
3. VS will think for a few seconds as if attempting and then SyntaxEditorBasedFixAllProvider will crash with an NRE

![image](https://user-images.githubusercontent.com/947020/69689295-715e6b80-10c0-11ea-9a17-d1ffcb123185.png)

Here is the stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.FixDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

**Expected Behavior**:
Formatting is performed across my project

**Actual Behavior**:
NRE is thrown and no formatting is performed.

**Comment by odyth** [comment]
To reproduce
1. Make a console project
2. Create a new .cs file called ProcessQueue.cs
3. insert this code

```
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class ProcessQueue<T>
    {
        private readonly BlockingCollection<T> _queue = new BlockingCollection<T>(100000);
        private readonly Func<IReadOnlyList<T>, Task> _action;
        private void ProcessQueueItems()
        {
            var localQueue = new List<T>();
            var finishedCountdown = new CountdownEvent(1);
            foreach (var item in _queue.GetConsumingEnumerable())
            {
                localQueue.Add(item);
                if (_queue.Count == 0 || localQueue.Count > 10)
                {
                    finishedCountdown.AddCount(1);
                    var threadLocal = new List<T>(localQueue);
                    Task.Run(async () =>
                    {
                        await _action(threadLocal);
                        finishedCountdown.Signal();
                    });
                    localQueue.Clear();
                }
            }
            finishedCountdown.Signal();
            if (localQueue.Count > 0)
            {
                _action(localQueue);
            }
            try
            {
                finishedCountdown.Wait(TimeSpan.FromSeconds(10));
            }
            catch
            {
                // ignored
            }
        }
    }
}
```

4. go down `finishedCountdown.Wait(TimeSpan.FromSeconds(10));` and use discard for project
![image](https://user-images.githubusercontent.com/947020/69760690-1595f000-115d-11ea-8e28-585b5b477474.png)

SyntaxEditorBasedFixAllProvider  will then crash.

If you instead change line 23 from 
`var threadLocal = new List<T>(localQueue);`
to
`var threadLocal = new List<object>(localQueue);`

then SyntaxEditorBasedFixAllProvider will not crash. Not sure why that generic list messes it up.

**Comment by 06needhamt** [comment]
I can not reproduce with the latest version of visual studio with the above code. @odyth Can you still reproduce it?

**Comment by CyrusNajmabadi** [comment]
Can't repro either.  Please reactive if you can with a file that shows this.  Thanks!
