### ISSUE TITLE
Rename Type to Match File crashes VS when code only contains `class` keyword

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#40043]
Also tracked by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1030401

**Steps to Reproduce**:

1. In an otherwise empty C# file:

```C#
class$$
```

2. Remove the `$$` and invoke the lightbulb at that location
3. Pick "Rename type to Program"

**Expected Behavior**: The refactoring shouldn't be offered on this particular incomplete code.
**Actual Behavior**: VS crashes.

**Note: This is particularly important because of the way the LSP is implemented today.** See https://github.com/dotnet/roslyn/issues/40086

```
ArgumentException: openBraceToken

   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ClassDeclaration(SyntaxList`1 attributeLists, SyntaxTokenList modifiers, SyntaxToken keyword, SyntaxToken identifier, TypeParameterListSyntax typeParameterList, BaseListSyntax baseList, SyntaxList`1 constraintClauses, SyntaxToken openBraceToken, SyntaxList`1 members, SyntaxToken closeBraceToken, SyntaxToken semicolonToken) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Main.Generated.cs:line 4333
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Update(SyntaxList`1 attributeLists, SyntaxTokenList modifiers, SyntaxToken keyword, SyntaxToken identifier, TypeParameterListSyntax typeParameterList, BaseListSyntax baseList, SyntaxList`1 constraintClauses, SyntaxToken openBraceToken, SyntaxList`1 members, SyntaxToken closeBraceToken, SyntaxToken semicolonToken) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Syntax.Generated.cs:line 7788
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Main.Generated.cs:line 1739
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Syntax.Generated.cs:line 7782
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 171
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in C:\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Main.Generated.cs:line 1703
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in C:\src\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Syntax.Generated.cs:line 6936
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 171
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.AnnotateAndRename(RenameRewriterParameters parameters) in C:\src\roslyn\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 45
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__27.MoveNext() in C:\src\roslyn\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 795
```

**Comment by dpoeschl** [comment]
FYI @jinujoseph This is the LSP server exception we talked about today. In addition to fixing the refactoring itself, we should probably guard (all of?) the LSP entry points against exceptions?

**Comment by dpoeschl** [comment]
Also tagging @jmarolf — shouldn’t exceptions in the production of the preview window turn into gold bars? Another aspect to look at.

**Comment by jmarolf** [comment]
@dpoeschl its possible that there is a hole somewhere. We also crash VS when you build locally instead of showing a gold bar so that we can find these kinds of issues.

**Comment by dpoeschl** [comment]
@jmarolf The [rename code is littered](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.Session.cs) with `FatalError.ReportUnlessCanceled` calls in exception filters.  That's why the gold bar didn't have a chance to fire in this case.
