### ISSUE TITLE
OOP: KeyNotFoundException from RequestAsset

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40073]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/733900/streamjsonrpcremoteinvocationexception-unable-to-r.html)._

```
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.Execution.AssetStorages.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Execution.RemotableDataServiceFactory.Service.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteOneAssetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteAssetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<RequestAssetAsync>d__3.MoveNext()
09/27/2019 16:05:42 : Error : 10 :Exception thrown from request "2028" for method RequestAssetAsync: System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.Execution.AssetStorages.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Execution.RemotableDataServiceFactory.Service.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteOneAssetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteAssetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<RequestAssetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.Execution.AssetStorages.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Execution.RemotableDataServiceFactory.Service.GetRemotableData(Int32 scopeId, Checksum checksum, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteOneAssetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<WriteAssetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Remote.RemotableDataJsonRpc.<RequestAssetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 9/16/2019, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### HeeJae Chang [MSFT] on 9/16/2019, 11:18 AM: 

<p>thank you for the feedback! if possible, can you share us logs in %temp%\servicehub\logs ? we need little bit more info to find out what has happened. since this issue involves multiple processes, some times 1 callstack is not enough.</p>
<p>thank you very much</p>

#### Visual Studio Feedback System on 9/24/2019, 08:46 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Andrew Prime on 9/27/2019, 08:15 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 10/17/2019, 04:42 PM: 

<p>This issue has been identified as a duplicate of an earlier reported feedback linked here: <a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/676930/visual-studio-crash-with-remoteinvocationexception.html">https://developercommunity.visualstudio.com/content/problem/676930/visual-studio-crash-with-remoteinvocationexception.html</a>. If you reported or voted here, your vote has been applied to the original issue. Everyone else can add their vote directly at the above linked feedback. Voting helps increase the priority of the issue by consolidating customer impact under one feedback. Thank you!</p>

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
There is not enough information to investigate further. 

See https://developercommunity.visualstudio.com/comments/839021/view.html for instructions on how to provide the necessary info.

**Comment by CyrusNajmabadi** [comment]
Closing out.
