### ISSUE TITLE
'CSharpRemoveUnusedVariableCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40336]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/843951/csharpremoveunusedvariablecodefixprovider-encounte.html)._

---
Here is the stack trace:
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ForStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax'.
   at Microsoft.CodeAnalysis.RemoveUnusedVariable.AbstractRemoveUnusedVariableCodeFixProvider`3.MergeNodesToRemove(HashSet`1 nodesToRemove)
   at async Microsoft.CodeAnalysis.RemoveUnusedVariable.AbstractRemoveUnusedVariableCodeFixProvider`3.FixAllAsync[TLocalDeclarationStatement,TVariableDeclarator,TVariableDeclaration](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Visual Studio Feedback System on 12/4/2019, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by lameox** [comment]
The problem seems to be the loop in  [```AbstractRemoveUnusedVariableCodeFixProvider`3.MergeNodesToRemove(Hashset<SyntaxNode>)```](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs#L157).

The cast in there assumes, that the `VariableDeclarator.Parent.Parent` is always a `TLocalDeclarationStatement`.
This however is not the case for declarations in For loops (as seen in the stacktrace) and the error can be repro'd with this snippet when trying to fix the reported diagnostic on `j`:
```cs
    for(int i = 0, j = 0; i < 1; i++)
    {
    }
```
____________________
A similar error also happens in [`AbstractRemoveUnusedValuesCodeFixProvider`](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs#L425) where the code also assumes that a given declarator always has a local declaration somewhere in its parent tree. The call however returns a null which then gets passed to `ShouldRemoveStatement` and ultimately to `syntaxFacts.GetVariablesOfLocalDeclarationStatement` where it crashes with a stacktrace like this: 
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.GetVariablesOfLocalDeclarationStatement(SyntaxNode node)
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.<>c__DisplayClass25_0.<FixAllValueAssignedIsUnusedDiagnosticsAsync>g__ShouldRemoveStatement|3(TLocalDeclarationStatementSyntax localDeclarationStatement,SeparatedSyntaxList`1& variables)
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllValueAssignedIsUnusedDiagnosticsAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

This can be reproduced with the following snippet when trying to fix the diagnostic on `i`:
```cs
    for(int i = 0; true;)
    {
    }
```
____________________
Now my guess would be that the assumption of having a LocalDeclarationStatementSyntax somewhere in the parent tree of all VariableDeclarators is just a false assumption and needs to be checked for in both implementations and a special case introduced for variables declared in for loops.

I would like to write a fix for these two issues but am unsure on weather to do them in 1 or 2 PRs and weather or not my suggested fix is the right way to go about it. Id somebody from the team could give me a few pointers that would be great.

**Comment by CyrusNajmabadi** [comment]
> I would like to write a fix for these two issues but am unsure on weather to do them in 1 or 2 PRs

One PR is fine for now.  If it ends up being far larger in scope, it may make sense to split into two.

> and weather or not my suggested fix is the right way to go about it. 

Your approach sounds fine.
