### ISSUE TITLE
InvalidCastException in GenerateParameterizedMember (NonErrorNamedTypeSymbol)

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#40402]
**Version Used**: VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150

**Actual Behavior**:

Code fix error info bar:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'TypeSymbolWithNullableAnnotation'.
   at Microsoft.CodeAnalysis.NullableExtensions.WithNullability[T](T typeSymbol,NullableAnnotation nullability)
   at Microsoft.CodeAnalysis.NullableExtensions.TypeSymbolWithNullableAnnotation.Microsoft.CodeAnalysis.ITypeSymbol.WithNullableAnnotation(NullableAnnotation nullableAnnotation)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalent(ISymbol x,ISymbol y,Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.Equals(IParameterSymbol x,IParameterSymbol y,Dictionary`2 equivalentTypesWithDifferingAssemblies,Boolean compareParameterName,Boolean isCaseSensitive)
   at Microsoft.CodeAnalysis.Shared.Utilities.SignatureComparer.HaveSameSignature(IList`1 parameters1,IList`1 parameters2,Boolean compareParameterName,Boolean isCaseSensitive)
   at Microsoft.CodeAnalysis.Shared.Utilities.SignatureComparer.HaveSameSignature(IMethodSymbol method1,IMethodSymbol method2,Boolean caseSensitive,Boolean compareParameterName,Boolean isParameterCaseSensitive)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.<>c__DisplayClass55_0.<TryFinishInitializingStateAsync>b__0(IMethodSymbol m)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.TryFinishInitializingStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.GenerateMethodStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.GenerateMethodAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
```

**Comment by jaredpar** [comment]
@AlekseyTs can you take a look at this?

**Comment by AlekseyTs** [comment]
This is IDE code and ```TypeSymbolWithNullableAnnotation``` is a type in Workspaces layer.

**Comment by jasonmalinowski** [comment]
Going to close this as fixed, since the wrapping mechanism is now entirely deleted. It looks like this must have been an odd bug when the new compiler implementation was in place but our wrappers weren't gone yet.
