### ISSUE TITLE
CodeAnalysis issue when project dependancies from VB.net project are in a C# project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/815752/codeanalysis-issue-when-project-dependancies-from.html)._

---
[regression] [worked-in:16.2]
This happened to me when adding a "using" statement at the top in a C# project that also contains VB.net project dependancies.
According to your stack trace, this issue happens in the **GetAliasSymbol( )** function, as it cannot cast between the CSharp and VisualBasic Symbol objects.

The stack trace should give you everything that you need:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol' to type 'Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol'.**

at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.GetAliasSymbol(INamespaceOrTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.TryAddAlias(INamespaceOrTypeSymbol symbol,ArrayBuilder`1 builder)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.Accept(SymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol,SemanticModel semanticModelOpt,Int32 positionOpt,SymbolDisplayFormat format,Boolean minimal)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToMinimalDisplayParts(ISymbol symbol,SemanticModel semanticModel,Int32 position,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ISymbol_ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.Editor.CSharp.LanguageServices.CSharpSymbolDisplayService.ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.ToMinimalDisplayString(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider. <CreateActions>d__11.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at async Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 11/12/2019, 00:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/15/2019, 03:11 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
I hit what I think is a variant of this while dogfooding a few days ago:

```
System.ArgumentException : Expected a {0} SemanticModel.
Parameter name: C#
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.GetCSharpSemanticModel(SemanticModel semanticModel)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.LanguageServices.VisualBasicSymbolDisplayService.ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.ToMinimalDisplayString(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider.<CreateActions>d__11.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at async Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

It looks like the vsfeedback was the C# referencing VB.NET case, and in my case it was the reverse. The exception might also be different for the C# case since C# symbols are now wrapped which might be a bit different for VB. (Not sure, I'd have to look but it wouldn't surprise me.)

**Comment by Brain2000** [comment]
This is still happening in the latest Visual Studio 16.4.5:

System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol' to type 'Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol'.
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.GetAliasSymbol(INamespaceOrTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.TryAddAlias(INamespaceOrTypeSymbol symbol,ArrayBuilder`1 builder)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.Accept(SymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol,SemanticModel semanticModelOpt,Int32 positionOpt,SymbolDisplayFormat format,Boolean minimal)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToMinimalDisplayParts(ISymbol symbol,SemanticModel semanticModel,Int32 position,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ISymbol_ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.Editor.CSharp.LanguageServices.CSharpSymbolDisplayService.ToMinimalDisplayParts(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.ToMinimalDisplayString(SemanticModel semanticModel,Int32 position,ISymbol symbol,SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider.<CreateActions>d__11.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at async Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
