### ISSUE TITLE
[Bug] Returning null from SupportedDiagnostics crashes VS2015 RTM

### ISSUE THREAD

**Issue by axel-habermaier** [dotnet/roslyn#4055]
Create a new library, containing only the following analyzer:

```C#
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class MyAnalyzer : DiagnosticAnalyzer
{
	public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get; }
	public override void Initialize(AnalysisContext context)
	{
	}
}
```

Add the analyzer to a C# project. VS2015 RTM crashes (no error dialog is displayed). The Windows event log contains the following exception trace:

``
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Immutable.ImmutableArray`1.GetEnumerator()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.<>c__DisplayClass10_0.<GetSupportedDiagnosticDescriptors>b__0(DiagnosticAnalyzer key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.GetSupportedDiagnosticDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, Func`2 isCompilerAnalyzer, AnalyzerExecutor analyzerExecutor)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.IsAnalyzerSuppressed(DiagnosticAnalyzer analyzer)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetAsync>d__13.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+LatestDiagnosticsForSpanGetter+<TryGetAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+LatestDiagnosticsForSpanGetter+<TryGetAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+LatestDiagnosticsForSpanGetter+<TryGetAsync>d__13, Microsoft.CodeAnalysis.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<TryGetAsync>d__13 ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+LatestDiagnosticsForSpanGetter.TryGetAsync()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+<TryAppendDiagnosticsForSpanAsync>d__60.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer+<TryAppendDiagnosticsForSpanAsync>d__60, Microsoft.CodeAnalysis.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<TryAppendDiagnosticsForSpanAsync>d__60 ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService+IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService+<>c__DisplayClass15_0+<<TryAppendDiagnosticsForSpanAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService+<>c__DisplayClass15_0+<<TryAppendDiagnosticsForSpanAsync>b__0>d, Microsoft.CodeAnalysis.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<TryAppendDiagnosticsForSpanAsync>b__0>d ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService+<>c__DisplayClass15_0.<TryAppendDiagnosticsForSpanAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
``

**Comment by mavasani** [comment]
This should be addressed by https://github.com/dotnet/roslyn/pull/4081
I'll add a regression test to confirm once that PR is merged.

**Comment by mavasani** [comment]
Regression test added with https://github.com/dotnet/roslyn/commit/db536b0f30f6d52f778ba68795b07fb3ca5a9468
