### ISSUE TITLE
Argument out of Range: VB invert if

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#40589]
**Version Used**: 
16.4.<smth>

**Steps to Reproduce**:

1. Caret in the middle of `if` token -> Invert if
2. Not sure how specific the code was

**Expected Behavior**:

**Actual Behavior**:

```
System.ArgumentOutOfRangeException : Zadaný argument je mimo rozsah platných hodnot.
   at Microsoft.CodeAnalysis.SyntaxList`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.VisualBasic.InvertIf.VisualBasicInvertSingleLineIfCodeRefactoringProvider.UpdateIf(SourceText sourceText,SingleLineIfStatementSyntax ifNode,SyntaxNode condition,SyntaxList`1 trueStatements,SyntaxList`1 falseStatements)
   at Microsoft.CodeAnalysis.InvertIf.AbstractInvertIfCodeRefactoringProvider`3.GetRootWithInvertIfStatement(SourceText text,SyntaxNode root,TIfStatementSyntax ifNode,InvertIfStyle invertIfStyle,SyntaxNode subsequentSingleExitPointOpt,SyntaxNode negatedExpression)
   at async Microsoft.CodeAnalysis.InvertIf.AbstractInvertIfCodeRefactoringProvider`3.InvertIfAsync[TIfStatementSyntax,TStatementSyntax,TEmbeddedStatement](<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Neznámé parametry>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Neznámé parametry>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
