### ISSUE TITLE
NRE from SymbolFinder invoked from CodeLens.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40722]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/605549/possible-roslyn-crash.html)._

---
On each load of my project I get the "Unfortunately, a process used by Visual Studio has encountered an unrecoverable error." message at the top. From the error logs I see the following exception:

```
Error : Microsoft.CodeAnalysis.Remote.CodeAnalysisService (12) : Exception: System.InvalidOperationException: Unexpected Null
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
```

Attached are logs from %temp%\servicehub\logs

---
#### Santosh Patil on 6/12/2019, 10:28 PM: 

<p>I failed to mention that due to the above error the references don't show up in the IDE. See attached screenshot.<a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/78385-ref.jpg">ref.jpg</a></p>

#### Visual Studio Feedback System on 6/13/2019, 02:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/13/2019, 10:14 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 12/31/2019, 09:36 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---

The issue is in SymbolFinder invoked from CodeLens.

```
System.InvalidOperationException: Unexpected Null
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.VerifyForwardedTypes(Dictionary`2 equivalentTypesWithDifferingAssemblies, Compilation compilation, HashSet`1 verifiedKeys, Boolean isSearchSymbolCompilation)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.VerifyForwardedTypes(Dictionary`2 equivalentTypesWithDifferingAssemblies, ISymbol searchSymbol, ISymbol symbolToMatch, Solution solution, Compilation searchSymbolCompilation, Compilation symbolToMatchCompilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.OriginalSymbolsMatchCore(ISymbol searchSymbol, ISymbol symbolToMatch, Solution solution, Compilation searchSymbolCompilation, Compilation symbolToMatchCompilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.OriginalSymbolsMatch(ISymbol searchSymbol, ISymbol symbolToMatch, Solution solution, Compilation searchSymbolCompilation, Compilation symbolToMatchCompilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeSymbolExtensions.<>c__DisplayClass16_0.<FindImplementationsForInterfaceMemberAsync>b__1(ISymbol m)
```
   ...
```
at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.<FindAsync>d__1`1.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Closing out.  No prism hits for this in recent builds.
