### ISSUE TITLE
Csharpaddimportcodefixprovider crashing due to Roslyn and nuget

### ISSUE THREAD

**Issue by selMicrosoft** [dotnet/roslyn#40857]
**Version Used**: 16.4.2

**Steps to Reproduce**:
1. Referenced a type in my class that didn't have the appropriate "using" import statement yet
2. Try to resolve the type by importing the using through the quick actions
3. Also have a nuget.config that did not have the correct credentials to reach nuget
4. I also want add that this happens for types that are system types (like System.Collections.Generic.Dictionary) as well as solution defined types. This doesn't only happen when I try to reference types that are only available through nuget packages.

**Expected Behavior**:
Using the quick actions, the sln defined type is found and the using statement is added to the class, allowing the type to be used.

**Actual Behavior**:
Quick actions is opened and then at the top I get a "encountered an error" message for Csharpaddimportcodefixprovider with the stack trace of:

```
System.ArgumentException : Value cannot be null or empty string.
Parameter name: password
   at NuGet.Configuration.CredentialsItem..ctor(String name,String username,String password,Boolean isPasswordClearText,String validAuthenticationTypes)
   at NuGet.Configuration.CredentialsItem.Clone()
   at NuGet.Configuration.VirtualSettingSection.<>c.<Clone>b__7_0(SettingItem s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at NuGet.Configuration.SettingsGroup`1..ctor(IReadOnlyDictionary`2 attributes,IEnumerable`1 children)
   at NuGet.Configuration.SettingSection..ctor(String name,IReadOnlyDictionary`2 attributes,IEnumerable`1 children)
   at NuGet.Configuration.VirtualSettingSection.Clone()
   at NuGet.Configuration.Settings.GetSection(String sectionName)
   at NuGet.PackageManagement.VisualStudio.VSSettings.GetSection(String sectionName)
   at NuGet.Configuration.PackageSourceProvider.ReadCredential(String sourceName,ISettings settings)
   at NuGet.Configuration.PackageSourceProvider.ReadPackageSource(SourceItem setting,Boolean isEnabled,ISettings settings)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSourceLookup(Boolean byName,ISettings settings)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources(ISettings settings,IEnumerable`1 defaultPackageSources)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources()
   at NuGet.VisualStudio.VsPackageSourceProvider.GetSources(Boolean includeUnOfficial,Boolean includeDisabled)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.GetPackageSources()
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue.  It would have to go to the nuget team.  Looks like a bug on their side.

**Comment by sharwell** [comment]
@CyrusNajmabadi There may be a NuGet issue, but the Roslyn feature should not be failing completely in this case, which is what happens today.

**Comment by CyrusNajmabadi** [comment]
> It should instead just ignore the NuGet packages portion of this fix.

Sure.  We can try to be more resilient to bugs in other modules.  But i'm always wary about that as i really don't know how to assess the state of hte system here.

**Comment by jmarolf** [comment]
What would roslyn do? add the using and not the nuget package? I assume if we did anything here we would want to pop some kind of error dialog telling the user that we couldn't add the nuget package and ask them what they want to do.

**Comment by selMicrosoft** [comment]
I don't understand all the in's and out's of the conversation/what quick actions is doing behind the scenes. But this seems odd to me that this would even be thought of as just a nuget issue. This doesn't only happen to types applicable to nuget packages. This also happens for system types that should already be on my computer like System.Collections.Generic.Dictionary or types from namespaces I have defined in my personal solution. Why would nuget even be involved in something like that? Wouldn't that alone make this more than just a "nuget" or "roslyn" issue? I could see this being a nuget issue if I was pulling in a package like Newtonsoft, but not for the other scenarios mentioned. Seems like a bit of both to me, even with my little knowledge of what is going on here.

**Comment by CyrusNajmabadi** [comment]
> Wouldn't that alone make this more than just a "nuget" or just a "roslyn" issue, maybe a bit of both?
