### ISSUE TITLE
Cannot find drive. A drive with the name '"C' does not exist. Cannot find line number in build scripts

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/roslyn#40920]
**Version Used**: 

Windows 10 2019 Enterprise LTSC

**Steps to Reproduce**:

1. Roslyn 2017 15.9
2. Visual Studio 2017 Enterprise
3. run restore.cmd

**Expected Behavior**:
restore complete
**Actual Behavior**:
Cannot find drive. A drive with the name '"C' does not exist.
System.Management.Automation.DriveNotFoundException: Cannot find drive. A drive with the name '"C' does not exist.
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at System.Management.Automation.LocationGlobber.GetDriveRootRelativePathFromPSPath(String path, CmdletProviderContext context, Boolean escapeCurrentLocation, PSDriveInfo& workingDriveForPath, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetProviderPath(String path, CmdletProviderContext context, Boolean isTrusted, ProviderInfo& provider, PSDriveInfo& drive)
   at System.Management.Automation.SessionStateInternal.MakePath(String parent, String child, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.JoinPathCommand.ProcessRecord()
at Get-DotnetDir, E:\roslyn-Visual-Studio-2017-Version-15.9\build\scripts\build-utils.ps1: line 127
at Ensure-DotnetSdk, E:\roslyn-Visual-Studio-2017-Version-15.9\build\scripts\build-utils.ps1: line 137
at Ensure-MSBuild, E:\roslyn-Visual-Studio-2017-Version-15.9\build\scripts\build-utils.ps1: line 197
at <ScriptBlock>, E:\roslyn-Visual-Studio-2017-Version-15.9\build\scripts\build.ps1: line 773
'E:\roslyn-Visual-Studio-2017-Version-15.9\' is not recognized as an internal or external command,
operable program or batch file.

It's an easy fix it you can find the extra apostrophe in that one error

**Comment by tmat** [comment]
Does it repro with master?

**Comment by jdm7dv** [comment]
no I just downloaded the 2017 release I don't want 2019.

**Comment by tmat** [comment]
You'll need to work around the issue then. You can probably just `subst` the C drive.

**Comment by jdm7dv** [comment]
No I don't want to create a Virtual Drive C: when that is the boot drive.

**Comment by tmat** [comment]
You can also fix the build script in your local clone. We won't be accepting the change to 16.9 branch though as it is not critical for servicing.
