### ISSUE TITLE
Test AsyncIteratorWithThis is flaky

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40927]
https://dev.azure.com/dnceng/public/_build/results?buildId=481050&view=ms.vss-test-web.build-test-results-tab&runId=15266940&resultId=101109&paneView=debug

`System.InvalidOperationException : Operation is not valid due to the current state of the object.`

Stack trace
```
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.ThrowInvalidOperationException()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.CompletionSentinel(Object _)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.InvokeContinuation()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
   at C.M()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.MoveNext[TStateMachine](TStateMachine& stateMachine)
   at C.M()
   at C.Main()
   at C.Main()
   at C.<Main>()
```

|Build|Kind|Start Time|
|---|---|---|
[883867](https://dev.azure.com/dnceng/public/_build/results?buildId=883867)|Rolling|2020-12-11|

**Comment by jcouv** [comment]
I've encountered this today with `CancellationTokenParameter_Overridding` as well

https://dev.azure.com/dnceng/public/_build/results?buildId=485631&view=ms.vss-test-web.build-test-results-tab&runId=15432148&resultId=104357&paneView=debug

```
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.ThrowInvalidOperationException()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.CompletionSentinel(Object _)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.InvokeContinuation()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
   at C.Iter(CancellationToken token1, Int32 value)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.MoveNext[TStateMachine](TStateMachine& stateMachine)
   at C.Iter(CancellationToken token1, Int32 value)
   at C.Main()
   at C.<Main>()
```

**Comment by jcouv** [comment]
There's not been any more reports of this problem. I'll go ahead and close

**Comment by sharwell** [comment]
Duplicate of #34207
