### ISSUE TITLE
ArgumentOutOfRangeException in MetadataReader ctor

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4108]
Our only reports are from win7.

```
System.ArgumentOutOfRangeException
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata; Int32 length; MetadataReaderOptions options; MetadataStringDecoder utf8Decoder)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.DkmUtilities.GetMetadataBlock(IntPtr ptr; UInt32 size)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.DkmUtilities.GetMetadataBlocks(DkmClrRuntimeInstance runtime; DkmClrAppDomaat appDomain)
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CSharpInstructionDecoder.GetCompilation(DkmClrModuleInstance moduleInstance)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.LanguageInstructionDecoder`6.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmLanguageInstructionDecoder.GetMethodName(DkmLanguageInstructionAddress languageInstructionAddress; DkmVariableInfoFlags argumentFlags)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmLanguageInstructionDecoder_GetMethodName(IntPtr pvClassInfo; IntPtr LanguageInstructionAddress; DkmVariableInfoFlags ArgumentFlags; IntPtr& MethodName)
```

**Comment by amcasey** [comment]
FYI @KevinH-MS

**Comment by amcasey** [comment]
Negative length maybe?  I'm not sure what else could go wrong without being more catastrophic (e.g. bad pointer).

**Comment by KevinH-MS** [comment]
There were cases where Windows.winmd was returning ```length == 0```.  I'll try to figure out the details.

**Comment by davkean** [comment]
+ @nguerrera as FYI

**Comment by nguerrera** [comment]
Just to confirm, this would happen if length <= 0 were passed.

**Comment by ManishJayaswal** [comment]
@KevinH-MS moving this to 1.2
