### ISSUE TITLE
Crash invoking quick actions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/890186/crash-invoking-quick-actions.html)._

---
<p>[regression] [worked-in:Previous IntPreview]<br>
Attempting to click on a light bulb for a analyser fix crashes the process.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/114730-quick-action-crash.gif"> Image:114730-quick-action-crash.gif</a></p><p><p>To repro:</p>
<ul>
<li>clone <a href="https://github.com/dotnet/winforms.git">https://github.com/dotnet/winforms.git</a> @ 96beeb0dab7f1c2596761072a165ace9901eb8f6</li>
<li>open in VS in Release mode</li>
<li>navigate to \winforms\src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Message.cs</li>
<li>click on the light bulb for the Message to fix public API warning</li>
</ul>

---
#### Visual Studio Feedback System on 1/19/2020, 10:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### igveliko [MSFT] on 1/20/2020, 00:01 AM: 

<p>Here's a stack trace from EventViewer</p><pre>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.SortedList`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService+&lt;GetFixesAsync&gt;d__15.MoveNext()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](System.Threading.Tasks.Task`1&lt;System.Collections.Immutable.ImmutableArray`1&lt;System.__Canon&gt;&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetCodeFixes(Microsoft.CodeAnalysis.Editor.Shared.ITextBufferSupportsFeatureService, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.Document, Microsoft.VisualStudio.Text.SnapshotSpan, System.Func`2&lt;System.String,System.IDisposable&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetSuggestedActions(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Utilities.IUIThreadOperationContext, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetSuggestedActions(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Utilities.IUIThreadOperationContext)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession+&lt;&gt;c__DisplayClass40_0.&lt;TryGetSuggestedActionSets&gt;b__0(Microsoft.VisualStudio.Utilities.IUIThreadOperationContext)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(Microsoft.VisualStudio.Utilities.UIThreadOperationExecutionOptions, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(System.String, System.String, Boolean, Boolean, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Text.Utilities.UIThreadOperationExecutor.Execute(System.String, System.String, Boolean, Boolean, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.TryGetSuggestedActionSets(System.Collections.Generic.IEnumerable`1&lt;Microsoft.VisualStudio.Language.Intellisense.SuggestedActionSet&gt; ByRef, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.TransitionToExpandedState()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.ChangeState(Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbState)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.&lt;OnSessionStateChanged&gt;b__37_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
<br></pre>

#### Visual Studio Feedback System on 1/20/2020, 00:17 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
This was caused by https://github.com/dotnet/roslyn/pull/40814
