### ISSUE TITLE
TaskCanceledException in TodoCommentIncrementalAnalyzer.GetTodoItems

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41158]
**Version Used**: 16.5 Preview 2

**Steps to Reproduce**: Unknown

**Actual Behavior**:

<pre>
System.Threading.Tasks.TaskCanceledException: A task was canceled.
    at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzer.GetTodoItems(Workspace workspace, DocumentId id, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzerProvider.GetTodoItems(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken)
    at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseTodoListTable.TableDataSource.TableEntriesSource.GetItems()
    at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory`1.AggregatedEntriesSource.GetItems()
    at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory`1.GetSnapshot(Int32 versionNumber)
    at Microsoft.VisualStudio.Shell.TableControl.Implementation.EntriesFromSnapshot.&lt;PinSnapshot&gt;b__14_1()
    at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow)
</pre>

**Comment by CyrusNajmabadi** [comment]
Haven't seen any more cases of this.  closing out.
