### ISSUE TITLE
Trying build Roslyn [Master, VS2015 Enterprise]

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#4122]
```
Severity	Code	Description	Project	File	Line
Warning		The "PrereleaseResolveNuGetPackageAssets" task failed unexpectedly.
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.NuGet.Build.Tasks.PrereleaseResolveNuGetPackageAssets.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	VbcCore		
Error	CS0103	The name 'MockComWrapperFactory' does not exist in the current context	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	33
Warning		The referenced component 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' could not be found.	VisualBasicErrorFactsGenerator		
Warning		The referenced component 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' could not be found.	VisualBasicSyntaxGenerator		
Warning		The referenced component 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll' could not be found.	BasicVisualStudioRepl		
Warning		The referenced component 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\mscorlib.dll' could not be found.	BasicCodeAnalysis		
Warning		The referenced component 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\mscorlib.dll' could not be found.	VbcCore		
Warning		The referenced component 'System.Collections' could not be found.	VisualStudioInteractiveServices		
Error	CS0246	The type or namespace name 'MockComponentModel' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\Options\OptionViewModelTests.cs	21
Error	CS0246	The type or namespace name 'MockComponentModel' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	31
Error	CS0246	The type or namespace name 'MockComponentModel' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\Options\OptionViewModelTests.cs	25
Error	CS0246	The type or namespace name 'MockServiceProvider' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	32
Error	CS0246	The type or namespace name 'MockTextPoint' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeFunctionTests.cs	537
Error	CS0246	The type or namespace name 'MockTextPoint' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeFunctionTests.cs	552
Error	CS0246	The type or namespace name 'MockVisualStudioWorkspace' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	35
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpHelpers.cs	17
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	47
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	78
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	114
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	144
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	166
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	197
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	238
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpCompilerOptionsTests.cs	26
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpCompilerOptionsTests.cs	44
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpCompilerOptionsTests.cs	61
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpCompilerOptionsTests.cs	98
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpReferencesTests.cs	27
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpReferencesTests.cs	49
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpReferencesTests.cs	74
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpReferencesTests.cs	94
Error	CS0246	The type or namespace name 'TestEnvironment' could not be found (are you missing a using directive or an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\SourceFileHandlingTests.cs	17
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeFunctionTests.cs	7
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	9
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\CodeModel\FileCodeModelTestHelpers.cs	10
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\Options\OptionViewModelTests.cs	11
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\AnalyzersTests.cs	9
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpCompilerOptionsTests.cs	13
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpHelpers.cs	10
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\CSharpReferencesTests.cs	13
Error	CS0234	The type or namespace name 'UnitTests' does not exist in the namespace 'Microsoft.VisualStudio.LanguageServices' (are you missing an assembly reference?)	CSharpVisualStudioTest	C:\Users\Adam\Documents\GitHub\roslyn-AdamSpeight2008\src\VisualStudio\CSharp\Test\ProjectSystemShim\SourceFileHandlingTests.cs	4
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic with ID 'RS0022' is not supported by the analyzer.
Parameter name: diagnostic'.	CodeAnalysis		1
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic with ID 'RS0022' is not supported by the analyzer.
Parameter name: diagnostic'.	CodeAnalysis		1
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic with ID 'RS0022' is not supported by the analyzer.
Parameter name: diagnostic'.	BasicCodeAnalysis		1
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic with ID 'RS0022' is not supported by the analyzer.
Parameter name: diagnostic'.	BasicCodeAnalysis		1
Error		There was a problem uninstalling the extension with a VSIX identifier of "0b5e8ddb-f12d-4131-a71d-77acc26a798f". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Language Services.	VisualStudioSetup		
Error		There was a problem uninstalling the extension with a VSIX identifier of "1F42C6D0-F876-4AF0-8185-1BEB0A325BB2". You need to use the Programs and Features pane in the Windows Control Panel to remove VisualStudio Interactive Components.	VisualStudioInteractiveWindow		
Error		There was a problem uninstalling the extension with a VSIX identifier of "21BAC26D-2935-4D0D-A282-AD647E2592B5". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Expression Evaluators.	ExpressionEvaluatorPackage		

```

**Comment by xdaDaveShaw** [comment]
I'm not seeing all these errors, but I am seeing:

> Build FAILED.

>"C:\Users\dave\Source\Repos\roslyn\BuildAndTest.proj" (default target) (1) ->
"C:\Users\dave\Source\Repos\roslyn\Src\Roslyn.sln" (Build target) (2) ->
"C:\Users\dave\Source\Repos\roslyn\Src\InteractiveWindow\VisualStudio\VisualStudioInteractiveWindow.csproj" (default target) (79) ->
(DeployVsixExtensionFiles target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(592,5): error VSSDK1041: There was a problem uninstalling the extension with a VSIX identifier of "1F42C6D0-F876-4AF0-8185-1BEB0A325BB2". You need to use the Programs and Features pane in the Windows Control Panel to remove VisualStudio Interactive Components. [C:\Users\dave\Source\Repos\roslyn\Src\InteractiveWindow\VisualStudio\VisualStudioInteractiveWindow.csproj]


>"C:\Users\dave\Source\Repos\roslyn\BuildAndTest.proj" (default target) (1) ->
"C:\Users\dave\Source\Repos\roslyn\Src\Roslyn.sln" (Build target) (2) ->
"C:\Users\dave\Source\Repos\roslyn\Src\VisualStudio\Setup\VisualStudioSetup.csproj" (default target) (90) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(592,5): error VSSDK1041: There was a problem uninstalling the extension with a VSIX identifier of "0b5e8ddb-f12d-4131-a71d-77acc26a798f". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Language Services. [C:\Users\dave\Source\Repos\roslyn\Src\VisualStudio\Setup\VisualStudioSetup.csproj]

>    0 Warning(s)
    2 Error(s)

When running `msbuild BuildAndTest.proj` on VS 2015 Enterprise RTM on an clean Azure VM.

Tried using `vxisinstaller` to uninstall the extensions, but the error persists.

**Comment by paul1956** [comment]
Following the instructions on https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging

 

Installed Visual Studio 2015 with Azure SDK 2.7 on Windows Server 2012 R2 (New Azure VM compute Image)

Clone using GitHub for Windows

Change directory to  <clone dir>  and run  powershell .nuget\NuGetRestore.ps1  

Open Roslyn.sln

Installed Roslyn SDK when prompted by Visual Studio

Restart Visual Studio and wait the number 235,496 keeps doing up for over an hour.

**Comment by codespare** [comment]
If you have installed the Python extension when setting up VS try and remove it using the VS installer. It has a dependency on the Interactive Components that prevents it being changed via vsix.
An untested alternative could be to repackage the vsix minus that dependency.

**Comment by xdaDaveShaw** [comment]
I don't have any Python Tools installed.

I don't know too much about VSIX packaging to debug this myself, but it still happens everytime I build.

**Comment by codespare** [comment]
Unless you need to test modifications to the interactive features in VS 2015, you are pretty safe ignoring those two. The build tries to deploy those vsix and fails because VS 2015 RTM msi installer has already installed and locked them. Windows installer is a bit rigid like that, which can be annoying, but it also guards VS against irrecoverable damage unless you really mean it :)

**Comment by xdaDaveShaw** [comment]
Can't seem to get everything working, building in VS seems problematic because the complete build doesn't run, and none of the xUnit tests are showing up in Test Explorer - might be an unrelated issue.

I'm just trying to add some new tests into the CSharp Emit tests. I've found I can make changes and build that project, then run the tests via the RunTests.exe commandline. 

It's a bit painful, but I can just about manage it.

**Comment by gafter** [comment]
Dup of #3612
