### ISSUE TITLE
Visual studio crashes while typing inside expression nuggets in C# websites

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#413]
1. With latest roslyn bits installed, open a new C# webforms website.
2. Add a new webform - default2.aspx
3. add below code inside `<div>`

         <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
         <%=Label1.$$%>

4. When caret is at $$, type a few backspaces
5. VS crashes.

Here is the relevant stack trace: 

~~~
ArgumentNullException {"Value cannot be null.\r\nParameter name: path"}
   at Microsoft.CodeAnalysis.FileLinePositionSpan..ctor(String path, LinePositionSpan span) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Diagnostic\FileLinePositionSpan.cs:line 80
   at Microsoft.CodeAnalysis.FileLinePositionSpan..ctor(String path, LinePosition start, LinePosition end) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Diagnostic\FileLinePositionSpan.cs:line 66
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioVenusSpanMappingService.GetAdjustedDiagnosticSpan(DocumentId documentId, Location location, TextSpan& sourceSpan, FileLinePositionSpan& originalLineInfo, FileLinePositionSpan& mappedLineInfo) in E:\Roslyn\Main\Open\Src\VisualStudio\Core\Def\Implementation\Diagnostics\VisualStudioVenusSpanMappingService.cs:line 53
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.GetLocationInfo(Document document, Location location, TextSpan& sourceSpan, FileLinePositionSpan& originalLineInfo, FileLinePositionSpan& mappedLineInfo) in E:\Roslyn\Main\Open\Src\Features\Core\Diagnostics\DiagnosticData.cs:line 332
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Document document, Diagnostic diagnostic) in E:\Roslyn\Main\Open\Src\Features\Core\Diagnostics\DiagnosticData.cs:line 286
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.DiagnosticIncrementalAnalyzer.<>c__DisplayClass57_0.<GetDiagnosticData>b__1(Diagnostic d) in E:\Roslyn\Main\Open\Src\Features\Core\Diagnostics\DiagnosticAnalyzerService.IncrementalAnalyzer.cs:line 804
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T](IEnumerable`1 items) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Collections\ImmutableArrayExtensions.cs:line 45
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.DiagnosticIncrementalAnalyzer.AnalyzerExecutor.<GetSyntaxAnalysisDataAsync>d__2.MoveNext() in E:\Roslyn\Main\Open\Src\Features\Core\Diagnostics\DiagnosticAnalyzerService.IncrementalAnalyzer.AnalyzerExecutor.cs:line 50
~~~

**Comment by Pilchie** [comment]
@heejaechang and/or @mavasani Did one of you add `VisualStudioVenusSpanMappingService`?

**Comment by heejaechang** [comment]
yes. I changed it. let me take a look.

**Comment by mavasani** [comment]
:+1:
