### ISSUE TITLE
csc.exe fails with mathematical assignment operators working on nullable value types

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#4132]
I'm trying to upgrade a rather large codebase to VS2015. The codebase builds perfectly on VS2013.

In VS2015, csc exits with an exit code corresponding to `COR_E_FAILFAST`.

I've managed to narrow this down to mathematical operations on nullable structs with implicit conversions. This can be reproduced with the following simple case:

    using System;

    namespace NullableMathRepro
    {
        class Program
        {
            static void Main(string[] args)
            {
                int? x = 0;
                x += 5;
                Console.WriteLine("'x' is {0}", x);

                IntHolder? y = 0;
                y += 5;
                Console.WriteLine("'y' is {0}", y);
            }
        }

        struct IntHolder
        {
            private int x;

            public static implicit operator int(IntHolder ih)
            {
                return ih.x;
            }

            public static implicit operator IntHolder(int i)
            {
                return new IntHolder { x = i };
            }

            public override string ToString()
            {
                return x.ToString();
            }
        }
    }

Using mathematical assignment operators on just the `int?` works fine.
Using mathematical assignment operators on the `IntHolder` works just fine.

**Using mathematical assignment operators on the `IntHolder?` causes the compiler to crash.**

If I replace `y += 5` with `y = y.Value + 5`, it compiles and runs as expected.

Visual Studio output:

    1>------ Build started: Project: NullableMathRepro, Configuration: Debug Any CPU ------
    1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code -2146232797.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

If I compile and run Roslyn from master (0000c35d), this assertion fails:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs#L956

If I ignore that assertion, this assertion subsequently fails:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs#L769

(`newOwner.OriginalDefinition` is `Int32`, but `this.ContainingSymbol.OriginalDefinition` is `Nullable<T>`.)

If I ignore that subsequent assertion, it finally fails with an `InvalidCastException` on the following line ( https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs#L770 ):

    System.InvalidCastException: Unable to cast object of type 'PENamedTypeSymbolNonGeneric' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SubstitutedNamedTypeSymbol'.
       at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.AsMember(NamedTypeSymbol newOwner) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Symbols\MethodSymbol.cs:line 770
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.GetNullableMethod(CSharpSyntaxNode syntax, TypeSymbol nullableType, SpecialMember member) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_BinaryOperator.cs:line 1631
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeLiftedUserDefinedConversionConsequence(BoundCall call, TypeSymbol resultType) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Conversion.cs:line 957
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteLiftedUserDefinedConversion(CSharpSyntaxNode syntax, BoundExpression rewrittenOperand, MethodSymbol method, TypeSymbol rewrittenType, ConversionKind conversionKind) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Conversion.cs:line 1019
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteUserDefinedConversion(CSharpSyntaxNode syntax, BoundExpression rewrittenOperand, MethodSymbol method, TypeSymbol rewrittenType, ConversionKind conversionKind) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Conversion.cs:line 939
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeConversion(CSharpSyntaxNode syntax, BoundExpression rewrittenOperand, Conversion conversion, TypeSymbol rewrittenType, Boolean checked, Boolean explicitCastInCode, ConstantValue constantValueOpt) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Conversion.cs:line 557
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitCompoundAssignmentOperator(BoundCompoundAssignmentOperator node, Boolean used) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_CompoundAssignmentOperator.cs:line 65
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_ExpressionStatement.cs:line 43
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_ExpressionStatement.cs:line 15
       at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) in C:\GH\Roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs:line 2037
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 149
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Block.cs:line 30
       at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in C:\GH\Roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs:line 1719
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 149
       at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawAwaitInExceptionHandler) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs:line 70
       at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1151
       at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 961
       at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 432
       at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass20_0.<CompileNamedTypeAsTask>b__0() in C:\GH\Roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 322

**Comment by brettshearer** [comment]
Nice repro and explanation.

**Comment by yaakov-h** [comment]
I spent some time investigating and it seems that the `Int32?` type (in the variable `rewrittenType` is substituted for the `op_Implicit`'s return value (the `Int32` type - not nullable) in [LocalRewriter_Conversion.cs#L561](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs#L561).

If I change `conversion.Method.ReturnType` to `rewrittenType`, it fixes my case but breaks these two unit tests:
* `TestNullCoalescingOverImplicitExplicitUDC`
* `TestNullCoalescingOverImplicitExplicitUDC_2`

Any advice on how to fix this without breaking anything else? :)

Also, what does the 1.1 milestone represent? Is that an upcoming VS2015 update, if so with what sort of timeframe?

THanks.

**Comment by AlekseyTs** [comment]
@VSadov, please verify.
