### ISSUE TITLE
VS crashes when I change branches

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#41378]
**Version Used**: 16.5.0 Preview 3 [29802.14.master]

**Steps to Reproduce**:

1. Open Roslyn.sln in VS
2. Go into the terminal and 'git checkout' a different branch (e.g. master to release/dev16.4)
3. Return to VS and run a build

**Expected Behavior**:

VS loads the project changes and keeps going.

**Actual Behavior**:

VS shows some diagnostics about bad restores eventually crashes.

![image](https://user-images.githubusercontent.com/5833655/73704206-2015be00-46a7-11ea-962c-312269d227b5.png)

/cc @jmarolf

**Comment by sharwell** [comment]
Can you file a feedback ticket with a crash dump?

**Comment by RikkiGibson** [comment]
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.VisualStudio.Shell.Interop.IVsBuildStatusCallback.BuildEnd(Int32)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.BuildableProjectConfig+<>c__DisplayClass73_1.<NotifyBuildEnd>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Verify(System.Func`1<Int32>, System.String, ErrorBehavior)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.BuildableProjectConfig.NotifyBuildEnd(Boolean)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.BuildableProjectConfig+<BuildAsync>d__67.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation+<>c.<.cctor>b__8_0(System.Object)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

Will get a dump and file properly when I have the chance, but I believe this call stack from the event log is from this crash.

**Comment by jmarolf** [comment]
@jinujoseph and @sharwell this looks like e project system issue, can you move it over to that repo?
