### ISSUE TITLE
ArgumentOutOfRangeException in CustomDebugInfoReader.GetCSharpGroupedImportStrings

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4138]
```
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode; IntPtr errorInfo)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.ThrowExceptionForHR(Int32 hr)
at Microsoft.CodeAnalysis.CustomDebugInfoReader.GetCSharpGroupedImportStrings(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; ImmutableArray`1& externAliasStrings)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.SymUnmanagedReaderExtensions.GetMethodDebugInfo(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; String firstLocalName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpCompilation compilation; Object symReader; Guid moduleVersionId; Int32 methodToken; Int32 methodVersion; Int32 ilOffset; Int32 localSignatureToken)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpMetadataContext previous; ImmutableArray`1 metadataBlocks; Object symReader; Guid moduleVe...
```

```
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode; IntPtr errorInfo)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.ThrowExceptionForHR(Int32 hr)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetItems[TEntity;TArg1;TArg2;TItem](TEntity entity; TArg1 arg1; TArg2 arg2; ItemsGetter`4 getter)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetCustomDebugInfoBytes(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion)
at Microsoft.CodeAnalysis.CustomDebugInfoReader.GetCSharpGroupedImportStrings(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; ImmutableArray`1& externAliasStrings)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.SymUnmanagedReaderExtensions.GetMethodDebugInfo(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; String firstLocalName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpCompilation compilation; Object symRea...
```

```
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode; IntPtr errorInfo)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.ThrowExceptionForHR(Int32 hr)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetItems[TEntity;TArg1;TArg2;TItem](TEntity entity; TArg1 arg1; TArg2 arg2; ItemsGetter`4 getter)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetCustomDebugInfoBytes(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion)
at Microsoft.CodeAnalysis.CustomDebugInfoReader.GetCSharpGroupedImportStrings(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; ImmutableArray`1& externAliasStrings)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.SymUnmanagedReaderExtensions.GetMethodDebugInfo(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; String firstLocalName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpCompilation compilation; Object...
```

```
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode; IntPtr errorInfo)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.ThrowExceptionForHR(Int32 hr)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetItems[TEntity;TArg1;TArg2;TItem](TEntity entity; TArg1 arg1; TArg2 arg2; ItemsGetter`4 getter)
at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetCustomDebugInfoBytes(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion)
at Microsoft.CodeAnalysis.CustomDebugInfoReader.GetCSharpGroupedImportStrings(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; ImmutableArray`1& externAliasStrings)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.SymUnmanagedReaderExtensions.GetMethodDebugInfo(ISymUnmanagedReader reader; Int32 methodToken; Int32 methodVersion; String firstLocalName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpCompilation compilation;...
```

**Comment by amcasey** [comment]
The third is easily the most common.

**Comment by amcasey** [comment]
@ManishJayaswal this is one of our top three hits, so we might want to consider moving it into 1.1 Preview.

**Comment by amcasey** [comment]
I simulated such an exception and ended up with no locals.  This is worth fixing, even if the fix is only a mitigation.

**Comment by amcasey** [comment]
The immediate cause appears to be that ```ISymUnmanagedReader3.GetSymAttributeByVersion``` may return the HRESULT for ```ArgumentOutOfRangeException```, rather than the expected ```E_FAIL```, when custom debug info is unavailable for a method.  It's probably worth investigating when this occurs (@pnelsonmsft suspects dynamic modules for ASP.NET), but we should implement a workaround (i.e. catch and drop) ASAP to unblock customers.

**Comment by amcasey** [comment]
Remaining (debugger) work tracked by internal bug 144396.

**Comment by amcasey** [comment]
We'll reactivate/refile if this keeps happening after we've shipped the fix.
