### ISSUE TITLE
CSharpInteractiveDirectives.VerifyHashReset test failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#41409]
https://dev.azure.com/dnceng/public/_build/results?buildId=507587&view=ms.vss-test-web.build-test-results-tab&runId=16112530&resultId=100489&paneView=debug

```
System.ArgumentOutOfRangeException : StartIndex cannot be less than zero.\r\nParameter name: startIndex


Stack trace

Server stack trace: 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.GetLastReplOutput()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 getValue, Func`2 isExpectedValue)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutput(String outputText)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutput(String outputText)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.WaitForLastReplOutput(String outputText) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/InteractiveWindow_OutOfProc.cs:line 79
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveDirectives.VerifyHashReset() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveDirectives.cs:line 191
```

**Comment by sharwell** [comment]
@tmat it looks like the "Resetting execution engine." operation never completed.

![image](https://user-images.githubusercontent.com/1408396/74375991-2e926280-4d96-11ea-9fab-92220312bf8a.png)

**Comment by 333fred** [comment]
Failed in https://github.com/dotnet/roslyn/pull/44954.
