### ISSUE TITLE
NullReferenceException at PlaceholderLocalSymbol.GetInstrinsicMethod

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4140]
```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExceptionLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitConversion(BoundConversion node)
at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExceptionLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Micr...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExceptionLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.Code...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExceptionLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.C...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.LocalDeclarationRewriter.RewriteLocalDeclaration(CSharpCompilation compilation; EENamedTypeSymbol container; HashSet`1 declaredLocals; ArrayBuilder`1 statements; BoundLocalDeclaration node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.LocalDeclarationRewriter.Rewrite(CSharpCompilation compilation; EENamedTypeSymbol container; HashSet`1 declaredLocals; BoundNode node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EEMethodSymbol.GenerateMethodBody(TypeCompilationState compilationState; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(ImmutableArray`1 additionalTypes; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation; PEModuleBuilder moduleBeingBuiltOpt...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ReturnValueLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Mi...
```

```
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalSymbol.GetIntrinsicMethod(CSharpCompilation compilation; String methodName)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ReturnValueLocalSymbol.RewriteLocal(CSharpCompilation compilation; EENamedTypeSymbol container; CSharpSyntaxNode syntax; DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.RewriteLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.PlaceholderLocalRewriter.VisitLocal(BoundLocal node)
at Microsoft.CodeAnalysis.CSharp.BoundLocal.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
at Microsoft.Co...
```

**Comment by amcasey** [comment]
FYI @cston
