### ISSUE TITLE
MSBuildWorkspaceTests.Test_OpenProjectReferencingPortableProject Test failure

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#41456]
The following test always fails on my machine:

```none
 Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTests.Test_OpenProjectReferencingPortableProject
\r\nExpected:\r\n\r\nActual:\r\nMsbuild failed when processing the file 'C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\ReferencesPortableProject.csproj' with message: C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj: (44, 11): The imported project \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\MSBuild\\Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" was not found. Also, tried to find \"Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" in the fallback search path(s) for $(MSBuildExtensionsPath32) - \"C:\\Program Files (x86)\\MSBuild\" . These search paths are defined in \"R:\\roslyn\\artifacts\\bin\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests\\Debug\\net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.dll.config\". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.,\r\nMsbuild failed when processing the file 'C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj' with message: The imported project \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\MSBuild\\Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" was not found. Also, tried to find \"Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" in the fallback search path(s) for $(MSBuildExtensionsPath32) - \"C:\\Program Files (x86)\\MSBuild\" . These search paths are defined in \"R:\\roslyn\\artifacts\\bin\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests\\Debug\\net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.dll.config\". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj\r\nDifferences:\r\n++> Msbuild failed when processing the file 'C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\ReferencesPortableProject.csproj' with message: C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj: (44, 11): The imported project \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\MSBuild\\Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" was not found. Also, tried to find \"Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" in the fallback search path(s) for $(MSBuildExtensionsPath32) - \"C:\\Program Files (x86)\\MSBuild\" . These search paths are defined in \"R:\\roslyn\\artifacts\\bin\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests\\Debug\\net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.dll.config\". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.,\r\n++> Msbuild failed when processing the file 'C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj' with message: The imported project \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\MSBuild\\Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" was not found. Also, tried to find \"Microsoft\\Portable\\v4.5\\Microsoft.Portable.CSharp.targets\" in the fallback search path(s) for $(MSBuildExtensionsPath32) - \"C:\\Program Files (x86)\\MSBuild\" . These search paths are defined in \"R:\\roslyn\\artifacts\\bin\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests\\Debug\\net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.dll.config\". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\\Users\\ngafter\\AppData\\Local\\Temp\\RoslynTests\\f6f186d6-4561-42ee-bb5b-a24aca92fdee\\CSharpProject\\PortableProject.csproj\r\n\r\nExpected: True\r\nActual:   False
   at Roslyn.Test.Utilities.AssertEx.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector, String expectedValueSourcePath, Int32 expectedValueSourceLine) in R:\roslyn\src\Test\Utilities\Portable\Assert\AssertEx.cs:line 230
   at Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTestBase.AssertFailures(MSBuildWorkspace workspace, String[] expectedFailures) in R:\roslyn\src\Workspaces\MSBuildTest\MSBuildWorkspaceTestBase.cs:line 25
   at Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTests.<Test_OpenProjectReferencingPortableProject>d__3.MoveNext() in R:\roslyn\src\Workspaces\MSBuildTest\MSBuildWorkspaceTests.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

FYI the directory `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft` does not contain a subdirectory `v4.5`.

**Comment by jmarolf** [comment]
portable class libraries are no longer supported by default in Visual Studio.
