### ISSUE TITLE
Navigating to the error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41688]
**Version Used**: 

**Steps to Reproduce**:

1. Create project like:
``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>

    <Compile Include="..\..\Shared\NonExistentFile.cs">
    </Compile>

  </ItemGroup>

</Project>

```
2. Navigate to:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1100	Error reading content of source file 'C:\Users\davkean\source\repos\Shared\Class1.cs' -- 'Could not find file 'C:\Users\davkean\source\repos\Shared\Class1.cs'.'.	𪛑𪛒𪛓𪛔	C:\Users\davkean\source\repos\Shared\Class1.cs	1	Active

```
**Expected Behavior**:
No yellow bar

**Actual Behavior**:
Yellow bar:

```
System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocumentCore(DocumentId documentId, Boolean activate)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocument(DocumentId documentId, Boolean activate)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.OpenDocument(Workspace workspace, DocumentId documentId)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToLineAndOffset(Workspace workspace, DocumentId documentId, Int32 lineNumber, Int32 offset, OptionSet options)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableEntriesSnapshot`1.TryNavigateTo(Workspace workspace, DocumentId documentId, LinePosition position, Boolean previewTab)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableEntriesSnapshot`1.TryNavigateToItem(Int32 index, Boolean previewTab)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSnapshot.TryNavigateTo(Int32 index, Boolean previewTab)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableControlEventProcessorProvider`1.EventProcessor.PreprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass40_0.&lt;OnEntryElementNavigate&gt;b__2(ITableControlEventProcessor p, ITableEntryHandle entry)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass60_1`1.&lt;EventProcessorHandler&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

**Comment by sharwell** [comment]
Just hit this today.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocumentCore(DocumentId documentId, Boolean activate)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocument(DocumentId documentId, Boolean activate)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.OpenDocument(Workspace workspace, DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToLineAndOffset(Workspace workspace, DocumentId documentId, Int32 lineNumber, Int32 offset, OptionSet options)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableEntriesSnapshot`1.TryNavigateTo(Workspace workspace, DocumentId documentId, LinePosition position, Boolean previewTab)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableEntriesSnapshot`1.TryNavigateToItem(Int32 index, Boolean previewTab)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSnapshot.TryNavigateTo(Int32 index, Boolean previewTab)
   at Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.AbstractTableControlEventProcessorProvider`1.EventProcessor.PreprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass40_0.<OnEntryElementNavigate>b__2(ITableControlEventProcessor p, ITableEntryHandle entry)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.<>c__DisplayClass60_1`1.<EventProcessorHandler>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by tamlin-mike** [comment]
Also hit it now, though in my case the file exists. Tried to navigate from the "quick look view" of a type to the full edit view using F12.

VS 16.7.7

<details>
<summary>Stack trace</summary>
<pre>    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;
      at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocumentCore(DocumentId documentId, Boolean activate)&#x000D;&#x000A;
      at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OpenDocument(DocumentId documentId, Boolean activate)&#x000D;&#x000A;
      at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.OpenDocument(Workspace workspace, DocumentId documentId)&#x000D;&#x000A;
      at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToSpan(Workspace workspace, DocumentId documentId, TextSpan textSpan, OptionSet options)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.DocumentSpanExtensions.TryNavigateTo(DocumentSpan documentSpan, NavigationBehavior navigationBehavior)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryNavigateTo(Workspace workspace, NavigationBehavior navigationBehavior)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.Editor.Host.IStreamingFindUsagesPresenterExtensions.&lt;TryNavigateToOrPresentItemsAsync&gt;d__0.MoveNext()&#x000D;&#x000A;
      --- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;
      at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;
      at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()&#x000D;&#x000A;
      at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionHelpers.TryGoToDefinition(ISymbol symbol, Solution solution, IThreadingContext threadingContext, IStreamingFindUsagesPresenter streamingPresenter, CancellationToken cancellationToken, Boolean thirdPartyNavigationAllowed)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.Editor.GoToDefinition.AbstractGoToDefinitionService.TryGoToDefinition(Document document, Int32 position, CancellationToken cancellationToken)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand(Document document, Int32 caretPosition, IGoToDefinitionService goToDefinitionService, CommandExecutionContext context)&#x000D;&#x000A;
      at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.ExecuteCommand(GoToDefinitionCommandArgs args, CommandExecutionContext context)&#x000D;&#x000A;
      at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass14_1`1.&lt;ExecuteStartingAtIndex&gt;b__0()&#x000D;&#x000A;
      at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
</pre>
</details>
