### ISSUE TITLE
Initializing interactive window with project causes FailFast due to NRE in RemoteService.Dispose

### ISSUE THREAD

**Issue by LinqToException** [dotnet/roslyn#41731]
**Version Used**: 
- VS Enterprise 2019; 16.4.4
- Microsoft (R) Visual C# Interactive Compiler version 3.4.1-beta4-19614-01

**Steps to Reproduce**:
Not reproducible anymore. Original steps that led to this behaviour:

1. Creating a new solution, .NET Framework 4.7.2 Console Application (Project A)
2. Add a new project (Project B)
3. Add an internal class to Project A.
4. Add an `IgnoresAccessChecksToAttribute` to project B which allows access to A.
5. Have the `Main` method of Project B reference the class from Project A by typing its name and having Intellisense auto-complete & auto-reference it.
6. Try to initialize the C# interactive window with Project A by right-clicking it in the solution explorer.
7. VS crashes and restarts.
8. VS crashes and restarts every time this is attempted. Re-builds do not seem to change this behaviour.

After commenting the attribute definition as well as its usage in Project B out and making the class public, rebuilding it and trying to initialize it again, it works. Commenting the attribute in again results in it still working - so the crash is gone.

I've tried reproducing this crash by going through the same steps again with a new solution, but have not been able to get it to crash again.

**Event Log Entries:**

```
Faulting application name: devenv.exe, version: 16.4.29728.190, time stamp: 0x5e312a76
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80131623
Fault offset: 0x14555a7a
Faulting process id: 0x1fa8
Faulting application start time: 0x01d5e424d5838e24
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: d123479b-ea18-4d7e-ba79-800f56558cd6
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.RemoteService.Dispose()
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.LazyRemoteService.<TryStartAndInitializeProcessAsync>d__8.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost+LazyRemoteService+<TryStartAndInitializeProcessAsync>d__8.MoveNext()
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost+RemoteService.Dispose()
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost+LazyRemoteService+<TryStartAndInitializeProcessAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SetResult(Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost+<Async>d__46`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult)
   at System.Threading.Tasks.TaskCompletionSource`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost+RemoteAsyncOperation`1[[Microsoft.CodeAnalysis.Interactive.RemoteExecutionResult, Microsoft.CodeAnalysis.InteractiveHost, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].<.ctor>b__3_0(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)
```

**Comment by tmat** [comment]
Seems like an issue addressed in https://github.com/dotnet/roslyn/pull/40542. Please reopen if it reproduces in 16.5 Preview 2 or newer.
