### ISSUE TITLE
Flaky test CodeGenOperators.EmitSequenceOfBinaryExpressions_06

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#41900]
The following failure occurs from time to time:

``` none
Failed tests 
0.9740011s 
✘ Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenOperators.EmitSequenceOfBinaryExpressions_06
System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.\r\n---- System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.StartNew(Action`1 action, Object state, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 786
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
   at Roslyn.Utilities.ObjectWriter.WriteValue(IObjectWritable value) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 277
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.BinaryExpressionSyntax.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\CSharp\Portable\Generated\Syntax.xml.Internal.Generated.cs:line 2937
   at Microsoft.CodeAnalysis.GreenNode.Roslyn.Utilities.IObjectWritable.WriteTo(ObjectWriter writer) in R:\roslyn\src\Compilers\Core\Portable\Syntax\GreenNode.cs:line 457
   at Roslyn.Utilities.ObjectWriter.WriteObjectWorker(IObjectWritable writable) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 822
   at Roslyn.Utilities.ObjectWriter.WriteObject(Object instance, IObjectWritable instanceAsWritableOpt) in R:\roslyn\src\Compilers\Core\Portable\Serialization\ObjectWriter.cs:line 804
(and lots more)
```

**Comment by jcouv** [comment]
It looks like there has been zero occurrences of this flakiness in the last 30 days ([runfo](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aroslyn-ci+name%3ACodeGenOperators)). I'll go ahead and close
