### ISSUE TITLE
Can't rename Enum. Some enum works, but some don't

### ISSUE THREAD

**Issue by qcnguyen** [dotnet/roslyn#42131]
**Version Used**: Visual studio 2019 - Version 16.5.0 Preview 5.0

**Steps to Reproduce**:

1. Rename Enum

**Expected Behavior**: rename ok

**Actual Behavior**: exception thrown:
`System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.FixReferencesAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.FixReferencingDocumentAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceInSingleDocumentAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveToNamespace.AbstractMoveToNamespaceService`3.MoveItemsInNamespaceAsync[TCompilationUnitSyntax,TNamespaceDeclarationSyntax,TNamedTypeDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveToNamespace.AbstractMoveToNamespaceService`3.MoveTypeToNamespaceAsync[TCompilationUnitSyntax,TNamespaceDeclarationSyntax,TNamedTypeDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MoveToNamespace.AbstractMoveToNamespaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)`

**Comment by ryzngard** [comment]
@qcnguyen thanks for the report.  The stack included looks like a bug in one of our refactorings (Move to namespace). That said, it shouldn't negatively impact the ability to rename. It should crash and disable in isolation. Is there any other errors? If you can still repro the issue, can you report the problem to get logs using these steps https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019 ?
