### ISSUE TITLE
NullReferenceException binding invalid using local declaration

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42387]
Compile the following:
```C#
class Program
{
    static System.IDisposable F() => null;

    static void Main()
    {
        using const System.IDisposable o = F();
    }
}
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.BoundNodeExtensions.HasErrors[T](ImmutableArray`1 nodeArray) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundNodeExtensions.cs:line 25
   at Microsoft.CodeAnalysis.CSharp.BoundBlock..ctor(SyntaxNode syntax, ImmutableArray`1 locals, ImmutableArray`1 localFunctions, ImmutableArray`1 statements, Boolean hasErrors) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2556
   at Microsoft.CodeAnalysis.CSharp.BoundBlock..ctor(SyntaxNode syntax, ImmutableArray`1 locals, ImmutableArray`1 statements, Boolean hasErrors) in /_/src/Compilers/CSharp/Portable/BoundTree/Constructors.cs:line 602
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.SynthesizedNoLocals(SyntaxNode syntax, BoundStatement[] statements) in /_/src/Compilers/CSharp/Portable/BoundTree/Constructors.cs:line 619
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteDeclarationUsingStatement(SyntaxNode usingSyntax, BoundLocalDeclaration localDeclaration, BoundBlock tryBlock, Conversion iDisposableConversion, SyntaxToken awaitKeywordOpt, BoundAwaitableInfo awaitOpt, MethodSymbol methodSymbol) in /_/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs:line 257
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeDeclarationUsingStatement(SyntaxNode syntax, BoundBlock body, ImmutableArray`1 locals, ImmutableArray`1 declarations, Conversion iDisposableConversion, MethodSymbol disposeMethodOpt, BoundAwaitableInfo awaitOpt, SyntaxToken awaitKeyword) in /_/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs:line 70
...
```

**Comment by cston** [comment]
cc @chsienki

**Comment by chsienki** [comment]
Dupe of #42362
