### ISSUE TITLE
C# Compiler is bundling resx/resources with a different path when building across a symlink

### ISSUE THREAD

**Issue by mdshaner** [dotnet/roslyn#42390]
**Version Used**: 3.1.102

**Steps to Reproduce**: 
-Reproduction Case Repo- https://github.com/mdshaner/dotnet-symlink-res-mrc

1. `git clone https://github.com/mdshaner/dotnet-symlink-res-mrc.git`
2. `mv TestApp/Resources ~/Resources`
3. `ln -s ~/Resources TestApp/Resources`
4. Within the TestRunner project, `dotnet build; dotnet run`

**Expected Behavior**: The embedded resx should be embedded with the same path even if built through a symlink

> Testing
> Hello World!

**Actual Behavior**: When built through a symlink, the embedded resx is embedded to a different path than when not (`Resources.Common.resources` vs `Resources.resx.Common.Common.resources`)

>Unhandled exception. System.Resources.MissingManifestResourceException: Could not find the resource "Resources.resx.Common.Common.resources" among the resources "Resources.Common.resources" embedded in the assembly "Resources", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
>   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
>   at CustomNamespace.Common.get_Test() in /Users/devusr/Work/Resources/resx/Common/Common.Designer.cs:line 52
>   at TestRunner.Program.Main(String[] args) in /Users/devusr/Newish/TestApp/TestRunner/Program.cs:line 10

This issue does not occur when building on windows, but it does occur on Linux + macOS. If built on windows, and run on Linux/macOS it runs as expected as well.
Within 'TestApp/Resources/obj/Debug/netstandard2.0', the .resources files also seem to have an unexpected filename (`Resources.Common.resources` vs `Resources.resx.Common.Common.resources`)

**Comment by mdshaner** [comment]
After looking at this, I'm also not sure if the Roslyn repo is the right, would the msbuild be the appropriate repo for this issue instead? I apologize if I put it in the wrong place.
