### ISSUE TITLE
Using tuples in PEModule causes TestAnalyzerLoading to fail in Debug legs

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#42423]
Relates to PR https://github.com/dotnet/roslyn/pull/41675 which was unblocked by changing the use of tuples to use a custom struct.

```
Assert.Null() Failure\r\nExpected: (null)\r\nActual: System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.PEModule' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.\r\n\r\n --- End of inner exception stack trace ---\r\n at Microsoft.CodeAnalysis.PEModule..cctor()\r\n --- End of inner exception stack trace ---\r\n at Microsoft.CodeAnalysis.PEModule..ctor(ModuleMetadata owner, PEReader peReader, IntPtr metadataOpt, Int32 metadataSizeOpt, Boolean includeEmbeddedInteropTypes, Boolean ignoreAssemblyRefs)\r\n at Microsoft.CodeAnalysis.ModuleMetadata..ctor(PEReader peReader) in //src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs:line 31\r\n at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options) in //src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs:line 182\r\n at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, Boolean leaveOpen) in //src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs:line 141\r\n at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromFile(String path) in //src/Compilers/Core/Portable/MetadataReference/ModuleMetadata.cs:line 200\r\n at Microsoft.CodeAnalysis.AssemblyMetadata.CreateFromFile(String path) in //src/Compilers/Core/Portable/MetadataReference/AssemblyMetadata.cs:line 166\r\n at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.GetAnalyzerTypeNameMap(String fullPath, AttributePredicate attributePredicate) in //src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:line 168\r\n at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions1.GetExtensionTypeNameMap() in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:line 314\r\n at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions1.AddExtensions(Builder builder, String language) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:line 372


Stack trace
   at Microsoft.CodeAnalysis.UnitTests.AnalyzerFileReferenceTests.TestAnalyzerLoading() in /_/src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs:line 198
```

**Comment by sharwell** [comment]
The test creates an incomplete AppDomain and then attempts to use it. Fixing the AppDomain setup and/or providing an assembly resolver that can see back to the original domain would fix it.
