### ISSUE TITLE
[Microsoft.CodeAnalysis] 'GenerateMethodCodeFixProvider' encountered an error and has been disabled when typing nullable enum

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/952684/microsoftcodeanalysis-generatemethodcodefixprovide.html)._

---
[regression] [worked-in:16.4 preview 6]
Typing near a nullable enum declaration, getting this error.

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'TypeSymbolWithNullableAnnotation'.
   at Microsoft.CodeAnalysis.NullableExtensions.WithNullability[T](T typeSymbol,NullableAnnotation nullability)
   at Microsoft.CodeAnalysis.NullableExtensions.TypeSymbolWithNullableAnnotation.Microsoft.CodeAnalysis.ITypeSymbol.WithNullableAnnotation(NullableAnnotation nullableAnnotation)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalent(ISymbol x,ISymbol y,Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.Equals(IParameterSymbol x,IParameterSymbol y,Dictionary`2 equivalentTypesWithDifferingAssemblies,Boolean compareParameterName,Boolean isCaseSensitive)
   at Microsoft.CodeAnalysis.Shared.Utilities.SignatureComparer.HaveSameSignature(IList`1 parameters1,IList`1 parameters2,Boolean compareParameterName,Boolean isCaseSensitive)
   at Microsoft.CodeAnalysis.Shared.Utilities.SignatureComparer.HaveSameSignature(IMethodSymbol method1,IMethodSymbol method2,Boolean caseSensitive,Boolean compareParameterName,Boolean isParameterCaseSensitive)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.<>c__DisplayClass55_0. <TryFinishInitializingStateAsync>b__0(IMethodSymbol m)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.TryFinishInitializingStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.GenerateMethodStateAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.GenerateMethodAsync[TService,TSimpleNameSyntax,TExpressionSyntax,TInvocationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 12/9/2019, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/16/2020, 05:44 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

**Comment by jasonmalinowski** [comment]
This would have been fixed by now since that code doesn't exist -- this was some odd interaction with our workaround for nullable APIs.
