### ISSUE TITLE
VS crashes upon refactoring some code to extract a new method

### ISSUE THREAD

**Issue by ahmedahamid** [dotnet/roslyn#4251]
Unable to share code snippet. Crash dump is right here: http://1drv.ms/1OEm2zV.
VS version: 14.0.23107.0
Windows version: 10.0 Build 10176.0

**Comment by balajikris** [comment]
~~~
Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.VisualStudio.Text.Utilities.FrugalList`1.get_Item(Int32 index) in f:\dd\src\Platform\Text\Util\TextDataUtil\FrugalList.cs:line 263
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapToSourceSnapshot(Int32 position) in f:\dd\src\Platform\Text\Impl\TextModel\Projection\ProjectionSnapshot.cs:line 489
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToInsertionPoint(SnapshotPoint position, PointTrackingMode trackingMode, Predicate`1 match) in f:\dd\src\Platform\Text\Impl\TextModel\Projection\BufferGraph.cs:line 168
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.IBufferGraphExtensions.MapUpOrDownToBuffer(IBufferGraph bufferGraph, SnapshotPoint point, ITextBuffer targetBuffer) in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Extensions\IBufferGraphExtensions.cs:line 66
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextViewExtensions.GetCaretPoint(ITextView textView, ITextBuffer subjectBuffer) in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Extensions\ITextViewExtensions.cs:line 34
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.ViewTagSource`1.GetCaretPoint() in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Tagging\TagSources\ViewTagSource.cs:line 40
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.RecomputeTagsForeground() in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Shared\Tagging\TagSources\ProducerPopulatedTagSource.cs:line 404
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker() in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\ForegroundNotification\ForegroundNotificationService.cs:line 116
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground() in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\EditorFeatures\Core\Implementation\ForegroundNotification\ForegroundNotificationService.cs:line 90
   at Roslyn.Utilities.TaskFactoryExtensions.<>c__DisplayClass1_0.<SafeStartNew>b__0() in F:\Builds\6272\Roslyn\Dev14RTM-Signed-Release\src\Open\src\Workspaces\Core\Portable\Utilities\TaskFactoryExtensions.cs:line 30
~~~

**Comment by Pilchie** [comment]
From a customer feedback bug, extracting `newdic` in the this sample:

``` C#
using System;
using System.Collections.Generic;
using static System.Console;

class Program
{
    static void Main(string[] args)
    {
        var newdic = new Dictionary<int, string>
        {
            [1] = "something",
            [2] = "otherthing",
        };

        var now = DateTime.Now;
        WriteLine("${now}");
        ReadLine();
    }
}
```

Also repros this.

**Comment by balajikris** [comment]
Thanks, will make a note to verify all reports when fixing this.

Note to self: see internal bug 1209739 and all associated vs feedback items.

**Comment by balajikris** [comment]
_status_: **Reproducible** using the code snippet given above
_Notes_:
From preliminary investigations, this does not appear to be a bug in extract method. Extract Method command (Ctrl + R, M) works perfectly in all such cases. However, trying to invoke Extract Method via Lightbulb UI brings up a crash due to ArgumentOutOfRange Exception.

**Comment by balajikris** [comment]
Looks like an editor bug to me at this point. Will file a bug for the editor team and use this as a tracking bug for updates.

**Comment by balajikris** [comment]
Filed 1212762 internally for the editor team. Also added context and related (vs-feedback items) to this bug.

**Comment by dpoeschl** [comment]
Work in progress at https://github.com/dpoeschl/roslyn/tree/LightBulbDiffProjectionBufferCrash

**Comment by balajikris** [comment]
The editor team has fixed IBufferGraph.MapDownToInsertionPoint to handle literal buffers better. So, we may not need to fix it on our end. Have to test using latest editor bits with the change to confirm.

**Comment by dpoeschl** [comment]
This is tracked internally by bug 142856. I've left a note there to verify & update this thread when it is tested.
