### ISSUE TITLE
CSharp.Emit.UnitTests are flaky 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#42590]
Failing builds:
- https://dev.azure.com/dnceng/public/_build/results?buildId=558830&view=results

Stack trace of failure:

```
    Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncIteratorTests.TryFinally_Goto(iterations: 5, expectedOutput: "0 1 Finally 2 3 Finally END DISPOSAL DONE") [STARTING]
0 1 Finally 2 3 Finally END DISPOSAL DONE    Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncIteratorTests.TryFinally_Goto(iterations: 5, expectedOutput: "0 1 Finally 2 3 Finally END DISPOSAL DONE") [FINISHED] Time: 0.1190328s
    Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncIteratorTests.AsyncIteratorWithReturnNull [STARTING]
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at D.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.ValueTaskAwaiter.<>c.<.cctor>b__9_0(Object state)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.InvokeContinuation()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
   at C.<M>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.RunAction(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by jcouv** [comment]
@jaredpar As far as I know, all flakiness issues with async-streams have been fixed by PR https://github.com/dotnet/roslyn/pull/58864 (the linked issues have runinfo results showing zero occurrences for at least a month).
Can we close this issue too?
