### ISSUE TITLE
Invalid code generated for nullable conversion to IntPtr?

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42834]
```C#
using System;

class Program
{
    static System.IntPtr Convert1(double? value)
    {
        return (System.IntPtr)value;
    }

    static System.IntPtr? Convert2(double? value)
    {
        return (System.IntPtr?)value;
    }

    static void Main()
    {
        double? d = 42;
        Console.WriteLine(Convert1(d));
        Console.WriteLine(Convert2(d));
    }
}
```
Result:
```
> c.exe
42
11529392
```
It looks like the IL generated for `Convert2` is missing a `conv.i8` when compared to `Convert1`.

**Comment by cston** [comment]
Similar issue with `decimal`, although in that case the generated code is missing a call to `decimal.op_Explicit(decimal)` in `Convert2`:
```C#
using System;

class Program
{
    static System.UIntPtr Convert1(decimal? value)
    {
        return (System.UIntPtr)value;
    }

    static System.UIntPtr? Convert2(decimal? value)
    {
        return (System.UIntPtr?)value;
    }

    static void Main()
    {
        decimal? d = 42;
        Console.WriteLine(Convert1(d));
        Console.WriteLine(Convert2(d));
    }
}
```

**Comment by cston** [comment]
Another example where the conversion is dropped. And in this case, an assertion fails in `LocalRewriter.MakeLiftedUserDefinedConversionConsequence()` as well.
```C#
class Program
{
    static char? Convert(System.IntPtr? value)
    {
        return (char?)value;
    }
}
```

**Comment by jcouv** [comment]
When trying on ([sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoa0gAiLIHZqBvauzhspbgOgCSeDAAUMUOgGEIeAG4woGMgAoAJhBzAANjAD8dWQEMtOGAEoOXdlS62GTOssaDhYqGaMmYAbkucAvtR+3LzOQqLi+tJyChgkahraegbGphY2VsG2RA5OZC4RULoeqT7BgTQZnIyhKHQAsoYAlnjK6bbWdlzqmjr6qnQAvHQoJL5VdowAnMrR8ooqqmZm413VZDNzsfFLK+XU/kA===)), I'm getting an exception from `Convert2`:
```
42
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Program.Convert2(Nullable`1 value)
   at Program.Main()
```
