### ISSUE TITLE
Scripting error

### ISSUE THREAD

**Issue by Hetal728** [dotnet/roslyn#4283]
I was using the nightly build in one of my projects and I got "The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception." from "result = CSharpScript.EvaluateAsync(code, ScriptOptions.Default);"

**Comment by svick** [comment]
Could you post the full exception, including the inner exception and the stack trace?

**Comment by Hetal728** [comment]
System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, Boolean leaveOpen)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(Assembly[] assemblies)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.Scripting.Script..ctor(String code, String path, ScriptOptions options, Type globalsType, ScriptBuilder builder, Script previous)
   at Microsoft.CodeAnalysis.Scripting.CSharp.CSharpScript.EvaluateAsync(String code, CancellationToken cancellationToken)

**Comment by Hetal728** [comment]
System.Reflection.Metadata version is 1.0.21.0

**Comment by ManishJayaswal** [comment]
This has been added back. Using the latest packages from myget feed should have this functionality.

**Comment by richardfencel** [comment]
Thanks very much for letting me know
