### ISSUE TITLE
Black punctuation in dark theme caused by exception during color scheme initialization

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#42905]
I'm seeing black punctuation in the dark theme after deleting my RoslynDev hive. Stepping through the ColorSchemeApplier results in an ArgumentException with the stack below.

<details>
<summary>Stack Trace</summary>
   at System.Enum.ToObject(Type enumType, Object value) in f:\dd\ndp\clr\src\BCL\system\enum.cs:line 590
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.RoamingVisualStudioProfileOptionPersister.TryFetch(OptionKey optionKey, Object& value) in C:\src\ros\src\VisualStudio\Core\Def\Implementation\Options\RoamingVisualStudioProfileOptionPersister.cs:line 158
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.LoadOptionFromSerializerOrGetDefault(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\GlobalOptionService.cs:line 96
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption_NoLock(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\GlobalOptionService.cs:line 283
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\GlobalOptionService.cs:line 272
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.GetOption(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\OptionServiceFactory.cs:line 124
   at Microsoft.CodeAnalysis.Options.SerializableOptionSet.WorkspaceOptionSet.GetOption(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\SerializableOptionSet.WorkspaceOptionSet.cs:line 47
   at Microsoft.CodeAnalysis.Options.SerializableOptionSet.GetOption(OptionKey optionKey) in C:\src\ros\src\Workspaces\Core\Portable\Options\SerializableOptionSet.cs:line 116
   at Microsoft.CodeAnalysis.Options.SerializableOptionSet.WithChangedOption(OptionKey optionKey, Object value) in C:\src\ros\src\Workspaces\Core\Portable\Options\SerializableOptionSet.cs:line 126
   at Microsoft.CodeAnalysis.Options.OptionSet.WithChangedOption[T](Option2`1 option, T value) in C:\src\ros\src\Workspaces\Core\Portable\Options\OptionSet.cs:line 84
   at Microsoft.VisualStudio.LanguageServices.ColorSchemes.ColorSchemeApplier.ColorSchemeSettings.MigrateToColorSchemeSetting(Boolean isThemeCustomized) in C:\src\ros\src\VisualStudio\Core\Def\Implementation\ColorSchemes\ColorSchemeApplier.Settings.cs:line 134
   at Microsoft.VisualStudio.LanguageServices.ColorSchemes.ColorSchemeApplier.UpdateColorScheme(Boolean themeChanged) in C:\src\ros\src\VisualStudio\Core\Def\Implementation\ColorSchemes\ColorSchemeApplier.cs:line 124
   at Microsoft.VisualStudio.LanguageServices.ColorSchemes.ColorSchemeApplier.<>c__DisplayClass19_0.<QueueColorSchemeUpdate>b__0() in C:\src\ros\src\VisualStudio\Core\Def\Implementation\ColorSchemes\ColorSchemeApplier.cs:line 106
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass7_0.<CreateTaskBody>b__0(IVsTask task, IVsTask[] parents) in Q:\cmd\r\src\env\shell\PackageFramework\Current\Shell\VsTaskLibraryHelper.cs:line 117
   at Microsoft.VisualStudio.Shell.VsManagedTaskBody.DoWork(IVsTask pTask, UInt32 dwCount, IVsTask[] pParentTasks, Object& pResult) in Q:\cmd\r\src\env\shell\PackageFramework\Current\Shell\VsTaskLibraryHelper.cs:line 1111
   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass118_0.<GetCallbackForMultipleParent>b__0(Task`1[] _) in Q:\cmd\d\src\env\shell\UIInternal\Packages\TaskScheduler\VsTask.cs:line 1140
</details>

Also, the "Editor Color Scheme" dropdown in Tools | Options | Text Editor | C# | Advanced is blank, and switching to one of the themes (2017 or 2019) has no effect:

![image](https://user-images.githubusercontent.com/235241/77944032-0e016780-7273-11ea-9f4f-05cd052cc109.png)

**Comment by JoeRobich** [comment]
Troubleshot offline and this was a local configuration issue with the dev hive.

**Comment by CyrusNajmabadi** [comment]
I'm also seeing this whne a project loads initially.  Then the actual colors seem to take effect, and things turn white.  It's not a good experience.  Do we know what's up here?

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/77962576-ae19b980-7290-11ea-84ce-ec689e689153.png)

Repros 100% of the time for me.

**Comment by JoeRobich** [comment]
Should be resolved with https://github.com/dotnet/roslyn/pull/43200

**Comment by JoeRobich** [comment]
Closing for now. Please reopen if you still see issues in builds with this change.
