### ISSUE TITLE
NullReferenceException in GetLanguageProviders

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#42982]
Found in the following build https://dev.azure.com/dnceng/public/_build/results?buildId=582697

```
 at Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest) in /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:line 142
----- Inner Stack Trace -----
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractEmbeddedLanguageCompletionProvider.GetLanguageProviders[T](Func`2 documentProvider, T state) in /_/src/Features/Core/Portable/Completion/Providers/AbstractEmbeddedLanguageCompletionProvider.cs:line 39
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractEmbeddedLanguageCompletionProvider.ShouldTriggerCompletion(SourceText text, Int32 caretPosition, CompletionTrigger trigger, OptionSet options) in /_/src/Features/Core/Portable/Completion/Providers/AbstractEmbeddedLanguageCompletionProvider.cs:line 48
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<>c__DisplayClass22_0.<GetCompletionsWithAvailabilityOfExpandedItemsAsync>b__3(CompletionProvider p) in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 228
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Roslyn.Utilities.ImmutableArrayExtensions.ToImmutableArrayOrEmpty[T](IEnumerable`1 items) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ImmutableArrayExtensions.cs:line 45
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsWithAvailabilityOfExpandedItemsAsync>d__22.MoveNext() in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource.<GetCompletionContextWorkerAsync>d__25.MoveNext() in /_/src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__36`1.MoveNext()
```

**Comment by 333fred** [comment]
I hit this when attempting to implement completion for Omnisharp. I'm seeing an exception on this line: https://github.com/dotnet/roslyn/blob/f244a9377cd43685fa56dfa9c9a0b374f4560cd9/src/Features/Core/Portable/Completion/Providers/AbstractEmbeddedLanguageCompletionProvider.cs#L39. Specifically, the call to `documentProvider(state)` is returning a `null` workspace. This only reproduces when you call `GetCompletions` _with_ an insertion or deletion trigger in a location that would cause embedded providers to be queried. A minimal example of this:
```cs
        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
        public async Task EmbeddedProviderNullRef()
        {
            var code = @"using System;

class C 
{
    void M()
    {
        var m = new $$";

            using var workspace = TestWorkspace.CreateCSharp(code);
            var testDocument = workspace.Documents.Single();
            var position = testDocument.CursorPosition.Value;

            var document = workspace.CurrentSolution.GetDocument(testDocument.Id);
            var service = CompletionService.GetService(document);
            var completions = await service.GetCompletionsAsync(document, position, CodeAnalysis.Completion.CompletionTrigger.CreateInsertionTrigger(' '));
        }

```

The null ref vanishes if the insertion trigger is removed (defaulting to Invoked).

**Comment by 333fred** [comment]
@jasonmalinowski I'm not exactly sure when this happened, but I'm no longer seeing the failures above with `3.10.0-1.21125.6`.

**Comment by jasonmalinowski** [comment]
@333fred Any hunch if you've heard of other failures since they seemed to go away?
@ashmind Is this still impacting that SharpLab issue? I see the bug is being updated but are those really old/stale branches?

**Comment by 333fred** [comment]
Not that I've heard of.

**Comment by ashmind** [comment]
Yep based on the data seems to be only old branches, so I would say resolved from SharpLab perspective.

**Comment by CyrusNajmabadi** [comment]
I odn't see any hits for this.  And it sounds like this is no longer a problem for sharplab or omnisharp.  So going to close out.
