### ISSUE TITLE
Fix flaky suite CodeGenAsyncTests.Return07_2

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#4300]
The Return07_2 test is periodically failing with the below stack trace.  Need to fix the flaky behavior and re-enable the suite:

```
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.Return07_2 : Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : Execution failed for assembly 'C:\Users\acasey\AppData\Local\Temp\RoslynTestFailureDump\de5c3197-023b-4a93-af6d-6f556d27c828'. Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. at TestCase.<>c__DisplayClass6.<<Run>b__9>d__0.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine) at TestCase.<>c__DisplayClass6.<Run>b__9() at TestCase.<Run>d__1.MoveNext() at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at TestCase.Run() at Driver.Main() ---- System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, Int32 expectedOutputLength, String& processOutput) in F:\Enlistments\Roslyn1\Open\Test\Utilities\HostedRuntimeEnvironment.cs:line 257
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput) in F:\Enlistments\Roslyn1\Open\Test\Utilities\HostedRuntimeEnvironment.cs:line 264
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.CompilationVerifier.cs:line 114
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitOptions, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.cs:line 400
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.cs:line 202
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`1 sourceSymbolValidator, Action`2 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.CompileAndVerify(String source, String expectedOutput, IEnumerable`1 references, TestEmitters emitOptions, CSharpCompilationOptions compOptions) in F:\Enlistments\Roslyn1\Open\Compilers\CSharp\Test\Emit\CodeGen\CodeGenAsyncTests.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.Return07_2() in F:\Enlistments\Roslyn1\Open\Compilers\CSharp\Test\Emit\CodeGen\CodeGenAsyncTests.cs:line 1984
----- Inner Stack Trace -----
   at TestCase.<>c__DisplayClass6.<<Run>b__9>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at TestCase.<>c__DisplayClass6.<Run>b__9()
   at TestCase.<Run>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at TestCase.Run()
   at Driver.Main()
```

**Comment by jaredpar** [comment]
This should be fixed now.  Will re-enable and let it run through Jenkins.
