### ISSUE TITLE
Deleting a file in SDK-style project causes non-fatal error

### ISSUE THREAD

**Issue by cartermp** [dotnet/roslyn#43131]
1. `dotnet new console -lang F#`
2. Load into VS after packages restore.
3. Add a few F# file.
4. Delete that file.

**Expected:** File deleted with no issue.

**Actual:** File deleted, but VS encounters a non-fatal error.  Log here:

```
=====================
8/23/2017 10:52:24 AM
Recoverable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: newMkDoc
   at Microsoft.Requires.FailRange(String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass478_0.<<TransferItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass558_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass36_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

I can repro this with a Library and MVC templates as well.

**Comment by jasonmalinowski** [comment]
So I'm unable to get a repro for this. I've tried:

1. Deleting a file from an F# .NET Core project.
2. Deleting a file from a C# .NET Core project that targets a single target.
3. Deleting a file from a C# .NET Core project that targets multiple targets.
4. Deleting a file from a C# shared project that is consumed by a .NET Core project.
5. Deleting a linked file that's linked across projects, including shared projects.

Any other things to try? @tmat doesn't recall what he did when he hit the issue; @lifengl's comment predates the rewrite all of this, and there were absolutely bugs around that time.

Closing as no-repro but if somebody else gets a repro _please_ reactivate.

**Comment by tmat** [comment]
Would adding some invariant validation help?

**Comment by jasonmalinowski** [comment]
@tmat: I'm not sure what I'd check. The invariants would be checking the sanity of project system outputs if I do a bunch of UI calls...

**Comment by jeremy-marcus** [comment]
I know this isn't quite the right place but I'm getting the exact exception at the top but when trying to change project context for shared project files.

**Comment by jasonmalinowski** [comment]
@jeremy-marcus can you file a new bug to track?

**Comment by jeremy-marcus** [comment]
@jasonmalinowski I created #51781
