### ISSUE TITLE
devenv dissappears off my screen constantly with Out Of Memory or Not Enough Storage Space

### ISSUE THREAD

**Issue by JayCroghan** [dotnet/roslyn#43218]
**Version Used**: 16.4.2

**Steps to Reproduce**:

16GB Ram, Windows 7 x64, 1TB hard drive with 800GB free. Dual Core.

1. Open solution in Visual Studio
2. Do literally anything, it happens completely at random, sometimes running code, sometimes just editing code, sometimes when I'm not even at the computer. It's a very large solution. But sometimes it happens once every 15 mins, sometimes twice per day. Almost always the exact same stack trace, the top of the stack is identical but the bottom can change slightly but the error is always one of two, either Out Of Memory or Not Enough Storage Space. The only difference is whether it's devenv.exe or ServiceHub.RoslynCodeAnalysisService32.exe

**Expected Behavior**: Visual Studio stays on my screen.

**Actual Behavior**: Visual Studio (and if debugging all running processed) dissappears. No "Restart?" dialog.

Stack Trace of Out of Memory
```
Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.CodeAnalysis.Text.LargeText.ReadChunksFromTextReader(TextReader reader, Int32 maxCharRemainingGuess, Boolean throwIfBinaryDetected)
   at Microsoft.CodeAnalysis.Text.LargeText.Decode(TextReader reader, Int32 length, Encoding encodingOpt, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.Text.SourceText.From(TextReader reader, Int32 length, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.Host.TextFactoryService.CreateText(TextReader reader, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.ReadText(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Serialization.SerializerService.DeserializeSourceText(ObjectReader reader, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Serialization.SerializerService.Deserialize[T](WellKnownSynchronizationKind kind, ObjectReader reader, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.SnapshotService.JsonRpcAssetSource.ReadAssets(Stream stream, Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.SnapshotService.JsonRpcAssetSource.<>c__DisplayClass2_0.<RequestAssetsAsync>b__1(Stream s, CancellationToken c)
   at Microsoft.CodeAnalysis.Remote.Extensions.<InvokeAsync>d__4`1.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.Report(System.String, System.Exception, System.Func`2<Microsoft.VisualStudio.Telemetry.IFaultUtility,Int32>, Microsoft.CodeAnalysis.ErrorReporting.WatsonSeverity)
   at Microsoft.CodeAnalysis.Remote.RemoteHostService+<>c.<SetGlobalContext>b__15_0(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.Remote.Extensions.ReportUnlessCanceled(System.Exception, System.Threading.CancellationToken, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__4`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.CodeAnalysis.Text.LargeText.ReadChunksFromTextReader(System.IO.TextReader, Int32, Boolean)
   at Microsoft.CodeAnalysis.Text.LargeText.Decode(System.IO.TextReader, Int32, System.Text.Encoding, Microsoft.CodeAnalysis.Text.SourceHashAlgorithm)
   at Microsoft.CodeAnalysis.Text.SourceText.From(System.IO.TextReader, Int32, System.Text.Encoding, Microsoft.CodeAnalysis.Text.SourceHashAlgorithm)
   at Microsoft.CodeAnalysis.Host.TextFactoryService.CreateText(System.IO.TextReader, System.Text.Encoding, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+TemporaryStorageService+TemporaryTextStorage.ReadText(System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Serialization.SerializerService.DeserializeSourceText(Roslyn.Utilities.ObjectReader, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Serialization.SerializerService.Deserialize[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.CodeAnalysis.Serialization.WellKnownSynchronizationKind, Roslyn.Utilities.ObjectReader, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.SnapshotService+JsonRpcAssetSource.ReadAssets(System.IO.Stream, Int32, System.Collections.Generic.ISet`1<Microsoft.CodeAnalysis.Checksum>, Microsoft.CodeAnalysis.Serialization.ISerializerService, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.SnapshotService+JsonRpcAssetSource+<>c__DisplayClass2_0.<RequestAssetsAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.Extensions+<InvokeAsync>d__4`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

```

Stack Trace of Not Enough Storage
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.<>c.<CreateReadableStream>b__14_0(MemoryMappedInfo info)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.RunWithCompactingGCFallback[TArg,T](Func`2 function, TArg argument)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateReadableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.ReadText(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass13_0.<ReadTextAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.<RecoverAsync>d__5.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor.CrashUnlessCanceled(System.AggregateException)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__35`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__35`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<>c__DisplayClass33_1`1+<<RunAnalyzersAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.SolutionSize.SolutionSizeTracker+IncrementalAnalyzer+<AnalyzeSyntaxAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.DocumentState+<GetSyntaxTreeAsync>d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by sharwell** [comment]
Hi @JayCroghan,

The only way for us to review and fix this issue is to follow the steps on the following page to submit a memory heap for analysis:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#crashes

Thanks!

**Comment by JayCroghan** [comment]
Hi @sharwell after following the steps, no dmp files are created, we have reproduced on a number of different machines repeatedly and no dmp files are created, not before and not after we make the registry changes to change the dmps to full. I really don't know what else to do at this point. It's happening on all 5 dev machines.

**Comment by JayCroghan** [comment]
I can ask my colleague attach the log files collected using the log collection tools as some of the crashes are satellite applications, each time it happens it's either RoslynCodeAnalysisService32.exe or devenv.exe there is no difference in what we do and only one event is registered per crash. I can reproduce it by simply opening a handful of files from the solution but it happens completely unattended too. The solution has 454 projects and has a wild variety of types, winforms, console and console services, windows apis and tests for all of the above. We cannot submit the logs via VS as we get a '401 unauthorized' errror when clicking submit with the logs.

**Comment by sharwell** [comment]
@JayCroghan this is super strange. We use these steps for most of our internal and external investigations, so I'm surprised to hear it didn't work for you. Can you check the following to make sure it was correctly configured?

![image](https://user-images.githubusercontent.com/1408396/78966451-cc638e80-7ab4-11ea-95bc-ff608e504341.png)

**Comment by JayCroghan** [comment]
It's not letting me upload the screenshot but yes I tried the command lines in the article and then when that didn't work deleted them and created them manually. But on another machine before applying these changes no dump files are created in the default location either. There are older dumps from times when it crashed for other reasons but 0 dump files in the last week before these changes and with 10+ crashes since these changes also 0 dump files. I even removed the DumpFolder so it would use the default dump location and still no dumps.

**Comment by JayCroghan** [comment]
@sharwell I updated to 16.5.4 and finally got a crash dump. It's 4GB in size but due to limitations within the VDIs we use I cannot login to my Microsoft account in VS. I can login via Chrome or IE just notr VS. How can we go about getting you the dmp file if I cannot use Report a Problem? I get the error AADSTS900144 The request body must contain the following parameter: 'state'

**Comment by JayCroghan** [comment]
@sharwell the issue that you linked on Dev Community from the issue below was created by my colleague my instruction. It is this issue, same solution and symptoms so you can close this.

https://github.com/dotnet/roslyn/issues/43802

**Comment by sharwell** [comment]
@JayCroghan Thanks for the update!

**Comment by sharwell** [comment]
Duplicate of #43802
