### ISSUE TITLE
F2 Rename Stopped working version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43260]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/981226/f2-rename-stopped-working-version.html)._

---
[regression] [worked-in:before 16.5.3]
I got Visual Studio yesterday. New version today so I updated. 16.5.3
F2 just does nothing. Context Menu Rename does nothing.

Not sure if this is related, but it happened the first time I tried use F2 in the new version.

```
System.InvalidOperationException: Unexpected false
at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
at Microsoft.VisualStudio.LanguageServices.Implementation.InlineRename.VisualStudioInlineRenameUndoManagerServiceFactory.InlineRenameUndoManager.CreateStartRenameUndoTransaction(Workspace workspace, ITextBuffer subjectBuffer, InlineRenameSession inlineRenameSession)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.. ctor(InlineRenameSession session, ITextBuffer subjectBuffer, Workspace workspace, ITextBufferFactoryService textBufferFactoryService)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.TryPopulateOpenTextBufferManagerForBuffer(ITextBuffer buffer)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.InitializeOpenBuffers(SnapshotSpan triggerSpan)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.. ctor(IThreadingContext threadingContext, InlineRenameService renameService, Workspace workspace, SnapshotSpan triggerSpan, IInlineRenameInfo renameInfo, IWaitIndicator waitIndicator, ITextBufferAssociatedViewService textBufferAssociatedViewService, ITextBufferFactoryService textBufferFactoryService, IFeatureServiceFactory featureServiceFactory, IEnumerable`1 refactorNotifyServices, IAsynchronousOperationListener asyncListener)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService.StartInlineSession(Document document, TextSpan textSpan, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteRenameWorker(RenameCommandArgs args, CommandExecutionContext context)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(RenameCommandArgs args, CommandExecutionContext context)
at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass13_1`1. <Execute>b__1()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 4/7/2020, 08:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@ryzngard there are a couple feedback tickets linked as duplicates of the one above.

**Comment by ryzngard** [comment]
```csharp
            public void CreateStartRenameUndoTransaction(Workspace workspace, ITextBuffer subjectBuffer, InlineRenameSession inlineRenameSession)
            {
                var startRenameUndoPrimitive = new RenameUndoPrimitive(EditorFeaturesResources.Start_Rename);
                var textUndoHistoryService = workspace.Services.GetService<ITextUndoHistoryWorkspaceService>();
                Contract.ThrowIfFalse(textUndoHistoryService.TryGetTextUndoHistory(workspace, subjectBuffer, out var undoHistory));
                Contract.ThrowIfFalse(undoHistory.Properties.TryGetProperty(typeof(ITextBuffer), out ITextBuffer primaryBuffer));
                var undoManager = GetUndoManager(primaryBuffer);
 
                UndoManagers[subjectBuffer] = new BufferUndoState() { UndoManager = undoManager, TextUndoHistory = undoHistory, StartRenameSessionUndoPrimitive = startRenameUndoPrimitive, UndoHistoryBuffer = primaryBuffer };
                undoManager.Add(startRenameUndoPrimitive);
            }
```

@jasonmalinowski  are there valid times when one of these two would fail?

```csharp
 Contract.ThrowIfFalse(textUndoHistoryService.TryGetTextUndoHistory(workspace, subjectBuffer, out var undoHistory));
 Contract.ThrowIfFalse(undoHistory.Properties.TryGetProperty(typeof(ITextBuffer), out ITextBuffer primaryBuffer));
```

**Comment by jasonmalinowski** [comment]
I can't think of any normal scenario where they might. I think the editor used to have a "stress mode" which internally would disable undo entirely, but that was something we couldn't support for inline rename since we rely on undo behavior. But that was an internal flag used for specific testing and not something customers should be reporting.

@olegtk any other ideas?

**Comment by olegtk** [comment]
No idea honestly. Looking at ticket diagnostics I see a lot of MEF errors, including some that look somewhat critical. So I'd suggest repairing VS first.

**Comment by sharwell** [comment]
@ryzngard Reopening this. There are now three separate reports of this:

- AB#1094626 (the original report)
- AB#1051620
- AB#1230608 (came today)

**Comment by ryzngard** [comment]
[AB#1290451](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1290451) as well

**Comment by ryzngard** [comment]
AB#1159768 looks related

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/issues/55411 seems related?

**Comment by eitama** [comment]
I'm having the same issue.

1. Start visual studio, open my .cs file, rebuild it just to see it compiles.
2. Try to F2 on a variable, it won't work, in addition, a banner on top reports the crash and offers the xml log file.
3. From that moment, F2 will not work, autocomplete won't work. If you try F2 again, there will also be no more errors. It just won't work.
4. Restart VS if you want to see the error again when pressing F2.

VS Version: Version 17.0.1

**Comment by CyrusNajmabadi** [comment]
Closing out as we havne't gotten reports of this in several years.
