### ISSUE TITLE
Clicking on empty line causes InvalidOperationException in InlineTemporaryCodeRefactoringProvider

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#43666]
Version: 16.7.0 Preview 1.0 [30024.6.master]

Repro steps:
1. Click on the empty line 144 in [AbstractIntroduceVariableService.cs](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/IntroduceVariable/AbstractIntroduceVariableService.cs,144) (following the call to ```CreateConstantFieldActions``` in the block context branch of the if-statement).
2. Gold bar appears with message that InlineTemporaryCodeRefactoringProvider encountered an error and has been disabled.

Stack trace:
``` C#
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.CSharp.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.GetReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by sharwell** [comment]
I expect we'll be seeing a fair number of reports for this. I've hit it 4 times now since I updated to 16.7 Preview 1 yesterday.
