### ISSUE TITLE
Exception GetSemanticModelAsync().Result : One or more errors occurred. (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by abhijitparkhi1983** [dotnet/roslyn#43679]
**Version Used**: 
3.5.0

**Steps to Reproduce**:

1. Use MSBuildLocator.QueryVisualStudioInstances() for getting the MsBuild Instance 
2. Using below code Open .csproj, run through all the documents :

```
using (var workspace = MSBuildWorkspace.Create())
{
     Project currentProject = workspace.OpenProjectAsync(projectPath).Result;
     workspace.LoadMetadataForReferencedProjects = true;
     foreach (var document in currentProject .Documents)
     {
          SyntaxNode decendendNodes = document.GetSyntaxRootAsync().Result;
          SemanticModel sementicModel = document.GetSemanticModelAsync().Result;
          ............................
          ..............................
     }
}
```

3. In the above code, we get exception at line **document.GetSemanticModelAsync().Result** for only few .cs documents.
4. NOTE: There isnt any **workspace.Diagnostics** issues before we get the exception.

**Expected Behavior**:
The SemanticModel should be loaded sucessfully.

**Actual Behavior**:

**Outer Exception**

```
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
One or more errors occurred. (Object reference not set to an instance of an object.)  
```

With some trace to **System.Private.CoreLib**

**Inner Exception**

```
at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.BindImports(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.EnsureImportsAreBound(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.get_MemberImports()
   at Microsoft.CodeAnalysis.VisualBasic.BinderBuilder.CreateBinderForSourceFile(SourceModuleSymbol moduleSymbol, SyntaxTree tree)
   at Microsoft.CodeAnalysis.VisualBasic.BinderBuilder.CreateBinderForNamespace(SourceModuleSymbol moduleSymbol, SyntaxTree tree, NamespaceSymbol nsSymbol)
   at Microsoft.CodeAnalysis.VisualBasic.BinderBuilder.CreateBinderForProjectLevelNamespace(SourceModuleSymbol moduleSymbol, SyntaxTree tree)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.GetAttributeBinder(SyntaxList`1 syntaxList, SourceModuleSymbol sourceModule)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.GetAttributesToBind(OneOrMany`1 attributeDeclarationSyntaxLists, AttributeLocation symbolPart, VisualBasicCompilation compilation, ImmutableArray`1& binders)
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.LoadAndValidateAttributes(OneOrMany`1 attributeBlockSyntaxList, CustomAttributesBag`1& lazyCustomAttributesBag, AttributeLocation symbolPart)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.get_IsDelaySigned()
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.get_IsDelaySigned()
   at Microsoft.CodeAnalysis.Compilation.get_HasStrongName()
   at Microsoft.CodeAnalysis.Compilation.ConstructModuleSerializationProperties(EmitOptions emitOptions, String targetRuntimeVersion, Guid moduleVersionId)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, ImmutableArray`1 additionalTypes, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.CheckOptionsAndCreateModuleBuilder(DiagnosticBag diagnostics, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyImage.Create(Workspace workspace, ITemporaryStorageService service, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(SolutionState solution, ProjectReference projectReference, Compilation finalCompilation, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataOnlyImageReferenceAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Document.<GetSemanticModelAsync>d__23.MoveNext()
```

some trace to **Microsoft.CodeAnalysis.VisualBasic**

**Comment by CyrusNajmabadi** [comment]
looks like a compiler crash with those files.  Can you supply a small repro so we can investigate?

**Comment by abhijitparkhi1983** [comment]
@CyrusNajmabadi 

I have the exact same code which I have mentioned in my question. I was trying to reproduce the issues on one of the open source repositories. I could reproduce the same on multiple .cs files under the Roslyn source code itself. 

I can reproduce the issue for example if the input file is **\roslyn-master\src\Compilers\Extension\CompilerPackage.cs** which is located under project **\roslyn-master\src\Compilers\Extension\Roslyn.Compilers.Extension.csproj**

Few more inputs:
HResult value : -2146233088
Source for outer exception: System.Private.CoreLib
Source for inner exception: Microsoft.CodeAnalysis.VisualBasic

Please let me know if you need any further information.

**Comment by CyrusNajmabadi** [comment]
Hrmm. I don't repro this. Can you make a small sell contained repro and upload it to GitHub?  Thanks!

**Comment by Eliador** [comment]
Hello, I have the same issue.
Here is a [link to the example](https://github.com/Eliador/GitHubIssuesReproducing/tree/master/Issue%2343679/LoadSolutionIssue) for this issue on github repo.
