### ISSUE TITLE
InvalidOperationException: The operation failed as details for project Xyz could not be loaded

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43854]
**Version Used**: 

Version 16.7.0 Preview 1.0 [30021.13.master]

While inspecting ServiceHub logs I found a bunch of errors like following. These are not crashing VS but are logged (and likely with NFW reported).
It'd be good to guard against NuGet failures like so without reporting them and follow up with NuGet to get the root cause fixed.

```
04/30/2020 16:08:03 Pacific Standard Time: Error : 1 :[devenv:46312] Unexpected exception: System.InvalidOperationException: The operation failed as details for project RoslynDeployment could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAndAdditionalMessagesAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.<GetPackageSpecsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass8_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)
```

**Comment by tmat** [comment]
@CyrusNajmabadi FYI
