### ISSUE TITLE
ArgumentOutOfRangeException thrown in InteractiveWindow_InProc.GetLastReplOutput

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#43967]
```
System.ArgumentOutOfRangeException : StartIndex cannot be less than zero.
Parameter name: startIndex
Server stack trace: 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.GetLastReplOutput()
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 getValue, Func`2 isExpectedValue)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutputContains(String outputText)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForLastReplOutputContains(String outputText)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.WaitForLastReplOutputContains(String outputText) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/InteractiveWindow_OutOfProc.cs:line 76
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.ForStatement() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractive.cs:line 40
```

There are a couple of other open issues for this test, but the failures there do not appear to be related to this stack. Failed in https://github.com/dotnet/roslyn/pull/43962.
https://dev.azure.com/dnceng/public/_build/results?buildId=630588&view=ms.vss-test-web.build-test-results-tab&runId=19673644&resultId=100468&paneView=debug

**Comment by 333fred** [comment]
I've seen this stack in a few places: VerifySquiggleAndErrorMessageUnderIncorrectDirective ([Run](https://dev.azure.com/dnceng/public/_build/results?buildId=635111&view=ms.vss-test-web.build-test-results-tab&runId=19771230&resultId=100496&paneView=debug)), VerifyHashReset ([Run](https://dev.azure.com/dnceng/public/_build/results?buildId=653945&view=ms.vss-test-web.build-test-results-tab&runId=20301880&resultId=100502&paneView=debug)), TopLevelMethod ([Run](https://dev.azure.com/dnceng/public/_build/results?buildId=648490&view=ms.vss-test-web.build-test-results-tab&runId=20130082&resultId=100465&paneView=debug)), and ForStatement ([Run](https://dev.azure.com/dnceng/public/_build/results?buildId=649788&view=ms.vss-test-web.build-test-results-tab&runId=20174694&resultId=100468&paneView=debug)). All told, this accounts for 6 failed runs in the past 14 days: https://dev.azure.com/dnceng/public/_test/analytics?definitionId=245&contextType=build, our second-highest flaky failure.
