### ISSUE TITLE
System.ArgumentNullException in SyntaxNodeExtensions.RemoveNode

### ISSUE THREAD

**Issue by default0** [dotnet/roslyn#4412]
The following Code causes an exception:

```
void M()
        {
            CompilationUnitSyntax compilationUnitSyntax = SyntaxFactory.ParseCompilationUnit(
@"namespace A
{
    public class B
    {
        public void M()
        {
            M();
        }
    }
}"
            );
            NamespaceDeclarationSyntax namespaceDecl = (NamespaceDeclarationSyntax)compilationUnitSyntax.Members[0];
            ClassDeclarationSyntax classDecl = (ClassDeclarationSyntax)namespaceDecl.Members[0];
            MethodDeclarationSyntax methodDecl = (MethodDeclarationSyntax)classDecl.Members[0];
            methodDecl.RemoveNode(((ExpressionStatementSyntax)methodDecl.Body.Statements[0]).Expression, SyntaxRemoveOptions.KeepNoTrivia);
```

My assumption is that an AST with an ExpressionStatementSyntax that has no ExpressionSyntax is invalid, and thus an error occurs. The error message could be a lot more descriptive about that, though...

Exception:
```
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ExpressionStatement(ExpressionSyntax expression, SyntaxToken semicolonToken)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Update(ExpressionSyntax expression, SyntaxToken semicolonToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.RemoveNodes[TRoot](TRoot root, IEnumerable`1 nodes, SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.RemoveNodesCore(IEnumerable`1 nodes, SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode[TRoot](TRoot root, SyntaxNode node, SyntaxRemoveOptions options)
   at RoslynBugTest.Program.Main() in c:\Users\cs\Documents\Visual Studio 2013\Projects\RoslynBugTest\RoslynBugTest\Program.cs:Zeile 31.
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by vamuzumd** [comment]
I am facing the same issue when trying to remove 'Message' IdentifierNode from the ex?.GetBaseException.Message expression.

The stack trace is as follows:-

'parent.RemoveNode(messageNode, SyntaxRemoveOptions.KeepExteriorTrivia)' threw an exception of type 'System.ArgumentNullException'

at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MemberAccessExpression(SyntaxKind kind, ExpressionSyntax expression, SyntaxToken operatorToken, SimpleNameSyntax name)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax.Update(ExpressionSyntax expression, SyntaxToken operatorToken, SimpleNameSyntax name)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMemberAccessExpression(MemberAccessExpressionSyntax node)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)\r\n   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.RemoveNodes[TRoot](TRoot root, IEnumerable`1 nodes, SyntaxRemoveOptions options)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.RemoveNodesCore(IEnumerable`1 nodes, SyntaxRemoveOptions options)\r\n   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode[TRoot](TRoot root, SyntaxNode node, SyntaxRemoveOptions options)"

Any ETA on when this issue would be fixed?

**Comment by CyrusNajmabadi** [comment]
> Any ETA on when this issue would be fixed?

There is nothing to "fix" here, outside of throwing a more clear exception.  What you are trying to do is illegal.  A member-access-expression (i.e. `expr.b`) is required to have a non-null left and non-null right.  You cannot remove either side without causing an invariant exception (which manifests here as an argumentnullexception).

If you want to convert the above to `ex?.GetbaseException.`, then right thing to do is to not RemoveNode on 'Message', but instead do a ReplaceNode of `Message` with an empty IdentifierSyntax.

You can get a sense for what tree you need to convert the 'before' into by using a quoter tool like https://roslynquoter.azurewebsites.net/ .  This will show you what the expected tree form is for something like `ex?.GetbaseException.`.  You will have to generate that form, otherwise the behavior of all further parts of the system is undefined.

**Comment by CyrusNajmabadi** [comment]
@windhandel We'd welcome a PR that helped with that.  Thanks!
