### ISSUE TITLE
Cannot load project Metadata references since upgrading from visual studio 16.4.6 to 16.5

### ISSUE THREAD

**Issue by KarimGhallab** [dotnet/roslyn#44140]
**3.5.0 (https://www.nuget.org/packages/Microsoft.CodeAnalysis)**: 

Hi guys, I'am building a project that performs code analyzis on another C# project.
To do so, I give to my analyzer a path to a ".csproj" file.

Everything worked great before I upgrade from version 16.4.6 of visual studio to 16.5.*

The problem is that now a cannot get the metadata references of the project I try to analyze

This is the code that load the project : 
`var msWorkspace = MSBuildWorkspace.Create();`
`var project = msWorkspace.OpenProjectAsync(projectFilePath).Result;`

After that, when I read `project.MetadataReferences`, it is empty.

Here are the diagnostics messages I get from the msWorkspace after trying to read the project.
`[Échec] MSBuild a échoué pendant le traitement du fichier 'C:\Users\Coach\Documents\Mobioos-Seeds-Sower\analyzer\ExampleHelloWorld\ExampleHelloWorld.csproj' avec le message : C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets: (59, 5): Échec inattendu de la tâche "ProcessFrameworkReferences".
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Le fichier spécifié est introuvable.
File name: 'NuGet.Frameworks, Version=5.5.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)`

I'am fairly new to the .NET environment so I may have misunderstood some points

Thanks in advance.

**Comment by KarimGhallab** [comment]
Fixed by adding `<PackageReference Include="NuGet.ProjectModel" Version="5.5.1" />` to my analyzer.
