### ISSUE TITLE
'ChangeSignatureCodeRefactoringProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#44198]
```
System.InvalidOperationException : WaitAndGetResult cannot be called from a thread pool thread.
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken,Solution& updatedSolution)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by AlekseyTs** [comment]
CC @dpoeschl

**Comment by boomalator** [comment]
I dunno. Doesn't seem too "fixed" to me.
I still get this:
![image](https://user-images.githubusercontent.com/17992669/208830120-4478e24d-2b91-4392-ba7d-4b5aff5c3ba7.png)

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.4.2

**Comment by CyrusNajmabadi** [comment]
What stack trace is in that message?

**Comment by daytonarob** [comment]
> What stack trace is in that message?
I am getting this as well, Version 17.4.4 here is the stack trace:
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetParameterIndexFromInvocationArgument(SyntaxNode argument,Document document,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.ChangeSignature.CSharpChangeSignatureService.GetInvocationSymbolAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

**Comment by CyrusNajmabadi** [comment]
This was fixed with https://github.com/dotnet/roslyn/pull/65307.  Which is in:

![image](https://user-images.githubusercontent.com/4564579/217061591-559fb965-0b2a-4c05-9aa0-8f9fb5f668f7.png)

If you are experiencing this problem in that version, let us know.
