### ISSUE TITLE
TypeLoadException when f5ing latest roslyn

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44279]
**Version Used**: Roslyn commit ee6aae8, Visual Studio 16.6 Preview 6
This commit is from merging master into a feature branch, but the feature branch content shouldn't be affecting this.

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Debug RoslynDeployment
3. Open a project in the child VS instance

**Expected Behavior**:
project opens successfully

**Actual Behavior**:
TypeLoadException: `Method 'get_IsRemoteHost64Bit' in type 'Roslyn.Test.Utilities.Remote.InProcRemoteHostClient' from assembly 'Roslyn.Services.Test.Utilities, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.`

Stack:
```
   at Roslyn.VisualStudio.DiagnosticsWindow.Remote.RemoteHostClientFactory.CreateAsync(Workspace workspace, CancellationToken cancellationToken) in C:\Users\rikki\src\roslyn\src\VisualStudio\RemoteHostClientMock\Remote\RemoteHostClientFactory.cs:line 31
   at Microsoft.VisualStudio.LanguageServices.Remote.RemoteHostClientServiceFactory.RemoteHostClientService.<EnableAsync>d__18.MoveNext() in C:\Users\rikki\src\roslyn\src\VisualStudio\Core\Def\Implementation\Remote\RemoteHostClientServiceFactory.RemoteHostClientService.cs:line 202
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.LanguageServices.Remote.SolutionChecksumUpdater.<SynchronizePrimaryWorkspaceAsync>d__15.MoveNext() in C:\Users\rikki\src\roslyn\src\VisualStudio\Core\Def\Implementation\Remote\SolutionChecksumUpdater.cs:line 126
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.LanguageServices.Remote.SolutionChecksumUpdater.<ExecuteAsync>d__9.MoveNext() in C:\Users\rikki\src\roslyn\src\VisualStudio\Core\Def\Implementation\Remote\SolutionChecksumUpdater.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor.<ProcessAsync>d__12.MoveNext() in C:\Users\rikki\src\roslyn\src\Features\Core\Portable\SolutionCrawler\IdleProcessor.cs:line 102
```

Tagging @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
This is the diagnostics window mis-sycning, so it means something probably didn't redeploy right. Do an explicit `msbuild /t:Rebuild /m /v:m Roslyn.sln` and see if that fixes it.

**Comment by RikkiGibson** [comment]
How odd, these two commands did not resolve the issue:
- `.\Build.cmd -rebuild`
- `git clean -xdf; .\Build.cmd -restore`

But this one (that you provided) did: `msbuild /t:Rebuild /m /v:m Roslyn.sln`.

I guess I won't worry too much about why--just good to know the root cause and what to do about the issue. Thanks @jasonmalinowski!
