### ISSUE TITLE
CSharpSpellCheckCodeFixProvider encoutered and error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44299]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/11140/csharpspellcheckcodefixprovider-encoutered-and-err.html)._

---
Appeared in yellow top bar while editing source code in editor.

System.ArgumentOutOfRangeException : Position is not within syntax tree with full span [6642..6900)
Parameter name: position
Actual value was 9737.
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32 position,SyntaxToken&amp; token)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbolsInternal(Int32 position,NamespaceOrTypeSymbol container,String name,LookupOptions options,Boolean useBaseReferenceAccessibility)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupNamespacesAndTypesCore(Int32 position,INamespaceOrTypeSymbol container,String name)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForTypeOrNamespaceContext(CSharpSyntaxContext context)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForCurrentContext(CSharpSyntaxContext context,Boolean filterOutOfScopeLocals,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsWorker(CSharpSyntaxContext context,Boolean filterOutOfScopeLocals,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetRecommendedSymbolsAtPositionWorkerAsync(Workspace workspace,SemanticModel semanticModel,Int32 position,OptionSet options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPositionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Recommendations.Recommender.GetImmutableRecommendedSymbolsAtPositionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetPerContextSymbols(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Matthew Snider [MSFT] on 5/3/2017, 02:21 PM: 

<p>I am also hitting this, VS 2017 RTM. </p>

#### Roy Foreman on 7/14/2017, 03:36 AM: 

<p>Also seeing this in VS 2015 since installing VS 2017.  My circumstances are in c# code editor, type override and as it brings up the intellisense the error above appears.  Then when I select a method to override VS 2015 crashes with an Index out of bounds error in Roslyn (at Microsoft.CodeAnalysis.SymbolId.Parser.GetNthTypeParameter() method)</p>

#### Toby Herring on 5/18/2018, 06:59 AM: 

<p>Still going.  VS2017 Enterprise:</p><p>System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.GetSeparator(Int32 index)</p><p>
   at async Roslynator.CSharp.CodeFixes.SyntaxErrorCharExpectedCodeFixProvider.RegisterCodeFixesAsync(&lt;Unknown Parameters&gt;)</p><p>
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;)</p>

#### Scott Manktelow on 7/6/2018, 08:33 AM: 

<p>I'm getting this too, started happening today. No idea why. Happens when I type override and try to use intellisense to select a method as well.  My stack trace is different.  My version is 2017 Professional 15.2 (26430.12) Release</p><p>System.InvalidOperationException : Sequence contains no elements at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray) at async Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.GenerateMemberAndUsingsAsync(&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.DetermineNewDocumentAsync(&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.GetChangeAsync(&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetChangeAsync(&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.GetInsertionTextAsync[TSimpleName](&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](&lt;Unknown Parameters&gt;) at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(&lt;Unknown Parameters&gt;) at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</p>

#### Jinu Joseph [MSFT] on 7/15/2018, 01:52 AM: 

<p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

#### Blair Wang [MSFT] on 8/2/2019, 09:20 AM: 

After 90 days of no priority changing activity, we’ve closed this report. We prioritize based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Closing low priority tickets helps us manage our workload and focus on problems that impact most users. If you still face this issue in our latest version, please report it as a new problem.

#### Peter Shaw on 5/15/2020, 07:42 AM: 

<p>Been plaguing me for months in VS2019 now, and I've finally gotten fed up of it killing my IntelliSense!!</p>

---
### Original Solutions
(no solutions)

**Comment by KirillOsenkov** [comment]
Seeing this as well:

```
System.ArgumentOutOfRangeException: Position is not within syntax tree with full span [14869..18324)
Parameter name: position
Actual value was 32737.
   at int Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(int position, out SyntaxToken token) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:line 1300
   at ISymbol Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbol(int position, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:line 4828
   at ISymbol Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbolCore(int position, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:line 5248
   at bool Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions.IsInstanceContext(SyntaxTree syntaxTree, SyntaxToken targetToken, SemanticModel semanticModel, CancellationToken cancellationToken) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs:line 2010
   at CSharpSyntaxContext Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker(Workspace workspace, SemanticModel semanticModel, int position, CancellationToken cancellationToken) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/CSharpSyntaxContext.cs:line 217
   at Task<CSharpSyntaxContext> Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.CreateContextAsync(Workspace workspace, SemanticModel semanticModel, int position, CancellationToken cancellationToken) in /_/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs:line 26
   at async Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService<TSyntaxContext>.GetRecommendedSymbolsAtPositionAsync(Workspace workspace, SemanticModel semanticModel, int position, OptionSet options, CancellationToken cancellationToken)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService<TSyntaxContext>.GetRecommendedSymbolsAtPositionAsync(Workspace workspace, SemanticModel semanticModel, int position, OptionSet options, CancellationToken cancellationToken)
   at async Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.Recommendations.Recommender.GetImmutableRecommendedSymbolsAtPositionAsync(SemanticModel semanticModel, int position, Workspace workspace, OptionSet options, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Recommendations/Recommender.cs:line 50
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.Recommendations.Recommender.GetImmutableRecommendedSymbolsAtPositionAsync(SemanticModel semanticModel, int position, Workspace workspace, OptionSet options, CancellationToken cancellationToken)
   at Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.CSharp.Completion.Providers.SymbolCompletionProvider.GetSymbolsAsync(SyntaxContext context, int position, OptionSet options, CancellationToken cancellationToken) in /_/src/Features/CSharp/Portable/Completion/CompletionProviders/SymbolCompletionProvider.cs:line 38
   at Task<ImmutableArray<ISymbol>> Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetSymbolsAsync(int position, bool preselect, SyntaxContext context, OptionSet options, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:line 362
   at async Task<IEnumerable<CompletionItem>> Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(CompletionContext completionContext, SyntaxContext syntaxContext, Document document, int position, Lazy<ImmutableArray<ITypeSymbol>> inferredTypes, OptionSet options, bool preselect, TelemetryCounter telemetryCounter, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:line 317
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<IEnumerable<CompletionItem>> Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(CompletionContext completionContext, SyntaxContext syntaxContext, Document document, int position, Lazy<ImmutableArray<ITypeSymbol>> inferredTypes, OptionSet options, bool preselect, TelemetryCounter telemetryCounter, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext completionContext) in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:line 276
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext completionContext)
   at async Task<CompletionContext> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, int position, CompletionTrigger triggerInfo, OptionSet options, TextSpan? defaultSpan, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 544
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<CompletionContext> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, int position, CompletionTrigger triggerInfo, OptionSet options, TextSpan? defaultSpan, CancellationToken cancellationToken)
   at async Task<ValueTuple<ImmutableArray<CompletionContext>, bool>> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(Document document, int caretPosition, CompletionTrigger trigger, OptionSet options, TextSpan defaultItemSpan, ImmutableArray<CompletionProvider> providers, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 414
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<ValueTuple<ImmutableArray<CompletionContext>, bool>> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.ComputeNonEmptyCompletionContextsAsync(Document document, int caretPosition, CompletionTrigger trigger, OptionSet options, TextSpan defaultItemSpan, ImmutableArray<CompletionProvider> providers, CancellationToken cancellationToken)
   at async Task<(CompletionList completionList, bool expandItemsAvailable)> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(Document document, int caretPosition, CompletionTrigger trigger, ImmutableHashSet<string> roles, OptionSet options, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 312
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<(CompletionList completionList, bool expandItemsAvailable)> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(Document document, int caretPosition, CompletionTrigger trigger, ImmutableHashSet<string> roles, OptionSet options, CancellationToken cancellationToken)
   at async Task<CompletionList> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, int caretPosition, CompletionTrigger trigger, ImmutableHashSet<string> roles, OptionSet options, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs:line 254
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<CompletionList> Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, int caretPosition, CompletionTrigger trigger, ImmutableHashSet<string> roles, OptionSet options, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.CreateSpellCheckCodeIssueAsync(CodeFixContext context, SyntaxToken nameToken, bool isGeneric, CancellationToken cancellationToken)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.CreateSpellCheckCodeIssueAsync(CodeFixContext context, SyntaxToken nameToken, bool isGeneric, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.CheckNodeAsync(CodeFixContext context, Document document, SyntaxNode node, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/SpellCheck/AbstractSpellCheckCodeFixProvider.cs:line 80
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.CheckNodeAsync(CodeFixContext context, Document document, SyntaxNode node, CancellationToken cancellationToken)
   at async Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.RegisterCodeFixesAsync(CodeFixContext context)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider<TSimpleName>.RegisterCodeFixesAsync(CodeFixContext context)
   at Task<bool> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync(Document document, DiagnosticData diagnostic, CancellationToken cancellationToken)+() => { } in /_/src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs:line 745
   at async Task Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(IExtensionManager extensionManager, object extension, Func<Task> function) in /_/src/Workspaces/Core/Portable/ExtensionManager/IExtensionManagerExtensions.cs:line 73
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(IExtensionManager extensionManager, object extension, Func<Task> function)
   at async Task<bool> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync(Document document, DiagnosticData diagnostic, CancellationToken cancellationToken) in /_/src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs:line 745
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<bool> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync(Document document, DiagnosticData diagnostic, CancellationToken cancellationToken)
   at async Task<DiagnosticData> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetFirstDiagnosticWithFixAsync(Document document, IEnumerable<DiagnosticData> severityGroup, TextSpan range, CancellationToken cancellationToken)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<DiagnosticData> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetFirstDiagnosticWithFixAsync(Document document, IEnumerable<DiagnosticData> severityGroup, TextSpan range, CancellationToken cancellationToken)
   at Task<FirstDiagnosticResult> Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetMostSevereFixableDiagnosticAsync(Document document, TextSpan range, CancellationToken cancellationToken)+() => { } in /_/src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs:line 114
```

**Comment by KirillOsenkov** [comment]
This also happened to me when typing out this code and hovering over the error squiggle:

```
using System.Collections.Generic;

class C
{
    Dictionary<string, string> d;

    public bool P { get; set; } d.Keys;

    public C()
    {
        d = 
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  Closing out.
