### ISSUE TITLE
Not enough quota when opening Window

### ISSUE THREAD

**Issue by NickeManarin** [dotnet/roslyn#44332]
After updating my WPF app from 4.6.1 to 4.8, users started getting this exception (multiple times in a row) when opening windows:

```
• Message - 
    Not enough quota is available to process this command
• Type - 
    System.ComponentModel.Win32Exception
• Source - 
    PresentationCore
• TargetSite - 
    Void UpdateWindowSettings(Boolean, System.Nullable`1[System.Windows.Media.Composition.DUCE+ChannelSet])
• StackTrace - 
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Unfortunately, I could not get this exception on my machine, so I can't really understand what's happening.

I already tried setting `HandleDispatcherRequestProcessingFailureOptions.Reset`, but people are still reporting crashes to me.

What could possibly be happening? Is there any way to fix this or maybe set an workaround?

**Comment by NickeManarin** [comment]
Does anybody have an input on this issue?

**Comment by CyrusNajmabadi** [comment]
This does not appear to be a Roslyn issue.  Sorry @NickeManarin .  Maybe try: https://github.com/dotnet/wpf ?
