### ISSUE TITLE
Several scripting error tests are invalidated due to the fact that top-level statements are now supported in regular code.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#44418]
```
Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_02 [FAIL]
  Assert.Null() Failure
  Expected: (null)
  Actual:   System.Console.WriteLine(int)
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\ScriptSemanticsTests.cs(1276,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_02()
Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_03 [FAIL]
  Assert.Null() Failure
  Expected: (null)
  Actual:   x
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\ScriptSemanticsTests.cs(1311,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_03()
Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_01 [FAIL]
  Assert.Null() Failure
  Expected: (null)
  Actual:   System.Console.WriteLine(int)
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\ScriptSemanticsTests.cs(1184,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.ScriptSemanticsTests.Errors_01()
```

**Comment by AlekseyTs** [comment]
The tests are temporarily disabled.
