### ISSUE TITLE
IDE crashes when using relational pattern on bool constant

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#44518]
**Version Used**: 16.7P1, master (69b3bf5)

**Steps to Reproduce**:

```c#
class C
{
    void M()
    {
        _ = is < true;
    }
}
```

**Expected Behavior**: Compiler errors.

**Actual Behavior**: The IDE crashes.

```
System.ArgumentException: relation
   at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.BoolValueSetFactory.Related(BinaryOperatorKind relation, Boolean value)
   at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.BoolValueSetFactory.Microsoft.CodeAnalysis.CSharp.IValueSetFactory.Related(BinaryOperatorKind relation, ConstantValue value)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.<SplitValues>g__resultForRelation|34_0(BinaryOperatorKind relation, ConstantValue value, <>c__DisplayClass34_0& )
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitValues(ImmutableDictionary`2 values, BoundDagTest test)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitCases(ImmutableArray`1 statesForCases, ImmutableDictionary`2 values, BoundDagTest test, ImmutableArray`1& whenTrue, ImmutableArray`1& whenFalse, ImmutableDictionary`2& whenTrueValues, ImmutableDictionary`2& whenFalseValues, Boolean& foundExplicitNullTest)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeDecisionDag(ImmutableArray`1 casesForRootNode)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeBoundDecisionDag(SyntaxNode syntax, ImmutableArray`1 cases)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CreateDecisionDagForIsPattern(SyntaxNode syntax, BoundExpression inputExpression, BoundPattern pattern, LabelSymbol whenTrueLabel)
   at Microsoft.CodeAnalysis.CSharp.Binder.MakeIsPatternExpression(SyntaxNode node, BoundExpression expression, BoundPattern pattern, TypeSymbol boolType, Boolean hasErrors, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindIsPatternExpression(IsPatternExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GenerateCompilationEvents(AnalysisScope analysisScope, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__55.MoveNext()

```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44441

**Comment by jhinder** [comment]
I tried it with today's master, where that change should be included, and it still causes an exception.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/pull/44441 went into `dotnet:release/dev16.7-preview2`.  Were you able to try that?

**Comment by alrz** [comment]
Looks like the stacktrace is different from what #44441 fixes

**Comment by jhinder** [comment]
The exception still occurs on `release/dev16.7-preview2`.

**Comment by CyrusNajmabadi** [comment]
Thanks.  Tagging @gafter .
