### ISSUE TITLE
Gold bar from InlineTemporaryCodeRefactoringProvider

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#44519]
**Version Used**: VS 16.7 P1

**Steps to Reproduce**:

1. Find a place with a type check of the form
```c#
var x = obj as T;
if (x != null) { /*something*/ }
```
2. Place the cursor in front of 'var' and bring up the quick actions.

Note: this does not always happen, but I've had it occur several times when browsing code in Roslyn.sln.

**Expected Behavior**: "Inline temporary variable" is offered.

**Actual Behavior**: A gold bar appears: "InlineTemporaryCodeRefactoringProvider encountered an error and has been disabled."

```
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.CSharp.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.GetReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by allisonchou** [comment]
This looks like the same issue as #43666. I'm also not able to get the problem to consistently repro, which has made it hard to determine the source of the issue, but added a check in #43959 to prevent the crash from happening again.
