### ISSUE TITLE
ArgumentException in VisualBasicChangeSignatureService.GetPositionBeforeParameterListClosingBrace

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44603]
**Version Used**: Latest 16.7 dogfooding build

**Steps to Reproduce**:

Say the following exception/gold bar while typing:

```
System.ArgumentException : Unexpected SyntaxNode
Parameter name: matchingNode
   at Microsoft.CodeAnalysis.VisualBasic.ChangeSignature.VisualBasicChangeSignatureService.GetPositionBeforeParameterListClosingBrace(SyntaxNode matchingNode)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mavasani** [comment]
@dpoeschl Known?
