### ISSUE TITLE
Introduce variable crashes with certain target-typed new expressions

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#44656]
**Version Used**: 30128.12.master

**Steps to Reproduce**:

1. In the following code, right-click on ```new(1)``` in class ```D``` (should have a red underline):
``` C#
class A
{
    public void Create(B b, D d)
    {

    }
}

class B
{

}

class D
{
    void M()
    {
        new A().Create(new B(), new(1));
    }
}
```

Introduce variable crashes with the following stack trace:
```
System.ArgumentNullException : Value cannot be null.
Parameter name: destination
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.ClassifyConversion(Int32 position,ExpressionSyntax expression,ITypeSymbol destination,Boolean isExplicitInSource)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.CastMustBePreserved(ExpressionSyntax castNode,ExpressionSyntax castedExpressionNode,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsCastSafeToRemove(ExpressionSyntax castNode,ExpressionSyntax castedExpressionNode,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.CastIfPossible(ExpressionSyntax expression,ITypeSymbol targetType,Int32 position,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.TryCastTo(ITypeSymbol targetType,ExpressionSyntax expression,ExpressionSyntax newExpression,ExpressionSyntax& newExpressionWithCast)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitArgument(ArgumentSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax originalNode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expand(SyntaxNode node,SemanticModel semanticModel,SyntaxAnnotation annotationForReplacedAliasIdentifier,Func`2 expandInsideNode,Boolean expandParameter,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Simplification.Simplifier.Expand[TNode](TNode node,SemanticModel semanticModel,Workspace workspace,Func`2 expandInsideNode,Boolean expandParameter,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Simplification.Simplifier.ExpandAsync[TNode](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.<>c__DisplayClass37_0.<ComplexifyParentingStatementsAsync>b__1[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Shared.Extensions.SyntaxNodeExtensions.ReplaceSyntaxAsync[TRoot](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.ComplexifyParentingStatementsAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.IntroduceVariable.CSharpIntroduceVariableService.IntroduceLocalDeclarationIntoBlockAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.IntroduceVariable.CSharpIntroduceVariableService.IntroduceLocalAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.AbstractIntroduceVariableCodeAction.GetChangedDocumentCoreAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.AbstractIntroduceVariableCodeAction.GetChangedDocumentAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by gafter** [comment]
I suspect the IDE is passing a `null` type to `ClassifyConversion`.

**Comment by jcouv** [comment]
This didn't repro in 16.8p3.1. Will add a test
