### ISSUE TITLE
VisualBasicLanguageServiceTest failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#44690]
https://dev.azure.com/dnceng/public/_build/results?buildId=663914&view=ms.vss-test-web.build-test-results-tab&runId=20586588&resultId=202442&paneView=debug

```
The collection was expected to contain a single element, but it was empty.


Stack trace
   at Roslyn.VisualStudio.Next.UnitTests.Services.LanguageServiceTests.<VisualBasicLanguageServiceTest>d__2.MoveNext() in /_/src/VisualStudio/Core/Test.Next/Services/LanguageServiceTests.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by tmat** [comment]
@dibarbet

**Comment by dibarbet** [comment]
A fix went in here on the same date this was filed - https://github.com/dotnet/roslyn/pull/44673 which I believe fixed the issue.
I don't see any failures in the past 100 runs from the ADO dashboard, so marking this resolved.
