### ISSUE TITLE
System.NullReferenceException in CSharpCreateTestAccessorFixer

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#44738]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(SyntaxNode node,CancellationToken cancellationToken)
   at async Roslyn.Diagnostics.Analyzers.CreateTestAccessorFixer.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
It seems that `GetDeclaredSymbolCore` tries to access `node.Kind()` while `node` is null?
If so, I've opened #44743
