### ISSUE TITLE
[LSP] LSP methods with metadata files

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#44766]
Parent - https://github.com/dotnet/roslyn/issues/44764

To move local features to LSP we need to support commands on metadata files.  Going to common metadata files generally works, but need to verify the more uncommon cases.

**Comment by dibarbet** [comment]
Note that this actually now causes a bunch of exceptions now that we've enabled semantic classifications.  The client calls into us for the metadata file, but we throw every time because we can't find the document.

For request
```
{
  "jsonrpc": "2.0",
  "id": 218,
  "method": "textDocument/semanticTokens",
  "params": {
    "textDocument": {
      "uri": "file:///C:/Users/dabarbet/AppData/Local/Temp/MetadataAsSource/c02abc17d7454d1484c9fd0f9d68a5c0/3ae8e60c0219464da4b946616d4c6ac6/Console.cs"
    }
  }
}
```

Document is null.
   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHandler.<HandleRequestAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestExecutionQueue.<>c__DisplayClass11_0`2.<<ExecuteAsync>b__0>d.MoveNext()

I think once your PR goes in we should be good @allisonchou 
I've followed up with Dayton again to see what the expectation is.
