### ISSUE TITLE
Static type in function pointer causes crash

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#44953]
```cs
static class C
{
    static delegate*<C, C> Ptr;
}
```
crashes with
```
at Roslyn.Utilities.RoslynDebug.Assert(Boolean b) in /home/fred/roslyn/src/Compilers/Core/Portable/InternalUtilities/Debug.cs:line 16
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbolExtensions.IsInterfaceType(TypeSymbol type) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:line 294
   at Microsoft.CodeAnalysis.CSharp.Symbols.ParameterHelpers.ReportParameterErrors(Symbol owner, ParameterSyntax parameterSyntax, ParameterSymbol parameter, SyntaxToken thisKeyword, SyntaxToken paramsKeyword, Int32 firstDefault, DiagnosticBag diagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs:line 453
   at Microsoft.CodeAnalysis.CSharp.Symbols.ParameterHelpers.MakeParameters[TParameterSymbol,TOwningSymbol](Binder binder, TOwningSymbol owner, SeparatedSyntaxList`1 parametersList, SyntaxToken& arglistToken, DiagnosticBag diagnostics, Boolean allowRefOrOut, Boolean allowThis, Boolean addRefReadOnlyModifier, Boolean suppressUseSiteDiagnostics, Int32 lastIndex, Func`11 parameterCreationFunc, Boolean parsingFunctionPointer) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs:line 187
   at Microsoft.CodeAnalysis.CSharp.Symbols.ParameterHelpers.MakeFunctionPointerParameters(Binder binder, FunctionPointerMethodSymbol owner, SeparatedSyntaxList`1 parametersList, DiagnosticBag diagnostics, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs:line 66
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionPointerMethodSymbol..ctor(CallingConvention callingConvention, RefKind refKind, TypeWithAnnotations returnType, ImmutableArray`1 refCustomModifiers, FunctionPointerTypeSyntax syntax, Binder typeBinder, DiagnosticBag diagnostics, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs:line 317
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionPointerMethodSymbol.CreateFromSource(FunctionPointerTypeSyntax syntax, Binder typeBinder, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs:line 84
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionPointerTypeSymbol.CreateFromSource(FunctionPointerTypeSyntax syntax, Binder typeBinder, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerTypeSymbol.cs:line 20
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:line 448
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:line 315
   at Microsoft.CodeAnalysis.CSharp.Binder.BindType(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:line 295
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbolFromDeclarator.GetFieldType(ConsList`1 fieldsBeingBound) in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs:line 457
   at Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol.get_TypeWithAnnotations() in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs:line 58
   at Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol.get_Type() in /home/fred/roslyn/src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs:line 67
```

Thanks @jkoritzinsky for reporting.

**Comment by 333fred** [comment]
Note: this also occurs for other restricted types like `ArgIterator`.
