### ISSUE TITLE
Flow graphs in null coalescing are null reffing

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#45119]
This test:
```cs
        public void PatternindexNullableCoalescingAssignmentClass()
        {
            var src = @"
using System;
struct S
{
    private readonly string[] _array;

    private int _counter;

    public S(string[] a)
    {
        _array = a;
        _counter = 0;
    }
    public int Length
    {
        get
        {
            Console.WriteLine(""Length "" + _counter++);
            return _array.Length;
        }
    }
    public string this[int index] 
    {
        get
        {
            Console.WriteLine(""Get "" + _counter++);
            return _array[index];
        }
        set
        {
            Console.WriteLine(""Set "" + _counter++);
            _array[index] = value;
        }
    }

}
class C
{
    static void Main(string[] args)
    /*<bind>*/{
        var array = new string[2];
        var s = new S(array);
        s[^1] ??= s[^2];
    }/*</bind>*/
}";
            var comp = CreateCompilationWithIndex(src, options: TestOptions.ReleaseExe);
            VerifyFlowGraphForTest<BlockSyntax>(comp, "");
        }
```

Is currently failing. It's a modification of `IndexAndRangeTests.PatternindexNullableCoalescingAssignmentClass`, so I'm not sure where the exact minimal repro is.

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitCoalesceAssignment(ICoalesceAssignmentOperation operation, Nullable`1 captureIdForResult) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 2909
   at Microsoft.CodeAnalysis.Operations.BaseCoalesceAssignmentOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 7512
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 8755
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation, Nullable`1 argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 6970
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Visit(IOperation operation) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 6960
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitExpressionStatement(IExpressionStatementOperation operation, Nullable`1 captureIdForResult) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 3294
   at Microsoft.CodeAnalysis.Operations.BaseExpressionStatementOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 3888
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 8755
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1206
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatementsOneOrAll(IOperation operation, ImmutableArray`1 statements, Int32 startIndex) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1403
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatements(ImmutableArray`1 statements) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1373
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitBlock(IBlockOperation operation, Nullable`1 captureIdForResult) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1342
   at Microsoft.CodeAnalysis.Operations.BaseBlockOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 2928
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 8755
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1206
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodies(IBlockOperation blockBody, IBlockOperation expressionBody) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1470
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodyBaseOperation(IMethodBodyBaseOperation operation) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1463
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitMethodBodyOperation(IMethodBodyOperation operation, Nullable`1 captureIdForResult) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1456
   at Microsoft.CodeAnalysis.Operations.BaseMethodBodyOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 7323
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.Visit(IOperation operation, TArgument argument) in /home/fred/roslyn/src/Compilers/Core/Portable/Generated/Operations.Generated.cs:line 8755
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.VisitStatement(IOperation operation) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 1206
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraphBuilder.Create(IOperation body, ControlFlowGraph parent, ControlFlowRegion enclosing, CaptureIdDispenser captureIdDispenser, Context& context) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:line 111
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraph.CreateCore(IOperation operation, String argumentNameForException, CancellationToken cancellationToken) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs:line 181
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraph.CreateCore(IOperation operation, String argumentNameForException, CancellationToken cancellationToken) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs:line 181
   at Microsoft.CodeAnalysis.FlowAnalysis.ControlFlowGraph.Create(IMethodBodyOperation methodBody, CancellationToken cancellationToken) in /home/fred/roslyn/src/Compilers/Core/Portable/Operations/ControlFlowGraph.cs:line 156
   at Microsoft.CodeAnalysis.Test.Utilities.ControlFlowGraphVerifier.GetControlFlowGraph(SyntaxNode syntaxNode, SemanticModel model) in /home/fred/roslyn/src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:line 46
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.VerifyFlowGraph(CSharpCompilation compilation, SyntaxNode syntaxNode, String expectedFlowGraph) in /home/fred/roslyn/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs:line 1776
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.VerifyFlowGraphForTest[TSyntaxNode](CSharpCompilation compilation, String expectedFlowGraph) in /home/fred/roslyn/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs:line 1770
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.IndexAndRangeTests.PatternindexNullableCoalescingAssignmentClass() in /home/fred/roslyn/src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:line 460
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 150
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 257
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__0() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 242
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 
```

**Comment by 333fred** [comment]
This is a very common failure when running with the IOperation test hook currently.
