### ISSUE TITLE
Throwing IndexOutOfRange in MetadataWriter.GetRowCounts()

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/roslyn#4512]
On Linux I am getting:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Cci.MetadataWriter.GetRowCounts()
   at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[] methodBodyRvas, BlobBuilder mappedFieldDataWriter, BlobBuilder resourceWriter)
   at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& entryPointToken, MetadataSizes& metadataSizes)
   at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, CancellationToken cancellationToken)
```

A quick look at the code didn't show anything obvious, an array was created with the size of the largest element in a enum + 1 and the index accesses were just the enum values.

**Comment by jaredpar** [comment]
Can you give us some more info:

- A repro solution or an indication of the code that was being compiled 
- A dump of the compiler

Need some more information in order to track this down.

**Comment by BrennanConroy** [comment]
Found out that this is caused by a difference in the TableIndex.cs file used by Microsoft.CodeAnalysis from Roslyn and System.Reflection.Metadata from Cross-Plat CoreCLR

**Comment by jaredpar** [comment]
@BrennanConroy how is this difference causing the bug?

**Comment by BrennanConroy** [comment]
Microsoft.CodeAnalysis has a TableIndex enum with 55 as the highest value but System.Reflection.Metadata has a TableIndex enum with 44 as the highest value. So when accessing the array created with size = highest value of enum with the highest being 44 but indexes going to 55, you get an exception.

This can be closed. Its an issue with picking the correct dll's between Roslyn and CoreCLR
