### ISSUE TITLE
NullReferenceException on GetChangedRoot call while the xmldoc doesn't mention any exception

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45145]
**Version Used**: 

Visual Studio 2019 16.5.4

**Steps to Reproduce**:

https://stackoverflow.com/questions/62363572 (It's not answered yet, but whether the code I've have a problem or not, the xmldoc should mention that GetChangedRoot may throw an exception with, and when/why it's thrown with the `<exception>` tag.

**Comment by CyrusNajmabadi** [comment]
It's an internal crash. Those aren't things that are doc'ed :-(

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Does that mean it's a bug and the error shouldn't happen?

**Comment by Youssef1313** [comment]
Stackoverflow question was deleted for some reason. Here is the report:

I wrote an analyzer with codefix to remove all the ByVals in VB code as they're useless. The analyzer works, the codefix test passes, but the codefix doesn't work in Visual Studio.

Analyzer:

```vb
Imports System.Collections.Immutable
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.VisualBasic
Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
Imports Microsoft.CodeAnalysis.Diagnostics

<DiagnosticAnalyzer(LanguageNames.VisualBasic)>
Public Class Analyzer2Analyzer
    Inherits DiagnosticAnalyzer

    Private Shared ReadOnly Rule As New DiagnosticDescriptor("IDE0078", "Unnecessary ByVal", "The modifier ByVal is unnecessary and can be removed.", "CodeStyle", DiagnosticSeverity.Hidden, isEnabledByDefault:=True, description:="Unnecessary ByVal can be removed.", "https://helplink.com/", WellKnownDiagnosticTags.Unnecessary, WellKnownDiagnosticTags.Telemetry)

    Public Overrides ReadOnly Property SupportedDiagnostics As ImmutableArray(Of DiagnosticDescriptor) = ImmutableArray.Create(Rule)

    Public Overrides Sub Initialize(context As AnalysisContext)
        context.EnableConcurrentExecution()
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None)
        context.RegisterSyntaxNodeAction(
            Sub(syntaxContext As SyntaxNodeAnalysisContext)
                Dim parameterSyntax = DirectCast(syntaxContext.Node, ParameterSyntax)
                For Each modifier In parameterSyntax.Modifiers
                    If modifier.IsKind(SyntaxKind.ByValKeyword) Then
                        syntaxContext.ReportDiagnostic(Diagnostic.Create(Rule, modifier.GetLocation()))
                    End If
                Next
            End Sub, SyntaxKind.Parameter)
    End Sub

End Class
```


CodeFix:

```
Imports System.Collections.Immutable
Imports System.Composition
Imports System.Threading
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.CodeFixes
Imports Microsoft.CodeAnalysis.CodeActions
Imports Microsoft.CodeAnalysis.VisualBasic
Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
Imports Microsoft.CodeAnalysis.Editing

<ExportCodeFixProvider(LanguageNames.VisualBasic, Name:=NameOf(Analyzer2CodeFixProvider)), [Shared]>
Public Class Analyzer2CodeFixProvider
    Inherits CodeFixProvider

    Public NotOverridable Overrides ReadOnly Property FixableDiagnosticIds As ImmutableArray(Of String) = ImmutableArray.Create("IDE0078")

    Public NotOverridable Overrides Function GetFixAllProvider() As FixAllProvider
        Return WellKnownFixAllProviders.BatchFixer
    End Function

    Public Overrides Async Function RegisterCodeFixesAsync(context As CodeFixContext) As Task
        Dim root = Await context.Document.GetSyntaxRootAsync(context.CancellationToken)
        Dim editor As New SyntaxEditor(root, context.Document.Project.Solution.Workspace)
        For Each diagnostic In context.Diagnostics
            context.RegisterCodeFix(New MyCodeAction(Function(ct) FixAsync(context.Document, diagnostic, editor, ct)), context.Diagnostics)
        Next
    End Function

    Private Async Function FixAsync(document As Document, diagnostic As Diagnostic, editor As SyntaxEditor, cancellationToken As CancellationToken) As Task(Of Document)
        Dim root = Await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(False)
        Dim node = DirectCast(root.FindNode(diagnostic.Location.SourceSpan), ParameterSyntax)
        Dim tokenList = SyntaxFactory.TokenList(node.Modifiers.Where(Function(m) Not m.IsKind(SyntaxKind.ByValKeyword)))
        editor.ReplaceNode(node, node.WithModifiers(tokenList))
        Dim newRoot As SyntaxNode
        Try
            newRoot = editor.GetChangedRoot()
        Catch ex As Exception
            Debug.WriteLine(ex) ' This line is hit, which indicates that the exception is thrown by GetChangedRoot(), the StackTrace shows that too.
            Throw
        End Try
        Return document.WithSyntaxRoot(newRoot)
    End Function


    Private Class MyCodeAction
        Inherits CodeAction

        Public Overrides ReadOnly Property Title As String = "Remove ByVal modifier"

        Private ReadOnly _createChangedDocument As Func(Of CancellationToken, Task(Of Document))

        Public Sub New(createChangedDocument As Func(Of CancellationToken, Task(Of Document)))
            _createChangedDocument = createChangedDocument
        End Sub

        Protected Overrides Function GetChangedDocumentAsync(cancellationToken As CancellationToken) As Task(Of Document)
            Return _createChangedDocument(cancellationToken)
        End Function
    End Class
End Class
```

Unit Tests:

```
Imports Analyzer2.Test.TestHelper
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.CodeFixes
Imports Microsoft.CodeAnalysis.Diagnostics
Imports Microsoft.VisualStudio.TestTools.UnitTesting

Namespace Analyzer2.Test
    <TestClass>
    Public Class UnitTest
        Inherits CodeFixVerifier

        'Diagnostic And CodeFix both triggered And checked for
        <TestMethod>
        Public Sub TestRemoveByVal()

            Dim test = "
Module Module1

    Sub Main(ByVal x As String)

    End Sub

End Module"
            Dim expected = New DiagnosticResult With {.Id = "IDE0078",
                .Message = "The modifier ByVal is unnecessary and can be removed.",
                .Severity = DiagnosticSeverity.Hidden,
                .Locations = New DiagnosticResultLocation() {
                        New DiagnosticResultLocation("Test0.vb", 4, 14)
                    }
            }


            VerifyBasicDiagnostic(test, expected)

            Dim fixtest = "
Module Module1

    Sub Main(x As String)

    End Sub

End Module"
            VerifyBasicFix(test, fixtest)
        End Sub

        Protected Overrides Function GetBasicCodeFixProvider() As CodeFixProvider
            Return New Analyzer2CodeFixProvider()
        End Function

        Protected Overrides Function GetBasicDiagnosticAnalyzer() As DiagnosticAnalyzer
            Return New Analyzer2Analyzer()
        End Function

    End Class
End Namespace
```

Visual Studio shows the following error when applying the codefix:

'Analyzer2CodeFixProvider' encountered an error and has been disabled.

The StackTrace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.CodeGeneration.VisualBasicSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Analyzer2.Analyzer2CodeFixProvider.VB$StateMachine_6_FixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

Note: Visual Studio correctly shows a preview of the fix, but fails to actually apply it.

**Comment by Youssef1313** [comment]
This no longer reproduces for me. I'm going to close.
