### ISSUE TITLE
'VisualBasicInvertSingleLineIfCodeRefactoringProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45177]
**Version Used**: 

Visual Studio 2019 16.5.4

**Steps to Reproduce**:

```vb
        Using client As New WebClient() With {.Proxy = New WebProxy()}
            If Not client.DownloadString("SOME_LINK").ToUpperInvariant().Contains("SOME_STRING") Then End
        End Using
```

**StackTrace**

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxList`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.VisualBasic.InvertIf.VisualBasicInvertSingleLineIfCodeRefactoringProvider.UpdateIf(SourceText sourceText,SingleLineIfStatementSyntax ifNode,SyntaxNode condition,SyntaxList`1 trueStatements,SyntaxList`1 falseStatements)
   at Microsoft.CodeAnalysis.InvertIf.AbstractInvertIfCodeRefactoringProvider`3.GetRootWithInvertIfStatement(SourceText text,SyntaxNode root,TIfStatementSyntax ifNode,InvertIfStyle invertIfStyle,SyntaxNode subsequentSingleExitPointOpt,SyntaxNode negatedExpression)
   at async Microsoft.CodeAnalysis.InvertIf.AbstractInvertIfCodeRefactoringProvider`3.InvertIfAsync[TIfStatementSyntax,TStatementSyntax,TEmbeddedStatement](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
@allisonchou want to take a look?
