### ISSUE TITLE
NullReferenceException in SyntaxNodeExtensions.WithTrailingTrivia

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45190]
StackTrace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia)
   at async Microsoft.NetCore.Analyzers.Performance.DoNotUseCountWhenAnyCanBeUsedFixer.DoNotUseCountWhenAnyCanBeUsedCodeAction.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

![image](https://user-images.githubusercontent.com/31348972/84649831-83421780-af07-11ea-9748-9caef9ff3577.png)

**Comment by CyrusNajmabadi** [comment]
> `Microsoft.NetCore.Analyzers.Performance.DoNotUseCountWhenAnyCanBeUsedFixer.DoNotUseCountWhenAnyCanBeUsedCodeAction.`

This is not roslyn.  I'll transfer.
