### ISSUE TITLE
CSharpGenerateVariableCodeFixProvider crash -  Destination type must be a TypeDeclarationSyntax 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1082525/csharpgeneratevariablecodefixprovider-crash-destin.html)._

---
I got a note that it crashed. Here is the provided stack trace. It happened when I clicked on the tip on the left for a red underlined keyword. I had some compiler errors earlier in the file, and it looks like the rest of the file is confused and the brackets might be wrong, making the rest of the file at namespace declaration scope somehow.

System.ArgumentException : Destination type must be a TypeDeclarationSyntax or a CompilationUnitSyntax, but given one is NamespaceDeclarationSyntax.
Parameter name: destination
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.CheckDeclarationNode[TDeclarationNode1,TDeclarationNode2](SyntaxNode destination)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddProperty[TDeclarationNode](TDeclarationNode destination,IPropertySymbol property,CodeGenerationOptions options,IList`1 availableIndices)
   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.<>c__DisplayClass51_0. <AddPropertyAsync>b__0(SyntaxNode t,CodeGenerationOptions opts,IList`1 ai,CancellationToken ct)
   at async Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.GetEditAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Visual Studio Feedback System on 6/18/2020, 02:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/18/2020, 09:17 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by AndrewFauldsMsft** [comment]
More specific repro - I had an extra } or two a few lines above where the issue was, causing the scope this issue was in to think it was at namespace scope in the C# file (when really it was inside a method). Then when I clicked on the tool tip, it crashed. I forget what the exact problem was - possibly a missing using statement.

**Comment by danmosemsft** [comment]
Here's my repro:
```C#
using System;

namespace ConsoleApp5
{
    class MyException: Exception
    
    internal MyException(int error, int offset, string message) : base(message)
    {
        Error = error;
        Offset = offset;
    }
```
Note the missing open curly for the class. 
I ctrl-. on “Error” and the callstack appears:
System.ArgumentException : Destination type must be a TypeDeclarationSyntax or a CompilationUnitSyntax, but given one is NamespaceDeclarationSyntax.
Parameter name: destination
