### ISSUE TITLE
Editor: crashed in ExtractMethod

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45422]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1087377/editor-crashed-in-extractmethod.html)._

---
C#

Editing my file by copy/pasting code from another window. 

For sure, I was not actually extracting a method (just copying lines).

Got this crash:

```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.ExtractMethod.InsertionPoint.ComputeContextNode()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.ExtractMethod.InsertionPoint.GetContext()
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractLocalFunctionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Visual Studio Feedback System on 6/22/2020, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 This looks very similar to #40555, but it was reported in 16.6.2 where the earlier issue was already fixed.

**Comment by allisonchou** [comment]
I've asked the user in the original GitHub issue for additional details - marking as Need More Info for now.

**Comment by yyjdelete** [comment]
@allisonchou
See the same stacktrace in VS16.8 Preview3.2

One possible reproduce
* Select `static void >LocalMethod1_1<()`(text between `>` and `<`) and Press Alt+Enter;
* Or select all text between `>` and `<`
```cs
                    LocalMethod1_1();>

                    static void LocalMethod1_1()
                    {
                    }<
```

Reproduce code
```cs
using System.Collections.Generic;

    class Class1
    {
        static void Method()
        {
            foreach (var cur in new List<int>())
            {
                LocalMethod1();
                static void LocalMethod1()
                {
                    LocalMethod1_1();

                    static void LocalMethod1_1()
                    {
                    }

                    static void LocalMethod1_2()
                    {
                        //It's useless and can be any local functions, but without this, you can see the gold bar only once.
                    }
                }
            }
        }
    }
```
