### ISSUE TITLE
CSharpDeclareAsNullableCodeFixProvider: System.ArgumentException : The node is not part of the tree.

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#45431]
**Version Used**: 16.6.2

**Steps to Reproduce**:
Not sure exactly.

**Exception**:
```
System.ArgumentException : The node is not part of the tree.
Parameter name: node
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.CheckNodeInOriginalTreeOrTracked(SyntaxNode node)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceNode(SyntaxNode node,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.MakeDeclarationNullable(SyntaxEditor editor,SemanticModel model,SyntaxNode node,HashSet`1 alreadyHandled)
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.FixAllAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Evangelink** [comment]
@jinujoseph I can't find a way to have a constant reproduction of this error. I'll let you know if this still happens on more recent versions of VS.
