### ISSUE TITLE
Extract method crashes when using wrong number of type arguments

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#45488]
Using 30222.8.master

Extract method seems to crash when the  wrong number of arguments are provided, for example when invoking the lightbulb on the highlighted code below:
![extractmethod](https://user-images.githubusercontent.com/16968319/85899207-97610100-b7b2-11ea-8c07-25cf39e5afe9.png)

**Stack trace:**
```
System.ArgumentException : Wrong number of type arguments
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct(ImmutableArray`1 typeArguments,Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamedTypeSymbol.Microsoft.CodeAnalysis.INamedTypeSymbol.Construct(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.SymbolKey.ErrorTypeSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKey()
   at Microsoft.CodeAnalysis.SymbolKey.ResolveString(String symbolKey,Compilation compilation,Boolean ignoreAssemblyKey,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.Extensions.ResolveType[T](SemanticModel semanticModel,T symbol)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.AnalyzerResult..ctor(SemanticDocument document,IEnumerable`1 typeParametersInDeclaration,IEnumerable`1 typeParametersInConstraintList,IList`1 variables,VariableInfo variableToUseAsReturnValue,ITypeSymbol returnType,Boolean awaitTaskReturn,Boolean instanceMemberIsUsed,Boolean shouldBeReadOnly,Boolean endOfSelectionReachable,OperationStatus status)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)```

**Comment by ryzngard** [comment]
Moving to backlog. I believe this should be fixed, but isn't high priority because this is refactoring code that fails to compile AND falls into a specific case where we can't resolve the  symbol. Likely the fix is that the extracted method returns `object` or `Task<object>` in this case

**Comment by akhera99** [comment]
No repro on Visual Studio 16.10.0 Preview 0, the code action no longer seems to be offered in this case.
