### ISSUE TITLE
Visual Studio instantly crashes if you really want it to by doing this rename

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45677]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1095778/visual-studio-instantly-crashes-if-you-really-want.html)._

---
Priority of this issue may be, very, very low, but not completely, because instant crashes can lead to serious loss of data ... ;)

What happened?:
I just made a little discovery when experimenting with the deep limits of the C# language :P (with a property-versus-method conflict that technically only exists at IL level and not in C# itself):

Supose you have a property:
```
public int MyProperty { get; set; }
```
Then you have this method:
```
private void _set_MyProperty(int value) => MyProperty = value;
```
Then use Visual Studio its renaming feature (Ctrl+R, Ctrl+R) and try to remove the underscore so that you get this:
```
private void set_MyProperty(int value) => MyProperty = value;
```

BOOM! Instant exit of the entire IDE.

---
#### Roi Chen [MSFT] on 6/29/2020, 07:18 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
• Open Visual Studio Feedback tool.<br>
• Click the banner letting you know that you have problems requesting your attention.<br>
• Click this problem from the list<br>
• Click “View their request and respond” from the problem details banner<br>
• Add a comment, in the Attachments/Record: click Start Recording<br>
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
• When you’re done, choose the Stop Record button.<br>
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Eduard de Jong on 6/30/2020, 02:02 PM: 

Hereby my reply to your request, including the requested recording.<br>This time, Visual Studio did an automatic reboot after the crash, which it doesn&#39;t do each time by the way.<br><br>And I realize that I forgot to add the following information:<br>The project type is a Console application, .NET Core 3.1.<br><br>The complete code you need is nothing more than simply this:<br><br>using System;<br><br>namespace ConsoleApp1<br>{<br>    class Program<br>    {<br>        public int MyProperty { get; set; }<br><br>        public void _set_MyProperty(int value) =&gt; MyProperty = value;<br><br>        static void Main(string[] args)<br>        {<br>            Console.WriteLine(&quot;Hello World!&quot;);<br>        }<br>    }<br>}<br>
#### Visual Studio Feedback System on 7/6/2020, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
```
Event Time (UTC): 29-6-2020 23:59:34
Event ID: 1025
Data: Toepassing: devenv.exe
Framework-versie: v4.0.30319
Beschrijving: in de toepassing is gevraagd het proces te beëindigen via System.Environment.FailFast (tekenreeksbericht).
Bericht: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<>c__DisplayClass4_0.<ComputeDeclarationConflictsAsync>b__3(Location t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableArray`1.Builder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConflictsAsync>d__4.MoveNext()
Stack:
   bij System.Environment.FailFast(System.String, System.Exception)
   bij Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   bij Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   bij Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   bij Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   bij Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService+<ComputeDeclarationConflictsAsync>d__4.MoveNext()
   bij System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   bij Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService+<>c__DisplayClass4_0.<ComputeDeclarationConflictsAsync>b__3(Microsoft.CodeAnalysis.Location)
   bij System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   bij System.Collections.Immutable.ImmutableArray`1+Builder[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   bij Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   bij Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService+<ComputeDeclarationConflictsAsync>d__4.MoveNext()
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].Start[[Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService+<ComputeDeclarationConflictsAsync>d__4, Microsoft.CodeAnalysis.CSharp.Workspaces, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComputeDeclarationConflictsAsync>d__4 ByRef)
   bij Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.ComputeDeclarationConflictsAsync(System.String, Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.ISymbol, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId>, Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Solution, System.Collections.Generic.IDictionary`2<Microsoft.CodeAnalysis.Location,Microsoft.CodeAnalysis.Location>, System.Threading.CancellationToken)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+<AddDeclarationConflictsAsync>d__9.MoveNext()
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+<AddDeclarationConflictsAsync>d__9, Microsoft.CodeAnalysis.Workspaces, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<AddDeclarationConflictsAsync>d__9 ByRef)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.AddDeclarationConflictsAsync(Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.ISymbol, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId>, Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution, System.Collections.Generic.IDictionary`2<Microsoft.CodeAnalysis.Location,Microsoft.CodeAnalysis.Location>, System.Threading.CancellationToken)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session+<IdentifyConflictsAsync>d__19.MoveNext()
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session+<IdentifyConflictsAsync>d__19, Microsoft.CodeAnalysis.Workspaces, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<IdentifyConflictsAsync>d__19 ByRef)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session.IdentifyConflictsAsync(System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DocumentId>, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.DocumentId>, Microsoft.CodeAnalysis.ProjectId, Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolution)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session+<ResolveConflictsAsync>d__18.MoveNext()
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session+<ResolveConflictsAsync>d__18, Microsoft.CodeAnalysis.Workspaces, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ResolveConflictsAsync>d__18 ByRef)
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver+Session.ResolveConflictsAsync()
   bij Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.ResolveConflictsAsync(Microsoft.CodeAnalysis.Rename.RenameLocations, System.String, System.Collections.Immutable.ImmutableHashSet`1<Microsoft.CodeAnalysis.ISymbol>, System.Threading.CancellationToken)
   bij Microsoft.CodeAnalysis.Rename.Renamer+<RenameAsync>d__3.MoveNext()
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Rename.Renamer+<RenameAsync>d__3, Microsoft.CodeAnalysis.Workspaces, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RenameAsync>d__3 ByRef)
   bij Microsoft.CodeAnalysis.Rename.Renamer.RenameAsync(Microsoft.CodeAnalysis.Rename.RenameLocations, System.String, System.Collections.Immutable.ImmutableHashSet`1<Microsoft.CodeAnalysis.ISymbol>, System.Threading.CancellationToken)
   bij Microsoft.CodeAnalysis.Rename.Renamer+<RenameSymbolAsync>d__4.MoveNext()
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bij System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bij System.Threading.Tasks.Task.FinishContinuations()
   bij System.Threading.Tasks.Task.FinishStageThree()
   bij System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bij Microsoft.CodeAnalysis.Rename.RenameLocations+<FindAsync>d__26.MoveNext()
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bij System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bij System.Threading.Tasks.Task.FinishContinuations()
   bij System.Threading.Tasks.Task.FinishStageThree()
   bij System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   bij Microsoft.CodeAnalysis.Rename.RenameLocations+<AddLocationsReferenceSymbolsAsync>d__30.MoveNext()
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   bij System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   bij System.Threading.Tasks.Task.FinishContinuations()
   bij System.Threading.Tasks.Task.FinishStageThree()
   bij System.Threading.Tasks.Task.FinishStageTwo()
   bij System.Threading.Tasks.Task.Finish(Boolean)
   bij System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bij System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bij System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bij System.Threading.ThreadPoolWorkQueue.Dispatch()
   bij System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
