### ISSUE TITLE
NRE in GetNamingRulesAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#45944]
Seen in logs from https://developercommunity.visualstudio.com/content/problem/1078164/visual-studio-unrecoverable-process-error-4.html

```
07/03/2020 11:31:25 Russia TZ 2 Standard Time: Error : 1 :[devenv:7420] Unexpected exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetNamingRulesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.AddConstructorParametersFromMembers.AddConstructorParametersFromMembersCodeRefactoringProvider.State.<TryInitializeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.AddConstructorParametersFromMembers.AddConstructorParametersFromMembersCodeRefactoringProvider.State.<GenerateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.AddConstructorParametersFromMembers.AddConstructorParametersFromMembersCodeRefactoringProvider.<AddConstructorParametersFromMembersAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.AddConstructorParametersFromMembers.AddConstructorParametersFromMembersCodeRefactoringProvider.<ComputeRefactoringsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__13.MoveNext()
```

**Comment by kirsan31** [comment]
Hi, the original issue is my. As I [wrote](https://developercommunity.visualstudio.com/comments/1111568/view.html) when sending logs:  the logs from last 10 days. and I am not sure that this error was happening during last 10 days. It's less frequent now...
Is this issue really the same as [original](https://developercommunity.visualstudio.com/content/problem/1078164/visual-studio-unrecoverable-process-error-4.html)?
As soon as I see error again I will provide the logs...

**Comment by kirsan31** [comment]
As I was afraid this is 2 different issues :( [Original](https://developercommunity.visualstudio.com/content/problem/1078164/visual-studio-unrecoverable-process-error-4.html) error happens today again, logs:
[logs.zip](https://github.com/dotnet/roslyn/files/4926978/logs.zip).
