### ISSUE TITLE
Assertion Failed in Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#45955]
**Version Used**: 
Version 16.7.0 Preview 4.0 [30312.25.d16.7]

The assert fails within 5 minutes of working in Roslyn.sln in both in-proc and out-of-proc processes. When it's in OOP it seems to be causing failures in the remote service (still investigating why exactly).

Memory dump:
%internal_share%\public\tomat\Bugs\45955
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()

   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)

   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)

   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)

   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel, SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.State.<TryInitializeAsync>d__97.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.State.TryInitializeAsync(TService service, SemanticDocument semanticDocument, SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.State.<GenerateAsync>d__96.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.State.GenerateAsync(TService service, SemanticDocument document, SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.<GenerateTypeAsync>d__26.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.GenerateTypeAsync(Document document, SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CodeFixes.GenerateType.GenerateTypeCodeFixProvider.GetCodeActionsAsync(Document document, SyntaxNode node, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.<RegisterCodeFixesAsync>d__3.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(CodeFixContext context)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass26_1.<ContainsAnyFixAsync>b__1()

   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(IExtensionManager extensionManager, Object extension, Func`1 function)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<ContainsAnyFixAsync>d__26.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.ContainsAnyFixAsync(Document document, DiagnosticData diagnostic, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<GetFirstDiagnosticWithFixAsync>d__13.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetFirstDiagnosticWithFixAsync(Document document, IEnumerable`1 severityGroup, TextSpan range, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass12_0.<GetMostSevereFixableDiagnosticAsync>b__2()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by 333fred** [comment]
This is a threading bug: we check to make sure that we don't need to take an unnecessary read lock before attempting to take it, but then after we take the read lock we assume that no one else grabbed the write lock in between the check and the read lock acquire. It'll cause us to do more work, but shouldn't have any observable side affects.
