### ISSUE TITLE
Failed composition in Microsoft.VisualStudio.CodeLens.Service.CodeLensServiceHubService.<CanCreateDataPointAsync> 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46103]
**Version Used**: 

16.6.30225.117

Seen in ServiceHub logs of https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1155340

```
07/13/2020 10:11:08 GMT Standard Time : Error : System.InvalidOperationException: GetExportedValue cannot be called before prerequisite import 'Microsoft.VisualStudio.LanguageServices.CodeLens.ReferenceCodeLensProvider..ctor (Parameter="codeLensCallbackService", ContractName="Microsoft.VisualStudio.Language.CodeLens.Remoting.ICodeLensCallbackService")' has been set.
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.EnsureGettable()
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.GetExportedValue(ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.CodeLens.Service.CodeLensServiceHubService.<CanCreateDataPointAsync>d__21.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and lack of reports.
