### ISSUE TITLE
Source text cannot be embedded when using SourceGenerator

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#46158]
**Version Used**:  Vs 16.7.0 preview 4.0

**Steps to Reproduce**:

I'm referencing a source generator from another project in the same solution like so:

```xml
	<ItemGroup>
		<ProjectReference Include="..\StrongInject\StrongInject.csproj"
						  OutputItemType="Analyzer">
			<SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
		</ProjectReference>
	</ItemGroup>
```

when I build I get the following error:

```
Description
Unhandled Exception: System.ArgumentException: SourceText cannot be embedded. Provide encoding or canBeEmbedded=true at construction.
Parameter name: text
   at Microsoft.CodeAnalysis.EmbeddedText.FromSource(String filePath, SourceText text)
   at Microsoft.CodeAnalysis.CommonCompiler.<>c.<CompileAndEmit>b__65_1(SyntaxTree t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray`1.InsertRange(Int32 index, IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray`1.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

**Comment by jinujoseph** [comment]
cc @chsienki @jasonmalinowski

**Comment by YairHalberstadt** [comment]
This can be fixed by specifying the encoding when generating the original sourceText. However it would probably be best if the generator driver does this for you by default?

**Comment by chsienki** [comment]
Currently you have to explicitly add an encoding to the source text. 

```csharp
var sourceText = SourceText.From(output, Encoding.UTF8);
```

 We're planning on fixing this for the next SG preview: https://github.com/dotnet/roslyn/projects/54#card-42290066

**Comment by chsienki** [comment]
We've added an overload in an upcoming release that takes a string, and doesn't require encoding, as well as throwing an exception much earlier if you provide a source text without encoding.
