### ISSUE TITLE
NullReferenceException in ParseNamespaceBody

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#46202]
**Version Used**: 3.7.0-4.final 

**Steps to Reproduce**:
Sorry, I don't have a repro. Hopefully the stack trace can help pinpoint this.

**Expected Behavior**:
No exception.

**Actual Behavior**:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(?)
   at async Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(?)
```

**Comment by jaredpar** [comment]
Closing because the stack trace itself isn't enough to track down this particular bug. If you can get a repro or crash dump please let us know and we will take a look.
