### ISSUE TITLE
SyntaxEditorBasedFixAllProvider crashes when resolving all "IDE0058 C# Expression value is never used" issues with nested calls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46251]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1103976/syntaxeditorbasedfixallprovider-crashes-when-resol.html)._

---
Create a new C# solution with the following in the main .cs file:

```
using System;

namespace ConsoleApp {
	public static class ConsoleApp {
		public static void Main(string[] args) {
			Foo(() => { Bar(); return true; });
		}

public static bool Foo(Func<bool> func) {
			return func. Invoke();
		}

public static bool Bar() {
			return true;
		}
	}
}
```

Invoke the "IDE0058" resolver for the file/project/solution (eg., ctrl+. on `Foo` in `Main` -> Use Discard '_' => Fix all occurrences in Document | Project | Solution).

SyntaxEditorBasedFixAllProvider crashes with the following stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.LanguageServices.CSharpSyntaxFacts.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.FixDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0. <InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

Resolving either of the unused expression values (and restarting the SyntaxEditorBasedFixAllProvider) will resolve the issue, and all instances can be resolved in the document/project/solution.

Note: a stop-gap solution which includes the location of the nested call in the error message or stack trace would be very much appreciated, even if the bug itself can't be resolved; as-is, finding such calls requires a fairly tedious manual search through the code base.

---
#### Roi Chen [MSFT] on 7/6/2020, 07:32 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
• Open Visual Studio Feedback tool.<br>
• Click the banner letting you know that you have problems requesting your attention.<br>
• Click this problem from the list<br>
• Click “View their request and respond” from the problem details banner<br>
• Add a comment, in the Attachments/Record: click Start Recording<br>
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
• When you’re done, choose the Stop Record button.<br>
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Robert Fensterman on 7/7/2020, 08:57 AM: 

Commenting so I can add a recording as an attachment, per request.
#### Feedback Bot on 7/14/2020, 09:52 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Robert Fensterman on 7/15/2020, 06:53 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/18031/d62bfa40-d617-6c9d-ad68-8760dcad8e39.html" nodeid="18031">@Roi Chen [MSFT]</a>: <a rel="user" href="https://developercommunity.visualstudio.com/users/7/siteadmin.html" nodeid="7">@Feedback Bot</a> says you need additional information, but I think I included everything that was requested.</p><p>If there's anything else that would be helpful, please let me know.</p>

#### Feedback Bot on 7/22/2020, 08:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani
