### ISSUE TITLE
Flaky test RemoteHostClientServiceFactoryTests.UpdaterService

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46252]
The following test failure occurred in #46114. I believe it is spurious. FYI @tmat @sharwell.

Build link: https://dev.azure.com/dnceng/public/_build/results?buildId=742574&view=logs&jobId=6a7d83c1-6850-57a3-ff09-22192451ed19&j=6a7d83c1-6850-57a3-ff09-22192451ed19&t=4ea3a14e-48a8-5786-ef24-cc42a01f29bc

From the xunit log:
```cs
Roslyn.VisualStudio.Next.UnitTests.Remote.RemoteHostClientServiceFactoryTests.UpdaterService [STARTING]
    Assert.True() Failure
    Expected: True
    Actual:   False
    Stack Trace:
    /_/src/VisualStudio/Core/Test.Next/Remote/RemoteHostClientServiceFactoryTests.cs(67,0): at Roslyn.VisualStudio.Next.UnitTests.Remote.RemoteHostClientServiceFactoryTests.<UpdaterService>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Roslyn.VisualStudio.Next.UnitTests.Remote.RemoteHostClientServiceFactoryTests.UpdaterService [FINISHED] Time: 4.2453052s
```

**Comment by RikkiGibson** [comment]
Closing in favor of #46255
