### ISSUE TITLE
Roslyn OOP error KeyNotFoundException in SymbolFinder.FindReferencesServerCallback.<OnReferenceFoundAsync>

### ISSUE THREAD

**Issue by eddynaka** [dotnet/roslyn#46258]
**Version Used**: Microsoft Visual Studio Enterprise 2019 Preview / Version 16.7.0 Preview 5.0

Place where I found the log: `%temp%\servicehub\logs`

Don't know exactly how to force the error, but it's kinda frequent.

Below, the log:

```
07/23/2020 11:13:45 E. South America Standard Time: Error : 1 :[ServiceHub.RoslynCodeAnalysisService32:6920] Unexpected exception: StreamJsonRpc.RemoteInvocationException: The given key was not present in the dictionary.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__118`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.RemoteEndPoint.<InvokeAsync>d__19.MoveNext()
RPC server exception:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
      at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesServerCallback.<OnReferenceFoundAsync>d__13.MoveNext()
```

**Expected Behavior**:
- no gold bar

**Actual Behavior**:
- gold bar showing an exception/stack trace

**Comment by sharwell** [comment]
@CyrusNajmabadi

**Comment by sharwell** [comment]
@eddynaka I've seen this exception in the logs, but I'm not sure this exception is the reason the gold bar appeared.

**Comment by CyrusNajmabadi** [comment]
Mitigated with https://github.com/dotnet/roslyn/pull/47339 and fixed with https://github.com/dotnet/roslyn/pull/47343
