### ISSUE TITLE
InvalidOperationException: Unexpected value 'UnconvertedConditionalOperator' in EmitExpression

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#46339]
Compile:
```C#
class Program
{
    static unsafe void M(bool b, byte[] bytes)
    {
        fixed (byte* buffer = b ? bytes : null)
        {
        }
    }
}
```
Result:
Unexpected value 'UnconvertedConditionalOperator' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) in C:\Roslyn\open2\src\Compilers\CSharp\Portable\CodeGen\EmitExpression.cs:line 337
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) in C:\Roslyn\open2\src\Compilers\CSharp\Portable\CodeGen\EmitExpression.cs:line 61
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAssignmentValue(BoundAssignmentOperator assignmentOperator) in C:\Roslyn\open2\src\Compilers\CSharp\Portable\CodeGen\EmitExpression.cs:line 2458
...
cc @stephentoub

**Comment by cston** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/46231.
