### ISSUE TITLE
AD0001: Analyzer 'Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer'

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#46345]
**Version Used**: VS Version 16.6.5

**Steps to Reproduce**:

I just did a rebuild. It happened only once.

Error:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer' threw an exception of type 'System.OperationCanceledException' with message 'The operation was canceled.'.	Liceus-XamlProject		1	Active	Analyzer 'Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer' threw the following exception:
'System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.ParseXmlDocument(Int32 elements)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.Parser.ParseXmlDocument()
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.CachingParser.ParseAndCacheResult(Parser parser, CachedParseResult resultContext, ITextSnapshot textSnapshot)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.CachingParser.GetOrParseXmlDocument(ITextSnapshot textSnapshot, IXmlParseContext parseContext, IMarkupSourceProvider sourceProvider, CancellationToken cancelToken, Parser parser)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.CreateXmlTree(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<>c__DisplayClass433_0.<GetXmlTreeAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<GetXamlTreeAsync>d__435.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XamlFileContext.<Microsoft-VisualStudio-DesignTools-Xaml-LanguageService-Semantics-IXamlFileInformationContext-GetMessagesAsync>d__385.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.DesignTools.Xaml.CodeAnalysis.Diagnostics.Analyzers.XamlDocumentAnalyzerService.<AnalyzeSyntaxAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Xaml.Diagnostics.Analyzers.XamlDocumentDiagnosticAnalyzer.<AnalyzeSyntaxAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.<ComputeDocumentDiagnosticAnalyzerDiagnosticsAsync>d__35.MoveNext()
-----
'.
```

**Comment by mgoertz-msft** [comment]
@tmat Are analyzers supposed to handle cancellation themselves?

**Comment by tmat** [comment]
@mavasani

**Comment by mavasani** [comment]
> Are analyzers supposed to handle cancellation themselves?

Can you check if the token for which the exception was unhandled is same as the token passed into the analyzer? Normally, the above unhandled operation canceled exception indicates that is not the case.

**Comment by mavasani** [comment]
@jinujoseph I believe this needs to be moved to XAML team to investigate if they are throwing a cancellation on a different token then the one that was provided to the analyzer on the callback. Our calls into the document diagnostic analyzer already handle cancellations on the same token in the `IsCanceled` method below to ensure we do not report AD0001 for that case:

https://github.com/dotnet/roslyn/blob/507c81a5146ba714f827b730cac2339605e22c12/src/Features/Core/Portable/Diagnostics/AnalyzerHelper.cs#L343-L377

**Comment by jinujoseph** [comment]
Routed to [xaml ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163699) team cc @mgoertz-msft
