### ISSUE TITLE
'CSharpDeclareAsNullableCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#46354]
**Version Used**: 

```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 5.0
VisualStudio.16.Preview/16.7.0-pre.5.0+30317.65
Microsoft .NET Framework
Version 4.8.03752
```

**Steps to Reproduce**:

Paste the following code in VS, expand the bulb while caret is on `null` in `t.Item1 = null;`
```
#nullable enable
class Program
{
  static void F1<T>((T, T?) t) where T : class
  {
    if (t.Item2 == null) return;
    t.Item1 = null;
    
    var (a, b) = t;
  }
}
```

**Expected Behavior**:
No exceptions I guess

**Actual Behavior**:
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.TryGetDeclarationTypeToFix(SemanticModel model,SyntaxNode node)
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by nstepanets** [comment]
Has this bug been fixed?

Microsoft Visual Studio Community 2022 (64-bit), Version 17.3.5:
`System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.TryGetDeclarationTypeToFix(SemanticModel model,SyntaxNode node)
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)`
