### ISSUE TITLE
NRE in RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46423]
**Version Used**: 

Version 16.8.0 Preview 2.0 [30327.8.master]

```
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: destination'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.EditorFeatures
SyntaxTree: C:\R3\src\EditorFeatures\Core\Shared\Extensions\TelemetryExtensions.cs
SyntaxNode: (short)(scope switch { FixAllScope ... [CastExpressionSyntax]@[1114..1321) (28,15)-(34,14)

System.ArgumentNullException: Value cannot be null.
Parameter name: destination
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.ClassifyConversion(Int32 position, ExpressionSyntax expression, ITypeSymbol destination, Boolean isExplicitInSource)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.CastMustBePreserved(ExpressionSyntax castNode, ExpressionSyntax castedExpressionNode, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsCastSafeToRemove(ExpressionSyntax castNode, ExpressionSyntax castedExpressionNode, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsUnnecessaryCast(ExpressionSyntax cast, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer.IsUnnecessaryCast(SemanticModel model, ExpressionSyntax cast, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer`2.TryRemoveCastExpression(SemanticModel model, TCastExpression node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer`2.AnalyzeSyntax(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__60`1.<ExecuteSyntaxNodeAction>b__60_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

```

The code referred to from the exception is

```C#
public static short GetScopeIdForTelemetry(this FixAllScope scope)
            => (short)(scope switch
            {
                FixAllScope.Document => 1,
                FixAllScope.Project => 2,
                FixAllScope.Solution => 3,
                _ => 4,
            });
```

**Comment by jnm2** [comment]
Same crash in 16.7-p6
