### ISSUE TITLE
Flaky tests due to illegal characters in path

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46480]
Various tests are failing due to this exception. Is it possible that a method we have for generating temporary paths occasionally produces a path with illegal characters? @jaredpar

Example builds:
https://dev.azure.com/dnceng/public/_build/results?buildId=753101&view=ms.vss-test-web.build-test-results-tab&runId=23359376&resultId=135420&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=753140&view=ms.vss-test-web.build-test-results-tab&runId=23361574&paneView=debug&resultId=133022

Xunit log:
```
    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.Bug781312(parseOptions: CSharpParseOptions { DocumentationMode = Parse, Errors = [], Features = [], Kind = Regular, Language = "C#", ... }) [STARTING]
      System.ArgumentException : Illegal characters in path.
      Stack Trace:
           at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
        /_/src/Test/Utilities/Portable/FX/ImmutableArrayTestExtensions.cs(27,0): at Microsoft.CodeAnalysis.Test.Utilities.ImmutableArrayTestExtensions.WriteToFile(ImmutableArray`1 bytes, String path)
        /_/src/Test/Utilities/Portable/Compilation/IRuntimeEnvironment.cs(331,0): at Roslyn.Test.Utilities.RuntimeEnvironmentUtilities.DumpAssemblyData(IEnumerable`1 modules, String& dumpDirectory)
        /_/src/Test/Utilities/Portable/Platform/Desktop/RuntimeAssemblyManager.cs(457,0): at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
           at Roslyn.Test.Utilities.Desktop.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError)
        /_/src/Test/Utilities/Portable/Platform/Desktop/DesktopRuntimeEnvironment.cs(297,0): at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Verify(Verification verification)
        /_/src/Test/Utilities/Portable/CompilationVerifier.cs(203,0): at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures)
        /_/src/Test/Utilities/Portable/CommonTestBase.cs(150,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify)
        /_/src/Test/Utilities/Portable/CommonTestBase.cs(64,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        /_/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs(826,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        /_/src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs(2541,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.Bug781312(CSharpParseOptions parseOptions)
    Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.Bug781312(parseOptions: CSharpParseOptions { DocumentationMode = Parse, Errors = [], Features = [], Kind = Regular, Language = "C#", ... }) [FINISHED] Time: 0.2181943s
```

**Comment by Youssef1313** [comment]
@RikkiGibson, I'm not sure if this is helpful or not. But could it be [this](https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Test/Utilities/Portable/Compilation/IRuntimeEnvironment.cs#L286) method for some reason?
