### ISSUE TITLE
System.Exception: Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind' crashed Visual Studio

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#46544]
https://dev.azure.com/dnceng/public/_build/results?buildId=753622&view=artifacts&type=publishedArtifacts

```
Message: System.Exception: Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonTraceListener.Exit(System.String)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean, System.String)
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(System.Object)
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind)
   at Roslyn.Utilities.ObjectReader.ReadStringValue()
   at Roslyn.Utilities.ObjectReader.ReadString()
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.ReadDiagnosticAnalysisResults(Roslyn.Utilities.ObjectReader, System.Collections.Generic.IDictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.VersionStamp, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner+<ReadCompilerAnalysisResultAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.ReadCompilerAnalysisResultAsync(System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner+<>c__DisplayClass11_0.<AnalyzeOutOfProcAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.RemoteEndPoint+<InvokeAsync>d__22`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by sharwell** [comment]
@jasonmalinowski I only saw a case where this crashed **devenv.exe**. Did you see a case where it crashed OOP?

**Comment by mavasani** [comment]
`DiagnosticResultSerializer.ReadDiagnosticAnalysisResults` should only be invoked in devenv.

**Comment by jasonmalinowski** [comment]
I probably misread it then.

**Comment by mavasani** [comment]
@jasonmalinowski @sharwell either of you have a pointer to a dump with the above stack? Its hard to root cause this without a dump..

**Comment by sharwell** [comment]
@mavasani I don't have a dump. The error did not occur during the build linked above, but rather during a previous build on the same machine.

**Comment by mavasani** [comment]
Alright, not sure I can make much headway here without a dump. I will wait for another failure with dump.

**Comment by sharwell** [comment]
Looks like **devenv.exe.1232.dmp** has the information in https://dev.azure.com/dnceng/public/_build/results?buildId=753620.
