### ISSUE TITLE
'ExtractMethodCodeRefactoringProvider' encountered an error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46561]
I don't have a clear repro steps, just happened to me and couldn't repro again.

Here is the StackTrace:

```
System.ArgumentException : Wrong number of type arguments
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct(ImmutableArray`1 typeArguments,Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamedTypeSymbol.Microsoft.CodeAnalysis.INamedTypeSymbol.Construct(ITypeSymbol[] typeArguments)
   at Microsoft.CodeAnalysis.SymbolKey.ErrorTypeSymbolKey.Resolve(SymbolKeyReader reader)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadWorker(SymbolKeyType type)
   at Microsoft.CodeAnalysis.SymbolKey.SymbolKeyReader.ReadSymbolKey()
   at Microsoft.CodeAnalysis.SymbolKey.ResolveString(String symbolKey,Compilation compilation,Boolean ignoreAssemblyKey,Boolean resolveLocations,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.Extensions.ResolveType[T](SemanticModel semanticModel,T symbol)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.AnalyzerResult..ctor(SemanticDocument document,IEnumerable`1 typeParametersInDeclaration,IEnumerable`1 typeParametersInConstraintList,IList`1 variables,VariableInfo variableToUseAsReturnValue,ITypeSymbol returnType,Boolean awaitTaskReturn,Boolean instanceMemberIsUsed,Boolean shouldBeReadOnly,Boolean endOfSelectionReachable,OperationStatus status)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/46357
