### ISSUE TITLE
Restore misses .tools\msbuild\16.6.5-alpha1\tools\MSBuild\Current\Bin\msbuild.exe

### ISSUE THREAD

**Issue by 7enderhead** [dotnet/roslyn#46584]
**Version Used**: forked from Master, commit  81c5d71a65daa74343241b3ad9c25b6fc372096e 

**Steps to Reproduce**:

1. run Restore.cmd (or build.ps1 -restore) on Windows 10

**Expected Behavior**:
- restore runs through

**Actual Behavior**:
```
$ Restore.cmd
Tool 'dotnet-format' (version '4.0.130203') was restored. Available commands: dotnet-format
Tool 'powershell' (version '7.0.0') was restored. Available commands: pwsh

Restore was successful.
Roslyn.sln:
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
System.Management.Automation.MethodInvocationException: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified" ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at Exec-Process, C:\src\roslyn\eng\common\tools.ps1: line 79
at MSBuild-Core, C:\src\roslyn\eng\common\tools.ps1: line 593
at InitializeToolset, C:\src\roslyn\eng\common\tools.ps1: line 510
at BuildSolution, C:\src\roslyn\eng\build.ps1: line 213
at <ScriptBlock>, C:\src\roslyn\eng\build.ps1: line 670
at <ScriptBlock>, <No file>: line 1
```

- Debugging with `Write-Host "command: $($command), args: $($commandArgs)"` at tools.ps1 prior to line 79 shows that it is tried to invoke `.tools\msbuild\16.6.5-alpha1\tools\MSBuild\Current\Bin\msbuild.exe`, which does not exist.
- Instead, the folder only contains `RoslynTools.MSBuild.16.6.5-alpha1.nupkg`:
```
$ ls .tools\msbuild\16.6.5-alpha1\
RoslynTools.MSBuild.16.6.5-alpha1.nupkg
```

**Comment by 7enderhead** [comment]
- tried to unpack the nupkg manually, was reported to be invalid archive
- re-downloaded and extracted manually -> now works as expected
- interestingly, no error messages in previous restore steps hinted at the impossibility to unpack the nupkg
