### ISSUE TITLE
CSharpDeclareAsNullableCodeFixProvider threw "ArgumentException" on foreach declaration

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46802]
**Version Used**: 
Version 16.8.0 Preview 2.0 [30404.163.master]

**Steps to Reproduce**:

CTRL+. below where indicated by the $

``` C#
#nullable enable

        [Fact]
        public void AllRulesMustBeExported()
        {
            foreach ($var rule in GetRules(suffix: null, recursive: true))
            {

            }
        }

        protected static IEnumerable<string> GetRules(string suffix, bool recursive = false)
        {
        }
```

```
System.ArgumentException : The node is not part of the tree.
Parameter name: node
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.CheckNodeInOriginalTreeOrTracked(SyntaxNode node)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceNode(SyntaxNode node,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.MakeDeclarationNullable(SyntaxEditor editor,SemanticModel model,SyntaxNode node,HashSet`1 alreadyHandled)
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.FixAllAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by davkean** [comment]
If I remove `: null` from the argument of `suffix`, then this no longer crashes.

**Comment by jinujoseph** [comment]
also reported [here ](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1438081)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44604  verified:

![image](https://user-images.githubusercontent.com/4564579/153944528-c4021f6c-8d20-470a-8e38-f48392f7c843.png)
