### ISSUE TITLE
Assertion failed in VBCSCompiler on Linux in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46835]
https://dev.azure.com/dnceng/public/_build/results?buildId=769229&view=results

```
Process terminated. Assertion failed.
   at Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.ListenAndDispatchConnections(Nullable`1 keepAlive, CancellationToken cancellationToken) in /_/src/Compilers/Server/VBCSCompiler/ServerDispatcher.cs:line 84
   at Microsoft.CodeAnalysis.CompilerServer.BuildServerController.RunServer(String pipeName, ICompilerServerHost compilerServerHost, IClientConnectionHost clientConnectionHost, IDiagnosticListener listener, Nullable`1 keepAlive, CancellationToken cancellationToken) in /_/src/Compilers/Server/VBCSCompiler/BuildServerController.cs:line 143
   at Microsoft.CodeAnalysis.CompilerServer.BuildServerController.CreateAndRunServer(String pipeName, ICompilerServerHost compilerServerHost, IClientConnectionHost clientConnectionHost, IDiagnosticListener listener, Nullable`1 keepAlive, NameValueCollection appSettings, CancellationToken cancellationToken) in /_/src/Compilers/Server/VBCSCompiler/BuildServerController.cs:line 159
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.ServerUtil.<>c__DisplayClass8_0.<CreateServer>b__0() in /_/src/Compilers/Server/VBCSCompilerTests/ServerUtil.cs:line 127
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by RikkiGibson** [comment]
If the test passes after a rerun please add the Flaky label so we can track test reliability issues in our queries.

**Comment by JoeRobich** [comment]
Closing as it appears the assert was removed by https://github.com/dotnet/roslyn/pull/47133
