### ISSUE TITLE
csc.exe exited with code -2146232797 build error using switch expressions in VS 16.7.1

### ISSUE THREAD

**Issue by antoniovalentini** [dotnet/roslyn#46877]
**Version Used**: .NET Core 3.1.401 with Visual Studio Professional 2019 v16.7.1

**Steps to Reproduce**:

1. Create a Class Library project (.NET Standard 2.1)
2. Create a class
3. Paste the following code in the class and Build

```C#
using System;

namespace VsBug.Domain
{
    public class MyClass
    {
        public void Something()
        {
            var first = new First();
            var second = new Second();
            var identifyResult = (first.Status, second.Status) switch
            {
                (SomeEnum.NotFound, SomeEnum.Found) => DoSomething(),
                (SomeEnum.Found, SomeEnum.NotFound) => DoSomething(),
                (SomeEnum.Found, SomeEnum.Found) => DoSomething(),
                (_, SomeEnum.Error) => DoSomething(), // TODO: the bad line
                (SomeEnum.Error, _) => DoSomething(),
                _ => throw new ArgumentOutOfRangeException()
            };
        }

        private Result DoSomething()
        {
            return new Result();
        }
    }

    public class First
    {
        public SomeEnum Status { get; set; }
    }

    public class Second
    {
        public SomeEnum Status { get; set; }
    }

    public class Result
    {

    }

    public enum SomeEnum
    {
        NotFound,
        Found,
        Error
    }
}
```

Here's my .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
```

**Expected Behavior**: Successful build.

**Actual Behavior**: Build error => MSB6006 | "csc.exe" exited with code -2146232797. | VsBug.Domain | C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets | Line 70	

**Temporary solution**: Comment out or remove the line marked with "*TODO (the bad line)*" and rebuild

**Comment by jcouv** [comment]
Repro'ed this and captured a stack trace for the NRE:

```
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.BasicBlock.ShortenBranches(Int32& delta) in /_/src/Compilers/Core/Portable/CodeGen/BasicBlock.cs:line 346
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.ComputeOffsetsAndAdjustBranches() in /_/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs:line 829
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks() in /_/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs:line 859
   at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize() in /_/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs:line 195
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() in /_/src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs:line 290
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans, AsyncForwardEntryPoint entryPointOpt) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1478
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1237
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 506
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 396
```
