### ISSUE TITLE
RemoteHostService crashes with "Serialized session is not valid" opening a solution

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46895]
**Version Used**: 
Version 16.8.0 Preview 3.0 [30417.263.main]

**Steps to Reproduce**:

1.  Opened a solution, i used http://github.com/dotnet/project-system

```
    StreamJsonRpc.RemoteInvocationException : Serialized session is not valid
Parameter name: serializedSession
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync(<Unknown Parameters>)
---> (Remote Exception) {
  "type": "System.ArgumentException",
  "message": "Serialized session is not valid\r\nParameter name: serializedSession",
  "stack": "   at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.Parse(String serializedSession)\r\n   at Microsoft.CodeAnalysis.Remote.RemoteHostService.<>c__DisplayClass7_0.<InitializeTelemetrySession>b__0()\r\n   at Microsoft.CodeAnalysis.Remote.ServiceBase.RunService(Action call, CancellationToken cancellationToken)\r\n   at Microsoft.CodeAnalysis.Remote.RemoteHostService.InitializeTelemetrySession(String host, String serializedSession, CancellationToken cancellationToken)",
  "code": -2147024809,
  "inner": null
} <---
```

**Comment by davkean** [comment]
I also get the following at the same time, but it forces to me start VS in logging mode to actually see its error.

![image](https://user-images.githubusercontent.com/1103906/90473662-cb2f2600-e166-11ea-9ee5-4943323a2f27.png)

**Comment by sharwell** [comment]
```
Serialized session is not valid
Parameter name: serializedSession
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.Parse(String serializedSession)
   at Microsoft.CodeAnalysis.Remote.RemoteHostService.<>c__DisplayClass7_0.<InitializeTelemetrySession>b__0()
   at Microsoft.CodeAnalysis.Remote.ServiceBase.RunService(Action call, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.RemoteHostService.InitializeTelemetrySession(String host, String serializedSession, CancellationToken cancellationToken)
```

**Comment by sharwell** [comment]
@tmat Looks like potentially caused by #45588

**Comment by tmat** [comment]
I think the issue is that the LSP uses RemoteHostClient before Roslyn package is loaded, which initializes the telemetry session. Looking into it.
