### ISSUE TITLE
Squiggles.ErrorTagGeneratedForSimpleError flaky test

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#46931]
Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorTagGeneratedForSimpleError

Merge PR: https://github.com/dotnet/roslyn/pull/46913
Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=776388&view=ms.vss-test-web.build-test-results-tab&runId=24280238&resultId=180776&paneView=debug

Stack trace:
```
Assert.Equal() Failure\r\nExpected: 1\r\nActual:   0
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.VB$StateMachine_2_ErrorTagGeneratedForSimpleError.MoveNext() in /_/src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
This is the same as #46786
