### ISSUE TITLE
Invalid IL generated when compiling valid C# code

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4695]
Description: Compile and run the following code: 

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace ConsoleApplication17 {
	class Program {
		public sealed class Cache {
			private abstract class BucketwiseBase<TArg> where TArg: class {
				internal abstract void Default(TArg arg);
			}

			private class BucketwiseBase<TAccumulator, TArg> : BucketwiseBase<TArg> where TArg: class {
				internal override void Default(TArg arg = null) {
					throw new Exception("THIS IS NEVER THROWN");
				}
			}

			public void GetAll() {
				new BucketwiseBase<object, object>().Default(); // Bad image format thrown here. 
				//new BucketwiseBase<object, object>().Default(null); // This will run 
				throw new Exception("TEST"); // THIS IS NEVER THROWN 
			}
		}

		static void Main(string[] args) {
			Cache c = new Cache();
			c.GetAll();
		}
	}
}
```

You will see the generated IL is invalid: 

```
.method public hidebysig instance void GetAll() cil managed 
{ 
// Code size 32 (0x20) 
.maxstack 2 
.locals init ([0] !1 CS$0$0000) 
IL_0000: nop 
IL_0001: newobj instance void class ConsoleApplication17.Program/Cache/BucketwiseBase1`2<object,object>::.ctor() 
IL_0006: ldloca.s CS$0$0000 
IL_0008: initobj !1 
IL_000e: ldloc.0 
IL_000f: callvirt instance void class ConsoleApplication17.Program/Cache/BucketwiseBase`1<object>::Default(!0) 
IL_0014: nop 
IL_0015: ldstr "TEST" 
IL_001a: newobj instance void [mscorlib]System.Exception::.ctor(string) 
IL_001f: throw 
} // end of method Cache::GetAll 
```

When running a BadImageFormat exception is thrown 

Impact:It took a long time to find.

[Migrated from TFS/DevDiv 1212260]

**Comment by leppie** [comment]
Can't repro. PEVerify fine. 
```
Unhandled Exception: System.Exception: THIS IS NEVER THROWN
   at ConsoleApplication17.Program.Cache.BucketwiseBase`2.Default(TArg arg)
   at ConsoleApplication17.Program.Cache.GetAll()
   at ConsoleApplication17.Program.Main(String[] args)
```
IL output:
```
.method public hidebysig instance void  GetAll() cil managed
{
  // Code size       24 (0x18)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  newobj     instance void class ConsoleApplication17.Program/Cache/BucketwiseBase`2<object,object>::.ctor()
  IL_0006:  ldnull
  IL_0007:  callvirt   instance void class ConsoleApplication17.Program/Cache/BucketwiseBase`1<object>::Default(!0)
  IL_000c:  nop
  IL_000d:  ldstr      "TEST"
  IL_0012:  newobj     instance void [mscorlib]System.Exception::.ctor(string)
  IL_0017:  throw
} // end of method Cache::GetAll
```

**Comment by gafter** [comment]
Hm. I suspect this is a bug in the legacy compiler.

**Comment by leppie** [comment]
@gafter: You are correct, fails with version 4.6.0079.0

**Comment by TyOverby** [comment]
Issue closed?

**Comment by jaredpar** [comment]
Looks like a native compiler bug.  We need to add a test case to ensure we don't regress this behavior but won't be fixing the actual behavior in the native compiler.

**Comment by leppie** [comment]
Agreed that there should be a test case. PEVerify will catch this.
