### ISSUE TITLE
FailFast in IncrementallyParse when try to edit some invalid code.

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#46958]
**Version Used**: 
VS16.8.0 preview1(and also for old versions)

**Steps to Reproduce**:
1. Edit the below code in vs;
```cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace TestNs
{
	public class TestClass
	{
		private readonly Dictionary<int, int> dic = new Dictionary<int, int>();
		public abstract void Test1();
		{
				if (dic.TryGetValue(1, out var res))
				{
					return res;
				}
				return 0;
		}

		//public abstract Task Test2(int x);//NullReferenceException

		//public abstract Task Test3();//IndexOutOfRangeException
	}
}
```
2. Uncomment Test2 or Test3;
3. Remove and readd `;` or '//' at the end of the line;

**Expected Behavior**:
Not crash(still invalid code, and get error).

**Actual Behavior**:
Get one of the below stacktrace, or random strange semantic color.
```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParameterList(SyntaxToken& open, SeparatedSyntaxListBuilder`1 nodes, SyntaxToken& close, SyntaxKind openKind, SyntaxKind closeKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedParameterList()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatementCore(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__24.MoveNext()
```
------
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.FetchCurrentToken()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSimpleName(NameOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAliasQualifiedName(NameOptions allowedParts)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseQualifiedName(NameOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseUnderlyingType(ParseTypeMode mode, NameOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeCore(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseType(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTupleElement()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTupleType()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseUnderlyingType(ParseTypeMode mode, NameOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeCore(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseType(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTupleElement()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTupleType()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseUnderlyingType(ParseTypeMode mode, NameOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeCore(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseType(ParseTypeMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParameter()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParameterList(SyntaxToken& open, SeparatedSyntaxListBuilder`1 nodes, SyntaxToken& close, SyntaxKind openKind, SyntaxKind closeKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedParameterList()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatementCore(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__24.MoveNext()
```
------
```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.<>c.<SkipBadParameterListTokens>b__127_0(LanguageParser p)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.SkipBadTokensWithExpectedKind(Func`2 isNotExpectedFunction, Func`2 abortFunction, SyntaxKind expected, GreenNode& trailingTrivia)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.SkipBadSeparatedListTokensWithExpectedKind[T,TNode](T& startToken, SeparatedSyntaxListBuilder`1 list, Func`2 isNotExpectedFunction, Func`2 abortFunction, SyntaxKind expected)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.SkipBadParameterListTokens(SyntaxToken& open, SeparatedSyntaxListBuilder`1 list, SyntaxKind expected, SyntaxKind closeKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParameterList(SyntaxToken& open, SeparatedSyntaxListBuilder`1 nodes, SyntaxToken& close, SyntaxKind openKind, SyntaxKind closeKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedParameterList()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatementCore(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__24.MoveNext()
```
---
```cs
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineNumberFromPosition(Int32 position)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromPosition(Int32 position)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.GetLinePosition(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLinePosition(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SourceLocation.GetLineSpan()
   at Microsoft.VisualStudio.LanguageServices.Implementation.Diagnostics.VisualStudioVenusSpanMappingService.GetAdjustedDiagnosticSpan(DocumentId documentId, Location location, TextSpan& sourceSpan, FileLinePositionSpan& originalLineInfo, FileLinePositionSpan& mappedLineInfo)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.GetLocationInfo(TextDocument document, Location location, TextSpan& sourceSpan, FileLinePositionSpan& originalLineInfo, FileLinePositionSpan& mappedLineInfo)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.CreateLocation(TextDocument document, Location location)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, TextDocument document)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerHelper.<ConvertToLocalDiagnostics>d__34.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Roslyn.Utilities.ImmutableArrayExtensions.ToImmutableArrayOrEmpty[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.<ComputeDocumentAnalysisDataAsync>d__48.MoveNext()
```
------
```cs
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<TryClassifyContainingMemberSpanAsync>d__1.MoveNext()
```
------
```cs
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position, Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position, Func`2 stepInto)
   at Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(Int32 position, Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.Editor.Implementation.Highlighting.AbstractKeywordHighlighter.AddTouchingTokens(SyntaxNode root, Int32 position, List`1 tokens, Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.Editor.Implementation.Highlighting.AbstractKeywordHighlighter.AddHighlights(SyntaxNode root, Int32 position, List`1 highlights, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Highlighting.HighlightingService.AddHighlights(SyntaxNode root, Int32 position, List`1 highlights, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Highlighting.HighlighterViewTaggerProvider.<ProduceTagsAsync>d__10.MoveNext()
```
------

**Comment by CyrusNajmabadi** [comment]
I cannot repro this at all on D18.
