### ISSUE TITLE
Versions of shared dlls that are shipped in the analyzers must be incremented every update

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46984]
We upgraded our analyzers here: https://github.com/dotnet/project-system/pull/6502, which caused a bunch of analyzer crashes:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderDiagnosticAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper' threw an exception.'.
Exception occurred with following context:
Compilation: Microsoft.VisualStudio.AppDesigner
SyntaxTree: C:\project-system\src\Microsoft.VisualStudio.AppDesigner\PropPages\PropertyListener.vb

System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper' threw an exception. ---> System.TypeLoadException: Method 'get_CloseBraceToken' in type 'Microsoft.CodeAnalysis.VisualBasic.LanguageServices.VisualBasicSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.VisualBasic.CodeStyle, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper..ctor()
   at Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderDiagnosticAnalyzer.get_FileHeaderHelper()
   at Microsoft.CodeAnalysis.FileHeaders.AbstractFileHeaderDiagnosticAnalyzer.HandleSyntaxTree(SyntaxTreeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSyntaxTreeActionsCore>b__59_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.TypeLoadException: Method 'get_CloseBraceToken' in type 'Microsoft.CodeAnalysis.VisualBasic.LanguageServices.VisualBasicSyntaxKinds' from assembly 'Microsoft.CodeAnalysis.VisualBasic.CodeStyle, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper..ctor()
   at Microsoft.CodeAnalysis.VisualBasic.FileHeaders.VisualBasicFileHeaderHelper..cctor()
-----

Suppress the following diagnostics to disable this analyzer: IDE0073, IDE0073WithoutSuggestion	Microsoft.VisualStudio.AppDesigner		1	Active

```

This is because Microsoft.CodeAnalysis.CSharp.CodeStyle and Microsoft.CodeAnalysis.VisualBasic.CodeStyle ship the same assembly; Microsoft.CodeAnalysis.CodeStyle with the same assembly name and version but different contents. This causes the compiler to load one version of this assembly, and share it between these two different packages. Shared binaries must be bumped every version so that NuGet packages are self-contained.

**Comment by mavasani** [comment]
Tagging @sharwell @jmarolf we need to fix this before shipping the assemblies inside the .NET SDK
