### ISSUE TITLE
SolutionServiceTests.TestDocument is failing intermittently

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#46996]
Over the past 3 days, this test has failed 22 times. Failures started with the build of this commit: https://github.com/dotnet/roslyn/commit/05b8f2d4f627ae4756b0a99ca0fad853e101baef. @tmat, I'm going to send a PR to disable this test.

**Comment by 333fred** [comment]
First failing run: https://dev.azure.com/dnceng/public/_build/results?buildId=775467&view=results.

Error Message:
```
System.TimeoutException : Failed to clean up listeners in a timely manner.
  WorkItem WorkCoordinator.LowPriorityProcessor.cs 98
---- System.OperationCanceledException : The operation was canceled.
```

Stack:
```
   at Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.DisposeExportProvider(ExportProvider exportProvider) in /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:line 155
   at Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest) in /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:line 87
----- Inner Stack Trace -----
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcherNoResult(Task task, CancellationToken cancellationToken) in /_/src/Workspaces/CoreTestUtilities/TaskJoinExtensions.cs:line 62
   at Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcher(Task task, CancellationToken cancellationToken) in /_/src/Workspaces/CoreTestUtilities/TaskJoinExtensions.cs:line 25
   at Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.DisposeExportProvider(ExportProvider exportProvider) in /_/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:line 104
```

**Comment by tmat** [comment]
@sharwell @mavasani

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/46997 will disable.
