### ISSUE TITLE
'InlineTemporaryCodeRefactoringProvider' encountered an error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47058]
**Version Used**: Microsoft Visual Studio 16.7.2

**Steps to Reproduce**:

I was scrolling over ~~`Binder_Statements_Tests.vb`~~ `Parser.vb`, not sure what exactly happened. So I don't have clear repro steps. However, the stack trace should give an insight on what happened.

**Expected Behavior**:

No crash

**Actual Behavior**:

```
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.VB$StateMachine_4_GetReferencesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.VB$StateMachine_3_ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
