### ISSUE TITLE
📝 In the first round of testing, the macOS_Test leg failed with this assertion:

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47061]
📝 In the first round of testing, the macOS_Test leg failed with this assertion:

https://github.com/dotnet/roslyn/blob/4320650d051420a90e940f147dfab6011d039f5f/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs#L226

```
Process terminated. Assertion failed.
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.VerifyNewEntryForPendingMemberSymbolsMap(ISymbol symbol, HashSet`1 dependentSymbols) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs:line 226
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass14_0.<GetSymbolAnalysisScopeAsync>g__getSymbolAnalysisScopeCore|2() in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs:line 160
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass14_0.<GetSymbolAnalysisScopeAsync>b__1() in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs:line 140
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The assertion did not produce a test failure according to CI because we do not currently hook up a trace listener, so the default handler calls `FailFast`.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/47055#issuecomment-678607624_

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/47410
