### ISSUE TITLE
Flaky test - SendSingleLineSubmissionToInteractive

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#47123]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=787056&view=ms.vss-test-web.build-test-results-tab&runId=24806144&resultId=100579&paneView=debug

Error message:
```
System.Exception : Unable to find expected content in REPL within 10000 milliseconds and no exceptions were thrown. Actual content:\r\n[[Microsoft (R) Visual C# Interactive Compiler version 3.8.0-ci ()\r\nLoading context from 'CSharpInteractive.rsp'.\r\nType "#help" for more information.\r\n> #reset 64\r\nResetting execution engine.\r\n]]
```

Stack trace:
```
Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 getValue, Func`2 isExpectedValue) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 234
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForReplPrompt() in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 199
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.Reset(Boolean waitForPrompt) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 166
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.Reset(Boolean waitForPrompt)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.Reset(Boolean waitForPrompt) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/InteractiveWindow_OutOfProc.cs:line 67
   at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest.ClearInteractiveWindow() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractInteractiveWindowTest.cs:line 29
   at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest.<InitializeAsync>d__1.MoveNext() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractInteractiveWindowTest.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.<InitializeAsync>d__2.MoveNext() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpSendToInteractive.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/59d8cd7c8d872e35edf45e65fb20c38f5d0c3ffd/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs#L28

Can just increasing the timeout a little bit fixes the problem?

**Comment by Youssef1313** [comment]
I think this was fixed in https://github.com/dotnet/roslyn/pull/52453. @sharwell Can you confirm and close?

**Comment by JoeRobich** [comment]
Closing as this test is currently passing
