### ISSUE TITLE
Flaky test - DiagnosticsClassificationTaggerProviderTests.Test_FadingSpans

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#47185]
Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=789701&view=ms.vss-test-web.build-test-results-tab&runId=24915754&resultId=162982&paneView=debug
PR: https://github.com/dotnet/roslyn/pull/47177/checks?check_run_id=1035019716

Maybe related to #46950?

Error message:
```
Assert.Equal() Failure\r\nExpected: 2\r\nActual:   0
```

Stack trace:
```
  at Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticsClassificationTaggerProviderTests.<Test_FadingSpans>d__0.MoveNext() in /_/src/EditorFeatures/Test/Diagnostics/DiagnosticsClassificationTaggerProviderTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
@allisonchou the build above is an older branch than the fix for #46950. I believe this one is already fixed.
