### ISSUE TITLE
IncrementallyParse fails for certain text changes

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#47234]
**Version Used**: 16.8 IntPreview 3

**Steps to Reproduce**:

🔗 [AB#1180669](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1180669)
🔗 [AB#1193786](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1193786)
🔗 [AB#1216814](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1216814)
🔗 [AB#1217030](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1217030)
🔗 [AB#1217491](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1217491)
🔗 [AB#1220119](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1220119)
🔗 [AB#1221787](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1221787)

1. Create a Xunit test project(.NET core)
2. Add test property and priority label to the method

```
[Fact]
        [Trait("cat", "TA")]
 
        [Trait("cat", "TB")]
        public void Test4()
        {
 
        }
[Fact]
        [Trait("cat", "TA")]
      
        public void Test6()
        {
 
        }
 
        [Fact]
       
        [Trait("cat", "TB")]
        public void Test2()
        {
 
        }
 
        [Fact]
        [Trait("cat", "TA")]
        [Trait("cat", "TB")]
        public void Test34()
        {
 
        }
```

**Notes**:

This seems similar to #39258, but occurs in a much newer build.

**Actual Behavior**:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: start
 at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)
 at Microsoft.CodeAnalysis.Text.ChangedText.Merge(ImmutableArray`1 oldChanges, ImmutableArray`1 newChanges)
 at Microsoft.CodeAnalysis.Text.ChangedText.Merge(IReadOnlyList`1 changeSets)
 at Microsoft.CodeAnalysis.Text.ChangedText.GetChangeRanges(SourceText oldText)
 at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
 at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__48.MoveNext()
 at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetRequiredSyntaxTreeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Document.<GetSyntaxRootAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Remote.RemoteDocumentDifferenceService.<GetDifferenceAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.<EnqueueWorkItemAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.<EnqueueWorkItemAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.<EnqueueWorkItemAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetRequiredSemanticModelAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsInCurrentProcessAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<>c__DisplayClass35_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Remote.ServiceBase.<RunServiceAsync>d__18`1.MoveNext()
```

**Comment by RikkiGibson** [comment]
Is it possible the failing scenario is related to https://github.com/dotnet/roslyn/pull/39258#discussion_r336746816?

**Comment by CyrusNajmabadi** [comment]
Quite possibly.  Note: i'm not sure why this is assigned to me.  Does compiler want to look at this, as i would expect this API to fall under the SourceText API.

**Comment by RikkiGibson** [comment]
I think I can only repro this when using 64-bit OOP..are there instructions on how to debug in that scenario? @sharwell

**Comment by IraJain09** [comment]
@sharwell  there is a change in exception here:-
![MicrosoftTeams-image](https://user-images.githubusercontent.com/49509107/94414660-37f00400-019a-11eb-904e-39f4ae4a10bb.png)

**Comment by sharwell** [comment]
@IraJain09 The `ConnectionLostException` message that appears for the "Show Stack Trace" command isn't the underlying issue here. For each of the issues marked as duplicates of this one, we found separate evidence that the original error was likely to be the stack trace shown at the top. We're working to make it much easier for both users and people working on the project to find the right issue by just looking at the stack trace window, but we're not quite there yet.

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson @jaredpar this is a pretty critical issue that is impacting lots of scenarios.  Can it be prioritized or load balanced?

**Comment by jaredpar** [comment]
@CyrusNajmabadi we're looking into it. Would help if we could get some responses to @RikkiGibson earlier question:

> I think I can only repro this when using 64-bit OOP..are there instructions on how to debug in that scenario?

**Comment by CyrusNajmabadi** [comment]
>I think I can only repro this when using 64-bit OOP..are there instructions on how to debug in that scenario?

Basically, just attach debugger to:

![image](https://user-images.githubusercontent.com/4564579/95244190-7c952400-07c6-11eb-9e7f-9174caa87e2b.png)

attach to teh one that use less ram.  The big one is the OOP server for Roslyn.sln itself :)

**Comment by RikkiGibson** [comment]
I was unable to set or hit breakpoints when using this method. Could you please confirm whether you are able to set and hit breakpoints when debugging using this method?

Steps I performed:

1. Open Roslyn.sln
2. "Start Without Debugging" on RoslynDeployment project
3. Find the two ServiceHub.RoslynCodeAnalysisService.exe processes in Task Manager, find the PID for the one that uses less memory
4. Use "Attach to Process" in VS on the RoslynCodeAnalysisService process using less memory
5. Set a breakpoint on a source file in Microsoft.CodeAnalysis project

![image](https://user-images.githubusercontent.com/5833655/95246736-c5021100-07c9-11eb-9734-7bb9a928f90a.png)

Screenshot of the Modules view when debugging:

![image](https://user-images.githubusercontent.com/5833655/95246881-faa6fa00-07c9-11eb-8b0c-a120db3bad03.png)

**Comment by tmat** [comment]
Memory dump can be found in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1179103

**Comment by RikkiGibson** [comment]
> Could you please confirm whether you are able to set and hit breakpoints when debugging using this method?

Please let me know about [this](https://github.com/dotnet/roslyn/issues/47234#issuecomment-704482322) when you have the chance--it would be great to know where things may be going wrong in my setup to make debugging issues that show up in the IDE more easily. @CyrusNajmabadi @tmat

**Comment by tmat** [comment]
@RikkiGibson It doesn't seem like you are debugger the bits built on your machine since those wouldn't be GAC'd.

When I want to be sure the build deploys to RoslynDev hive I do following:
1) delete `C:\Users\{user}\AppData\Local\Microsoft\VisualStudio\16.0_*RoslynDev`
2) `build -d` from command line
