### ISSUE TITLE
NRE in Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.MakeExplicitInterfaceImplementationMap

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47351]
I haven't had luck getting a repro with a debugger attached, but the I don't think the root cause is in the analyzer.

To repro, I've had to run `build.cmd`, touch src\System.Windows.Forms.Primitives\src\System.Windows.Forms.Primitives.csproj, then `build.cmd` again. If I just invoke dotnet.exe exec ...\csc.dll @args.txt, no luck for me. Nor with adding another analyzer just to add a Debugger.Launch().

The extra context in msbuild log from the repro is:

```
Errors
    CSC error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\dotnet\winforms\src\System.Windows.Forms.Primitives\src\System.Windows.Forms.Primitives.csproj]
Exception occurred with following context:
Compilation: System.Windows.Forms.Primitives
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol.get_ExplicitInterfaceImplementations()
at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.GetExplicitInterfaceImplementations(Symbol member)
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.MakeExplicitInterfaceImplementationMap()
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.GetExplicitImplementationForInterfaceMember(Symbol interfaceMember)
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationForInterfaceMember(Symbol interfaceMember, TypeSymbol implementingType, DiagnosticBag diagnostics, Boolean ignoreImplementationInInterfaces, Boolean& implementationInInterfacesMightChangeResult)
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.ComputeImplementationAndDiagnosticsForInterfaceMember(Symbol interfaceMember, Boolean ignoreImplementationInInterfaces, Boolean& implementationInInterfacesMightChangeResult)
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMemberInNonInterfaceWithDiagnostics(Symbol interfaceMember, Boolean ignoreImplementationInInterfacesIfResultIsNotReady)
at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.FindImplementationForInterfaceMember(Symbol interfaceMember)
at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeSymbol.Microsoft.CodeAnalysis.ITypeSymbol.FindImplementationForInterfaceMember(ISymbol interfaceMember)
at Analyzer.Utilities.Extensions.IMethodSymbolExtensions.IsImplementationOfInterfaceMethod(IMethodSymbol method, ITypeSymbol typeArgument, INamedTypeSymbol interfaceType, String interfaceMethodName)
at Analyzer.Utilities.Extensions.IMethodSymbolExtensions.IsDisposeImplementation(IMethodSymbol method, INamedTypeSymbol iDisposable)
at Microsoft.NetCore.Analyzers.Security.DoNotCallDangerousMethodsInDeserialization.<>c__DisplayClass8_0.<Initialize>b__2(CompilationAnalysisContext compilationAnalysisContext)
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationActionsCore>b__48_1(ValueTuple`2 data)
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
Suppress the following diagnostics to disable this analyzer: CA5360
```

_Originally posted by @dotpaul in https://github.com/dotnet/roslyn-analyzers/issues/4108#issuecomment-685180637_

**Comment by mavasani** [comment]
Tagging @RussKie
