### ISSUE TITLE
BadImageFormatException when running RoslynDeployment

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47485]
### Repro steps:

1. https://github.com/dotnet/roslyn/pull/47369/commits/7741c76af7549f0c2cffd90158a0637bf2d7a827 (Currently, the latest commit in my PR, https://github.com/dotnet/roslyn/pull/47369. My PR only adds an analyzer and codefix provider, so the changes seem to be unrelated to the exception, correct me if wrong please)
2. Open Roslyn.sln
3. F5 to run RoslynDeployment
4. Create new project
5. See exception:

   ![image](https://user-images.githubusercontent.com/31348972/92300892-000cec80-ef5f-11ea-8213-eaadca0f22f4.png)

```
System.BadImageFormatException
  HResult=0x80131018
  Message=Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The module was expected to contain an assembly manifest.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.<>c__DisplayClass17_0.<LoadAssembly>b__0(AssemblyName assemblyNameParam)
   at Microsoft.VisualStudio.ExtensibilityHosting.Utilities.SafeGetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Object lockObj, Func`2 valueFactory)
   at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.GetManifest(Resolver resolver, AssemblyName assemblyName)
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.TryUseFastReflection(TypeRef typeRef, Module& manifest)
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)
   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()
   at Microsoft.VisualStudio.Composition.Reflection.MemberRef.get_MemberInfo()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass71_1`2.<GetExports>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]() in C:\Users\Youssef1313\Desktop\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Workspace\Core\Workspace\Mef\MefLanguageServices.cs:line 55
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService`2.PrimeLanguageServiceComponentsOnBackground() in C:\Users\Youssef1313\Desktop\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractLanguageService`2.cs:line 202
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService`2.<Setup>b__35_0() in C:\Users\Youssef1313\Desktop\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageService\AbstractLanguageService`2.cs:line 106
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass7_0.<CreateTaskBody>b__0(IVsTask task, IVsTask[] parents)
   at Microsoft.VisualStudio.Shell.VsManagedTaskBody.DoWork(IVsTask pTask, UInt32 dwCount, IVsTask[] pParentTasks, Object& pResult)
   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass118_0.<GetCallbackForMultipleParent>b__0(Task`1[] _)
```

Clicking "Continue" keeps showing other few exceptions in other several places.

**Comment by sharwell** [comment]
@Youssef1313 did you at any point run with `-testCI` from the command line?

**Comment by Youssef1313** [comment]
@sharwell I dont even know about the testVsi option :smile:
Only ran Build.cmd and Test.cmd before. I'll try again to see if it still reproduces or not and respond back.

**Comment by Youssef1313** [comment]
@sharwell I couldn't repro again. I think this doesn't require any action/investigation. Hence, closing.
