### ISSUE TITLE
BclMathCall integration test is flaky

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#47562]
https://dev.azure.com/dnceng/public/_build/results?buildId=806327&view=ms.vss-test-web.build-test-results-tab&runId=25554508&resultId=100463&paneView=history

There seem to be multiple failures.

```
System.Exception : Unable to find expected content in REPL within 10000 milliseconds and no exceptions were thrown. Actual content:\r\n[[Microsoft (R) Visual C# Interactive Compiler version 3.8.0-ci ()\r\nLoading context from 'CSharpInteractive.rsp'.\r\nType "#help" for more information.\r\n> #reset 64\r\nResetting execution engine.\r\n]]
```
([link](https://dev.azure.com/dnceng/public/_build/results?buildId=806327&view=ms.vss-test-web.build-test-results-tab&runId=25554508&resultId=100463&paneView=debug))
and

```
System.AggregateException : One or more errors occurred.\r\n---- System.Runtime.InteropServices.COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.
```
([link](https://dev.azure.com/dnceng/public/_build/results?buildId=806663&view=ms.vss-test-web.build-test-results-tab&runId=25570170&resultId=100463&paneView=debug))

**Comment by sharwell** [comment]
```
Failed to launch 'c:\users\sam\appdata\local\microsoft\visualstudio\16.0_80a394a5roslyndev\extensions\microsoft\roslyn language services\42.42.42.4242424\InteractiveHost\Desktop\InteractiveHost64.exe' process (exit code: 1) with output: 
System.IO.FileLoadException: Could not load file or assembly 'StreamJsonRpc, Version=2.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'StreamJsonRpc, Version=2.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<RunServerAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.RunServerAsync(String pipeName, Int32 clientProcessId, Func`2 invokeOnMainThread)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.RunServerAsync(String[] args, Func`2 invokeOnMainThread) in C:\dev\roslyn\src\Interactive\Host\Interactive\Core\InteractiveHost.Service.cs:line 220
   at Microsoft.CodeAnalysis.Interactive.InteractiveHostEntryPoint.<Main>d__0.MoveNext() in C:\dev\roslyn\src\Interactive\HostProcess\InteractiveHostEntryPoint.cs:line 46
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by Youssef1313** [comment]
@sharwell Is this related to this exception? or it's something else in my case?

![image](https://user-images.githubusercontent.com/31348972/93608734-459fcf80-f9cb-11ea-9ce8-167c10dfca3c.png)
