### ISSUE TITLE
IOException setting Console.OutputEncoding

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#47571]
**Version Used**: 20760c9123e7734d338f6f21071782b612bd45ae

**Steps to Reproduce**:

Run dotnet/roslyn integration tests.

**Actual Behavior**:

```
Failed to launch 'c:\users\sam\appdata\local\microsoft\visualstudio\16.0_80a394a5roslyndev\extensions\microsoft\roslyn language services\42.42.42.4242424\InteractiveHost\Desktop\InteractiveHost64.exe' process (exit code: 1) with output: 
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_OutputEncoding(Encoding value)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service..ctor(Func`2 invokeOnMainThread) in C:\dev\roslyn\src\Interactive\Host\Interactive\Core\InteractiveHost.Service.cs:line 143
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<RunServerAsync>d__18.MoveNext() in C:\dev\roslyn\src\Interactive\Host\Interactive\Core\InteractiveHost.Service.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Interactive.InteractiveHostEntryPoint.<Main>d__0.MoveNext() in C:\dev\roslyn\src\Interactive\HostProcess\InteractiveHostEntryPoint.cs:line 46
```

**Comment by tmat** [comment]
Related: https://github.com/dotnet/runtime/issues/43295
