### ISSUE TITLE
Invalid IL is emitted for Records(method PrintMembers) which contains an Indexer

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#47672]
**Version Used**: 
master? (I can only see `PrintMembers` in sharplab, and not in 5.0.0-preview8)

**Steps to Reproduce**:
See `PrintMembers`
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKAHYRhxQAOEAxnAAQoYB0ASgK54wCWRdAwgPZglsANogDKiAG5tKUAN7oqASSgBRAB7wEBQQrxsYMgL4HcCOOR4IAJlQAaACjasqqgJS4ZuKl5oBmKo5gqGAALNigAbQCqAGs4AE8AXSoAXgA+KgAGAG5cAyA
```cs
record X(int x)
{
    public int this[int key] => 0;
}
```

**Expected Behavior**:
Ignore the indexer.

**Actual Behavior**:
`InvalidProgramException: Common Language Runtime detected an invalid program.` when executed.

-----
And NullReferenceException for property without getter;
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKAHYRhxQAOEAxnAAQoYB0ASgK54wCWRdAwgPZglsANogDKiAG5tKUAN7oqASSgBRAB7wEBQQrxsYMgL4HcCOOR4IAJlQAaACjasqqgJS4ZuKl5oBmKo5hbGxsqGSooOEDDKmMcAyA
```cs
record X(int x)
{
    public int XXX { set {} }
}
```
```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.Call(BoundExpression receiver, MethodSymbol method, ImmutableArray`1 args) in /_/src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs:line 738
   at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.Call(BoundExpression receiver, MethodSymbol method) in /_/src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs:line 713
   at Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedRecordPrintMembers.GenerateMethodBody(TypeCompilationState compilationState, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs:line 167
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 884
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 506
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 402
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /_/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 143
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 311
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 203
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2949
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2563
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2519
```

**Comment by RikkiGibson** [comment]
fyi @jcouv

**Comment by miloush** [comment]
Why was this closed?

**Comment by RikkiGibson** [comment]
Sorry, I must have hit the wrong button.

**Comment by jcouv** [comment]
Thanks for reporting this @yyjdelete ! Fix is in progress
