### ISSUE TITLE
Assert in latest internal preview

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#47724]
Version: Version 16.8.0 Preview 4.0 [30515.30.main]

```
We should only be called by the incremental analyzer once the solution is fully loaded.
   at Microsoft.VisualStudio.LanguageServices.Implementation.SemanticClassificationCache.SemanticClassificationCacheIncrementalAnalyzerProvider.SemanticClassificationCacheIncrementalAnalyzer.<AnalyzeDocumentAsync>d__0.MoveNext() in C:\source\dotnet\roslyn\src\VisualStudio\Core\Def\Implementation\SemanticClassificationCache\SemanticClassificationCacheIncrementalAnalyzerProvider.cs:line 65
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioWorkspaceStatusServiceFactory.Service.<IsFullyLoadedAsync>d__8.MoveNext() in C:\source\dotnet\roslyn\src\VisualStudio\Core\Def\Implementation\Workspace\VisualStudioWorkspaceStatusServiceFactory.cs:line 121
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioWorkspaceStatusServiceFactory.Service.<GetProgressStageStatusAsync>d__9.MoveNext() in C:\source\dotnet\roslyn\src\VisualStudio\Core\Def\Implementation\Workspace\VisualStudioWorkspaceStatusServiceFactory.cs:line 129
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__7`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

@mavasani could this be realated to anything you've changed recently?

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/47338. I believe this is a new assert that @CyrusNajmabadi added recently. It is somewhat benign, but indicates some unnecessary work at solution load time.

**Comment by jmarolf** [comment]
dupe looks correct
