### ISSUE TITLE
ExtractMethodCodeRefactoringProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47783]
StackTrace:

```
System.ArgumentNullException : Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source,Func`2 predicate)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.Normalize(IEnumerable`1 data)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.AnalyzeReadWrite()
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicDataFlowAnalysis.get_Captured()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(Boolean bestEffort,SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap,IDictionary`2& variableInfoMap,List`1& failedVariables)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Unfortunately, I don't have a clear repro steps. It just happened while I was editing a VB file and I cannot repro again.

**Comment by akhera99** [comment]
No repro, closed.
