### ISSUE TITLE
Assertion failed in CSharpCompilation.FindEntryPoint when opening ASP.NET MVC project

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#47858]
**Version Used**: 
Version 16.8.0 Preview 4.0 [30514.8.main]

**Steps to Reproduce**:

Create a new ASP.NET MVC project in VS.

**Expected Behavior**:

**Actual Behavior**:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.FindEntryPoint(MethodSymbol simpleProgramEntryPointSymbol, CancellationToken cancellationToken, ImmutableArray`1& sealedDiagnostics) in C:\R2\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1829

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPointAndDiagnostics(CancellationToken cancellationToken) in C:\R2\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1616

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPoint(CancellationToken cancellationToken) in C:\R2\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1579

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetEntryPoint(CancellationToken cancellationToken) in C:\R2\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 3529

   at Microsoft.CodeAnalysis.Compilation.GetEntryPoint(CancellationToken cancellationToken) in C:\R2\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 832

   at Microsoft.WebTools.ProjectSystem.Web.Telemetry.WebProjectDetailsTelemetryCollector.GetStartupClass(Compilation comp)

   at Microsoft.WebTools.ProjectSystem.Web.Telemetry.WebProjectDetailsTelemetryCollector.PopulateStartupClassInfo(WebProjectDetailsEvent detailsEvent, Project project, Compilation comp)

   at Microsoft.WebTools.ProjectSystem.Web.Telemetry.WebProjectDetailsTelemetryCollector.<CollectDataAndPostTelemetryAsync>d__25.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)

   at Microsoft.WebTools.ProjectSystem.Web.Telemetry.WebProjectDetailsTelemetryCollector.<GetProjectAsync>d__38.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)

   at Microsoft.WebTools.Shared.VS.CodeGeneration.WorkspaceProvider.<GetWorkspaceAsync>d__3.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)

   at Microsoft.WebTools.Shared.VS.CodeGeneration.WorkspaceProvider.<EnsureWorkspaceInitializedAsync>d__4.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by RikkiGibson** [comment]
Tagging @333fred
