### ISSUE TITLE
CSharpImplementImplicitlyCodeRefactoringProvider crash

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#48027]
```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray)
   at async Microsoft.CodeAnalysis.CSharp.ImplementInterface.AbstractChangeImplementionCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

Repro code (try invoke codeactions at $$):
```cs
using System;
using System.Collections;


namespace Foo
{
    public class Bar
    {

        IEnumerator $IEnumerable$.GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}

```

**Comment by louis-z** [comment]
I'd like to work on this.

**Comment by genlu** [comment]
@louis-z Awesome, thanks! Please let me know if you have any questions :)

**Comment by louis-z** [comment]
No worries @genlu, it was easy to create a test that reproduces the problem. However, I'm thinking that since the code snippet you provided doesn't compile, CSharpImplementImplicitlyCodeRefactoringProvider should simply not report anything. Is that what you had in mind?
