### ISSUE TITLE
CSharpAddParameterCodeFixProvider crashes on activation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48042]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1196736/csharpaddparametercodefixprovider-crashes-on-activ.html)._

---
[severity:It's more difficult to complete my work]
Adding an optional parameter to a function, immediately after pressing Ctrl-'.' the `CSharpAddParameterCodeFixProvider` crashes.

Getting this stacktrace: 
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.InsertRange(Int32 index,IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertParameters(SyntaxNode declaration,Int32 index,IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditorExtensions.<>c__DisplayClass14_0.<InsertParameter>b__0(SyntaxNode d,SyntaxGenerator g)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.AddParameter.AddParameterService.AddParameterAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddParameter.AbstractAddParameterCodeFixProvider`6.FixAsync[TArgumentSyntax,TAttributeArgumentSyntax,TArgumentListSyntax,TAttributeArgumentListSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

---
#### Feedback Bot on 9/24/2020, 06:40 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.
#### Feedback Bot on 9/24/2020, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
Can't repro, have asked for more info on the feedback ticket.

**Comment by pasisavolainen** [comment]
copy from feedback ticket:

Hi, sorry this has taken some time.

I'm original submitter, corp changed organization name.

Below is my minimal repro. Add in `net5` project. Go to "param3" and press `Ctrl-.`, CSharpAddParameterCodeFixProvider will crash immediately.

Reproducible in `Version 16.8.0 Preview 6.0`.
```csharp
namespace r
{
    static class AbcExtensions
    {
        public static Abc Act(this Abc state, bool p = true) => state;
    }
    class Abc {
        void Test()
            => new Abc().Act(param3: 123);
    }
}
```

**Comment by davidwengier** [comment]
Thank you so much for the excellent repro @pasisavolainen
