### ISSUE TITLE
No hash-resistant equality comparer available for type: Microsoft.CodeAnalysis.DocumentId

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#48108]
**Version Used**: Version 16.9.0 Preview 1.0 [30527.11.main]

**Steps to Reproduce**:

1. Rename a method

**Stack Trace**

```
MessagePack.MessagePackSerializationException : Failed to deserialize Microsoft.CodeAnalysis.Rename.SerializableConflictResolution value. ---> System.TypeAccessException : No hash-resistant equality comparer available for type: Microsoft.CodeAnalysis.DocumentId
   at MessagePack.MessagePackSecurity.GetHashCollisionResistantEqualityComparer[T]()
   at MessagePack.MessagePackSecurity.GetEqualityComparer[T]()
   at Microsoft.CodeAnalysis.Remote.ImmutableCollectionMessagePackResolver.ImmutableDictionaryFormatter`2.Create(Int32 count,MessagePackSerializerOptions options)
   at MessagePack.Formatters.DictionaryFormatterBase`5.Deserialize(MessagePackReader& reader,MessagePackSerializerOptions options)
   at Deserialize(Object[] ,MessagePackReader& ,MessagePackSerializerOptions )
   at MessagePack.Internal.AnonymousSerializableFormatter`1.Deserialize(MessagePackReader& reader,MessagePackSerializerOptions options)
   at Deserialize(Object[] ,MessagePackReader& ,MessagePackSerializerOptions )
   at MessagePack.Internal.AnonymousSerializableFormatter`1.Deserialize(MessagePackReader& reader,MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader,MessagePackSerializerOptions options)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader,MessagePackSerializerOptions options)
   at lambda_method(Closure ,MessagePackReader& ,MessagePackSerializerOptions )
   at MessagePack.MessagePackSerializer.Deserialize(Type type,MessagePackReader& reader,MessagePackSerializerOptions options)
   at StreamJsonRpc.MessagePackFormatter.JsonRpcResult.SetExpectedResultType(Type resultType)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StreamJsonRpc.MessagePackFormatter.JsonRpcResult.GetResult[T]()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
```

FYI @tmat in case this is a duplicate or known. Searched for the exception message ¯\\\_(ツ)_/¯

**Comment by sharwell** [comment]
This is fixed by https://github.com/dotnet/roslyn/pull/47870/commits/a760513500eedcf0aa3f2cc2c3bcc983ed2d11ec
