### ISSUE TITLE
CSharpRemoveRedundantEqualityDiagnosticAnalyzer analyzer is failing with null-reference

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48236]
**Version Used**: 
Version 16.9.0 Preview 1.0 [30601.208.main]

We're seeing 10s of these across multiple code bases after updating to a recent build.

**Steps to Reproduce**:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveRedundantEquality.CSharpRemoveRedundantEqualityDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
IOperation: BinaryOperator
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Package\Nodes\Nesting\INestingProfilesSnapshotExtensions.cs
SyntaxNode: type == null [BinaryExpressionSyntax]@[721..733) (20,16)-(20,28)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.RemoveRedundantEquality.AbstractRemoveRedundantEqualityDiagnosticAnalyzer.AnalyzeBinaryOperator(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0100	Microsoft.VisualStudio.ProjectSystem.VS.Implementation		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveRedundantEquality.CSharpRemoveRedundantEqualityDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
IOperation: BinaryOperator
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Package\Nodes\Nesting\INestingProfilesSnapshotExtensions.cs
SyntaxNode: type == null [BinaryExpressionSyntax]@[721..733) (20,16)-(20,28)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.RemoveRedundantEquality.AbstractRemoveRedundantEqualityDiagnosticAnalyzer.AnalyzeBinaryOperator(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Expected Behavior**:

**Actual Behavior**:

**Comment by Youssef1313** [comment]
@davkean Are all of these errors in the **same** analyzer or **different** analyzers that all use IOperation?

**Comment by decriptor** [comment]
+1 this for us too
Version 16.9.0 Preview 1.0 [30601.220.main]

**Comment by davkean** [comment]
I thought this was a bunch, but you are right it's just CSharpRemoveRedundantEqualityDiagnosticAnalyzer.

**Comment by davidwengier** [comment]
I don't think this is in 16.8...

Its in [release/16.8](https://github.com/dotnet/roslyn/blob/release/16.8/src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs) but not [release/dev16.8](https://github.com/dotnet/roslyn/blob/release/16.8/src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs)

**Comment by Youssef1313** [comment]
> 
> 
> I don't think this is in 16.8...
> 
> Its in [release/16.8](https://github.com/dotnet/roslyn/blob/release/16.8/src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs) but not [release/dev16.8](https://github.com/dotnet/roslyn/blob/release/16.8/src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs)

Probably because https://github.com/dotnet/project-system/blob/b17cab2d0ffab5372e3fac6464d942576840c31e/build/import/Packages.targets#L33
