### ISSUE TITLE
Assertion failure in RemoveUnusedMembers.AbstractRemoveUnusedMembersDiagnosticAnalyzer`2

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48247]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at Microsoft.CodeAnalysis.RemoveUnusedMembers.AbstractRemoveUnusedMembersDiagnosticAnalyzer`2.CompilationAnalyzer.IsCandidateSymbol(ISymbol memberSymbol) in C:\R5\src\Analyzers\Core\Analyzers\RemoveUnusedMembers\AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs:line 593

   at Microsoft.CodeAnalysis.RemoveUnusedMembers.AbstractRemoveUnusedMembersDiagnosticAnalyzer`2.CompilationAnalyzer.GetCandidateSymbolsReferencedInDocComments(INamedTypeSymbol namedTypeSymbol, Compilation compilation, CancellationToken cancellationToken) in C:\R5\src\Analyzers\Core\Analyzers\RemoveUnusedMembers\AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs:line 523

   at Microsoft.CodeAnalysis.RemoveUnusedMembers.AbstractRemoveUnusedMembersDiagnosticAnalyzer`2.CompilationAnalyzer.OnSymbolEnd(SymbolAnalysisContext symbolEndContext, Boolean hasUnsupportedOperation) in C:\R5\src\Analyzers\Core\Analyzers\RemoveUnusedMembers\AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs:line 414

   at Microsoft.CodeAnalysis.RemoveUnusedMembers.Ab......

```

Dumps: `\\mlangfs1\public\tomat\Bugs\diagassert`

**Comment by Youssef1313** [comment]
I suspect the following line to be the problem:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs#L524

Nearly all the callers passes the symbol's original definition. So this line should probably have been:

```diff
- var symbol = lazyModel.GetSymbolInfo(node, cancellationToken).Symbol;
+ var symbol = lazyModel.GetSymbolInfo(node, cancellationToken).Symbol.OriginalDefinition;
```
