### ISSUE TITLE
Serialization error in AbstractDesignerAttributeIncrementalAnalyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#48271]
**Version Used**: #48263

🔗 https://dev.azure.com/dnceng/public/_build/results?buildId=840446

**Steps to Reproduce**:

Appeared in servicehub logs for integration tests.

**Actual Behavior**:

```
10/02/2020 23:10:32 Coordinated Universal Time: Error : 1 :[ServiceHub.RoslynCodeAnalysisService:6704] Unexpected exception: System.InvalidOperationException: Unexpected value 'ObjectRef_1Byte' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind kind) in /_/src/Compilers/Core/Portable/Serialization/ObjectReader.cs:line 402
   at Microsoft.CodeAnalysis.DesignerAttribute.AbstractDesignerAttributeIncrementalAnalyzer.TryReadPersistedInfo(ObjectReader reader) in /_/src/Features/Core/Portable/DesignerAttribute/AbstractDesignerAttributeIncrementalAnalyzer_Serialization.cs:line 26
```

**Comment by CyrusNajmabadi** [comment]
@sharwell @tmat i literally don't know what i woudl do about this.  We write 3 values like this:

```
            writer.WriteString(SerializationFormat);
            writer.WriteString(data.Category);
            projectVersion.WriteTo(writer);
```

and we read in 2 values like this:

```
                // type. If not, then we can't read this out.
                var format = reader.ReadString();
                if (format != SerializationFormat)
                    return default;

                // Looks good, pull out the stored data.
                var category = reader.ReadString();
                var projectVersion = VersionStamp.ReadFrom(reader);

                return (category, projectVersion);
```

If this is failing, then we have a serious issue with our ObjectReader/Writer subsystem :-/

**Comment by CyrusNajmabadi** [comment]
Closing out.  This code was entirely removed and subsumed moving to ISB+MessagePack.  i.e. we have no custom serialization here at all anymore
