### ISSUE TITLE
Incorrect compiler output for code involving async, loop, switch.

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/roslyn#4838]
I've spotted an issue with compilation output from VS 2015 Enterprise (RTM version).

The following code involving async, loop and switch constructs causes  ```ArgumentOutOfRangeException``` from ```default:``` branch when run, whereas a return from ```case 0:``` is expected. Apparently the compiler generates code without ```case 0:``` branch.

**Code**
```
using System;
using System.Threading.Tasks;

namespace ConsoleApplication11
{
    class Program
    {
        static void Main()
        {
            M(0).Wait();
        }

        static async Task M(int input)
        {
            for (;;)
            {
                var value = await Task.FromResult(input);
                switch (value)
                {
                    case 0:
                        return;
                    case 3:
                        return;
                    case 4:
                        continue;
                    case 100:
                        return;
                    default:
                        throw new ArgumentOutOfRangeException("Unknown value: " + value);
                }
            }
        }
    }
}
```

**Compile with optimizations**
```
D:\dev\bugs>"c:\Program Files (x86)\MSBuild\14.0\Bin\csc.exe" Program1.cs /o+
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Output**
```

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unknown value: 0
   at ConsoleApplication11.Program.<M>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ConsoleApplication11.Program.Main()
```

**Comment by jaredpar** [comment]
Thanks for reporting this!
