### ISSUE TITLE
Invalid compilation output for code involving async and switch

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/roslyn#4839]
I've spotted an issue with compilation output from VS 2015 Enterprise (RTM version).

The compiler generates invalid IL for the following code involving async and switch constructs.

**Code**
```
using System;
using System.Threading.Tasks;

namespace ConsoleApplication11
{
    class Program
    {
        static void Main()
        {
            M(0).Wait();
        }
 
        static async Task M(int input)
        {
            var value = await Task.FromResult(input);
            switch (value)
            {
                case 0:
                    return;
                case 1:
                    return;
            }
        }
    }
}
```

**Compile with optimizations**
```
D:\dev\bugs>"c:\Program Files (x86)\MSBuild\14.0\Bin\csc.exe" Program2.cs /o+
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Output**
```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ConsoleApplication11.Program.<M>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ConsoleApplication11.Program.M(Int32 input)
   at ConsoleApplication11.Program.Main()
```

**Comment by ArturDorochowicz** [comment]
I found this when trying to come up with a trimmed down repro for #4839 so they may be related.

**Comment by jaredpar** [comment]
Thanks for reporting this!  It does look like it could be related to #4838. Even if it is though, it's another test case :)

**Comment by ArturDorochowicz** [comment]
@jaredpar Yes, I intended to link to #4838 in my first comment, but incorrectly linked this item to itself. Corrected.
