### ISSUE TITLE
NullReferenceException when updating from 3.3.1 to 3.4.0

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#48470]
Getting:
```
   at Microsoft.CodeAnalysis.PooledObjects.PooledDelegates.FuncWithBoundArgument`3.<Bind>b__0_0(T1 arg1)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyArguments(Diagnostic diagnostic, Compilation compilationOpt, Func`2 isSupportedDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
```

When running unit tests using 3.4.0 to 3.8.0-3.final, works when using 3.3.1

**Comment by CyrusNajmabadi** [comment]
Can you give more of the callstack?

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell in case there's an issue with FuncWithBoundArgument itself.  It's not clear to me if the crash is inside that, or inside teh bound func that that is calling.

**Comment by sharwell** [comment]
This can occur if `SyntaxNodeAnalysisContext.ReportDiagnostic` is called after the syntax node callback returns. Can you show the analyzer code which led to this?
