### ISSUE TITLE
Visual Studio 2019 keeps restarting after exception in Inline Rename application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48537]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1114309/visual-studio-2019-keeps-restarting.html)._

---
[regression] [worked-in:VS 2019 Preview 3]
Visual Studio 2019 preview 4 keeps restarting after renaming multiple files/locations.

My solution has 40 projects and when I rename a file, which will rename the use everywhere restarted everytime the Visual Studio.

---
#### Feedback Bot on 7/15/2020, 11:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sunny Song [MSFT] on 7/16/2020, 02:53 AM: 

<p>Dear customer, Thanks for your feedback!<br>
We are investigating this issue now, but we cannot able reproduce the issue on VS 2019 Dev16.7 preview 4<br>
In order to help you solve the problem, could you please try the solution:</p>
<ol>
<li>Repair your VS then reopen your solution</li>
</ol>
<p>If this doesn’t solve your issue, please provide following information to us:</p>
<ol>
<li>Could you please provide the screenshot about the issue</li>
<li>The detailed reproduce steps for your issue</li>
<li>Please provide us the project that you met issue if convenient</li>
</ol>

#### Sunny Song [MSFT] on 7/26/2020, 08:02 PM: 

<p>Dear customer, we haven’t gotten your reply yet, does the issue still reproduce?</p>

#### Eddy Nakamura [MSFT] on 7/27/2020, 02:22 AM: 

<p>Hi Sunny, after the update (preview 4 to preview 5), continues restarting, but in a smaller amount.</p><p>What I saw so far: normally, when you are renaming a file, which will rename the class name as well and that class is used in many places (more than 30), it restarts. When I check VS after the restart, everything is updated.</p>
<a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/1114309/visual-studio-2019-keeps-restarting.html?childToView=1125937#"></a>

#### Feedback Bot on 7/27/2020, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/27/2020, 03:13 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
```
Event Time (UTC): 7/15/2020 1:16:19 AM
Event ID: 1026
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.EnsureEditableDocuments(System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.DocumentId>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentTextChanged(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(Microsoft.CodeAnalysis.ProjectChanges, Microsoft.CodeAnalysis.DocumentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(Microsoft.CodeAnalysis.ProjectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Shared.Utilities.IProgressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Shared.Utilities.IProgressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Microsoft.CodeAnalysis.Solution)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyRename(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.Editor.Host.IWaitContext)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(Microsoft.CodeAnalysis.Editor.Host.IWaitContext, Boolean)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession+<>c__DisplayClass78_0.<CommitWorker>b__0(Microsoft.CodeAnalysis.Editor.Host.IWaitContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(System.String, System.String, Boolean, Boolean, System.Action`1<Microsoft.CodeAnalysis.Editor.Host.IWaitContext>)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Commit()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Apply_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```
