### ISSUE TITLE
ArgumentOutOfRangeException from SymbolFinder.FindLinkedSymbolsAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48696]
**Version Used**: 
Version 16.9.0 Preview 1.0 [30613.262.main]

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
Actual value was StreamJsonRpc.MessagePackFormatter+RawMessagePack.
      at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindLinkedSymbolsAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_1.<<DetermineAllSymbolsCoreAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsCoreAsync>d__20.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsAsync>d__19.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetTagsForReferencedSymbolAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsInCurrentProcessAsync>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsAsync>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by tmat** [comment]
@CyrusNajmabadi FYI

**Comment by CyrusNajmabadi** [comment]
Tihs indicates OOP corruption in the solution snapshot.  Specifically, we walk through all linked files (which should have the same contents), looking for everything that is at the span of a symbol in the originating document.  If the linked files have different contents this would crash.  But this would also be bad given that the purpose of linked files is to have them all have the same contents.


@jasonmalinowski who may have more context on this.

**Comment by jasonmalinowski** [comment]
Do we have a dump?

**Comment by tmat** [comment]
In theory you should be able to find it in Watson (@ryzngard).

**Comment by ryzngard** [comment]
@tmat is this failure in the OOP process or devenv.exe?

**Comment by tmat** [comment]
OOP. Indicated by remote service entry point:
````
at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext()
```

**Comment by jasonmalinowski** [comment]
@tmat I don't see any Watson hits for you past 10/6. Can you provide the bucket/cab IDs from your machine's event log?

**Comment by tmat** [comment]
Report Id: d2df93f3-1418-4f56-881b-0597bd113ce6

**Comment by ryzngard** [comment]
[Link to cab](https://watsonportal.microsoft.com/CabAnalysis?CabIdentifier=https://weus2watcab01.blob.core.windows.net/global-202010/10072dd8-2119-4036-a08a-5eec02bb5712.zip)

Doesn't look like a dump was uploaded for that report

**Comment by jasonmalinowski** [comment]
Is the lack of dump expected in this case? Otherwise is there any other action left to take or do we need to close this?

**Comment by ryzngard** [comment]
Lack of dump can be for many reasons, but nonfatal by default should not collect dumps. The fact that it even had a watson report at all is suspect, since nonfatals are purely telemetry and don't go through watson unless requested. As far as I know we have no pending data collection on nonfatal. 

If there's not enough information in this bug, I would close it. I don't expect a dump to show up from this report.

**Comment by tmat** [comment]
@ryzngard Can we not request the dump? In general NFEs without memory dump are not very useful for investigation. It's nice to see things are failing but in order to do something about that we usually need a dump. I think we should 
1) Automatically request dumps for top hitting NFEs - as soon as we file a bug for NFE we should request dumps, so that at the time someone is actually trying to investigate they already have the info.
2) Force collection of the dump for internal users and show an info bar with a link to the dump file. This would allow dogfooders to file a bug and attach the dump right away.

**Comment by ryzngard** [comment]
For this instance, you can't request the dump. It was never collected. Requests happen and future instances collect dumps. 

Yes, we want to enable automatic dump request for top hitting NFE. That discussion is ongoing. 

>Force collection of the dump for internal users and show an info bar with a link to the dump file. This would allow dogfooders to file a bug and attach the dump right away.

I haven't focused on this, but maybe we could go ahead and do this. The downside here is that internal users will have the perf hit of every NFE collecting a dump, which isn't great. We have too many faults for this to be considered a rare case.

**Comment by jasonmalinowski** [comment]
> The downside here is that internal users will have the perf hit of every NFE collecting a dump

Sounds like a great stick for us to fix NFE!

**Comment by tmat** [comment]
> The downside here is that internal users will have the perf hit of every NFE collecting a dump

Yes, no pain no gain :)

**Comment by tmat** [comment]
We could have a switch to turn it off if it becomes a blocker, until a fix is deployed.

**Comment by jasonmalinowski** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1243024 against @ryzngard to track the change to enable dumps for NFWs; it's a task rather than a code change according to him. I'm going to close this report since there's nothing actionable at this point.
