### ISSUE TITLE
'VisualBasicAddExplicitCastCodeFixProvider' encountered an error and has been disabled. Show Stack Trace Enable Enable and ignore future errors 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48702]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1221923/visualbasicaddexplicitcastcodefixprovider-encounte.html)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Visual Studio 2019 Version 16.7.5]
Gets this all the time in VB.Net project
Running Visual Studio 2019 Version 16.7.6

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.ExpressionSyntaxExtensions.Cast(ExpressionSyntax expression,ITypeSymbol targetType,Boolean& isResultPredefinedCast)
   at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddExplicitCast.VisualBasicAddExplicitCastCodeFixProvider.ApplyFix(SyntaxNode currentRoot,ExpressionSyntax targetNode,ITypeSymbol conversionType)
   at Microsoft.CodeAnalysis.CodeFixes.AddExplicitCast.AbstractAddExplicitCastCodeFixProvider`1.<>c__DisplayClass15_0. <FixAllAsync>b__2(SemanticModel semanticModel,SyntaxNode currentRoot,TExpressionSyntax spanNode)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxEditorExtensions.<>c__DisplayClass2_0`1. <ApplyExpressionLevelSemanticEditsAsync>b__2(SemanticModel semanticModel,SyntaxNode currentRoot,TNode _,TNode node)
   at async Microsoft.CodeAnalysis.Shared.Extensions.SyntaxEditorExtensions.ApplySemanticEditsAsync[TType,TNode](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.AddExplicitCast.AbstractAddExplicitCastCodeFixProvider`1.FixAllAsync[TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 10/15/2020, 00:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Ronny Jakobsson on 10/15/2020, 00:28 AM: 

<p>I have discovered that this always happen when cast suggestion is CShort()</p>

#### Ronny Jakobsson on 10/15/2020, 01:23 AM: 

<p>System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.ExpressionSyntaxExtensions.Cast(ExpressionSyntax expression,ITypeSymbol targetType,Boolean& isResultPredefinedCast)
   at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddExplicitCast.VisualBasicAddExplicitCastCodeFixProvider.ApplyFix(SyntaxNode currentRoot,ExpressionSyntax targetNode,ITypeSymbol conversionType)
   at Microsoft.CodeAnalysis.CodeFixes.AddExplicitCast.AbstractAddExplicitCastCodeFixProvider`1.&lt;&gt;c__DisplayClass15_0.&lt;FixAllAsync&gt;b__2(SemanticModel semanticModel,SyntaxNode currentRoot,TExpressionSyntax spanNode)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxEditorExtensions.&lt;&gt;c__DisplayClass2_0`1.&lt;ApplyExpressionLevelSemanticEditsAsync&gt;b__2(SemanticModel semanticModel,SyntaxNode currentRoot,TNode _,TNode node)
   at async Microsoft.CodeAnalysis.Shared.Extensions.SyntaxEditorExtensions.ApplySemanticEditsAsync[TType,TNode](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.AddExplicitCast.AbstractAddExplicitCastCodeFixProvider`1.FixAllAsync[TExpressionSyntax](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.&lt;&gt;c__DisplayClass11_0.&lt;GetPreviewAsync&gt;b__0(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</p>

---
### Original Solutions
(no solutions)

**Comment by CodeAdze** [comment]
Could you please fix this, this feture is quite handy and it fails regularly.

**Comment by CyrusNajmabadi** [comment]
@CodeAdze can you supply is with a repro so we know when this is happening?  Thanks!

**Comment by CodeAdze** [comment]
Sure no problem.

   ```
 Public Sub PersistStateChangeBundle(persistBundle() As (ValuesType As Type,
                                                            Value As Object,
                                                            Source As SourceAttribute)) _
        Implements IStateRepositoryPersist.PersistStateChangeBundle

        Dim requiredProcessors As Dictionary(Of Mediums, Task) = (
                From medium As Mediums In [Enum].GetValues(GetType(Mediums))
                Let bundleForMedium = (From stateChange In persistBundle
                                       Where stateChange.Source.Medium = medium
                                       Select stateChange).ToArray()
                Select New With {Key .Medium = medium,
                                 Key .Task = New Task(Function() MediumBundleProcessors(medium).
                                                                    ProcessBundle(bundleForMedium))}).
                                                                        ToDictionary(Function(ep) ep.Medium,
                                                                                     Function(ep) ep.Task)
```

While writing the above code Visual Studio puts a red squggly line under `As Mediums` (in the first line of the Linq expression), mousing over this error line displays a tool tip saying "BC30512: Option strict on disallows inplicit conversions from 'Object' to 'Mediums'. " and the QuickFix options button. Clicking the QuickFix options button (just to get the list of available QuickFixes) causes Visual Studio to display an error banner at the top of VS saying "VisualBasicAddExplicitCastCodeFixProvider' encountered an error and has been disabled."
I have uploaded a couple of screen shots and the code below is just some code so you can see everythine thats being referenced in the Linq expression.

```
Public Enum Mediums
    DB
    CONFIG
End Enum


<AttributeUsage(AttributeTargets.Property, AllowMultiple:=False, Inherited:=False)>
Public Class SourceAttribute
    Inherits Attribute

    Public Sub New(medium As Mediums, location As String, name As String, containingType As Type)
        Me.Medium = medium
        Me.Location = location
        Me.Name = name
        Me.ContainingType = containingType
    End Sub

    Public ReadOnly Medium As Mediums
    Public ReadOnly Location As String
    Public ReadOnly Name As String
    Public ReadOnly ContainingType As Type

```

![VS-Before-Error-Banner](https://github.com/dotnet/roslyn/assets/44961560/0ade4434-b4e8-4e5b-9dca-1ef076a6b836)
![VS-After-Clicking-QuickFix-](https://github.com/dotnet/roslyn/assets/44961560/1ae192fd-5e8c-4071-9a9d-543287a2c1fc)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in this area.
