### ISSUE TITLE
Missing Reference Microsoft.Build.Framework.IProjectElement

### ISSUE THREAD

**Issue by Heitzmann2000** [dotnet/roslyn#48788]
**Version Used**: 
3.7.0

**Steps to Reproduce**:

1. Created new project (Console with Framework 4.7.2) with solution (Named CodeChecker).
2. Added by Nuget :

- Microsoft.CodeAnalysis (Currently newest 3.7.0)
- Microsoft.CodeAnalysis.CSharp.Workspaces (Currently newest 3.7.0)

3. Added following in Main
`Solution s = MSBuildWorkspace.Create().OpenSolutionAsync("..\\..\\..\\CodeChecker.sln").Result`

**Expected Behavior**:
Returned solution can be used to analyse contained sourceCode

**Actual Behavior**:

```
System.AggregateException
  HResult=0x80131500
  Message=Mindestens ein Fehler ist aufgetreten.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CodeChecker.Program.Main(String[] args) in ......\CodeChecker\CodeChecker\Program.cs:line 15

Inner Exception 1:
TypeLoadException: Der Typ "Microsoft.Build.Framework.IProjectElement" in der Assembly "Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" konnte nicht geladen werden.
```

If I am wrong here, I say sorry. But please tell me then where i can report such problem.

**Comment by Heitzmann2000** [comment]
Is there any workaround ?

**Comment by Heitzmann2000** [comment]
Microsoft.CodeAnalysis (Currently newest 3.8.0)
    **Microsoft.CodeAnalysis.Workspaces.MSBuild** (Currently newest 3.8.0)

But get same error.

Does anyone know a workaround ?

**Comment by jmarolf** [comment]
This issue is "Which MSBuild should we use to load your project?" While it is possible for you to deploy all of msbuild (and its targets) to correctly load a project it is not recommended.  Instread you should use the msbuild locator class to tell you console app where to load these dlls from. This is provided in the console app project template for roslyn.

It is recommended to use the template that is provided.

1. ensure you have the roslyn SDK installed

![image](https://user-images.githubusercontent.com/9797472/101841552-f9ac8480-3afa-11eb-8f81-e14a80fa30f2.png)

2. Create a new project using the "Standalone Code Analysis Tool"

![image](https://user-images.githubusercontent.com/9797472/101841662-38dad580-3afb-11eb-8ac3-79bc90e29c9e.png)

For reference I would recommend your project file look like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <!-- Analyzers that help with using roslyn apis -->
  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" 
		PrivateAssets="all" 
		IncludeAssets="runtime;build;native;contentfiles;analyzers" />
  </ItemGroup>

  <!-- Recommended references -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.15-ge4e3fc36c9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.9.0-2.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="3.9.0-2.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.9.0-2.final" />
  </ItemGroup>

</Project>
```

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.MSBuild;
using Microsoft.CodeAnalysis.Text;

namespace SolutionLoader
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // Attempt to set the version of MSBuild.
            var visualStudioInstances = MSBuildLocator.QueryVisualStudioInstances().ToArray();
            var instance = visualStudioInstances.Length == 1
                // If there is only one instance of MSBuild on this machine, set that as the one to use.
                ? visualStudioInstances[0]
                // Handle selecting the version of MSBuild you want to use.
                : SelectVisualStudioInstance(visualStudioInstances);

            Console.WriteLine($"Using MSBuild at '{instance.MSBuildPath}' to load projects.");

            // NOTE: Be sure to register an instance with the MSBuildLocator 
            //       before calling MSBuildWorkspace.Create()
            //       otherwise, MSBuildWorkspace won't MEF compose.
            MSBuildLocator.RegisterInstance(instance);
            
            using (var workspace = MSBuildWorkspace.Create())
            {
                // Print message for WorkspaceFailed event to help diagnosing project load failures.
                workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);

                var solutionPath = args[0];
                Console.WriteLine($"Loading solution '{solutionPath}'");

                // Attach progress reporter so we print projects as they are loaded.
                var solution = await workspace.OpenSolutionAsync(solutionPath, new ConsoleProgressReporter());
                Console.WriteLine($"Finished loading solution '{solutionPath}'");

                // TODO: Do analysis on the projects in the loaded solution
            }
        }
        
        private static VisualStudioInstance SelectVisualStudioInstance(VisualStudioInstance[] visualStudioInstances)
        {
            Console.WriteLine("Multiple installs of MSBuild detected please select one:");
            for (int i = 0; i < visualStudioInstances.Length; i++)
            {
                Console.WriteLine($"Instance {i + 1}");
                Console.WriteLine($"    Name: {visualStudioInstances[i].Name}");
                Console.WriteLine($"    Version: {visualStudioInstances[i].Version}");
                Console.WriteLine($"    MSBuild Path: {visualStudioInstances[i].MSBuildPath}");
            }

            while (true)
            {
                var userResponse = Console.ReadLine();
                if (int.TryParse(userResponse, out int instanceNumber) &&
                    instanceNumber > 0 &&
                    instanceNumber <= visualStudioInstances.Length)
                {
                    return visualStudioInstances[instanceNumber - 1];
                }
                Console.WriteLine("Input not accepted, try again.");
            }
        }

        private class ConsoleProgressReporter : IProgress<ProjectLoadProgress>
        {
            public void Report(ProjectLoadProgress loadProgress)
            {
                var projectDisplay = Path.GetFileName(loadProgress.FilePath);
                if (loadProgress.TargetFramework != null)
                {
                    projectDisplay += $" ({loadProgress.TargetFramework})";
                }

                Console.WriteLine($"{loadProgress.Operation,-15} {loadProgress.ElapsedTime,-15:m\\:ss\\.fffffff} {projectDisplay}");
            }
        }
    }
}
```
