### ISSUE TITLE
IL trimming: can we fall back to non-trimmed publishing on failure?

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/roslyn#48873]
**Version Used**: 5.0.100-rc.2.20479.15

**Steps to Reproduce**:

1. Build a complex application
2. Try to publish it
3. Notice IL linker exception
4. Edit csproj to add  `<PublishTrimmed>false</PublishTrimmed>`
5. Never benefit from trimming again
6. Never actually remember that I had to set that flag
7. Wonder whether it couldn't just fall back to untrimmed publish when the linker crashes

**Expected Behavior**:

Well, ideally the IL trimming would work every time. I get that this is a really difficult thing and I'm okay with failures. Would it be possible to just perform a fallback to non-trimmed and display a giant warning? The end result the user wants from a `dotnet publish` is a published app. Ideally trimmed, yes, but that's sort of a nice-to-have on top, rather than a show-stopper. If there is such a failure, I either have to investigate (can take forever) or disable trimming (I guess that's the far more common action). What I actually would have wanted is a successful publish result, maybe with a warning that trimming didn't work.

**Actual Behavior**:

publish fails, and I have to add set `<PublishTrimmed>false</PublishTrimmed>`, which now permanently disables the benefit of trimmed publishing. I don't want to have to occasionally try whether it works now.

For reference, this is where it failed for me

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/home/runner/work/Blazor.Grids/Blazor.Grids/TestProject_ClientSide/TestProject_ClientSide.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasCustomAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.CustomAttributeSource.HasAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.HasLinkerAttribute[T](IMemberDefinition member)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Error: /home/runner/.dotnet/sdk/5.0.100-rc.2.20479.15/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/home/runner/work/Blazor.Grids/Blazor.Grids/TestProject_ClientSide/TestProject_ClientSide.csproj]
Error: Process completed with exit code 1.
```

**Comment by jaredpar** [comment]
@agocke IL trimming issue: should this move to runtime or SDK repo?

**Comment by agocke** [comment]
`mono/linker`. But we can't move issues across org.

@stefanloerwald I think this is just a crash in the linker. I'd rather just fix these things rather than hiding them. We recently made a change that may have addressed this problem. Do you think you could retry publishing with the latest .NET Core build and see if it reproduces?

**Comment by jaredpar** [comment]
Moved the issue to mono/linker (adhoc style) https://github.com/mono/linker/issues/1586
