### ISSUE TITLE
Intellisense does not work for generated code in VS 2015

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/roslyn#4893]
WCF Ria Services and its open source version Open Ria Services uses a custom build task to generated client side code. During compilation one or many code files are generated and added to the build output. 

The build integration works as expected when compiling the application, but it seems like intellisense most often fail to see the generated code, resulting in intellisense errors all over the code with not only missing intellisense but also incorrect indentation when editing the code.

The code generation hooks into the "CoreCompile" build target by adding itself to "CoreCompileDependsOn" but my guess is that it is not executed by VS2015 intellisense. 

Is this an intended change in behavior or a bug and could you please help in providing a solution?

The source can be found at http://openriaservices.codeplex.com/SourceControl/latest#OpenRiaServices.NuGet/OpenRiaServices.Client.CodeGen/build/OpenRiaServices.CodeGen.targets

To reproduce the error you can easily create a "Silverlight Business Application" (in vs 2012 and then open it in VS 2015). I have also prepared a simple example project in case it is needed, but the easiest way to reproduce is to just create the business application and then try to recompile

![build_output](https://cloud.githubusercontent.com/assets/3167509/9573647/fbe14eca-4fbe-11e5-98d4-1854f70c3844.PNG)

![intellisense_output](https://cloud.githubusercontent.com/assets/3167509/9573503/93857fa0-4fbd-11e5-86af-f7a8b939a83e.PNG)

**Comment by dsoltesz** [comment]
any update on this?

**Comment by Pilchie** [comment]
Based on some other investigations I've done, I suspect that the "design time build" that we run in order to populate IntelliSense is crashing in the `CreateOpenRiaClientFilesTask`.  You might be able to make it more resilient to this by adding `ContinueOnError=$(ContinueOnEror)` to the task invocation in your targets files.

Otherwise, I believe the error I was seeing before for regular RIA services was:

```
C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018: The "CreateRiaClientFilesTask" task failed unexpectedly.
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018: System.Web.HttpException (0x80004005): The configuration system has already been initialized. ---> System.InvalidOperationException: The configuration system has already been initialized.
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Configuration.ConfigurationManager.SetConfigurationSystem(IInternalConfigSystem configSystem, Boolean initComplete)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Configuration.Internal.InternalConfigSettingsFactory.System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem configSystem, Boolean initComplete)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Configuration.HttpConfigurationSystem.EnsureInit(IConfigMapPath configMapPath, Boolean listenToFileChanges, Boolean initComplete)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironmentAndReportErrors(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.ApplicationManager.GetAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.ApplicationManager.CreateObjectInternal(String appId, Type type, IApplicationHost appHost, Boolean failIfExists, HostingEnvironmentParameters hostingParameters)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Hosting.ApplicationManager.CreateObjectWithDefaultAppHostAndAppId(String physicalPath, VirtualPath virtualPath, Type type, Boolean failIfExists, HostingEnvironmentParameters hostingParameters, String& appId, IApplicationHost& appHost)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Compilation.ClientBuildManager.CreateHost()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Compilation.ClientBuildManager.EnsureHostCreated()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at System.Web.Compilation.ClientBuildManager.CreateObject(Type type, Boolean failIfExists)
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at Microsoft.ServiceModel.DomainServices.Tools.CreateRiaClientFilesTask.GenerateClientProxies()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at Microsoft.ServiceModel.DomainServices.Tools.CreateRiaClientFilesTask.ExecuteInternal()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at Microsoft.ServiceModel.DomainServices.Tools.RiaClientFilesTask.Execute()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Microsoft.Ria.Client.targets(303,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Perhaps a similar exception could be guarded against in the OpenRIA task?

**Comment by Pilchie** [comment]
BTW - you can see the results of the design time build to confirm that it's a similar exception by:

1. Starting a Developer Command Prompt
2. Deleting the .vs directory beside your project
3. Running `set TraceDesignTime=true`
4. Running `devenv`
5. Opening your project
6. Navigating to your temp directory and looking at the `<guid>designtime.log` files for the one that runs the "Compile" target.

**Comment by dsoltesz** [comment]
adding        ContinueOnError="true" to the CreateRiaClientFilesTask still doesn't allow intellisense to work/see the ria generated code..can someone provide an actual solution to this issue?

**Comment by Daniel-Svensson** [comment]
Thank you for the help, we think we now have a working solution for OpenRiaServices described in https://openriaservices.codeplex.com/workitem/78

It seems like the AppDomain trying to host the asp.net process from within intellisens was trying to initialize System.Configuration twice (both the .NET 2.0-3.5 and then the .Net 4.5 version). 
It might due to a change in how ClientBuildManager works or to a change in how the IntelliSense process runs (such as .net target runtime version).
