### ISSUE TITLE
C# Interactive: "#reset core" fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49016]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Interactive:-reset-core-fails/1236388?preview=true)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.9.30613.262.main]
In the C# interactive window, I cannot switch to .NET Core:

```
#reset core
Resetting execution engine.
Failed to launch 'c:\program files (x86)\microsoft visual studio\2019\main\common7\ide\commonextensions\microsoft\managedlanguages\vbcsharp\languageservices\InteractiveHost\Core\InteractiveHost64.exe' process (exit code: 1) with output: 
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at StreamJsonRpc.JsonMessageFormatter.. ctor(Encoding encoding)
   at StreamJsonRpc.JsonMessageFormatter.. ctor()
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.CreateRpc(Stream stream, Object incomingCallTarget)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.RunServerAsync(String pipeName, Int32 clientProcessId, Func`2 invokeOnMainThread)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHostEntryPoint.Main(String[] args)
```

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
We might be missing binding redirect.

**Comment by vsccarl** [comment]
We couldn't repro this in 16.9 Preview 5 or 31022.10.main.
