### ISSUE TITLE
VS 2019 crashes when trying to open ruleset file

### ISSUE THREAD

**Issue by gansvv** [dotnet/roslyn#49073]
**Version Used**: Visual Studio 2019 16.7.7

**Steps to Reproduce**:

1. Open attached StyleCop.Analyzers.RuleSet in VS.
2. Double-click or open the file via Solution Explorer.
3. It tries to bring up the RuleSet Editor and then crashes. Looks like a UI bug, here is the stack trace:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Value of '-244935' is not valid for 'SplitterDistance'. 'SplitterDistance' must be greater than 0.
Parameter name: SplitterDistance
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.LoadHelpPaneSizeString(String settings)
   at Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.LoadHelpPaneSettings()
   at Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.SplitterResized(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.SplitContainer.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    System.Windows.Forms.SplitContainer.SplitterDistance.set(int)
    Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.LoadHelpPaneSizeString(string)
    Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.LoadHelpPaneSettings()
    Microsoft.VisualStudio.CodeAnalysis.AdvancedRuleSetEdit.SplitterResized(object, System.EventArgs)
    System.Windows.Forms.Control.OnResize(System.EventArgs)
    System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
    System.Windows.Forms.Control.UpdateBounds(int, int, int, int, int, int)
    System.Windows.Forms.Control.UpdateBounds()
    System.Windows.Forms.Control.WmWindowPosChanged(ref System.Windows.Forms.Message)
    System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message)
    ...
    [Call Stack Truncated]
```

**Expected Behavior**: Open the ruleset file in RuleSet Editor in VS 2019.

**Actual Behavior**: VS crashes and has to be restarted. 
(Ruleset file can be opened via VS code, but not in RuleSet editor in VS 2019.)

Attached: The StyleCop.Analyzers.ruleset file (as zip because the ruleset file extensions is unsupported for upload here.).
[StyleCop.Analyzers.zip](https://github.com/dotnet/roslyn/files/5465528/StyleCop.Analyzers.zip)

**Comment by mavasani** [comment]
This should be fixed in 16.8.
