### ISSUE TITLE
Tab to insert new method for event handler crashed with top-level statements

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#49325]
**Version Used**: Compiler version: '3.9.0-1.20521.14 (182c1e33)'. Language version: 9.0.

**Steps to Reproduce**:

With the cursor at the location of `$$` below, type `+=`

```csharp
using System;

AppDomain.CurrentDomain.AssemblyResolve $$
```

Visual Studio will offer to create a method for event handler:

![image](https://user-images.githubusercontent.com/278957/98984136-68d88e00-24e7-11eb-9011-d1e19a4fd727.png)

Press tab to accept adding the new method.

**Expected Behavior**: A local function is created for the event handler.

**Actual Behavior**: A `NullReferenceException` is thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeGeneration.CodeGenerator.AddMethodDeclaration[TDeclarationNode](TDeclarationNode destination, IMethodSymbol method, Workspace workspace, CodeGenerationOptions options)
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.AddGeneratedHandlerMethodToSolution(SemanticDocument document, String eventHandlerMethodName, SyntaxAnnotation plusEqualsTokenAnnotation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.CreateSolutionWithEventHandler(Document document, String eventHandlerMethodName, Int32 position, Int32&amp; plusEqualTokenEndPosition, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.GenerateAndAddEventHandler(ITextView textView, ITextBuffer subjectBuffer, String eventHandlerMethodName, Action nextHandler, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.HandleTabWorker(ITextView textView, ITextBuffer subjectBuffer, Action nextHandler, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.ExecuteCommand(TabKeyCommandArgs args, Action nextHandler, CommandExecutionContext cotext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass14_1`1.&lt;ExecuteStartingAtIndex&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

------

Maybe related, but not quite the same: https://github.com/dotnet/roslyn/issues/44425 https://github.com/dotnet/roslyn/issues/44387 https://github.com/dotnet/roslyn/issues/43878

**Comment by CyrusNajmabadi** [comment]
@sharwell I believe you updated the code generation service to support adding members at the top level.  Did that go in?  Would it resolve this?  Thanks!

**Comment by Youssef1313** [comment]
@PathogenDavid I could reproduce the crash for a couple of times in 16.8.3. But suddenly I got another weird behavior in the same version with the same repro steps. I'm completely unsure what's happened. I hit the `=` key once, and it's written twice :smile: (Confirmed my keyboard is okay 😄 )

![repro](https://user-images.githubusercontent.com/31348972/105578470-1e964780-5d89-11eb-922f-ad164ddea62e.gif)

**Comment by Youssef1313** [comment]
Here is a GIF demonstrating how the behavior suddenly changed.

![How-it-happened gif](https://user-images.githubusercontent.com/31348972/105578827-9d8c7f80-5d8b-11eb-8b61-f698a87bb8b5.gif)

**Comment by Youssef1313** [comment]
The method causing the crash here is [AddMethodDeclaration](https://github.com/dotnet/roslyn/search?q=AddMethodDeclaration) which is currently only used by `EventHookupCommandHandler`. I think there is a room to completely remove this method, and rely on whatever other mechanism used for generation on top-level statements.

Tagging @sharwell @CyrusNajmabadi for more information about what are the alternatives.

**Comment by CyrusNajmabadi** [comment]
ICodeGenerationService may be something viable here.  I believe sam updated it to work with top level statements.

**Comment by PathogenDavid** [comment]
> I could reproduce the crash for a couple of times in 16.8.3. But suddenly I got another weird behavior in the same version with the same repro steps. I'm completely unsure what's happened. I hit the `=` key once, and it's written twice 😄

Whacky! It still crashes for me on both 16.8.4 and 16.9.0p3

> I think there is a room to completely remove this method, and rely on whatever other mechanism used for generation on top-level statements.

Not sure if this implies the feature going away completely, but for what it's worth I think the ideal solution is probably that it adds a local function instead. Otherwise the tab-to-add-handler feature just seems broken in top-level statements. Although admittedly wanting to create event handlers in top-level statements files probably isn't common.

**Comment by Youssef1313** [comment]
> Not sure if this implies the feature going away completely

Nope, I meant to discuss the implementation detail to make the feature work.

**Comment by Youssef1313** [comment]
> ICodeGenerationService may be something viable here. I believe sam updated it to work with top level statements.

@CyrusNajmabadi It's still broken, and fixing it is tracked by https://github.com/dotnet/roslyn/issues/44425

I believe @sharwell have fixed something else related but in the "Features" layer, not "Workspaces". That's why I was suggesting if there could be a way to rely on only one of the, which reduce maintainability cost.

**Comment by Youssef1313** [comment]
Test passed in #50726 :tada:

**Comment by Youssef1313** [comment]
Already fixed in https://github.com/dotnet/roslyn/pull/58475. @davidwengier Can you close?

**Comment by davidwengier** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/58475 and the weird double-equals thing is fixed in https://github.com/dotnet/roslyn/pull/58477

Thank you @PathogenDavid and @Youssef1313 for your contributions, even if I completely stole your thunder on Xmas Eve. You may refer to me as the grinch for the next 2 hours.
