### ISSUE TITLE
System.DllNotFoundException: "Unable to load DLL 'clr' or one of its dependencies" is thrown by MSBuildWorkspace on the re-addition of a metadata reference

### ISSUE THREAD

**Issue by SENya1990** [dotnet/roslyn#49463]
Hi,
I encountered a strange run-time error in Roslyn. I obtain a project's `MetadataRefence`, save it in a variable and remove it from the project, apply changes to the workspace and then add it back to the project. When I attempt to apply changes to the workspace a second time I receive a strange exception `System.DllNotFoundException: 'Unable to load DLL 'clr' or one of its dependencies: The specified module could not be found. `

**Version Used**: 
I use Roslyn 3.8.0 with .net core 3.1. Here are my nuget packages:
```
<ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.6" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.8.0" />
  </ItemGroup>
```

**Steps to Reproduce**:

1.  Prepare some demo project to load. In my case it is console application for .net framework 4.8. I also add a reference to a compiled dll of my second test project to it. The second test project is a DLL for .net framework 4.8.
2. Reproduce the situation I described above with the code similar to the following:
```csharp
const string projectPath = @"<path-to-the-demo-project>";

Project project = await workspace.OpenProjectAsync(projectPath);

// I rely on the fact that the first metadata reference corresponds to the second demo project's dll. 
// After all it is a synthetic code to reproduce the issue
MetadataReference metadataReference = project.MetadataReferences[0];  
project = project.RemoveMetadataReference(metadataReference);

workspace.TryApplyChanges(project.Solution);

project = workspace.CurrentSolution.GetProject(project.Id);           //Get an actual version of the project
project = project.AddMetadataReference(metadataReference);

workspace.TryApplyChanges(project.Solution);    //Here the exception is thrown
```

**Expected Behavior**:
The metadata reference is successfully returned to the project

**Actual Behavior**:
A weird exception is thrown:
```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'clr' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=Microsoft.CodeAnalysis.Workspaces.MSBuild
  StackTrace:
   at Microsoft.CodeAnalysis.GlobalAssemblyCacheLocation.GetCachePath(ASM_CACHE id, Byte* path, Int32& length)
   at Microsoft.CodeAnalysis.GlobalAssemblyCacheLocation.GetLocation(ASM_CACHE gacId)

```
Strangely this call stack is incomplete. Below is a screenshot of a more detailed stack in Visual Studio
![изображение](https://user-images.githubusercontent.com/7687400/99527065-41813580-29ad-11eb-8314-48547af23e25.png)

**Comment by jinujoseph** [comment]
cc @jmarolf

**Comment by brian-reichle** [comment]
When `GlobalAssemblyCacheLocation` pinvokes the [`GetCachePath` method in clr.dll](https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Compilers/Shared/GlobalAssemblyCacheHelpers/GlobalAssemblyCacheLocation.cs#L27), is it specifically referring to the clr.dll provided by .Net Framework? or is .Net Core expected to provide it's own clr.dll? The behaviour I have observed could be explained by logic being written for a .Net Framework environment and not being updated to run in a .Net Core environment.

**Comment by jasonmalinowski** [comment]
Leaving this open since I'd imagine we shouldn't be taking that path in the .NET Core case, but I'm not seeing an obvious place where that condition exists. I also can't explain why tests wouldn't be failling.
