### ISSUE TITLE
Compilers are unable to consume signatures that do not specify bounds for multi-dimensional arrays.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#4954]
```
class Program
{
    static void Main()
    {
        var t = new Test();
        t.Test3();
        t.Test4(new double[1,1]);

	t = new C();
        t.Test3();
        t.Test4(new double[1,1]);
    }
}

class C : Test
{
    public override double[,] Test3()
    {
        System.Console.WriteLine("Overriden3");
        return null;
    }
    public override void Test4(double[,] a)
    {
        System.Console.WriteLine("Overriden4");
    }
}
```

Compile code above by referencing a library with a type built from this IL:
```
.class public auto ansi beforefieldinit Test
       extends [mscorlib]System.Object
{
    .method public hidebysig specialname rtspecialname 
            instance void  .ctor() cil managed
    {
      // Code size       7 (0x7)
      .maxstack  1
      IL_0000:  ldarg.0
      IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
      IL_0006:  ret
    } // end of method Test1::.ctor

    .method public hidebysig newslot virtual 
            instance float64[,] Test3() cil managed
    {
      // Code size       11 (0xb)
      .maxstack  4
      IL_0000:  ldstr      "Test3"
      IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
      IL_0007:  ldc.i4.1
      IL_0008:  ldc.i4.1
      IL_0009:  newobj     instance void float64[,]::.ctor(int32,int32)
      IL_000a:  ret
    } // end of method Test::Test3

    .method public hidebysig newslot virtual 
            instance void Test4(float64[,] x) cil managed
    {
      // Code size       11 (0xb)
      .maxstack  2
      IL_0000:  ldstr      "Test4"
      IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
      IL_000a:  ret
    } // end of method Test::Test4
} // end of class Test
```

An executable produced by VS2015 compiler fails with the following errors:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Double[,] Test.Test3()'.
   at Program.Main()
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Test.Test4(Double[,])'.
   at Program.Main()
```

An executable produced by VS2013 compiler successfully calls the methods, but overriding methods aren't considered as valid overrides by CLR.

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
