### ISSUE TITLE
Record types error: ExtractInerfaceCodeRefactoringProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49739]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Record-types-error:-ExtractInerfaceCodeR/1272660)._

---
[severity:It's more difficult to complete my work]
## Description 
When I try to extract an interface from a `record`, it fails with the error _'ExtractInerfaceCodeRefactoringProvider' encountered an error and has been disabled_. This happens regardless of what properties/methods I select/deselect, and behaves the same if I choose _current file_ or _new file_. Still works as expected for `class` and `struct` declarations.

## Stack trace:

```stack
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ShiftTrivia(SyntaxNode root,SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AddBaseList(SyntaxNode declaration,BaseListSyntax baseList)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AddInterfaceType(SyntaxNode declaration,SyntaxNode interfaceType)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.GetSolutionWithOriginalTypeUpdatedAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToSameFileAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0. <InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 11/30/2020, 06:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I'm going to add a test showing this works.  If the OP can provide a repro case we can continue.
