### ISSUE TITLE
Crash opening Quick Info

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#49755]
**Version Used**: e9fd4dc7

**Steps to Reproduce**:

Not sure

**Expected Behavior**:

No crash

**Actual Behavior**:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.CodeAnalysis.Solution.CheckContainsDocument(Microsoft.CodeAnalysis.DocumentId)
   at Microsoft.CodeAnalysis.Solution.WithDocumentText(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.PreservationMode)
   at Microsoft.CodeAnalysis.Document.WithText(Microsoft.CodeAnalysis.Text.SourceText)
   at Microsoft.CodeAnalysis.Editor.QuickInfo.ContentControlService.CreateDisposableToolTip(Microsoft.CodeAnalysis.Document, Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.VisualStudio.Text.Span, System.Object)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter+DocumentSpanEntry.CreateDisposableToolTip(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter+DocumentSpanEntry.<TryCreateColumnContent>b__6_0()
   at Microsoft.CodeAnalysis.Editor.QuickInfo.ContentControlService+LazyToolTip.OnToolTipOpening(System.Object, System.Windows.Controls.ToolTipEventArgs)
   at System.Windows.Controls.ToolTipEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean)
   at System.Windows.Controls.PopupControlService+<>c__DisplayClass8_0.<InspectElementForToolTip>b__0(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by jasonmalinowski** [comment]
Scenario here is if you do a find references on a symbol defined from a source generator and you hover over the entry in the find references window, since we then screw up trying to make a preview for it. Fix is under way.
