### ISSUE TITLE
NullReferenceException from Microsoft.CodeAnalysis.CSharp.EditAndContinue.BreakpointSpans.CreateSpanForConstructorDeclaration

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#49779]
Seen in logs of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1247686

```
11/17/2020 10:27:10 W. Europe Standard Time: Error : 1 :[devenv:21156] Unexpected exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.BreakpointSpans.CreateSpanForConstructorDeclaration(ConstructorDeclarationSyntax constructorSyntax)
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.BreakpointSpans.TryCreateSpanForNode(SyntaxNode node, Int32 position)
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.BreakpointSpans.TryGetClosestBreakpointSpan(SyntaxNode root, Int32 position, TextSpan& span)
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.BreakpointSpans.TryGetBreakpointSpan(SyntaxTree tree, Int32 position, CancellationToken cancellationToken, TextSpan& breakpointSpan)
   at Microsoft.CodeAnalysis.CSharp.Debugging.CSharpBreakpointResolutionService.<ResolveBreakpointAsync>d__1.MoveNext()
```

**Comment by Youssef1313** [comment]
@tmat Are there any repro steps for this?

**Comment by tmat** [comment]
Unfortunately, no more info is available.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
