### ISSUE TITLE
Error from BasicDoNotUseVerbatimCrefsAnalyzer

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#4983]
'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.	BasicCodeAnalysis		1	Analyzer 'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw the following exception:
'System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.SyntaxTokenList.First()
   at Roslyn.Diagnostics.Analyzers.Documentation.DoNotUseVerbatimCrefsAnalyzer.ProcessAttribute(SyntaxNodeAnalysisContext context, SyntaxTokenList textTokens)
   at Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer.AnalyzeXmlAttribute(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by rchande** [comment]
Unfortunately, this appeared in my error list, so I have neither dump nor repro.

**Comment by jmarolf** [comment]
Moved to https://github.com/dotnet/roslyn-analyzers/issues/287 since that's where this code lives now.
