### ISSUE TITLE
'GenerateConstructorCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#49850]
**Version Used**: e9fd4dc7

**Steps to Reproduce**:

Add a parameter to a VB constructor?

**Expected Behavior**:

Code fix does not crash.

**Actual Behavior**:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol'.
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.ClassifyConversion(SemanticModel semanticModel,ExpressionSyntax expression,ITypeSymbol destination)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSemanticFactsService.ClassifyConversion(SemanticModel semanticModel,SyntaxNode expression,ITypeSymbol destination)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.GenerateConstructorHelpers.IsCompatible[TExpressionSyntax](ISemanticFactsService semanticFacts,SemanticModel semanticModel,IMethodSymbol constructor,ImmutableArray`1 expressions)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.GenerateConstructorHelpers.CanDelegateTo[TExpressionSyntax](SemanticDocument document,ImmutableArray`1 parameters,ImmutableArray`1 expressions,IMethodSymbol constructor)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.FindConstructorToDelegateTo(ImmutableArray`1 parameters,ImmutableArray`1 expressions,ImmutableArray`1 constructors,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.FindConstructorToDelegateTo(ImmutableArray`1 allParameters,ImmutableArray`1 allExpressions,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeDelegatedConstructor(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.GenerateAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.GenerateConstructorAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by jasonmalinowski** [comment]
Recently hit this too; fix incoming.
