### ISSUE TITLE
Unreachable code exception is thrown for incomplete With statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49904]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Structures-and-Multidimensional-Array/726880)._

---
[regression] [worked-in:Community Preview 16.2.0 (untested)]
What steps will reproduce the problem?
1.Create a structure
    Structure MyStruct
        Dim A As Integer
        Dim B As Integer
        Dim C As Integer
    End Structure
and create an array
Private MyArr(9, 3, 11) As MyStruct
2.
Trying to assign values
        Dim n, p, r As Integer
        For n = 0 To 9
            For p = 0 To 3
                For r = 0 To 11
                    With MyArr(n, error)
                        . A = n
                        . B = p
                        . C = r
                    End With
                Next
            Next
        Next
3.
As soon as I try to write , p  (after (n)) VS crashes
4.
The same problem apears in VS Community 16.2.4
Apparently this happens after upgrading both versions
Forcing the introdution (commenting the line, for example) and writing (n, p, r) and uncommenting the line, no error apears and the project is created

---
#### Feedback Bot on 9/9/2019, 03:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2019, 00:59 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/31/2019, 07:13 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Wenwen Fan [MSFT] on 12/1/2020, 00:57 AM: 

<p>Thank you for taking the time to log this issue! Verified on VS2019 build 16.8.2, we create a VB winform project with the code:</p>
<p>Public Class Form1<br>
Structure MyStruct<br>
Dim A As Integer</p>
<pre><code>    Dim B As Integer

    Dim C As Integer
End Structure

Private MyArr(9, 3, 11) As MyStruct

Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    Dim n, p, r As Integer
    For n = 0 To 9
        For p = 0 To 3
            For r = 0 To 11
                With MyArr(n, p, r)
                    .A = n
                    .B = p
                    .C = r
                End With
            Next
        Next
    Next
End Sub
</code></pre>
<p>End Class</p>
<p>When We write p after n, VS not crashed, and popup two errors bellow the menu bar:<br>
“IntroduceVariableCodeRefactoringProvider” encountered an error has been disabled.<br>
“VisualBasicAddAwaitCodeRefactoringProvider” encountered an error and has been disabled.<br>
Could you please have a try with the latest build, thank you.</p>

#### Feedback Bot on 12/8/2020, 07:33 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
```
       <Fact()>
        Public Sub Test()
            Dim compilation = CreateCompilation(
<compilation>
    <file name="c.vb">
Module Class

    Private MyArr(9, 3, 11) As MyStruct

    Sub Main()
        Dim n, p, r As Integer
        For n = 0 To 9
            For p = 0 To 3
                For r = 0 To 11
                    With MyArr(n, )
                        .A = n
                        .B = p
                        .C = r
                    End With
                Next
            Next
        Next
    End Sub

End Class

Structure MyStruct
    Dim A As Integer
    Dim B As Integer
    Dim C As Integer
End Structure
    </file>
</compilation>)

            compilation.AssertTheseEmitDiagnostics(
<expected>
</expected>)
        End Sub
```

Observed:
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.WithBlockErrorTests.Test [FAIL]
  System.InvalidOperationException : This program location is thought to be unreachable.
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Lowering\WithExpressionRewriter.vb(168,0): at Microsoft.CodeAnalysis.VisualBasic.WithExpressionRewriter.CaptureRValue(BoundExpression value, State state)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Lowering\WithExpressionRewriter.vb(133,0): at Microsoft.CodeAnalysis.VisualBasic.WithExpressionRewriter.CaptureArrayAccess(BoundArrayAccess value, State state)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Lowering\WithExpressionRewriter.vb(324,0): at Microsoft.CodeAnalysis.VisualBasic.WithExpressionRewriter.CaptureWithExpression(BoundExpression value, State state)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Lowering\WithExpressionRewriter.vb(269,0): at Microsoft.CodeAnalysis.VisualBasic.WithExpressionRewriter.AnalyzeWithExpression(Symbol containingMember, BoundExpression value, Boolean doNotUseByRefLocal, Binder binder, Boolean preserveIdentityOfLValues)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_WithBlock.vb(219,0): at Microsoft.CodeAnalysis.VisualBasic.WithBlockBinder.EnsureExpressionAndPlaceholder()
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_WithBlock.vb(298,0): at Microsoft.CodeAnalysis.VisualBasic.WithBlockBinder.CreateBoundWithBlock(WithBlockSyntax node, Binder boundBlockBinder, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(4361,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindWithBlock(WithBlockSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(100,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2043,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics, Binder stmtListBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2032,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3007,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForLoopBodyAndNextControlVariables(ForOrForEachBlockSyntax node, ImmutableArray`1& nextVariables, BoundBlock& loopBody, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3209,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlockParts(ForOrForEachBlockSyntax node, LocalSymbol declaredOrInferredLocalOpt, BoundExpression controlVariableOpt, Boolean isInferredLocal, Boolean hasErrors, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2851,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlock(ForOrForEachBlockSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(94,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2043,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics, Binder stmtListBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2032,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3007,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForLoopBodyAndNextControlVariables(ForOrForEachBlockSyntax node, ImmutableArray`1& nextVariables, BoundBlock& loopBody, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3209,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlockParts(ForOrForEachBlockSyntax node, LocalSymbol declaredOrInferredLocalOpt, BoundExpression controlVariableOpt, Boolean isInferredLocal, Boolean hasErrors, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2851,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlock(ForOrForEachBlockSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(94,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2043,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics, Binder stmtListBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2032,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3007,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForLoopBodyAndNextControlVariables(ForOrForEachBlockSyntax node, ImmutableArray`1& nextVariables, BoundBlock& loopBody, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(3209,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlockParts(ForOrForEachBlockSyntax node, LocalSymbol declaredOrInferredLocalOpt, BoundExpression controlVariableOpt, Boolean isInferredLocal, Boolean hasErrors, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2851,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindForToBlock(ForOrForEachBlockSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(94,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2043,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics, Binder stmtListBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(2032,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(315,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindMethodBlock(MethodBlockBaseSyntax methodBlock, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Statements.vb(148,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMethodSymbol.vb(1195,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.GetBoundMethodBody(TypeCompilationState compilationState, DiagnosticBag diagnostics, Binder& methodBodyBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb(552,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GetBoundMethodBody(TypeCompilationState compilationState, DiagnosticBag diagnostics, Binder& methodBodyBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(1702,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.BindAndAnalyzeMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, Binder containingTypeBinder, MethodSymbol& referencedConstructor, Boolean& injectDefaultConstructorCall, Binder& methodBodyBinder)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(1199,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(MethodSymbol method, Int32 methodOrdinal, Int32& withEventPropertyIdDispenser, Int32& delegateRelaxationIdDispenser, Predicate`1 filter, TypeCompilationState compilationState, ProcessedFieldOrPropertyInitializers processedInitializers, Binder containingTypeBinder, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol& referencedConstructor)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(665,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType, Predicate`1 filter)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(507,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__30-0._Lambda$__0()
    F:\GitHub\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs(139,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location ---
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(317,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.WaitForWorkers()
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\MethodCompiler.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethodBodies(VisualBasicCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Predicate`1 filter, DiagnosticBag diagnostics, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb(2432,0): at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs(2585,0): at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs(2528,0): at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Test\Utilities\VisualBasic\CompilationTestUtils.vb(768,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.AssertTheseEmitDiagnostics(Compilation compilation, XElement errs, Boolean suppressInfos)
    F:\GitHub\roslyn\src\Compilers\VisualBasic\Test\Semantic\Semantics\WithBlockErrorTests.vb(1083,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.WithBlockErrorTests.Test()
```
