### ISSUE TITLE
VS randomly crashes and finally hangs on recovering files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49952]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-randomly-crashes-and-finally-hangs-on/757601)._

---

This is the result of 2 days of misery where VS would just kill itself at random times

**THIS IS THE WORST RELEASE OF VS EVER AND IT HAS WASTED COUNTLESS HOURR FOR ME.  FIX IT.**

On top of all that, if I try to record the problem, it does not occur (but then again, VS now does not ask to restore recovered files anymore, so I guess the problem was in those files and I've lost all my work now ...)

Application Event Log Entries :

**Monday september 30th :**
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.PropertySymbol.IsWritable(BoundExpression receiver, Binder containingBinder)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.CreateBoundCallOrPropertyAccess(SyntaxNode node, SyntaxNode target, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, CandidateAnalysisResult bestResult, ImmutableArray`1 asyncLambdaSubToFunctionMismatch, DiagnosticBag diagnostics, Boolean suppressAbstractCallDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode target, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, DiagnosticBag diagnostics, SyntaxNode callerInfoOpt, Boolean allowConstructorCall, Boolean suppressAbstractCallDiagnostics, Boolean isDefaultMemberAccess, Symbol representCandidateInDiagnosticsOpt, Boolean forceExpandedForm)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.ReclassifyAsValue(BoundExpression expr, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MakeValue(BoundExpression expr, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.AdjustReceiverValue(BoundExpression receiver, SyntaxNode node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindMemberAccess(VisualBasicSyntaxNode node, BoundExpression left, SimpleNameSyntax right, Boolean eventContext, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindQualifiedName(QualifiedNameSyntax name, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindExpression(ExpressionSyntax node, Boolean isInvocationOrAddressOf, Boolean isOperandOfConditionalBranch, Boolean eventContext, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.TryBindNamespaceOrTypeAsExpression(ExpressionSyntax node, SymbolInfoOptions options)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetTypeOrNamespaceSymbolInfoNotInMember(TypeSyntax expression, SymbolInfoOptions options)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(ExpressionSyntax node, SymbolInfoOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNameSyntax(NameSyntax node, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxNode syntax, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5.MoveNext()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.PropertySymbol.IsWritable(Microsoft.CodeAnalysis.VisualBasic.BoundExpression, Microsoft.CodeAnalysis.VisualBasic.Binder)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.CreateBoundCallOrPropertyAccess(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeCharacter, Microsoft.CodeAnalysis.VisualBasic.BoundMethodOrPropertyGroup, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.VisualBasic.BoundExpression>, CandidateAnalysisResult, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.VisualBasic.BoundExpression>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpression(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeCharacter, Microsoft.CodeAnalysis.VisualBasic.BoundMethodOrPropertyGroup, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.VisualBasic.BoundExpression>, System.Collections.Immutable.ImmutableArray`1<System.String>, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.SyntaxNode, Boolean, Boolean, Boolean, Microsoft.CodeAnalysis.VisualBasic.Symbol, Boolean)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.ReclassifyAsValue(Microsoft.CodeAnalysis.VisualBasic.BoundExpression, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MakeValue(Microsoft.CodeAnalysis.VisualBasic.BoundExpression, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.AdjustReceiverValue(Microsoft.CodeAnalysis.VisualBasic.BoundExpression, Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindMemberAccess(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode, Microsoft.CodeAnalysis.VisualBasic.BoundExpression, Microsoft.CodeAnalysis.VisualBasic.Syntax.SimpleNameSyntax, Boolean, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindQualifiedName(Microsoft.CodeAnalysis.VisualBasic.Syntax.QualifiedNameSyntax, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, Boolean, Boolean, Boolean, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.TryBindNamespaceOrTypeAsExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, SymbolInfoOptions)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetTypeOrNamespaceSymbolInfoNotInMember(Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax, SymbolInfoOptions)
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, SymbolInfoOptions, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetSymbolInfo(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNameSyntax(Microsoft.CodeAnalysis.VisualBasic.Syntax.NameSyntax, Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.Classify(Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.Text.TextSpan, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Func`2<Microsoft.CodeAnalysis.SyntaxNode,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, System.Func`2<Microsoft.CodeAnalysis.SyntaxToken,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5, Microsoft.CodeAnalysis.Workspaces, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<AddSemanticClassificationsAsync>d__5 ByRef)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, System.Func`2<Microsoft.CodeAnalysis.SyntaxNode,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, System.Func`2<Microsoft.CodeAnalysis.SyntaxToken,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService+<AddSemanticClassificationsAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Classification.AbstractClassificationService+<AddSemanticClassificationsAsync>d__2, Microsoft.CodeAnalysis.Workspaces, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<AddSemanticClassificationsAsync>d__2 ByRef)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities+<ClassifySpansAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities+<ClassifySpansAsync>d__2, Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ClassifySpansAsync>d__2 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ClassifySpansAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext`1<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan, Microsoft.CodeAnalysis.Classification.IClassificationService, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities+<ProduceTagsAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities+<ProduceTagsAsync>d__0, Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProduceTagsAsync>d__0 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext`1<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan, Microsoft.CodeAnalysis.Classification.IClassificationService, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext`1<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1+TagSource+<RecomputeTagsAsync>d__70[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1+TagSource+<RecomputeTagsAsync>d__70[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RecomputeTagsAsync>d__70<System.__Canon> ByRef)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1+TagSource[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].RecomputeTagsAsync(System.Object, System.Nullable`1<Microsoft.VisualStudio.Text.SnapshotPoint>, System.Nullable`1<Microsoft.CodeAnalysis.Text.TextChangeRange>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan>, System.Collections.Immutable.ImmutableDictionary`2<Microsoft.VisualStudio.Text.ITextBuffer,Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree`1<System.__Canon>>, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1+TagSource+<>c__DisplayClass63_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<RecomputeTagsForeground>b__0(System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue+<>c__DisplayClass12_0.<EnqueueBackgroundTask>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Tuesday Ocotber 1st :**
Faulting application name: devenv.exe, version: 16.3.29324.140, time stamp: 0x5d8ab88a
Faulting module name: clr.dll, version: 4.8.4018.0, time stamp: 0x5d4a64a8
Exception code: 0xc00000fd
Fault offset: 0x000b5b99
Faulting process id: 0x137c
Faulting application start time: 0x01d57851500a8dd1
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: c1cbad13-43cf-4004-86d5-5b6932cb6a1e
Faulting package full name: 
Faulting package-relative application ID: 

**Wednesday Ocotber 2nd :**
The program devenv.exe version 16.3.29324.140 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4120
 Start Time: 01d578e786d51357
 Termination Time: 14
 Application Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe
 Report Id: d793fa90-b20d-4eae-807e-e078213afbf1
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown

---
#### Feedback Bot on 10/3/2019, 00:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/7/2019, 07:34 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/27/2020, 09:02 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
I am not sure how customer's code looks like, but I was able to get a crash with a following unit-test:
```
        <Fact>
        Public Sub Test()
            Dim compilation = CompilationUtils.CreateCompilationWithMscorlib40AndVBRuntime(
<compilation name="GetSemanticInfo">
    <file name="a.vb"><![CDATA[
Class CTest
    Public ReadOnly Property P As MyStructure

Class CTest2
    Function Test() As P.F
    End Function
End Class

End Class

Structure MyStructure
    Public F As Integer
End Structure
    ]]></file>
</compilation>)

            Dim tree As SyntaxTree = (From t In compilation.SyntaxTrees Where t.FilePath = "a.vb").Single()
            Dim root = tree.GetCompilationUnitRoot
            Dim node = root.DescendantNodes().OfType(Of QualifiedNameSyntax).Single()
            Dim semanticModel = compilation.GetSemanticModel(tree)

            Dim symbolInfo = semanticModel.GetSymbolInfo(node)
            Assert.Equal("", symbolInfo.CandidateSymbols.Single().ToTestDisplayString())
            Assert.Equal(CandidateReason.NotATypeOrNamespace, symbolInfo.CandidateReason)
        End Sub
```

Observed:
```
 Microsoft.CodeAnalysis.VisualBasic.UnitTests.SemanticModelAPITests.Test [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
   Stack Trace:
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Symbols\PropertySymbol.vb(158,0): at Microsoft.CodeAnalysis.VisualBasic.Symbols.PropertySymbol.IsWritable(BoundExpression receiver, Binder containingBinder)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Invocation.vb(976,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.CreateBoundCallOrPropertyAccess(SyntaxNode node, SyntaxNode target, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, CandidateAnalysisResult bestResult, ImmutableArray`1 asyncLambdaSubToFunctionMismatch, DiagnosticBag diagnostics, Boolean suppressAbstractCallDiagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Invocation.vb(809,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode target, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, DiagnosticBag diagnostics, SyntaxNode callerInfoOpt, Boolean allowConstructorCall, Boolean suppressAbstractCallDiagnostics, Boolean isDefaultMemberAccess, Symbol representCandidateInDiagnosticsOpt, Boolean forceExpandedForm)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(992,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.ReclassifyAsValue(BoundExpression expr, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(1229,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.MakeValue(BoundExpression expr, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(929,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.AdjustReceiverValue(BoundExpression receiver, SyntaxNode node, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(2906,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindMemberAccess(VisualBasicSyntaxNode node, BoundExpression left, SimpleNameSyntax right, Boolean eventContext, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(653,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindQualifiedName(QualifiedNameSyntax name, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(202,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindExpression(ExpressionSyntax node, Boolean isInvocationOrAddressOf, Boolean isOperandOfConditionalBranch, Boolean eventContext, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Binding\Binder_Expressions.vb(25,0): at Microsoft.CodeAnalysis.VisualBasic.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb(275,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.TryBindNamespaceOrTypeAsExpression(ExpressionSyntax node, SymbolInfoOptions options)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb(690,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetTypeOrNamespaceSymbolInfoNotInMember(TypeSyntax expression, SymbolInfoOptions options)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb(250,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(ExpressionSyntax node, SymbolInfoOptions options, CancellationToken cancellationToken)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb(167,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb(3073,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoForNode(SyntaxNode node, CancellationToken cancellationToken)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb(3164,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
     F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\SemanticModel.cs(108,0): at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)
     F:\GitHub\roslyn\src\Compilers\VisualBasic\Test\Semantic\Compilation\SemanticModelAPITests.vb(4603,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.SemanticModelAPITests.Test()
```
