### ISSUE TITLE
Reproducible crash while typing in .NET Core WPF project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49997]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Reproducible-crash-while-typing-in-NET-/970721)._

---
I have a reproducible crash happening when I start making changes in example project. It happens not exactly after typing things seen on screenshots, but maybe a few lines later and 100% reproducible.

This is simple a WPF .NET Core project, with a few NuGet packages installed:

DynamicData
DynamicData.Plinq
DynamicData.ReactiveUI
PropertyChanged.Fody

The full project directory is attached. I also attach two screenshots: first is what I have after VS start, second is when VS freezes (and then automatically restarts).

---
#### Feedback Bot on 4/1/2020, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/8/2020, 03:17 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
```
        [Fact]
        public void Test2()
        {
            var text = @"
public class Cls
{
    public static void Main()
    {
        if ()
        .Test1().Test2(out var x1).Test3();
    }
}

static class Ext
{
    public static void Test3(this Cls x) {}
}
";
            var compilation = CreateCompilation(text);

            var tree = compilation.SyntaxTrees.Single();
            var model = compilation.GetSemanticModel(tree);

            var node = tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().Where(id => id.Identifier.ValueText == "Test3").Last();
            model.GetSymbolInfo(node);
        }
```

Observed:
```
Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Test2 [FAIL]
  System.InvalidOperationException : This program location is thought to be unreachable.
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2788,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2741,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2711,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2673,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2626,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(SeparatedSyntaxList`1 arguments, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2597,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(ArgumentListSyntax argumentListOpt, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs(172,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(538,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(483,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(478,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(5899,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindLeftOfPotentialColorColorMemberAccess(ExpressionSyntax left, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(5793,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccess(MemberAccessExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(558,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(483,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs(2004,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrExpression(ExpressionSyntax node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs(2365,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs(109,0): at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs(2134,0): at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs(542,0): at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs(1344,0): at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs(1220,0): at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs(218,0): at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs(574,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs(4878,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs(4977,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\SemanticModel.cs(108,0): at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\OutVarTests.cs(36249,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.Test2()
```
