### ISSUE TITLE
Unexpected False Crash

### ISSUE THREAD

**Issue by kfrancis** [dotnet/roslyn#5011]
See the following: http://youtu.be/Z911jedtEjA

I'm writing this code in an MVC controller which inherits from a "BaseController" that has a private property.

```c#
public class BaseController : Controller
{
    private ChargifyConnect Chargify
    {
        get
        {
            return new ChargifyConnect(); // example
        }
    }
}
```

The issue is that:

a) I'm getting intellisense when I can't actually access the property due to it being Private
b) When I do continue to type the code `Chargify.Find<Subscription>()` in the subclass, it crashes 100% of the time with the error:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)
   at Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.InvocationExpressionSignatureHelpProvider.GetMethodGroupItems(InvocationExpressionSyntax invocationExpression, SemanticModel semanticModel, ISymbolDisplayService symbolDisplayService, IAnonymousTypeDisplayService anonymousTypeDisplayService, IDocumentationCommentFormattingService documentationCommentFormattingService, ISymbol within, IEnumerable`1 methodGroup, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.SignatureHelp.InvocationExpressionSignatureHelpProvider.<GetItemsWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by brettfo** [comment]
Thank you for the call stack and I **love** that you included a video; it makes it a lot easier for us to understand the issue.

I've confirmed that this issue will be fixed by PR #4157 and you should get the fix in the next update to VS2015.
