### ISSUE TITLE
Exceptions from NullableWalker caused by a deeply nested pattern result in tons of internal errors

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#50161]
**Version Used**: 
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.9.0 Preview 2.0
VisualStudio.16.Preview/16.9.0-pre.2.0+30803.129
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:

Copy the following code in VS 16.9 Preview 2
```cs
#nullable enable
class E
{
  public E F = new E();
}

class Test
{
  void M7(E e)
  {
    switch (e)
    {
      case { F: { F: { F: { F: { F: null } } } } }: return;
    }
    e.F.ToString();
    e.F.F.ToString();
    e.F.F.F.ToString();
    e.F.F.F.F.ToString();
  }
}
```

**Expected Behavior**:

**Actual Behavior**:
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.BitVector.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.LocalState.get_Item(Int32 slot)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.LearnFromDecisionDag(SyntaxNode node,BoundDecisionDag decisionDag,BoundExpression expression,TypeWithState expressionType,LocalState& initialState)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitSwitchStatementDispatch(BoundSwitchStatement node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitSwitchStatement(BoundSwitchStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundSwitchStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatement(BoundStatement statement)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitMethodBodies(BoundBlock blockBody,BoundBlock expressionBody)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
   at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Analyze(Boolean& badRegion,Optional`1 initialState)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker,Symbol symbol,DiagnosticBag diagnostics,VariableState initialState,Builder snapshotBuilderOpt)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation,Symbol symbol,BoundNode node,Binder binder,Conversions conversions,DiagnosticBag diagnostics,Boolean useConstructorExitWarnings,Boolean useDelegateInvokeParameterTypes,MethodSymbol delegateInvokeMethodOpt,VariableState initialState,Builder analyzedNullabilityMapOpt,Builder snapshotBuilderOpt,ArrayBuilder`1 returnTypesOpt,Boolean getFinalNullableState,VariableState& finalNullableState)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(CSharpCompilation compilation,Symbol symbol,BoundNode node,Binder binder,VariableState initialState,DiagnosticBag diagnostics,Boolean createSnapshots)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation,Symbol symbol,BoundNode node,Binder binder,VariableState initialState,DiagnosticBag diagnostics,Boolean createSnapshots,SnapshotManager& snapshotManager,ImmutableDictionary`2& remappedSymbols)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method,TypeCompilationState compilationState,DiagnosticBag diagnostics,VariableState nullableInitialState,ImportChain& importChain,Boolean& originalBodyNested,InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol,Int32 methodOrdinal,ProcessedFieldInitializers& processedInitializers,SynthesizedSubmissionFields previousSubmissionFields,TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol,TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor,TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation,PEModuleBuilder moduleBeingBuiltOpt,Boolean emittingPdb,Boolean emitTestCoverageData,Boolean hasDeclarationErrors,DiagnosticBag diagnostics,Predicate`1 filterOpt,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree,Nullable`1 span,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage,SyntaxTree syntaxTree,Nullable`1 filterSpanWithinTree,Boolean includeEarlierStages,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.GetDiagnosticsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.HasMissingImportsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
![yellowbars](https://user-images.githubusercontent.com/5566206/103289433-37187980-49f8-11eb-883e-a278aef0ae8c.gif)

**Comment by jaredpar** [comment]
@cston this looks like a good issue to validate against the rework of the nullable walker state storage.
