### ISSUE TITLE
It looks like Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTests.TestOpenProject_AssemblyNameIsPath unit-test is flaky

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#50258]
Lately, I am consistently getting the test failure when run it on my dev box. Both from command line and from VS:
```
Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTests.TestOpenProject_AssemblyNameIsPath [FAIL]
  Assert.Equal() Failure
                                   ↓ (pos 50)
  Expected: ···l\Temp\2\RoslynTests
  Actual:   ···l\Temp\2\RoslynTests\fc082681-b2ee-4795-a7b1-cda1d73c7e31\CSh···
                                   ↑ (pos 50)
  Stack Trace:
    F:\GitHub\roslyn\src\Workspaces\MSBuildTest\MSBuildWorkspaceTests.cs(830,0): at Microsoft.CodeAnalysis.MSBuild.UnitTests.MSBuildWorkspaceTests.<TestOpenProject_AssemblyNameIsPath>d__40.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

The guid is different from run to run.
However, CI for a GitHub PR is passing.

**Comment by JoeRobich** [comment]
This issue causes the Roslyn integration tests to fail on the 16.9 Preview 3 scouting image - https://dev.azure.com/dnceng/public/_build/results?buildId=969374&view=ms.vss-test-web.build-test-results-tab&runId=30470034&resultId=100039&paneView=debug

**Comment by JoeRobich** [comment]
This was caused by a MSBuild change where they will infer an OutputPath when one is not specified. See https://github.com/dotnet/msbuild/pull/5238
