### ISSUE TITLE
yellow bar "Feature 'Asset synchronization' is currently unavailable due to an internal error."

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#50257]
**Version Used**: 
VS 2019 16.9.0 Preview 2.0
**Steps to Reproduce**:
it happens arbitrarily when starting VS - about half the time. - seems to only happen when a file is opened in the solution, though.

**Expected Behavior**:
no yellow bar
**Actual Behavior**:
Yellow bar

**here is the stacktrace**:
```
StreamJsonRpc.RemoteInvocationException: Unable to find the specified file.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__138`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.IO.FileNotFoundException: Unable to find the specified file.
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, Int32 desiredAccessRights, Boolean createOrOpen)
      at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability)
      at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.AttachTemporaryStreamStorage(String storageName, Int64 offset, Int64 size, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.GetTemporaryStorage(ObjectReader reader, SerializationKinds kind, ITemporaryStreamStorage& storage, Int64& length, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.ReadModuleMetadataFrom(ObjectReader reader, SerializationKinds kind, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.TryReadMetadataFrom(ObjectReader reader, SerializationKinds kind, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.ReadPortableExecutableReferenceFrom(ObjectReader reader, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.ReadMetadataReferenceFrom(ObjectReader reader, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Serialization.SerializerService.Deserialize[T](WellKnownSynchronizationKind kind, ObjectReader reader, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.ReadData(Stream stream, Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.<ReadDataAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.<ReadDataAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass21_0`1.<<InvokeStreamingServiceAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass21_0`1.<<InvokeStreamingServiceAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<InvokeStreamingServiceAsync>d__21`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__4`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.SolutionAssetSource.<GetAssetsAsync>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.<RequestAssetsAsync>d__12.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.<SynchronizeAssetsAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.<SynchronizeProjectsAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.<SynchronizeProjectAssets_NoLockAsync>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.<SynchronizeProjectAssetsAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.<SynchronizeProjectAssetsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<SynchronizeAssetsAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<UpdatePrimaryBranchSolutionAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteAssetSynchronizationService.<>c__DisplayClass2_0.<<SynchronizePrimaryWorkspaceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Tagging @tmat @sharwell

**Comment by tmat** [comment]
Should be fixed by https://github.com/dotnet/roslyn/pull/49974 in 16.9 Preview 3.

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/roslyn/issues/49005.

**Comment by Kevin-Andrew** [comment]
I go this error today. Coincidentally enough, it also seemed to appear right after I opened a file from the Solution Explorer, after just having opened a very large solution (147 projects with over 6,500 files). So Visual Studio was still very busy doing a lot of background work.

Here is the stack trace:
```
StreamJsonRpc.RemoteInvocationException: The project already transitively references the target project.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: The project already transitively references the target project.
      at Microsoft.CodeAnalysis.Solution.CheckCircularProjectReferences(ProjectId projectId, IReadOnlyCollection`1 projectReferences)
      at Microsoft.CodeAnalysis.Solution.WithProjectReferences(ProjectId projectId, IEnumerable`1 projectReferences)
      at Microsoft.CodeAnalysis.Project.WithProjectReferences(IEnumerable`1 projectReferences)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<UpdatePrimaryBranchSolutionAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteAssetSynchronizationService.<>c__DisplayClass2_0.<<SynchronizePrimaryWorkspaceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()
```
![image](https://user-images.githubusercontent.com/22459191/114439566-f6dfa000-9b7d-11eb-9ee0-af4c27038321.png)

**Comment by tmat** [comment]
@jasonmalinowski Looks like an issue with project references.

**Comment by jasonmalinowski** [comment]
Filed #52578 to track and will discuss there.

**Comment by NickeManarin** [comment]
What happened with VS? 
Stay away from v16.9.4

![image](https://user-images.githubusercontent.com/14798947/115488857-97def280-a231-11eb-859e-581ed3999831.png)

**Comment by CyrusNajmabadi** [comment]
@NickeManarin Please file feedback from vs so we can retrieve the logs necessary to diagnose this. Thanks.

**Comment by NickeManarin** [comment]
@CyrusNajmabadi A strange thing happened, I had to restart twice to stop getting this kind of issue.

**Comment by ProIntegritate** [comment]
Getting this tonight, has happened earlier randomly.
https://raw.githubusercontent.com/ProIntegritate/Misc-data/main/Bug_VisualStudio.png

According to the error messages which are pretty similar:
> "StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete."

I'm guessing that this has to do with some of the services that VS connects to isn't available. This happens _regardless_ of what project I'm opening, has opened a console application, forms application, small application and a larger project.

Problem is that i cannot suppress the messages and they keep popping up. I can still work and write code, i just want the bloody yellow bars to go away.

Running VS2019 **v16.10.3**.

**Comment by oleglukin** [comment]
I've got the yellow bar as well.
Visual Studio 2019 Professional. Version 16.11.3
`StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete. ---> System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(<Unknown Parameters>)
   at async StreamJsonRpc.JsonRpc.TransmitAsync(<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)`

**Comment by jjxtra** [comment]
It's back in 17.14.10

**Comment by jasonmalinowski** [comment]
@jjxtra If you could file a new bug with the stack trace, that'd be a wonderful help!

**Comment by CyrusNajmabadi** [comment]
Also, please open a new issue.  This was closed out 4 years ago.  Thanks.
