### ISSUE TITLE
Unable to install ".NET Compiler Platform SDK Templates" VSIX

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#5044]
I'm trying to install the VSIX with the Roslyn project templates (http://go.microsoft.com/fwlink/?LinkID=526901)

The installation fails with the following error:
<img width="446" alt="screen shot 2015-09-06 at 12 53 05" src="https://cloud.githubusercontent.com/assets/1710369/9704015/70355ce0-5496-11e5-9fbd-e55fcb0ce860.png">

The log:

```
2015-09-06 12:52:11 PM - Microsoft VSIX Installer
2015-09-06 12:52:11 PM - -------------------------------------------
2015-09-06 12:52:11 PM - Initializing Install...
2015-09-06 12:52:11 PM - Extension Details...
2015-09-06 12:52:11 PM - 	Identifier      : 3a012d4e-6057-4e7c-8123-6d4be1d4723c
2015-09-06 12:52:11 PM - 	Name            : .NET Compiler Platform SDK
2015-09-06 12:52:11 PM - 	Author          : Microsoft
2015-09-06 12:52:11 PM - 	Version         : 1.0.0.50618
2015-09-06 12:52:11 PM - 	Description     : The .NET Compiler Platform ("Roslyn") provides open-source C# and Visual Basic compilers with rich code analysis APIs. You can build code analysis tools with the same APIs that Microsoft is using to implement Visual Studio! Also includes the Syntax Visualizer, a Visual Studio extension that allows you to inspect and explore the syntax trees you'll use as you build applications and VS extensions atop the .NET Compiler Platform ("Roslyn").
2015-09-06 12:52:11 PM - 	Locale          : en-US
2015-09-06 12:52:11 PM - 	MoreInfoURL     : 
2015-09-06 12:52:11 PM - 	InstalledByMSI  : False
2015-09-06 12:52:11 PM - 	SupportedFrameworkVersionRange : [4.5.2,)
2015-09-06 12:52:11 PM - 
2015-09-06 12:52:11 PM - 	SignedBy        : Microsoft Corporation
2015-09-06 12:52:11 PM - 	Certificate Info : [Subject]
  CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Issuer]
  CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Serial Number]
  33000000A81581DB462EBDD9480000000000A8

[Not Before]
  2015-03-05 12:42:40 AM

[Not After]
  2016-06-05 1:42:40 AM

[Thumbprint]
  EFCF3B47C17854AB6E4C63821DE31A59B24D62B2

2015-09-06 12:52:11 PM - 	Supported Products : 
2015-09-06 12:52:11 PM - 		Microsoft.VisualStudio.Pro
2015-09-06 12:52:11 PM - 			Version : [14.0.23107,)
2015-09-06 12:52:11 PM - 
2015-09-06 12:52:11 PM - 	References      : 
2015-09-06 12:52:11 PM - 		-------------------------------------------------------
2015-09-06 12:52:11 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
2015-09-06 12:52:11 PM - 		Name         : Visual Studio MPF 14.0
2015-09-06 12:52:11 PM - 		Version      : [14.0]
2015-09-06 12:52:11 PM - 		MoreInfoURL  : 
2015-09-06 12:52:11 PM - 		Nested       : No
2015-09-06 12:52:11 PM - 
2015-09-06 12:52:11 PM - 
2015-09-06 12:52:11 PM - Searching for applicable products...
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Premium 2013 
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Professional 2013
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Professional 2015
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio Community 2015
2015-09-06 12:52:11 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2015-09-06 12:52:11 PM - Found installed product - Global Location
2015-09-06 12:52:11 PM - Found installed product - ssms
2015-09-06 12:52:11 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by jmarolf** [comment]
Which version of Visual Studio do you have installed?

**Comment by filipw** [comment]
```
Microsoft Visual Studio Enterprise 2015
Version 14.0.23103.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Enterprise
```

**Comment by jmarolf** [comment]
RTM is 
```
Version 14.0.23107.0 D14REL
```
We block installing the SDK on non-RTM versions

**Comment by filipw** [comment]
Thanks, I uninstalled the version that I had and installed VS again and it helped. Bizarre that I had a version that differs so little in version number, not sure how that happened - it was surely not RC.
