### ISSUE TITLE
Failed contract in CSharpUseNotPatternCodeFixProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#50534]
**Version Used**: 
Version 16.9.0 Preview 3.0 [30904.5.main]

In Roslyn.sln `AbstractEditAndContinueAnalyzer` method `ReportStateMachineRudeEdits`:

```C#
if (!(oldMember is IMethodSymbol oldMethod))
{
  return;
}
```

![image](https://user-images.githubusercontent.com/41759/104767759-8a413a80-5721-11eb-8c67-eb5bfd358cee.png)

```
System.InvalidOperationException : We should have never gotten here as CODE_STYLE doesn't support C# 9 yet.
   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpUseNotPatternCodeFixProvider.FixAllAsync(Document document,ImmutableArray`1 diagnostics,SyntaxEditor editor,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<>c__DisplayClass4_0.<FixAllAsync>b__0(SyntaxEditor editor)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
This appears to be fixed by https://github.com/dotnet/roslyn/pull/49033

**Comment by jinujoseph** [comment]
@tmat are you seeing this with latest build ?

**Comment by sharwell** [comment]
Unfortunately we cannot update the Code Style analyzers without forcing users onto a new version of Visual Studio. Currently the minimum version of Visual Studio for working in Roslyn.sln is 16.8, which means the Code Style layer is locked to 3.8.0 and we cannot use the fix from #49033.

**Comment by sharwell** [comment]
This issue will be automatically resolved when Roslyn updates to a new minimum version of the IDE.

**Comment by CyrusNajmabadi** [comment]
> This issue will be automatically resolved when Roslyn updates to a new minimum version of the IDE.

Any idea when that will happen next Sam?  Thanks!
