### ISSUE TITLE
Internal CLR error in PEWriter.WritePEToStream

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#50655]
Build log: https://dev.azure.com/dnceng/public/_build/results?buildId=958976&view=logs&j=7817cc08-46f6-529a-b675-9c2d2b016c0b&t=8c177619-984e-58de-5e95-103fbf6e1f0a

Artifacts: (includes dump file) https://dev.azure.com/dnceng/public/_build/results?buildId=958976&view=artifacts&pathAsName=false&type=publishedArtifacts

Also attaching the run logs here but not the dump file due to size.
[runtests.log](https://github.com/dotnet/roslyn/files/5845670/runtests.log)
[xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log](https://github.com/dotnet/roslyn/files/5845671/xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log)

This occurred in the Test_Windows_CoreClr_Release job. Wondering if we should file this on dotnet/runtime or if we need to first change some configs and keep running CI to try and repro the failure with the diagnostic info they need. @jkotas could you please advise?

```log
Command: test "Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll" --filter "Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.UnsafeTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.UsingStatementTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.WinMdDelegateTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.WinMdDelegateTests+VerifyType|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenInParametersTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenReadOnlyStructTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenRefLocalTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenRefReadOnlyReturnTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenStackAllocInitializerTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DesktopStrongNameProviderTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CodeGenScriptTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests+TestPEBuilder|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests+TestResourceSectionBuilder|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CovariantReturnTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.DeterministicTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.DeterministicTests+WriteOnlyStream|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EmitCustomModifiers|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EndToEndTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EntryPointTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.InAttributeModifierTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.OptionalArgumentsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.Perf|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.ResourceTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.UnmanagedTypeModifierTests|Microsoft.CodeAnalysis.CSharp.UnitTests.EmitErrorTests|Microsoft.CodeAnalysis.CSharp.UnitTests.EmitMetadata|Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CheckSumTest|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CSharpDeterministicBuildCompilationTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CSharpPDBTestBase|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBAsyncTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBConstantTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBDynamicLocalsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBEmbeddedSourceTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBIteratorTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLambdaTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBSourceLinkTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBTupleTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBUsingTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBWinMdExpTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PortablePdbTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PrivateProtected|Microsoft.CodeAnalysis.CSharp.UnitTests.ReadOnlyStruct|Microsoft.CodeAnalysis.CSharp.UnitTests.RefReturnTests" --framework net5.0 --logger "xunit;LogFilePath=F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4_net5.0_x86_test_results.xml"
xUnit output log: F:\workspace\_work\1\s\artifacts\log\Release\xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log
The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
   at System.IO.MemoryStream.set_Capacity(Int32)
   at System.IO.MemoryStream.EnsureCapacity(Int32)
   at System.IO.MemoryStream.Write(Byte[], Int32, Int32)
   at System.Reflection.Metadata.BlobBuilder.WriteContentTo(System.IO.Stream)
   at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, Boolean, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Func`2<Microsoft.DiaSymReader.ISymWriterMetadataProvider,Microsoft.DiaSymReader.SymUnmanagedWriter>, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.Emit.EmitOptions, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.EmitWithPdb(System.IO.MemoryStream, System.IO.MemoryStream, Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.IMethodSymbol, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Boolean)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.<VerifyPdbImpl>g__Verify|13_0(Boolean, Boolean, <>c__DisplayClass13_0 ByRef)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdbImpl(Microsoft.CodeAnalysis.Compilation, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, System.String, System.String, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String, Boolean)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdb(Microsoft.CodeAnalysis.Compilation, System.String, System.String, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdb(Microsoft.CodeAnalysis.Compilation, System.String, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String)
   at Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLambdaTests.Queries1()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CallTestMethod(System.Object)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<InvokeTestMethodAsync>b__1>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4, xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AggregateAsync>d__4 ByRef)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9, xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__9 ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<InvokeTestMethodAsync>d__48<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InvokeTestMethodAsync(System.Object)
   at Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<RunAsync>b__47_0>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<RunAsync>b__47_0()
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__10`1<System.Decimal> ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.Threading.Tasks.Task`1<System.Decimal>>)
   at Xunit.
Test Run Aborted.
```

**Comment by jaredpar** [comment]
This appears to be crash during the GC process. Possibly another symptom of https://github.com/dotnet/runtime/issues/45557

```
 # Child-SP          RetAddr           Call Site
00 (Inline Function) --------`-------- coreclr!MethodTable::GetFlag [F:\workspace\_work\1\s\src\coreclr\src\vm\methodtable.h @ 3705] 
01 (Inline Function) --------`-------- coreclr!MethodTable::HasComponentSize [F:\workspace\_work\1\s\src\coreclr\src\vm\methodtable.h @ 1688] 
02 (Inline Function) --------`-------- coreclr!WKS::my_get_size+0x4 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 9542] 
03 00000033`4dff8ee0 00007ff9`7bb28299 coreclr!WKS::gc_heap::mark_object_simple+0x7b [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 19432] 
04 (Inline Function) --------`-------- coreclr!WKS::gc_heap::mark_through_cards_helper+0x1b9 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 29827] 
05 00000033`4dff8f30 00007ff9`7bb4bcd6 coreclr!WKS::gc_heap::mark_through_cards_for_segments+0x4e9 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 30261] 
06 00000033`4dff9080 00007ff9`7bb49223 coreclr!WKS::gc_heap::mark_phase+0x17a6 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 20839] 
07 00000033`4dffa680 00007ff9`7bb48377 coreclr!WKS::gc_heap::gc1+0x1c3 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 16694] 
08 (Inline Function) --------`-------- coreclr!GCToOSInterface::GetLowPrecisionTimeStamp+0x5 [F:\workspace\_work\1\s\src\coreclr\src\vm\gcenv.os.cpp @ 1033] 
09 00000033`4dffa750 00007ff9`7bb14266 coreclr!WKS::gc_heap::garbage_collect+0xa67 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 18280] 
0a 00000033`4dffa830 00007ff9`7bb276d5 coreclr!WKS::GCHeap::GarbageCollectGeneration+0x256 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 37751] 
0b (Inline Function) --------`-------- coreclr!WKS::gc_heap::trigger_gc_for_alloc+0x19b [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 13862] 
0c (Inline Function) --------`-------- coreclr!WKS::gc_heap::try_allocate_more_space+0x1a2 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 13985] 
0d 00000033`4dffa8c0 00007ff9`7bb29ff7 coreclr!WKS::gc_heap::allocate_more_space+0x1c5 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14486] 
0e (Inline Function) --------`-------- coreclr!WKS::gc_heap::allocate+0x5a [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 14517] 
0f 00000033`4dffa940 00007ff9`7bab760c coreclr!WKS::GCHeap::Alloc+0x87 [F:\workspace\_work\1\s\src\coreclr\src\gc\gc.cpp @ 36745] 
10 (Inline Function) --------`-------- coreclr!Alloc+0xbd [F:\workspace\_work\1\s\src\coreclr\src\vm\gchelpers.cpp @ 228] 
11 (Inline Function) --------`-------- coreclr!AllocateSzArray+0x17f [F:\workspace\_work\1\s\src\coreclr\src\vm\gchelpers.cpp @ 483] 
12 00000033`4dffa9b0 00007ff9`1e34858b coreclr!JIT_NewArr1+0x28c [F:\workspace\_work\1\s\src\coreclr\src\vm\jithelpers.cpp @ 2723] 
13 00000033`4dffac80 00000000`00000001 0x00007ff9`1e34858b
14 00000033`4dffac88 0000020b`e3325480 0x1
15 00000033`4dffac90 0000020b`e3325148 0x0000020b`e3325480
16 00000033`4dffac98 0000020b`e32b3660 0x0000020b`e3325148
17 00000033`4dffaca0 4be90158`0000072c 0x0000020b`e32b3660
18 00000033`4dffaca8 55ce83d3`673032a3 0x4be90158`0000072c
19 00000033`4dffacb0 0000020b`e3325148 0x55ce83d3`673032a3
1a 00000033`4dffacb8 0000020b`e32b3660 0x0000020b`e3325148
1b 00000033`4dffacc0 00000000`0000009c 0x0000020b`e32b3660
1c 00000033`4dffacc8 00007ff9`1e3484b4 0x9c
1d 00000033`4dffacd0 0000020b`e32b3660 0x00007ff9`1e3484b4
1e 00000033`4dffacd8 00000000`00000100 0x0000020b`e32b3660
1f 00000033`4dfface0 00000000`00000000 0x100

```

Moving to dotnet/runtime
