### ISSUE TITLE
Renaming variable passed to method generated by a source generator causes Visual Studio to crash

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/roslyn#50933]
Hi. I'm using generators to generate methods, it's working fantastically well.  

There is an issue I've been having though. Say I pass a variable to a generated method:

```cs
string test = "test";

Helper.GeneratedMethod(test);
```

When I rename the variable using VS's rename feature (Ctrl-R + Ctrl-R or right click > rename), VS crashes. I've created a [minimal repro](https://github.com/JeremyTCD/Repro.Generators.VariableRenaming). Usage:

- Clone
- Open
- `Ctrl-R + Ctrl-R` `message` in `Program`
-  VS hangs with message "Unfortunately, a process used by Visual Studio has encountered an unrecoverable error.  We recommend saving your work, and then closing and restarting Visual Studio."

VS stack trace:

```
System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](<Unknown Parameters>)
   at async Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<RequestServiceChannelAsync>b__0(<Unknown Parameters>)
   at async Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](<Unknown Parameters>)
   at async Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(<Unknown Parameters>)
   at async Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(<Unknown Parameters>)
   at async Microsoft.ServiceHub.Client.HubClient.GetPipeAsync(<Unknown Parameters>)
   at async Microsoft.ServiceHub.Client.HubClient.RequestServiceAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.ServiceHubRemoteHostClient.RequestServiceAsync(<Unknown Parameters>)
```

## Repro source for quick reference

`DummyGenerator` finds member accesses on `DummyMethods` and generates methods for those accesses. 
Generator:

```cs
  [Generator]
  public class DummyGenerator : ISourceGenerator
  {
      public void Execute(GeneratorExecutionContext context)
      {
          string dummySource = $@"using System;

namespace Repro.Generators.VariableRenaming
{{ 
  public static class DummyMethods
  {{
      public static void {((SyntaxReceiver)context.SyntaxReceiver).MethodName}(string message){{
          Console.Write(message);
      }}
  }}
}}
";

          context.AddSource("DummyMethods.Generated.cs", dummySource);
      }

      public void Initialize(GeneratorInitializationContext context)
      {
          context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
      }

      private class SyntaxReceiver : ISyntaxReceiver
      {
          public string MethodName;

          public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
          {
              if (syntaxNode is MemberAccessExpressionSyntax memberAccessExpressionSyntax &&
                  memberAccessExpressionSyntax.Expression is IdentifierNameSyntax identifierNameSyntax &&
                  identifierNameSyntax.Identifier.ValueText == "DummyMethods")
              {
                  MethodName = memberAccessExpressionSyntax.Name.Identifier.ValueText;
              }
          }
      }
  }
```

`Program`:
```cs
using Repro.Generators.VariableRenaming;
class Program
{
    static void Main()
    {
        string message = "Hello";

        DummyMethods.Test(message);
    }
}
```

VS version: 16.8.4

**Comment by jasonmalinowski** [comment]
@JeremyTCD: thanks for the repro steps! It's no longer reproducing for me on 16.9 Preview 4, which is what I expected as we made a bunch of changes, specifically #49680 to generally normalize how the IDE handles symbols coming from generated files.

(and don't feel bad about filing a bug that was fixed here...this was good for us to sanity test the work is fixing the real-world issues.)

**Comment by JeremyTCD** [comment]
Thanks for the quick response! Glad it's fixed!
