### ISSUE TITLE
NRE in Microsoft.CodeAnalysis.VisualBasic.Extensions.SemanticModelExtensions.GenerateNameForExpression

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#51040]
**Version Used**: 
Version 16.9.0 Preview 4.0 [30920.304.main]

While working in Roslyn solution with some errors present (passing argument to constructor call that does not have corresponding parameter)

```VB
        Friend Shared Function DocumentResults(
            Optional activeStatements As ActiveStatementsDescription = Nothing,
            Optional semanticEdits As SemanticEditDescription() = Nothing,
            Optional diagnostics As RudeEditDiagnosticDescription() = Nothing,
            Optional dependentDocuments As Integer() = Nothing) As DocumentAnalysisResultsDescription
            Return New DocumentAnalysisResultsDescription(activeStatements, semanticEdits, diagnostics, dependentDocuments)
        End Function
```

![image](https://user-images.githubusercontent.com/41759/107126962-ca4e9580-6867-11eb-935b-aafffdce1189.png)

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.SemanticModelExtensions.GenerateNameForExpression(SemanticModel semanticModel,ExpressionSyntax expression,Boolean capitalize,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.GenerateConstructor.VisualBasicGenerateConstructorService.GenerateNameForExpression(SemanticModel semanticModel,ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.GenerateNameForArgument(SemanticModel semanticModel,Argument argument,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.<>c__DisplayClass17_0.<GenerateParameterNames>b__2(Argument a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.GenerateParameterNames(SemanticDocument document,IEnumerable`1 arguments,IList`1 reservedNames,NamingRule parameterNamingRule,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeDelegatedConstructor(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.TryInitializeAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.State.GenerateAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.GenerateMember.GenerateConstructor.AbstractGenerateConstructorService`2.GenerateConstructorAsync[TService,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
It could be `a.GetArgumentExpression()` is returning null in the following line:

https://github.com/dotnet/roslyn/blob/01fbb9887d22c68596a856092520a9e66c72f9d9/src/Features/VisualBasic/Portable/GenerateConstructor/VisualBasicGenerateConstructorService.vb#L162

which propagated to `GenerateNameForExpression`.
