### ISSUE TITLE
InvalidOperationException from CSharpTypeInferenceService

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5126]
Crash dump:

%internal_share%\public\tomat\Bugs\5126

Repro:

1. Open src\Scripting\Core\ScriptMetadataReferenceResolver.cs in Roslyn.sln solution in Repro.zip in the folder above.
2. Edit line 60 like so:

```C#
return PackageResolver.ResolveNuGetPackage(reference).SelectAsArray(p => 
```

```C#
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Construct(ImmutableArray`1 typeArguments)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(ITypeSymbol[] arguments)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.Instantiate(IMethodSymbol method, IList`1 invocationTypes)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass20_0.<InferTypeInArgument>b__0(IMethodSymbol m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(Int32 index, IEnumerable`1 methods, ArgumentSyntax argumentOpt)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInInvocationExpression(InvocationExpressionSyntax invocation, Int32 index, ArgumentSyntax argumentOpt)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(ArgumentSyntax argument, Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<InferTypesWorker_DoNotCallDirectly>b__6_1(ArgumentSyntax argument)
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 defaultFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(ExpressionSyntax expression)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(TExpressionSyntax expression, Boolean filterUnusable)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInLambdaExpression(ExpressionSyntax lambdaExpression)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInSimpleLambdaExpression(SimpleLambdaExpressionSyntax lambdaExpression, Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass8_0.<InferTypesWorker_DoNotCallDirectly>b__35(SimpleLambdaExpressionSyntax simpleLambdaExpression)
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TDerivedType39,TDerivedType40,TDerivedType41,TDerivedType42,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 matchFunc39, Func`2 matchFunc40, Func`2 matchFunc41, Func`2 matchFunc42, Func`2 defaultFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.InferTypes(SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferType(ITypeInferenceService typeInferenceService, SemanticModel semanticModel, Int32 position, Boolean objectAsDefault, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.<GetItemsWorkerAsync>d__2.MoveNext()

```

**Comment by Pilchie** [comment]
Can you let us know if we're using the API incorrectly?

**Comment by brettfo** [comment]
FYI, I found a shorter repro:

``` C#
using System.Collections.Generic;
using System.Linq;

class C
{
    void M(IEnumerable<string> args)
    {
        args = args.Select(a =>$$) // where '$$' is the cursor location, hit space
    }
}
```

**Comment by tmat** [comment]
@TyOverby @jaredpar Could you prioritize this? VS keeps crashing whenever I type lambda.

**Comment by gafter** [comment]
I suspect the client is attempting to construct (instantiate with type arguments) a method that is already constructed or not generic.
