### ISSUE TITLE
Unable to apply rename file suggestion with links

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51342]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Unable-to-apply-rename-file-suggestion-w/1273748)._

---
\[severity:It's more difficult to complete my work\]
The MoveTypeCodeRefactoringProvider doesn't consider links. Attempting to apply the suggestion on a link file crashes the provider.
Remedations:
Rename link and target (golden path)
Don't offer the code fix in case of links
Show a sensible error message ("Renaming a link file is not allowed") instead of letting the code fix crash.

Stack trace:
```
System.Runtime.InteropServices.COMException : Renaming a link file is not allowed. at EnvDTE.ProjectItem.set\_Name(String pbstrReturn)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentInfoChanged(DocumentId documentId,DocumentInfo updatedInfo) at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
 at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges) at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
 at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray\`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray\`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func\`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c\_\_DisplayClass20\_0.b\_\_0()
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 12/1/2020, 06:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/2/2020, 09:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 2/19/2021, 09:54 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Related to #39733
