### ISSUE TITLE
ArgumentOutOfRangeException from InteractiveWindow

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5141]
Repro:

Enter a couple of submissions:
```C#
> var s = "002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293";
> for (int i = 0; i < s.Length; i += 2) Console.Write($"{s[i]}{s[i+1]}");
```
Hit Enter to evaluate the second submission. It prints out a string.

UpArrow, LeftArrow, LeftArrow, DownArrow, ```<crash>```

Crash dump:
%internal_share%\public\tomat\Bugs\5141
```
   at Microsoft.VisualStudio.Text.Utilities.FrugalList`1.get_Item(Int32 index)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapToSourceSnapshot(Int32 position)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToInsertionPoint(SnapshotPoint position, PointTrackingMode trackingMode, Predicate`1 match)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.IBufferGraphExtensions.MapUpOrDownToBuffer(IBufferGraph bufferGraph, SnapshotPoint point, ITextBuffer targetBuffer)
   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ITextViewExtensions.GetCaretPoint(ITextView textView, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.GetCaretPoint(ITextView textViewOpt, ITextBuffer subjectBuffer)
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.RecomputeTagsForeground()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.<>c__DisplayClass1_0.<SafeStartNew>b__0()
```

**Comment by amcasey** [comment]
I've seen that too.

**Comment by tmat** [comment]
@amcasey Have a repro.

**Comment by amcasey** [comment]
As the caret comes back down to the prompt for the current input, a tagger (keyword highlighting in one instance) tries to map the caret position down to a specific subject buffer.  However, the caret is no longer in that subject buffer, so the mapping fails.

It's worth mentioning that the caret is exactly on the boundary of the subject buffer.  My guess is that with ```PointTrackingMode.Negative```, the mapping would have succeeded.  However, it seems more likely that failure should either be handled or detected and prevented.

**Comment by amcasey** [comment]
The ```TagSource``` already handles the fact that a caret position might not be found (```GetCaretPoint``` returns a nullable).

**Comment by amcasey** [comment]
Correction: while the caret is on the boundary of two subject buffers, neither of those buffers is the one we're trying to map into.

**Comment by amcasey** [comment]
Reduced repro: evaluate ```for (int i = 0; i < 10; i++) Console.Write(i);``` and then up, left, left, down.

**Comment by amcasey** [comment]
I'm getting suspicious of ```InteractiveWindow.EditResolver``` since it computes the out-of-range value.

**Comment by amcasey** [comment]
The list of points passed to ```resolver.GetTypicalInsertionPosition``` is empty, so there's no value that could be returned that would not cause this exception.

**Comment by amcasey** [comment]
It looks like ```ProjectionSnapshot.MapInsertionPointToSourceSnapshot``` (which produces the empty list handed to ```GetTypicalInsertionPoint```) specifically excludes the "inert" subject buffer containing the prompts.  In a comment, it suggests that this approach is "flawed" but is required for back-compat.  I suspect this is why we're getting an empty list.

**Comment by amcasey** [comment]
Prompts are ending up in the "inert" subject buffer because we're using strings (rather than ```ITrackingSpan```s).

**Comment by amcasey** [comment]
This is happening on ```Console.Write``` because we insert a newline after the output and that newline is also "inert".  Therefore, the caret is at the boundary between two "inert" spans and ```MapInsertionPointToSourceSnapshot``` rejects both.

**Comment by amcasey** [comment]
Filed internal bug 144964 to track the underlying issue.

**Comment by amcasey** [comment]
Should not repro, as of https://github.com/dotnet/roslyn/commit/6e515e6ee4a74ba398a7311c58b08e99d7a41b8d.
