### ISSUE TITLE
Visual Studio crashes when typing "public sealed record("

### ISSUE THREAD

**Issue by SirDuke** [dotnet/roslyn#51590]
**Version Used**: 
Visual Studio 16.8.6
Visual Studio 16.9.0 preview 5.0

**Steps to Reproduce**:

1. Create new .Net5 Class Library
2. Delete all content from "Class1.cs", then add the following text:
`public sealed record(`

**Expected Behavior**:
Visual Studio shows errors in the code.

**Actual Behavior**:
VS 16.8.6 crashes
VS 16.9.0 Preview 5.0 shows a lot of exceptions in the upper yellow bar

**Comment by RikkiGibson** [comment]
Thank you for reporting. Have slightly modified the repro steps to make it easier to repro.

**Comment by RikkiGibson** [comment]
The following test crashes:

```cs
        [Fact]
        public void SealedIncomplete()
        {
            var source = @"
public sealed record(";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();
        }
```

```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.RecordTests.SealedIncomplete:
    Outcome: Failed
    Error Message:
    System.InvalidOperationException : Unexpected difference at offset 16: Line 2, Column 15 "public sealed record("  (Found: [(] Expected: [r])
    Stack Trace:
       at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Core\ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.CodeAnalysis.SyntaxTreeExtensions.VerifySource(SyntaxTree tree, IEnumerable`1 changes) in c:\Users\rikki\src\roslyn\src\Compilers\Core\Portable\Syntax\SyntaxTreeExtensions.cs:line 80
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, ImmutableDictionary`2 diagnosticOptions, Nullable`1 isGeneratedCode, CancellationToken cancellationToken) in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxTree.cs:line 490
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, ImmutableDictionary`2 diagnosticOptions, CancellationToken cancellationToken) in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxTree.cs:line 913
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, CancellationToken cancellationToken) in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxTree.cs:line 449
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseSyntaxTree(SourceText text, ParseOptions options, String path, CancellationToken cancellationToken) in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Portable\Syntax\SyntaxFactory.cs:line 1573
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.Parse(String text, String filename, CSharpParseOptions options, Encoding encoding) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 871
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource.GetSyntaxTrees(CSharpParseOptions parseOptions, String sourceFileName) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestSource.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource.<>c__DisplayClass6_0.<GetSyntaxTrees>b__0(CSharpTestSource s) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestSource.cs:line 48
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource.GetSyntaxTrees(CSharpParseOptions parseOptions, String sourceFileName) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestSource.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilationCore(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable, Nullable`1 experimentalFeature) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 1095
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 1083
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, TargetFramework targetFramework, String assemblyName, String sourceFileName, Boolean skipUsesIsNullable) in c:\Users\rikki\src\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 1074
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.RecordTests.CreateCompilation(CSharpTestSource source) in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\RecordTests.cs:line 26
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.RecordTests.SealedIncomplete() in c:\Users\rikki\src\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\RecordTests.cs:line 46
```

I think maybe the parser is breaking invariants of syntax trees--dropping a token by accident, maybe?

Should we fix in 16.9? @jaredpar

**Comment by Youssef1313** [comment]
> I think maybe the parser is breaking invariants of syntax trees--dropping a token by accident, maybe?

@RikkiGibson That sounds correct.

![image](https://user-images.githubusercontent.com/31348972/109701027-3dafa280-7b9b-11eb-9da0-7fd1cbd888ff.png)

**Comment by RikkiGibson** [comment]
I think the issue may be specific to `sealed record(` rather than `public record(` or `record(`.
