### ISSUE TITLE
CSharpMatchFolderAndNamespaceDiagnosticAnalyzer throws exception

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#51602]
installed .NET 6 preview SDK

Opened default console app in VS 2019.10 Preview 1

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: net6-analyzers-bug
SyntaxTree: C:\source\jmarolf\scratch\net6-analyzers-bug\Program.cs
SyntaxNode: namespace ConsoleCore { class Program ... [NamespaceDeclarationSyntax]@[15..173) (1,0)-(9,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by CyrusNajmabadi** [comment]
Looks like a bug in PathUtilities.GetRelativePath.  That function should never throw an index out of range.

**Comment by benaadams** [comment]
Have 20 of these errors since upgrading
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: AoA.Compressor
SyntaxTree: D:\Work\AoA\tools\AoA.Compressor\Program.cs
SyntaxNode: namespace AoA.Compressor { class ... [NamespaceDeclarationSyntax]@[65..955) (4,0)-(30,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
```
![image](https://user-images.githubusercontent.com/1142958/111056227-52324b80-8475-11eb-9c69-27863b8fd435.png)

**Comment by benaadams** [comment]
Doesn't looks like the method has changed in 4 years, so is a bit odd.

**Comment by tmat** [comment]
The issue is with the following inputs:
`GetRelativePath(@“C:\A\B\”, @”C:\A\B”)`

**Comment by benaadams** [comment]
I get 594 of these errors when opening [dotnet/aspnetcore/Servers/Kestrel](https://github.com/dotnet/aspnetcore/tree/main/src/Servers/Kestrel)

![image](https://user-images.githubusercontent.com/1142958/112734017-10a4a480-8f3b-11eb-93cd-3d855516dfe2.png)

**Comment by gakera** [comment]
I'm getting this error on Microsoft Visual Studio Enterprise 2022 Preview (64-bit), how do apply the fix?

**Comment by ryzngard** [comment]
@gakera the fix will be coming in Preview 2 for VS 2022

**Comment by george-tsiros** [comment]
For what it's worth, I am getting internal errors like this in preview 4.1
```cs
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: key'.
Exception occurred with following context:
Compilation: Engine5
IOperation: PropertyReference
SyntaxTree: C:\projects\source\Engine\Engine5\GlWindowBase.cs
SyntaxNode: Window [IdentifierNameSyntax]@[621..627) (29,8)-(29,14)

System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.SymbolIsAnnotatedAsPreview(ISymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttribute)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.SymbolIsAnnotatedOrUsesPreviewTypes(ISymbol symbol, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol, ISymbol& referencedPreviewSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.OperationUsesPreviewFeatures(OperationAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol, ISymbol& referencedPreviewSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.BuildSymbolInformationFromOperations(OperationAnalysisContext context, ConcurrentDictionary`2 requiresPreviewFeaturesSymbols, INamedTypeSymbol previewFeatureAttributeSymbol)
   at Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer.<>c__DisplayClass26_0.<Initialize>b__1(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA2252	Engine5		1	Active
```

**Comment by CyrusNajmabadi** [comment]
@george-tsiros that is about a different analyzer. Please open a new issue for that.
