### ISSUE TITLE
EditSession.EmitSolutionUpdateAsync can null ref for source generated documents

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#51681]
Stack trace:

```C#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.<>c.<EmitSolutionUpdateAsync>b__31_1(ValueTuple`2 lineChange, Project project) in src\Features\Core\Portable\EditAndContinue\EditSession.cs:line 874
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TArg,TResult](ImmutableArray`1 items, Func`3 selector, TArg arg)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.SelectAsArray[TItem,TArg,TResult](ImmutableArray`1 items, Func`3 map, TArg arg) in src\Compilers\Core\Portable\Collections\ImmutableArrayExtensions.cs:line 154        
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, SolutionActiveStatementSpanProvider solutionActiveStatementSpanProvider, CancellationToken cancellationToken) in src\Features\Core\Portable\EditAndContinue\EditSession.cs:line 872
```

`GetDocument` may return null for source generated documents here: https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/EditAndContinue/EditSession.cs#L874

**Comment by pranavkm** [comment]
This has since been fixed.
