### ISSUE TITLE
Renaming not working correctly for JavaScript in cshtml file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51752]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Renaming-not-working-correctly-for-JavaS/1340535)._

---
[severity:Other]
Hi I am working in asp.net C# mvc project and the renaming  feature which comes from using Ctrl+r Ctrl+r to rename variable name where its all used but its not working there but if I use it in a javascript file then its works and renames the variables please check this error and fix it

---
#### Feedback Bot on 2/17/2021, 11:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
An exception from the activity log per the internal conversation:

```
<description>System.InvalidOperationException: Sequence contains more than one element
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
</description>
```

**Comment by CyrusNajmabadi** [comment]
Rename in javascript would be need to be handled by the TS/JS team.  Closing out as we haven't heard more reports about thsi.
