### ISSUE TITLE
Flaky test - Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.MetadataReference

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51784]
Link to test - http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.IntegrationTests/Workspace/WorkspacesNetCore.cs,a3b2c5efc14b7bf4

Has been failing a few times over the past few days:
https://dev.azure.com/dnceng/public/_build/results?buildId=1031089&view=ms.vss-test-web.build-test-results-tab&runId=32004246&resultId=100627&paneView=debug

Error message:
```
Assert.Contains() Failure
Not found: struct name
In value:  identifier
```

Stack trace:
```
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CurrentTokenType(String tokenType) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/TextViewWindow_OutOfProc.Verifier.cs:line 125
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspaceBase.MetadataReference() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspaceBase.cs:line 60
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.MetadataReference() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:line 49
```

**Comment by allisonchou** [comment]
Failed again here - https://dev.azure.com/dnceng/public/_build/results?buildId=1035604&view=ms.vss-test-web.build-test-results-tab&runId=32127480&resultId=100616&paneView=debug

**Comment by sharwell** [comment]
The failure in 20210310.4 is serious:
![image](https://user-images.githubusercontent.com/1408396/110970345-82aba580-830e-11eb-92a1-eff2a8452610.png)

**Comment by sharwell** [comment]
Asset synchronization is broken again

```
03/10/2021 13:29:43 Coordinated Universal Time: Error : 10 :System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Differences detected in solution checksum: assets only in new solutoin but not in the request
4Pirq6SkuXhyorIF3i+g6DqkkUs=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
yn/DKz6XTcGVX1VKiWBEmeGqqiI=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
GB8i6Td6/zG+l0BOr38yjplZmKE=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
xRZrCEsYx24GcSB7mIRhMIiy6rE=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
kXqkqKcc8G3qQkhd7SKZ2JgIo6k=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the incremental solution but not in the request
4Pirq6SkuXhyorIF3i+g6DqkkUs=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
yn/DKz6XTcGVX1VKiWBEmeGqqiI=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
GB8i6Td6/zG+l0BOr38yjplZmKE=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
xRZrCEsYx24GcSB7mIRhMIiy6rE=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
kXqkqKcc8G3qQkhd7SKZ2JgIo6k=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the request but not in new solution
Pw0SJ8Fc6HZ2S1XSZGD5+GZmTP8=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
vFJId86WTiNaeRT/Ni4Mk/b3ftc=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
x4lgMyQB69L0OtojiehLWtahk00=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
f0ukll2Oaqa86QK9IyE1KqWZZtk=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
J+hXYrBMPB1UmEwfcbspr9dyziA=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the request but not in incremental solution
Pw0SJ8Fc6HZ2S1XSZGD5+GZmTP8=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
vFJId86WTiNaeRT/Ni4Mk/b3ftc=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
x4lgMyQB69L0OtojiehLWtahk00=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
f0ukll2Oaqa86QK9IyE1KqWZZtk=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
J+hXYrBMPB1UmEwfcbspr9dyziA=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference



   at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs:line 25
   at System.Diagnostics.TraceInternal.Fail(String message)
   at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetSolutionAsync>d__12.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 73
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Differences detected in solution checksum: assets only in new solutoin but not in the request
4Pirq6SkuXhyorIF3i+g6DqkkUs=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
yn/DKz6XTcGVX1VKiWBEmeGqqiI=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
GB8i6Td6/zG+l0BOr38yjplZmKE=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
xRZrCEsYx24GcSB7mIRhMIiy6rE=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
kXqkqKcc8G3qQkhd7SKZ2JgIo6k=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the incremental solution but not in the request
4Pirq6SkuXhyorIF3i+g6DqkkUs=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
yn/DKz6XTcGVX1VKiWBEmeGqqiI=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
GB8i6Td6/zG+l0BOr38yjplZmKE=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
xRZrCEsYx24GcSB7mIRhMIiy6rE=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
kXqkqKcc8G3qQkhd7SKZ2JgIo6k=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the request but not in new solution
Pw0SJ8Fc6HZ2S1XSZGD5+GZmTP8=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
vFJId86WTiNaeRT/Ni4Mk/b3ftc=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
x4lgMyQB69L0OtojiehLWtahk00=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
f0ukll2Oaqa86QK9IyE1KqWZZtk=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
J+hXYrBMPB1UmEwfcbspr9dyziA=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference

assets only in the request but not in incremental solution
Pw0SJ8Fc6HZ2S1XSZGD5+GZmTP8=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
vFJId86WTiNaeRT/Ni4Mk/b3ftc=, Microsoft.CodeAnalysis.Serialization.ProjectChecksumCollection
x4lgMyQB69L0OtojiehLWtahk00=, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums
f0ukll2Oaqa86QK9IyE1KqWZZtk=, Microsoft.CodeAnalysis.Serialization.MetadataReferenceChecksumCollection
J+hXYrBMPB1UmEwfcbspr9dyziA=, Microsoft.CodeAnalysis.Serialization.SerializerService+SerializedMetadataReference



   at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs:line 25
   at System.Diagnostics.TraceInternal.Fail(String message)
   at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetSolutionAsync>d__12.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 73<---
, GetDocumentHighlightsAsync, 6
```

**Comment by allisonchou** [comment]
Failed again here: https://dev.azure.com/dnceng/public/_build/results?buildId=1040265&view=ms.vss-test-web.build-test-results-tab&runId=32231498&resultId=100616&paneView=debug

@sharwell Who would be the best person on the team to reach out about this issue?
