### ISSUE TITLE
Flaky test - Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesDesktop.ProjectProperties

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51783]
Link to test - http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.IntegrationTests/Workspace/WorkspacesDesktop.cs,42

Noticed this one a few times over the past few days:
https://dev.azure.com/dnceng/public/_build/results?buildId=1031089&view=ms.vss-test-web.build-test-results-tab&runId=32030968&resultId=100619&paneView=debug

Error messsage:
```
Assert.Equal() Failure
↓ (pos 0)
Expected: Sub Program.M(p As Integer) (+ 1 overload···
Actual:

↑ (pos 0)
```

Stack trace:
```
at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspaceBase.ProjectProperties() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspaceBase.cs:line 99
   at Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesDesktop.ProjectProperties() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesDesktop.cs:line 47
```

**Comment by JoeRobich** [comment]
unskipping this test is being tracked by https://github.com/dotnet/roslyn/issues/64672
