### ISSUE TITLE
Flaky test - Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.BclMathCall

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51856]
Link to test: http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.IntegrationTests/CSharp/CSharpInteractive.cs,25

Have noticed this one failing a couple times over the past few days.

Error message:
```
System.Exception : Unable to find expected content in REPL within 10000 milliseconds and no exceptions were thrown.
Expected:
[[> ]]Actual:
[[Microsoft (R) Visual C# Interactive Compiler version 3.10.0-ci ()
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.

reset 64
Resetting execution engine.
]]
```

Stack trace:

```
Server stack trace: 
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForPredicate(Func`1 getValue, String expectedValue, Func`3 valueComparer) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 236
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.WaitForReplPrompt() in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 205
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.Reset(Boolean waitForPrompt) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 172
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.Reset(Boolean waitForPrompt)
   at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest.ClearInteractiveWindow() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractInteractiveWindowTest.cs:line 28
   at Roslyn.VisualStudio.IntegrationTests.AbstractInteractiveWindowTest.<InitializeAsync>d__1.MoveNext() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/AbstractInteractiveWindowTest.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by allisonchou** [comment]
Another failure here:
https://dev.azure.com/dnceng/public/_build/results?buildId=1037639&view=ms.vss-test-web.build-test-results-tab&runId=32171082&resultId=100324&paneView=debug

**Comment by jmarolf** [comment]
happened in a recent [run](https://dev.azure.com/dnceng/public/_build/results?buildId=1060871&view=ms.vss-test-web.build-test-results-tab&runId=32694542&resultId=100634&paneView=debug)

**Comment by Youssef1313** [comment]
Also in https://dev.azure.com/dnceng/public/_build/results?buildId=1062903&view=logs&j=cf757b30-6920-5b57-d4b8-8b599fbc5c5f&t=2213ea15-66b2-5fe4-0869-050835bf49d2

This should probably be re-opened.

FYI @sharwell

**Comment by Youssef1313** [comment]
> happened in a recent [run](https://dev.azure.com/dnceng/public/_build/results?buildId=1060871&view=ms.vss-test-web.build-test-results-tab&runId=32694542&resultId=100634&paneView=debug)

@jmarolf Did you mean to comment on https://github.com/dotnet/roslyn/issues/51783 or copied a wrong link?

**Comment by sharwell** [comment]
someone needs to modify the test to force the interactive host process to crash when this test fails. We already have tools in place to capture that crash dump and attach it to the build

**Comment by Youssef1313** [comment]
@sharwell Can you re-open to track that? The test failure rate seems to be high.

**Comment by sharwell** [comment]
@Youssef1313 can you file a new issue for that? Previously some failures were caused by a short timeout. The new issue is a case where either VS or the interactive host process is either hanging or crashing.
