### ISSUE TITLE
ArgumentOutOfRangeException in InteractiveWindow.UIThreadOnly.IndentCurrentLine

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5224]
In C# interactive, type:
```
> int foo = 1;
> double foo()
. {
.     return 1.1;
. }
> Console.WriteLine(foo);
```
observe:
```(1,19): error CS1503: Argument 1: cannot convert from 'method group' to 'bool'```

now type:
Alt + Up

modify to add "()":
```> Console.WriteLine(foo());```

Press Ctrl + Enter (cursor after "foo()")

**RESULTS:**
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.VisualStudio.Text.Utilities.FrugalList`1.get_Item(Int32 index)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionSnapshot.MapToSourceSnapshot(Int32 position)
   at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapDownToInsertionPoint(SnapshotPoint position, PointTrackingMode trackingMode, Predicate`1 match)
   at Microsoft.VisualStudio.Text.Implementation.MappingPoint.GetInsertionPoint(Predicate`1 match)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveSmartIndenter.GetDesiredIndentation(ITextSnapshotLine line)
   at Microsoft.VisualStudio.Text.Editor.Implementation.SmartIndentationService.GetDesiredIndentation(ITextView textView, ITextSnapshotLine line)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.IndentCurrentLine(SnapshotPoint caretPosition)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.CaretPositionChanged(Object sender, CaretPositionChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by tmat** [comment]
I think this is expected. Method "foo" hides variable "foo". "foo" in Console.WriteLine always refers to the method group.

**Comment by KevinH-MS** [comment]
Yeah, the error is expected, but the crash is not (sorry, I'm still trying to get attached so I can link to a dump...I'm currently just getting a modal dialog saying to check the ActivityLog).

**Comment by tmat** [comment]
Ah, there is a crash... that's certainly not expected :)

**Comment by KevinH-MS** [comment]
@amcasey, you were looking at an issue with MapDownToInsertionPoint, weren't you?  Does this look same/similar?

**Comment by amcasey** [comment]
Looks like a dup of https://github.com/dotnet/roslyn/issues/5141, which I'm working on now.  I'll confirm that this is fixed too.

**Comment by amcasey** [comment]
As with #5141, the root cause is internal bug 144964.

**Comment by amcasey** [comment]
Should not repro, as of https://github.com/dotnet/roslyn/commit/6e515e6ee4a74ba398a7311c58b08e99d7a41b8d.
