### ISSUE TITLE
Crash navigating to location in generate code right after opening VS.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#52698]
This was the oder of operations i did.

1. navigate-to to RecordDeclarationSyntax.
2. this took to me the partial part that is *not* generated.
3. i then opened up the nav-bar (which tool a little time since the solution was loading) and navigated to one of the props of this type in generated code (maybe 'semicolontoken'?)
4. Crash:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Collections.Comparer.Compare(System.Object, System.Object)
   at System.Collections.Immutable.ImmutableSortedDictionary`2+Node[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Search(System.__Canon, System.Collections.Generic.IComparer`1<System.__Canon>)
   at System.Collections.Immutable.ImmutableSortedDictionary`2+Node[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TryGetValue(System.__Canon, System.Collections.Generic.IComparer`1<System.__Canon>, System.__Canon ByRef)
   at Microsoft.CodeAnalysis.SolutionState.GetDocumentState(Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.CodeAnalysis.Solution.GetDocument(Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.CodeAnalysis.Editor.FindUsages.DefinitionItemExtensions+<ToDefinitionItemAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Threading.Tasks.Task`1<System.__Canon>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.FindUsages.DefinitionItemExtensions.ToNonClassifiedDefinitionItem(Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.Solution, Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioSymbolNavigationService.TryNotifyForSpecificSymbol(Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.Solution, System.Threading.CancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioSymbolNavigationService.TrySymbolNavigationNotify(Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Extensibility.NavigationBar.AbstractEditorNavigationBarItemService.NavigateToSymbolItem(Microsoft.CodeAnalysis.Document, SymbolItem, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.NavigationBar.CSharpEditorNavigationBarItemService.NavigateToItem(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Editor.WrappedNavigationBarItem, 
```

**Comment by CyrusNajmabadi** [comment]
Watson bucket:

```
Fault bucket 1710005495247580638, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 17.0.31214.86
P3: 5ce869ec
P4: mscorlib
P5: 4.8.4300.0
P6: 5f7e60da
P7: 3715
P8: 6e
P9: System.ArgumentException
P10: 

Attached files:
\\?\C:\Users\cyrusn\AppData\Roaming\microsoft\visualstudio\17.0_d715e233\activitylog.xml
\\?\C:\Users\cyrusn\AppData\Local\microsoft\visualstudio\17.0_d715e233\devenv.exe.config
\\?\C:\Program Files\Microsoft Visual Studio\17\Preview\Common7\IDE\devenv.isolation.ini
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B93.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER878A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER879B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER87A9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER87C9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_b8ebccf3b2a42d6eb8feb1bd58331639fafb5d7_26b9c011_e3725fae-9544-4a2f-b3a3-87efa005f184

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5ec85ad6-d3b6-44e3-90a3-ba8296ecb807
Report Status: 268435456
Hashed bucket: 28572bee76d70b20c7bb28f01c32adde
Cab Guid: 0
```
