### ISSUE TITLE
Nested non-root .editorconfig file fails to open

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53081]
**Version Used**: 16.10.P2.1

When I double-click the nested .editorconfig file, it cycles between a simple message box saying "Sequence contains no elements" and this stack trace. In neither case does it open the .editorconfig file.

The root .editorconfig that is a solution item opens just file.

![image](https://user-images.githubusercontent.com/8040367/116790164-e76abd00-aa80-11eb-8f39-0b48cb67d0f6.png)

I found https://github.com/dotnet/roslyn/issues/52668 and https://github.com/dotnet/roslyn/issues/52716#issuecomment-822658635, but @jmarolf said in the latter comment that this issue applied when you don't have a solution open. I definitely have a managed project loaded as you can see in the screenshot.

```
An error occurred while initializing the frame's content
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray)
   at Microsoft.CodeAnalysis.Editor.EditorConfigSettings.DataProvider.SettingsProviderBase`4.Update()
   at Microsoft.CodeAnalysis.Editor.EditorConfigSettings.DataProvider.Formatting.CommonFormattingSettingsProviderFactory.GetForFile(String filePath)
   at Microsoft.CodeAnalysis.Editor.EditorConfigSettings.DataProvider.CombinedOptionsProviderFactory`1.GetForFile(String filePath)
   at Microsoft.CodeAnalysis.Editor.EditorConfigSettings.SettingsAggregator.GetSettingsProvider[TData](String fileName)
   at Microsoft.VisualStudio.LanguageServices.EditorConfigSettings.SettingsEditorPane.<Initialize>g__GetFormattingView|12_0()
   at Microsoft.VisualStudio.LanguageServices.EditorConfigSettings.SettingsEditorPane.Initialize()
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsWindowPane.SetSite(IServiceProvider psp)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.SetUIElementSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)
```

**Comment by Youssef1313** [comment]
The crash was recently fixed. However, I think the issue that no project is found remains. It now just bails out silently as far as I understand.

https://github.com/dotnet/roslyn/blob/9dc51cfd0b45ff87c595bd35d4edb65b743930f9/src/EditorFeatures/Core/EditorConfigSettings/DataProvider/SettingsProviderBase.cs#L46

At this point, projects shouldn't be empty.

I'm also wondering the following line:

https://github.com/dotnet/roslyn/blob/9dc51cfd0b45ff87c595bd35d4edb65b743930f9/src/EditorFeatures/Core/EditorConfigSettings/DataProvider/SettingsProviderBase.cs#L47

If we have multiple projects, we're literally picking up a random one. What are the behavioral changes that depends on the project?

**Comment by jmarolf** [comment]
cannot reproduce, I believe this was fixed

**Comment by Youssef1313** [comment]
@jmarolf This does repro for me in VS 17.0 P2.1, but as a blank page instead of crash for the reason I stated earlier.

![image](https://user-images.githubusercontent.com/31348972/128065407-30c63516-6831-4c62-b42a-cbaa09d010eb.png)

Repro steps:

1. `git clone https://github.com/Techsola/InstantReplay`
2. `get reset --hard 290e27f1b73c71da602666b98ce3d105e3f0ab2b`
3. From solution explorer, `Techsola.InstantReplay` → `Native` → `.editorconfig`.

**Comment by jmarolf** [comment]
tracking as part of https://github.com/dotnet/roslyn/issues/54568
