### ISSUE TITLE
Crashing when using Analyze & Suppress

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53160]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Crashing-when-using-Analyze--Suppress/1409120)._

---
[severity:My work is severely impacted or blocked (internal MSFT only)]
Visual Studio 2019 is continually crashing when running the Analyze & Suppress build step. Often times (but not always) the GlobalSuppressions.cs file is generated, but Visual Studio crashes before it can be added to the project. I am unable to reproduce the issue using the step recorder but I do have a crash dump from windbg I can provide.

---
#### Adam Meltzer [MSFT] on 4/27/2021, 11:17 AM: 

(private comment, text removed)
#### null on 4/27/2021, 07:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sam Harwell [MSFT] on 4/29/2021, 07:20 AM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal “steps to reproduce”. We created a set of instructions for providing additional information which will help us track down the true source of the problems.</p>
<p>Based on the information provided so far, the most likely scenario to follow is for “Crashes”. Please take a look at the following document to provide the feedback most relevant for the problems you would like to see fixed: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#crashes">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#crashes</a></p>

#### Adam Meltzer [MSFT] on 4/30/2021, 05:19 PM: 

(private comment, text removed)
#### Adam Meltzer [MSFT] on 5/4/2021, 03:53 PM: 

(private comment, text removed)
#### Adam Meltzer [MSFT] on 5/4/2021, 04:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Here's a stack trace of the exception:

```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.GlobalUndoServiceFactory.WorkspaceUndoTransaction.Commit()
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, ImmutableArray`1 operations, String title, IProgressTracker progressTracker, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Suppression.VisualStudioSuppressionFixService.<>c__DisplayClass21_0.<ApplySuppressionFix>g__applyFix|1(IWaitContext context)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Suppression.VisualStudioSuppressionFixService.<>c__DisplayClass23_0.<InvokeWithWaitDialog>b__0(IWaitContext waitContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Boolean showProgress, Action`1 action)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Suppression.VisualStudioSuppressionFixService.InvokeWithWaitDialog(Action`1 action, String waitDialogTitle, String waitDialogMessage)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Suppression.VisualStudioSuppressionFixService.ApplySuppressionFix(IEnumerable`1 diagnosticsToFix, Func`2 shouldFixInProject, Boolean filterStaleDiagnostics, Boolean isAddSuppression, Boolean isSuppressionInSource, Boolean onlyCompilerDiagnostics, Boolean showPreviewChangesDialog)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Suppression.VisualStudioSuppressionFixService.AddSuppressions(IVsHierarchy projectHierarchyOpt)
   at Microsoft.CodeAnalysis.ExternalAccess.LegacyCodeAnalysis.LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.AddSuppressions(IVsHierarchy projectHierarchyOpt)
   at Microsoft.VisualStudio.CodeAnalysis.MenuHandlers.<>c__DisplayClass89_0.<CreateSuppression>b__1()
   at Microsoft.VisualStudio.Shell.ThreadHelper.InvokeInternal(Action action, Boolean fromInvokeAsync)
   at Microsoft.VisualStudio.CodeAnalysis.MenuHandlers.<>c__DisplayClass89_0.<<CreateSuppression>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by sharwell** [comment]
This call to `CloseLinkedUndo` is returning `E_FAIL`:

https://github.com/dotnet/roslyn/blob/40f149dd8243658f17680f12dbcb84141ec1a65c/src/VisualStudio/Core/Def/Implementation/Workspace/GlobalUndoServiceFactory.WorkspaceGlobalUndoTransaction.cs#L101-L108

**Comment by ameltzerMSFT** [comment]
It appears that in most cases when this crash occurs that the GlobalSuppressions.cs file _is_ created, but it's not added to the project (I'm assuming it crashes before it gets to that point). When I reload Visual Studio I can manually add the .cs file.

**Comment by sharwell** [comment]
The action item here is to update this method to catch exceptions and _show a gold bar_ indicating the failure occurred.

https://github.com/dotnet/roslyn/blob/40f149dd8243658f17680f12dbcb84141ec1a65c/src/VisualStudio/Core/Def/ExternalAccess/LegacyCodeAnalysis/LegacyCodeAnalysisVisualStudioSuppressionFixServiceAccessor.cs#L28-L29

@CyrusNajmabadi @tmat @ryzngard do you know what error handler we can use that reports telemetry and shows the gold bar?

**Comment by ryzngard** [comment]
@sharwell what telemetry do you want? The error handler reports telemetry with https://github.com/dotnet/roslyn/blob/9dc51cfd0b45ff87c595bd35d4edb65b743930f9/src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioErrorReportingService.cs#L30 

It will have the message passed to `IErrorReportingService` as the message of the telemetry

**Comment by sharwell** [comment]
@ryzngard `IErrorReportingService` is what I was looking for, thanks!
