### ISSUE TITLE
MakeLocalFunctionStaticCodeRefactoringProvider crashes casting LocalFunctionSymbol to SynthesizedSimpleProgramEntryPointSymbol

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53179]
**Version Used**: 16.10-p2.1

```cs
void M<SomeTypeParameter>(
    SomeClass a,
    SomeStruct b,
    SomeRecord c,
    SomeEnum d,
    SomeInterface e,
    SomeDelegate f,
    SomeTypeParameter g)
{
}

class SomeClass { }
struct SomeStruct { }
record SomeRecord;
enum SomeEnum { }
interface SomeInterface { }
delegate void SomeDelegate();
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/8040367/117175660-147ae080-ad9d-11eb-93de-6824594c009a.png)

> System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.LocalFunctionSymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedSimpleProgramEntryPointSymbol'.

```
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgram(CompilationUnitSyntax compilationUnit,BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax,BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindMethodBody(CSharpSyntaxNode node,BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder,CSharpSyntaxNode node,BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetUpperBoundNode(CSharpSyntaxNode node,Boolean promoteToBindable)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundRoot()
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.RegionAnalysisContext(StatementSyntax firstStatement,StatementSyntax lastStatement)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.AnalyzeDataFlow(StatementSyntax firstStatement,StatementSyntax lastStatement)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AnalyzeDataFlow(StatementSyntax statement)
   at Microsoft.CodeAnalysis.CSharp.MakeLocalFunctionStatic.MakeLocalFunctionStaticHelper.TryGetDataFlowAnalysis(LocalFunctionStatementSyntax localFunction,SemanticModel semanticModel,DataFlowAnalysis& dataFlow)
   at Microsoft.CodeAnalysis.CSharp.MakeLocalFunctionStatic.MakeLocalFunctionStaticHelper.CanMakeLocalFunctionStaticByRefactoringCaptures(LocalFunctionStatementSyntax localFunction,SemanticModel semanticModel,ImmutableArray`1& captures)
   at async Microsoft.CodeAnalysis.CSharp.MakeLocalFunctionStatic.MakeLocalFunctionStaticCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
It's not the same stacktrace as https://github.com/dotnet/roslyn/issues/47173, but is the same cast failing.

cc @AlekseyTs since I don't think this is an issue in the code refactoring itself. It just called AnalyzeDataFlow on the local function.

**Comment by jcouv** [comment]
This seems to have been fixed. It shares the last portion of stacktrace with https://github.com/dotnet/roslyn/issues/47467 which was fixed.
Tried with dev17.0-p4 and the issue didn't repro. Instead, I get correctly offered some suggestions to make the local function static.
However, the refactoring doesn't have any effect. That is an IDE issue. I'll have a fix shortly.
