### ISSUE TITLE
Running ServiceHub on coreclr throws unsupported exception

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#53651]
When running Roslyn OOP on .Net 6 host, it throws unsupport exception 

"The type initializer for 'Microsoft.Win32.Registry' threw an exception." 

```
at Microsoft.VisualStudio.Utilities.Internal.RegistryTools.GetRegistryValueFromCurrentUserRoot(String regKeyPath, String regKeyName, Object defaultOnError)
   at Microsoft.VisualStudio.Telemetry.WindowsInternalSettings.GetUserEventTag()
   at Microsoft.VisualStudio.Telemetry.WindowsInternalSettings..ctor(IDiagnosticTelemetry diagnosticTelemetry, IRegistryTools registryTools)
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.GetInternalSettings(IDiagnosticTelemetry diagnosticTelemetry, IRegistryTools registryTools)
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.BuildInitializer(TelemetrySessionSettings telemetrySessionSettings)
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.FromSessionSettings(TelemetrySessionSettings telemetrySessionSettings)
   at Microsoft.VisualStudio.Telemetry.TelemetrySession..ctor(TelemetrySessionSettings telemetrySessionSettings)
   at Microsoft.VisualStudio.Telemetry.TelemetrySession..ctor(String serializedSession)
   at Microsoft.CodeAnalysis.Remote.RemoteHostService.<>c__DisplayClass7_0.<InitializeTelemetrySession>b__0() in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Services\Host\RemoteHostService.cs:line 121
   at Microsoft.CodeAnalysis.Remote.ServiceBase.RunService(Action call, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Services\ServiceBase.cs:line 155
   at Microsoft.CodeAnalysis.Remote.RemoteHostService.InitializeTelemetrySession(Int32 hostProcessId, String serializedSession, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Services\Host\RemoteHostService.cs:line 116
```

inner exception:

"Registry is not supported on this platform."
```
   at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)
   at Microsoft.Win32.RegistryKey.OpenBaseKey(RegistryHive hKey, RegistryView view)
   at Microsoft.Win32.Registry..cctor()
```

**Comment by genlu** [comment]
This is caused by deploying netstandard2.0 version of MS.win32.registry as part of our vsix, exclude it and using the one from runtime fixed it.
