### ISSUE TITLE
CSharpGenerateVariableCodeFixProvider crashed with ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53686]
**Version Used**: VS 16.10.0

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.InsertRange(Int32 index,IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertParameters(SyntaxNode declaration,Int32 index,IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditorExtensions.<>c__DisplayClass14_0.<InsertParameter>b__0(SyntaxNode d,SyntaxGenerator g)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.AddParameter.AddParameterService.AddParameterAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by davidwengier** [comment]
Can't seem to repro this. Don't suppose you know what the code you were triggering this on was @jnm2 ?

**Comment by Youssef1313** [comment]
Likely duplicate of #47586. @davidwengier There is a repro in https://github.com/dotnet/roslyn/issues/47586#issuecomment-690372276.

**Comment by jnm2** [comment]
@davidwengier I wasn't able to figure it out at the time, sorry. Looks like a duplicate to me too, so I'll close.

**Comment by davidwengier** [comment]
Thanks @Youssef1313 and @jnm2 

Fix is in https://github.com/dotnet/roslyn/pull/56397
