### ISSUE TITLE
Searching with Ctrl+Q gives me a `Navigate to` internal error

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#53813]
**Version Used**: 
Visual Studio 2019 Preview 16.10 Preview 4
**Steps to Reproduce**:

1. Typed Ctrl+Q and started typing `codelens` so I can disable it.
2. Received the following gold bar: 
![image](https://user-images.githubusercontent.com/46729679/120375900-24201300-c2d0-11eb-8c00-b207b6512b2b.png)

Stack Trace: 

```
StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
      at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass3_0.<<GetCallback>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<AddResultIfMatchAsync>d__20.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessIndexAsync>d__19.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentAsync>d__16.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentsAsync>d__15.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<FindSearchResultsAsync>d__14.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass6_0.<<SearchFullyLoadedProjectAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()
```

**Comment by mikadumont** [comment]
@CyrusNajmabadi

**Comment by sharwell** [comment]
@tmat For some reason we're losing inner stack traces for exceptions that go over remoting _more than once_.

**Comment by tmat** [comment]
@AArnott

**Comment by AArnott** [comment]
Yes. I think if you're using brokered services to initialize JsonRpc it's on by default. For other cases, you have to opt in by setting `JsonRpc.ExceptionStrategy = ExceptionProcessing.ISerializable`. That *might* do the trick here for you.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I'm happy to try adding the code to get better exceptions in teh future in case it happens again.  However, this is currently unactionable in it's current form.  AFAICT< this is crashing on the OOP side when we literally are trying to get back the callback channel to send resutls back to VS with.  If that step fails i genuinely don't know what we could do as that means our communication mechanism is completely borked and any further processing is meaningless.

**Comment by CyrusNajmabadi** [comment]
I'm going to close this otu as non-actionable currenlty.  https://github.com/dotnet/roslyn/pull/53839 was opened to collect more data to help us rack this down though.

**Comment by Youssef1313** [comment]
I'm hitting this a lot in 16.10.0.
