### ISSUE TITLE
Script Document IntelliSense race condition

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5390]
SSL reported:

Source: (in a `Script` document):

```C#
if (someSequence.Count() > 2)
IEnumerable<int> RandomStream(int max) {
    yield return int.
```

Pressing Ctrl+Space, Space, or Enter will try to consume a cancelled Model task in the completion controller and throw.

Stack:

```
 System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions) Unknown
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Unknown
 System.Threading.Tasks.Task.Wait(System.Threading.CancellationToken cancellationToken) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.WaitForModel() Unknown
> Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnEnter(out bool sendThrough, out bool committed) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>.AnonymousMethod__7() Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(Microsoft.CodeAnalysis.Editor.CommandArgs args, System.Action nextHandler, System.Threading.CancellationToken cancellationToken) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>.AnonymousMethod__7() Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Formatting.Indentation.AbstractSmartTokenFormatterCommandHandler.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>.AnonymousMethod__7() Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action nextHandler) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>(System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>> commandHandlers, Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action lastHandler) Unknown
 Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute<Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs>(Microsoft.VisualStudio.Utilities.IContentType contentType, Microsoft.CodeAnalysis.Editor.Commands.ReturnKeyCommandArgs args, System.Action lastHandler) Unknown
 Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteReturn(Microsoft.VisualStudio.Text.ITextBuffer subjectBuffer, Microsoft.VisualStudio.Utilities.IContentType contentType, System.Action executeNextCommandTarget) Line 638 C#
```

**Comment by amcasey** [comment]
Was http://roslyn.codeplex.com/workitem/488.  FYI @slaks.

**Comment by amcasey** [comment]
[1/11/2015 10:37:06 AM] SSL commented: This is completely reproducible in VSEmbed or my Markdown editor, and probably also in any other Script editor.

**Comment by amcasey** [comment]
@Pilchie noted:

When I paste this code into a csx file in ETA, I get a bunch of exceptions from:
```
System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.BuckStopsHereBinder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\BuckStopsHereBinder.cs:line 131
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.BindYieldReturnStatement(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 192
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 112
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1636
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 2066
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1394
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 896
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 775
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 175
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 507
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 443
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions.IsEnumTypeMemberAccessContext(SyntaxTree syntaxTree, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ContextQuery\SyntaxTreeExtensions.cs:line 2372
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ContextQuery\CSharpSyntaxContext.cs:line 190
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.KeywordCompletionProvider.<CreateContextAsync>d__6.MoveNext() in D:\Roslyn\Main\Open\src\Features\CSharp\Completion\CompletionProviders\KeywordCompletionProvider.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<RecommendKeywordsAsync>d__9.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<>c__DisplayClass6_0.<<GetItemsWorkerAsync>b__0>d.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetUnionResultsFromDocumentAndLinks>d__3`1.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DocumentExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<GetItemsWorkerAsync>d__6.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in D:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in D:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
2/19/2015 1:35:23 PM
Source: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: Microsoft.CodeAnalysis.CSharp
StackTrace:    at Microsoft.CodeAnalysis.CSharp.BuckStopsHereBinder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\BuckStopsHereBinder.cs:line 131
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.GetIteratorElementType(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 251
   at Microsoft.CodeAnalysis.CSharp.Binder.BindYieldReturnStatement(YieldStatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 192
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 112
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1636
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 2066
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1394
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 896
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 775
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 175
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 507
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 443
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTreeExtensions.IsEnumTypeMemberAccessContext(SyntaxTree syntaxTree, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ContextQuery\SyntaxTreeExtensions.cs:line 2372
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ContextQuery\CSharpSyntaxContext.cs:line 190
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.KeywordCompletionProvider.<CreateContextAsync>d__6.MoveNext() in D:\Roslyn\Main\Open\src\Features\CSharp\Completion\CompletionProviders\KeywordCompletionProvider.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<RecommendKeywordsAsync>d__9.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<>c__DisplayClass6_0.<<GetItemsWorkerAsync>b__0>d.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetUnionResultsFromDocumentAndLinks>d__3`1.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DocumentExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<GetItemsWorkerAsync>d__6.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in D:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in D:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in D:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
```

**Comment by amcasey** [comment]
@slaks, can you please let us know if you see this in the final version of Update 1?

**Comment by amcasey** [comment]
No reports of further repros.
