### ISSUE TITLE
Errors after upgrading to .Net 6.0 preview

### ISSUE THREAD

**Issue by gpuchtel** [dotnet/roslyn#53914]
Hello, I'm getting errors after upgrading my .Net Framework to 6.0 (preview 4):

Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Core
SyntaxTree: D:\Cybernetics\Core\Either.cs
SyntaxNode: namespace Core { public class Left ... [NamespaceDeclarationSyntax]@[0..661) (0,0)-(32,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Core		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Cyborg
SyntaxTree: D:\Cybernetics\Cyborg\Startup.cs
SyntaxNode: namespace Cyborg { using Cyborg ... [NamespaceDeclarationSyntax]@[379..2418) (11,0)-(84,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Cyborg		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Cyborg
SyntaxTree: D:\Cybernetics\Cyborg\Program.cs
SyntaxNode: namespace Cyborg { public static ... [NamespaceDeclarationSyntax]@[100..471) (4,0)-(17,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Cyborg		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Cyborg
SyntaxTree: D:\Cybernetics\Cyborg\Player.cs
SyntaxNode: namespace Cyborg { using Cyborg ... [NamespaceDeclarationSyntax]@[334..2403) (14,0)-(94,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Cyborg		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Cyborg
SyntaxTree: D:\Cybernetics\Cyborg\Game.cs
SyntaxNode: namespace Cyborg { using Cyborg ... [NamespaceDeclarationSyntax]@[426..7400) (17,0)-(280,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Cyborg		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Core
SyntaxTree: D:\Cybernetics\Core\ValueObject.cs
SyntaxNode: namespace Core { public abstract ... [NamespaceDeclarationSyntax]@[0..662) (0,0)-(28,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Core		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Core
SyntaxTree: D:\Cybernetics\Core\Result`.cs
SyntaxNode: namespace Core { public class Result ... [NamespaceDeclarationSyntax]@[57..1368) (3,0)-(46,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Core		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Core
SyntaxTree: D:\Cybernetics\Core\Result.cs
SyntaxNode: namespace Core { public class Result ... [NamespaceDeclarationSyntax]@[17..1490) (2,0)-(54,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Core		1	Active
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Core
SyntaxTree: D:\Cybernetics\Core\Enumeration.cs
SyntaxNode: namespace Core { public abstract ... [NamespaceDeclarationSyntax]@[17..871) (2,0)-(30,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0130	Core		1	Active

**Actual Behavior**:

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/52912.

**Comment by gpuchtel** [comment]
@Youssef1313  Thanks for your reply, and I apologize in advance for what might be a silly question, but how does one get these fixes?

**Comment by Youssef1313** [comment]
@gpuchtel I believe you will get this fix in Visual Studio 16.11.

**Comment by gpuchtel** [comment]
@Youssef1313 thanks for the quick reply, guess I'll have to wait, cuz I'm already running 16.11

![image](https://user-images.githubusercontent.com/5240685/121068812-b9247f80-c79a-11eb-8d26-8c9f77bee514.png)

**Comment by Youssef1313** [comment]
@gpuchtel Yeah I think the backport (https://github.com/dotnet/roslyn/pull/53786) was merged after Preview 1 was released. So the fix will probably be in the next preview.

**Comment by jmarolf** [comment]
closed via https://github.com/dotnet/roslyn/pull/53786

This will ship in 16.11 Preview 2
