### ISSUE TITLE
crash in Outlining RegionCollector

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#541]
out of range exception in Region Collector. I have put dump in our dump folder 

dump directory name is 541
...

   at Microsoft.CodeAnalysis.SyntaxTriviaList.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Editor.CSharp.Outlining.DisabledTextTriviaOutliner.CollectOutliningSpans(SyntaxTree syntaxTree, SyntaxTrivia trivia, List`1 spans, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.CSharp.Outlining.DisabledTextTriviaOutliner.CollectOutliningSpans(Document document, SyntaxTrivia trivia, List`1 spans, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Outlining.RegionCollector.GetOutliningSpans(SyntaxTriviaList triviaList)
   at Microsoft.CodeAnalysis.Editor.Implementation.Outlining.RegionCollector.Collect(SyntaxNode root)
   at Microsoft.CodeAnalysis.Editor.Implementation.Outlining.AbstractOutliningService.<GetOutliningSpansAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Outlining.OutliningTaggerProvider.TagProducer.<ProduceTagsAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.<RecomputeTagsAsync>d__1.MoveNext()

**Comment by Pilchie** [comment]
Is this on the latest bits?  I fixed an issue here a while ago in TFS, but not in time for CTP5.

**Comment by Pilchie** [comment]
Confirmed that this was found on a build from before the fix I was thinking of.

**Comment by Pilchie** [comment]
@MattGal - can you try a new build and add the "Verified" label?
