### ISSUE TITLE
RenameTracking encountered an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/RenameTracking-encountered-an-error/1120075)._

---
I organize my Blazor Components in two files: a xxx.razor and a xxx.razor.cs. In the .cs file a use public partial class xxx.
Whe I try to rename the partial class in .cs I get the error:

System.InvalidOperationException : Rename Tracking could not update solution.
   at Roslyn.Utilities.Contract.Fail(String message)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForResetOfTypedIdentifier(Workspace workspace,Solution newSolution,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0. <InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)

---
#### Feedback Bot on 7/21/2020, 03:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/22/2020, 09:57 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/29/2020, 11:28 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Josef Bogad on 10/30/2020, 00:33 AM: 

<p>In Version 16.7.7 problem did not occur. Renaming an opended .razor file requires to close and reopen the file. Otherwise errors are shown inidcating that the class representing the razor component is not found. But thats OK for me.</p>

#### Feedback Bot on 2/24/2021, 06:02 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Josef Bogad on 4/16/2021, 02:28 AM: 

<p>Just updated to VS 2019 V16.9.4 and it happend again:</p>
<p>I renamed a Blazor Parameter and this happend:<br>
<img src="https://aka.ms/dc/image?name=B1bdc0b8831494bc5b57a8079452978c4637541621027418566_Screenshot_(8).png&amp;tid=1bdc0b8831494bc5b57a8079452978c4637541621027418566" alt="Screenshot (8).png"></p>
<p>‘RenameTrackingCodeRefactoringProvider’ encountered an error and has been disabled. Show Stack Trace Enable Enable and ignore future errors</p>
<p>Stacktrace:<br>
System.InvalidOperationException : Rename Tracking could not update solution.<br>
at Roslyn.Utilities.Contract.Fail(String message)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForResetOfTypedIdentifier(Workspace workspace,Solution newSolution,Int32 trackingSessionId)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray<code>1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken) at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray</code>1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)<br>
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass22_0.b__0()<br>
at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)</p>

#### Andrew Hall 🤘 [MSFT] on 6/9/2021, 01:21 PM: 

<p>I am unable to reproduce this issue with split razor/cs files in a simple project with 16.10. Are you still hitting this issue? If so, could you provide a solution?</p>
<p>There is also an experimental editor available in 16.10 in which I did hit a similar error, we will be investigating that separately since it wasn’t available in the version where this was filed.</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Josef Bogad on 6/10/2021, 06:33 AM: 

(private comment, text removed)
#### Andrew Hall 🤘 [MSFT] on 6/10/2021, 00:01 PM: 

<p>@<a target='_blank' href="https://developercommunity2.visualstudio.com/users/259962/JosefBogad.html">Josef Bogad</a> an example sln would be helpful. You’re saying this isn’t always happening? That does seem odd given the nature of the issue.</p>

#### Josef Bogad on 6/11/2021, 00:47 AM: 

<p><a target='_blank' href="https://developercommunity2.visualstudio.com/user/bf138afb-d2fd-4cf7-9db6-b9c90d1dec7f/profile">Andrew Hall 🤘 [MSFT]</a> Yes, its anoying. From my observations I suspect, that it’s a timing issue. I am working with an older notebook and I also observed that keyboard input suddly stops, VS gets stuck for a moment and than the characters appear in edit window. This was not in direct releation to problem. But may help. I had also problems with live share, which I finally disabled, but that produces other problems and exceptions.<br>
However I can work, but I have to restart VS more often.<br>
Unfortunately, as said before, I can’t reproduce that in a consistent manner, thus I have not idea how to create an example. The solution I am working on consists of over 30 projectes with DB access and over about 300 xUnit Unit tests.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as this was heavily rewritten.
