### ISSUE TITLE
'Add parameter' code fix crashes for the primary constructor of a record

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#54408]
**Version Used**: 16.10.2, 17.0.0-p1.1

```cs
var b = "B";
var r = new R(1, b[||]);

record R(int A);
```

💡 Add parameter to 'R(int)':

CSharpAddParameterCodeFixProvider crashes.

> System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index

```
   at Roslyn.Utilities.SpecializedCollections.Empty.List`1.get_Item(Int32 index)
   at async Microsoft.CodeAnalysis.AddParameter.AddParameterService.AddParameterAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddParameter.AbstractAddParameterCodeFixProvider`6.FixAsync[TArgumentSyntax,TAttributeArgumentSyntax,TArgumentListSyntax,TAttributeArgumentListSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Youssef1313** [comment]
I wrote a unit test, and it doesn't show a crash. However, it shows that the parameter doesn't get added. The crash may have been fixed unintentionally (as part of fixing another feature). I opened https://github.com/dotnet/roslyn/pull/54427 to address that.
