### ISSUE TITLE
An exception of type InvalidOperationException has been encountered

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54714]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/An-exception-of-type-InvalidOperationExc/1470161)._

---
! [image.png] (https://aka.ms/dc/image?name=B40fb5601b34b4a0fada6ca7009b8590b637612991538792146_20210707-165913-image.png&tid=40fb5601b34b4a0fada6ca7009b8590b637612991538792146)

```
System.InvalidOperationException: Token's parent was null
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxTokenExtensions.GetRequiredParent(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.GoToDefinition.CSharpGoToDefinitionSymbolService.GetTargetPositionIfControlFlow(SemanticModel semanticModel, SyntaxToken token)
   at Microsoft.CodeAnalysis.GoToDefinition.AbstractGoToDefinitionSymbolService.<GetTargetIfControlFlowAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.GoToDefinition.AbstractGoToDefinitionService.TryGoToDefinition(Document document, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand(Document document, Int32 caretPosition, IGoToDefinitionService goToDefinitionService, CommandExecutionContext context)
   at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.ExecuteCommand(GoToDefinitionCommandArgs args, CommandExecutionContext context)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<ExecuteStartingAtIndex>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

---
#### Feedback Bot on 7/8/2021, 01:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
@Forgind Don't suppose you remember what you were trying to Go To Definition on when you got this? I'd love to add a specific test here...

**Comment by Forgind** [comment]
I'm sorry—I don't normally notice this kind of thing until I walk away from my computer and come back, so I have no idea what I was doing when it popped up. I can say it didn't really affect my productivity, but that doesn't really help.

**Comment by davidwengier** [comment]
No worries :)
