### ISSUE TITLE
'CSharpChangeNamespaceToMatchFolderCodeFixProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54757]
**Version Used**: 

Compiler version: '3.10.0-4.21269.26 (02984771)'. Language version: 8.0.

SDK Version:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4
```

**Steps to Reproduce**:

Have a namespace not matching the folder structure. Stack trace:

```
System.InvalidOperationException : This Workspace does not support changing a document's Folders.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.FailIfDocumentInfoChangesNotSupported(Document document,DocumentInfo updatedInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyDocumentInfoChanged(DocumentId documentId,DocumentInfo updatedInfo)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges,DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Note: the crash happens on applying the change, but the preview shows a change without crash.
Note 2: the change suggested is actually incorrect (note the "expected" part in the diagnostic message, it's correct, but the suggestion isn't the same).

![image](https://user-images.githubusercontent.com/31348972/125203254-f6879b80-e277-11eb-91e6-89fe40422979.png)

cc @ryzngard

**Comment by Youssef1313** [comment]
@ryzngard I see there is already another code action provided, "Change namespace to '...'", so a functionality similar to IDE0130 was already implemented without the need to any changes in the SDK, and now we have two things (the old code refactoring and the new analyzer) that does very similar things. Can't we extract a service based on `AbstractSyncNamespaceCodeRefactoringProvider` implementation, and use it in both `AbstractSyncNamespaceCodeRefactoringProvider` and IDE0130? which (likely) won't require any additional changes in dotnet/sdk?

**Comment by Youssef1313** [comment]
Also tagging @sharwell, since the tests doesn't fail, but the codefix is crashing in Visual Studio.

**Comment by ryzngard** [comment]
> @ryzngard I see there is already another code action provided, "Change namespace to '...'", so a functionality similar to IDE0130 was already implemented without the need to any changes in the SDK, and now we have two things (the old code refactoring and the new analyzer) that does very similar things. Can't we extract a service based on `AbstractSyncNamespaceCodeRefactoringProvider` implementation, and use it in both `AbstractSyncNamespaceCodeRefactoringProvider` and IDE0130? which (likely) won't require any additional changes in dotnet/sdk?

They use the same underlying engine to handle refactoring code.

**Comment by Youssef1313** [comment]
@ryzngard But:

- they provide different suggestions.
- the refactoring didn't require changes in dotnet/sdk.

What's causing that if they're built on top of the same engine?

**Comment by ryzngard** [comment]
> They provide different suggestions

This we can improve. They use the same engine for refactoring, not for analyzing.

> Didn't require sdk changes...

That's because it works in a context where it can get information about project folders. Analyzers can't by default, and that information needs to be added to the properties passed into analyzers for it to work. Otherwise there's no way to tell where the folder is in comparison to the project it belongs to.

**Comment by Youssef1313** [comment]
> not for analyzing

Can this be improved to use the same service/engine for analyzing as well (ie, collect the information available to refactorings but not analyzers, since use the same engine to analyze)?

**Comment by ryzngard** [comment]
I was looking at this today and decided not to completely unify, but did remove some more discrepancies in a unified way. There are some behaviors the code refactoring has that aren't the same, such as if the namespace is not prepended with the default namespace. For example, if the default is `Microsoft.CodeAnalysis` and I have a namespace `Microsoft.Tests` then it won't offer to sync based on folder structure. In the analyzer we _do_ want it to report that as a problem, since you can configure with editorconfig specific areas you want to be ignored

**Comment by KamranShahid** [comment]
Same happening at my end as well. what is the fix?

**Comment by davidwengier** [comment]
> Same happening at my end as well. what is the fix? i have latest VS 2019 installed

@KamranShahid the fix for this issue is in Visual Studio 2022. You would have to install that version to get the fix.
