### ISSUE TITLE
Analyzer 'Microsoft.CodeAnalysis.CSharp.SimplifyInterpolation.CSharpSimplifyInterpolationDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#54834]
**Version Used**: VS2022 17.0.0 Preview2.0

**Steps to Reproduce**:
Run code analysis with the below code
```cs
ReadOnlySpan<char> strSpan = "0123456789".AsSpan();
var str = $"xxx{strSpan[1..2].ToString()}xxx";
```

**Expected Behavior**:
No exception.

**Actual Behavior**:
```
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.SimplifyInterpolation.CSharpSimplifyInterpolationDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'The object reference is not set to an instance of the object.'.
Exception occurred with following context:
Compilation: ***
IOperation: Interpolation
SyntaxTree: ***
SyntaxNode: {strSpan[1..2].ToString()} [InterpolationSyntax]@[670..696) (21,27)-(21,53)

System.NullReferenceException:
   at Microsoft.CodeAnalysis.SimplifyInterpolation.AbstractSimplifyInterpolationHelpers.UnwrapFormatString(IVirtualCharService virtualCharService, ISyntaxFacts syntaxFacts, IOperation expression, IOperation& unwrapped, String& formatString, List`1 unnecessarySpans)
   at Microsoft.CodeAnalysis.SimplifyInterpolation.AbstractSimplifyInterpolationHelpers.UnwrapInterpolation[TInterpolationSyntax,TExpressionSyntax](IVirtualCharService virtualCharService, ISyntaxFacts syntaxFacts, IInterpolationOperation interpolation, TExpressionSyntax& unwrapped, TExpressionSyntax& alignment, Boolean& negate, String& formatString, ImmutableArray`1& unnecessaryLocations)
   at Microsoft.CodeAnalysis.SimplifyInterpolation.AbstractSimplifyInterpolationDiagnosticAnalyzer`2.AnalyzeInterpolation(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0071
```

**Comment by yyjdelete** [comment]
Already reported as #54364
