### ISSUE TITLE
[LSP] workspace diagnostics fail when we encounter documents in the TypeScript misc project

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#54970]
In razor scenarios, Typescript adds typescript files (e.g. lib.es6.d.ts) and the top level generated razor file (e.g. Counter.razor) to a 'misc project' in the main VS workspace roslyn solution.
![image](https://user-images.githubusercontent.com/5749229/126275613-429c5f6d-7d40-4792-a7f7-5b5fc889ae07.png)

Workspace diagnostics happily returns no diagnostics for these TS + "Counter.razor" docs.  This actually doesn't cost too much computation since these files never get updated diagnostics.  

This becomes a problem though as the top level razor documents (e.g. "Counter.razor") are somehow getting added to the C# project's _filePathToDocumentIds map (in the map there is a documentId pointing to "Counter.razor" that points to the project Id of the C# project) but there is _no matching documentId_ in the same c# project in the solution.
https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/SolutionState.cs,44 ?

THis means that when we attempt to read the previous results, we throw since we find documents with an Id by file path (_filePathToDocumentIds contains two documentIds, one in misc TS, one in C#), but then fail to look up the document by Id since the C# project does not contain the doc. 
 https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Extensions/Extensions.cs,34
Manifested in the logs as
```
Exception: System.InvalidOperationException: Error handling 'workspace/_ms_diagnostic' request: The solution does not contain the specified document. ---> System.InvalidOperationException: The solution does not contain the specified document.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items, Func`2 selector)
   at Microsoft.CodeAnalysis.LanguageServer.Extensions.GetDocuments(Solution solution, Uri documentUri, String clientName)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`2.HandleRemovedDocuments(RequestContext context, DiagnosticParams[] previousResults, BufferedProgress`1 progress)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`2.<HandleRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestExecutionQueue.<>c__DisplayClass15_0`2.<<ExecuteAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestExecutionQueue.<>c__DisplayClass15_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestExecutionQueue.QueueItem.<CallbackAsync>d__12.MoveNext()
```

I think there are two issues
1.  We should only compute workspace diagnostics for files with a matching client name for the server (the top level razor doc has client name "TypeScript".  However the other TS files do not have this name (@uniqueiniquity should the other TS files also have the TS client name?).
2.  Something somewhere is causing a document in the C# project for razor top level documents to be created (any ideas @uniqueiniquity ?).  This is then removed? from the workspace but the file path mapping lingers.

**Comment by uniqueiniquity** [comment]
> We should only compute workspace diagnostics for files with a matching client name for the server (the top level razor doc has client name "TypeScript". However the other TS files do not have this name (should the other TS files also have the TS client name?).

Nope, we only do that for files we get via HTML delegation.

**Comment by dibarbet** [comment]
discussed offline a bit
I think a reasonable solution here is to ensure that Roslyn workspace diagnostics are calculated only for projects that have a supported language (e.g. c#/vb/f#), otherwise we should skip them.
