### ISSUE TITLE
"Unsupported encoding" error in Servicehub core host

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#54985]
**Steps to Reproduce**:

1 . Enable servicehub core host in VS
```
<VSInstallPath>\Common7\IDE\VsRegEdit.exe set <VSInstallPath> <Hive> HKCU "Roslyn\Internal\OnOff\Features" OOPCoreClr dword 1
```

2. create a new empty class in a project

3. "file -> save as" the new class

4. choose to save with encoding in the dialog
![image](https://user-images.githubusercontent.com/788783/126385670-84e6f25a-a323-482a-b220-cdfcdedb5181.png)

5. pick codepage 1252
![image](https://user-images.githubusercontent.com/788783/126385714-c395f306-9ba3-4deb-adcd-fc8de62889c3.png)

6. close and restart vs with the same project

7. you should see a bunch of infobars about encoding errors

**Expected Behavior**:

No errors in OOP

**Actual Behavior**:

Goldbar showing a bunch of features hit the same error, for example:
```
StreamJsonRpc.RemoteInvocationException: 'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17`1.MoveNext() in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.ArgumentException: 'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
      at System.Text.EncodingTable.InternalGetCodePageFromName(String name) in System.Private.CoreLib.dll:token 0x6003234+0xba
      at System.Text.EncodingTable.GetCodePageFromName(String name) in System.Private.CoreLib.dll:token 0x6003233+0x24
      at System.Text.Encoding.GetEncoding(String name) in System.Private.CoreLib.dll:token 0x60031ae+0x0
      at Roslyn.Utilities.ObjectReader.ReadValueWorker() in C:\Users\gel\roslyn2\src\Compilers\Core\Portable\Serialization\ObjectReader.cs:line 284
      at Roslyn.Utilities.ObjectReader.ReadValue() in C:\Users\gel\roslyn2\src\Compilers\Core\Portable\Serialization\ObjectReader.cs:line 207
      at Microsoft.CodeAnalysis.Serialization.SerializerService.DeserializeSerializableSourceText(ObjectReader reader, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Core\Portable\Serialization\SerializerService_Asset.cs:line 53
      at Microsoft.CodeAnalysis.Serialization.SerializerService.Deserialize[T](WellKnownSynchronizationKind kind, ObjectReader reader, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Core\Portable\Serialization\SerializerService.cs:line 215
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.ReadData(Stream stream, Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\RemoteHostAssetSerialization.cs:line 191
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.ReadDataAsync(PipeReader pipeReader, Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\RemoteHostAssetSerialization.cs:line 130
      at Microsoft.CodeAnalysis.Remote.RemoteHostAssetSerialization.ReadDataAsync(PipeReader pipeReader, Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\RemoteHostAssetSerialization.cs:line 143
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass21_0`1.<<InvokeStreamingServiceAsync>b__1>d.MoveNext() in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 325
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass21_0`1.<<InvokeStreamingServiceAsync>b__1>d.MoveNext() in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 334
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.InvokeStreamingServiceAsync[TResult](TService service, Func`4 invocation, Func`3 reader, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 337
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.InvokeAsync[TResult](Func`4 invocation, Func`3 reader, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\Core\RemoteCallback.cs:line 68
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) in Microsoft.VisualStudio.Telemetry.dll:token 0x6000993+0x2
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.SolutionAssetSource.GetAssetsAsync(Int32 scopeId, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\SolutionAssetSource.cs:line 34
      at Microsoft.CodeAnalysis.Remote.AssetProvider.RequestAssetsAsync(ISet`1 checksums, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\AssetProvider.cs:line 151
      at Microsoft.CodeAnalysis.Remote.AssetProvider.SynchronizeAssetsAsync(ISet`1 checksums, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\AssetProvider.cs:line 122
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.SynchronizeProjectAssets_NoLockAsync(IEnumerable`1 projectChecksums, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\ChecksumSynchronizer.cs:line 75
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.SynchronizeSolutionAssetsAsync(Checksum solutionChecksum, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\ChecksumSynchronizer.cs:line 45
      at Microsoft.CodeAnalysis.Remote.AssetProvider.SynchronizeSolutionAssetsAsync(Checksum solutionChecksum, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\AssetProvider.cs:line 85
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.CreateSolution_NoLockAsync(AssetProvider assetProvider, Checksum solutionChecksum, Boolean fromPrimaryBranch, Int32 workspaceVersion, Solution baseSolution, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 148
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.GetSolutionAsync(AssetProvider assetProvider, Checksum solutionChecksum, Boolean fromPrimaryBranch, Int32 workspaceVersion, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 213
      at Microsoft.CodeAnalysis.Remote.RemoteNavigationBarItemService.<>c__DisplayClass2_0.<<GetItemsAsync>b__0>d.MoveNext() in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Services\NavigationBar\RemoteNavigationBarItemService.cs:line 32
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken) in C:\Users\gel\roslyn2\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 73

```

**Comment by genlu** [comment]
Probably need to run `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` when initializing the remote service.
https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix

**Comment by genlu** [comment]
@tmat Do you know where'd be a good place to call `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`? I think we just need to do this once in remote process.

**Comment by tmat** [comment]
here: https://sourceroslyn.io/#Microsoft.CodeAnalysis.Remote.ServiceHub/Services/Host/RemoteHostService.cs,53
