### ISSUE TITLE
CSharpPopulateSwtichStatementCodeFixProvider threw unhandled exception when trying to populate switch statements via Visual Studio light bulb

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpPopulateSwtichStatementCodeFixProv/1484973)._

---
[severity:It bothers me. A fix would be nice]
When trying to use Visual Studio light bulb to populate switch statements (specifically, pattern matching by type), the error "CSharpPopulateSwtichStatementCodeFixProvider encountered an error and has been disabled" appears. I have several VS extensions installed but I think none of them should affect code analysis or code completion (see Visual Studio version info attached below. I have tried disabling JetBrains Resharper and the issue still exists).

**Steps to reproduce:**

1. I have the following incomplete code snippet in my editor:
! [image.png] (https://aka.ms/dc/image?name=B805da937439447bd9dc99636c9aafcf9637626031732833860_20210723-101251-image.png&tid=805da937439447bd9dc99636c9aafcf9637626031732833860)

2. Upon clicking on the VS light bulb, this error message immediately appears:
! [image.png] (https://aka.ms/dc/image?name=Bf5a0bc09d3074f209abfd7938d7fe35e637626035665867676_20210723-101924-image.png&tid=f5a0bc09d3074f209abfd7938d7fe35e637626035665867676)

3. Re-enabling it does not help. After re-enabling, this issue can be reproduced again.

**Here is the stacktrace:**

```
System.InvalidOperationException : This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchStatementCodeFixProvider`3.GetSwitchType(ISwitchOperation switchOperation)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.UpdateSwitchNode(SyntaxEditor editor,SemanticModel semanticModel,Boolean addCases,Boolean addDefaultCase,Boolean hasMissingCases,Boolean hasMissingDefaultCase,TSwitchSyntax switchNode,TSwitchOperation switchOperation)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchStatementCodeFixProvider`3.FixOneDiagnostic(Document document,SyntaxEditor editor,SemanticModel semanticModel,Boolean addCases,Boolean addDefaultCase,Boolean onlyOneDiagnostic,Boolean hasMissingCases,Boolean hasMissingDefaultCase,TSwitchSyntax switchNode,ISwitchOperation switchOperation)
   at async Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixOneDiagnosticAsync[TSwitchOperation,TSwitchSyntax,TSwitchArmSyntax,TMemberAccessExpression](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixWithEditorAsync[TSwitchOperation,TSwitchSyntax,TSwitchArmSyntax,TMemberAccessExpression](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

---
#### Feedback Bot on 7/23/2021, 00:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
