### ISSUE TITLE
Attempt to load abstract code fix results in an exception

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#55329]
roslyn-analyzers has an exported abstract CodeFix class with a derived concrete class:
https://github.com/dotnet/roslyn-analyzers/commit/cb17df3f04d2d9a444665ad85bae293a8850ddb8

The logic to load code fix types doesn't check whether the type is abstract:
https://github.com/dotnet/roslyn/blob/159cb67bb1e38f12662b22681e412c9746e7bcfb/src/Features/Core/Portable/Common/AbstractProjectExtensionProvider%602.cs#L59

This results in MissingMethodException:

```
System.MissingMethodException: Cannot create an abstract class.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

FYI @MeikTranel @sharwell

**Comment by Youssef1313** [comment]
I think an analyzer for this case would be useful to early detect the issue.

**Comment by sharwell** [comment]
> I think an analyzer for this case would be useful to early detect the issue.

This would fall under a general request to add analyzers for MEF usage.

**Comment by sharwell** [comment]
> The logic to load code fix types doesn't check whether the type is abstract:

This part is fine. It doesn't make sense to have a MEF export that's abstract, and Roslyn already handles the poorly-structured code in a reasonable way. I'll move this issue to roslyn-analyzers to fix the export location directly.
