### ISSUE TITLE
OptionPagesDTE fails in Standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5540]
VS crashes after attempting to verify autocomment after closing and reopening VS. 

Test log indicates that the VS component cache is out of date, but this might not be real issue. I'm going to be disabling this test in the standalone runs. 

Stack Trace here:
--------------------------------
 Microsoft.VisualStudio.ExtensibilityHosting.InvalidMEFCacheException: The Visual Studio component cache is out of date. Please restart Visual Studio. The Visual Studio component cache is out of date. Please restart Visual Studio.

 Server stack trace: 
```
    at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.<LoadAssembly>b__12_0(AssemblyName assemblyNameParam)
    at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.SafeGetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 valueFactory)
    at Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.LoadAssembly(AssemblyName assemblyName)
    at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.GetManifest(Resolver resolver, AssemblyName assemblyName)
    at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(ConstructorRef constructorRef)
    at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimePart.get_ImportingConstructor()
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
    at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
    at System.Lazy`1.CreateValue()
    at System.Lazy`1.LazyInitValue()
    at System.Lazy`1.get_Value()
    at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
    at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
    at System.ComponentModel.Composition.Primitives.Export.get_Value()
    at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
    at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass3`1.<CreateStronglyTypedLazyOfT>b__5()
    at System.Lazy`1.CreateValue()
    at System.Lazy`1.LazyInitValue()
    at System.Lazy`1.get_Value()
    at Roslyn.VSHosting.Test.RoslynInProcessAPI.get_WaitingService()
    at Roslyn.VSHosting.Test.RoslynInProcessAPI.EnableTrackActiveTokens()
    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

**Comment by jmarolf** [comment]
@mattscheffer I believe this has been fixed.

**Comment by mattscheffer** [comment]
Crash no longer appears. Thanks!
