### ISSUE TITLE
ExtractMethodCodeRefactoringProvider encountered an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55411]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ExtractMethodCodeRefactoringProvider-enc/1421997)._

---
In Visual Studio 2019, I press CTRL . to refactor a selection of code to "Extract Method." Visual Studio reports the error and offers to Enable or Enable and ignore future errors. Then, I can no longer type in the editor window until I restart Visual Studio.

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition)
   at Microsoft.VisualStudio.LanguageServices.Implementation.InlineRename.VisualStudioInlineRenameUndoManagerServiceFactory.InlineRenameUndoManager.CreateStartRenameUndoTransaction(Workspace workspace,ITextBuffer subjectBuffer,IInlineRenameSession inlineRenameSession)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.. ctor(InlineRenameSession session,ITextBuffer subjectBuffer,Workspace workspace,ITextBufferFactoryService textBufferFactoryService)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.TryPopulateOpenTextBufferManagerForBuffer(ITextBuffer buffer)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.InitializeOpenBuffers(SnapshotSpan triggerSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.. ctor(IThreadingContext threadingContext,InlineRenameService renameService,Workspace workspace,SnapshotSpan triggerSpan,IInlineRenameInfo renameInfo,IWaitIndicator waitIndicator,ITextBufferAssociatedViewService textBufferAssociatedViewService,ITextBufferFactoryService textBufferFactoryService,IFeatureServiceFactory featureServiceFactory,IEnumerable`1 refactorNotifyServices,IAsynchronousOperationListener asyncListener)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService.StartInlineSession(Document document,TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.TryNavigateToLocationOrStartRenameSession(Workspace workspace,Solution oldSolution,Solution newSolution,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0. <InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
---
#### Feedback Bot on 5/12/2021, 07:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/14/2021, 11:50 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Tracking for dumps with https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1735605
