### ISSUE TITLE
InteractiveWindow tests that uses system clipboard fails with COM exception intermittently

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#5544]
see http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_master_win_dbg_32/1928/console

```  
Errors Roslyn.InteractiveWindow.UnitTests.dll: 
  Command: C:\Users\dotnet-bot\.nuget\packages\xunit.runners\2.0.0-alpha-build2576\tools\xunit.console.x86.exe "Binaries\Debug\Roslyn.InteractiveWindow.UnitTests.dll" -xml "Binaries\Debug\Roslyn.InteractiveWindow.UnitTests.TestResults.xml" -noshadow
     Microsoft.VisualStudio.InteractiveWindow.UnitTests.InteractiveWindowTests.PasteWithOutSelectionInReadOnlyArea [FAIL]
        System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.\r\n---- System.Runtime.InteropServices.COMException : OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
        Stack Trace:
              at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
              at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
              at System.Delegate.DynamicInvokeImpl(Object[] args)
              at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
              at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
              at System.Windows.Threading.DispatcherOperation.InvokeImpl()
              at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
              at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
              at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
              at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
              at System.Windows.Threading.DispatcherOperation.Invoke()
              at System.Windows.Threading.Dispatcher.ProcessQueue()
              at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
              at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
              at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
              at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
              at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
              at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
              at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
              at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
              at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
              at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
              at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
              at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
              at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
              at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority)
           src\EditorFeatures\TestUtilities\Async\WaitHelper.cs(17,0): at Roslyn.Test.Utilities.WaitHelper.WaitForDispatchedOperationsToComplete(DispatcherPriority priority)
           src\EditorFeatures\TestUtilities\Async\WaitHelper.cs(41,0): at Roslyn.Test.Utilities.WaitHelper.PumpingWaitAll(IEnumerable`1 tasks)
           src\EditorFeatures\TestUtilities\Async\WaitHelper.cs(22,0): at Roslyn.Test.Utilities.WaitHelper.PumpingWait(Task task)
           src\InteractiveWindow\EditorTest\InteractiveWindowTests.cs(1233,0): at Microsoft.VisualStudio.InteractiveWindow.UnitTests.InteractiveWindowTests.PasteWithOutSelectionInReadOnlyArea()
           ----- Inner Stack Trace -----
              at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
              at System.Windows.DataObject.OleConverter.GetDataInner(FORMATETC& formatetc, STGMEDIUM& medium)
              at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
              at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
              at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
              at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
              at System.Windows.DataObject.GetData(String format, Boolean autoConvert)
              at System.Windows.Clipboard.GetDataInternal(String format)
              at System.Windows.Clipboard.GetData(String format)
           src\InteractiveWindow\Editor\InteractiveWindow.UIThreadOnly.cs(607,0): at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.Paste()
           src\InteractiveWindow\Editor\InteractiveWindow.cs(255,0): at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.<>c.<Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowOperations.Paste>b__42_0(UIThreadOnly uiOnly)
```

**Comment by genlu** [comment]
This test is not the only clipboard related test that can fail, e.g.:
http://dotnet-ci.cloudapp.net/view/dotnet_roslyn/job/dotnet_roslyn_master_win_rel_32/814/

We need a mocked clipboard instead of using system one. I created https://github.com/dotnet/roslyn/issues/5562 to track it.
