### ISSUE TITLE
C# compiler crash related to nullability and class static field

### ISSUE THREAD

**Issue by slavanap** [dotnet/roslyn#55483]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 4.0.0-2.21362.3 (5f7ddf6f)

**Steps to Reproduce**:
.NET 5.0 sample program that crashes analysers and compiler. Tested in VS 2022.

```c#
#nullable enable

using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class Class1
    {
        public static readonly int Field1 = default!;
    }

    public interface IClass2 { }

    public class Class2: IClass2 { }

    public class Class3<T> { }

    class Program
    {
        public async Task F1(Class3<IClass2> a, int? b) => throw null!;

        void Main(string[] args)
        {
            Task F2(Class1 class1, Class3<Class2> class3) =>
                F1(class3, false ? Class1.Field1 : null);

            Task F3(Class1 class1, Class3<Class2> class3) =>
                F2(class1, class3);

            Console.WriteLine("Hello world!");
        }
    }
}
```

**Expected Behavior**:
Diagnostic received: at line with F1 call can't cast class3 to `Class3<IClass2>` type.

**Actual Behavior**:
Compilation crash.

**Analyser crash stack trace**:
```StreamJsonRpc.RemoteInvocationException: An item with the same key has already been added.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.ArgumentException: An item with the same key has already been added.
      at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
      at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitConditionalOperatorCore(BoundExpression node, Boolean isRef, BoundExpression condition, BoundExpression originalConsequence, BoundExpression originalAlternative)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitConditionalOperator(BoundConditionalOperator node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArgumentEvaluate(BoundExpression argument, RefKind refKind, FlowAnalysisAnnotations annotations)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArgumentsEvaluate(SyntaxNode syntax, ImmutableArray`1 arguments, ImmutableArray`1 refKindsOpt, ImmutableArray`1 parametersOpt, ImmutableArray`1 argsToParamsOpt, BitVector defaultArguments, Boolean expanded)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArguments(BoundNode node, ImmutableArray`1 arguments, ImmutableArray`1 refKindsOpt, ImmutableArray`1 parametersOpt, ImmutableArray`1 argsToParamsOpt, BitVector defaultArguments, Boolean expanded, Boolean invokedAsExtensionMethod, MethodSymbol method)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.ReinferMethodAndVisitArguments(BoundCall node, TypeWithState receiverType)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitCall(BoundCall node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitRvalue(BoundExpression node, Boolean isKnownToBeAnLvalue)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitAwaitExpression(BoundAwaitExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitAwaitExpression(BoundAwaitExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitRvalue(BoundExpression node, Boolean isKnownToBeAnLvalue)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitExpressionStatement(BoundExpressionStatement node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeLocalFunctionOrLambda(IBoundLambdaOrFunction lambdaOrFunction, MethodSymbol lambdaOrFunctionSymbol, LocalState state, MethodSymbol delegateInvokeMethod, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLocalFunctionStatement(BoundLocalFunctionStatement node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitMethodBodies(BoundBlock blockBody, BoundBlock expressionBody)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Scan(Boolean& badRegion)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Analyze(Boolean& badRegion, Optional`1 initialState)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, Optional`1 initialState, Builder snapshotBuilderOpt, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, Conversions conversions, DiagnosticBag diagnostics, Boolean useConstructorExitWarnings, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType, MethodSymbol delegateInvokeMethodOpt, VariableState initialState, Builder analyzedNullabilityMapOpt, Builder snapshotBuilderOpt, ArrayBuilder`1 returnTypesOpt, Boolean getFinalNullableState, VariableState& finalNullableState, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(BoundNode boundRoot, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<EnsureNullabilityAnalysisPerformedIfNecessary>g__rewriteAndCache|131_1(<>c__DisplayClass131_0& )
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxNode syntax, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsInCurrentProcessAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext()
```

**Additional Information**:

Annoying side effect of C# code analysers crash in VS 2022 is that Ctrl+V hotkey starts to paste buffer contents twice.

**Comment by RikkiGibson** [comment]
I think this is a minimal repro for the same issue (at least when running tests in debug configuration):

```cs
        [Fact]
        public void Repro_55483()
        {
            var source = @"
#nullable enable

void F2(bool b) =>
    F1(ERROR, b ? 1 : null);

void F1(object a, int? b) => throw null!;
";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics(
                // (4,6): warning CS8321: The local function 'F2' is declared but never used
                // void F2(bool b) =>
                Diagnostic(ErrorCode.WRN_UnreferencedLocalFunction, "F2").WithArguments("F2").WithLocation(4, 6),
                // (5,8): error CS0103: The name 'ERROR' does not exist in the current context
                //     F1(ERROR, b ? 1 : null);
                Diagnostic(ErrorCode.ERR_NameNotInContext, "ERROR").WithArguments("ERROR").WithLocation(5, 8));
        }
```

**Comment by slavanap** [comment]
@RikkiGibson not sure whether it helps but I've noticed that in release the issue appears when a function has 2 internal functions with same prototype (argument list, result), but with different names. When I cut the minimal example in the issue, whenever I removed or keep unreferenced the function prototype duplicate, the crash didn't happen.

**Comment by RikkiGibson** [comment]
Do you find that keeping them as local functions is necessary to produce the crash, or have you been able to produce the crash when they are ordinary class methods? I predict that they would have to be local functions or maybe lambdas--it's possible the NullableWalker instance or fields on it get reused when analyzing local functions within a given member method.

BTW, I put your exact scenario in my fix PR, and I think I have addressed the root of the problem. Just need my teammates to review and agree that the solution is good :)
https://github.com/dotnet/roslyn/pull/56190/files#diff-14fe026e6093e9522c01e6c377b26554dd6b663214884198dcc244f370548fa1R72734-R72766

Thanks for reporting the bug.

**Comment by slavanap** [comment]
@RikkiGibson 

> Do you find that keeping them as local functions is necessary to produce the crash,

Yes.

> or have you been able to produce the crash when they are ordinary class methods?

No, I wasn't able to reproduce it with class methods. When I had modified argument lists of local functions the crash disappeared. Back then it seemed important to me to keep 2 local functions with same argument lists to reproduce the crash.

Thanks for fixing it.

It's difficult to code without class fields suggestions these days. 😅
