### ISSUE TITLE
Roslyn.InteractiveHost.UnitTests.dll fails in Standalone run

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5551]
xUnit is failing to load the this suite of Unittests. It gives a System.BadImageFormatException. This suite will be disabled until it is fixed.

System.BadImageFormatException: Could not load file or assembly 'Roslyn.InteractiveHost.UnitTests, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fc793a00266884fb' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.Executor..ctor(String assemblyFilename)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
   at Xunit.Xunit1Executor..ctor(String testAssemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.Xunit1.CreateExecutor(String testAssemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.Xunit1..ctor(ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink)
   at Xunit.ConsoleClient.Program.ExecuteAssembly(Object consoleLock, String defaultDirectory, XunitProjectAssembly assembly, Boolean needsXml, Boolean teamCity, Boolean silent)

**Comment by mattscheffer** [comment]
#5552

**Comment by mattscheffer** [comment]
Testcase appears to be 32 bit only. Error pops up when ran via 64 bit xunit. Passes in x86.
