### ISSUE TITLE
Roslyn.InteractiveWindow.UnitTests fails in standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5552]
xUnit is failing to load the this suite of unit tests. It gives a System.BadImageFormatException. This suite will be disabled until it is fixed.

System.BadImageFormatException: Could not load file or assembly 'Roslyn.InteractiveWindow.UnitTests, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fc793a00266884fb' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.Executor..ctor(String assemblyFilename)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
   at Xunit.Xunit1Executor..ctor(String testAssemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.Xunit1.CreateExecutor(String testAssemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.Xunit1..ctor(ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink)
   at Xunit.ConsoleClient.Program.ExecuteAssembly(Object consoleLock, String defaultDirectory, XunitProjectAssembly assembly, Boolean needsXml, Boolean teamCity, Boolean silent)

**Comment by genlu** [comment]
This suite works fine, did I miss anything?

![tests](https://cloud.githubusercontent.com/assets/788783/10316425/1067e978-6c14-11e5-9999-eb6540885510.jpg)

**Comment by mattscheffer** [comment]
It looks like you just ran these with roslyn built right? Standalone is a separate scenario where Roslyn isn't built. Instead it runs off of what is installed with the VS build and a few separate binaries. Contact me and I can get you a machine with the standalone setup and all you'd have to do is run the test.

**Comment by genlu** [comment]
It seems the cause is the suite is trying to run 64bit xunit.console.exe on 32bit Roslyn.InteractiveWindow.UnitTests.dll. @mattscheffer helped me verified this on the test machine. I think it's probably the same issue with https://github.com/dotnet/roslyn/issues/5553 and https://github.com/dotnet/roslyn/issues/5551. We need to remove this test dll from x64 suite.

**Comment by mattscheffer** [comment]
I've removed the test from the standalone suite
