### ISSUE TITLE
Roslyn.Services.Editor.VisualBasic.UnitTests.dll fail in Standalone Run

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5555]
There are 13 unit tests in this suite with failures. Each are looking for slightly different items but are unable to find them. Tests names indicate Intellisense, specifically Completion List. I will be disabling the suite until these are fixed.

Example:
OverrideCompletionProviderTests.EscapedPropertyNameInIntelliSenseList [FAIL]
      No expected item was found.\nExisting items: ToString(), Equals(obj As Object), GetHashCode(), [Class]
      Stack Trace:
            at Roslyn.Test.Utilities.AssertEx.Any[T](IEnumerable`1 actual, Func`2 predicate)
            at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.CheckResults(Document document, Int32 position, String expectedItemOrNull, String expectedDescriptionOrNull, Boolean usePreviousCharAsTrigger, Boolean checkForAbsence, Nullable`1 glyph)
            at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.VerifyWorker(String code, Int32 position, String expectedItemOrNull, String expectedDescriptionOrNull, SourceCodeKind sourceCodeKind, Boolean usePreviousCharAsTrigger, Boolean checkForAbsence, Boolean experimental, Nullable`1 glyph)
            at OverrideCompletionProviderTests.EscapedPropertyNameInIntelliSenseList()

**Comment by mattscheffer** [comment]
These tests have been disabled in ..Qa\md\wd\roslyn\_tst\ParseUnitTestResults.cs. They will need to be renabled. Either contact me, or go to the above path and remove the Known failures chunk from line 57 to line 68

**Comment by rchande** [comment]
@mattscheffer Can you give the the full list of failing tests? 

Also, the two tests you mention above pass for me locally. Can you point me to a run where they failed? Thanks!

**Comment by DustinCampbell** [comment]
Getting stale...

**Comment by rchande** [comment]
These tests are not currently running and the file that skips tests. Moving out of RC2 and assigning back to Matt so he can reenable these tests once the standalone runs run again.

**Comment by CyrusNajmabadi** [comment]
These tests are running again.  closing this out.
