### ISSUE TITLE
Visual Studio 2019 - account settings not working

### ISSUE THREAD

**Issue by dan-seol** [dotnet/roslyn#55792]
**Version Used**: 
VS community 2019 16.11.1
**Steps to Reproduce**:
Not sure how it happened.
**Expected Behavior**:
Account Settings should have profiles visible, the IDE shouldn't restart every time i click account settings
IntelliCode Suggestions should be enabled
**Actual Behavior**:
Error at start:
![bug](https://user-images.githubusercontent.com/37251706/130333817-276158c2-7fd9-4cdd-9d19-ea7b5d3f881d.png)
Account settings:
![image](https://user-images.githubusercontent.com/37251706/130333831-d2b70a8e-e5c8-486f-91b8-69233d78ce7b.png)
with Stacktrace:

```
StreamJsonRpc.RemoteInvocationException: The type initializer for 'Microsoft.VisualStudio.Telemetry.WindowsIdentityInformationProvider' threw an exception. (ErrorKind: Error HResult: 80131534)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<RequestServiceChannelAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<RequestServiceChannelAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.<GetPipeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<GetPipeAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.<RequestServiceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.ServiceHubRemoteHostClient.<RequestServiceAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
Microsoft.ServiceHub.Utility.ServiceHubError: The type initializer for 'Microsoft.VisualStudio.Telemetry.WindowsIdentityInformationProvider' threw an exception. (ErrorKind: Error HResult: 80131534)
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.Telemetry.WindowsIdentityInformationProvider' threw an exception.
 ---> System.TypeLoadException: The signature is incorrect.
      at Microsoft.VisualStudio.Telemetry.WindowsIdentityInformationProvider..cctor()
   --- End of inner exception stack trace ---
      at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.GetIdentityInformationProvider()
      at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.BuildInitializer(TelemetrySessionSettings telemetrySessionSettings)
      at Microsoft.VisualStudio.Telemetry.TelemetryService.get_DefaultSession()
      at Microsoft.ServiceHub.Utility.VsTelemetryLogger.GetCurrentTelemetrySessionSerialized()
      at Microsoft.ServiceHub.Controller.LocationService.<StartNewHostAsync>d__59.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.ServiceHub.Controller.LocationService.<StartServiceAsync>d__58.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.ServiceHub.Controller.LocationService.<GetHostedServiceLocationAsync>d__75.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.ServiceHub.Controller.LocationService.<LocateAsync>d__42.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.ServiceHub.Controller.HubController.<LocateAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
      at Microsoft.ServiceHub.Controller.HubController.<LocateAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.ServiceHub.Controller.HubController.<RequestServiceChannelAsync>d__12.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.ServiceHub.Controller.ClientConnection.<RequestServiceChannelAsync>d__26.MoveNext()
```

This is my first time ever submitting an issue. Please let me know should you need more info.

**Comment by eriawan** [comment]
@dotnet/roslyn team,

Please review and consider to close this issue, because this issue is not roslyn related and it should be submitted in VS feedback/bug report: https://developercommunity.visualstudio.com/home
