### ISSUE TITLE
Feature 'Find usages' is currently unavailable due to an internal error: An item with the same key has already been added.

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#55955]
**Version Used**: 
Failed: VS2022 17.0 Preview3.1
Works: VS2019 16.11.2 Preview 1.0

**Steps to Reproduce**:

1. git clone https://github.com/yyjdelete/repo_find_refs
2. Open it in VS
3. Open file `ConsoleApp1/Program.cs`, right click and click `Find All References` on `SubmitAsync`

**Expected Behavior**:
Both references in `ClassLibrary1` and `ConsoleApp1` can be found.

**Actual Behavior**:
Only references in `ClassLibrary1` is found, and an blue info bar is shown: `Feature 'Find usages' is currently unavailable due to an internal error`
```cs
RPC server exception:
StreamJsonRpc.RemoteInvocationException: An item with the same key has already been added.
      at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.FindReferencesProgressAdapter.<OnDefinitionFoundAsync>d__13.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ReportGroupsAsync>d__13.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.<FindReferencesAsync>d__15.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteFindUsagesService.<>c__DisplayClass3_0.<<FindReferencesAsync>b__0>d.MoveNext()
   --- The end of the stack trace in the previous position where the exception was raised ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()
```

**Comment by yyjdelete** [comment]
Try to update the repro, seems it always failed when call `Find reference` for nuget from more than one projects with different TargetFramework(net5.0 and net5.0 with `Microsoft.AspNetCore.App` are different ones), or single project with multi TargetFrameworks

**Comment by CyrusNajmabadi** [comment]
Thanks for the repo.  It was very helpful!
