### ISSUE TITLE
Random crash from BasicDoNotUseVerbatimCrefsAnalyzer

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5609]
```C#
Message	AD0001	Analyzer 'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.			1	Active	Analyzer 'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw the following exception:
'System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.SyntaxTokenList.First()
   at Roslyn.Diagnostics.Analyzers.Documentation.DoNotUseVerbatimCrefsAnalyzer.ProcessAttribute(SyntaxNodeAnalysisContext context, SyntaxTokenList textTokens)
   at Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer.AnalyzeXmlAttribute(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

**Comment by rchande** [comment]
Again, this was just in my error list.

**Comment by AdamSpeight2008** [comment]
@rchande Analyser has move to a different repo [roslyn analyzers](https://github.com/dotnet/roslyn-analyzers) (See [Related Issue] (https://github.com/dotnet/roslyn-analyzers/issues/287))
