### ISSUE TITLE
Assertion failed in AbstractMergeNestedIfStatementsCodeRefactoringProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#56101]
While editing top level code of a web application.

```C#
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
[assembly: MetadataUpdateHandler(typeof(UpdateHandler))]

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();

internal static class UpdateHandler
{
    public static void UpdateApplication(Type[] types)
    {
        Console.WriteLine("Types:");
        Console.WriteLine(types == null ? "<null>" : types.Length == 0 ? "<empty>" : string.Join(",", types.Select(t => t.Name)));
    }
}
```

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeNestedIfStatementsCodeRefactoringProvider.IsFirstStatementOfIfOrElseIf(ISyntaxFactsService syntaxFacts, IIfLikeStatementGenerator ifGenerator, SyntaxNode statement, SyntaxNode& ifOrElseIf) in C:\R1\src\Features\Core\Portable\SplitOrMergeIfStatements\Nested\AbstractMergeNestedIfStatementsCodeRefactoringProvider.cs:line 96

   at Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeNestedIfStatementsCodeRefactoringProvider.CanBeMergedUpAsync(Document document, SyntaxNode ifOrElseIf, CancellationToken cancellationToken, SyntaxNode& outerIfOrElseIf) in C:\R1\src\Features\Core\Portable\SplitOrMergeIfStatements\Nested\AbstractMergeNestedIfStatementsCodeRefactoringProvider.cs:line 48

   at Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeIfStatementsCodeRefactoringProvider.<ComputeRefactoringsAsync>d__5.MoveNext() in C:\R1\src\Features\Core\Portable\SplitOrMergeIfStatements\AbstractMergeIfStatementsCodeRefactoringProvider.cs:line 47

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeIfStatementsCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context)

   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__14.MoveNext() in C:\R1\src\Features\Core\Portable\CodeRefactorings\CodeRefactoringService.cs:line 182

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan state, CodeRefactoringProvider provider, CodeChangeProviderMetadata providerMetadata, IExtensionManager extensionManager, Boolean isBlocking, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<HasRefactoringsAsync>d__12.MoveNext() in C:\R1\src\Features\Core\Portable\CodeRefactorings\CodeRefactoringService.cs:line 96

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.HasRefactoringsAsync(Document document, TextSpan state, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.<TryGetRefactoringSuggestedActionCategoryAsync>d__21.MoveNext() in C:\R1\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActionsSource.cs:line 441

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.TryGetRefactoringSuggestedActionCategoryAsync(Document document, Nullable`1 selection, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.<>c__DisplayClass30_0.<GetSuggestedActionCategoriesAsync>b__1() in C:\R1\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActionsSource.cs:line 606

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by CyrusNajmabadi** [comment]
@Neme12  can you take a look at this?

**Comment by Neme12** [comment]
@tmat I copied the code into a new project, tried hitting CTRL+. on the `if` and `else` and I'm getting no failure. Did you hit CTRL+. on a particular piece of syntax to get this?

**Comment by CyrusNajmabadi** [comment]
Ashley, these are debug asserts.  Were you running a debug version of this code?

**Comment by Neme12** [comment]
Oh, oops, no I wasn't. But the assert was removed in #56373 anyway.

**Comment by CyrusNajmabadi** [comment]
Ah, you edited your post.  I don't see those in email.  Clsoing this out.

**Comment by CyrusNajmabadi** [comment]
FIxed in https://github.com/dotnet/roslyn/pull/56373
