### ISSUE TITLE
Microsoft.CodeAnalysis.Workspaces SymbolFinder.FindReferencesAsync NullReferenceException

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/roslyn#56133]
I'm using these packages.
```
Microsoft.Build 16.11.0
Microsoft.Build.Tasks.Core 16.11.0
Microsoft.CodeAnalysis.CSharp.Workspaces (4.0.0-3.final)
Microsoft.CodeAnalysis.Workspaces.MSBuild (4.0.0-3.final)
```

The following line referencing Microsoft.CodeAnalysis.Workspaces throws a NullReferenceException.
```
await SymbolFinder.FindReferencesAsync(symbol, solution).ConfigureAwait(false);
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.HandleTupleTypes(INamedTypeSymbol x, INamedTypeSymbol y, Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalentWorker(ISymbol x, ISymbol y, SymbolKind k, Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalent(ISymbol x, ISymbol y, Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.MethodsAreEquivalent(IMethodSymbol x, IMethodSymbol y, Dictionary`2 equivalentTypesWithDifferingAssemblies, Boolean considerReturnRefKinds)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalentWorker(ISymbol x, ISymbol y, SymbolKind k, Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer.EquivalenceVisitor.AreEquivalent(ISymbol x, ISymbol y, Dictionary`2 equivalentTypesWithDifferingAssemblies)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<OriginalSymbolsMatchCoreAsync>d__45.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Can you provide the entirety of the code where you're calling into SymbolFinder, and can you provide the project you are executing SymbolFinder against?

**Comment by sharwell** [comment]
Also filed as:
🔗 AB#1388780
🔗 AB#1391743
🔗 AB#1393352

**Comment by nnpcYvIVl** [comment]
@CyrusNajmabadi Thank you!

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
