### ISSUE TITLE
Process terminated. System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/roslyn#56244]
**Version Used**: 

**Steps to Reproduce**:

.NET 6.0.100-preview.7.21379.14

1. clone https://github.com/wieslawsoltes/Core2D/tree/b07cf2773eea61db35c5f6d9bdb1ed634f003c71
2. dotnet build

**Expected Behavior**:

Code compiles.

**Actual Behavior**:

https://gist.github.com/wieslawsoltes/ff9b0d18b77288658b5e88bb055e4f0e

**Comment by wieslawsoltes** [comment]
This fixed the build:

https://github.com/wieslawsoltes/Core2D/commit/7a7c4aebda66c705f2e7d12890d23d9f3d4f39e0

**Comment by AlekseyTs** [comment]
It looks like the crash got fixed fairly recently. For example, for the following code I get a crash in (features/RawStringLiterals 28 Aug 2021). However it compiles successfully in main (3 Sep 2021).

```
using Core2D.ViewModels.Containers;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.ComponentModel;
using System.Linq;

class Test
{
    public void OnImportObject(object item, bool restore)
    {
        switch (item)
        {
            case LibraryViewModel sl when sl.Items.All(x => x is null):
                {
                    break;
                }
            case IList<LibraryViewModel> sll when sll.All(x => x.Items.All(_ => _ is null)):
                {
                    break;
                }
            case LibraryViewModel gl:
                {
                    break;
                }
            default:
                throw new NotSupportedException("Not supported import object.");
        }
    }

}

namespace Core2D.ViewModels
{
    public abstract partial class ViewModelBase : INotifyPropertyChanged
    {
        event PropertyChangedEventHandler? INotifyPropertyChanged.PropertyChanged
        {
            add
            {
                throw new NotImplementedException();
            }

            remove
            {
                throw new NotImplementedException();
            }
        }
    }
}

namespace Core2D.ViewModels.Containers
{
    public partial class LibraryViewModel : ViewModelBase
    {
        public ImmutableArray<ViewModelBase> Items { get; set; }
    }
}
```

Crash observed in features/RawStringLiterals (28 Aug 2021)
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.SmallDictionary`2.HandleInsert(AvlNode node, AvlNode parent, K key, V value, Boolean add) in /_/src/Compilers/Core/Portable/Collections/SmallDictionary.cs:line 461
   at Microsoft.CodeAnalysis.SmallDictionary`2.Insert(Int32 hashCode, K key, V value, Boolean add) in /_/src/Compilers/Core/Portable/Collections/SmallDictionary.cs:line 310
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.DeclareLocals[TSymbol](Scope scope, ImmutableArray`1 locals, Boolean declareAsFree) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 780
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitNestedFunction(MethodSymbol functionSymbol, BoundBlock body) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 575
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitLambda(BoundLambda node) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 431
   at Microsoft.CodeAnalysis.CSharp.BoundLambda.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 7018
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 88
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeVisitors.cs:line 223
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitConversion(BoundConversion node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9253
   at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2531
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 88
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeVisitors.cs:line 223
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitCall(BoundCall node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9647
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitCall(BoundCall node) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 442
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 5715
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 88
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeVisitors.cs:line 248
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeVisitors.cs:line 223
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitConditionalGoto(BoundConditionalGoto node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9470
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitConditionalGoto(BoundConditionalGoto node) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 521
   at Microsoft.CodeAnalysis.CSharp.BoundConditionalGoto.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 4452
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitSequencePointWithSpan(BoundSequencePointWithSpan node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9278
   at Microsoft.CodeAnalysis.CSharp.BoundSequencePointWithSpan.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2742
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitScope(BoundScope node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9291
   at Microsoft.CodeAnalysis.CSharp.BoundScope.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2909
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9287
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitBlock(BoundBlock node) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 402
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2880
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitSequencePointWithSpan(BoundSequencePointWithSpan node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9278
   at Microsoft.CodeAnalysis.CSharp.BoundSequencePointWithSpan.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2742
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 9287
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.VisitBlock(BoundBlock node) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 402
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in /_/src/Compilers/CSharp/Portable/Generated/BoundNodes.xml.Generated.cs:line 2880
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node) in /_/src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.Build() in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 379
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.ScopeTreeBuilder.Build(BoundNode node, MethodSymbol topLevelMethod, HashSet`1 methodsConvertedToDelegates, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.Tree.cs:line 365
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Analysis.Analyze(BoundNode node, MethodSymbol method, Int32 topLevelMethodOrdinal, MethodSymbol substitutedSourceMethod, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, ArrayBuilder`1 closureDebugInfo, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.Analysis.cs:line 77
   at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, HashSet`1 assignLocals) in /_/src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs:line 241
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, BindingDiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1436
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 918
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 524
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 420
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /_/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 141
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 329
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 128
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 3238
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, RebuildData rebuildData, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2635
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, RebuildData rebuildData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2576
   at SharpLab.Server.Compilation.Compiler.TryCompileToStreamAsync(MemoryStream assemblyStream, MemoryStream symbolStream, IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-RawStringLiterals\sharplab\source\Server\Compilation\Compiler.cs:line 29
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-RawStringLiterals\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 91
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

**Comment by AlekseyTs** [comment]
Could be related to https://github.com/dotnet/roslyn/pull/55981
