### ISSUE TITLE
Diagnostic analyzer runner is unavailable on NetCore OOP 

### ISSUE THREAD

**Issue by y87feng** [dotnet/roslyn#56254]
**Version Used**: Version 17.0.0 Preview 5.0 [31706.66.main]

**Steps to Reproduce**:

1.  Turn on NetCore OOP
2.  Open a test project

**Expected Behavior**:
No error

**Actual Behavior**:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26366507/132568546-98e6b601-7968-4de1-8fbe-09539406a518.png)

**Comment by y87feng** [comment]
tag @genlu

**Comment by genlu** [comment]
Thanks @y87feng 
Do you have the stacktrace available?

**Comment by y87feng** [comment]
@genlu Yes, it's below
```
StreamJsonRpc.RemoteInvocationException: Argument cannot be empty. (Parameter 'analyzers')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.ArgumentException: Argument cannot be empty. (Parameter 'analyzers')
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyAnalyzersArgumentForStaticApis(ImmutableArray`1 analyzers, Boolean allowDefaultOrEmpty) in Microsoft.CodeAnalysis.dll:token 0x6002316+0x1c
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyArguments(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions) in Microsoft.CodeAnalysis.dll:token 0x6002315+0x1c
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers..ctor(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.dll:token 0x6002314+0x5a
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers..ctor(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions) in Microsoft.CodeAnalysis.dll:token 0x6002313+0x0
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerExtensions.WithAnalyzers(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions) in Microsoft.CodeAnalysis.dll:token 0x600243e+0x0
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<CreateCompilationWithAnalyzersCacheEntryAsync>g__CreateCompilationWithAnalyzerAsync|15_0(Project project, ImmutableArray`1 analyzers, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x600017b+0xb0
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.CreateCompilationWithAnalyzersCacheEntryAsync(Project project, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x6000179+0x15f
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<>c__DisplayClass14_0.<<GetOrCreateCompilationWithAnalyzersAsync>g__GetOrCreateCacheEntryAsync|0>d.MoveNext() in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x600049e+0x138
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetOrCreateCompilationWithAnalyzersAsync(Project project, Boolean isDocumentAnalysis, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x6000178+0x8d
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x6000172+0x8d
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass3_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext() in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x6000421+0x26e
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Remote.ServiceHub.dll:token 0x60000c5+0x76
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) in Microsoft.VisualStudio.Telemetry.dll:token 0x60009a1+0x2
```
