### ISSUE TITLE
Change Signature crashes if the signature is not valid

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#56495]
Repro steps:

1. create a record type with invalid optional parameters (optional parameters need to be at the end):
```csharp
internal record Person(string FirstName, string? MiddleName = null, string LastName);
```
2. Invoke Change signature
![image](https://user-images.githubusercontent.com/9797472/133857182-29965df5-44f8-44e6-88d9-8a262b529769.png)
3. Move the optional parameter to the end of the constructor
![image](https://user-images.githubusercontent.com/9797472/133857254-dd274119-6c94-44c9-9e9a-9f6f5d4d2ee6.png)

Expected: 
Change signature moves constructor argument to the end

Actual:
crash
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryGetNodeWithEditableSignatureOrAttributes(Location location,Solution solution,SyntaxNode& nodeToUpdate,DocumentId& documentId)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.CreateUpdatedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.<ChangeSignatureWithContextAsync>g__GetChangeSignatureResultAsync|19_0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by allisonchou** [comment]
@jmarolf confirmed this issue no longer repros, closing out.
