### ISSUE TITLE
Json source generator corrupts Workspace

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#56499]
Version: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 4.0

1. Create a new Blazor WASM app
2. Add a new file Class.cs with the following contents

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

internal record Person(string FirstName, string LastName);

[JsonSerializable(typeof(Person))]
internal partial class PersonJsonContext : JsonSerializerContext { }

public class Class
{
    static void Main(string[] args)
    {
        using MemoryStream ms = new();
        using Utf8JsonWriter writer = new(ms);
        var person = new Person(FirstName: "Jane", LastName: "Doe");
        PersonJsonContext.Default.Person.Serialize!(writer, person);
        writer.Flush();
    }
}

```

Expected: json source generator runs

Actual: All Roslyn features are broken 
```
System.ArgumentException : An element with the same key but a different value already exists. Key: '(DocumentId, #8f8fd6fd-5ec7-97ef-4961-c500d05f573e - PersonJsonContext.String.g.cs)'
   at System.Collections.Immutable.ImmutableSortedDictionary`2.FillFromEmpty(IEnumerable`1 items,Boolean overwriteOnCollision)
   at System.Collections.Immutable.ImmutableSortedDictionary`2.AddRange(IEnumerable`1 items,Boolean overwriteOnCollision,Boolean avoidToSortedMap)
   at System.Collections.Immutable.ImmutableSortedDictionary.ToImmutableSortedDictionary[TSource,TKey,TValue](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IComparer`1 keyComparer)
   at Microsoft.CodeAnalysis.TextDocumentStates`1..ctor(IEnumerable`1 states)
   at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`2.FindDisposableLocalDeclarationAsync[TStatementSyntax,TLocalDeclarationSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`2.ComputeRefactoringsAsync[TStatementSyntax,TLocalDeclarationSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by jasonmalinowski** [comment]
Repro worked for me first time, investigating further. (Thanks @jmarolf for the repro!)

**Comment by jasonmalinowski** [comment]
This is happening because we're being given the System.Text.Json source generator _twice_, and they're both running:

![image](https://user-images.githubusercontent.com/201340/134406147-6e274ab3-01f9-4f54-814a-b5e8d2464ced.png)

If you run this in a debug build you hit this assert first:

https://github.com/dotnet/roslyn/blob/2eddced21a8d9dcfea0509dec368be07644b4302/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs#L32

@chsienki I'm guessing if we find ourselves in a situation like this all warranties are void from the compiler API? Or is this something the IDE needs to be more robust against? It's also possible we both have to be more robust, in addition to diagnosing why this is happening in the first place.

**Comment by jmarolf** [comment]
yep feel free to clone
