### ISSUE TITLE
Feature 'Navigate to' is currently unavailable due to an internal error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#56607]
**Version Used**: 

17.0 P4

**Steps to Reproduce**:

I had a consistent repro in https://github.com/dotnet/roslyn/issues/54464#issuecomment-870659502.
I'm not sure if's still consistent repro, but I'm hitting this crash randomly multiple times a day.

**Expected Behavior**:

No crash.

**Actual Behavior**:

```
StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
      at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass3_0.<<GetCallback>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<AddResultIfMatchAsync>d__20.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessIndexAsync>d__19.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentAsync>d__16.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentsAsync>d__15.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<FindSearchResultsAsync>d__14.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass6_0.<<SearchFullyLoadedProjectAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()

```

**Comment by jinujoseph** [comment]
@Youssef1313 mind filing a issue via "report a problem" so we get all related logs

**Comment by Youssef1313** [comment]
Sure. Will do the next time I get this and add a link here.

**Comment by CyrusNajmabadi** [comment]
i'm not sure what work for next steps on this error:

```
StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
      at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
```

@tmat @AArnott @sharwell any thoughts on what could cause this or how to investigate this?

**Comment by AArnott** [comment]
The frame you quote with the exception is just re-throwing. You should look further down in the stack including inner exceptions to find the original frame that threw that exception. I'm not super great at reading such deep nesting exception stacks, but these look possibly interesting:

      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass3_0.<<GetCallback>b__0>d.MoveNext()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<AddResultIfMatchAsync>d__20.MoveNext()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessIndexAsync>d__19.MoveNext()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentAsync>d__16.MoveNext()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<ProcessDocumentsAsync>d__15.MoveNext()
      at Microsoft.CodeAnalysis.NavigateTo.AbstractNavigateToSearchService.<FindSearchResultsAsync>d__14.MoveNext()
      at Microsoft.CodeAnalysis.Remote.RemoteNavigateToSearchService.<>c__DisplayClass6_0.<<SearchFullyLoadedProjectAsync>b__0>d.MoveNext()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14.MoveNext()

**Comment by CyrusNajmabadi** [comment]
>  at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__2.MoveNext()

That's just us making a remote call back to the VS side.  I can't tell if this is saying that somethign is throwing o the VS side.  Or if this is saying it's throwing in it's attempt to call into the VS side.

**Comment by AArnott** [comment]
A `RemoteInvocationException` is thrown on the RPC client side to wrap an exception thrown on the RPC server.

But what's really interesting is that there appears to be *two* such exceptions. So it actually appears that party A called party B which then called party A (or C), and the last call threw, which bounced through B and then (back) to A. 
At least I _think_ that that situation may manifest this way.
But I suspect the _original_ exception stack trace may not be represented here. I've only tested for propagation of an exception callstack from RPC server back to client. I haven't tested that it goes on from that client to yet another server->client jump.

The exception message came from the original exception, wherever that was. That exception message would not ever come from StreamJsonRpc itself because it never does URI parsing.

**Comment by sharwell** [comment]
My gut feeling is this is related to this exception:

```
System.Uri.CreateThis(String,Boolean,UriKind)
System.Uri..ctor(String)
Microsoft.VisualStudio.GraphModel.CodeSchema.SourceLocation..ctor(String,Position,Position)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.GraphBuilder.<AddNodeAsync>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SearchGraphQuery.<AddLinkedNodeForTypeAsync>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SearchGraphQuery.<AddLinkedNodeForTypeAsync>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SearchGraphQuery.<ProcessProjectAsync>d__3.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.SearchGraphQuery.<GetGraphAsync>d__2.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
Microsoft.VisualStudio.LanguageServices.Implementation.Progression.GraphQueryManager.<PopulateContextGraphAsync>d__14.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
That's very promising. @Youssef1313 can you show me where you were invoking navigate-to from (i.e. a literal picture of what VS ui you were using). Thanks!!

**Comment by Youssef1313** [comment]
@CyrusNajmabadi https://github.com/dotnet/roslyn/issues/54464#issuecomment-870659502

**Comment by Youssef1313** [comment]
@CyrusNajmabadi @sharwell I opened via VS feedback as requested by @jinujoseph 

https://developercommunity.visualstudio.com/t/navigateto-is-currently-unavailable-crash/1538891

**Comment by sharwell** [comment]
I haven't been able to reproduce this locally. Right now it seems like my previous comment is the most likely cause, but if you can capture a performance recording of the search itself and the resulting gold bar, we can prove it (the performance recording captures exceptions and their stacks).

**Comment by Youssef1313** [comment]
@sharwell Thanks for taking a look! I think this requires starting a recording and reproducing the issue *while* recording right?

Unfortunately it looks like the consistent repro I had from https://github.com/dotnet/roslyn/issues/54464#issuecomment-870659502 is no longer a consistent repro. I'm hitting this randomly now, so will be hard to reproduce *while* recording.

Anyway since it's most likely that https://github.com/dotnet/roslyn/issues/56607#issuecomment-926329199 is the original stack trace that was lost in remoting, you can close the VS feedback ticket. I'll provide feedback when https://github.com/dotnet/roslyn/issues/56607#issuecomment-926329199 is investigated and fixed. Hopefully it will fix it for me.

Thanks again!

**Comment by CyrusNajmabadi** [comment]
@sharwell  the stack you're reporting is likely not what @Youssef1313 is hitting, but it's definitely something that needs attention as well.   Looks like both LSP and Progression attempt to convert doc paths to URIs, whch is likely something not always supported.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski do you know of scenarios where we have documents whose FilePath could not be made into a URI?  It looks like we'll need to filter those out from LSP and Progression as

**Comment by Youssef1313** [comment]
@sharwell @CyrusNajmabadi Finally finally got a somewhat consistent repro on my machine and recorded it!! Opened a VS feedback just to make sure if it's the issue fixed in #56700 or not:

Can you please take a look? https://developercommunity.visualstudio.com/t/performance-trace-for-the-navigate-to-crash/1539219?from=email

**Comment by Youssef1313** [comment]
Reopened in https://developercommunity.visualstudio.com/t/performance-trace-for-navigate-to-crash-for/1539225?from=email 
The old ticket isn't showing for some reason.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: I'm guessing this might have been source generator related, if we weren't producing usable full file paths for generated files. The compiler also might in VB cases produce trees that may not have sane file paths either for things like some of the My stuff; we wouldn't have _documents_ for those but if something was walking trees I could imagine that happening.
