### ISSUE TITLE
Three tests are failing in MSBuildWorkspaceTests

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#5721]
Follow instructions on https://github.com/dotnet/roslyn how to enlist.
Run ```msbuild /v:m /m BuildAndTest.proj``` from the root

Observed:
3 tests failed

```
Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithoutPrefer32BitAndConsoleApplication [FAIL]
        Assert.Equal() Failure\r\nExpected: AnyCpu32BitPreferred\r\nActual:   AnyCpu
        Stack Trace:
           src\Workspaces\CoreTest\WorkspaceTests\MSBuildWorkspaceTests.cs(507,0): at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithoutPrefer32BitAndConsoleApplication()
     Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithPrefer32BitAndConsoleApplication [FAIL]
        Assert.Equal() Failure\r\nExpected: AnyCpu32BitPreferred\r\nActual:   AnyCpu
        Stack Trace:
           src\Workspaces\CoreTest\WorkspaceTests\MSBuildWorkspaceTests.cs(532,0): at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_VisualBasic_WithPrefer32BitAndConsoleApplication()
     Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestCompilationOptions_VisualBasic_OptionStrict_On [FAIL]
        Assert.Equal() Failure\r\nExpected: On\r\nActual:   Off
        Stack Trace:
           src\Workspaces\CoreTest\WorkspaceTests\MSBuildWorkspaceTestBase.cs(32,0): at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTestBase.AssertVBOptions[T](T expected, Fu
  nc`2 actual)
           src\Workspaces\CoreTest\WorkspaceTests\MSBuildWorkspaceTests.cs(1622,0): at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestCompilationOptions_VisualBasic_OptionStrict_On()
```

**Comment by balajikris** [comment]
I can't seem to get this to repro. These tests pass for me when i run the entire assembly or the individual test...

**Comment by AlekseyTs** [comment]
Passed for me this morning too.

**Comment by balajikris** [comment]
so, we're not sure if this is a flakey test or if a bug was introduced and was fixed..

**Comment by balajikris** [comment]
@AlekseyTs This no longer reproes, I've tried looking for them in local runs on developer boxes, standalone runs and CI runs. If you're aware of any, please reactivate and/or let me know.
