### ISSUE TITLE
Debugger fails to expand ref members in the same way it expands pointer members.

### ISSUE THREAD

**Issue by The-Futurist** [dotnet/roslyn#57220]
C# 10
**Steps to Reproduce**:

Consider this code (a bit contrived but it shows the problem)

```cs
namespace ConsoleApp38
{
    internal class Program
    {

        static void Main(string[] args)
        {
            Demo demo = new Demo();

            demo.Ref.f0 = 123;
        }
    }

    public unsafe struct Demo
    {
        private readonly Fields * fields;

        public Demo()
        {
            // Just allocate some memory so we can write to it
            fields = (Fields*)Marshal.AllocHGlobal(sizeof(Fields));
            fields->f0 = 0;
            fields->f1 = 0;
        }

        public Fields * Ptr { get { return fields; } }

        public ref Fields Ref { get { return ref (*fields); } }
    }

    public struct Fields
    {
        public int f0;
        public double f1;
    }
}
```

**Expected Behavior**:

When debugged with a break on the line that assigns `123` to `f0`, we can see in the Locals window that `demo` can be expanded as can `Ptr` (but not `Ref`).

**Actual Behavior**:

The debugger does not let us 'expand' the 'ref', which is a `ref return` property. 

If you execute the line you can also see that the structs fields `f0` is updated via the ref, so we can clearly see that the ref and ptr are valid values.

I'm regarding this as a bug but there may be more to this...

**Comment by CyrusNajmabadi** [comment]
@tmat is this on our end (with the EE)?  Or is on the debugger side?

Interestingly, when i try this in debug mode, i get the following (possibly related) assertion:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.ExpressionEvaluator.TypeHelpers.IsObject(Type type) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Helpers\TypeHelpers.cs:line 290

   at Microsoft.CodeAnalysis.ExpressionEvaluator.TypeHelpers.TryGetEvalAttribute[T](DkmClrType type, DkmClrType& attributeTarget, T& evalAttribute) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Helpers\TypeHelpers.cs:line 527

   at Microsoft.CodeAnalysis.ExpressionEvaluator.TypeHelpers.GetProxyType(DkmClrType type) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Helpers\TypeHelpers.cs:line 656

   at Microsoft.CodeAnalysis.ExpressionEvaluator.DebuggerTypeProxyExpansion.CreateExpansion(ResultProvider resultProvider, DkmInspectionContext inspectionContext, String name, TypeAndCustomInfo typeDeclaringMemberAndInfoOpt, TypeAndCustomInfo declaredTypeAndInfo, DkmClrValue value, Boolean childShouldParenthesize, String fullName, String childFullNamePrefix, ReadOnlyCollection`1 formatSpecifiers, DkmEvaluationResultFlags flags, String editableValue) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Expansion\DebuggerTypeProxyExpansion.cs:line 45

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.CreateDataItem(DkmInspectionContext inspectionContext, String name, TypeAndCustomInfo typeDeclaringMemberAndInfo, TypeAndCustomInfo declaredTypeAndInfo, DkmClrValue value, Boolean useDebuggerDisplay, ExpansionFlags expansionFlags, Boolean childShouldParenthesize, String fullName, ReadOnlyCollection`1 formatSpecifiers, DkmEvaluationResultCategory category, DkmEvaluationResultFlags flags, DkmEvaluationFlags evalFlags, Boolean canFavorite, Boolean isFavorite, Boolean supportsFavorites) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\ResultProvider.cs:line 598

   at Microsoft.CodeAnalysis.ExpressionEvaluator.MemberExpansion.CreateMemberDataItem(ResultProvider resultProvider, DkmInspectionContext inspectionContext, MemberAndDeclarationInfo member, DkmClrValue memberValue, EvalResultDataItem parent, CustomTypeInfoTypeArgumentMap customTypeInfoMap, ExpansionFlags flags, Boolean supportsFavorites) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Expansion\MemberExpansion.cs:line 502

   at Microsoft.CodeAnalysis.ExpressionEvaluator.MemberExpansion.GetMemberRow(ResultProvider resultProvider, DkmInspectionContext inspectionContext, DkmClrValue value, MemberAndDeclarationInfo member, EvalResultDataItem parent, CustomTypeInfoTypeArgumentMap customTypeInfoMap) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Expansion\MemberExpansion.cs:line 323

   at Microsoft.CodeAnalysis.ExpressionEvaluator.MemberExpansion.GetRows(ResultProvider resultProvider, ArrayBuilder`1 rows, DkmInspectionContext inspectionContext, EvalResultDataItem parent, DkmClrValue value, Int32 startIndex, Int32 count, Boolean visitAll, Int32& index) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\Expansion\MemberExpansion.cs:line 308

   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrResultProvider.GetChildren(DkmEvaluationResult evaluationResult, DkmWorkList workList, Int32 initialRequestSize, DkmInspectionContext inspectionContext, DkmCompletionRoutine`1 completionRoutine) in C:\github\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\ResultProvider.cs:line 135

   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrResultProvider_GetChildren(IntPtr pvClassInfo, IntPtr Result, IntPtr WorkList, Int32 InitialRequestSize, IntPtr InspectionContext, IntPtr CompletionRoutine)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

Looks like a potential valuable point to start investigating.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Probably on our end.

SG.  @Korporal if you're interested in contributing a fix, please feel free to.  If you ping me on the PR i'll review it quickly.  Thanks!
