### ISSUE TITLE
KeyNotFoundException from FindReferencesSearchEngine.ProcessDocumentAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#57235]
FAR in Roslyn

```
StreamJsonRpc.RemoteInvocationException: The given key was not present in the dictionary. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__19.MoveNext() in D:\R1\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 301
RPC server exception:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
      at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__18.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 276
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__17.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 258
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__17.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 268
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__15.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 215
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__15.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 225
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 112
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 112
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 116
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext() in D:\R1\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder_FindReferences_Current.cs:line 54
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Editor.FindUsages.AbstractFindUsagesService.<FindReferencesAsync>d__15.MoveNext() in D:\R1\src\EditorFeatures\Core\FindUsages\AbstractFindUsagesService_FindReferences.cs:line 149
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteFindUsagesService.<>c__DisplayClass3_0.<<FindReferencesAsync>b__0>d.MoveNext() in D:\R1\src\Workspaces\Remote\ServiceHub\Services\FindUsages\RemoteFindUsagesService.cs:line 52
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__15.MoveNext() in D:\R1\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 117
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/57449

**Comment by GrahamTheCoder** [comment]
I just hit this same stack trace in a [unit test run](https://github.com/icsharpcode/CodeConverter/runs/6723689584?check_suite_focus=true)

The csproj references version 4.1.0 which was released quite a while after this issue was closed
(Test csproj: https://github.com/icsharpcode/CodeConverter/blob/6b9428ecb9a1481296b66c5198132a5377e8f188/Tests/Tests.csproj#L30-L35)

#### Rarity
I clicked rerun and it passed as normal: https://github.com/icsharpcode/CodeConverter/runs/6753432003?check_suite_focus=true

There are probably a few hundred tests that hit this code path that have all run a hundred times since using this version of the library and this is the first time I've spotted this.

#### Stack trace

```csharp
The given key was not present in the dictionary.
       at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__18.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__17.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__17.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__34.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__37.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at ICSharpCode.CodeConverter.CSharp.UsageTypeAnalyzer.<GetUsagesAsync>d__2.MoveNext() in /_/CodeConverter/CSharp/UsageTypeAnalyzer.cs:line 34
    --- End of stack trace from previous location where exception was thrown ---
```

Since it seems rare (in my use case anyway) I'd say it probably isn't very high priority. Just wanted to share the information in case it helps.
