### ISSUE TITLE
Differences detected in solution checksum in integration tests

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#57324]
https://dev.azure.com/dnceng/public/_build/results?buildId=1435293

```
10/21/2021 23:00:35 Coordinated Universal Time: Error : 10 :Exception thrown from request "175" for method GetSemanticClassificationsAsync: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
K6KNtbaq4J9OHFz9CN5KpVfBZSA=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
1Klmgbr52uzG1q1KW5Pyh57zGTo=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
DWprk9+b7/OEg616KG74XuO9LGE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
7QTq/v/nTyIDHiwCiano7+nASYE=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
K6KNtbaq4J9OHFz9CN5KpVfBZSA=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
1Klmgbr52uzG1q1KW5Pyh57zGTo=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
DWprk9+b7/OEg616KG74XuO9LGE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
7QTq/v/nTyIDHiwCiano7+nASYE=, Microsoft.CodeAnalysis.Options.SerializableOptionSet


   at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Host/ThrowingTraceListener.cs:line 27
   at System.Diagnostics.TraceInternal.Fail(String message)
   at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<<GetProjectSubsetSolutionAsync>g__GetProjectSubsetSolutionSlowAsync|15_0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__13`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 99
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
K6KNtbaq4J9OHFz9CN5KpVfBZSA=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
1Klmgbr52uzG1q1KW5Pyh57zGTo=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
DWprk9+b7/OEg616KG74XuO9LGE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
7QTq/v/nTyIDHiwCiano7+nASYE=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
K6KNtbaq4J9OHFz9CN5KpVfBZSA=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
1Klmgbr52uzG1q1KW5Pyh57zGTo=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
DWprk9+b7/OEg616KG74XuO9LGE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
7QTq/v/nTyIDHiwCiano7+nASYE=, Microsoft.CodeAnalysis.Options.SerializableOptionSet


   at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Host/ThrowingTraceListener.cs:line 27
   at System.Diagnostics.TraceInternal.Fail(String message)
   at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<<GetProjectSubsetSolutionAsync>g__GetProjectSubsetSolutionSlowAsync|15_0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__13`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 99<---
```

![23 03 22-BasicGenerateConstructorDialog VerifyDeselect-ContainsException (2)](https://user-images.githubusercontent.com/1408396/138483239-89466fae-3798-4fcb-9b0a-b7bdd8ea9fdc.png)

|Build|Kind|Start Time|
|---|---|---|
[1433408](https://dev.azure.com/dnceng/public/_build/results?buildId=1433408)|Rolling|2021-20-10|
[1434995](https://dev.azure.com/dnceng/public/_build/results?buildId=1434995)|[PR 57309](https://github.com/dotnet/roslyn/pull/57309)|2021-21-10|
[1435293](https://dev.azure.com/dnceng/public/_build/results?buildId=1435293)|Rolling|2021-21-10|
[1436880](https://dev.azure.com/dnceng/public/_build/results?buildId=1436880)|Rolling|2021-22-10|
[1440184](https://dev.azure.com/dnceng/public/_build/results?buildId=1440184)|Rolling|2021-26-10|

**Comment by CyrusNajmabadi** [comment]
Looks like no hits in 6 months.  Closing out as presumably fixed with all the OOP changes that have gone in.
