### ISSUE TITLE
Cascadia Code/Mono crashes VS 2022 Editor

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#57704]
See https://github.com/dotnet/roslyn/pull/56530#issuecomment-966149617

Microsoft Visual Studio Community 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Azure App Service Tools v3.0.0   17.0.789.48259
Azure App Service Tools v3.0.0

C# Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Currently I am experiencing a few issues when trying to work with Roslyn.sln. VS 2019 won't run unit tests anymore and VS 2022 refuses to show any editor windows.

![image](https://user-images.githubusercontent.com/344204/141274352-c480eb99-3ff1-4829-9e88-1710518ee53b.png)

Now it finally displays the tests, in the pane to the left, but also printed this exception to the output.

```
Log level is set to Informational (Default).
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation. ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32 A_0)
   at MS.Internal.FontFace.PhysicalFontFamily.MapGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch, CharacterBufferRange charString, CultureInfo digitCulture, Int32& advance, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFaceFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Boolean nullFont, Double scaleInEm, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Boolean ignoreMissing, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, CanonicalFontFamilyReference canonicalFamilyReference, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapOnceByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapItem(CharacterBufferRange unicodeString, CultureInfo culture, Span itemSpan, SpanVector`1& cachedScaledTypefaceIndexSpans, Int32 ichItem)
   at MS.Internal.Shaping.TypefaceMap.GetShapeableText(CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at MS.Internal.Shaping.GlyphingCache.GetShapeableText(Typeface typeface, CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at System.Windows.Media.TextFormatting.TextCharacters.MS.Internal.TextFormatting.ITextSymbols.GetTextShapeableSymbols(GlyphingCache glyphingCache, CharacterBufferReference characterBufferReference, Int32 length, Boolean rightToLeft, Boolean isRightToLeftParagraph, CultureInfo digitCulture, TextModifierScope textModifierScope, TextFormattingMode textFormattingMode, Boolean isSideways)
   at MS.Internal.TextFormatting.TextStore.CreateTextLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.CreateLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel, Int32& textRunLength)
   at MS.Internal.TextFormatting.TextStore.CreateLSRunsUniformBidiLevel(SpanVector runInfoVector, SpanVector textEffectsVector, Int32 runInfoFirstCp, Int32 ichUniform, Int32 cchUniform, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.FetchLSRun(Int32 lscpFetch, TextFormattingMode textFormattingMode, Boolean isSideways, Plsrun& plsrun, Int32& lsrunOffset, Int32& lsrunLength)
   at MS.Internal.TextFormatting.LineServicesCallbacks.FetchRunRedefined(IntPtr pols, Int32 lscpFetch, Int32 fIsStyle, IntPtr pstyle, Char* pwchTextBuffer, Int32 cchTextBuffer, Int32& fIsBufferUsed, Char*& pwchText, Int32& cchText, Int32& fIsHidden, LsChp& lschp, IntPtr& lsplsrun)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine.FormatLine(FullTextState fullText, Int32 cpFirst, Int32 lineLength, Int32 formatWidth, Int32 finiteFormatWidth, Int32 paragraphWidth, LineFlags lineFlags, FormattedTextSymbols collapsingSymbol)
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine..ctor(FormatSettings settings, Int32 cpFirst, Int32 lineLength, Int32 paragraphWidth, LineFlags lineFlags)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.FormatLine(TextSource textSource, Int32 textSourcePosition, Double maxLineLength, TextParagraphProperties paraProps, TextLineBreak lineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.MoveNext()
   at System.Windows.Media.FormattedText.DrawAndCalculateMetrics(DrawingContext dc, Point drawingOffset, Boolean getBlackBoxMetrics)
   at System.Windows.Media.FormattedText.get_Metrics()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.TextInfoCache.GetTextInfo(TextRunProperties key)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedTextSourceFactoryService.Create(ITextSnapshot sourceTextSnapshot, ITextSnapshot visualBufferSnapshot, Int32 tabSize, Double lineSpacing, Double baseIndentation, Double wordWrapWidth, Double maxAutoIndent, Boolean useDisplayMode, IClassifier aggregateClassifier, ITextAndAdornmentSequencer sequencer, IClassificationFormatMap classificationFormatMap, Boolean isViewWrapEnabled)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PreLayout(LayoutLineCache lineCache)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.CreateAndTrackTextView(ITextDataModel dataModel, ITextViewRoleSet roles, IEditorOptions parentOptions, Boolean initialize)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.CreateTextView(ITextBuffer textBuffer, ITextViewRoleSet roles, IEditorOptions parentOptions)
   at Microsoft.VisualStudio.TestWindow.Internal.UI.Summary.SummaryBuilder.InitializeTextView()
   at Microsoft.VisualStudio.TestWindow.Internal.UI.Summary.SummaryControl.<InitializeControlContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
Connected to test environment '< Local Windows Environment >'
Test data store opened in 81,904 sec.
```

**Comment by siegfriedpammer** [comment]
Additional info: changing the editor font to "Consolas" (from Cascadia Mono) fixes the issue. And changing it back, crashes VS immediately.

If you need any further information, let me know.

**Comment by siegfriedpammer** [comment]
Same happens with Cascadia Code...

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue. Can you please file this over at developercommunity instead?  Thanks!

**Comment by siegfriedpammer** [comment]
Done... https://developercommunity.visualstudio.com/t/Cascadia-CodeMono-crashes-VS-2022-Edito/1580696
