### ISSUE TITLE
CSharpAddBracesCodeFixProvider Exception with Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57770]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpAddBracesCodeFixProvider-Exception/1582211)._

---
[severity:It's more difficult to complete my work]
I have just installed Visual Studio 2022 17.0.0 Current.  

I go to the **C#** | **Code Style** | **General** section in the **Options** and then set the Severity of **Prefer Braces** to _Suggestion_:

! [unnamed.png] (https://aka.ms/dc/image?name=B909454ae438048afb1b46a108c1d05aa637723289933317080_unnamed.png&tid=909454ae438048afb1b46a108c1d05aa637723289933317080)

Then I click the light bulb to show suggestions:

! [unnamed (1).png] (https://aka.ms/dc/image?name=B5e031c9257514687b94fd43657047fa3637723290358322459_unnamed_(1).png&tid=5e031c9257514687b94fd43657047fa3637723290358322459)

In this way, I obtain the following error:

! [unnamed (2).png] (https://aka.ms/dc/image?name=B647d1c5cb8fe4a53a29dde355517a965637723290698297024_unnamed_(2).png&tid=647d1c5cb8fe4a53a29dde355517a965637723290698297024)

Here it is also the stack trace: 

System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.AddBraces.CSharpAddBracesCodeFixProvider.<>c.<FixAllAsync>b__6_0(SyntaxNode currentStatement,SyntaxGenerator g)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Feedback Bot on 11/12/2021, 08:42 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 11/12/2021, 08:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
refer [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1435177)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/57835
