### ISSUE TITLE
IBCMerge error for EditorFeatures.Wpf in signed build

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#57863]
EXEC : error : the following exception was thrown while processing profile data [D:\a\_work\1\s\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) the following exception was thrown while processing profile data
  System.BadImageFormatException: Read out of bounds.
     at System.Reflection.Throw.OutOfBounds()
     at MDReader.GetSigType(BlobReader& sig, ModuleId moduleId) in /_/src/IbcMerge/ibcmerge.cs:line 1840
     at MDReader.GetSigType(BlobReader& sig, ModuleId moduleId) in /_/src/IbcMerge/ibcmerge.cs:line 2045
     at MDReader.GetMethodName(ModuleId moduleId, UInt32 methodToken, BlobReader& genSig, Boolean encodesMethodInstantiation, String& returnType) in /_/src/IbcMerge/ibcmerge.cs:line 2312
     at MDReader.GetSigMethodInstantiation(BlobReader sig, String& typeInstantiation, String& returnType) in /_/src/IbcMerge/ibcmerge.cs:line 2143
     at IBCData.ParamSpecLookupName(MDReader mdr, UInt32 token) in /_/src/IbcMerge/ibcmerge.cs:line 1564
     at IBCRead.DumpAsXml(String outFileName) in /_/src/IbcMerge/ibcmerge.cs:line 9867
     at IBCMerge.Merge(String[] args) in /_/src/IbcMerge/ibcmerge.cs:line 11196
     at IBCMerge.Main(String[] args) in /_/src/IbcMerge/ibcmerge.cs:line 10638
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21559.3\tools\OptimizationData.targets(191,5): error : IBCMerge failed with exit code -1. [D:\a\_work\1\s\src\EditorFeatures\Core.Wpf\Microsoft.CodeAnalysis.EditorFeatures.Wpf.csproj]
##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21559.3\tools\OptimizationData.targets(191,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) IBCMerge failed with exit code -1.

**Comment by genlu** [comment]
Close. Didn't hit this recently
