### ISSUE TITLE
Broken unit test Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5800]
Test 'Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3' failed:
	System.InvalidOperationException : Key already exists in table.
	Implementation\Interop\CleanableWeakComHandleTable.cs(174,0): at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value)
	CodeModel\FileCodeModel.cs(193,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated(SyntaxNodeKey nodeKey, CodeElement element)
	CodeModel\InternalElements\CodeClass.cs(31,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind)
	CodeModel\VisualBasicCodeModelService.vb(563,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\FileCodeModel.cs(226,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetOrCreateCodeElement[T](SyntaxNode node)
	CodeModel\AbstractCodeModelService.cs(400,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttribute(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\AbstractCodeModelService.cs(506,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttributeArgument(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\VisualBasicCodeModelService.vb(538,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\FileCodeModel_CodeGen.cs(155,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddAttributeArgument(SyntaxNode containerNode, String name, String value, Object position)
	CodeModel\InternalElements\CodeAttribute.cs(150,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.<>c__DisplayClass23_0.<AddArgument>b__0()
	CodeModel\FileCodeModel.cs(275,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
	CodeModel\InternalElements\CodeAttribute.cs(148,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position)
	at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position)
	CodeModel\AbstractCodeAttributeTests.vb(55,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data)
	CodeModel\AbstractCodeAttributeTests.vb(123,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data)
	CodeModel\VisualBasic\CodeAttributeTests.vb(847,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3()

**Comment by gafter** [comment]
Also `AddAttributeArgument2`
