### ISSUE TITLE
new AdhocWorkspace throws NullReferenceException on API startup

### ISSUE THREAD

**Issue by h0wXD** [dotnet/roslyn#58121]
**Version Used**: 
Latest .NET 6 SDK, with latest 4.0.0.0 nuget packages referenced.

**Steps to Reproduce**:

1. Start my .NET 6 API server which provides server side autocompletion for a react side C# code editor.
2. First few autocomplete requests will throw NullReferenceException when creating a new AdhocWorkspace.

**Expected Behavior**:
No exception thrown when invoked immediately on startup.

**Actual Behavior**:
I get a null reference exception when initializing the AdhocWorkspace, however once my app is up and running it goes away and starts working. I am targeting the latest .NET 6 with latest nuget packages referenced. 

![image](https://user-images.githubusercontent.com/10574115/144758246-36164e35-74d6-4ad7-8829-d42c1fb0033d.png)

**Comment by h0wXD** [comment]
Seems to happen when the API is offline, and requests are queuing up on client side application, and once they hit the API, with MefHostServices being executed more than once at the same time.

call stack being:
```System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.Workspaces
  StackTrace:
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService..ctor(IGlobalOptionService globalOptionService, HostWorkspaceServices workspaceServices)
   at Microsoft.CodeAnalysis.Options.OptionServiceFactory.CreateService(HostWorkspaceServices workspaceServices)
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c__DisplayClass5_0.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.Workspace..ctor(HostServices host, String workspaceKind)
   at Microsoft.CodeAnalysis.AdhocWorkspace..ctor(HostServices host, String workspaceKind)
   at MyCode.DynamicCodeHelper.GetCompletionService(String text) in MyCode\DynamicCodeHelper.cs:line 832
   at MyCode.DynamicCodeHelper.<GetCompileSuggestionsAsync>d__10.MoveNext() in MyCode\DynamicCodeHelper.cs:line 475
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at API.Controllers.MyCodeController.<GetSuggestionsAsync>d__8.MoveNext() in Controllers\MyCodeController.cs:line 253
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    Microsoft.CodeAnalysis.Options.OptionServiceFactory.OptionService.OptionService(Microsoft.CodeAnalysis.Options.IGlobalOptionService, Microsoft.CodeAnalysis.Host.HostWorkspaceServices)
    Microsoft.CodeAnalysis.Options.OptionServiceFactory.CreateService(Microsoft.CodeAnalysis.Host.HostWorkspaceServices)
    Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices..ctor.AnonymousMethod__1()
    System.Lazy<T>.ViaFactory(System.Threading.LazyThreadSafetyMode)
    System.Lazy<T>.ExecutionAndPublication(System.LazyHelper, bool)
    System.Lazy<T>.CreateValue()
    Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetService<TWorkspaceService>()
    Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService<TWorkspaceService>()
    Microsoft.CodeAnalysis.Workspace.Workspace(Microsoft.CodeAnalysis.Host.HostServices, string)
    Microsoft.CodeAnalysis.AdhocWorkspace.AdhocWorkspace(Microsoft.CodeAnalysis.Host.HostServices, string)
    ...
    [Call Stack Truncated]

**Comment by sharwell** [comment]
> Seems to happen when the API is offline, and requests are queuing up on client side application, and once they hit the API, with MefHostServices being executed more than once at the same time.

MEF 2 (the default composition if you don't provide one separately) does not support concurrent use. I strongly recommend constructing your workspace with vs-mef explicitly, which is much faster and supports concurrent execution. Here's how we construct an AdhocWorkspace with vs-mef for testing:

https://github.com/dotnet/roslyn-sdk/blob/10b52dee20f620354c35115ce609714bafee505d/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L1345-L1350
