### ISSUE TITLE
System.InvalidOperationException at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#5837]
I saw the following exception in my Jenkins [run](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/308/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp/CodeAttributeTests/AddAttributeArgument3/), the failure is unrelated to my change:

```
Failed

Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3 (from (empty)) 

MESSAGE:
System.InvalidOperationException : Key already exists in table.

STACK TRACE:
at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Def\Implementation\Interop\CleanableWeakComHandleTable.cs:line 174
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated(SyntaxNodeKey nodeKey, CodeElement element) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 193
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs:line 31 
at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs:line 521 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetOrCreateCodeElement[T](SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 226 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttribute(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs:line 400 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttributeArgument(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs:line 506 at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs:line 502 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddAttributeArgument(SyntaxNode containerNode, String name, String value, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs:line 155 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.<>c__DisplayClass23_0.<AddArgument>b__0() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 150 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 275 at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 148 
at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position) 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 55 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 123 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeAttributeTests.vb:line 639\CodeAttribute.cs:line 150 at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 275 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 148 at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position) at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 55 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 123 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeAttributeTests.vb:line 639

```

**Comment by Pilchie** [comment]
These are all fixed now, right?

**Comment by DustinCampbell** [comment]
Yes, this is a dupe
