### ISSUE TITLE
Null array constant in metadata causes overflow in attribute decoding

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#58598]
The following test should pass:

```cs

        [Fact]
        public void MemberNotNull_NullConstant()
        {
            var c = CreateNullableCompilation(new[] { @"
using System.Diagnostics.CodeAnalysis;
public class C
{
    [MemberNotNull((string[]?)null)]
    public void Init() => throw null!;
}
", MemberNotNullAttributeDefinition }, parseOptions: TestOptions.Regular9);

            CompileAndVerify(c, symbolValidator: module =>
            {
                var c = module.ContainingAssembly.GetTypeByMetadataName("C");
                var init = c.GetMember<MethodSymbol>("Init");
                Assert.Empty(init.NotNullMembers);
            });
        }
```

Instead, it crashes with the following stack:

```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.MemberNotNull_NullConstant:
    Outcome: Failed
    Error Message:
    System.OverflowException : Arithmetic operation resulted in an overflow.
    Stack Trace:
       at Microsoft.CodeAnalysis.PEModule.CrackStringArrayInAttributeValue(ImmutableArray`1& value, BlobReader& sig) in /home/fred/git/r2/src/Compilers/Core/Portable/MetadataReader/PEModule.cs:line 1906
   at Microsoft.CodeAnalysis.PEModule.TryExtractValueFromAttribute[T](CustomAttributeHandle handle, T& value, AttributeValueExtractor`1 valueExtractor) in /home/fred/git/r2/src/Compilers/Core/Portable/MetadataReader/PEModule.cs:line 1711
   at Microsoft.CodeAnalysis.PEModule.TryExtractStringArrayValueFromAttribute(CustomAttributeHandle handle, ImmutableArray`1& value) in /home/fred/git/r2/src/Compilers/Core/Portable/MetadataReader/PEModule.cs:line 1689
   at Microsoft.CodeAnalysis.PEModule.GetMemberNotNullAttributeValues(EntityHandle token) in /home/fred/git/r2/src/Compilers/Core/Portable/MetadataReader/PEModule.cs:line 1379
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol.PopulateMemberNotNullData() in /home/fred/git/r2/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:line 654
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEMethodSymbol.get_NotNullMembers() in /home/fred/git/r2/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:line 635
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.<>c.<MemberNotNull_NullConstant>b__480_0(ModuleSymbol module) in /home/fred/git/r2/src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:line 20436
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.<>c__DisplayClass30_0.<CompileAndVerify>b__1(IModuleSymbol m) in /home/fred/git/r2/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs:line 834
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.RunValidators(CompilationVerifier verifier, Action`1 assemblyValidator, Action`1 symbolValidator) in /home/fred/git/r2/src/Compilers/Test/Core/CommonTestBase.cs:line 135
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify) in /home/fred/git/r2/src/Compilers/Test/Core/CommonTestBase.cs:line 160
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) in /home/fred/git/r2/src/Compilers/Test/Core/CommonTestBase.cs:line 68
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify) in /home/fred/git/r2/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs:line 842
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.MemberNotNull_NullConstant() in /home/fred/git/r2/src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:line 20432
```

`CrackStringArrayInAttributeValue` attempts to figure out the length of the array, which is returned as `uint.MaxValue`. This is then turned into an array length, which overflows, resulting in the crash.

**Comment by 333fred** [comment]
Related to https://github.com/dotnet/roslyn/issues/58025.
