### ISSUE TITLE
Integration tests fail when System.Composition.* packages are updated to 6.0.0

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59128]
```
Microsoft.VisualStudio.Composition.CompositionFailedException : Expected 1 export(s) with contract name "Microsoft.CodeAnalysis.Options.IGlobalOptionService" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.Extensibility.Testing.InProcComponent.<GetComponentModelServiceAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.InProcess.StateResetInProcess.<ResetGlobalOptionsAsync>d__0.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__3.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__7.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractEditorTest.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
Integration tests run on 17.1 Preview 1.0. Was VS updated to System.Composition 6.0 prior to that?

**Comment by tmat** [comment]
Not sure.

**Comment by jinujoseph** [comment]
Blocked: on the machine upgrade to support to this package

**Comment by sharwell** [comment]
Here's the file containing these VS references:
https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FConfigData%2FPackages%2FMicrosoft.VisualStudio.MinShell%2Fcorefx.props&version=GBmain&_a=contents

Here's the version we're currently on (17.1 Preview 1.0):
https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FConfigData%2FPackages%2FMicrosoft.VisualStudio.MinShell%2Fcorefx.props&version=GTrelease%2Fvs%2F17.1-preview.1&_a=contents

Based on this, we can use at most System.Composition 5.0.1 and System.ComponentModel.Composition 5.0.0 in integration tests. _However_, if we exceed the versions used for 17.0.5 (5.0.1 and 4.5.0, respectively), it will break users who are expecting those changes to only appear in a vs-deps branch.

**Comment by sharwell** [comment]
Reassigned to @tmat to handle based on the added details.

**Comment by CyrusNajmabadi** [comment]
@tmat @sharwell is there anything left to do here, of not, please close out.
