### ISSUE TITLE
Possible race in an Assert recently added to Compilation.GetTypeByMetadataName

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#59395]
The following assert fails from time to time in context of different unit-tests:
```
Debug.Assert(result || (_getTypeCache.TryGetValue(fullyQualifiedMetadataName, out var addedType) && ReferenceEquals(addedType, val)));
```

Example #1:
```
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.ImplementInterface.ImplementInterfaceTests.TestIntegralAndFloatLiterals3s 529ms
Error:
System.InvalidOperationException : Assertion failed

Stack trace:
   at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in D:\GitHub\roslyn\src\Compilers\Test\Core\ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.Compilation.GetTypeByMetadataName(String fullyQualifiedMetadataName) in D:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1172
   at Microsoft.CodeAnalysis.Shared.Extensions.ICompilationExtensions.ComAliasNameAttributeType(Compilation compilation) in D:\GitHub\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Extensions\ICompilationExtensions.cs:line 141
   at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.AttributesToRemove(Compilation compilation) in D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction_Property.cs:line 70
   at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMethod(Compilation compilation, IMethodSymbol method, Accessibility accessibility, DeclarationModifiers modifiers, Boolean generateAbstractly, Boolean useExplicitInterfaceSymbol, String memberName) in D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction_Method.cs:line 30
   at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMember(Compilation compilation, ISymbol member, String memberName, Boolean generateInvisibly, Boolean generateAbstractly, Boolean addNew, Boolean addUnsafe, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior) in D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs:line 412
   at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMember(Compilation compilation, ISymbol member, ArrayBuilder`1 implementedVisibleMembers, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior) in D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs:line 330
   at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMembers(Compilation compilation, ImmutableArray`1 unimplementedMembers, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior) in D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs:line 
```

Example #2:
```
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.ImplementInterface.ImplementInterfaceTests.TestCharLiterals [FAIL]
  System.InvalidOperationException : Assertion failed
  Stack Trace:
    D:\GitHub\roslyn\src\Compilers\Test\Core\ThrowingTraceListener.cs(26,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
       at System.Diagnostics.TraceListener.Fail(String message)
       at System.Diagnostics.TraceInternal.Fail(String message)
       at System.Diagnostics.Debug.Assert(Boolean condition)
    D:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs(1172,0): at Microsoft.CodeAnalysis.Compilation.GetTypeByMetadataName(String fullyQualifiedMetadataName)
    D:\GitHub\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Extensions\ICompilationExtensions.cs(153,0): at Microsoft.CodeAnalysis.Shared.Extensions.ICompilationExtensions.DynamicAttributeType(Compilation compilation)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction_Property.cs(70,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.AttributesToRemove(Compilation compilation)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction_Method.cs(30,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMethod(Compilation compilation, IMethodSymbol method, Accessibility accessibility, DeclarationModifiers modifiers, Boolean generateAbstractly, Boolean useExplicitInterfaceSymbol, String memberName)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs(412,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMember(Compilation compilation, ISymbol member, String memberName, Boolean generateInvisibly, Boolean generateAbstractly, Boolean addNew, Boolean addUnsafe, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs(330,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMember(Compilation compilation, ISymbol member, ArrayBuilder`1 implementedVisibleMembers, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs(247,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.GenerateMembers(Compilation compilation, ImmutableArray`1 unimplementedMembers, ImplementTypePropertyGenerationBehavior propertyGenerationBehavior)
    D:\GitHub\roslyn\src\Features\Core\Portable\ImplementInterface\AbstractImplementInterfaceService.CodeAction.cs(201,0): at Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService.ImplementInterfaceCodeAction.<GetUpdatedDocumentAsync>d__23.MoveNext()
```

It looks like the assert was added in https://github.com/dotnet/roslyn/pull/58366.

**Comment by AlekseyTs** [comment]
CC @333fred
