### ISSUE TITLE
ArgumentException from AnalyzerDriver

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59626]
```
System.ArgumentException: An item with the same key has already been added.
      at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
      at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
      at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
      at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
      at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
      at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
      at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationBlocksToAnalyze(ImmutableArray`1 executableBlocks, SemanticModel semanticModel, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass12_0.<TryExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|3()
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisState, GroupedAnalyzerActions coreActions, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisState, Boolean isGeneratedCodeSymbol, IGroupedAnalyzerActions additionalPerSymbolActions, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessSymbolDeclaredAsync>d__132.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
```

Code was something like:

```C#
internal readonly record struct BlockStructureOptions(
        bool ShowBlockStructureGuidesForCommentsAndPreprocessorRegions = false,
        bool ShowBlockStructureGuidesForDeclarationLevelConstructs = true,
        bool ShowBlockStructureGuidesForCodeLevelConstructs = true,
        bool ShowOutliningForCommentsAndPreprocessorRegions = true,
        bool ShowOutliningForDeclarationLevelConstructs = true,
        bool ShowOutliningForCodeLevelConstructs = true,
        bool CollapseRegionsWhenCollapsingToDefinitions = false,
        int MaximumBannerLength = 80,
        bool IsMetadataAsSource = false)
    {
        public BlockStructureOptions(ShowBlockStructureGuidesForCommentsAndPreprocessorRegions = false)
            : base()
        {
        }

        public static readonly BlockStructureOptions Default = new();
    }
```

**Comment by jcouv** [comment]
Tagging @333fred to triage and advise.

**Comment by 333fred** [comment]
This appears to be an invalid code scenario. I attempted to reproduce in our IOperation hook by pasting the above code in, but could not. Absent a dump of the exception or a code sample that reproduces, there's nothing I can do here.
