### ISSUE TITLE
ArgumentOutOfRangeException in CSharpWrappingCodeRefactoringProvider

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#59624]
Encountered this in Version 17.2.0 Preview 2.0 [32216.311.main]

callstack:
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxNodeOrTokenList.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.GetWrapEachEdits(WrappingStyle wrappingStyle,SyntaxTrivia indentationTrivia)
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.GetWrapEveryNestedCodeActionAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.GetWrapEveryGroupAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.AddWrappingGroupsAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.ComputeWrappingGroupsAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractSyntaxWrapper.AbstractCodeActionComputer`1.GetTopLevelCodeActionsAsync[TWrapper](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractWrappingCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment]
Working on a fix.
