### ISSUE TITLE
CSharpRecommendationServiceRunner breaks on some bad syntax using a third party api

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59714]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpRecommendationServiceRunner-breaks/1663234)._

---
[severity:Other]
New console project > add newtonsoft json library. Type this:

```
            JObject a = new JObject();

a["b"]?. Value<bool>!();
```

Removing either the coalescing or the suppressing operator make the crash go away.

---
#### Feedback Bot on 2/14/2022, 05:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
```
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationServiceRunner.GetSymbolsOffOfContainer()
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationServiceRunner.GetRecommendedSymbols()
   at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService`1.GetRecommendedSymbolsAtPosition(Document document, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.UnnamedSymbolCompletionProvider.<ProvideCompletionsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsWithAvailabilityOfExpandedItemsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.<CreateSpellCheckCodeIssueAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.<CheckNodeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.<RegisterCodeFixesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```
