### ISSUE TITLE
ArgumentOutOfRangeException from Microsoft.CodeAnalysis.VisualBasic.UseCollectionInitializer.VisualBasicUseCollectionInitializerDiagnosticAnalyzer

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59819]
In Roslyn.sln 

```
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.VisualBasic.UseCollectionInitializer.VisualBasicUseCollectionInitializerDiagnosticAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.VisualBasic
SyntaxTree: D:\R4\src\Compilers\VisualBasic\Portable\Errors\ErrorFactories.vb
SyntaxNode: New Dictionary(Of ERRID, String ... [ObjectCreationExpressionSyntax]@[956..1064) (20,22)-(22,17)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.UseCollectionInitializer.UseCollectionInitializerAnalyzer`7.AddMatches(ArrayBuilder`1 matches)
   at Microsoft.CodeAnalysis.UseCollectionInitializer.AbstractObjectCreationExpressionAnalyzer`5.AnalyzeWorker()
   at Microsoft.CodeAnalysis.UseCollectionInitializer.UseCollectionInitializerAnalyzer`7.Analyze(SemanticModel semanticModel, ISyntaxFacts syntaxFacts, TObjectCreationExpressionSyntax objectCreationExpression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UseCollectionInitializer.AbstractUseCollectionInitializerDiagnosticAnalyzer`8.AnalyzeNode(SyntaxNodeAnalysisContext context, INamedTypeSymbol ienumerableType)
   at Microsoft.CodeAnalysis.UseCollectionInitializer.AbstractUseCollectionInitializerDiagnosticAnalyzer`8.<>c__DisplayClass5_0.<OnCompilationStart>b__0(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0028	Microsoft.CodeAnalysis.VisualBasic (netstandard2.0)		1	Active
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/59629
