### ISSUE TITLE
Unexpected Debug.Assert is fired for erroneous scenario. 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#59946]
```
        [Fact]
        public void Test()
        {
            var source1 =
@"
partial class C1<T> where T : C1<T>
{
}

class Test<T> where T : C1<T>
{
    static void MT1(C1<T> a)  checked {
    {
        _ = -a;
    }}

    static void MT2()  checked {
    {
        _ = (System.Linq.Expressions.Expression<System.Action<T>>)((T b) => (-b).ToString());
    }}
}
";

            var compilation1 = CreateCompilation(source1, options: TestOptions.DebugDll);

            compilation1.VerifyDiagnostics(
                );
        }
```

Observed:
```
System.InvalidOperationException : Assertion failed
Stack Trace:
  src\Compilers\Test\Core\ThrowingTraceListener.cs(26,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
     at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
     at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
     at System.Diagnostics.Debug.Fail(String message, String detailMessage)
     at System.Diagnostics.Debug.Assert(Boolean condition)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(804,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.CheckMethodGroup(BoundMethodGroup node, MethodSymbol method, Boolean parentIsConversion, TypeSymbol convertedToType)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(795,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitMethodGroup(BoundMethodGroup node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(6066,0): at Microsoft.CodeAnalysis.CSharp.BoundMethodGroup.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(88,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(212,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(75,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(10330,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitCall(BoundCall node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(444,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitCall(BoundCall node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(6160,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(88,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(212,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(75,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(10003,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3557,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(22,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9947,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3192,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(10485,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitLambda(BoundLambda node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(601,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitLambda(BoundLambda node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(7519,0): at Microsoft.CodeAnalysis.CSharp.BoundLambda.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(88,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(212,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(75,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9913,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitConversion(BoundConversion node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(773,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitConversion(BoundConversion node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(2840,0): at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(88,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(212,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(75,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9821,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitAssignmentOperator(BoundAssignmentOperator node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(247,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitAssignmentOperator(BoundAssignmentOperator node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(1898,0): at Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(88,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(242,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(216,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(75,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(10003,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3557,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(22,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9947,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3192,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(22,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9947,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3192,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(22,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9947,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(3192,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(151,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs(78,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeWalkerWithStackGuard.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(371,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.Visit(BoundNode node)
src\Compilers\CSharp\Portable\Lowering\DiagnosticsPass_ExpressionTrees.cs(40,0): at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.IssueDiagnostics(CSharpCompilation compilation, BoundNode node, BindingDiagnosticBag diagnostics, MethodSymbol containingSymbol)
src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(1119,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(525,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(419,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs(139,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(330,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(165,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2759,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(BindingDiagnosticBag diagnostics, Boolean doLowering, CancellationToken cancellationToken)
src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2730,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken)
src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2641,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2633,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2627,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)
src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(103,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
src\Compilers\CSharp\Test\Symbol\Symbols\StaticAbstractMembersInInterfacesTests.cs(6677,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.StaticAbstractMembersInInterfacesTests.Test()
```

It is quite possible that, if the assert is ignored, the tests completes as expected.

**Comment by jcouv** [comment]
@AlekseyTs The scenario looks niche (`checked` and expression tree) and the bug was there for many years, so I'd put this in Backlog milestone. How does that sound?

**Comment by AlekseyTs** [comment]
Fine with me.
