### ISSUE TITLE
[Broken test] Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpGoToBase.GoToBaseFromMetadataAsSource

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#60386]
It seems `GoToBaseFromMetadataAsSource` broke once the integration test machines upgraded to 17.2 P2.

Error message:
> System.InvalidOperationException : After updating CI to 17.2 Preview 2, the following call to ExecuteCommandAsync should has its first parameter, and uint cast, removed leaving just EditorConstants.EditorCommandID.GoToBase instead of an explicit CommandID and Guid.

Stack trace:
> at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Compilers/Test/Core/ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<GoToBaseAsync>d__48.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 966
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpGoToBase.<GoToBaseFromMetadataAsSource>d__3.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpGoToBase.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Example build link: https://dev.azure.com/dnceng/public/_build/results?buildId=1681105&view=ms.vss-test-web.build-test-results-tab

**Comment by allisonchou** [comment]
cc @sharwell
