### ISSUE TITLE
Update ICSharpCode.Decompiler

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#60479]
We got that decompiler exception reported:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitTypeDefinition(ITypeDefinition type) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\ApplyAttributeTypeVisitor.cs:line 269
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.AcceptVisitor(TypeVisitor visitor) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\Implementation\MetadataTypeDefinition.cs:line 460
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.VisitParameterizedType(ParameterizedType type) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\ApplyAttributeTypeVisitor.cs:line 258
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType.AcceptVisitor(TypeVisitor visitor) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\ParameterizedType.cs:line 319
   at ICSharpCode.Decompiler.TypeSystem.ApplyAttributeTypeVisitor.ApplyAttributesToType(IType inputType, ICompilation compilation, Nullable`1 attributes, MetadataReader metadata, TypeSystemOptions options, Nullability nullableContext, Boolean typeChildrenOnly) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\ApplyAttributeTypeVisitor.cs:line 115
   at ICSharpCode.Decompiler.TypeSystem.MetadataModule.ResolveType(EntityHandle typeRefDefSpec, GenericContext context, TypeSystemOptions customOptions, Nullable`1 typeAttributes, Nullability nullableContext) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\MetadataModule.cs:line 300
   at ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.get_DirectBaseTypes() in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\Implementation\MetadataTypeDefinition.cs:line 311
   at ICSharpCode.Decompiler.TypeSystem.Implementation.BaseTypeCollector.CollectBaseTypes(IType type) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\Implementation\BaseTypeCollector.cs:line 56
   at ICSharpCode.Decompiler.TypeSystem.TypeSystemExtensions.GetAllBaseTypes(IType type) in C:\projects\ilspy\ICSharpCode.Decompiler\TypeSystem\TypeSystemExtensions.cs:line 50
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesForTypeReference(IType type) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 164
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesForMemberReference(IMember member) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 325
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespacesFromMethodBody(MethodBodyBlock method, MetadataModule module) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 281
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 117
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, CodeMappingInfo mappingInfo) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 123
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(IEntity entity, MetadataModule module, HashSet`1 namespaces) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 52
   at ICSharpCode.Decompiler.CSharp.RequiredNamespaceCollector.CollectNamespaces(EntityHandle entity, MetadataModule module, HashSet`1 namespaces) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\RequiredNamespaceCollector.cs:line 175
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IEnumerable`1 definitions) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 874
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(EntityHandle[] definitions) in C:\projects\ilspy\ICSharpCode.Decompiler\CSharp\CSharpDecompiler.cs:line 856
   at MonoDevelop.AssemblyBrowser.ItemWrapper.MemberItemWrapper.GetOutputFormatter(AssemblyBrowserView view, OutputFormatterLanguage language) in /Users/runner/work/1/s/main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/ItemWrapper/ItemWrapper.MemberItemWrapper.cs:line 122

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1509990

We're using the decompiler that roslyn uses (6.1) -the current version 7.2 should've fixed that bug.

**Comment by sharwell** [comment]
This was already fixed by https://github.com/dotnet/roslyn/pull/53304

**Comment by jinujoseph** [comment]
cc @davidwengier for info if this comes up in Mac insertion discussion

**Comment by davidwengier** [comment]
The current VS Mac insertion, https://github.com/xamarin/vsmac/pull/6172, also bumps ICSharpCode to 7.1, so should be good :)
