### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer.UnitTests.DocumentChanges.DocumentChangesTests.DidCloseWithoutDidOpen_Errors is Flakey

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#60476]
## Build Information
Build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1689246
Build error leg: Test_Windows_Desktop_Release_32 / Run Unit Tests

## Error Message

*Exception Message*
```
System.InvalidOperationException : Shutdown has already been called. - line 170
```

*CallStack*
```
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.LanguageServerTarget.ShutdownImpl() in /_/src/Features/LanguageServer/Protocol/LanguageServerTarget.cs:line 170
   at Roslyn.Test.Utilities.AbstractLanguageServerProtocolTests.TestLspServer.Dispose() in /_/src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs:line 684
   at Microsoft.CodeAnalysis.LanguageServer.UnitTests.DocumentChanges.DocumentChangesTests.<DidCloseWithoutDidOpen_Errors>d__3.MoveNext() in /_/src/Features/LanguageServer/ProtocolUnitTests/DocumentChanges/DocumentChangesTests.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
Closing as this is not skipped.
