### ISSUE TITLE
Feature 'semantic classification' is currently unavailable due to internal error (VB compiler crash)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60525]
```
StreamJsonRpc.RemoteInvocationException: Sequence contains more than one element
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: Sequence contains more than one element
      at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
      at System.Linq.ImmutableArrayExtensions.Single[T](ImmutableArray`1 immutableArray)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.CreateBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, Binder containingBinder)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position, Binder containingBinder)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetContainingNamedTypeBinderForMemberNode(VisualBasicSyntaxNode node, Binder containingBinder)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.CreateBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, Binder containingBinder)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position, Binder containingBinder)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.VisitVariableDeclarator(VariableDeclaratorSyntax node)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.MakeBinder(SyntaxNode node, Int32 position)
      at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderAtOrAbove(SyntaxNode node, Int32 position)
      at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(Int32 position)
      at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(ExpressionSyntax node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNameSyntax(NameSyntax node, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(SyntaxNode syntax, SemanticModel semanticModel, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsInCurrentProcessAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass18_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__13`1.MoveNext()
```

I've no repro unfortunately. It happened once and I couldn't reproduce.

**Comment by Youssef1313** [comment]
I think I got a repro:

- Checkout 6888cd64fd590ed8a3c66fcda9804ab8d6e08b98
- Go to VisualBasicAddImportsService.vb
- After the last `Imports`, paste the following (it's C# code pasted in VB file):

    ```csharp
    #if CODE_STYLE
    using OptionSet = Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions;
    #else
    using OptionSet = Microsoft.CodeAnalysis.Options.OptionSet;
    #endif
    ```

**Note: CTRL+Z messes up everything with me. (IDE issue)**

**Comment by jcouv** [comment]
@Youssef1313 I wasn't able to repro with those steps (`VisualStudio.17.IntPreview/17.2.0-pre.3.0+32314.332.main`). Also didn't find a watson crash report in `CreateBinderForNodeAndUsage` yet.
If you're still able to repro, a crash dump with be greatly appreciated. (some [tips](https://github.com/dotnet/roslyn/blob/main/docs/wiki/Troubleshooting-tips.md#capturing-a-crash-dump) for doing that if you need any)

**Comment by Youssef1313** [comment]
It was an always repro for the specific Visual Studio instance that I had open at that time (I think it somehow got into a bad state (possibly due to a race?) that caused this to always repro). At some point it happened that we had a symbol with two `<invalid-global-code>` children, then `CreateBinderForNodeAndUsage` is going to definitely crash for that.

---

> Also didn't find a watson crash report in CreateBinderForNodeAndUsage yet.

I would expect a dump file to be too large. My 5Mbps connection won't be able to upload such a large file.

---

@jcouv If it's hard to investigate from a StackTrace only, feel free to close.

**Comment by jcouv** [comment]
@AlekseyTs I'm not sure we'll have enough information in this bug to figure it out. Would you mind taking a look and see if something jumps out? If not, we can close until we get a Watson/crash dump.

**Comment by AlekseyTs** [comment]
This issue doesn't look actionable. Not enough information.

**Comment by patdevlin** [comment]
I am having the same issue on Visual Studio 17.4.2, see image below and stack trace:

![image](https://user-images.githubusercontent.com/106593309/205068946-360b61e0-0ca9-4318-8a09-058b6b99909f.png)


StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete. ---> System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.SendAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   --- End of inner exception stack trace ---
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)

Only extension installed is =

JetBrains ReSharper 2022.2.4 Build 222.0.20221024.165723 built on 2022-10-24
dotCover 2022.2.20221024.174408
dotTrace 2022.2.20221024.174359
ReSharper C++ 2022.2.20221027.94151
ReSharper 2022.2.20221024.173218
dotMemory 2022.2.20221024.174359

If you need any further information let me know and i am happy to share.

**Comment by AlekseyTs** [comment]
@patdevlin Why do you think this is the same issue?

**Comment by DrGriff** [comment]
I had a similar 'semantic classification' warning, but with different call stack.  I'm not using VB but C#

> StreamJsonRpc.RemoteInvocationException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
>    at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
> RPC server exception:
> System.ArgumentException: SyntaxTree is not part of the compilation (Parameter 'syntaxTree')
>       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
>       at Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(Document document, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.AddEmbeddedLanguageClassificationsAsync(Document document, TextSpan textSpan, ClassificationOptions options, SegmentedList`1 result, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddClassificationsInCurrentProcessAsync(Document document, TextSpan textSpan, ClassificationType type, ClassificationOptions options, SegmentedList`1 result, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
>    --- End of stack trace from previous location ---
>       at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
>    --- End of stack trace from previous location ---
>       at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
>       at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
