### ISSUE TITLE
VS crashes (AV) in MemberRangeMap.UpdateMemberRange_NoLock

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6074]
Crash dump at 

%internal_share%\public\tomat\Bugs\6074

There is something strange going on - the callstack points to a method that doesn't have any dereferences, so it might be deeper issue than what can be seen in the source (bad IL, CLR JIT bug, memory corruption, etc.). Also, it wasn't straightforward to capture this dump. VS just disappeared. It was necessary to attach a debugger, stop at the exception and then save the memory dump.

```
   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length) in F:\Builds\5437\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Core\Portable\Text\TextSpan.cs:line 30
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.MemberRangeMap.UpdateMemberRange_NoLock(DictionaryData data, Document document, VersionStamp newVersion, Int32 memberId, TextSpan currentSpan, VersionStamp oldVersion) in F:\Builds\5437\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV1\MemberRangeMap.cs:line 160
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.MemberRangeMap.UpdateMemberRange(DiagnosticAnalyzer analyzer, Document document, VersionStamp newVersion, Int32 memberId, TextSpan span, MemberRanges oldRanges) in F:\Builds\5437\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV1\MemberRangeMap.cs:line 54
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeBodyDocumentAsync>d__52.MoveNext() in F:\Builds\5437\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 240
```

**Comment by amcasey** [comment]
Dup of https://github.com/dotnet/roslyn/issues/5894.
