### ISSUE TITLE
NRE while renaming property in Roslyn.sln

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#60776]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.<>c__DisplayClass15_0.<GetSymbolLocationAsync>b__0(Location l)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements,Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements,Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.GetSymbolLocationAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.CreateDeclarationLocationAnnotationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.RenameAndAnnotateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.VisitToken(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIdentifierName(IdentifierNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitQualifiedName(QualifiedNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitUsingDirective(UsingDirectiveSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node)
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.AnnotateAndRename_WorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.ResolveConflictsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.ResolveConflictsInCurrentProcessAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.ResolveConflictsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.GetReplacementsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass72_0.<UpdateConflictResolutionTask>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.Join(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IUIThreadOperationContext operationContext,Boolean previewChanges)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(UIThreadOperationExecutionOptions executionOptions,Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Commit()
```

**Comment by Youssef1313** [comment]
There is a null suppression here:

https://github.com/dotnet/roslyn/blob/4814028f1e138ed17a7d05f76d8532a0c4ed5687/src/Workspaces/Core/Portable/Rename/ConflictEngine/ConflictResolver.cs#L391

Could it be it?

**Comment by ryzngard** [comment]
@Youssef1313 that's likely the line, but if it's in source and GetDocumentId returns null that's troubling. I can't imagine a scenario where that's the case. @jasonmalinowski do you know?

**Comment by Youssef1313** [comment]
@ryzngard I guess it's null for generated code.

**Comment by jasonmalinowski** [comment]
@ryzngard: yep, generated docs you have to call the GetDocumentAsync() or one of our other helpers.

**Comment by ryzngard** [comment]
@Youssef1313 it shouldn't be, but also if the locations are in a generated document we don't allow renaming because of https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.cs#L143 right? 

We could definitely add a check here and fix that line, but it seems wonky to me.

**Comment by jasonmalinowski** [comment]
Deleted earlier comment: even if it's a source generated file, GetDocumentId(SyntaxTree) should work just fine.

**Comment by jasonmalinowski** [comment]
Was it VB code and it's one of the generated trees?

**Comment by ryzngard** [comment]
"generated trees"? From source generator or are you referring to something else?

**Comment by jasonmalinowski** [comment]
The compiler I think in VB code can also create it's own trees that are added to the compilation and those wouldn't have an ID. But honestly this might be a lot easier just to get a crash dump and see what looks like.
