### ISSUE TITLE
Add constructor parameter fails with System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60816]
**Version Used**: main

**Steps to Reproduce**:
1.  Insert the following code
```
namespace Microsoft.ProgramSynthesis.Suggestions.Code.Tests.Benchmark {
public class BenchmarkMetaData {
 public int RequiredFeatures { get; }
public int Details { get; }
public int NumTransients { get; }
public int GraphSize { get; }
public int NumExpandedNodes { get; set; }
public int IndexToUriMap { get; }
 public int LastExampleIndex { get; }
 public bool NoRepeatedEdit { get; }
 public int EditSuggestionResult { get; }
 public int ValidSuggestionIndexes { get; }
 public int OnePointOneStatus { get; }
 public BenchmarkMetaData(
int requiredFeatures,
int details,
int lastExampleIndex,
bool noRepeatedEdit,
int numTransients,
int graphSize,
int numExpandedNodes,
int editSuggestionResult,
int validSuggestionIndexes,
int indexToUriMap,
int onePointOneStatus) {
RequiredFeatures = requiredFeatures;
Details = details;
LastExampleIndex = lastExampleIndex;
NoRepeatedEdit = noRepeatedEdit;
NumTransients = numTransients;
GraphSize = graphSize;
NumExpandedNodes = numExpandedNodes;
EditSuggestionResult = editSuggestionResult;
ValidSuggestionIndexes = validSuggestionIndexes;
IndexToUriMap = indexToUriMap;
OnePointOneStatus = onePointOneStatus;
}
}
```
2.  Add 2 new properties, e.g. `public int a { get; }` and `public int a2 { get; }`
3.  Select both new properties and Invoke refactoring to add them to the constructor
4.  See following exception
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.get_Item(Int32 index)
at Microsoft.CodeAnalysis.Editing.AddParameterEditor.AddParameter(ISyntaxFacts syntaxFacts,SyntaxEditor editor,SyntaxNode declaration,Int32 insertionIndex,SyntaxNode parameterDeclaration,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddParameters[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 parameters,CSharpCodeGenerationOptions options,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService`1.AddParameters[TDeclarationNode](TDeclarationNode destination,IEnumerable`1 parameters,CodeGenerationOptions options,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.AddConstructorParametersFromMembers.AddConstructorParametersFromMembersCodeRefactoringProvider.AddConstructorParametersCodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by pgroene** [comment]
You need to add 2 parameters and try to add them by selecting and quick action
