### ISSUE TITLE
TestPreviewDiagnosticTaggerInPreviewPane  is flaky

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60863]
https://runfo.azurewebsites.net/search/tests/?q=started:~1+definition:roslyn-ci+name:TestPreviewDiagnosticTaggerInPreviewPane

```
[xUnit.net 00:00:24.28]     Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests.TestPreviewDiagnosticTaggerInPreviewPane [FAIL]
  Failed Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests.TestPreviewDiagnosticTaggerInPreviewPane [61 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   0
  Stack Trace:
     at Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests.<TestPreviewDiagnosticTaggerInPreviewPane>d__9.MoveNext() in /_/src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/60856
