### ISSUE TITLE
Reenable DotNetSdk editorconfig tests on linux

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61017]
Disabled for linux CI in https://github.com/dotnet/roslyn/pull/61018

Due to failing runs, e.g.
https://dev.azure.com/dnceng/public/_build/results?buildId=1742521&view=ms.vss-test-web.build-test-results-tab&runId=47095474&resultId=157944&paneView=debug

Error message
```
System.UnauthorizedAccessException : Access to the path '/datadisks' is denied.
---- System.IO.IOException : Permission denied
```

Stack trace
```
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at Microsoft.CodeAnalysis.BuildTasks.UnitTests.DotNetSdkTests.AppendExtraEditorConfigs(String[] expected, Boolean findEditorConfigs, Boolean findGlobalConfigs) in /_/src/Compilers/Core/MSBuildTaskTests/DotNetSdkTests.cs:line 570
   at Microsoft.CodeAnalysis.BuildTasks.UnitTests.DotNetSdkTests.TestDiscoverEditorConfigFilesCanBeDisabled() in /_/src/Compilers/Core/MSBuildTaskTests/DotNetSdkTests.cs:line 440
----- Inner Stack Trace -----
```

Advice from arcade is that tests should not be peeking outside of the work items directory as other test runs may have modified state there.  However that seems to defeat the purpose of the tests since they are searching for global configs.  One other possible resolution is containerizing the tests.

**Comment by RikkiGibson** [comment]
I wonder if the feature is innately designed to peek up directory paths up to the root? Maybe it would be possible to designate the work-item directory as the "root" of the search somehow?
