### ISSUE TITLE
NFW while typing anonymous type in REPL

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6104]
Type:
```C#
 #r "C:\R1\Binaries\Debug\Microsoft.CodeAnalysis.Scripting.CSharp.dll"
> using Microsoft.CodeAnalysis.Scripting.CSharp;
. 
. CSharpScript.EvaluateAsync("X+Y", new{ }
```

```
Non-fatal exception being thrown.
   at Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.CheckThrottledSubmission(String componentName)

   at Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.ReportIfNecessary()

   at Microsoft.VisualStudio.LanguageServices.Implementation.WatsonReporter.Report(Exception exception)

   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(Exception exception, Action`1 handler)

   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportWithoutCrash(Exception exception)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.VerifyDiagnostics(SemanticModel model)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<<TryGetSyntaxAndSemanticCompilerDiagnostics>b__17_3>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticCompilerDiagnostics>b__17_3(DiagnosticAnalyzerDriver _1, DiagnosticAnalyzer _2)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__22.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(StateSet stateSet, StateType stateType, Boolean supportsSemanticInSpan, Func`3 versionCheck, Func`3 getDiagnostics, DiagnosticAnalyzerDriver analyzerDriverOpt)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticCompilerDiagnostics>d__17.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics(StateSet stateSet, VersionStamp textVersion, VersionStamp syntaxVersion, VersionStamp semanticVersion)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticDiagnosticsAsync>d__16.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticDiagnosticsAsync(StateSet stateSet, VersionStamp textVersion, VersionStamp syntaxVersion, VersionStamp semanticVersion)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetAsync>d__15.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync()

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<TryAppendDiagnosticsForSpanAsync>d__60.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass16_0.<<TryAppendDiagnosticsForSpanAsync>b__0>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass16_0.<TryAppendDiagnosticsForSpanAsync>b__0()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by cston** [comment]
See #6262.

**Comment by cston** [comment]
See #6264.
