### ISSUE TITLE
Integration test failure: CSharpEncapsulateField

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#61128]
https://dev.azure.com/dnceng/public/_build/results?buildId=1750697&view=results

branch: release/dev17.3

```
System.OperationCanceledException: IDE version '17.2.32317.152' unexpectedly dismissed the light bulb.
   at Roslyn.VisualStudio.IntegrationTests.InProcess.LightBulbHelper.<TryWaitForItemsAsync>d__2.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.InProcess.LightBulbHelper.<WaitForItemsAsync>d__1.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.InProcess.LightBulbHelper.<WaitForLightBulbSessionAsync>d__0.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<ShowLightBulbAsync>d__34.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 616
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<InvokeCodeActionListWithoutWaitingAsync>d__36.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 641
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<InvokeCodeActionListAsync>d__35.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 623
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpEncapsulateField.<EncapsulateThroughLightbulbDefinitionsOnly>d__6.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpEncapsulateField.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpEncapsulateField.<EncapsulateThroughLightbulbDefinitionsOnly>d__6.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpEncapsulateField.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Xunit.Threading.InProcessIdeTestInvoker.<>c__DisplayClass6_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
```

**Comment by vatsalyaagrawal** [comment]
Fixed by #61151
