### ISSUE TITLE
Jenkins doesn't list test failures, even though there are some

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6113]
My job states:

![image](https://cloud.githubusercontent.com/assets/1103906/10560697/bf73ebd6-74c7-11e5-8470-b18be2491564.png)

However, this is the log (full log [here](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/203/console)):

In particular, this part of the log:
```
6:42:59   Running 37 test assemblies
16:43:00     6 running, 31 queued, 0 completed
16:43:05     6 running, 30 queued, 1 completed
16:43:07     6 running, 29 queued, 2 completed
16:43:09     6 running, 28 queued, 3 completed
16:43:14   xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
16:43:14     Discovering: Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
16:43:14     Discovered:  Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
16:43:14     Starting:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
16:43:14     Finished:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
16:43:14   System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
16:43:14      at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
16:43:14      at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
16:43:14      at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)  6 running, 27 queued, 4 completed
16:43:17     6 running, 26 queued, 5 completed
16:43:19     6 running, 25 queued, 6 completed
16:43:21     6 running, 24 queued, 7 completed
16:43:29     6 running, 23 queued, 8 completed
16:43:30     6 running, 22 queued, 9 completed
16:43:46     6 running, 21 queued, 10 completed
16:43:49     6 running, 20 queued, 11 completed
16:44:17     6 running, 19 queued, 12 completed
16:44:23     6 running, 18 queued, 13 completed
16:45:08     6 running, 17 queued, 14 completed
16:45:13     6 running, 16 queued, 15 completed
16:46:03     6 running, 15 queued, 16 completed
16:46:17     6 running, 14 queued, 17 completed
16:46:25     6 running, 13 queued, 18 completed
16:47:42     6 running, 12 queued, 19 completed
16:47:56     6 running, 11 queued, 20 completed
16:48:16     6 running, 10 queued, 21 completed
16:49:18     6 running, 9 queued, 22 completed
16:52:21     6 running, 8 queued, 23 completed
16:52:59     6 running, 7 queued, 24 completed
16:53:54     6 running, 6 queued, 25 completed
16:54:23     6 running, 5 queued, 26 completed
16:56:42     6 running, 4 queued, 27 completed
16:59:52     6 running, 3 queued, 28 completed
17:03:09     6 running, 2 queued, 29 completed
17:04:29     6 running, 1 queued, 30 completed
17:04:30     6 running, 0 queued, 31 completed
17:08:12     5 running, 0 queued, 32 completed
17:14:03     4 running, 0 queued, 33 completed
17:14:36     3 running, 0 queued, 34 completed
17:15:34     2 running, 0 queued, 35 completed
17:17:11     1 running, 0 queued, 36 completed
17:20:06     0 running, 0 queued, 37 completed
17:20:06   Errors Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll: 
17:20:06   Command: C:\Users\dotnet-bot\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.exe "Binaries\Debug\Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll" -xml "Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll.xml" -noshadow
17:20:06   xunit produced no error output but had exit code 1
17:20:06   
17:20:06   ================
17:20:06   Microsoft.CodeAnalysis.Scripting.VisualBasic.Desktop.UnitTests.dll          PASSED 00:00:05.3053683
17:20:06   Microsoft.Build.Tasks.CodeAnalysis.UnitTests.dll                            PASSED 00:00:07.5985347
17:20:06   Microsoft.CodeAnalysis.Scripting.UnitTests.dll                              PASSED 00:00:07.7855477
17:20:06   ConvertToAutoPropertyVB.UnitTests.dll                                       PASSED 00:00:09.5986761
17:20:06   Microsoft.DiaSymReader.PortablePdb.UnitTests.dll                            PASSED 00:00:10.9670537
17:20:06   Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests.dll                      FAILED 00:00:14.7540372
17:20:06   ImplementNotifyPropertyChangedVB.UnitTests.dll                              PASSED 00:00:16.3070173
17:20:06   ImplementNotifyPropertyChangedCS.UnitTests.dll                              PASSED 00:00:18.8273234
17:20:06   Microsoft.CodeAnalysis.Scripting.VisualBasic.UnitTests.dll                  PASSED 00:00:28.9793813
17:20:06   Roslyn.ExpressionEvaluator.VisualBasic.ResultProvider.UnitTests.dll         PASSED 00:00:34.1582555
17:20:06   Roslyn.Compilers.CSharp.WinRT.UnitTests.dll                                 PASSED 00:00:34.6541636
17:20:06   Roslyn.Services.VisualBasic.UnitTests.dll                                   PASSED 00:00:34.8429836
17:20:06   Microsoft.CodeAnalysis.Scripting.CSharp.Desktop.UnitTests.dll               PASSED 00:00:38.2345546
17:20:06   Roslyn.Services.CSharp.UnitTests.dll                                        PASSED 00:00:44.0231005
17:20:06   Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll              PASSED 00:00:56.1299448
17:20:06   Microsoft.CodeAnalysis.Scripting.CSharp.UnitTests.dll                       PASSED 00:00:59.5197641
17:20:06   Roslyn.Compilers.UnitTests.dll                                              PASSED 00:01:09.3463319
17:20:06   Roslyn.ExpressionEvaluator.CSharp.ExpressionCompiler.UnitTests.dll          PASSED 00:01:38.6151345
17:20:06   Roslyn.Compilers.CSharp.CommandLine.UnitTests.dll                           PASSED 00:02:34.3085090
17:20:06   Roslyn.ExpressionEvaluator.VisualBasic.ExpressionCompiler.UnitTests.dll     PASSED 00:02:43.5100555
17:20:06   Roslyn.VisualStudio.CSharp.UnitTests.dll                                    PASSED 00:02:55.7366308
17:20:06   Roslyn.Compilers.CSharp.Syntax.UnitTests.dll                                PASSED 00:04:42.9151432
17:20:06   Roslyn.Compilers.VisualBasic.Syntax.UnitTests.dll                           PASSED 00:05:04.1825566
17:20:06   Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll                      PASSED 00:05:32.8427398
17:20:06   Roslyn.Services.UnitTests.dll                                               PASSED 00:07:28.4393605
17:20:06   Roslyn.Compilers.CSharp.Semantic.UnitTests.dll                              PASSED 00:07:47.5985256
17:20:06   Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll                           PASSED 00:08:20.5679788
17:20:06   Roslyn.Compilers.CompilerServer.UnitTests.dll                               PASSED 00:08:59.9382018
17:20:06   Roslyn.Compilers.CSharp.Symbol.UnitTests.dll                                PASSED 00:10:09.4975148
17:20:06   Roslyn.Services.Editor.UnitTests.dll                                        PASSED 00:10:25.5770721
17:20:06   Roslyn.Compilers.CSharp.Emit.UnitTests.dll                                  PASSED 00:10:54.3517648
17:20:06   Roslyn.Compilers.VisualBasic.Semantic.UnitTests.dll                         PASSED 00:11:03.9948906
17:20:06   Roslyn.VisualStudio.Services.UnitTests.dll                                  PASSED 00:11:55.4263222
17:20:06   Roslyn.Services.Editor.UnitTests2.dll                                       PASSED 00:12:07.6148293
17:20:06   Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll                             PASSED 00:12:42.8144865
17:20:06   Roslyn.Services.Editor.VisualBasic.UnitTests.dll                            PASSED 00:20:42.2579910
17:20:06   Roslyn.Services.Editor.CSharp.UnitTests.dll                                 PASSED 00:25:43.5372168
17:20:06   ================
17:20:06   Test failures encountered: 00:37:06.7338518
```

Clearly test failures, however, from here I cannot see what actually failed.

**Comment by tannergooding** [comment]
@davkean, if there was a failure and it is not available in the Jenkins test results, then xunit probably failed to output a log altogether. If you will examine the rest of the log (specifically where it parses the xunit log files) you will notice that the failed test (Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests) did not have a log file for processing:

```
17:20:06 [xUnit] [INFO] - Starting to record.
17:20:06 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
17:20:07 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - 36 test report file(s) were found with the pattern '**/xUnitResults/*.xml' relative to 'd:\j\workspace\roslyn_prtest_win_dbg_unit64' for the testing framework 'xUnit.Net-v2 (default)'.
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\ConvertToAutoPropertyVB.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\ImplementNotifyPropertyChangedCS.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\ImplementNotifyPropertyChangedVB.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.Build.Tasks.CodeAnalysis.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.CSharp.Desktop.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.CSharp.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.VisualBasic.Desktop.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.CodeAnalysis.Scripting.VisualBasic.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Microsoft.DiaSymReader.PortablePdb.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.CommandLine.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.Emit.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.Semantic.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.Symbol.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.Syntax.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CSharp.WinRT.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.CompilerServer.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.VisualBasic.Semantic.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.VisualBasic.Symbol.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Compilers.VisualBasic.Syntax.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.ExpressionEvaluator.CSharp.ExpressionCompiler.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.ExpressionEvaluator.VisualBasic.ExpressionCompiler.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.ExpressionEvaluator.VisualBasic.ResultProvider.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.CSharp.UnitTests.dll.xml' .
17:20:07 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.Editor.CSharp.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.Editor.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.Editor.UnitTests2.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.Editor.VisualBasic.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.VisualBasic.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.VisualStudio.CSharp.UnitTests.dll.xml' .
17:20:08 [xUnit] [INFO] - Converting 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.VisualStudio.Services.UnitTests.dll.xml' .
17:20:14 [xUnit] [INFO] - Check 'Failed Tests' threshold.
17:20:14 [xUnit] [INFO] - Check 'Skipped Tests' threshold.
17:20:14 [xUnit] [INFO] - Setting the build status to FAILURE
17:20:14 [xUnit] [INFO] - Stopping recording.
```

**Comment by davkean** [comment]
Either way, Jenkins says there's no test failures, but clearly there is.

**Comment by jaredpar** [comment]
Looks like it is running into the following issue:

https://github.com/dotnet/corefx/issues/3793

**Comment by davkean** [comment]
Going to close and resolve this, I added a fault cause for this to catch it.
