### ISSUE TITLE
IndexOutOfRangeException from VisualBasic.Binder.ReportOverloadResolutionFailureForASingleCandidate

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#61193]
While working in Roslyn.sln. Not sure what caused this as I was not even in VB code file.

```
StreamJsonRpc.RemoteInvocationException: Index was outside the bounds of the array.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16`1.MoveNext()
RPC server exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
      at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportOverloadResolutionFailureForASingleCandidate(SyntaxNode node, Location diagnosticLocation, LookupResultKind lookupResult, CandidateAnalysisResult& candidateAnalysisResult, ImmutableArray`1 arguments, ImmutableArray`1 argumentNames, Boolean allowUnexpandedParamArrayForm, Boolean allowExpandedParamArrayForm, Boolean includeMethodNameInErrorMessages, Boolean reportNarrowingConversions, BindingDiagnosticBag diagnostics, Symbol delegateSymbol, Boolean queryMode, SyntaxNode callerInfoOpt, Symbol representCandidateInDiagnosticsOpt)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportOverloadResolutionFailureForASetOfCandidates(SyntaxNode node, Location diagnosticLocation, LookupResultKind lookupResult, ERRID errorNo, ArrayBuilder`1 candidates, ImmutableArray`1 arguments, ImmutableArray`1 argumentNames, BindingDiagnosticBag diagnostics, Symbol delegateSymbol, Boolean queryMode, SyntaxNode callerInfoOpt)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportOverloadResolutionFailureAndProduceBoundNode(SyntaxNode node, LookupResultKind lookupResult, ArrayBuilder`1 bestCandidates, ImmutableArray`1 bestSymbols, TypeSymbol commonReturnType, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, BindingDiagnosticBag diagnostics, SyntaxNode callerInfoOpt, BoundMethodOrPropertyGroup groupOpt, Symbol delegateSymbol, Boolean queryMode, BoundTypeExpression boundTypeExpression, Symbol representCandidateInDiagnosticsOpt, Location diagnosticLocationOpt)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportOverloadResolutionFailureAndProduceBoundNode(SyntaxNode node, LookupResultKind lookupResult, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, OverloadResolutionResult& results, BindingDiagnosticBag diagnostics, SyntaxNode callerInfoOpt, BoundMethodOrPropertyGroup groupOpt, TypeSymbol overrideCommonReturnType, Boolean queryMode, BoundTypeExpression boundTypeExpression, Symbol representCandidateInDiagnosticsOpt, Location diagnosticLocationOpt)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode target, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, BindingDiagnosticBag diagnostics, SyntaxNode callerInfoOpt, Boolean allowConstructorCall, Boolean suppressAbstractCallDiagnostics, Boolean isDefaultMemberAccess, Symbol representCandidateInDiagnosticsOpt, Boolean forceExpandedForm)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpressionPossiblyWithoutArguments(InvocationExpressionSyntax node, TypeCharacter typeChar, BoundMethodOrPropertyGroup group, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNames, ImmutableArray`1 argumentNamesLocations, Boolean allowBindingWithoutArguments, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindInvocationExpression(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindExpression(ExpressionSyntax node, Boolean isInvocationOrAddressOf, Boolean isOperandOfConditionalBranch, Boolean eventContext, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindReturn(ReturnStatementSyntax originalSyntax, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(SyntaxNode syntax, SyntaxList`1 stmtList, BindingDiagnosticBag diagnostics, Binder stmtListBinder)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindMethodBlock(MethodBlockBaseSyntax methodBlock, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.GetBoundMethodBody(TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Binder& methodBodyBinder)
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.BindAndAnalyzeMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Binder containingTypeBinder, MethodSymbol& referencedConstructor, Boolean& injectDefaultConstructorCall, Binder& methodBodyBinder)
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(MethodSymbol method, Int32 methodOrdinal, Int32& withEventPropertyIdDispenser, Int32& delegateRelaxationIdDispenser, Predicate`1 filter, TypeCompilationState compilationState, ProcessedFieldOrPropertyInitializers processedInitializers, Binder containingTypeBinder, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol& referencedConstructor)
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType, Predicate`1 filter)
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__33-0._Lambda$__0()
      at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
      at System.Threading.Tasks.Task.Execute()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.WaitForWorkers()
      at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.GetCompileDiagnostics(VisualBasicCompilation compilation, NamespaceSymbol root, SyntaxTree tree, Nullable`1 filterSpanWithinTree, Boolean hasDeclarationErrors, BindingDiagnosticBag diagnostics, Boolean doLoweringPhase, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnosticsForAllMethodBodies(Boolean hasDeclarationErrors, BindingDiagnosticBag diagnostics, Boolean doLowering, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsWithoutStateTrackingAsync>d__49.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultWithoutStateTrackingAsync>d__46.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultAsync>d__39.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<AnalyzeAsync>d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<GetDiagnosticsAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<CalculateDiagnosticsAsync>d__4.MoveNext()
```

**Comment by AlekseyTs** [comment]
This doesn't look actionable without more details, or dump, or repro.
