### ISSUE TITLE
VB compiler crashes with `NullReferenceException` in decoding well-known attributes

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#61492]
```vb
Imports System.Security.Permissions

<A>'BIND:"A"
Class A
    Inherits CodeAccessSecurityAttribute
    Public Sub New(Optional x As SecurityAction = 0)
    End Sub
End Class
```

StackTrace

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.VisualBasicAttributeData.ValidateSecurityAction(TypedConstant typedValue, Symbol targetSymbol, AttributeSyntax nodeOpt, BindingDiagnosticBag diagnostics, Boolean& hasErrors) in /_/src/Compilers/VisualBasic/Portable/Symbols/Attributes/AttributeData.vb:line 305
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.VisualBasicAttributeData.DecodeSecurityAttributeAction(Symbol targetSymbol, VisualBasicCompilation compilation, AttributeSyntax nodeOpt, Boolean& hasErrors, BindingDiagnosticBag diagnostics) in /_/src/Compilers/VisualBasic/Portable/Symbols/Attributes/AttributeData.vb:line 240
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.VisualBasicAttributeData.DecodeSecurityAttribute[T](Symbol targetSymbol, VisualBasicCompilation compilation, DecodeWellKnownAttributeArguments`3& arguments) in /_/src/Compilers/VisualBasic/Portable/Symbols/Attributes/AttributeData.vb:line 193
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.DecodeWellKnownAttribute(DecodeWellKnownAttributeArguments`3& arguments) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 2282
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ValidateAttributeUsageAndDecodeWellKnownAttributes(ImmutableArray`1 binders, ImmutableArray`1 attributeSyntaxList, ImmutableArray`1 boundAttributes, BindingDiagnosticBag diagnostics, AttributeLocation symbolPart) in /_/src/Compilers/VisualBasic/Portable/Symbols/Symbol_Attributes.vb:line 472
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.LoadAndValidateAttributes(OneOrMany`1 attributeBlockSyntaxList, CustomAttributesBag`1& lazyCustomAttributesBag, AttributeLocation symbolPart) in /_/src/Compilers/VisualBasic/Portable/Symbols/Symbol_Attributes.vb:line 277
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetAttributesBag() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 1845
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetAttributes() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 1857
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb:line 321
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 111
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb:line 288
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__78-1._Lambda$__1(NamespaceOrTypeSymbol typeOrNamespace) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb:line 679
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__80-1._Lambda$__0() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb:line 728
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /_/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 141
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetAllDeclarationErrors(BindingDiagnosticBag diagnostics, CancellationToken cancellationToken, Boolean& hasExtensionMethods) in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceModuleSymbol.vb:line 688
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb:line 2175
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb:line 2119
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb:line 2108
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CancellationToken cancellationToken) in /_/src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb:line 2065
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAllDiagnosticsWithoutStateTrackingAsync(ImmutableArray`1 analyzers, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 478
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAllDiagnosticsAsync(CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 326
   at MirrorSharp.Internal.Roslyn.RoslynSession.GetDiagnosticsAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 102
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 39
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

This bug produces in SharpLab main branch (commit e6b5dd8)

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/commit/6fae25d645a52df895bf9fa2d731a7a17439d573 is a partial fix. There are other two `diagnostics.Add(...)` that should be revised and tested.
