### ISSUE TITLE
NRE in `VisualBasicAddExplicitCastCodeFixProvider`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#61538]
[SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRII5wJZICaoC2EhwECyANADYgBuwAPgJKEAOA9gjMgAQDKAT2QwSAOgBKcAHYxsxMc1nkObfuTrYAxigCwAKANH9AHgDC1KMmRLRCMFB0AKAIwBKAHwGACnGDVtXgsrPiU6KAC8YOsDAFFpPCDLayA==)

Code:

```vb
Imports System.Runtime.InteropServices



<ClassInterface(1)>
Public Class InvalidClass
End Class
```

StackTrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddExplicitCast.VisualBasicAddExplicitCastCodeFixProvider.GetPotentialConversionTypesWithInvocationNode(SemanticModel semanticModel, SyntaxNode root, SyntaxNode invocationNode, CancellationToken cancellationToken) in /_/src/Analyzers/VisualBasic/CodeFixes/AddExplicitCast/VisualBasicAddExplicitCastCodeFixProvider.vb:line 157
   at Microsoft.CodeAnalysis.VisualBasic.CodeFixes.AddExplicitCast.VisualBasicAddExplicitCastCodeFixProvider.TryGetTargetTypeInfo(Document document, SemanticModel semanticModel, SyntaxNode root, String diagnosticId, ExpressionSyntax spanNode, CancellationToken cancellationToken, ImmutableArray`1& potentialConversionTypes) in /_/src/Analyzers/VisualBasic/CodeFixes/AddExplicitCast/VisualBasicAddExplicitCastCodeFixProvider.vb:line 81
   at Microsoft.CodeAnalysis.CodeFixes.AddExplicitCast.AbstractAddExplicitCastCodeFixProvider`1.RegisterCodeFixesAsync(CodeFixContext context) in /_/src/Analyzers/Core/CodeFixes/AddExplicitCast/AbstractAddExplicitCastCodeFixProvider.cs:line 74
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.GetCodeActionsAsync(Diagnostic diagnostic, WorkSession session, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-required-members\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 114
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.SendSlowUpdateAsync(IReadOnlyList`1 diagnostics, WorkSession session, Object extensionResult, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-required-members\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 60
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-required-members\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 39
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-required-members\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-required-members\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

![image](https://user-images.githubusercontent.com/31348972/170552203-c9481e85-098c-47f6-99a3-d0dedcda028e.png)

**Comment by Youssef1313** [comment]
Likely duplicate of https://github.com/dotnet/roslyn/issues/52838, but this one has a repro :)

**Comment by kfechter** [comment]
Right now, it doesn't generate any fixes to apply, I temporarily added a null check around the failing code so I could debug and step around it. 

I'm currently trying to figure out why the call to GetAncestors is returning an empty IEnumerable. I believe it's due to the tNode at line 45 of SyntaxNodeExtensions.cs being null so the yield return is never called. 

for the call to GetAncestors when the example class is used, tNode in the following snippet is null on every iteration, and yield return is never called.

`if (current is TNode tNode)
 {
     yield return tNode;
 }`

**Comment by kfechter** [comment]
I don't want to keep spamming anyone listening to this issue, so this will be the last reply for the night. I got it working the way I think it should work based on the original post. Instead of throwing a null reference when error BC30519 occurs in an Attribute, it will now suggest code fixes, and applying them generates the code that the fix suggests. 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/4164101/174946199-1d877327-585a-46c8-a283-e07493c3557a.png">

**Comment by Youssef1313** [comment]
@kfechter I think you can open a PR, and reviewers will help suggesting cleaning up the code if needed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/62075
