### ISSUE TITLE
[Flaky Test] Roslyn.InteractiveWindow.UnitTests failing with race in Stabilization

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6178]
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_win_dbg_unit32/33/

```
23:21:27   xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
23:21:27     Discovering: Roslyn.InteractiveWindow.UnitTests
23:21:27     Discovered:  Roslyn.InteractiveWindow.UnitTests
23:21:27     Starting:    Roslyn.InteractiveWindow.UnitTests
23:21:27     Finished:    Roslyn.InteractiveWindow.UnitTests
23:21:27   System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
23:21:27      at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
23:21:27      at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
23:21:27      at System.Collections.Generic.List`1.Enumerator.MoveNext()
```

**Comment by amcasey** [comment]
FYI @dotnet/interactive

**Comment by davkean** [comment]
This is caused by https://github.com/dotnet/corefx/issues/3793 (I added a cause for it last week and its listed on the front page). Given we're hitting this a lot and we're not going to see a fix from .NET for a while, we should probably consider submitting a PR to xunit to make them avoid this path.

**Comment by jaredpar** [comment]
Dupe of #6358
