### ISSUE TITLE
CSharpRemoveUnreachableCodeCodeFixProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by JeroenOortwijn-Romias** [dotnet/roslyn#61810]
**Version Used**: The one with Visual Studio v17.2.3?

**Steps to Reproduce**:

1. Create a console app project with the following code in Program.cs:
``` C#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

do
{

} while (true);

Console.WriteLine("Hello, World!");
```
2. Press <kbd>Alt</kbd>-<kbd>Enter</kbd> on the second `Console.WriteLine("Hello, World!");` line.

**Expected Behavior**: No crash. 😄

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/97881867/173093169-7b651ca4-b31b-4c9f-851c-d6516d8286dc.png)

**Stack trace**:
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.GlobalStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax'.
   at Microsoft.CodeAnalysis.CSharp.RemoveUnreachableCode.CSharpRemoveUnreachableCodeCodeFixProvider.FixAllAsync(Document document,ImmutableArray`1 diagnostics,SyntaxEditor editor,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<>c__DisplayClass4_0.<FixAllAsync>b__0(SyntaxEditor editor)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/ceadf946cd2a7f54eae6e8d8599bc56d4475d25c/src/Analyzers/CSharp/CodeFixes/RemoveUnreachableCode/CSharpRemoveUnreachableCodeCodeFixProvider.cs#L68

Probably passing `getInnermostNodeForTie: true` will fix the problem.
