### ISSUE TITLE
It seems like a syntax parser bug when combined `switch` statement and a wrong open square bracket `[` token

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#62126]
**Version Used**: 

VS17.3p2

**Steps to Reproduce**:

Type code like below (I use tabs to trigger the bug, but using spaces may also trigger):

```csharp
using System;

switch (getVirtualKey())
{
	case VirtualKey.Up or VirtualKey.Down or VirtualKey.Left or VirtualKey.Right:
	{

	}
}

// A local function to simulate get operation.
static VirtualKey getVirtualKey() => VirtualKey.Up;


enum VirtualKey
{
	Up,
	Down,
	Left,
	Right
}
```

![image](https://user-images.githubusercontent.com/23616315/175546583-a928fa20-e8c1-40bf-8605-eaba5d748414.png)

Then I input a open square bracket `[` after the colon token `:` case label, the highlight will be messed up:

```csharp
using System;

switch (getVirtualKey())
{
//                                                                             Insert '[' here
//                                                                                    ↓
	case VirtualKey.Up or VirtualKey.Down or VirtualKey.Left or VirtualKey.Right: [
	{

	}
}

// A local function to simulate get operation.
static VirtualKey getVirtualKey() => VirtualKey.Up;


enum VirtualKey
{
	Up,
	Down,
	Left,
	Right
}
```

![image](https://user-images.githubusercontent.com/23616315/175546702-34f7b002-0ae2-4dbe-b70b-0d32c83e3f43.png)

It seems that the syntax highlight has been messed up.

See [sharplab](https://sharplab.io/#v2:D4AQTAjAsAULDOB3AlgFwMYAsAEAKA5gKaoBqyATqgK4CGANgNKECeuAlG7AN6wCQ6NeIWxlKtRiwB0AVQAO2APbkRFavSbNJAEQWIAdouWi1EzQBlCAM1SGVY9VIBKyfJlQAuPjzgxeAX1gAnwB6YOwAQWw6BQE6bEsqPXRUZAUDVAVseGQAWyo6GlRhIhsFWUJyQtS9SVgQCAA2OxMNbBLjcQ12bABeAD5mzqk5AG5YcZhCPSocwYdmbj45ABo+HX1V3wtrTd5nV1RAoA=)

If the same operation is applied to the sharplab, the information will be incorrect:

Step 1:

![image](https://user-images.githubusercontent.com/23616315/175547808-b33a056f-edca-4440-877b-419b57788a0a.png)

Step 2 (Add '[' token):

![image](https://user-images.githubusercontent.com/23616315/175547892-ab954754-72f4-441b-82e8-4f86cc37b1ab.png)

Step 3 (Press <kbd>Ctrl + Z</kbd> to undo):

![image](https://user-images.githubusercontent.com/23616315/175548031-f04fd0c5-d443-4a02-a8d4-85af924bec4d.png)

The error info is different with the original case.

**Expected Behavior**:

The syntax is wrong but the info and syntax highlighter behave as normal.

**Actual Behavior**:

The syntax is wrong, but it seems that the syntax highlighter is broken.

---

Stacktrace:

```
StreamJsonRpc.RemoteInvocationException: 指定的参数已超出有效值的范围。
参数名: span
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: span
      在 Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
      在 Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<GetLocationsAsync>d__5.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddClassificationsInCurrentProcessAsync>d__7.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 System.Threading.Tasks.ValueTask`1.get_Result()
      在 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 System.Threading.Tasks.ValueTask`1.get_Result()
      在 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 System.Threading.Tasks.ValueTask`1.get_Result()
      在 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 System.Threading.Tasks.ValueTask`1.get_Result()
      在 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
definitely an issue with incremental parsing.  Doing this with a debug build results in:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected difference at offset 250: Line 12, Column 51 "static VirtualKey getVirtualKey() => VirtualKey.Up;"  (Found: [
] Expected: [;])



   at Microsoft.CodeAnalysis.SyntaxTreeExtensions.VerifySource(SyntaxTree tree, IEnumerable`1 changes) in C:\github\roslyn\src\Compilers\Core\Portable\Syntax\SyntaxTreeExtensions.cs:line 80

   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes) in C:\github\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxTree.cs:line 572

   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText) in C:\github\roslyn\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxTree.cs:line 531

   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\Core\Portable\Workspace\Solution\DocumentState.cs:line 269

   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__23.MoveNext() in C:\github\roslyn\src\Workspaces\Core\Portable\Workspace\Solution\DocumentState.cs:line 230

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(ValueSource`1 oldTreeSource, ValueSource`1 newTextSource, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.DocumentState.<>c__DisplayClass22_0.<CreateLazyIncrementallyParsedTree>b__0(CancellationToken c) in C:\github\roslyn\src\Workspaces\Core\Portable\Workspace\Solution\DocumentState.cs:line 213

   at Roslyn.Utilities.AsyncLazy`1.StartAsynchronousComputation(AsynchronousComputationToStart computationToStart, Request requestToCompleteSynchronously, CancellationToken callerCancellationToken) in C:\github\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Utilities\AsyncLazy`1.cs:line 398

   at Roslyn.Utilities.AsyncLazy`1.GetValueAsync(CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Utilities\AsyncLazy`1.cs:line 355

   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__48.MoveNext() in C:\github\roslyn\src\Workspaces\Core\Portable\Workspace\Solution\DocumentState.cs:line 685

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Document.GetSyntaxTreeAsync(CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\Core\Portable\Workspace\Solution\Document.cs:line 195

   at Microsoft.CodeAnalysis.Host.BackgroundParser.<>c__DisplayClass22_0.<<ParseDocumentAsync>b__0>d.MoveNext() in C:\github\roslyn\src\Features\Core\Portable\Workspace\BackgroundParser.cs:line 211

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Host.BackgroundParser.<>c__DisplayClass22_0.<ParseDocumentAsync>b__0()

   at Roslyn.Utilities.TaskQueue.<>c__DisplayClass19_0.<ScheduleTaskInProgress>b__0(Task _) in C:\github\roslyn\src\Workspaces\Core\Portable\Utilities\TaskQueue.cs:line 101

   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

@jcouv @jaredpar  can you assign/prioritize (note: incremental parsing bugs are very bad.  teh tree is effectively bogus and higher layers are sure to crash soon after).
