### ISSUE TITLE
`VisualBasicSyntaxFacts.IsEqualsValueOfPropertyDeclaration` throws NRE

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62146]
Seeing on 17.3 Preview 2

```
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.CodeAnalysis.VisualBasic.LanguageServices.VisualBasicSyntaxFacts.IsEqualsValueOfPropertyDeclaration(SyntaxNode node)
      at Microsoft.CodeAnalysis.EmbeddedLanguages.EmbeddedLanguageDetector.IsEmbeddedLanguageStringLiteralToken(SyntaxToken token, SemanticModel semanticModel, CancellationToken cancellationToken, String& identifier, IEnumerable`1& options)
      at Microsoft.CodeAnalysis.EmbeddedLanguages.EmbeddedLanguageDetector.IsEmbeddedLanguageTokenWorker(SyntaxToken token, SemanticModel semanticModel, CancellationToken cancellationToken, String& identifier, IEnumerable`1& options)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.ClassifyToken(SyntaxToken token)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.ProcessToken(SyntaxToken token)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.Worker.Recurse(SyntaxNode node)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.AddEmbeddedLanguageClassifications(Project project, SemanticModel semanticModel, TextSpan textSpan, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractEmbeddedLanguageClassificationService.<AddEmbeddedLanguageClassificationsAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddClassificationsInCurrentProcessAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<SlowGetSolutionAndRunAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<SlowGetSolutionAndRunAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

It happened when I opened `NamingStyleTests.vb`, but I'm not sure if the repro is consistent.

The stacktrace might help though.

**Comment by Youssef1313** [comment]
Looks like @CyrusNajmabadi has already fixed it in https://github.com/dotnet/roslyn/pull/61725 :)
Closing
