### ISSUE TITLE
Compiler asserting in CSharpSemanticModel.GetImportScopesCore

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#62227]
Running d1077466a0ab3d3ec4a194f464e0608b3dd58e2d, I hit this assert if I try to use the C# interactive window.

```

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetImportScopesCore(Int32 position, CancellationToken cancellationToken) in F:\Projects\Roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 5304
   at Microsoft.CodeAnalysis.SemanticModel.GetImportScopes(Int32 position, CancellationToken cancellationToken) in F:\Projects\Roslyn\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 782
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.TypeSyntaxSimplifierWalker.AddAliasedNames(CompilationUnitSyntax compilationUnit) in F:\Projects\Roslyn\src\Features\CSharp\Portable\Diagnostics\Analyzers\TypeSyntaxSimplifierWalker.cs:line 97
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.TypeSyntaxSimplifierWalker..ctor(CSharpSimplifyTypeNamesDiagnosticAnalyzer analyzer, SemanticModel semanticModel, CSharpSimplifierOptions options, SimpleIntervalTree`2 ignoredSpans, CancellationToken cancellationToken) in F:\Projects\Roslyn\src\Features\CSharp\Po......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by jasonmalinowski** [comment]
FYI to @CyrusNajmabadi.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63146
