### ISSUE TITLE
EnC crash

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#62478]
**Version Used**:
VS 27.3 Preview 2

**Stack trace:**
```
StreamJsonRpc.RemoteInvocationException: The specified document does not exist in the solution.
in StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.InvalidOperationException: The specified document does not exist in the solution.
at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.<GetRequiredDocumentAsync>d__9.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.CodeAnalysis.EditAndContinue.RemoteEditAndContinueService.<>c__DisplayClass9_0.<<GetDocumentDiagnosticsAsync>b__0>d.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
--- End stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()

```

**Context:**
I was editing a ```.razor``` file, nothing special. Tried to add a `style` attribute to a `div` (crashed when editing the value of the attribute). No idea why this happened, can't remember anything like this before

**Comment by Youssef1313** [comment]
I'm hitting a similar crash but for inheritance margin.

```
StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocumentAsync(Solution solution, DocumentId documentId, Boolean includeSourceGenerated, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<>c__DisplayClass6_1.<<DescendInheritanceTreeAsync>g__GetRequiredSemanticModelAsync|4>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<>c__DisplayClass6_1.<<DescendInheritanceTreeAsync>g__AddSourceTypesThatDeriveFromNameAsync|6>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<>c__DisplayClass6_0.<<DescendInheritanceTreeAsync>g__AddDescendantSourceTypesInProjectAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.<>c__DisplayClass6_0.<<DescendInheritanceTreeAsync>g__DescendInheritanceTreeInProjectAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.DescendInheritanceTreeAsync(INamedTypeSymbol type, Solution solution, IImmutableSet`1 projects, Func`3 typeMatches, Func`2 shouldContinueSearching, Boolean transitive, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.FindTypesInCurrentProcessAsync(INamedTypeSymbol type, Solution solution, IImmutableSet`1 projects, Boolean transitive, DependentTypesKind kind, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.DependentTypeFinder.FindTypesAsync(INamedTypeSymbol type, Solution solution, IImmutableSet`1 projects, Boolean transitive, DependentTypesKind kind, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindDerivedClassesArrayAsync(INamedTypeSymbol type, Solution solution, Boolean transitive, IImmutableSet`1 projects, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetDerivedTypesAndImplementationsAsync(Solution solution, INamedTypeSymbol typeSymbol, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.AddInheritanceMemberItemsForNamedTypeAsync(Solution solution, INamedTypeSymbol memberSymbol, Int32 lineNumber, ArrayBuilder`1 builder, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetSymbolInheritanceChainItemsAsync(Project project, Document document, ImmutableArray`1 symbolAndLineNumbers, Boolean frozenPartialSemantics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetInheritanceMarginItemsInProcessAsync(Document document, TextSpan spanToSearch, Boolean includeGlobalImports, Boolean frozenPartialSemantics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetInheritanceMemberItemsAsync(Document document, TextSpan spanToSearch, Boolean includeGlobalImports, Boolean frozenPartialSemantics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteInheritanceMarginService.<>c__DisplayClass2_0.<<GetInheritanceMarginItemsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)

```
