### ISSUE TITLE
Multiple CodeRefactoringProvider failed with InvalidOperationException 

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#62561]
Visual Studio Version 17.4.0 Preview 1.0 [32708.385.main]

`'CSharpPullMemberUpCodeRefactoringProvider' encountered an error and has been disabled.`

Stack trace:

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeRefactorings.PullMemberUp.AbstractPullMemberUpRefactoringProvider.<>c__DisplayClass3_0.<ComputeRefactoringsAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.CodeRefactorings.PullMemberUp.AbstractPullMemberUpRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

`'CSharpMoveStaticMembersRefactoringProvider' encountered an error and has been disabled.`

Stack trace:

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.<>c__DisplayClass1_0.<ComputeRefactoringsAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

`'CSharpExtractClassCodeRefactoringProvider' encountered an error and has been disabled.`

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractClass.AbstractExtractClassRefactoringProvider.<>c__DisplayClass5_0.<TryGetMemberActionAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.ExtractClass.AbstractExtractClassRefactoringProvider.TryGetMemberActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractClass.AbstractExtractClassRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by Youssef1313** [comment]
Being fixed in https://github.com/dotnet/roslyn/pull/62509 :)
