### ISSUE TITLE
Feature 'Missing import discovery' is currently unavailable due to an internal error.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62737]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Missing-import-discovery-is-cu/10096436)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.2]
While building my project, I opened a file that was created via the new "source generators" feature and encountered a gold bar with this error: `Feature 'Missing import discovery' is currently unavailable due to an internal error.`

Please see attached trace files and screenshot.

Stack trace:
```
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   at StreamJsonRpc.JsonRpc.d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.d__20`1.MoveNext()
RPC server exception:
System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.CodeAnalysis.Remote.RemoteMissingImportDiscoveryService.<>c__DisplayClass3_0.<b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__14`1.MoveNext()

```

---
#### Feedback Bot on 7/15/2022, 03:12 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This feature assumes the document is not a source generated document:

https://github.com/dotnet/roslyn/blob/027ff7b510ed0d5a5616e093eb572117826cf8dc/src/Workspaces/Remote/ServiceHub/Services/MissingImportDiscovery/RemoteMissingImportDiscoveryService.cs#L47

**Comment by Bosch-Eli-Black** [comment]
Thanks for taking a look at this, @sharwell 🙂  BTW, were the traces from VS helpful in this case?

**Comment by kbarrows-work** [comment]
![VS Load Errors](https://github.com/dotnet/roslyn/assets/163931014/ee828470-0f5e-4dee-bb4b-88cdc48cfee9)

After the last VS upgrade I am constantly getting these errors.  (See image)

> Microsoft Visual Studio Professional 2022
Version 17.9.2
VisualStudio.17.Release/17.9.2+34622.214
Microsoft .NET Framework
Version 4.8.09037

> Installed Version: Professional

> Visual C++ 2022   00476-80000-00000-AA881
Microsoft Visual C++ 2022

> ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

> ASA Service Provider   1.0

> ASP.NET and Web Tools   17.9.197.37128
ASP.NET and Web Tools

> C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Comment by sharwell** [comment]
@kbarrows-work Your issue does not appear to be related to this issue. Can you file a new feedback using the [Report a Problem](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) tool in Visual Studio?
