### ISSUE TITLE
'CSharpMoveStaticMembersRefactoringProvider' encountered an error and has been disabled

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62823]
When I try to move static members into helpers in https://github.com/dotnet/roslyn/blob/8f9d451782344a3a5641e5c3aad63f5032cd6f14/src/Analyzers/CSharp/Analyzers/UseExpressionBodyForLambda/UseExpressionBodyForLambdaDiagnosticAnalyzer.cs, I get:

```
Microsoft.Assumes+InternalErrorException : Did not find new element in the hierarchy for item "C:\Users\PC\Desktop\Roslyn\src\Analyzers\CSharp\Analyzers\UseExpressionBodyForLambda\UseExpressionBodyForLambdaDiagnosticAnalyzerHelpers.cs". The item would have been added with type "Compile". The project item schema service knows about this item type. The item does not exist in the project file.
   at Microsoft.Assumes.Fail(String message)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.EvaluateAddResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddItemAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass4_0.<AddFromFile>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToProjectItems(ProjectItems projectItems,DocumentId documentId,String folderPath,String documentName,SourceText initialText,String filePath,TextDocumentKind documentKind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToProject(Project project,DocumentId documentId,String documentName,TextDocumentKind documentKind,SourceText initialText,String filePath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,TextDocumentKind documentKind)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApplyAsync(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionEditHandlerService.ProcessOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

FYI @Soreloser2

**Comment by Youssef1313** [comment]
Note that the file with the selected methods was created. But it wasn't added to projitems. Also the original methods were not really moved, they were "copied" (ie, they exist in the original location and the new static class). Method callers were not updated also.

**Comment by Youssef1313** [comment]
Also a bad change has happened, a `<Compile Include="..."/>` was added in `Microsoft.CodeAnalysis.CSharp.Features.csproj`. I assume that shared projects somehow confuses the refactoring or whatever API used to add a new file.

**Comment by Soreloser2** [comment]
Trying to repro this (select all in dialog, otherwise defaults), I get a different error:
```
System.ArgumentException : Node to track is not a descendant of the root.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root,IEnumerable`1 nodes)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.MoveStaticMembersWithDialogCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```
There are no changes made (no new file, static members still in old file)

**Comment by Youssef1313** [comment]
@Soreloser2 I'm on 17.3 Preview 2. It's not the latest preview so probably something has changed.

**Comment by Youssef1313** [comment]
I also didn't select all, here are things I selected:

- UseExpressionBodyTitle
- UseBlockBodyTitle
- CanOfferUseBlockBody
- CanOfferUseExpressionBody
- GetBodyAsExpression
- GetCodeStyleOption
- GetOptionSeverity
- TryConvertToExpressionBody

**Comment by Soreloser2** [comment]
The error I had encountered is probably a separate issue having to do with members defined across multiple documents for a single partial class. Trying again on the main from the commit branch, I don't get an exception but I do get all the things you described, (added to `.csproj` and not projitems, members in new file but not old one). In the debugger it seems like we're running through code to delete the members, but something goes wrong after we return from [`MoveStaticMembersCodeAction.ComputeOperationsAsync`](https://github.com/dotnet/roslyn/blob/0f4e90ab1e9367a3914c348b2d0b2c6f58228c29/src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs#L54)

**Comment by ryzngard** [comment]
Looks specific to shared projects, multiple of our refactorings have this problem with shared projects (extract type, rename file, etc)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback and division not investing in shared projects.
