### ISSUE TITLE
Move Static Members refactoring with dialog fails when selecting members from partial class

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#62846]
**Version Used**: 17.4.0 Preview 1 (internal preview 32720.392.main)

**Steps to Reproduce**:

1. Create a partial class across 2 documents, where both declare/implement static members
2. Activate the Move Static Members refactoring on one of the documents, and select members from the other document
3. Move the members to a new class

**Expected Behavior**:
We should move/remove selected members from all class declarations of the partial class

**Actual Behavior**:
Refactoring fails with:
```
System.ArgumentException : Node to track is not a descendant of the root.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root,IEnumerable`1 nodes)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.MoveStaticMembersWithDialogCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```
This is likely because we are tracking the definition of members so we can still find them after changes, but we expect all those members to be declared in the same syntax tree/document. When they aren't, we get the error [here](https://github.com/dotnet/roslyn/blob/0f4e90ab1e9367a3914c348b2d0b2c6f58228c29/src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs#L72).

This may also apply to members moved via Extract Base Class and Pull Members Up, but they each use slightly different logic so it's possible that this is not an issue.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feeddback.
