### ISSUE TITLE
Assertion in CSharpSemanticModel.GetImportScopesCore fails in Interactive Window

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63144]
![image](https://user-images.githubusercontent.com/41759/182473731-bc54f2e6-8277-4980-9f94-3945ee70f34d.png)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetImportScopesCore(Int32 position, CancellationToken cancellationToken) in D:\R3\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 5304

   at Microsoft.CodeAnalysis.SemanticModel.GetImportScopes(Int32 position, CancellationToken cancellationToken) in D:\R3\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 782

   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.TypeSyntaxSimplifierWalker.AddAliasedNames(CompilationUnitSyntax compilationUnit) in D:\R3\src\Features\CSharp\Portable\Diagnostics\Analyzers\TypeSyntaxSimplifierWalker.cs:line 97

   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.TypeSyntaxSimplifierWalker..ctor(CSharpSimplifyTypeNamesDiagnosticAnalyzer analyzer, SemanticModel semanticModel, CSharpSimplifierOptions options, SimpleIntervalTree`2 ignoredSpans, CancellationToken cancellationToken) in D:\R3\src\Features\CSharp\Portable\Diagnostics\Analyzers\TypeSyntaxSimplifierWal......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by tmat** [comment]
Caused by #59533
