### ISSUE TITLE
NumericIntPtr tests fail in certain partitioning schemes

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#63152]
Found in https://github.com/dotnet/roslyn/pull/62138
Tests will be temporarily disabled

Depending on how the partition occurs, these tests will sometimes fail

```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.BuiltInConversions_NativeIntegers
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.BuiltInOperators_NativeIntegers
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.ParameterDefaultValue_02
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.Constraints_01
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.Overloads_01
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.Overrides_01
```

with a stack trace similar to
```
Error Message:
   System.InvalidOperationException : Assertion failed
  Stack Trace:
     at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Compilers/Test/Core/ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MetadataOrSourceAssemblySymbol.set_RuntimeSupportsNumericIntPtr(Boolean value) in /_/src/Compilers/CSharp/Portable/Symbols/MetadataOrSourceAssemblySymbol.cs:line 59
   at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.set_RuntimeSupportsNumericIntPtr(Boolean value) in /_/src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs:line 457
   at Microsoft.CodeAnalysis.CSharp.Symbols.MetadataOrSourceAssemblySymbol.set_RuntimeSupportsNumericIntPtr(Boolean value) in /_/src/Compilers/CSharp/Portable/Symbols/MetadataOrSourceAssemblySymbol.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateNumericIntPtrCompilation(CSharpTestSource source, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName, String sourceFileName) in /_/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs:line 1106
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NumericIntPtrTests.BuiltInConversions_NativeIntegers(Boolean useCompilationReference, Boolean useLatest, Boolean useSystemTypes) in /_/src/Compilers/CSharp/Test/Emit2/Emit/NumericIntPtrTests.cs:line 1423
   at InvokeStub_NumericIntPtrTests.BuiltInConversions_NativeIntegers(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

See https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-roslyn-refs-pull-62138-merge-5bb111d9f8b745e68b/Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests_7/1/console.a2937105.log?helixlogtype=result

From run https://dev.azure.com/dnceng/public/_build/results?buildId=1912816&view=ms.vss-test-web.build-test-results-tab&runId=49621468&resultId=160668&paneView=debug

The failure is not consistent - sometimes the tests will pass.  I have reproduced this locally as well, by first 
1.  Restore and Build roslyn.sln
2.  run eng/prepare-tests.ps1
3.  run rehydrate.cmd in the `artifacts/testPayload/artifacts/bin` output folder for `Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests\Debug\net6.0\Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests.dll`
4.  put the attached vstest_7.rsp file in `artifacts/testPayload/artifacts/bin` (rename from .txt to .rsp, github won't let me upload the attachment as .rsp) - [vstest_7.txt](https://github.com/dotnet/roslyn/files/9246125/vstest_7.txt)
5.  run ``dotnet exec "C:\Users\dabarbet\source\repos\roslyn\.dotnet\sdk\7.0.100-preview.5.22307.18\vstest.console.dll" `@vstest_7.rsp`` from `artifacts/testPayload/artifacts/bin` but replace the path to the vstest.console.dll to your appropriate folder.

**Comment by dibarbet** [comment]
cc @jcouv could this potentially be fixed by addressing https://github.com/dotnet/roslyn/issues/61235 ?

**Comment by jcouv** [comment]
@dibarbet Yes, adding and moving to `TargetFramework.Net70` should solve this. However, those tests use a special test hook in order to avoid such test ordering/interference problems. I'll still want to figure out why that didn't work.

**Comment by jaredpar** [comment]
@jcouv which test hook are we using in this test?

**Comment by jcouv** [comment]
@jaredpar The test hook to fake the presence of runtime feature flag (`RuntimeSupportsNumericIntPtr`).
