### ISSUE TITLE
StreamJsonRpc.RemoteInvocationException in VS 17.4 preview 2 when editing C#

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/roslyn#63235]
VS build: 17.4.0 Preview 2.0 [32803.494.main]

When typing in C# files a series of exceptions in various components is reported via the error info bars. Stack traces look like this:

```
StreamJsonRpc.RemoteInvocationException: Request for solution-checksum 'xMUm8WPCz38JmFqTcMb50pkiwOk=' that was not pinned on the host side.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17.MoveNext()
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Request for solution-checksum 'xMUm8WPCz38JmFqTcMb50pkiwOk=' that was not pinned on the host side.
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass23_0`1.<<InvokeStreamingServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<>c__DisplayClass23_0`1.<<InvokeStreamingServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.InvokeStreamingServiceAsync[TResult](TService service, Func`4 invocation, Func`3 reader, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.InvokeAsync[TResult](Func`4 invocation, Func`3 reader, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.InvokeServiceAsync[TResult](ServiceBrokerClient client, ServiceRpcDescriptor serviceDescriptor, Func`3 invocation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.SolutionAssetSource.GetAssetsAsync(Checksum solutionChecksum, ISet`1 checksums, ISerializerService serializerService, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.RequestAssetsAsync(ISet`1 checksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.SynchronizeAssetsAsync(ISet`1 checksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.SynchronizeAssets_NoLockAsync(IReadOnlyCollection`1 checksumOrCollections, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.SynchronizeAssetsAsync(HashSet`1 checksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.AssetProvider.GetAssetsAsync[T](HashSet`1 checksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.GetDocumentMapAsync(AssetProvider assetProvider, HashSet`1 documents, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentsAsync(Project project, ProjectStateChecksums projectChecksums, IEnumerable`1 existingTextDocumentStates, ChecksumCollection oldChecksums, ChecksumCollection newChecksums, Func`3 addDocuments, Func`3 removeDocuments, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectAsync(Project project, ProjectStateChecksums oldProjectChecksums, ProjectStateChecksums newProjectChecksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, HashSet`1 oldChecksums, HashSet`1 newChecksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Solution solution, ChecksumCollection oldChecksums, ChecksumCollection newChecksums, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.CreateSolutionAsync(Checksum newSolutionChecksum, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.ComputeDisconnectedSolutionAsync(AssetProvider assetProvider, Checksum solutionChecksum, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.InFlightSolution.<>c__DisplayClass12_0.<<TryKickOffPrimaryBranchWork_NoLock>g__ComputePrimaryBranchAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync(Func`2 implementation, CancellationToken cancellationToken)
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63141
