### ISSUE TITLE
InvalidOperationException thrown by AbstractMoveStaticMembersRefactoringProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63287]
Version 17.4.0 Preview 2.0 [32807.141.main]

In broken VB code like

```
using md0 = ModuleMetadata.CreateFromImage(v0.EmittedAssemblyData)
Dim reader0 = md0.MetadataReader;
Dim generation0 = EmitBaseline.CreateInitialBaseline(md0, v0.CreateSymReader().GetEncMethodDebugInfo)
```

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.<>c__DisplayClass1_0.<ComputeRefactoringsAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by Youssef1313** [comment]
A similar C# bug was #62561.

Product change in #62509 was C#-only.

cc @Soreloser2

**Comment by Soreloser2** [comment]
Maybe I'm not in the right selection/context (I'm in a fresh project without the correct imports), but it seems to work fine for me on 32809.534.main: 
![image](https://user-images.githubusercontent.com/43689321/183953550-623ade05-20a4-4958-85fb-54bae0125796.png)

In C#, the bug was that we could have the error type `IncompleteMemberSyntax` be returned as it was a subclass of `MemberDeclarationSyntax`, but since there is no same abstraction in VB, we look for `MethodBaseSyntax` (methods and properties) and `ModifiedIdentifierSyntax` (fields).

I don't think there's an error syntax type for VB in the same way, but it could be the case that we're unable to get the declared symbol from one of the `ModifiedIdentifier`s.

According to the syntax visualizer, it looks like we're producing modified identifiers for each of `md0`, `reader0`, and `generation0`, although `md0` does not activate the refactoring because it isn't deemed as valid to move.

**Comment by Youssef1313** [comment]
@Soreloser2 I'll take a look to see if I can find a repro.

**Comment by Youssef1313** [comment]
@Soreloser2 This test crashes:

```vb
            Dim initialMarkup = "
Namespace TestNs
    Public Class Class1
        [|Public|]{|BC30203:|}
    End Class
End Namespace"

            Await New Test("", ImmutableArray(Of String).Empty, "") With
            {
                .TestCode = initialMarkup,
                .FixedCode = initialMarkup
            }.RunAsync().ConfigureAwait(False)
```

It's exactly the same as `TestSelectInIncompleteField_NoAction1`, except that I used a non-empty span.
