### ISSUE TITLE
RemoteSymbolFinderService gold bars with missing required document

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#63682]
**Version Used**:  32829.479.main

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Wait
3. See gold bar "Feature 'Symbol finder is currently unavailable due to an internal error` with stack
```
StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId)
      at Microsoft.CodeAnalysis.Remote.RemoteSymbolFinderService.<>c__DisplayClass11_0.<<AnalyzeDocumentAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync(Func`2 implementation, CancellationToken cancellationToken)

```

**Expected Behavior**:
No gold bar

**Comment by dibarbet** [comment]
looks like a generated doc
```
08/30/2022 14:43:16 Pacific Standard Time: Information : 7 :{"id":4530,"method":"AnalyzeDocumentAsync"}
08/30/2022 14:43:16 Pacific Standard Time: Verbose : 7 :Received: {"jsonrpc":"2.0","id":4530,"method":"AnalyzeDocumentAsync","params":[[[-5265620132179291062,-7483097340954239963,399435690]],[["a9f1e6d4-375d-4432-87d9-89b47f5f0437","C:\\Users\\dabarbet\\source\\repos\\roslyn\\src\\Compilers\\CSharp\\Portable\\Microsoft.CodeAnalysis.CSharp.csproj (netstandard2.0 {B501A547-C911-4A05-AC6E-274A50DFF30E})"],"8301e1f7-9ffe-083a-8387-1b29f4ce62bc","Syntax.xml.Syntax.Generated.cs"],false]}
08/30/2022 14:43:16 Pacific Standard Time: Information : 6 :Received request "4530" for method "AnalyzeDocumentAsync".
08/30/2022 14:43:16 Pacific Standard Time: Information : 9 :Invoking Microsoft.CodeAnalysis.Remote.RemoteSymbolFinderService.AnalyzeDocumentAsync(Checksum, DocumentId, Boolean, CancellationToken)
08/30/2022 14:43:16 Pacific Standard Time : Start : AnalyzeDocumentAsync
08/30/2022 14:43:16 Pacific Standard Time: Error : 10 :Exception thrown from request "4530" for method AnalyzeDocumentAsync: System.AggregateException: One or more errors occurred. (The solution does not contain the specified document.)
```

**Comment by CyrusNajmabadi** [comment]
Fix available.
