### ISSUE TITLE
`CSharpWrappingCodeRefactoringProvider` crashes with `ArgumentOutOfRangeException`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63732]
```
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at async Microsoft.CodeAnalysis.Wrapping.AbstractSyntaxWrapper.AbstractCodeActionComputer`1.RewriteTreeAsync[TWrapper](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractSyntaxWrapper.AbstractCodeActionComputer`1.TryCreateCodeActionAsync[TWrapper](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.GetWrapEveryNestedCodeActionAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.GetWrapEveryGroupAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.AddWrappingGroupsAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.SeparatedSyntaxListCodeActionComputer.ComputeWrappingGroupsAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractSyntaxWrapper.AbstractCodeActionComputer`1.GetTopLevelCodeActionsAsync[TWrapper](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractWrappingCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

Seeing in 17.4 P1

I have no repro, unfortunately. It happened once and I couldn't get it again.

Crashing line:

https://github.com/dotnet/roslyn/blob/8a5b7e88476d81d3d269c201e3f4d936a307e854/src/Features/Core/Portable/Wrapping/AbstractCodeActionComputer.cs#L182

Edits are calculated in:

https://github.com/dotnet/roslyn/blob/8a5b7e88476d81d3d269c201e3f4d936a307e854/src/Features/Core/Portable/Wrapping/SeparatedSyntaxList/SeparatedSyntaxListCodeActionComputer.cs#L395-L433

**Comment by Youssef1313** [comment]
The PR is set for 17.4 P1, and I'm on the same version

**Comment by Youssef1313** [comment]
Also note the stack trace is a bit different.

**Comment by CyrusNajmabadi** [comment]
Unfortunately no.  This is new.  Will have to add some info to figure out what's going on here, unless we can get a dump.

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 why do you think this is in GetWrapEachEdits?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi There is `GetWrapEveryNestedCodeActionAsync` call in the stack trace. It has `var edits = GetWrapEachEdits(wrappingStyle, indentationTrivia);`

The `edits` variable calculated by calling `GetWrapEachEdits` is passed down to `RewriteTreeAsync`

NOTE: My code had syntax errors and there were unbalanced parentheses.

**Comment by etbyrd** [comment]
I'm not sure if this should be a new issue, but this is showing up in 17.4.4 with .NET 7. 

Simplest repro is separate a variable name with '.' : 
<img width="683" alt="crash" src="https://user-images.githubusercontent.com/36282608/215905582-b6a64d9b-b4a8-42ac-80ec-aa854522da43.png">

Stack Trace: 

``` 
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.CSharp.Wrapping.SeparatedSyntaxList.CSharpParameterWrapper.PositionIsApplicable(SyntaxNode root,Int32 position,SyntaxNode declaration,Boolean containsSyntaxError,BaseParameterListSyntax listSyntax)
   at async Microsoft.CodeAnalysis.Wrapping.SeparatedSyntaxList.AbstractSeparatedSyntaxListWrapper`2.TryCreateComputerAsync[TListSyntax,TListItemSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Wrapping.AbstractWrappingCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>) ```

**Comment by CyrusNajmabadi** [comment]
Investigating.

**Comment by CyrusNajmabadi** [comment]
@etbyrd This was fixed in 17.5p1.  Do you still encounter it on that build?  Preview builds can be installed from here (https://visualstudio.microsoft.com/vs/preview/) and run side-by-side with your non-preview builds.

**Comment by CyrusNajmabadi** [comment]
I get no crash on current builds.

**Comment by etbyrd** [comment]
Just tested it and the above repro no longer works, thanks!

**Comment by CyrusNajmabadi** [comment]
Thank you!
