### ISSUE TITLE
Integration test process crashes

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#63773]
Example https://dev.azure.com/dnceng-public/public/_build/results?buildId=3017&view=logs&j=0071c484-3439-5854-d224-dcc06fee9f52&t=4bf3fce0-7c3e-545f-ec38-59bccb83af83

This appears to be affecting all the integration test legs
```
Errors Microsoft.VisualStudio.LanguageServices.New.IntegrationTests_2
The active test run was aborted. Reason: Test host process crashed
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
Command: exec "D:\a\_work\1\s\.dotnet\sdk\7.0.100-preview.7.22377.5\vstest.console.dll" @"D:\a\_work\1\s\vstest_2.rsp"
xUnit output log: D:\a\_work\1\s\artifacts\log\Debug\xUnitFailure-Microsoft.VisualStudio.LanguageServices.New.IntegrationTests_2.log
The active test run was aborted. Reason: Test host process crashed
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.

```

This is producing dumps, but they are not getting uploaded, so the first thing to fix would be that
``
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Data collector 'Blame' message: The specified inactivity time of 15 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: Dumping 1236 - testhost.net472.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Results File: D:\a\_work\1\s\artifacts\TestResults\Debug\WorkItem_2_x64_test_results.xml

Attachments:
  D:\a\_work\1\s\TestResults\0afef366-34e4-4961-a05e-db8a50d6ec17\testhost.net472_1236_20220902T152659_hangdump.dmp
  D:\a\_work\1\s\TestResults\0afef366-34e4-4961-a05e-db8a50d6ec17\testhost.net472_1236_20220902T152659_hangdump.dmp
### Standard Error
The active test run was aborted. Reason: Test host process crashed
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
### End 3624
```

**Comment by dibarbet** [comment]
Fixed dump collection in #63774 

Dump - https://dev.azure.com/dnceng-public/public/_build/results?buildId=3383&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by dibarbet** [comment]
We appear to be timing out waiting for
```
 	Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IntegrationHelper.TryLocateDteForProcess(System.Diagnostics.Process process)	Unknown
 	Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.VisualStudioInstanceFactory.UpdateCurrentlyRunningInstanceAsync.AnonymousMethod__0()	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IntegrationHelper.WaitForNotNullAsync<EnvDTE.DTE>(System.Func<EnvDTE.DTE> action)	Unknown
>	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.VisualStudioInstanceFactory.UpdateCurrentlyRunningInstanceAsync(System.Version version, string rootSuffix, System.Collections.Immutable.ImmutableList<string> extensionFiles, System.Collections.Immutable.ImmutableHashSet<string> requiredPackageIds, bool shouldStartNewInstance)	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.VisualStudioInstanceFactory.GetNewOrUsedInstanceAsync(System.Version version, string rootSuffix, System.Collections.Immutable.ImmutableList<string> extensionFiles, System.Collections.Immutable.ImmutableHashSet<string> requiredPackageIds)	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IdeTestAssemblyRunner.CreateTestCollectionInvoker.AnonymousMethod__0()	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IdeTestAssemblyRunner.RunTestCollectionForVersionAsync.AnonymousMethod__0()	Unknown
 	[Async] mscorlib.dll!System.Threading.Tasks.Task.Run	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IdeTestAssemblyRunner.RunTestCollectionForVersionAsync.AnonymousMethod__1()	Unknown
 	[Async] mscorlib.dll!System.Threading.Tasks.Task.Run	Unknown
 	[Async] Microsoft.VisualStudio.Extensibility.Testing.Xunit.dll!Xunit.Harness.IdeTestAssemblyRunner.RunTestCollectionAsync(Xunit.Sdk.IMessageBus messageBus, Xunit.Abstractions.ITestCollection testCollection, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases, System.Threading.CancellationTokenSource cancellationTokenSource)	Unknown
 	[Async] xunit.execution.desktop.dll!Xunit.Sdk.TestAssemblyRunner<Xunit.Sdk.IXunitTestCase>.RunTestCollectionsAsync(Xunit.Sdk.IMessageBus messageBus, System.Threading.CancellationTokenSource cancellationTokenSource) Line 231	C#
 	[Async] xunit.execution.desktop.dll!Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionsAsync(Xunit.Sdk.IMessageBus messageBus, System.Threading.CancellationTokenSource cancellationTokenSource) Line 165	C#
 	[Async] xunit.execution.desktop.dll!Xunit.Sdk.TestAssemblyRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 196	C#

```

**Comment by dibarbet** [comment]
ProcessId is zero which I think means the process failed to start?
@sharwell any immediate things you can think of that I should check?  I'm not able to find much more info on why the process isn't starting from the dump.  I don't see any obviously related exceptions (or ones with enough stack info)

**Comment by CyrusNajmabadi** [comment]
@Cosifne can this be closed?  or do we still need to do something here?
