### ISSUE TITLE
InvalidOperationException from AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#64012]
**Version Used**: 
Version 17.4.0 Preview 3.0 [32906.470.main]

**Steps to Reproduce**:

Editing VB file in Roslyn.sln

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.<>c__DisplayClass1_0.<ComputeRefactoringsAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by arkalyanms** [comment]
@tmat do you still have a repro and can you share the file being edited and such?

**Comment by genlu** [comment]
I'm hitting this today as well, when editing inside a test method in `src\EditorFeatures\Test2\IntelliSense\CSharpCompletionCommandHandlerTests.vb`

**Comment by ryzngard** [comment]
This looks like a problem with [GetSelectedMemberDeclarationAsync](https://github.com/dotnet/roslyn/blob/0ebd046e6c1de14e51deca5dbf2b92c9e3b6e2ff/src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb#L14) returning things that don't actually have member declaration symbols. I wonder if somehow in editing VB it could end up having a member level declaration syntax node with no backing symbol? 

It filters out `IncompleteMemberSyntax` but maybe something else needs filtering? It will end up using https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs so maybe @CyrusNajmabadi  or @Soreloser2 know something?

**Comment by CyrusNajmabadi** [comment]
one possibility would be how it handles FieldDeclarationSyntaxes that's a single MemberDecalration, but it has N variable-declarators which have their own symbols.

that said, we could jsut get a dump here and see what it had.

**Comment by ryzngard** [comment]
I think it's related to this low hit [NFW](https://prism.vsdata.io/failure/?query=c%3A*AbstractMoveStaticMembersRefactoringProvider*%20fe%3Aide%2Fvbcs%2Fnonfatalwatson&eventType=fault&failureType=hits&failureHash=4aa747a7-2e8c-2a72-a3ba-2df59300385c) I put in for cabs
