### ISSUE TITLE
Crash typing malformed #load directive in .csx files

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#6405]
Type the following in a .csx file:

```#load f```

**RESULTS:**
```
System.InvalidOperationException: Unexpected value 'LoadDirectiveTrivia' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind'
   at Microsoft.CodeAnalysis.CSharp.Syntax.DirectiveTriviaSyntax.get_DirectiveNameToken()
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.SnippetCompletionProvider.<GetSnippetsForDocumentAsync>d__4.MoveNext()
...
```

**Comment by KevinH-MS** [comment]
@drognanar, could you verify that this is fixed?
