### ISSUE TITLE
LocalRewriter.TransformCompoundAssignmentLHS assert dialog in Immediate Window on "int x; x++;"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6419]
1. Create a new console application and press F11 to start a new debugging session.
2. In the Immediate Window, type ```int x = 7;``` and hit enter.
3. In the Immediate Window, type ```x++;``` and hit enter.

Assert dialog: 
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected value 'PseudoVariable' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'



   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)

   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.TransformCompoundAssignmentLHS(BoundExpression originalLHS, ArrayBuilder`1 stores, ArrayBuilder`1 temps, Boolean isDynamicAssignment)

   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIncrementOperator(BoundIncrementOperator node)

   at Microsoft.CodeAnalysis.CSharp.BoundIncrementOperator.Accept(BoundTreeVisitor visitor)

   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)

   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)

   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)

   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)

   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewr......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by amcasey** [comment]
Dup of https://github.com/dotnet/roslyn/issues/3861.
