### ISSUE TITLE
NRE in `dotnet-runtime-perf` with wasm+AOT

### ISSUE THREAD

**Issue by radical** [dotnet/roslyn#64312]
`dotnet-runtime-perf` [build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2004856&view=logs&j=e57eed19-532e-51af-97c3-04d32d813641&t=84d1403a-85dc-55e4-8e62-e7b39417073b) built for wasm/aot on `dotnet/runtime` `main` [dotnet/runtime#7fc8fb56327e9696ce9baa80f997e3f50675af1f](https://github.com/dotnet/runtime/commit/7fc8fb56327e9696ce9baa80f997e3f50675af1f).

**Version Used**: 
Sdk version `8.0.100-alpha.1.22463.23`

**Steps to Reproduce**:

Instructions to build:

https://github.com/radical/performance/blob/wasm-docs/docs/benchmarking-workflow-dotnet-runtime.md#dotnet-runtime-prerequisites-for-wasm

This does not happen on every run.

**Expected Behavior**:

No exception.

**Actual Behavior**:
```
/home/helixbot/work/A90D097A/p/dotnet/sdk/8.0.100-alpha.1.22463.23/Roslyn/Microsoft.CSharp.Core.targets(79,5):

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNode.get_FullSpan()
   at Microsoft.CodeAnalysis.SyntaxNode.DescendantNodesOnly(TextSpan span, Func`2 descendIntoChildren, Boolean includeSelf)+MoveNext()
   at Microsoft.CodeAnalysis.PredicateSyntaxStrategy`1.Builder.<VisitTree>g__getFilteredNodes|8_0(SyntaxNode root, Func`3 func, CancellationToken token)
   at Microsoft.CodeAnalysis.PredicateSyntaxStrategy`1.Builder.VisitTree(Lazy`1 root, EntryState state, Lazy`1 model, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SyntaxStore.Builder.GetSyntaxInputTable(SyntaxInputNode syntaxInputNode, NodeStateTable`1 syntaxTreeTable)
   at Microsoft.CodeAnalysis.SyntaxInputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.BatchNode`1.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsAndUpdateCompilation(Compilation compilation, Compilation& outputCompilation, ImmutableArray`1& diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunGenerators(Compilation input, ParseOptions parseOptions, ImmutableArray`1 generators, AnalyzerConfigOptionsProvider analyzerConfigOptionsProvider, ImmutableArray`1 additionalTexts, DiagnosticBag generatorDiagnostics)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

cc @lewing @DrewScoggins this as hit on PERFTIGER198, build number `20220926.10`.

**Comment by jaredpar** [comment]
Closing due to age. Can reopen if we see more recent instances
