### ISSUE TITLE
CSharpChangeNamespaceToMatchFolderCodeFixProvider crash when trying to fix Refit interface

### ISSUE THREAD

**Issue by Kloizdena** [dotnet/roslyn#64396]
**Version Used**: 
Visual Studio 2022 Version 17.3.4

**Steps to Reproduce**:

1. Create an empty .NET 6 class library
2. Add Refit as a nuget reference
3. Add the following interface in the root folder:
```csharp
using Refit;

namespace AnalyzerTest.TestFolder2
{
	public interface ITestApi
	{
		[Post("/api/Test")]
		Task TestCall();
	}
}
```
4. Click on the namespace and try to load code suggestions 

**Expected Behavior**:
A suggestion should appear to "Change namespace to match folder structure"

**Actual Behavior**:
An error appears:
'CSharpChangeNamespaceToMatchFolderCodeFixProvider' encountered an error and has been disabled
![image](https://user-images.githubusercontent.com/17968888/193323520-7840dd74-0486-420d-83b8-99210f621fa0.png)

Stack trace:
```
System.InvalidOperationException : The solution does not contain the specified document.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,DocumentId documentId)
   at Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.<>c__DisplayClass26_0.<ChangeNamespaceInSingleDocumentAsync>b__4(IGrouping`2 refInOneDocument)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1 tasks)
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceInSingleDocumentAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.TryChangeTopLevelNamespacesAsync[TNamespaceDeclarationSyntax,TCompilationUnitSyntax,TMemberDeclarationSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.Renamer.SyncNamespaceDocumentAction.GetModifiedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Rename.Renamer.RenameDocumentActionSet.UpdateSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.MatchFolderAndNamespace.AbstractChangeNamespaceToMatchFolderCodeFixProvider.FixAllInDocumentAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
Andrew, can you ptal?

**Comment by CyrusNajmabadi** [comment]
Closing as i don't see any prism hits on this.
