### ISSUE TITLE
System.ArgumentException when binding pattern matching expression

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#64399]
We start seeing NFWs for this in 17.4, and I can repro with latest int.preview 17.4.0 Preview 3.0 [32929.104.main]

Repro steps:
Open a document with the code below would trigger yellow bar in VS, with the following stack

```
System.ArgumentException: Value does not fall within the expected range.
      at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.NumericValueSet`2.Microsoft.CodeAnalysis.CSharp.IValueSet.get_Sample()
      at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SampleValueString(IValueSet remainingValues, TypeSymbol type, Boolean requireExactType, Boolean& unnamedEnumValue)
      at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
      at Microsoft.CodeAnalysis.CSharp.PatternExplainer.<SamplePatternForTemp>g__tryHandleTuplePattern|2_5(Boolean& unnamedEnumValue, <>c__DisplayClass2_0& )
      at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForTemp(BoundDagTemp input, Dictionary`2 constraintMap, Dictionary`2 evaluationMap, Boolean requireExactType, Boolean& unnamedEnumValue)
      at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause, Boolean& unnamedEnumValue)
      at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
      at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
      at System.Threading.Tasks.Task.Execute()
```

```cs
public enum EffectiveVisibility
    {
        Private,
        Public,
        Family,
        Assembly,
        FamilyAndAssembly,
        FamilyOrAssembly,
    }

    class N
    {
        private static EffectiveVisibility ConstrainToVisibility(this EffectiveVisibility visibility, EffectiveVisibility enclosingVisibility)
        {
            return (visibility, enclosingVisibility) switch
            {
                (_, EffectiveVisibility.Private) => EffectiveVisibility.Private,
                (EffectiveVisibility.Private, _) => EffectiveVisibility.Private,
                (EffectiveVisibility.Public, _) => enclosingVisibility,
                (_, EffectiveVisibility.Public) => visibility,
                (EffectiveVisibility.FamilyOrAssembly, _) => enclosingVisibility,
                (_, EffectiveVisibility.FamilyOrAssembly) => visibility,
                (EffectiveVisibility.Family, EffectiveVisibility.Family) => EffectiveVisibility.Family,
                (EffectiveVisibility.Family, EffectiveVisibility.Assembly) => EffectiveVisibility.FamilyAndAssembly,
                (EffectiveVisibility.Family, EffectiveVisibility.FamilyAndAssembly) => EffectiveVisibility.FamilyAndAssembly,
                (EffectiveVisibility.Assembly, EffectiveVisibility.Family) => EffectiveVisibility.FamilyAndAssembly,
                (EffectiveVisibility.Assembly, EffectiveVisibility.FamilyAndAssembly) => EffectiveVisibility.FamilyAndAssembly,
                (EffectiveVisibility.FamilyAndAssembly, EffectiveVisibility.Family) => EffectiveVisibility.FamilyAndAssembly,
                (EffectiveVisibility.FamilyAndAssembly, EffectiveVisibility.Assembly) => EffectiveVisibility.FamilyAndAssembly,
                ( < 0 or > EffectiveVisibility.FamilyOrAssembly, _) => throw new InvalidCastException(),
                (_, < 0 or > EffectiveVisibility.FamilyOrAssembly) => throw new InvalidCastException()
            };
        }
    }
```

**Comment by jcouv** [comment]
Thanks for reporting this with a concise code snippet. This was a tricky issue, but the fix is in for 17.5
