### ISSUE TITLE
StackOverflowException in code analyzer for simple class

### ISSUE THREAD

**Issue by znakeeye** [dotnet/roslyn#64392]
Create a `.NET 6` console app, and add the following erroneous class:
```c#
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace SimpleTest;

[Display(x => $"{Name}")]
public class Foo
{
    [Display(Name = "Name")]
    public string Name { get; }
}
```

Wait for the Code Analyzer to analyze the code...

**Visual Studio crashes**
Sometimes the process doesn't get killed, and you get a chance to copy the exception details:
```
StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
```

Then, in Event Viewer, I can find some more details:
```
Faulting application name: devenv.exe, version: 17.3.32901.215, time stamp: 0x63112d8a
Faulting module name: Microsoft.CodeAnalysis.CSharp.ni.dll, version: 4.300.22.42310, time stamp: 0x84a74681
Exception code: 0xc00000fd
Fault offset: 0x0000000000ea35d9
Faulting application start time: 0x01d8d4d3ac9b88d7
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.C1d3c2215#\47032c6832869df03ca7a311375febdc\Microsoft.CodeAnalysis.CSharp.ni.dll
```

**Version Used**: 
Microsoft Visual Studio Professional 2022
Version 17.3.4
VisualStudio.17.Release/17.3.4+32901.215
Microsoft .NET Framework
Version 4.8.04084
C# Tools   4.3.0-3.22423.10+b35bb0baca1071d50cc4f8cf5a1a89e7cc112461

**Comment by jasonmalinowski** [comment]
@znakeeye The error information there won't be sufficient for us to diagnose this; there should be additional entries in the event viewer that have bucket/report IDs that we can use to try to find your report in our crash reporting systems. Alternatively, if you report a bug through the Visual Studio feedback tool that should also capture those logs automatically.

**Comment by jasonmalinowski** [comment]
This appears to be an infinite recursion in the compiler's attribute resolution. I'm seeing this set of frames repeating over and over again on our background thread:

```
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAttributesBag+0xd1 [/_/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs @ 838] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetDecodedWellKnownAttributeData+0x42 [/_/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs @ 868] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.get_Layout+0x18 [/_/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs @ 1378] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbolWithAttributesAndModifiers.PostDecodeWellKnownAttributes+0xc2 [/_/src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs @ 337] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedBackingFieldSymbol.PostDecodeWellKnownAttributes+0x35 [/_/src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedBackingFieldSymbol.cs @ 131] 
Microsoft_CodeAnalysis_CSharp_ni!
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbolWithAttributesAndModifiers.GetAttributesBag+0xbf [/_/src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs @ 89] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbolWithAttributesAndModifiers.GetAttributes+0xb [/_/src/Compilers/CSharp/Portable/Symbols/Source/FieldSymbolWithAttributesAndModifiers.cs @ 72] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbolBase.GetAttributesBag+0xff [/_/src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs @ 1072] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbolBase.GetAttributes+0xb [/_/src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs @ 1090] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.LazyObsoleteDiagnosticInfo.ResolveInfo+0x59 [/_/src/Compilers/CSharp/Portable/Errors/LazyObsoleteDiagnosticInfo.cs @ 31] 
Microsoft_CodeAnalysis_CSharp_ni!Microsoft.CodeAnalysis.CSharp.LazyDiagnosticInfo.GetResolvedInfo+0x2c [/_/src/Compilers/CSharp/Portable/Errors/LazyDiagnosticInfo.cs @ 22] 
Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.DiagnosticWithInfo.get_Severity+0x1c [/_/src/Compilers/Core/Portable/Diagnostic/DiagnosticWithInfo.cs @ 77] 
Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.DiagnosticBag.ToReadOnlyCore<Microsoft.CodeAnalysis.Diagnostic>+0xee [/_/src/Compilers/Core/Portable/Diagnostic/DiagnosticBag.cs @ 205] 
Microsoft_CodeAnalysis_ni!Microsoft.CodeAnalysis.BindingDiagnosticBag<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol>.ToReadOnly+0x3f [/_/src/Compilers/Core/Portable/Binding/BindingDiagnosticBag.cs @ 87] 
```
