### ISSUE TITLE
Roslyn could not load assembly when a reference is added and InvokeMember method is used.

### ISSUE THREAD

**Issue by mustafas18** [dotnet/roslyn#64462]
Roslyn could not load assembly, when `InvokeMember` method is used.  Here is the error:

> FileNotFoundException: Could not load file or assembly 'SimpleLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

In the following code, the `SimpleLibrary `is added to references and the program is compiled successfully. But when `InvokeMember `is used, the program could not find `SimpleLibrary ` and a FileNotFound exception is thrown.

``` C#
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using System.Reflection;
using System.Text;

namespace ConsoleApp1
{
    public class Program
    {

        static void Main(string[] args)
        {

            List<MetadataReference> references = new List<MetadataReference>(DefaultReferences());

            var strBuilder = new StringBuilder();

            strBuilder.AppendLine(@"
            using SimpleLibrary;
            using System.IO;
            namespace RoslynCompileSample
            {

                public class Program
                {
                    public string Main()
                    {
                        if (StringLibrary.StartsWithUpper(""StartsWithUpper""))
                        {
                           System.Console.WriteLine(""yes!"");
                        }
                       return ""Hi!"";

                    }

                }
            }
            ");

            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(strBuilder.ToString());

            string assemblyName = Path.GetRandomFileName();
            CSharpCompilation compilation = CSharpCompilation.Create(
               assemblyName,
               syntaxTrees: new[] { syntaxTree },
               references: references,
               options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary


                ));

            using (var ms = new MemoryStream())
            {
                try
                {
                    EmitResult result = compilation.Emit(ms);
                    if (!result.Success)
                    {
                        IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                                diagnostic.IsWarningAsError ||
                                diagnostic.Severity == DiagnosticSeverity.Error);

                    }
                    else
                    {
                        ms.Seek(0, SeekOrigin.Begin);
                        Assembly assembly = Assembly.Load(ms.ToArray());
                        Type type = assembly.GetType("RoslynCompileSample.Program");
                        object obj = Activator.CreateInstance(type);

                        var methodOutput = type.InvokeMember("Main",
                               BindingFlags.Default | BindingFlags.InvokeMethod,
                                null,
                                obj,
                                null);
                                            }
                }
                catch (Exception ex)
                {

                }

            }


        }
        private static List<MetadataReference> DefaultReferences()
        {
            List<MetadataReference> references = new List<MetadataReference>();

            references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(System.Runtime.CompilerServices.DynamicAttribute).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("System.Console")).Location));
            references.Add(MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("System.Runtime")).Location));

            Stream stream = File.OpenRead(@"D:\SimpleLibrary.dll");
            references.Add(MetadataReference.CreateFromStream(stream));

            return references;
        }
    }
}

```
And here is the reference dll file
[SimpleLibrary.dll](https://cdn.mana-automation.com/Files/sb.mana-automation.com/a9eea3ad-c178-410b-94e6-56dc1c255673.zip)

**Comment by jaredpar** [comment]
The sample provided here is incomplete. Could you expand it out to a complete sample?

**Comment by mustafas18** [comment]
@jaredpar . In the code, I add `SimpleLibrary ` to references. but when I invoke `Main` method the following error is occurred:

`FileNotFoundException: Could not load file or assembly 'SimpleLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**Comment by jaredpar** [comment]
@mustafas18 I understand but that is not enough for us to reproduce this error. We need a complete code sample.

**Comment by mustafas18** [comment]
@jaredpar I updated the code and now the code sample is complete. The SampleLibrary.dll file can be downloaded from : [SampleLibrary.dll](https://cdn.mana-automation.com/Files/sb.mana-automation.com/a9eea3ad-c178-410b-94e6-56dc1c255673.zip)

**Comment by jaredpar** [comment]
Thanks, I can now reproduce the problem.

The issue is that `SimpleLibrary.dll` is compiled for .NET Core. When the code you provided is run on .NET Core everything executes as expected. When it's run on .NET Framework then it fails because the references that SimpleLibrary depends on are not available and hence you get that error

```cmd
> dotnet run --framework net472
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at ConsoleApp1.Program.DefaultReferences() in C:\Users\jaredpar\code\temp\console\Program.cs:line 99
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\jaredpar\code\temp\console\Program.cs:line 19

> dotnet run --framework net7.0
>
```

**Comment by mustafas18** [comment]
The error is `FileNotFoundException: Could not load file or assembly 'SimpleLibrary....` Therefore, we should look for a method to load the assembly.

The `SimpleLibrary `assembly can be added to a scope by `AssemblyLoadContext.Default.LoadFromStream `method as follow:

```
Stream stream = File.OpenRead(@"d:\SimpleLibrary.dll");
AssemblyLoadContext.Default.LoadFromStream(stream);
```

Here is the complete code:

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using System.Reflection;
using System.Text;

namespace ConsoleApp1
{
    public class Program
    {

        static void Main(string[] args)
        {

            List<MetadataReference> references = new List<MetadataReference>(DefaultReferences());

            var strBuilder = new StringBuilder();

            strBuilder.AppendLine(@"
            using SimpleLibrary;
            using System.IO;
            namespace RoslynCompileSample
            {

                public class Program
                {
                    public string Main()
                    {
                        if (StringLibrary.StartsWithUpper(""StartsWithUpper""))
                        {
                           System.Console.WriteLine(""yes!"");
                        }
                       return ""Hi!"";

                    }

                }
            }
            ");

            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(strBuilder.ToString());

            string assemblyName = Path.GetRandomFileName();
            CSharpCompilation compilation = CSharpCompilation.Create(
               assemblyName,
               syntaxTrees: new[] { syntaxTree },
               references: references,
               options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary


                ));

            using (var ms = new MemoryStream())
            {
                try
                {
                    EmitResult result = compilation.Emit(ms);
                    if (!result.Success)
                    {
                        IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                                diagnostic.IsWarningAsError ||
                                diagnostic.Severity == DiagnosticSeverity.Error);

                    }
                    else
                    {
                        ms.Seek(0, SeekOrigin.Begin);
                        Assembly assembly = Assembly.Load(ms.ToArray());

                        stream = File.OpenRead(@"d:\SimpleLibrary.dll");
                        AssemblyLoadContext.Default.LoadFromStream(stream);

                        Type type = assembly.GetType("RoslynCompileSample.Program");
                        object obj = Activator.CreateInstance(type);

                        var methodOutput = type.InvokeMember("Main",
                               BindingFlags.Default | BindingFlags.InvokeMethod,
                                null,
                                obj,
                                null);
                                            }
                }
                catch (Exception ex)
                {

                }

            }


        }
        private static List<MetadataReference> DefaultReferences()
        {
            List<MetadataReference> references = new List<MetadataReference>();

            references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(System.Runtime.CompilerServices.DynamicAttribute).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("System.Console")).Location));
            references.Add(MetadataReference.CreateFromFile(Assembly.Load(new AssemblyName("System.Runtime")).Location));

            Stream stream = File.OpenRead(@"D:\SimpleLibrary.dll");
            references.Add(MetadataReference.CreateFromStream(stream));

            return references;
        }
    }
}
```
