### ISSUE TITLE
TypeLoadException when declaring a task-like type as `ref struct`

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64903]
**Version Used**: VS 2022 17.4 Preview 4

**Steps to Reproduce**:

1.  Declare a task-like type as a `ref struct`: the task type itself is a ref struct, the builder needs to be one by extension too; the awaiter is a class as it must implement an interface.
2. Write a simple `await` expression using that type.
3. Run the application.

The sample code can be found in the [Sharplab repro](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0AlArgOwC4EsBbAU1QGEB7QgB3wBtiAnAZSYDd8BjYgZwG5YCZBACsAmLGwBDEj2pTuiAAp0pATwDmjCjgAm4wWGEB2WAG9YiK8gDMwgGzIAHMkcBZKfmwAKAJSXrCxhrEOQATkQ3P3EQgF9YAKsURxAXdGIAM2ZcRkxOXBB3P0TEINDrEAjC8ipqBlxiXUKY63iYNtgAbQBBHjVsTjdiXAALCl0AIUx6XSZvXDVqYgoM73SsnLyC+yHR8amZpl9fAF1YRkzEHk38xHXs3PzC8xKQO26Ad08GxkQAcWGn2+c18pWQxkQ2GIH0QQPwP2iiDaHTgRjhP0QAC5EABJAByFAIGTUlBo9XwFGwL2CFTsACMKBQ6LieKS6sNGmCNMM+EjXnYQAAWf7DdI8TB0XB+MFtEJvZDCgDy2DZ9Ua3hQRk4tXJlNBZj57XOl2uj1wd0yDy2hV2Y0m0zos0Y1LlAogjnuN22tv2DqdiDIFykDWlBpAEKhH0RKNdCsQ2SkjFwAB4ACoJhoeTgjLzEAB83guGUQ6dwweIWZzUKuZczCirxH8NPKHxGTGIJYzFfruaxuN6/U4XcruZKBpjtLjrFww57UO8OIHA1n2d713LI6h+sNsaF8eGAFEAB7cagESneY+n8/YRDEE/EM8U7Db2WTvfTsUSqWvhLN2xxuiyqqhyuhpuiTAADSdrW3arlCBYlCERYlhBvyVFBiAoaWG5zh2651vBjZIdYrbtqhXzwkwfb4oS+DEiBN4kVYZEXDBuFETRS5DrBm7EGOO7vsK6IAKrYDwUgZMQwE6qB4GUT80E4YRDaIf+yGXKmaHhJh2Erg2NYcQ2TblCxbZsVpCnUdiOKBvCXBSHQBJEiSslMeppHmR2ylwQZNncfpo7/uOf6xp6ZqFK4XI8oabRAA==).

**Expected Behavior**: I'm not familiar with the internals of task-like types and async state machines in C#, so I don't know if it's even possible to emit valid async code in this scenario. The alternative would be to reject ref struct task-like types altogether.

**Actual Behavior**: `TypeLoadException`, probably because the state machine (regular struct) contains a field for the builder (ref struct)?

```
System.TypeLoadException: A ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type.
   at Playground.Program.M() in E:\Projects\compiler-playground\Program.cs:line 15
   at Playground.Program.<Main>d__0.MoveNext() in E:\Projects\compiler-playground\Program.cs:line 11
```

It's also not possible to assign such types to variables inside async methods: writing `var task = M(); await task;` in the `Main` method (something that would be perfectly legal for regular task types) leads to CS4012: "Parameters or locals of type 'RefStructTask' cannot be declared in async methods or async lambda expressions."

**Comment by jcouv** [comment]
Assigned to @cston to load-balance
