### ISSUE TITLE
Assertion in nullable walker in speculation on switch expression

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#65061]
Stack:

I had this code:

```c#
using System;

int? Test1(string str)
{
    return str switch
    {
        "A" => 1,
        "B" => 2,
        "C" => 3,
        _ => default,
    };
}
static int? Test2(string str)
{
    switch (str)
    {
        case "A":
            return 1;
        case "B":
            return 2;
        case "C":
            return 3;
        default:
            return default;
    }
}
```

And i was trying to run `convert switch statement to expression` on the statement in `Test2`.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Variables.CreateNestedMethodScope(MethodSymbol method) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.Variables.cs:line 217

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.GetOrCreateNestedFunctionVariables(Variables container, MethodSymbol lambdaOrLocalFunction) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 2966

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeLocalFunctionOrLambda(IBoundLambdaOrFunction lambdaOrFunction, MethodSymbol lambdaOrFunctionSymbol, LocalState state, MethodSymbol delegateInvokeMethod, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 3003

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLocalFunctionStatement(BoundLocalFunctionStatement node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by mavasani** [comment]
I also hit this assert - for me it came from running the debug bits of compiler + analyzer in the IDE and was reported as an AD0001 in the error list:

```
Severity	Code	Description	Project	File	Line	Category	Source	Suppression State	Tool
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.SimplifyThisOrMe.CSharpSimplifyThisOrMeDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Assertion failed'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis
SyntaxTree: C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs
SyntaxNode: this [ThisExpressionSyntax]@[142482..142486) (2838,35)-(2838,39)

System.InvalidOperationException: Assertion failed
   at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in C:\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 27
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Variables.CreateNestedMethodScope(MethodSymbol method) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.Variables.cs:line 217
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.GetOrCreateNestedFunctionVariables(Variables container, MethodSymbol lambdaOrLocalFunction) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 2965
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeLocalFunctionOrLambda(IBoundLambdaOrFunction lambdaOrFunction, MethodSymbol lambdaOrFunctionSymbol, LocalState state, MethodSymbol delegateInvokeMethod, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 3002
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLocalFunctionStatement(BoundLocalFunctionStatement node) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 2947
   at Microsoft.CodeAnalysis.CSharp.BoundLocalFunctionStatement.Accept(BoundTreeVisitor visitor) in C:\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 3260
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitWithStackGuard(BoundNode node) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractFlowPass.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitAlways(BoundNode node) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractFlowPass.cs:line 353
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Visit(BoundNode node) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractFlowPass.cs:line 342
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node, Boolean expressionIsRead) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 3334
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 3317
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Scan(Boolean& badRegion) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractFlowPass.cs:line 424
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 566
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Analyze(Boolean& badRegion, Optional`1 initialState) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\AbstractFlowPass.cs:line 447
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, Optional`1 initialState, Builder snapshotBuilderOpt, Boolean requiresAnalysis) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1695
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewriteSpeculation(Int32 position, BoundNode node, Binder binder, SnapshotManager originalSnapshots, SnapshotManager& newSnapshots, ImmutableDictionary`2& remappedSymbols) in C:\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1504
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary() in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1955
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 2052
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 544
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1328
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1206
   at Microsoft.CodeAnalysis.CSharp.SpeculativeSemanticModelWithMemberModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\SpeculativeSemanticModelWithMemberModel.cs:line 448
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 572
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 4932
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 5031
   at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 99
   at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel, SyntaxNode node, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\Core\Portable\Compilation\Extensions.cs:line 21
   at Microsoft.CodeAnalysis.Simplification.Simplifiers.AbstractMemberAccessExpressionSimplifier`3.ShouldSimplifyThisMemberAccessExpression(TMemberAccessExpressionSyntax memberAccessExpression, SemanticModel semanticModel, SimplifierOptions simplifierOptions, TThisExpressionSyntax& thisExpression, ReportDiagnostic& severity, CancellationToken cancellationToken) in C:\roslyn\src\Workspaces\Core\Portable\Simplification\Simplifiers\AbstractMemberAccessExpressionSimplifier.cs:line 65
   at Microsoft.CodeAnalysis.SimplifyThisOrMe.AbstractSimplifyThisOrMeDiagnosticAnalyzer`4.AnalyzeNode(SyntaxNodeAnalysisContext context) in C:\roslyn\src\Features\Core\Portable\SimplifyThisOrMe\AbstractSimplifyThisOrMeDiagnosticAnalyzer.cs:line 62
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data) in C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 932
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info) in C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1611
-----

Suppress the following diagnostics to disable this analyzer: IDE0003	Microsoft.CodeAnalysis (netcoreapp3.1)		1	Compiler	IntelliSense	Active	Compiler
```
