### ISSUE TITLE
C# intellisense claims cast is unnecessary, but in fact it is necessary

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#6507]
VS2015 RTM C# claims "cast is redundant" within the formatted string below for `(int)`.

```csharp
SECURITY_STATUS status = SECURITY_STATUS.SomeConstant;
throw new Exception($"SECURITY_STATUS: 0x{(int)status:x8}");
```

But in fact it is necessary. With the cast, I get the exception message I expect: 

    System.Exception : SECURITY_STATUS: 0x80090029

But if I remove the cast, as Roslyn suggests, I get an error in formatting the string:

```
System.FormatException : Format String can be only "G", "g", "X", "x", "F", "f", "D" or "d".
   at System.Enum.ToString(String format)
   at System.Enum.ToString(String format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at PInvoke.NCrypt.ThrowOnError(SECURITY_STATUS status) in C:\Users\andarno\git\pinvoke\src\NCrypt\NCrypt.Helpers.cs:line 83
   at PInvoke.NCrypt.NCryptCreatePersistedKey(SafeProviderHandle provider, String algorithmId, String keyName, LegacyKeySpec legacyKeySpec, NCryptCreatePersistedKeyFlags flags) in C:\Users\andarno\git\pinvoke\src\NCrypt\NCrypt.Helpers.cs:line 62
   at NCrypt.CreatePersistedKey() in C:\Users\andarno\git\pinvoke\src\NCrypt.Tests\NCrypt.cs:line 24
```

Evidently Roslyn doesn't appreciate that the cast does in fact make a difference. It should be fixed to not suggest I can remove it without any effect.

**Comment by dpoeschl** [comment]
Probable dupe of https://github.com/dotnet/roslyn/issues/4037

**Comment by AArnott** [comment]
I agree. It looks exactly like a dupe. I'll close.
