### ISSUE TITLE
Cannot find references to generated method in hand-written source

### ISSUE THREAD

**Issue by kjkrum** [dotnet/roslyn#65105]
VS 17.3.6

Background: I'm working on an ASP.NET Core project that uses a custom source generator to generate public methods from private methods. The generator seems to be working perfectly. Intellisense knows about the generated methods.

Hand-written `partial` service: `private async Task<Foo> GetFooAsyncInternal(...)`
Generated `partial` service: `public async Task<Foo> GetFooAsync(...)` calls `GetFooAsyncInternal`
Hand-written controller: calls `GetFooAsync`

In my hand-written service, "find all references" to a private method correctly finds the references in generated code. But if I navigate to that generated code and "find all references" to the generated public method, it does *not* find the references in my hand-written controller. It works if I "find all references" from where the generated method is referenced. It only fails when using "find all references" from within the generated code, at the target of the reference.

Possibly related to #64348.

**Comment by jasonmalinowski** [comment]
@kjkrum Does it work if you check this checkbox? 
![image](https://user-images.githubusercontent.com/201340/199565192-78e2acc2-bc8b-4b24-9317-bd5b19daf9f5.png)

**Comment by kjkrum** [comment]
@jasonmalinowski Yes, thanks! However, I get a new error when navigating to generated code from the find references search results. This may deserve its own issue. I'll see if it's been reported.

>Feature 'Inheritance margin' is currently unavailable due to an internal error.

```
StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16`1.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId)
      at Microsoft.CodeAnalysis.Remote.RemoteInheritanceMarginService.<>c__DisplayClass2_0.<GetInheritanceMarginItemsAsync>b__0(Solution solution)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

I eliminated the error spam by disabling Text Editor > C# > Advanced > Show inheritance margin, which I never paid attention to anyway.

**Comment by kjkrum** [comment]
This appears to be #63232.
