### ISSUE TITLE
I received this error just starting Visual Studio 2022 Pro.

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#65123]
I received this error just starting Visual Studio 2022 Pro. 

I selected a solution from the context menu - right-clicking the Visual Studio 2022 Pro icon in the start menu.

```
StreamJsonRpc.RemoteInvocationException: Unexpected false - line 54
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__13.MoveNext()
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Unexpected false - line 54
      at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1.<InvokeAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.SymbolSearch.SymbolSearchUpdateEngine.Updater.<UpdateInBackgroundAsync>d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__17.MoveNext()
```

_Originally posted by @Chris-Dickerson in https://github.com/dotnet/roslyn/issues/46580#issuecomment-1295816731_

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Is this one you already fixed?

**Comment by CyrusNajmabadi** [comment]
No.  This is the xml downloading issue.  We do have new telemetry in place to tell us what data we're getting, so we can attempt to place the blame accordingly on where things are going wrong.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Is there an existing bug to dupe against, or should this be kept around to remind somebody to look at that telemetry?

**Comment by CyrusNajmabadi** [comment]
Mitigated with https://github.com/dotnet/roslyn/pull/65279.
