### ISSUE TITLE
Unable to reference netmodule

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#65499]
**Version Used**: 

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
```

**Steps to Reproduce**:

Run the following code:

```C#
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;

var moduleSource = @"
    class Base {
    }
";

var assemblySource = @"
    class Derived : SourceA {
    }
";

var moduleCompilation = CreateCompilation(moduleSource);
moduleCompilation = moduleCompilation.WithOptions(moduleCompilation.Options.WithOutputKind(OutputKind.NetModule).WithModuleName("base"));

var moduleStream = new MemoryStream();
moduleCompilation.Emit(moduleStream);
moduleStream.Position = 0;
var moduleBytes = moduleStream.ToArray();

var moduleReference = MetadataReference.CreateFromImage(moduleBytes, MetadataReferenceProperties.Module);

var assemblyCompilation = CreateCompilation(assemblySource).AddReferences(moduleReference);
assemblyCompilation = assemblyCompilation.WithOptions(assemblyCompilation.Options.WithModuleName("derived"));

Console.WriteLine(assemblyCompilation.Assembly.Modules.Count());

static CSharpCompilation CreateCompilation(string source)
{
    var syntaxTree = CSharpSyntaxTree.ParseText(source);
    var syntaxTrees = new[] { syntaxTree };
    var references = new []
    {
        MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
    };

    var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true);
    var compilation = CSharpCompilation.Create("dummy", syntaxTrees, references, options);
    return compilation;
}
```

**Expected Behavior**:

It prints the number of modules, which should be 2.

**Actual Behavior**:

It crashes with an exception:

```text
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.AssemblyMetadata' to type 'Microsoft.CodeAnalysis.ModuleMetadata'.
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBoundReferenceManager()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.get_SourceAssembly()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.get_Assembly()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.get_CommonAssembly()
   at Microsoft.CodeAnalysis.Compilation.get_Assembly()
   at Program.<Main>$(String[] args) in T:\RoslynRepro\Program.cs:line 27
```

After stepping through the sources, it seems to me as if the problem is here:

https://github.com/dotnet/roslyn/blob/dc04e499a090e9e2277ef358eb385905fd4a6003/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L158

It seems to me as if the expectation was that depending on the module kind in the properties the metadata that is constructed should be an `AssemblyMetadata` or `ModuleMetadat`, but it unconditionally chooses `AssemblyMetadata`.

**Comment by Youssef1313** [comment]
Similar issue: https://github.com/dotnet/roslyn/issues/11581
