### ISSUE TITLE
ArgumentOutOfRangeException while renaming

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#65798]
While working in Roslyn.sln (RoamingProfileStorageLocation.cs).

Add this to the file:

```C#
/// <summary>
/// Specifies that the option should be stored into a roamed profile across machines.
/// </summary>
internal sealed class RoamingProfileStorageMultiLocation : ClientSettingsStorageLocation
{
    public override bool IsMachineLocal => false;

    public RoamingProfileStorageLocation(string keyName)
        : base(keyName)
    {
    }

    /// <summary>
    /// Creates a <see cref="RoamingProfileStorageLocation"/> that has different key names for different languages.
    /// </summary>
    /// <param name="keyNameFromLanguageName">A function that maps from a <see cref="LanguageNames"/> value to the key name.</param>
    public RoamingProfileStorageLocation(Func<string?, string> keyNameFromLanguageName)
        : base(keyNameFromLanguageName)
    {
    }
}
```

Copy `RoamingProfileStorageMultiLocation`, select ctor name and paste the text over it.

```
StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values. (Parameter 'span')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'span')
      at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindLinkedSymbolsAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.SymbolSet.<>c__DisplayClass13_0.<<AddCascadedAndLinkedSymbolsToAsync>g__MapAndAddLinkedSymbolsAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.SymbolSet.AddCascadedAndLinkedSymbolsToAsync(FindReferencesSearchEngine engine, ISymbol symbol, MetadataUnifyingSymbolHashSet seenSymbols, Stack`1 workQueue, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.SymbolSet.DetermineInitialSearchSymbolsAsync(FindReferencesSearchEngine engine, MetadataUnifyingSymbolHashSet symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.SymbolSet.CreateAsync(FindReferencesSearchEngine engine, MetadataUnifyingSymbolHashSet symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindRenamableReferencesAsync(ImmutableArray`1 symbols, Solution solution, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Rename.SymbolicRenameLocations.AddLocationsReferenceSymbolsAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Rename.SymbolicRenameLocations.FindLocationsInCurrentProcessAsync(ISymbol symbol, Solution solution, SymbolRenameOptions options, CodeCleanupOptionsProvider cleanupOptions, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteRenamerService.<>c__DisplayClass6_0.<<FindRenameLocationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)

```

**Comment by CyrusNajmabadi** [comment]
Closing out as we fixed up solution snapshots to ensure linked files all agree on document contents.
