### ISSUE TITLE
Quick Info tests fail when using new editor package versions

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#65840]
Found and disabled in https://github.com/dotnet/roslyn/pull/65795

```
at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 29
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<InvokeQuickInfoAsync>d__13.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicQuickInfo.<International>d__4.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicQuickInfo.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Note - these work fine in main.  Only in -vs-deps with new editor package versions do these fail.  Most likely related to the fact that the VS install on integration test machines is extremely old.  Hopefully can re-enable with https://github.com/dotnet/roslyn/pull/65839

**Comment by dibarbet** [comment]
Yes.  THis might be fixed after this PR goes in, but may not be fixed until we can upgrade to 17.5p2.  Will test after 
https://github.com/dotnet/roslyn/pull/65846
