### ISSUE TITLE
Running incorrect #load command crashes Visual Studio

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#6589]
Running
```
>#load "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.dll"
```

In the C# interactive window causes Visual Studio to crash with the following stack trace:

```
   "The given key was not present in the dictionary."
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key) in f:\dd\ndp\fxcore\Open\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableDictionary`2.cs:line 258
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.GetRemoveSetForLoadedTrees(ImmutableArray`1 loadDirectives, ImmutableDictionary`2 loadDirectiveMap, ImmutableDictionary`2 loadedSyntaxTreeMap, HashSet`1 removeSet) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 405
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.GetRemoveSet(SyntaxTree oldTree, Boolean includeLoadedTrees, ImmutableArray`1 syntaxTrees, ImmutableDictionary`2 syntaxTreeOrdinalMap, ImmutableDictionary`2 loadDirectiveMap, ImmutableDictionary`2 loadedSyntaxTreeMap, HashSet`1 removeSet, Int32& totalReferencedTreeCount, ImmutableArray`1& oldLoadDirectives) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 365
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 448
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 804
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2737
   at Microsoft.CodeAnalysis.Solution.<UpdateDocumentInCompilationAsync>d__115.MoveNext() in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.cs:line 1621
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 166
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<BuildDeclarationCompilationFromInProgressAsync>d__27.MoveNext() in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.CompilationTracker.cs:line 551"	string
```

Dump available at (ML File Share)\public\jmarolf\Dumps\LoadCrash.dmp

**Comment by amcasey** [comment]
FYI @KevinH-MS

**Comment by ManishJayaswal** [comment]
@KevinH-MS  - This is a VS crash so we should take this through shiproom - ideally at 1p tomorrow.

**Comment by KevinH-MS** [comment]
@jmarolf the dump isn't at the point of the Exception (it's in the Exception filter, so the locals aren't available).  Was there anything more to the repro that pasting the code and hitting {ENTER}?

(I haven't been able to repro yet)

**Comment by amcasey** [comment]
@KevinH-MS repros on my box (on stabilization).  Let me know if you need an input file.

**Comment by amcasey** [comment]
Seems like we just have to use `TryGetValue` instead of indexing.

**Comment by amcasey** [comment]
Incidentally, mine crashes before I submit.

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn/blob/5e676fdeb1b95b54aebf78ff489e50457ce30d6f/src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs#L386
https://github.com/dotnet/roslyn/blob/5e676fdeb1b95b54aebf78ff489e50457ce30d6f/src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs#L407
https://github.com/dotnet/roslyn/blob/5e676fdeb1b95b54aebf78ff489e50457ce30d6f/src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs#L591

**Comment by ManishJayaswal** [comment]
@KevinH-MS this met the bar in shiproom today. If the fix is not too risky then we would consider taking it.

**Comment by KevinH-MS** [comment]
The fix for the crash in this scenario is as simple as Andrew suggests, but while testing, I've found another subtle issue with rebuilding the ordinal map.  I hope to have a fix out for both later today or early tomorrow.
