### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65949]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemInvalidOperationException/10226739)._

---
[severity:It bothers me. A fix would be nice]
>System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.<>c__DisplayClass1_0.b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync()

---
#### Feedback Bot on 12/11/2022, 07:02 PM: 

(private comment, text removed)
#### Feedback Bot on 12/12/2022, 05:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of prism hits.
