### ISSUE TITLE
Assert fired at Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations..ctor

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65968]
Hit the below assert in the ServiceProcess while debugging locally built Roslyn bits (F5 in Roslyn.sln and open Roslyn.sln in the instance from RoslynDev hive). I don't have a concrete repro, just the assert stack.

https://github.com/dotnet/roslyn/blob/6392f2f2d3106ac250e7dcc3b9a54478330add09/src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs#L52

```
StreamJsonRpc.RemoteInvocationException: Assertion failed
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext() in C:\roslyn\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 192
RPC server exception:
System.InvalidOperationException: Assertion failed
      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in C:\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 27
      at System.Diagnostics.TraceInternal.Fail(String message)
      at System.Diagnostics.Debug.Assert(Boolean condition)
      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations..ctor(TypeSymbol defaultType, NullableAnnotation nullableAnnotation, Extensions extensions) in C:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeWithAnnotations.cs:line 52
      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.CreateNonLazyType(TypeSymbol typeSymbol, NullableAnnotation nullableAnnotation, ImmutableArray`1 customModifiers) in C:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeWithAnnotations.cs:line 167
      at Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.SetUnknownNullabilityForReferenceTypes() in C:\roslyn\src\Compilers\CSharp\Portable\Symbols\TypeWithAnnotations.cs:line 716
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.AddAllCandidates(Dictionary`2 candidates, HashSet`1 bounds, VarianceKind variance, ConversionsBase conversions) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 3113
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.Fix(CSharpCompilation compilation, ConversionsBase conversions, TypeParameterSymbol typeParameter, HashSet`1 exact, HashSet`1 lower, HashSet`1 upper, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 2680
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.Fix(Int32 iParam, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 2612
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.FixParameters(Func`3 predicate, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 878
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.FixNondependentParameters(CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 841
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.DoSecondPhase(Binder binder, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 750
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.InferTypeArgsSecondPhase(Binder binder, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 709
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.InferTypeArgs(Binder binder, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 562
      at Microsoft.CodeAnalysis.CSharp.MethodTypeInferrer.Infer(Binder binder, ConversionsBase conversions, ImmutableArray`1 methodTypeParameters, NamedTypeSymbol constructedContainingTypeOfMethod, ImmutableArray`1 formalParameterTypes, ImmutableArray`1 formalParameterRefKinds, ImmutableArray`1 arguments, CompoundUseSiteInfo`1& useSiteInfo, Extensions extensions) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\MethodTypeInference.cs:line 301
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.InferMethodTypeArguments(MethodSymbol method, ImmutableArray`1 originalTypeParameters, AnalyzedArguments arguments, EffectiveParameters originalEffectiveParameters, Boolean& hasTypeArgumentsInferredFromFunctionType, MemberAnalysisResult& error, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 3564
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArgumentsBuilder, AnalyzedArguments arguments, EffectiveParameters originalEffectiveParameters, EffectiveParameters constructedEffectiveParameters, ImmutableArray`1 argsToParamsMap, Boolean hasAnyRefOmittedArgument, Boolean inferWithDynamic, Boolean completeResults, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 3462
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsMemberApplicableInNormalForm[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, Boolean completeResults, CompoundUseSiteInfo`1& useSiteInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 3329
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.AddMemberToCandidateSet[TMember](TMember member, ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Dictionary`2 containingTypeMapOpt, Boolean inferWithDynamic, CompoundUseSiteInfo`1& useSiteInfo, Boolean allowUnexpandedForm) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 930
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[TMember](ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, BoundExpression receiver, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, RefKind returnRefKind, TypeSymbol returnType, Boolean allowRefOmittedArguments, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConventionInfo, CompoundUseSiteInfo`1& useSiteInfo, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 267
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodOrPropertyOverloadResolution[TMember](ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, BoundExpression receiver, AnalyzedArguments arguments, OverloadResolutionResult`1 result, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, CompoundUseSiteInfo`1& useSiteInfo, Boolean inferWithDynamic, Boolean allowUnexpandedForm, RefKind returnRefKind, TypeSymbol returnType, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConventionInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 177
      at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodInvocationOverloadResolution(ArrayBuilder`1 methods, ArrayBuilder`1 typeArguments, BoundExpression receiver, AnalyzedArguments arguments, OverloadResolutionResult`1 result, CompoundUseSiteInfo`1& useSiteInfo, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, Boolean allowUnexpandedForm, RefKind returnRefKind, TypeSymbol returnType, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConventionInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 133
      at Microsoft.CodeAnalysis.CSharp.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, CompoundUseSiteInfo`1& useSiteInfo, Boolean inferWithDynamic, Boolean allowUnexpandedForm, RefKind returnRefKind, TypeSymbol returnType, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConvention) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 8933
      at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal(BoundMethodGroup methodGroup, SyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, CompoundUseSiteInfo`1& useSiteInfo, Boolean inferWithDynamic, Boolean allowUnexpandedForm, RefKind returnRefKind, TypeSymbol returnType, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConvention) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 8818
      at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroup(BoundMethodGroup node, SyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, CompoundUseSiteInfo`1& useSiteInfo, Boolean inferWithDynamic, Boolean allowUnexpandedForm, RefKind returnRefKind, TypeSymbol returnType, Boolean isFunctionPointerResolution, CallingConventionInfo& callingConventionInfo) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 8764
      at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, BindingDiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm, Boolean& anyApplicableCandidates) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 578
      at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, BindingDiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 271
      at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 184
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 572
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionAllowArgList(ExpressionSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 535
      at Microsoft.CodeAnalysis.CSharp.Binder.BindValueAllowArgList(ExpressionSyntax node, BindingDiagnosticBag diagnostics, BindValueKind valueKind) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 420
      at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(BindingDiagnosticBag diagnostics, ExpressionSyntax argumentExpression, RefKind refKind, Boolean allowArglist) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 3061
      at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(BindingDiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2799
      at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, BindingDiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2751
      at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(BaseArgumentListSyntax argumentListOpt, BindingDiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 2704
      at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 183
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 572
      at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 517
      at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, BindingDiagnosticBag diagnostics, BindValueKind valueKind) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 235
      at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(ReturnStatementSyntax syntax, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2911
      at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 100
      at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1895
      at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1883
      at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 63
      at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3951
      at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, BindingDiagnosticBag diagnostics) in C:\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3550
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel) in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1787
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1042
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 530
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 424
      at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 139
      at System.Threading.Tasks.Task.Execute()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 335
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 165
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(BindingDiagnosticBag diagnostics, Boolean doLowering, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2775
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2746
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2657
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2649
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) in C:\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2643
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsWithoutStateTrackingAsync>d__49.MoveNext() in C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\CompilationWithAnalyzers.cs:line 447
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultWithoutStateTrackingAsync>d__46.MoveNext() in C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\CompilationWithAnalyzers.cs:line 371
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultAsync>d__39.MoveNext() in C:\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\CompilationWithAnalyzers.cs:line 296
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__8.MoveNext() in C:\roslyn\src\Workspaces\Core\Portable\Diagnostics\Extensions.cs:line 328
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__7.MoveNext() in C:\roslyn\src\Workspaces\Core\Portable\Diagnostics\Extensions.cs:line 315
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<AnalyzeAsync>d__12.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Services\DiagnosticAnalyzer\DiagnosticComputer.cs:line 128
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<GetDiagnosticsAsync>d__11.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Services\DiagnosticAnalyzer\DiagnosticComputer.cs:line 110
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Services\DiagnosticAnalyzer\RemoteDiagnosticAnalyzerService.cs:line 78
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 179
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__7`1.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 119
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__7`1.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 130
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 92
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<CalculateDiagnosticsAsync>d__4.MoveNext() in C:\roslyn\src\Workspaces\Remote\ServiceHub\Services\DiagnosticAnalyzer\RemoteDiagnosticAnalyzerService.cs:line 63
```

**Comment by jaredpar** [comment]
@jcouv  PTAL
