### ISSUE TITLE
Flaky tests - Service hub cancellation

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#65999]
There is no specific test failure - seems to be hitting classification, navbar, find refs when using the OOP test host.

```
[xUnit.net 00:00:20.17]     Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.CSharpNavigationBarTests.TestProperties(host: OutOfProcess) [FAIL]
  Failed Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.CSharpNavigationBarTests.TestProperties(host: OutOfProcess) [60 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteHostClient.<TryInvokeAsync>d__17`2.MoveNext() in /_/src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.NavigationBar.AbstractNavigationBarItemService.<GetItemsAsync>d__1.MoveNext() in /_/src/Features/Core/Portable/NavigationBar/AbstractNavigationBarItemService.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Extensibility.NavigationBar.AbstractEditorNavigationBarItemService.<GetItemsAsync>d__3.MoveNext() in /_/src/EditorFeatures/Core/Extensibility/NavigationBar/AbstractEditorNavigationBarItemService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.TestHelpers.VB$StateMachine_4_AssertItemsAreAsync.MoveNext() in /_/src/EditorFeatures/Test2/NavigationBar/TestHelpers.vb:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.CSharpNavigationBarTests.VB$StateMachine_13_TestProperties.MoveNext() in /_/src/EditorFeatures/Test2/NavigationBar/CSharpNavigationBarTests.vb:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Examples 
https://dev.azure.com/dnceng-public/public/_build/results?buildId=111503&view=ms.vss-test-web.build-test-results-tab&runId=2371314&resultId=224154&paneView=debug

https://dev.azure.com/dnceng-public/public/_build/results?buildId=111216&view=results

https://dev.azure.com/dnceng-public/public/_build/results?buildId=110286&view=ms.vss-test-web.build-test-results-tab&runId=2348472&resultId=224571&paneView=debug

**Comment by CyrusNajmabadi** [comment]
Closing out as we fixed the accidental captur eof a canceled token.
