### ISSUE TITLE
Crash on clearing Interactive Window while outputting

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6600]
I evaluated a loop that basically dumped file contents to stdout and hit the Clear button when it was part way done.

```InvalidOperationException: Master edit already in progress```

```
   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.PerformMasterEdit(ITextBuffer buffer, ISubordinateTextEdit xedit, EditOptions options, Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.TextBuffer.BasicEdit.PerformApply()
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferEdit.Apply()
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.InsertOutput(IEnumerable`1 output, Int32 position)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.AppendOutput(IEnumerable`1 output)
   at Microsoft.VisualStudio.InteractiveWindow.OutputBuffer.Flush()
   at Microsoft.VisualStudio.InteractiveWindow.OutputBuffer.Write(String text)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.Write(String text)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.<>c__DisplayClass79_0.<Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow.Write>b__0(UIThreadOnly uiOnly)
```

**Comment by amcasey** [comment]
We're on the main thread, so I'm not sure who we're racing with.  Maybe something is asynchronous and yielded before it finished its edit?

**Comment by amcasey** [comment]
I suspect we're hitting a boundary condition where we run out of resources and stop keeping track of things properly.  As I've been testing this, I've hit a lot of OOMs, sometimes followed by ArgumentExceptions about spans being from the wrong snapshot.

**Comment by amcasey** [comment]
I have to admit that I find it curious that the window doesn't OOM *until* it is cleared.  I would have thought that the problem was too much text, but maybe it has to do with the way we're clearing the text?  It's all in one buffer, AFAIK, so it shouldn't be a giant buffer graph operation.

**Comment by amcasey** [comment]
Here's the OOM stack:
```
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.ReferenceChangeString.get_Text()
   at Microsoft.VisualStudio.Text.Implementation.TextChange.get_OldText()
   at Microsoft.VisualStudio.Text.Implementation.NormalizedTextChangeCollection.Denormalize(INormalizedTextChangeCollection normalizedChanges, List`1 denormChangesWithSentinel)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.PreparePendingChanges()
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.ComputeProjectedChanges(SortedDictionary`2 spanPreAdjustments, SortedDictionary`2 spanPostAdjustments)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.InterpretSourceChanges(EditOptions options, Object editTag)
   at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.PropagateSourceChanges(EditOptions options, Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.BufferGroup.PerformMasterEdit(ITextBuffer buffer, ISubordinateTextEdit xedit, EditOptions options, Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.TextBuffer.BasicEdit.PerformApply()
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferEdit.Apply()
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.ClearView() in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\Editor\InteractiveWindow.UIThreadOnly.cs:line 291
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.<>c.<Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowOperations.ClearView>b__47_0(UIThreadOnly uiOnly) in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\Editor\InteractiveWindow.cs:line 256
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThread(Action`1 action) in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\Editor\InteractiveWindow.cs:line 524
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowOperations.ClearView() in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\Editor\InteractiveWindow.cs:line 256
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowCommandFilter.PreLanguageCommandFilterExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\VisualStudio\VsInteractiveWindowCommandFilter.cs:line 414
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowCommandFilter.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in c:\Enlistments\roslyn-internal_master\Open\src\InteractiveWindow\VisualStudio\VsInteractiveWindowCommandFilter.cs:line 154
```

**Comment by amcasey** [comment]
It seems strange to me that deletion would have to realize the "OldText" as a string but insertion would not.

**Comment by amcasey** [comment]
Looks like it's the `SuppressPromptInjectionTag`, which I believe is unnecessary.  I'll confirm.

**Comment by amcasey** [comment]
To be re-opened if we observe lingering issues post-#6870.
