### ISSUE TITLE
ArgumentException from RemoteDiagnosticAnalyzerService

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#66138]
Hit the following error (gold bar) after opening roslyn.sln from release/dev17.5 branch in VS 17.5.0 Preview 3.0 [33226.46.main]

```
StreamJsonRpc.RemoteInvocationException: An item with the same key has already been added. Key: Microsoft.CodeAnalysis.Diagnostics.CSharp.CSharpCompilerDiagnosticAnalyzer, Microsoft.CodeAnalysis.CSharp, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.ArgumentException: An item with the same key has already been added. Key: Microsoft.CodeAnalysis.Diagnostics.CSharp.CSharpCompilerDiagnosticAnalyzer, Microsoft.CodeAnalysis.CSharp, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
      at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
      at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.PerformanceQueue.AnalyzerNumberAssigner.GetUniqueNumber(String analyzerName)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.PerformanceQueue.Snapshot.<>c.<Convert>b__7_0(ValueTuple`2 kv)
      at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
      at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
      at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
      at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, IComparer`1 comparer)
      at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.PerformanceQueue.Snapshot.Reset(Dictionary`2 map, IEnumerable`1 rawData, Int32 fileCount)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.PerformanceQueue.Add(IEnumerable`1 rawData, Int32 unitCount)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.PerformanceTrackerService.AddSnapshot(IEnumerable`1 snapshot, Int32 unitCount, Boolean forSpanAnalysis)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)
```

FYI @mavasani

**Comment by genlu** [comment]
fixed by https://github.com/dotnet/roslyn/pull/66230
