### ISSUE TITLE
AspNetCore.Mvc.Consumes attribute triggers CA1825

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/roslyn#66150]
**Version Used**: 

C# 6, VS 17.5.0 Preview 2.0

**Steps to Reproduce**:

Strangely, when I use `ConsumesAttribute` in my code, it generates a [CA1825: Avoid zero-length array allocations](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825) warning:

```c#
using Microsoft.AspNetCore.Mvc;

public partial class ExampleController
{
    // CA1825: Avoid zero-length array allocations
    [Consumes("multipart/form-data")]
    public async Task<IActionResult> ExampleAsync()
    {
    }
}
```

If I activate VS' "Show potential fixes" option, `AvoidZeroLengthArrayAllocationsFixer` crashes with this stack trace:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.IArrayTypeSymbol'.
   at Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.GetArrayElementType(SyntaxNode arrayCreationExpression,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.ConvertToArrayEmptyAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.<>c__DisplayClass4_0.<RegisterCodeFixesAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Diagnostic Id**:

CA1825

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning

**Comment by Bosch-Eli-Black** [comment]
Note to self: I observed this in `CommandController.cs`

**Comment by Youssef1313** [comment]
This doesn't belong to dotnet/roslyn, and it was fixed.

**Comment by Bosch-Eli-Black** [comment]
@Youssef1313 Ah, thanks! 🙂 I always forgot about that repo, haha.
