### ISSUE TITLE
Attribute argument of a type containing function pointer fails with `TypeLoadException` during reflection

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#66187]
**Version Used**: 34180c3974c46fe354740d7f5fddd17244474612 (2022-12-20)

**Steps to Reproduce**:

```cs
[Theory, CombinatorialData, WorkItem(65594, "https://github.com/dotnet/roslyn/issues/65594")]
public void Attribute_TypedDefault_Enum([CombinatorialValues("class", "struct")] string kind)
{
    var source = $$"""
        using System;
        using System.Linq;
        
        var attr = typeof(C).CustomAttributes.Single(d => d.AttributeType == typeof(A));
        var arg = attr.ConstructorArguments.Single();
        Console.WriteLine((int)arg.Value == 0);
        
        class A : Attribute
        {
            public A(B<delegate*<void>[]>.E e) { }
        }

        {{kind}} B<T>
        {
            public enum E { }
        }

        [A(default)]
        class C { }
        """;

    var verifier = CompileAndVerify(source, expectedOutput: "True", symbolValidator: static module =>
    {
        var c = module.GlobalNamespace.GetTypeMember("C");
        var attr = c.GetAttributes().Single(d => d.AttributeClass?.Name == "A");
        Assert.Empty(attr.ConstructorArguments);
    });
    verifier.VerifyDiagnostics();
}
```

**Expected Behavior**: The test succeeds.

**Actual Behavior**: At runtime, it fails with:

```
System.TypeLoadException: Could not load type '(fnptr)' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(String name, RuntimeModule scope)
   at System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)
   at System.Reflection.CustomAttributeTypedArgument..ctor(RuntimeModule scope, CustomAttributeEncodedArgument encodedArg)
   at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
   at Program.<Main>$(String[] args)
```

Changing `A`'s constructor to take parameter of a different type, e.g., `B<int>.E` instead of `B<delegate*<void>[]>.E`, makes the test pass. (Although I wouldn't expect the symbol validator to discover empty attribute constructor arguments, but that's probably a different issue.)

**Comment by jcouv** [comment]
Assigned to @jjonescz for initial investigation (confirm whether this is a runtime/reflection issue). Thanks

**Comment by jjonescz** [comment]
@jcouv Yes, this seems to be runtime issue. The emitted metadata look correct. Here is an IL repro:

```cs
[Fact]
public void Issue66187()
{
    var ilSource = """
        .class public auto ansi beforefieldinit A
            extends [mscorlib]System.Attribute
        {
            .method public hidebysig specialname rtspecialname 
                instance void .ctor (
                    valuetype B`1/E<method void *()[]> e
                ) cil managed 
            {
                .maxstack 8
                ret
            }
        }

        .class public auto ansi beforefieldinit B`1<T>
            extends System.Object
        {
            .class nested public auto ansi sealed E<T>
                extends [mscorlib]System.Enum
            {
                .param type T
                .field public specialname rtspecialname int32 value__
            }
        }

        .class public auto ansi beforefieldinit C
            extends System.Object
        {
            .custom instance void A::.ctor(valuetype B`1/E<method void *()[]>) = (
                01 00 00 00 00 00 00 00
            )
        }
        """;
    var source = """
        using System;
        using System.Linq;

        var attr = typeof(C).CustomAttributes.Single(d => d.AttributeType == typeof(A));
        var arg = attr.ConstructorArguments.Single();
        Console.WriteLine((int?)arg.Value == 0);
        """;
    var comp = CreateCompilationWithIL(source, ilSource).VerifyDiagnostics();
    CompileAndVerify(comp, expectedOutput: "True");
}
```

Fails with:

```
System.TypeLoadException : Could not load type '(fnptr)' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Stack Trace:
     at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(String name, RuntimeModule scope)
     at System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)
     at System.Reflection.CustomAttributeTypedArgument..ctor(RuntimeModule scope, CustomAttributeEncodedArgument encodedArg)
     at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
  (4,0): at Program.<Main>$(String[] args)
```
