### ISSUE TITLE
Cannot activate language client Roslyn Language Server Client in Visual Studio

### ISSUE THREAD

**Issue by sanmuru** [dotnet/roslyn#66262]
There was no such bug in Dec 7th last year.

**Version Used**: 
Roslyn: latest commit
Visual Studio: Professional 2022 Preview 17.5.0 Preview 1.0

**Steps to Reproduce**:

1. Follow the [instructions](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md#trying-your-changes-in-visual-studio) and then run command `.\Build.cmd -Configuration Release -deployExtensions -launch`
2. Startup Visual Studio `RoslynDev` hive with command `devenv /rootSuffix RoslynDev`
3. Create a new C# Project.
4. A yellow bar at the top of the VS window appears and says `An exception of type FileLoadException has been encountered. This may be caused by an extension.`
5. At bottom-left corner, **Background tasks** shows task failed.

**Expected Behavior**:
All tasks success.

**Actual Behavior**:
There are many features not working.
Output from *Language Client activation failures*:
```
Task Failed - Activating language client Roslyn Language Server Client: Roslyn Language Server Client failed to initialize. Status = Activating language client. Exception = System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.RpcContracts, Version=17.5.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.VisualStudio.RpcContracts, Version=17.5.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.VisualStudioLogHubLoggerFactory.CreateLoggerAsync(String serverTypeName, JsonRpc jsonRpc, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.LanguageClient.AbstractInProcLanguageClient.<CreateAsync>d__39`1.MoveNext() in E:\LFF\Sandbox\GitHub\dotnet\roslyn\src\EditorFeatures\Core\LanguageServer\AbstractInProcLanguageClient.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.LanguageClient.AbstractInProcLanguageClient.<ActivateAsync>d__35.MoveNext() in E:\LFF\Sandbox\GitHub\dotnet\roslyn\src\EditorFeatures\Core\LanguageServer\AbstractInProcLanguageClient.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<TrackTaskAsync>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__128.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Does this repro for Preview2?

**Comment by sanmuru** [comment]
> Does this repro for Preview2?

Preview 2.0 work fine. I did see this update suggestion but I ignored it.
Thanks for your help!

**Comment by GearTheWorld** [comment]
VS 2026 right now !

<img width="1258" height="665" alt="Image" src="https://github.com/user-attachments/assets/d9d1aeb3-d3bb-4ad6-bc69-5bdba60ad7e9" />
