### ISSUE TITLE
Can't run "Declare Public Members" codefix provider for newly added Syntax types.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66414]
This was discovered in the Collection-Literals work here. 

Trying to add new Syntax types to the PublicAPI file produces thsi crash:

```
System.NotImplementedException : The method or operation is not implemented.
   at Microsoft.CodeAnalysis.SolutionState.GeneratedFileReplacingCompilationTracker.Fork(ProjectState newProject,CompilationAndGeneratorDriverTranslationAction translate)
   at Microsoft.CodeAnalysis.SolutionState.ForkProject(ProjectState newProjectState,CompilationAndGeneratorDriverTranslationAction translate,ProjectDependencyGraph newDependencyGraph,ImmutableDictionary`2 newFilePathToDocumentIdsMap,Boolean forkTracker)
   at Microsoft.CodeAnalysis.SolutionState.UpdateAdditionalDocumentState(AdditionalDocumentState newDocument,Boolean contentChanged)
   at Microsoft.CodeAnalysis.SolutionState.WithAdditionalDocumentText(DocumentId documentId,SourceText text,PreservationMode mode)
   at Microsoft.CodeAnalysis.Solution.WithAdditionalDocumentText(DocumentId documentId,SourceText text,PreservationMode mode)
   at async Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiFix.GetFixAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski This is def a PITA as writing out all these APIs by hand is enormously painful :'(

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Will try to get a fix in ASAP.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits.

**Comment by jasonmalinowski** [comment]
This was fixed by https://github.com/dotnet/roslyn/pull/75180.
