### ISSUE TITLE
ChangeSignatureCodeRefactoringProvider NullReferenceException

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/roslyn#66694]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

**Steps to Reproduce**:
Was commenting out and renaming some code that I copy/pasted from another project.

**Expected Behavior**:
No crash of ChangeSignatureCodeRefactoringProvider.

**Actual Behavior**:
Yellow bar showing `ChangeSignatureCodeRefactoringProvider encountered an error and has been disabled`.
Stack trace:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetParameterIndexFromInvocationArgument(SyntaxNode argument,Document document,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.ChangeSignature.CSharpChangeSignatureService.GetInvocationSymbolAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/65307
