### ISSUE TITLE
Visual studio crashes while previewing Inline Temp refactoring.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#667]
1. With latest roslyn bits installed, open C# console app.
2. add the following code without the `$$` characters:
~~~
        static int GetInt(int n)
        {
            int $$n = 1;
            return n;
        }
~~~
3.  Place caret at `$$`
4. Ctrl + . and bring up InlineTemp refactoring.
5. It automatically displays a diff preview, which then crashes VS.

~~~
{"Object reference not set to an instance of an object."}

      at Microsoft.CodeAnalysis.Editor.Shared.Preview.PreviewSolutionCrawlerRegistrationService.<Register>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
~~~

I believe something is wrong at `foreach (var documentId in workspace.GetOpenDocumentIds())` inside `Register()`

If the repro is not as simple as I believe it is, please ping me and I can help in arriving at a reliable repro. Saved a dump at %internaldumpsshare%\667

**Comment by srivatsn** [comment]
@heejaechang is this from your recent change to add the progress mechanism?

**Comment by heejaechang** [comment]
@srivatsn not sure, but preview should have nothing to do with it.

**Comment by balajikris** [comment]
@heejaechang @srivatsn I can no longer repro this with latest code.. I'm okay if you wish to close it, since we don't have a repro or a dump..

**Comment by srivatsn** [comment]
Okay I'll close it and if you see it happening please reopen

**Comment by balajikris** [comment]
I hit this again and have now captured a dump. Note that this happens on the Main hive and not so much in the Developmental hives, which puzzles me, because the bits on my Main hive are as latest as today's.

**Comment by balajikris** [comment]
@heejaechang came by and we found that I had diagnostic provider disabled in my Main hive, something i did much earlier to investigate some other bug :disappointed: Everything looks good here. Thanks and apologies.
