### ISSUE TITLE
CharacterInfo Issue

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6683]
I'm current working on a pull request for `CharacterInfo.vb.` which uses Char literals for fullwidth characters, and I've encounteres some issues.
```vb.net
Friend Const LEFT_SINGLE_QUOTATION_MARK = "‘"c 'ChrW(&H2018)        REM  ‘ / "‘"c / ChrW(&H2018)
```
I get a test failure related to the C# expression evaluator (?). 

```xml
-<test time="0.0539852" name="Microsoft.CodeAnalysis.CSharp.UnitTests.DynamicTests.LocalsWithLongAndShortNames" result="Fail" method="LocalsWithLongAndShortNames" type="Microsoft.CodeAnalysis.CSharp.UnitTests.DynamicTests">
-<failure exception-type="System.BadImageFormatException">
-<message>
-<![CDATA[System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)]]>
</message>
-<stack-trace>
-<![CDATA[   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.ThrowExceptionForHR(Int32 hr) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\PdbUtilities\Shared\SymUnmanagedReaderExtensions.cs:line 489
   at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetItems[TEntity,TItem](TEntity entity, ItemsGetter`2 getter) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\PdbUtilities\Shared\SymUnmanagedReaderExtensions.cs:line 106
   at Microsoft.DiaSymReader.SymUnmanagedReaderExtensions.GetSignature(ISymUnmanagedConstant constant) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\PdbUtilities\Shared\SymUnmanagedReaderExtensions.cs:line 457
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.GetConstants(ArrayBuilder`1 builder, MethodSymbol method, ArrayBuilder`1 scopes, MetadataDecoder metadataDecoder, ImmutableDictionary`2 dynamicLocalConstantMap, SourceAssemblySymbol containingAssembly) in H:\Source\Repos\roslyn-AdamSpeight2008\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\EvaluationContext.cs:line 517
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpCompilation compilation, Object symReader, Guid moduleVersionId, Int32 methodToken, Int32 methodVersion, Int32 ilOffset, Int32 localSignatureToken) in H:\Source\Repos\roslyn-AdamSpeight2008\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\EvaluationContext.cs:line 223
   at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CreateMethodContext(CSharpMetadataContext previous, ImmutableArray`1 metadataBlocks, Object symReader, Guid moduleVersionId, Int32 methodToken, Int32 methodVersion, UInt32 ilOffset, Int32 localSignatureToken) in H:\Source\Repos\roslyn-AdamSpeight2008\src\ExpressionEvaluator\CSharp\Source\ExpressionCompiler\EvaluationContext.cs:line 147
   at Microsoft.CodeAnalysis.CSharp.UnitTests.ExpressionCompilerTestBase.CreateMethodContext(RuntimeInstance runtime, String methodName, Int32 atLineNumber) in H:\Source\Repos\roslyn-AdamSpeight2008\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\ExpressionCompilerTestBase.cs:line 132
   at Microsoft.CodeAnalysis.CSharp.UnitTests.DynamicTests.LocalsWithLongAndShortNames() in H:\Source\Repos\roslyn-AdamSpeight2008\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\DynamicTests.cs:line 520]]>
</stack-trace>
</failure>
</test>
```
----------------

```vb.net
Friend Const LEFT_DOUBLE_QUOTATION_MARK = "““"c 'ChrW(&H201C)        REM   ““ / "““"c / ChrW(&H201C)
```
I get the following test failure
```xml
-<test time="0.0064839" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax.ScannerXml_SmartStrings" result="Fail" method="ScannerXml_SmartStrings" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax">
-<failure exception-type="Xunit.Sdk.EqualException">
-<message>
-<![CDATA[Assert.Equal() Failure\r\nExpected: DoubleQuoteToken\r\nActual:   XmlNameToken]]>
</message>
-<stack-trace>
-<![CDATA[   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax.ScannerXml_SmartStrings() in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Scanner\XmlScannerTests.vb:line 307]]>
</stack-trace>
</failure>
</test>
```

------------------------

```vb.net
Friend Const RIGHT_DOUBLE_QUOTATION_MARK = "””"c 'ChrW(&H201D)       REM   ”” / "””"c / ChrW(&H201D) 
```

I get the following two test failures.
```xml
-<test time="0.0332933" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests.Bug17703" result="Fail" method="Bug17703" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests">
-<failure exception-type="Xunit.Sdk.TrueException">
-<message>
-<![CDATA[\r\nExpected:\r\n    Diagnostic(ERRID.ERR_MissingXmlEndTag),\r\n    Diagnostic(ERRID.ERR_ExpectedXmlName),\r\n    Diagnostic(ERRID.ERR_ExpectedXmlName),\r\n    Diagnostic(ERRID.ERR_ExpectedEQ),\r\n    Diagnostic(ERRID.ERR_ExpectedQuote),\r\n    Diagnostic(ERRID.ERR_ExpectedLT),\r\n    Diagnostic(ERRID.ERR_ExpectedGreater)\r\nActual:\r\n    Diagnostic(ERRID.ERR_MissingXmlEndTag, @"<\n”'\n\n        ").WithLocation(2, 9),\r\n    Diagnostic(ERRID.ERR_IllegalXmlWhiteSpace, @"\n").WithLocation(2, 10),\r\n    Diagnostic(ERRID.ERR_IllegalXmlStartNameChar, "”").WithArguments("”", "&H201D").WithLocation(3, 1),\r\n    Diagnostic(ERRID.ERR_ExpectedXmlName, "").WithLocation(3, 2),\r\n    Diagnostic(ERRID.ERR_ExpectedEQ, "").WithLocation(3, 2),\r\n    Diagnostic(ERRID.ERR_ExpectedSQuote, "").WithLocation(5, 9),\r\n    Diagnostic(ERRID.ERR_ExpectedLT, "").WithLocation(5, 9),\r\n    Diagnostic(ERRID.ERR_ExpectedGreater, "").WithLocation(5, 9)\r\nDiff:\r\n++>     Diagnostic(ERRID.ERR_MissingXmlEndTag, @"<\r\n++> ”'\r\n++>         ").WithLocation(2, 9),\r\n++>     Diagnostic(ERRID.ERR_IllegalXmlWhiteSpace, @"\r\n++> ").WithLocation(2, 10),\r\n++>     Diagnostic(ERRID.ERR_IllegalXmlStartNameChar, "”").WithArguments("”", "&H201D").WithLocation(3, 1),\r\n++>     Diagnostic(ERRID.ERR_ExpectedXmlName, "").WithLocation(3, 2),\r\n++>     Diagnostic(ERRID.ERR_ExpectedEQ, "").WithLocation(3, 2),\r\n++>     Diagnostic(ERRID.ERR_ExpectedSQuote, "").WithLocation(5, 9),\r\n++>     Diagnostic(ERRID.ERR_ExpectedLT, "").WithLocation(5, 9),\r\n++>     Diagnostic(ERRID.ERR_ExpectedGreater, "").WithLocation(5, 9)\r\n-->     Diagnostic(ERRID.ERR_MissingXmlEndTag),\r\n-->     Diagnostic(ERRID.ERR_ExpectedXmlName),\r\n-->     Diagnostic(ERRID.ERR_ExpectedXmlName),\r\n-->     Diagnostic(ERRID.ERR_ExpectedEQ),\r\n-->     Diagnostic(ERRID.ERR_ExpectedQuote),\r\n-->     Diagnostic(ERRID.ERR_ExpectedLT),\r\n-->     Diagnostic(ERRID.ERR_ExpectedGreater)\r\nExpected: True\r\nActual:   False]]>
</message>
-<stack-trace>
-<![CDATA[   at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs:line 84
   at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyErrorCodes(IEnumerable`1 actual, DiagnosticDescription[] expected) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Test\Utilities\Shared\Diagnostics\DiagnosticExtensions.cs:line 31
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ParserTestUtilities.ParseAndVerify(String source, VisualBasicParseOptions options, DiagnosticDescription[] expectedDiagnostics, Boolean errorCodesOnly) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\VisualBasic\ParserTestUtilities.vb:line 85
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ParserTestUtilities.ParseAndVerify(String source, VisualBasicParseOptions options, XElement expectedErrors) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\VisualBasic\ParserTestUtilities.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ParserTestUtilities.ParseAndVerify(String source, XElement expectedErrors) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\VisualBasic\ParserTestUtilities.vb:line 45
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ParserTestUtilities.ParseAndVerify(XCData code, XElement expectedErrors) in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\Test\Utilities\VisualBasic\ParserTestUtilities.vb:line 18
   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.ScannerTests.Bug17703() in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Scanner\ScannerTests.vb:line 1152]]>
</stack-trace>
</failure>
</test>
```
```xml
-<test time="0.0039807" name="Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax.ScannerXml_SmartStrings" result="Fail" method="ScannerXml_SmartStrings" type="Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax">
-<failure exception-type="Xunit.Sdk.EqualException">
-<message>
-<![CDATA[Assert.Equal() Failure\r\n                   ↓ (pos 9)\r\nExpected: some text\r\nActual:   some text”\r\n                   ↑ (pos 9)]]>
</message>
-<stack-trace>
-<![CDATA[   at Microsoft.CodeAnalysis.VisualBasic.UnitTests.XmlInternalSyntax.ScannerXml_SmartStrings() in H:\Source\Repos\roslyn-AdamSpeight2008\src\Compilers\VisualBasic\Test\Syntax\Scanner\XmlScannerTests.vb:line 311]]>
</stack-trace>
</failure>
</test>
```

**Comment by gafter** [comment]
It is not important to us that you make this change, so it would not make sense for us to devote much time to diagnosing it.

Please let us know what the root of the problem is in case it turns out to be a bug that we need to fix.

**Comment by AdamSpeight2008** [comment]
@gafter Do C# and VB use the same `CharacterInfo`? Or is one for each language. ais the first issue affected CSharp. I think the problem lies in the double char literal scanner/parser code.
I'll have do bit research on what the specification says about it.

**Comment by AdamSpeight2008** [comment]
@gafter 
The test [Scanner_CharLiteralToken](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/VisualBasic/Test/Syntax/Scanner/ScannerTests.vb#L596) in ScannerTests, does not covers all of the possible variants, it just assumes `"` is the only valid character for `DoubleQuoteCharacter` when the specification define two additional alternatives.
```
DoubleQuoteCharacte ::=   "
                        |  < Unicode left double quote character (0x201C) >
                        |  < Unicode right double quote character (0x201D) >

StringCharacter ::= < Character except for DoubleQuoteCharacter >
                    | DoubleQuoteChar DoubleQuoteCharacter

StringLiteral ::= DoubleQuoteCharacter StringCharacter DoubleQuoteCharacter

CharacterLiteral ::= DoubleQuoteChar StringCharacter DoubleQuoteCharacter C
```

If we take the second alternative of `StringCharacter::= ` there is 9 different and valid combinations.
. 
For `CharacterLiteral` there are 81 possible ways for saying double quote character and 9 different and valid ways of representing all the others. 
According to the specification all perfectly valid;

**Comment by gafter** [comment]
According to the VB language spec:

> 2.4.4 String Literals
A string literal is a sequence of zero or more Unicode characters beginning and ending with an ASCII double-quote character, a Unicode left double-quote character, or a Unicode right double-quote character. Within a string, **a sequence of two double-quote characters is an escape sequence representing a double quote in the string**. A string constant is of the String type.

The replacement does not replace a pair of double quote characters *with the same unicode character* in case they happen to be the same. It replaces them with the ASCII double-quote.

There is no bug.
