### ISSUE TITLE
Crash in AnalzyerDriver.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66878]
Was just editing in Roslyn on today's intpreview builds and got this:

```
StreamJsonRpc.RemoteInvocationException: Assertion failed
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 192
RPC server exception:
System.InvalidOperationException: Assertion failed
      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 27
      at System.Diagnostics.TraceInternal.Fail(String message)
      at System.Diagnostics.Debug.Assert(Boolean condition)
      at Microsoft.CodeAnalysis.Diagnostics.AnalysisState.PerAnalyzerState.TryStartSyntaxAnalysis(SourceOrAdditionalFile tree, AnalyzerStateData& state) in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisState.PerAnalyzerState.cs:line 469
      at Microsoft.CodeAnalysis.Diagnostics.AnalysisState.TryStartSyntaxAnalysis(SourceOrAdditionalFile file, DiagnosticAnalyzer analyzer, AnalyzerStateData& state) in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisState.cs:line 782
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.TryStartSyntaxAnalysis(SourceOrAdditionalFile file, DiagnosticAnalyzer analyzer, AnalysisScope analysisScope, AnalysisState analysisState, AnalyzerStateData& analyzerState) in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1952
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.TryExecuteSyntaxTreeActions(ImmutableArray`1 syntaxTreeActions, DiagnosticAnalyzer analyzer, SourceOrAdditionalFile file, AnalysisScope analysisScope, AnalysisState analysisState, Boolean isGeneratedCode) in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 779
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecuteSyntaxTreeActions(AnalysisScope analysisScope, AnalysisState analysisState, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 763
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass132_0.<ProcessCompilationEventsAsync>b__0() in C:\github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1475
      at System.Threading.Tasks.Task.Execute()
   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by CyrusNajmabadi** [comment]
@mavasani did your recent optimization change go in?

**Comment by mavasani** [comment]
Code removed with https://github.com/dotnet/roslyn/pull/66750
