### ISSUE TITLE
LSIF generator fails to start because it cannot find the .NET SDK - Near term fix

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#67383]
Various repos have started failing to generate LSIF with the following message:

```
Error: Unhandled exception: System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
Error:    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
Error:    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
Error:    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
Error:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
Error:    at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
Error:    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
Error:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
Error:    at Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Program.LocateAndRegisterMSBuild(TextWriter logFile, DirectoryInfo workingDirectory)
Error:    at Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Program.GenerateAsync(FileInfo solution, FileInfo project, FileInfo compilerInvocation, FileInfo binLog, String output, LsifFormat outputFormat, String log)
Error: Unhandled exception: System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
Error:    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
Error:    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
Error:    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
Error:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
Error:    at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
Error:    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
Error:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
Error:    at Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Program.LocateAndRegisterMSBuild(TextWriter logFile, DirectoryInfo workingDirectory)
Error:    at Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Program.GenerateAsync(FileInfo solution, FileInfo project, FileInfo compilerInvocation, FileInfo binLog, String output, LsifFormat outputFormat, String log)
Error:    at Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.Program.GenerateAsync(FileInfo solution, FileInfo project, FileInfo compilerInvocation, FileInfo b
```

This work item tracks finding a _near term_ solution to the problem to immediately unblock generation of the affected repos.

Seems like this issue is related to some combination of:

- Recent `MSBuildLocator` changes that change the specific behaviors around environment variables used to locate MSBuild.
- Repos updating to new 7.X versions of the .NET SDK.

Affected repos include VS-Platform and CPS. [Sample build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7493301&view=results)

**Comment by gundermanc** [comment]
Should go to area-IDE. @jasonmalinowski FYI, this is probably our highest priority immediate ask. 

**cc:** @NTaylorMullen .

**Comment by jasonmalinowski** [comment]
@gundermanc Not saying we don't have some general work to do here, but can we close this specific bug? I'm not sure if there's anything valuable here anymore?

**Comment by gundermanc** [comment]
> @gundermanc Not saying we don't have some general work to do here, but can we close this specific bug? I'm not sure if there's anything valuable here anymore?

Yeah I think we have worked around this for now. I think some of the other items are still relevant but feel free to close them while we work through the investigation our side as to what 'self-contained' means unless you have things you want to start working on asynchronously (e.g.: requirements declarations).
