### ISSUE TITLE
Source Generator files are being generated, are valid, can be navigated to but are marked as "not found" by the IDE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67573]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Source-Generator-files-are-being-generat/10312555)._

---
\[severity:It’s more difficult to complete my work\] \[regression\] \[worked-in:17.5\]  
For our MongoDB entities we generate model wrapper classes and interfaces in order to use them a bit more conveniently (like lazy resolving of referenced entities). It work’s like a charm and the source generator works good in theory. But it looks like Visual Studio has serious issues handling source generators, especially this one. The other one we’re using (for ResponseCommand classes seen in the return values in the screenshot) always seems to work.

So issues where always there but as of lately (possibly since the 17.5 update) it’s become worse. It runs the generator, all files are present (can be seen in the Analyzers > Generator > Files node in the explorer), are valid and fine and even can be navigated to. But still the IDE thinks they’re missing and says that the namespace does not exist. But IntelliSense recommends the namespace, so it can detect it.

The solution builds fine and the app runs, but the errors are highlighted everywhere which makes working a big pain:

![MicrosoftTeams-image.png](https://aka.ms/dc/image?name=Bb691934423fe477fa43740586fb66348638145577040023878_MicrosoftTeams-image.png&tid=b691934423fe477fa43740586fb66348638145577040023878)

It seems like after multiple solution cleans, rebuilding the source generators, multiple VS restarts it randomly starts working again. It’s not really deterministic when it fails but it does often. I guess it might correlate with branch checkouts in git which might be a source of throwing VS off.

**EDIT:** It happened again, when I navigate to the file, two bars pop up with errors. One "Feature 'Fully qualify' is currently unavailable due to an internal error" and another feature (the bar disappeared) with this stack trace (both identical):

```
StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.d__20`1.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId)
      at Microsoft.CodeAnalysis.Remote.RemoteFullyQualifyService.<>c__DisplayClass2_0.<b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.d__7`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.d__7`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__14`1.MoveNext()
```

---
#### Feedback Bot on 3/16/2023, 05:34 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 3/17/2023, 06:43 AM: 

(private comment, text removed)
#### Manuel Eisenschink on 3/30/2023, 05:05 AM: 

(private comment, text removed)
#### Feedback Bot on 3/29/2023, 00:19 AM: 

(private comment, text removed)
#### Feedback Bot on 3/30/2023, 05:34 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski possibly related to https://github.com/dotnet/roslyn/issues/63968.  Seems to be the general bucket of ensuring that both sides are referring to the same view of hte world.

**Comment by CyrusNajmabadi** [comment]
Closing out to age and this all being effectively rewritten.
