### ISSUE TITLE
NRE in NullableWalker while editing code

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#67816]
I'm on 17.6 P2

```
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.EnforceParameterNotNullOnExit(SyntaxNode syntaxOpt, LocalState state)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeLocalFunctionOrLambda(IBoundLambdaOrFunction lambdaOrFunction, MethodSymbol lambdaOrFunctionSymbol, LocalState state, MethodSymbol delegateInvokeMethod, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLambda(BoundLambda node, NamedTypeSymbol delegateTypeOpt, Optional`1 initialState)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.<VisitArguments>g__visitArguments|227_0(BoundNode node, ImmutableArray`1 arguments, ImmutableArray`1 argumentsNoConversions, ImmutableArray`1 conversions, ImmutableArray`1 results, ImmutableArray`1 refKindsOpt, ImmutableArray`1 parametersOpt, ImmutableArray`1 argsToParamsOpt, BitVector defaultArguments, Boolean expanded, Boolean invokedAsExtensionMethod, MethodSymbol method, Boolean delayCompletionForTargetMember)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.ReinferMethodAndVisitArguments(BoundCall node, TypeWithState receiverType)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitCall(BoundCall node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitUnaryOperator(BoundUnaryOperator node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AfterLeftChildOfBinaryLogicalOperatorHasBeenVisited(BoundExpression node, BoundExpression right, Boolean isAnd, Boolean isBool, LocalState& leftTrue, LocalState& leftFalse)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitBinaryLogicalOperatorChildren(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitBinaryOperator(BoundBinaryOperator node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitConversion(BoundConversion node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitIfStatement(BoundIfStatement node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitMethodBodies(BoundBlock blockBody, BoundBlock expressionBody)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitConstructorMethodBody(BoundConstructorMethodBody node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion)
      at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Analyze(Boolean& badRegion, Optional`1 initialState)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, Optional`1 initialState, Builder snapshotBuilderOpt, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, Conversions conversions, DiagnosticBag diagnostics, Boolean useConstructorExitWarnings, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType, MethodSymbol delegateInvokeMethodOpt, VariableState initialState, MethodSymbol baseOrThisInitializer, Builder analyzedNullabilityMapOpt, Builder snapshotBuilderOpt, ArrayBuilder`1 returnTypesOpt, Boolean getFinalNullableState, VariableState& finalNullableState, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, Boolean requiresAnalysis)
      at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(BoundNode boundRoot, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<EnsureNullabilityAnalysisPerformedIfNecessary>g__rewriteAndCache|130_1(<>c__DisplayClass130_0& )
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.Classification.OperatorOverloadSyntaxClassifier.AddClassifications(SyntaxNode syntax, SemanticModel semanticModel, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassificationsAsync(Document document, TextSpan textSpan, ClassificationOptions options, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddClassificationsInCurrentProcessAsync(Document document, TextSpan textSpan, ClassificationType type, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)

```

I have no repro steps :(
But happened while typing. Hope the stack trace can help.

**Comment by jcouv** [comment]
I took a peek, but couldn't obviously spot the problem, and I couldn't find an internal bug/crash report mentioning `EnforceParameterNotNullOnExit`. Can you enable crash dumps in case you hit this again?

**Comment by Youssef1313** [comment]
@jcouv If you are referring to https://gist.github.com/sharwell/95d97318c0e4612d9ad91b6223297f49, then I have them enabled. But nothing is in `C:\CrashDumps` (other than old dumps)

I think those dumps are written only when devenv gets a hard crash that the process is terminated.

If you are referring to something else, please let me know.

Note: My code was in error state when this happened.

**Comment by Youssef1313** [comment]
@jcouv Note: Part of the code was greatly invalid syntax when this exception occurred, with multiple incomplete lambdas and missing parentheses.

**Comment by Youssef1313** [comment]
@jcouv I took a look, and here are my findings:

https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs#L77-L108

Here, the base implementation could return null if the syntax node isn't one that is explicitly handled.

So, in theory, `boundRoot` in this line *may* be null? https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs#L1941

Then we could go into https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs#L1960

Then https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs#L1982, the first parameter of the `RewriteNullableBoundNodesWithSnapshots` may be null.

which goes into https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs#L298

and few calls here and there (omitted to not make the comment unnecessarily long), it will propagate to

https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs#L216

which may be dereferenced here:

https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L1170

**This is only a guess - I still don't have a dump. Only going through the code and guessing what could be null and tracking it backwards**

**Comment by Youssef1313** [comment]
@jcouv I got a minimized repro. Paste this code in VS

```csharp
#nullable enable

using System.Diagnostics.CodeAnalysis;

internal class C
{
    private static bool M([NotNullWhen(true)] out object? o)
    {
    }

    public C()
    {
        if (!M(p => p.A(), out
            "".B() is null
            ))
        {
        }
    }
}
```

and it will crash.

I tried to look via a compiler unit test. I found couple assertion failures, but when commenting them temporarily, I don't see a crash at the end.

**Comment by jcouv** [comment]
Thanks so much for digging up a minimal repro! It didn't crash in VS 17.6p3 but it did cause assertions in unittest like you mentioned. 
I'm wondering whether something we fixed recently affected the crash. Could you put `#error version` in your code to check what version of the compiler caused the crash?
Anyways, we'll investigate on the basis of the assertions.

**Comment by Youssef1313** [comment]
Compiler version: '4.6.0-2.23151.17 (1314d090)'.

**Comment by Youssef1313** [comment]
@jcouv I kept reverting some commits, and as soon as I reverted https://github.com/dotnet/roslyn/pull/66637 locally, I found a crash.

There are few more stack traces than what I got in VS, but I'm not sure if it's a result of inlining or something?

At the top I'm seeing:

```
[xUnit.net 00:00:04.32]       System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:04.32]       Stack Trace:
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(11478,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.LocalState.<NormalizeIfNeeded>g__hasValueCore|21_1(LocalState& state, Int32 id, Int32 index)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(11470,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.LocalState.<NormalizeIfNeeded>g__hasValue|21_0(LocalState& state, Int32 slot)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(11460,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.LocalState.NormalizeIfNeeded(Int32 slot, NullableWalker walker, Variables variables, Boolean useNotNullsAsDefault)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(1839,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.NormalizeIfNeeded(LocalState& state, Int32 slot, Boolean useNotNullsAsDefault)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(1824,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.GetState(LocalState& state, Int32 slot)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(1160,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.EnforceParameterNotNullOnExit(SyntaxNode syntaxOpt, LocalState state)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(3123,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeLocalFunctionOrLambda(IBoundLambdaOrFunction lambdaOrFunction, MethodSymbol lambdaOrFunctionSymbol, LocalState state, MethodSymbol delegateInvokeMethod, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType)
[xUnit.net 00:00:04.32]         src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs(8992,0): at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLambda(BoundLambda node, NamedTypeSymbol delegateTypeOpt, Optional`1 initialState)
```

**Comment by jcouv** [comment]
Hmm, not sure why those 5 more frames didn't appear in the original stack trace, but they do make the problem clearer and confirm the crash you hit was related to something we fixed. Thanks for figuring it out :-)
