### ISSUE TITLE
IDE errors with file-local extension method

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#67940]
**Version Used**: 

Any.
(I checked with VS 17.5.4 and VS 17.6.0 Preview 4.)

**Steps to Reproduce**:

1. Write followin 3 cs files:

Extension.cs

```cs
internal static class Extensions
{
    public static void M(this string _) { }
}
```

FileExtensions.cs

```cs
file static class FileExtensions
{
    public static void M(this string _) { }
}
```

Program.cs

```cs
"".M();
```

2. Open Program.cs or bring the cursor over `M` in Program.cs

**Expected Behavior**:

No error.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3760955/233886441-5fe29c31-1190-4ee9-ba62-1a7a947789a0.png)

The IDE repeatedly fails.

The IDE errors can occur even without internal `Extensions`; `Extensions` exists only to ensure successful compilation.

**Comment by CyrusNajmabadi** [comment]
Could you please include the stack trace.

**Comment by ufcpp** [comment]
Partially in Japanese in my environment:

Document hilights:

```
StreamJsonRpc.RemoteInvocationException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, MethodSymbol method, ImmutableArray`1 typeArguments, TypeSymbol receiverType, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.MergeReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, SingleLookupResult singleResult, ImmutableArray`1 typeArguments, TypeSymbol receiverType, LookupResultKind& resultKind, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetReducedAndFilteredMethodGroupSymbols(Binder binder, BoundMethodGroup node)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetMethodGroupSemanticSymbols(BoundMethodGroup boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, LookupResultKind& resultKind, Boolean& isDynamic, ImmutableArray`1& methodGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSemanticSymbols(BoundExpression boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, SymbolInfoOptions options, Boolean& isDynamic, LookupResultKind& resultKind, ImmutableArray`1& memberGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
      場所 Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetAliasInfo(IdentifierNameSyntax nameSyntax, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetAliasInfoCore(SyntaxNode node, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, SyntaxToken token, SolutionServices services, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<GetSemanticInfoAtPositionAsync>d__4.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindSymbolAtPositionAsync>d__3.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsInCurrentProcessAsync>d__2.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsAsync>d__1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

Semantic classification:

```
StreamJsonRpc.RemoteInvocationException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, MethodSymbol method, ImmutableArray`1 typeArguments, TypeSymbol receiverType, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.MergeReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, SingleLookupResult singleResult, ImmutableArray`1 typeArguments, TypeSymbol receiverType, LookupResultKind& resultKind, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetReducedAndFilteredMethodGroupSymbols(Binder binder, BoundMethodGroup node)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetMethodGroupSemanticSymbols(BoundMethodGroup boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, LookupResultKind& resultKind, Boolean& isDynamic, ImmutableArray`1& methodGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSemanticSymbols(BoundExpression boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, SymbolInfoOptions options, Boolean& isDynamic, LookupResultKind& resultKind, ImmutableArray`1& memberGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
      場所 Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(SyntaxNode syntax, SemanticModel semanticModel, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      場所 Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      場所 Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__6.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddClassificationsInCurrentProcessAsync>d__7.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 System.Threading.Tasks.ValueTask`1.get_Result()
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 System.Threading.Tasks.ValueTask`1.get_Result()
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 System.Threading.Tasks.ValueTask`1.get_Result()
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 System.Threading.Tasks.ValueTask`1.get_Result()
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
```

CodeLens references:

```
StreamJsonRpc.RemoteInvocationException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, MethodSymbol method, ImmutableArray`1 typeArguments, TypeSymbol receiverType, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.MergeReducedAndFilteredMethodGroupSymbol(ArrayBuilder`1 methods, ArrayBuilder`1 filteredMethods, SingleLookupResult singleResult, ImmutableArray`1 typeArguments, TypeSymbol receiverType, LookupResultKind& resultKind, CSharpCompilation compilation)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetReducedAndFilteredMethodGroupSymbols(Binder binder, BoundMethodGroup node)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetMethodGroupSemanticSymbols(BoundMethodGroup boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, LookupResultKind& resultKind, Boolean& isDynamic, ImmutableArray`1& methodGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSemanticSymbols(BoundExpression boundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt, SymbolInfoOptions options, Boolean& isDynamic, LookupResultKind& resultKind, ImmutableArray`1& memberGroup)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
      場所 Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferenceCache.<>c.<GetSymbolInfo>b__8_0(SyntaxNode n, ValueTuple`2 arg)
      場所 Microsoft.CodeAnalysis.PooledObjects.PooledDelegates.FuncWithBoundArgument`3.<Bind>b__0_0(T1 arg1)
      場所 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
      場所 Roslyn.Utilities.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TArg,TValue](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg factoryArgument)
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferenceCache.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.SymbolsMatchAsync(ISymbol symbol, FindReferencesDocumentState state, SyntaxToken token, CancellationToken cancellationToken)
      場所 Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.<FindReferencesInTokensAsync>d__17.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.<FindReferencesInDocumentUsingIdentifierAsync>d__15.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.Finders.OrdinaryMethodReferenceFinder.<FindReferencesInDocumentAsync>d__11.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_0.<<ProcessDocumentAsync>g__ProcessDocumentAsync|0>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__20.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessDocumentAsync>d__20.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__18.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<ProcessProjectAsync>d__18.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__13.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__13.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__13.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__35.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__42.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.<FindAsync>d__2`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.<GetReferenceCountAsync>d__4.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<>c__DisplayClass3_0.<<GetReferenceCountAsync>b__0>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()
   --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
      場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      場所 Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<GetReferenceCountAsync>d__3.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Thanks!  @jcouv  can you triage?

**Comment by jasonmalinowski** [comment]
Internal bug from error reporting: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1844805. @RikkiGibson the hit counts should be high enough that you should be able to get some crash dumps if needed.
