### ISSUE TITLE
CI test failure: Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicEncapsulateField.EncapsulateThroughLightbulbIncludingReferences

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#67981]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=252320&view=ms.vss-test-web.build-test-results-tab&runId=4898170&resultId=100634&paneView=debug

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Extensibility.Testing.InProcComponent.<WaitForApplicationIdleAsync>d__11.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/Microsoft.VisualStudio.Extensibility.Testing.SourceGenerator/Microsoft.VisualStudio.Extensibility.Testing.SourceGenerator.TestServicesSourceGenerator/InProcComponent.g.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.InProcess.InputInProcess.<>c__DisplayClass5_0.<<SendWithoutActivateAsync>b__0>d.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Roslyn.VisualStudio.IntegrationTests.InProcess.InputInProcess.<SendWithoutActivateAsync>d__5.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/InputInProcess.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Roslyn.VisualStudio.IntegrationTests.InProcess.StateResetInProcess.<ResetHostSettingsAsync>d__2.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.AbstractIntegrationTest.<InitializeAsync>d__3.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.AbstractEditorTest.<InitializeAsync>d__8.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractEditorTest.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
The test is correctly identifying that the feature is broken:
![22 21 43-BasicEncapsulateField EncapsulateThroughLightbulbIncludingReferences-Exception](https://user-images.githubusercontent.com/1408396/234656532-7dcf2d3d-e743-4dba-b725-5d4b901da8dc.png)

**Comment by CyrusNajmabadi** [comment]
@mavasani something broken in lightbulb calculation?  race condition perhaps?

**Comment by CyrusNajmabadi** [comment]
Closing as this is not skipped and we haven't seen this in a long time.
