### ISSUE TITLE
CI test failure: Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicArgumentProvider.TabTabCompleteObjectEquals

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#67980]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=252637&view=ms.vss-test-web.build-test-results-tab&runId=4903672&resultId=100611&paneView=debug

```
Assert.Equal() Failure
↓ (pos 21)
Expected: ···       Object.Equals(Nothing
Actual:   ···       Object.Equals

↑ (pos 21)


Stack trace
   at Roslyn.VisualStudio.IntegrationTests.InProcess.EditorVerifierInProcess.<CurrentLineTextAndAssertCaretPositionAsync>d__1.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorVerifierInProcess.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.IntegrationTests.InProcess.EditorVerifierInProcess.<CurrentLineTextAsync>d__0.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorVerifierInProcess.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicArgumentProvider.<TabTabCompleteObjectEquals>d__5.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicArgumentProvider.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
The test is correctly identifying that the feature is broken:
![14 09 36-BasicArgumentProvider TabTabCompleteObjectEquals-EqualException](https://user-images.githubusercontent.com/1408396/234656446-a166fc14-66a0-45a5-9303-926e3330b368.png)
