### ISSUE TITLE
Feature 'Semantic classification' is currently unavailable due to an internal error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68026]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Semantic-classification-is-cur/10170856)._

---
[severity:It bothers me. A fix would be nice]

```
foreach
Console.Write($"{1 switch { _ => 1 }}");
```

```
StreamJsonRpc.RemoteInvocationException: Odkaz na objekt není nastaven na instanci objektu.
   at StreamJsonRpc.JsonRpc.d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.d__18`1.MoveNext()
RPC server exception:
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
      v Microsoft.CodeAnalysis.CSharp.Binder.BindSwitchExpression(SwitchExpressionSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindInterpolatedString(InterpolatedStringExpressionSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(BindingDiagnosticBag diagnostics, ExpressionSyntax argumentExpression, RefKind refKind, Boolean allowArglist)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, BindingDiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(BaseArgumentListSyntax argumentListOpt, BindingDiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
      v Microsoft.CodeAnalysis.CSharp.ForEachLoopBinder.BindForEachPartsWorker(BindingDiagnosticBag diagnostics, Binder originalBinder)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindForEach(CommonForEachStatementSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
      v Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
      v Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
      v Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(SyntaxNode syntax, SemanticModel semanticModel, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      v Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      v Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken)
      v Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.d__6.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v Microsoft.CodeAnalysis.Classification.AbstractClassificationService.d__7.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<b__0>d.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v System.Threading.Tasks.ValueTask`1.get_Result()
      v Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v System.Threading.Tasks.ValueTask`1.get_Result()
      v Microsoft.CodeAnalysis.Remote.RemoteWorkspace.d__10`1.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v System.Threading.Tasks.ValueTask`1.get_Result()
      v Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__11`1.MoveNext()
   --- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
      v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      v System.Threading.Tasks.ValueTask`1.get_Result()
      v Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.d__14`1.MoveNext()

```

---
#### Feedback Bot on 10/12/2022, 07:26 PM: 

(private comment, text removed)
#### Feedback Bot on 10/26/2022, 03:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
```

        [Fact]
        [WorkItem("https://github.com/dotnet/roslyn/issues/68026")]
        public void ErrorScenario_01()
        {
            var source = @"
foreach
Console.Write($""{1 switch { _ => 1 }}"");
";
            CreateCompilation(source).VerifyDiagnostics(
                );
        }
```

Observed:
https://github.com/dotnet/roslyn/blob/93cd10a5fdff679ecab004afb9e594c0be240b11/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs#L150
```
  Message: 
System.InvalidOperationException : Assertion failed

  Stack Trace: 
ThrowingTraceListener.Fail(String message, String detailMessage) line 26
TraceInternal.Fail(String message, String detailMessage)
TraceProvider.Fail(String message, String detailMessage)
Debug.Fail(String message, String detailMessage)
Debug.Assert(Boolean condition)
RoslynDebug.Assert(Boolean b) line 15
Binder.BindSwitchExpression(SwitchExpressionSyntax node, BindingDiagnosticBag diagnostics) line 150
Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) line 668
Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) line 517
Binder.BindValue(ExpressionSyntax node, BindingDiagnosticBag diagnostics, BindValueKind valueKind) line 235
```
