### ISSUE TITLE
CI test failure: Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests+VisualBasicConflicts.RenameAttributeFromUsage

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#68073]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=260018&view=ms.vss-test-web.build-test-results-tab&runId=5098646&resultId=189914&paneView=debug

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.

Stack trace
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__22`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.RemoteHostClient.<TryInvokeAsync>d__19`2.MoveNext() in /_/src/Workspaces/Core/Portable/Remote/RemoteHostClient.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Rename.Renamer.<RenameSymbolAsync>d__8.MoveNext() in /_/src/Workspaces/Core/Portable/Rename/Renamer.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.GetConflictResolution(String renameTo, Solution solution, ISymbol symbol, SymbolRenameOptions renameOptions, RenameTestHost host) in /_/src/EditorFeatures/Test2/Rename/RenameEngineResult.vb:line 139
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineResult.Create(ITestOutputHelper helper, XElement workspaceXml, String renameTo, RenameTestHost host, SymbolRenameOptions renameOptions, Boolean expectFailure, ISourceGenerator sourceGenerator) in /_/src/EditorFeatures/Test2/Rename/RenameEngineResult.vb:line 93
   at Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.VisualBasicConflicts.RenameAttributeFromUsage(RenameTestHost host) in /_/src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb:line 1604
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we dont' have more reports of this and the test is not skipped.
