### ISSUE TITLE
ArgumentOutOfRangeException in ReplacePropertyWithMethodsCodeRefactoringProvider

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/roslyn#68207]
**Version Used**: 17.5.5

**Steps to Reproduce**:

Similar to issue #41159.
Also while converting to a full property.

**Expected Behavior**:
No crash.

**Actual Behavior**:
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.GetBinaryExpressionOperatorTokenKind(SyntaxKind kind)
   at Microsoft.CodeAnalysis.CSharp.ReplacePropertyWithMethods.CSharpReplacePropertyWithMethodsService.UnwrapCompoundAssignment(SyntaxNode compoundAssignment,ExpressionSyntax readExpression)
   at Microsoft.CodeAnalysis.ReplacePropertyWithMethods.AbstractReplacePropertyWithMethodsService`5.ReferenceReplacer.<>c.<.cctor>b__36_2(ReferenceReplacer replacer,SyntaxNode parent)
   at Microsoft.CodeAnalysis.ReplacePropertyWithMethods.AbstractReplacePropertyWithMethodsService`5.ReferenceReplacer.<>c.<.cctor>b__36_3(SyntaxNode parent,SyntaxGenerator generator,ReplaceParentArgs args)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange`1.Apply(SyntaxNode root,SyntaxNode currentNode,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.UpdateReferencesInDocumentAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.UpdateReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ReplacePropertyWithMethods.ReplacePropertyWithMethodsCodeRefactoringProvider.ReplacePropertyWithMethodsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by JeroenOortwijn** [comment]
It happens specifically when you press <kbd>Alt</kbd>-<kbd>Enter</kbd> and then repeatedly <kbd>↓</kbd> until you arrive at:

![image](https://github.com/dotnet/roslyn/assets/51476918/ea218418-c8ca-4d7d-af01-d15e566730ca)

**Comment by CyrusNajmabadi** [comment]
Can you provide a copy of your source code?  We're crashing in a particular syntax node.  Having the source will tell us which one it is.

**Comment by JeroenOortwijn** [comment]
Unfortunately, I tried to reproduce the crash, but am unable to.
I updated to Visual Studio v17.6.0, so maybe that fixed it.

Closing this issue for now.
If I encounter the same crash again, I will reopen it.
