### ISSUE TITLE
Error performing rename: 'Unexpected false - line 20'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68244]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-performing-rename:-Unexpected-fal/10366034)._

---
Getting this when attempting to rename a method parameter. I'm not sure of the circumstances. The method has documentation comments, including a `<param name="foo"/>` for the parameter in question. The method also includes a `static extern` local method adorned with a `[DllImport]` attribute.

Here's the stack trace:
```
System.InvalidOperationException : Unexpected false - line 20
   at Roslyn.Utilities.Contract.Fail(String message,Int32 lineNumber)
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,Int32 lineNumber)
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.GetReplacementsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass76_0.<UpdateConflictResolutionTask>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.Commit(InlineRenameSession activeSession,ITextView textView)
```

---
#### Feedback Bot on 5/17/2023, 09:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This appears to be introduced by #62453, which added the following constraint which is apparently not always met:
https://github.com/dotnet/roslyn/blob/078c7947e2db1253194355d758c8394e87b2a45c/src/EditorFeatures/Core/InlineRename/AbstractEditorInlineRenameService.InlineRenameReplacementInfo.cs#L20
