### ISSUE TITLE
Feature 'Solution Events' is currently unavailable due to an internal error.

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#68247]
**Version Used**: 17.6.0

StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__25.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId)
      at Microsoft.CodeAnalysis.Workspace.<SetCurrentSolution>g__UpdateAddedDocumentToExistingContentsInSolution|26_1(Solution solution, DocumentId addedDocumentId)
      at Microsoft.CodeAnalysis.Workspace.<SetCurrentSolution>g__UnifyLinkedDocumentContents|26_0(Solution oldSolution, Solution newSolution)
      at Microsoft.CodeAnalysis.Workspace.<>c.<SetCurrentSolution>b__26_3(Solution oldSolution, ValueTuple`7 data)
      at Microsoft.CodeAnalysis.Workspace.SetCurrentSolution[TData](TData data, Func`3 transformation, Action`3 onBeforeUpdate, Action`3 onAfterUpdate)
      at Microsoft.CodeAnalysis.Workspace.SetCurrentSolution(Func`2 transformation, Func`3 changeKind, ProjectId projectId, DocumentId documentId, Action`2 onBeforeUpdate, Action`2 onAfterUpdate)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.TryUpdateWorkspaceCurrentSolutionWorkerAsync(Int32 workspaceVersion, Solution newSolution, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.TryUpdateWorkspaceCurrentSolutionAsync(Int32 workspaceVersion, Solution newSolution, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.InFlightSolution.<>c__DisplayClass14_0.<<TryKickOffPrimaryBranchWork_NoLock>g__ComputePrimaryBranchAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.VisualStudio.Threading.ThreadingTools.WithCancellationSlow[T](Task`1 task, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync(Func`2 implementation, CancellationToken cancellationToken)

**Comment by kindermannhubert** [comment]
This has probably same root issue as #68246 (I've moved the info there).
