### ISSUE TITLE
CodeFixProvider throws InvalidOperationException: 'ISymbolDeclarationService' is required to accomplish the task but is not available from the workspace

### ISSUE THREAD

**Issue by cremor** [dotnet/roslyn#68440]
**Version Used**: 
VS 17.6.2

**Steps to Reproduce**:

1. Create a new .NET 7 console app.
2. Add the line `Func<int, int> test = (int n) => n * 2;`.
3. Place the cursor at the new line and open the quick actions menu. Note that the quick action "Use local function" appears and shows a correct preview.
4. Add the line `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` to the project file.
5. Open the quick actions menu on the code line again.

**Diagnostic Id**:
IDE0039

**Expected Behavior**:
The code fix "Use local function" should be available.

**Actual Behavior**:
VS shows a yellow error bar with the error "'CSharpUseLocalFunctionCodeFixProvider' encountered an error and has been disabled." and the following stack trace:

```
System.InvalidOperationException : Service of type 'Microsoft.CodeAnalysis.LanguageService.ISymbolDeclarationService' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostLanguageServices.GetRequiredService[TLanguageService]()
   at async Microsoft.CodeAnalysis.CSharp.UseLocalFunction.CSharpUseLocalFunctionCodeFixProvider.FixAllAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @sharwell .  I can't imagine what would be the issue here.  Maybe mef corruption?  I don't even see anything in the code that would need this service. 

@cremor could you provide a link to your project?  Could you also try on 17.7 latest public preview?

**Comment by cremor** [comment]
I now know how to reproduce this in a new project. `EnforceCodeStyleInBuild` needs to be enabled. See updated steps to reproduce in my initial post.

**Comment by CyrusNajmabadi** [comment]
I don't repro this on 17.7p1.  CAn you supply a repro project as i don't know if i'm doing something differently than you.

**Comment by cremor** [comment]
Here is a sample project: https://github.com/cremor/code-fix-provider-error-sample
I use VS 17.6.2.

**Comment by CyrusNajmabadi** [comment]
I still get no issue on 17.7p1.  Do you still repro this issue on our latest public builds?  Thanks!

**Comment by cremor** [comment]
I don't have a preview build installed and don't really want to install one for this small bug, sorry.

**Comment by CyrusNajmabadi** [comment]
Preview builds install SxS :)  It takes just a couple of minutes to install.  But understood if you don't want to do that.  Cheers!
