### ISSUE TITLE
C# Interactive UnauthorizedAccessException

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#68606]
**Version Used**: VS 17.6.3

This started right after the installation of 17.6.3. 

When I start VS with C# Interactive window closed and try to open it after the start I get:
![image](https://github.com/dotnet/roslyn/assets/11704036/5fb7a60c-7eb4-4742-9ca1-4c4135ce006d)

When I start VS with C# Interactive window already open the window contains only the following error:

![image](https://github.com/dotnet/roslyn/assets/11704036/4d864f5b-fcf7-4bde-9094-2ac08f63c0fb)

An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\\__my_username__\AppData\Roaming\Microsoft\VisualStudio\17.0_44905dec\ActivityLog.xml".

Exception details:
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation. ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32 A_0)
   at MS.Internal.FontFace.PhysicalFontFamily.MapGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch, CharacterBufferRange charString, CultureInfo digitCulture, Int32& advance, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFaceFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Boolean nullFont, Double scaleInEm, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Boolean ignoreMissing, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, CanonicalFontFamilyReference canonicalFamilyReference, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapOnceByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapItem(CharacterBufferRange unicodeString, CultureInfo culture, Span itemSpan, SpanVector`1& cachedScaledTypefaceIndexSpans, Int32 ichItem)
   at MS.Internal.Shaping.TypefaceMap.GetShapeableText(CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at MS.Internal.Shaping.GlyphingCache.GetShapeableText(Typeface typeface, CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at System.Windows.Media.TextFormatting.TextCharacters.MS.Internal.TextFormatting.ITextSymbols.GetTextShapeableSymbols(GlyphingCache glyphingCache, CharacterBufferReference characterBufferReference, Int32 length, Boolean rightToLeft, Boolean isRightToLeftParagraph, CultureInfo digitCulture, TextModifierScope textModifierScope, TextFormattingMode textFormattingMode, Boolean isSideways)
   at MS.Internal.TextFormatting.TextStore.CreateTextLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.CreateLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel, Int32& textRunLength)
   at MS.Internal.TextFormatting.TextStore.CreateLSRunsUniformBidiLevel(SpanVector runInfoVector, SpanVector textEffectsVector, Int32 runInfoFirstCp, Int32 ichUniform, Int32 cchUniform, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.FetchLSRun(Int32 lscpFetch, TextFormattingMode textFormattingMode, Boolean isSideways, Plsrun& plsrun, Int32& lsrunOffset, Int32& lsrunLength)
   at MS.Internal.TextFormatting.LineServicesCallbacks.FetchRunRedefined(IntPtr pols, Int32 lscpFetch, Int32 fIsStyle, IntPtr pstyle, Char* pwchTextBuffer, Int32 cchTextBuffer, Int32& fIsBufferUsed, Char*& pwchText, Int32& cchText, Int32& fIsHidden, LsChp& lschp, IntPtr& lsplsrun)
   --- End of inner exception stack trace ---
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine.FormatLine(FullTextState fullText, Int32 cpFirst, Int32 lineLength, Int32 formatWidth, Int32 finiteFormatWidth, Int32 paragraphWidth, LineFlags lineFlags, FormattedTextSymbols collapsingSymbol)
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine..ctor(FormatSettings settings, Int32 cpFirst, Int32 lineLength, Int32 paragraphWidth, LineFlags lineFlags)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.FormatLine(TextSource textSource, Int32 textSourcePosition, Double maxLineLength, TextParagraphProperties paraProps, TextLineBreak lineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.MoveNext()
   at System.Windows.Media.FormattedText.DrawAndCalculateMetrics(DrawingContext dc, Point drawingOffset, Boolean getBlackBoxMetrics)
   at System.Windows.Media.FormattedText.get_Metrics()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.TextInfoCache.GetTextInfo(TextRunProperties key)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedTextSourceFactoryService.Create(ITextSnapshot sourceTextSnapshot, ITextSnapshot visualBufferSnapshot, Int32 tabSize, Double lineSpacing, Double baseIndentation, Double wordWrapWidth, Double maxAutoIndent, Boolean useDisplayMode, IClassifier aggregateClassifier, ITextAndAdornmentSequencer sequencer, IClassificationFormatMap classificationFormatMap, Boolean isViewWrapEnabled)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PreLayout(LayoutLineCache lineCache)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop, Boolean updateLayoutHeight, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.get_WpfTextViewHost()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetData(Guid& riidKey, Object& pvtData)
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetWpfTextViewHostFromVsTextView(IVsTextView viewAdapter)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowCommandFilter..ctor(IVsEditorAdaptersFactoryService adapterFactory, IInteractiveWindow window, IVsTextView textViewAdapter, IVsTextBuffer bufferAdapter, IEnumerable`1 oleCommandTargetProviders, IContentTypeRegistryService contentTypeRegistry)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowEditorFactoryService.Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindowEditorFactoryService.CreateTextView(IInteractiveWindow window, ITextBuffer buffer, ITextViewRoleSet roles)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly..ctor(InteractiveWindow window, IInteractiveWindowEditorFactoryService factory, IContentTypeRegistryService contentTypeRegistry, ITextBufferFactoryService bufferFactory, IProjectionBufferFactoryService projectionBufferFactory, IEditorOperationsFactoryService editorOperationsFactory, ITextBufferUndoManagerProvider textBufferUndoManagerProvider, ITextEditorFactoryService editorFactory, IRtfBuilderService rtfBuilderService, IIntellisenseSessionStackMapService intellisenseSessionStackMap, ISmartIndentationService smartIndenterService, IInteractiveEvaluator evaluator, IUIThreadOperationExecutor uiThreadOperationExecutor)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow..ctor(IInteractiveWindowEditorFactoryService host, IContentTypeRegistryService contentTypeRegistry, ITextBufferFactoryService bufferFactory, IProjectionBufferFactoryService projectionBufferFactory, IEditorOperationsFactoryService editorOperationsFactory, ITextBufferUndoManagerProvider textBufferUndoManagerProvider, ITextEditorFactoryService editorFactory, IRtfBuilderService rtfBuilderService, IIntellisenseSessionStackMapService intellisenseSessionStackMap, ISmartIndentationService smartIndenterService, IInteractiveEvaluator evaluator, IUIThreadOperationExecutor uiThreadOperationExecutor)
   at Microsoft.VisualStudio.InteractiveWindow.InteractiveWindowProvider.CreateWindow(IInteractiveEvaluator evaluator)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow.OnCreate()
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.CreateUIElementPane(Object& uiElement)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.Init(Boolean initSize)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindow..ctor(IComponentModel model, Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags, Guid toolbarCommandSet, UInt32 toolbarId, IOleCommandTarget toolbarCommandTarget)
   at Microsoft.VisualStudio.InteractiveWindow.Shell.VsInteractiveWindowFactory.Create(Guid providerId, Int32 instanceId, String title, IInteractiveEvaluator evaluator, __VSCREATETOOLWIN creationFlags)
   at Microsoft.VisualStudio.LanguageServices.Interactive.VsInteractiveWindowProvider.Create(Int32 instanceId)
   at Microsoft.VisualStudio.LanguageServices.Interactive.VsInteractiveWindowPackage`1.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& rguidPersistenceSlot, UInt32 id)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<ConstructContent>g__ConstructContentFromPackage|145_1(WindowFrame frame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

**Comment by kindermannhubert** [comment]
This is probably related to this:
![image](https://github.com/dotnet/roslyn/assets/11704036/dd5daf52-34ed-435d-bd79-f9f261ad971d)
I also cannot view any files. Changing font helps (for viewing files and C# Interactive too).

My default font is Cascadia Code - this has been broken by VS update 😞. When I change it to e.g. Cascadia Code Light it works.

**Comment by kindermannhubert** [comment]
Reinstalling Cascadia Code manually seems to help.

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue. It looks like something is up with your windows install, or fonts installation.  I don't believe vs itself touches that font.  It instead looks like whatever installed it, did so in a way that you yourself did not have access to it.
