### ISSUE TITLE
ObservableProperty breaks ExtractInterfaceCodeRefactoringProvider

### ISSUE THREAD

**Issue by mikeKuester** [dotnet/roslyn#68748]
**Version Used**: Visual Studio Enterprise 2022, v17.6.4

**Steps to Reproduce**:
- Create a new project with the "WPF Application" template for C#.
- Add the Communmity.Toolkit.Mvvm package (8.2.0).
- Add a partial public class and inherit from ObservableObject.
- Add a private field with the attribute ObservableProperty.
- Right click on the class name and choose the refactoring action "Extract interface".

```csharp
public partial class ViewModel : ObservableObject
{
    [ObservableProperty]
    private int _myProperty;
}
```

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**: none

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

The interface should be extracted from the class.

If I use this code - just with a public property with out using the ObservableProperty attribute, the interface could be extracted.

```csharp
public partial class ViewModel : ObservableObject
{
    public int MyProperty { get; set; }
}
```

**Actual Behavior**:

Visual Studio shows the following error:

> "ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled."

```csharp
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,SyntaxTree syntaxTree)
   at async Microsoft.CodeAnalysis.Shared.Utilities.AnnotatedSymbolMapping.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToNewFileAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

I first reported this to the CommunitiyToolkit/dotnet Project: https://github.com/CommunityToolkit/dotnet/issues/726  but as @333fred mentioned there, this is a roslyn bug.

**Comment by mikeKuester** [comment]
10 month later and still no solution for that?

**Comment by CyrusNajmabadi** [comment]
@mikeKuester There's only been one report of this.  If you're interested in contributing a fix, we'd be happy to work with you on that.

**Comment by mikeKuester** [comment]
I'm  just starting a discussion at the Community Toolkit project: https://github.com/CommunityToolkit/dotnet/discussions/871
I was also wondering that no one adds a comment here.

**Comment by CyrusNajmabadi** [comment]
@nvstrien @mikeKuester we'd be happy to take community contributions here. Thanks!

**Comment by nvstrien** [comment]
I am afraid I am unfamiliar with how to debug an issue like this.  Also, I was under the impression that the ExtractInterfaceCodeRefactoringProvider is Microsoft maintained code, but perhaps I am mistaken. If @CyrusNajmabadi  you can provide me a pointer how to approach this, I can give it a try.

**Comment by CyrusNajmabadi** [comment]
> ExtractInterfaceCodeRefactoringProvider is Microsoft maintained code

This type is contained within this project it is open source and anyone can contribute to it :-)

On the phone right now. But see our home page for a link on how to contribute! :-)

**Comment by usefulBeeing** [comment]
I hope this issue gets some attention because it is causing productivity issues. 

Where did the experts disappear?! :loudspeaker:

**Comment by CyrusNajmabadi** [comment]
@usefulBeeing see https://github.com/dotnet/roslyn/issues/68748#issuecomment-2075043435

**Comment by jphorv-bdo** [comment]
I am also having this issue, attempting to extract an interface on any of our view models crashes.
