### ISSUE TITLE
Compiler can silently generate a bad image when there's 0xFFFF parameters in the module

### ISSUE THREAD

**Issue by jbevain** [dotnet/roslyn#68754]
**Version Used**: 
.NET 7.0.400-preview.23225.8

**Steps to Reproduce**:

Started as an investigation of https://github.com/jbevain/cecil/issues/913

1. Compile this absolute unit of a compilation unit as the single file of a library project: https://gist.github.com/jbevain/9599e655adad445a6ee447add305a8bc
2. Reference the library in a console project:

```csharp
using System.Reflection;

var a = Assembly.LoadFile(typeof(P3).Assembly.Location);
foreach (var t in a.GetTypes())
{
    Console.WriteLine(t.FullName);
    foreach (var m in t.GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static))
    {
        Console.WriteLine(m.Name);
        foreach (var p in m.GetParameters())
        {
            Console.WriteLine(p.Name);
        }
    }
}
```

3. `dotnet run` the console project:

**Expected Behavior**:
Should print:

```
...
F_65534
a
```

**Actual Behavior**:

```
...
F_65534
Unhandled exception. System.BadImageFormatException: File is corrupt. (0x8013110E)
   at System.Reflection.MetadataImport._Enum(IntPtr scope, Int32 type, Int32 parent, MetadataEnumResult& result)
   at System.Reflection.RuntimeParameterInfo.GetParameters(IRuntimeMethodInfo methodHandle, MemberInfo member, Signature sig, ParameterInfo& returnParameter, Boolean fetchReturnParameter)
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Program.<Main>$(String[] args) in C:\tmp\ReproFFFF\exe\Program.cs:line 10
```

Note that the last row of the `Method` table has a `Param` of `0x80000000` which is unexpected:

<img width="790" alt="Screenshot 2023-06-23 at 5 50 21 PM" src="https://github.com/dotnet/roslyn/assets/79284/faef24a0-1107-4bce-a71e-1e7c130e95bd">

**Comment by jbevain** [comment]
Michal on Twitter pointed at the similarity to his old issue: https://github.com/dotnet/coreclr/pull/20865

There's obviously multiple components to this. It's not unreasonable to imagine that Roslyn could detect this special case and generate one additional empty method to prevent the generation of invalid metadata.

**Comment by FSDKO** [comment]
I found a similar error but with fields: #70857

**Comment by jbevain** [comment]
@FSDKO yes, everything that is represented as a “range” in metadata (Fields, Methods, Parameters) has this issue.
