### ISSUE TITLE
Assertion failure in switch expression with tuple literal

### ISSUE THREAD

**Issue by addabis** [dotnet/roslyn#69015]
**Version Used**: 
Originally on dev/17.6 branch, retested on main.

**Steps to Reproduce**:
Using debug build of the compiler produced assertion failure in our code. I'm including a repro project since I was unable to quickly reproduce the problem on a simpler code without references to Microsoft.CodeAnalysis assemblies.

[MLBug33466.zip](https://github.com/dotnet/roslyn/files/12037183/MLBug33466.zip)

I have included my workarounds for reference.

**Expected Behavior**:
Should not fail on assertion.

**Actual Behavior**:
Fails on the assertion in ConversionBase.GetImplicitTupleLiteralConversion.

**Comment by davidwengier** [comment]
If you want a repro of this, clone https://github.com/dotnet/razor, reference a debug build of Roslyn, and run `build.cmd`

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.GetImplicitTupleLiteralConversion(BoundTupleLiteral source, TypeSymbol destination, CompoundUseSiteInfo`1& useSiteInfo) in D:\Code\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\Conversions\ConversionsBase.cs:line 2288

   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ClassifyImplicitTupleLiteralConversion(BoundTupleLiteral source, TypeSymbol destination, CompoundUseSiteInfo`1& useSiteInfo) in D:\Code\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\Conversions\ConversionsBase.cs:line 1297

   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ClassifyImplicitBuiltInConversionFromExpression(BoundExpression sourceExpression, TypeSymbol source, TypeSymbol destination, CompoundUseSiteInfo`1& useSiteInfo) in D:\Code\roslyn\src\Compilers\CSharp\Portable\Binder\Semantics\Conversions\ConversionsBase.cs:line 1083

   at Microsoft.CodeAnalysis.CSharp.ConversionsBase.ClassifyImplicitConversionFromExpression(BoundExpression sourceExpression, TypeSym......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```
