### ISSUE TITLE
InvalidOperationException in CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#69459]
1. Open Roslyn.sln
2. Add a new C# source file to `Microsoft.CodeAnalysis.LanguageServerProtocol.csproj` with the following contents (note the file has errors):
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Composition;
using System.Diagnostics;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Host.Mef;
using Microsoft.CodeAnalysis.LanguageServer.Handler;
using Microsoft.CodeAnalysis.Options;
using Microsoft.CodeAnalysis.PooledObjects;
using Roslyn.Utilities;
using LSP = Microsoft.VisualStudio.LanguageServer.Protocol;

namespace Microsoft.CodeAnalysis.LanguageServer.Handler;

[DataContract]
internal readonly record struct BuildOnlyDiagnosticIdsResult([property: DataMember(Name = "ids")] string[] Ids);

[ExportCSharpVisualBasicStatelessLspService(typeof(BuildOnlyDiagnosticIdsHandler)), Shared]
[Method(BuildOnlyDiagnosticIdsMethodName)]
[method: ImportingConstructor]
[method: Obsolete(MefConstruction.ImportingConstructorMessage, error: true)]
internal class BuildOnlyDiagnosticIdsHandler(DiagnosticAnalyzerInfoCache.SharedGlobalCache _globalCache) 
        : ILspServiceRequestHandler<BuildOnlyDiagnosticIdsResult>
{
    private const string BuildOnlyDiagnosticIdsMethodName = "workspace/buildOnlyDiagnosticIds";

    public bool MutatesSolutionState => false;
    public bool RequiresLSPSolution => true;

    public Task<BuildOnlyDiagnosticIdsResult> HandleRequestAsync(RequestContext context, CancellationToken cancellationToken)
    {
        Contract.ThrowIfNull(context.Solution);

        using var _ = ArrayBuilder<string>.GetInstance(out var builder);
        foreach (var project in context.Solution.Projects)
        {
            foreach (var analyzersPerReference in context.Solution.State.Analyzers.CreateDiagnosticAnalyzersPerReference(project))
            {
                foreach (var analyzer in analyzersPerReference.Value)
                {
                    if (analyzer.IsCompilerAnalyzer())
                    {

                    }
                    else
                    {
                        foreach (var buildOnlyDescriptor in _globalCache.AnalyzerInfoCache.GetNonCompilationEndDiagnosticDescriptors(analyzer))
                        {
                            builder.Add(buildOnlyDescriptor.Id);
                        }
                    }
                }
            }
        }

        return builder.ToImmutable();
        return Task.FromResult(new LspSolutionSnapshotId(id.Id));
    }
}
```
3. Place the cursor on the primary constructor parameter, `_globalCache` and try to invoke the code fix `Create and assign property 'GlobalCache'`

**Actual:** Got the below gold bar in `CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider`

```
System.InvalidOperationException : GetCurrentNode returned null with the following node: _globalCache - line 255
   at Roslyn.Utilities.Contract.Fail(String message,Int32 lineNumber)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at Microsoft.CodeAnalysis.Editing.SolutionEditor.GetChangedSolution()
   at async Microsoft.CodeAnalysis.CSharp.InitializeParameter.CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider.<AddMultipleMembersAsync>g__AddSingleMemberAsync|3_0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CSharp.InitializeParameter.CSharpInitializeMemberFromPrimaryConstructorParameterCodeRefactoringProvider.AddMultipleMembersAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by mavasani** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Looking.

**Comment by CyrusNajmabadi** [comment]
Works in a standalone file.  Trying again within roslyn itself.

**Comment by CyrusNajmabadi** [comment]
Ok.  i repro this in roslyn.  debugging.
