### ISSUE TITLE
Feature 'Diagnostic analyzer runner' fails with gold bar when encountering list pattern on pointer type

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#70046]
**Version Used**: VS 2022 17.8 Preview 2 (4.8.0-2.23429.7)

**Steps to Reproduce**:
Paste this code into a class.

```csharp
unsafe void M()
{
    void* v = null;
    if (v is [])
}
```

**Expected Behavior**: No exception/gold bar.

**Actual Behavior**: A gold bar titled "Feature 'Diagnostic analyzer runner' is currently unavailable due to an internal error" appears.

Stack trace:
```
StreamJsonRpc.RemoteInvocationException: Unexpected value 'PointerElementAccess' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidOperationException: Unexpected value 'PointerElementAccess' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
      at Microsoft.CodeAnalysis.CSharp.Binder.GetIndexerOrImplicitIndexerSymbol(BoundExpression e)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundListPatternOperation(BoundListPattern boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundIsPatternExpressionOperation(BoundIsPatternExpression boundIsPatternExpression)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundConversionOperation(BoundConversion boundConversion, Boolean forceOperandImplicitLiteral)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundIfStatementOperation(BoundIfStatement boundIfStatement)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateMethodBodyOperation(BoundNonConstructorMethodBody boundNode)
      at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation()
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationBlocksToAnalyze(ImmutableArray`1 executableBlocks, SemanticModel semanticModel, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass11_0.<ExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|2()
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, GroupedAnalyzerActions coreActions, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, Boolean isGeneratedCodeSymbol, IGroupedAnalyzerActions additionalPerSymbolActions, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessSymbolDeclaredAsync(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessEventCoreAsync(CompilationEvent compilationEvent, AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventAsync(CompilationEvent e, AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(AnalysisScope analysisScope, Boolean prePopulatedEventQueue, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass132_0.<<ProcessCompilationEventsAsync>b__2>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync(AnalysisScope analysisScope, Boolean prePopulatedEventQueue, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecutePrimaryAnalysisTaskAsync(AnalysisScope analysisScope, Boolean usingPrePopulatedEventQueue, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.AttachQueueAndProcessAllEventsAsync(AsyncQueue`1 eventQueue, AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>g__attachQueueAndProcessAllEventsAsync|62_0(ArrayBuilder`1 builder, AnalyzerDriver driver, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync(AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalysisResultCoreAsync(SemanticModel model, Nullable`1 filterSpan, ImmutableArray`1 analyzers, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, Project project, DiagnosticAnalyzerInfoCache analyzerInfoCache, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)

```

**Comment by mavasani** [comment]
Exception in the compiler layer, moving to Compiler team. I am able to repro this on the latest IntPreview 17.9 dogfood build.
