### ISSUE TITLE
AnalyzerRunner throws an Exception: Missing assembly 'Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost'

### ISSUE THREAD

**Issue by mpidash** [dotnet/roslyn#70139]
**Version Used**: 

main (79155765545a)

**Steps to Reproduce**:

(Following [steps](https://github.com/dotnet/roslyn-analyzers/blob/main/docs/NetCore_GettingStarted.md#testing-against-the-roslyn-repo) to test an analyzer against `dotnet/roslyn`)

1. Build roslyn: `PS W:\roslyn> .\Build.cmd -restore -Configuration Release`
2. Build roslyn-analyzers: `PS W:\roslyn-analyzers> .\Build.cmd -Configuration Debug`
3. Run AnalyzerRunner: `PS W:\roslyn> .\artifacts\bin\AnalyzerRunner\Release\net7.0\AnalyzerRunner.exe ..\roslyn-analyzers\artifacts\bin\Microsoft.CodeAnalysis.Analyzers.Package\Debug\netstandard2.0 .\Roslyn.sln /stats /concurrent /a AvoidLengthCalculationWhenSlicingToEndAnalyzer /log Output.txt`

**Expected Behavior**:

AnalyzerRunner tests the analyzer against roslyn.

**Actual Behavior**:

An exception is thrown:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.CreateDefaultAssemblies()
   at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.get_DefaultAssemblies() in W:\roslyn\src\Workspaces\Core\MSBuild\Host\Mef\MSBuildMefHostServices.cs:line 37
   at AnalyzerRunner.AnalyzerRunnerMefHostServices.get_DefaultAssemblies() in W:\roslyn\src\Tools\AnalyzerRunner\AnalyzerRunnerMefHostServices.cs:line 32
   at AnalyzerRunner.AnalyzerRunnerMefHostServices.get_DefaultServices() in W:\roslyn\src\Tools\AnalyzerRunner\AnalyzerRunnerMefHostServices.cs:line 24
   at AnalyzerRunner.AnalyzerRunnerHelper.CreateWorkspace() in W:\roslyn\src\Tools\AnalyzerRunner\AnalyzerRunnerHelper.cs:line 49
   at AnalyzerRunner.Program.Main(String[] args) in W:\roslyn\src\Tools\AnalyzerRunner\Program.cs:line 58
   at AnalyzerRunner.Program.<Main>(String[] args)
```

**Workaround / Fix**:

The AnalyzerRunner works as expected after adding the following line to `AnalyzerRunner.csproj` and rebuilding:

```diff
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj" />
    <ProjectReference Include="..\..\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj" />
    <ProjectReference Include="..\..\Compilers\VisualBasic\Portable\Microsoft.CodeAnalysis.VisualBasic.vbproj" />
    <ProjectReference Include="..\..\Features\LanguageServer\Protocol\Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj" />
    <ProjectReference Include="..\..\Scripting\Core\Microsoft.CodeAnalysis.Scripting.csproj" />
    <ProjectReference Include="..\..\Workspaces\Core\Portable\Microsoft.CodeAnalysis.Workspaces.csproj" />
    <ProjectReference Include="..\..\Workspaces\Core\MSBuild\Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj" />
+   <ProjectReference Include="..\..\Workspaces\Core\MSBuild.BuildHost\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj" />
    <ProjectReference Include="..\..\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj" />
    <ProjectReference Include="..\..\Workspaces\VisualBasic\Portable\Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj" />
    <ProjectReference Include="..\..\Features\Core\Portable\Microsoft.CodeAnalysis.Features.csproj" />
    <ProjectReference Include="..\..\EditorFeatures\Text\Microsoft.CodeAnalysis.EditorFeatures.Text.csproj" />
    <!-- These aren't used by the build, but it allows the tool to locate dependencies of the built-in analyzers. -->
    <ProjectReference Include="..\..\Features\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Features.csproj" />
    <ProjectReference Include="..\..\Features\VisualBasic\Portable\Microsoft.CodeAnalysis.VisualBasic.Features.vbproj" />
  </ItemGroup>
```

**Comment by mavasani** [comment]
@sharwell - does the fix mentioned above seem correct to you?

**Comment by mavasani** [comment]
@mpidash Would you like to create a PR with your recommended fix? Looks good to me!
