### ISSUE TITLE
Feature "Document highlights" fails with exception when navigating in code using pointers

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#70159]
**Version Used**: VS 17.8 Preview 2

**Steps to Reproduce**:
Place the editor caret on or in the `!=` token.
```csharp
unsafe void M(void* v)
{
    _ = (int*)v != null;
}
```
**Expected Behavior**:
No exception.

**Actual Behavior**:
A gold bar appears: "Feature 'Document highlights' is currently unavailable due to an internal error."

```
StreamJsonRpc.RemoteInvocationException: Cannot generated a documentation comment id for symbol.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.InvalidOperationException: Cannot generated a documentation comment id for symbol.
      at Microsoft.CodeAnalysis.DocumentationCommentId.DeclarationGenerator.Generator.DefaultVisit(ISymbol symbol)
      at Microsoft.CodeAnalysis.SymbolVisitor`1.VisitPointerType(IPointerTypeSymbol symbol)
      at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.PointerTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor)
      at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
      at Microsoft.CodeAnalysis.SymbolVisitor`1.Visit(ISymbol symbol)
      at Microsoft.CodeAnalysis.DocumentationCommentId.DeclarationGenerator.Generator.VisitMethod(IMethodSymbol symbol)
      at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.MethodSymbol.Accept[TResult](SymbolVisitor`1 visitor)
      at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
      at Microsoft.CodeAnalysis.SymbolVisitor`1.Visit(ISymbol symbol)
      at Microsoft.CodeAnalysis.DocumentationCommentId.DeclarationGenerator.VisitMethod(IMethodSymbol symbol)
      at Microsoft.CodeAnalysis.DocumentationCommentId.CreateDeclarationId(ISymbol symbol)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.ShouldFindReferencesInGlobalSuppressions(ISymbol symbol, String& documentationCommentId)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.FindReferencesInDocumentInsideGlobalSuppressionsAsync(ISymbol symbol, FindReferencesDocumentState state, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.Finders.OperatorSymbolReferenceFinder.FindReferencesInDocumentAsync(IMethodSymbol symbol, FindReferencesDocumentState state, FindReferencesSearchOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass28_0.<<FindReferencesInDocumentsAsync>g__PerformSearchInDocumentWorkerAsync|4>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass28_0.<<FindReferencesInDocumentsAsync>g__PerformSearchInDocumentAsync|3>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass28_0.<<FindReferencesInDocumentsAsync>g__PerformSearchInProjectAsync|2>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesInDocumentsAsync(ISymbol originalSymbol, IImmutableSet`1 documents, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetTagsForReferencedSymbolAsync(ISymbol symbol, Document document, IImmutableSet`1 documentsToSearch, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsInCurrentProcessAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)

```

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler  to take a look.  We're just taking a method symbol, passed back from the compiler, as an argument to DocumentationCommentId.CreateDeclarationId.  All that API says is:

```c#
        /// <summary>
        /// Creates an id string used by external documentation comment files to identify declarations
        /// of types, namespaces, methods, properties, etc.
        /// </summary>
```

I would not expect any symbol to fail, esp. not because of pointer symbol.  I think the issue is:

```c#
                public override bool VisitMethod(IMethodSymbol symbol)
                {
                    if (this.Visit(symbol.ContainingSymbol))
                    {
```

which likely needs to be:

`if (this.GetReferenceGenerator(symbol).Visit(symbol.ContainingSymbol)` (or somethign like that).

**Comment by CyrusNajmabadi** [comment]
@jcouv can you triage this?

**Comment by autoany** [comment]
Getting these a lot in unsafe context. Example:

```
unsafe struct ByteBuffer(int capacity)
{
	byte* at, end, start;
	byte[] bytes = new byte[capacity];
	GCHandle handle;

	public readonly int size => (int)(at - start);

	public void Pin()
	{
		Debug.Assert(!handle.IsAllocated);

		handle = GCHandle.Alloc(bytes, GCHandleType.Pinned);
		at = start = (byte*)handle.AddrOfPinnedObject();
		end = at + bytes.Length;
```
Just click at the "+" operator on the last line.

**Comment by CyrusNajmabadi** [comment]
Thanks for the repro case!

**Comment by CyrusNajmabadi** [comment]
@jaredpar @jcouv can you assign?

**Comment by jaredpar** [comment]
The docs are a [bit ambiguous](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/#id-strings
) as to whether or not pointers are supposed to be supported as type identifiers. The `T` modifier is listed as only supporting 

> A type is a class, interface, struct, enum, or delegate.

A pointer doesn't fall into that category which is why the compiler generates an error here. Looking through the code it seems it's pretty intentional that it's not supported (not an accident of visiting in the wrong order). 

The code does support them as parts of signatures though. This is also called out as legal in the docs and they have examples. 

Overall it seems like we're following the spec here.

**Comment by CyrusNajmabadi** [comment]
@jaredpar we're not calling this on a type.  We're calling it on a a method (the operator method in this case).

**Comment by jaredpar** [comment]
Gotcha. Even with that though, still seems like it's in the unsupported category. 

> Programs that process the XML file use the ID string to identify the corresponding .NET metadata or reflection item that the documentation applies to.

Pointers don't have members or operators in metadata that we can point to. All of their operations are IL intrinsics. It's not like say `int` where even though we emit intrinsics there are still operators on the types to point to. They just don't exist in metadata at all. 

Unlike `T:` though we don't really parse `M:` in the compiler but other places that do parse `M:` don't seem to [expect pointers](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/DocumentationCommentIdParser.cs#L25) here. 

XML docs are a bit of a nebulous space so it's possible I'm missing something but this seems like intended behavior.

**Comment by CyrusNajmabadi** [comment]
> Pointers don't have members or operators in metadata that we can point to. 

Sure... but how is the IDE to know that.  All we have is a normal IMethodSymbol for a conversion operator, just like any other IMethodSymbol.  

I guess my point is: it's not that we're saying: you must encode this.  We're saying, we have no idea what you would throw on or why, so we probably need a way to find out.  

Otherwise, we'll have to do what we hate doing, which is reimplementing all the compiler logic again in an IDE api that bypasses this issue (which defeats the purpose of us having the apis in the first place) :)

**Comment by CyrusNajmabadi** [comment]
Basically, how do we know if `DocumentationCommentId.CreateDeclarationId` will throw, without reimplementing the logic from DocumentationCommentId.CreateDeclarationId?

**Comment by jaredpar** [comment]
> I guess my point is: it's not that we're saying: you must encode this. We're saying, we have no idea what you would throw on or why, so we probably need a way to find out.

Can't you interpret the exception as "we can't encode this?". Can use a more specific exception if that helps. Or if the exception is problematic can consider switching to a `null` return to indicate can't be encoded.

**Comment by CyrusNajmabadi** [comment]
> Or if the exception is problematic can consider switching to a null return to indicate can't be encoded.

That would be lovely, and would be my preference.  I can work on such a PR :)

**Comment by jaredpar** [comment]
@333fred for any API change concerns here.

**Comment by CyrusNajmabadi** [comment]
Note: having an existing API return null (where it didn't before), is something we've done in teh past :)

given that you would have crashed before, it's generally no worse.

**Comment by CyrusNajmabadi** [comment]
i'll work on a PR and proposal to bring to api review.

**Comment by 333fred** [comment]
Related: https://github.com/dotnet/roslyn/issues/48363
