### ISSUE TITLE
NRE in CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#70178]
**Version Used**: 17.8 Preview 2.0

The syntax it crashed on:

```cs
var permissionIdList = ImmutableArray.Create(permissionId)
    .AddRange(AllPermissions.Where(p => p.IncludedViewModels.Contains(permissionId)).Select(p => p.ViewModel));
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.UseCollectionExpression.UseCollectionExpressionHelpers.<>c__DisplayClass7_0.<IsCollectionFactoryCreate>b__0(AttributeData a)
   at System.Linq.ImmutableArrayExtensions.FirstOrDefault[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Microsoft.CodeAnalysis.CSharp.UseCollectionExpression.UseCollectionExpressionHelpers.IsCollectionFactoryCreate(SemanticModel semanticModel, InvocationExpressionSyntax invocationExpression, MemberAccessExpressionSyntax& memberAccess, Boolean& unwrapArgument, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.UseCollectionExpression.CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.AnalyzeInvocation(UpdateExpressionState`2 state, InvocationExpressionSyntax invocation, ArrayBuilder`1 matchesInReverse, InitializerExpressionSyntax& existingInitializer, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.UseCollectionExpression.CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.AnalyzeInvocation(UpdateExpressionState`2 state, InvocationExpressionSyntax invocation, Boolean addMatches, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.UseCollectionExpression.CSharpUseCollectionExpressionForFluentDiagnosticAnalyzer.AnalyzeMemberAccess(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
```

**Comment by jnm2** [comment]
Guessing because this codebase does not declare CollectionBuilderAttribute.

https://github.com/dotnet/roslyn/blob/8d5504812a765d203adf9531ccca312fe3f82eaa/src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs#L526-L532

**Comment by jnm2** [comment]
@CyrusNajmabadi Also, is this `compilation.CollectionBuilderAttribute().Equals(a.AttributeClass)` going to match when people use the System.Collections.Immutable 8.0.0 package that runs downlevel by declaring its own internal CollectionBuilderAttribute type?
