### ISSUE TITLE
VB Hot Reload bug

### ISSUE THREAD

**Issue by CoolCoderSuper** [dotnet/roslyn#70198]
**Version Used**: 
17.8.0 Preview 2.0
**Steps to Reproduce**:
1. Create a basic VB console app.
2. Loop through something and capture the loop variable in a lambda.

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:
ENC0088
If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
It would hot reload.

**Actual Behavior**:
```
System.InvalidOperationException: Unexpected false - line 620
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Microsoft.CodeAnalysis.VisualBasic.EditAndContinue.VisualBasicEditAndContinueAnalyzer.GetSymbolDeclarationSyntax(ISymbol symbol, Func`2 selector, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.CalculateCapturedVariablesMaps(ImmutableArray`1 oldCaptures, SyntaxNode oldDeclaration, IMethodSymbol oldPrimaryConstructor, ImmutableArray`1 newCaptures, ISymbol newMember, SyntaxNode newDeclaration, IMethodSymbol newPrimaryConstructor, BidirectionalMap`1 bodyMap, ArrayBuilder`1 reverseCapturesMap, ArrayBuilder`1 newCapturesToClosureScopes, ArrayBuilder`1 oldCapturesToClosureScopes, ArrayBuilder`1 diagnostics, Boolean& hasErrors, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaAndClosureRudeEdits(SemanticModel oldModel, ISymbol oldMember, MemberBody oldMemberBody, SyntaxNode oldDeclaration, SemanticModel newModel, ISymbol newMember, MemberBody newMemberBody, SyntaxNode newDeclaration, IReadOnlyDictionary`2 activeOrMatchedLambdas, BidirectionalMap`1 map, EditAndContinueCapabilitiesGrantor capabilities, ArrayBuilder`1 diagnostics, Boolean& syntaxMapRequired, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.AnalyzeChangedMemberBody(SyntaxNode oldDeclaration, SyntaxNode newDeclaration, MemberBody oldMemberBody, MemberBody newMemberBody, SemanticModel oldModel, SemanticModel newModel, ISymbol oldMember, ISymbol newMember, Compilation oldCompilation, SourceText newText, Match`1 topMatch, ImmutableArray`1 oldActiveStatements, ImmutableArray`1 newActiveStatementSpans, EditAndContinueCapabilitiesGrantor capabilities, Builder newActiveStatements, Builder newExceptionRegions, ArrayBuilder`1 diagnostics, Func`2& syntaxMap, CancellationToken cancellationToken)	HotReloadBug	C:\CodingCool\Code\Projects\HotReloadBug\HotReloadBug\Program.vb	2	Active	
   ```

**Comment by CyrusNajmabadi** [comment]
I wasn't able to repro this. Could you flesh out the repro steps with more explicit examples of what you originally wrote, and what you changed it to while debugging?

**Comment by CoolCoderSuper** [comment]
Here is the exact code I'm using.
```vb
Public Module Program
    Public Sub Main(args As String())
        Console.WriteLine("Hello World!")
        Dim numbers As Integer() = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
        For Each i As Integer In numbers
            Console.WriteLine(i)
            Dim y As Integer = numbers.Where(Function(x) x > i).Sum()
        Next
        'insert any statement here
        Console.ReadKey()
    End Sub
End Module
```
I just put a breakpoint in added the line and immediately got the error.
https://github.com/dotnet/roslyn/assets/76707331/7720619a-b4a9-486a-a055-1085fdb6fc57

**Comment by tmat** [comment]
I can repro. Thanks!
