### ISSUE TITLE
`AbstractChangeImplementationCodeRefactoringProvider` crashes with `InvalidOperationException` calling LINQ's `First`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#70232]
```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray)
   at async Microsoft.CodeAnalysis.CSharp.ImplementInterface.AbstractChangeImplementationCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

Minimal repro:

```csharp
interface I
{
    event EventHandler Click;
}

class C : I
{
    event EventHandler I.Click { add { } remove { } }

    event EventHandler I.Click
}
```

**Comment by jasonmalinowski** [comment]
It appears there's been 107 hits in the last week, so we might want to actually fix this sooner.
