### ISSUE TITLE
Assertion failure in semantic model on `foreach` with custom enumerator of pointer type

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#70340]
**Version Used**: VS 17.8 Preview 3

**Steps to Reproduce**:
Paste this code into a C# file in a Visual Studio instance running a debug build of Roslyn.

```csharp
internal class MyEnumerable
{
    public Enumerator GetEnumerator() => new Enumerator();
}

internal unsafe class Enumerator
{
    public int* Current { get; }

    public bool MoveNext() => true;
}

class C
{
    void M()
    {
        foreach (var x in new MyEnumerable())
        {
        }
    }
}
```

**Expected Behavior**: No failed assertion.

**Actual Behavior**: This assertion fails and the members `Enumerator.Current` and `Enumerator.MoveNext` do not display the reference count in CodeLens.

https://github.com/dotnet/roslyn/blob/0caa880a161057559d1dcaad890e4053f520136e/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs#L955

```
System.InvalidOperationException: Assertion failed
      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 24
      at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
      at System.Diagnostics.Debug.Fail(String message, String detailMessage)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetForEachStatementInfo(CommonForEachStatementSyntax node) in A:\dotnet-src\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 955
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetForEachStatementInfo(CommonForEachStatementSyntax node) in A:\dotnet-src\roslyn\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 2369
      at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetForEachStatementInfo(SemanticModel semanticModel, CommonForEachStatementSyntax forEachStatement) in A:\dotnet-src\roslyn\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 886
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticFacts.GetForEachSymbols(SemanticModel semanticModel, SyntaxNode forEachStatement) in A:\dotnet-src\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\CSharp\Services\SemanticFacts\CSharpSemanticFacts.cs:line 171
      at Microsoft.CodeAnalysis.LanguageService.AbstractSemanticFactsService.GetForEachSymbols(SemanticModel semanticModel, SyntaxNode forEachStatement) in A:\dotnet-src\roslyn\src\Workspaces\SharedUtilitiesAndExtensions\Workspace\Core\LanguageServices\SemanticsFactsService\AbstractSemanticFactsService.cs:line 164
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.<>c__DisplayClass31_0.<FindReferencesInForEachStatementsAsync>g__CollectMatchingReferences|1(SyntaxNode node, FindReferencesDocumentState state, ArrayBuilder`1 locations) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\Finders\AbstractReferenceFinder.cs:line 403
      at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder.FindReferencesInDocumentAsync(FindReferencesDocumentState state, Func`2 isRelevantDocument, CollectMatchingReferences collectMatchingReferences, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\Finders\AbstractReferenceFinder.cs:line 381
      at Microsoft.CodeAnalysis.FindSymbols.Finders.OrdinaryMethodReferenceFinder.FindReferencesInDocumentAsync(IMethodSymbol symbol, FindReferencesDocumentState state, FindReferencesSearchOptions options, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\Finders\OrdinaryMethodReferenceFinder.cs:line 123
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass20_0.<<ProcessDocumentAsync>g__ProcessDocumentAsync|0>d.MoveNext() in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 295
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, MetadataUnifyingSymbolHashSet symbols, Dictionary`2 symbolToGlobalAliases, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 274
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, MetadataUnifyingSymbolHashSet symbols, Dictionary`2 symbolToGlobalAliases, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 280
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 219
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 232
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 126
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 126
      at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\FindReferences\FindReferencesSearchEngine.cs:line 131
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IStreamingFindReferencesProgress progress, IImmutableSet`1 documents, FindReferencesSearchOptions options, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder_FindReferences_Current.cs:line 64
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IFindReferencesProgress progress, IImmutableSet`1 documents, FindReferencesSearchOptions options, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Core\Portable\FindSymbols\SymbolFinder_FindReferences_Legacy.cs:line 107
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.FindAsync[T](Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Func`2 onResults, Func`2 onCapped, Int32 searchCap, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Features\Core\Portable\CodeLens\CodeLensReferencesService.cs:line 66
      at Microsoft.CodeAnalysis.CodeLens.CodeLensReferencesService.GetReferenceCountAsync(Solution solution, DocumentId documentId, SyntaxNode syntaxNode, Int32 maxSearchResults, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Features\Core\Portable\CodeLens\CodeLensReferencesService.cs:line 93
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.<>c__DisplayClass3_0.<<GetReferenceCountAsync>b__0>d.MoveNext() in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Services\CodeLensReferences\RemoteCodeLensReferencesService.cs:line 55
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext() in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 181
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 121
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 132
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 92
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 118
      at Microsoft.CodeAnalysis.Remote.RemoteCodeLensReferencesService.GetReferenceCountAsync(Checksum solutionChecksum, DocumentId documentId, TextSpan textSpan, Int32 maxResultCount, CancellationToken cancellationToken) in A:\dotnet-src\roslyn\src\Workspaces\Remote\ServiceHub\Services\CodeLensReferences\RemoteCodeLensReferencesService.cs:line 47

```

**Comment by jcouv** [comment]
Confirmed the bug:
```cs
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/70340")]
        public void TODO2()
        {
            var comp = CreateCompilation("""
                internal class MyEnumerable
                {
                    public Enumerator GetEnumerator() => new Enumerator();
                }

                internal unsafe class Enumerator
                {
                    public int* Current { get; }

                    public bool MoveNext() => true;
                }

                class C
                {
                    void M()
                    {
                        foreach (var x in new MyEnumerable())
                        {
                        }
                    }
                }
                """, options: TestOptions.UnsafeDebugDll).VerifyDiagnostics();

            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);
            var loop = tree.GetRoot().DescendantNodes().OfType<ForEachStatementSyntax>().Single();
            var info = model.GetForEachStatementInfo(loop); // hits assertion
        }
```
