### ISSUE TITLE
RValue receivers are improperly spilled in some scenarios

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#70356]
Compile and run:
```
Imports System
Imports System.Threading.Tasks

Structure Item
    Public Property Name As String

    Public Sub GetName(x As Integer)
            Console.WriteLine("GetName: '{0}'", Me.Name.ToString())
    End Sub
End Structure

Class Program
    Shared Sub Main()
        Dim item3 = {New Item With {.Name = "3"}}
        Call3(item3).Wait()
    End Sub

    Private Shared Async Function Call3(item As Item()) As Task
        With (item(0))
            call .GetName(await GetOffsetAsync(0))
        End With
    End Function

    Shared Async Function GetOffsetAsync(i As Integer) As Task(Of Integer)
        await Task.Yield()
        Return i
    End Function

End Class
```

Observed:
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Item.GetName(Int32 x)
   at Program.Call3(Item[] item)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Program.Main()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Comment out ```await Task.Yield()``` and observe expected output:
```
GetName: '3'
```

Works as expected when receiver is explicit:
```
Imports System
Imports System.Threading.Tasks

Structure Item
    Public Property Name As String

    Public Sub GetName(x As Integer)
            Console.WriteLine("GetName: '{0}'", Me.Name.ToString())
    End Sub
End Structure

Class Program
    Shared Sub Main()
        Dim item3 = {New Item With {.Name = "3"}}
        Call3(item3).Wait()
    End Sub

    Private Shared Async Function Call3(item As Item()) As Task
            call (item(0)).GetName(await GetOffsetAsync(0))
    End Function

    Shared Async Function GetOffsetAsync(i As Integer) As Task(Of Integer)
        await Task.Yield()
        Return i
    End Function

End Class
```

**Comment by AlekseyTs** [comment]
It looks like a scenario with an explicit local is affected as well:
```
Imports System
Imports System.Threading.Tasks

Structure Item
    Public Property Name As String

    Public Sub GetName(x As Integer)
            Console.WriteLine("GetName: '{0}'", Me.Name.ToString())
    End Sub
End Structure

Class Program
    Shared Sub Main()
        Dim item3 = {New Item With {.Name = "3"}}
        Call3(item3).Wait()
    End Sub

    Private Shared Async Function Call3(item As Item()) As Task
            Dim x As Item =item(0)     
            call (x).GetName(await GetOffsetAsync(0))
    End Function

    Shared Async Function GetOffsetAsync(i As Integer) As Task(Of Integer)
        await Task.Yield()
        Return i
    End Function

End Class
```

Observed:
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Item.GetName(Int32 x)
   at Program.Call3(Item[] item)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Program.Main()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
