### ISSUE TITLE
VerifyOverloadsUpdated integration tests are failing

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#70511]
- Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicRename.VerifyOverloadsUpdated (VS2022)
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpRename.VerifyOverloadsUpdated (VS2022)

Failing currently in all integration pipelines.

```
Expected:
[27..37)
[56..66)
[124..134)
[178..188)
Actual:
[27..37)
[124..134)
Differences:
[27..37)
--> [56..66)
[124..134)
--> [178..188)

Expected: True
Actual:   False

Stack trace
   at Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector) in /_/src/Compilers/Test/Core/Assert/AssertEx.cs:line 478
   at Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpRename.<VerifyOverloadsUpdated>d__11.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs:line 393
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by sharwell** [comment]
Manually verified in **Version 17.9.0 Preview 1.0 [34216.205.main]** that the feature does not work (this is a user-visible product regression).

**Comment by pgroene** [comment]
I think our keybinding is registered to the editor context. Does the rename window has its own editor context with the command bind to that context?
