### ISSUE TITLE
Running analyzers on dotnet/runtime yields AD0001 failures from IDE0004

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#70654]
I ran code analysis on all of the libraries in dotnet/runtime, and I encountered multiple AD0001 errors from IDE004, similar to this:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning (active)	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144'.
Exception occurred with following context:
Compilation: Microsoft.Extensions.DependencyInjection.Specification.Tests
SyntaxTree: D:\repos\runtime\src\libraries\Microsoft.Extensions.DependencyInjection.Specification.Tests\src\ActivatorUtilitiesTests.cs
SyntaxNode: (CreateInstanceFunc)CreateInstanceDirectly ... [CastExpressionSyntax]@[1626..1668) (38,37)-(38,79)

System.InvalidOperationException: This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateISymbol()
   at Microsoft.CodeAnalysis.CSharp.Symbol.get_ISymbol()
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.GetITypeSymbol(NullableAnnotation nullableAnnotation)
   at Microsoft.CodeAnalysis.CSharp.BoundExpression.GetPublicTypeSymbol()
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundConversionOperation(BoundConversion boundConversion, Boolean forceOperandImplicitLiteral)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayInitializationOperation(BoundArrayInitialization boundArrayInitialization)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayCreationOperation(BoundArrayCreation boundArrayCreation)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundYieldReturnStatementOperation(BoundYieldReturnStatement boundYieldReturnStatement)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation()
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SpeculativeSemanticModelWithMemberModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsDelegateCreationCastSafeToRemove(ExpressionSyntax castNode, ExpressionSyntax castedExpressionNode, SemanticModel originalSemanticModel, IDelegateCreationOperation originalDelegateCreationOperation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsCastSafeToRemove(ExpressionSyntax castNode, ExpressionSyntax castedExpressionNode, SemanticModel originalSemanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsUnnecessaryCast(CastExpressionSyntax cast, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsUnnecessaryCast(ExpressionSyntax cast, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer.IsUnnecessaryCast(SemanticModel model, ExpressionSyntax cast, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer`2.TryRemoveCastExpression(SemanticModel model, TCastExpression node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer`2.AnalyzeSyntax(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__49`1.<ExecuteSyntaxNodeAction>b__49_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: IDE0004	Microsoft.Extensions.DependencyInjection.Specification.Tests (net8.0)	D:\repos\runtime\src\libraries\Microsoft.Extensions.DependencyInjection.Specification.Tests\src\Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj	1		
```

**Comment by CyrusNajmabadi** [comment]
Adding compiler.  This is a crash in the compiler layer.

**Comment by CyrusNajmabadi** [comment]
@stephentoub are you still seeing this.  I'm guessing no, based on the date and how we haven't heard any more reports.  My guess is that this has just been fixed up since then.

**Comment by stephentoub** [comment]
> [@stephentoub](https://github.com/stephentoub) are you still seeing this. I'm guessing no, based on the date and how we haven't heard any more reports. My guess is that this has just been fixed up since then.

I've not seen it recently.
