### ISSUE TITLE
Test CSharpCompletionCommandHandlerTests.TestNonBlockingExpandCompletionDoesNotChangeItemOrder failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#70835]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=470101&view=ms.vss-test-web.build-test-results-tab&runId=10701172&resultId=208263&paneView=debug

```
Assert.Equal() Failure
Expected: False
Actual:   True



Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState.AssertCompletionItemExpander(Boolean isAvailable, Boolean isSelected) in /_/src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb:line 487
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.VB$StateMachine_371_TestNonBlockingExpandCompletionDoesNotChangeItemOrder.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb:line 10503
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
@genlu
