### ISSUE TITLE
CSharpSpellCheckCodeFixProvider encountered an error in Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.9.0 Preview 1.0

### ISSUE THREAD

**Issue by SmackyPappelroy** [dotnet/roslyn#70830]
When I try to write code in an C# class-library I don't get any code completion. I get this stack trace: 

System.NullReferenceException : Object reference not set to an instance of an object.
   at SyntaxTree.VisualStudio.Unity.Completion.MessageCompletionProvider.get_EnableCompletion()
   at async SyntaxTree.VisualStudio.Unity.Completion.BaseMessageCompletionProvider.ProvideCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.GetContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.ComputeNonEmptyCompletionContextsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by CyrusNajmabadi** [comment]
This appears to be an issue with some unity component crashing.  I'd report the problem to them as well.  Thanks!

-- 

We can see what we can do about trying to be resilient to them crashing.

**Comment by hecram777** [comment]
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.9.0 Preview 1.0

Same here, the project is a 

<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
		<IsPackable>false</IsPackable>
		<SpaRoot>ClientApp\</SpaRoot>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
		<SpaProxyServerUrl>https://localhost:44400</SpaProxyServerUrl>
		<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

Details:
System.NullReferenceException : Object reference not set to an instance of an object.
   at SyntaxTree.VisualStudio.Unity.Completion.MessageCompletionProvider.get_EnableCompletion()
   at async SyntaxTree.VisualStudio.Unity.Completion.BaseMessageCompletionProvider.ProvideCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.GetContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.ComputeNonEmptyCompletionContextsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by CyrusNajmabadi** [comment]
While this is an issue with unity, https://github.com/dotnet/roslyn/pull/70843 will make it so we're at least resilient to them crashing.  You'll get a yellow bar saying they crashed, and we'll disable their provider.

**Comment by jbevain** [comment]
(that's a known issue in 17.9P1, it's already fixed for the next preview. As a workaround you can remove the “Game Development with Unity” workload from your preview install)

**Comment by xela-trawets** [comment]
Just to note fo those searching that the symptom that caught me was that intellisense goes silent for complete-word (ctrl-space, ctrl+K,W, or alt+rightarrow
Removing the Unity work load fixes this, as suggested above, (but it took a while to figure out)

**Comment by adydeshmukh** [comment]
> Just to note fo those searching that the symptom that caught me was that intellisense goes silent for complete-word (ctrl-space, ctrl+K,W, or alt+rightarrow Removing the Unity work load fixes this, as suggested above, (but it took a while to figure out)

This helped me fix issue in my VS2022 Preview
