### ISSUE TITLE
Roslyn generates corrupt assembly with 65535 (0xFFFF) fields - BadImageFormatException (0x8013110E)

### ISSUE THREAD

**Issue by FSDKO** [dotnet/roslyn#70857]
If there are **exact** 65535 fields in an assembly, the roslyn compiler may generate an "corrupt" assembly file.
With one field more or less everything works fine.

Rosyln compiles this assemly without any error or warning. Also dependent projects, that references this, compiles without any error or warning.
But at runtime accessing any type of this "corrupt" assembly results in an [`System.BadImageFormatException`](https://learn.microsoft.com/dotnet/api/system.badimageformatexception):
"File is corrupt. (0x8013110E)"

This problem may be similar to the existing issue #68754.

**Version Used**: 

* 3.0.19.17001 (net48)
* 4.700.23.40302 (Visual Studio 2022 Version 17.7.1)

Target Framework for the Library / Console App:

 * net48 / net48 (❌ fails)
 * netstandard2.0 / net6.0 (❌ fails)
 * net6.0 / net6.0 (❌ fails)
 * net7.0 / net7.0 (✅  works)

**Steps to Reproduce**:

1. Create a class library project "FFFF_Field" with following code:
<details>
  <summary>Generate the complete code...</summary>

  ```c#
    int maxFieldCount = 65535;

    var sb = new StringBuilder();
    sb.AppendLine("namespace FFFF_Field");
    sb.AppendLine("{");

    sb.AppendLine($"    public class MyClass1");
    sb.AppendLine("    {");
    for (int field = 1; field <= 10; field++)
        sb.AppendLine($"        public static readonly string Field_{field:X4} = null;");
    sb.AppendLine("    }");

    sb.AppendLine($"    public class MyClass2");
    sb.AppendLine("    {");
    for (int field = 11; field <= maxFieldCount; field++)
        sb.AppendLine($"        public static readonly string Field_{field:X4} = null;");
    sb.AppendLine("    }");

    sb.AppendLine("    public interface ITest1");
    sb.AppendLine("    {");
    sb.AppendLine($"       string Property {{ get; set; }}");
    sb.AppendLine("    }");

    sb.AppendLine("}");
  ```
</details>

```c#
namespace FFFF_Field
{
    public class MyClass1
    {
        public static readonly string Field_0001 = null;
        public static readonly string Field_0002 = null;
        public static readonly string Field_0003 = null;
        public static readonly string Field_0004 = null;
        public static readonly string Field_0005 = null;
        public static readonly string Field_0006 = null;
        public static readonly string Field_0007 = null;
        public static readonly string Field_0008 = null;
        public static readonly string Field_0009 = null;
        public static readonly string Field_000A = null;
    }
    public class MyClass2
    {
        public static readonly string Field_000B = null;
        public static readonly string Field_000C = null;
        public static readonly string Field_000D = null;
        [...]
        public static readonly string Field_FFFD = null;
        public static readonly string Field_FFFE = null;
        public static readonly string Field_FFFF = null;
    }
    public interface ITest1
    {
       string Property { get; set; }
    }
}
```

2. Create a Console App "ConsoleTest" and reference the class libraray project "FFF_Field":
```c#
using System;

namespace ConsoleTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            try
            {
                Test();
            }
            catch (Exception ex)
            {
                Console.Write(ex.ToString());
            }
            Console.ReadLine();
        }

        private static void Test()
        {
            Console.WriteLine(typeof(FFFF_Field.MyClass1).FullName);
            Console.WriteLine(typeof(FFFF_Field.MyClass2).FullName);
            Console.WriteLine(typeof(FFFF_Field.ITest1).FullName);
        }
    }
}
```

3. Execute the console App

**Diagnostic Id**:

-/-

**Expected Behavior**:

Console-Output:
```console
FFFF_Field.MyClass1
FFFF_Field.MyClass2
FFFF_Field.ITest1
```

**Actual Behavior**:

Console-Output:
```console
System.BadImageFormatException: Could not load file or assembly 'FFFF_Field, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. File is corrupt. (0x8013110E)
File name: 'FFFF_Field, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: File is corrupt. (0x8013110E)
   at ConsoleTest.Program.Test()
   at ConsoleTest.Program.Main(String[] args) in C:\FS\repos\FFFF_Method\TestAssembly\Program.cs:line 9
```

**Comment by AlekseyTs** [comment]
It looks like the Field value for the last TypeDef table is incorrect.
```
 2(0x2): TypeDef              cRecs:    4(0x4), cbRec: 18(0x12), cbTable:    72(0x48)
  col  0:  Flags        oCol: 0, cbCol:4, ULONG  
  col  1:  Name         oCol: 4, cbCol:4, string 
  col  2:  Namespace    oCol: 8, cbCol:4, string 
  col  3:  Extends      oCol: c, cbCol:2, TypeDefOrRef
  col  4:  FieldList    oCol: e, cbCol:2, Field  
  col  5:  MethodList   oCol:10, cbCol:2, Method 
-------------------------------------------------
   1 == 0:00000000, 1:string#6e01d, 2:string#0, 3:TypeDefOrRef[02000000], 4:Field[4000001], 5:Method[6000001]
   2 == 0:00100001, 1:string#15ff6, 2:string#b0026, 3:TypeDefOrRef[0100000d], 4:Field[4000001], 5:Method[6000001]
   3 == 0:00100001, 1:string#21014, 2:string#b0026, 3:TypeDefOrRef[0100000d], 4:Field[400000b], 5:Method[6000002]
   4 == 0:001000a1, 1:string#15fff, 2:string#b0026, 3:TypeDefOrRef[02000000], 4:Field[4000000], 5:Method[6000003]
=================================================
```

The value is 4000000, but I think it should be 4010000.

I think the problem is in the way The table is serialized - https://github.com/dotnet/runtime/blob/45978bd7191fcbb793dc12b162540022063551b6/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataBuilder.Tables.cs#L1970C19-L1970C19
