### ISSUE TITLE
CSharpUsePrimaryConstructorCodeFixProvider threw an exception

### ISSUE THREAD

**Issue by grosch-intl** [dotnet/roslyn#70898]
**Version Used**: 

**Steps to Reproduce**:

I upgraded my project to .NET 8 and got a code fix, so I told it to run, and it threw the exception shown below.  This is what the class has for the constructor:

```csharp
[DatabaseWrapper, RegisteredInterface]
public sealed partial class ActionsRequiredDatabase {
    public DateTime OneYearAgo { get; }
    private readonly int _wwid;

    public ActionsRequiredDatabase(IDbContextFactory<LampContext> contextFactory, ICaller caller) {
        OneYearAgo = DateTime.UtcNow.AddYears(-1);
        _context = contextFactory.CreateDbContext();
        _wwid = caller.Wwid;
    }
```

Those two attributes are custom code generator flags. Not sure if the failure relates to that at all or not, but wanted to point that out.  The generator just creates an `IActionsRequiredDatabase` interface, and applies that interface to the class in the generated code, plus defines some methods. However, neither generator defines any constructors.

**Diagnostic Id**:

IDE0290 Use primary constructor

**Expected Behavior**:

**Actual Behavior**:

System.ArgumentNullException : Value cannot be null.
Parameter name: document
   at async Microsoft.CodeAnalysis.Editing.DocumentEditor.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editing.SolutionEditor.GetDocumentEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CSharp.UsePrimaryConstructor.CSharpUsePrimaryConstructorCodeFixProvider.<>c__DisplayClass17_0.<UsePrimaryConstructorAsync>g__ProcessAssignmentAsync|8(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CSharp.UsePrimaryConstructor.CSharpUsePrimaryConstructorCodeFixProvider.UsePrimaryConstructorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CSharp.UsePrimaryConstructor.CSharpUsePrimaryConstructorCodeFixProvider.UsePrimaryConstructorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by grosch-intl** [comment]
OK, it's definitely the fact a generator is associated.  The generator also is what declares the _context variable there, so if I remove the attributes and add `private readonly LampContext _context;` then your CodeFix will run and I end up with this:

```csharp
public sealed partial class ActionsRequiredDatabase(IDbContextFactory<LampContext> contextFactory, ICaller caller) {
    public DateTime OneYearAgo { get; } = DateTime.UtcNow.AddYears(-1);
    private readonly int _wwid = caller.Wwid;
    private readonly LampContext _context = contextFactory.CreateDbContext();
```

**Comment by jasonmalinowski** [comment]
Probably just needs a filter to filter out generated files.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70718.

**Comment by grosch-intl** [comment]
@CyrusNajmabadi Thanks for fixing.  Do you know what release this will be in?

**Comment by CyrusNajmabadi** [comment]
The linked pr says 17.9 preview2
