### ISSUE TITLE
Failing to build a C# class library project. Unhandled Exception: System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by patryk9200** [dotnet/roslyn#70948]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.9.0 Preview 1.0

Used version of .NET in library project: 8.0

**Steps to Reproduce**:

1. Open a solution in Visual Studio 2022 Version 17.19.0 Preview 1.0
2. Select project to build
3. Wait for project to build.

I don't have a minimal repro and I have a problem to pinpoint the issue to make it.
It works perfectly fine in previous versions of Visual Studio 2022.
When I try to build project then I get an Exception like this:

```
2>------ Rebuild All started: Project: StatesHistory, Configuration: Release Any CPU ------

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Unhandled Exception: System.ArgumentNullException: Value cannot be null.

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Parameter name: key

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Collections.Internal.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Collections.SegmentedDictionary2.FindValue(TKey key)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.<EnsureRequiredMembersCalculated>g__tryCalculateRequiredMembers|189_0(Builder& requiredMembersBuilder)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.EnsureRequiredMembersCalculated()

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.get_AllRequiredMembers()

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.get_HasAnyRequiredMembers()

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.AddRequiredMembersMarkerAttributes(ArrayBuilder1& attributes, MethodSymbol methodToAttribute)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbol.GetCustomAttributesToEmit(PEModuleBuilder moduleBuilder, Boolean emittingAssemblyAttributesInNetModule)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataVisitor.Visit(ITypeDefinitionMember typeMember)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable1 methods)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataVisitor.VisitNestedTypes(IEnumerable1 nestedTypes)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable1 types)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.CreateIndices()

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func1 getPeStream, Func1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable1 privateKeyOpt, CancellationToken cancellationToken)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func1 getPeStream, Func1 getMetadataPeStreamOpt, Func1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable1 privateKeyOpt, CancellationToken cancellationToken)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable1 privateKeyOpt, CancellationToken cancellationToken)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray1 analyzers, ImmutableArray1 generators, ImmutableArray1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray1 sourceFileAnalyzerConfigOptions, ImmutableArray1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable1& generatorTimingInfo)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func2 func)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)

2>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)

2>Done building project "StatesHistory.csproj" -- FAILED.
```

**Expected Behavior**:
I want to build a library C# project in multiple projects solution that I can build perfectly fine in previous versions of Visual Studio 2022.

**Actual Behavior**:
I have a multiple projects solutions where I have one library C# project that I cannot build but I can build it in previous version of Visual Studio (it works in Visual Studio 2022 17.8.1).

**Comment by Robulane** [comment]
Seeing similar issue

**Comment by CyrusNajmabadi** [comment]
@patryk9200 what does this have to do with IDE0030?  It looks like a crash in normal compilation.  Thanks!

**Comment by markjinhua** [comment]
Same issue in Azure and used VisualStudioVersion = 17.8.34330.188

**Comment by 333fred** [comment]
@RealDotNetDave please open a new issue, and include reproduction instructions if possible. If it's something you can only share privately, open a vs feedback ticket and link to it from the new issue.
