### ISSUE TITLE
C# code with lambda in an array causes severl errors in refactoring code provider + diag analysis

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71002]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1919598

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-code-with-lambda-in-an-array-causes-s/10520221)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.7.7]
Added code...

var tests = new[]
            {
                () => 
            };

Encountered several errors, these 2 are the last.

Resulted in... (even after re-starting VS)

StreamJsonRpc.RemoteInvocationException: This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144
   at StreamJsonRpc.JsonRpc. <InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1. <TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidOperationException: This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144
      at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateISymbol()
      at Microsoft.CodeAnalysis.CSharp.Symbol.get_ISymbol()
      at Microsoft.CodeAnalysis.DiagnosticInfo.GetArgumentsToUse(IFormatProvider formatProvider)
      at Microsoft.CodeAnalysis.DiagnosticInfo.GetMessage(IFormatProvider formatProvider)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, ProjectId projectId, String language, DiagnosticDataLocation location, ImmutableArray`1 additionalLocations, ImmutableDictionary`2 additionalProperties)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, TextDocument document)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDocumentDiagnostic(Dictionary`2& map, TextDocument document, Diagnostic diagnostic)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDiagnostics(Dictionary`2& lazyLocals, SyntaxTree tree, IEnumerable`1 diagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions. <ToResultBuilderMapAsync>g__AddDiagnosticsToResult|6_1(ImmutableArray`1 diagnostics, DiagnosticAnalysisResultBuilder& result, Compilation compilation, SyntaxTree tree, DocumentId additionalDocumentId, Nullable`1 span, AnalysisKind kind, ImmutableArray`1 diagnosticIdsToFilter, Boolean includeSuppressedDiagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.ToResultBuilderMapAsync(AnalysisResult analysisResult, ImmutableArray`1 additionalPragmaSuppressionDiagnostics, DocumentAnalysisScope documentAnalysisScope, Project project, VersionStamp version, Compilation compilation, IEnumerable`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0. <<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1. <<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)

====================================

System.InvalidOperationException : This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=146
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateITypeSymbol(NullableAnnotation nullableAnnotation)
   at Microsoft.CodeAnalysis.CSharp.BoundExpression.GetPublicTypeSymbol()
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundConversionOperation(BoundConversion boundConversion,Boolean forceOperandImplicitLiteral)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayInitializationOperation(BoundArrayInitialization boundArrayInitialization)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayCreationOperation(BoundArrayCreation boundArrayCreation)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInitializer(BoundLocalDeclaration boundLocalDeclaration,SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInternal(BoundLocalDeclaration boundLocalDeclaration,SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclarator(BoundNode declaration,SyntaxNode declarationSyntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundLocalDeclarationOperation(BoundLocalDeclaration boundLocalDeclaration)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundTryStatementOperation(BoundTryStatement boundTryStatement)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateMethodBodyOperation(BoundNonConstructorMethodBody boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation()
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`3.FindDisposableLocalDeclarationAsync[TStatementSyntax,TLocalDeclarationSyntax,TTryStatementSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`3.ComputeRefactoringsAsync[TStatementSyntax,TLocalDeclarationSyntax,TTryStatementSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

---
#### Feedback Bot on 11/20/2023, 00:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
```
        [Fact]
        [WorkItem("https://github.com/dotnet/roslyn/issues/71002")]
        public void ArrayInitializer()
        {
            var source =
@"class Program
{
    static void Main()
    {
        var tests = new[]
        {
        () =>
        };
    }
}";

            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();
        }
```

Observed:
```
Starting:    Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests
  Microsoft.CodeAnalysis.CSharp.UnitTests.DelegateTypeTests.ArrayInitializer [FAIL]
    System.InvalidOperationException : This program location is thought to be unreachable. File=src\Compilers\CSharp\Portable\Symbols\FunctionTypeSymbol.cs' Line=144
    Stack Trace:
      src\Compilers\CSharp\Portable\Symbols\FunctionTypeSymbol.cs(144,0): at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateISymbol()
      src\Compilers\CSharp\Portable\Symbols\Symbol.cs(1806,0): at Microsoft.CodeAnalysis.CSharp.Symbol.get_ISymbol()
      src\Compilers\CSharp\Portable\Symbols\Symbol.cs(329,0): at Microsoft.CodeAnalysis.CSharp.Symbol.Microsoft.CodeAnalysis.Symbols.ISymbolInternal.GetISymbol()
      src\Compilers\Core\Portable\Diagnostic\DiagnosticInfo.cs(343,0): at Microsoft.CodeAnalysis.DiagnosticInfo.GetArgumentsToUse(IFormatProvider formatProvider)
      src\Compilers\Core\Portable\Diagnostic\DiagnosticInfo.cs(327,0): at Microsoft.CodeAnalysis.DiagnosticInfo.GetMessage(IFormatProvider formatProvider)
      src\Compilers\Core\Portable\Diagnostic\DiagnosticWithInfo.cs(101,0): at Microsoft.CodeAnalysis.DiagnosticWithInfo.GetMessage(IFormatProvider formatProvider)
      src\Compilers\Core\Portable\Diagnostic\DiagnosticFormatter.cs(56,0): at Microsoft.CodeAnalysis.DiagnosticFormatter.Format(Diagnostic diagnostic, IFormatProvider formatter)
      src\Compilers\CSharp\Portable\Errors\CSDiagnostic.cs(23,0): at Microsoft.CodeAnalysis.CSharp.CSDiagnostic.ToString()
      src\Compilers\Test\Core\Diagnostics\DiagnosticDescription.cs(521,0): at Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription.GetAssertText(DiagnosticDescription[] expected, IEnumerable`1 actual, DiagnosticDescription[] unmatchedExpected, IEnumerable`1 unmatchedActual)
      src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(98,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
      src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(48,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
      src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(63,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
      src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(109,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
      src\Compilers\CSharp\Test\Semantic\Semantics\DelegateTypeTests.cs(18279,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.DelegateTypeTests.ArrayInitializer()
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
