### ISSUE TITLE
[Test Failure] Build Timed Out in prtest/win/vsi/p3 on PR #7114

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7126]
PR: [#7114](https://github.com/dotnet/roslyn/pull/7114) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/67/

**Issue 1: Build Timed Out**
The build timed out, or was forcible aborted after reaching the maximum length. View the log right before the flagged timeout message to see what was happening.

**Comment by davkean** [comment]
@heejaechang Can you figure out which test is failing here?

@brettfo/@dpoeschl why aren't we getting screenshots for this failure?

**Comment by brettfo** [comment]
Screenshot failure is due to this:

```
System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
    at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
    at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)
    at Roslyn.Hosting.Test.ScreenshotExceptionLogger.SaveScreenToFile(String fileName) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Closed\Hosting\Test\Execution\Logging\ScreenshotExceptionLogger.cs:line 52
    at Roslyn.Hosting.Test.ScreenshotExceptionLogger.SaveScreen(String description) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p3\Closed\Hosting\Test\Execution\Logging\ScreenshotExceptionLogger.cs:line 24
```

@dpoeschl, does that mean there wasn't a console session?  Is your PR to fail-fast TAO if there's no console merged?

**Comment by davkean** [comment]
@Brettfo where did you see that?

**Comment by dpoeschl** [comment]
@brettfo Yeah, I don't see that either.

**Comment by dpoeschl** [comment]
@brettfo It was merged: https://github.com/dotnet/roslyn-internal/pull/410

**Comment by dpoeschl** [comment]
Oh I see it in places. See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/67/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpNavigationBar.html

**Comment by dpoeschl** [comment]
Yes, this seems to indicate that the screenshot-check failed. I'll investigate that part.

**Comment by davkean** [comment]
Hitting this pretty consistently. @heejaechang Can you figure out what test is failing and disable it?

**Comment by davkean** [comment]
@heejaechang how did you go with this?

**Comment by heejaechang** [comment]
I will take a look tonight.

**Comment by heejaechang** [comment]
dupe to this - https://github.com/dotnet/roslyn/issues/7193
