### ISSUE TITLE
Can not get compilation object for web aplications

### ISSUE THREAD

**Issue by technites-pl** [dotnet/roslyn#71302]
**Version Used**: 4.8.0, 4.9.0-1.final

**Steps to Reproduce**:

1. Create solution with two default web applications one targeting .net 6, the other targeting .net7.
2. Create class library targeting .net6 with code (see below) that tries to get compilation object for further analysis.
3. Create two console applications referencing library from point 2 one targeting .net 6, the other targeting .net7. Call `MyAnalyzer.Analyse` method passing path to solution created in point 1. 
4. Run both console applications and see errors in console.

```
public static class MyAnalyzer
{
    static MyAnalyzer() => MSBuildLocator.RegisterDefaults();

    public static async Task Analyse(string slnPath)
    {
        var workspace = MSBuildWorkspace.Create();
        workspace.SkipUnrecognizedProjects = true;
        workspace.WorkspaceFailed += (_, args) => Console.WriteLine($"Workspace diagnostic: {args.Diagnostic.Message}");
        var solution = await workspace.OpenSolutionAsync(slnPath);

        foreach (var project in solution.Projects)
        {
            try
            {
                var compilation = await Compile(project);
                Console.WriteLine(compilation is null
                    ? $"Compilation failed for: {project.Name}"
                    : $"Compilation succeeded for: {project.Name}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Console.WriteLine($"Compilation failed for: {project.Name}");
            }
        }
    }

    private static async Task<Compilation?> Compile(Project project)
    {
        var targetFramework = XDocument.Load(project.FilePath!).Descendants("TargetFramework").First().Value;
        var references = targetFramework switch
        {
            "net6.0" => Net60.References.All,
            "net7.0" => Net70.References.All,
            _ => throw new ArgumentOutOfRangeException()
        };
        project = project.AddMetadataReferences(references);
        var compilation = await project.GetCompilationAsync();
        if (compilation is null)
        {
            Console.WriteLine($"Can not compile project: {project.Name}");
            return null;
        }

        var diagnostics = compilation.GetDiagnostics();
        foreach (var diagnostic in diagnostics.Where(d => d.Severity != DiagnosticSeverity.Hidden))
            Console.WriteLine($"Compilation diagnostic: [{diagnostic.Severity}] {diagnostic.GetMessage()}");
        return diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error)
            ? null
            : compilation;
    }
}
```

Repository with full code needed to reproduce is here: https://github.com/technites-pl/roslyn

**Expected Behavior**:

Both console console applications can compile both web applications.

**Actual Behavior**:

Console application targeting .net6 can not compile .net 7 web application. Error: 
`Type or namespace 'AspNetCore' is not present in namespace 'Microsoft' (am I missing an assembly reference?)`

Console application targeting .net7 can not compile both web applications. Error:
```
Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.
   at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGenerators(Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.ComputeNewGeneratorInfoInCurrentProcessAsync(SolutionState solution, Compilation compilationWithoutGeneratedFiles, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.ComputeNewGeneratorInfoAsync(SolutionState solution, Compilation compilationWithoutGeneratedFiles, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.AddExistingOrComputeNewGeneratorInfoAsync(SolutionState solution, Compilation compilationWithoutGeneratedFiles, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGeneratedFiles, CompilationTrackerGeneratorInfo generatorInfo, Compilation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoFromScratchAsync(SolutionState solution, CompilationTrackerGeneratorInfo generatorInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(SolutionState solution, CancellationToken cancellationToken)
   at Analyzer.MyAnalyzer.Compile(Project project) in Analyzer/MyAnalyzer.cs:line 47
   at Analyzer.MyAnalyzer.Analyse(String slnPath) in Analyzer/MyAnalyzer.cs:line 24
```

Class libraries compiles correctly in both cases.

**Comment by JoeRobich** [comment]
@technites-pl The issue may be related with how MSBuildWorkspace loads the projects in process. Starting with 4.9.0-2.final projects are loaded out of process. Do you have better luck using that version of MSBuildWorkspace?

**Comment by jasonmalinowski** [comment]
The issues with the "method not found" should be fixed not necessarily by the OOP work but by us now bundling the external access binary that wasn't deployed earlier. That's still a part of 4.9.0-2.final though so @JoeRobich's suggestion is great.

**Comment by technites-pl** [comment]
@jasonmalinowski you're right, now it's not necessary. It's a big simplification that you don't have to worry about loading metadata references manually. Thanks!

Has project's target framework (or even multiple frameworks) any impact on getting compilation object and analyzing semantic model? Is there anything I should think about writing standalone application that analyzes semantic model for arbitrary any .net solution?

**Comment by jasonmalinowski** [comment]
> Is there anything I should think about writing standalone application that analyzes semantic model for arbitrary any .net solution?

There were a lot of caveats and challenges prior to the 4.9.0-2.final packages you're on now, but we did some pretty fundamental changes to address that so you should be good. (And I appreciate hearing that it's working for you -- so that means I didn't screw anything up! :smile:) The main thing at this point is we still will assume you have the appropriate SDK installed for your project, and make sure NuGet restore has ran so all packages are present prior to using MSBuildWorkspace.

For multiple target frameworks you'll get multiple Projects in the workspace that each have their own compilations/semantic models, which could of course be different in interesting ways. But it _should_ work. If you find  yourself having to do more workarounds let us know since that's something we should be fixing on our side.

**Comment by jasonmalinowski** [comment]
Sounds like this is all addressed, so going to close this out. If you hit new issues (which I can't rule out given the changes made) let us know!
