### ISSUE TITLE
[Test Failure] WpfTestCase failed due to task being disposed before it reaches completion state

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7130]
http://dotnet-ci.cloudapp.net/view/roslynpr/job/roslyn_prtest_win_dbg_unit32/1658/

http://dotnet-ci.cloudapp.net/view/roslynpr/job/roslyn_prtest_win_dbg_unit32/1658/artifact/Binaries/Debug/xUnitResults/Roslyn.Services.Editor.CSharp.UnitTests2.dll.out.log

    Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Recommendations.InterfaceKeywordRecommenderTests.AfterUsing
  Finished:    Roslyn.Services.Editor.CSharp.UnitTests2
=== TEST EXECUTION SUMMARY ===
   Roslyn.Services.Editor.CSharp.UnitTests2  Total: 0
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at Roslyn.Test.Utilities.WpfTestCase.<>c__DisplayClass2_0.<<RunAsync>b__0>d.MoveNext() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\EditorFeatures\TestUtilities\Threading\WpfTestCase.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()

**Comment by heejaechang** [comment]
this seems same issue 
http://dotnet-ci.cloudapp.net/view/roslynpr/job/roslyn_prtest_win_dbg_unit64/1638/

**Comment by jasonmalinowski** [comment]
This was just an issue with my PR I didn't catch locally.
