### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.Scripting throws exception in .Net 8 Standalone Blazor Wasm

### ISSUE THREAD

**Issue by roysurles** [dotnet/roslyn#71371]
.Net 8 & Visual Studio 2022

https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md
1.   Create a new Standalone Blazor Wasm app
2.   Install nuget package: Microsoft.CodeAnalysis.CSharp.Scripting
3.   Add the following statement to Home.razor OnInitializedAsync() method
var result = await CSharpScript.EvaluateAsync("1 + 2");
4.  Run the app

**Expected Behavior**:
This works in a new Console app and should work in Blazor Wasm

**Actual Behavior**:
Throws exception:
System.NotSupportedException: Can't create a metadata reference to an assembly without location.
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly)
   at Microsoft.CodeAnalysis.Scripting.Script.GetReferencesForCompilation(CommonMessageProvider messageProvider, DiagnosticBag diagnostics, MetadataReference languageRuntimeReferenceOpt)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScriptCompiler.CreateSubmission(Script script)
   at Microsoft.CodeAnalysis.Scripting.Script.GetCompilation()
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[Object](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[Object](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at BlazorWasmCalculator.Pages.CalculatorComponent.OnInitializedAsync() in C:\Users\surle\source\repos\BlazorChallenges\src\net8\BlazorWasmCalculator\Pages\CalculatorComponent.razor:line 152
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by hawkerm** [comment]
Even though this is older, there's more info/discussion in #74555, so this should probably be closed as the duplicate?
