### ISSUE TITLE
Null reference exception in code fix provider for IDE0045

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#71403]
**Version Used**: `4.8.0-7.23558.1 (e0917286)`

**Steps to Reproduce**:
Create a new console project and set Program.cs to the following
```cs
object? x = null;
object? y = null;
object? z;

if (x != null)
{
    z = x;
}
else
{
    z = y;
}

Console.WriteLine($"{x}{y}{z}");
```
Create a .editorconfig file and paste in the following
```ini
[*.cs]
root = true
dotnet_diagnostic.IDE0045.severity = warning
dotnet_style_prefer_conditional_expression_over_assignment = true
```

Open the project in Visual Studio and hover over the if statement to get the code fix

**Diagnostic Id**: IDE0045

**Expected Behavior**: Code fix shows up and suggests rewriting the if statement as `z = x ?? y;` or `z = (x != null) ? x : y;`

**Actual Behavior**: Code fix provider crashes
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.UseConditionalExpression.UseConditionalExpressionForAssignmentHelpers.TryMatchPattern(ISyntaxFacts syntaxFacts,IConditionalOperation ifOperation,Boolean& isRef,IOperation& trueStatement,IOperation& falseStatement,ISimpleAssignmentOperation& trueAssignment,ISimpleAssignmentOperation& falseAssignment)
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionForAssignmentCodeFixProvider`6.FixOneAsync[TStatementSyntax,TIfStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TExpressionSyntax,TConditionalExpressionSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.UseConditionalExpression.AbstractUseConditionalExpressionCodeFixProvider`4.FixAllAsync[TStatementSyntax,TIfStatementSyntax,TExpressionSyntax,TConditionalExpressionSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by vibeeshan025** [comment]
Shall I try this Item?

**Comment by CyrusNajmabadi** [comment]
You're definitely welcome to!

**Comment by vibeeshan025** [comment]
`        public SyntaxNode FindNode(TextSpan span, bool findInsideTrivia = false, bool getInnermostNodeForTie = false)
`

It seems the find FindNode method returns a wrapped Node which is from `GlobalStatementSyntax ` in Root level statement files. We don't get this wrapper node if we do the same with an IF condition within a method. 

Since the return Node type is `GlobalStatementSyntax `, the `AbstractUseConditionalExpressionForReturnCodeFixProvider`.`FixOneAsync` raises an exception at below code. 

` var ifOperation = (IConditionalOperation)semanticModel.GetOperation(ifStatement, cancellationToken)!;`

So the solution is either to 

1. Remove the wrapper, from where it gets created. It's not feasible since I believe a lot of logic depends on this for Root Level Statements.
2. The FindNode method should not return the wrapper, instead, it should return the actual `IF `Node.

Since Implementing the 2nd one is much easier and less breaking changes, one of the major problems is `GlobalStatementSyntax `is specific to C# and should not be exposed to `Microsoft.CodeAnalysis` project.

below are my two suggestions.

Check the last If statement.
```
  while (true)
  {
      var parent = node.Parent;
      // NOTE: We care about FullSpan equality, but FullWidth is cheaper and equivalent.
      if (parent == null || parent.FullWidth != node.FullWidth) break;
      // prefer child over compilation unit
      if (parent == cuRoot) break;
      // Special Cases in Languages Like C# where Top-Level Statements are supported.
      if (parent.FullSpan == node.FullSpan && (parent.Parent == null && !parent.HasErrors && !node.HasErrors || parent.Parent == cuRoot)) break;

      node = parent;
  }
```

Or we will create a base Class / Interface to denote `GlobalStatementSyntax ` in which resides inside Microsoft.CodeAnalysis project and the GlobalStatementSyntax class inside the Microsoft.CodeAnalysis.CSharp project will inherit or implement it. So that we know they are of social node and we can break the loop early.  (This may be helpful in case we may introduce such a feature to VB.NET in the future 😄  )

**Comment by CyrusNajmabadi** [comment]
Use `getInnermostNodeForTie: true`

**Comment by vibeeshan025** [comment]
> Use `getInnermostNodeForTie: true`

Ohh my bad. Thanks. Its done.

**Comment by CyrusNajmabadi** [comment]
@vibeeshan025 Were you planning on opening a PR for this?

**Comment by jjonescz** [comment]
A PR referencing this issue is here: https://github.com/dotnet/roslyn/pull/71420

**Comment by vibeeshan025** [comment]
> A PR referencing this issue is here: https://github.com/dotnet/roslyn/pull/71420

Sure I will start working on this.
