### ISSUE TITLE
Initializing a ConcurrentBag with a dynamic variable using a collection initializer results in MSB6006 "csc.exe" exited with code -2146232797

### ISSUE THREAD

**Issue by cgallimore1** [dotnet/roslyn#71703]
**Version Used**: Visual studio 17.8.4 .NET 8.0.101

**Steps to Reproduce**: Run code analysis or build the following code with analyzers enabled:

```cs
dynamic testVar = "test";
ConcurrentBag<object> testBag = [testVar];
```

Event viewer stack trace:
```
Application: csc.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.VisitNoneOperation(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.VisitChildrenOperations(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.OperationMapBuilder.Walker.DefaultVisit(IOperation operation, Dictionary`2 argument)
   at Microsoft.CodeAnalysis.Operations.OperationWalker`1.Visit(IOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationBlocksToAnalyze(ImmutableArray`1 executableBlocks, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass11_0.<ExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|2()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, GroupedAnalyzerActions coreActions, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, Boolean isGeneratedCodeSymbol, IGroupedAnalyzerActions additionalPerSymbolActions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessSymbolDeclaredAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessEventCoreAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventAsync>d__134.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity, Boolean)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportAndPropagateUnlessCanceled(System.Exception, System.Threading.CancellationToken, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__133, Microsoft.CodeAnalysis, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessCompilationEventsCoreAsync>d__133 ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass132_0+<<ProcessCompilationEventsAsync>b__2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass132_0+<<ProcessCompilationEventsAsync>b__2>d, Microsoft.CodeAnalysis, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<ProcessCompilationEventsAsync>b__2>d ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass132_0.<ProcessCompilationEventsAsync>b__2()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Diagnostic Id**: `"MSB6006"`

**Expected Behavior**: Code analysis doesn't crash

**Actual Behavior**: MSB6006	"csc.exe" exited with code -2146232797.

**Note**: Adding `<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>` to the `.csproj` results in a successful compile

**Comment by cston** [comment]
@cgallimore1, thanks for reporting this issue.

The issue has been fixed in 17.9 with https://github.com/dotnet/roslyn/pull/70650.
