### ISSUE TITLE
Some services crash when interpolating strings using switch expressions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71754]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Some-services-crash-when-interpolating-s/10565581)._

---
[severity:It bothers me. A fix would be nice]
Some services will crash when typing '.'

```cs
var obj = new { Value = 1 };
Console.WriteLine($"{obj. switch { }}");
```

![image.png](https://aka.ms/dc/image?name=B4295063d2219402c9b653bbe8bcab63d638413218960258627_20240120-123135-image.png&tid=4295063d2219402c9b653bbe8bcab63d638413218960258627)

One of the crash logs:
```
System.InvalidOperationException : Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorkerFromParent(SyntaxNode parent,SyntaxNode node,ExpressionSyntax expression,Nullable`1 token)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(SyntaxNode node)
   at Microsoft.CodeAnalysis.LanguageService.TypeInferenceService.AbstractTypeInferenceService.AbstractTypeInferrer.InferTypes(SyntaxNode expression,Boolean filterUnusable)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInMemberAccessExpression(MemberAccessExpressionSyntax memberAccessExpression,ExpressionSyntax expressionOpt,Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorkerFromParent(SyntaxNode parent,SyntaxNode node,ExpressionSyntax expression,Nullable`1 token)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position)
   at Microsoft.CodeAnalysis.LanguageService.TypeInferenceService.AbstractTypeInferenceService.InferTypes(SemanticModel semanticModel,Int32 position,String nameOpt,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext.. ctor(Document document,SemanticModel semanticModel,Int32 position,SyntaxToken leftToken,SyntaxToken targetToken,Boolean isAnyExpressionContext,Boolean isAtEndOfPattern,Boolean isAtStartOfPattern,Boolean isAttributeNameContext,Boolean isAwaitKeywordContext,Boolean isEnumBaseListContext,Boolean isEnumTypeMemberAccessContext,Boolean isGenericConstraintContext,Boolean isGlobalStatementContext,Boolean isInImportsDirective,Boolean isInQuery,Boolean isTaskLikeTypeContext,Boolean isNameOfContext,Boolean isNamespaceContext,Boolean isNamespaceDeclarationNameContext,Boolean isOnArgumentListBracketOrComma,Boolean isPossibleTupleContext,Boolean isPreProcessorDirectiveContext,Boolean isPreProcessorExpressionContext,Boolean isRightAfterUsingOrImportDirective,Boolean isRightOfNameSeparator,Boolean isRightSideOfNumericType,Boolean isStatementContext,Boolean isTypeContext,Boolean isWithinAsyncMethod, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.. ctor(Document document,SemanticModel semanticModel,Int32 position,SyntaxToken leftToken,SyntaxToken targetToken,TypeDeclarationSyntax containingTypeDeclaration,BaseTypeDeclarationSyntax containingTypeOrEnumDeclaration,Boolean isAnyExpressionContext,Boolean isAtEndOfPattern,Boolean isAtStartOfPattern,Boolean isAttributeNameContext,Boolean isAwaitKeywordContext,Boolean isCatchFilterContext,Boolean isConstantExpressionContext,Boolean isCrefContext,Boolean isDefiniteCastTypeContext,Boolean isDelegateReturnTypeContext,Boolean isDestructorTypeContext,Boolean isEnumBaseListContext,Boolean isEnumTypeMemberAccessContext,Boolean isFixedVariableDeclarationContext,Boolean isFunctionPointerTypeArgumentContext,Boolean isGenericConstraintContext,Boolean isGenericTypeArgumentContext,Boolean isGlobalStatementContext,Boolean isImplicitOrExplicitOperatorTypeContext,Boolean isInImportsDirective,Boolean isInNonUserCode,Boolean isInQuery,Boolean isInstanceContext,Boolean isTaskLikeTypeContext,Boolean isIsOrAsOrSwitchOrWithExpressionContext,Boolean isIsOrAsTypeContext,Boolean isLabelContext,Boolean isLeftSideOfImportAliasDirective,Boolean isLocalFunctionDeclarationContext,Boolean isLocalVariableDeclarationContext,Boolean isNameOfContext,Boolean isNamespaceContext,Boolean isNamespaceDeclarationNameContext,Boolean isNonAttributeExpressionContext,Boolean isObjectCreationTypeContext, Boolean isOnArgumentListBracketOrComma,Boolean isParameterTypeContext,Boolean isPossibleLambdaOrAnonymousMethodParameterTypeContext,Boolean isPossibleTupleContext,Boolean isPreProcessorDirectiveContext,Boolean isPreProcessorExpressionContext,Boolean isPreProcessorKeywordContext,Boolean isPrimaryFunctionExpressionContext,Boolean isRightAfterUsingOrImportDirective,Boolean isRightOfNameSeparator,Boolean isRightSideOfNumericType,Boolean isStatementContext, Boolean isTypeArgumentOfConstraintContext,Boolean isTypeContext,Boolean isTypeOfExpressionContext,Boolean isUsingAliasTypeContext,Boolean isWithinAsyncMethod,ISet`1 precedingModifiers,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker(Document document,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContextService.CreateContext(Document document,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractImportCompletionProvider.CreateContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.Providers.AbstractImportCompletionProvider.ProvideCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

---
#### Feedback Bot on 1/21/2024, 11:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/71612.
