### ISSUE TITLE
Failed assert at AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.GetSemanticModel

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#72020]
**Version Used**: Using Roslyn bits built from main branch as of today 02/09/24

**Steps to Reproduce**: Hit this while editing code and introducing a compiler error:
1. git clone https://github.com/dotnet/roslyn-analyzers
2. restore
3. Open RoslynAnalyzers.sln
4. Edit the below line to add a semantic error by changing `var operation = operations[i];` to `var operation = operations[builder];`: https://github.com/dotnet/roslyn-analyzers/blob/d0311fbcd264aaba20544e611e04976c4ada57da/src/Utilities/Compiler/Extensions/IOperationExtensions.cs#L135

**Assert failure**:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
How?

   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.GetSemanticModel(SyntaxTree tree) in C:\dotnet-roslyn\src\Features\Core\Portable\LanguageServices\SymbolDisplayService\AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs:line 143
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.AddCaptures(SyntaxNode syntax) in C:\dotnet-roslyn\src\Features\Core\Portable\LanguageServices\SymbolDisplayService\AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs:line 237
   at Microsoft.CodeAnalysis.Editor.CSharp.LanguageServices.CSharpSymbolDisplayService.SymbolDescriptionBuilder.AddCaptures(ISymbol symbol) in C:\dotnet-roslyn\src\Features\CSharp\Portable\LanguageServices\CSharpSymbolDisplayService.SymbolDescriptionBuilder.cs:line 201
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<AddPartsAsync>d__30.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\LanguageServices\SymbolDisplayService\AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs:line 163
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.AddPartsAsync(ImmutableArray`1 symbols)
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<BuildDescriptionSectionsAsync>d__37.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\LanguageServices\SymbolDisplayService\AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs:line 292
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.BuildDescriptionSectionsAsync(ImmutableArray`1 symbolGroup)
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.<ToDescriptionGroupsAsync>d__7.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\LanguageServices\SymbolDisplayService\AbstractSymbolDisplayService.cs:line 54
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.LanguageService.AbstractSymbolDisplayService.ToDescriptionGroupsAsync(SemanticModel semanticModel, Int32 position, ImmutableArray`1 symbols, SymbolDescriptionOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoUtilities.<CreateQuickInfoItemAsync>d__1.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\QuickInfoUtilities.cs:line 39
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoUtilities.CreateQuickInfoItemAsync(SolutionServices services, SemanticModel semanticModel, TextSpan span, ImmutableArray`1 symbols, SupportedPlatformData supportedPlatforms, Boolean showAwaitReturn, NullableFlowState flowState, SymbolDescriptionOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.CreateContentAsync(SolutionServices services, SemanticModel semanticModel, SyntaxToken token, TokenInformation tokenInformation, SupportedPlatformData supportedPlatforms, SymbolDescriptionOptions options, CancellationToken cancellationToken) in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\CommonSemanticQuickInfoProvider.cs:line 173
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<BuildQuickInfoAsync>d__0.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\CommonSemanticQuickInfoProvider.cs:line 32
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.BuildQuickInfoAsync(QuickInfoContext context, SyntaxToken token)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__6.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\CommonQuickInfoProvider.cs:line 76
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.GetQuickInfoAsync(QuickInfoContext context, SyntaxToken token)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__2.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\CommonQuickInfoProvider.cs:line 25
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.GetQuickInfoAsync(QuickInfoContext context)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoServiceWithProviders.<>c__DisplayClass4_1.<GetQuickInfoAsync>b__0() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\QuickInfoServiceWithProviders.cs:line 64
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext() in C:\dotnet-roslyn\src\Workspaces\Core\Portable\ExtensionManager\IExtensionManagerExtensions.cs:line 80
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](IExtensionManager extensionManager, Object extension, Func`1 function, T defaultValue)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoServiceWithProviders.<GetQuickInfoAsync>d__4.MoveNext() in C:\dotnet-roslyn\src\Features\Core\Portable\QuickInfo\QuickInfoServiceWithProviders.cs:line 58
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.QuickInfo.QuickInfoServiceWithProviders.GetQuickInfoAsync(Document document, Int32 position, SymbolDescriptionOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.QuickInfoSourceProvider.QuickInfoSource.<GetQuickInfoItemAsync>d__8.MoveNext() in C:\dotnet-roslyn\src\EditorFeatures\Core\IntelliSense\QuickInfo\QuickInfoSourceProvider.QuickInfoSource.cs:line 79
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.QuickInfoSourceProvider.QuickInfoSource.GetQuickInfoItemAsync(IAsyncQuickInfoSession session, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.ComputeSourceContentAsync(IAsyncQuickInfoSource source, IList`1 items, IList`1 applicableToSpans, IList`1 failures, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeContentAsync>d__37.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by CyrusNajmabadi** [comment]
I do not repro this.
