### ISSUE TITLE
Crash when trying to create a netmodule reference during P2P conversion

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#72183]
I have  same problem on 17.9 and 17.10 Preview. It is happenig always after I uupdate and add SDK

```
StreamJsonRpc.RemoteInvocationException: Can't create a reference to a module.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__21.MoveNext()
RPC server exception:
System.NotSupportedException: Can't create a reference to a module.
      at Microsoft.CodeAnalysis.CompilationReference.GetProperties(Compilation compilation, ImmutableArray`1 aliases, Boolean embedInteropTypes)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ToMetadataReference(ImmutableArray`1 aliases, Boolean embedInteropTypes)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetPartialMetadataReference(ProjectState fromProject, ProjectReference projectReference)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetPartialCompilationState(SolutionCompilationState compilationState, DocumentId id, ProjectState& inProgressProject, CompilationPair& compilations, CompilationTrackerGeneratorInfo& generatorInfo, Dictionary`2& metadataReferenceToProjectId, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.FreezePartialStateWithTree(SolutionCompilationState compilationState, DocumentState docState, SyntaxTree tree, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.WithFrozenPartialCompilationIncludingSpecificDocument(DocumentId documentId, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Document.WithFrozenPartialSemantics(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ProcessProjectAsync(Project project, Document specificDocument, Boolean useFrozenSnapshots, ICallback callback, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeDiscoveryService.ProcessSolutionAsync(Solution solution, DocumentId priorityDocumentId, Boolean useFrozenSnapshots, ICallback callback, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<>c__DisplayClass16_0.<<RunServiceAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync(Func`2 implementation, CancellationToken cancellationToken)
```

17.9 after uupdate
![image](https://github.com/dotnet/roslyn/assets/31588744/0d52f158-d333-4b7a-bd61-11ce6404b973)

_Originally posted by @kubakorecek in https://github.com/dotnet/roslyn/issues/72074#issuecomment-1950161737_

**Comment by jasonmalinowski** [comment]
@kubakorecek: in your solution do you have any projects that are changing their output type to output a netmodule?

**Comment by arunchndr** [comment]
Closing since there is no update on the question. Feel free to reopen if this is still an issue.
