### ISSUE TITLE
Explicit interface member completion doesn't work with params collections

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#72224]
```
        [Fact]
        public async Task TestWithParamsCollectionParameter()
        {
            var markup = """
                using System.Collections.Generic;

                interface I
                {
                    void M(params IEnumerable<string> args);
                }

                class C : I
                {
                    void I.$$
                }
                """;

            var expected = """
                using System.Collections.Generic;

                interface I
                {
                    void M(params IEnumerable<string> args);
                }

                class C : I
                {
                    void I.M(params IEnumerable<string> args)
                }
                """;

            await VerifyProviderCommitAsync(markup, "M(params IEnumerable<string> args)", expected, '\t');
        }
```

Observed:
```
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionProviders.ExplicitInterfaceMemberCompletionProviderTests.TestWithParamsCollectionParameter [FAIL]
  Assert.Contains() Failure
  Not found: (filter expression)
  In value:  SegmentedList<CompletionItem> [M(params System.Collections.Generic.IEnumerable<string> args)]
  Stack Trace:
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(588,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitCheckResultsAsync>d__59.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(573,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitWorkerAsync>d__58.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(320,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitAsync>d__45.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\CSharpTest\Completion\CompletionProviders\ExplicitInterfaceMemberCompletionProviderTests.cs(821,0): at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionProviders.ExplicitInterfaceMemberCompletionProviderTests.<TestWithParamsCollectionParameter>d__29.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by CyrusNajmabadi** [comment]
Not repro.  This produces: 

![Image](https://github.com/user-attachments/assets/ae05cab4-b9b4-4b00-80ab-87c5537364e7)

**Comment by AlekseyTs** [comment]
There was a skipped test for this issue. Is it no longer skipped?
