### ISSUE TITLE
NRE in QuickInfo

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#72245]
**Version Used**: 4.10.0-2.24119.2+a9695b10adbb64ee5532468506ec67a48f513083

**Steps to Reproduce**:

I was in https://github.com/dotnet/aspnetcore/blob/f26b79eb34d13648bedc5ec98e2151f8c55db978/src/DataProtection/DataProtection/src/KeyManagement/DefaultKeyResolver.cs with local edits (all comments) but no squiggles.  I've seen it in other files in the same project.

**Actual Behavior**:

Goldbar for
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.WhereAsArrayImpl[T,TArg](ImmutableArray`1 array, Func`2 predicateWithoutArg, Func`3 predicateWithArg, TArg arg)
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, SyntaxToken token, SolutionServices services, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.GetSymbolsFromToken(SyntaxToken token, SolutionServices services, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.BindToken(SolutionServices services, SemanticModel semanticModel, SyntaxToken token, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<ComputeFromLinkedDocumentsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<ComputeQuickInfoDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<BuildQuickInfoAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/71595.
