### ISSUE TITLE
Crash when compiling a VB project

### ISSUE THREAD

**Issue by ddobrev** [dotnet/roslyn#7236]
When I try compiling http://sourceforge.net/p/nicevs/code/HEAD/tree/ with Visual Studio 2015 Update 1, I get:

```
Object reference not set to an instance of an object.

   at Microsoft.CodeAnalysis.VisualBasic.NamespaceScopeBuilder.BuildNamespaceScope(PEModuleBuilder moduleBuilder, Dictionary`2 xmlNamespaces, IEnumerable`1 aliasImports, ImmutableArray`1 memberImports, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFile.TranslateImports(PEModuleBuilder moduleBuilder, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceFile.Translate(PEModuleBuilder moduleBuilder, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.LowerAndEmitMethod(MethodSymbol method, Int32 methodOrdinal, BoundBlock block, Binder binderOpt, TypeCompilationState compilationState, DiagnosticBag diagsForCurrentMethod, ProcessedFieldOrPropertyInitializers processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol constructorToInject, Int32& delegateRelaxationIdDispenser)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(MethodSymbol method, Int32 methodOrdinal, Int32& withEventPropertyIdDispenser, Int32& delegateRelaxationIdDispenser, Predicate`1 filter, TypeCompilationState compilationState, ProcessedFieldOrPropertyInitializers processedInitializers, Binder containingTypeBinder, SynthesizedSubmissionFields previousSubmissionFields, MethodSymbol& referencedConstructor)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType, Predicate`1 filter)
   at Microsoft.CodeAnalysis.VisualBasic.MethodCompiler._Closure$__30-0._Lambda$__0()

HResult: -2147467261
```

**Comment by jaredpar** [comment]
@AlekseyTs can you take a look at this?

**Comment by AlekseyTs** [comment]
@tmat This looks PDB related.

**Comment by AlekseyTs** [comment]
@tmat It looks like you are the author of the Microsoft.CodeAnalysis.VisualBasic.NamespaceScopeBuilder.BuildNamespaceScope method. Could you please take a look.

**Comment by ddobrev** [comment]
Hello, 3 days passed, has there been any progress on this bug? It's critical because I cannot work on the project in question, and perhaps many others.

**Comment by tmat** [comment]
@ddobrev We are working on the fix. Meanwhile to get yourself unblocked you can remove (or comment out) the following import in ```NiceVS.Core\PropertyDictionary.vb```:

```VB
Imports PlatformUI = Microsoft.Internal.VisualStudio.PlatformUI
```

**Comment by jaredpar** [comment]
@tmat why is this bug still open?  Is there more work here?

**Comment by tmat** [comment]
No more work.
