### ISSUE TITLE
CompletionService.GetCompletionsAsync NullReferenceException

### ISSUE THREAD

**Issue by chrisdaiii** [dotnet/roslyn#72389]
**Version Used**: 4.8.0

**Steps to Reproduce**:

1. arg1 `document`
```c#
using Point = int[];

v
```
2. arg2 `position` 
```c#
23
```
3. arg3 `trigger` 
```c#
{
    Kind = CompletionTriggerKind.Invoke,
    Character= 'v'
}
```
4. Invoke
```c#
var service = CompletionService.GetService(document);
await service.GetCompletionsAsync(document, position, trigger: trigger, cancellationToken: cancellationToken);
```

**Actual Behavior**:
```c#
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.Features
  StackTrace:
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractTypeImportCompletionProvider`1.GetAliasTypeDictionary(Document document, SyntaxContext syntaxContext, CancellationToken cancellationToken) in Microsoft.CodeAnalysis.Completion.Providers\AbstractTypeImportCompletionProvider.cs:line 100
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractTypeImportCompletionProvider`1.<AddCompletionItemsAsync>d__4.MoveNext() in Microsoft.CodeAnalysis.Completion.Providers\AbstractTypeImportCompletionProvider.cs:line 72
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractImportCompletionProvider.<ProvideCompletionsAsync>d__9.MoveNext() in Microsoft.CodeAnalysis.Completion.Providers\AbstractImportCompletionProvider.cs:line 63
   at Microsoft.CodeAnalysis.Completion.CompletionService.<GetContextAsync>d__38.MoveNext() in Microsoft.CodeAnalysis.Completion\CompletionService.cs:line 797
   at Microsoft.CodeAnalysis.Completion.CompletionService.<ComputeNonEmptyCompletionContextsAsync>d__33.MoveNext() in Microsoft.CodeAnalysis.Completion\CompletionService.cs:line 740
   at Microsoft.CodeAnalysis.Completion.CompletionService.<GetCompletionsAsync>d__29.MoveNext() in Microsoft.CodeAnalysis.Completion\CompletionService.cs:line 647

  This exception was originally thrown at this call stack:
    Microsoft.CodeAnalysis.Completion.Providers.AbstractTypeImportCompletionProvider<AliasDeclarationTypeNode>.GetAliasTypeDictionary(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext, System.Threading.CancellationToken) in AbstractTypeImportCompletionProvider.cs
    Microsoft.CodeAnalysis.Completion.Providers.AbstractTypeImportCompletionProvider<AliasDeclarationTypeNode>.AddCompletionItemsAsync(Microsoft.CodeAnalysis.Completion.CompletionContext, Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext, System.Collections.Generic.HashSet<string>, System.Threading.CancellationToken) in AbstractTypeImportCompletionProvider.cs
    Microsoft.CodeAnalysis.Completion.Providers.AbstractImportCompletionProvider.ProvideCompletionsAsync(Microsoft.CodeAnalysis.Completion.CompletionContext) in AbstractImportCompletionProvider.cs
    Microsoft.CodeAnalysis.Completion.CompletionService.GetContextAsync(Microsoft.CodeAnalysis.Completion.CompletionProvider, Microsoft.CodeAnalysis.Document, int, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Completion.CompletionOptions, Microsoft.CodeAnalysis.Text.TextSpan, Microsoft.CodeAnalysis.Completion.SharedSyntaxContextsWithSpeculativeModel, System.Threading.CancellationToken) in CompletionService.cs
    Microsoft.CodeAnalysis.Completion.CompletionService.ComputeNonEmptyCompletionContextsAsync(Microsoft.CodeAnalysis.Document, int, Microsoft.CodeAnalysis.Completion.CompletionTrigger, Microsoft.CodeAnalysis.Completion.CompletionOptions, Microsoft.CodeAnalysis.Text.TextSpan, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Completion.CompletionProvider>, Microsoft.CodeAnalysis.Completion.SharedSyntaxContextsWithSpeculativeModel, System.Threading.CancellationToken) in CompletionService.cs
    Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAsync(Microsoft.CodeAnalysis.Document, int, Microsoft.CodeAnalysis.Completion.CompletionOptions, Microsoft.CodeAnalysis.Options.OptionSet, Microsoft.CodeAnalysis.Completion.CompletionTrigger, System.Collections.Immutable.ImmutableHashSet<string>, System.Threading.CancellationToken) in CompletionService.cs
```

When I type 'v' in the editor, an event is triggered and an exception occurs when calling the GetCompletionsAsync service. 
When I remove this code `using Point = int[];` or change it to another type `using Point = (int x, int y);`, everything is normal.
The specific reason is that `ContainingNamespace` is empty

**Comment by ToddGrun** [comment]
Looks to have been fixed by https://github.com/dotnet/roslyn/pull/72401
