### ISSUE TITLE
The server disconnected unexpectedly when using the Microsoft.CodeAnalysis.Workspaces.MSBuild v4.9.2

### ISSUE THREAD

**Issue by hideintheclouds** [dotnet/roslyn#72558]
**Version Used**: 
4.9.2
**Steps to Reproduce**:

- Try to get the solution from a workspace using the following git repo:

https://github.com/mattjhosking/roslyn-analysis/blob/6165100c8b613fe3153a1da76bb6539ebbac4e02/RoslynAnalysis/Program.cs

- When the OpenSolutionAsync is called with:

           `var solution = await workspace.OpenSolutionAsync(fileName, new ProgressBarProjectLoadStatus());` 

The following exception is displayed:
```
System.Exception
HResult=0x80131500
Message=The server disconnected unexpectedly.
Source=Microsoft.CodeAnalysis.Workspaces.MSBuild
StackTrace:
at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.<InvokeCoreAsync>d__15.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.<InvokeAsync>d__141.MoveNext() at Microsoft.CodeAnalysis.MSBuild.Rpc.RemoteBuildHost.<LoadProjectFileAsync>d__5.MoveNext() at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__181.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectFileInfosAsync>d__20.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__21.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__19.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__22.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__22.MoveNext()
at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__24.MoveNext()
at RoslynAnalysis.Model.WorkspaceSolution.<Load>d__2.MoveNext() in C:\RoslynAnalysis\Model\WorkspaceSolution.cs:line 20
```

This behaviour is observed using the **4.9.2** packages:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
	  <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Build" Version="17.9.5" ExcludeAssets="runtime" />
	  <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.9.2" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.9.2" />
  </ItemGroup>

</Project>
```

**Seems to be working fine with the previous version of the CSharp.Workspaces and Workspaces.MSBuild (4.8.0) packages**:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
	  <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Build" Version="17.9.5" ExcludeAssets="runtime" />
	  <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" />
  </ItemGroup>

</Project>
```

**Comment by dibarbet** [comment]
I wasn't able to reproduce this myself after a quick look.  However I would recommend trying a couple things
1.  Try targeting .net8
2.  Try using the latest roslyn package versions - 4.10.0-2.final - there were a couple issues in the first implementation of the initial build host that might have been fixed.

**Comment by Matiszak** [comment]
Hey,
Did maybe anything move forward with this ?
We are facing the same issue and from our perspective seems that file "\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.12.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" has references to 6.0.0 versions of files:
`// Metadata version: v4.0.30319
.module extern libc
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 6:0:0:0
}
.assembly extern System.Collections.Immutable
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 8:0:0:0
}
.assembly extern System.Collections
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 6:0:0:0
}
il`

and at the same time this codes rolls framework to newest one:
https://github.com/dotnet/roslyn/blob/main/src/Workspaces/MSBuild/Core/MSBuild/BuildHostProcessManager.cs#L174-L176

I'm not an expert on such low level stuff but maybe thats the issue ?

Because if we try to run it by hand (what the codeanalysis seems to be doing underneath)
`dotnet --roll-forward LatestMajor C:\\Users\\test\\source\\repos\\RoslynHostTester\\bin\\Debug\\net8.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll --property SolutionDir=C:\\Users\\test\\source\\repos\\RoslynHostTester\\SimpleApp\\` then we get
`
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I'll try to add minimum reproduction example later because it's my colleague that was analyzing it and has all the details.
`

**Comment by jasonmalinowski** [comment]
@Matiszak I wouldn't expect roll forward to then ignore the binary we're shipping, since that'd break rather than work. Please file a new bug and indeed if you have a repro that would be good for us to look at.

**Comment by jasonmalinowski** [comment]
@hideintheclouds Any chance you ever tried moving to a newer version of the packages? We did make a few fixes that could result in this symptom.

**Comment by jasonmalinowski** [comment]
Closing as stale; if folks are still having issues like this absolutely we're happy to take a look.
