### ISSUE TITLE
System.InvalidCastException while typing code

### ISSUE THREAD

**Issue by ArchieCoder** [dotnet/roslyn#72758]
I have the impression that I keep getting the same bunch of errors all the time.

**Question: what do I need to do to avoid them?** Do I click on the button "X" at the right side, click on Enable or click on Enable and ignore future errors?

Here is one that I'm sure I had before:

System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax'.
   at Microsoft.CodeAnalysis.CSharp.LanguageService.CSharpSyntaxFacts.GetPartsOfInvocationExpression(SyntaxNode node,SyntaxNode& expression,SyntaxNode& argumentList)
   at async Microsoft.CodeAnalysis.IntroduceParameter.AbstractIntroduceParameterCodeRefactoringProvider`5.IntroduceParameterDocumentRewriter.ModifyDocumentInvocationsTrampolineOverloadAndIntroduceParameterAsync[TExpressionSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax,TIdentifierNameSyntax,TArgumentSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceParameter.AbstractIntroduceParameterCodeRefactoringProvider`5.IntroduceParameterDocumentRewriter.RewriteDocumentAsync[TExpressionSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax,TIdentifierNameSyntax,TArgumentSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceParameter.AbstractIntroduceParameterCodeRefactoringProvider`5.IntroduceParameterAsync[TExpressionSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax,TIdentifierNameSyntax,TArgumentSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by CyrusNajmabadi** [comment]
@akhera99 ptal.

**Comment by CyrusNajmabadi** [comment]
> I have the impression that I keep getting the same bunch of errors all the time.

Please file issues for the unique stacks you see.

**Comment by CyrusNajmabadi** [comment]
> Question: what do I need to do to avoid them? Do I click on the button "X" at the right side, click on Enable or click on Enable and ignore future errors?

Clickingon the 'x' dismisses hte error.  'Enable' reenables the analyzer/fixer that crashes.  Enable-and-ignore-errors will reneable the analyzer/fixer that crashed, and silence future errors from it within the same VS session.

**Comment by CyrusNajmabadi** [comment]
@akhera99 i think you may have fixed this already.  If so, can you link to the PR for it.   @ArchieCoder can you please include the version of VS you are using when you report these issues.  Thanks :)

**Comment by ArchieCoder** [comment]
Ah, thank you for the explanation of "within the same VS session"! 

I'm on the latest 17.9.5.

**Comment by akhera99** [comment]
> @akhera99 i think you may have fixed this already. If so, can you link to the PR for it. @ArchieCoder can you please include the version of VS you are using when you report these issues. Thanks :)

should be fixed with this PR
https://github.com/dotnet/roslyn/pull/72191
