### ISSUE TITLE
Assertion in `BindCollectionInitializerElementAddMethod` in ref struct error scenario

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#72762]
```cs
        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/72762")]
        public void RefStruct_04()
        {
            var source = """
                using System.Collections;
                using System.Collections.Generic;

                dynamic d = null;
                S s = [d];

                ref struct S : IEnumerable<int>
                {
                    public IEnumerator<int> GetEnumerator() => throw null;
                    IEnumerator IEnumerable.GetEnumerator() => throw null;
                    public void Add<T>(T t) => throw null;
                }
                """;

            // https://github.com/dotnet/roslyn/issues/72762 - There should be diagnostics for S implementing an interface, and
            // there should also be a diagnostic that `s` cannot be used a recevier for a dynamic call.
            CreateCompilation(source).VerifyDiagnostics();
        }
```

```
System.InvalidOperationException : Assertion failed
   at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in /home/fred/git/roslyn/src/Compilers/Test/Core/ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindCollectionInitializerElementAddMethod(SyntaxNode elementInitializer, ImmutableArray`1 boundElementInitializerExpressions, Boolean hasEnumerableInitializerType, Binder collectionInitializerAddMethodBinder, BindingDiagnosticBag diagnostics, BoundObjectOrCollectionValuePlaceholder implicitReceiver) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 5936
   at Microsoft.CodeAnalysis.CSharp.Binder.ConvertCollectionExpression(BoundUnconvertedCollectionExpression node, TypeSymbol targetType, Conversion conversion, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:line 648
   at Microsoft.CodeAnalysis.CSharp.Binder.<CreateConversion>g__createConversion|211_1(SyntaxNode syntax, BoundExpression source, Conversion conversion, Boolean isCast, ConversionGroup conversionGroupOpt, Boolean wasCompilerGenerated, TypeSymbol destination, BindingDiagnosticBag diagnostics, Boolean hasErrors) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:line 241
   at Microsoft.CodeAnalysis.CSharp.Binder.CreateConversion(SyntaxNode syntax, BoundExpression source, Conversion conversion, Boolean isCast, ConversionGroup conversionGroupOpt, Boolean wasCompilerGenerated, TypeSymbol destination, BindingDiagnosticBag diagnostics, Boolean hasErrors) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.Binder.CreateConversion(SyntaxNode syntax, BoundExpression source, Conversion conversion, Boolean isCast, ConversionGroup conversionGroupOpt, TypeSymbol destination, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.Binder.GenerateConversionForAssignment(TypeSymbol targetType, BoundExpression expression, BindingDiagnosticBag diagnostics, Conversion& conversion, ConversionForAssignmentFlags flags) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1966
   at Microsoft.CodeAnalysis.CSharp.Binder.GenerateConversionForAssignment(TypeSymbol targetType, BoundExpression expression, BindingDiagnosticBag diagnostics, ConversionForAssignmentFlags flags) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1909
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, BindingDiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1064
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, BindingDiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 964
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 729
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 691
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 66
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgramCompilationUnit(CompilationUnitSyntax compilationUnit, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3582
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgram(CompilationUnitSyntax compilationUnit, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3565
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, BindingDiagnosticBag diagnostics) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3556
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1775
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 991
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 530
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() in /home/fred/git/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 432
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /home/fred/git/roslyn/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 139
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by 333fred** [comment]
This has been addressed in main.
