### ISSUE TITLE
Error running code action with `EnforceCodeStyleInBuild` in new Roslyn with .NET8 SDK

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#72879]
**Version Used**: 
Using a recent VS version (e.g. 17.11 P1 34801.192) or latest VSCode extension version (e.g. v2.24.17).
As long as the roslyn version contains a version that added this new property - https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/Symbols/IParameterSymbol.cs#L38

**Steps to Reproduce**:

1. Using the IDE version above, open a solution using the .net8 SDK (e.g. global.json)
2. Ensure `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` is set in the project, reloading if necessary
3. Invoke a code fix that is defined in the codestyle layer (e.g. remove unnecessary usings)
4. Results in an error

**Expected Behavior**:
Code action applies

**Actual Behavior**:
```
[Error - 11:40:52 AM] [LanguageServerHost] System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.8.10.6724, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.MefHostExportProvider.Create(String languageName)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices..ctor(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.Create(HostLanguageServices hostLanguageServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.GetRequiredMappedCodeStyleLanguageServices(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.RemoveUnnecessaryImports.AbstractRemoveUnnecessaryImportsCodeFixProvider.RemoveUnnecessaryImportsAsync(Document document, CodeActionOptionsProvider fallbackOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 356
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 310
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(Solution originalSolution, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 247
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionResolveHandler.HandleRequestAsync(CodeAction codeAction, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs:line 92
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, IMethodHandler handler, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 150
System.TypeLoadException: Method 'get_IsParamsArray' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.8.10.6724, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
```

This is caused by a mismatch between the Roslyn APIs used in Microsoft.CodeAnalysis.CodeStyle.Fixes and the Roslyn API versions shipped in the IDE.

The cause appears to the the use of a non-public APIs in the codestyle layer that was changed in recent versions of Roslyn, making the code fix no longer load correctly.  Specifically [this type](https://github.com/dotnet/roslyn/blob/5019bd5e900909dda8bed2339fe2d9db0208e663/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/Symbols/CodeGenerationParameterSymbol.cs#L17) in the code style layer in the .Net8 SDK does not implement the new interface member (IsParamsArray)

Some possible resolutions (as discussed offline with Sam / Cyrus)
1.  Enable analyzer to track usage of internal interface - https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md#rs1009-only-internal-implementations-of-this-interface-are-allowed .  Currently [this is disabled for roslyn here](https://github.com/dotnet/roslyn/blob/5019bd5e900909dda8bed2339fe2d9db0208e663/eng/config/globalconfigs/Common.globalconfig#L48), we could enable it only for the codestyle project.
2.  Remove code fixes using implementations ISymbol out of codestyle
3.  Rewrite code fixes to not use implementations of ISymbol

**Comment by nawafAlsaadi** [comment]
update  Microsoft.CodeAnalysis.CSharp.Features  

to +  4.12.0 . 
the Nuget Package Manger did not see the update . i did it manually  then its works 

NuGet\Install-Package Microsoft.CodeAnalysis.CSharp.Features -Version 4.12.0
