### ISSUE TITLE
MSBuildWorkspace.OpenSolutionAsync fails with the new slnx files

### ISSUE THREAD

**Issue by virzak** [dotnet/roslyn#73004]
**Version Used**: Microsoft.CodeAnalysis.Workspaces.MSBuild 4.9.2

**Steps to Reproduce**:

1. Create a solution file
2. Save As `slnx` using Visual Studio Version 17.10.0 Preview 3.0 or later ![image](https://github.com/dotnet/roslyn/assets/6209775/dae9ec31-d347-4c86-a985-226c86548324)
3. Add reference to `Microsoft.CodeAnalysis.Workspaces.MSBuild`
4. Try opening the solution
```cs
var workspace = MSBuildWorkspace.Create();
var solution = await workspace.OpenSolutionAsync(@"C:\PathTo\ExampleSlnx.slnx").ConfigureAwait(false);
```

**Expected Behavior**:

Should have no exception. It doesn't occur when opening "ExampleSlnx.sln"

**Actual Behavior**:

Microsoft.Build.Exceptions.InvalidProjectFileException
  HResult=0x80131500
  Message=No file format header found.  Q:\Code\Sandbox\ExampleSlnx\ExampleSlnx.slnx
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, String resourceName, Object[] args)
   at Microsoft.Build.Construction.SolutionFile.ParseFileHeader()
   at Microsoft.Build.Construction.SolutionFile.ParseSolution()
   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__22.MoveNext()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__24.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in Q:\Code\Sandbox\ExampleSlnx\ExampleSlnx\Program.cs:line 9

**Comment by huoyaoyuan** [comment]
The stack trace belongs to MSBuild, not roslyn.
As the new format is still in development, integration with MSBuild is simply not done yet.

**Comment by virzak** [comment]
@huoyaoyuan Moving to https://github.com/dotnet/msbuild/issues/10012

**Comment by Aaronontheweb** [comment]
Has this been resolved now that the `.slnx` format is widely available to the public?

**Comment by CyrusNajmabadi** [comment]
@Aaronontheweb see msbuild response at: https://github.com/dotnet/msbuild/issues/10012

Roslyn does not own this.  We just defer to them.

**Comment by Aaronontheweb** [comment]
@CyrusNajmabadi looks like there's an open PR adding support for it here: https://github.com/dotnet/roslyn/pull/77326
