### ISSUE TITLE
MSBuildWorkspace.OpenProjectAsync cannot load Solution Filter .slnf

### ISSUE THREAD

**Issue by boop5** [dotnet/roslyn#73105]
**Version Used**: 

$ dotnet --list-sdks
7.0.203 [C:\Program Files\dotnet\sdk]
8.0.101 [C:\Program Files\dotnet\sdk]
8.0.204 [C:\Program Files\dotnet\sdk]

$ dotnet --version
8.0.204

**Steps to Reproduce**:

Try to load a Solution Filter with `Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync`

**Expected Behavior**:

You can load Solution Filters

**Actual Behavior**:

You can not load Solution Filters, `OpenProjectAsync` throws an exception

**StackTrace**

This came up while I wanted to use roslynator but it seems to be a bug within roslyn though. 

I've opened an issue on [dotnet/roslynator #1431](https://github.com/dotnet/roslynator/issues/1431) 

The exception message is in `de-DE` and means: Project "somefilter.slnf" can't be opened, the file extension ".slnf" can't be matched to any language.

```csharp
Error occurred while loading project 'somefilter.slnf'
System.InvalidOperationException: Projekt "somefilter.slnf" kann nicht geöffnet werden, da die Dateierweiterung ".slnf" keiner Sprache zugeordnet ist.
   at Microsoft.CodeAnalysis.MSBuild.DiagnosticReporter.Report(DiagnosticReportingMode mode, String message, Func`2 createException)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFileLoaderRegistry.TryGetLoaderFromProjectPath(String projectFilePath, DiagnosticReportingMode mode, IProjectFileLoader& loader)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadProjectFileInfosAsync(String projectPath, DiagnosticReportingOptions reportingOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadProjectInfosFromPathAsync(String projectPath, DiagnosticReportingOptions reportingOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadProjectInfoAsync(String projectFilePath, ProjectMap projectMap, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync(String projectFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at Roslynator.CommandLine.MSBuildWorkspaceCommand`1.OpenProjectOrSolutionAsync(String path, MSBuildWorkspace workspace, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/CommandLine/Commands/MSBuildWorkspaceCommand.cs:line 242
```

**Comment by JoeRobich** [comment]
@boop5 You should be able to open solution filters (*.slnf) using `MSBuildWorkspace.OpenSolutionAsync` (Implemented in https://github.com/dotnet/roslyn/pull/51782).

Please reopen this issue if you are still having issues when using `OpenSolutionAsync`.
