### ISSUE TITLE
System.ArgumentNullException in Binaries\Debug\RunTests.exe

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#7331]
The error occured in:
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/1882/

Here's the stacktrace
```
11:33:13   Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
11:33:13   Parameter name: path1
11:33:13      at System.IO.Path.Combine(String path1, String path2)
11:33:13      at RunTests.TestRunner.PrintFailedTestResult(TestResult testResult) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Tools\Source\RunTests\TestRunner.cs:line 105
11:33:13      at RunTests.TestRunner.Print(List`1 testResults) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Tools\Source\RunTests\TestRunner.cs:line 89
11:33:13      at RunTests.TestRunner.<RunAllAsync>d__3.MoveNext() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Tools\Source\RunTests\TestRunner.cs:line 78
11:33:13      --- End of inner exception stack trace ---
11:33:13      at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
11:33:13      at System.Threading.Tasks.Task`1.get_Result()
11:33:13      at RunTests.Program.Main(String[] args) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Tools\Source\RunTests\Program.cs:line 45
```
FYI @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
@heejaechang Can you take a look at this?

**Comment by heejaechang** [comment]
David. Where can I add that regex you mentioned to identify this type of failures later.


-          heejae

**Comment by jaredpar** [comment]
I think this is just a bug in RunTests.  There is the chance one of the paths is `null` and I believe the tool is just handling that improperly.

**Comment by brettfo** [comment]
I've been speaking with @heejaechang offline and he's looking at one of my bugs (#6866) so I'll take this one to balance out the load.

**Comment by davkean** [comment]
Hitting this too:

```
The test runner has encountered a non-test-related exception.
09:17:54 To be clear, this is a problem with the test runner, not a test.
09:17:54 0a7ba10e-c611-4fb0-aefe-0c2efd6fe413
09:17:54 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
09:17:54    at RoslynBuildAndTest.TestRunner.DeleteTestResultsFile(String resultsFile) in d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Closed\Tools\Source\Test\RoslynBuildAndTest\RoslynBuildAndTest\TestRunner.Test.cs:line 328
09:17:54    at RoslynBuildAndTest.TestRunner.<RunMSTestAsync>d__51.MoveNext() in d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Closed\Tools\Source\Test\RoslynBuildAndTest\RoslynBuildAndTest\TestRunner.Test.cs:line 302
09:17:54 --- End of stack trace from previous location where exception was thrown ---
09:17:54    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:17:54    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:17:54    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
09:17:54    at RoslynBuildAndTest.TestRunner.<RunTestsAsync>d__45.MoveNext() in d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Closed\Tools\Source\Test\RoslynBuildAndTest\RoslynBuildAndTest\TestRunner.Test.cs:line 59
```

http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/365/consoleFull#-911669781a937a245-1bcd-4648-b555-7d3e2507afd7

**Comment by brettfo** [comment]
I've created an internal PR for this second issue here: dotnet/roslyn-internal#437.

**Comment by heejaechang** [comment]
Thank you

-          heejae
