### ISSUE TITLE
ReplaceMethodWithPropertyCodeRefactoringProvider crash with System.InvalidOperationException : GetCurrentNode returned null

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/roslyn#73637]
**Version Used**: Visual Studio 17.11.0 Preview 1.0

**Steps to Reproduce**:

Start with the following code:
``` csharp
namespace Test;

/// <summary>An array indexed by an Enum</summary>
/// <typeparam name="TValue">Type stored in array</typeparam>
/// <typeparam name="TEnumKey">Indexer Enum type</typeparam>
/// If you know your enum does not have much gapps in the value, this will be more efficient than a Dictionary
public struct ArrayByEnum<TEnumKey, TValue> : IEnumerable<TValue> where TEnumKey : Enum // requires C# 7.3 or later
{
    private readonly TValue[] _array;
    private readonly int _lower;

    public ArrayByEnum()
    {
        _lower = Convert.ToInt32(Enum.GetValues(typeof(TEnumKey)).Cast<TEnumKey>().Min());
        int upper = Convert.ToInt32(Enum.GetValues(typeof(TEnumKey)).Cast<TEnumKey>().Max());
        _array = new TValue[1 + upper - _lower];
    }

    public TValue this[TEnumKey key]
    {
        get { return _array[Convert.ToInt32(key) - _lower]; }
        set { _array[Convert.ToInt32(key) - _lower] = value; }
    }

    public IEnumerator<TValue> GetEnumerator()
    {
        var myThis = this;
        return Enum.GetValues(typeof(TEnumKey))
                .Cast<TEnumKey>()
                .Select(i => myThis._array[Convert.ToInt32(i) - myThis._lower])
                .GetEnumerator();
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
}
```

1. Go to the second-last line.
2. Invoke the Quick Actions and Refactorings menu:
  ![image](https://github.com/dotnet/roslyn/assets/51476918/1d27f19d-dfe3-42ec-8b70-109862c371e1)
3. Press <kbd>↓</kbd>
4. Wait for it to crash:
  ![image](https://github.com/dotnet/roslyn/assets/51476918/d6aa9af1-94bd-4713-9f78-eb8ba6533e2f)

**Expected Behavior**:
A code preview is shown.

**Actual Behavior**:
ReplaceMethodWithPropertyCodeRefactoringProvider crashes:
```
System.InvalidOperationException : GetCurrentNode returned null with the following node: foreach (System.Reflection.FieldInfo subfield in fieldValue.GetType().GetFields())
            {
                Console.WriteLine($"  {subfield.Name} = {subfield.GetValue(fieldValue)}");
            } - file SyntaxEditor.cs line 255
   at Roslyn.Utilities.Contract.Fail(String message,Int32 lineNumber,String filePath)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.UpdateReferencesInDocumentAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.UpdateReferencesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ReplaceMethodWithProperty.ReplaceMethodWithPropertyCodeRefactoringProvider.ReplaceMethodsWithPropertyAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass16_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/3ec10d2c2040b6f27a6d6dcc4b0a0b2206bde29d
