### ISSUE TITLE
[Test] CSharpNavigateTo is failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7367]
Job: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/103/
Screenshots: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/103/artifact/Open/Binaries/Release/Screenshots/.

```
Start - list of failing integration tests:
09:04:53 CSharpNavigateTo.xml
09:04:53 End - list of failing integration tests.
09:04:53 VS integration tests failed
09:04:53 ================================================================================
09:04:53 Dumping the log file for the last TAO test.  It may or may not include a failure.
09:04:53 ================================================================================
09:04:53 Test: CSharpNavigateTo started: 12/9/2015 5:08:15 PM
09:04:53 	Executing action [12/9/2015 5:08:15 PM] StartTarget
09:04:53 Begin Waiting for Apex Communication
09:04:53 	Executing action [12/9/2015 5:08:15 PM] AddProject
09:04:53 	Executing action [12/9/2015 5:08:27 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:08:27 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:08:27 PM] SetEditorText
09:04:53 	Executing action [12/9/2015 5:08:27 PM] CloseFile
09:04:53 	Executing action [12/9/2015 5:08:28 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:08:28 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:08:28 PM] WaitForWorkspace
09:04:53  Scenario: Verify 'Navigate To' class
09:04:53 	Executing action [12/9/2015 5:08:28 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstClass returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-08-41_93 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify 'Navigate To' member
09:04:53 	Executing action [12/9/2015 5:08:41 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstMethod returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-08-53_96 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify 'Navigate To' from vb file
09:04:53 	Executing action [12/9/2015 5:08:54 PM] AddProject
09:04:53 	Executing action [12/9/2015 5:09:05 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:09:05 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:09:05 PM] WaitForWorkspace
09:04:53 	Executing action [12/9/2015 5:09:05 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstClass returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-09-17_69 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify IDocumentNavigationService calls utilized by 'Navigate To' correctly promote the preview tab to a permanent tab on item selection
09:04:53 	Executing action [12/9/2015 5:09:17 PM] ExcludeScenarioInHost
09:04:53 	Executing action [12/9/2015 5:09:17 PM] CloseFile
09:04:53 	Executing action [12/9/2015 5:09:17 PM] DocumentNavigation
09:04:53 	Executing action [12/9/2015 5:09:17 PM] VerifyActiveDocumentWindow
09:04:53 	Executing action [12/9/2015 5:09:18 PM] DocumentNavigation
09:04:53 	Executing action [12/9/2015 5:09:18 PM] VerifyActiveDocumentWindow
09:04:53 	Executing action [12/9/2015 5:09:18 PM] CloseTarget
09:04:53 Test finished: 12/9/2015 5:09:22 PM
09:04:53 	Executing action [12/9/2015 5:09:22 PM] CloseTarget
09:04:53 Closing VS. force Close = True, closeVsToFreeHandles = False
09:04:53 	Executing action [12/9/2015 5:09:27 PM] CloseTarget
09:04:53 
09:04:53 ================================================================================
09:04:53 Dumping logs of all failed TAO tests.
09:04:53 ================================================================================
09:04:53 ================================================================================
09:04:53  Dumping log file d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\VSIntegrationTestLogs\CSharpNavigateTo.txt
09:04:53 Test: CSharpNavigateTo started: 12/9/2015 5:08:15 PM
09:04:53 	Executing action [12/9/2015 5:08:15 PM] StartTarget
09:04:53 Begin Waiting for Apex Communication
09:04:53 	Executing action [12/9/2015 5:08:15 PM] AddProject
09:04:53 	Executing action [12/9/2015 5:08:27 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:08:27 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:08:27 PM] SetEditorText
09:04:53 	Executing action [12/9/2015 5:08:27 PM] CloseFile
09:04:53 	Executing action [12/9/2015 5:08:28 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:08:28 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:08:28 PM] WaitForWorkspace
09:04:53  Scenario: Verify 'Navigate To' class
09:04:53 	Executing action [12/9/2015 5:08:28 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstClass returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-08-41_93 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify 'Navigate To' member
09:04:53 	Executing action [12/9/2015 5:08:41 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstMethod returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-08-53_96 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify 'Navigate To' from vb file
09:04:53 	Executing action [12/9/2015 5:08:54 PM] AddProject
09:04:53 	Executing action [12/9/2015 5:09:05 PM] AddItem
09:04:53 	Executing action [12/9/2015 5:09:05 PM] OpenFile
09:04:53 	Executing action [12/9/2015 5:09:05 PM] WaitForWorkspace
09:04:53 	Executing action [12/9/2015 5:09:05 PM] NavigateTo
09:04:53 NavigateTo threw an exception: a VS dump should be available
09:04:53 --------------------------------
09:04:53 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstClass returned no results.
09:04:53 
09:04:53 Server stack trace: 
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToSession.cs:line 219
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 134
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 123
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio.OM\BrowsingAndNavigation\NavigateTo\NavigateToTestService.cs:line 113
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
09:04:53    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
09:04:53 
09:04:53 Exception rethrown at [0]: 
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
09:04:53    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
09:04:53    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
09:04:53    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\Test\Actions\VisualStudio\NavigateToAction.cs:line 25
09:04:53    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
09:04:53    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
09:04:53 ================================
09:04:53 
09:04:53 
09:04:53 Saved screenshot: d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\Binaries\Release\Screenshots\2015-12-09_17-09-17_69 - Exception Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException.png
09:04:53  Scenario: Verify IDocumentNavigationService calls utilized by 'Navigate To' correctly promote the preview tab to a permanent tab on item selection
09:04:53 	Executing action [12/9/2015 5:09:17 PM] ExcludeScenarioInHost
09:04:53 	Executing action [12/9/2015 5:09:17 PM] CloseFile
09:04:53 	Executing action [12/9/2015 5:09:17 PM] DocumentNavigation
09:04:53 	Executing action [12/9/2015 5:09:17 PM] VerifyActiveDocumentWindow
09:04:53 	Executing action [12/9/2015 5:09:18 PM] DocumentNavigation
09:04:53 	Executing action [12/9/2015 5:09:18 PM] VerifyActiveDocumentWindow
09:04:53 	Executing action [12/9/2015 5:09:18 PM] CloseTarget
09:04:53 Test finished: 12/9/2015 5:09:22 PM
09:04:53 	Executing action [12/9/2015 5:09:22 PM] CloseTarget
09:04:53 Closing VS. force Close = True, closeVsToFreeHandles = False
```

**Comment by davkean** [comment]
This is being disabled in https://github.com/dotnet/roslyn-internal/pull/436.
