### ISSUE TITLE
[Test Failure] CSharpIntellisense failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7379]
PR: [#7375](https://github.com/dotnet/roslyn/pull/7375) *Upgrade NuGet to 3.4.0.247 and increase restore timeout* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2422/

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpIntellisense.xml

**Comment by dpoeschl** [comment]
Intellisense not showing on Ctrl+space in an empty file

```
 Scenario: Dismiss on Select All
	Executing action [12/9/2015 10:36:23 PM] SetEditorText // to /**/
	Executing action [12/9/2015 10:36:23 PM] PlaceCursor // on /**/
	Executing action [12/9/2015 10:36:23 PM] SendKeys // DELETE
	Executing action [12/9/2015 10:36:24 PM] WaitForWorkspace
	Executing action [12/9/2015 10:36:24 PM] SendKeys // Ctrl+space
	Executing action [12/9/2015 10:36:24 PM] VerifyCompletionList // It should be showing
--------------------------------
Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifyCompletionListAction]: Completion list was not showing and it was expected to be showing
   at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message) in f:\dd\src\Omni\Tao\Tao.Utilities\Extensions.cs:line 457
   at Roslyn.Hosting.Test.VerifyCompletionListAction.ExecuteOnUIThread() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\RoslynTaoActions\Actions\EditorTestApp\VerifyCompletionListAction.cs:line 41
   at Roslyn.Hosting.Test.EditorAction.<Execute>b__0_0() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 21
   at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
   at Roslyn.Hosting.Test.EditorAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 13
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
================================
```

**Comment by rchande** [comment]
Unable to repro failure locally, hasn't failed in the last week. Additionally, I tried adding some logging to make failures more informative, but haven't seen any failures. Closing.
