### ISSUE TITLE
Code Compiled with Roslyn 1.1.1 crashes with strange exceptions.

### ISSUE THREAD

**Issue by inforithmics** [dotnet/roslyn#7391]
I used this nuget package to compile my code with roslyn (https://www.nuget.org/packages/Microsoft.Net.Compilers/)

And then a lot of unit tests started failing with the following stacktrace:

at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
 at System.MulticastDelegate.CtorClosed(Object target, IntPtr methodPtr)
 McBaseDaoExtender.SetReferences(DataRowAttribute dra, IEnumerable\`1 ignoreTables, IEnumerable\`1 allowedTables) in McBaseDaoExtender.cs:line 176
....

Below is the Code that crashed:

```csharp
 private static void SetReferences(DataRowAttribute dra, IEnumerable<string> ignoreTables = null, IEnumerable<string> allowedTables = null)
        {
            if (dra == null)
            {
                return;
            }

            HashSet<string> nonReferences = new HashSet<string> { "summary", "leistungstarif" };
            if (ignoreTables != null)
            {
                foreach (string item in ignoreTables)
                {
                    nonReferences.Add(item);
                }
            }

            HashSet<string> allowedReferences = allowedTables.ToHashSet();

            if (dra.DataRowAttributeDataSet != null && dra.DataRowAttributeDataSet.referenzen != null && dra.DataRowAttributeDataSet.referenzen.Any())
            {
                var references = dra.DataRowAttributeDataSet.referenzen.Where(f => f != null && f.referenz != null && !nonReferences.Contains(f.referenz));

                if (allowedReferences != null)
                {
                    references = references.Where(f => allowedReferences.Contains(f.referenz));
                }

                if (references.Any())
                {
Exception -->       dra.References = references.Sum(f => f.cnt);
                }
            }    
        }
```

So the exception occured in a Linq Expression. I tried to isolate the Exception but I didn't succeed to create a small repro. Because the Bug went away, so it only occurs during longer runtimes of the code. And only with Roslyn compiled code not with code Compiled with csc.

Because I'm not an il expert, and the il of Roslyn and Csc is totally different. I couldn't see wath's different. so I attached the IL of The class compiled with roslyn and the IL of the class compiled with csc.

Additional Data: Runtime is .NET 4.6.1 in a 32bit process on Windows 8.1 x64, and the Code is Compiled against .NET 4.0.

[RoslynCompileDebugIl.txt](https://github.com/dotnet/roslyn/files/57994/RoslynCompileDebugIl.txt)
[CscCompileDebugIl.txt](https://github.com/dotnet/roslyn/files/57995/CscCompileDebugIl.txt)

A work around I found is not to use Linq(only foreach loops) then the code although works with Roslyn, But I have a lot of Linq Expressions in the Code so it's not really a solution.

Could it be that this is caused, by Roslyn changing how Delegates are compiled?

**Comment by inforithmics** [comment]
Code of csc of Exception site:

```IL
  IL_014b: ldftn        int32 Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender::'<SetReferences>b__5'(class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow)
    IL_0151: newobj       instance void class [mscorlib]System.Func`2<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow, int32>::.ctor(object, native int)
    IL_0156: stsfld       class [mscorlib]System.Func`2<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow, int32> Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender::'CS$<>9__CachedAnonymousMethodDelegate8'
    IL_015b: br.s         IL_015d
    IL_015d: ldsfld       class [mscorlib]System.Func`2<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow, int32> Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender::'CS$<>9__CachedAnonymousMethodDelegate8'
    IL_0162: call         int32 [System.Core]System.Linq.Enumerable::Sum<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!0/*class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow*/>, class [mscorlib]System.Func`2<!!0/*class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow*/, int32>)
    IL_0167: callvirt     instance void [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttribute::set_References(int32)
```

Code of Roslyn of Exception site:

```IL
 IL_0115: ldsfld       class Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender/'<>c' Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender/'<>c'::'<>9'
    IL_011a: ldftn        instance int32 Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender/'<>c'::'<SetReferences>b__3_2'(class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow)
    IL_0120: newobj       instance void class [mscorlib]System.Func`2<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow, int32>::.ctor(object, native int)
    IL_0125: dup          
    IL_0126: stsfld       class [mscorlib]System.Func`2<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow, int32> Muellerchur.Famc.Server.DataAccessObjects.McBaseDaoExtender/'<>c'::'<>9__3_2'
    IL_012b: call         int32 [System.Core]System.Linq.Enumerable::Sum<class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!0/*class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow*/>, class [mscorlib]System.Func`2<!!0/*class [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttributeDataSet/referenzenRow*/, int32>)
    IL_0130: callvirt     instance void [Muellerchur.Famc.Shared]Muellerchur.Famc.Shared.DataTransferObjects.DataRowAttribute::set_References(int32)
```

In Roslyn the the Delegate f => f.cnt is a method on a class saved on a field: 
In Csc it is a direct method call:

What I don't unterstand is from where the null reference Delegate exceptoin comes

**Comment by inforithmics** [comment]
I found out why my tests didn't work with roslyn, after each test I executed following Code.
This Code initializes Singletons back to its initial value. (null). A singleton is a class that has a static field with type of the class. Unfortunatly this pattern although happens to match the delegate class, which I set to null and therefore the bugs with roslyn.

```csharp
        foreach (Type type in typeof(PersonDao).Assembly.GetTypes())
        {
            ClearSingleton(type);
        }

        private static void ClearSingleton(Type type)
        {          
            // Find static fields
            foreach (FieldInfo fieldInfo in type.GetFields(BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public))
            {
                // set the values to null
                if (fieldInfo.FieldType == type)
                {
                    fieldInfo.SetValue(null, null);
                }
            }
        }

```

I changed the Code now that I ask the FieldInfo if it is init only (Then it is a Delegate class and I don't set it to null. And now my tests work.

```csharp
        foreach (Type type in typeof(PersonDao).Assembly.GetTypes())
        {
            ClearSingleton(type);
        }

        private static void ClearSingleton(Type type)
        {          
            // Find static fields
            foreach (FieldInfo fieldInfo in type.GetFields(BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public))
            {
                // set the values to null
                if (fieldInfo.FieldType == type&& !fieldInfo.IsInitOnly)
                {
                    fieldInfo.SetValue(null, null);
                }
            }
        }

```

Observations:

1. Is this intened that I can write with reflection to a InitOnlyField after it is initialized? So this is only a Usage flag and not an enforced flag by the runtime.

2. The Error that appears when I null the Delegate Singleton Instance is absolutly not understandable, but I don't know a better message either. ( I have this Bug since I switched to Visual Studio 2015 and now I took the time to track it down).

So In my opinion this is not a Bug but a behavior change of the Roslyn compiler, that bit me. I still think this report is useful, because when someone else hits this. He might find it.
