### ISSUE TITLE
TestFindAllReferencesAsync_Streaming failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#74284]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=728021&view=ms.vss-test-web.build-test-results-tab&runId=18287322&resultId=208506&paneView=debug

```
Assert.Equal() Failure
Expected: M2
Actual:   (null)



Stack trace
   at Microsoft.CodeAnalysis.LanguageServer.UnitTests.References.FindAllReferencesHandlerTests.<TestFindAllReferencesAsync_Streaming>d__2.MoveNext() in /_/src/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.LanguageServer.UnitTests.References.FindAllReferencesHandlerTests.<TestFindAllReferencesAsync_Streaming>d__2.MoveNext() in /_/src/LanguageServer/ProtocolUnitTests/References/FindAllReferencesHandlerTests.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by tmat** [comment]
@dibarbet fyi

**Comment by CyrusNajmabadi** [comment]
Did your branch have https://github.com/dotnet/roslyn/pull/74261 in it yet?

**Comment by dibarbet** [comment]
The run linked in the PR ran on Tuesday July 2nd, but my PR to fix it only merged on July 3rd.  So I presume the run did not have my fix.  Closing this issue as fixed by https://github.com/dotnet/roslyn/pull/74261
