### ISSUE TITLE
Switching AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult from WpfFact causes it to fail

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7438]
I tried changing this test from `WpfFact` -> `Fact` and it failed this way:

```
Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult
      System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.AggregateException'.
      Stack Trace:
        src\EditorFeatures\Test\Utilities\AsyncLazyTests.cs(53,0): at Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueOrGetValueAsyncStillCachesResultCore(Func`3 doGetValue, Boolean includeSynchronousComputation)
        src\EditorFeatures\Test\Utilities\AsyncLazyTests.cs(18,0): at Microsoft.CodeAnalysis.UnitTests.AsyncLazyTests.CancellationDuringInlinedComputationFromGetValueStillCachesResult()
```

This is suspicious -- I can't imagine why the test would change exception types depending upon the thread. We might have a very subtle bug.

**Comment by jasonmalinowski** [comment]
The mystery deepens: in 8ffa1ee the tests were moved to the IDE layer tests, and this duplicate was left. That copy already had [Fact] set, so why they are different I can't say.
