### ISSUE TITLE
Crash in rename with generic partial class "mix-in"

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#7440]
```C#
partial class C<T>
    where T : C<T>.D
{

}

partial class C<T>
{
    public class D { }
}
```

Move caret to T` and invoke Rename.

**Comment by dpoeschl** [comment]
```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.Single[T](ImmutableArray`1 immutableArray)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConflictsAsync>d__3.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 878
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.<AddDeclarationConflictsAsync>d__9.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<IdentifyConflictsAsync>d__20.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 430
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__18.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.<GetReplacementsAsync>d__7.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\AbstractEditorInlineRenameService.InlineRenameLocationSet.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass63_0.<<UpdateConflictResolutionTask>b__0>d.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 446
12/18/2015 1:41:04 PM
Source: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: System.Core
StackTrace:    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.Single[T](ImmutableArray`1 immutableArray)
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.<ComputeDeclarationConflictsAsync>d__3.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 878
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.<AddDeclarationConflictsAsync>d__9.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<IdentifyConflictsAsync>d__20.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 430
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__18.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.<GetReplacementsAsync>d__7.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\AbstractEditorInlineRenameService.InlineRenameLocationSet.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass63_0.<<UpdateConflictResolutionTask>b__0>d.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 446
```

**Comment by davkean** [comment]
We had another hit of this internally.

**Comment by dpoeschl** [comment]
Fix merged into stabilization. Closing.
