### ISSUE TITLE
C# Intellisense parameter info stops working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74500]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Intellisense-parameter-info-stops-wor/10707796)._

---
[severity:It bothers me. A fix would be nice]
In the following C# code, the Parameter Info feature does not work. And it stops working everywhere until restarting Visual Studio.

```
class C {
	void _Caller() {
		M(c: ); // To reproduce, click inside ( ) and press Ctrl+Shift+Space.
	}

/// <summary>
	/// About M.
	/// </summary>
	/// <param name="a">About a.</param>
	/// <param name="b">About b.</param>
	/// <param name="c">About c.</param>
	public static void M(int a = 0, int b = 0, int c = 0) { }
}
```

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.11.0 Preview 4.0
Windows 11

---
#### Feedback Bot on 7/22/2024, 11:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
```
argumentCount < argumentIndex. 1 < 2
Parameter name: argumentIndex
   at Microsoft.CodeAnalysis.SignatureHelp.SignatureHelpItems..ctor(IList`1 items, TextSpan applicableSpan, Int32 argumentIndex, Int32 argumentCount, String argumentName, Nullable`1 selectedItem)
   at Microsoft.CodeAnalysis.SignatureHelp.AbstractSignatureHelpProvider.CreateSignatureHelpItems(IList`1 items, TextSpan applicableSpan, Nullable`1 state, Nullable`1 selectedItemIndex, Int32 parameterIndexOverride)
   at Microsoft.CodeAnalysis.CSharp.SignatureHelp.InvocationExpressionSignatureHelpProviderBase.<GetItemsWorkerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SignatureHelp.AbstractSignatureHelpProvider.<GetItemsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext()
```

**Comment by CyrusNajmabadi** [comment]
hrmm... this doesn't repro for me.
