### ISSUE TITLE
Roslyn Scripting APIs for Blazor WebAssembly

### ISSUE THREAD

**Issue by winscripter** [dotnet/roslyn#74555]
**Version Used**:  Roslyn 4.10.0; .NET 8.0; Visual Studio 2022
**Steps to Reproduce**:
1. Create a Blazor WebAssembly project (with the default Visual Studio template)
2. Inside Counter.razor, change the IncrementCount() method to the following:
```cs
_ = CSharpScript.RunAsync<int>("1 + 2").GetAwaiter().GetResult();
currentCount++;
```
3. Run the Blazor WebAssembly application, navigate to the Counter and click on the button

Counter.razor file to reproduce:
```cs
@using Microsoft.CodeAnalysis.CSharp.Scripting
@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        _ = CSharpScript.RunAsync<int>("1 + 2").GetAwaiter().GetResult();
        currentCount++;
    }
}
```

**Expected Behavior**:
The C# script, "1 + 2", should evaluate without any issues.

**Actual Behavior**:
Instead, the following exception is thrown:
```
System.NotSupportedException: Can't create a metadata reference to an assembly without location.
at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly)
```

**Note**: There is a [similar issue](https://github.com/dotnet/roslyn/issues/71371) created about half a year ago, but it did not receive response or attention.

**Comment by wherewhere** [comment]
I copied the dlls to output for creating `MetadataReference`.
https://github.com/wherewhere/SharpScript/blob/wasm/SharpScript/SharpScript.csproj#L25-L37
```cs
private static async ValueTask<List<MetadataReference>> GetMetadataReferencesAsync(string baseUrl, params string[] assemblies)
{
    List<MetadataReference> references = [];
    using HttpClient client = new() { BaseAddress = new Uri(baseUrl) };
    foreach (string assembly in assemblies)
    {
        using Stream stream = await client.GetStreamAsync($"{assembly}.dll").ConfigureAwait(false);
        references.Add(MetadataReference.CreateFromStream(stream));
    }
    return references;
}
```
At first I was trying to use wasm files to create it. But `MetadataReference.CreateFromStream` doesn't supports WebIL. I saw that ILSpy supports decompile WebIL, so I try to use that way read it but failed.
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/Metadata/WebCilFile.cs#L146-L183

**Comment by winscripter** [comment]
I found out a [workaround](https://github.com/winscripter/blazorwasmevalexample) a few months ago, but even then it's still extremely limiting: no async support, cannot keep track of compilation, and if any code or dependencies have the `[CLSCompliant]` attribute it will return an error due to a single `.GetAwait().GetResult()` somewhere in Roslyn...

Yeah looks like solving this issue won't be easy.

**Comment by wherewhere** [comment]
It is copy dll too...

**Comment by wherewhere** [comment]
Here is a PE COFF file to WebCIL file converter. Maybe we can create a  WebCIL to PE converter...
https://github.com/dotnet/runtime/blob/main/src/tasks/Microsoft.NET.WebAssembly.Webcil/WebcilConverter.cs

**Comment by jjonescz** [comment]
> Maybe we can create a WebCIL to PE converter

Here's one: https://github.com/StefH/ProtoBufJsonConverter/blob/fc0530d796ce1659cdf8e852970c1219c7296be8/src-webcil/MetadataReferenceService.BlazorWasm/WasmWebcil/WebcilConverterUtil.cs#L56

**Comment by wherewhere** [comment]
Now the wasm file name has add version code so that we can not get file name directly from library name now...

**Comment by jjonescz** [comment]
> Now the wasm file name has add version code so that we can not get file name directly from library name now...

There is a generated JSON file which has a mapping from the original file names to the versioned file names. For example, I do that here in my app: https://github.com/jjonescz/DotNetInternals/blob/066e7bb0ba240457019d470c94857644786c1d1f/src/Worker/Lab/AssemblyDownloader.cs

**Comment by hawkerm** [comment]
I've been able to use just the raw `CSharpCompilation` in Uno WASM without issue, but was hoping to use the slightly higher-level Scripting API, but his this as well.

Part of the issue (if you trace where the error message comes from) is specific to this code-path here:

https://github.com/dotnet/roslyn/blob/3683d8b6bb9e0527b4e8a46c4885ef7177fefb38/src/Scripting/Core/Script.cs#L257-L268

In `CreateFromAssembly` where it's trying to reload the assembly from disk (even if we already loaded them into memory directly in my case):

https://github.com/dotnet/roslyn/blob/3683d8b6bb9e0527b4e8a46c4885ef7177fefb38/src/Scripting/Core/Script.cs#L313-L322

Which gets blocked in `MetadataReference.GetAssemblyFilePath` before trying to use the function to even load (as there's no file path):

https://github.com/dotnet/roslyn/blob/3683d8b6bb9e0527b4e8a46c4885ef7177fefb38/src/Scripting/Core/Script.cs#L324-L337

But all this is doing is trying to recreate the MetadataReference...

In my case, I've already loaded the assemblies from the WASM context (copying them from the wasm-tools workload) using `MetadataReference.CreateFromStream(stream)` (akin to [this working Uno example with CSharpCompilation directly here]( https://github.com/jeromelaban/uno.skiasharpfiddle/blob/master/UnoSkiaSharpFiddle/UnoSkiaSharpFiddle.Shared/Compiler.cs)).

I tried providing the hint path for the file in the CreateFromStream, but that didn't change anything...

---

I think then I realized the first thing it'd doing is trying to load the corLib (based on the variable name), but I have that one loaded through the assemblies I have, so I need it to just not do that step and let me provide it in this case... (would be the same thing for the globals type I guess too?).

Seems like we'd just need a tweaked option to skip these steps or resolve them from a direct provide an existing MetadataReference for these memory non-disk environments?

**Comment by hawkerm** [comment]
I was falling back to try and just use CSharpCompilation directly, but to try and use it in the scripting context isn't well documented and seems complex (passing in prior executions to the next initialization, I think?). I'm going to try copying the Scripting code out and fiddle with the loading aspect which I already have setup and see where that goes. As, I'm pretty sure this seems like an artificial limitation from trying to be helpful loading the base assemblies over anything beyond that.

**Comment by hawkerm** [comment]
The Scripting has a bunch of internal references, so wasn't easy to separate out on its own. Was able to build roslyn, but not sure how hard it'd be to make a change and test it effectively. I was able to get IronPython to more easily work in the WASM context, but still would really like to use C# as well in a scriptable context. May come back to fiddling with roslyn codebase, but may focus more on my project with some scripting language to work on its general architecture more first.

**Comment by wherewhere** [comment]
How can I enable runtime features? Default roslyn does not enable default interface implementation and ref fields.

![Image](https://github.com/user-attachments/assets/d23aaa25-fd4a-46f9-94af-14f0f2ad70cd)

**Comment by wherewhere** [comment]
Is that possible to run .NET wasm directly on Web Worker? I have to add fake DOM API to run `blazor.webassembly.js`.
https://github.com/wherewhere/SharpScript/blob/wasm/SharpScript/wwwroot/worker.js#L2-L23

**Comment by jjonescz** [comment]
> Is that possible to run .NET wasm directly on Web Worker?

That's not related to this issue, but yes, it is possible. I'm using https://github.com/KristofferStrube/Blazor.WebWorkers in https://github.com/jjonescz/DotNetLab for example.

**Comment by wherewhere** [comment]
> How can I enable runtime features? Default roslyn does not enable default interface implementation and ref fields.
> 
> ![Image](https://github.com/user-attachments/assets/d23aaa25-fd4a-46f9-94af-14f0f2ad70cd)

Figure it out. It's because the `RuntimeFeature` has be trimmed. Need to add
```cs
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(RuntimeFeature))]
```
to keep it.

**Comment by wherewhere** [comment]
The `blazor.boot.json` is gone in .NET Core App 10.0...

![Image](https://github.com/user-attachments/assets/032817f9-0122-4e77-bb17-4c9381c46c9e)

**Comment by jjonescz** [comment]
You can get it via JS - `getDotnetRuntime(0).getConfig()`

**Comment by wherewhere** [comment]
I found `Blazor.runtime.config.resources` can get it, but the `fingerprinting` is gone. So, I create it by myself:
```js
let fingerprinting = Blazor.runtime.config.resources.fingerprinting;
if (!fingerprinting) {
    fingerprinting = {};
    for (const x of Blazor.runtime.config.resources.coreAssembly) {
        fingerprinting[x.name] = x.virtualPath;
    }
    for (const x of Blazor.runtime.config.resources.assembly) {
        fingerprinting[x.name] = x.virtualPath;
    }
}
```
But then when I read the `Stream`, it said `net_http_synchronous_reads_not_supported`...

**Comment by jjonescz** [comment]
> But then when I read the `Stream`, it said `net_http_synchronous_reads_not_supported`...

Sounds like you need to read the stream via Async functions.
