### ISSUE TITLE
Old release branch signed builds are broken

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#74649]
Found due to builds kicked off by #74447

https://dev.azure.com/dnceng/internal/_build/results?buildId=2504035&view=logs&j=7ae71e7c-d4fe-51ea-64cd-240849b77ab1&t=e2756d63-0606-58d5-0f0d-91c79a5ba922

It looks like RIT is not handling the case where default.config is present, which is only in these old branches, not in the more recent ones.

**Comment by RikkiGibson** [comment]
It looks like various auth issues have been occurring in more recent runs of the old release branch builds.

---

```log
# in Publish Assets task
error: Response status code does not indicate success: 401 (Unauthorized).
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2525345&view=logs&j=20fcf628-b65c-5865-625a-1cef81cda63b&t=4ed2e466-dd33-5328-0e9b-c43f9f8f6f25&l=60

---

```log
# in Publish Using Darc task
fail: A '401 - Unauthorized' status was returned for a HTTP request. We'll set the retries amount to 0. 
fail: Non-continuable HTTP 401 error encountered while making request against URI '_apis/build/builds/2523590/artifacts'
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs:line 103
fail: Error: Failed to assign build '236235' to channel ''.
      Microsoft.DotNet.DarcLib.DarcAuthenticationFailureException: Failure to authenticate: Response status code does not indicate success: 401 (Unauthorized).
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs:line 120
         at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs:line 857
         at Microsoft.DotNet.DarcLib.AzureDevOpsClient.GetBuildArtifactsAsync(String accountName, String projectName, Int32 azureDevOpsBuildId, Int32 maxRetries) in /_/src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs:line 1262
         at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ValidateAzDOBuildAsync(IAzureDevOpsClient azdoClient, String azureDevOpsAccount, String azureDevOpsProject, Int32 azureDevOpsBuildId) in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs:line 332
         at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IBarApiClient barClient) in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs:line 232
         at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs:line 162
Problems using Darc to promote build 236235 to default channels. Stopping execution...
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2523590&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=b3ecf0d0-598d-5874-6547-0432d3f07f6b

---

@arkalyanms @phil-allen-msft for visibility. I don't expect to have bandwidth to fix these in the near future.

**Comment by Cosifne** [comment]
Fixed in a set of PRs:
https://github.com/dotnet/roslyn/pull/75425
https://github.com/dotnet/roslyn/pull/75348
https://github.com/dotnet/roslyn-tools/pull/1444
