### ISSUE TITLE
FxCopAnalyzers, System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer, NullReferenceException

### ISSUE THREAD

**Issue by BGrojer** [dotnet/roslyn#7475]
With version 1.1 of the Analyzer I run into a NullRefIssues in multiple projects:

Warning	AD0001	Analyzer 'System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Platform.Shared		1	Active	Analyzer 'System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer' threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer.AnalyzeBinaryExpression(SyntaxNodeAnalysisContext context)
   at System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by srivatsn** [comment]
This has been moved to the roslyn-analyzers repo as https://github.com/dotnet/roslyn-analyzers/issues/774
