### ISSUE TITLE
`CSharpMergeNestedIfStatementsCodeRefactoringProvider` encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74772]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CSharpMergeNestedIfStatementsCodeRefact/10723696)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Preview 11]
![image.png](https://aka.ms/dc/image?name=Bd544634b909a46138b16b00f2410abac638593170826385721_20240815-071122-image.png&tid=d544634b909a46138b16b00f2410abac638593170826385721)

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span,Boolean findInsideTrivia,Boolean getInnermostNodeForTie)
   at async Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeIfStatementsCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by akhera99** [comment]
I am unable to reproduce. Please file a new ticket if you find a new issue!
