### ISSUE TITLE
NRE in CreateQuickToken

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#7478]
Repro taken from https://github.com/dotnet/cli/issues/489#issuecomment-164591100

> I cloned the current master (91acc03) and ran build.cmd on Windows 10 x64 Pro with VS2015 Community.
> 
> The compilation terminated with csc crash ("csc.exe has stopped working") as follow:

```
C:\Users\Adeel\Source\Repos> git clone https://github.com/dotnet/cli --recursive
C:\Users\Adeel\Source\Repos> cd cli
C:\Users\Adeel\Source\Repos\cli [master]> .\build.cmd
# .... package restore spew....
# .... build spew....
# .....stage 0 cleared......
# .......then the error.....
# ...........................
Published to C:\Users\Adeel\Source\Repos\cli\artifacts\win7-x64\stage1\bin
Publishing dotnet-pack for DNXCore,Version=v5.0/win7-x64
Compiling Microsoft.DotNet.ProjectModel for DNXCore,Version=v5.0

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object
reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.CreateQuickToken()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LexerCache.LookupToken(Char[] textBuffer, Int32 keyStart, Int3
2 keyLength, Int32 hashCode, Func`1 createTokenFunction)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.QuickScanSyntaxToken()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.Lex(LexerMode mode)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.PreLex()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser..ctor(Lexer lexer, LexerMode mode, CSharpSyntaxNo
de oldTree, IEnumerable`1 changes, Boolean allowModeReset, Boolean preLexIfNotIncremental, CancellationToken cancellatio
nToken)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser..ctor(Lexer lexer, CSharpSyntaxNode oldTree, IE
numerable`1 changes, LexerMode lexerMode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path,
 CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(CSharpParseOptions parseOptions, CSharpParseOptions scriptP
arseOptions, SourceText content, CommandLineSourceFile file)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(TextWriter consoleOutput, CSharpParseOptions parseOptions,
CSharpParseOptions scriptParseOptions, Boolean& hadErrors, CommandLineSourceFile file, ErrorLogger errorLogger, String&
normalizedFilePath)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.<>c__DisplayClass7_0.<CreateCompilation>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout,
 Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout,
 Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolea
n stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, Cancellat
ionToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.CreateCompilation(TextWriter consoleOutput, TouchedFileLogger touched
FilesLogger, ErrorLogger errorLogger)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken
 cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter textWriterOut, TextWriter
_)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(List`1 arguments, String clientDir, Stri
ng sdkDir)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPat
hs)
The destination "C:\Users\Adeel\Source\Repos\cli\artifacts\win7-x64\stage2\bin" does not exist. This script is only desi
gned to update a previous full build!
The destination "C:\Users\Adeel\Source\Repos\cli\artifacts\win7-x64\stage2\bin" does not exist. This script is only desi
gned to update a previous full build!

   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, Compi
leFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
C:\Users\Adeel\Source\Repos\cli\src\Microsoft.DotNet.ProjectModel\project.json(15,52): warning NU1007: Dependency specif
ied was Microsoft.Extensions.FileSystemGlobbing >= 1.0.0-rc2-15791 but ended up with Microsoft.Extensions.FileSystemGlob
bing 1.0.0-rc2-15875.
Compilation failed.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:12.5411998

Command failed: dotnet publish --framework dnxcore50 --runtime win7-x64 --output C:\Users\Adeel\Source\Repos\cli\artifac
ts\win7-x64\stage1\bin --configuration Debug C:\Users\Adeel\Source\Repos\cli\src\Microsoft.DotNet.Tools.Pack
Command failed: C:\Users\Adeel\Source\Repos\cli\scripts\build\build-stage.ps1 -Tfm: dnxcore50 -Rid: win7-x64 -Configurat
ion: Debug -OutputDir: C:\Users\Adeel\Source\Repos\cli\artifacts\win7-x64\stage1 -RepoRoot: C:\Users\Adeel\Source\Repos\
cli -HostDir: C:\Users\Adeel\Source\Repos\cli\artifacts\win7-x64\corehost
Building dotnet tools finished with errors.
```

**Comment by agocke** [comment]
It seems like this may be a race that's being revealed by running on CoreCLR

**Comment by jaredpar** [comment]
Moving out for now.  There are no recent repos, none at all on desktop.  As we move to full CoreClr testing in update 1 we can revisit this.

**Comment by jaredpar** [comment]
Closing as we haven't seen any other reports of this and none of the existing repros have enabled us to track down this problem.  It's plausible this was resulting from a bad combination of runtime libraries and that has since been resolved.
