### ISSUE TITLE
`InvalidOperationException` in `SemanticTokensHelpers` when applying embedded classification on verbatim string

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#74809]
### Version Used

Compiler: 4.12.0-2.24413.5 (a187b891)  
.NET: 9.0.100-preview.7.24407.12  
Visual Studio Code: 1.92.2, `fee1edb8d6d72a0ddff41e5f71a671c23ed924b9`, x64  
C# Extension: v2.43.16  
C# Dev Kit Extension: v1.10.6

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code.
2. Add the following code wherever applicable:
   ```cs
   // lang=c#-test
   const string Code = @"
   class C {
       //
   }";
   ```
3. Observe the error.

### Expected Behavior

No error is reported.

> [!NOTE]
> The error is not reported when using a raw string literal (`""" """`).

### Actual Behavior

```
[Error - 8:35:28 PM] [LanguageServerHost] System.InvalidOperationException: deltaLine is less than 0: -1 - file SemanticTokensHelpers.cs line 300
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber, String filePath) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 157
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeNextToken(TextLineCollection lines, Int32& lastLineNumber, Int32& lastStartCharacter, SegmentedList`1 classifiedSpans, Int32 currentClassifiedSpanIndex, IReadOnlyDictionary`2 tokenTypeMap, IReadOnlyDictionary`2 tokenTypesToIndex, Int32& deltaLineOut, Int32& startCharacterDeltaOut, Int32& tokenLengthOut, Int32& tokenTypeOut, Int32& tokenModifiersOut)
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeTokens(TextLineCollection lines, SegmentedList`1 classifiedSpans, Boolean supportsVisualStudioExtensions, IReadOnlyDictionary`2 tokenTypesToIndex) in /_/src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 256
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeSemanticTokensDataAsync(Document document, ImmutableArray`1 spans, Boolean supportsVisualStudioExtensions, ClassificationOptions options, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 122
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.HandleRequestHelperAsync(Document document, ImmutableArray`1 spans, Boolean supportsVisualStudioExtensions, ClassificationOptions options, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 69
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.HandleRequestHelperAsync(IGlobalOptionService globalOptions, SemanticTokensRefreshQueue semanticTokensRefreshQueue, Range[] ranges, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 48
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensRangeHandler.HandleRequestAsync(SemanticTokensRangeParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs:line 44
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[Error - 8:35:28 PM] Request textDocument/semanticTokens/range failed.
  Message: deltaLine is less than 0: -1 - file SemanticTokensHelpers.cs line 300
  Code: -32000 
```

**Comment by jasonmalinowski** [comment]
I hit this looking at src\LanguageServer\ProtocolUnitTests\Miscellaneous\LspMiscellaneousFilesWorkspaceTests.cs or src\LanguageServer\Protocol.TestUtilities\LanguageServer\AbstractLanguageServerProtocolTests.cs. I don't have a specific repro, but the first one does have embedded C# strings at least.
