### ISSUE TITLE
'CSharpRemoveUnusedValuesCodeFixProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/roslyn#75005]
**Version Used**: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.12.0 Preview 2.0 [35228.322.main]

**Steps to Reproduce**:

1. Clone https://github.com/dotnet/aspire
2. Launch VS using startvs.cmd
3. Start moving around the code base and wait for error to occur.

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**: CSharpRemoveUnusedValuesCodeFixProvider

If this is a report about a bug in an analyzer, please include the diagnostic ID and message if possible (e.g. `"IDE0030: Use coalesce expression"`).

**Expected Behavior**:

No yellow bars.

**Actual Behavior**:

![image](https://github.com/user-attachments/assets/8e461733-8fab-4343-a7c3-27d584d27a93)

Getting an exception in VS (this is one of many that I get, starting to file issues that I'm having):

System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types,AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.MefHostExportProvider.Create(String languageName)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key,CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices..ctor(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.Create(HostLanguageServices hostLanguageServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key,CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions.GetExtendedLanguageServices(Project project)
   at Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.IsForEachIterationVariableDiagnostic(Diagnostic diagnostic,Document document,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.RegisterCodeFixesAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by CyrusNajmabadi** [comment]
@sharwell can you dupe this against the primary issue?  Thanks!

**Comment by mkchandler** [comment]
I have been running into this issue a lot in Visual Studio 2026 as well. Will be following the journey of pull request #82442 that hopefully resolves this.

**Comment by deadman2000** [comment]
Same problem on Visual Studioo 2026 18.4.0.
Very annoying

**Comment by CyrusNajmabadi** [comment]
@deadman2000 please provide a repro so we can look at your case. Thanks.

**Comment by deadman2000** [comment]
@CyrusNajmabadi I found root of problem: analyzer version conflict.

Demonstration: https://github.com/deadman2000/vs_analyzer_problem

Open `Program.cs` and type `new MyRecord(`

**Comment by akhera99** [comment]
@deadman2000 this issue was fixed via https://github.com/dotnet/roslyn/pull/82442. The fix should flow through the SDK, but if you reference Microsoft.CodeAnalysis.CSharp.CodeStyle directly you can change the version to 5.3.0
