### ISSUE TITLE
GenerateTypeTests.TestGenerateVarType broken by #7515

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7516]
The test `GenerateTypeTests.TestGenerateVarType` is broken by #7515. Can someone on the IDE team please help me diagnose this?

The branch to work from is https://github.com/gafter/roslyn/tree/fix7387

**Comment by gafter** [comment]
Here is the symptom:

```none
------ Test started: Assembly: Roslyn.Services.Editor.CSharp.UnitTests.dll ------

Unknown .NET Framework Version: v4.6

Test 'Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.TestGenerateVarType' failed:
	Assert.NotNull() Failure
	CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(306,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<VerifyInputsAndGetOperationsAsync>d__21.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(212,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestActionsAsync>d__16.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(198,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	CodeActions\AbstractCodeActionOrUserDiagnosticTest.cs(162,0): at Microsoft.CodeAnalysis.Editor.UnitTests.CodeActions.AbstractCodeActionOrUserDiagnosticTest.<TestAsync>d__13.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	Diagnostics\GenerateType\GenerateTypeTests.cs(1388,0): at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateTypeTests.GenerateTypeTests.<TestGenerateVarType>d__138.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

7779 passed, 1 failed, 24 skipped (see 'Task List'), took 524.00 seconds (xUnit.net 2.1.0 build 3179).
```

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide: Anyone have any ideas of the top?

**Comment by CyrusNajmabadi** [comment]
Let me debug through this to find out.

**Comment by leppie** [comment]
@CyrusNajmabadi I already found the problem/fix, see https://github.com/dotnet/roslyn/pull/7515#issuecomment-165192650

**Comment by CyrusNajmabadi** [comment]
Hey Neal, the issue here is that "@var" is misclassified by the compiler as the "var" keyword.  Causing the following error to be emitted instead:

"test1.cs(1,41): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code"

I'm not sure what the reason for that is, but it seems useful to have a test that validates that @var doesn't produce that error in the compiler layer.  Once that gets fixed up, the IDE test will likely succeed again.

**Comment by CyrusNajmabadi** [comment]
Hi @leppie  Thanks for the investigation as well.  Looks like we both found it at the same time :)

**Comment by Pilchie** [comment]
Moving to compiler based on the investigations above.

**Comment by jaredpar** [comment]
@gafter the PR which should have fixed this (#7515) was closed apparently without merging.  Is this bug still active?  If so why did we close down the PR?

**Comment by NoneGiven** [comment]
@jaredpar Commit https://github.com/dotnet/roslyn/commit/cc10b52bc5f9c8ec5a81d8a9792270f95253da4d made by @gafter merged the changes from that PR (see "closed this in" at the bottom).

**Comment by jaredpar** [comment]
@NoneGiven thanks!
