### ISSUE TITLE
Can't move type to file due to `MoveTypeCodeRefactoringProvider` error

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#75405]
**Version Used**: 17.12 P2.1 with .NET 8 project (8.0.108 SDK)

**Stack trace**:

```
Microsoft.Assumes+InternalErrorException : Did not find new element in the hierarchy for item "REDACTED.cs". The item would have been added with type "Compile". The project item schema service knows about this item type. The item does not exist in the project file.
   at Microsoft.Assumes.Fail(String message)
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.EvaluateAddResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddItemAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToProjectItems(ProjectItems projectItems,DocumentId documentId,String folderPath,String documentName,SourceText initialText,String filePath,TextDocumentKind documentKind)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentToFolder(Project project,DocumentId documentId,IEnumerable`1 folders,String documentName,TextDocumentKind documentKind,SourceText initialText,String filePath)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.AddDocumentCore(DocumentInfo info,SourceText initialText,TextDocumentKind documentKind)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgress`1 progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgress`1 progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.ApplyOrMergeChanges(Workspace workspace,Solution originalSolution,Solution changedSolution,IProgress`1 progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApplyAsync(Workspace workspace,Solution originalSolution,IProgress`1 progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionEditHandlerService.ProcessOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

(May be related to recent Create & Copy File issues in VS?)

**Comment by CyrusNajmabadi** [comment]
We'd need a repro for this.  This appears to be an isue with some project system.  So we'd have to figure out waht about your project file is throwing them off.  Can you provide such a repro?  Thanks!

**Comment by Peter-Juhasz** [comment]
It was not something I could consistently repro, and as far as I remember trying it again for the second time usually succeeded.

I'll keep an eye on it and get back to you whether I still see it or not.
