### ISSUE TITLE
Several StreamJsonRpc.RemoteInvocationException/System.InvalidCastExceptions when working in a mixed VB/C# solution

### ISSUE THREAD

**Issue by ejdownescx** [dotnet/roslyn#75590]
Seen on Visual Studio Community 2022 Version 17.11.5.

When a solution with a mix of VB/C# projects is loaded, opening any file within is yielding a large stream of errors on features and providers:

![Image](https://github.com/user-attachments/assets/fece63e9-b617-4a69-af49-a5871aaf577b)

Dismissing them or trying to re-enable providers just results in the errors returning in the UI.

All of the stack traces are various flavors of one of the below, basically invalid casts:

```
StreamJsonRpc.RemoteInvocationException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode'.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode'.
      at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxTreeFactoryService.CreateSyntaxTree(String filePath, ParseOptions options, Encoding encoding, SourceHashAlgorithm checksumAlgorithm, SyntaxNode root)
      at Microsoft.CodeAnalysis.DocumentState.<UpdateTextAndTreeContentsWorker>g__TryReuseSiblingRoot|61_2(String filePath, LanguageServices languageServices, LoadTextOptions loadTextOptions, ParseOptions parseOptions, SyntaxNode siblingRoot, VersionStamp siblingVersion, Boolean forceEvenIfTreesWouldDiffer, TreeAndVersion& newTreeAndVersion)
      at Microsoft.CodeAnalysis.DocumentState.<UpdateTextAndTreeContentsWorker>g__TryReuseSiblingTreeAsync|61_3(String filePath, LanguageServices languageServices, LoadTextOptions loadTextOptions, ParseOptions parseOptions, ITreeAndVersionSource treeSource, ITextAndVersionSource siblingTextSource, ITreeAndVersionSource siblingTreeSource, Boolean forceEvenIfTreesWouldDiffer, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentState.GetTopLevelChangeTextVersionAsync(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.ProjectState.ComputeLatestDocumentTopLevelChangeVersionAsync(TextDocumentStates`1 documentStates, TextDocumentStates`1 additionalDocumentStates, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.ProjectState.GetSemanticVersionAsync(CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.ComputeDependentSemanticVersionAsync(SolutionCompilationState compilationState, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.SkeletonReferenceCache.GetOrBuildReferenceAsync(ICompilationTracker compilationTracker, SolutionCompilationState compilationState, MetadataReferenceProperties properties, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.GetMetadataReferenceAsync(ICompilationTracker tracker, ProjectState fromProject, ProjectReference projectReference, Boolean includeCrossLanguage, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<<GetOrBuildFinalStateAsync>g__FinalizeCompilationWorkerAsync|4>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<<GetOrBuildFinalStateAsync>g__FinalizeCompilationAsync|3>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<<GetOrBuildFinalStateAsync>g__BuildFinalStateAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetOrBuildFinalStateAsync(SolutionCompilationState compilationState, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetCompilationSlowAsync(SolutionCompilationState compilationState, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions.GetRequiredCompilationAsync(Project project, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Document.<>c__DisplayClass28_0.<<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Document.GetSemanticModelHelperAsync(Boolean disableNullableAnalysis, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(Document document, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetMemberSymbolsAsync(Document document, TextSpan spanToSearch, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetInheritanceMarginItemsInProcessAsync(Document document, TextSpan spanToSearch, Boolean includeGlobalImports, Boolean frozenPartialSemantics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.InheritanceMargin.AbstractInheritanceMarginService.GetInheritanceMemberItemsAsync(Document document, TextSpan spanToSearch, Boolean includeGlobalImports, Boolean frozenPartialSemantics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteInheritanceMarginService.<>c__DisplayClass2_0.<<GetInheritanceMarginItemsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode'.
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxTreeFactoryService.CreateSyntaxTree(String filePath,ParseOptions options,Encoding encoding,SourceHashAlgorithm checksumAlgorithm,SyntaxNode root)
   at Microsoft.CodeAnalysis.DocumentState.<UpdateTextAndTreeContentsWorker>g__TryReuseSiblingRoot|61_2(String filePath,LanguageServices languageServices,LoadTextOptions loadTextOptions,ParseOptions parseOptions,SyntaxNode siblingRoot,VersionStamp siblingVersion,Boolean forceEvenIfTreesWouldDiffer,TreeAndVersion& newTreeAndVersion)
   at async Microsoft.CodeAnalysis.DocumentState.<UpdateTextAndTreeContentsWorker>g__TryReuseSiblingTreeAsync|61_3(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.DocumentState.GetTopLevelChangeTextVersionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ProjectState.ComputeLatestDocumentTopLevelChangeVersionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ProjectState.GetSemanticVersionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.ComputeDependentSemanticVersionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.SkeletonReferenceCache.GetOrBuildReferenceAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.GetMetadataReferenceAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<GetOrBuildFinalStateAsync>g__FinalizeCompilationWorkerAsync|4(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<GetOrBuildFinalStateAsync>g__FinalizeCompilationAsync|3(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.<>c__DisplayClass23_0.<GetOrBuildFinalStateAsync>g__BuildFinalStateAsync|0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetOrBuildFinalStateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SolutionCompilationState.CompilationTracker.GetCompilationSlowAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions.GetRequiredCompilationAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Document.<>c__DisplayClass28_0.<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Document.GetSemanticModelHelperAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SemanticDocument.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<>c__DisplayClass12_0.<GetRefactoringFromProviderAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by CyrusNajmabadi** [comment]
Can you supply a repro project?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Created a fix.

**Comment by CyrusNajmabadi** [comment]
Thanks for the report!

**Comment by ejdownescx** [comment]
[ClassLibrary1.zip](https://github.com/user-attachments/files/17497823/ClassLibrary1.zip)

I think I found the cause and narrowed it down to the bare minimum attached repro. Looks like it happens when a single .cs file is included across a VB and a C# project.

Granted, the original offending solution shouldn't have included it in the first place, and removing it ended the errors. None of the messages mentioned it though, and it was by luck that I spotted the .cs file linked in the VB project amongst the huge number of files in the solution.

Weirdly enough, the .cs file is completely blank yet still causes the errors.

**Comment by CyrusNajmabadi** [comment]
> Weirdly enough, the .cs file is completely blank yet still causes the errors.

A blank file is legal C# and VB.  We create a C# syntax tree for the file contents, and then we attempt to share that into the VB project.  This blows up badly.  

The fix addresses exactly this.  While this should not be something we would expect people to do, we will at least not attempt to share tree contents across languages.  That way we don't blow up in the rare case where someone accidentally places a shared file into different language projects.
