### ISSUE TITLE
Roslyn crashes when opening a project without Visual Studio version 2017 or higher installed on a machine

### ISSUE THREAD

**Issue by NikiPn** [dotnet/roslyn#75886]
**Version Used**: 
4.13.0-2.24561.4

**Steps to Reproduce**:

1. Create a console application and add packages, 'Microsoft.CodeAnalysis' and 'Microsoft.CodeAnalysis.Workspaces.MSBuild' (version 4.13.0-2.24561.4).
The project file will be as follows:
```
<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="4.13.0-2.24561.4" />
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.13.0-2.24561.4" />
  </ItemGroup>
 
</Project>
```
2. Add this code fragment to the 'Main' method:
 ```
var workspace = MSBuildWorkspace.Create();
_ = workspace.OpenSolutionAsync("D:\\ MySolution.sln").Result;
```
3. Create a console app in a project templates for Visual Studio 2015. Open the project using the program created above.

**Expected Behavior**:
No exception.

**Actual Behavior**:
Exception is thrown:
 ```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager.<GetBuildHostAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager.<GetBuildHostWithFallbackAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
....
 ```

**Note**: We would like to note that this issue is critical for us. We would be grateful if you could assist us in fixing it. Furthermore, we would deeply appreciate it if you could tell us if there are any known possible workarounds.

This information may help you: MSBuildLocator can successfully register MSBuild for Visual Studio 2015.
 ``` 
MSBuildLocator.RegisterMSBuildPath(@"C:\Program Files (x86)\MSBuild\14.0\Bin"); 
```

**Comment by arunchndr** [comment]
VS 2015 only supports security fixes at this point I believe. This will not likely not fit our priority list.

**Comment by jasonmalinowski** [comment]
The error would make me think that the problem isn't anything to do with the project file itself, but rather we're having troubles launching our build host in the first place. We check for the existence of the build host DLL/EXE before running it...so maybe we're trying to launch dotnet.exe and that's not on the machine? Or wasn't on the path? @NikiPn if you still have a repro, can catch the exception under a debugger and take a dump file that'll be helpful here.

**Comment by jasonmalinowski** [comment]
Oh: I don't think we implemented Content support in NuGet until 2016 or so, so if you're building the consuming app with 2015 that just might not work.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski is there anything we need to do here, or is this just by design?

**Comment by jasonmalinowski** [comment]
It's either "by design" if indeed this is NuGet content not working in VS2015 (but that's now out of support anyways so we wouldn't fix it), or "needs more info" if that analysis is wrong.
