### ISSUE TITLE
Intermittent failure of ConditionalMemberAccessRace002

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#760]
I get intermittent failures of ConditionalMemberAccessRace002

When it fails, I see this:

```none
 Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002 : System.CannotUnloadAppDomainException : Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.System.IDisposable.Dispose() in D:\Roslyn\Open\src\Test\Utilities\HostedRuntimeEnvironment.cs:line 422
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.CompilationVerifier.cs:line 116
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitOptions, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 329
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 222
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String[] sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 155
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 119
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`1 sourceSymbolValidator, Action`2 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 79
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002() in D:\Roslyn\Open\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs:line 4244
```

**Comment by jaredpar** [comment]
This failure indicates we are attempting to unload an `AppDomain` while it was stuck in native code.  Is it possible we are in the PeVerify calls still?

**Comment by gafter** [comment]
Dup of #836... or is it the other way around?

**Comment by tmat** [comment]
Do we have a full dump?

**Comment by gafter** [comment]
I do not think we have a dump but it fails fairly often

**Comment by gafter** [comment]
Verified that the relevant test is not skipped and no longer appears to be flaky.
