### ISSUE TITLE
ArgumentOutOfRangeException in SyntaxNode.FindNode when writing invalid for loop

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#76114]
**Version Used**: VS IntPreview Version 17.13.0 Preview 2.0 [35518.259.main]

**Steps to Reproduce**:

Write the following into a .cs file in Visual Studio (notice the colon instead of semicolon - that's triggering the error):

```cs
Console.WriteLine();
int? x = 0;
for (int i = x ?? 0:)
```

<details>

<summary>Semantic classification crash stack trace</summary>

```
StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values. (Parameter 'span')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'span')
      at Microsoft.CodeAnalysis.SyntaxNode.FindNode(TextSpan span, Boolean findInsideTrivia, Boolean getInnermostNodeForTie)
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.<>c__DisplayClass5_0.<GetLocationsAsync>g__Recurse|0(TextSpan span, SemanticModel semanticModel)
      at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService`4.GetLocationsAsync(Document document, ImmutableArray`1 spans, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddClassificationsInCurrentProcessAsync(Document document, ImmutableArray`1 textSpans, ClassificationType type, ClassificationOptions options, SegmentedList`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddClassificationsAsync(Document document, ImmutableArray`1 textSpans, ClassificationOptions options, ClassificationType type, SegmentedList`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

</details>

(there are many more crashing services similarly, not just semantic classification)

**Comment by CyrusNajmabadi** [comment]
@sharwell  this is in:  at Microsoft.CodeAnalysis.ReassignedVariable.AbstractReassignedVariableService

**Comment by CyrusNajmabadi** [comment]
Closing out as neither myself nor Jan can repro this.
