### ISSUE TITLE
dotnet watch crashed while applying a code change.

### ISSUE THREAD

**Issue by tanveerbadar** [dotnet/roslyn#76137]
I don't have an exact repro for this issue but noticed the process had died with the following stack trace when I changed an int's value in my code.

dotnet watch ❌ System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.EmitParametersFromOriginalMetadata(IMethodDefinition methodDef, MethodDefinitionHandle handle)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.CreateIndicesForMethod(IMethodDefinition methodDef, SymbolChange methodChange)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.CreateIndicesForNonTypeMembers(ITypeDefinition typeDef)
   at Microsoft.Cci.MetadataWriter.CreateIndicesFor(ITypeDefinition typeDef, Queue`1 nestedTypes)
   at Microsoft.Cci.MetadataWriter.CreateIndicesForModule()
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.MetadataWriter.WriteMetadataAndIL(PdbWriter nativePdbWriterOpt, Stream metadataStream, Stream ilStream, Stream portablePdbStreamOpt, MetadataSizes& metadataSizes)
   at Microsoft.CodeAnalysis.Compilation.SerializeToDeltaStreams(CommonPEModuleBuilder moduleBeingBuilt, EmitBaseline baseline, DefinitionMap definitionMap, SymbolChanges changes, Stream metadataStream, Stream ilStream, Stream pdbStream, ArrayBuilder`1 updatedMethods, ArrayBuilder`1 changedTypes, DiagnosticBag diagnostics, Func`2 testSymWriterFactory, String pdbFilePath, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider activeStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExternalAccess.Watch.Api.WatchHotReloadService.GetUpdatesAsync(Solution solution, Func`2 isRunningProject, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.CompilationHandler.HandleFileChangesAsync(Func`3 restartPrompt, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred

dotnet --info
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.4872d5d5
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Unfortunately, I cannot provide more info at the point as I don't know exactly what might have caused this.

**Comment by hibbault** [comment]
Hitting the identical stack on **.NET SDK 10.0.103** (RTM) — `dotnet watch run` against an ASP.NET Core 10 + EF Core 10 + Hangfire app on Windows 11 (10.0.26200). One restart of `dotnet watch` clears it; reproduces again after a similar edit cadence.

```
dotnet watch ❌ An unexpected error occurred: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.EmitParametersFromOriginalMetadata(IMethodDefinition methodDef, MethodDefinitionHandle handle)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.CreateIndicesForMethod(IMethodDefinition methodDef, SymbolChange methodChange)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.CreateIndicesForNonTypeMembers(ITypeDefinition typeDef)
   at Microsoft.Cci.MetadataWriter.<CreateIndicesForModule>g__createIndices|102_0(...)
   at Microsoft.Cci.MetadataWriter.CreateIndicesForModule()
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(...)
   at Microsoft.Cci.MetadataWriter.WriteMetadataAndIL(...)
   at Microsoft.CodeAnalysis.Compilation.SerializeToDeltaStreams(...)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(...)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(...)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(...)
   at Microsoft.CodeAnalysis.ExternalAccess.HotReload.Api.HotReloadService.GetUpdatesAsync(...)
   at Microsoft.DotNet.Watch.CompilationHandler.HandleManagedCodeChangesAsync(...)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(...)
```

### Environment
- **SDK:** `10.0.103` (`dotnet --version`)
- **OS:** Windows 11 Pro 10.0.26200.8457
- **App:** ASP.NET Core 10 web API, EF Core 10 (PostgreSQL), Hangfire, Elasticsearch.Net 8 client
- **No Razor / no Blazor / no source generators** beyond what EF Core 10 ships internally — so the source-generator-drift theory from #49448 doesn't apply here.

### Stable trigger (single session, no restart)
1. `dotnet watch run`, let the host boot (slow first launch — Testcontainers, EF migrations apply, seeders run, ~30–45 s).
2. Make several edits to a single `.cs` file — the kind of edits LLM-driven coding sessions produce:
   - add a new method (`private static int SeedXxxAttrs(...)`)
   - modify an existing method body (string-replace blocks)
   - rename a parameter
   - add or remove a parameter on a `private static` method
3. Each edit triggers a successful hot-reload patch (`dotnet watch ⌚ Hot reload of changes succeeded`).
4. Around the 10th–20th successful patch in one session, the IOOR fires and `dotnet watch` exits. Restarting `dotnet watch` (fresh baseline) takes another ~15 minutes of similar edits before it recurs.

Subjective pattern: crashes correlate with **edits that change a private static method's parameter list** after several body-only edits to the same file have already succeeded. Not 100% confirmed — I don't have a one-shot deterministic reproducer.

### Offer
Happy to capture `Microsoft_CodeAnalysis_EditAndContinue_LogDir` output on the next reproduction if that would help. If there's a specific MSBuild flag or environment variable you'd want set during the watch session (e.g. `DOTNET_WATCH_ITERATION_LOG=1`, EnC dump-on-failure), let me know and I'll re-run.

The repo is a closed-source customer build, so I can't share the full source, but I can extract a minimal-shape reproducer (private-static methods with similar parameter shapes in a stub project) if that would unblock you.

**Comment by tmat** [comment]
@hibbault  `Microsoft_CodeAnalysis_EditAndContinue_LogDir` logs or minimal repro would be greatly appreciated!

The logs contain parts of the code, so you might not want to share them publicly. Please file ticket on https://developercommunity.visualstudio.com/ if you need to share private bits.

**Comment by hibbault** [comment]
Follow-up — a closer look at the session that triggered the earlier crashes suggests a more specific pattern than my first comment implied:

- Adding **5+ new `private static` methods** to the same class in one watch session (each a fresh `Microsoft.CodeAnalysis.EditAndContinue` capability `AddMethodToExistingType` request)
- Extending an existing `if / else if` dispatch chain in the same file to call into those new methods (body change on the caller after each new method)
- Mixed with body-only refactors elsewhere in the same class (an N+1 query fix that reshaped a per-row loop)
- All without restarting `dotnet watch`

So it's less "10–20th edit triggers it" and more "a session of bulk method additions + dispatch-chain restructure in one file". I'm captured `Microsoft_CodeAnalysis_EditAndContinue_LogDir` traces from a re-attempt today — the logs show repeated `ENC1008` "stale project" warnings + `Checksum differs` for the file under edit + multiple `Debugging session started: #N` lines (silent watch restarts), but I didn't capture a fresh IOOR. Will keep the env var set in my dev shell and ping back here as soon as a crash + log set lines up; happy to file a private developer-community ticket at that point with the source-bearing logs.
