### ISSUE TITLE
CompilerServerUnitTests.MultipleSimultaneousCompiles failed 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#7618]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2290/console

```
  Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MultipleSimultaneousCompiles
      Assert.Equal() Failure
      Expected: 20
      Actual:   19
      Stack Trace:
        src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(259,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<Verify>d__35.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(1010,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<MultipleSimultaneousCompiles>d__63.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by tmat** [comment]
@dotnet/roslyn-compiler

**Comment by amcasey** [comment]
Failed again: Roslyn-Master-Signed-Release\20160106.1\xUnitResults

**Comment by jaredpar** [comment]
I believe the problem here is the Jenkins machine is under serious load.  As a result the server simply can't keep up with the requests being sent and one of them falls back to a local compilation.  That throws off the test which is expecting that all of them complete on the server.  

Need to change the suite so that it accounts for this possibility.
