### ISSUE TITLE
System.ArgumentOutOfRangeException from Microsoft.CodeAnalysis.CSharp

### ISSUE THREAD

**Issue by patheikkinen** [dotnet/roslyn#76225]
**Version Used**: Visual Studio 2022 Professional 17.12.1 - and whatever Roslyn version is included. ALso using ReSharper.

**Steps to Reproduce**:

Not sure about the exact steps as I cannot post the actual source code here and won't bother to try too hard to locate the problem, but here's a rough description of what I did.

I had (have) a lambda defined in a rather long method and placed in a variable. It takes an object reference as a parameter and is used to call a delegate using the parameter, among other things, and then return the object. So I have something like this:

`var callStuffAndReturn = (FancyClass fancy) =>
{
    do stuff...
    return fancy;
}
`

so I can do this in a couple of places without repeating myself:

`return callStuffAndReturn(aThing)`

Yeah I know I could implement this using a local method, but this is what crashed the code analysis so that's what I'm reporting.

After implementing this I started getting "Feature 'Diagnostic analyzer runner' is currently unavailable due to an internal error." The stack trace looks like this:

`StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values. (Parameter 'character')
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'character')
      at Microsoft.CodeAnalysis.Text.LinePosition..ctor(Int32 line, Int32 character)
      at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
      at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SourceLocation.GetLineSpan()
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.CreateLocation(TextDocument document, Location location)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, TextDocument document)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDocumentDiagnostic(Dictionary`2& map, TextDocument document, Diagnostic diagnostic)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDiagnostic(Dictionary`2& lazyLocals, SyntaxTree tree, Diagnostic diagnostic)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDiagnostics(Dictionary`2& lazyLocals, SyntaxTree tree, IEnumerable`1 diagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<ToResultBuilderMapAsync>g__AddDiagnosticsToResult|7_1(ImmutableArray`1 diagnostics, DiagnosticAnalysisResultBuilder& result, Compilation compilation, SyntaxTree tree, DocumentId additionalDocumentId, Nullable`1 span, AnalysisKind kind, ImmutableArray`1 diagnosticIdsToFilter, Boolean includeSuppressedDiagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.ToResultBuilderMapAsync(AnalysisResult analysisResult, ImmutableArray`1 additionalPragmaSuppressionDiagnostics, DocumentAnalysisScope documentAnalysisScope, Project project, VersionStamp version, Compilation compilation, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzersPair compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 projectAnalyzers, ImmutableArray`1 hostAnalyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass3_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)
`

**Expected Behavior**:

Code analysis doesn't crash.

**Actual Behavior**:

Code analysis crashes due to ArgumentOutOfRangeException.

**Workaround**:

Convert to a local method. Then it doesn't crash.

**Comment by patheikkinen** [comment]
Visual Studio shows the analyzers in the solution tree as dependencies, I suppose that's what you'd need?

`
C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll
C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll
C:\Users\pauhei\.nuget\packages\microsoft.extensions.logging.abstractions\9.0.0\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Logging.Generators.dll
C:\Users\pauhei\.nuget\packages\microsoft.extensions.options\9.0.0\analyzers\dotnet\roslyn4.4\cs\Microsoft.Extensions.Options.SourceGeneration.dll
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\analyzers\dotnet\cs\Microsoft.Interop.ComInterfaceGenerator.dll
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\analyzers\dotnet\cs\Microsoft.Interop.JavaScript.JSImportGenerator.dllC:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\analyzers\dotnet\cs\Microsoft.Interop.LibraryImportGenerator.dll
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\analyzers\dotnet\cs\Microsoft.Interop.SourceGeneration.dll
C:\Users\pauhei\.nuget\packages\system.text.json\9.0.0\analyzers\dotnet\roslyn4.4\cs\System.Text.Json.SourceGeneration.dll
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\analyzers\dotnet\cs\System.Text.RegularExpressions.Generator.dll
`

**Comment by ToddGrun** [comment]
@patheikkinen -- are you still hitting this issue? We think we know the offending commit, but it's rather large and not easy to deduce how it might have gone wrong. A repro would really help in tracking this down. If you are able to still repro, can you document the steps you used to do so? Out of curiosity, do you use standard windows newlines in your files (\r\n), or use a different newline format?

**Comment by patheikkinen** [comment]
@ToddGrun Newline format is unix style (\n). Since I worked around it by changing the code the same specific piece of code of course no longer triggers it for me... I can see about repro later but next few days will be quite busy.

**Comment by ToddGrun** [comment]
Very much appreciated!
