### ISSUE TITLE
Find-all-references fails on `SyntaxTree` in VSCode

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#76367]
**Version Used**: 4.13.0-3.24577.4 (6cc106c0), C# ext version v2.59.14 (pre-release)

**Steps to Reproduce**:

1. Open `src/Compilers/Core/Portable/Syntax/SyntaxTree.cs`
2. Invoke Find-All-References on the `SyntaxTree` identifier

**Expected Behavior**:

References are found.

**Actual Behavior**:

```
2024-12-10 17:56:31.700 [info] [Error - 5:56:31 PM] Request textDocument/references failed.
2024-12-10 17:56:31.700 [info]   Message: Object reference not set to an instance of an object.
  Code: -32000 
[object Object]
2024-12-10 17:57:08.113 [info] [Error - 5:57:08 PM] [LanguageServerHost] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.ChildSyntaxList.CountNodes(GreenNode green) in /_/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:line 42
   at Microsoft.CodeAnalysis.SyntaxNode.DescendantNodesAndTokensIntoTrivia(TextSpan span, Func`2 descendIntoChildren, Boolean includeSelf)+MoveNext()
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.CreateIndex(ProjectState project, SyntaxNode root, Checksum checksum, CancellationToken _) in /_/src/Workspaces/Core/Portable/FindSymbols/SyntaxTree/SyntaxTreeIndex_Create.cs:line 84
   at Microsoft.CodeAnalysis.FindSymbols.AbstractSyntaxIndex`1.CreateIndexAsync(ProjectState project, DocumentState document, Checksum textChecksum, Checksum textAndDirectivesChecksum, IndexCreator create, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/Shared/AbstractSyntaxIndex.cs:line 142
   at Microsoft.CodeAnalysis.FindSymbols.AbstractSyntaxIndex`1.GetIndexWorkerAsync(SolutionKey solutionKey, ProjectState project, DocumentState document, Boolean loadOnly, IndexReader read, IndexCreator create, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.AbstractSyntaxIndex`1.GetIndexAsync(SolutionKey solutionKey, ProjectState project, DocumentState document, Boolean loadOnly, IndexReader read, IndexCreator create, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.AbstractSyntaxIndex`1.GetRequiredIndexAsync(SolutionKey solutionKey, ProjectState project, DocumentState document, IndexReader read, IndexCreator create, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder`1.GetAllMatchingGlobalAliasNamesAsync(Project project, String name, Int32 arity, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs:line 875
   at Microsoft.CodeAnalysis.FindSymbols.Finders.AbstractReferenceFinder`1.GetAllMatchingGlobalAliasNamesAsync(Project project, String name, Int32 arity, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs:line 873
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.AddGlobalAliasesAsync(Project project, ImmutableArray`1 allSymbols, PooledDictionary`2 symbolToGlobalAliases, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 352
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, Action`1 onReferenceFound, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 226
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.ProcessProjectAsync(Project project, ImmutableArray`1 allSymbols, Action`1 onReferenceFound, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 266
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<>c__DisplayClass13_0.<<PerformSearchAsync>b__0>d.MoveNext() in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 122
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__57`1.<<ForEachAsync>b__57_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.PerformSearchAsync(ImmutableArray`1 symbols, Action`1 onReferenceFound, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 117
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.PerformSearchAsync(ImmutableArray`1 symbols, Action`1 onReferenceFound, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 117
   at Microsoft.CodeAnalysis.Shared.Utilities.ProducerConsumer`1.<>c__DisplayClass12_0`2.<<RunChannelAsync>g__ProduceItemsAndWriteToChannelAsync|2>d.MoveNext() in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ProducerConsumer.cs:line 322
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Shared.Utilities.ProducerConsumer`1.RunChannelAsync[TArgs,TResult](ProducerConsumerOptions options, Func`4 produceItems, Func`4 consumeItems, TArgs args, CancellationToken cancellationToken) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ProducerConsumer.cs:line 301
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 69
   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.FindReferencesAsync(ImmutableArray`1 symbols, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.cs:line 78
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, IStreamingFindReferencesProgress progress, IImmutableSet`1 documents, FindReferencesSearchOptions options, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_FindReferences_Current.cs:line 64
   at Microsoft.CodeAnalysis.FindUsages.AbstractFindUsagesService.FindReferencesAsync(IFindUsagesContext context, ISymbol symbol, Project project, FindReferencesSearchOptions searchOptions, OptionsProvider`1 classificationOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs:line 151
   at Microsoft.CodeAnalysis.FindUsages.AbstractFindUsagesService.FindSymbolReferencesAsync(IFindUsagesContext context, ISymbol symbol, Project project, OptionsProvider`1 classificationOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs:line 121
   at Microsoft.CodeAnalysis.FindUsages.AbstractFindUsagesService.FindSymbolReferencesAsync(IFindUsagesContext context, Document document, Int32 position, OptionsProvider`1 classificationOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs:line 99
   at Microsoft.CodeAnalysis.FindUsages.AbstractFindUsagesService.FindLiteralOrSymbolReferencesAsync(IFindUsagesContext context, Document document, Int32 position, OptionsProvider`1 classificationOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/FindUsages/AbstractFindUsagesService_FindReferences.cs:line 61
   at Microsoft.CodeAnalysis.LanguageServer.Handler.FindAllReferencesHandler.FindReferencesAsync(IProgress`1 progress, Workspace workspace, Document document, LinePosition linePosition, Boolean supportsVSExtensions, IGlobalOptionService globalOptions, IMetadataAsSourceFileService metadataAsSourceFileService, IAsynchronousOperationListener asyncListener, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs:line 88
   at Microsoft.CodeAnalysis.LanguageServer.Handler.FindAllReferencesHandler.HandleRequestAsync(VSInternalReferenceParams referenceParams, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/References/FindAllReferencesHandler.cs:line 64
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
```

**Comment by 333fred** [comment]
FYI @dibarbet

**Comment by 333fred** [comment]
Even weirder: when I make a subsequent Find-All-Refs call, I get mixed results:

![Image](https://github.com/user-attachments/assets/13ecaff9-f29a-4005-8f6f-09ebe40d3cff)

The Find-All-Refs call was on https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Errors/DiagnosticInfoWithSymbols.cs#L14, on `Symbols`.

**Comment by CyrusNajmabadi** [comment]
```
    at Microsoft.CodeAnalysis.ChildSyntaxList.CountNodes(GreenNode green) in /_/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:line 42
   at Microsoft.CodeAnalysis.SyntaxNode.DescendantNodesAndTokensIntoTrivia(TextSpan span, Func`2 descendIntoChildren, Boolean includeSelf)+MoveNext()
```

Well that seems bad.  Someone on compiler needs to see how we can have a tree we can't walk the descendant nodes/tokens of without crashing :(

**Comment by apostate0** [comment]
I'd like to work on this issue. Based on the stack trace, the NRE occurs in `ChildSyntaxList.CountNodes` when `green` is null. A simple null guard in the `CountNodes` method should fix this. Can I take this?

**Comment by CyrusNajmabadi** [comment]
No. We'd need to know how such a node got into the tree in the first place. That's the core bug here.  Papering over the crash would just be hiding that.

**Comment by apostate0** [comment]
You're right.
Looking at this issue, the crash occurs because a [SyntaxNode](cci:2://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs:25:4-1694:5) has a null `Green` property. The [SyntaxNode](cci:2://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs:25:4-1694:5) constructor sets `Green = green` directly without null checking, so for this to happen, a node must have been constructed with a null `GreenNode` parameter.

I've investigated the git history and found that commit [0b8371953e6](https://github.com/dotnet/roslyn/commit/0b8371953e6) (PR #73650 - "ChildSyntaxList.ItemInternal optimization") from June 13, 2024 introduced the [SlotData](cci:2://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:86:8-114:9) struct and optimized the [ItemInternal](cci:1://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:116:8-121:9) methods. This commit is included in the version mentioned in the issue (4.13.0-3.24577.4, commit 6cc106c from Nov 27, 2024).

A later commit [6e85e46dc82](https://github.com/dotnet/roslyn/commit/6e85e46dc82) (PR #82816 - "Optimize annotation search to avoid unnecessary red node creation") from March 22, 2026 added green node filtering logic that modified the same files involved in the crash, suggesting ongoing work in this area.

The investigation suggests that the SlotData optimization might have introduced a bug where slot information becomes corrupted or invalid, leading to a null Green being accessed. The [GetGreenChildAt](cci:1://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:183:8-194:9) method has a debug-only null assertion, so this would only be caught in debug builds.

Rather than papering over the crash with a null guard in [CountNodes](cci:1://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/ChildSyntaxList.cs:36:8-57:9) (which would hide the real bug), I've added a defensive check in the [SyntaxNode](cci:2://file:///d:/Projects/.NET/roslyn/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs:25:4-1694:5) constructor to fail fast with a clear error message when null is passed. This will expose the caller that's passing null and help identify the root cause.

I'm gonna investigate further with runtime debugging and determine where the corrupted node is being created and update here
