### ISSUE TITLE
Feature 'Diagnostic analyzer runner' is unavailable due to an internal error is not being resolved - We found 244274 similar items.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#76451]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Diagnostic-analyzer-runner-is-/10812543)._

---
\[severity:It’s more difficult to complete my work\] \[regression\] \[worked-in:Version 17.11.\*\]  
Because there seem to be a gazillion reports (or “We found 244274 similar items.”) most with the top items listed as being ‘Closed -Duplicate’ or ‘Closed - not enough info’, I was not able to find the one where to add my report details.

It also seems to show a long history of issues with this particular feature. And as I come to expect from MS these days, this stuff will continue to go on and be swept under the carpet for close to a decade. Yet that won’t stop me from reporting it.

---
Update: added extra logs as suggested: https://developercommunity.visualstudio.com/t/Feature-Diagnostic-analyzer-runner-is/10789271#T-N10789596
[92D03C76-ManagedLanguage.IDE.RemoteHostClient-37668-rcduuk2a-1.log](https://aka.ms/dc/file?name=Be22c9a928a4b48a98304b9af5ce492ac638696827733717239_92D03C76-ManagedLanguage.IDE.RemoteHostClient-37668-rcduuk2a-1.log&tid=e22c9a928a4b48a98304b9af5ce492ac638696827733717239)
[92D03C76-Microsoft.VisualStudio.LanguageServices.DiagnosticAnalyzerCore64-40716-j5fawt1c-1.log](https://aka.ms/dc/file?name=B427289bcb6bf470d9d36955cca7f3e64638696859736803707_92D03C76-Microsoft.VisualStudio.LanguageServices.DiagnosticAnalyzerCore64-40716-j5fawt1c-1.log&tid=427289bcb6bf470d9d36955cca7f3e64638696859736803707)
[92D03C76-Microsoft.VisualStudio.LanguageServices.ProcessTelemetryCore64-40716-vf2q14df-1.log](https://aka.ms/dc/file?name=Ba956d3492d354b41a6cdfb421c87d6ca638696859894250662_92D03C76-Microsoft.VisualStudio.LanguageServices.ProcessTelemetryCore64-40716-vf2q14df-1.log&tid=a956d3492d354b41a6cdfb421c87d6ca638696859894250662)

```  
StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values. (Parameter 'character')
   at StreamJsonRpc.JsonRpc. &lt;InvokeCoreAsync&gt;d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1. &lt;TryInvokeAsync&gt;d__18`1.MoveNext()
RPC server exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'character')
      at Microsoft.CodeAnalysis.Text.LinePosition.. ctor(Int32 line, Int32 character)
      at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
      at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.SourceLocation.GetLineSpan()
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData. &lt;CreateLocation&gt;g__GetLocationInfo|30_0(FileLinePositionSpan& originalLineInfo, FileLinePositionSpan& mappedLineInfo, &lt;&gt;c__DisplayClass30_0&)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.CreateLocation(TextDocument document, Location location)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, TextDocument document)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDocumentDiagnostic(Dictionary`2& map, TextDocument document, Diagnostic diagnostic)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDiagnostics(Dictionary`2& lazyLocals, SyntaxTree tree, IEnumerable`1 diagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions. &lt;ToResultBuilderMapAsync&gt;g__AddDiagnosticsToResult|7_1(ImmutableArray`1 diagnostics, DiagnosticAnalysisResultBuilder& result, SyntaxTree tree, DocumentId additionalDocumentId, Nullable`1 span, AnalysisKind kind, ImmutableArray`1 diagnosticIdsToFilter, Boolean includeSuppressedDiagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.ToResultBuilderMapAsync(AnalysisResultPair analysisResult, ImmutableArray`1 additionalPragmaSuppressionDiagnostics, DocumentAnalysisScope documentAnalysisScope, Project project, VersionStamp version, ImmutableArray`1 projectAnalyzers, ImmutableArray`1 hostAnalyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzersPair compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 projectAnalyzers, ImmutableArray`1 hostAnalyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.&lt;&gt;c__DisplayClass3_0. &lt;&lt;CalculateDiagnosticsAsync&gt;b__0&gt;d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.&lt;&gt;c__DisplayClass7_0`1. &lt;&lt;RunWithSolutionAsync&gt;g__ProcessSolutionAsync|1&gt;d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)
  
```

---
#### Feedback Bot on 12/13/2024, 00:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/16/2024, 01:25 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by CyrusNajmabadi** [comment]
Already reported at: https://github.com/dotnet/roslyn/issues/50496#issuecomment-2540954720

**Comment by sharwell** [comment]
@CyrusNajmabadi The duplicate in this case should go the other way. I'm seeing numerous reports of this issue.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2321725
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2329879
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2455417

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/78025 which compiler is already looking at.
