### ISSUE TITLE
IndexOutOfRangeException in UseConcreteTypeAnalyzer

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#76546]
**Version Used**: 17.13.0 Preview 2.1

```
Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.Workspaces
IOperation: Invocation
SyntaxTree: D:\Source\roslyn\src\Workspaces\Core\Portable\Storage\SQLite\v2\SQLitePersistentStorage_Threading.cs
SyntaxNode: vt.Item1() [InvocationExpressionSyntax]@[3458..3468) (61,12)-(61,22)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Analyzer.Utilities.AnalyzerOptionsExtensions.TryGetSyntaxTreeForOption(ISymbol symbol, SyntaxTree& tree)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.<>c__DisplayClass9_1.<Initialize>b__4(ISymbol symbol)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.Collector.HandleInvocation(IInvocationOperation op)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: CA1859
```

**Comment by jnm2** [comment]
Wrong repo! This belongs in <https://github.com/dotnet/roslyn-analyzers>.
