### ISSUE TITLE
Wrong results from VB variable.Type.ToString

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#7698]
I am looking to Analyze AbstractFlowPass.VB in Roslyn Source specifically the second line.

```
Dim caseBlockStateBuilder = ArrayBuilder(Of LocalState).GetInstance(caseBlocks.Length)
```

I am trying to get the Type of ArrayBuilder(Of LocalState).GetInstance(caseBlocks.Length) which I believe is an ArrayBuilder(Of LocalState). using the Snippet of code below.

```
Dim variableType As TypeInfo = Model.GetTypeInfo(lVariableDeclarator.Initializer.Value)
Dim expressionType As ITypeSymbol = variableTypeInfo.Type
```

The variable expressionType contains the Type and looks almost perfect, except for the exception, in the Immediate Window as it is a NamedType whose value is Microsoft.CodeAnalysis.ArrayBuilder(Of LocalState).

```
?expressionType
NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of LocalState)
    AllInterfaces: Length = 4
    Arity: 1
    AssociatedSymbol: Nothing
    BaseType: NamedType System.Object
    CanBeReferencedByName: True
    ConstructedFrom: NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    Constructors: Length = 2
    ContainingAssembly: Assembly Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    ContainingModule: NetModule Microsoft.CodeAnalysis.dll
    ContainingNamespace: Namespace Microsoft.CodeAnalysis
    ContainingSymbol: Namespace Microsoft.CodeAnalysis
    ContainingType: Nothing
    DeclaredAccessibility: Friend {4}
    DeclaringSyntaxReferences: Length = 0
    DefaultMarshallingCharSet: 'DirectCast(expressionType, Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol).DefaultMarshallingCharSet' threw an exception of type 'System.InvalidOperationException'
    DelegateInvokeMethod: Nothing
    EnumUnderlyingType: Nothing
    HasUnsupportedMetadata: False
    HighestPriorityUseSiteError: 30649
    ISymbol_IsAbstract: False
    ISymbol_IsSealed: True
    ISymbol_IsStatic: False
    InstanceConstructors: Length = 2
    Interfaces: Length = 4
    IsAnonymousType: False
    IsDefinition: False
    IsGenericType: True
    IsImplicitClass: False
    IsImplicitlyDeclared: False
    IsMustInherit: False
    IsMustOverride: False
    IsNamespace: False
    IsNotInheritable: True
    IsNotOverridable: False
    IsOverridable: False
    IsOverrides: False
    IsReferenceType: True
    IsScriptClass: False
    IsShared: False
    IsSubmissionClass: False
    IsType: True
    IsUnboundGenericType: False
    IsValueType: False
    Kind: NamedType {11}
    Language: "Visual Basic"
    Locations: Length = 1
    MemberNames: {Roslyn.Utilities.SpecializedCollections.ReadOnly.Collection(Of System.Collections.Generic.ICollection(Of String), String)}
    MetadataName: "ArrayBuilder`1"
    MightContainExtensionMethods: False
    Name: "ArrayBuilder"
    OriginalDefinition (Microsoft.CodeAnalysis.VisualBasic.Symbol): NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    OriginalDefinition (Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol): NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    OriginalDefinition: NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    OriginalSymbolDefinition: NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    OriginalTypeSymbolDefinition: NamedType Microsoft.CodeAnalysis.ArrayBuilder(Of T)
    SharedConstructors: Length = 0
    SpecialType: None {0}
    TypeArguments: Length = 1
    TypeKind: Class {2}
    TypeParameters: Length = 1
```

But If I output expressionType.ToString in the mmediate Windows I get a strange result

```
?expressionType.tostring
"Microsoft.CodeAnalysis.ArrayBuilder(Of LocalState As Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of LocalState).AbstractLocalState)"
```

I have tried this same code on 10% of Roslyn Source and this is the only place so far I have seen this odd behavior. It looks like it throws an exception that I have not noticed before trying to get DefaultMarshallingCharSet: which in other cases is Ansi {2}.

**Comment by paul1956** [comment]
After some research it looks like this might be caused by the following errors
```
at Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE.PEModuleSymbol.get_DefaultMarshallingCharSet()
at Microsoft.CodeAnalysis.VisualBasic.Symbol.get_EffectiveDefaultMarshallingCharSet()
at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_DefaultMarshallingCharSet()
```
I am unable to set breakpoint at this location to see what is going on, and creating a test requires copying too much of Roslyn source because most of the symbol types involved are not public.

**Comment by gafter** [comment]
There are two issues here.

First is the exception.

Second is the fact that we display the constraint on the type parameter with an `As` clause, which seems wrong.

**Comment by paul1956** [comment]
@gafter the As clause is only displayed when you do a .ToString, if you display in the debugger it looks correct but you see the exceptions. I would have assumed that the first line in the debugger (NameType in the example) should match what you get with .ToString and you do almost all the time.

**Comment by paul1956** [comment]
@gafter I have another example which also has the exception but the issue may not be the same.

Trying to add As Clause
```
Dim sortedDefines As IOrderedEnumerable(Of <anonymous type: Key As String, Value As Object>)= parsedArgs.ParseOptions.PreprocessorSymbols.Select(Function(d) New With {d.Key, d.Value}).OrderBy(Function(o) o.Key)
```
The Type of the initializer is  IOrderedEnumerable(Of <anonymous type: Key As String, Value As Object>). This is also shown by the error BC30512 when I try to type the variable as something random.
```
Code	Description
BC30512	Option Strict On disallows implicit conversions from 'IOrderedEnumerable(Of <anonymous type: Key As String, Value As Object>)'…
```
If I set it to the Type expected I get 7 errors
```
Code	Description
BC30180	Keyword does not name a type.
BC30201	Expression expected.
BC30451	'Key' is not declared. It may be inaccessible due to its protection level.
BC30451	'Value' is not declared. It may be inaccessible due to its protection level.
BC30451	'PreprocessorSymbols' is not declared. It may be inaccessible due to its protection level.
BC30800	Method arguments must be enclosed in parentheses.
BC32017	Comma, ')', or a valid expression continuation expected.
```

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Would need more information from paul if this is still a problem.

**Comment by paul1956** [comment]
Haven't run into this recently. I will close.
