### ISSUE TITLE
Flaky test: CompilerServerUnitTests.MultipleSimultaneousCompiles

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7801]
Roslyn-Master-Signed-Release\20160106.1\xUnitResults
```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Compilers.CompilerServer.UnitTests
  Discovered:  Roslyn.Compilers.CompilerServer.UnitTests
  Starting:    Roslyn.Compilers.CompilerServer.UnitTests
      Assert.Equal() Failure
      Expected: 20
      Actual:   19
      Stack Trace:
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(259,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<Verify>d__35.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs(1010,0): at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<MultipleSimultaneousCompiles>d__63.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.ServerRespectsAppConfig [SKIP]
      DevDiv 1095079
  Finished:    Roslyn.Compilers.CompilerServer.UnitTests
=== TEST EXECUTION SUMMARY ===
   Roslyn.Compilers.CompilerServer.UnitTests  Total: 73, Errors: 0, Failed: 1, Skipped: 1, Time: 415.713s
```

**Comment by amcasey** [comment]
Interesting.  It looks like the test is *already* skipped: `Fact(Skip = "DevDiv 1095079")`

**Comment by amcasey** [comment]
I notice that the test is async, which is probably a recent change.  Is it possible that that interacts badly with `Skip`?

**Comment by amcasey** [comment]
Oops, misread the log file.  I thought the test name at the bottom of the stack trace was the failing test, but it's actually unrelated output.  It appears that the actual failure was in `MultipleSimultaneousCompiles`.

**Comment by amcasey** [comment]
Dup of https://github.com/dotnet/roslyn/issues/7618
