### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'CompilationMergedNamespaceSymbol' to type 'Microsoft.CodeAnalysis.IMethodSymbol'

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#786]
System.InvalidCastException: Unable to cast object of type 'CompilationMergedNamespaceSymbol' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISymbolExtensions.ConvertToType(ISymbol symbol, Compilation compilation, Boolean extensionUsedAsInstance)
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.ExpressionSyntaxExtensions.DetermineType(ExpressionSyntax expression, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.GenerateMember.GenerateMethod.VisualBasicGenerateParameterizedMemberService`1.InvocationExpressionInfo._Closure$__9-0._Lambda$__1(ArgumentSyntax a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.VisualBasic.GenerateMember.GenerateMethod.VisualBasicGenerateParameterizedMemberService`1.InvocationExpressionInfo.DetermineParameterTypes(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.SignatureInfo.DetermineParameters(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.SignatureInfo.GenerateMethod(SyntaxGenerator factory, Boolean isAbstract, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.&lt;TryFinishInitializingState&gt;d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.&lt;GenerateMethodStateAsync&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.&lt;GenerateMethodAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.&lt;RegisterCodeFixesAsync&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&lt;PerformActionAsync&gt;d__2.MoveNext()</description>

**Comment by amcasey** [comment]
FYI @rchande

**Comment by rchande** [comment]
@jmarolf Have you guys seen this before?

**Comment by jmarolf** [comment]
Have not seen this before.  Will take a look.

**Comment by srivatsn** [comment]
Fixed by #1809

**Comment by amcasey** [comment]
We don't have repro steps, but the fix looks good to me.
