### ISSUE TITLE
NRE at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<GetNamespacesForMatchingExtensionMethodsAsync>

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#794]
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<GetNamespacesForMatchingExtensionMethodsAsync>d__20.MoveNext() in C:\Roslyn\Open\src\Features\Core\CodeFixes\AddImport\AbstractAddImportCodeFixProvider.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<RegisterCodeFixesAsync>d__15.MoveNext() in C:\Roslyn\Open\src\Features\Core\CodeFixes\AddImport\AbstractAddImportCodeFixProvider.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()

**Comment by mavasani** [comment]
Dump shared at %internal_share%\dumps\794\devenv.dmp

@jmarolf you probably want to take a look.

**Comment by jmarolf** [comment]
@mavasani Can you verify that this is fixed?

**Comment by mavasani** [comment]
Well, I don't have a repro. I hit this while dogfooding. Closing this out.. Thanks for the fix.
