### ISSUE TITLE
Flaky test : project system csharp unit test failed randomly in an unrelated PR against future branch.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8060]
###### Failure log : [link](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2948/artifact/Binaries/Debug/ProjectSystem/Tests/xUnitResults/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests.dll.out.log)

~~~
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
  Discovered:  Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
  Starting:    Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
    ApplyModifications_TreeWithNestedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder ("...)
    ApplyModifications_TreeWithNestedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder ("...)
    ApplyModifications_TreeWithNestedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder1 "...)
    Constructor_NullAsImageProvider_ThrowsArgumentNull
    Constructor_NullAsDesignerService_ThrowsArgumentNull
    ApplyModifications_TreeWithPropertiesCandidateButSupportsProjectDesignerFalse_ReturnsUnmodifiedTree
    ApplyModifications_TreeWithPropertiesCandidateAlreadyMarkedAsAppDesigner_ReturnsUnmodifiedTree(input: "\r\nRoot(capabilities: {ProjectRoot})\r\n    Propertie"...)
    ApplyModifications_TreeWithPropertiesCandidateAlreadyMarkedAsAppDesigner_ReturnsUnmodifiedTree(input: "\r\nRoot(capabilities: {ProjectRoot})\r\n    Propertie"...)
    ApplyModifications_TreeWithPropertiesCandidateAlreadyMarkedAsAppDesigner_ReturnsUnmodifiedTree(input: "\r\nRoot(capabilities: {ProjectRoot})\r\n    Propertie"...)
    ApplyModifications2_NullAsTree_ThrowsArgumentNull
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    PROPERTI"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    PROPERTI"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithPropertiesCandidate_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"..., expected: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications1_NullAsTreeProvider_ThrowsArgumentNull
    ApplyModifications_ProjectWithNonDefaultPropertiesFolder_ReturnsCandidateMarkedWithAppDesignerFolderAndBubbleUp
    ApplyModifications2_NullAsTreeProvider_ThrowsArgumentNull
    ApplyModifications_TreeWithFileCalledProperties_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithFileCalledProperties_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithFileCalledProperties_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    Constructor_NullAsProjectServices_ThrowsArgumentNull
    ApplyModifications_TreeWithExcludedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithExcludedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithExcludedPropertiesFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Properti"...)
    ApplyModifications_TreeWithMyProjectFolder_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    My Proje"...)
    ApplyModifications_TreeWithoutPropertiesCandidate_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n")
    ApplyModifications_TreeWithoutPropertiesCandidate_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder ("...)
    ApplyModifications_TreeWithoutPropertiesCandidate_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder ("...)
    ApplyModifications_TreeWithoutPropertiesCandidate_ReturnsUnmodifiedTree(input: "\r\nRoot (capabilities: {ProjectRoot})\r\n    Folder ("...)
    ApplyModifications_ProjectWithEmptyPropertiesFolder_DefaultsToProperties
    ApplyModifications1_NullAsTree_ThrowsArgumentNull
    ApplyModifications_ProjectWithNullPropertiesFolder_DefaultsToProperties
  Finished:    Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
~~~

**Comment by davkean** [comment]
This has been fixed.
