### ISSUE TITLE
VSI tests are unable to deal with segmented quick actions menu. 

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8112]
BasicCodeActions, CSharpCodeActions, and CSharpGenerateFromUsage are all failing in the standalone context on the latest vsuml build due to recent changes to the Quick Actions menu.

BasicCodeAction's is below. As you can see in the exception, the correct text is present. However the testrunner isn't finding that line and isn't finding several of the lines in addition to finding extra 'Preview changes' lines.

![image](https://cloud.githubusercontent.com/assets/10537189/12521037/fa74659a-c0fc-11e5-8741-2b7e79d97244.png)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Tao.Engine.Exceptions.UnexpectedResultException: ISuggestedAction Introduce local constant for '4 + 4' not found.  Buffer content type=Basic
Actions: Actual ISuggestedAction: Generate method 'Program.Foo'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Change 'Foo' to 'For'.
Actual ISuggestedAction: Preview changes

   at Roslyn.VSHosting.Test.RoslynInProcessAPI.<>c__DisplayClass22_0.<VerifyCodeActions>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.Test.Apex.Hosts.Services.UIThreadInvokerHelper.InvokeByAction(Object[] values)
   at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments)

**Comment by mattscheffer** [comment]
This has been fixed in VSUML by Oleg Tkachenko. Verified passing now
