### ISSUE TITLE
Inline Temporary Variable fails in VB when references exist with varying casing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8119]
Paste VB (note the lowercase "list" on the `Banana` line):
```VB
Class C
    Sub M()
        Dim List As New List(Of String)
        List.Add("Apple")
        list.Add("Banana")
    End Sub
End Class
```
Ctrl+. on the declaration of `List` causes `InlineTemporaryCodeRefactoringProvider` to fail and show the infobar.

**Comment by dpoeschl** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
```
   at Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.VB$StateMachine_20_DetectSemanticConflicts.MoveNext() in C:\src\roslyn-internal\Open\src\Features\VisualBasic\Portable\CodeRefactorings\InlineTemporary\InlineTemporaryCodeRefactoringProvider.vb:line 470
   at Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings.InlineTemporary.InlineTemporaryCodeRefactoringProvider.VB$StateMachine_10_InlineTemporaryAsync.MoveNext() in C:\src\roslyn-internal\Open\src\Features\VisualBasic\Portable\CodeRefactorings\InlineTemporary\InlineTemporaryCodeRefactoringProvider.vb:line 234
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionAsync>d__16.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 122
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputeOperationsAsync>d__14.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\CodeActions\CodeAction.cs:line 98
```
