### ISSUE TITLE
Replacing a VariableDeclaratorSyntax with DocumentEditor.ReplaceNode introduces an InvalidCastException

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#8154]
When trying to replace a `VariableDeclaratorSyntax` node with a modified `VariableDeclaratorSyntax` it throws an exception with message

> Unable to cast object of type '`Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax`' to type '`Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax`'

I discovered the issue by modifying the declarator using `.WithAdditionalAnnotations` but an investigation by @dpoeschl indicated that any sort of modification reproduces the problem.

Below the code to reproduce. Using the commented replacement will throw the exception.

```csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Text;

namespace ConsoleApplication1
{
    internal class Test
    {
        internal static void Execute()
        {
            var source = @"
using System;
using System.Text;
namespace ConsoleApplication1
{
    class MyClass
    {
        private int oAsInt32;
        void Method(object o)
        {
            if (o is int)
            {
                var oAsInt = (int)o;
                Console.Write(oAsInt);
                Console.Write(this.oAsInt32);
            }
        }
    }
}";

            var workspace = new AdhocWorkspace();
            var project = workspace.AddProject(ProjectInfo.Create(ProjectId.CreateNewId(), VersionStamp.Create(), "NewProject", "projName", LanguageNames.CSharp));
            var document = workspace.AddDocument(project.Id, "NewFile.cs", SourceText.From(source));
            var root = document.GetSyntaxRootAsync().Result;
            var editor = DocumentEditor.CreateAsync(document).Result;

            var ifStatement = root.DescendantNodes().OfType<IfStatementSyntax>().Single();

            var declarator = ifStatement.DescendantNodes().OfType<VariableDeclaratorSyntax>().First();
            //editor.ReplaceNode(declarator, declarator.WithAdditionalAnnotations(new SyntaxAnnotation("QueueRename")));
            editor.ReplaceNode(declarator, declarator);

            var result = editor.GetChangedDocument();
            Console.WriteLine(result.GetTextAsync().Result);
        }
    }
}
```

====
Full stacktrace:
====

```
System.InvalidCastException was unhandled
  HResult=-2147467262
  Message=Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax'.
  Source=Microsoft.CodeAnalysis.CSharp
  StackTrace:
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIfStatement(IfStatementSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
       at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNode[TRoot](TRoot root, SyntaxNode oldNode, SyntaxNode newNode)
       at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.ReplaceRange(SyntaxNode root, SyntaxNode node, IEnumerable`1 replacements)
       at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root, SyntaxNode declaration, SyntaxNode newDeclaration)
       at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root, SyntaxGenerator generator)
       at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
       at Microsoft.CodeAnalysis.Editing.DocumentEditor.GetChangedDocument()
       at ConsoleApplication1.Test.Execute() in D:\Github\Thesis\SourceCode\ThesisConsole\ConsoleApplication1\Test.cs:line 49
       at ConsoleApplication1.Program.Main(String[] args) in D:\Github\Thesis\SourceCode\ThesisConsole\ConsoleApplication1\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by dpoeschl** [comment]
@Vannevelj - Thanks for the report & detailed repro!

We get to http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpSyntaxGenerator.cs,3085, and then call SplitAndReplace with a LocalDeclarationStatementSyntax as the `fullDecl`. This returns a list of **declarators**, including the updated declarator with the annotation. So far so good.

But then we call ReplaceRange with the *DeclarationStatement* and the list of *declarators* to replace it with, but you can't replace a declaration with a declarator. It's not clear to me what the contract here is, whether SplitAndReplace is supposed to return the same type of node as `multiPartDeclaration`, or whether ReplaceNode (at the location of the link above) should be reconstructing the LocalDeclarationStatementSyntax from the declarators before passing them on to ReplaceRange.

/cc: @mattwar

**Comment by dpoeschl** [comment]
Actually, I'm not sure about the Area

**Comment by Sebazzz** [comment]
Same exception happens as well with this setup:

    public sealed class ClassWithRemovedTranslationAttributes {
        
        public int Id { get; set; }

        [TranslateProperty]
        public string Name { get; set; }

        [TranslateProperty]
        public string Description { get; set; }
    }

    // (boilerplate skipped for brevity: get document, find one of the attributes)
    AttributeSyntax declaration = ; //...

    DocumentEditor documentEditor = await DocumentEditor.CreateAsync(document, cancellationToken);

    AttributeSyntax replacementAttribute = Attribute(IdentifierName("Translatable"));
    documentEditor.ReplaceNode(declaration, replacementAttribute);
           
    documentEditor.GetChangedDocument();
