### ISSUE TITLE
New line handling changed in Version 1.2

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#8200]
In version 1.0 the below code produced `lines1 == lines2 == 3`, while in 1.2 an exception is thrown in the last line. It seems like a super special corner case, but it introduces a breaking change in 1.2.

```C#
var code = "\n\r"; // Note, it's not "\r\n"
var tree = CSharpSyntaxTree.ParseText(code);
var lines1 = tree.GetText().Lines.Count; // 3
var lines2 = tree.GetLineSpan(Text.TextSpan.FromBounds(0, tree.Length)).EndLinePosition.Line + 1; // throws ArgumentOutOfRangeException
```

Exception details:
```
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: span
  ParamName=span
  Source=Microsoft.CodeAnalysis
  StackTrace:
       at Microsoft.CodeAnalysis.Text.TextLine.FromSpan(SourceText text, TextSpan span)
       at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
       at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.GetLineFromPosition(Int32 position)
       at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLinePosition(Int32 position)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetLineSpan(TextSpan span, CancellationToken cancellationToken)
...
  InnerException: 

```

This change in behavior was probably introduced in https://github.com/dotnet/roslyn/commit/174bf9450553b5cc45393f0462badebdf2712753, in `ParseLineStarts()`.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/9036
