### ISSUE TITLE
Passing relative path to strong name key file triggers Debug.Assert in csc.exe

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8360]
1. Get a debug build of the command line compiler.
2. Run:

`csc.exe /keyfile:..\..\..\NuGet.BuildTasks\build\PublicKey.snk /publicsign /out:test.exe`

where in this case you're passing some relative path to a key file (pick any).

*Assert*:
```
   at Microsoft.CodeAnalysis.StrongNameKeys.Create(String keyFilePath, CommonMessageProvider messageProvider) in D:\Projects\Roslyn\src\Compilers\Core\Portable\StrongName\StrongNameKeys.cs:line 98
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeStrongNameKeys() in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Symbols\Source\SourceAssemblySymbol.cs:line 478
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_StrongNameKeys() in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Symbols\Source\SourceAssemblySymbol.cs:line 503
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ValidateAttributeSemantics(DiagnosticBag diagnostics) in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Symbols\Source\SourceAssemblySymbol.cs:line 541
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Symbols\Source\SourceAssemblySymbol.cs:line 856
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2118
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1960
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 1895
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 381
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in D:\Projects\Roslyn\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) in D:\Projects\Roslyn\src\Compilers\Shared\Csc.cs:line 27
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Boolean utf8Output, TextWriter textWriter, Func`2 func) in D:\Projects\Roslyn\src\Compilers\Core\CommandLine\ConsoleUtil.cs:line 54
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) in D:\Projects\Roslyn\src\Compilers\Shared\Csc.cs:line 27
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) in D:\Projects\Roslyn\src\Compilers\Shared\DesktopBuildClient.cs:line 59
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter) in D:\Projects\Roslyn\src\Compilers\Core\CommandLine\BuildClient.cs:line 124
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader) in D:\Projects\Roslyn\src\Compilers\Shared\DesktopBuildClient.cs:line 54
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs) in D:\Projects\Roslyn\src\Compilers\CSharp\csc\Program.cs:line 15
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) in D:\Projects\Roslyn\src\Compilers\CSharp\csc\Program.cs:line 12
```

The problem is the code is internally asserting that the CompilationOptions type has a fully rooted path, but it doesn't. We're doing reads relative to the working directory, which seems pretty bad.

**Comment by VSadov** [comment]
According to @tmat CSC is supposed to normalize the path. So we have a real bug here.
 We may be forced to remove the assert for now since it is very noisy.

However, once this bug is fixed, the assert must be reinstated.
