### ISSUE TITLE
 Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests throws invalid operation exception

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8386]
Seeing this often on release builds

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
  Discovered:  Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
  Starting:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
    Microsoft.CodeAnalysis.UnitTests.GlobalAssemblyCacheTests.GetAssemblyIdentities [SKIP]
      https://github.com/dotnet/roslyn/issues/6179
  Finished:    Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

**Comment by davkean** [comment]
This is due to the event listener bug: https://github.com/dotnet/roslyn/issues/6358.

I've turned off AppDomain isolation in https://github.com/dotnet/roslyn/pull/8534 and https://github.com/dotnet/roslyn/pull/8672.
