### ISSUE TITLE
Inline rename crash

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#8412]
ArgumentOutOfRangeException at ```CSharpSimplificationService.Expander.VisitParenthesizedLambdaExpression```

Crash dump:
%internal_share%\public\tomat\Bugs\8412

Repro:
1) Pull Roslyn branch from ```https://github.com/tmat/roslyn/tree/EEPPDB```, commit ab6cc9cb34683323cf0d9065a6cd77b328753bb5
2) In ```src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\ExpressionCompilerTestBase.cs``` rename

```C#
internal static void WithRuntimeInstancePortableBug(Compilation compilation, IEnumerable<MetadataReference> references, Action<RuntimeInstance> validator)
```

to ```WithRuntimeInstance``` and accept the rename even though there is a collision with existing method.

Stack trace:
```
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.Replace(TNode nodeInList, TNode newNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Core\Portable\Syntax\SeparatedSyntaxList.cs:line 480
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitParenthesizedLambdaExpression(ParenthesizedLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 212
   at Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedLambdaExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 51330
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69607
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 274
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50774
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 179
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69592
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50571
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69577
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax originalNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 1027
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50379
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69905
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 54282
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69870
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 53836
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69643
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 254
   at Microsoft.CodeAnalysis.CSharp.Syntax.SimpleLambdaExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 51208
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69607
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 274
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50774
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 218
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69592
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50571
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69577
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax originalNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 1027
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50379
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69905
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 54282
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expand(SyntaxNode node, SemanticModel semanticModel, SyntaxAnnotation annotationForReplacedAliasIdentifier, Func`2 expandInsideNode, Boolean expandParameter, CancellationToken cancellationToken) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.cs:line 50
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 248
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69870
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 53836
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70428
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 60770
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70276
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 58673
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70196
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 57680
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70167
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 57295
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.AnnotateAndRename(RenameRewriterParameters parameters) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 39
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__26.MoveNext() in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 752
```

**Comment by dpoeschl** [comment]
@tmat - When I try this, I get 245 unresolvable conflicts, but the rename works without crashing. However, the compilation is full of errors -- it can't bind Compilation or MetadataReference or RuntimeInstance, for instance, so I wonder if I don't have an appropriate reproduction of your situation. Were there tons of errors in the code when you did this? If not, what might I be missing here?

**Comment by tmat** [comment]
Maybe it's been fixed? Have you checked the crash dump to see if there is anything obviously wrong?

**Comment by tmat** [comment]
Have you synced nugets?

**Comment by dpoeschl** [comment]
@jmarolf - You fixed a bunch of these before, and it didn't repro for me when I tried it last. Does this look like one of the ones you fixed?

**Comment by DustinCampbell** [comment]
I was able to reproduce the crash with the latest stabilization bits.

**Comment by DustinCampbell** [comment]
Looks like the problem is when the simplification engine expands a lambda's parameter list when there are more than one parameter. This is pretty bad.
