### ISSUE TITLE
BasicNaviageTo and CSharpNavigateTo are failing in standalone, when attempting to navigate to items in a not open class file

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8429]
This is occurring on latest ML build/standalone run

The log for BasicNavigateTo is below. When attempting manually, I don't see a way to get that file either via the Navigation Bar. (Which I assume its used for NaviagteTo).

Test: BasicNavigateTo started: 2/5/2016 1:37:56 PM
     Executing action [2/5/2016 1:37:56 PM] StartTarget
 Begin Waiting for Apex Communication
     Executing action [2/5/2016 1:37:56 PM] AddProject
     Executing action [2/5/2016 1:38:06 PM] AddItem
     Executing action [2/5/2016 1:38:06 PM] OpenFile
     Executing action [2/5/2016 1:38:06 PM] SetEditorText
     Executing action [2/5/2016 1:38:06 PM] CloseFile
     Executing action [2/5/2016 1:38:07 PM] AddItem
     Executing action [2/5/2016 1:38:07 PM] OpenFile
     Executing action [2/5/2016 1:38:07 PM] WaitForWorkspace
  Scenario: Verify 'Navigate To' class
     Executing action [2/5/2016 1:38:07 PM] NavigateTo
 NavigateTo threw an exception: a VS dump should be available
 --------------------------------
 Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToException: Search for FirstClass returned no results.

 Server stack trace: 
    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToSession.Navigate(String searchString, Int32 itemIndex, Int32 timeout, NavigationResult& returnValue)
    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex, Int32 timeout)
    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString, Int32 itemIndex)
    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

 Exception rethrown at [0]: 
    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
    at Microsoft.Test.Apex.VisualStudio.BrowsingAndNavigation.NavigateTo.NavigateToService.Navigate(String searchString)
    at Roslyn.VSHosting.Test.NavigateToAction.Execute(TaoEngine engine)
    at Tao.Engine.DebuggableActionExecutor.Execute()
    at Tao.Engine.DefaultActionExecutor.Execute()
 ================================

**Comment by mattscheffer** [comment]
Test has been passing the last few days. Closing
