### ISSUE TITLE
Several standalone integration tests fail to close target correctly

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8430]
BasicSnippets, BasicWPF, CSharpSnippets, and CSharpWPF are all failing in the latest ML build standalone context.

From what I can gather form the text, its occuring when closing the target. It may be due to the 'Force Close' option that they all show. It indicates that Microsoft.VisualStudio.Settings.15.0 or one of its dependencies can not be found. However, the binding redirect in devenv.exe.config is correct. As far as I can tell there aren't any conflicting redirects.

Test Log for BasicSnippets is below:

Test: BasicSnippets started: 2/5/2016 1:43:27 PM
     Executing action [2/5/2016 1:43:27 PM] StartTarget
 Begin Waiting for Apex Communication
     Executing action [2/5/2016 1:43:27 PM] CloseTarget
 Closing VS. force Close = True, closeVsToFreeHandles = False
 Failed to close VS:Microsoft.Test.Apex.Services.FactoryServiceException: 1 errors encountered while removing products from HostFactoryService. First error is stored in inner exception. ---> Microsoft.Test.Apex.Hosts.HostShutdownException: Host post stop action failed to execute, see inner exception for details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    at Microsoft.Test.Apex.VisualStudio.AppPropertyManager.SetUserProperty(String collectionPath, String propertyName, Object value)
    at Microsoft.Test.Apex.VisualStudio.Services.PropertyManagerWrapper.SetUserProperty(String path, String name, Object value)
    at Microsoft.Test.Apex.VisualStudio.Services.PropertyManagerWrapper.SetUserProperty[T](String path, String name, T value)
    at Microsoft.Test.Apex.VisualStudio.LifetimeActions.TestContractsLifetimeAction.OnPostHostStop()
    at Microsoft.Test.Apex.Hosts.Host.RaisePostHostStopActions()
    --- End of inner exception stack trace ---
   at Microsoft.Test.Apex.Hosts.Host.RaisePostHostStopActions()
    at Microsoft.Test.Apex.Hosts.Host.PostHostStopInternal()
    at Microsoft.Test.Apex.Hosts.Host.Stop()
    at Microsoft.Test.Apex.Services.HostFactoryService.OnRemoveTrackingProduct(HostConfiguration input, Host product)
    at Microsoft.Test.Apex.Services.TrackingFactoryService`2.RemoveAll()
    --- End of inner exception stack trace ---
   at Microsoft.Test.Apex.Services.TrackingFactoryService`2.RemoveAll()
    at Microsoft.Test.Apex.Operations.Shutdown()
    at Tao.VS.ObjectModel.VisualStudio.Close(TaoEngine engine)
    at Roslyn.VSHosting.Test.CloseTargetAction.Close(TaoEngine engine, VisualStudio vs, Boolean forceClose, IEnumerable`1 ignorableLines, Boolean deleteSolutionFolder)
 --------------------------------
 Microsoft.Test.Apex.Services.FactoryServiceException: 1 errors encountered while removing products from HostFactoryService. First error is stored in inner exception. ---> Microsoft.Test.Apex.Hosts.HostShutdownException: Host post stop action failed to execute, see inner exception for details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    at Microsoft.Test.Apex.VisualStudio.AppPropertyManager.SetUserProperty(String collectionPath, String propertyName, Object value)
    at Microsoft.Test.Apex.VisualStudio.Services.PropertyManagerWrapper.SetUserProperty(String path, String name, Object value)
    at Microsoft.Test.Apex.VisualStudio.Services.PropertyManagerWrapper.SetUserProperty[T](String path, String name, T value)
    at Microsoft.Test.Apex.VisualStudio.LifetimeActions.TestContractsLifetimeAction.OnPostHostStop()
    at Microsoft.Test.Apex.Hosts.Host.RaisePostHostStopActions()
    --- End of inner exception stack trace ---
   at Microsoft.Test.Apex.Hosts.Host.RaisePostHostStopActions()
    at Microsoft.Test.Apex.Hosts.Host.PostHostStopInternal()
    at Microsoft.Test.Apex.Hosts.Host.Stop()
    at Microsoft.Test.Apex.Services.HostFactoryService.OnRemoveTrackingProduct(HostConfiguration input, Host product)
    at Microsoft.Test.Apex.Services.TrackingFactoryService`2.RemoveAll()
    --- End of inner exception stack trace ---
   at Microsoft.Test.Apex.Services.TrackingFactoryService`2.RemoveAll()
    at Microsoft.Test.Apex.Operations.Shutdown()
    at Tao.VS.ObjectModel.VisualStudio.Close(TaoEngine engine)
    at Roslyn.VSHosting.Test.CloseTargetAction.Close(TaoEngine engine, VisualStudio vs, Boolean forceClose, IEnumerable`1 ignorableLines, Boolean deleteSolutionFolder)
    at Roslyn.VSHosting.Test.CloseTargetAction.Execute(TaoEngine engine)
    at Roslyn.VSHosting.Test.RoslynActions.CloseTargetAction.Execute(TaoEngine engine)
    at Tao.Engine.DebuggableActionExecutor.Execute()
    at Tao.Engine.DefaultActionExecutor.Execute()
 ================================

**Comment by mattscheffer** [comment]
This was fixed by @tannergooding. Verified with 25201.00 build. Closing
