### ISSUE TITLE
BasicWebApp fails in standalone as it attempts to create Default.aspx because it already exists

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8431]
Occurs in latest ML standalone build. Might just need to have its baseline updated.

Test: BasicWebApp started: 2/5/2016 1:44:34 PM
     Executing action [2/5/2016 1:44:34 PM] StartTarget
 Begin Waiting for Apex Communication
     Executing action [2/5/2016 1:44:34 PM] SetFeatureOption
     Executing action [2/5/2016 1:44:34 PM] AddProject
     Executing action [2/5/2016 1:44:50 PM] AddItem
 --------------------------------
 System.Runtime.InteropServices.COMException (0x80004005): A file with the name 'Default.aspx' already exists and is open in an editor. Please give a unique name to the item you are adding, or delete the existing item first.
    at EnvDTE.ProjectItems.AddFromTemplate(String FileName, String Name)
    at Microsoft.VisualStudio.TemplateWizard.Wizard.EnumContentsAddItem(ProjectItems projectItems, XmlNode contentNode, String projectName, String currentFolder, String currentTargetFolder, String rootName, String templateFolderPath, String destinationRootFolderPath, String userSpecifiedDestItemPath, String projectTypeString, List`1 wizardExtensions, String rootExtension)
    at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
    at EnvDTE.ProjectItems.AddFromTemplate(String FileName, String Name)
    at Roslyn.VSHosting.Test.AddItemAction.Execute(TaoEngine engine)
    at Tao.Engine.DebuggableActionExecutor.Execute()
    at Tao.Engine.DefaultActionExecutor.Execute()

View of solution explorer at time of crash:
![image](https://cloud.githubusercontent.com/assets/10537189/12862711/e5addce6-cc22-11e5-9b3c-cbdf6501e6ca.png)

**Comment by balajikris** [comment]
Even if it were to get past this, it would fail right after. That's because standalone runs are against update 1 whereas our apex libraries are still on RTM version (to be compatible with Jenkins queues boxes). So, we're blocked until we move our queues to Update 1.

**Comment by balajikris** [comment]
Same goes for internal bug 161421 and #7162 (for Razor tests).

**Comment by balajikris** [comment]
- [ ] To be unblocked by #7537

**Comment by balajikris** [comment]
It turns out that there are some template differences between Dev14 and Dev.vNext. In order for the test to be compatible on all versions of VS and to be robust against template changes (we're not testing templates with this test), lets just give the files we add a unique name that doesn't clash with the ones in the default template. 

@mattscheffer is working on a fix.

**Comment by balajikris** [comment]
@mattscheffer fixed this with [dotnet/roslyn-internal/577](https://github.com/dotnet/roslyn-internal/pull/577)
