### ISSUE TITLE
NotSupportedException from CommonObjectFormatter.FormatMethodSignature

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#8452]
MethodBase.GetGenericArguments() shouldn't be called on ConstructorInfo.

```C#
> class C { public C() { throw new Exception("error"); } }
> new C();
Unexpected error:
System.NotSupportedException: Derived classes must provide an implementation.
   at System.Reflection.MethodBase.GetGenericArguments()
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatUnhandledException(Exception e)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpObjectFormatter.FormatUnhandledException(Exception e)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<>c__DisplayClass42_0.<<ExecuteOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteOnUIThread>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Interactive.InteractiveHost.Service.<ExecuteAsync>d__30.MoveNext()
```

**Comment by amcasey** [comment]
I probably just forgot to call `IsGeneric` somewhere.

**Comment by amcasey** [comment]
@tmat Can you please verify that you haven't seen this recently?
