### ISSUE TITLE
InvalidOperationException in Roslyn.VisualStudio.Services.UnitTests.dll 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8576]
We encountered a System.InvalidOperationException in Roslyn.VisualStudio.Services.UnitTests.dll from an internal build, which looks like a race.

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.VisualStudio.Services.UnitTests
  Discovered:  Roslyn.VisualStudio.Services.UnitTests
  Starting:    Roslyn.VisualStudio.Services.UnitTests
    Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets.VisualBasicSnippetExpansionClientTests.TestAddImport_AddsOnlyNewAliasAndNamespacePairs [SKIP]
      Issue #321
      System.InvalidOperationException : Key already exists in table.
      Stack Trace:
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Def\Implementation\Interop\CleanableWeakComHandleTable.cs(179,0): at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeVariable.cs(23,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeVariable.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs(566,0): at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs(85,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.CreateInternalCodeMember(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs(431,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddVariable(SyntaxNode containerNode, String name, Object type, Object position, vsCMAccess access)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs(200,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.<>c__DisplayClass27_0.<AddVariable>b__0()
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs(309,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs(196,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.AddVariable(String name, Object type, Object position, vsCMAccess access, Object location)
           at EnvDTE80.CodeClass2.AddVariable(String Name, Object Type, Object Position, vsCMAccess Access, Object Location)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3848,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests._Closure$__._Lambda$__187-0(CodeModelTestState state, CodeClass2 codeClass)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\AbstractCodeElementTests`1.vb(39,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1.VB$StateMachine_5_TestElement.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3845,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests.VB$StateMachine_187_TestAddAndRemoveViaTextChangeManyTimes.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Roslyn.VisualStudio.Services.UnitTests
=== TEST EXECUTION SUMMARY ===
   Roslyn.VisualStudio.Services.UnitTests  Total: 3277, Errors: 0, Failed: 1, Skipped: 1, Time: 751.327s
```

FYI @dotnet/roslyn-infrastructure

**Comment by CyrusNajmabadi** [comment]
tagging @DustinCampbell 

Did you fix this recently?

**Comment by davkean** [comment]
The question is, is this blocking? Does it occur always?

**Comment by DustinCampbell** [comment]
Actually, I'm totally confused by the stack. The stack is in code model but the test says that it's about snippets. Do snippets call into code model somehow? @dpoeschl, do you know?

**Comment by CyrusNajmabadi** [comment]
DId we miss a WpfFact somewhere?  And we're somehow chaining async stuff improperly?

**Comment by dpoeschl** [comment]
@DustinCampbell The Snippets test is `[Skip]`'d and unrelated to the failure. The failure text begins at `System.InvalidOperationException : Key already exists in table.`.

**Comment by DustinCampbell** [comment]
I see now. thanks!

FWIW, I *didn't* fix this recently because the test that's running (`TestAddAndRemoveViaTextChangeManyTimes`) is the one I added when fixing #8423. Have we seen this fail consistently?

**Comment by seko111** [comment]
I've searched for this error message on Google, and ended up here.
I'm experiencing the same problem, and if you tell me how to get the stack trace out of VS I'm glad to post it here.
I'm pretty sure that in my case it happens because I've added a test project via VS automatically by clicking on the "Create Unit Tests" command when on a method in a class I wanted to test.
VS created the corresponding test project, but then I've deleted it.
I then tried creating it again (via "create unit tests"), and that's when I got the error.
Hope this helps.

**Comment by DustinCampbell** [comment]
Thanks @seko111! I think the fix to #8423 should address that but I'll verify. This particular issue is around some flakiness in the fix.

**Comment by davkean** [comment]
We got more logs:

``` C#
MESSAGE:
Failed to add variable in loop iteration 38!\r\n\r\nDocument text:\r\nClass C\r\nEnd Class\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeClassTests._Closure$__._Lambda$__169-0(CodeModelTestState state, CodeClass2 codeClass) in d:\j\workspace\roslyn_master_win_rel_unit32\src\VisualStudio\Core\Test\CodeModel\VisualBasic\CodeClassTests.vb:line 3156 at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1.VB$StateMachine_5_TestElement.MoveNext() in d:\j\workspace\roslyn_master_win_rel_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeElementTests`1.vb:line 39 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeClassTests.VB$StateMachine_169_TestAddAndRemoveViaTextChangeManyTimes.MoveNext() in d:\j\workspace\roslyn_master_win_rel_unit32\src\VisualStudio\Core\Test\CodeModel\VisualBasic\CodeClassTests.vb:line 3154 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Comment by genlu** [comment]
It looks like we hit this again, even with the fix from #8607.

Here's the stack trace:
```
Failed to add variable in loop iteration 10!
      
      Exception: Key already exists in table: {C.x, 1}.
      
      Document text:
      class C
      {
      }
      Expected: False
      Actual:   True
      Stack Trace:
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3854,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests._Closure$__._Lambda$__187-0(CodeModelTestState state, CodeClass2 codeClass)
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\AbstractCodeElementTests`1.vb(39,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1.VB$StateMachine_5_TestElement.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3845,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests.VB$StateMachine_187_TestAddAndRemoveViaTextChangeManyTimes.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Failed to add variable in loop iteration 23!
      
      Exception: Key already exists in table: {C.x, 1}.
      
      Document text:
      Class C
      End Class
      Expected: False
      Actual:   True
      Stack Trace:
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\VisualBasic\CodeClassTests.vb(3163,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeClassTests._Closure$__._Lambda$__169-0(CodeModelTestState state, CodeClass2 codeClass)
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\AbstractCodeElementTests`1.vb(39,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1.VB$StateMachine_5_TestElement.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5525\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\VisualBasic\CodeClassTests.vb(3154,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeClassTests.VB$StateMachine_169_TestAddAndRemoveViaTextChangeManyTimes.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davkean** [comment]
Did this build include his changes? He only merged in the change 3 hours ago.

**Comment by genlu** [comment]
Yes, it does.

**Comment by DustinCampbell** [comment]
Ugh.

**Comment by DustinCampbell** [comment]
Looking closer at Jenkins, it appears that this is only failing on Release which is probably why I'm not seeing it. I'll dig in and see if I can repro that locally.

**Comment by DustinCampbell** [comment]
OK. I can repro locally on Release bits. Investigating more thoroughly.

**Comment by genlu** [comment]
@DustinCampbell Thanks for investigating this!

**Comment by DustinCampbell** [comment]
It was my bad. Tests were passing for me locally and PR tests were passing as well. It only just occurred to me that all of that was on Debug bits.

**Comment by DustinCampbell** [comment]
ok, I think I've got the right fix this time. It turned out to be a subtle GC race.
