### ISSUE TITLE
[Add Using] CSharpAddImportCodeFixProvider crashes in ASP.NET Core 1.0 Project

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8577]
![image](https://cloud.githubusercontent.com/assets/9797472/12966129/7ba19d96-d010-11e5-9a93-9ffb08d67d7d.png)

1. Create `ConsoleApp1.xproj` and `ClassLibrary1.xproj`
2. Add xUnit as a nuget package to `ClassLibrary1.xproj`
3. In `ConsoleApp1.xproj` add `[Fact]` to the top of a method
4. Invoke Add Using

**Expected**: Xunit is added as an assembly reference

**Actual**: CSharpAddImportCodeFixProvider crashes

![image](https://cloud.githubusercontent.com/assets/9797472/12966182/dd4ff5c4-d010-11e5-85b5-0aa9128c03b1.png)

```
Unable to find a type of reference that is appropriate for this file: "C:\Users\jmarolf\.dnx\packages\xunit.extensibility.core\2.2.0-beta1-build3239\lib\dotnet\xunit.core.dll". 
at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.Add(String bstrPath) 
at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyMetadataReferenceAdded(ProjectId projectId, MetadataReference metadataReference) at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges) 
at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution) 
at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution) 
at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace, CancellationToken cancellationToken) 
at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, IEnumerable`1 operations, String title, CancellationToken cancellationToken) 
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument, CancellationToken cancellationToken) 
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass14_0.<InvokeCore>b__1(IWaitContext context)
at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Action`1 action) 
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass14_0.<InvokeCore>b__0() 
at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager, Object extension, Action action)
```

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by DustinCampbell** [comment]
Cy - could you touch base with Bill Hiebert over in ASP.NET land about how to fix this?
