### ISSUE TITLE
SplitFile is flaky

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#8747]
Flaky dotnet_roslyn_prtest_win_dbg_eta failure with 

**Individual TAO Test Failure**

Failing integration tests: SplitFile.xml 
Indication 1 

[PR3955](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3955/) and [PR3953](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3953/)

**Comment by Pilchie** [comment]
Can you take a look.  Seems like some other exception is being thrown and caught, but we'll need to dig it out of the dump.

**Comment by balajikris** [comment]
Tao printed that an assert failed to the log but doesn't say what was the assertion that failed or a stack. The jobs that basoundr linked don't have build artifacts (a bug which tannergooding fixed just last night.)

Incidentally, genlu linked another report of this which has artifacts. Looking now.

**Comment by balajikris** [comment]
There isn't enough information from the logs to act on this :( The stack doesn't have the inner exception and the screenshot doesn't show the output window.
~~~
Tao.Engine.Exceptions.DebugAssertException
Executing action [2/19/2016 3:50:23 PM] CloseTarget

System.AggregateException: Exceptions found in the exception log ---> System.Exception: ASSERT FAILED 
   --- End of inner exception stack trace ---
   at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16
   at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
   at Roslyn.Hosting.Test.EditorTestAppAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 147
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
---> (Inner Exception #0) System.Exception: ASSERT FAILED <---

~~~

**Comment by Pilchie** [comment]
Can you update the logging to make it more actionable next time?

**Comment by balajikris** [comment]
sure, is it still Urgency-Now ?

**Comment by Pilchie** [comment]
It is Urgency-Now to get the logging in place, then the bug can be closed until we get a repro with more data.

**Comment by davkean** [comment]
We hit this again, http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4643/consoleFull#-195473607061aefe2b-268e-4e71-8c03-11b4c0acbfbc.

@Pilchie This is marked Urgency-Now, which is supposed to mean Pri0 drop everything - but hasn't been updated in 11 days. Is the priority correct?

**Comment by balajikris** [comment]
sorry, looking at it. i sorta have a fix but working on make it nicer.

**Comment by balajikris** [comment]
I've added better logging to diagnose this issue. as such there is nothing more to do until it fails again, closing.
