### ISSUE TITLE
[project reference add using] Reference desktop class library from UWP project crashes codefix

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8771]
1. Create UWP app
2. Create Desktop class library `Class1`
3. Add code that will reference `var a = new Class1();`

![image](https://cloud.githubusercontent.com/assets/9797472/13094328/d1eac99a-d4be-11e5-8fda-208aa4123598.png)

**Expected**: Add Using is not offered because it is invalid to referece Desktop from UWP

**Actual**: Codefix crashes with following stack
```
User canceled out of save dialog (Exception from HRESULT: 0x8004000C (OLE_E_PROMPTSAVECANCELLED))
 at VSLangProj.References.AddProject(Project pProject)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyProjectReferenceAdded(ProjectId projectId, ProjectReference projectReference)
 at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
 at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution)
 at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, Document fromDocument, String title, Solution oldSolution, Solution updatedSolution, List`1 operationsList, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, IEnumerable`1 operations, String title, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<InvokeWorkerAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<<InvokeCoreAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by davkean** [comment]
This is due to the flavor rejecting the reference. 

There isn't an _easy way_ to figure out if a reference is going to succeed, but is a way, you basically want do the following:

1) If the _referencing/referenced_ hierarchies implement `IVsProjectFlavorReferences3` (C#/VB/CPS) then you want to call two methods (switching the referencing/referenced):

```C# 
IVsProjectFlavorReferences3.QueryAddProjectReferenceEx(referencedHierarchy, (int)__VSQUERYFLAVORREFERENCESCONTEXT.VSQUERYFLAVORREFERENCESCONTEXT_RefreshReference, out result, out reason)
```
``` C#
IVsProjectFlavorReferences3.QueryCanBeReferencedEx(referencingHierarchy, (int)__VSQUERYFLAVORREFERENCESCONTEXT.VSQUERYFLAVORREFERENCESCONTEXT_RefreshReference, out result, out reason)
```
Make sure you pass RefreshReference as the context to avoid displaying UI.

- If both set `result` to `__VSREFERENCEQUERYRESULT.REFERENCE_UNKNOWN`, __continue to 2)__
- Otherwise, If one or both set `result` to `__VSREFERENCEQUERYRESULT.REFERENCE_DENY`, the __reference is not allowed.__
- Otherwise, if one or both set `result` to `__VSREFERENCEQUERYRESULT.REFERENCE_ALLOW`, the __reference is allowed.__

You _do not_ want to call through IVsProjectFlavorReferences (v1) as implementers often prompted UI when the reference was rejected.

2) If the hierarchy doesn't implement `IVsProjectFlavorReferences3` (say C++), or both returned `REFERENCE_UNKNOWN` you want to fall back to the default project-to-project matrix in VS.

You can get access to it by looking up `SVsReferenceManager` to get a `IVsReferenceManager` instance, From here call `IVsReferenceManager.QueryCanReferenceProject` which also returns one of the  `__VSREFERENCEQUERYRESULT` values (_not a_ HRESULT).

If it returns `__VSREFERENCEQUERYRESULT.REFERENCE_UNKNOWN` or '__VSREFERENCEQUERYRESULT.REFERENCE_ALLOW', the reference is allowed.
Otherwise, if it returns  `__VSREFERENCEQUERYRESULT.REFERENCE_DENY`, the reference is not allowed.
Otherwise, if it returns  `__VSREFERENCEQUERYRESULT.REFERENCE_ALLOW`, the reference is allowed.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
