### ISSUE TITLE
[project reference add using] Reference desktop class library from Website project crashes codefix

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8777]
1. Create ASP.NET Empty Web Site
2. Add a new class in the App_Code folder
3. Create a Desktop class library `ClassLibrary1`
4. Add code that will reference `ClassLibrary1` `var a = new Class2();`

**Expected**: Add Usings is not offered because WebSite projects cannot reference other projects

**Actual**: Add Usings is offered and crashes due to COM exception

![image](https://cloud.githubusercontent.com/assets/9797472/13095225/1e8e30a6-d4c5-11e5-9156-e1de57acb521.png)

```
Unable to cast COM object of type 'System.__ComObject' to interface type 'VSLangProj.VSProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{2CFB826F-F6BF-480D-A546-95A0381CC411}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyProjectReferenceAdded(ProjectId projectId, ProjectReference projectReference)
 at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
 at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution)
 at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, Document fromDocument, String title, Solution oldSolution, Solution updatedSolution, List`1 operationsList, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, IEnumerable`1 operations, String title, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<InvokeWorkerAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<<InvokeCoreAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
