### ISSUE TITLE
[project reference add using] Referencing ASP.NET Core 1.0 from ASP.NET 4.6 WebForms project crashes codefix

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8779]
Create ASP.NET 4.6 WebForms project
Add a new ASP.NET Core 1.0 Class Library `ClassLibrary1 `
Add code that will reference ClassLibrary1 `var a = new Class1();`

**Expected**: Add Usings is not offered because ASP.NET Core 1.0projects cannot be referenced from ASP.NET 4.6 WebForms projects

**Actual**: Add Usings is offered and crashes due to Unspecified error

![image](https://cloud.githubusercontent.com/assets/9797472/13095402/56d14c04-d4c6-11e5-8748-bc7f10a6538a.png)

```
Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
 at VSLangProj.References.AddProject(Project pProject)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyProjectReferenceAdded(ProjectId projectId, ProjectReference projectReference)
 at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
 at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution)
 at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, Document fromDocument, String title, Solution oldSolution, Solution updatedSolution, List`1 operationsList, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, IEnumerable`1 operations, String title, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<InvokeWorkerAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<<InvokeCoreAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```

**Comment by jmarolf** [comment]
@CyrusNajmabadi
