### ISSUE TITLE
BasicWinForms is still flaky

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8971]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/158/consoleFull#42085259261aefe2b-268e-4e71-8c03-11b4c0acbfbc

```
11:16:45 System.Exception: Actual and expected items don't match:
11:16:45 Expected: this.SomeButton.Text = "ButtonTextGoesHere";
11:16:45 Actual: namespace TestProj
11:16:45 {
11:16:45     partial class Form1
11:16:45     {
11:16:45         /// <summary>
11:16:45         /// Required designer variable.
11:16:45         /// </summary>
11:16:45         private System.ComponentModel.IContainer components = null;
11:16:45 
11:16:45         /// <summary>
11:16:45         /// Clean up any resources being used.
11:16:45         /// </summary>
11:16:45         /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
11:16:45         protected override void Dispose(bool disposing)
11:16:45         {
11:16:45             if (disposing && (components != null))
11:16:45             {
11:16:45                 components.Dispose();
11:16:45             }
11:16:45             base.Dispose(disposing);
11:16:45         }
11:16:45 
11:16:45         #region Windows Form Designer generated code
11:16:45 
11:16:45         /// <summary>
11:16:45         /// Required method for Designer support - do not modify
11:16:45         /// the contents of this method with the code editor.
11:16:45         /// </summary>
11:16:45         private void InitializeComponent()
11:16:45         {
11:16:45             this.components = new System.ComponentModel.Container();
11:16:45             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
11:16:45             this.Text = "Form1";
11:16:45         }
11:16:45 
11:16:45         #endregion
11:16:45     }
11:16:45 }
11:16:45 
11:16:45 
11:16:45 
11:16:45    at Roslyn.VSHosting.Test.Utilities.CompareAndThrowIfNotEqual[TItem](TItem expected, TItem actual) in d:\j\workspace\roslyn-intern---3b4b7ba3\Closed\Hosting\Test\Actions\VisualStudio\Utilities\Utilities.cs:line 15
11:16:45    at Roslyn.VSHosting.Test.VerifyEditorContainsTextAction.<>c.<Execute>b__4_0(Object[] args) in d:\j\workspace\roslyn-intern---3b4b7ba3\Closed\Hosting\Test\Actions\VisualStudio\VerifyEditorContainsTextAction.cs:line 23
11:16:45    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
11:16:45 ================================
```

**Comment by davkean** [comment]
Dupe https://github.com/dotnet/roslyn/issues/7643
