### ISSUE TITLE
Crash in `Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IsStandaloneStatement(StatementSyntax node)`

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9015]
Can be repro'd in following tests with OperationWAlker hooked up:
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_5
```
Stack trace:
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1' failed: Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : Unexpected value 'ResumeStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'

	ThrowingTraceListener.cs(25,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition, String message)
	InternalUtilities\ExceptionUtilities.cs(13,0): at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)
	Binding\MemberSemanticModel.vb(381,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IsStandaloneStatement(StatementSyntax node)
	Binding\MemberSemanticModel.vb(1905,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBindingRoot(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(1780,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(142,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(200,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodeSummary(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(789,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SyntaxTreeSemanticModel.vb(357,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SemanticModel.vb(143,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\SemanticModel.cs(74,0): at Microsoft.CodeAnalysis.SemanticModel.GetOperation(SyntaxNode node, CancellationToken cancellationToken)
	CompilationTestUtils.vb(246,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(120,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, MetadataReference[] additionalRefs, VisualBasicCompilationOptions options, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(125,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, VisualBasicCompilationOptions options)
	Semantics\UnstructuredExceptionHandling.vb(13907,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1()Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1' failed: Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : Unexpected value 'ResumeStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'

	ThrowingTraceListener.cs(25,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition, String message)
	InternalUtilities\ExceptionUtilities.cs(13,0): at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)
	Binding\MemberSemanticModel.vb(381,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IsStandaloneStatement(StatementSyntax node)
	Binding\MemberSemanticModel.vb(1905,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBindingRoot(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(1780,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(142,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(200,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodeSummary(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(789,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SyntaxTreeSemanticModel.vb(357,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SemanticModel.vb(143,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\SemanticModel.cs(74,0): at Microsoft.CodeAnalysis.SemanticModel.GetOperation(SyntaxNode node, CancellationToken cancellationToken)
	CompilationTestUtils.vb(246,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(120,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, MetadataReference[] additionalRefs, VisualBasicCompilationOptions options, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(125,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, VisualBasicCompilationOptions options)
	Semantics\UnstructuredExceptionHandling.vb(13907,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1()Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1' failed: Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : Unexpected value 'ResumeStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'

	ThrowingTraceListener.cs(25,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition, String message)
	InternalUtilities\ExceptionUtilities.cs(13,0): at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)
	Binding\MemberSemanticModel.vb(381,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IsStandaloneStatement(StatementSyntax node)
	Binding\MemberSemanticModel.vb(1905,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBindingRoot(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(1780,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(142,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(200,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodeSummary(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(789,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SyntaxTreeSemanticModel.vb(357,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SemanticModel.vb(143,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\SemanticModel.cs(74,0): at Microsoft.CodeAnalysis.SemanticModel.GetOperation(SyntaxNode node, CancellationToken cancellationToken)
	CompilationTestUtils.vb(246,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(120,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, MetadataReference[] additionalRefs, VisualBasicCompilationOptions options, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(125,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, VisualBasicCompilationOptions options)
	Semantics\UnstructuredExceptionHandling.vb(13907,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.UnstructuredExceptionHandling.Resume_in_Lambda_1()
```

**Comment by JohnHamby** [comment]
What's the syntax kind causing the crash? (Knowing this makes it trivial to construct a small repro, and in fact gives the information needed to fix the problem.)

**Comment by genlu** [comment]
The syntax kind is `ResumeStatement`.

**Comment by JohnHamby** [comment]
I'm already adding some entries for other statements, so I can take this one.
