### ISSUE TITLE
InvalidCastException in BoundUserDefinedBinaryOperator.Left

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9018]
Crash with InvalidCastException in `BoundUserDefinedBinaryOperator.Left` when hooked up with OperationWalker with test
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.IntrinsicSymbols
```

Here's the stack trace:
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.IntrinsicSymbols' failed: System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.BoundBadExpression' to type 'Microsoft.CodeAnalysis.VisualBasic.BoundCall'.
	BoundTree\BoundUserDefinedBinaryOperator.vb(25,0): at Microsoft.CodeAnalysis.VisualBasic.BoundUserDefinedBinaryOperator.get_Call()
	BoundTree\BoundUserDefinedBinaryOperator.vb(13,0): at Microsoft.CodeAnalysis.VisualBasic.BoundUserDefinedBinaryOperator.get_Left()
	BoundTree\Expression.vb(727,0): at Microsoft.CodeAnalysis.VisualBasic.BoundUserDefinedBinaryOperator.get_IBinaryOperatorExpression_LeftOperand()
	Compilation\OperationWalker.cs(285,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBinaryOperatorExpression(IBinaryOperatorExpression operation)
	BoundTree\Expression.vb(809,0): at Microsoft.CodeAnalysis.VisualBasic.BoundUserDefinedBinaryOperator.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(55,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclaration(IVariableDeclaration operation)
	Compilation\Statement.cs(35,0): at Microsoft.CodeAnalysis.Semantics.VariableDeclaration.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(50,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclarationStatement(IVariableDeclarationStatement operation)
	BoundTree\Statement.vb(1081,0): at Microsoft.CodeAnalysis.VisualBasic.BoundDimStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	CompilationTestUtils.vb(247,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(74,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlib(XElement sources, VisualBasicCompilationOptions options, IEnumerable`1 references, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	Semantics\BinaryOperators.vb(932,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.BinaryOperators.IntrinsicSymbols()
```

Even though I found this crash through IOperation interface, it doesn't seems to be a bug at this layer.

**Comment by genlu** [comment]
@AlekseyTs Could you take a look at this please?

**Comment by AlekseyTs** [comment]
It is a bug in the IOperation implementation, the APIs it is using are non meant to be used for erroneous bound trees, see #8849

**Comment by genlu** [comment]
Reassigned to @JohnHamby since this is basically a subset of #8849.
