### ISSUE TITLE
CSharpReplIntellisense randomly failed due to IOException

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#9064]
From a test run on Jenkins:

```
14:56:33  Dumping log file d:\j\workspace\dotnet_roslyn---bd6e1dbd\Open\Binaries\Debug\ETAIntegrationTestLogs\CSharpReplIntellisense.txt
14:56:33 Test: CSharpReplIntellisense started: 2/22/2016 10:41:11 PM
14:56:33 	Executing action [2/22/2016 10:41:11 PM] StartTarget
14:56:33 	Executing action [2/22/2016 10:41:11 PM] InteractiveWindow
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SetSuggestionMode
14:56:33  Scenario: 1) Verify completion list on empty text at top-level
14:56:33 	Executing action [2/22/2016 10:41:13 PM] ClearReplText
14:56:33 Note: ActiveTextView has lost Keyboard focus.
14:56:33 	Executing action [2/22/2016 10:41:13 PM] InvokeCompletionList
14:56:33 	Executing action [2/22/2016 10:41:13 PM] VerifyCompletionList
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SendKeys
14:56:33  Scenario: 3) Verify #r completion list
14:56:33 	Executing action [2/22/2016 10:41:13 PM] ClearReplText
14:56:33 	Executing action [2/22/2016 10:41:13 PM] SetReplText
14:56:33 	Executing action [2/22/2016 10:41:13 PM] InvokeCompletionList
14:56:33 	Executing action [2/22/2016 10:41:13 PM] VerifyCompletionList
14:56:33 	Executing action [2/22/2016 10:41:14 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:14 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:14 PM] SendKeys
14:56:33 	Executing action [2/22/2016 10:41:14 PM] SendKeys
14:56:33  Scenario: 4) Verify completion list for #load members
14:56:33 	Executing action [2/22/2016 10:41:14 PM] ClearReplText
14:56:33 	Executing action [2/22/2016 10:41:14 PM] CreateUserFile
14:56:33 	Executing action [2/22/2016 10:41:14 PM] SubmitReplText
14:56:33 given range is not current
14:56:33 given range is not current
14:56:33 	Executing action [2/22/2016 10:41:16 PM] DeleteUserFile
14:56:33 --------------------------------
14:56:33 System.IO.IOException: The process cannot access the file 'C:\Users\dotnet-bot\c.csx' because it is being used by another process.
14:56:33    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
14:56:33    at System.IO.File.InternalDelete(String path, Boolean checkHost)
14:56:33    at System.IO.File.Delete(String path)
14:56:33    at Roslyn.CommonToBothHosts.Test.DeleteUserFileAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\Common\DeleteUserFileAction.cs:line 22
14:56:33    at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
14:56:33    at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
14:56:33 ================================
```

@dotnet/roslyn-infrastructure: just to check, I assume we're not running parallel jobs on the machines?
@dotnet/roslyn-interactive: what does "given range not current" mean?

**Comment by davkean** [comment]
We're not running concurrent jobs.

**Comment by ManishJayaswal** [comment]
@tannergooding Can you take a look why this is flaky?

**Comment by tannergooding** [comment]
There appear to be three issues here:
1. The CreateUserFile action uses the user profile directory rather than the temp folder
2. We reuse the same file name (c.csx and temp.csx) in multiple locations rather than generating a unique filename.
3. It appears that CreateUserFile is sometimes maintaining a handle (although I am not sure how, since it is just using `File.WriteAllText`) to the generated file, which causes the InteractiveHost process to fail when it tries to load it.

**Comment by tannergooding** [comment]
Submitted a PR containing a fix which ensures that the `CreateUserFileAction` creates the file in a new random Temp directory, rather than creating it in the User directory.

**Comment by davkean** [comment]
Let's mark it as Blocked.

**Comment by ManishJayaswal** [comment]
@drognanar as he was also working on something similar.

**Comment by drognanar** [comment]
I was working on issue #9714 which does look similar. Changes I made:
1. I added a separate action that makes use of the `CreateTemporaryFileAction` instead.
2. I have renamed the `#load` csx paths.
3. In cleanup I first call `ResetAndWaitForInputPrompt` and then `CleanupTemporaryFiles`.

**Comment by tannergooding** [comment]
Assigning back to @jasonmalinowski for verification.
