### ISSUE TITLE
NRE in `Microsoft.CodeAnalysis.Semantics.Expression.Literal.Text`

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9116]
For the following code, parameter default value of `o` is `null`, which results the value of `_value.Value` to be `null`.
```cs
struct S
{
    void M(
        int i = 1,
        string str = ""hello"",
        object o = null,
        S s = default(S))
    {
        M();
    }
}
```
Call stack:
```
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.GetSemanticInfoTests.ParameterDefaultValues' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	Compilation\Expression.cs(311,0): at Microsoft.CodeAnalysis.Semantics.Literal.get_Text()
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(415,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitLiteralExpression(ILiteralExpression operation)
	Compilation\Expression.cs(325,0): at Microsoft.CodeAnalysis.Semantics.Literal.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(204,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArgument(IArgument operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(229,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitArgument(IArgument operation)
	BoundTree\Expression.cs(261,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.ArgumentBase.Microsoft.CodeAnalysis.IOperation.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(210,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitInvocationExpression(IInvocationExpression operation)
	BoundTree\Expression.cs(77,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(181,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(185,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	BoundTree\Statement.cs(699,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(45,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(IBlockStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(51,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitBlockStatement(IBlockStatement operation)
	BoundTree\Statement.cs(52,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	CSharpTestBase.cs(582,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.WalkOperationTree(CSharpCompilation compilation)
	CSharpTestBase.cs(529,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilation(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(443,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(434,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(SyntaxTree syntaxTree, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	Compilation\GetSemanticInfoTests.cs(1819,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.GetSemanticInfoTests.ParameterDefaultValues()
```

**Comment by JohnHamby** [comment]
The Text property of ILiteralExpression should probably be removed. It's problematic and not very useful in its current form.

**Comment by genlu** [comment]
@JohnHamby Sorry I was out of internet for most of the day so didn't know you took this... If you decided to remove `Text` property, then yo ucan just ignore my PR.

**Comment by genlu** [comment]
Stealing this since I have a fix already.
