### ISSUE TITLE
Visual Studio crashes when using Rename

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9117]
**Version Used**: Visual Studio 2015 Update 1

**Description**: Visual Studio crashes when using the Rename function trying to rename the property name that is used with combination of Group By clause and ToDictionary extension method of LINQ.

**Steps to Reproduce**:

 1.Create a VB class library
 2.Enter the following code

```VB
Public Class Class1 
  Public Property Field1 As Integer ' conducting Rename to this property crashes the system 
End Class 

Public Class Class2 
  Public Shared Property DataSource As IEnumerable(Of Class1) 
  Public ReadOnly Property Dict As IReadOnlyDictionary(Of Integer, IEnumerable(Of Class1)) = 
  ( 
    From data 
    In DataSource 
    Group By 
    data.Field1 ' used here 
    Into Group1 = Group 
  ).ToDictionary( 
    Function(group) group.Field1, ' used here 
    Function(group) group.Group1) 
End Class 
```
 3.Rename `Field1` at the first position

**Expected Behavior**:  `Field1` is renamed

**Actual Behavior**:

Visual Studio Crashes

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 189
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 138
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 3838
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26304
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 3872
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 475
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26623
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitEqualsValue(EqualsValueSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2546
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.EqualsValueSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16004
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitPropertyStatement(PropertyStatementSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2267
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 13633
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1499
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6104
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.AnnotateAndRename(RenameRewriterParameters parameters) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 32
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__27.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 772
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__18.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.<GetReplacementsAsync>d__7.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\AbstractEditorInlineRenameService.InlineRenameLocationSet.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass63_0.<<UpdateConflictResolutionTask>b__0>d.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 446
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IWaitContext waitContext, Boolean previewChanges) in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 579
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass69_0.<Commit>b__0(IWaitContext waitContext) in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 551
   at Roslyn.Editor.TestApp.UI.Dialogs.WaitIndicator.Wait(String title, String message, Boolean allowCancel, Action`1 action) in C:\src\roslyn-internal\Closed\Hosting\RoslynETAHost\UI\Dialogs\WaitIndicator.cs:line 30
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.Commit(Boolean previewChanges) in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 547
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Commit() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\Dashboard\Dashboard.xaml.cs:line 264
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Apply_Click(Object sender, RoutedEventArgs e) in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\Dashboard\Dashboard.xaml.cs:line 259
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnAccessKey(AccessKeyEventArgs e)
   at System.Windows.Input.AccessKeyManager.ProcessKey(List`1 targets, String key, Boolean existsElsewhere, Boolean userInitiated)
   at System.Windows.Input.AccessKeyManager.ProcessKeyForSender(Object sender, String key, Boolean existsElsewhere, Boolean userInitiated)
   at System.Windows.Input.AccessKeyManager.OnText(TextCompositionEventArgs e)
   at System.Windows.Input.AccessKeyManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.TextCompositionManager.UnsafeCompleteComposition(TextComposition composition)
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.TextCompositionManager.UnsafeStartComposition(TextComposition composition)
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Roslyn.Editor.TestApp.EditorTestApp.Run(Application app) in C:\src\roslyn-internal\Closed\Hosting\EditorTestApp\EditorTestApp.cs:line 224
   at Roslyn.Editor.TestApp.EditorTestApp.RunEditorTestApp() in C:\src\roslyn-internal\Closed\Hosting\EditorTestApp\EditorTestApp.cs:line 216
   at Roslyn.Editor.TestApp.EditorTestApp.Main() in C:\src\roslyn-internal\Closed\Hosting\EditorTestApp\EditorTestApp.cs:line 166
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 189
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 138
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 3838
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26304
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 3872
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 475
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26623
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitEqualsValue(EqualsValueSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2546
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.EqualsValueSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16004
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitPropertyStatement(PropertyStatementSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2267
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 13633
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1499
   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in C:\src\roslyn-internal\Open\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6104
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.RenameRewriter.Visit(SyntaxNode node) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 140
   at Microsoft.CodeAnalysis.VisualBasic.Rename.VisualBasicRenameRewriterLanguageService.AnnotateAndRename(RenameRewriterParameters parameters) in C:\src\roslyn-internal\Open\src\Workspaces\VisualBasic\Portable\Rename\VisualBasicRenameRewriterLanguageService.vb:line 32
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__27.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 772
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<ResolveConflictsAsync>d__18.MoveNext() in C:\src\roslyn-internal\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.InlineRenameLocationSet.<GetReplacementsAsync>d__7.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\AbstractEditorInlineRenameService.InlineRenameLocationSet.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass63_0.<<UpdateConflictResolutionTask>b__0>d.MoveNext() in C:\src\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\InlineRename\InlineRenameSession.cs:line 446<---
```

**Comment by jmarolf** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/9118
