### ISSUE TITLE
Cycle in operation tree causes stack exception

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9128]
A cycle in the operation tree causes stack exception. Here's a test to repro this (with OperationWalker hooked up):
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.SemanticModelTests.ForAndForEachGetDeclaredSymbolWithImplicitlyDeclaredVariable
```

Here's the bottom of the stack trace:
```
......
	Compilation\Expression.cs(180,0): at Microsoft.CodeAnalysis.Semantics.Assignment.AssignmentExpression.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(181,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(185,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	Compilation\Expression.cs(147,0): at Microsoft.CodeAnalysis.Semantics.Assignment.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(109,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitForLoopStatement(IForLoopStatement operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitForLoopStatement(IForLoopStatement operation)
	BoundTree\Statement.vb(685,0): at Microsoft.CodeAnalysis.VisualBasic.BoundForToStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(264,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitSyntheticLocalReferenceExpression(ISyntheticLocalReferenceExpression operation)
	BoundTree\Statement.vb(706,0): at Microsoft.CodeAnalysis.VisualBasic.BoundForToStatement.Temporary.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(373,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitAssignmentExpression(IAssignmentExpression operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(482,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitAssignmentExpression(IAssignmentExpression operation)
	Compilation\Expression.cs(180,0): at Microsoft.CodeAnalysis.Semantics.Assignment.AssignmentExpression.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(181,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(185,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	Compilation\Expression.cs(147,0): at Microsoft.CodeAnalysis.Semantics.Assignment.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(109,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitForLoopStatement(IForLoopStatement operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitForLoopStatement(IForLoopStatement operation)
	BoundTree\Statement.vb(685,0): at Microsoft.CodeAnalysis.VisualBasic.BoundForToStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	c:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	CompilationTestUtils.vb(279,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(230,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(200,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(75,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlib(XElement sources, VisualBasicCompilationOptions options, IEnumerable`1 references, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	Semantics\GetSemanticInfoTests.vb(658,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Semantics.SemanticModelTests.ForAndForEachGetDeclaredSymbolWithImplicitlyDeclaredVariable()
```

**Comment by genlu** [comment]
Turns out the cycle was introduced in OperationWalker for test, not in operation tree. Not a bug, closed.
