### ISSUE TITLE
Absent property on dynamic object crashes csi.exe with NullReferenceException in ObjectFormatter.FormatMethodSignature

### ISSUE THREAD

**Issue by atifaziz** [dotnet/roslyn#9176]
If a non-existent property is accessed on a dynamic object then `csi.exe` crashes due to a `NullReferenceException` in `ObjectFormatter.FormatMethodSignature`.

Simplest steps to reproduce the problem:

```
Microsoft (R) Visual C# Interactive Compiler version 1.1.0.51109
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> var today = DateTime.Today;
> dynamic d = today;
> Console.WriteLine(d.Year);
2016
> Console.WriteLine(d.x);
'System.DateTime' does not contain a definition for 'x'
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Scripting.Hosting.ObjectFormatter.FormatMethodSignature(MethodBase method)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.DisplayException(Exception e)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.TryBuildAndRun(Script`1 newScript, InteractiveScriptGlobals globals, ScriptState`1& state, ScriptOptions& options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveLoop(ScriptOptions options, String initialScriptCodeOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractiveCore(ErrorLogger errorLogger)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommandLineRunner.RunInteractive()
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.Csi.Main(String[] args)
```

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/31b600d92b17a47750bd42ff7062bd95d16ef0ae

**Comment by atifaziz** [comment]
@tmat Thank you for fixing this so promptly. :+1:
