### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Simple_Threadsafety failure on Linux

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9223]
PR: [#files](https://github.com/dotnet/roslyn/pull/9200/files) *Use var codestyle updates* by @balajikris
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4363/

**1 Test Failures:**
Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.AnonymousTypesSymbolTests.AnonymousTypeSymbol_Simple_Threadsafety

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by jaredpar** [comment]
Closing for now.  Hard to tell if this is a Mono issue or a real compiler bug.  Given it only repros on Linux and we aren't running this test anymore (hasn't been ported to CoreCLR) there isn't much action to take. 

This should start running again in a few weeks when we finish porting to CoreCLR.  If it shows up again there we'll dive into this and see what's going on.

**Comment by JoeRobich** [comment]
Hit this on Linux_Test coreclr - [Logs](https://dnceng.visualstudio.com/public/_build/results?buildId=69554) Attempt 1

```
Assertion Failed

   at Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder.Translate(TypeSymbol typeSymbol, SyntaxNode syntaxNodeOpt, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:line 1019
   at Microsoft.CodeAnalysis.Emit.PEModuleBuilder`9.CreateConstant(TTypeSymbol type, Object value, TSyntaxNode syntaxNodeOpt, DiagnosticBag diagnostics) in /_/src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs:line 582
   at Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData.CreateMetadataConstant(ITypeSymbol type, Object value, EmitContext context) in /_/src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs:line 151
   at Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData.CreateMetadataExpression(TypedConstant argument, EmitContext context) in /_/src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs:line 110
   at Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData.Microsoft.Cci.ICustomAttribute.GetArguments(EmitContext context) in /_/src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs:line 26
   at Microsoft.Cci.MetadataVisitor.Visit(ICustomAttribute customAttribute) in /_/src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs:line 57
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 customAttributes) in /_/src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs:line 45
   at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module) in /_/src/Compilers/Core/Portable/PEWriter/ReferenceIndexer.cs:line 26
   at Microsoft.Cci.MetadataWriter.CreateIndices() in /_/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs:line 493
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup) in /_/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs:line 1802
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/PEWriter/PeWriter.cs:line 66
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2781
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2680
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2446
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2349
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.AnonymousTypesSymbolTests.<>c__DisplayClass10_1.<AnonymousTypeSymbol_Simple_Threadsafety>b__0() in /_/src/Compilers/CSharp/Test/WinRT/AnonymousTypesSymbolTests.cs:line 607
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

https://github.com/dotnet/roslyn/blob/4ca8c4626bb5e3eb6126d0c05de71c67eeb4cbbf/src/Compilers/CSharp/Test/WinRT/AnonymousTypesSymbolTests.cs#L607

**Comment by jaredpar** [comment]
Hmm this doesn't make a lot of sense. The assert that is firing is the following:

``` csharp
Debug.Assert(diagnostics != null);
```

That value comes from `EmitContext.Diagnostics` on this line:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs#L151

If `EmitContext.Diagnsotics` was `null` though then the assert in the ctor should have fired before this one. 

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Emit/Context.cs#L22

Only possibility that comes to mind here is that the value on the heap is being subject to a tearing write with `default(EmitContext)`. Looking to see if that's somehow possible here.
