### ISSUE TITLE
Unexpected value 'ExitPropertyStatement' in `VisualBasic.MemberSemanticModel`

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9254]
Can be repro'd in 
```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.ExitPropertyGetterSetReturnValue
Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.ExitPropertyDefaultReturnValue
Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.ExitPropertySetterSetReturnValue
```

Here's call stack:
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.ExitPropertyGetterSetReturnValue' failed: Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : Unexpected value 'ExitPropertyStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'

	ThrowingTraceListener.cs(25,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition, String message)
	InternalUtilities\ExceptionUtilities.cs(13,0): at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)
	Binding\MemberSemanticModel.vb(381,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.IsStandaloneStatement(StatementSyntax node)
	Binding\MemberSemanticModel.vb(1905,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBindingRoot(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(1780,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodes(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(142,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetUpperBoundNode(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(200,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetBoundNodeSummary(VisualBasicSyntaxNode node)
	Binding\MemberSemanticModel.vb(789,0): at Microsoft.CodeAnalysis.VisualBasic.MemberSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SyntaxTreeSemanticModel.vb(357,0): at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetOperationWorker(VisualBasicSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken)
	Compilation\SemanticModel.vb(143,0): at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\SemanticModel.cs(74,0): at Microsoft.CodeAnalysis.SemanticModel.GetOperation(SyntaxNode node, CancellationToken cancellationToken)
	CompilationTestUtils.vb(290,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(243,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(213,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(88,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlib(XElement sources, VisualBasicCompilationOptions options, IEnumerable`1 references, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CodeGen\CodeGenTests.vb(11402,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.ExitPropertyGetterSetReturnValue()
```

**Comment by JohnHamby** [comment]
MemberSemanticModel.IsStandaloneStatement was missing entries for ExitPropertyStatement and ExitOperationStatement.
