### ISSUE TITLE
Test `CSharpIntellisense.Dismiss on Select All` is flaky

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9366]
Here's an instance of the failure
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4637/

```
Stacktrace

MESSAGE:
Completion list was not showing and it was expected to be showing
+++++++++++++++++++
STACK TRACE:
at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message) in f:\dd\src\Omni\Tao\Tao.Utilities\Extensions.cs:line 457 
at Roslyn.Hosting.Test.VerifyCompletionListAction.ExecuteOnUIThread() in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\RoslynTaoActions\Actions\EditorTestApp\VerifyCompletionListAction.cs:line 41 
at Roslyn.Hosting.Test.EditorAction.<Execute>b__0_0() in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 21 
at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178 
at Roslyn.Hosting.Test.EditorAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 13 
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139 
at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

@dotnet/roslyn-infrastructure 

Bounty

**Comment by balajikris** [comment]
hindered by #9415.

**Comment by balajikris** [comment]
Note that this is a focus sensitive scenario, without screenshots there isn't much to tell.

**Comment by Pilchie** [comment]
We appear to have hit this again on the internal signed build for `stabilization` 1.2.20160309.4.

**Comment by davkean** [comment]
Hit this twice more: 
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_rel_eta/171/testReport/(root)/CSharpIntellisense/Dismiss_on_Select_All/
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_dbg_eta/lastCompletedBuild/testReport/(root)/CSharpIntellisense/Dismiss_on_Select_All/

**Comment by balajikris** [comment]
scenario is hitting Ctrl + Space in line 0, col 0 of an empty file and verifying that brings up completion list. From screenshot, completion didn't show up :(

![image](https://cloud.githubusercontent.com/assets/4213867/13861906/204b8e44-ec4d-11e5-8c04-2a0f73847877.png)

**Comment by balajikris** [comment]
This may or may not be the same issue as we're seeing with the CreateWebProject DDRITs, where completion doesn't show up after `@`. That however, I don't think is the empty file case, but the logging I've added for that should help here too?

**Comment by davkean** [comment]
Bounty

**Comment by balajikris** [comment]
I'm seeing the Trace messages I added above via 9898, but they might not be sufficient for this scenario - its bringing up completion via Ctrl + Space, whereas I instrumented mainly typechar cases and some other general places where we fail.

**Comment by balajikris** [comment]
This is affecting a lot of signed builds recently. Please look again.

**Comment by jaredpar** [comment]
This is an urgency now bug that hasn't been updated in a month now.  What is the status?

**Comment by rchande** [comment]
No recent reports, closing.
