### ISSUE TITLE
ETA test SplitFile is flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9454]
Failures: 

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4748/

**Comment by Pilchie** [comment]
Can you take a look?

**Comment by balajikris** [comment]
I made us capture dumps for this but can't find dumps in build artifacts. :disappointed:  Will dive in.

**Comment by balajikris** [comment]
ha. turns out my diagnostics is in master and this failure is in future. codeflows were frozen and my change isn't in master yet. With things as they are currently, I have nothing left to wait until another instance of this occurs in master..

**Comment by TyOverby** [comment]
can you give me the hash for your diagnostics commit?

**Comment by balajikris** [comment]
I'm going to try it locally and see if I can work out some magic.

**Comment by balajikris** [comment]
final update for now: didn't have luck running the test several times in a loop on my local box. It always passes.

**Comment by balajikris** [comment]
For the record, couldn't do anything about the above failure (in mavasani's PR) as well, as it occurred in stabilization and my diagnostics are not in stabilization. waiting for something to happen in master and future.

**Comment by TyOverby** [comment]
This is occurring in at least `future`

**Comment by balajikris** [comment]
@TyOverby could you please link me to the failure, i dont see any here: https://github.com/dotnet/roslyn/pulls

**Comment by davkean** [comment]
Another hit count: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4891/

**Comment by davkean** [comment]
And another: https://github.com/dotnet/roslyn/issues/9454

**Comment by balajikris** [comment]
wonderful, let there be dumps!

**Comment by balajikris** [comment]
Nailed one.. Don't have a very pretty dump because i don't throw an exception per se, but yet have enough info i hope..

this is why split file is failing:
~~~
String:         at Roslyn.Editor.TestApp.OutputWindowTraceListener.Fail(String message, String detailMessage) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\EditorTestApp\UI\ToolWindows\Output\OutputWindowTraceListener.cs:line 50
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Roslyn.Utilities.Contract.Assert(Boolean condition, String message) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Workspaces\Core\Portable\Utilities\Contract.cs:line 38
   at Roslyn.Utilities.Contract.Requires(Boolean condition, String message) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Workspaces\Core\Portable\Utilities\Contract.cs:line 19
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.RaiseProjectAnalyzerReferenceChangedIfNeeded(Project project, ImmutableDictionary`2 newMapPerReference, ImmutableDictionary`2 newMap) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs:line 167
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.GetOrUpdateAnalyzerMap(Project project) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs:line 89
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.GetAnalyzers(Project project) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs:line 38
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateManager.GetAnalyzers(Project project) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.StateManager.cs:line 49
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.GetCompilationWithAnalyzers(Project project, Compilation compilation, Boolean concurrentAnalysis, Boolean reportSuppressedDiagnostics) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 145
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.GetCompilationWithAnalyzers(Compilation compilation) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticAnalyzerDriver.cs:line 129
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.<GetSemanticDiagnosticsAsync>d__26.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticAnalyzerDriver.cs:line 253
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.GetSemanticDiagnosticsAsync(DiagnosticAnalyzer analyzer)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<GetSemanticDiagnosticsAsync>d__91.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 959
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.GetSemanticDiagnosticsAsync(DiagnosticAnalyzerDriver userDiagnosticDriver, DiagnosticAnalyzer analyzer)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__22.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer_GetLatestDiagnosticsForSpan.cs:line 292
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(StateSet stateSet, StateType stateType, Boolean supportsSemanticInSpan, Func`3 versionCheck, Func`3 getDiagnostics, DiagnosticAnalyzerDriver analyzerDriverOpt)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__21.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer_GetLatestDiagnosticsForSpan.cs:line 255
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(StateSet stateSet, StateType stateType, Func`3 versionCheck, Func`3 getDiagnostics)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticDiagnosticsAsync>d__16.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer_GetLatestDiagnosticsForSpan.cs:line 130
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticDiagnosticsAsync(StateSet stateSet, VersionStamp textVersion, VersionStamp syntaxVersion, VersionStamp semanticVersion)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetAsync>d__15.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer_GetLatestDiagnosticsForSpan.cs:line 82
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<TryAppendDiagnosticsForSpanAsync>d__64.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 499
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken) in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\DiagnosticAnalyzerService_IncrementalAnalyzer.cs:line 168
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass18_0.<<TryAppendDiagnosticsForSpanAsync>b__0>d.MoveNext() in d:\j\workspace\roslyn-intern---cd4c5d61\Open\src\Features\Core\Portable\Diagnostics\DiagnosticAnalyzerService.cs:line 139
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass18_0.<TryAppendDiagnosticsForSpanAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

~~~

**Comment by balajikris** [comment]
At this point, whoever owns DiagnosticIncrementalAnalyzer should take over this. 

/ cc: @davkean

**Comment by Pilchie** [comment]
Tag @heejaechang

**Comment by heejaechang** [comment]
I will take a look.


-          heejae

**Comment by davkean** [comment]
By looking at the code, I'm convinced that this doesn't impact negatively: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.StateManager.ProjectStates.cs,167.

**Comment by heejaechang** [comment]
fixed https://github.com/dotnet/roslyn/pull/9683

**Comment by heejaechang** [comment]
@TyOverby can you verify?

**Comment by TyOverby** [comment]
@heejaechang I haven't seen it fail since then, but I'm no longer watching the builds.

**Comment by davkean** [comment]
Have not seen it fail either. Looks like we got this one! Thanks!
