### ISSUE TITLE
Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.PersistentStorageTests.PersistentService_Document_SimultaneousReads failed in signed build

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9475]
This failed in a signed build for stabilization:
```
System.IO.IOException : The directory is not empty.\r\n
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.PersistentStorageTests.Dispose() in F:\Builds\5530\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\VisualStudio\CSharp\Test\PersistentStorage\PersistentStorageTests.cs:line 49
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by Pilchie** [comment]
Can you take a look?  Maybe talk to @mattwar and/or @heejaechang about these tests.

**Comment by balajikris** [comment]
Notes:

This has nothing to do with the PersistenceService itself I guess. Just an IOError when deleting directories during clean up. 
Some reasons as to when this can happen: http://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true

**Comment by davkean** [comment]
Yes, but that could be a product bug - ie we could be holding onto a file too long.

**Comment by heejaechang** [comment]
@davkean in production, we don't delete those file in .vs folder. we do switch when IVsWorkingFolder event happens, we let handle go and switch and delete old one. but if there is someone who hold onto handle, we will handle that case gracefully.

**Comment by DustinCampbell** [comment]
Moving to 1.3. It doesn't seem like this is actually a product issue based on @heejaechang's comment.

**Comment by balajikris** [comment]
This hasn't repro -ed in a long time now. Please reactivate if you see it shows up again.
