### ISSUE TITLE
Microsoft.CodeAnalysis.CompilerServer.UnitTests/CompilerServerUnitTests/MultipleSimultaneousCompiles/

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9630]
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit64/927/testReport/junit/Microsoft.CodeAnalysis.CompilerServer.UnitTests/CompilerServerUnitTests/MultipleSimultaneousCompiles/

```
MESSAGE:
System.ArgumentException : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
+++++++++++++++++++
STACK TRACE:
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
at System.Collections.Generic.List`1.set_Capacity(Int32 value) at System.Collections.Generic.List`1.EnsureCapacity(Int32 min) 
at System.Collections.Generic.List`1.Add(T item) 
at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<RunCompilationAsync>d__58.MoveNext() in d:\j\workspace\roslyn_master---01224af0\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs:line 964 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.<MultipleSimultaneousCompiles>d__59.MoveNext() in d:\j\workspace\roslyn_master---01224af0\src\Compilers\Server\VBCSCompilerTests\CompilerServerTests.cs:line 987 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task
```

**Comment by jaredpar** [comment]
Took a quick look and I understand what is going on here.  Will have a fix out tonight or early AM.
