### ISSUE TITLE
AVE when running multiple dotnet builds in parallel

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#9632]
**Version Used**: 
1.2.60202 that comes with CLI version 1.0.0.001540

**Steps to Reproduce**:

Launch dotnet build on multiple projects in a `Parallel.For`

**Actual Behavior**:

The build failed with the following stack trace:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.CodeAnalysis.ArrayBuilder`1.ToDictionary[K](Func`2 keySelector, IEqualityComparer`1 comparer)
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GroupByName(ArrayBuilder`1 symbols)
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.EnsureNestedTypesAreLoaded()
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.LoadMembers()
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetMembers(String name)
at Microsoft.CodeAnalysis.CSharp.Symbols.OverriddenOrHiddenMembersHelpers.FindOverriddenOrHiddenMembersInType(Symbol member, Boolean memberIsFromSomeCompilation, NamedTypeSymbol memberContainingType, NamedTypeSymbol currType, Symbol& currTypeBestMatch, Boolean& currTypeHasSameKindNonMatch, ArrayBuilder`1& hiddenBuilder)
at Microsoft.CodeAnalysis.CSharp.Symbols.OverriddenOrHiddenMembersHelpers.MakeOverriddenOrHiddenMembersWorker(Symbol member)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbol.get_OverriddenOrHiddenMembers()
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckMembersAgainstBaseType(DiagnosticBag diagnostics, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetSynthesizedExplicitImplementations(CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
```

Remainder of the stack trace: https://gist.github.com/pranavkm/0c65e901154100fbcf60

**Comment by pranavkm** [comment]
Log from event viewer if that helps:

```
Faulting application name: csc.exe, version: 0.0.0.0, time stamp: 0x56df5b9a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x1c7c
Faulting application start time: 0x01d17a5f0482bdc0
Faulting application path: C:\Users\lab\AppData\Local\Microsoft\dotnet\cli\bin\csc.exe
Faulting module path: unknown
Report Id: 43508a89-e652-11e5-80d7-000d3a321d01
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by muratg** [comment]
:eyes:

**Comment by gkhanna79** [comment]
@pranavkm Can you please share the exact steps for repro?

**Comment by jaredpar** [comment]
This is a crash in native code that disappears when crossgen is no longer used.  We should just use the CLI bug to track this.  Having two bugs across repros confuses the issue. 

https://github.com/dotnet/cli/issues/1785

**Comment by Eilon** [comment]
@gkhanna79 right, when the NI files are deleted, the problem goes away.
