### ISSUE TITLE
Git2TfsMirror is running out of windows handles

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9680]
```
   LibGit2Sharp.LibGit2SharpException: Could not open 'C:/Workspaces/Roslyn-Wo
ing/Stabilization/.git/config': Too many open files
  at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
  at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
  at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options)
  at GitToTfsMirror.Program.LoadBranchesToSync() in C:\Workspaces\DotNet\Rosly
Closed\Tools\GitToTfsMirror\GitToTfsMirror\Program.cs:line 211
  at GitToTfsMirror.Program.Main(String[] args) in C:\Workspaces\DotNet\Roslyn
losed\Tools\GitToTfsMirror\GitToTfsMirror\Program.cs:line 250

```

This is happening daily.

**Comment by davkean** [comment]
See dump: [internalshare]\public\davkean\GitToTfsMirror.dmp
