### ISSUE TITLE
Crash in CLSCompliance checking

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9734]
Repro code: 

``` vb
<Assembly: CLSCompliant(True)>

Public Class C
    Public Function CreateConversionDelegate(Of TFrom, TTo)(conversion As Func(Of TFrom, TTo)) As Func(Of TFrom, TTo)
        Return Nothing
    End Function
End Class

Module Conversion

End Module
```

Repro Steps: Place the caret before `conversion` and type `something As`.  The result is a crash with the following stack trace:

``` txt
System.InvalidOperationException: Unexpected value 'Module' of type 'Microsoft.CodeAnalysis.TypeKind'
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.ReportNonCompliantTypeArguments(TypeSymbol type, NamedTypeSymbol context, Symbol diagnosticSymbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.CheckParameterCompliance(ImmutableArray`1 parameters, NamedTypeSymbol context)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitMethod(MethodSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol.Accept(VisualBasicSymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitNamedType(NamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.Accept(VisualBasicSymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceSymbol.Accept(VisualBasicSymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceSymbol.Accept(VisualBasicSymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamespaceSymbol.Accept(VisualBasicSymbolVisitor visitor)
  at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitModule(ModuleSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.VisitAssembly(AssemblySymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.AssemblySymbol.Accept(VisualBasicSymbolVisitor visitor)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSymbolVisitor.Visit(Symbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.ClsComplianceChecker.CheckCompliance(VisualBasicCompilation compilation, DiagnosticBag diagnostics, CancellationToken cancellationToken, SyntaxTree filterTree, Nullable`1 filterSpanWithinTree)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetClsComplianceDiagnostics(CancellationToken cancellationToken, SyntaxTree filterTree, Nullable`1 filterSpanWithinTree)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyImage.Create(ITemporaryStorageService service, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MetadataOnlyReference.GetOrBuildReference(Solution solution, ProjectReference projectReference, Compilation finalCompilation, VersionStamp version, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<GetMetadataOnlyImageReferenceAsync>d__31.MoveNext()
```

**Comment by jcouv** [comment]
@jaredpar, I just tried this on update 2 and it did not repro. Instead of a crash, I get squiggles under `As` with `End of statement expected`.

Do you want a second verification before closing the bug?

**Comment by jaredpar** [comment]
@jcouv weird, I tried on update 2 and got the crash.  I'll drop by and see if there is a subtle difference in how we are repo'ing it.

**Comment by jaredpar** [comment]
Resolving as a dupe of #9719
