### ISSUE TITLE
RunTests.exe causes IOException when outputting html

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9787]
xunit appears to have a race on the `HTML.xslt` file that causes tests to fail when producing html output

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Microsoft.CodeAnalysis.Scripting.UnitTests
  Discovered:  Microsoft.CodeAnalysis.Scripting.UnitTests
  Starting:    Microsoft.CodeAnalysis.Scripting.UnitTests
    Microsoft.CodeAnalysis.UnitTests.Interactive.RuntimeMetadataReferenceResolverTests.Resolve
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.AddReferences
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.AddNamespaces
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.WithReferences
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.WithReferences_Errors
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.AddReferences_Errors
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.WithImports_Errors
    Microsoft.CodeAnalysis.Scripting.Test.ScriptOptionsTests.AddImports_Errors
    Microsoft.CodeAnalysis.Scripting.Test.NuGetPackageResolverTests.ParsePackageNameAndVersion
  Finished:    Microsoft.CodeAnalysis.Scripting.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.CodeAnalysis.Scripting.UnitTests  Total: 9, Errors: 0, Failed: 0, Skipped: 0, Time: 0.977s
System.IO.IOException: The process cannot access the file 'C:\Users\jmarolf\.nuget\packages\xunit.runner.console\2.1.0\tools\HTML.xslt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Xunit.ConsoleClient.TransformFactory.Handler_XslTransform(String xslPath, XElement xml, String outputFileName)
   at Xunit.ConsoleClient.TransformFactory.<>c__DisplayClass2_1.<.ctor>b__1(XElement xml, String outputFileName)
   at Xunit.ConsoleClient.TransformFactory.<>c__DisplayClass5_0.<GetXmlTransformers>b__1(XElement xml)
   at Xunit.ConsoleClient.Program.<>c__DisplayClass10_0.<RunProject>b__5(Action`1 transformer)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Xunit.ConsoleClient.Program.RunProject(XunitProject project, Boolean serialize, Nullable`1 parallelizeAssemblies, Nullable`1 parallelizeTestCollections, Nullable`1 maxThreadCount, Boolean diagnosticMessages, Boolean noColor, Boolean noAppDomain, Boolean failSkips)
   at Xunit.ConsoleClient.Program.Main(String[] args)
```

**Comment by davkean** [comment]
Not sure understand. Is this representing the issue that the file was locked or the fact that the test run failed because of file was locked. If its the latter, it seems somewhat the correct behavior.

**Comment by davkean** [comment]
tag @jaredpar Looks like this was broken in the unification.

**Comment by jaredpar** [comment]
That XSLT file is such a pain.  I've already had to change xunit sources to not take an exclusive read lock on the file.  Looks like we're doing it implicitly as a part of a copy command we run now.  Blarg.

**Comment by jasonmalinowski** [comment]
@jaredpar: what's the status of this?

**Comment by jaredpar** [comment]
@jasonmalinowski I haven't seen any recent instance of this and it fell off my radar.  New problem show up?

**Comment by jasonmalinowski** [comment]
No, it was on the infrastructure backlog assigned to you. So just checking in.

**Comment by jasonmalinowski** [comment]
@agocke, was this why you upgraded to the newer xUnit version as a part of the MicroBuild changes?

**Comment by agocke** [comment]
@jasonmalinowski Sorry, missed this notification. Yes, that's why.

**Comment by jasonmalinowski** [comment]
@agocke, now clear to close this since we're on microbuild v2 now?

**Comment by agocke** [comment]
@jasonmalinowski :+1:

**Comment by davkean** [comment]
What's relevance of this bug to MicroBuild/Xunit versions?

**Comment by jasonmalinowski** [comment]
This was a bug in xunit, we ended up taking a newer version as a part of c0fc9e24763c29fa972dfdd4c0fcc7b58024711a which came along with the microbuild v2 branch.
