### ISSUE TITLE
BasicGenerateTypeDialog.xml failure

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9790]
PR: [#693](https://github.com/dotnet/roslyn-internal/pull/693) *Merge stabilization into master* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/861/

**2 Test Failures:**
BasicGenerateTypeDialog.Generate Type Dialog VB-to-C#
BasicGenerateTypeDialog.Generate Type Dialog Check_Folders_Populating

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicGenerateTypeDialog.xml

**Comment by jmarolf** [comment]
**BasicGenerateTypeDialog.Generate Type Dialog VB-to-C#**
![image](https://cloud.githubusercontent.com/assets/9797472/13812535/05942a66-eb3a-11e5-93ee-3da9aa8cae5d.png)

```
    Executing action [3/16/2016 7:20:47 AM] VerifyText
Note: ActiveTextView has lost Keyboard focus.
--------------------------------
Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifyTextAction]: Expected 'namespace CSProj
{
    public struct A
    {
    }
}' 
Actual 'Class C
    Sub Method()
        Dim _A As A
    End Sub
End Class
'
   at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message) in f:\dd\src\Omni\Tao\Tao.Utilities\Extensions.cs:line 457
   at Roslyn.Hosting.Test.VerifyTextAction.ExecuteOnUIThread() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\VerifyTextAction.cs:line 16
   at Roslyn.Hosting.Test.EditorAction.<Execute>b__0_0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 21
   at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
   at Roslyn.Hosting.Test.EditorAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 13
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
================================
```

**BasicGenerateTypeDialog.Generate Type Dialog Check_Folders_Populating**
![image](https://cloud.githubusercontent.com/assets/9797472/13812625/6ebc5cca-eb3a-11e5-8e26-ecef607a16f7.png)

```
Stacktrace

MESSAGE:
Exceptions found in the exception log
+++++++++++++++++++
STACK TRACE:
at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16 
at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178 
at Roslyn.Hosting.Test.EditorTestAppAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 147 
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139 
at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

**Comment by jmarolf** [comment]
```
Test: BasicGenerateTypeDialog started: 3/16/2016 7:20:35 AM
    Executing action [3/16/2016 7:20:35 AM] StartTarget
 Scenario: Generate Type Dialog VB-to-C#
    Executing action [3/16/2016 7:20:35 AM] AddProject
    Executing action [3/16/2016 7:20:37 AM] AddProject
    Executing action [3/16/2016 7:20:37 AM] AddItem
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:20:37 AM] OpenFile
    Executing action [3/16/2016 7:20:37 AM] SetEditorText
    Executing action [3/16/2016 7:20:37 AM] PlaceCursor
    Executing action [3/16/2016 7:20:38 AM] GenerateTypeDialog
Note: ActiveTextView has lost Keyboard focus.
Actual ISuggestedAction count: 13
Actual ISuggestedAction: Generate class 'A' in new file
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate nested class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate new type...
Actual ISuggestedAction: Suppress BC42024
Actual ISuggestedAction: in Source
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Document
Actual ISuggestedAction: Project
Actual ISuggestedAction: Solution
Note: ActiveTextView has lost Keyboard focus.
ComboBox 'AccessList' value set to 'Public'
ComboBox 'KindList' value set to 'Structure'
ComboBox 'ProjectList' value set to 'CSProj'
Radio button 'CreateNewFileRadioButton' selected
TextBox value set to GenerateTypeTest
Button OkButton clicked
    Executing action [3/16/2016 7:20:47 AM] OpenFile
    Executing action [3/16/2016 7:20:47 AM] VerifyText
Note: ActiveTextView has lost Keyboard focus.
--------------------------------
Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifyTextAction]: Expected 'namespace CSProj
{
    public struct A
    {
    }
}' 
Actual 'Class C
    Sub Method()
        Dim _A As A
    End Sub
End Class
'
   at Tao.Utilities.Extensions.ThrowUnexpectedResultException[TAction](TAction action, String message) in f:\dd\src\Omni\Tao\Tao.Utilities\Extensions.cs:line 457
   at Roslyn.Hosting.Test.VerifyTextAction.ExecuteOnUIThread() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\VerifyTextAction.cs:line 16
   at Roslyn.Hosting.Test.EditorAction.<Execute>b__0_0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 21
   at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass25_0.<ExecuteOnUIThread>b__0() in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Hosting.Test.EditorTestAppAction.ExecuteOnUIThread(Action a) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 178
   at Roslyn.Hosting.Test.EditorAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---cd4c5d61\Closed\Hosting\Test\Actions\EditorTestApp\EditorAction.cs:line 13
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
================================
    Executing action [3/16/2016 7:21:18 AM] CloseSolution
 Scenario: Generate Type Dialog VB-SameProject
    Executing action [3/16/2016 7:21:18 AM] AddProject
    Executing action [3/16/2016 7:21:18 AM] AddProject
    Executing action [3/16/2016 7:21:18 AM] AddItem
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:21:18 AM] OpenFile
    Executing action [3/16/2016 7:21:18 AM] SetEditorText
    Executing action [3/16/2016 7:21:18 AM] PlaceCursor
    Executing action [3/16/2016 7:21:19 AM] GenerateTypeDialog
Note: ActiveTextView has lost Keyboard focus.
Actual ISuggestedAction count: 13
Actual ISuggestedAction: Generate class 'A' in new file
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate nested class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate new type...
Actual ISuggestedAction: Suppress BC42024
Actual ISuggestedAction: in Source
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Document
Actual ISuggestedAction: Project
Actual ISuggestedAction: Solution
Note: ActiveTextView has lost Keyboard focus.
ComboBox 'AccessList' value set to 'Public'
ComboBox 'KindList' value set to 'Structure'
Radio button 'CreateNewFileRadioButton' selected
TextBox value set to GenerateTypeTest2
Button OkButton clicked
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:21:26 AM] OpenFile
    Executing action [3/16/2016 7:21:26 AM] VerifyText
    Executing action [3/16/2016 7:21:26 AM] OpenFile
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:21:26 AM] VerifyText
    Executing action [3/16/2016 7:21:26 AM] CloseSolution
Note: ActiveTextView has lost Keyboard focus.
 Scenario: Generate Type Dialog Check_Folders_Populating
    Executing action [3/16/2016 7:21:26 AM] AddProject
    Executing action [3/16/2016 7:21:26 AM] AddProject
    Executing action [3/16/2016 7:21:26 AM] AddNewDocument
    Executing action [3/16/2016 7:21:26 AM] OpenFile
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:21:27 AM] SetEditorText
    Executing action [3/16/2016 7:21:27 AM] PlaceCursor
    Executing action [3/16/2016 7:21:27 AM] GenerateTypeDialog
Note: ActiveTextView has lost Keyboard focus.
Actual ISuggestedAction count: 13
Actual ISuggestedAction: Generate class 'A' in new file
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate nested class 'A'
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Generate new type...
Actual ISuggestedAction: Suppress BC42024
Actual ISuggestedAction: in Source
Actual ISuggestedAction: Preview changes
Actual ISuggestedAction: Document
Actual ISuggestedAction: Project
Actual ISuggestedAction: Solution
Note: ActiveTextView has lost Keyboard focus.
Radio button 'CreateNewFileRadioButton' selected
ComboBox 'CreateNewFileComboBox' checked for '\folder1\' value present
ComboBox 'CreateNewFileComboBox' checked for '\folder1\folder2\' value present
Button CancelButton clicked
    Executing action [3/16/2016 7:21:35 AM] CloseSolution
Note: ActiveTextView has lost Keyboard focus.
    Executing action [3/16/2016 7:21:35 AM] CloseTarget
Test finished: 3/16/2016 7:21:35 AM
```
