### ISSUE TITLE
[Test Failure] VSOptionPagesUI.xml (VSOptionPagesUI.Show the CSharp IntelliSense option page UI) failed

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9804]
PR: [#705](https://github.com/dotnet/roslyn-internal/pull/705) *Merge future-stabilization into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/237/

these test failures are first time I saw.

**Comment by jmarolf** [comment]
```
VSOptionPagesUI.Show the CSharp IntelliSense option page UI (from (empty))

MESSAGE:
Exception has been thrown by the target of an invocation.
+++++++++++++++++++
STACK TRACE:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Tao.Engine.Utilities.MethodCaller.CallMethod[T](T objectWithMethods, XElement xmlMethod) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 85 at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, IEnumerable`1 xmlList) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 37 at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, XElement xml) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 30 at Tao.Engine.DebuggableActionExecutor.CallMethods(TaoEngine engine, TaoAction action) in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 183 at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 142
```

```
VSOptionPagesUI.Verified the modification through DTE (from (empty))

MESSAGE:
Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))
+++++++++++++++++++
STACK TRACE:
at EnvDTE._DTE.get_Properties(String Category, String Page) at Roslyn.VSHosting.Test.VerifyToolsOptionAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---3b4b7ba3\Closed\Hosting\Test\Actions\VisualStudio\VerifyToolsOptionAction.cs:line 17
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139 at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

```
VSOptionPagesUI.Change the option value back through DTE then verify in UI (from (empty))

MESSAGE:
Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))
+++++++++++++++++++
STACK TRACE:
at EnvDTE._DTE.get_Properties(String Category, String Page) at Roslyn.VSHosting.Test.SetToolsOptionAction.Execute(TaoEngine engine) in d:\j\workspace\roslyn-intern---3b4b7ba3\Closed\Hosting\Test\Actions\VisualStudio\SetToolsOptionAction.cs:line 16 
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139 at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

```
VSOptionPagesUI.Change the option value back through DTE then verify in UI (from (empty))

MESSAGE:
Exception has been thrown by the target of an invocation.
+++++++++++++++++++
STACK TRACE:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at Tao.Engine.Utilities.MethodCaller.CallMethod[T](T objectWithMethods, XElement xmlMethod) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 85
at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, IEnumerable`1 xmlList) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 37
at Tao.Engine.Utilities.MethodCaller.CallMethods[T](T objectWithMethods, XElement xml) in f:\dd\src\Omni\Tao\Tao.Engine\Utilities\MethodCaller.cs:line 30
at Tao.Engine.DebuggableActionExecutor.CallMethods(TaoEngine engine, TaoAction action) in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 183
at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 142
```

**Comment by jmarolf** [comment]
dci-win-rbld-5 appears to have problems, not a test issue

**Comment by gafter** [comment]
dci-win-rbld-5 is now fixed. It is possible the current run may fail.
